### ISSUE TITLE
Unknown Issue with e107_class.php

### ISSUE THREAD

**Issue by halfwolf102** [e107inc/e107#1000]
I wish I could give more details about this issue, but there's something wrong with e107_class.php in /e107_handlers and when I upload the current one to my site, I get a blank screen on all pages. I replaced it with one I have from a backup and it works fine now, but I figured I should mention this so that it could be looked into.

**Comment by CaMer0n** [comment]
In your PHP error_log you should find the reason/cause. Also you could try enabling debugging and see if that throws something to the screen/browser. Which version of PHP are you using?

**Comment by halfwolf102** [comment]
I cannot find the PHP error_log, any idea of where it would be or how to find it? The debugging addon for Firefox also came up blank.
Php version: 5.2.17

**Comment by CaMer0n** [comment]
That could be it, minimum version for v2.x is PHP v5.3

**Comment by CaMer0n** [comment]
Closing. Please speak to your provider regarding changing to a higher version of PHP.
