### ISSUE TITLE
Feature Request: Allow BBCode and/or html in Links

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1004]
In Admin Area - Links - allow BBCode and/or html for links - I want to add some custom font at the front of the link name like how Members has that Person font/icon.

If no bbcode or html then maybe an option when creating/editing the links to pick a font/icon from the bootstrap themes?

Also BBCode to make some bold etc - http://www.defiantz.org  (look at the bottom (Footer Links) - Created Two links that go no where - MEMBERS and INFORMATION (Have them in caps cause lower case you cant see them) and added links as sublinks.

**Comment by CaMer0n** [comment]
Are you referring to Admin Area -> Site links? Each link can have it's own Glyph/Icon.

**Comment by LaocheXe** [comment]
Yes

**Comment by CaMer0n** [comment]
I don't understand. This option already exists.

**Comment by LaocheXe** [comment]
Ah now I see, then never mind on this one.
