### ISSUE TITLE
Question: admin-config list page custom "options"

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1005]
Wasn't quite sure where to post this. Am developing a plugin and was wondering if there was a way to add another "option" button within admin-config. I see that but setting the readParms sort=1 shows the sort button, but is there a way to add a custom button that links to one of the customPages defined

The line of code I'm referring to is this...

'options' => array('title'=> LAN_OPTIONS, 'type' => null,	 'forced'=>TRUE, 'width' => '10%', 'thclass' => 'center last', 'class' => 'center', 'readParms'=>'sort=1')

**Comment by CaMer0n** [comment]
Yes, take a look at e107_admin/cron.php for the use of a custom "options" method.

**Comment by pricey1981** [comment]
nice one, just what I'm after.

**Comment by CaMer0n** [comment]
:+1:
