### ISSUE TITLE
Bad redirect after login

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1006]
I use SEF URLs, and after I login, the destination URL is bad:

http://mydomain.com/e107v2/e_SELF?e_QUERY

**Comment by CaMer0n** [comment]
Are you able to reproduce this with a fresh install of e107?

**Comment by lonalore** [comment]
No, it's an old install, but I removed and updated e107 files to the latest github master a week ago.

**Comment by CaMer0n** [comment]
Could it be related to your 'frontpage' settings?

**Comment by lonalore** [comment]
I think it's not. I sent you an admin account for my demo website, you can check my frontpage settings, and you can reproduce this "bug" if you visit this page: http://demo.lonalore.hu/e107v2/qna/categories
... and make a login. After login the destination URL is bad.

**Comment by CaMer0n** [comment]
@lonalore This *should* fix it. If not, please re-open.

**Comment by lonalore** [comment]
Thank you @CaMer0n! Your commit fixed it, and it also fixed issue #996. :)
