### ISSUE TITLE
Warning This theme would like to make the following changes to your database:

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1011]
Hi All, 
Playing with latest release 2 files downloaded from Git. On changing theme I get the warning 

Warning
This theme would like to make the following changes to your database:

It appears to create / overwrite existing content. 
Thanks
MikeyGMT

===========
Warning
This theme would like to make the following changes to your database:
Replace/Overwrite 1 record(s) in your generic table.
Replace/Overwrite 8 record(s) in your menus table.
Replace/Overwrite 6 record(s) in your page table.
Replace/Overwrite 2 record(s) in your page_chapters table.

**Comment by LaocheXe** [comment]
It should ask you if you want to do this or not, the content is ment to fill the site up with some to show the site off.

**Comment by MikeyGMT** [comment]
It does indeed ask. But could confuse a new user and wipe their own content.

**Comment by CaMer0n** [comment]
Any ideas how to make it less confusing? No damage done if they refuse it. And if they are a new user, I guess we can assume there's little content in the database to actually overwrite?

**Comment by MikeyGMT** [comment]
Hi Cam, 
Maybe consider, leave out the install files in "official release" packages, that's all

On initially seeing the message, I assumed it was some new feature which was needed to actually finish the Theme setup, so hit ok. I did not think about much, but I did lose some of my initial setup, welcome message - I think. It was only when I installed on a new test site and put two and two together. 

No biggy. 
Mikey

**Comment by CaMer0n** [comment]
Thanks Mikey. Not really an option though, as the install.xml file is used to populate the default bootstrap theme. Maybe it just needs a better description to say that it is optional.

**Comment by Moc** [comment]
What about something like this:

==========================

This theme comes with pre-installed example content, such as pages and menus, that can be used on your website.  
Be aware that this content will **overwrite** the current content on your website!

Would you like to replace your current content with the default example content provided by the theme?

**Comment by CaMer0n** [comment]
Great @Moc! Would you mind committing that?

**Comment by Moc** [comment]
Will do

**Comment by Moc** [comment]
@MikeyGMT @LaocheXe What do you think of this? See image below: 

![image](https://cloud.githubusercontent.com/assets/577978/8295136/f46f6dc4-1941-11e5-8dcb-f03e8a540a7e.png)

**Comment by MikeyGMT** [comment]
That is much clearer. Thanks folks
