### ISSUE TITLE
Forum upgrade shown even after updation finished

### ISSUE THREAD

**Issue by ajaybhargav** [e107inc/e107#1012]
I have successfully updated the forum from 1.x to 2.0 but e107 update still showing forum to be updated and if I run update again, it gets stuck at forum table not created (as tables are already created by previous update process).
![screenshot1](https://cloud.githubusercontent.com/assets/927133/7720696/ead7eb2e-feed-11e4-9de9-a2dae53e58aa.png)

BTW I am using latest git version.

**Comment by Moc** [comment]
@CaMer0n see #727

**Comment by CaMer0n** [comment]
@ajaybhargav Are you able to give me FTP and Admin access to your site (via Private-message at http://e107.org/developers/) ?  This is an old problem which I have been unable to fix because I cannot reproduce it. Debugging it on a site which DOES have this problem would be extremely helpful.

**Comment by willem010** [comment]
try removing all the files from the forum folder, and reupload fresh files from git
i had a similar issue on tinymce, caused by an older e_meta file which came from an older git version.

**Comment by tgtje** [comment]
Just finished 3 test updates from v1 TO v2 (in Xampp).
All 3 have issues on step 3 (either an empty installed but not used forum or 2 fully equipped)
It can (will not create) the extended fields.
Error
Creating extended user field user_plugin_forum_posts
Creating extended user field user_plugin_forum_viewed
Creation of extended field(s) failed. You can not continue until these are create successfully!

I overcame ( had to investigate) by backing up all, then DE-install the forum plugin but ONLY gave command to delete the extended fields (all others is no).
So forum is deinstalled while tables keep prseent in dbase. Next i installed the forum plugin (it uses the stored tables) and e107 reports > update  > finish that > forum runs fine..(upgrade complete)

**Comment by ajaybhargav** [comment]
I manually created those two extended fields to continue the setup.

did you also try to update having public files in place?

**Comment by tgtje** [comment]
@ajaybhargav j The upgrade is used on a v1 website which uses nearly everything (except pm).
Data : db 6.2 Mb sql base
File size on server > about 920Mb 
Files used > total (system and downloads etc..) 11.300.

**Comment by upperking** [comment]
Error
Adding Table: forum
Adding Table: forum_thread
Adding Table: forum_post
Adding Table: forum_track

Success
Settings successfully saved.
Adding Link: Forum with url [{e_PLUGIN}forum/forum.php] and perm everyone
Adding Userclass: forum_moderator
Adding Extended Field: plugin_forum_viewed ...
Adding Extended Field: plugin_forum_posts ...
Installation Complete.

it will not get past the point of creatting new tables

**Comment by tgtje** [comment]
@upperking  more info is needed like, is it an update. date of files etc..The more the better
