### ISSUE TITLE
Issue: Forums Links Broken

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1015]
Updated the CMS code today and now the forums links are broken.

Example: Forums main page (siteurl.org/e107_plugins/forums/forum.php) Works
Also: (siteurl.org/forum#general-discussions)

Going to General Chat Section (site.url.org/forum/general-chat) Love that e107_plugins is hidded - also Works

Going into the topic that is in General Chat Section (siteurl.org/forum/general-chat/10-welcome-to-the-forums/) Don't Work - redirects me back to the mail forum page.

Can make post, but can't read such post.

http://defiantz.org/e107_plugins/forum/forum.php
http://defiantz.org/forum

Them work

**Comment by CaMer0n** [comment]
Please check that all your forums have sef-urls assigned.

**Comment by LaocheXe** [comment]
Went in and made sure every forum had a sef-urls assigned - same issue, cant go in and view the post

**Comment by CaMer0n** [comment]
Sounds like an userclass (read-access) issue, rather than a URL issue.

**Comment by LaocheXe** [comment]
Wouldn't it display an error if it was userclass read-access issue? General Chat is open to every one to read it (View Pers set to Everyone (public)) but Post and create thread limit to members. I am using an admin account.

However before updating the code a few days ago, I notice a few forum area that had no post in them where missing the Create a new topic button, updated the code fix it (they are displaying again) so maybe you are right it might be userclass read-access issue

**Comment by LaocheXe** [comment]
When I go to the General Chat area on my forums (with the FireFox e107 Debugger tool enabled) I get this:

e_URL in forum with key: forum matched ^forum/(.*)$ and included: e107_plugins/forum/forum_viewforum.php with $_GET: 
 Array
(
    [sef] => general-chat
)

But that's it - so must be userclass issue

**Comment by LaocheXe** [comment]
Just did some more testing and notice something odd.

If I go to a thread that was created a few months ago, I can access it (read it), But if I post something today or a few days ago, I get sent back to the forums front page. 

(Should not be able to view this thread but posting link to show the url) http://defiantz.org/e107_plugins/forum/forum_viewtopic.php?id=3

If I switch the id to say 10 (which is the "Welcome to the Forums" post in General Chat (That every one can see) - http://defiantz.org/e107_plugins/forum/forum_viewtopic.php?id=10
You can view the topic.

So this link doesn't work: http://defiantz.org/forum/general-chat/10-welcome-to-the-forums/
but this one does work: http://defiantz.org/e107_plugins/forum/forum_viewtopic.php?id=10

So I don't know if it is a user class read-access issue or not.

**Comment by LaocheXe** [comment]
I also just notice that when I go to a new post I get the main news page so I wonder if this is a SEF URL issue

http://defiantz.org/news/game-revies/battlefield-hardline-multiplayer  
That is the Link I went to and ended up here seeing what is on the news.php page
http://defiantz.org/news.php

is this my .htaccess not being updated or what, I have no idea.

**Comment by CaMer0n** [comment]
I believe I fixed this issue yesterday evening. News SEF URLs broke with a previous commit.

**Comment by LaocheXe** [comment]
Seems all to be working now

**Comment by pierre0042** [comment]
I have the same problem

**Comment by pierre0042** [comment]
For me commenting all lines in the .htaccess file solved the problem.
