### ISSUE TITLE
Missing folder or communication error

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1022]
Newest (datestamp +/- 19 hours) FRESH install >

Install runs fine (testing on 'normal' dbase and on Mariadb)
Error displayed when logging in as admin : go to login page  > admin area should display

(blank page with this notification only  #halt)

File is not writeable, and could not correct permissions: ../e107_media/28dbd6548e/temp/800x30_button.png  

This happens on Opera and Firefox, IE 11 (shows 500 error) Chrome stutters but seems to willing to go .. 

A page refresh seems to trigger the 'workflow' and admin area appears..

Because of the fact this this happened ( i reinstalled every time new ( about 8 installs)  on empty dbases etc.. with new uploaded files ) and not really seems influenced by browser communication i like to report this (mediafoldername changes per install)

**Comment by CaMer0n** [comment]
@tgtje Thanks. I know what is causing that. The default folders need to be created earlier on.

**Comment by CaMer0n** [comment]
@tgtje Would you mind updating, then deleting e107_media/xxxxx/temp and logging into admin?

**Comment by tgtje** [comment]
timeline version yesterday (reinstalled again with same version 
#identical behaviour) :
install > login >error display appears > refresh > pass through (no temp 
folder yet)
run update (v1 to v2 > normal) temp folder appears directly here after.

timeline version today (newest files) (full timeline behaviour)
install  (info mediafolder without temp appears when filling in website 
preferences #step 6) >
completion install > still no temp (ftp refresh> login > admin area (no 
error message) > update available (ftp refresh) > running update > temp 
folder appears (ftp refresh)


as asked :
version Yesterday overwritten all (all files) deleted the present 
mediafolder > login > admin area
! notice > new mediafolder including temp folder appears ( issue is not 
present).

**Comment by CaMer0n** [comment]
Thank you, that's the normal behavior.
