### ISSUE TITLE
Future Request: Downloads ScreenShot

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1027]
So currently when you go to the downloads and select a download and see a link for a screenshot - maybe make it into a small image of the screenshot that was uploaded and when clicked it brings it out in a pop out window instead of going to a page to display it in:

http://defiantz.org/download/7/defiantzstrap-lite
http://defiantz.org/e107_plugins/download/request.php?download.7
^^^^^ Thats what it looks like now ^^^^^

**Comment by tgtje** [comment]
Something like this ? http://tgtje.eu/download.php?view.29 Mind = v 1 adjusted download template and shortcode (by 4xa.de )

**Comment by LaocheXe** [comment]
Yes - Like that, thanks for the reply tgtje!

**Comment by tgtje** [comment]
@LaocheXe 

Just played around with some code (by copy and paste). Seems to work and i share for experimenting > it's is plain, needs nothing else and still it keeps working (original).
No need for thumb > is thumb from original 
No lightbox however > static (needs further coding), i am already happy it can be used.
If you like to test or use (no guarantee , it works for me, but for you ? I do hope coding is correct).
backup download_shortcodes php and change line 570 from

return "<a href='".e_PLUGIN_ABS."download/request.php?download.".$this->var['download_id']."'>".LAN_dl_40."</a>";

 to : 

      	return "<a href='".e_PLUGIN_ABS."download/request.php?download.".$this->var['download_id']."'>".LAN_dl_40." <img class='download-image dl_image img-responsive' src='".$tp->thumbUrl($this->var['download_image'])."' alt='*'  /></a>";

example : 
![wow](https://cloud.githubusercontent.com/assets/1811857/10312336/1f508f62-6c4b-11e5-8b27-9f89b8854338.jpg)
