### ISSUE TITLE
Reporting forum posts fails to report and redirects to blank screen

### ISSUE THREAD

**Issue by martasalek** [e107inc/e107#1028]
Hi guys,

The "Report" option from the forum post Options dropdown redirects the user to a blank screen and appears to fail to report the post.

Our system is using files from the 36fb58192a commit.

Thanks!

Marta

**Comment by CaMer0n** [comment]
Thanks for posting. Took a look at the code. This whole function needs to be moved and rewritten to some degree. In the meantime, you may wish to disable reporting in the forum preferences. I'll try to look at it tomorrow.

**Comment by martasalek** [comment]
Thanks, Cameron. Much appreciated.

**Comment by martasalek** [comment]
Hi Cameron,

Apologies for the delay in getting back to you. Thanks, appears that this is now working fine.

Cheers

Marta
