### ISSUE TITLE
Feature Suggestion : When verifying language files, add check to see if EN value = FOREIGN value

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1029]
Hi e107 Devs, 

RE: using e107_admin/language.php?tools function / Verify

Please can I suggest adding a very useful little check to see if the English Value is the same as the foreign value? 

For example check 
EN: Username 
CY: Username 

If they are the same then please fire a warning, and list alongside : 
[x] Display only errors during verification

Many thanks 

Mikey

**Comment by CaMer0n** [comment]
@MikeyGMT  Please let me know if that commit makes things easier.

**Comment by MikeyGMT** [comment]
@CaMer0n Absolutely Perfect - Five Star Service!

Thank you I'll test and look for any issues over the next few days.
