### ISSUE TITLE
lan_installer.php - LANINS_062 out of date

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1030]
LANINS_062 	[b]Welcome to your new website![/b]

e107 has installed successfully and is now ready to accept content.<br />

Your administration section is [link=e107_admin/admin.php]located here[/link], click to go there now. 

You will have to login using the name and password you entered during the installation process. [b]Support[/b] e107 Homepage: [link=http://e107.org]http://e107.org[/link], you will find the FAQ and documentation here. 

Forums: [link=http://e107.org/e107_plugins/forum/forum.php]http://e107.org/e107_plugins/forum/forum.php[/link] 

Plugin Developer Community: 
[link=http://www.e107coders.org]http://e107coders.org[/link] 

[b]Downloads[/b] 
Plugins: [link=http://plugins.e107.org]http://plugins.e107.org[/link] 
Themes: [link=http://themes.e107.org]http://themes.e107.org[/link] 

Thank you for trying e107, we hope it fulfils your website needs. 

(You can delete this message from your admin section.)

**Comment by MikeyGMT** [comment]
Also lan_installer.php cannot be saved in the UI 

e107_admin/language.php?f=lan_installer.php&lan=Welsh

On Save :- 

Error 403 - Access forbidden

This looks like one of the security features detecting code in the submission, I am a bit rusty on how to disable detection. I have checked the old wiki.  

I ran the debugger and saw 

PHP Errors:

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 1, Line 3662 of /home/green2015/public_html/e107_handlers/e_parse_class.php

**Comment by CaMer0n** [comment]
Thanks for this. Indeed, very outdated!
re: Error 403 - Access forbidden - Sounds like mod_security on the server. Better to do translations locally.

**Comment by CaMer0n** [comment]
LANINS_062 is/was no longer used.
