### ISSUE TITLE
Enhancement: Setting>Languages> Verify> Facility to Globally Edit the same phrase across the site

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1032]
I realise this can be done with file editor tools, but it would be nifty if we could update the same exact phrases globally.

**Comment by CaMer0n** [comment]
Please take note of all LANs which are identical - they are candidates for being moved to e107_languages/English.php or lan_admin.php

**Comment by MikeyGMT** [comment]
OK good idea - there's a lot of them - some even in the same files :S

**Comment by Moc** [comment]
Closing this. If there are indeed many of the same phrases which appear in different language files, then these should be moved to the generic language files.
