### ISSUE TITLE
BUG Language > Verify > Edit > Save not always successful

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1033]
Hi All
Go to Admin>Prefs>Language>Verify>Edit
Make some changes and save. 
You either save OK, or get to a completely blank page, with no warnings or errors. 
Or you are sent to the "error page" shown below. 
It may have something to do with bits of code in the values. 
Is it possible to over-ride the security for the language editor?
Thanks
Mikey

Examples are lan_admin.php and lan_installer.php cannot be saved in the UI

e107_admin/language.php?f=lan_installer.php&lan=Welsh

On Save :-

Error 403 - Access forbidden

This looks like one of the security features detecting code in the submission, I am a bit rusty on how to disable detection. I have checked the old wiki.

I ran the debugger and saw

PHP Errors:

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 1, Line 3662 of /home/green2015/public_html/e107_handlers/e_parse_class.php

**Comment by Moc** [comment]
> It may have something to do with bits of code in the values. 

Can you give an example of code that you enter?

**Comment by MikeyGMT** [comment]
Hi Moc, 

Just edit the existing suggested files. 

For example Verify then Edit lan_admin.php 

Add a space or something then hit save. 

It won't save. 

There are only some < b > bold tags in the values : no actual code in this one.  

Thanks

Mike

**Comment by CaMer0n** [comment]
All html needs to eventually be removed from LANs. @MikeyGMT Please also check if you have mod_security running on your server.

**Comment by MikeyGMT** [comment]
OK that worked on lan_admin I replaced <b> with [b] shortcodes. So a task needs to be setup to fix all the instances.

**Comment by MikeyGMT** [comment]
Oops - BB codes - yes that worked for the lan_installer.php
