### ISSUE TITLE
facebook redirected url

### ISSUE THREAD

**Issue by JihadTamimi** [e107inc/e107#1036]
after i press facebook sign-up icon the page stays white blank , i think the problem is the redirected url can any one tell me how to get it for e107 script , 
web site : http://www.ppucitce.com/

**Comment by tgtje** [comment]
Sorry but your page (aka Fbook icon works correct)
![face](https://cloud.githubusercontent.com/assets/1811857/7944609/ffbdd64c-096b-11e5-94e5-dfe922352ce8.jpg)
