### ISSUE TITLE
Bug: Import Site Data

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1037]
I went and export my data today (moving the site to a new host) and with a new instal version of e107 - tried to import the data that I exported today - upload and seems to be doing something then the page refresh, go out to see if the users and that have been imported in and nothing.

I open the xml of the exported data and see every thing is in there. So Import has an issue

**Comment by LaocheXe** [comment]
Doing some Testing - Exported just the Preferences settings and imported them, and it worked.

Tables on the other hand did not. 

I went and selected the tables instead - 

core_media
core_media_cat
cron
dblog
download
download_category
download_request
featurebox
featurebox_category
forum
forum_post
forum_thread
generic
links
news
news_category
page
page_chapters
user
user_extended
user_extended_struct
userclass_classes

Did not select:
admin_log
audit_log
banlist
logstats
mail_content
mail_recipients
menus
newsletter
rate
rss
submitnews
voice_exesystem
---------

Ones I did select - Upload and got an error for user_extended: Failed to Insert user_extended  Over and Over again (I do have my own user_extended tables), but got success for the rest.


Next try I have the fallowing selected:
submitnews
user_extended_struct
voice_exesystem

All was successful

Now for user_extended again but alone - still fail

After all this - Notice if it is too bit of an xml it times out (doesn't try to import at all) - also user_extended has an issue - xml gist: https://gist.github.com/LaocheXe/ca244c5b9deb8a55eaec

**Comment by CaMer0n** [comment]
The number of fields in user_extended is variable, which is why it is failing.

**Comment by Moc** [comment]
Is this still an open issue?

**Comment by Moc** [comment]
@LaocheXe @CaMer0n Is this still an issue?

**Comment by LaocheXe** [comment]
I haven't had any issues importing site data via xml  - so I think it might have been fix, not 100% sure - CaMer0n might know.

**Comment by CaMer0n** [comment]
@Moc I believe it is fixed. Closing.
