### ISSUE TITLE
gallery - sub categories

### ISSUE THREAD

**Issue by kreos** [e107inc/e107#1040]
i need the sub-category in the gallery area. it's possible?

**Comment by tgtje** [comment]
Explanation from e107help : http://www.e107help.org/1147/gallery-subcategory

each galleru basically uses subgalleries where each subgallery itself also has subs
gallery
   gallery/subgallery
              subgallery/subgallery

**Comment by kreos** [comment]
I did not understand! You may give me an example?

**Comment by Jimmi08** [comment]
There should be plugin for something like this. Gallery is not exact gallery, but just media category and actual gallery plugin uses these tables. For simple gallery good, but for complex gallery system not. 

Now, with e_admin functionality I would extended functionality of Book/CH/Pages system and add field for selecting gallery category to pages.

**Comment by KiraTheUltimate** [comment]
I support the idea. Every gallery needs an option to create subcategories.

**Comment by Jimmi08** [comment]
@KiraTheUltimate Idea is great but actual gallery is in fact media manager. And extending media manager with subcategories is just wrong way.

**Comment by KiraTheUltimate** [comment]
@Jimmi08  And if the gallery plugin would be only the extension of the media manager? And you could create categories in the gallery plugin and categorize the pictures there? (not in the media manager)

**Comment by Jimmi08** [comment]
Yes, but it shouldn't use media manager tables.   

This plugin should be fully updated: https://github.com/CaMer0n/pviewgallery/
It has albums, users albums, categories etc. 

Do you know that you can create simple gallery (category with images) and insert it via shortcode to news or pages?  And with book/chapter system you have gallery hierarchy then.

**Comment by KiraTheUltimate** [comment]
@Jimmi08 
Do you have a good portfolio template? Because the original is not so good, and I'm not a webprogrammer...
I would like to the images are displayed side by side.

Bottom of the page: https://starwarsmedia.hu/oldalak/star-wars-i-resz-baljos-arnyak

**Comment by KiraTheUltimate** [comment]
@Jimmi08 
Yes, but modified.

**Comment by Jimmi08** [comment]
Your answer:
https://www.e107.sk/forum/general-theme-questions/157/how-to-fix-gallery-portfolio-shortcode-output/

Tested with original theme.

**Comment by Moc** [comment]
This is plugin territory. Closing.
