### ISSUE TITLE
changing email in user settings

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1041]
![4t03vqe](https://cloud.githubusercontent.com/assets/12760959/8004168/1c44c180-0b75-11e5-9dc5-57ae4d0f691a.png)
Hi apologies if already open, but couldn't find a similar thread.

I just installed v2, using the latest master zip.

I am having an issue in my profile user settings setting and or changing email address.

Whatever email i try to use, personal, or domain email i am presented with the following error when submitting changes.

Error

12 - Email address - Invalid format for email address: gary231178@sky.com

I have also tried domain email of gary@ltnclan.com

Any advice please guys?

If i go to admin area, then users and edit user, i can edit and save with no problems. But if i then visit my profile and edit any info, set avatar etc, i um unable to save changes due to invalid email format again.

Regards.

Gary

http://i.imgur.com/4t03vqe.png

**Comment by LaocheXe** [comment]
Admin Area > Perference > User Registration&Login - Check remote servers when validating email addresses.

You have that enabled? Mine is disable and I tested e-mail changes in my settings and got no error.

Also what version of e107 v2 are you using (Beta1?)

**Comment by gary231178** [comment]
Yes that resolved both my problems, thanks for the help!!

**Comment by CaMer0n** [comment]
This feature worked at one time, but I believe it is no longer useful and is a candidate for removal.
