### ISSUE TITLE
Issue: Alternate Authorisation

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1042]
When set up on another site (same host) - ID 1 from Site A cannot login with Site B (Site B has Alt Auth that points to Site's A Database)

I went and changed it to Site B user login name is admin while Site A is LaocheXe - still an issue.

Method used: e107db - Primany: e107 - secondary: e107db - Failed Types will use secondary auth type.

Error on site:
Error
Incorrect login. The entered data doesn't match to a registered user. Check if you have the CAPS-LOCK key activated as logins on this site are case sensitive
Incorrect login. The entered data doesn't match to a registered user. Check if you have the CAPS-LOCK key activated as logins on this site are case sensitive

Yes displays it twice

If I use another user account (TestMe) it works...I even tried using the e-mail method to login and still the same error.

Configur e107db
User class restriction: 0
Password Method is set up to the right selection
Check the box against any field you wish to be transferred to the local database: All but ID have been selected

When testing to see if I can login

Username = LaocheXe
Password = **********\*  
Authentification successful
Retrieved parameters:
  user_email=>forbiddenchaos@gmail.com
  user_hideemail=>0
  user_name=>LaocheXe
  user_login=>Travis
  user_customtitle=>
  user_signature=>
  user_image=>-upload-ap_0000001_exeavata1r.png
  user_sess=>
  user_join=>1423692744
  user_ban=>0
  user_class=>10,11,12,5,6,7,8,9

is what I get - and TestMe
Username = TestMe
Password = ********\*  
Authentification successful
Retrieved parameters:
  user_email=>Testme@gmail.com
  user_hideemail=>0
  user_name=>TestMe
  user_login=>
  user_customtitle=>
  user_signature=>
  user_image=>
  user_sess=>
  user_join=>1433551501
  user_ban=>0
  user_class=>

So I don't know why it is having an issue with the one account (Unless it's because it is the main admin account)

**Comment by LaocheXe** [comment]
I also notice is once some one logs in - then logs out it deleted thair account on Site B

**Comment by Moc** [comment]
> If I use another user account (TestMe) it works...I even tried using the e-mail method to login and still the same error.

> So I don't know why it is having an issue with the one account (Unless it's because it is the main admin account)

So if I understand this correctly, it works for any other account but not with the main admin account?

**Comment by LaocheXe** [comment]
Yes, can't remember much, but I do believe it was an issue with the main admin account (ID as 1) - Can't test it further due to lack of having them websites up anymore. maybe in the future,

**Comment by Jimmi08** [comment]
@Moc this could be probably closed. AltAuth works correctly, expert option when e107 is a secondary source, but there is an issue with this.
