### ISSUE TITLE
Zend Optimizer is too new

### ISSUE THREAD

**Issue by pss0ft** [e107inc/e107#1043]
Hi,

I am trying to install the latest version of E107, but after the install seems succesfull I get the error message: 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@weststellingwerf.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2 Server at test.weststellingwerf.org Port 80

I found in the log one line which is in that log several times:

[Sun Jun 07 00:51:48 2015] [error] [client 217.120.173.252] Cannot load the ionCube PHP Loader - it was built with configuration 2.2.0, whereas running engine is API220090626,NTS
[Sun Jun 07 00:51:48 2015] [error] [client 217.120.173.252] Zend Optimizer requires Zend Engine API version 220060519.
[Sun Jun 07 00:51:48 2015] [error] [client 217.120.173.252] The Zend Engine API version 220090626 which is installed, is newer.
[Sun Jun 07 00:51:48 2015] [error] [client 217.120.173.252] Contact Zend Technologies at http://www.zend.com/ for a later version of Zend Optimizer

it seems that the Zend Optimizer used is newer than the one which is requiered by E107. Any idea for a solution?

Kind regards,

Henk

**Comment by Moc** [comment]
e107 is open source and does not need ionCube or Zend to load the CMS. The errors you copied must be triggered by another script or they are generic messages which are automatically send to the log by ionCube and Zend themselves. They are definitely not triggered by e107. 

Try and find other lines in the server log which may be related. Usually a 500 error is caused by a misconfiguration in the htaccess file (either due to a typo or due a conflict with the server configuration). Try temporarily renaming the htaccess file to something like `.htaccess_old`, this will deactivate its functionality.

**Comment by pss0ft** [comment]
Hi,

TNX for the help. I renamed the htaccess file to htaccess.old and E107 works now. The strange thing is that I installed E107 2.0beta1 from scratch. So the htaccess file must be created during the setup process, because the folder was empty when I ran the setup of E107.

How to proceed further now? I think I need some kind of htaccess file. Right? I will try to look for myself what can cause this error when I am using this htaccess file. I am not an expert in that area. :-)

TNX again.

Kind regards,

Henk

**Comment by Moc** [comment]
> So the htaccess file must be created during the setup process

Correct, this is part of the installation process. 

> How to proceed further now? I think I need some kind of htaccess file. Right?

Correct, to make full use of all functionalities you will need a functioning htaccess file. As noted in my previous reply, there is probably a line in the htaccess file which conflicts with your server configuration.  You may want to consult with your webhosting provider. A common issue I see is the configuration on line 35 of the htaccess file: `Options All -Indexes`. 
- Try disabling this line by putting a `#` sign in front of it. 
- Rename the htaccess file back to its original `.htaccess` (don't forget the dot)

Hope this helps.

**Comment by pss0ft** [comment]
Hi Moc,

This works. I re-enebled the .htaccess file with disabling 'Options All -Indexes'.

Thank you for the help. I am trying to convert my theme for this 2.0 version. The next problem is some glyph extensions which gives some strange results, but this is another topic. :-) I have no problems with the 1.xx version with this theme.

For example:

1.x E107: www.ph5hp.nl
2.0 E107: test.weststellingwerf.org

Kind regards,

Henk

**Comment by Moc** [comment]
No problem :)

Just create new separate issues if you experience bugs.

**Comment by CaMer0n** [comment]
@pss0ft @Moc - If you change it to just "Options -Indexes" - does it fix the problem?

**Comment by pss0ft** [comment]
Hi,

Yes, it does solve my problem, but I do not know what I have disabled now. What does ''Options -Indexes" ?...

Kind regards,

Henk

**Comment by tgtje** [comment]
If i am correct pss0ft it means that you have the file (htacc) in 1 directory only and works from througout there for the directory it is in, and all other directories following...

**Comment by Moc** [comment]
> What does ''Options -Indexes" ?...

It's a security measure which disables the 'listing' of all the files in a particular folder, when no index file is present. It's rather technical but there is no immediate need to worry as all of e107's folders have empty index files in each folder as a security measure. 

The problem you are facing is related to your particular server configuration. Webservers, on which websites are located, are configured in different ways according to the preferences and needs of the webhosters. Some configurations conflict with each other. While e107 tries to use the most standardized options, it may happen that these options conflict with particular server configurations as was the case with your website. 

I'm confident that the default htaccess file will be tweaked in an update of e107 so such conflict can be avoided.
