### ISSUE TITLE
Question: Language / hardcoded txt translation question (premature?)

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1044]
Most likely premature at this point as it is NOT really a bug. 
How to handle hardcoded txt in systemfiles ( to defined lan's ?)

**Comment by CaMer0n** [comment]
I'm not sure I fully understand the question. Are you asking how to translate and define hard-coded terms?

**Comment by tgtje** [comment]
Example : sitelinks > menulinks> tools >
it display 2 tabbed windows > 1 sunlink generator 2 > generate LANS

tab window 1 (sublink generator) 
is fully defined in languages (# lang/Dutch/admin/lan_links php > (LINKLAN_4 etc.....)

tab window 2 (generate LANS) is english > finding the appropiate texts as displayed (alike button txt #blue and button #red ) are NOT available in #lang/English/admin/lan_links php ( expected to find them here; seems most logical)
search reveals the content/txt is hardcoded in > e107_admin/links php  as $text2 ....... (line 335 and 338 )

This is just 1 example (it also happens at some other files and dropdown menus etc..).
Hope it is better explained, hence also maybe premature stage to get/translate to full?.

Note : ! it will NOT interfere with the internal working, just the internal does display in both languages. (and there can not be language related check runs..hardcoded is not in there etc....)

Of course i could create an OWN lan in respective file and add it to file definitions, but at this state i would hack core files (at a personal/only me level).

**Comment by nlstart** [comment]
I'm not quite sure if it is possible, but it would be great if there would be a possibility to create a theme lan items that would overwrite core lan's. With such a scenario you wouldn't have to 'hack' existing lan files, and it would be easier to handle updates/upgrades etc.

**Comment by tgtje** [comment]
No it is (imo) merely an agreement how and where the definition belongs to.
Of course the base is created with hardcoded txt and at later stage the txt is replaced by a lan call..
here's an example ( i 'hack' admin/links php delete the txt and replace with a 'imagined' lan and put it dutch/admin/lan_links php... it is rather easy to do but as mentioned above.. is it at the right place and would it be suitable etc... (agreement on..)
![runlan](https://cloud.githubusercontent.com/assets/1811857/8083750/2e7eb12e-0f87-11e5-9440-ca4314e90b8d.jpg)

**Comment by nlstart** [comment]
My humble advice would be NEVER to use Windows Notepad for translation files. It can leave BOM. http://wiki.e107.org/index.php?title=Install_troubleshoot#BOM_-_Byte_Order_Mark

**Comment by tgtje** [comment]
I know Henk , but it is merely used to create the screenshot for now (the editor does not like to be in multiple windows).

 I did mention to forget, i would need to define the new define in English/admin/lan_links also.. to make it system correct....

**Comment by nlstart** [comment]
Okay Leo, I was already confident you knew that. Just leaving it for future reference so users unfamiliar with that subject can take the BOM notice into account.

**Comment by Moc** [comment]
I suppose what Leo is asking is this: are we at a stage where the hardcoded LANs can be added to the English LAN files? This way the translators can see which strings need translating through the language tools.

**Comment by tgtje** [comment]
Basically yes Moc. I do NOT  want to saddle up people with much rewriting on files just for the sake of language only. While there are still things changing i can see that development/debugging will suffer when only defines are in place, against it : the issue/bug reporting could be more specific..

**Comment by CaMer0n** [comment]
Please see my comment from Feb 15 in #6 .

**Comment by tgtje** [comment]
Got it; a commit on actual file involved and a defined LAN what does not exist AND is NOT in use for v1 too... ( as done in example) but ONLY for english... so a to translate pack creates itself

(let'see if i get the commiting again running; last time i was Lucky i guess)

**Comment by tgtje** [comment]
First pull request submitted ( working and tested ) please comment if useable and correct applied..

**Comment by tgtje** [comment]
For readers : the example screenshot has to be interpreted as a true example. The file (-s) in question are changed at present time (that can happen due to enhancements/bug correction etc.. ), however the 'how to handle' method can be used. 
Just a note for those that would use it similar ( the define placed in system files (write/coding) differ from the position it is in (standalone vs part of... beware!! # for the non coders... like me)

**Comment by tgtje** [comment]
Answer was given and referenced , think it is save to close this one..
Reopen if still needed

**Comment by Moc** [comment]
@tgtje Great work :) Please take into consideration the checklist as posted here by cameron: https://github.com/e107inc/e107/issues/6
