### ISSUE TITLE
Blank posts

### ISSUE THREAD

**Issue by Ashguardian** [e107inc/e107#1046]
Hi!

I have installed the latest version to test, and found an issue. If I use html tags or/and (hungarian) unique letters (űáőúóüö) in input fields (page, news, chat, etc.), I get blank posts.

**Comment by tgtje** [comment]
Can not recreate ; working as expected :  screenshot from page (file date 1,5 weeks)

![hung](https://cloud.githubusercontent.com/assets/1811857/8084273/8697b61e-0f8a-11e5-84c2-b3f59d175815.jpg)

**Comment by Ashguardian** [comment]
I have installed the latest version of xampp, and the problem has gone.
