### ISSUE TITLE
Announcement: Multiple Languages Plugin for v2.

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#1049]
I have just added a new "multiple languages" plugin for e107 v2 in it's own repo. It's based on a couple of plugins I developed for v1 but never released. If you find bugs, please post them in the corresponding issues tracker here: https://github.com/e107inc/multilan or better still, submit a pull-request with a fix. 

@nlstart @myovchev @Moc @lonalore @LaocheXe  @tgtje

**Comment by tgtje** [comment]
Question : this is an enhancement on the  (2015-06-10)  revoked  sitelinks/tools/Tab window 2 >  Generate Lan's code ? 

Note:  # if users did not update all files from master again, they will find the 'old traces' still in their system. (the above)

**Comment by CaMer0n** [comment]
Yes, It's a small part of it. The main part is the syncing of data between languages.

**Comment by Moc** [comment]
Closing this on this repo. Further communication on the multilan plugin can take place in its own repo.
