### ISSUE TITLE
Blank page after submitting news in admin

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1050]
Hi, after submitting a news article (admin screen)) i get a blank page, but the article is placed, there's a problem with 
    After submit:
    go to list
    create another
    edit current

When i enter 'create another' it works... so the standard 'go to list' gives a problem..

Alex

**Comment by CaMer0n** [comment]
Please enable debug and also check for error_log files in the admin directory.

**Comment by Alex-e107nl** [comment]
Solved with the 2.0.0. version THX!
