### ISSUE TITLE
.Glyph

### ISSUE THREAD

**Issue by pss0ft** [e107inc/e107#1052]
Hello,

I am trying to get a theme without missing icons. Every time I am trying to use with version 2 of E107 will have icon issues. I found out that in the code a glyph icon is used. See ththis line below:

```html
<img src="/e107_images/icons/icon-upload.glyph" alt="" style="vertical-align:middle">
```

There are NO glyph icons to be found in this installation of E107. No icons with the glyph extensions at all. What is the story about this? I have found this icons on the web with allmost the some file name exept the glyph extension. It is all ending on PNG.

Can anyone tell me if this is a bug or do I something wrong? Must the THEME I want to use be edited/updated to use with version 2 of E107? I am puzzled .

Kind regards,

Henk

**Comment by tgtje** [comment]
Maybe this will help (or give some inside info) http://www.e107help.org/137/home-other-pages-different-bootstrap-than-admin-admin-panel
Read the comments please 
Main page for dev : http://e107.org/developer-manual/classes-and-methods/parser
general advice : Use Bootstrap 3 html/css standards in your templates and/or HTML markup

**Comment by Moc** [comment]
It would really help if you could show us a live example of your issue. What code is being used, and where is this code used?

**Comment by pss0ft** [comment]
Hello Moc,

I am not an expert, but it seems that some icons are missing from the image\icons directory. I searched in the source code of the theme I used and this line is not a part of that php code. So I think it is a part of E107 itself.

I learned some in the last several days about glyph icons, but I still do not know what to do in case of the E107 CMS. Do I have to copy them in to the image/icons directory and what about the extension? The .glyph extension which is used.  I am puzzled.

It takes a long time before version 2.0 is out on the market. Maybe too long. I know several people who abandonned E107 for that and if it also is difficult to make it work maybe more people will hop over to other CMS. I like E107 and I even programmed some plugins for that, but even I am looking for alternatives in the future if E107 will slowly go forward.

Kind regards,

Henk

**Comment by Moc** [comment]
I understand the confusion. Let me try to explain:

- The glyphicons are not physical images as you would see with for example png or jpg images. 
- They are included in the e107 core and every theme or plugin can make use of them by simply using:
```php 
e107::getParser()->toGlyph('star'); // replace star with whatever glyphicon you want
```
- This means you cannot trace the location of the glyphicon. It's based on CSS. The e107 core uses the fontawesome glyphs: http://fortawesome.github.io/Font-Awesome/

It would help if you could show us what you want to do. Perhaps by providing the link to your website. 

As for the development pace... Yeah, mostly it's just Cameron working on it and he has a full time job and a personal life to take care of. There's no huge development team or any financing for that matter. Having said that, the current beta version is pretty stable already :)

**Comment by pss0ft** [comment]
Hello Moc,

Thank you for your help. If I want to progress to version 2 in the future I expect that my theme must be adjusted to be able to use these glyphicons? Adjusted in the CSS file?

Are there more significant changes in the Theme area I should know about?

Kind regards,

Henk

**Comment by Moc** [comment]
> I expect that my theme must be adjusted to be able to use these glyphicons

Nope :) The glyphicons are optional and are not required. They are usually used in combination with Bootstrap based themes, which is the main CSS framework that e107 v2 uses (but which is not required to be used). 

There is no need to adjust your theme files to support Glyphicons. If you want to use them, you can do so using the code above or through minor editing of the theme file. 

I am unsure of what specific issue you are experiencing. 
You stated this:

> I am trying to get a theme without missing icons. Every time I am trying to use with version 2 of E107 will have icon issues. 

What do you mean specifically by this? Can you show me an example or screenshot of the issue? This way I can understand what your considerations are, so that I can give more targeted advice.

**Comment by CaMer0n** [comment]
$tp->toIcon() will detect between a .png and .glyph automatically. It is the best option to use for rendering this data from the links and other tables. .

**Comment by Moc** [comment]
Oh and here are some guidelines on updating v1 plugins/themes to make them compatible with the new features in v2: 

- http://e107.org/developer-manual/plugin-basics#upgrading-v1-x-plugins
- http://e107.org/developer-manual/theme-basics#upgrading-v1-x-themes

**Comment by Moc** [comment]
Closing this issue as I think the question has been answered. If you have any other questions, let us know
