### ISSUE TITLE
userclass specific forum threads

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1054]
Hi in my forum i have 2 locked areas only visible by specific userclasses.
1 is for admins (admin userclass)
2 is for clan members (clan userclass)

Question is the 2 sections of forum keep randomly disapearing and can not be seen by those with the active userclasses. Only way i can get them back is by logging out and back in again where they become visible again.

Any ideas?

Gary

**Comment by Moc** [comment]
Question, do you have 'cache' enabled?
- In admin area > settings > cache
- If enabled, try disabling the content cache
- Then emtpy all caches by means of the red button below. 

Does this help to avoid the issue?

**Comment by gary231178** [comment]
Hiya, thanks disabling cache seems to resolve the issue,

**Comment by Moc** [comment]
If you re-enable the cache again, does the issue come back again? 

I'm asking because if this is the case, I would consider this a bug that needs fixing.

**Comment by gary231178** [comment]
I can confirm, that when re - enabling the cache i am presented with the issue again, so yes is a bug if using cache enabled.

Gary

**Comment by CaMer0n** [comment]
Thanks @gary231178, I'm guessing that you made the class modifications using the inline editing, rather than via the 'edit page' ?

**Comment by gary231178** [comment]
Not sure what you mean, but in the forums section the classes are assigned to the forums there as below:-

Hope that helps.

![screenshot_12](https://cloud.githubusercontent.com/assets/12760959/8192562/e94fbc30-1466-11e5-8707-7755032ff22e.png)

**Comment by gary231178** [comment]
Hi, i commited the 2 changes 
e107_handlers/admin_ui.php & e107_plugins/forum/forum_admin.php

Re enabled cache to test, refreshed forum and immediately class forums disappeared again, so the commited changes didn't seem to resolve this issue at present.

![screenshot_13](https://cloud.githubusercontent.com/assets/12760959/8193330/161ca4f8-146c-11e5-8476-5e10c793f753.png)

![screenshot_14](https://cloud.githubusercontent.com/assets/12760959/8193369/5f178f4c-146c-11e5-93ca-29aceed5756f.png)

**Comment by CaMer0n** [comment]
Please clear the cache in full. It may have left-over data from an earlier version of e107 (without the changes I made)

**Comment by CaMer0n** [comment]
@gary231178 can we close this one now?

**Comment by Moc** [comment]
I'm assuming this is fixed. Closing for now, let us know if it needs to be reopened.
