### ISSUE TITLE
user login issue after admin edit.

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1055]
Hi,
If an admin visits a users profile and edits any of their info, i.e sets an avatar or fills in missing data,
the next time the user tries to login after entering their details and logging in, it shows them as being online but not logged in. 
When re entering their details again it says incorect login info. Seems i have to delete the user and let them re sign up again.
How i came about this issue was, i was editing all users which did not display an avatar selecting a site stored avatar for each user.
I save etc without adjusting any of the users login info / passwords etc.
All of the users i have edited have since had this "ghost login" problem, showing logged in on online menus etc, but physically not.
Users have tried forgot pwd links etc to reset and this doesn't resolve the issue either.

Any help much appreciated.

Gary

**Comment by gary231178** [comment]
Hi able to do a test user and get a screenshot.
A screenshot shows incorrect login info, but online menu below shows "test user" online

![screenshot_5](https://cloud.githubusercontent.com/assets/12760959/8150841/b306b3a2-12f1-11e5-96a4-2a659f7aff0c.png)

**Comment by CaMer0n** [comment]
Thank you for the info @gary231178 . Would you mind also providing a screenshot of the page you are editing the user data with, (and be sure to include the password field etc.). ie. a screenshot of you reproducing the issue in admin. Thank you.

**Comment by gary231178** [comment]
Hiya, please find enclosed 2 screenies.
The first is prior to editing, which auto puts in my user name (being the admin editing) into the custom tilte for some reason (but it did this in v 1 also) and ********* in password field.
![screenshot_8](https://cloud.githubusercontent.com/assets/12760959/8186570/f92fce70-1442-11e5-9368-3835f3bd7dc0.png)


When i made the changes i empty both these fields and then save as screenshot below.

![screenshot_9](https://cloud.githubusercontent.com/assets/12760959/8186576/ff46aac2-1442-11e5-814d-77c49954102b.png)

**Comment by CaMer0n** [comment]
Thanks, yes that's browser auto-complete.

**Comment by CaMer0n** [comment]
@gary231178 do you have access to phpmyadmin? I am curious to know exactly what data in the user record is changing after you make the edit. You might consider doing an mysql export of a single record BEFORE the edit, and another AFTER the edit. Then doing a file-comparison.

**Comment by gary231178** [comment]
Ok, so i actually think that the bug doesn't lie here and the admin edits were just coincidental, reason being i am having the same issue with other members who i haven't edited profiles for, so will close and open a seperate report with more info on this issue.

Gary
