### ISSUE TITLE
Forum rules not showing

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1056]
Hi i have activated forum rules for specific userclasses, but they aren't anywhere to be seen by members to read, where are they and when should they be found? prior to posting, landing on the forum page? even if i navigate to /forum?rules nothing shows.

Regards.

Gary

**Comment by CaMer0n** [comment]
Most likely missing from the v2 template. I will look into it.

**Comment by gary231178** [comment]
Thanks CaMer0n much apreciated.
