### ISSUE TITLE
Login menu fix produces new bug

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1059]
Hiya, sorry for lots of posts recently, but love e107 as a user for past 7 years, and just actively started switching to v2.

I just updated using master zip as i noticed recent changes (5 days old)
1 of which references to login menu cleanup.
However i have a new bug since updating files showing LOGIN_MENU_L25: code in menu, which wasn't present prior to updating.
![screenshot_11](https://cloud.githubusercontent.com/assets/12760959/8186938/008d1bd0-1445-11e5-8e26-f7f015b886bb.png)

**Comment by CaMer0n** [comment]
hey @gary231178 - we appreciate the posts - keep 'em coming!. 
If you have used a modified version of bootstrap3 for your theme, you just need to do a search/replace on your files. (most likely theme_config.php)

LOGIN_MENU_L1 should be replaced with LAN_LOGINMENU_1
LOGIN_MENU_L25 should be replaced with LAN_LOGINMENU_25
etc. etc. 

,

**Comment by tgtje** [comment]
Cameron was quicker, your files are probably just over 5 days old (around start of june) .

There L25  still exists in those. As described above> the newer files  (5 days) are correct..(you alwaus may update and have all changes...;-)

**Comment by gary231178** [comment]
@tgtje  Nope i saw the change log and as of today the modified files were showing 5 days old, so i re downloaded the master.zip and overwrote all files so if the master was updated 5 days ago, or even today i am using the latest.
@CaMer0n i'm using a premium theme by @mcpeace (AKA manatwork) so not sure if its a modded bootstrap3 or not, but ill search out those files and cross-examine

Cheers all,

Gary.

**Comment by gary231178** [comment]
Found it and fixed!! was in the following:-
login_menu_template.php
Replaced LOGIN_MENU_L25 should be replaced with LAN_LOGINMENU_25

Cheers all
