### ISSUE TITLE
Deleting avatars in Media manager.

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1061]
Hi when deleting avatars within media manager, after selecting said avatars and clicking delete checked, the page refreshes, returns to media library, but the avatars are still there un-deleted 

Where can i find them in ftp to delete as an alternative? is this possible?
There is one particular offensive avatar i need to delete urgently.

Regards.

Gary

**Comment by CaMer0n** [comment]
I believe this is a duplicate of a known issue. Path is e107_media/xxxxxx/avatars

**Comment by Moc** [comment]
#802

**Comment by Moc** [comment]
Hmm may not a complete duplicate. In my report, the files are deleted from the media manager but when checking with ftp, they're still there.
