### ISSUE TITLE
Downloads category icon does not show

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1062]
Download categories not displaying category icon on downloads page.
However when you refresh webpage it appears & disappears in the background.

**Comment by Moc** [comment]
Do you have a live website example of this? What type of icon are you using? Ie. an image or a glyph or?

**Comment by gary231178** [comment]
Glyph's work fine but not any uploaded images. As a temp work around i have just put an image in the body of the text for each category.
website:- http://www.ltnclan.com

**Comment by gary231178** [comment]
It would seem that the custom images are automatically being overrode with a tick glyph by default, if that helps.

**Comment by CaMer0n** [comment]
@Moc I believe this may have been fixed with the legacy-path fallback I added a month or so ago.

**Comment by Moc** [comment]
@gary231178 This should be resolved in the latest release (2.1.3) as well as the latest Github version. Please update and confirm.

**Comment by CaMer0n** [comment]
Confirmed, broken when SEF URLs are used and a legacy icon path is in use.
