### ISSUE TITLE
Bug: Topics not being listed when click on forum heading

### ISSUE THREAD

**Issue by martasalek** [e107inc/e107#1066]
Hi guys,

Just updated our site to the e8892454da commit. (Actually, I downloaded a different commit last night, then noticed a couple of extra files so added those in.)

After this update, when you click on a forum heading from the main forum.php page, you end up with a message saying that there are no topics for that forum, even though there are some. The issue appears to be with the e107107_plugins/forum/forum_viewforum.php and or forum_class.php page. See attached image.

![notopicslisted](https://cloud.githubusercontent.com/assets/9205671/8270712/43879320-1832-11e5-9d94-cde0e5c16ad1.png)

I believe @CaMer0n has the login details to our test site where you can also see the problem reproduced. The Members Message Board forum has at least one topic in it. (Note that the counts of topics is incorrect for each forum as we are using a cut down database, but we have definitely created a test topic in that forum.)

I've reverted the forum plugin on our live site for the moment.

Thanks!

Marta

**Comment by martasalek** [comment]
Update: After some investigation, it appears that the issue was caused because there'd been a new field added to the e107_forum table: forum_sef. I've added this field now on our live and test sites and the issue appears to be resolved. 

Just before I close this and apologise for wasting your time, are you able to let me know if there have been other database changes that we need to be aware of since our last update in mid April?

Thanks!

**Comment by Moc** [comment]
There probably are but there is no easy way to check for that and create a list of them. 

I strongly recommend updating all the files from Github. Then login to the admin area and it will tell you if it needs any database updates. You can also run this check manually through the 'Tools > Database' section.

**Comment by CaMer0n** [comment]
@Moc :+1:   Yes, 'Sync with Github' should save most people a LOT of time. 

From memory, forum_sef was added a while back, and more recently thread_sef was dropped. All these changes should occur automatically when the 'update' is triggered.
