### ISSUE TITLE
'Go to page' broken for topics with multiple pages

### ISSUE THREAD

**Issue by martasalek** [e107inc/e107#1068]
Hi guys

After updating to commit e8892454da, the 'Go to page' buttons for a topic listed under a given forum appear to be broken. 
![gotopagebrokensmall](https://cloud.githubusercontent.com/assets/9205671/8279668/d6c5c642-1919-11e5-9079-914617f53fd5.png)
Clicking on one of the numbered page links takes the user to the first page of the topic. 

The URL when clicking on one of these page buttons is of the form:

[siteurl]/e107_plugins/forum/forum_viewtopic.php?id=463411?p=2

Note the second question mark in front of the p rather than the ampersand.

To rectify this issue on our live site, we have for the time being updated the e107_plugins/forum/forum_viewforum.php file at lines 813 823 and 835, changing:

$url = e107::url('forum','topic',$urlparms).'?p='.$aa;

to 

$url = e107::url('forum','topic',$urlparms).'& amp;p='.$aa;

(Note the space between & and amp above is artificial to prevent HTML rendering into an ampersand.)

Cheers

Marta

**Comment by martasalek** [comment]
Thanks, @CaMer0n :).

**Comment by CaMer0n** [comment]
Thank you for the file and line numbers - it made it too easy! :+1:
