### ISSUE TITLE
Editing sticky topics does not preserve stickiness

### ISSUE THREAD

**Issue by martasalek** [e107inc/e107#1069]
Hi guys,

Just a minor thing. After updating to commit e8892454da, we've noticed that editing the first post in a sticky topic does not, by default, have the sticky option selected. When you update the topic post, the topic 'unstickies' which can lead to confusion if you don't notice it straight away.

To illustrate, a couple of sticky topics on our live site:

![stickytopics](https://cloud.githubusercontent.com/assets/9205671/8279985/5123bdd4-191c-11e5-817c-8c320b0f4b2f.png)

When I edit the first post in one of them, you'll note the 'sticky' option at the bottom of the edit screen is not selected.

![editingtopicnotsticky](https://cloud.githubusercontent.com/assets/9205671/8279993/655bc788-191c-11e5-9f11-cb6277b2ba52.png)

Thanks!

Marta

**Comment by Moc** [comment]
Confirmed. Saw it after I committed some changes in that area a few days ago but didn't get a chance to take another look. Will do so asap.

**Comment by Moc** [comment]
Do you happen to know if this issue was also present before updating or did this issue start after updating to the latest files?

**Comment by martasalek** [comment]
Hi @Moc, prior to this update we'd last updated in April. At that time, we were unable to edit the first post for a topic as per the closed issue #1001 so can't confirm. Sorry!

**Comment by Moc** [comment]
That makes sense, thanks for the quick response.
I'll take another look shortly.

**Comment by Moc** [comment]
This should do the trick, let me know if it works properly or not :)

**Comment by martasalek** [comment]
Thanks, all good @Moc :). You guys are quick!
