### ISSUE TITLE
Language by Domain Name = Welsh - No longer working

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1072]
Hi e107 Devs
I am testing progress of my attempt to build a translation pack for Welsh, admittedly the translation is incomplete. When I go to the .cymru URL it's not displaying the site in Welsh (but it was a few weeks ago). The default site is .wales (English). 

I yesterday's extraction of the Git Repository. I have set:-
* Sessions not cookies. 
* Default Lan = English 
* Admin Lan = English 
* Language by Domain Name = Welsh
* e107 Cache = Disabled

I have cleared browser cache etc. I see the notices pasted below, which may provide a hint. 

I spotted that in e107_handlers/language_class.php the variable the variable 
protected $names = array(
does not contain 
,   "Welsh" => "Cymraeg"	
which I added after Vietnamese, but it did not help. 

My lan folder is named Welsh and the locale details in Welsh.php are 

setlocale(LC_ALL, 'cym.UTF-8', 'cym.utf8', 'cym.utf8', 'cym');
define("CORE_LC", "cy");
define("CORE_LC2", "gb");

Although I don't fully understand what each of the above need to be. Should LC_ALL end in EN so it can back track, and what should LC2 be? Have searched the old wiki and the legacy forum search function is disabled and my account there is locked - which drives wiki access too. 
 
Thanks

MikeyGMT

Notice: Undefined index: noLanguageSubs, Line 64 of /home/xxx/public_html/e107_admin/language.php
Notice: Undefined index: f, Line 357 of /home/xxx/public_html/e107_admin/language.php
Notice: Undefined index: mode, Line 358 of /home/xxx/public_html/e107_admin/language.php
Notice: Undefined index: lan, Line 359 of /home/xxx/public_html/e107_admin/language.php

**Comment by MikeyGMT** [comment]
Checked error_log

[22-Jun-2015 23:15:58 GMT] PHP Parse error:  syntax error, unexpected T_STRING, expecting T_VARIABLE or '$' in /home/xxx/public_html/e107_languages/Welsh/lan_error.php on line 42

I'll check that lan file now

**Comment by Moc** [comment]
>  PHP Parse error: syntax error,

That would be the reason for it not to work :) Let me know if you need help sorting that out.

**Comment by MikeyGMT** [comment]
OK I found a cheeky . appeared in the variable, {$ mySQLdefaultdb}

[7]: MySQL yn rhedeg, ond cronfa ddata ({$ mySQLdefaultdb}) na ellid fod yn gysylltiedig â.<br /> Gwiriwch ei fod yn bodoli, a bod eich e107_config.php yn cynnwys y wybodaeth gywir.

One down, I'll continue working on it :)

**Comment by Moc** [comment]
So is the Welsh language working again now?

**Comment by MikeyGMT** [comment]
Well it got rid of the warning/error in the log. 

Still not working, it works only if I set the Default Site to Welsh. 

I forgot to mention that I had e107_plugins/multilan-master installed to test, but that won't load the config page - see separate thread. 

Un-installed e107_plugins/multilan-master no joy.

I'll keep playing ...

**Comment by Moc** [comment]
Did you try renaming `multilan-master` to `multilan`?

**Comment by MikeyGMT** [comment]
>>Did you try renaming multilan-master to multilan?
Yes that worked > thanks for that :D 

Switched to Bootstrap 3 Theme to try to eliminate my theme.

**Comment by MikeyGMT** [comment]
Is there a recent v2.0 lan pack elsewhere like German/French/Spanish to test & rule out my work?

**Comment by Moc** [comment]
> Is there a recent v2.0 lan pack elsewhere like German/French/Spanish to test & rule out my work? Or NL of course :)

I'm not sure to be very honest with you. I do know that there are people working on a Dutch language pack but I haven't seen the source code of it. I'm not even sure if it's published somewhere. Maybe @tgtje can help you out.

**Comment by tgtje** [comment]
No secret there @Moc or @ MikeyGMT  the code is still on sourceforge/e107Dutch
Note ! because the last 2/3 weeks more LANS have been changed on e107 master, rewrite has te be done (again hehe)  path(code)

beware the pack if used Mikey (the build could seem a little different) it is a work in progress.
it is functional (for that that is finished) Complete > NO  (even ready things have to be looked into again because of new changes # and newer ones will come)

**Comment by MikeyGMT** [comment]
Aha ... spotted there was an area in the main links with an active link but no text. Just an extra wide gap.

Edited the English version Site Link to have Language / Welsh to Iaith 

Both of the links are assigned Functions > Multilan > Language Links

![image](https://cloud.githubusercontent.com/assets/2847651/8304801/3d772d5e-19a1-11e5-918e-1924ec26c1cc.png)

However the system seems to follow the Default Site Language, and ignores the domain setting.

Default Lan = English
Admin Lan = English
Language by Domain Name = Welsh

The result is 
.wales visitor => sees English (correct)
.cymru visitor => sees English (incorrect)

But it is working sort of.

**Comment by tgtje** [comment]
by domain name ( old issue) => TRUE domain (  $$ )

**Comment by MikeyGMT** [comment]
So I am guess it's an issue of which option should take precedence? Hmm difficult one as there are different situations. 

In my case, I hope Welsh speakers will go to fy-ngwefan.cymru and English speakers to the my-website.wales 

I would rather not use cy.my-website.wales or en.my-website.wales or cy.my-website.wales or en.fy-ngwefan.cymru I am sure others would want to keep their brand by using only the one base url. 

Now my head hurts :)

**Comment by CaMer0n** [comment]
@MikeyGMT , please enable the e107 debug (Firefox plugin) so it shows Paths and Variables, then check the value for e_DOMAIN and e_SUBDOMAIN. It could be something as simple as that value being incorrect.

**Comment by MikeyGMT** [comment]
Hi @CaMer0n 

When navigating to the mysite.cymru 
e_DOMAIN is the mysite.cymru (correct)
e_SUBDOMAIN is null
e_LAN 	en
e_LANCODE 	
e_LANGUAGE 	English
e_LANGUAGEDIR 	e107_languages/
e_LANLIST 	Welsh,English
USERLAN 	English - when I change the Language via the menu it does change to CY

To mysite.wales 
e_DOMAIN is the mysite.wales 
e_SUBDOMAIN is null
e_LAN 	en
e_LANCODE 	
e_LANGUAGE 	English
e_LANGUAGEDIR 	e107_languages/
e_LANLIST 	Welsh,English
USERLAN 	English

When going to cy.mysite.wales 
e_DOMAIN is the mysite.wales 
e_SUBDOMAIN is cy
e_LAN 	en
e_LANCODE 	
e_LANGUAGE 	English
e_LANGUAGEDIR 	e107_languages/
e_LANLIST 	Welsh,English
USERLAN 	English

But for each the default Language displayed by any visitor loaded is EN.

I have even changed my firefox and MSIE language to CY 

I'll disabled the lan links from multilan and that has worked for the .cymru and .wales

The cy. is still in English - which has worked for me as I won't be using the cy. However, others users may want to use parked domains - so maybe still needs to be looked at. 

Also does this need to be fixed?
>> I spotted that in e107_handlers/language_class.php the variable the variable 
>> protected $names = array(
>> does not contain 
>> , "Welsh" => "Cymraeg"

Thanks for the assistance guys 
:) 

Mikey

**Comment by CaMer0n** [comment]
Thanks. One more thing, do you have "Enable Multi-Language Tables" enabled?
btw. CORE_LC = language, CORE_LC2 = country. This is how it can tell the difference between French from France or French from Canada, for example.

**Comment by CaMer0n** [comment]
I can't find ANY reference to the preference "multilanguage_domain", so this feature needs to be added.

**Comment by MikeyGMT** [comment]
Hi Cameron, 
Thanks for the info. Looks like I have set LC and LC2 correctly then. 
Enable Multi-Language Tables = Yes ... for ... comments, links, menus, news, news_category, newsletter, page, page_chapters, polls, submitnews (I was looking for 'welcome message' too, as I use Welcome Msg for my home page, as it loads without a redirect - I read some time ago that this helps SEO by not confusing crawlers).
Cheers
Mike

**Comment by MikeyGMT** [comment]
Thanks tgtje, I had a look on sourceforge/e107Dutch could only see v1's and earlier.

**Comment by CaMer0n** [comment]
@MikeyGMT You'll want to enable 'generic' for the welcome-message. Please test with the recent change. I added the code but have not tested it.

**Comment by MikeyGMT** [comment]
Thanks @CaMer0n 
Welcome message is working fine, both front pages can have the same message with English and Welsh in the same message - so it can tell them to go here or there for their own language. No need for a change there. 

I have the master domain as mysite.wales plus the parked domains cy.mysite.wales and mysite.cymru 

Cleared caches - site and browser
Master .wales is ok - is in English.
mysite,cymru is ok - is in Welsh
cy.mysite.wales - is in English - oops

But I suspect because I have both enabled or there is some caching elsewhere in the ether going on. I guess though it is unlikely that someone would use both formats at the same time. In my situation I can use parked domain redirect cy. to the .cymru which should be treated as the official Welsh site. 

Tomorrow I will test another site using just the prefixed language parked domain cy.somewhere.co.uk to ensure this feature is working, as I guess this is more common.
Cheers 
Mikey

**Comment by tgtje** [comment]
Look again @MikeyGMT  ( as mentioned ) use Code (bar link) at that page. ( both versions are there)

**Comment by MikeyGMT** [comment]
got it thanks :)

**Comment by CaMer0n** [comment]
Just committed something which should, in theory, fix the "cy.mysite.wales - is in English - oops" scenario.  ;-)

**Comment by MikeyGMT** [comment]
There's a small problem, when on .cymru / Admin / Welsh is displayed, but if you use the Globe Link to switch to English it stays in Welsh.

**Comment by CaMer0n** [comment]
@MikeyGMT Could you please tell me what the URL is of the English link (under the globe)?

**Comment by MikeyGMT** [comment]
http://xxx.cymru/e107_admin/admin.php?elan=en
Yep Default

![image](https://cloud.githubusercontent.com/assets/2847651/8413599/9bcd29ca-1e89-11e5-893c-4bbe94c0848d.png)

**Comment by CaMer0n** [comment]
Difficult to fix while using 'language domain' only. The Solution is to use a language subdomain so that you can seamlessly switch between languages in admin without being logged out.
