### ISSUE TITLE
Enhancement>Languages>New Pack Generator>Pre-Populate a New Lan via BING Translate Free API

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1074]
To help grow the available languages faster, could we consider including a new feature in the New Language Pack Generator? I am thinking of the BING Translate free API for translators to be able to pre-populate a New Lan (empty) file. https://msdn.microsoft.com/en-us/library/ff512421.aspx#phpexample 
Due to the 2 million char's free limit per month I suggest it should be at the file level. Then each translator only has to validate or correct the data returned in each file, rather than do all the donkey work to populate all the files in the first place, which is what I am doing now. It's helping me learn a lot of new words in my rusty Welsh skills! When complete it's my intention to ask a competent Welsh speaker to proof read for me.  
I am currently using Chrome Extension TransOver, which is fiddly but a bit faster than flicking between full google translate.

**Comment by tgtje** [comment]
@MikeyGMT not the best method to get a message through but in relationship to Github pull requests :   
maybe take a look here https://www.youtube.com/channel/UCdzghA7K6K5KqUrCow5z4UQ/videos  (videos turn out to be a bit blur) it will at least show a method..
Success

**Comment by Moc** [comment]
Don't forget these: https://guides.github.com

**Comment by CaMer0n** [comment]
@MikeyGMT I'll be including this in the multilan plugin.

**Comment by CaMer0n** [comment]
Closing. See multilan plugin.
