### ISSUE TITLE
Back door spam entry (forum)

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1075]
Hiya, i'm noticing that in my forums, threads which are set to admin post only, spammers are gaining acess and spamming as admin userclass without even a user signup created.
Please see the new post just now:-
![screenshot_2](https://cloud.githubusercontent.com/assets/12760959/8356022/97608b8a-1b4a-11e5-87d7-b6cba7c8b084.png)

And then in admin permissions:-

![screenshot_1](https://cloud.githubusercontent.com/assets/12760959/8356031/a3cde70a-1b4a-11e5-904f-73c3fa8dace8.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/12760959/8356181/bd6dd1ce-1b4b-11e5-9e7d-8e66b06b3e6a.png)

How is this post possible as a spammer with admin status which hasn't even initiated a signup?

Please help.

Regards.

Gary

**Comment by gary231178** [comment]
Aah i see they are posting as annonymous but using my admin avatar, still baffled as no signup and hence no option to select a site stored avatar.
Also is this then a bug with userclass perms allowing annonymous posting? As clearly i have it set that only admins can create threads in this section.

**Comment by Moc** [comment]
It has been reported before: https://github.com/e107inc/e107/issues/441
Seems like it's still present.. I haven't figured it out yet.

**Comment by gary231178** [comment]
Wow since posting over 200 spam posts now added in minutes lol.

Guess following bug report #441 will have to make forums non public, which i didn't really want to do. I do have sfs installed also which appears to be doing nothing lol.

**Comment by gary231178** [comment]
Ok hope this helps, but i have narrowed it down with the help of spammers:-
It seems that they can only post in a forum thread that is subject to a Sub forum, well at least they havn't been able to post in any other topics / threads which aren't in a sub forum.
Bug with the sub forum which is set to show to members only is still visible when not logged in publically when this should be hidden, thus allowing spammers to see the thread.
It does then also allow public posting, as i can clearly select new topic and post away without being logged in!!

**Comment by gary231178** [comment]
OK well maybe not, not sure if it was a result of the recent forum fixes on other issues, but it now seems that i can annonomously post without being logged in, in any forum on any topic regardless of whether the topics are set to public / members only.
This applies to creating a new topic and replying to open threads which should only be postable by members.
Only ones i cant see and or post are the admin userclass forums.

**Comment by CaMer0n** [comment]
Please check your apache logs, you should see which script is being hit repeatedly.

**Comment by gary231178** [comment]
Does this help?
 "GET /forum/war-thunder-updates/192-genes-occupying-criteria-lesson-instability-lazy-protocols/&last=1 HTTP/1.0" 200 26239 "http://www.ltnclan.com/forum/war-thunder-updates/192-genes-occupying-criteria-lesson-instability-lazy-protocols/&last=1" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0"

**Comment by gary231178** [comment]
I have overwritten all the files in e107 with the current master.zip but couldn't find any changed files since last updating, so don't appear to have been hacked unless there is an sql injection somewhere which i can't find

**Comment by gary231178** [comment]
More info from error log:-
ltnclan.com [Thu Jun 25 02:04:19 2015] [error] [client 66.249.64.196:46706] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 10:38:39 2015] [error] [client 91.212.124.187:47117] End of script output before headers: forum_viewforum.php
ltnclan.com [Thu Jun 25 10:38:39 2015] [error] [client 91.212.124.187:35859] End of script output before headers: forum_viewforum.php
ltnclan.com [Thu Jun 25 11:35:35 2015] [error] [client 66.249.64.196:46705] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 11:38:36 2015] [error] [client 188.122.41.94:49742] End of script output before headers: index.php
ltnclan.com [Thu Jun 25 12:15:43 2015] [error] [client 66.249.64.206:52127] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 12:28:45 2015] [error] [client 66.249.64.206:50854] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 14:44:36 2015] [error] [client 91.200.12.170:52554] End of script output before headers: index.php
ltnclan.com [Thu Jun 25 14:44:36 2015] [error] [client 91.200.12.170:37470] End of script output before headers: index.php
ltnclan.com [Thu Jun 25 15:25:03 2015] [error] [client 91.200.12.27:52185] End of script output before headers: index.php
ltnclan.com [Thu Jun 25 15:25:15 2015] [error] [client 91.200.12.27:52185] End of script output before headers: error.php
ltnclan.com [Thu Jun 25 15:25:15 2015] [error] [client 91.200.12.27:36384] End of script output before headers: index.php
ltnclan.com [Thu Jun 25 18:38:47 2015] [error] [client 66.249.78.66:33953] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 18:38:58 2015] [error] [client 66.249.78.52:39941] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10
ltnclan.com [Thu Jun 25 18:39:20 2015] [error] [client 66.249.78.59:53039] AH01215: PHP Fatal error:  Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10

**Comment by gary231178** [comment]
Sorry for the many posts, not sure if and how it is relevent but disabling cache removes the ability from posting anonymously. As soon as cache is enabled again allows for annoymous posting. Is this the bug, or am i still subject to a vulnerability somewhere.

**Comment by LaocheXe** [comment]
I had a few issues with cache on my site with CloudFlare enabled as well - Moved to another website host and issues I had I no longer get - plus cache is disabled but still got my CloudFlare enabled.

**Comment by gary231178** [comment]
I'm not using cloudfare, i also have my own reseller webhosting company. I just need to clarify if this is a bug with cache enabled, or if i am still subject to a hack which i need to find and resolve, If its a bug with cache then it may be the answer to bug report https://github.com/e107inc/e107/issues/441 also

The error logs, from what i can make out appear that attackers are trying to acess e107_plugins/forum/e_emailprint.php 

with the following repeated error

Call to undefined method e107forum::thread_get() in /home/sites/ltnclan.com/public_html/e107_plugins/forum/e_emailprint.php on line 10

**Comment by Moc** [comment]
You are not subject to a hack. It's a bug that's causing this spam issue. The caching aspect was not considered before so that's useful new info. 

The fatal error on emailprint is also a bug. Not a hack of any sorts.

I'll look into this issue asap

**Comment by gary231178** [comment]
Cool thanks Moc for the reassurance and speedy response.

**Comment by Moc** [comment]
When you sat that disabling the cache stops the ability to post anonymously, you mean the e107 cache (content or system cache) or on server level? 

Will try to reproduce this issue asap. Once reproduced it should be easy to fix.

**Comment by gary231178** [comment]
Hi it is the system cache (when enabled) allows annonymous posting.

Regards.

Gary

**Comment by gary231178** [comment]
Your changes have fixed my issues.
Once again thank you for the continued development and commitment to the e107 cms, it is much appreciated.

**Comment by CaMer0n** [comment]
Likewise @gary231178 , thank you for the positive feedback and for helping with your bug reports. :+1:
