### ISSUE TITLE
Move thread / post (Forum)

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1079]
Sorry can't confirm if this is a new issue since recent forum updates or already existed because the need hadn't arisen to move a thread.
However I am trying to move a forum thread using the move dropdown via forums, and once selected it gives me the following url:- http://www.ltnclan.com/e107_plugins/forum/forum_conf.php?f=move&id=1
but it presents me with an empty page with just theme background and no physical options to move thread from existing parent to new etc.

Regards.

Gary

![screenshot_8](https://cloud.githubusercontent.com/assets/12760959/8374762/f9c0fc60-1bef-11e5-9f44-f56331e2c897.png)

**Comment by Moc** [comment]
It's a bug. Temporary fix: Go into the topic itself and then select the 'Move' option in the options dropdown of the initial post.

**Comment by gary231178** [comment]
Cheers, that worked :+1:

**Comment by Moc** [comment]
@CaMer0n 

forum_viewforum.php on line 755 needs updating: 
```php
	$moveUrl 		= e107::getUrl()->create('forum/thread/move', "id=".$thread_info['thread_id']);
```

Tried some things but couldn't figure it out.
