### ISSUE TITLE
Login Menu

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1082]
In Login Menu the shortcodes have ids like username, userpass ... . If you use 2 times in the same page the login menu, that page will have many double ids. Please use classes or simple remove the ids.
Another thing is that the shortcode {MENU=login_menu} is not working. It is not ready yet or my syntax is not OK?

**Comment by MikeyGMT** [comment]
Hi mcpeace-maw

I am having similar problems. You may be aware already, but here's a bit of background. There is an effort ongoing to reduce the duplications in LAN files so common phrases like "Login", "User", "Password", "Plugin" and so on are slowly being moved to English.php This will reduce the amount of work in translating the system. Meanwhile it looks like the dev's are standardising the naming conventions. 

For example: 
LOGIN_MENU_L42 
is now 
LAN_LOGINMENU_42

But this means both the LAN files and the code files calling them must match - which as this is a work-in-progress we have both been caught by these changes.  

I need to learn how to do these pull requests and help the dev's in this big task which hopefully will help us all.   

Cheers

MikeyGMT

**Comment by MikeyGMT** [comment]
Aha - found why it is happening in my site. 

I copied Bootstrap3 to my own copy. That contains theme_shortcodes.php 

History shows 

theme_shortcodes.php	txt replaced by system own LANs	10 days ago

So I just tested this solution is :- 

copy theme_shortcodes.php from the repository to your own custom theme.

And the login menu works properly without showing LOGIN_MENU_LXX 

Well I learnt something new today!

Mikey

**Comment by mcpeace-maw** [comment]
There is no connection between the problem I described and the theme. The ids I'm talking about are in login_menu_shortcodes.php file that is in the plugin folder.  username id is at line 75 and so on.

**Comment by mcpeace-maw** [comment]
@CaMer0n if it is OK I'll try to remove these ids and send a pull-request.

**Comment by CaMer0n** [comment]
I think the form-handler may be adding it by default.

**Comment by mcpeace-maw** [comment]
I checked login_menu_shortcodes.php file and are there. First id is username, this input form have also classes "form-control tbox login user", if I remove the id all is OK. I don't thin the id is used in some way.

**Comment by gary231178** [comment]
Would this contribute to https://github.com/e107inc/e107/issues/1077 its a maw theme i am using? Or is this a different issue?

**Comment by mcpeace-maw** [comment]
This is not related with login menu functionality, it is related just with HTML validation issue when you use many login menus in the same page.

**Comment by mcpeace-maw** [comment]
OK, the ids will stay. Only thing is, if you want your page to pass HTML validation, use just one time Login Menu in a page.

**Comment by Moc** [comment]
Out of curiosity, is there a specific case or situation in which you'd want to have the same login menu appear twice on the same page?

**Comment by gary231178** [comment]
Yes they are the best v2 themes i have seen to date. Mobile compatability is flawless, even my google webmaster tools loves it now lol compared to old theme which i would get hundreds of warnings about not mobile compatable etc lol

**Comment by mcpeace-maw** [comment]
My last theme that you can see here: http://mcpeace.x10.mx/e1/news.php have a modal login menu for PC/ wide size screen and an hidden panel on the right side with a login menu in it for mobile. If you try HTML validation will give you many double IDs. I can use a jquery solution but I prefer to have the theme with less js code loaded.
