### ISSUE TITLE
Blog Calendar Menu

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1083]
This menu has some HTML errors. Inside menu caption that is H tag are some divs that give the HTML errors. So in blogcalendar_menu.php file on line 169 the class btn-group is a div and must be changed in a span. On line 170 is the closing tag of class btn-group that need to be also a span. On line 172 is class inline-text that is a div too and need to be changed in span. In this way the menu pass HTML test without errors. Also the tables used inside this plugin must be removed and make the plugin responsive, now is not responsive.

**Comment by CaMer0n** [comment]
Thanks. Sounds like you know exactly what to change. Please send a pull-request of the changes and I'll take a look. Thank you.

**Comment by mcpeace-maw** [comment]
Ok, I just sent the pull-request.

**Comment by CaMer0n** [comment]
Thank you! Does it render the same way in the browser?

**Comment by mcpeace-maw** [comment]
Yes, no visible changes, just the HTML validation is Ok now. 
H tag can have inside just inline tags, span is an inline tag so the validation is OK.

**Comment by CaMer0n** [comment]
Thank you! Committed. :+1:
