### ISSUE TITLE
Forum display icon errors (new)

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1088]
After having uploaded the new changes made for forum an issue is still there

the image says it all.
even changing the cdn from netdna to maxcdn for call does not display..

just to inform (on latest changes)
![newbs](https://cloud.githubusercontent.com/assets/1811857/8392090/06d8f1f2-1cde-11e5-80a1-7430793de989.jpg)

**Comment by mcpeace-maw** [comment]
You need at the top of theme.php :
define("FONTAWESOME", 	4);
and also you need to load font awesome 4.x

**Comment by Moc** [comment]
The next time please continue the discussion in the originally reported issue. They are still monitored and in the case bug is not fixed, it can be easily reopened without losing references. 

https://github.com/e107inc/e107/issues/1085

**Comment by willem010** [comment]
please use default bootstrap icons and leave fontawesome optional.
thnx.

**Comment by Moc** [comment]
They will remain optional for any theme author to use and the scripts are not included by default unless specified by the theme author. In this case Boostrap 3 does make use of the FontAwesome icons.

**Comment by willem010** [comment]
my mistake.. i got the idea those were hardcoded outside the theme.
never mind!

**Comment by willem010** [comment]
being from the "bitneuker" generation (dutch), where we tried to save every bit possible on our (dos) applications .. lol .. i now try to use the same approach when creating sites; every bit we can shave off is a win.

when a site gets millions of hits it really makes a difference ;) 

so it's my mission to keep e107 as lean as possible ;)
