### ISSUE TITLE
TinyMce corrupted image URL when params specified.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1092]
when saving newsitems the following message sometimes appears 

Could not determine format of remote image: %22http://decade-events.nl/site/thumb.php?src=e_MEDIA_IMAGE/2015-06/p004_.jpg&aw=300&ah=0&w=300&h=199%22

the newsitem is saved correctly.. 

it looks like something is trying to add more w and h parameters where there already was an ah and aw specified. 
(btw those h & w parms came from e107, :
i had a user who just used his basic html skills to enter the newsitem, 
user probably pasted a thumb from the site in the newsitem.)

(i already posted about this in another topic, but this doesnt seem related to the other issue at all)

**Comment by willem010** [comment]
it's even adding h & w params to external images now.
when i add an image from facebook using the add image button, 
change to wysiwyg and back, the image url gets the params added.

i think a check for use of thumb.php should be added before changing img url's ?

**Comment by CaMer0n** [comment]
I'm assuming the image was placed in the news item with TinyMce, correct?

**Comment by willem010** [comment]
yep. using the add image button.
