### ISSUE TITLE
html in titles issues.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1099]
low prio issue ?

On some of my sites i use html in news / page / menu titles, 
(to style certain words, add highlights etc. F.I. a news title like this:
 New items in the (span class="highlight" ) Company name (/span) store .. )
i know this probably isnt the best practice, but this used to work ok.. 

on current git it doesnt work as good though. at least 2 issues appear.

first issue : html title tag now is showing the html in the title.. 
so please add a striptags to get rid of those first,

second issue,
where the title is rendered as a link it adds a set of " to many..
html becomes : (span slass=""highlights"" ) 
rendering it useless.

**Comment by CaMer0n** [comment]
Yeah, it was never designed for HTML and never will be. If you really need to do it, then wrap the word to highlight in a character, and then use tablerender() to replace that character with tags to style it.

**Comment by willem010** [comment]
ah yes.. that will work.

thnx
