### ISSUE TITLE
Question about GIT Usage

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1101]
I have created my copy (fork) of e107/master and as I am 19 commits behind. Hence now want to update mine to the latest. Please can you confirm I am in the right screen to do this? I think I need to hit create a pull request - is this correct? I don't want to break the master copy!

![image](https://cloud.githubusercontent.com/assets/2847651/8412493/265ba236-1e82-11e5-85d3-cb5bc7cac7c3.png)

If this is OK, I am hoping to do some work on odd things I find in Lan's?

For example: English/admin/lan_administrator.php refers to Custom when I think we have dropped custom from elsewhere. If I remember correctly, custom page should refer to a user off-system-created php pages. Hence change 
define("ADMSLAN_23", "Create/edit custom pages");
to
define("ADMSLAN_23", "Create/edit pages");

So I'd change that in my copy, test then update my fork. I'll ask what the next stage is :)

Thanks 
Mikey

**Comment by tgtje** [comment]
A) you are in the correct screen . left should be you right should be e107 inc ('sync')
when hitting the create pull you will get another new page (open a pull req..) (notice : at time of adding txt the bottom create button becomes activated to be pushed)  for some info to post  about why etc... (it will run along into your synced master) the next screen (bottom tells about MERGE.. do it !

B) NO edit custom pages is the (if you like) old term for created pages through the admin area.

the offline>  . standalone custom page (which one could see as being 'really' custom (fitted) pages.
Interpretation of custom... 

Noob point of view ; create/edit pages > = 'bundle' okay i can change here everything ? > no.. (follow?)

**Comment by Moc** [comment]
> I don't want to break the master copy!

You will not break it. All pull requests are only merged in when approved by Cameron. The code is reviewed and if changes are needed, he'll let you know.

**Comment by MikeyGMT** [comment]
Thanks folks - done my updates! I did read the GIT articles, but was getting confused by them. I am getting there - baby steps !

Good - we did drop 'custom'. I'll update that one. And progress to the next steps.

Is it true we want to replace HTML tags with BBCodes from the LAN's? I can do some of those too if  agreed.

**Comment by MikeyGMT** [comment]
Sorry for all the questions. 

Thanks Moc - found this too which is very useful https://github.com/e107inc/e107/wiki/Contributing 

Is there a current/common header for the LAN files to be used?

In User>Administrators>Permissions - would it be simpler in the list to use the module or feature name? We know the selection will allow the admin to alter, edit, manage, configured etc For example:

lan_admin.php(231): define("LAN_PREFS","Preferences");
rather than 
lan_administrator.php(22): define("ADMSLAN_19", "Alter site preferences");

At the moment I wont alter any code files, until you and I are happy with my contributions. But I will put in a comment with a suitable global phrase to use. Such as

lan_administrator.php(22): define("ADMSLAN_19", "Alter site preferences"); // LAN_PREFS

Some cases, of course, won't be appropriate for replacement.

**Comment by tgtje** [comment]
My view if i may : 
"Preferences" exists as common term stiil at 4 places ( lan_prefs;adlan;dblan;epl adlan) which probably will/should  be 'redefined' to LAN_PREFS as for singular use ( decrease lan definitions).

However ADSMLAN not conflicting but to the point.

**Comment by CaMer0n** [comment]
@tgtje When you do your search for LANs, you need to ignore commented-out terms. 
eg. 

    lan_admin.php
     // define("ADLAN_4", "Preferences");

**Comment by tgtje** [comment]
It was just a quick answer i broaden it out : Preferences as term is used  : 
E:\WERKKOPIEwc\trunk\e107_languages\English\admin\lan_admin.php
// define("ADLAN_4", "Preferences");
define("LAN_PREFS","Preferences");                                          <<<<<<<<<<

E:\WERKKOPIEwc\trunk\e107_languages\English\admin\lan_db.php
define('DBLAN_96', "Preferences");                                            <<<<<<<<<<<<<

E:\WERKKOPIEwc\trunk\e107_languages\English\admin\lan_plugin.php
define ('EPL_ADLAN_110',"Preferences");                     <<<<<<<<<<<<<<<<<<<<

E:\WERKKOPIEwc\trunk\e107_languages\English\admin\lan_search.php
//define("SEALAN_42", "Preferences");

E:\WERKKOPIEwc\trunk\e107_languages\English\admin\lan_wmessage.php
// define("WMLAN_08","Preferences");

E:\WERKKOPIEwc\trunk\e107_plugins\forum\languages\English\English_admin.php
// define("FORLAN_79", "Preferences");

**Comment by CaMer0n** [comment]
Thank you! Yes, DBLAN_96 and EPL_ADLAN_110 were just updated in my commit today: 
https://github.com/e107inc/e107/commit/be54ccfae4d04a752aac25db28a1ee79da603113

**Comment by Moc** [comment]
Closing this issue as I think the question has been answered. If not, let us know. 

I suggest looking into the new 'Github Desktop' software: https://desktop.github.com/
