### ISSUE TITLE
upload.php fails to load LAN_ERROR_29 from lan_error.php

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1110]
v2 site - never upgraded

Hopefully I did not break this... I am fairly certain I have not changed this part of upload.   

The upload.php is unable to load the LAN_ERROR_29 defined in lan_error.php

![image](https://cloud.githubusercontent.com/assets/2847651/8497780/d1126136-2177-11e5-8baf-b859fc6c0515.png)

Meanwhile before submission ... debug shows 
![image](https://cloud.githubusercontent.com/assets/2847651/8498136/51e27410-217b-11e5-97dc-7c973f851a3e.png)

Table 'xxx_e107v2.e107_download_category' doesn't exist
![image](https://cloud.githubusercontent.com/assets/2847651/8498008/041d4710-217a-11e5-9f5e-aefaf3cfb7b8.png)

I can see 3 category tables. 
![image](https://cloud.githubusercontent.com/assets/2847651/8497926/36be5430-2179-11e5-80ee-e3e38012e368.png)

I can see Media Manager > Create Categories ... is that where it is created ? If so how do we create for uploads as the owner only lists featurebox and gallery?

Here's prefs for uploads

![image](https://cloud.githubusercontent.com/assets/2847651/8498059/67c97266-217a-11e5-8d76-53563140d8c8.png)

**Comment by MikeyGMT** [comment]
OK so I had not installed downloads plugin.

**Comment by MikeyGMT** [comment]
Maybe there is an issue - the error system should still load the message correctly, hence prompt the user to install the Downloads Plugin.

**Comment by MikeyGMT** [comment]
What's upload_ss which seems to be hard coded and not a lan ?

![image](https://cloud.githubusercontent.com/assets/2847651/8498580/853cfa10-2180-11e5-8e59-f86e5bbeac7e.png)

Also the category has not been populated. Hmm - seems a bit odd. Category exists ... 

Should Uploads and Downloads sit in the same plugin, as they are so closely related and interdependent.

**Comment by MikeyGMT** [comment]
Da'h screenshot of course. Changing to LAN_SCREENSHOT

OK you need at least one Parent Category and a Child Category. We need a prompt somewhere to tell the user.

In summary then, I recommend we add some text somewhere to instruct users. I'm thinking instead of the old wiki - can we include text in the screen?

upload.php needs to check if downloads plugin is installed if not return a messages - please install the download plugin before proceeding.

**Comment by MikeyGMT** [comment]
OK so uploading Version 2 of file via uploads.php, is accepted. e.g. charlie.jpg 
Going to Admin>File Uploads to approve> Rejected > File Not Found 
So upload.php should reject if the same filename already exists?

SS and Main Image replaced with LAN_SCREENSHOT in upload.php x2 & Downloads plugin. I've tested that all now. Outstanding then 

* Disable upload.php when download plugin not installed. 
* Maybe merge uploads into the downloads plugin 
* Hint text to ensure a Category and Sub-Category exists for Uploads & Downloads.
* Add link to Submitted Files in Downloads Plugin. 
* Stop files with same name from being uploaded by public uploads
** e.g. Fred could upload myplugin.php and so could John
** Only one of their files would be uploaded

**Comment by MikeyGMT** [comment]
I have done lots of LAN transfers from Downloads and Uploads and am testing. 

I see these notices but cannot seem to clear them up. 

Downloads > Create Mirror. 

Page Title is "Downloads DOWLAN_143"

Notice: Use of undefined constant DOWLAN_128 - assumed 'DOWLAN_128', Line 234 of /home/atlantic/public_html/testv2/e107-master/e107_plugins/download/admin_download.php
Notice: Use of undefined constant DOWLAN_143 - assumed 'DOWLAN_143', Line 234 of /home/atlantic/public_html/testv2/e107-master/e107_plugins/download/admin_download.php
Notice: Use of undefined constant DOWLAN_112 - assumed 'DOWLAN_112', Line 234 of /home/atlantic/public_html/testv2/e107-master/e107_plugins/download/admin_download.php

ALL 3 of these remain defined in English_admin.php ...

define("DOWLAN_143", "Create Mirror"); 

I just cannot seem to get around it. 

Mike

**Comment by CaMer0n** [comment]
Please see my comments in #6 - it will make this process much easier.

**Comment by MikeyGMT** [comment]
If you have only one or two menus, a very quick workaround to this is to ... 

1) Go to Menu's 
2) Copy all Menu contents to a text file or to a page 
3) Delete all Menus
4) Run the update and it will succeed. 
5) Recreate your menus again

**Comment by CaMer0n** [comment]
@MikeyGMT I came across this error message too and have corrected it.

**Comment by MikeyGMT** [comment]
Confirmed - closing
