### ISSUE TITLE
Contact Form - Image Code Not Recognised

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1111]
I have on a test instance rationalised the Lans usage on my fork - but the Image Code is not accepted.

**Comment by CaMer0n** [comment]
Could you elaborate further, which script, where and under what conditions?

**Comment by Moc** [comment]
Just tested and /contact.php is working fine with captcha for me. 

I do get this line at the top of the page though: "Image file not found:". Possibly this is a leftover debug message.

**Comment by MikeyGMT** [comment]
I am away for a week or so - hence reply will be delayed.

**Comment by Moc** [comment]
@MikeyGMT Any updates?
Closing for now, feel free to re-open if this issue is still present.
