### ISSUE TITLE
email@domain.us not being recognized as valid email during signup

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#1114]
Error
12 - Email address - Invalid format for email address: <emailnm>@<domain>.us

Also after trying to complete a new user signup the error Image not found was displayed.  The signup still occurred but the end user would be left with uncertainty.  This is based on latest github from 7/5/2015 AM

Thanks
-D-

**Comment by Moc** [comment]
'test@testdomain.us` seems to work for me, no error saying that email address is invalid. However, I do get a blank page... Needs debugging.

**Comment by Moc** [comment]
More info:

- Able to reproduce the issue on live Linux website: 
blank page with `Image file not found:`

- Not able to reproduce localhost on Windows. 

/cc @CaMer0n

**Comment by dimante** [comment]
Dimante -a- jmgservices.us does not though ...

On Sunday, July 5, 2015, Tijn Kuyper <notifications@github.com> wrote:

> 'test@testdomain.us <javascript:_e(%7B%7D,'cvml','test@testdomain.us');>`
> seems to work for me, no error saying that email address is invalid.
> However, I do get a blank page... Needs debugging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1114#issuecomment-118640522>.
>


-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Still a problem in latest git pull:
Error
12 - LAN_USER_08 - Invalid format for email address: dimante@jmgservices.us

**Comment by dimante** [comment]
Also even when I do a valid signup it comes back with IMg not found...  Puts the user in "Not Verified" status and never sends an email...  We have problems in the signup arena again everyone....

**Comment by dimante** [comment]
Error
12 - LAN_USER_08 - Invalid format for email address: dimante@jmgservices.us

**Comment by dimante** [comment]
Ok now it's just all domains that I can see
Error
12 - LAN_USER_08 - Invalid format for email address: jeannie@dimante.net

Ps those are both valid emails/.

**Comment by dimante** [comment]
SO then I use a .org address that it seems to accept but this is all that is returned to the screen :+1: Image file not found: 

Signups are key to a site like this!  Please help!

**Comment by dimante** [comment]
WHen that message appears the user gets placed in the database as unverified but the email never gets sent...

**Comment by CaMer0n** [comment]
@dimante, are you willing to provide an admin  login (perms 0) and FTP access to your site, so I can take a look? If so, please login at e107.org/developers and send me a message via the contact page.

**Comment by CaMer0n** [comment]
@dimante Please update, run the upgrade and try again. Thanks

**Comment by dimante** [comment]
Will do!

On Friday, August 21, 2015, Cameron <notifications@github.com> wrote:

> @dimante <https://github.com/dimante> Please update, run the upgrade and
> try again. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1114#issuecomment-133545324>.
>


-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Ok so we had some forward progress.. It accepted the domain but upon submission the screen showed this alone:

Image file not found: 

And did not send the confirmation email..  So something is still broken.
-D-

**Comment by dimante** [comment]
Current GIThub pull this matter is resolved.!
