### ISSUE TITLE
When editing downloads the description text is not showing...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#1115]
When editing previously added downloads the description text flashes for a second then disappears...

-D-

**Comment by dimante** [comment]
Just updated to latest GIT and this is still an issue.  I cannot edit my download text!!!

**Comment by CaMer0n** [comment]
@dimante It displays just fine for me. Is it possible you have wysiwyg active or tinymce running, but failing to load? (please check for js errors in the browser)

**Comment by dimante** [comment]
I have never enabled tinymce but the errors support your statement...

GET http://www.<site>.net/e107_plugins/tinymce/plugins/e107bbcode/plugin.js
e @ tinymce.min.js:5(anonymous function) @ tinymce.min.js:5a @
tinymce.min.js:2r.loadScripts.h @ tinymce.min.js:5r.loadScripts @
tinymce.min.js:5r.loadQueue @ tinymce.min.js:5t @ tinymce.min.js:11N.render
@ tinymce.min.js:11r @ tinymce.min.js:11(anonymous function) @
tinymce.min.js:11a @ tinymce.min.js:2a @ tinymce.min.js:11i @
tinymce.min.js:2m @ tinymce.min.js:2o @ tinymce.min.js:2
tinymce.min.js:5 Failed to load: http://www
.<site>.net/e107_plugins/tinymce/plugins/e107bbcode/plugin.js

How do I turn it off?

On Wed, Jul 15, 2015 at 7:33 PM, Cameron <notifications@github.com> wrote:

> @dimante <https://github.com/dimante> It displays just fine for me. Is it
> possible you have wysiwyg active or tinymce running, but failing to load?
> (please check for js errors in the browser)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1115#issuecomment-121789373>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Agreed.  I removed the tinymce folder and it is good now..  How do I know when you get rid of a directory>?

**Comment by CaMer0n** [comment]
it was probably the e_meta.php file. Only way to know is to use git. I'll add a check for it in admin.

**Comment by dimante** [comment]
THanks!

On Wed, Jul 15, 2015 at 9:32 PM, Cameron <notifications@github.com> wrote:

> it was probably the e_meta.php file. Only way to know is to use git. I'll
> add a check for it in admin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1115#issuecomment-121805920>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*
