### ISSUE TITLE
Issue: Plugin Not Showing

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1116]
After doing plugin builder for a plugin I am working on - has no sql.php (using just the prefs) - it makes everything but will not show up under Installed Plugins or Not Installed plugins section - I did a Scan plugin directories and can see it there but no where on the list.

**Comment by CaMer0n** [comment]
You might want to check that plugin.xml is valid XML.

**Comment by LaocheXe** [comment]
https://gist.github.com/LaocheXe/dc791ab1604f0b411172

Looks in order to me, plus I did not change the generated plugin.xml

**Comment by LaocheXe** [comment]
While looking at my first plugin and this one I notice that I had menu selected in the plugin.xml - i switched it to tools and now it shows.
