### ISSUE TITLE
Issue: Invalid argument e107_handlers/admin_ui.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1118]
Get a 
Warning: Invalid argument supplied for foreach(), Line 3484 of /usr/www/webmc/defiantz/e107_handlers/admin_ui.php

While in admin preferences area of a plugin using dropdown menu. (Nothing is shown at a drop down menu item

**Comment by CaMer0n** [comment]
The dropdown menu requires some writeParms data. Without it, you will see errors like that.

**Comment by LaocheXe** [comment]
I removed the dropdown menus and still get this error

**Comment by CaMer0n** [comment]
@LaocheXe Is this one still an issue?

**Comment by Moc** [comment]
Closing due to lack of feedback, please let us know if this is still an issue using the latest files.
