### ISSUE TITLE
Question: 3rd Party Code = Fatel error

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1122]
Months ago I used the PHP Framework for TeamSpeak 3 to call up the server view, it worked. Few days ago I tried another code for a new plugin that I am working on. This code is a widget, made a few years ago and it works without modifying it.

I went and made it into a ShortCode - and made no changes to one file, the Simple HTML DOM - https://gist.github.com/LaocheXe/aa797412281d835e54ac

When I tired to use the Shortcode on a custom page, I got this error: Fatal error: Call to a member function innertext() on a non-object in /usr/www/webmc/defiantz/e107_plugins/swtorss/simple_html_dom.php on line 871

Now thinking about it there could be a few reasons for this. A. the shortcode isn't getting the vales correctly from the plugin prefs, B. the Simple HTML DOM has an issue with e107 code, C. i am as dumb as a bucket.

This is what I am trying to do for this plugin, allow the admin to select what server he wants to show the server status of for the MMORPG Star Wars The Old Republic using the Simple HTML DOM to cache the server status page that SWTOR has.

Here is the Shortcode - https://gist.github.com/LaocheXe/320b2d6f4504f6a568dc
Here is the widget - https://github.com/dankraus/Star-Wars-The-Old-Republic-Server-Status-Widget

**Comment by LaocheXe** [comment]
I went and did a few test.

http://defiantz.org/page.php?id=15 <-- Shortcode page

http://defiantz.org/e107_plugins/swtorss/swtor-serverstatus.php <-- No shortcode

http://defiantz.org/e107_plugins/swtorss/swtor-server-widget.php <-- default code

http://defiantz.org/e107_plugins/swtorss/swtor-server-widget-test.php <-- default code with

When using require_once('../../class2.php'); - I get the error

**Comment by tgtje** [comment]
Just a comment ( i just mention it) based on a 4 year old software (if it works;it works) but the age of the simple html dom php ? the latest is version 1.5 rev 210... it is php.. and php changed a lot in 4 years (so did the file + 300 lines) ???
For the rest i can not help..

**Comment by LaocheXe** [comment]
I downloaded the latest version of simple html dom php (v1.5) and still works, just not with e107

**Comment by tgtje** [comment]
Did some reading up on the posts you made : i do not know where i read it, but was to place and call simple dom outside .. instead of a include a require_once (folder/dom ...) ?  if it has any influence but it seemed identical  behaviour (who knows?)

**Comment by Jimmi08** [comment]
Is there a way how I could test this?  Your $plugin_pref are from some form - because $_POST? Did you tried to echo/print_a values of $plugin_pref. SHD has some debug function, if I remember correctly.
I used SHD in menu (not page as you) for testing, but not as shortcode, I had included file with class (originaly e_cron) and later I used it in cron.

Yes, just checked, I have included simple_html_dom.php ouside class, something like this:

if (!defined('e107_INIT')) { exit; }
include_once(e_PLUGIN.'featurebox/simple_html_dom.php'); 
class featurebox_cron // include plugin-folder in the name.
{
	public function __construct()
	{$this->weburl ="..."; }

... rest of code...
}
But I don't used OOP version of SHD...

**Comment by LaocheXe** [comment]
Here is the github for the plugin I am working on

https://github.com/LaocheXe/SWTOR-Server-Status

**Comment by Jimmi08** [comment]
Thank you. So for now:
- your preferences are read correctly
- your simple html dom object is different in swtor-server-widget.php and swtor-server-widget-test.php. I suppose it's related to this http://stackoverflow.com/questions/5301432/simple-html-dom, something with "You cannot concatenate DOM document elements"
So after changing your part with loading and saving  with this:

include_once('simple_html_dom.php');
$mylocalfile = e_PLUGIN."/swtorss/".$cache_file_name;
//echo "url: ".$mylocalfile;
$data = file_get_html($mylocalfile);
if(!$data)  {  	print_a("Couldn't read local file"); die;	}

I got it works.  So you can't use SHD object inside e107 and you need to solve reading from online server (or saving it before using file_get_html)

Try and let me know. I used  e107::getFile()->getRemoteFile() for this before and put it in temp directory for site'safety with hash (like download plugin works). But it's six months, but I vague remember that it doesn't work on localhost. I am sure I will need this in future, so if I can help, let me know.

**Comment by LaocheXe** [comment]
@Jimmi08 - It be nice for help, since I did this: http://defiantz.org/e107_plugins/swtorss/swtor-server-widget-test.php

Some how the website for swtor loaded up - I did something wrong lol - however you are right, I got it to work in some degree - I already had a cache file in the directory - and it showed up, but after deleting it to see if I can get the save_file or getFile I ended up getting a webpage lol

**Comment by Jimmi08** [comment]
I am overloaded with translating, so doing something different can help me. There is in that plugin your email, can I write you? 
PS. Yesterday there were 3500 missing phrases, now I have 5400 errors! I couldn't believe when I saw it.  I would cry. So, yes, I will try help you.

**Comment by tgtje** [comment]
@Jimmi08  not for the issue : translation : simple help > if blank pages > coding error ( usually double quotes vs single  or both in file) eg Editor Colour ; editor : green = fine black = error (go to where it starts) ;-)

**Comment by Jimmi08** [comment]
Yes, I know... I didn't get error. Just after hours I left yesterday with cca 3500 strings (after verification), today I continued and after verification I got 5400 errors. OK, problem with SHD solved as I hope, go back to translating.
