### ISSUE TITLE
verify lang pack - just information

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1127]
This error was able to get through verification of lang pack as correct:

![image](https://cloud.githubusercontent.com/assets/5429548/8633583/a566df9a-27cf-11e5-83b8-43c9b68c9ebb.png)

and cause parse error:
![image](https://cloud.githubusercontent.com/assets/5429548/8633584/b45be072-27cf-11e5-8663-1dc2a9e76d14.png)

![image](https://cloud.githubusercontent.com/assets/5429548/8633586/cc01fff4-27cf-11e5-8a29-b93b55d2a7de.png)

**Comment by Jimmi08** [comment]
Closing, I probably didn't remember correctly that this was checked in version 1.

**Comment by Jimmi08** [comment]
Next mistake missed by verification:

![image](https://cloud.githubusercontent.com/assets/5429548/26628952/88beefee-4600-11e7-820c-c636c54a0729.png)

**Comment by CaMer0n** [comment]
Needs to be modified to use [x]

**Comment by Jimmi08** [comment]
This is changed already.
