### ISSUE TITLE
hardcoded menu name - contact/contact_menu.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1128]
$ns->tablerender("Contact Us", $text, 'contact-menu');

It uses: e107::lan('core','contact');

but there is this string: 
define('PAGE_NAME',     'Contact Us'); 

not special string for this.

Could you add something like LANCONTACT_00 to solve this?

**Comment by tgtje** [comment]
You could use ( create a fictious LAN define like that, but i asked the same question this morning (about 4 hours ago) for more of those 'captions' #6 
My guess they come from within def.install xml  however for the menu itself a new lan would be sufficient (should be in MAIN language file ! to work)
