### ISSUE TITLE
hardcoded "by" in news/templates/news_template.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1129]
I found next hardcoded string. And I didn't find similar strong in lanquage's files.
       
   <p class="lead">by {NEWSAUTHOR}</p>

**Comment by tgtje** [comment]
list #6

**Comment by tgtje** [comment]
Question : (as i can still see 'by' ) would it be needed to change the folowwing piece too ?
$NEWS_TEMPLATE['default']['item'] = '
		{SETIMAGE: w=900&h=300}
		<h2>{NEWSTITLELINK}</h2>
          <p class="lead">by {NEWSAUTHOR}</p>    <<< around line 86

**Comment by tgtje** [comment]
just noticed all fixed in a5246a31a3b8b1122581bc0b934796dfd6ce78dd (08-22)

**Comment by CaMer0n** [comment]
yes, thank you for sharing! :+1:
