### ISSUE TITLE
hardcoded "none" in code

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1130]
news_shortcodes.php:
	return "None";

e107_plugins/list_new/list_news.php
		$list_display = (vartrue($this->parent->settings['open']) ? '' : 'none');

**Comment by tgtje** [comment]
list #6

**Comment by Jimmi08** [comment]
correct path: e107_plugins/list_new/section/list_news.php

Sorry, that issue has so many entries, this way I am able to track my changes to code with next update. Frontend is important than solving all strings at once.

**Comment by tgtje** [comment]
It ( suppose list in 6) is just a a txt based list showing a lot of terms existing as doubled throughout; it is not complete and is still (if you like) a work in progress. Some of the terms in there are already 'treated', but not all..
