### ISSUE TITLE
TinyMce editor size issue on usersettings page. 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1132]
Hi,
fresh instalation today. Tinymce editor is too narrow:

![image](https://cloud.githubusercontent.com/assets/5429548/8634925/e04d2c84-280d-11e5-86b8-a5465601cea3.png)

**Comment by CaMer0n** [comment]
@Jimmi08 could you please tell me which page/script you are on and which theme you are using? thank you!

**Comment by Jimmi08** [comment]
Fresh install. bootstrap 3 , /usersetting.php (frontend)  If you need more info, let me know.
