### ISSUE TITLE
sc_logo - question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1133]
I am just curious if there is some reason for this, but you use width and height in pixels along with img-responsive bootstrap class. And if I use just {SITELOGO} with too large image, it uses full dimensions and it brokes layout.  

![image](https://cloud.githubusercontent.com/assets/5429548/8636863/54e63842-2877-11e5-80ed-5181ee88fe80.png)

Code is from e107_plugins/siteinfo/e_shortcode.php

Thank you

**Comment by CaMer0n** [comment]
Not everyone uses bootstrap. We should probably add a check for Bootstrap in there and remove the 'style' when in use.
