### ISSUE TITLE
Feature: e107::url() modification to support query parameters

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1139]
I did some modifications on the url() method of e107 class so now, it supports the query parameters. Using:

```
e107::url('plugin', 'list', $row, null, array('foo' => 'bar'));
```

If SEF URLs are enabled, it generates URL like this:

> something/path/key?foo=bar

... if disabled:

> something/path.php?id=key&foo=bar

I push my changes soon, and if you are satisfied, I create a pull-request.

**Comment by lonalore** [comment]
Now, it supports hashtag too. Using:

```
$options = array(
	'query'    => array(
		'foo' => 'bar',
	),
	'fragment' => 'hashtag',
);

e107::url('plugin', 'list', $row, null, $options);
```

If SEF URLs are enabled, it generates URL like this:

> something/path/key?foo=bar#hashtag

... if disabled:

> something/path.php?id=key&foo=bar#hashtag

**Comment by lonalore** [comment]
I modified index.php because the query parameters were not appended to the "new location" path, so the $_GET variable only contained the the query parameters are defined in the "redirect" path in e_url.php

so in this case: something/path/key?foo=bar
I got only: {e_PLUGIN}qna/questions.php?id=key
instead of: {e_PLUGIN}qna/questions.php?id=key&foo=bar

**Comment by CaMer0n** [comment]
@lonalore Did you take a look at 'legacy'? (see forum/e_url.php) - it achieves the same thing to a large extent.

**Comment by lonalore** [comment]
I tried everything, but in the $_GET variable I only got the query parameters are defined in the "redirect" path. I want to make a simple pager with SEF URL..

this is my SEF implementation in e_url.php:
```php
$config['questions_by_category'] = array(
	'regex'    => '^qna/questions/(.*)$',
	'sef'      => 'qna/questions/{qna_sef}',
	'redirect' => '{e_PLUGIN}qna/questions.php?c=$1'
);
```
The requested URL is: 
> qna/questions/core/?frm=1

and dumping the $_GET variable I only get this:
> array(1) { ["c"]=> string(11) "core/?frm=1" }

I think, I should get something like this:
> array(2) { ["c"]=> string(4) "core" ["frm"]=> int(1) }

What do I do wrong? o.O

**Comment by CaMer0n** [comment]
Your regex is incorrect. Try this: 

        'regex'    => '^qna/questions/core/(.*)$',

**Comment by lonalore** [comment]
But in your example, the "core" is hardcoded and fix. It should be dynamically, because it's a category.

**Comment by CaMer0n** [comment]
How about this?

    'regex'    => '^qna/questions/(.*)/(.*)$',
    'redirect' => '{e_PLUGIN}qna/questions.php?type=$1&c=$2'

**Comment by lonalore** [comment]
Yes, this can be a good solution! But the main problem is that, the query parameteres are not passed to the "redirect" location. 

Another example: If I append a campaign ID to an URL in eDM:

> somethingurl/qna/questions/foo/bar?CID=XYZ

and if I use your solution:
```
'regex'    => '^qna/questions/(.*)/(.*)$',
'redirect' => '{e_PLUGIN}qna/questions.php?type=$1&c=$2'
```

...I only get the "type" and "c" parameters, because the $_GET variable only contains the parameters from "redirect" URL. And I can not get the "CID".

**Comment by CaMer0n** [comment]
Something like this (untested): 

     'regex'    => '^qna/questions/(.*)/(.*)\?(.*)$',
     'redirect' => '{e_PLUGIN}qna/questions.php?type=$1&c=$2&$3'

I use a similar solution in the forum plugin's e_url.php for 'topic'

**Comment by lonalore** [comment]
Seems to be good, I try as soon as I have time. Thank you!
And what about my first two commits (extended functionality of e107::url(): support for query parameters and fragment)? :) I think it's more elegant solution than appending query parameters to the generated url. You do not have to care for the right way to append parameters.

**Comment by CaMer0n** [comment]
Sounds good! Perhaps you can made the 4th param the $options? 

    e107::url('plugin', 'list', $row, array('mode'=>'abs', 'foo' => 'bar'));

And then inside: 

    if(is_string($options)) // backwards compat. 
    {
        $options['mode'] = $options; 
    }
    elseif(empty($options['mode']))
    {
         $options['mode'] = 'abs';  
    }

Know what I mean?

**Comment by lonalore** [comment]
I collected all of my changes into my last commit. The rest is removed. If you think that is acceptable, then I create a pull-request.

**Comment by CaMer0n** [comment]
Merged. Will close this issue now.
