### ISSUE TITLE
hardcoded Search in Book/Chapter page plugin e_search.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1141]
Hi,
hardcoded string. 
'text' => "Search in Book/Chapter"

![image](https://cloud.githubusercontent.com/assets/5429548/8697699/76be7b3c-2af7-11e5-8f83-b8852c0cf122.png)

**Comment by tgtje** [comment]
Nice find ;-) would be a candidate for a LAN, 
I have to test Git anyway so i make a commit.
Thanks..

**Comment by tgtje** [comment]
As mentioned above : it is solved, can be tested and closed ?

**Comment by Jimmi08** [comment]
With next site. I am not able to test it now. Sorry
