### ISSUE TITLE
Tinymce 4 not saving text.

### ISSUE THREAD

**Issue by jdarbyshire** [e107inc/e107#1155]
Similar issues to #1035 except in trouble shooting removed TinyMCE4 plugin and problem stopped. 
System - fresh GIT Clone install.  
Server Centos 6 dedicated server.
Sympton: when editing Welcome Message, on Save with TinyMCE4,  the system returned  
System Information
Nothing updated as no changes were made.
Monitored the DB field
Added data with TinyMCE - correctly saved as [html]Hello, Hello[/html]
Opened with TinyMCE installed - and saved - field in DB was blank.  
Removed TinyMCE plugin and issue stopped.  
e107 
Version 2.0.0 (git) 

Security level 
[5] Balanced 

Site Theme 
bootstrap3

Admin Theme 
Bootstrap 3 v1.0 by e107 Inc (2013-12-25)

Install date 
Tuesday 21 July 2015 - 05:21:42 

Server 
Apache
(host: www.darbysys.com) 

PHP Version 
5.3.3 

MySQL 
5.1.73
Database: e107bs 

Charset 
utf-8 

Server Time 
Thu, 23 Jul 2015 13:42:57 -0700

**Comment by CaMer0n** [comment]
You probably had an old e_meta.php file in the plugin's directory.

**Comment by jdarbyshire** [comment]
Thank you for the fast response.

Not in tinymce 

?>[root@u*******e107bs]find . -name e_meta.php
./e107_plugins/rss_menu/e_meta.php
./e107_plugins/log/e_meta.php
./e107_plugins/tagwords/e_meta.php
./e107_plugins/trackback/e_meta.php
./e107_plugins/forum/e_meta.php
./e107_plugins/faqs/e_meta.php
[root@u***********e107bs]# 

Can these be deleted? Or do I need to find newer version?

**Comment by jdarbyshire** [comment]
Bit more detail
find . -name e_meta.php -exec ls -sl {} \;
4 -rw-r--r-- 1 root root 1639 Jul 23 14:26 ./e107_plugins/rss_menu/e_meta.php
4 -rw-r--r-- 1 root root 3417 Jul 23 14:26 ./e107_plugins/log/e_meta.php
4 -rw-r--r-- 1 root root 598 Jul 23 14:26 ./e107_plugins/tagwords/e_meta.php
4 -rw-r--r-- 1 root root 454 Jul 23 14:26 ./e107_plugins/trackback/e_meta.php
4 -rw-r--r-- 1 root root 331 Jul 23 14:26 ./e107_plugins/forum/e_meta.php
4 -rw-r--r-- 1 root root 48 Jul 23 14:26 ./e107_plugins/faqs/e_meta.php

**Comment by jdarbyshire** [comment]
punched close in error...

**Comment by CaMer0n** [comment]
You need those e_meta files. I was referring to the tinymce4 folder.

**Comment by jdarbyshire** [comment]
No more ideas?  I was using e107 pre-bootstrap.

**Comment by CaMer0n** [comment]
@jdarbyshire please update from github, clear browser cache, and test at least a few times.

**Comment by CaMer0n** [comment]
Sorry, this hasn't fixed it. This problem seems almost random. :/

**Comment by CaMer0n** [comment]
@jdarbyshire I am able to reproduce this with Firefox, but not Chrome. Also, are you testing on a local machine or remote machine? Linux or Windows?

**Comment by CaMer0n** [comment]
TinyMce bug - Firefox specific: http://www.tinymce.com/develop/bugtracker_view.php?id=7655
