### ISSUE TITLE
all avatar are 'not in use'

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1156]
sorry for my english.....

in the image.php i changed for me in line 1932
from:
$fileName = basename($image_name);

to:
if (substr($image_name,0,8) != "-upload-") {
   // $fileName = basename($image_name);
   $fileName = "-upload-" . basename($image_name);
}

thx René

**Comment by CaMer0n** [comment]
@schlrech You may also submit pull-requests. This will make adding your fixes much quicker!

**Comment by CaMer0n** [comment]
@schlrech Please update and let me know if this fixes it.

**Comment by CaMer0n** [comment]
Closing, but please re-open if it appears again.
