### ISSUE TITLE
Calender(usersettings) missing glyphicons and date-format is wrong for german

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1157]
in the picture you see the missing glyphicon left and right for bootstrap3 datetimepicker-function (yellow marked) and the date is not in German format
e.g. 30.06.1966

![date](https://cloud.githubusercontent.com/assets/1758577/8873224/ae2eb7b2-3204-11e5-8f3e-6dad631cc40b.png)

**Comment by CaMer0n** [comment]
@schlrech This should now be fixed. Could you please check? Thank you.

**Comment by schlrech** [comment]
The name of the months are correct now,.
The format of the date is not correct.
At the moment English and German are in the same format: 1966-06-30 
in German the date must be like this: 30.06.1966

A new problem accured: in chrome there is no calander popup, firefox and Internet explorer are ok

Thank you

**Comment by schlrech** [comment]
ok, i see also the calender in chrome, but is on wrong position

![image](https://cloud.githubusercontent.com/assets/1758577/8926398/b375b988-350f-11e5-97cc-fdf68ca66db7.png)

**Comment by schlrech** [comment]
The wrong vutton(close) clicked, sorry

**Comment by CaMer0n** [comment]
Please check your 'date' settings under Admin -> Preferences. "Date Input".

**Comment by schlrech** [comment]
its only in the birthday field in all other is the date correct

![image](https://cloud.githubusercontent.com/assets/1758577/8938276/f7f47a2e-355d-11e5-85e1-7126ae0e0313.png)

This is my plugin with e107
![image](https://cloud.githubusercontent.com/assets/1758577/8938298/2326c684-355e-11e5-88ca-371466301be7.png)

my code:
<td>" . $frm->datepicker("Event_Date", vartrue($datum) ? $datum : time()+86400, array('size'=>10,'class'=>'tbox e-time','type'=>'date','format'=>'dd.mm.yyyy','required'=>1)) . "</td>

**Comment by Jimmi08** [comment]
I confirm this issue for extended field Birthday (latest version from github)
- wrong position, wrong date format
![image](https://cloud.githubusercontent.com/assets/5429548/9533175/94e8db30-4d10-11e5-9872-72727db65b6c.png)
![image](https://cloud.githubusercontent.com/assets/5429548/9533190/aa118f3e-4d10-11e5-948a-b4286121b661.png)

**Comment by Moc** [comment]
Using the latest files, this should now be fixed. Please re-open in case the issue persists.
