### ISSUE TITLE
Admin-Area - Bootstrap3 - select all

### ISSUE THREAD

**Issue by Radzi0** [e107inc/e107#1159]
Hi

I found that select all i admin area is not working.

![admin](https://cloud.githubusercontent.com/assets/10882348/8895785/157accde-33e6-11e5-9241-764e83567da8.jpg)

**Comment by Jimmi08** [comment]
I can't confirm this for List News and Pages. I have no Submitted news.

**Comment by Radzi0** [comment]
I have the same issue with users, failed logins, etc.

**Comment by CaMer0n** [comment]
I'm sorry, but I'm unable to reproduce this. Could you please check for javascript errors and make sure you're using the latest files from here on Github?

**Comment by CaMer0n** [comment]
@tgtje Are you able to reproduce this issue?

**Comment by Radzi0** [comment]
Fresh instal - github files resolved this problem.
Git - 08.08.2015 - 10:44

Had the issue, after updating older files, now its fine.

**Comment by tgtje** [comment]
Sorry bit late on answer ,  can not replicate at this point.

Since i already updated with new files i can only support Radzi's latest 
post.
Overall the select all function works.. ( on those pages it is in use) :+
