### ISSUE TITLE
autoload jquery - to be able to choose jquery version, suggestion

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1160]
After some time updated to last version. Only problem was that my theme need 1.8.3 jquery version (for masonry script), it has problem with 2.1.1. 

Error was caused this: It appears as though jQuery 1.9 and later does not have the jQuery.event.handle property.

I am not able to correct this (I will contact theme author) but maybe to add functionality to choose jquery version in admin area would be good idea. 

And sorry for maybe stupid question, but this is related to e107 or my browser? I didn't see it before update:
![image](https://cloud.githubusercontent.com/assets/5429548/8899848/ef6cac70-3439-11e5-8da7-12c094843135.png)

Thanks.

**Comment by tgtje** [comment]
Q : extension in Chrome throws it ..... which one ???

**Comment by Jimmi08** [comment]
I have no idea. I just noticed it, I don't know how to find it. But it's not probably e107 related, I saw it on wordpress site with bootstrap too.

**Comment by tgtje** [comment]
Do not mind unless it happens often, than you should disable the extensions one by one to see which one it is..

**Comment by willem010** [comment]
file location should be optional too.. 
not just the version.

(in a previous git you guys referred to a server which took ages to load.. )

but in some way it already is : 
i have disabled autoloading, and use a manual load from local server using the theme.php

reducing domain calls, using my own cdn. which is faster and i'm sure there are no version conflicts.
google and gtmetrix like this better then using an bootstrap from another server anyway.

**Comment by Jimmi08** [comment]
Do you disable autoloading in admin area (set jquery OFF) or manually in code? If I did this in admin area, there were problems with gallery plugin (or scripts with jquery parameter)
Did you try put jquery in footer too?  This should be optional too.

**Comment by willem010** [comment]
i did it using the admin section, just autoload for admin.

i did have some conflicts in jq, but i solved those using a version on my own server instead.
(preventing to load different versions at once)

yep.. it should load in footer..
