### ISSUE TITLE
e_dashboard not working

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1161]
I changed the code for me as follows

i changed in the file admin_shortcodes.php at the line 1154 from:
$configs = e107::getAddonConfig('e_dashboard','status');
to:
$configs = e107::getAddonConfig('e_dashboard',"",'status');

**Comment by schlrech** [comment]
the same at line 480
from: $configs = e107::getAddonConfig('e_dashboard','latest');
to: $configs = e107::getAddonConfig('e_dashboard','','latest');
thx

**Comment by schlrech** [comment]
or you change the function itself
from:
public static function getAddonConfig($addonName, $className = '', $methodName='config', $param=null ) 

to:
public static function getAddonConfig($addonName, $methodName='config', $className = '',  $param=null )

**Comment by CaMer0n** [comment]
Thank you!
