### ISSUE TITLE
[Little Doubt] Image of userclass in chatbox

### ISSUE THREAD

**Issue by zekss** [e107inc/e107#1166]
Hi everyone, i've created a new userclass and I uploaded an image to this class. My doubt is how can i achieve that the image appear on right side of the username on chatbox?

And two questions more (sorry):

Still serves: "check_class(USERCLASS)" for check the user class before assigning other class?
And, how can i set this class to an user with PHP code?

That's all. Thanks!

**Comment by Moc** [comment]
> how can i achieve that the image appear on right side of the username on chatbox?

This requires writing a new shortcode which checks the userclass of the user that is posting, retrieves the correct image associated with the userclass, and displays this image next to the username. I can try to give it a shot but it may take some time. Send me an email on e107@tijnkuyper.nl and I'll see what I can do. 

> Still serves: "check_class(USERCLASS)" for check the user class before assigning other class?

Yes, this has not changed in v2 (use userclass ID number or the userclass name)

> And, how can i set this class to an user with PHP code?

I don't understand this question, could you please verify?

**Comment by zekss** [comment]
Aaa.. I see, it's more complicated than I believed haha. I don't know how to quote, so, I answer your latest question. What I try to ask there is the following: With "check_class(...)" I verify the userclass, right? So, if with "check_class" I check the userclass, with which instruction/command like this (check_class) I set in a user an userclass? First of all, exist an instruction like this?. I hope you will understand better my question. I'll send you an email but not to do the job, only to guide me. I hate to bother. Thank you very much!

**Comment by Moc** [comment]
Is this issue still relevant? If yes, please let us know what you need help with :)
