### ISSUE TITLE
Question: How to have select element with "multiple" attribute in plugin admin

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1167]
Sorry if I'm missing something obvious, I can't seem to find how to add "multiple" to a select element on  a plugin admin page. Have tried to find a plugin with this to copy but can't locate one.

**Comment by CaMer0n** [comment]
writeParms => array('multiple'=>1);

**Comment by pricey1981** [comment]
thanks, knew it would be something simple, I was trying 'multiple'=>'multiple'!!

**Comment by CaMer0n** [comment]
You're welcome :+1:
