### ISSUE TITLE
Bug: LAN_HEADER_04

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1171]
After using the sync with github - the finished page title (header - or for firefox tab title) gets a missing LAN for LAN_HEADER_04

**Comment by CaMer0n** [comment]
@LaocheXe  Thanks. On which page does this occur?

**Comment by LaocheXe** [comment]
Was in db.php as in e107_admin/db.php?mode=github

Just did the sync again and no longer see the LAN_HEADER_04 - must have been fixed and I had out dated code.
