### ISSUE TITLE
Enhancement: Tinymce media

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1173]
Media plugin ; adds the ability to add HTML5 video and audio elements to TinyMCE.
Although ( in non wysiwig mode) html5 video tag is supported, tiny refuses; or mis-lables as incorrect mimetype... (adding the videotag (html5) into tiny windows will result in not working on present version)

**Comment by CaMer0n** [comment]
@tgtje is this still an issue?

**Comment by tgtje** [comment]
Yes partially, html 5 can only (for actual displaying) be put inside the 
source code 'mode'.
It will not function by plain adding the code in window itself.

furthermore : when using an own uploaded file (example movie), i can NOT 
use the link created by mediamanager >

format >  {e_MEDIA_VIDEO}  2015-09/  jki.mp4   (added spaces) is refused.

has to be manual adjusted to be > 
/e107_media/0bd6f9d0b9/videos/2015-09/jki.mp4

courtesy © Disney Pixar
© Disney Pixar

**Comment by tgtje** [comment]
Been a while, and kept experimenting. Update.
Html 5 video is possible in 'plain' and tiny editor window..
There's only the html 5 element to use.  (not in combination with capabilities of different browsers in use):

In short : as long as html 5  element  **_<  video  scr_**... is used a lot is possible.
As most (at least very often) is mentioned (to use in html 5) the tagging for < source  scr...) this will not be a possibilty  > source (as term) is stripped eg will erase the code following).   

As for the paths : these are now correct for use (own uploaded files) can be called through media manager  (as copy of id url path that is), but ONLY added using embed function (edit/insert video)  in which case the html 5 elements have to be correct . 
The general bar  (edit/insert) will (media url) will 'post' a screen in editor, but only the movie çontrols' (no actual movie itself).
So yes own uploaded movies can be used.. one just has to know the tag/element to use and in present state only as 'embed'.

**Comment by CaMer0n** [comment]
@tgtje Tinymce has changed a lot since this issue was posted. Is this still an issue?

**Comment by tgtje** [comment]
Partially it is. It comes down to what the end-user wishes to use as 'post code' for displaying 'his/here' idea/product. (_overall simplified use for ALL users, not just me_)

Since using html 5 ; responsisve and moreover the new browsers (and build in thingies) it comes more to having the exact piece of posted code. e107 (tiny or bb/plain) can handle a lot now, but still not all.

The issue/enhancement MIGHT be in the premium media plugin part (which e107 does not use as being open source and alike) but even that i am unsure of. No sure if tiny will be or have a solution for this..

I proposed the enhancement as a possible method to use (versatile) to use and embed different ways to use media in accordance to what the browsers 'wishes' to display and are capable of doing. But i think we have to wait or find another way to have a basic formula of input that does what one can use.
For myself i found different methods and possibilities, but _one that suits all. helas_..

We can close this post, and keep it in our mind as i do not see a real solution to the 'problem on a short term. Hence an actual enhancement which not only is applicable to e107...
Feel like closing?  please do so; as stated before : future... (but might take very long.)

**Comment by CaMer0n** [comment]
Opening because audio and video file handling could be improved.

**Comment by tgtje** [comment]
In combination as they seem quite the same i close this issue, there is a working method : related to #3793
