### ISSUE TITLE
LAN_TAG_MENU_2 bug

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#1175]
Where-
e107_plugins/tagwords/admin_tagwords_config.php

Status:
I see follow information-
menu caption    ---LAN_TAG_MENU_2

Is bug?

**Comment by tgtje** [comment]
NO not a 'real' bug it is interchangeable. As long as you leave it there the system's lan definition is called (Tagcloud) or equivelant in user language.

You may change it with a title or alike to use as a caption. That way it overrides the lan call with your own txt/title Note ! > for MENU (caption)

**Comment by Jimmi08** [comment]
Ha, I wanted to send the same issue as bug, because it seems like a bug (it should have translated text).  By the way, I am probably blind, but I don't see where to insert tags on news or pages.

**Comment by OTroccaz** [comment]
@Jimmi08 have you found where to insert tags?

**Comment by Jimmi08** [comment]
No, but it worked before, they were missed just with pages
https://github.com/e107inc/e107/issues/750

https://github.com/e107inc/e107/issues/699

**Comment by Jimmi08** [comment]
@CaMer0n 
You probably could close this, there is newer issue about this  and original question wasn't bug.
https://github.com/e107inc/e107/issues/1219

**Comment by CaMer0n** [comment]
@Jimmi08 Okay, thank you! :+1:
