### ISSUE TITLE
Fatal in comment manager

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#1176]
I see follow information:
Fatal error: Cannot use string offset as an array in \e107_plugins\social\e_comment.php on line 21

**Comment by CaMer0n** [comment]
@hanklu Please update e107_plugins\social\e_comment.php from github, does it help?

**Comment by hanklu** [comment]
I had update it and got same error.

**Comment by Radzi0** [comment]
Can you try it on a fresh install?

**Comment by hanklu** [comment]
It's OK for a fresh install.

**Comment by CaMer0n** [comment]
@hanklu What version were you upgrading from when the error occurred?

**Comment by hanklu** [comment]
a.I download it from e107 website (V2.0) got this issue(XAMPP, PHP Version 5.6.12),
b.I try upload github file(only e_comment.php) to my install web(V2.0). and still got this issue.
c.I upload to my hosting and got same issue.(try difference hosting)
c.I re-install it and file from github, issue is close.
