### ISSUE TITLE
Forum LAN_FORUM_2003

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#1177]
Version:e107 V2.0
Error: Forum LAN_FORUM_2003
Status:I see LAN in admin.
link:
e107_plugins/forum/forum_admin.php?mode=mods&action=list

**Comment by tgtje** [comment]
Ok, a slipup (1 lan not called in forum php : (i will make a commit for it)
e107::lan('forum','front', true);  (forum_admin .php)
has to be in place so it can call the LAN (description) from English_front

**Comment by tgtje** [comment]
https://github.com/e107inc/e107/pull/1178
please retest, thank you

**Comment by hanklu** [comment]
Re-install github file. I see same information.
Link:e107_plugins/forum/forum_admin.php?mode=mods&action=list
Status:Forum LAN_FORUM_2003

I find other new:
Status:Forum WMGLAN_5
Link:e107_plugins/forum/forum_admin.php?mode=main&action=rules

Forum FORLAN_116
Link:e107_plugins/forum/forum_admin.php?mode=report&action=list

**Comment by tgtje** [comment]
Ok, can not see the LAN_FORUM_2003 with new file, and do not notice the 
WMGLAN_5 (being Set Forum rules)

As for the FORLAN_116 (Reported Posts). happens now and then??, has to 
be more strict setting i guess
could you manually add (change) the following line in forum_admin.php ?  
(around line 20 )
e107::lan('forum', 'admin',true);
the piece >      ,true   is added) and recheck. if it works i can commit 
it.. (then at least 2 people would have checked it first)
Thank you

**Comment by Moc** [comment]
With all the LAN changes I'm pretty sure this has been addressed by now. If not please re-open.

**Comment by tgtje** [comment]
Yes, it was waiting for a response from the poster ( test)



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus
