### ISSUE TITLE
Enhancement/possibility/bug ? 'Message' Captions (empty)

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1180]
In v1 version one was able to do NOT use a 'caption' (where title leaves a heading /or ID name) for a page, menu or alike.
This function is still in v2 ! .BUT leaving that field without a letter/number/character WILL
save it to the databse!, but that particular 'item' (menu/page etc..) does NOT display in admin listing (belonging to); so no way of knowing it is there or editable., The only way to let it display is to manual add a caption in dbase (that way it is accepted but then caption is present again> not wanted)
Is quite often a handy and very usefull feature.

So being able to NOT use a caption > still displaying in admin

**Comment by CaMer0n** [comment]
I believe a menu template which doesn't include a caption will be the easiest way around this.

**Comment by tgtje** [comment]
@CaMer0n  ..I understand the explanation.... still remains:
the 'bug' part consist but for the users who by accident forget to add the 'title/caption'> system will accept it nonetheless, store it, and for those it would appear (listing) as> gone ( not saved) > (only dbase does have it).It just does not get displayed

**Comment by CaMer0n** [comment]
Indeed, I'll see what can be done.

**Comment by Moc** [comment]
Pretty sure this one can be closed now that #1474 is fixed.
