### ISSUE TITLE
Table margin settings

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#1181]
![margin](https://cloud.githubusercontent.com/assets/12445784/9757574/ca711cb0-56e1-11e5-996d-e829403489fe.jpg)

So, when I create a table in a single page in v2.0, I want to set up a table margin like in v1.0.4 ([img style=height:100px;float:left;margin-right: 20px]) but I can't, there is no option for this in tinymce. If I change to the source code, and set up margin with a code "margin-right: 20px", didn't work too.

(Sorry for my english...)

**Comment by Moc** [comment]
@KiraTheUltimate Is this still an issue in the latest version?

**Comment by KiraTheUltimate** [comment]
It's OK now. I closed! Thx! :)
