### ISSUE TITLE
https issue: browsers refuse to load unsafe http data (like bootstrap)

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#1183]
I have a site setup with E107 and https. Because some data like bootstrap is retrieved using http, firefox and Ie are complaining that there is secured data and unsecure data and refuse to load the unsecure data causing a corrupted website. I can click to verify and after that it's ok, but this looks like an issue to me. I can set the http to bootstrap to https so there's no reason why e107 is using http for these. After all, it's no problem to load secure data from within a http site, but the other way around is a problem under the most recent browsers. But perhaps I'm doing something wrong?

**Comment by CaMer0n** [comment]
Thanks. Is this also in the admin area, or just the front-end?

**Comment by aducom** [comment]
Good question. I checked and the admin area seems to be working fine. So I guess it's only the front-end.

**Comment by Moc** [comment]
@aducom Please update from Github and see if there are any remaining issues.

**Comment by aducom** [comment]
This was fixed in one of the updates of Cameron. So this issue can be closed.

**Comment by Moc** [comment]
@aducom Perfect! Thanks for checking.
