### ISSUE TITLE
[Upgrade v.1.0.4 to v.2.0]  Error message after 'e107_v1.x_to_2.0_upgrade' upload

### ISSUE THREAD

**Issue by mfpweb** [e107inc/e107#1184]
I've tested an Upgrade pack on a website running v.1.0.4
After completing all the files upload, it returned a blank page with the following Error message:
Fatal error: Call to undefined method language::bcDefs() in /membri/mywebsite/class2.php on line 644

I looked into class2.php, line 644 and I find:
$lng->bcDefs(); // defined v1.x definitions for old templates.

I first reported the issue on >> http://www.e107help.org/
and I was supported by Moc (you can see the whole topic here >> http://www.e107help.org/1396/what-is-the-best-procedure-to-upgrade-from-v-1-0-4-to-v-2-0 )

Since the site was compromised indeed, I made a second upload on another live website (also running v. 1.0.4), following his instructions:
- first I made a complete backup of the MySQL database
- then I uploaded all the e107_v1.x_to_2.0_upgrade files, making sure that all the files were overridden

This time the result was that the system was effectively trying to access to the admin area (= the e107_admin/admin.php URL was displayed on the browser window) but, instead of taking me to the Admin panel, the page remained still 'blank', this time reporting a different Error message:

Fatal error: Call to undefined method e107plugin::parse_plugin() in /membri/mywebsite/e107_handlers/sitelinks_class.php on line 950

When going into PhpMyAdmin > xxx_core prefs Table, I could see that the DB had actually taken some changes (for example, the Admin Theme was currently bootstrap3):
  'admintheme' => 'bootstrap3',
this means that the previous Core theme (as for admin theme) had been actually overridden... but the site still returned a blank page, with the above Error message.

I finally solved following Moc's suggestion, by overriding all the files with the latest 'GitHub version'!!!

That's why Moc and I had to agree that maybe there's a bug in 'e107_v1.x_to_2.0_upgrade' Pack

What do you think on it? 
Sorry if I don't attach any screen... I really forgot to make at that moment... but I can provide further data, if you need.

**Comment by CaMer0n** [comment]
Thank you for the detailed report. The upgrade pack was tested prior to release. I guess we'll have to wait and see if others here can confirm a similar case. What would have been useful was to download all the scripts that triggered errors. (ie. class2.php, sitelinks_class.php) and compared them against those in the fresh install.  We you uploading files one-by-one via FTP, or did you upload the .zip file and then extract/unzip it on the server? (using cPanel or command-line for example)

**Comment by mfpweb** [comment]
Hi Cameron :-)
Thank you for your interest.

On both sites I used the 'original' "e107 1.x to 2.0 Upgrade" (.zip) pack I've taken from e107.org page >> http://e107.org/get-started
As I always use to do for all my sites, I first unzipped on my desktop and then uploaded via FTP on the server.

In the first case, I also tried with the Full pack (with no e107_config.php and install.files of course, but with no results at all!

In the second case, I solved only after using the 'GitHub version'  :+1:

**Comment by Moc** [comment]
@mfpweb Did you manage to successfully upgrade your v1 websites by this time or are you still experiencing these issues?

**Comment by Moc** [comment]
Closing due to lack of feedback. I believe this issue has been resolved in the latest version. If this is not the case, please let us know and I'll re-open.

**Comment by mfpweb** [comment]
Sorry for the delay.... To be honest I've stopped using v.2.0 because of
that bug.
Thank you if you definitely solved. I'll try again and let you know.

2018-02-24 17:36 GMT+01:00 Tijn Kuyper <notifications@github.com>:

**Comment by CaMer0n** [comment]
@mfpweb I'd be happy to perform your upgrade for you if you run into problems. You can reach me in the gitter chatroom.
