### ISSUE TITLE
Faq plugin e107-2.0.0 Showing only one faq..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1185]
Hi,
installed the FAQ plugin, can only see one Faq Question and answer, whatever i do Faq front isn't showing anything else... Clean install Admin is having three faqs...

**Comment by tgtje** [comment]
confirmed; 1 display (number 1) txt visible on expand. The other s ( 2 & 3 ) are IN dbase, but do not display; also 1 info title > (General) is available on front.  Misc can be selected in admin, but has no influence on display.

**Comment by CaMer0n** [comment]
Please check the category visibility settings.

**Comment by Alex-e107nl** [comment]
Cameron, i've uninstalled the plugin and installed again, cache empty and now it works, but i really do not understand how... looks like its depending on something else in e107.. try to find it out..
Thx!

**Comment by Alex-e107nl** [comment]
Testing Faq plugin, github of today, english, only 1 category General is showing with only one faq, the top one in the admin list. Clean install, the category visibility settings are all Public..

**Comment by Alex-e107nl** [comment]
Testing Faq plugin, github of today, english, only 1 category General is showing with only one faq, the top one in the admin list. Clean install, the category visibility settings are all Public..

**Comment by CaMer0n** [comment]
@Alex-e107nl Are you available to troubleshoot this together? https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
I managed to reproduce this once. Going to the Faqs Preferences area appeared to have fixed it. Uninstalled/ReInstalled the plugin and it is still working as intended. Definitely an odd one.

**Comment by Alex-e107nl** [comment]
Cameron, 
i build websites and mostly use e107 for many years now, next week i wil test the faq and also the download plugin, there's also something else happening, looks the same, when you change something in the download plugin preferences its also showing only 1 download but there are 4.. Uninstalled/ReInstalled and it works again but do not change something in the prefs or it happens again..

**Comment by Moc** [comment]
Ah yeah, I've heard from other people that they had a similar bug with the download plugin.

**Comment by Alex-e107nl** [comment]
Cameron - Moc, tested on div accounts, i cannot get the FAQ plugin to show more then 1 faq... There are 3.. dates right, categorie right, going to settings or changing anything in it does not solve it.. using standard theme BS 3 github today..

**Comment by CaMer0n** [comment]
@Alex-e107nl Could you please try with debug disabled and enabled. Any change?

**Comment by Alex-e107nl** [comment]
Cameron, it does nothing... no changes.. also cleared cache, i only see 1 faq and there are 3, also tried with different categories, doesnt help...

**Comment by CaMer0n** [comment]
Okay thanks.

**Comment by CaMer0n** [comment]
@Alex-e107nl Would you like to troubleshoot in realtime with me? https://gitter.im/e107inc/e107

**Comment by Alex-e107nl** [comment]
Cameron, i am trying to tell TGTJE not to mess up the Dutch translation anymore :-) Sorry been very busy.. i just cannot understand why this is happening trying to build an new https://e107.nl now.. Faq would be welcome..

**Comment by CaMer0n** [comment]
Do you have emoticons enabled?

**Comment by Alex-e107nl** [comment]
No emoticons, i've just installed a standard e107 v2 github Here https://zorgvergoeding.com/faqs it's working but that is a e107 Version 2.0.0 (git) ...

**Comment by Alex-e107nl** [comment]
Cameron, found it... when i deactivate the Display Social buttons its working.... :-) Does this help?
Github of today, standard theme ..

**Comment by Alex-e107nl** [comment]
Solved! Can activate emoticons now and use the Social buttons! THX!!
