### ISSUE TITLE
Edit button front in custom pages gone..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1186]
There's no edit button in custom pages anymore, when you've got lots of pages it was a blessing to get to the right page in one click from the site into the admin.

Is it comming back?

**Comment by Moc** [comment]
In the admin area, you an easily use the search bar at the top. For example by searching for the title. There are also various other search filters right next to the search bar (chapter, template, visibility, etc.). 

I therefore don't think the edit button on the frontend will come back. It should be relatively easy to add a shortcode and edit the template though, if you really want it. I strongly suggest to use the search bar though.

**Comment by Alex-e107nl** [comment]
Hi Moc, http://e107help.org/2263/edit-link-in-pages does the trick... When you have 157 pages it's really easy to edit the right page now..  :+1:  Jimako - Hatori

**Comment by Moc** [comment]
Needs discussion, but easy to implement. 


in e107_core/shortcodes/batch/page_shortcodes.php, add:
```php
function sc_cpage_adminoptions($parm='')
{
    return "<a href='".e_ADMIN_ABS."/cpage.php?action=edit&id=".$this->var['page_id']." class='fa fa-edit'></a>";
}
``` 

Then in the page_template.php you can use {CPAGE_ADMINOPTIONS}

@CaMer0n What do you think?

**Comment by CaMer0n** [comment]
@Moc Yes, added it back as CPAGEEDIT with some perm checks and other features. 
Experimental:  `{CPAGEEDIT: modal=1}`

**Comment by Moc** [comment]
Re-opened for documentation
