### ISSUE TITLE
Download Plugin 2.0.0 nocaption

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1187]
When uploadeing a file within the plugin (File 	- Select local file), the caption field isn't filled, so there is nothing to identify the file with when choosing it after its uploaded. 
In the media manager you can also choose title under options but you cannot save.. so you can only see - Preview 	Caption 	Date stamp 	Options .. 

Its difficult to pick the right file when uploading more then one...

**Comment by CaMer0n** [comment]
@Alex-e107nl is this still an issue?

**Comment by CaMer0n** [comment]
I believe I fixed this a little while back. Please re-open if necessary.
