### ISSUE TITLE
Non-ASCII (Russian) symbol I lost

### ISSUE THREAD

**Issue by rusvision** [e107inc/e107#1188]
All the texts that contain big symbol of russian alphabet (our I) -- "И" -- after publication contain <?> symbol. It has numerical code "&#1048"
------------------------
![russian_symbol_lost](https://cloud.githubusercontent.com/assets/12779920/9959944/31f575da-5e20-11e5-903a-bd8c615d5c40.png)

**Comment by CaMer0n** [comment]
Please check your browser 'view' settings. Does it say it is UTF-8 ?

**Comment by rusvision** [comment]
yes, you can see it here - http://rusvision.com/ (Last sentence of Welcome message)

**Comment by CaMer0n** [comment]
Could you please go to the admin area, and click Tools->Database ->Check Charset. See if anything is marked with a red cross.

**Comment by rusvision** [comment]
yep, I checked - everything is ok. Not so far ago I upgraded from the e107 v2 (~April `15), but problem was already presented in April. Before I just forced using small "I" and now decided to signalize about issue

**Comment by CaMer0n** [comment]
I just checked the HTML and it says: <html lang="en">

**Comment by CaMer0n** [comment]
Please open e107_languages/Russian/Russian.php and paste the first 10 lines here. Thanks.

**Comment by rusvision** [comment]
in e107_languages\ I have only English (as in git). Do I need to download and activate multilang and switch from UTF-8 get this symbol?

**Comment by CaMer0n** [comment]
Yes, you need a Russian language pack.
