### ISSUE TITLE
E107v2 - Media Manager not worked

### ISSUE THREAD

**Issue by AlexL777** [e107inc/e107#1190]
Dear developers,

I brought only yesterday my blog on the new e107v2 version, but with me the Media Manager is not working. While I can upload pictures in the manager, but they are not uploaded and do not appear in the Library.

The Media Directory has CHMOD rights of 777 and also the images directory has CHMOD-rights 777 aircraft.

What can I do? There is also no error message appears. Perhaps I can help, what would be great. Thanks in advance.

![e107v2-media-manager-not-worked](https://cloud.githubusercontent.com/assets/7885632/9987573/56ba43fc-6049-11e5-8168-84e612798525.jpg)

**Comment by tgtje** [comment]
Please if possible use 755 max on chmod (or let the system do it > admin/tools/database/chmod
755 is sufficient normally for functions.
Just to be sure (no offence please; i can not replicate this) :  you are aware you have two ( 2) pages already while page 1 is displaying on screenshot)?

**Comment by AlexL777** [comment]
Thank you, everything has cleared up. The CHMOD Permissions were set correctly and as I had previously e107 2.0 Beta 2 and probably it did not work out something when you upload the files.

I have now e107 2.0.0 fresh install and use it the old database. Now I can work with the Media Manager and the Library. Hmm ... sometimes you something. Maybe I had some old files on the server or as you wrote in the first issue. The user upload was not enabled, which I suspect :)

**Comment by tgtje** [comment]
Please close issue if satisfied

**Comment by rica-carv** [comment]
Hi all
I've got this same issue, and further more, i can't upload files form my PC, using the file upload on Media Manager....
How can i resolve this issue?
