### ISSUE TITLE
Cannot change Avatar - E107V2

### ISSUE THREAD

**Issue by AlexL777** [e107inc/e107#1191]
Hello developers,

I have another problem and although I can not change the Avatar in the User Profile. There is no button to upload the avatar displayed. Currently I have only the default avatar and it is located in the directory /e107_images/generic/default_avatar.jpg

And where there are user avatars? Maybe I have to because even CHMOD rights of 777 awarded, although I have already done it anywhere.

Many light you can help me ?! Thank you in advance.

![e107v2_avatar_change](https://cloud.githubusercontent.com/assets/7885632/9988138/42021ef8-604e-11e5-91e1-28b56c0b8060.jpg)

**Comment by tgtje** [comment]
Did you enable  (admin/members/options) the first item : allow users to upload
this will enable an upload method (click image). There are NO preset avatars on board except the generic one.(preset)
When uploaded it (new avatar) will reside in folder /media/numb/avatars/ 
There is afaik no setting that allows the use of another one from inside system.

**Comment by AlexL777** [comment]
Thank you could help me a lot. And I just had too little experience with e107v2 and did not know why I can not upload avatar. But now I have everything set.

In the second issue of me today everything has settled. I have the project reinstalled, using the old database. Now anything goes.

**Comment by tgtje** [comment]
Please close issue if satisfied

**Comment by CaMer0n** [comment]
No feedback, so closing. Reopen if necessary.
