### ISSUE TITLE
e107 v1.0.4 Cookie Plugin not worked

### ISSUE THREAD

**Issue by AlexL777** [e107inc/e107#1195]
Hi Developers, I want to install in my e107 v1.0.4 Portal cookie bar, but http://e107.org/plugins/?id=786 this plugin can not be uploaded. I can already upload via FTP, but in the Plugin Manager in the backend of e107 You do not see the plugin.

Upload the zip package from the Plugin Manager out also does not work and it appears that it is not a proper package. How can I eliminate the problems or:

I have this code in the Embed theme.php file, but that's not because more errors in the frontend display. Is it possible to somehow modify code so e107 accepted it?

    <! - Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent ->
    <script type = "text / javascript">
    window.cookieconsent_options = {"message": ". This site uses cookies More  information you see in the privacy policy Thank you.", "dismiss" "Agreed," "Learn More": "More Info", "link": " http://e107v1.wpzweinull.ch/page.php?5","theme":"dark-top "};
     </ script>
    <script type = "text / javascript" src = "// s3.amazonaws.com/cc.silktide.com    /cookieconsent.latest.min.js"> </ script>
    <! - End Cookie Consent plugin ->

About a couple of ideas I would be grateful.

**Comment by CaMer0n** [comment]
The zipping/unzipping could be an issue with the server itself. (allowing such things). 
For the code, I suggest you take a look at the docs on e107.org regarding using javascript (e107::js) in an e_header.php file.

**Comment by CaMer0n** [comment]
Closing this. Not a core plugin.
