### ISSUE TITLE
Feature request: Different FRONTPAGE based on IP

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#1202]
I would have loved to have a different frontpage based on the IP that the user has.
And also for example if the user IP is in Spain, the language changes to Spanish.
Is that at all posible?  If yes....how?

Thanks!

I use 2.0 version with English, Spanish and Norwegian language packs installed.

**Comment by CaMer0n** [comment]
It is better to use the browsers default language, as I believe IPs are not always the best indication of country and rely on IP databases. It might be something I will include in the multilan plugin. (see here: https://github.com/e107inc/multilan ) You can add a feature-request there if you wish.
