### ISSUE TITLE
Feature Request: Find Plugin/Theme Error Page

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1203]
This started out as a bug but further investigation shed light on what is below:

My site uses the Developer Sync with GitHub

Issue: Plugin Manager -> Find Plugins

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' : Start tag expected, '<' not found in /usr/www/webmc/defiantz/e107_handlers/e_marketplace.php:456 Stack trace: #0 /usr/www/webmc/defiantz/e107_handlers/e_marketplace.php(456): SoapClient->SoapClient('http://e107.org...', Array) #1 /usr/www/webmc/defiantz/e107_handlers/e_marketplace.php(182): e_marketplace_adapter_wsdl->__construct() #2 /usr/www/webmc/defiantz/e107_handlers/e_marketplace.php(197): e_marketplace->adapter() #3 /usr/www/webmc/defiantz/e107_admin/plugin.php(455): e_marketplace->call('getList', Array) #4 /usr/www/webmc/defiantz/e107_admin/plugin.php(383): pluginManager->pluginOnline() #5 /usr/www/webmc/defiantz/e107_admin/plugin.php(176): pluginManager->pluginObserver() #6 {main} thrown in /usr/www/webmc/defiantz/e107_handlers/e_marketplace.php on line 456

**Comment by LaocheXe** [comment]
Well went to e107.org and got a "Invalid list file" on my screen - so my bug must be from the site having issues - so changing this from BUG to Feature Request: If any connection error is shown when Finding Plugin/Theme then have a error page to display. (More fluent in C# than PHP - Try Catch Error handling)

**Comment by Moc** [comment]
This should be fixed by now.
