### ISSUE TITLE
Dangerous Bug: Plugins Directory Wipe!

### ISSUE THREAD

**Issue by Buckfutt** [e107inc/e107#1205]
I found a terrifying bug today the hard way. After un-installing a plugin via the plugins manager page, I accidentally hit "Refresh" on my browser and it completely wiped out my plugins directory!

**Comment by LaocheXe** [comment]
shouldn't of - odd

**Comment by Buckfutt** [comment]
Recreation Steps:
1. Install a random plugin.
2. Uninstall that plugin.
3. With Uninstallation Confirmation information still on the screen: Hit F5 or Refresh the page.
4. Will say "../e107_plugins/" deleted.

Have tested again just to be sure and got the same result.

**Comment by tgtje** [comment]
Tested : live and xampp > can not replicate..

**Comment by Moc** [comment]
Bug confirmed 

@CaMer0n Needs a priority fix

@tgtje Select 'Delete files' during the uninstall process

**Comment by Moc** [comment]
@CaMer0n  Quick and dirty fix:

In e107_admin/plugin.php on line 791, change:
```php
if($_POST['delete_files'])
```

to 

```php
if($_POST['delete_files'] && $plug['plugin_installflag'] == TRUE)
```

**Comment by CaMer0n** [comment]
Thank you Moc!
