### ISSUE TITLE
Missing icons menu php

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1206]
Latest files, fresh install; just noticed (older files do have it too at recheck).

Since the NON use of Bootstrap as part of core themes (now only BS3) a small thing is missed. (any 'update' etc would have bootstrap on board so it does not 'appear' as mistake/error)

menus php line 1252 : e107::css('url','{e_THEME}/bootstrap/admin_style.css');

has to be : e107::css('url','{e_THEME}/bootstrap3/admin_style.css');
after changing this icons appear

![abs](https://cloud.githubusercontent.com/assets/1811857/10564058/e8f80504-75a4-11e5-87b4-bb888431e6fe.jpg)
![bs3](https://cloud.githubusercontent.com/assets/1811857/10564057/e8f789c6-75a4-11e5-9d0e-744f9dc8a555.jpg)

(did not submit a pull request), has to be confirmed..

( ????  sidetrack : message handler php line 993  call for bootstrap : href=    "//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
still ok ?  (version)

**Comment by CaMer0n** [comment]
Thank you, I noticed it too just yesterday. Will commit shortly.
