### ISSUE TITLE
[Bug] Critical errors from class2.php immediately after install with UTF8 charset and collation

### ISSUE THREAD

**Issue by dmitripot** [e107inc/e107#1207]
CRITICAL ERROR:
Line 483 /var/www/www.signisoft.com/class2.php
Error reported as: [3]: Core settings saved - backup made active.
CRITICAL ERROR:
Line 485 /var/www/www.signisoft.com/class2.php
Error reported as: [4]: No core backup found. Check that your database has valid content. 

Tested with regular MySQL charset/collation and it works.

Sucks.

**Comment by tgtje** [comment]
No offence please, but throughout time it 
a) very often appears when there are errors (mistakes) in credentials for/from host ; either on cpanel or config php has some mismatch. (general dbase related)
Or b) language related when using another language during install (language files have errors).

**Comment by ChiellieNL** [comment]
Same issue here.. 
Tried to install it over and over again, but never works..
Tried the download from e107.org as well as the latest Git..

**Comment by Moc** [comment]
Same issue here: http://e107help.org/1648/problem-with-index-php-after-instal

PHP 5.5.9
MySQL 5.5.46
Running on Ubuntu 14.04 LTS

**Comment by CaMer0n** [comment]
Tested working with Windows: 
PHP  5.4.17
MySQL 5.6.13

Wondering if it's a PHP 5.5 thing?

**Comment by dmitripot** [comment]
Yes, forgot to mention: it's
PHP 5.6.13-pl0-gentoo (might have been a few subversions less at the time of the bug, since I have a co-user on the server who runs emerge updates once in a while)
MySQL: 5.6.26-log

**Comment by CaMer0n** [comment]
Thanks @dmitripot  - Could you also please share the value of "sql-mode" in your mysql config file? ( my.cnf ). Thanks. 

     eg.    sql-mode = "STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by CaMer0n** [comment]
Likely related to Issue #1102

**Comment by dmitripot** [comment]
Hey, sorry about the late response. I'm back at it (helping somebody set up a site, they upgraded to v2).
So my sql-mode isn't set from the default location my.cnf, however I was able to get this:
'''
mysql> SELECT @@GLOBAL.sql_mode;
+------------------------+
| @@GLOBAL.sql_mode      |
+------------------------+
| NO_ENGINE_SUBSTITUTION |
+------------------------+
1 row in set (0.00 sec)

mysql> SELECT @@SESSION.sql_mode;
+------------------------+
| @@SESSION.sql_mode     |
+------------------------+
| NO_ENGINE_SUBSTITUTION |
+------------------------+
1 row in set (0.00 sec)
'''
So I'm guessing that STRICT_TRANS_TABLES and NO_AUTO_CREATE_USER aren't enabled.

**Comment by Moc** [comment]
Is this issue still present using the latest files on Github?

**Comment by Moc** [comment]
Closing due to lack of feedback. Presumed fixed. Let us know if this is still an issue and I'll re-open.
