### ISSUE TITLE
Log out doesn't work

### ISSUE THREAD

**Issue by dmitripot** [e107inc/e107#1208]
Pressing log out hangs at /index.php?logout
White screen and that's it. The session is not affected and I am still logged in.

**Comment by Moc** [comment]
Is this on a different installation than #1207?
Maybe related to #1211

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. I am closing this issue but in case you are still experiencing issues, please let us know and I'll re-open.
