### ISSUE TITLE
Feature Request: Allow Users to change Themes

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1209]
Allow users to change their theme preferences on an e107 website. 
 An Admin:
Admin area -> Users -> Options -> (Add) Allow users to switch Themes (If disable then forces all users to the main site theme, if enable allow users to change the site theme they see)
Admin area -> Theme Manager -> (Add) Users Themes -> (This area add some options like what themes they can selected)

An User:
Settings -> (Add) Theme Selection -> (Has the list the admin allowed for this)

**Comment by Moc** [comment]
This is possible by one of plugins that has been published in the last months. Closing.
