### ISSUE TITLE
Question: How to add script

### ISSUE THREAD

**Issue by TarekTaha** [e107inc/e107#1210]
Hi, 

I am trying to add a linked in code that embeds member profile inside the welcome site, similar to the code here : https://developer.linkedin.com/plugins/member-profile . The website editor wraps the code inside an [html][/html] and once rendered inside the browser the the quotations are removed and the script no longer works: &quot;text/javascript&quot; . Anyway I can overcome this ?

Cheers

**Comment by tgtje** [comment]
no (touches security), better way would be
http://e107.org/developer-manual/classes-and-methods#javascript

**Comment by CaMer0n** [comment]
Check Preferences in admin, allow posting of script/iframe etc.

**Comment by Moc** [comment]
Closing due to lack of feedback. Please feel free to re-open if this is still an issue.
