### ISSUE TITLE
Site sublink are not show on the main link menu

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1212]
more than 1 sublink are not show in the main menu
![image](https://cloud.githubusercontent.com/assets/1758577/10812389/ed5b319c-7e15-11e5-8e31-aac37f9b978b.png)

**Comment by schlrech** [comment]
![image](https://cloud.githubusercontent.com/assets/1758577/10812407/26306384-7e16-11e5-80fd-977375178935.png)

**Comment by tgtje** [comment]
This is correct. BS3 has no sub-menulinks (were removed by devs from BS)
alternative : http://www.e107help.org/714/bootstrap-3-sub-sublinks

**Comment by Moc** [comment]
You can use other themes (non bootstrap based) to have third level menus.

**Comment by schlrech** [comment]
@tgtje
thank you... now i have 3rd level menus

**Comment by Jimmi08** [comment]
Link to that old  but needed topic:
https://web.archive.org/web/20170107073117/http://e107help.org/714/bootstrap-3-sub-sublinks
