### ISSUE TITLE
Section Title not displaying LAN conversions correctly

### ISSUE THREAD

**Issue by septor** [e107inc/e107#1213]
When you define a LAN in English_admin.php and assign it to your adminMenu array as a title, it displays in the menu area correctly but not in the section title. Some images, for clarity:

![Image of Admin Area](http://septor.us/tmp/admin_area.png)
![Image of code](http://septor.us/tmp/editor.png)

**Comment by Moc** [comment]
@CaMer0n Bug or intended?

**Comment by tgtje** [comment]
If i may... you are using the new style for calling languages...
How are they 'called' (asking the defines txt to display instead of LAN) ?

example : include_lan(e_PLUGIN."anteup/languages/".e_LANGUAGE.".php"); (admin cash php)
while new would be similar to
 
e107::lan('anteup', 'admin', true); // e_PLUGIN.'anteup/languages/'.e_LANGUAGE.'/admin_config.php' (admin config php)
and so on....

sorry would like to test it, but the plugin (present files) throw "setup error (line 38) so can not continue. Maybe at least it triggers an idea.

**Comment by Moc** [comment]
The LANs are located in the English_admin.php file. This means they should be preloaded by the admin UI (which in fact it does because the other LAN do load up properly). 

For some reason though, it does not pick up the LAN for the different sections/areas.

**Comment by septor** [comment]
@tgtje - I would agree, except my issue is with admin_config.php where no calls, new or old, are even used. I'm under the impression that the English_admin.php file is automatically called on admin_config.php.

I'm not saying the old code isn't broken or using incorrect code, it is, but the new code doesn't function correctly, or I'm doing something wrong (possible!).

**Comment by tgtje** [comment]
@septor @Moc  similar behaviour (other plugin) where everything works but not main top lan def
see my last post on page https://github.com/e107inc/e107/issues/1177

**Comment by septor** [comment]
Adding `e107::lan('anteup', 'admin', true);` directly before the first class creation fixes the issue, but I'm still not sure this should be the correct solution. Kind of feels like a bandaid to me!

Why do some of the LAN calls work without the call? Shouldn't they all work or not work?

**Comment by tgtje** [comment]
@septor  longgshot here (not a coder) using gallery (admin_gall) as example 
instead of the above lan call  ..as in gall > 

$eplug_admin = true;   (  before calling class2.php )

**Comment by septor** [comment]
Hmm, I'll give it a shot and see if it nets the same result. Still begs my previous question though about some of the LANs working fine without any call at all.

PS: I'm not trying to make a mountain out of a mole hill with this either, I can just bet this happens to someone else down the road too.

**Comment by tgtje** [comment]
No you don't. Fully agree. It is informational, and adds to development use (in time) creating language related files building a plugin. When working with lans and defines the system still uses 3 kinds of lan calling... (maybe a standard will arise, or is on the wishlist ?? as e107::lan ..call is the new one, and this method works some what 'sideways. (hard to explain thought)

**Comment by septor** [comment]
Yeah, I'm noticing that in several things. LAN and pref calling to name a few. I would imagine some of the issues exist because of backwards compatibility.

Maybe the best action would be to name it so nothing is translated unless there's a LAN call in the file, then there's no confusion.

**Comment by asdonley** [comment]
{
    "name": "opauth/facebook",
    "description": "Facebook strategy for Opauth",
    "keywords": ["authentication", "auth", "facebook"],
    "homepage": "http://opauth.org",
    "license": "MIT",
    "authors": [
        {
            "name": "U-Zyn Chua",
            "email": "chua@uzyn.com",
            "homepage": "http://uzyn.com"
        },
        {
            "name": "Ceeram",
            "email": "c33ram@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.3.0",
        "opauth/opauth": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "Opauth\\Facebook\\Strategy\\": "src"
        }
    }
}

**Comment by tgtje** [comment]
??

piece of composer lock (Opauth test application)

? connection to e107 i can not see

**Comment by Moc** [comment]
Spam, just ignore. I've notified Github.

**Comment by septor** [comment]
Sorry, I apparently bring out the weirdos!

**Comment by CaMer0n** [comment]
I came across this issue again recently. It appears PHP manages to 'guess' what some LANs are while loading, however it will still throw a notice/error for these missing constants (ie. Missing Constant 'LAN_XXXX', assuming LAN_XXXX) . 

So, the correct thing to do while coding is use e107::lan() at the top of the page to include your language file.

**Comment by Moc** [comment]
@CaMer0n Shouldn't this be included in the plugin builder then somehow? This issue appears when using the Admin UI and I don't see any explicit e107::lan() calls.

**Comment by CaMer0n** [comment]
Plugin builder doesn't create language files. I'll add something commented it.

**Comment by Moc** [comment]
I know, but the admin UI is able to read the LAN defines, so they are included somehow right? I'm not sure where this is done but shouldn't they be included earlier to ensure that the issue discussed here is resolved?

**Comment by septor** [comment]
The issue is some calls are translated even without using any calls at all. Either they all should be translated or none of them.

**Comment by CaMer0n** [comment]
As it says on line 138 of boot.php: 

```
// DEPRECATED - plugins should load their lans manually
// plugin autoload, will be removed in the future! 
// here mostly because of BC reasons.
```
Conclusion: Use e107::lan();
