### ISSUE TITLE
Login top/bottom - Theme Manager > Site Theme > Preferences

### ISSUE THREAD

**Issue by Radzi0** [e107inc/e107#1214]
Hi

I found that settings for top bottom login field is not workin.

![login](https://cloud.githubusercontent.com/assets/10882348/10865012/f7cf3b6a-7ffe-11e5-814c-b35da6021a85.png)

When set to top, there is still login field on the bottom, same with bottom, there is still one on the top.

e107 - Github - 31 10 2015 - 18:00

**Comment by Moc** [comment]
Confirmed. 

@CaMer0n Possibly related: The default e107 site logo now shows in the navbar (top left) after updating to Github. Somehow the prefs are not correctly loaded? Not sure when this started.
