### ISSUE TITLE
comments on news posts.

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1218]
Hi am unable to post comments on news articles.

After posting news item, if i try to comment on it immediately i get a white page, unauthorised acess.
If i then go to home page, then back to news item, write the comment and submit, page refreshes but no comment appears.

I have comments turned on globally in preferences and for the news item posted.

Regards.

Gary

![screenshot_1](https://cloud.githubusercontent.com/assets/12760959/10946383/ea76c15e-8319-11e5-94ce-6d1d538d492e.png)

**Comment by gary231178** [comment]
I have also had confirmation from other site users both admin and standard member user class who are unable to leave a comment as-well.
First time for them upon submitting gives a white page, unauthorized access, then when trying again page refreshes with no comment showing.
Admin area also shows no comments submitted or requiring review by admin.

Regards.

Gary

**Comment by Moc** [comment]
Please ask your webhosting provider to check that the PHP session save path is configured correctly. It needs to point to a folder which is accessible and writable.

**Comment by CaMer0n** [comment]
Please check your template against the default bootstrap one. Look for ids and classes.
