### ISSUE TITLE
stuck in update, cannot create table, already exists

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1220]
after updating the files i'm stuck in the update process.

![untitled](https://cloud.githubusercontent.com/assets/6122908/10995246/bc04805a-847b-11e5-9c30-ca9605c57bc5.png)

same error re-appears when clicking update.. tried it four times.

this one totally funked up my media tables?
and dunno for sure but seems related :
several news items now are not showing my images.

edit.. 
after a few minutes most of the images seem to show again.
still stuck tho.

**Comment by Moc** [comment]
Hmm this one is odd. Not seen this before. Try this:

- Update again from Github (use the function in Tools > Database) or do it manually. Make sure you overwrite all the files properly. 
- Run a Tools > Database > Check database validity, to check if the tables are ok. 
- Clear the caches (e107 and browser)

**Comment by willem010** [comment]
i tried the verification. 
(will update files again later on, cant do this when the radio is broadcasting and thousands of users are online)

it shows me :
![dbveri](https://cloud.githubusercontent.com/assets/6122908/11042050/4e7c7cb2-8715-11e5-882d-2cd49eb55712.png)

which is weird.. the table exists : 
![mysqlworkb](https://cloud.githubusercontent.com/assets/6122908/11042056/5a5558d8-8715-11e5-942f-4b2dd11290ca.png)

do note the not default table prefix ..

**Comment by willem010** [comment]
updating from tools-> database doesnt do anything.
the notification on adminstartpage remains.. clicking update there gives the error as reported in my first msg here.

**Comment by Moc** [comment]
Would it be possible for me to receive an admin login? if yes, please send it to my email: e107@tijnkuyper.nl

**Comment by willem010** [comment]
your account should still work. 
user tijn

**Comment by berckoff** [comment]
Guys, as i have been some time off this project it might be irrelevant but anyway i think it could be lepful - have you noticed the table name differences: core_media/e_core_media ?

**Comment by Moc** [comment]
This is the custom prefix. Using the default installation prefix (`e107_`), the table would be named `e107_core_media`. In this case, on Willem's website, the prefix is `e_`, hence `e_core_media`. I'm thinking that there is a hardcoded prefix in the code somewhere, which causes these issues. 

@willem010 Thanks, I'll be looking into it asap.

**Comment by willem010** [comment]
@moc yep. hardcoded something somewhere.. that was what i was thinking and that's why i noted the not default tableprefix.

made me think.. this other issue with posting bodytext .. doesnt that use hardcoded table names by any chance? .. maybe thats why my data never gets inserted.. ? 
its a long shot.. i know.. but maybe its related. you never know.

**Comment by Moc** [comment]
I think the bodytext issue is related to the parser, and not a hardcoded prefix. But I'll check. I'm scarce on time, so it may take a little while. Hopefully by Thursday or Friday I have looked into this.

**Comment by CaMer0n** [comment]
@willem010 Please run the Tools > Database > Check database validity script again, but with Debug enabled. It should display every table comparing the data on file. (eg. core_sql.php) with the database structure.

**Comment by willem010** [comment]
@CaMer0n  here you go:

[dbase verification with debug on.pdf](https://github.com/e107inc/e107/files/34611/dbase.verification.with.debug.on.pdf)

**Comment by CaMer0n** [comment]
Thank you @willem010 perfect! Are you able to give me FTP access? I will need to upload a test script and play around a bit to see exactly what is going on.

**Comment by willem010** [comment]
sure., where can i send the details?

(and.. maybe you;re also able to look at #1035 ?
i'm about to create an alternate news edit page so my admins are able to post something on the site again.. I'm totally losing face due to this one.;) )

**Comment by CaMer0n** [comment]
@willem010 Please login at http://e107.org/developers/ and then use "Contact Us".  Thanks.

**Comment by willem010** [comment]
same issue running on xampp.3.2.2
fresh install with e_ prefix
latest git.
keeps thinking it needs to update tables.

**Comment by CaMer0n** [comment]
Thanks @willem010 - did you message me already with login details?

**Comment by willem010** [comment]
yep, i did.

btw, the server isnt really safe yet.
a full reinstall will soon be done. 
be carefull, 
you dont want to run the crap on your local machine

**Comment by CaMer0n** [comment]
@willem010 Thank you. I didn't see it (maybe went to spam bock). Anyway, nevermind, as I have just reproduced the issue and should be able to correct it now.

**Comment by willem010** [comment]
ok thanks!

(and if you want to check out the hack later on, i will be happy to share the details.)
