### ISSUE TITLE
Find theme or plugin soap error

### ISSUE THREAD

**Issue by janke31** [e107inc/e107#1221]
When i want to find a theme or a plugin i have this error
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' : failed to load external entity "http://e107.org/service?wsdl" in D:\Utilisateurs\phdj238\Documents\Data\xampp\htdocs\e107\e107_handlers\e_marketplace.php:456 Stack trace: #0 D:\Utilisateurs\phdj238\Documents\Data\xampp\htdocs\e107\e107_handlers\e_marketplace.php(456): 
I wor on intranet with a proxy i try to add this parameters in array options.

``` php
$option = array('proxy_host'     => "trace"                 => true, 
            'exception'             => true,
            "uri"                   => "http://server.soap.e107.inc.com/",
            'cache_wsdl'            => WSDL_CACHE_NONE,
            'connection_timeout'    => 60,
                                           'proxy_host'     => "localhost",
                                            'proxy_port'     => 8080,
                                            'proxy_login'    => "some_name",
                                            'proxy_password' => "some_password");

I have alawys the error
```

**Comment by berckoff** [comment]
If this is your actual config array, it is invalid on the very first row:
" $option = array('proxy_host' => "trace" => true, "
It seems you have a missing key definition (i think you are missing the 'proxy_host' value).

**Comment by Moc** [comment]
Error handling could be checked

**Comment by janke31** [comment]
Its a mistake in mypost i Have exactly this :+1: 
....php
$options = array(
			"trace" 				=> true, 
			'exception' 			=> true,
		    "uri" 					=> "http://server.soap.e107.inc.com/",
		    'cache_wsdl'			=> WSDL_CACHE_NONE,
		    'connection_timeout' 	=> 60,
                    'proxy_host'     => "web*********.fr",
                                            'proxy_port'     => 8080,
                                            'proxy_login'    => "*****",
                                            'proxy_password' => "*******"
                    
		);

		$this->client = new SoapClient($this->serviceUrl, $options);

**Comment by tbasra** [comment]
( ! ) Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' in C:\wamp\www\prevhealth\e107_handlers\e_marketplace.php on line 458
( ! ) SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' : failed to load external entity "http://e107.org/service?wsdl" in C:\wamp\www\prevhealth\e107_handlers\e_marketplace.php on line 458
Call Stack
#	Time	Memory	Function	Location
1	0.0074	649936	{main}( )	...\plugin.php:0
2	0.1983	7219232	pluginManager->pluginObserver( )	...\plugin.php:183
3	0.1984	7221592	pluginManager->pluginOnline( )	...\plugin.php:390
4	0.2177	7515448	e_marketplace->call( )	...\plugin.php:462
5	0.2177	7515520	e_marketplace->adapter( )	...\e_marketplace.php:197
6	0.2177	7516024	e_marketplace_adapter_wsdl->__construct( )	...\e_marketplace.php:182
7	0.2178	7517000	SoapClient ( )	...\e_marketplace.php:458

**Comment by Moc** [comment]
I am pretty sure the error handling has been optimised in the most recent version. If you are still getting these errors, please let us know and I'll re-open.
