### ISSUE TITLE
News or page datestamp subtracts one month after saving the changes

### ISSUE THREAD

**Issue by OTroccaz** [e107inc/e107#1222]
"Similar" to issue #509, after saving, it subtracts -1 month for news and pages dates.
I found it was due to the line 736 in date_handler.php ($vals['tm_mon'] -= 1;) but why?

**Comment by tgtje** [comment]
Confirmed ( at first instance) testing and playing (also advanced date) after about 8 tries the system functions as it should...(for a while)

 however a next time when using another language : calendar (popup misbehaves (starts at 1899 in advanced) i get PROBLEM WITH CONVERSION from zaterdag, 07 , 2015 04:00 PM to unix timestamp..and date is gone... going back again (do not change anything : voila correct date appears.. ( caching or cron ; also language use 'seems' to have some influence ) Setting lang table use active > calendar seems to behave, but than date is gone again (needs 2x update)..and date is back...edit post (normal) again > again date is gone  > 1 -1 1970) going back to news edit mode, just hit update  > date back (method looks looping over and over)....and i can start over again having same issues.... (Remark : used xamp install for testing, do not know if it might influence)

**Comment by Moc** [comment]
In the admin area, please go to About > PHP Info, and copy the following information from the table that you see:

- PHP Version
- System: the first word only (windows or linux) 
- SERVER_SOFTWARE

**Comment by OTroccaz** [comment]
Thanks for the reply.
PHP Version : 5.6.15
System : Windows
SERVER_SOFTWARE : Microsoft-IIS/7.5

**Comment by tgtje** [comment]
In case (xampp) : 
PHP 5.6.12
Windows
Apache/2.4.16 (Win32) OpenSSL/1.0.1p

(Q ?  php bug 70619 ? )

**Comment by Moc** [comment]
This is related to using a Windows environment versus a Linux environment and the way PHP deals with this. Looking into it.

**Comment by Moc** [comment]
I'm not able to reproduce this yet on my Windows PHP 5.3 install. Will test more recent versions of PHP asap.

**Comment by Moc** [comment]
Not able to reproduce this with PHP 5.6.14 on Windows either. 
Hmmm...

**Comment by Moc** [comment]
@OTroccaz Can you please provide step by step instructions to reproduce this issue?

**Comment by OTroccaz** [comment]
When I create an article or a page > e107 will give it today's date after backup (17/12/2015 for example). If I edit it, after backup, the creation date will be lost one month (17/11/2015). If I change it again and save it again, the creation date will have still lost one month (17/10/2015). And so on...
Actually, I have commented the line 736 in date_handler.php ($vals['tm_mon'] -= 1;) and everything is fine.

**Comment by Moc** [comment]
@OTroccaz Is the issue still occurring using the latest Github files?

**Comment by OTroccaz** [comment]
@Moc I just did a test (after decommented the line) and everything is ok!
Thanks
