### ISSUE TITLE
old user login issue

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#1223]
Hi guys,

Our site's been having a strange problem for a little while now but without being able to send details to replicate I've hesitated in posting it. But now I can.

If a user hasn't logged in for a little while, when they log in, the online menu says they are logged in, but they have no permissions - the sign in / sign up button is visible, and they can't post to forums - anything. 
<img width="1219" alt="screen shot 2015-11-10 at 9 47 04 am" src="https://cloud.githubusercontent.com/assets/887725/11050269/1a4169b4-8790-11e5-80d4-3dde811f5e3b.png">
^ this is what you see when logged in as ushida
The only way we've found to enable access again for users is to manually reset and send them a new password. The forgotten password utility doesn't work either, so they can't fix it themselves. The site is sending mail - activation email for new users, test mail sends just fine. Forgot password does nothing :(

So we're finding we can only fix this if the user contacts us - half the time we're guessing that they just don't bother, and have given up / left the site. Our participation has dropped significantly, unfortunately. 

We have a test site that I've been able to replicate the problem on - and I'd be happy to send an e107 rep the authentication details (cameron if you're reading/on this, it's the same test site as last time). I can send all the details - phpmyadmin, ftp - whatever you need.  

Cheers,
Min

**Comment by Moc** [comment]
> If a user hasn't logged in for a little while, 

How long is this? Hours? Days? Weeks? 

> manually reset and send them a new password

Do you mean: Admin area > Users > Reset password?

> Forgot password does nothing :(

Please clarify 'nothing'. Do you get an error, a blank page, timeout? Is there a confirmation but the email isn't sent? What happens? :)

**Comment by Minnn** [comment]
Hey Moc - I'll try answer as best I can. 

> How long is this? Hours? Days? Weeks?
We're not entirely sure. Some months, some years. It happened to me once, when I hadn't logged in for a few days. It might have nothing to do with it, either, we've just observed that the users who are contacting us saying it's happened may not have been active for some time. 

> Do you mean: Admin area > Users > Edit, then manually change the password. And send them the new password manually, by email or so?
Yes, that's exactly how we've been doing it.

> Please clarify 'nothing'. Do you get an error, a blank page, timeout? Is there a confirmation but the email isn't sent? What happens? :)
I've noticed a few things:
- if I try from *my* account (so, an admin) to send a password reset request, I'm redirected to the homepage. No email shows up.
- if I try from a test account (non admin) I get "Error. Sorry, unable to send email - please contact the main site administrator." - however, I have confirmed that sending email via the site DOES work (Admin > Users > Mail > Preferences > Send test email, and then I get an email saying "This is a test email, it appears that your email settings are working ok!"). Other automated emails, like the one advising that you have a new private message, also work. 

Does that help narrow it down at all? Sorry for the vagueness, as I said, it's been a really difficult problem to tie down.

Cheers,
Min

**Comment by Moc** [comment]
Thanks for the detailed info Min! I understand the vagueness, these bugs are the most annoying to fix (that is, if there's a bug that we can identify). 

I'll do some testing as soon as possible but I don't have any concrete leads yet. I will be testing the forgotten password feature to see if it's working on my end. 

I cannot think of any reason why a user that has not been logged in recently would stumble on this odd behaviour. Are the website files up-to-date from Github?

**Comment by Minnn** [comment]
Hey Moc - thanks for investigating. The files are up to date on our test site - we haven't updated on our live site because we're all a bit time poor and want to try get to the bottom of the issue before we bother rolling out another update. We've actually recently redirected the forgot password page to a content page that asks them to email us directly for a reset. 
When I posted about this yesterday, it was because I'd just done another update from git and when tested, found I could replicate the issue.
I'm happy to send you the test site url, authentication details with which the issue can be replicated, an admin account, phpmyadmin access - anything you need - if it will assist in tracking down the issue. It doesn't make sense to us either, but it's happened too many times now for it to be a random happenstance. When you're up for it, send me an email at min@equivalent-exchange.com and I'll forward the details to you.

**Comment by Moc** [comment]
I guess the best way to figure out what is causing this issue, is the follow approach:

- Have a situation where there is one specific user experiencing the problem. 
- Export the current MySQL database situation
- Do the password reset manually
- Export the new MySQL database situation
- Compare database versions to see what has changed 

If you have a specific user of whom you know that this user is experiencing the issue, I can do the above steps for you if you like.

**Comment by gary231178** [comment]
This sounds very similar to my online but not logged in issue. I'm unable to pin point it to users that have not logged in recently, but that could also be a factor, as i am noticing a decline of people logging into our site who usually log in regularly. I haven't had any feedback from users reporting the issue other than the ones who had the problem and come onto our voice comms. But there have been new users who have signed up recently, and verified login etc, but then fail to reappear.

Admin area shows no login errors for said users, and also no log of the returning users ip etc to confirm the issue of failing to log in.

Users that are online but not logged in, can they log in via mobile web instead of pc browser, or vice versa.
We also had issues where users could log in via the website, but when using mobile login replicate this error and vice versa.

Gary

**Comment by CaMer0n** [comment]
Looking into this on @Minnn 's test site.

**Comment by Minnn** [comment]
Hey guys, sorry for the delay. Cameron thanks for testing on our test site. Moc one of us (@skcihmit) have done a similar test in the past - checked the user table specifically to see what might change between the account being broken and fixed with the manual password reset - and I believe he didn't find any difference. It's all very odd and doesn't make sense if the manual password reset consistently fixes the issue (which it does, though there has been a rare instance or two where we've had to reset the password twice). 

Cameron let us know if you need anything more to check it out though it sounds like @martasalek has handed over everything you need.

**Comment by CaMer0n** [comment]
@Minnn This should be working correctly now. 
The account "ushida" is an unactivated account and I believe the password I was given for that account is incorrect. Since the account was not activated, then the reset-password wouldn't work. Instead a 'resend activation' notice should display. (when the correct password is entered). You could try resetting the pwd on this account via PHPMyadmin (and using the MD5 function) to test it. 

The main issue was that a site using bootstrap2 may be missing the {ALERTS} shortcode which renders any login errors that may occur. e107 will now automatically insert this on older themes and and display a notice when DEBUG is active.

**Comment by Minnn** [comment]
Thanks for checking it out - as soon as one of us can do an update, we will.
The odd thing though that you mention the user account was inactive - is this an automatic thing? Because we didn't set the account to be so. The issue occurred to many members who had (very) active accounts at some point, and then perhaps hadn't visited for months. It also happened to *my* account, on the test site, after I had been playing around with the two other old accounts that I'd set the same password on (ushida being one of them). 
Anyway as I said, thanks again for looking into it - and we'll run an update on the test site as soon as our real lives give us the time to, and let you know how it goes!

**Comment by Moc** [comment]
Hey Min,

Just keep an eye on the active/inactive issue. Perhaps there's a bug somewhere which sets the account to inactive, even though it shouldn't!
