### ISSUE TITLE
datapicker - load css twice and one time wrong

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1224]
In admin area 
![image](https://cloud.githubusercontent.com/assets/5429548/11072529/91cb3a54-87e6-11e5-9802-5bcc96c151bb.png)

This code is from e107_admin/header.php  -  css file doesn't exist

![image](https://cloud.githubusercontent.com/assets/5429548/11072585/d91b3f76-87e6-11e5-81aa-6b66db35f351.png)

and this from form_handler.php - if you use datepicker

![image](https://cloud.githubusercontent.com/assets/5429548/11072613/f270a6b4-87e6-11e5-9db2-b276a6a9e069.png)

**Comment by CaMer0n** [comment]
Should now be fixed by https://github.com/e107inc/e107/commit/ef1e1565ada755303b528c124a9a716e02940db0  Please re-open if need be.

**Comment by Jimmi08** [comment]
Thanks. I confim it's ok.
