### ISSUE TITLE
Question: using datetimepicker

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1226]
What is the correct way to get datetimepicker working with e107?

I have included the following two lines in my theme.php file...

    e107::css('core', 	'bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css');
    e107::js('core', 	'bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js', 'jquery', 2);

but what is the *correct* way to the implement this in the plugin php file?

**Comment by Moc** [comment]
You would use the form handler (e107_handlers/form_handler.php). You call this function (or 'method' as it should be called)

 ```php
e107::getForm()->datepicker();
```

More information on this method can be found in the form_handler file. Currently around line 1002:

```php

	/**
	 *	Date field with popup calendar // NEW in 0.8/2.0
	 *
	 * @param string $name the name of the field
	 * @param integer $datestamp UNIX timestamp - default value of the field
	 * @param array or str 
	 * @example $frm->datepicker('my_field',time(),'type=date');
	 * @example $frm->datepicker('my_field',time(),'type=datetime&inline=1');
	 * @example $frm->datepicker('my_field',time(),'type=date&format=yyyy-mm-dd');
	 * @example $frm->datepicker('my_field',time(),'type=datetime&format=MM, dd, yyyy hh:ii');
	 * 
	 * @url http://trentrichardson.com/examples/timepicker/
	 */
	function datepicker($name, $datestamp = false, $options = null)
```

For instance:

```php
$text = e107::getForm()->('banner_startdate', $_POST['banner_startdate'],'type=date');
```

**Comment by pricey1981** [comment]
Great, thanks for the quick response. I seem to have a slight issue in that the pop-up calendar appears correctly when the page first loads (and you first click the element). But if I scroll down the page and click the element (which is now further up the page due to scrolling), the calendar pops-up in the place the element appeared in before scrolling. Hope that makes sense.

Is this likely to be something with my coding, or is there an issue with the js?

I can't currently see any issues with my coding.

**Comment by Moc** [comment]
I saw something similar happening in the admin area earlier. I think there's a bug in the javascript/css. It's on my list, but time is so scarce for me at the moment :)

**Comment by Jimmi08** [comment]
I noticed this too. But datepicker() with AnteUp plugin works (field inside table cell). Just when you use admin UI (generated plugin files) and your datepicker is on first tab, nothing happens. If you put in on next tab (like news are), it works.

**Comment by Jimmi08** [comment]
Just new info. Datapicker works fine in Firefox.Issue is in Chrome.

By the way, what is correct way to validate $_POST value before inserting to database? 
vartrue() function?  Thanks

**Comment by Moc** [comment]
Thanks for the browser check Jana. 

> what is correct way to validate $_POST value before inserting to database?

```php
e107::getParser()->toDb("value here"); 

// or, for numeric values
intval()
int()
```

**Comment by CaMer0n** [comment]
Could be related to an invalid path that I corrected today. Please update from Github and test again. Thanks

**Comment by Jimmi08** [comment]
No, it still there, but only on first page and just in Chrome (there are issues similar to it on net). If you are on next tab (news), it works.
Firefox:

![image](https://cloud.githubusercontent.com/assets/5429548/11163034/872bf7c8-8ac0-11e5-80d5-7d6be6aeccc2.png)
![image](https://cloud.githubusercontent.com/assets/5429548/11163035/8f944cee-8ac0-11e5-8e24-4ba3ac0eef27.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/5429548/11163040/d54590b8-8ac0-11e5-9ec0-c7a30e181d94.png)

![image](https://cloud.githubusercontent.com/assets/5429548/11163039/ce2f64f2-8ac0-11e5-982c-ac87132c70dd.png)

There were issue something like this already...

**Comment by pricey1981** [comment]
also happening in Microsoft Edge, but ok in IE

**Comment by mcpeace-maw** [comment]
The trigger field must have position (relative) declared in css, if not the pop-up will be reported at a parent tag that have position declared in css.

**Comment by Jimmi08** [comment]
I have still problem with this when using $frm->datepicker().  Is @mcpeace-maw solution something that should be done in core or can I solve this in plugin? And how?

**Comment by mcpeace-maw** [comment]
@Jimmi08 it was an idea, not tested, but you can try to add in the plugin css .e-datetime (this is the trigger class in news, check if it is the same) position:relative;. Datepicker div is appended to the body outside the page wrapper div.

**Comment by Jimmi08** [comment]
@mcpeace-maw thanks, it didn't help, but I found it was already solved. 
https://github.com/smalot/bootstrap-datetimepicker/issues/363
Just replaced new version from here: 
http://www.malot.fr/bootstrap-datetimepicker/
![image](https://cloud.githubusercontent.com/assets/5429548/13154195/149ce754-d678-11e5-8101-eaac3cf1251a.png)
