### ISSUE TITLE
Error - That is not a valid user.

### ISSUE THREAD

**Issue by SPooCK** [e107inc/e107#1227]
Hi, we recently updated our website from e107 v1 to v2 and imported all the old data. But there seems to be an odd problem with the users. Every time I try to display a user profile or go into my settings I end up with error page That is not a valid user. Although every user is able to enter into his profile with all his profile settings saved and also his MySQL data is full with the information. The error display on the redirecting page if I am user 22 will be webstiename.com/user.php?id.22. Thanks, hope there is a solution how to fix that.

**Comment by SPooCK** [comment]
Found a solution closing the problem. The solution was to put under 
$qs = explode(".", e_QUERY);
$self_page =($qs[0] == 'id' && intval($qs[1]) == USERID);

this 2 lines:

include_once(e107::coreTemplatePath('user')); //correct way to load a core template.
$user_shortcodes = e107::getScBatch('user');

**Comment by CaMer0n** [comment]
@SPooCK Would you mind doing a little test? Could you add the following at line 103 and then reload the page and share the info?
After: 

    $USER_TEMPLATE = e107::getCoreTemplate('user');

add: 

      var_dump($USER_TEMPLATE);

Thanks.

**Comment by SPooCK** [comment]
array(4) { ["view"]=> string(1748) "{SETIMAGE: w=250}
{USER_SENDPM} {USER_RATING} {USER_SIGNATURE} {USER_EXTENDED_ALL} {USER_ADDONS} {USER_COMMENTPOSTS} {USER_COMMENTPER} {USER_UPDATE_LINK}
Member {USER_ID} : {USER_NAME}{USER_LOGINNAME}
{USER_PICTURE} 	
{USER_ICON=realname} Real Name:
{USER_REALNAME}
{USER_ICON=email} Email Address:
{USER_EMAIL}
{USER_ICON=level} Level:
{USER_LEVEL}
{USER_ICON=lastvisit} Last visit:  
{USER_LASTVISIT}
{USER_LASTVISIT_LAPSE}
Site Stats
Joined 	{USER_JOIN}
{USER_DAYSREGGED}
Visits to site since registration 	{USER_VISITS}

    {USER_JUMP_LINK=prev} {USER_JUMP_LINK=next} 

{PROFILE_COMMENTS} {PROFILE_COMMENT_FORM} " ["extended"]=> array(2) { ["start"]=> string(0) "" ["item"]=> string(166) " {EXTENDED_ICON}{EXTENDED_NAME} {EXTENDED_VALUE} " } ["addon"]=> string(110) " {USER_ADDON_LABEL} {USER_ADDON_TEXT} " ["list"]=> array(3) { ["start"]=> string(606) "
Registered members: {TOTAL_USERS}

{USER_FORM_START}
Show: {USER_FORM_RECORDS} Order: {USER_FORM_ORDER} {USER_FORM_SUBMIT}
{USER_FORM_END}


{SETIMAGE: w=40} " ["item"]=> string(275) " " ["end"]=> string(26) "
  	Member 	Email Address: 	Joined
{USER_PICTURE} 	{USER_ID}: {USER_NAME_LINK} 	{USER_EMAIL} 	{USER_JOIN}
" } } 

I hope it helps.

**Comment by CaMer0n** [comment]
Thanks. Are those templates still copied over? I would need the output when the blank page is occurring. Is this what you posted? Thank you.

**Comment by SPooCK** [comment]
Since I copied the templates I can't get the blank page which is needed and this is info after the templates have been copied.

**Comment by OTroccaz** [comment]
I have the same problem in a temporary site. Here's the output :
array(0) { }

**Comment by CaMer0n** [comment]
@SPooCK @OTroccaz Is this still an issue? There were some similar bugs corrected recently. Thanks

**Comment by OTroccaz** [comment]
Since the templates have been copied, every thing is fine. I will have to develop a new e107 site soon: I will test and see.
Thanks!

**Comment by CaMer0n** [comment]
Thank you! :+1:

**Comment by Moc** [comment]
@OTroccaz Have you had a chance to test if this issue is still present? :)

**Comment by OTroccaz** [comment]
@Moc Not yet. Maybe you can close this issue and see later if the problem appears again?

**Comment by Moc** [comment]
Sounds like a plan. Please do let us know if the problem appears again. Closing for now.
