### ISSUE TITLE
User Settings - Return Blank Page

### ISSUE THREAD

**Issue by SPooCK** [e107inc/e107#1228]
Recently I updated from e107 v1 to v2 and now when I click "Settings," or try to edit a user's details, I get a blank page. The site is still there, just no menu or anything other than the background in the middle of the page where the details should be. I guess probably the problem is somewhere in usersettings.php but don't know why is doing it. Hopefully someone have an idea how to fix this problem.

**Comment by SPooCK** [comment]
Problem solved: 
Copy all templates from e107_core/templates --> e107_themes/templates

**Comment by MikeyGMT** [comment]
This works TY!

**Comment by Moc** [comment]
@MikeyGMT Did you get the same issue after upgrading from v1 to v2? If yes, then apparently there may be a bug. Which theme were you using on v1?

**Comment by MikeyGMT** [comment]
One of my oldest sites, (originally on .6 something - older than wordpress :100:  ) upgraded from 1.0.4 earlier this month. 
It had a really old theme - custom copy of jayya or similar.  
Think we just need to advise folk to copy the template folders post upgrade.
