### ISSUE TITLE
Question - Theme Manager

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1230]
In Site Theme - Layouts section, on Visibility Filter column is loaded from theme.xml file just first custompages tag for every layout, the rest of custompages tags you need to add them manually. For example, if in theme.xml file at  "default-home" layout I have custompages: first row/tag FRONTPAGE and next row/tag contact.php, on Visibility Filter at "default-home" layout is displayed just FRONTPAGE, so I need to add contact.php manually. I have try it on 2 different installations (old installations but updated) and it is the same. The question is, that is normal?

**Comment by CaMer0n** [comment]
Does this work?

    <custompages>FRONTPAGE /contact.php</custompages>

**Comment by mcpeace-maw** [comment]
Yes but "/" is in his row so I try it just without / just with space and it works. So now the page names must be all in 1 row with spaces between them like it was on v.1 and not every page with his <custompages> tag like it was on v.2 alpha. OK, now I know, thanks.

**Comment by CaMer0n** [comment]
That's correct. It is 
     
     <custompages>
and not: 

     <custompage> 

It makes theme upgrading easier, so that the developer can just copy paste the $CUSTOMPAGES value straight in on one line.
