### ISSUE TITLE
question to media manager

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1239]
Hi, I ask here because I can put images here very easy. I have the same form for admin and frontend. 
It uses datepicker, imagepicker and iconpicker from e107::getForm();

In admin area it works. Datepicker works on frontend too. What I need to add to my theme to get media manager works on frontend?  I mean - how open it in modal window like in admin area?

Admin:
![image](https://cloud.githubusercontent.com/assets/5429548/11195633/332ae036-8cb3-11e5-9829-81946fffe28a.png)

Frontend: 
![image](https://cloud.githubusercontent.com/assets/5429548/11195724/b4ba53f2-8cb3-11e5-8f19-670c21d6f3f7.png)

It opens this url:
![image](https://cloud.githubusercontent.com/assets/5429548/11195688/83222f5e-8cb3-11e5-9a2e-699f3d941aa3.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I suggest to look at the bootstrap3 documentation on modal windows. It will help you with that.

**Comment by Jimmi08** [comment]
Sorry, this was not a point. I know how modal windows work. The content of imagepicker() in admin and in frontend is different.  When I take datepicker() - it adds needed files at frontend.  With imagepicker() there is no header (title Media manager) and close button.  So can be this function used on frontend? Thanks

**Comment by CaMer0n** [comment]
Admin uses the $ADMIN_MODAL template. You need to define a template for your modal as per the bootstrap documentation.

**Comment by Jimmi08** [comment]
Thank you. Although you forgot to mention that the most of script doing this is in admin.jquery.js. Without it, modal doesn't work (either $ADMIN_MODAL)

I think it should work the same way as datapicker(). If it is used, imagepicker() should insert all needed script and code into page itself. But I got it to work in theme, so for me it's solved for now.

I can't make from all users admins, and just admins have access to admin area. 

![image](https://cloud.githubusercontent.com/assets/5429548/11325751/393441b4-9156-11e5-82c4-8d6b02ac8329.png)

**Comment by CaMer0n** [comment]
Happy you got it solved. :+1:
