### ISSUE TITLE
usersettings - optional extended user fields showing as required

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1240]
I have some user extended fields which I have set the Required field to "No - Show on signup page".

However, if left blank on the User Settings page a field appears saying "Please fill in this field."

Looking at the html for the page, the input has "required".

Not sure if it's related but my theme is Bootstrap 3. Have been looking through the usersettings_shortcodes.php file and see that some things are different for Bootstrap 3. Can't see where this erroneous "required" is being added though.

Edit: I think it is happening here.. e107_handler/user_extended_class row 709:

    $required	= vartrue($struct['user_extended_struct_required']) ? "required"  : "";
needs changing to

    $required	= (vartrue($struct['user_extended_struct_required']) == 1? "required"  : "");

**Comment by CaMer0n** [comment]
@pricey1981 thanks for the fix! :+1:
