### ISSUE TITLE
toDb not parsing correctly on it's own!

### ISSUE THREAD

**Issue by septor** [e107inc/e107#1243]
Let me set the scene for the play. It was a dark and stormy night.. oh, oops, wrong website! Let me start over!

Be warned, this is a long winded issue. If you want to understand the problem you need to read the entire thing. I would shorten it up, but it's a complex issue that took a lot of time to figure out.

I'm writing an IRC quote displaying plugin. As anyone who uses a popular IRC client knows, most of the time usernames are displayed in a `<septor>` like format. This means when a quote gets put into the database it needs to convert the < and > characters since they are also used in HTML (and XML, and probably other things). In the backend I do this with `htmlspecialchars(addslashes($data))`. **This is not safe!**

While writing the frontend submit quotes page I asked myself, and then @Moc, "What's the best way to parse the textarea before putting it in the DB?". I know of toDb(), in fact I considered it but I was worried it would kill the < and > or do something funny with it. @Moc suggest I try anyways.

Bad news, it doesn't perform as desired. It parses it.. somehow. But I don't know because when I try and return it on the frontend with toHtml() (no parameters), it displays nothing. When I try and edit the field in the backend it displays nothing.

However, I can get it to display correctly on the frontend if I remove the toHtml call, but then there's no line breaks, `<br />`. I can get it to display on the frontend, but not the backend, if I use `toHtml($data, false, 'BODY');`, but this doesn't fix the backend problem. It still displays nothing.

On the backend, while using toDb to insert the data, if I go to edit the item the textarea is blank where the quote should be. However, if I paste **the same quote** into the textarea (the blank textarea), it returns 'No changes detected, blah blah blah'. The same thing happens if I enter nothing into the textarea. I have to input something completely different for it to save the changes.

Now you're asking yourself, "Well, then, how do I save something as simple as `<septor>` to the database, be able to reliably edit it from the backend and still display it on the frontend as it should be?", honestly, you can't. Not without using some tricks and **making** it work. At least not safely (using toDb).

You **can** get what you want, but passing your data in the backend through something like: `$tp->toDb(htmlspecialchars($data));`. At least, that's how I'm going to do it for now.

So, easy to follow steps on how to replicate this (@Moc has also done this, so I don't think it's just me):

1. Create a database table with a text field.
2. Enter a random IRC quote (I used [this](http://chickfights.us/?id=379&nomore) for my tests).
3. Have the data saved, in the backend, with something like `$new_data['quote'] = e107::getParser()->toDb($new_data['quote']);` inside the beforeCreate() function.
4. Pull the data onto the frontend with `$tp->toHtml($data);`.
5. Witness nothing displaying.
6. Head back to the backend. Attempt to edit the info, you clearly messed something up, notice nothing being displayed.
7. Change your save call to pass `$new_data['quote']` through `htmlspecialchars()` **before** you pass it through `toDb()`.
8. Notice how everything works fine, even if it's not the way it should.

Let me know if you have any questions. If you have any feedback on what **I** could maybe do differently to make it work as intended without having to pass it through htmlspecialchars first. If you can't reproduce this, tell me what you did!

**Comment by Moc** [comment]
In summary:

```php
$rawquote = "<septor> I am testing IRC quotes"; 
$todb = $tp->toDb($rawquote);
``` 

Nothing is returned for the $todb variable, whereas I would expect:

```php
&lt;septor&gt; I am testing IRC quotes
```

**Comment by willem010** [comment]
i'm not really sure but this looks an awefull lot like my bodytext issue. 
i'm glad to see u guys pinpointing it to todb fuction

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/1035

**Comment by CaMer0n** [comment]
You could use use [code]: 

    $rawquote = "[code]<septor> I am testing IRC quotes[/code]";
    $tp->test($rawquote);

or
$rawquote = "<septor> I am testing IRC quotes"; 
toDb($text, true, false, 'no_html')

**Comment by septor** [comment]
Well, that works a treat.

Thanks, @CaMer0n!
