### ISSUE TITLE
Media Manager - Category creation not available

### ISSUE THREAD

**Issue by csjjpm** [e107inc/e107#1246]
I have just upgraded from 1.4 to 2 using the latest zip from github.  The upgrade went well and I am just learning the new approach.
I have a WAMP setup.
I have a problem though.  I can upload media but I cannot create media categories, I get an error 'Category creation not available'
How do I fix this?
thanks
Paul

**Comment by pierre0042** [comment]
I have the same question :)

**Comment by CaMer0n** [comment]
Categories are created by plugins, not by admins. The only exception is the gallery plugin.

**Comment by pierre0042** [comment]
I don't understand your comment?

I am speaking of /e107_admin/image.php?mode=cat&action=create

**Comment by CaMer0n** [comment]
I guess my question should be, what kind of category are you attempting to create?

**Comment by pierre0042** [comment]
Just a music category for mp3 files.

But it seems to be working now for me.
