### ISSUE TITLE
Custom legacy Plugin SEF url -> blank page

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1247]
Hi, I´m reading a loot about people issues with e_url.php and url() function, but when I enter on the url: http://localhost:8000/nestor/e107v2Stable/tournaments I just get a blank page, no errors or anything, even on debug mode.

My e_url.php looks like:
`
if (!defined('e107_INIT')) { exit; }

class ebattles_url // plugin-folder + '_url' 
{
	function config() 
	{
		$config = array();
	
		$config['events'] = array(
			'regex'			=> '^tournaments/?$',
			'sef'      => 'tournaments',
			'redirect'		=> '{e_PLUGIN}ebattles/events.php',
		);
				
		return $config;
	}	
}

`

If I do a dump on events.php of the e107::url('ebattles','events'); it returns a relative valid url.

If I look into admin panel > settings > URL configuration > Redirects it shows me it the right way:
Key > 'events'
Regular expression > 'http://localhost:8000/nestor/e107v2Stable/tournaments/?$'
Url > '{e_PLUGIN}ebattles/events.php'

(withouth quotes ' )

I tested some thinks I found here on the Issues hub, but nothink seems to work.
I also tried editing logs plugin e_url, and it works with my modifications, and back to the original so, I dont know whats happening.

My e107 info: v2 stable fresh install, ebattles plugin for e107 v1 (legacy) directly installed.
Plugin works if I enter the old url like ebattles/events.php

If someone can point me to the right direction I would be pleased, maybe Im missing some kind of db setup or code setup for this to work.

Thanks!

**Comment by CaMer0n** [comment]
Please check how /e107_plugins/ebattles/events.php loads class2.php. 
It should be loaded like this: 

    if (!defined('e107_INIT'))
    {
    	require_once("../../class2.php");
    }

**Comment by nesjett** [comment]
It was loaded directly as require_once("../../class2.php");
but adding 
if (!defined('e107_INIT'))
{
    require_once("../../class2.php");
}

doesnt makes any difference.

Thanks for your attemption

**Comment by nesjett** [comment]
Problem solved, I was just calling the require_once direclty.

Do you mind why this issue can occur? 

Thanks

**Comment by CaMer0n** [comment]
Yes, index.php includes the plugin's script file when using SEF URLs in this way. So we must prevent class2 from being loaded twice using the if() statement above.
