### ISSUE TITLE
$frm->number and the min value=0

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1248]
```html
<tr>
<td>" . LAN_TURNIER_ADD_36 . "</td>
<td>". $frm->number('buyin', vartrue($anz_spieler) ? $anz_spieler : 10, 0, array('min'=>1, 'max'=>9999, 'required'=>0)) . "</td>
</tr>
``` 

if i set the `'min'=>1` then is the witdh of the field is 77px if set the ` 'min'=>0` then is the witdh 174px, why?

**Comment by schlrech** [comment]
if change line:577 in form_handler.php
from:
$min = varset($options['min']) ? 'min="'.$options['min'].'"' : '';
to:
$min = varset($options['min']) ? 'min="'.$options['min'].'"' : 'min=0';
then it's ok

**Comment by schlrech** [comment]
and the number is not right align in the field

**Comment by CaMer0n** [comment]
@schlrech Is this still an issue?

**Comment by schlrech** [comment]
yes it is
