### ISSUE TITLE
HTTPS in jquery url

### ISSUE THREAD

**Issue by ronaldocb** [e107inc/e107#1250]
A sugestion: use https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js (with https) in e107_handlers/js_manager.php.

If e107 configured with https this API show in browser security problem.

**Comment by CaMer0n** [comment]
Thanks. Are you using the latest github version of e107?

**Comment by Moc** [comment]
@ronaldocb Please update from github and see if the issue persists. If it does, please let me know and I'll reopen. Closing this issue for now.
