### ISSUE TITLE
Facebook Connect

### ISSUE THREAD

**Issue by TheDeathRaw** [e107inc/e107#1251]
Hi all,

I have a problem when i try to use Facebook connect for a registration.

[4]Signup failed! Can't access user email - registration without an email is impossible.

![captur_e](https://cloud.githubusercontent.com/assets/16007612/11398632/858a17ae-9382-11e5-8c1c-a98650ca8013.JPG)

Can't login too.

**Comment by TheDeathRaw** [comment]
Something new?

**Comment by lonalore** [comment]
Same issue with signup using GitHub profile.

```
Hiba
[4]Signup failed! Can't access user email - registration without an email is impossible.
Array
(
    [user_loginname] => GithubMD0399
    [user_email] => 
    [user_name] => Sándor Juhász
    [user_login] => Sándor Juhász
    [user_customtitle] => 
    [user_password] => ...
    [user_sess] => 
    [user_image] => https://avatars.githubusercontent.com/u/6043821?v=3
    [user_signature] => 
    [user_hideemail] => 1
    [user_xup] => Github_6043821
    [user_class] => 247
)
```

**Comment by CaMer0n** [comment]
@lonalore @TheDeathRaw in admin -> Preferences -> User Registration/Login , do you have "User login method" set to "Username and Password" ?

**Comment by lonalore** [comment]
No, it is set to "Username/email and password".
In my case, Facebook login works properly, but the GitHub not.

**Comment by CaMer0n** [comment]
Github is working (on e107.org) last time I checked.

**Comment by CaMer0n** [comment]
HybridAuth recently updated in e107. Facebook tested. Github working on e107.org
