### ISSUE TITLE
News Category Icon

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1253]
I'm looking to create a custom template for the news_categories_menu. I've noticed that sc_news_category_icon appears in both e107_handlers/news_class.php and e107_core/shortcodes/batch/news_shortcodes.php.

It is the version from news_class.php that seems to be called when using NEWS_CATEGORY_ICON in the news_menu_template.php file.

Neither of these shortcodes seems to cater for news categories that have glyphs for icons, which means the stock shrotcode renders a broken image.

My question is, is this something that needs fixing in news_class.php, or is there a way to override that shortcode using the normal override folder?

Secondly, is there a "correct" way to render the glyph, other than checking if $this->cat('icon') includes ".glyph"?

**Comment by Moc** [comment]
I'll check the {NEWS_CATEGORY_ICON} shortcode asap. 

> Secondly, is there a "correct" way to render the glyph, other than checking if $this->cat('icon') includes ".glyph"?

http://e107.org/developer-manual/classes-and-methods#parser`
```php
e107::getParser()->toGlyph() 
//and
e107::getParser()->Icon()
```

**Comment by realG** [comment]
I've just come across this now and was about to log a new issue, good I did a search first :)

@Moc , any chance {NEWS_CATEGORY_ICON} could be fixed in core shortcodes to handle glyphs?

**Comment by CaMer0n** [comment]
@realG @pricey1981 That should be working now.

**Comment by Moc** [comment]
@realG Thanks for searching! :)
