### ISSUE TITLE
new install issues (combining issues)

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1254]
When setting up a new server (PHP Version 5.5.9-1ubuntu4.14) we ran into a lot of issues already mentioned here. 

starting with #1102 / #1207   (same issues)
followed by #1208 #1211 and more related issues.

my admin solved the issues, all at once.
he told me there was a conflict between open_base dires and session paths.
(dunno what i just said.. :P  but after his help, the server works pretty much without error.)

hope this helps.

**Comment by CaMer0n** [comment]
Thank you. More information about the conflict would be very helpful so that an alert could be added to the admin area for such cases.

**Comment by willem010** [comment]
this is about all the info i got:
Include the session.save_path in the open_basedir of the vhost.

it would help if i knew what i am talking about, ;)

**Comment by Moc** [comment]
> Include the session.save_path in the open_basedir of the vhost.

I'm out of my league here as well but I think that doing this could potentially be dangerous (security wise):
https://bugs.php.net/bug.php?id=42077

**Comment by willem010** [comment]
sounds like an issue to me.. i will report this back to my linux guy.

(i will ask him to enter this topic, he's short on time, but maybe he wants to help a bit.)

**Comment by CaMer0n** [comment]
@Moc it is using files.

**Comment by Moc** [comment]
@CaMer0n Yeah my question was meant to say: why is it using files INSTEAD of sessions stored in the database? I'm just reading up on it and having it in the database seems to make more sense to me. Bt Like I said, I'm somewhat out of my league here.

**Comment by willem010** [comment]
i now do know some of these issues are caused by ownership and permissions.
my server is not using the same accounts for ftp and www. creating issues where e107 does not own certain folders and cant change file attributes in there..
(which in some cases is annoying, files created by e107 cannot be changed by ftp user and vise versa )

i do not think the database issues mentioned here were caused by this, but some of the other issues did.

**Comment by Moc** [comment]
Closing this as discussion seems to be no longer relevant with the latest tweaks to session handling. Please let us know if the issue needs to be re-opened.

**Comment by willem010** [comment]
You can close all issued by me.
Haven't been designing sites for over a year now.

Good to see you guys are still here working on it tho!
Maybe I will check out recent progress when there is some spare time.
Keep it up.
