### ISSUE TITLE
Trouble with database verification

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1255]
Hello,

When I check the database validity, it says that I have a problem in table 'user_extended' with 3 fields :

user_extended   user_extended_id    Field missing!  should be
INT(10) UNSIGNED NOT NULL DEFAULT '0'

user_extended   user_hidden_fields      Field missing!  should be
TEXT

user_extended   user_extended_id    Index missing!  should be
PRIMARY (user_extended_id);

The problem is that these fields and the index are not missing, I can see them in phpmyadmin.

And if I try to fix these issues with the button "fix issues", I got those errors :

Warning
Update Unsuccessful [ALTER TABLE `e107_user_extended` ADD `user_extended_id` INT(10) UNSIGNED NOT NULL DEFAULT '0']
Duplicate column name 'user_extended_id'
Update Unsuccessful [ALTER TABLE `e107_user_extended` ADD PRIMARY KEY (user_extended_id) ]
Multiple primary key defined
Update Unsuccessful [ALTER TABLE `e107_user_extended` ADD `user_hidden_fields` TEXT ]
Duplicate column name 'user_hidden_fields'

What could be wrong ?
I am trying to upgrade e107 from 1.x to 2.0.

**Comment by CaMer0n** [comment]
Thank you for posting. Please try with debug enabled: 

    e107_admin/db.php?[debug=basic+]mode=verify_sql

.....then find the user_extended table date and paste the left and right column of information here so we can check it.  
Thanks you.

**Comment by pierre0042** [comment]
I have this during the check
https://imgur.com/lx58Uhi

how can I find the table date ?

**Comment by pierre0042** [comment]
This is how my table look like :
https://imgur.com/LoX7wtR

**Comment by pierre0042** [comment]
Hello, I am still stuck with this, can I check anything else ?

**Comment by CaMer0n** [comment]
@pierre0042 Thanks for those screenshots. Would you mind also sending sending one of the content of the table: `e107_user_extended_struct` ?

**Comment by pierre0042** [comment]
Thanks for your answer.
Here is the table export :

[e107.zip](https://github.com/e107inc/e107/files/93687/e107.zip)

**Comment by CaMer0n** [comment]
@pierre0042 Thank you. Could you also send me a Structure/Data dump of a few rows of e107_user_extended? Thanks

**Comment by pierre0042** [comment]
Here are the first 20 rows

[e107_user_extended.sql.zip](https://github.com/e107inc/e107/files/104576/e107_user_extended.sql.zip)

**Comment by pierre0042** [comment]
Thanks, will you release a release 2.0.1 soon?

**Comment by CaMer0n** [comment]
Yes, that's the plan.

**Comment by pierre0042** [comment]
Great, thanks!

**Comment by tgtje** [comment]
Having EXACTLY same issue, new fix does not offer solution  (some more extended fields is only difference, not the message)

**Comment by CaMer0n** [comment]
Please share your *_sql.php file for testing

**Comment by tgtje** [comment]
Please provide a mail address (previous messages never arrived)



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by Moc** [comment]
I am pretty sure this issue has been resolved by now. If not, please feel free to let us know and I'll re-open.
