### ISSUE TITLE
Feature request: friendly url for thumbnailer

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1257]
the thumb.php script uses a lot of params, resulting in non cachable items,
when a friendly uri is used (i.e. /i/100/100/imagename or /i/scaled/100/100/imagename ) this.is no longer an issue.

the uri format is debatable, but i suggest something short.

**Comment by CaMer0n** [comment]
@willem010 Please give it a try. You'll need to add some lines to your .htaccess file. (see e107.htaccess)

**Comment by willem010** [comment]
cool! 
i will check it out this weekend. 
a huge thank you!

**Comment by willem010** [comment]
i have been trying to figure out what you did here, but it didn't have the effect i was expecting.

this sort of does what i want. (cropping / sizing probably should be different . )

```
RewriteRule ^img/s/([0-9]+)/([0-9]+)/(.*)\.(jpg|jpeg|png|gif)$ thumb.php?src=$3.$4&w=$1&h=$2 [NC,L]
RewriteRule ^img/s/([0-9]+)/(.*)\.(jpg|jpeg|png|gif)$ thumb.php?src=$2.$3&w=$1 [NC,L]

RewriteRule ^img/([0-9]+)/([0-9]+)/(.*)\.(jpg|jpeg|png|gif)$ thumb.php?src=$3.$4&aw=$1&ah=$2 [NC,L]
RewriteRule ^img/([0-9]+)/(.*)\.(jpg|jpeg|png|gif)$ thumb.php?src=$2.$3&aw=$1 [NC,L]

```
this would be nice. (original sized img)
` RewriteRule ^img/(.*)\.(jpg|jpeg|png|gif)$ thumb.php?src=$1.$2 [NC,L]
`
but doesnt work without the h param.

**Comment by CaMer0n** [comment]
@willem010 What result did you get? What is currently in the code does exactly what you mentioned. To use your example, the generated URL would look like this: 

    /media/img/500x500/2014-10/lock_n_load.jpg

or, to crop:

    /media/img/a500xa500/2014-10/lock_n_load.jpg

I have tested using https://gtmetrix.com/ and the performance improvement is there. I will upgrade e107.org shortly so you can see it in action.

**Comment by CaMer0n** [comment]
For reference: https://gtmetrix.com/reports/e107.org/17edmTWT 
Specifically, see "Remove query strings from static resources"

**Comment by willem010** [comment]
ah, thats the url i should have tested haha.. i'm not that great at reading regexps.

i did look for a changed url, but both my frontpage news and featurebox still use the thumb.php link,
now i realize the news part on my frontpage is using the latest_news plugin and this probably uses an older method for creating image links, but i would have expected the featurebox to use em.. 
o well, probably cache, or i didn't really woke up this morning haha.

anyway, thanks again
this should really help on server load as cloudflare now takes a huge load of our back.

**Comment by CaMer0n** [comment]
Any URLs in the content (such as added by TinyMce) would need to be resaved in order to update the links. Others rendered from a separate image field should auto-update if they are using thumbUrl()

**Comment by willem010** [comment]
jep, noted.

btw, a similar trick for the .js files would also help.

just my 2 cents again.

**Comment by CaMer0n** [comment]
@willem010 Try the "JS/CSS Cache" - it's not a friendly URL, but it should achieve the same performance boost.

**Comment by willem010** [comment]
yep, that does the trick (Y)
totally missed that one again.. haha.

btw, this also makes google fonts availabe using 
e107::css('url', "//fonts.googleapis.com/css?family=fontname;"); in theme.php :) )

which didnt work before without adding &amp; to the url ..

**Comment by willem010** [comment]
hmm.. just updated my xamp to latest git..  

(it does mention experimental..  but i do have a few issues with using that js/css cache.)
first notice.. for the first time script consolidation started working .. but only when this cache is enabled.
when disabled it doesnt consolidate.  
(the settings disable consolidation / disable consolidation cache have no effect at all
i did delete cache on every change)

when turned on i do get a few errors.

Uncaught ReferenceError: ejs_preload is not defined(anonymous function) @ (index):46
(index):333 GET http://localhost:81/e107_themes/GFM//e107_themes/GFM/images/player_icons.png 404 (Not Found)
(index):333 GET http://localhost:81/e107_themes/GFM//e107_themes/GFM/images/flags.png 404 (Not Found)
(index):333 GET http://localhost:81/e107_themes/GFM//e107_themes/GFM/images/emo.png 404 (Not Found)
player_widget_js.72d4c4ecf4244af0ed37d5b85327af1f.js:1 GET http://localhost:81/e107_themes/GFM//e107_themes/GFM/images/voting.png 404 (Not Found)

which only appears when js cache is on.
when turned off, all is ok.. but no consolidation, and params on all js and css.

some debugging .. 
the consolidated script has the ejs_preload function in there.
my consolidated scripts are running ok, 
included bootstrap functions appear to run. (which means there are no errors in my scripts)
no clue why it doesnt see ejs_preload. 
(from experience i think it has something todo with comment lines.. when you add a file
without adding a linebreak first, there is a chance the last line of prevous file was commented out, resulting in an commented out first line of second file.. ? .. just guessing here )

and i have no idea why the theme url is different from the not consolidated one..
but it appears there  is something wrong in the css consolidation adding the path to the theme twice.

**Comment by willem010** [comment]
o.. and the most important part i forgot to mention.

the new short url is nowhere to be found. 
all scripts just output the old fashioned thumb.php?src= url for the images.

**Comment by willem010** [comment]
ok, after some bug hunting sessions.. 
i found 2 issues, one with consolidation as mentioned before
and one with preload images combined with consolidation.

(with preload images turned off, i can get everything to work.
not the way it should be.. but i'm not complaining haha.)

@CaMer0n  do you want me to add new issues for this?

**Comment by CaMer0n** [comment]
Just re-opened this one, that's fine. I found another issue with the fontello.css messing up shared buttons.

**Comment by CaMer0n** [comment]
btw. Your Admin -> Preferences -> Javascript should look like this: 

![javascript_settings](https://cloud.githubusercontent.com/assets/2825679/12928750/254a7ff4-cf24-11e5-9855-5007eb50b881.png)

**Comment by willem010** [comment]
haha, i had it exact the opposite of this.

i want the scripts to be consolidated into 1 scripts.. so i would think disable consolidation would turn this off, 
i want zlib compression on the consolidated script.. so would think enabling it would add zlib on the js. (which my server will do anyway.. ).
disable the cache.. using it seems ok to me? lol  please use cache.. save every bit.
and browser cache.. please cache as much as possible .. :P

but most of these options do not seem to have any effect anyway.

is there any doc on what these options actually do?

**Comment by CaMer0n** [comment]
All the preferences above are for an older js management method which loads a url pointing to e_jslib.php and has PHP handle everything on the fly. The new "cache" system, just loads all the files and saves them in one compressed file located in e107_web/cache.

**Comment by willem010** [comment]
ok. from now on im setting those like you said. will leave it at that.

for the img url topic.
i did a quick rewrite of my plugins to use the new short uri on our production server.
cloudflare now takes > 70% of the load where it was just 20 before.. 
(which is a huge deal on a 800mb traffic-a-day website.)
the server load dropped dramaticly. a money saver.
just perfect

**Comment by CaMer0n** [comment]
:+1: Thanks for that.

**Comment by CaMer0n** [comment]
Would you consider running a report on your site and posting the URL?
https://gtmetrix.com/

**Comment by willem010** [comment]
![image](https://cloud.githubusercontent.com/assets/6122908/12932775/dd7b4e5e-cf84-11e5-9e55-b8595d119f6d.png)
this should show it :)
gtmetrix still doesnt like the frontpage of gabber.fm very much  .. 
but that still needs latest git (consol. not working there yet).  and it uses a lot of external scripts.
 gt metrix now scores 84 / 72 %
the big change here is it is using short uri (for 1,5 days now) on the covers and dj thumbnails throughout the site. this is what cloudflare now caches.

**Comment by CaMer0n** [comment]
Excellent! Thank you!! :+1:

**Comment by CaMer0n** [comment]
Closing this, as it appears to be reliable from what I can tell. Please re-open if necessary.
