### ISSUE TITLE
question -  how to set option values in select dropdown different than 0,1,2...

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1261]
When I fill ['writeParms']['optArray']  with array of names for dropdown, is there way how to set option value (key)?  For examle, not start with 0 or 10,20 etc... 

![image](https://cloud.githubusercontent.com/assets/5429548/11608354/1657ad8c-9b67-11e5-9ef4-7dee37a43c5f.png)

Thanks

**Comment by septor** [comment]
I have an idea for this. I'll elaborate more when I get to my computer.

**Comment by lonalore** [comment]
You can set option array (with key+value pairs), like:

```php
array(
  'title'  => 'Title',
  'type'  => 'dropdown',
  'writeParms' => array(
    0 => 'Label for value 0',
    1 => 'Label for value 1',
    ...
    'foo' => 'bar',
  ),
);
```

**Comment by Jimmi08** [comment]
I thought this was way (to send keys), but I probably made some typo errors, but with your code it works.

**Comment by septor** [comment]
You can still do it the way you were trying:

```
'writeParms' => array('optArray' => array(
    0 => 'one',
    1 => 'two',
)),
```

**Comment by Jimmi08** [comment]
Yes, thank you too. I use dropdown always this way:

``` $this->fields['myfield']['writeParms']['optArray']= ```

**Comment by CaMer0n** [comment]
Are you trying to set the default key value?

    $this->fields['myfield']['writeParms']['default']= 1;

**Comment by Jimmi08** [comment]
No, but your example is very usefull too. Thanks. I needed different keys for select options (I had problems with syntax, but code example from lonalore helped)

![image](https://cloud.githubusercontent.com/assets/5429548/11763380/b2d15ab8-a108-11e5-9bb3-eba6fee48bc4.png)
