### ISSUE TITLE
Signup main admin notification

### ISSUE THREAD

**Issue by OTroccaz** [e107inc/e107#1262]
Hello,
I have enabled the mail notification for user signup, but no mail is sent when someone registers. However, the test procedure on e107_admin/notify.php works. Any idea?
Thanks.
Olivier

**Comment by LaocheXe** [comment]
Have them check the junk mail, not to sure, right now I am running into an weird 500 error for user sing-ups

**Comment by Moc** [comment]
As @LaocheXe, make sure that the email did not end up in the spam folder. 

If that's not the case, I'd suggest changing the email method settings to smtp (Preferences > Email & Contact). Check with your hosting provider if you don't know the SMTP information to fill in.

**Comment by OTroccaz** [comment]
The parameters are already set to SMTP and the test procedure is working.

**Comment by martyshep** [comment]
I have same issue. I do not get notified of new users signup but Test email notification works ok.

**Comment by CaMer0n** [comment]
@martyshep @OTroccaz Could you please update from Github, and then add the following to your e107_config.php file? Then trigger some events in the usual way and check the system logs. 

    define('e_DEBUG_NOTIFY',true);

**Comment by OTroccaz** [comment]
Thanks CaMerOn!
I have updated from Github (every day in fact ;-) ), added the line in config.php and tested ... still nothing. And there's also nothing in the admin log. Is there somewhere to find a bug trace?

**Comment by CaMer0n** [comment]
@OTroccaz There's no NOTIFY_DBG entries in the System Logs?

**Comment by OTroccaz** [comment]
I just tested on different sites, all hosted on the same server (IIS 7.5 and PHP 5.6.19)
None of these sites send a mail notification after user signup. More, for sites in French, the system logs records no action. For those in English, there is a NOTIFY_DBG recording such as:

Array
(
    [id] => user_signup_submitted
    [subject] => Event Triggered: user_signup_submitted
    [recipients] => Array
        (
            [0] => Array
                (
                    [mail_recipient_id] => 1
                    [mail_recipient_name] => My Name
                    [mail_recipient_email] => my.email@adresse.fr
                    [mail_target_info] => Array
                        (
                            [USERID] => 1
                            [DISPLAYNAME] => My Name
                            [SUBJECT] => Event Triggered: user_signup_submitted
                            [USERNAME] => My Name
                            [USERLASTVISIT] => 1458066182
                            [UNSUBSCRIBE] => 
                            [UNSUBSCRIBE_MESSAGE] => 
                            [USERCLASS] => 250
                            [DATE_SHORT] => &lt;span data-livestamp="1458117998">16/03/2016 : 09:46&lt;/span>
                            [DATE_LONG] => &lt;span data-livestamp="1458117998">Wednesday 16/03/2016 - 09:46:38&lt;/span>
                        )

                )

        )

    [prefs] => Array
        (
            [class] => 250
            [email] => 
            [include] => 
            [legacy] => 0
        )

    [message] => &lt;pre>Array
(
    [id] =&amp;gt; Test for user_signup_submitted
    [data] =&amp;gt; example data
)
&lt;/pre>
)_

**Comment by martyshep** [comment]
e107 v2.1.0 fixed the issue for me. I get notification now to my email when a user registers.  (If I put the line in config.php I don't get email I just get debug message)

**Comment by CaMer0n** [comment]
Thanks @martyshep

**Comment by OTroccaz** [comment]
It works also for me! Thanks @CaMer0n

**Comment by CaMer0n** [comment]
@OTroccaz You're welcome. :+1:
