### ISSUE TITLE
tinymce (bbarea) problem with YTB video 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1263]
I need to insert /embed YTB video, normal sharing iframe (without API).

When I use button in TinyMCE to insert video:
- it works before saving 
![image](https://cloud.githubusercontent.com/assets/5429548/11610552/bc1da5a2-9ba6-11e5-87c8-863808b1e6e0.png)
- after saving result code is:
![image](https://cloud.githubusercontent.com/assets/5429548/11610558/d0f95638-9ba6-11e5-8f36-88ecddfd407e.png)

When I did this manually (source code, insert code for embeding video from YTB)
- before saving (looks correct)
![image](https://cloud.githubusercontent.com/assets/5429548/11610564/f38138b0-9ba6-11e5-95f4-6a37bdfbe9fe.png)

- after saving:
![image](https://cloud.githubusercontent.com/assets/5429548/11610565/fc65b5d2-9ba6-11e5-8ad0-b5bf8c18b252.png)

Do I need to set something? Thanks

**Comment by tgtje** [comment]
Not sure (works for me) just use one ( 1 ) div class embed-responsive

<div class="embed-responsive embed-responsive-16by9"><iframe width="560"height="315"src="https://www.youtube.com/embed/uy5yYU8hOkE" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

i did NOT use the html code

**Comment by Jimmi08** [comment]
This is weird. With news it works, with my plugin not...  I will try to find what is different. Thanks

**Comment by Jimmi08** [comment]
Solved. Problems was mine, so I am closing this. - wrong field type in database, not text, but varchar.
Thank you to all for your help.
