### ISSUE TITLE
 After upgrade to V2 the contact page does not display the content

### ISSUE THREAD

**Issue by UmbrellaBitcoins** [e107inc/e107#1264]
The contact information is properly selected and added to the public but even if no information is shown on page
I made the upgrade to v2 and after that I do not carry a widget external script and disappeared contact page

any suggestions? I 'm using the theme : Basic

**Comment by tgtje** [comment]
Most likely (guessing since info is to little to work on) it is settings under preferences regarding html use and scripting. The external widget might need other calls as v2 uses different measures (security etc..)

**Comment by pierre0042** [comment]
I have the same problem: contact is empty after upgrade

**Comment by LaocheXe** [comment]
Again this is a theme issue, you need to add the core template of contact_template.php into your selected theme folder

e107_core/templates/contact_template.php
copy and paste into
e107_themes/yourtheme/templates/contact_template.php

**Comment by pierre0042** [comment]
e107_core/templates/ ok...
I thought it was e107_themes/templates/

**Comment by pierre0042** [comment]
With e107_core/templates/ I have now my contact page correctly displayed.
Thanks.
