### ISSUE TITLE
admin UI  -  readonly with type user

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1265]
I tested readonly with type dropdown, int, text... it works. 

But if I use it with type user, I can't get it display in edit view.
Without readonly it works as should be have.
![image](https://cloud.githubusercontent.com/assets/5429548/11623865/0888a372-9cd0-11e5-9f90-d09024c3d766.png)

With readonly is set true, displayed field is empy (with other types is displayed)
```		  'lasteditby' =>   array ( 'title' => 'Lasteditby', 
          'type' => 'user', 
          'tab'=>2, 
          'data' => 'int', 'width' => 'auto', 'help' => '', 
          'readParms' => 'idField=user_id&nameField=user_name', 
          'readonly'  => true,
          'writeParms' => '', 
          'class' => 'left', 'thclass' => 'left',  ),```

![image](https://cloud.githubusercontent.com/assets/5429548/11623929/854e2792-9cd0-11e5-89dc-09c5f19a67d1.png)

I tried to set WriteParms the same way as ReadParms, to set some value in init(), still empty.

I have set $listgry this way:
```protected $listQry      = "SELECT n.*,u.user_id,u.user_name FROM `#staff` AS n LEFT JOIN `#user` AS u ON n.lasteditby = u.user_id "; ```

Thanks

**Comment by lonalore** [comment]
This should fix it.

**Comment by Jimmi08** [comment]
Confirm. Thank you very much, this was really quickly.

**Comment by lonalore** [comment]
I created a pull-request with my changes.

**Comment by Moc** [comment]
Yep seen it, good job, thanks!

When @CaMer0n merges it, this issue can be closed ;)

**Comment by Jimmi08** [comment]
I am sorry, I didn't notice it was just pull-request. I wouldn't close it otherwise.

**Comment by CaMer0n** [comment]
It's done! Thanks @lonalore.
