### ISSUE TITLE
help tooltip with block-level size

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1270]
I noticed this, but I don't know if this can be solved. 
Maybe block-level size not to have 100%, just 90% ?

![image](https://cloud.githubusercontent.com/assets/5429548/11669640/18accede-9dfe-11e5-86e1-ae18387b0f3c.png)

**Comment by CaMer0n** [comment]
the tip just needs to be positioned above in this case.

**Comment by CaMer0n** [comment]
@Jimmi08 Which block-level field is that in your example image?

**Comment by Jimmi08** [comment]
@CaMer0n You don't use help field with block-level size field in core (or I didn't find it). Screen is from plugin. But if you add a help f.e. to news_title in newspost.php, you will see it. 

![image](https://cloud.githubusercontent.com/assets/5429548/12574013/1daf6dd8-c400-11e5-90d4-caec5a314eb8.png)
