### ISSUE TITLE
How to... add divider in admin menu in new admin UI

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1276]
It's just triviality, for saving time.

To add divider (line) to divide menu parts:
![image](https://cloud.githubusercontent.com/assets/5429548/11912904/1ecd5156-a652-11e5-86ee-2d345634ee6d.png)

```
    protected $adminMenu = array(
        ...
    'divider1'            => array('divider'=>true),
    ...
    'divider2'            => array('divider'=>true),
    ...
    );
```

**Comment by Moc** [comment]
Keeping it open for documentation reminder

**Comment by Jimmi08** [comment]
You can close this
