### ISSUE TITLE
Bug: Sign Up/500 Error/Subscribe Required

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1277]
URL: http://the63ar.x10host.com/
Bug: After filling out user registration form, hitting submit button the user ends up getting 500 Error
URL that the error happens on: http://the63ar.x10host.com/signup.php

PHP Version 5.5.30
PHP Warnings - allow_url_fopen: If you have Curl enabled, you should consider disabling this feature. and expose_php: Disabling this will hide your PHP version from browsers.

Browsers tested in Google Chrome and Microsoft Edge

The site still creates the user accounts, and it sends out the e-mail's to activate the accounts, but when creating them the 500 error shows up.

This is a fresh install from e107 v2.xx that was downloaded from GitHub today (12/20/2015), Sign Up page has Email, Password, Real Name, and Email Confirmation set as required, Avatar, and User Custom Title set to hide, Option to hide email set to display, Subscribe to content/mailouts set to require, and signature and password in email confirmation set to hide.

However in the activation e-mail (that my test dummy account that I just made) was sent and it currently shows the password, shouldn't that be hidden with ********??? Unless I am mistaken.

Trouble Shoot: Issue is having Subscribe to content/mailouts set to require - set to hide and no more 500 error.

**Comment by Moc** [comment]
Please check the HTTP apache error log as 500 errors provide further information in that log. This way it's easier to find out what's causing the error. Consult with your hosting provider if you don't know where your apache error log files are located.

**Comment by LaocheXe** [comment]
Sadly that host provider doesn't like to show the errors - was able to re-create the issue on my main site (blank page - no 500 error (even had e107 debugger enable and nothing)), error:

[Tue Dec 22 18:42:54 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/404.shtml, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:54 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/e107_web/js/scriptaculous, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:54 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/404.shtml, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:54 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/e107_web/js/scriptaculous, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:47 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/404.shtml, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:47 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/e107_web/js/scriptaculous, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:46 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/404.shtml, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2
[Tue Dec 22 18:42:46 2015] [error] [client X.X.X.X] File does not exist: /home/clancoy1/public_html/defiantz/e107_web/js/scriptaculous, referer: http://defiantz.org/e107_admin/users.php?searchquery=&filter_options=user_ban__2



Issue is when ***Subscribe to content/mailouts*** is set to required in the site prefs area

**Comment by CaMer0n** [comment]
is .htaccess correct? (using the data from e107.htaccess) ?

**Comment by Moc** [comment]
I am assuming this has been fixed by now. If not, please let us know and I'll re-open.
