### ISSUE TITLE
feature request : autoblock known vunarabilities for various cms systems.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1278]
It would be great if there is a way to enter known vulnerabilities for various cms systems, like people searching for wordpress hacks / patched e107 hacks etc. on my sites.

currently my server log shows a lot of attempts to a known xmlrpc.php wordpress hack, or attempts to find login pages etc for wordpres and joomla.

it would be great if those #$@@#! beep #@$@# are added to the blocklist automatically.
this would save me a lot of time.

btw,
there are downloadable blacklists out on the net. maybe adding an option to e107 to download and import directly to the ban list isnt a bad idea? im not quiet sure of the quality of those lists tho maybe someone into security knows more about this or has better ideas??

on an average day my site draws about 25 attacks.. i would like to see this number go down.

**Comment by LaocheXe** [comment]
http://www.spambotsecurity.com/zbblock.php

**Comment by Moc** [comment]
This is outside of the scope of the core. There are tools such as zbblock as posted above to help you out. There are plenty of proper blacklists already (google for 5G blacklist for example - it's quite effective I can say from experience, you'll found more tools on their website). 

I don't think this will be included as it will also need continuous maintenace to check the quality of the blacklists. This requires resources that we simply don't have.

**Comment by willem010** [comment]
cool. thanks for the tips. i will look into it later on.

**Comment by tgtje** [comment]
Just as comment for the readers that are unaware of the import function for blacklists in v2 : it is available (members/ban)...

**Comment by willem010** [comment]
so the second part of my request actually already exists 
haha .. thnx @tgtje 
totally missed that one.
