### ISSUE TITLE
quick question about image uri

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1281]
first of all.. i would like to take this opportunity to wish you all happy holidays 
and thank you for all the hard word you guys do!

I noticed in the admin section (plus og:images) a direct url to the images is being used.
no thumb.php, but a link to the image folder in the hash folder. (revealing the hash to the outside.)

we found this because my admin tried to disable php in the root of the media folder, but that didnt wort out because of this.

is this something that still needs to be done?
or did i just enter another request ?

**Comment by willem010** [comment]
no one to answer this?  i didnt think this was a hard one to answer ? :P
is this direct url in the og images something thats still on a todo list?
(or do i need to enter a feature request for this? )

anyway.. looking at the og:images, 
is there an (easy) way to add an ogimage to a page?

**Comment by LaocheXe** [comment]
I don't know would be a simpler answer and really I don't know - are the other images using the direct url?

**Comment by CaMer0n** [comment]
@willem010 Could you be a little more specific. Which part of the admin area, for images for what exactly? Thank you.

**Comment by willem010** [comment]
sure, let me elaborate on this a bit :

first, only the ogimages are important here, cause this exposes the hashed folder to the outside:
<meta property="og:image" name="og:image" content="http://localhost:81/e107_media/e741e482f0/images/2015-11/12247953_1001831499873822_6338143045580469932_o.jpg" />
(taken from my xamp ;) )
that should use the thumb.php instead. 

but more direct image urls are found in the news admin section
how to reproduce and expose the problem.. (how we found out about this) 

add 
php_admin_value engine Off
to the .htaccess inside the e107_media folder 
(prevents direct opening of the images. .)

now open the admin section
news > (newspost.php) shows the thumbs of the newsitems using thumb.php no issue here, but when you click an image.. you will get an error.. it tries to open the image directly.
news > edit item (newspost.php?action=edit) on the bottom images part, thumbs not showing. again direct url to images.

when looking at other sections, (feature box, media manager, pages  and the lot) this all looks ok. clicking the thumb opens the image using thumb.php
thats why i figured it might be still on someones todo list.

.. and while its not really related to the issue.. as i was talking about ogimages..
the second question came from one of my admins who noted, news items and menu's do have an image, but pages do not.. and thats just what he wanted, .. a custom image for one of his pages to show when shared at facebook... so i just entered that here :P haha.

**Comment by CaMer0n** [comment]
The hash is less about security and more about running multiple sites off of the same core installation. 
thumb.php is for resizing images. I recently made a correction to news.php so that it also resized the og:image as it could share overly large images with Facebook unnecessarily. Whatever happens inside the admin area is not public anyway so it shouldn't be a concern. Admins should normally be aware of what their hash folders are.

**Comment by willem010** [comment]
ah ok. that answers my question about the urls. thnx. im running a git from last month. didnt get this og using thumb yet and that probably should fix it.

for the question about og image on pages.  
the only thing i can think of is using an e_meta.php scanning for the url and add a custom og inage on this specific page. 
im sure there is a better way?

**Comment by CaMer0n** [comment]
@willem010 You mean detecting the images in the "Page" body and including them in the header with og:image ?

**Comment by willem010** [comment]
thats an even better idea than what i had in mind. good one. mucho gracias!

**Comment by CaMer0n** [comment]
@willem010 That should fix it ;-)
