### ISSUE TITLE
[Documentation needed] Help with uploaded images and thumb.php

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1283]
Hi, I just added image uploading (extracted from submitnews.php) to a plugin, Im uploading this images to e_MEDIA/plugins/plugin-name/ (I´m not sure if its the best place, please, point me on the right way if not) but now, I dont know how to use thumb.php to print those images (cause I dont want people to see the real path to the image directory, which looks like e107_media/77e5b4o/plugins/plugin-name, for security reasons)

I´m looking for the news shortcodes, bbcode, etc but I cant find the right way of doing this.

So, can someone help me with rendering uploaded images?

Thank you so much.
- Nes

**Comment by willem010** [comment]
i think you just can use thumb.php?src={e_MEDIA_IMAGE}/plugins/pluginname/image.jpg&w=400 
i found you have to specify at least width for it to render an image.
in html you can use img src="{e_BASE}thumb.php?src={e_MEDIA_IMAGE}..... "

**Comment by Jimmi08** [comment]
You could try to find this somewhere (fe. gallery plugin):
```$att 		= 'aw='.$w.'&ah='.$h.'&x=1'; // 'aw=190&ah=150';```
```e107::getParser()->thumbUrl($this->var['media_cat_image'],$att); ```
But how you were able to use custom folder in e_MEDIA...  does your uploading really work? I wasn't able to get this work with new Admin UI.

**Comment by nesjett** [comment]
Thank you guys, I´ve already tried to find this out on news, without good results, Ill take a look to the gallery plugin.

Thanks for the snippet Jimmi, Ill start testing with this.
