### ISSUE TITLE
menu manager -  e107 is not defined

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1289]
Hi,
I noticed error with menu manager: 

![image](https://cloud.githubusercontent.com/assets/5429548/12144373/7d6e07d0-b487-11e5-910c-3fef994d8f31.png)

![image](https://cloud.githubusercontent.com/assets/5429548/12144559/d582269e-b488-11e5-8646-2902f97bd0da.png)

Fresh install. I didn't notice it before because it seems to work but with testing my new plugin menu manager started to behave very odd way and I noticed this error. After installing fresh version, it was there too.

**Comment by LaocheXe** [comment]
I get a few error's on my console and the e107 is not define is one of them as well and I just synced with GitHub

Errors:
============================================
TypeError: "Are you sure?".addModLan is not a function
menus.php (line 96, col 3)


TypeError: "Are you sure?".addModLan is not a function
menus.p...r_right (line 350, col 3)

ReferenceError: e107 is not defined
============================================

**Comment by Jimmi08** [comment]
If this helps:
![image](https://cloud.githubusercontent.com/assets/5429548/12144608/48e1d328-b489-11e5-835b-148464e365ba.png)
![image](https://cloud.githubusercontent.com/assets/5429548/12144615/4e77a0f6-b489-11e5-96bc-607d923688ba.png)

I have the same plugin used on localhost (just error from above,menu manager works). And the same code online and menu manager is "blinking/flashing" and error is repeating itself. Only diffs are in paths.

**Comment by lonalore** [comment]
Because of "all.jquery.js" is not loaded, and "e107" is defined in "e107_web/js/core/all.jquery.js".

**Comment by Jimmi08** [comment]
I see that file there...
![image](https://cloud.githubusercontent.com/assets/5429548/12146140/56ef35ec-b492-11e5-9ef5-b50beb4c5ed0.png)

**Comment by lonalore** [comment]
@Jimmi08 try with this URL (this is the iframe content): 
view-source:http://yourdomain.com/e107_admin/menus.php?configure=jumbotron_home

**Comment by Jimmi08** [comment]
Ups, I see, so menu manager (it's iframe) strips this. Thanks for this, I found reason why my plugin causes problems. 
I use e_header.php with including scripts just in frontend (testing if(USER_AREA) {}  But in theme display (layout in menu manager) I can see this code. And because it's code to change select options to tabs, menu manager doesn't work. 
Is there way how to use e107::js() without influence for menu manager? If it's able to strip core scripts, it should be able to strip plugin scripts too. Maybe I am doing somethong wrong.

**Comment by lonalore** [comment]
Hmm... Use "e107.behaviors" to run your scripts. Behaviors never run on menus.php, because of "all.jquery.js" is not loaded on that page.

**Comment by lonalore** [comment]
[Documentation for JavaScript Behaviors](https://github.com/e107inc/e107/issues/1259)
[Example usage](https://github.com/lonalore/libraries_test/blob/master/libraries_test.js)

**Comment by Jimmi08** [comment]
Thank you very much for your time and help. I confirm that your fix solved this problem, so this issue can be closed after they merge it. 
I solved problem with script now by testing e_REQUEST_URI and use e107::js() just if path is plugin path. It's just for demo purpose, so I think it's enough.

Your solution look absolutely amazing. I already noticed you are working on this but I am not too much to javascript, so this will take time. Maybe it will help to see it on real example doing both way;
 https://github.com/eggboxio/quick-select
This is my code in e_header.php now.
![image](https://cloud.githubusercontent.com/assets/5429548/12149237/def3a256-b4a2-11e5-9e64-1b35a7e48e27.png)
 Just idea, you don't need to do it :)

**Comment by lonalore** [comment]
Just create a javascript file (e.g. quickselect.init.js) in your plugin's folder with this code:
```javascript
var e107 = e107 || {'settings': {}, 'behaviors': {}};

(function ($)
{

	/**
	 * Behavior to attach Quick[select] to select boxes.
	 * 
	 * @type {{attach: Function}}
	 */
	e107.behaviors.initQuickSelect = {
		attach: function (context, settings)
		{
			$(context).find('select').once('quick-select').each(function () {
				$(this).quickselect({
					activeButtonClass: 'btn-primary active',
					breakOutValues: ['Breakfast', 'Lunch', 'Dinner'],
					buttonClass: 'btn btn-default',
					selectDefaultText: 'Other',
					wrapperClass: 'btn-group'
				});
			});
		}
	};

})(jQuery);
```

then, in your e_header.php file:
```php
e107::css('links_page', 'quick-select/css/quickselect.css');
e107::js('links_page', 'quick-select/js/jquery.quickselect.min.js');

// Now load behavior.
e107::js('links_page', 'quickselect.init.js');
```

:)

**Comment by lonalore** [comment]
Using e107.settings:

```javascript
var e107 = e107 || {'settings': {}, 'behaviors': {}};

(function ($)
{

	/**
	 * Behavior to attach Quick[select] to select boxes.
	 *
	 * @type {{attach: Function}}
	 */
	e107.behaviors.initQuickSelect = {
		attach: function (context, settings)
		{
			$(context).find('select').once('quick-select').each(function () {
				$(this).quickselect({
					activeButtonClass: e107.settings.links_page.activeButtonClass,
					breakOutValues: e107.settings.links_page.breakOutValues,
					buttonClass: e107.settings.links_page.buttonClass,
					selectDefaultText: e107.settings.links_page.selectDefaultText,
					wrapperClass: e107.settings.links_page.wrapperClass
				});
			});
		}
	};

})(jQuery);
```

then, in your e_header.php file:
```php
e107::css('links_page', 'quick-select/css/quickselect.css');
e107::js('links_page', 'quick-select/js/jquery.quickselect.min.js');

// Plugin settings for javascript.
$settings = array(
  'activeButtonClass' => 'btn-primary active',
  'breakOutValues' => array('Breakfast', 'Lunch', 'Dinner'),
  'buttonClass' => 'btn btn-default',
  'selectDefaultText' => 'Other', // Use constant for multi-language support.
  'wrapperClass' => 'btn-group',
);

e107::js('settings', array('links_page' => $settings));

// Now load behavior.
e107::js('links_page', 'quickselect.init.js');
```

**Comment by lonalore** [comment]
If you're interested, I show you how to use [libraries](https://github.com/lonalore/libraries) plugin to load external libraries (e.g. jquery.quickselect). :)

**Comment by Jimmi08** [comment]
I got t it work with one plugin, this is result, does it?
![image](https://cloud.githubusercontent.com/assets/5429548/12151490/a970eed8-b4af-11e5-92c2-08874b26401c.png)
Of course I am interested, but I want to try it myself. I will have time during weekend, I create issue in your repository.  When I get stuck.  I am sure I will get, the question is only in what point :)
Thank you again.

**Comment by lonalore** [comment]
Yes, it does. :)
All right, good luck! :)

**Comment by lonalore** [comment]
Commit has been merged, so this can be closed.

**Comment by Jimmi08** [comment]
Thank you to all
