### ISSUE TITLE
Shortcodes can't render some links properly in forum post due to incorrect IDs, etc when using non-Bootstrap theme.

### ISSUE THREAD

**Issue by dmitripot** [e107inc/e107#1290]
Post subject missing, polls missing, etc. They are missing, too, not just hidden due to CSS. I checked. On the other hand, including Bootstrap breaks the old 1.x themes. What do?

EDIT: Manually overriding the forum template, for example, and replacing the post style shortcodes like {SUBJECTBOX} with a concatenated .$subjectbox works. But why is it behaving like that?

**Comment by LaocheXe** [comment]
Bootstrap is just a theme, it has no influence with any e107 v 1.xx themes - I also don't quite understand what you are saying, you said a few elements are missing with a theme you are working on? Example the buttons are missing?

**Comment by dmitripot** [comment]
Yes, some don't work, etc. I managed to make the fields in new thread show up, but the quick reply button doesn't work. I have included JQuery into the theme, but still, no matter how much I add to my v1 theme, it's less functional than the Bootstrap one by far.

**Comment by LaocheXe** [comment]
Did you use the Theme Manager's convert old v1 themes to v2 before working on your version 1 theme?

**Comment by dmitripot** [comment]
Yes. I figured it out that it's mostly the AJAX stuff that's breaking it. Is there a quick way to disable all AJAX-related forum stuff?

**Comment by tgtje** [comment]
As comment on last posted comment : overall issues with v1 themes do exist; but generally it is css related or 'size of boxes. The described other problems i have seldom seen being posted (as e107help org for source). Being a v1 theme, a 'free' one or premium (name? ). Most issues can be overcome when applying the recommended changes ( http://e107.org/developer-manual/theme-basics#upgrading-v1-x-themes )
Than again : is your forum template > normal or changed.. Using language (non english) ? if so how does english react..

**Comment by dmitripot** [comment]
Forum template changed as of now. V2 style (theme/templates/forum/*_template.php). I am getting rid some of the layout problems using this method. The theme is actually based off of sebes. I guess I could re-add the original banner and post the updated theme so v2 people can use it later. The posting problems might not be theme-related now that I think of it. Is there a special function for themes that handles page refreshing?

**Comment by dmitripot** [comment]
Found it. Must be a problem with the {EDITIMG} shortcode when Bootstrap is not defined in theme.php

Problem? I guess so.

**Comment by dmitripot** [comment]
Good news. I have made a fix that seems to work. Please check this:
In e107/plugins/forum/forum_viewtopic.php, somewhere not far after line 1200:

Old code is commented out, new code is not commented, seems to work:
```
$ret .= "
		<div>
		<a href='" . $e107->url->create('forum/thread/edit', array('id' => $postInfo['post_thread'], 'post' => $postInfo['post_id']))."'>" . IMAGE_admin_edit . "</a>
		<input type='image' " . IMAGE_admin_delete . " name='delete{$type}_{$delId}' value='thread_action' onclick=\"return confirm_('{$type}', {$postInfo['post_forum']}, {$postInfo['post_thread']}, '{$postInfo['user_name']}')\" />
		<input type='hidden' name='mod' value='1'/>
		";
	/*$ret .= "
		<div>
		<a href='" . $e107->url->create('forum/thread/edit', array('id' => $postInfo['post_id']))."'>" . IMAGE_admin_edit . "</a>
		<input type='image' " . IMAGE_admin_delete . " name='delete{$type}_{$delId}' value='thread_action' onclick=\"return confirm_('{$type}', {$postInfo['post_forum']}, {$postInfo['post_thread']}, '{$postInfo['user_name']}')\" />
		<input type='hidden' name='mod' value='1'/>
		";*/
```

**Comment by LaocheXe** [comment]
how much have you tested on that? Does it still work with the Bootstrap theme? Does it work on other themes as well?

**Comment by dmitripot** [comment]
Haven't tested if my fix works on BS yet. I'm being rushed by a community with a 1.x theme conversion as I am GitHubbing here all at once :P
I'll test it out in a bit more thoroughly.

**Comment by dmitripot** [comment]
I just realized something: my fix might not be proper. I was fixing the other oldschool image buttons, and found out that there is sometimes commented out code near the line which has the thread and post id's properly set. Why was this code changed? Anyways, my "fix" above is actually working backwards from whatever the plan seems to be. I don't advise it.
