### ISSUE TITLE
Issue: Upgrade website and Downloads

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1291]
I've just notice that when I upgraded the site from v1.0.4 to 2.xx that all the downloads are listed but when you try to download the file you get sent to a page saying File not found. Could this be an issue because e107_files folder is no longer used and since the upgrade the core of v2.xx doesn't support e107_files anymore?

**Comment by tgtje** [comment]
Normally NO; it should work out of the box. Just updated a new system with about 900 downloads.
No issues, downloads available; all works, even the url's for outside source (mirrors etc..)
Note! v1 to v2 keeps the folders and files also config has the paths..Images could be/are an issue!!

**Comment by LaocheXe** [comment]
Well some how when trying to download a file the page goes to the "File not found" screen - while in Admin Area > Downloads: it displays the filename - but clicking on it to to see where only shows the media manager upload or select file section. so I don't know what is going on for this, I get no error's on the pages.

**Comment by tgtje** [comment]
Strange.. my admin area also displays the filename, and clicking (select local file) brings me to media manager > files are present....

**Comment by CaMer0n** [comment]
@LaocheXe Could you please locate one of the "File Not Found" downloads in the downloads table, (using phpmyadmin) and post the exact value of download_url ?

**Comment by LaocheXe** [comment]
Yes, in the database it only list the file  - no url just the file 'clanscrepair.zip'

Also I went in and had to go and move all the download files from e107_files/downloads/ and send them to e107_system/{FOLDER-NUMBER}/import  and used media manager to import them into the system, then go and edit each of the downloads and select the file. Had to do over 18 pages that listed 10 downloads lol I'm still not done yet lol had a few files left in the old downloads folder I haven't imported yet.

**Comment by CaMer0n** [comment]
There is probably just a minor backwards compatibility path to add to request.php. Where is clanscrepair.zip normally located? (before your moving/importing)

**Comment by LaocheXe** [comment]
e107_files/downloads

**Comment by CaMer0n** [comment]
Thank you. And what is the value of your $DOWNLOADS_DIRECTORY in e107_config.php ?

**Comment by LaocheXe** [comment]
heh well the e107_config.php has nothing for $DOWNLOADS_DIRECTORY

This is in the config - 

$ADMIN_DIRECTORY     = 'e107_admin/';
$FILES_DIRECTORY     = 'e107_files/';
$IMAGES_DIRECTORY    = 'e107_images/';
$THEMES_DIRECTORY    = 'e107_themes/';
$PLUGINS_DIRECTORY   = 'e107_plugins/';
$HANDLERS_DIRECTORY  = 'e107_handlers/';
$LANGUAGES_DIRECTORY = 'e107_languages/';
$HELP_DIRECTORY      = 'e107_docs/help/';
$MEDIA_DIRECTORY	  = 'e107_media/';
$SYSTEM_DIRECTORY    = 'e107_system/';

**Comment by CaMer0n** [comment]
If you upgraded, your e107_config.php file should have contained these variables: 

$FILES_DIRECTORY = 'e107_files/';
$DOWNLOADS_DIRECTORY = 'e107_files/downloads/';

..but not these variables..

$MEDIA_DIRECTORY = 'e107_media/';
$SYSTEM_DIRECTORY = 'e107_system/';

**Comment by LaocheXe** [comment]
Odd, guess I upgraded it wrong

**Comment by tgtje** [comment]
Candidate for closure of issue ?

**Comment by Moc** [comment]
@LaocheXe Any feedback on this one? Did you attempt another update and did the same issue occur? Or did it update properly and did the config file look as Cameron illustrated above?

**Comment by LaocheXe** [comment]
@Moc - I am sure what CaMer0n posted would have fixed my issue, I did do the upgrade wrong - what I did was installed the new version, then copied the e107_config.php and replaced the old one when I went and added the other files and did the upgrade.

I was almost done importing the downloads manually when CaMer0n posted but it is all done and finished now.

No other update was performed since the site that I did update was the main site for a team, only issue after the update was the downloads that I screwed up - and the theme needed to be updated to version 2.xx

**Comment by Moc** [comment]
Thanks for the feedback!
