### ISSUE TITLE
Issue: Upgrad website and Members list

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1292]
After upgrading the site from version 1.0.4 to version 2.xx I notice on the Users.php (Member's List) it shows this: "Using v1.x user template"

With nothing under that point.

**Comment by tgtje** [comment]
called : user php line 107 ( if ..else) debug mess. ( bc fix old templates)

**Comment by LaocheXe** [comment]
anyway to get this to show the members? Tried taking that out and still wont show anything.

**Comment by tgtje** [comment]
Not noticed such behaviour before, possible there is a user template in theme (non BS) ?
Or test: add v1 usertemplate in themes (add) template folder. htaccess file ok by name ?
At present no actual test sites available to replicate...

**Comment by LaocheXe** [comment]
Four templates in the theme, comment_template.php, forum_icons_template.php,  gc_custom_login.php, and news.php

I don't know to much about .htaccess files but all seems to be okay

**Comment by tgtje** [comment]
Ok, just installed a v1 site and updated : correct?  for memberlist (although i do not get the message), i only get the.... go to page numbers.. (no content). (calling user php ? for memberlist)
After investigation (for me it works, but unsure if it is mis..coding in file) i de-commented line 102 of user php and the list appears (multiple themes). Now why did i do that ? line 108 also calls basically the same... needs a dev point of view if it is a bug (alike).
Htaccess i meant name > dot..... not e107.....  (happens now and then).
(latest git files in use; about 90 members; forum, and downloads.. > no issues upgrading).

**Comment by LaocheXe** [comment]
commenting out line 102 seems to allow the page to show, i dont know why it's acting like that.

**Comment by tgtje** [comment]
Just adding : thought about the leftover template (themes/templates) when above is done, and i rename the template, differences on user 'image/icon' do display, so it looks like the system does switch between the themes/templates one, and the core one (style)

**Comment by LaocheXe** [comment]
I would like to point out, a way to fix the issue if Members list doesn't show is to put the user_template.php that is in core templates folder, copy and paste it into the theme you are using - it fixes the issue.

On the site which was upgraded has an old theme, the theme was converted to be used for version 2.xx and I have been doing fixes, because I had issues with the forums - I had to add the forum templates for it all to display again.

**Comment by CaMer0n** [comment]
@tgtje @LaocheXe Would it be possible to get direct FTP access to this problem in your upgrade so I can troubleshoot it?

**Comment by LaocheXe** [comment]
@CaMer0n sure thing, give me an e-mail address to shoot you the ftp info

**Comment by tgtje** [comment]
Sorry, xampp installation (testing purposes),
Can try to create an ftp server though ( not done before, and pc is not 
always 24/7 online.
??

**Comment by tgtje** [comment]
:+1:
