### ISSUE TITLE
Rendering avatar in cron callback.

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1293]
I would like to render some HTML contents (with user avatar) in a cron callback, but the avatar image has wrong URL. 

In a cron callback, $tp->toAvatar() method generates image with URL like:

```
/thumb.php?src={e_BASE}var/www/clients/client1/web2/web/e107_media/fce481f49f/avatars/upload/ap_0000002_11156363_915754901816355_4288881410527900253_n.jpg&amp;w=20&amp;h=20
```

instead of:

```
/thumb.php?src={e_AVATAR}upload/ap_0000002_11156363_915754901816355_4288881410527900253_n.jpg&w=20&h=20
```

This is a bug? 
Or how can I make it generate proper URL for avatar image?

**Comment by CaMer0n** [comment]
It may require some experimenting. I have updated the cron test email function for you. Run the cron and then wait for the test email. It will display all the environment paths available etc.

**Comment by lonalore** [comment]
I sent you an email with environment variables. I think it contains sensitive information, so I did not post it here.

**Comment by Moc** [comment]
Is this still an issue?

**Comment by Moc** [comment]
Closing due to due lack of feedback. Feel free to submit new information and I'll re-open.
