### ISSUE TITLE
e_frontpage.php - doesn't work for newsfeed plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1294]
There is error about missing class2.php,  instead of 

```
require_once('../../class2.php');
```
there should be 
```
if(!defined('e107_INIT'))
{
	require_once('../../class2.php');
}
```

By the way, e_frontpage.php is missing in documentation in the list of e_ files.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! How about making a pull-request for this one? I know it's simple, but you could be an even greater help if you were up to speed on making pull-request. What do you think?

**Comment by Jimmi08** [comment]
I suppose this is correct solution, so yes, I can do it. No problem.  Probably it's time to fork this. By the way, is there way I can delete my old pull?  It's not needed now.

Could you please look at my languages request? I didn't know what I did wrong. There should be separate requests for Slovak and Czech translation, it joined it to one pull. I am sure I did two pull requests. And I just found it added Norwegian lans and next changes after it too, I don't remember to create pull reguest for this. Thanks.

**Comment by CaMer0n** [comment]
Yes, they are all merged into one request and merged now. Please update your fork and make any further changes in a new pull-request. thank you!!

**Comment by Jimmi08** [comment]
Thank you, but Norwegian was just test, request was created somehow itself, I did something wrong.This is reason I am afraid to create request here.
