### ISSUE TITLE
Where can i find the MRBS plugin for the new version of e107?

### ISSUE THREAD

**Issue by patchie** [e107inc/e107#1296]
Our server has been running for a loooong time, and just crashed when the webhotel updated to a newer php version.

We have until now used e107 version 0.617 date 2005, and plugin for mrbs(https://sourceforge.net/projects/mrbs/).

But now we have to update to a newer version it seems, and since we mostly only use mrbs functionality, we have installed and setup mrbs on our server. But we just found out that we cannot ban users, users cannot press any password reset button, etc..

and now i wanted to install e107 and the mrbs pkugin, but i cannot find any mrbs plugin?

Can anyone help me?

Thanks in advance.

**Comment by tgtje** [comment]
This one ? http://e107.org/plugins/?id=616  (do not know if it runs in v2). Never used it

**Comment by Jimmi08** [comment]
http://e107help.org/1453/booking-plugin?show=1453#q1453  
See my last comment.

**Comment by Moc** [comment]
This is a question for e107help.org not Github.
