### ISSUE TITLE
Custom user extended fields are inoperative 

### ISSUE THREAD

**Issue by TealFox** [e107inc/e107#1297]
Hey Dev Team. 

I am experiencing some issues with e107. Essentially I have added custom user extended fields and made them optional checkboxes, but users are not able to save their profiles or make any modifications unless they check off each and every of the checkbox. 

@myovchev reckons the whole user extended field might need a review and I note that @septor has also suggested the same.  

Thanks for your thoughts & views on this issue.

**Comment by tgtje** [comment]
related ? #1255

**Comment by CaMer0n** [comment]
thanks @TealFox. I just create a custom extended field with 3 checkboxes and was able to save and update. btw. I reviewed a fair chunk of it prior to release. Are you using a custom usersettings_template.php ?

**Comment by TealFox** [comment]
Sorry! I wasn't keeping a close enough attention to my inbox! I think we might very well be doing that (I'm not sure we've left anything not customised lol). Do you want admin access to check it out?

**Comment by CaMer0n** [comment]
@TealFox Maybe you can just post your template in a gist so I can see which shortcodes you are using. Thanks.
