### ISSUE TITLE
e_list.php in forum plugin, SQL error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1298]
I just noticed this error:
![image](https://cloud.githubusercontent.com/assets/5429548/12280516/d2377d62-b98e-11e5-85d3-c20fdd44ab5c.png)

**Comment by CaMer0n** [comment]
Fixed the query, but I'm not sure about the plugin itself. Is it working for you @Jimmi08 ?

**Comment by Jimmi08** [comment]
Yes, it works. Thank you very much.
