### ISSUE TITLE
Issue: Contact Us Page

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1303]
Using the contact.php - the page displays the content but no theme, listing the basics this is what it reports:

Warning: explode() expects parameter 2 to be string, array given, Line 88 of /e107_core/templates/header_default.php
Warning: Invalid argument supplied for foreach(), Line 92 of /e107_core/templates/header_default.php
Warning: strstr() expects parameter 1 to be string, array given, Line 771 of /e107_core/templates/header_default.php
Warning: explode() expects parameter 2 to be string, array given, Line 88 of /e107_core/templates/header_default.php
Warning: Invalid argument supplied for foreach(), Line 92 of /e107_core/templates/header_default.php

**Comment by CaMer0n** [comment]
It's a problem with the value of $HEADER. Which theme are you using?

**Comment by LaocheXe** [comment]
Bootstrap 3

**Comment by LaocheXe** [comment]
Thinking about the theme more, I went into theme manager and added contact.php to Modern Business:layout - default layout was the Jumbotron (sidebar-right) and it now displays in the theme.

**Comment by LaocheXe** [comment]
Now the odd thing about this, is that after setting the theme to bootstrap 3 and back to the customized bootstrap 3 I have, the hole issue is gone now - which is odd.
