### ISSUE TITLE
e107.org feed - Invalid XML

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1304]
I found an error in the XML while building a plugin/theme filtering plugin: unescaped double quotes in attributes in XML string.

URL: http://e107.org/feed/?limit=1000&type=plugin
Error on line 1958: name="" Simple Image Upload ""

**Comment by Moc** [comment]
Is this still an issue?

**Comment by CaMer0n** [comment]
@Moc It's fine now. Closing.
