### ISSUE TITLE
Feature Request: Mobile Detection with Theme Layouts

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1307]
Right now e107 v 2.xx theme (Bootstrap 3) was created with mobile devices in mind, I was thinking what is you used just 1 layout for mobile? Confused yet?

Admin Area - > Theme Manager - > Layouts: (Where you can put in different web pages in for different layouts inside that theme) - Add the ability to use Mobile on the layout Jumbotron (home) or Jumbotron (full-width) - so when a user is using a tablet or some other mobile device they would see the layout of the page differently than they would on the computer.

This can be useful for any theme creators that are having trouble getting their theme layouts to work on any mobile device - this way they can focus on making a new layout for the mobile devices and not for both.

**Comment by CaMer0n** [comment]
I believe the point of bootstrap3 was to allow a single page/template to render on both mobile and desktop versions without having to make a different template for each (by using css classes). Please correct me if I'm wrong.

**Comment by LaocheXe** [comment]
You are right, just thought maybe something to do in the future - or something to allow for customized theme's etc..

**Comment by CaMer0n** [comment]
:+1:

**Comment by Moc** [comment]
I personally think this should be taken care of by the theme developer through using proper css classes (making use of the viewports in bootstrap). Having different templates for each device would kind of contradict with the purpose of using a responsive css framework like Bootstrap. 

Closing for now, but if others (especially theme developers) feel that this should be implemented then please do let us know!
