### ISSUE TITLE
Feature Request: Plugin/Theme Sync with GitHub

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1308]
I don't know how this would be done but allow a feature to plugin and theme developers to connect their gist repos to their plugins/themes and allow users to upgrade the code they have on the webserver with the GitHub Repo.

Kinda like Developer Mode for e107 v2.xx Github sync.

**Comment by tgtje** [comment]
Wouldn't it be an easier choice (it does exist in v1 in some plugins) to create a message that there's an update avalable. Saves you a lot of time and effort, and by link etc.. let the choice by user ? ( i realise it would have some security related issues if upgrade would be a sec.fix or alike and user does not take action). 
I get the idea but i think it will be a though one; there's no real check on viral behaviour (outsource and open); zip's are influenced by unpacker etc... Just some comment, not putting it down...
Dev mode will likely use a kind of secure channeling, where both system run handshakes etc.. (not sure but would guess).

**Comment by septor** [comment]
To be fair, I think this is something that could be handled by the plugin developer. Sure there could be hooks added to the core code, but I don't imagine a great deal of plugin developers use GitHub for their code.

**Comment by LaocheXe** [comment]
@tgtje I checked out the Sync with GitHub that e107 dev mode has, just a simple download the master.zip and extracting tool.

To have check the plugin/theme and see what version the GitHub repo has and what version they have is to add the .git to the plugin/theme folder and have code that checks the plugin/theme git to the one on GitHub.

There is already php code that does the job: https://github.com/inacho/Git-Deploy-PHP

How would it be done in the plugin/theme - if this feature is added to the core e107 add a spot in the plugin.xml and theme.xml for the .git url (example: https://github.com/e107inc/e107.git <- git for e107 GitHub). 

In Admin Area -> Plugin admin area can have an section of saying "an update is available for this plugin, would you like to update the plugin". Same goes for the theme: Admin area -> Theme Manager -> Site theme area - says the same thing as plugin.

@septor This could be done by the plugin/theme developer but it seems like a good feature/option to have, and some or most developers wont use GitHub for their code - but the cool part is even with the repo is private, the Git can still be checked and to see if update or not.

Just a thought.

**Comment by septor** [comment]
Eh, I didn't say it was a bad idea. I kind of like it, but it depends so much on server configuration that I don't really know if it will be added to the core.

**Comment by Moc** [comment]
I don't think we're adding this to core. 

Official plugin and theme releases can be updated through the Admin Area if they are uploaded on e107.org. Git versions should either be done manually by the user, or this functionality can be implemented by the plugin/theme author.
