### ISSUE TITLE
Setstyle doesn't get applied to custom pages

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#1311]
Using {SETSTYLE=X} doesn't have any effect in custom pages when viewing single page and thus applying default style defined. Is not theme depending, since {SETSTYLE=X} sc doesn't work in bootstrap theme too. 

However it is working properly in Books list and in Chapters list, so I'm thinking the problem is somewhere in processViewPage function.

**Comment by CaMer0n** [comment]
Thank you!. So I guess you tested this by echoing '$style' from inside the theme tablerender() function?

**Comment by CaMer0n** [comment]
@Serios Where are you using {SETSTYLE=X} specifically? Are you placing it in $PAGE_TEMPLATE['default']['start'] ?

**Comment by Serios** [comment]
Nope, not in page_template. Setstyle in theme

**Comment by CaMer0n** [comment]
{SETSTYLE} should normally be used in the template it is being applied to.

**Comment by CaMer0n** [comment]
Sorry, I read this as {SETIMAGE} you are correct {SETSTYLE} is used in theme.php 
Does your tablestyle function look like this?

```
function tablestyle($caption, $text, $id='', $info=array()) 
{
	$style = $info['setStyle'];
```

**Comment by Serios** [comment]
Yes, exactly like this. As I mentioned above, in Books and Chapters lists style is returned but in single page view doesn't.

**Comment by CaMer0n** [comment]
@Serios This should be working now, please update and let me know how it goes for you. Thanks.

**Comment by Serios** [comment]
@CaMer0n Thanks it works perfectly now.

**Comment by CaMer0n** [comment]
:+1:
