### ISSUE TITLE
Question: e107 tools in admin_ui

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1314]
Since the feature request about syncing plugins and themes, I went into the db.php and took out the Github code someone did and put it in my own plugin..

I copy the db.php from e107_admin and put it in my plugin folder and renamed it to sync.php and commented out a bunch of code because I want to focus on the github functions in the file. This works and does what the default sync with github does in the db.php for e107 v2.xx
[Sync.php](https://github.com/LaocheXe/Voice-eXeSystem/blob/master/voice/sync.php)

I went and copy the plugin's admin_config.php renamed it to admin_sync.php and went in and tried to put in the lines of code from the sync.php in but came up with a few issues.
[Admin_sync.php](https://github.com/LaocheXe/Voice-eXeSystem/blob/master/voice/admin_sync.php)

Question is, can we use e107 tools in the admin_ui?

**Comment by Moc** [comment]
I think you should use the sync code in a custom method within the admin_config.php file preferably. 

If this issue is still relevant, can you elaborate on what kind of issues you are experiencing and what you mean specifically with 'e107 tools'? Thanks!

**Comment by Moc** [comment]
Closing due to lack of feedback.
