### ISSUE TITLE
Sync with Github on localhost

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1315]
Does this work on localhost?

I got this error, but file is downloaded:
![image](https://cloud.githubusercontent.com/assets/5429548/12702808/337219cc-c833-11e5-839e-adc12dd3cb30.png)

After dump curl_error() in file_class.php I got this error:
SSL certificate problem: unable to get local issuer certificate

After adding curl_setopt($cp, CURLOPT_SSL_VERIFYPEER, FALSE); sync worked. 

This setting is set with get_remote_content(), but not with get_remote_file().

**Comment by Moc** [comment]
I can confirm that I get the same error message on localhost. On a live website it works fine.

**Comment by CaMer0n** [comment]
@Jimmi08 If that fixed it for you, would you like to send a pull-request?

**Comment by CaMer0n** [comment]
Nice one @Moc :+1:
