### ISSUE TITLE
DB caching

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1317]
I have disabled caching on my site, but it still appears to be caching DB data. For example, I have a page that loads records from a table, but if you add/update records in that table and refresh the page it doesn't update with the new values.

Any ideas?

**Comment by CaMer0n** [comment]
Hard to say without seeing your code. Can you share it with us? (gist)

**Comment by pricey1981** [comment]
Sorry for delayed response. I don't believe it's anything to do with my code, it's a simple $sql->retrieve call.

I note that the DB Structure caching cannot be disabled in admin. When I clear this cache after an update, the issue does not occur. Is there a reason why this can't be disabled?

**Comment by pricey1981** [comment]
Sorry, I've managed to track this down to an issue with the web host that I've now resolved
