### ISSUE TITLE
How to add multiple authors in plugin.xml?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1320]
The question is the title: How to add multiple authors in plugin.xml? :)

**Comment by tgtje** [comment]
Maybe i do misunderstand, than please broaden question).
In plugin xml (usually line 3 > author name) It is just a txt field, so adding any name there will do.
The names will be displayed in plugin manager
In plugin builder i can not add a second

**Comment by lonalore** [comment]
Yes, I can list authors separated by commas, but URL attribute allows only one value. 
Instead of single author line it should be something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<e107Plugin>
  <authors>
    <author name="John Doe" url="http://example.com"/>
    <author name="Jane Doe" url="http://example.com"/>
  </authors>
</e107Plugin>
```

**Comment by CaMer0n** [comment]
It's not supported at this time. I would have to make the plugin/theme uploads and feeds also support multiple authors. In all, a LOT of work. Another tag for 'contributors' could avoid that perhaps.

**Comment by LaocheXe** [comment]
@CaMer0n sounds like a good idea for contributors

**Comment by CaMer0n** [comment]
Feel free to go ahead and add them with the following format: 

   ```
 <contributors>
    <contributor name="John Doe" url="http://example.com" />
    <contributor name="Jane Doe" url="http://example.com" />
  </contributors>
```
