### ISSUE TITLE
Forum view are not correct

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1323]
The imported Forum view is not correct
![image](https://cloud.githubusercontent.com/assets/1758577/12841236/9882de18-cbea-11e5-8340-5b053f986500.png)

and the threads
![image](https://cloud.githubusercontent.com/assets/1758577/12841247/b1c7dc66-cbea-11e5-9b4f-94791f6a7791.png)

in the old forum show this

**Comment by tgtje** [comment]
Although i am not able to recreate, i would advice to upgrade your site's files or just for testing ( and if you would do, please report back to change )
about two weeks ago @CaMer0n made the following changes https://github.com/e107inc/e107/commit/7a38046e4e6dab025e5da084bc234ca5712ac55d
Please test to see if it helps ( 3.3.6 had many css changes and browser bugs fixes > 'external sourcing'.

**Comment by schlrech** [comment]
With the forum it’s like this:
Upgrade done, weeks ago. Everything was read.
Then neither entrys were made nor modified, and also no update on E107.
At some stage it simply was like that.
This is already the fourth time.
If I copy the old E107 forum into the new database again and let it convert ones more, it does work too.
But after a while the same problem occurs again.
Next Tuesday I will bring in the newest source and try it ones more. To update 3.3.5 to 3.5.6 wasn’t successful.

**Comment by Moc** [comment]
In combination with this discussion (http://e107help.org/1915/cant-make-comments-on-new-news-item-nor-on-forum-threads) I think there may be a bug which has some conflict with the v1 templates/shortcodes used in the forum.

**Comment by schlrech** [comment]
i don't have any v1 templates is a fresh v2 installation without old files and i'm using bootsrap v3 theme

**Comment by Moc** [comment]
Blegh, sorry, I misread your post. Still looks like a bug though :)

**Comment by CaMer0n** [comment]
I tested with jayya on v2 with forums, and its working correctly. I don't quite grasp the full issue here. Can someone paraphrase it for me? Please enable debug to be sure an SQL query is not failing.

**Comment by schlrech** [comment]
![image](https://cloud.githubusercontent.com/assets/1758577/12879735/944ada94-ce38-11e5-9cb0-3bb73ce702b2.png)

![image](https://cloud.githubusercontent.com/assets/1758577/12879741/a94d4f26-ce38-11e5-89e9-8c49fd9efd10.png)

**Comment by schlrech** [comment]
missing following fields
in 
![image](https://cloud.githubusercontent.com/assets/1758577/12879936/d3608b00-ce3a-11e5-9912-2a5ca146411e.png)

![image](https://cloud.githubusercontent.com/assets/1758577/12879951/eb7fc6ce-ce3a-11e5-9c7f-cff850e8603d.png)

**Comment by CaMer0n** [comment]
Did you run the forum upgrade process? These fields are normally created in "Step 3".

**Comment by schlrech** [comment]
Yes i run the upgrade process without errors.... and the DB check ist also correct

**Comment by CaMer0n** [comment]
Does e107_user_extended contain columns with the names: user_plugin_forum_viewed and user_plugin_forum_posts ?

**Comment by schlrech** [comment]
no, these fields are missing
![image](https://cloud.githubusercontent.com/assets/1758577/12880562/68e1c700-ce42-11e5-889b-dcaa5f751cbf.png)

**Comment by CaMer0n** [comment]
Please run this single command in Phpmyadmin. 
```
ALTER TABLE `e107_user_extended` ADD `user_plugin_forum_viewed` TEXT ,
ADD `user_plugin_forum_posts` INT(11) DEFAULT '0';
```

**Comment by schlrech** [comment]
@CaMer0n 
many thx, now the forum functionaly correct
thx

**Comment by CaMer0n** [comment]
:+1:
