### ISSUE TITLE
Wrong SEF URLs are generated for user profiles

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1324]
Example:
"/user/L%C3%B3na%20Lore"

According to URL settings, SEF URLs should not contain "space", or "uppercase letter":
![kepernyokep - 2016-02-05 - 13 25 23](https://cloud.githubusercontent.com/assets/6043821/12846324/2e0351d6-cc0c-11e5-8665-aeee28463a5a.png)

Furthermore, transliteration is missing too: "Lóna Lore" should be "lona-lore".

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/545

**Comment by CaMer0n** [comment]
@lonalore Is this one still an issue, I seem to recall working on this.

**Comment by Moc** [comment]
Pretty sure this is fixed. If not, please let us know and I'll re-open.
