### ISSUE TITLE
Banlist - many entries in the banlog.log

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1325]
I had a problem looking at one of my sites. 
It went over it's 500 MB file size limit, apache locked me out.
I found some very big log files. Cleaned them out. 

Still, I found each time I went to the site I got "Invalid File List" and could not access the site. 

I found the phrase in e107_handlers/iphandler_class.php  Line 439 
			echo 'Invalid list file';
			die();			// Debatable, because admins can't get in if this fails. But can manually delete the file.

I commented out the "die" line and could load the site. 
I then added my IP to the WhiteList.
I comment the die line back in and I'm running ok now. 

However, each time I navigate anywhere as admin, it generates more entries in the Banlog.log 

I'm up to 40+ lines in the log just navigating about the site, since it was fixed.

**Comment by MikeyGMT** [comment]
Checked User audit trail class Pref : was set to Everyone. 
However I have set to no-one inactive. 
New entries keep appearing in Banlog.log.

**Comment by Moc** [comment]
What do the entries look like? (you can mask the IP of course)

**Comment by MikeyGMT** [comment]
1454674436 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674436 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674439 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674441 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674441 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674442 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674444 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100
1454674444 0000:0000:0000:0000:0000:aaaa:nnnn:annn 100 result --> 100

>260 records now in a couple of hours

**Comment by Moc** [comment]
Let's debug. 

In iphandler_class.php, change this: 
```php
		$this->makeUserToken();
		$ipStatus = $this->checkIP($this->ourIP);
		if ($ipStatus != 0)
		{
```

to

```php
		$this->makeUserToken();
		$ipStatus = $this->checkIP($this->ourIP);
		print_a($ipStatus);
		if ($ipStatus != 0)
		{
```

Then go to your homepage, there should be a new box with a value. What's the value?

**Comment by Moc** [comment]
Ok, it's adding those lines because you are whitelisted. 
Try removing yourself from the whitelist and see if the entries stop. 

Now I need to figure out why it is logging so often when someone is on the whitelist.

**Comment by MikeyGMT** [comment]
Yes removing me from Whitelist stopped the entries being generated.

**Comment by Moc** [comment]
I'm just trying to figure out what the exact issues are. Obviously when an IP is whitelisted, it should not create a new entry on every single action and that's what I suspect is happening at the moment. 

> I found some very big log files. Cleaned them out.
Are these e107 log files or other? If e107, what are their file names and where are they located?

**Comment by MikeyGMT** [comment]
The main one to be concerned with I think is banlog.log where the duplicates occur on every navigation. 

Adding the debug line 
>>   print_a($ipStatus);
When I am not whitelist, I see iPStatus 0
When whitelisted = 100, regardless if logged on our off (separate browser)

**Comment by MikeyGMT** [comment]
The other logs were possibly because I left the logs enabled, i.e. forgot to reset to off.

Meanwhile (not really relevant to the Banlist Log issue here) I also saw MJ12bot bot was hitting my site thousands of times, so have added an exclusion to .htaccess

**Comment by MikeyGMT** [comment]
In this line, we are checking status not 0 then call logBanItem which I think writes the log. 

if ($ipStatus != 0)

But Whitelist >0 
Blacklist < 0 

Hence should the check be less than 0 

if ($ipStatus < 0)
then call logBanItem

**Comment by MikeyGMT** [comment]
Ah no, maybe move the logBanItem into the blacklist nested if. Hence : -

```
		if ($ipStatus != 0)
		{
			if ($ipStatus < 0)
			{	// Blacklisted
  			$this->logBanItem($ipStatus, 'result --> '.$ipStatus);
				$this->banAction($ipStatus);		// This will abort if appropriate
			}
			elseif ($ipStatus > 0)
			{	// Whitelisted - we may want to set a specific indicator
			}
		}

```

**Comment by CaMer0n** [comment]
@MikeyGMT Would you mind testing that change on your site?

**Comment by MikeyGMT** [comment]
Yes doing that now :+1:

**Comment by CaMer0n** [comment]
Thanks! :+1:

**Comment by MikeyGMT** [comment]
Yes - this worked.

Whitelisted my IP. 

Navigated around in sessions logged-on and logged-off. 

Checked banlist.log timestamp unchanged. No new entry.

Regards the die line, not sure what was going on, as the logs have all been cleared, I can't recreate the conditions. 

My Git Repo needs a total refresh. I'll try to do that. But it may be quicker for one of you guys who are nicely up to date to do move the line down.

**Comment by MikeyGMT** [comment]
Tested, working correctly, no log entries for whitelist ip's,  
@CaMer0n sorted my git issues - you may see some odd activity generated by me - hopefully I have reverted the incorrect git transactions!

**Comment by MikeyGMT** [comment]
Thanks @CaMer0n - somehow my git got messed up - it thought my fork was the main fork. I think it's sorted now. I'll try do a small LAN change and test a pull request from my fork instead of committing to the master.
