### ISSUE TITLE
Missing SEF URL Profile for Forum plugin

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1326]
I can't select SEF URL profile for the plugin:
![kepernyokep - 2016-02-05 - 14 08 59](https://cloud.githubusercontent.com/assets/6043821/12847251/2dffc2e0-cc12-11e5-899a-21eb1c7ceb0c.png)

**Comment by CaMer0n** [comment]
@lonalore This needs to be removed entirely. There is no profile selection for the forum plugin.
