### ISSUE TITLE
Last cron refresh: Never

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1327]
I created a crontab to run the command (suggested by e107) on my server every minute. And it works properly, it runs every minutes.

But, after visiting "e107_admin/cron.php" page, I get this:
![kepernyokep - 2016-02-05 - 14 15 52](https://cloud.githubusercontent.com/assets/6043821/12847456/a4ac9fb6-cc13-11e5-95ac-0df64f8800be.png)

After refreshing the page continuously, (maximum a minute later) I get this:
![kepernyokep - 2016-02-05 - 14 16 14](https://cloud.githubusercontent.com/assets/6043821/12847489/d76c0482-cc13-11e5-9c79-90e4bd076253.png)

But... if I visit another page (e.g. admin front page), then I visit "e107_admin/cron.php" page again, I get the following message again:
![kepernyokep - 2016-02-05 - 14 17 08](https://cloud.githubusercontent.com/assets/6043821/12847516/29d54c92-cc14-11e5-9257-8ba18eb921ed.png)

**Comment by CaMer0n** [comment]
@lonalore I have noticed this one too.
