### ISSUE TITLE
Wrong type is set for input field in inline editor

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1330]
Wrong type is set for input[type=number] field in inline editor.

I have an integer field, which has proper type (number) on create/edit form:
![kepernyokep - 2016-02-05 - 15 09 08](https://cloud.githubusercontent.com/assets/6043821/12848526/d9bddf2e-cc1a-11e5-836b-e90435683a94.png)

But in the inline editor, it has type "text":
![kepernyokep - 2016-02-05 - 15 09 30](https://cloud.githubusercontent.com/assets/6043821/12848550/f4a47294-cc1a-11e5-9b51-b141ff894b03.png)

Is this a bug, or I missed something?

**Comment by Moc** [comment]
Is this still an issue?
