### ISSUE TITLE
Cannot display users list due to broken newforumposts_menu

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1337]
I use e107 v2.0.

When I load /user.php, nothing is shown and I get this error :

 SQL Analysis

1 Query Errors!
Index	Query / Error
63  	SELECT p.post_user, p.post_id, p.post_datestamp, p.post_user_anon, p.post_entry, t.thread_id, t.thread_datestamp, t.thread_name, u.user_name FROM `e107_forum_post` as p LEFT JOIN `e107_forum_thread` AS t ON t.thread_id = p.post_thread LEFT JOIN `e107_user` AS u ON u.user_id = p.post_user WHERE p.post_forum IN (1,2,3,4,6,9,13,15,16,17,18,19,22,23,24,26,28,32,33,34,35,36,39,41,42,44,45,46,49,50,54,55,56,57,59,60,61,62,63,64,65,68,70,71,72,73,74,75,76,77,78,80,81,82,83,84,85,86,89,90,91,92,93,94,95,96,97,100,101,104,105,106,107,108,109) ORDER BY p.post_datestamp DESC LIMIT 0,
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 8

PHP Errors:

Warning: array_change_key_case() expects parameter 1 to be array, null given, Line 134 of [MYPATH]/www/e107_handlers/comment_class.php

**Comment by tgtje** [comment]
related to or part of #1336 ? ; ( i.e.  forum..post/threads called..)

**Comment by pierre0042** [comment]
maybe... it's the same installation

**Comment by Moc** [comment]
Yeah definitely related. The forum update did not go properly. Closing this issue. Please continue discussion in the other one.

**Comment by pierre0042** [comment]
So actually the SQL error comes from the "newforumpost" menu. After a Forum upgrade from v1 to v2 this menu doesn't work anymore. I have removed the menu as a temporary solution...

However, I still have the PHP warning.

**Comment by Moc** [comment]
No this can be sorted out through this issue, no need to create a new one. Thanks!

**Comment by CaMer0n** [comment]
@pierre0042 This menu is working again.

**Comment by pierre0042** [comment]
Not completely it seems :
http://imgur.com/wsE4t1Q

**Comment by CaMer0n** [comment]
Did you scan your plugin directories?

**Comment by pierre0042** [comment]
Now yes...
Here is what I got :
http://imgur.com/tmvc7I1

**Comment by CaMer0n** [comment]
Thanks. You can delete e_latest.php and e_status.php. Btw. you know you can drag images straight in there, right?

**Comment by pierre0042** [comment]
Ok thanks after files deletion its working again
