### ISSUE TITLE
Issue: Converted Themes show error

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1341]
Error
There is no layout in theme.php with the key: default

![capture](https://cloud.githubusercontent.com/assets/5818022/12904856/dcd0a528-ce97-11e5-911b-848e34896ee2.PNG)

I sync the e107 core files the other day and now this error is displaying.

**Comment by CaMer0n** [comment]
Please share your theme.xml

**Comment by Jimmi08** [comment]
I noticed this too in custom theme, I needed to add to theme $LAYOUT['mykey'] ...  
But his theme use old way with  $layout = "_default";  Maybe legacy problem?
in xml: ```<layout name='default' title='Default' default='true'/>```

**Comment by CaMer0n** [comment]
theme.php should contain a $HEADER['default'] and $FOOTER['default'] or the entry should be removed from theme.xml

**Comment by CaMer0n** [comment]
I made a minor change which could affect this. Please test again.

**Comment by LaocheXe** [comment]
The error no longer displays

**Comment by CaMer0n** [comment]
okay. Thank you. :+1:
