### ISSUE TITLE
ejs_preload issue on consolidated script 

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1344]
looks like a script conflict somewhere, 
when all scripts are consolidated into one file ejs_preload is undefined.

when theme img preloading is turned off, everything seems ok.

**Comment by CaMer0n** [comment]
If you take a look at the files generated in e107_web/cache perhaps you will see the issue?

**Comment by willem010** [comment]
i have been trying to find out whats happening here,

the function is loaded, present in the window object,
but when called it returns undefined.

maybe the call is too soon? and the js is not loaded yet?

**Comment by CaMer0n** [comment]
That javascript image preload code is VERY old. Perhaps we should be doing something like this instead? https://perishablepress.com/a-way-to-preload-images-without-javascript-that-is-so-much-better/

**Comment by willem010** [comment]
everything works just as fast without it haha.
no idea why i was using it anyway.

but that method seems to make more sense yep.

**Comment by CaMer0n** [comment]
This is the future of preloading. This old javascript is probably best removed. http://caniuse.com/#search=prefetch

**Comment by willem010** [comment]
:D perfect !!
