### ISSUE TITLE
consolidation into 1 file only working when js/css cache is on.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#1345]
For some reason the js/css cache switches consolidation.
when caching is on, i get 1 css and 1 js file just like i want.
when turned off, i get lots of js and css files. 
regardless of the javascript framework settings in prefs.
(those do not seem to do anything?)

**Comment by CaMer0n** [comment]
Most of it was experimental from what I see.

**Comment by willem010** [comment]
if it's not doing anything, i opt for a removal ? or revival of the options?

imo, just having one file should be all we want, but maybe turning consolidation off helps some devs when they encounter scripts issues. its a lot easier to debug small files.
caching on or off should be ok with just the one setting in cache prefs.
