### ISSUE TITLE
News are not visible and cannot be chosen from blog calendar

### ISSUE THREAD

**Issue by xenos88** [e107inc/e107#1346]
News are not visible and cannot be chosen from date picker. Tried several fresh installations and changing themes, did not work. The problem is also visible on the e107 website, f.e. (http://e107.org/blog/day/20160902.html).

**Comment by CaMer0n** [comment]
Thank you! Will look into it! :+1:

**Comment by CaMer0n** [comment]
@xenos88 I just realized the link you provided is for a day without a news release. Does this work for you? http://e107.org/blog/day/20150208.html

**Comment by xenos88** [comment]
Hello, the link does work. However, i can not still make the news working on my local machine. Spent already like 2 weeks on that. After a fresh installation it does not display any news (created by me in the admin panel or provided). It always shows no items. Moreover, after adding news it get's them to the count to the amount of posts in the month, but with "No news items for specified month".

**Comment by CaMer0n** [comment]
@xenos88 - Perhaps we can talk about it on gitter: https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
@xenos88 Please update and test again. Thank you.

**Comment by Jimmi08** [comment]
@CaMer0n You can close this. Tested on latest github. It works with EN and SK lang, with SEF url and with default.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! :+1:
