### ISSUE TITLE
plugin.xml wrong parse "error"?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1348]
Somehow, the plugin.xml check doesn't like portuguese language....
If i put this line
`<e107Plugin name="FilLis - Listas Filatélicas" version="0.30a" compatibility="2.0" installRequired="true" xhtmlcompliant="true" >`
or any other accented portuguese text inside the plugin.xml file, the plugin manager returns
> Error reading phlist/plugin.xml
> Parsing failed - file format error: phlist

and the plugin is not even listed on the installed plugins or to be installed plugins...
I've donne a XML check on my accented plugin.xml file, and is all ok, without any errors...

If i remove the accents, all is right....

Does the plugin.xml parser only likes non accented languages??? Or is it a bug with the parser???

**Comment by tgtje** [comment]
just commenting : when using plugin builder it IS mentioned that plugin name and some more... have to be English ....

**Comment by rica-carv** [comment]
I didn't use the plugin builder on that specific plugin, since i'm upgrading to v2 all my plugins, so i didn't noticed that crumbersome rule....
So, all the plugins have to be written in English?
Good way to go.....

**Comment by CaMer0n** [comment]
plugin.xml is in English, with lan="LAN_DEFINITION" to other languages for specific tags. (see forum/plugin.xml for an example)

**Comment by rica-carv** [comment]
So, on other words, i'll also have to upgrade all the lan files from my 1.4 plugins to the v2 structure (as in forum/languages)???

**Comment by Moc** [comment]
Well that would be the most optimal solution yes, especially to prepare for future updates. 

The minimal requirement however, is having English language files. These should already be present. The plugin.xml also needs to be in English, but you can reference the LAN_* for multilanguage. (See the forum plugin.xml for an example). So the only thing you need to change is:

`<e107Plugin name="ENGLISH NAME HERE" lan="LAN_REFERENCE_HERE".....`

Hope this helps
