### ISSUE TITLE
class2.php errors after install

### ISSUE THREAD

**Issue by kevinmui** [e107inc/e107#1349]
CRITICAL ERROR:

Line 483 /var/www/html/class2.php
Error reported as: [3]: Core settings saved - backup made active.
CRITICAL ERROR:

Line 485 /var/www/html/class2.php
Error reported as: [4]: No core backup found. Check that your database has valid content.

What's a guy to do?

**Comment by Moc** [comment]
Are you using the ZIP file from the e107.org website or are you using the latest files from Github?

Try downloading the latest files by clicking here: https://github.com/e107inc/e107/archive/master.zip 
Then reinstall. 

This way, you get all the recent bugfixes. If I remember correctly, there were some issues with the MySQL strict mode, causing the issue you are experiencing. Using the newest files should fix this.

**Comment by kevinmui** [comment]
Yes just grabbed the master.zip from Git ~15 minutes ago.  I will try again (tried many times over for the past 2 days!)  It's hit and miss thus far.  Sometimes install would go through (but with image problems), most of the time, class2 error.

php 5.5.9
mysql 14.14
ubuntu 14.04.2 lts

**Comment by Moc** [comment]
That's actually pretty interesting (the fact that sometimes it works and sometimes it does not) 

@CaMer0n Any suggestions on how to debug this?

**Comment by kevinmui** [comment]
@Moc 

I tried the master.zip, and that tar.gz from the sourceforge.  Difference I see from the installer is that master.zip does one extra check.

EXIF extension	Installed	 PASS

Aside from that, same outcome.

**Comment by Moc** [comment]
@kevinmui Can you check if MySQL runs in strict mode? Also, can you provide an export from your database table directly after install?

**Comment by Moc** [comment]
Related: #1207 and #1102

**Comment by kevinmui** [comment]
@Moc https://app.box.com/s/uun0rx4ip31z3nbtlfc78qkjw04ck8kk export file directly after install leading to the error.

**Comment by CaMer0n** [comment]
@kevinmui Please join us at https://gitter.im/e107inc/e107 to troubleshoot in real-time, if you have time.

**Comment by CaMer0n** [comment]
@kevinmui I ran some tests on PHP7 and committed some changes. Would you mind testing again?

**Comment by Moc** [comment]
@kevinmui Is this issue still happening?
