### ISSUE TITLE
Unable to add comment on downloads

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1351]
I cannot add a comment on a download page, despite the fact that I allowed comments on the admin options.

"0 comments" is shown but there is no field to add a comment.

Screenshot :

![qka9f1c](https://cloud.githubusercontent.com/assets/577978/13017683/e4258e0c-d1c5-11e5-8114-4ea3f284cca8.png)

**Comment by CaMer0n** [comment]
Please tell me, what theme is that you're using?

**Comment by pierre0042** [comment]
Information:	Supplementary theme ported by veskoto. Desing Free CSS Templates.

**Comment by tgtje** [comment]
Theme has not issues on this.... (comments work)
![dlc](https://cloud.githubusercontent.com/assets/1811857/13018609/c9bad68a-d1ca-11e5-8f0e-043b26d7fdb7.jpg)

**Comment by pierre0042** [comment]
Running "Repair plugin" doesn't fix the problem for me

**Comment by CaMer0n** [comment]
Tested with jayya v1.x theme and it works as expected. @pierre0042 This would appear to be an issue with this theme in particular. Could you try with some others?

**Comment by pierre0042** [comment]
Ok I will try to do that.

**Comment by pierre0042** [comment]
Ok it works with another theme (I tried with bread_of_life).
So this is probably theme-related...

**Comment by LaocheXe** [comment]
I had a legacy theme - what I did was copy the core templates and added them to the theme folder

themefolder -> templates

**Comment by CaMer0n** [comment]
@pierre0042 Just delete or rename the download template in your theme's folder, and it will automatically load the default one.

**Comment by pierre0042** [comment]
There is no "templates" folder in the theme currently

**Comment by pierre0042** [comment]
Adding the one from the "core" makes a "Submit comment " text appear but no box to enter text aside...

**Comment by pierre0042** [comment]
It's maybe related to this error I see at the bottom of the page :

PHP Errors:

Warning array_change_key_case() expects parameter 1 to be array, null given, Line 134 of [MYPATH]/www/e107_handlers/comment_class.php

**Comment by pierre0042** [comment]
Adding the e107_core/templates/ directory in my theme fix the problem (and the php error).
Thanks.
