### ISSUE TITLE
Some errors after plugins scan

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1353]
I see this errors after a plugin scan :

![e107plugins](https://cloud.githubusercontent.com/assets/4124597/13026988/3bce291c-d23d-11e5-88d3-a5a947e602e2.png)

**Comment by tgtje** [comment]
These are not real errors,   > hover mouse for info <  ; it warns you (due to older plugin) that  inside uses deprecated coding/standards which have been changed in v2

**Comment by pierre0042** [comment]
So I can basically ignore this ?

**Comment by CaMer0n** [comment]
Yes, they're just warnings.
