### ISSUE TITLE
PHP 7.0 not working with e107

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#1356]
Does E107 v2 support PHP 7.0.3 ?

**Comment by LaocheXe** [comment]
Just changed my server to PHP 7.0 - get a blank screen. So I don't think it does support it yet.

**Comment by Moc** [comment]
That may indeed be the case, since e107 is likely to use some outdated code which has been deprecated and removed since 5.3. It would be interesting to see what kind of errors it throws. So please use the debugger and post some of those errors here if you like. Then for the future, these can be reviewed.

**Comment by LaocheXe** [comment]
I used the e107 Debug tool for FireFox and nothing showed up on my end.

**Comment by Moc** [comment]
Ah probably because it throws a fatal error before debug can be initialized. Well all right. Then it will be manual debug work. I might fire up a test environment with PHP 7 to test sometime, but knowing me it will take a while haha.

**Comment by LaocheXe** [comment]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/xxxxxxx/public_html/xxxxxx/e107_handlers/mysql_class.php:203 Stack trace: #0 /home/xxxxxxx/public_html/xxxxxx/class2.php(410): e_db_mysql->db_Connect('localhost', 'dbUser', 'dbPass', 'dbTableName') #1 /home/xxxxxxx/public_html/xxxxxx/index.php(56): require_once('/home/clancoy1/...') #2 {main} thrown in /home/xxxxxxx/public_html/xxxxxx/e107_handlers/mysql_class.php on line 203

**Comment by LaocheXe** [comment]
looks like on my server the PHP 7 extensions are missing mssql and mysql

**Comment by CaMer0n** [comment]
Finally got PHP7 running on a portable webserver. Fixes coming shortly.

**Comment by dimante** [comment]
Nice!!

On Sunday, February 14, 2016, Cameron <notifications@github.com> wrote:

> Finally got PHP7 running on a portable webserver. Fixes coming shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1356#issuecomment-183964636>.
>


-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by tgtje** [comment]
Well, it's not 7.0.3 but 7.0.2 will do too ? (visual confirm)
![php7](https://cloud.githubusercontent.com/assets/1811857/13046656/509640de-d3da-11e5-965a-834a01b6a727.jpg)

**Comment by dimante** [comment]
http://php.net/ChangeLog-7.php#7.0.3



On Mon, Feb 15, 2016 at 4:50 AM, leo <notifications@github.com> wrote:

> Well, it's not 7.0.3 but 7.0.2 will do too ? (visual confirm)
> [image: php7]
> <https://cloud.githubusercontent.com/assets/1811857/13046656/509640de-d3da-11e5-965a-834a01b6a727.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1356#issuecomment-184164613>.
>



-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by tgtje** [comment]
Thanks but was aware of already 3thrd version in 3 months..., my hoster may or may not update at point in time ( not using 7 normally  as too much going on in 'the head', and since guessing most users are in the 5 versions , thats prime target.. at least for me ).

**Comment by LaocheXe** [comment]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /public_html/defiantz/e107_handlers/mysql_class.php:206 Stack trace: #0 /public_html/defiantz/class2.php(411): e_db_mysql->db_Connect('localhost', '*************', '*************', '********') #1 /public_html/defiantz/index.php(56): require_once('...') #2 {main} thrown in /public_html/defiantz/e107_handlers/mysql_class.php on line 206

**Comment by CaMer0n** [comment]
@LaocheXe If you switch to PHP7, you'll need to add: `define('e_PDO', true);` in your e107_config.php

**Comment by CaMer0n** [comment]
Added an auto-detect for an easy upgrade. ;-)

**Comment by tgtje** [comment]
Still have some issues on an update but here's a fresh one (not meant as advertising, and not up to date by content > tgtje.nl  > running on php 7.0.3   **(fresh install)** 1 issue = create database not accepted  who's error ? mine? or credentials from server..?

**Comment by CaMer0n** [comment]
I've run the full install process on 7.0.2 (including create database), but not 7.0.3 yet.

**Comment by tgtje** [comment]
@CaMer0n still got the private window ? ;-)

**Comment by CaMer0n** [comment]
Thanks @tgtje  - I saw it thanks. I will try to get a local version of 7.0.3 first, but thank you for setting it up. It will be good to have it tested on a remote machine also.

**Comment by dimante** [comment]
I have a 7.0.3 install on Windows so we can get that one tested too :-)

On Thu, Feb 25, 2016 at 8:49 PM, Cameron <notifications@github.com> wrote:

> Thanks @tgtje <https://github.com/tgtje> - I saw it thanks. I will try to
> get a local version of 7.0.3 first, but thank you for setting it up. It
> will be good to have it tested on a remote machine also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1356#issuecomment-189086635>.
>



-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by CaMer0n** [comment]
@dimante Excellent! the more the merrier! 

btw. For anyone wishes to run a test webserver on Windows (@Moc, @MikeyGMT  ?) , I just started using this:
 **Uniform Server Zero XII** 

A modular system, and I can test SSL locally as well. :+1: 

More info: 
http://www.uniformserver.com/ZeroXII_documentation/
https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXII/

**Comment by CaMer0n** [comment]
Update: Just ran a fresh install on 7.0.3 without issues.

**Comment by dimante** [comment]
But what about all the fun challenges of iis lol :)

On Friday, February 26, 2016, Cameron <notifications@github.com> wrote:

> @dimante <https://github.com/dimante> Excellent! the more the merrier!
>
> btw. For anyone wishes to run a test webserver on Windows (@Moc
> <https://github.com/Moc>, @MikeyGMT <https://github.com/MikeyGMT> ?) , I
> just started using this:
> *Uniform Server Zero XII*
>
> A modular system, and I can test SSL locally as well. [image: :+1:]
>
> More info:
> http://www.uniformserver.com/ZeroXII_documentation/
>
> https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXII/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1356#issuecomment-189401577>.
>


-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Should I grab the latest GIT and try this?

On Fri, Feb 26, 2016 at 12:22 PM, John Gates <dimante@dimante.net> wrote:

> But what about all the fun challenges of iis lol :)
>
>
> On Friday, February 26, 2016, Cameron <notifications@github.com> wrote:
>
>> @dimante <https://github.com/dimante> Excellent! the more the merrier!
>>
>> btw. For anyone wishes to run a test webserver on Windows (@Moc
>> <https://github.com/Moc>, @MikeyGMT <https://github.com/MikeyGMT> ?) , I
>> just started using this:
>> *Uniform Server Zero XII*
>>
>> A modular system, and I can test SSL locally as well. [image: :+1:]
>>
>> More info:
>> http://www.uniformserver.com/ZeroXII_documentation/
>>
>> https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXII/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/e107inc/e107/issues/1356#issuecomment-189401577>.
>>
>
>
> --
>
> *Let’s Connect!*
>
> <https://twitter.com/johngatesIII>
> <http://www.linkedin.com/in/JohnGates>
>
> *This email may contain information that is confidential or
> attorney-client privileged and may constitute inside information. The
> contents of this email are intended only for the recipient(s) listed above.
> If you are not the intended recipient, you are directed not to read,
> disclose, distribute or otherwise use this transmission. If you have
> received this email in error, please notify the sender immediately and
> delete the transmission. Delivery of this message is not intended to waive
> any applicable privileges.*
>
>


-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by CaMer0n** [comment]
@dimante Sure :+1:

**Comment by dimante** [comment]
Cameron.  Good work!  With the latest GIT pull my windows existing installation is working with PHP 7.0.3  I can keep this open if you wish to wait for feedback on other versions besides windows.

**Comment by CaMer0n** [comment]
Great! :+1:   I'll close this now. We can now consider any news bugs with PHP 7 as regular bugs with their own issue number.

**Comment by dimante** [comment]
Sounds good!

On Sun, Feb 28, 2016 at 3:13 PM, Cameron <notifications@github.com> wrote:

> Closed #1356 <https://github.com/e107inc/e107/issues/1356>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/1356#event-570087008>.
>



-- 

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*
