### ISSUE TITLE
Fix: YouTube and Media Manager

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1357]
So I've been trying to use the insert YouTube Videos via Media Manager - but running into issues.

First issue is the Debug: gives the url like this - https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=&type=video&maxResults=20&key=

Issue is it is missing the API key that is entered into the Media Manager settings, it is also missing the channelid as well

e107_admin/image.php
On line 1461 $apiKey is commented out
// $apiKey = e107::pref('core', 'youtube_apikey'); 
Remove the // and have it as
$apiKey = e107::pref('core', 'youtube_apikey');

On line 1529 $channelID = null;
Change to
$channelID = e107::pref('core', 'youtube_default_account');

**Comment by CaMer0n** [comment]
Thanks for the fix.
