### ISSUE TITLE
Error when updating download file

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1360]
In the Downloads > Manage section, when I edit one download, I change the file, select it from the Media Manager, Close, and when I click on "Update Download", I got this error displayed at the bottom of the page :

PHP Errors:

Warning filesize(): stat failed for ../../e107_files/downloads/Il y a un merveilleux a se dire que l on invente sa vie.mp3, Line 1630 of /home/polyamou/www/e107_plugins/download/includes/admin.php

**Comment by CaMer0n** [comment]
@pierre0042 If you re-import your vile and remove all the spaces from it's name, does it stop the error?

**Comment by pierre0042** [comment]
I cannot reproduce anymore.
