### ISSUE TITLE
errors in console

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1365]
Hi,
latest github files, I didn't notice this before, it has to be related to latest changes:

- fresh install
- go to news category
- edit category
- upload icon via media manager - first error
- insert icon (still in edit form) -  two errors

![image](https://cloud.githubusercontent.com/assets/5429548/13118659/8df79604-d5a5-11e5-8add-d0f30b729b70.png)

insert image to news:
![image](https://cloud.githubusercontent.com/assets/5429548/13118804/4bcaef00-d5a6-11e5-93b5-8caba689e509.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Is this one still occurring?

**Comment by Jimmi08** [comment]
Tested. No error. Thank you.
