### ISSUE TITLE
Errors in categories list

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1366]
In /e107_plugins/download/admin_download.php?mode=cat&action=list

At the bottom of the page I have :

PHP Errors:

Warning strlen() expects parameter 1 to be string, array given, Line 1459 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning strpos() expects parameter 1 to be string, array given, Line 1459 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning preg_split() expects parameter 2 to be string, array given, Line 1631 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning Invalid argument supplied for foreach(), Line 1632 of /home/polyamou/www/e107_handlers/e_parse_class.php
[...]

**Comment by Moc** [comment]
Pretty sure this has been fixed by now. If not, please let us know and I'll re-open.
