### ISSUE TITLE
Error when rebuilding class hierarchy

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1368]
Success
Rebuilding class hierarchy: completed

but at the bottom :

PHP Errors:

Warning Invalid argument supplied for foreach(), Line 1329 of /home/polyamou/www/e107_handlers/userclass_class.php

**Comment by pierre0042** [comment]
Error message is displayed 4 times

**Comment by pierre0042** [comment]
At the bottom of /e107_admin/userclass2.php, I see the nearly same error 2 times :

Warning Invalid argument supplied for foreach(), Line 1363 of /home/polyamou/www/e107_handlers/userclass_class.php

**Comment by Moc** [comment]
I am pretty sure this has been fixed by now. If not, please let us know and I'll re-open.
