### ISSUE TITLE
Forum Plugin URLs incorrect.

### ISSUE THREAD

**Issue by Aegypticus** [e107inc/e107#1369]
When I install the base Forum plugin it does not form the URLs for links correctly. It point to a "Forums" folder in the root instead of the \e107_plugins\Forums folder. The redirects listed in URL Configuration for the Forum plugin do not seem to work. If I disable SEF for the Main Forum link, it works, but any Forums I create do not create their sub filder or files and link to the non-existant Forum folder in to root.

**Comment by Moc** [comment]
- Is your .htaccess file working? The e107.htaccess file should be renamed to .htaccess. 
There is no need to create any folder with redirects. 

- Please also try using the latest files from Github. You can easily update to the latest Github files using the 'developer mode': go to preferences > advanced > developer mode > enable, then into Tools > Database > Sync with Github.

**Comment by Aegypticus** [comment]
Thanks for Pointing the way Moc! I ended up needing to uncomment the line below in .htaccess (worked without using renamed e107.htaccess) for the rewrites to work properly.

### Set this to your e107 site root, path relative to web root
 ### Uncomment it in case your server isn't able to rewrite proper
  RewriteBase /

Maybe it is something with the Gadaddy Host server.

**Comment by Moc** [comment]
Glad you sorted it out! 
GoDaddy has a terrible history with e107, just so you know haha. Don't be surprised if you run into more issues.
