### ISSUE TITLE
eURL bug in the forum plugin?

### ISSUE THREAD

**Issue by KonzolozZ** [e107inc/e107#1370]
Hello,

I updated the e107 CMS from v1.04 to v2. I upgraded the forum (each steps compleated prefectly). If i disable eURL in the e107_config (and also renamed e107.htaccess to .htaccess) file the forum works perfectly, but if i enable eURL option i have lots of same forum name and the forum link not contain forum ID. In this situation i access only one forum.

Once a time i get valid url, but i don't know how.

Regards,
EkE

**Comment by CaMer0n** [comment]
Thank you. Could you please share a screenshot of what you are enabling?

**Comment by KonzolozZ** [comment]
Hello,

I put define('e_MOD_REWRITE',true); to the config file. Downloads working correctly, but i have lots of same forum links:
https://dl.dropboxusercontent.com/u/2731244/e107/konzolozz-forum.jpg

**Comment by CaMer0n** [comment]
@KonzolozZ I'm unable to reproduce this problem. Could you please check that all your forum categories have SEF Urls?

**Comment by KonzolozZ** [comment]
Yes, all category has SEF URL, but some URL is same because it is generated from the topics name.
The SEF why not contain the topic id example?

**Comment by CaMer0n** [comment]
@KonzolozZ Forum category SEFs (as set in the admin area) should all be unique. Forum topic SEFs are auto-generated and do include the topic id.
