### ISSUE TITLE
RSS feeds not working

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1371]
I tried to repair the RSS plugin but it doesn't change anything.

Clicking on the RSS button 
/e107_plugins/rss_menu/rss.php?cat=news&type=2&topic=
gives me this :

rssCreate Object
(
    [e107:protected] => e107 Object
        (
            [server_path] => /
            [e107_dirs] => Array
                (
                    [ADMIN_DIRECTORY] => e107_admin/
                    [IMAGES_DIRECTORY] => e107_images/
                    [THEMES_DIRECTORY] => e107_themes/
                    [PLUGINS_DIRECTORY] => e107_plugins/
                    [FILES_DIRECTORY] => e107_files/
                    [HANDLERS_DIRECTORY] => e107_handlers/
                    [LANGUAGES_DIRECTORY] => e107_languages/
                    [DOCS_DIRECTORY] => e107_docs/
                    [MEDIA_DIRECTORY] => e107_media/a447c103fd/
                    [SYSTEM_DIRECTORY] => e107_system/a447c103fd/
                    [CORE_DIRECTORY] => e107_core/
                    [WEB_DIRECTORY] => e107_web/
                    [HELP_DIRECTORY] => e107_docs/help/
                    [DOWNLOADS_DIRECTORY] => e107_files/downloads/
                    [MEDIA_IMAGES_DIRECTORY] => e107_media/a447c103fd/images/
                    [MEDIA_ICONS_DIRECTORY] => e107_media/a447c103fd/icons/
                    [MEDIA_VIDEOS_DIRECTORY] => e107_media/a447c103fd/videos/
                    [MEDIA_FILES_DIRECTORY] => e107_media/a447c103fd/files/
                    [MEDIA_UPLOAD_DIRECTORY] => e107_system/a447c103fd/temp/
                    [AVATARS_DIRECTORY] => e107_media/a447c103fd/avatars/
                    [WEB_JS_DIRECTORY] => e107_web/js/
                    [WEB_CSS_DIRECTORY] => e107_web/css/
                    [WEB_IMAGES_DIRECTORY] => e107_web/images/
                    [UPLOADS_DIRECTORY] => e107_system/a447c103fd/temp/
                    [CACHE_DIRECTORY] => e107_system/a447c103fd/cache/
                    [CACHE_CONTENT_DIRECTORY] => e107_system/a447c103fd/cache/content/
                    [CACHE_IMAGE_DIRECTORY] => e107_system/a447c103fd/cache/images/
                    [CACHE_DB_DIRECTORY] => e107_system/a447c103fd/cache/db/
                    [CACHE_URL_DIRECTORY] => e107_system/a447c103fd/cache/url/
                    [AVATARS_UPLOAD_DIRECTORY] => e107_media/a447c103fd/avatars/upload/
                    [AVATARS_DEFAULT_DIRECTORY] => e107_media/a447c103fd/avatars/default/
                    [LOGS_DIRECTORY] => e107_system/a447c103fd/logs/
                    [BACKUP_DIRECTORY] => e107_system/a447c103fd/backup/
                    [TEMP_DIRECTORY] => e107_system/a447c103fd/temp/
                    [IMPORT_DIRECTORY] => e107_system/a447c103fd/import/
                    [MEDIA_BASE_DIRECTORY] => e107_media/a447c103fd/
                    [SYSTEM_BASE_DIRECTORY] => e107_system/a447c103fd/
                )

            [e107_config_mysql_info:protected] => Array

(I cut it here but you see the problem)

**Comment by CaMer0n** [comment]
Please disable DEBUGGING.

**Comment by pierre0042** [comment]
Ok it seems that the debug mode was responsible for this.
With debug disabled it now works fine.
Thanks.
