### ISSUE TITLE
Cannot display all forum posts

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1373]
When I look at an user details
/user.php?id.42 for example
It shows at the end  :
Forum posts 	1387 ( 14.09% )
Comments posted	3 ( 2.88% )

With a link on the number to display these posts/comments
But when I follow the link
(for example for forum posts it is /userposts.php?0.forums.42 )
only 1 result is shown... (seems to be the more recent)

**Comment by CaMer0n** [comment]
Please run this query in phpmyadmin: 
```mysql
SELECT * FROM `e107_forum_post` WHERE `post_user` = 42 ORDER BY `post_datestamp` DESC 

How many records do you see?

**Comment by pierre0042** [comment]
Showing rows 0 - 29 (1,390 total, Query took 0.0004 sec)

**Comment by pierre0042** [comment]
Changing the theme doesn't fix the problem for info

**Comment by CaMer0n** [comment]
@pierre0042 Please update from Github and try again. Thanks.

**Comment by pierre0042** [comment]
It doesn't fix it, sorry

**Comment by pierre0042** [comment]
The fix creates an error when I update from github and try to update the database :

CRITICAL ERROR:
Line 484 /home/polyamou/www/class2.php
Error reported as: [3]: Core settings saved - backup made active

**Comment by pierre0042** [comment]
Seems to work now

**Comment by pierre0042** [comment]
There is the same problem for comments actually

/userposts.php?0.comments.X displays only 1, although there is many.

I can create a new issue if you prefer.

**Comment by pierre0042** [comment]
Actually with the last fix the problem is not 100% solved, as I have no pagination displayed

**Comment by pierre0042** [comment]
Pagination is working now, thanks
