### ISSUE TITLE
smtp settings don't send emails

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1375]
Tested just with sending test email in Email preferencies, not contact page.

Result was message that mail was succesfully sended (no error) but never received

Reason for this is empty "sender", It has to be the same as "from" on my hosting. After manually changing this in code, mail was received and notification mail works too.

Because there are new settings, maybe I forgot somewhere to set "sender".  

I use normal SMPT settings (user, server, password), no SSL. The same as in version 1, that works.

Thanks

**Comment by LaocheXe** [comment]
Tested SMTP as well - got message was sent but nothing in the e-mail or junk-mail, used the SSL and TSL settings as well as the other settings (POP3 before SMTP) and no go.

**Comment by CaMer0n** [comment]
Some hosts block sending emails this way. Try enabling debug and then sending a test email.

**Comment by Jimmi08** [comment]
@CaMer0n Was your answer for me?  if yes, I did it and I found Sender is empty and I know from before that my hosting needs to have From and Sender the same values (and domain hosted in their servers)  I don't know how to get Sender filled.

**Comment by Jimmi08** [comment]
This line I needed to add to get smtp works on my old hosting:
![image](https://cloud.githubusercontent.com/assets/5429548/14938339/81718804-0f20-11e6-9323-abebcdc483e1.png)

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 I committed a change, would you mind testing it?

**Comment by Jimmi08** [comment]
Yes, but github sync get me black page, I need to do it manually and I haven't access to FTP now, I will try at the evening.

**Comment by Jimmi08** [comment]
@CaMer0n  Tested, sending test email works. Plus trigger notification too. Thank you.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! :+1:
