### ISSUE TITLE
Question: MyPlugin - Media Catagory

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1377]
I am developing a plugin that allows a admin to create ranks, awards, medals, etc......... each award, rank, medal gives them an option to upload an image - how do I create categories for the images?

Does my plugin get just one catagory or can I have unlimited categories? 

I did not see anything about this in the Dev plugin section on the e107 website.

**Comment by CaMer0n** [comment]
You should only need one category as the plugin will become the "owner" of that category. Check plugin.xml of gallery for an example to set it up.
