### ISSUE TITLE
Bug: Steam Auth (openID) Login fails

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1378]
I would like to ask someone to add a Steam Login to e107 - Steam uses OpenID and can be used as a Provider

https://steamcommunity.com/dev/

This should only take someone with better skills than me like 5/10 mins - all it needs is the API Key

**Comment by CaMer0n** [comment]
See if hybridauth has a plugin for it.

**Comment by LaocheXe** [comment]
http://hybridauth.sourceforge.net/userguide/IDProvider_info_Steam.html

https://github.com/hybridauth/hybridauth/blob/master/additional-providers/hybridauth-steam/Providers/Steam.php

Is that what you are asking for?

**Comment by LaocheXe** [comment]
I think that is what you asking for, I add that php file to e107_handlers/hybridauth/Hybrid/Providers correct? Then what, I add the apikey info in the social plugin?

Do I have to make any changes to the Providers/Steam.php file for e107?

**Comment by LaocheXe** [comment]
Okay so I added the Steam.php and added a steam with apikey to the admin_config.php uploaded it and added my Steam API Key - go to front page and get a Steam Icon to login with (not logged in) - click on the button and got × 
Error
[2]Signup failed! Wrong provider.

I don't know if I did something wrong or not.

**Comment by LaocheXe** [comment]
http://defiantz.org/?route=system/xup/test

Test login only with Steam I get error number [22]
Test signup/login with Steam I get error number [2]

**Comment by LaocheXe** [comment]
Okay I got it to work (some what) - added the Steam info into the config.php.tpl

(Using the Test xup to login/signup)
I click on the link to login - takes me to steam - Click the login button
Get this link (wrong link I think)
http://defiantz.org/?route=system/xup/endpoint&hauth.done=Steam&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198006790310&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198006790310&openid.return_to=http%3A%2F%2Fdefiantz.org%2F%3Froute%3Dsystem%2Fxup%2Fendpoint%26hauth.done%3DSteam&openid.response_nonce=2016-02-25T01%3A38%3A48ZzqrC5LpMhNeuq%2BU64SbN20BChNc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=upwKgrmlgj8AKHxsbqw6fmlKBE0%3D


The second button on the xup Test page does the same thing with this link
http://defiantz.org/?route=system/xup/endpoint&hauth.done=Steam&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198006790310&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198006790310&openid.return_to=http%3A%2F%2Fdefiantz.org%2F%3Froute%3Dsystem%2Fxup%2Fendpoint%26hauth.done%3DSteam&openid.response_nonce=2016-02-25T01%3A41%3A28ZM5UHhusIGlmP5mFkYg4dZjezGyo%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=44bzV%2BCYXUcVdHlWVNvbkDZ7ejg%3D


Any ideas?

**Comment by CaMer0n** [comment]
If you added the files, and the details to social/admin_config.php, I'm not sure what else to suggest. 
Some configs use 'key' while others use 'id'. Perhaps that's worth checking?

**Comment by LaocheXe** [comment]
Okay so it might be something I haven't done then?

What have I done so far:

Added Steam.php into the e107_handlers\hybridauth\Hybrid\Providers directory

Added this to e107_handlers\hybridauth\Hybrid\resources\config.php.tpl
`"Steam" => array (
            	"enabled" => #STEAM_ADAPTER_STATUS#,
                "keys"	  => array ( "key" => "#STEAM_APPLICATION_KEY#" )
            ),`

Added this to e107_plugins\social\admin_config.php
`"Steam" => array (
					"enabled" => true,
					"keys"	 => array ( "key" => "" )
				),`

Then added `"Steam" => "http://steamcommunity.com/dev/apikey",` in the `$this->social_external = array` in the admin_config.php for social.

Checked Steam.php and notice this:
`        // If API key is not provided, use legacy API methods
        if (!empty($this->config['keys']['key'])) {
            $this->getUserProfileWebAPI($this->config['keys']['key']);
        } else {
            $this->getUserProfileLegacyAPI();
        }`

I notice it calls for the $apiKey but how does it link to the database?

Taking screenshots of what I have right now

![first](https://cloud.githubusercontent.com/assets/5818022/13357398/983caade-dc6f-11e5-829a-78974790eb44.PNG)

![second](https://cloud.githubusercontent.com/assets/5818022/13357400/9c1d3024-dc6f-11e5-98e0-626a85479a75.PNG)

![third](https://cloud.githubusercontent.com/assets/5818022/13357403/9e7e7652-dc6f-11e5-932a-658aed3738a5.PNG)


So I don't know whats going on, check the users in the admin area and see no new user - so in the e107_handlers\hybridauth\Hybrid\resources\config.php.tpl I will enable debug and see if I can get something.

Debug file was empty and nothing on it.

After reading comments I notice a comment that told someone to update their HybridAuth library so I checked - main HybridAuth was updated 19 days ago while the one for e107 was last updated a year ago.

**Comment by LaocheXe** [comment]
I went and uploaded the current repo of hybridauth (https://github.com/hybridauth/hybridauth/tree/master/hybridauth)

making sure not to grab anything besides the files that e107 uses - that did nothing, found the log file from e107 (had to look in the system folder)

Im gonna delete that log and re-upload the e107 version of the hybridauth folder and add Steam to it once again

Attached below is the log file - changed filetype to txt for github

[hybridAuth.txt](https://github.com/e107inc/e107/files/148603/hybridAuth.txt)

I notice the apiKey is entered in the log - same apiKey I have entered in the social plguin. 

What I don't understand is the link = http://defiantz.org/?route=system
The part I can't understand is the defiantz.org/**_?route=system_**

why does it start with the ? is it using the index page? - I notice with the other log file I had facebook also used the same url and works - but what it does was login without taking me to facebook to approve the login (prob because I created the key etc)

In the log file above it does say [login_done] => http://defiantz.org/?route=system/xup/endpoint&hauth.done=Steam but idk if that is just for a link or not

What I just did was try to login using steam, when I got the white page I went and put in the url http://defiantz.org/?route=system/xup/endpoint&hauth.done=Steam   and got this error - [5]Authentication failed. Invalid request received!

However going to that address now gets a problem loading the page - so idk if it is an issue between e107 and the Steam.php or an issue inside the hybridauth code

**Comment by CaMer0n** [comment]
From what I remember, e107 doesn't use  hybridauth\Hybrid\resources\config.php.tpl - it is there just as a reference.

**Comment by LaocheXe** [comment]
Well what am I doing wrong here then? Should I take this to their github for more information/help?

**Comment by CaMer0n** [comment]
@LaocheXe Could you upload your changes to your fork and send a pull-request? Then I could check your code. Thanks.

**Comment by LaocheXe** [comment]
@CaMer0n done - did the pull request, take a look when you can.

**Comment by CaMer0n** [comment]
Tested by @LaocheXe and confirmed working. :+1:

**Comment by LaocheXe** [comment]
Alright, it work once - issue is - re-logging on.

So if a user uses Steam to login - they come back and use Steam to login again and then an issue comes up.


An error occurred while processing your request.

Reference #30.1675f648.1456694813.21ced38e 


Going to try this with Facebook to see if I can recreate it - but no - I am allowed to re-login with Facebook.

GitHub login re-login works as well

**Comment by CaMer0n** [comment]
@LaocheXe Try enabling e_DEBUG again, it could be related to e107_class.php again.

**Comment by LaocheXe** [comment]
It is enabled

Odd I just tried it again and it works

Thing I was testing out is that Steam allows users to change their display name, I wanted to see if I logged out and logged back in using Steam if my display name would change to what I changed it on Steam and it doesn't - keeps the first time display name.

I will keep trying to see if it comes up again

**Comment by LaocheXe** [comment]
Also with Steam you don't stay logged in

**Comment by LaocheXe** [comment]
After a few days and testing on other web browsers - logging in with Steam does not leave the person logged in - they can login, go to the forums and get logged out - I don't think it is a cookie thing but could be wrong.

Also can we add to the code to update the users Display name each time they login via Steam?

**Comment by CaMer0n** [comment]
Thanks. And if you use the github login, do you get logged out also?

**Comment by LaocheXe** [comment]
Right now it is allowing me to stay logged in - must have been a cookie/cache issue

**Comment by LaocheXe** [comment]
@CaMer0n How can we get this to update the users display name when they login on the site with Steam again? An example, Steam I have my name set to '[DG] LaocheXe' and logged into an e107 v 2 site with the Steam login function. Later that day I change my display name in Steam to 'Here It Comes' and go back to that same e107 v 2 site and login using the Steam function again.

Currently it does not update the user display name. 

Also another thing, Steam has user avatar's - how do we get that to work in e107 v 2?

**Comment by CaMer0n** [comment]
@LaocheXe It should update it now. Regarding the Steam avatar, it is up to the HybridAuth class to provide that info to e107. e107 will use it when found.

**Comment by LaocheXe** [comment]
Well on my members list (user.php) it has a image for the user - or what's so post to be an image - mouse hover and get this link: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/87/87e632c746d9c77f42e62f908eed

I don't know if that is an out-dated link because I uploaded a new avatar or not - well this is strange - I sync to github and logged in again - name updates - but also seems they use the name as a avatar

so I don't know - avatar is not an issue now - Thanks!!!!!
