### ISSUE TITLE
no test in news if social plugin is installed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1379]
With news (not important if theme use social shortcode or not), there is no test if social plugin is installed (it's not default)
Result:
![image](https://cloud.githubusercontent.com/assets/5429548/13213220/93ba347a-d947-11e5-9007-a349e64e9161.png)

I think that problem is in news.php here:
![image](https://cloud.githubusercontent.com/assets/5429548/13213249/c5bb628c-d947-11e5-982f-af929ebc6a95.png)

**Comment by CaMer0n** [comment]
You're right. It needs a check added.

**Comment by Jimmi08** [comment]
@CaMer0n 
This needs to be done else in e107_handlers/news_class.php
![image](https://cloud.githubusercontent.com/assets/5429548/13722818/fad5d5d8-e851-11e5-8b2f-5fa5b06b4b3b.png)
