### ISSUE TITLE
Cannot use non-ASCII characters in menu name

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1380]
When editing one of my menu I got this error :

![e107menu](https://cloud.githubusercontent.com/assets/4124597/13217157/c210bf24-d960-11e5-9faf-10240362cb67.png)

I think it was working in v1.

What is strange is that in the Menu list I can edit the menu names and use accents without error.

**Comment by CaMer0n** [comment]
The bug is that the inline editing is allowing it. Menu names should be ascii only. They are not displayed to the public, but are used by the code.

**Comment by pierre0042** [comment]
If they are not displayed to the public, I think I can deal with it.
