### ISSUE TITLE
PHP error when trying to see all comments from a user

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1381]
I go to /userposts.php?0.comments.42

It only display one comment, and at the end of the page I see (with debug mode) :

PHP Errors:

    Internal Error Message: Bad stored array data -

$data = array ( \'admin_cols_userclass_classes\' => array ( 0 => \'checkboxes\', 1 => \'userclass_id\', 2 => \'userclass_icon\', 3 => \'userclass_name\', 4 => \'userclass_description\', 5 => \'options\', ), );, Line 450 of /home/[PATH]/www/e107_handlers/core_functions.php

**Comment by Moc** [comment]
Is this issue still relevant seeing the other issues you created (of which some were fixed?)

**Comment by pierre0042** [comment]
I fixed this error which was not related
