### ISSUE TITLE
Custom Menu/Page > Update Page > LINK BB Code fails after 4 links in a list. 

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1383]
When attempt to update a page, I add a fourth link e,g. Three to I get 403. 

```
[h=2]Business Partners[/h]
* [link=http://www.theperfumeshop.com/]The Perfume Shop[/link]
* [link=http://www.superdrug.co.uk/]Superdrug[/link]
* [link=http://www.kruidvat.nl/]Kruidvat[/link]
* [link=http://www.three.co.uk/]Three[/link]
```

It does not seem to matter what site is used.

I have tested 
- using Lorem Ipsum .... , 3 x paragraphs - so it's not a size thing. 
- using bb editor
- using tinymce

It just bombs each time when I add the 4th URL in the page. 

It does NOT bomb when I put 

LINK 
Lorem ipsum ...
LINK 
Lorem ipsum ...
LINK 
Lorem ipsum ...
LINK 
Lorem ipsum ...

How strange?

**Comment by CaMer0n** [comment]
Is mod-security active?

**Comment by MikeyGMT** [comment]
I believe not, checked php_info, not found on page.

**Comment by MikeyGMT** [comment]
Problem remains active ... very strange

**Comment by rica-carv** [comment]
Can it be some setting enabling more than (x) links bbcode not allowed in page?
In this case, more than 3 links bbcode, the fourth is disabled?

**Comment by Moc** [comment]
I believe this to be a server side configuration which is triggered (such as mod security). I just tested this on various installations and it seems to work fine. 

Please contact your webhosting provider in case the issue persists. They may have a clue and can actually look into the server logs to check for more information on the 403.
