### ISSUE TITLE
weird behaviour with statistic logging plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1387]
Latest github, localhost
Developer mode ON (tested the same result with OFF)
I got this page when click to configure stats plugin:
![image](https://cloud.githubusercontent.com/assets/5429548/13362976/863cd518-dcc7-11e5-9b46-24ba6f6fcc89.png)

But when set on Firefox e107 debugger , page is changed:
![image](https://cloud.githubusercontent.com/assets/5429548/13363019/cd6ab680-dcc7-11e5-9b13-28dfe249725a.png)

Should this work this way? Thanks

**Comment by HDG-Krypt** [comment]
I can also confirm by default with statistic logging installed, the admin (e107_plugins/log/admin_config.php) page only renders the top image.

I am yet to try the solution with the FireFox e107 Debug Extension, but surely there is something amiss here.

Also I will note, I have not tried to replicate this same issue with alternate browsers just yet.
