### ISSUE TITLE
[Documentation] small mistake

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1389]
Well, there is no real problem with this, just a little correction to reach perfection hehe:

**_e_dashboard.php_**
Adds custom plugin information to the dashboard of e107's admin area. The 'latest', 'status' and 'website stats' areas may all contain information from your plugin. 
See e107_plugins/chatbox_menu**_/e_status_**.php for an example of usage. 

You are describing e_dashboard, not e_status, plus there is no e_status on chatbox_menu

Find it here: http://e107.org/developer-manual/plugin-basics#plugin-basics

Grts,
- Nes

**Comment by Moc** [comment]
Thank you! Fixed.
