### ISSUE TITLE
[Forum] Subjectbox not rendering in v1 theme

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1391]
On creating a new topic, there is no subject box.

This was an upgrade from a v1 to v2.

![screenshot](https://cloud.githubusercontent.com/assets/11775356/13380606/459c3aa2-de3f-11e5-8135-714948b977b7.PNG)

**Comment by LaocheXe** [comment]
You need the forum templates added to your theme - e107_plugins/forums/templates 

Just copy and past them into your theme's folder (ex: mytheme/templates/forum) <--- add them into that folder

**Comment by Brooniee** [comment]
@LaocheXe @CaMer0n 

tried this, still getting no subject box :(

my theme didn't have the structure templates/forum, so i created it and popped them in there, didn't work,
/e107_themes/Shaolin/templates/forum

i then tried in the root of the theme directory, still no luck ethier.
/e107_themes/Shaolin/

any suggestions?

**Comment by LaocheXe** [comment]
@Brooniee - CamEr0n just made a fix in the forum_post.php - I would download the e107 files from githum here and upload them to your site and see if they show up

**Comment by Brooniee** [comment]
@LaocheXe @CaMer0n yup after downloading latest git files and merging, the subject box is back. thanks!

**Comment by CaMer0n** [comment]
@Brooniee :+1:
