### ISSUE TITLE
[Admin] New 1.x upgrade to 2.0 every few hours

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1392]
This pops up every few hours, I go and carry out the upgrade but it always re-appears

![screenshot](https://cloud.githubusercontent.com/assets/11775356/13380627/82ab2c0a-de3f-11e5-9be8-9060668c9d41.PNG)

**Comment by LaocheXe** [comment]
That is because of the site has old preferences saved into the database I believe - don't quote me on this.

**Comment by CaMer0n** [comment]
@Brooniee Thank you for sharing. Could you please enable debug and visit that upgrade page again?

**Comment by Brooniee** [comment]
@CaMer0n thanks for quick response, currently can't enable developer mode due to:
https://github.com/e107inc/e107/issues/1393
:(

**Comment by CaMer0n** [comment]
@Brooniee This is an upgraded site, correct? What third-party plugins are you using?

**Comment by Brooniee** [comment]
@CaMer0n yeah a recent git clone too, but was happening on upgrade to 2.0

Plugins installed are:
Banners
Downloads
Feature Box
Forum
Gallery
Private Messenger
Poll
RSS
TinyMce4
User

**Comment by CaMer0n** [comment]
@Brooniee Thank you!

**Comment by Moc** [comment]
@Brooniee Now that #1393 is resolved, do you still get this upgrade message frequently? If yes, please enable debug mode when you get the message.

**Comment by CaMer0n** [comment]
This is usually caused by an older menu saving prefs in a serialized format.

**Comment by Moc** [comment]
@Brooniee Is this issue still happening using the latest files from Github?

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by Moc** [comment]
Closing due to lack of feedback. Please feel free to re-open.
