### ISSUE TITLE
[Admin] Saving preferences results in white screen after upgrading 1.x to 2.0

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1393]
Source code of page is blank, nothing is displayed in error.log of apache2

**Comment by LaocheXe** [comment]
Do you remember what changes you made that made this happen?

**Comment by Brooniee** [comment]
@LaocheXe happens every time after upgrade from 1.x to 2.0, even if i change no values.

**Comment by LaocheXe** [comment]
do you have the bootstrap 3 theme in your e107_themes folder?

**Comment by Brooniee** [comment]
@LaocheXe yes.

**Comment by LaocheXe** [comment]
@Brooniee would you like me to help you with this? Send me an e-mail to forbiddenchaos@gmail.com

**Comment by Brooniee** [comment]
@LaocheXe any help is welcome, thanks :)

though could i ask we go through steps here on github? might help if any other e107 users have issues when searching

**Comment by LaocheXe** [comment]
@Brooniee - very well, can I have a link to your website?

**Comment by Brooniee** [comment]
@LaocheXe http://www.crazy-fools.co.uk :)

**Comment by LaocheXe** [comment]
Well Notice that I can't create an account - you got any extended user fields enabled?

**Comment by Brooniee** [comment]
@LaocheXe another new issue :(

i have a few enabled yeah, but aren't be required at sign up.

**Comment by LaocheXe** [comment]
Which ones? I believe it was Birthday or another one that did this

**Comment by Brooniee** [comment]
On the page:

country 	Country.
x 	Favourite Minecraft Thing?
y 	IGN:
z 	Alternative IGN
birthday 	Birthday
location 	Location
timezone 	Timezone

**Comment by LaocheXe** [comment]
try disabling Birthday for me, let me know and I will try to sign up again

**Comment by Brooniee** [comment]
set: Applicable to No One for birthday

**Comment by LaocheXe** [comment]
I made an account, can you delete it?

**Comment by LaocheXe** [comment]
Also would you like help with your theme? Can I have your theme files?

**Comment by Brooniee** [comment]
@LaocheXe ah yeah, i see your account, now deleted.

sure, the theme needs some correcting too after upgrade but want to get the core issues fixed first :)

**Comment by LaocheXe** [comment]
Can you do me a favor - go into your e107_config.php and add this
`define('e_DEBUG', true);`

**Comment by Brooniee** [comment]
@LaocheXe done.

**Comment by Brooniee** [comment]
@LaocheXe referencing to original issue (saving preferences), debug that comes up is:

Bad Request: e107::filter_request : 3170

@CaMer0n may be of interest?

**Comment by CaMer0n** [comment]
@Brooniee,  Please check all your preference values for one of these:
```
document.location
document.write
document.cookie
```

**Comment by Brooniee** [comment]
@CaMer0n where do i find these? sorry.

**Comment by CaMer0n** [comment]
Database -> Preference Editor should list everything.

**Comment by Brooniee** [comment]
@CaMer0n yup, site disclaimer, google analytics code.

removed that and it's fixed it

thanks much!

**Comment by CaMer0n** [comment]
@Brooniee :+1:  You can use the google analytics plugin instead, if required.
