### ISSUE TITLE
Feature Request: Social Plguin Return_URL

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1396]
I've notice a few sites such as Google, and Twitter request for a callback_url a.k.a return url - without them then people cannot login to the site.

Request - when clicking on the enable button on social -> admin panel (under the key and salt) have the bottom display what the return url should be.

**Comment by nesjett** [comment]
If Im right you dont have to configure it on your site but on the twitter apps management.

Its here:
![screenshot_15](https://cloud.githubusercontent.com/assets/7051231/13390550/64396436-decf-11e5-9c99-c37c6b701ce0.png)



Grts,
- Nes

**Comment by CaMer0n** [comment]
@LaocheXe Normally http://_yourdomain.com_/index.php should work.
