### ISSUE TITLE
Last Post by username missing

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1397]
Hello again,

I cloned latest git, and overwrote files.

Username is missing from last forum posts. see screenshot

![screenshot](https://cloud.githubusercontent.com/assets/11775356/13382740/d14c0d3c-de73-11e5-89d2-80cc2f4a080b.PNG)

**Comment by CaMer0n** [comment]
@Brooniee Could you please provide the exact name of the menu? (as displayed in Admin->Menu Manager)

**Comment by Brooniee** [comment]
@CaMer0n Apologies if not clear, this is within the forum itself and viewing the topics

See http://crazy-fools.co.uk/e107_plugins/forum/forum_viewforum.php?id=2

Thanks :)

**Comment by CaMer0n** [comment]
@Brooniee I see. Thank you. Are you using a custom forum template?

**Comment by Brooniee** [comment]
@CaMer0n Just the one copied from a folder in e1072.0 'templates', nothing custom I believe?

**Comment by CaMer0n** [comment]
@Brooniee I might need to troubleshoot it with you in real-time.  if you have time please go here: https://gitter.im/e107inc/e107

**Comment by Moc** [comment]
Closing due to lack of feedback. Join us in the Gitter chatroom to have this issue debugged if you are still experiencing this issue.
