### ISSUE TITLE
[Documentation] small mistake on "typeahead"

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1399]
There is another small mistake on the docs, it says "typehead" in order of "typeahead"

http://e107.org/developer-manual/classes-and-methods#forms

![screenshot_16](https://cloud.githubusercontent.com/assets/7051231/13410783/eced526e-df39-11e5-89ca-a50f937e2cf8.png)

**Comment by Moc** [comment]
Thanks for reporting. Fixed!
