### ISSUE TITLE
Question about login, cookies/sessions and possible issue.

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1405]
Hi, well, this issue happened in v1.0.4, but I´m concerned about if that could happen on v2, because its an important security issue.

The problem is that 2 users logged in to the same account, but one of them was trying to login into his own account, that means that one user logged in on other user account at the same time as the other.

This happened 2 times in different days, on computers connected to the same network.

My question is if this could happen due to a possible issue with sessions/cookies or could it be a problem with the network in that place.

Seems that both users logged in at the same time, I was as surprised as probably you are now while reading this.

Grts,
- Nes

**Comment by Moc** [comment]
It shouldn't be possible for it to happen on v2. If you do however see this happening, please let us know and I'll re-open.
