### ISSUE TITLE
[Question] Proper way to add comments in a page

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1406]
Well, since v1.0.4 my comments in plugins got broken, so after some hours figuring out how to proper display comments, I came up with this conclusion:

```

$test = $Comments->compose_comment("myPlug", "comment", $match_id, null, "test", false, true);

foreach (array_reverse($test, false) as &$valor) {
    $text .= $valor;
}
```

But I´m pretty sure that there is a better way, am I right?

PD: news and page are very complex to understand.

PD2: Also, this solutions seems not to work as espected, I cant add a new comment nor delete or vote the existing ones.

Thanks,
- Nes

**Comment by Jimmi08** [comment]
If this  helps...
 Before:
```
require_once(e_HANDLER."comment_class.php");
$cobj = new comment;
```
Now:
```$cobj = e107::getComment();```

Otherwise no changes, examples from code:
```$cobj->enter_comment($_POST['author_name'], $_POST['comment'], "links_page", $qs[1], $pid, $_POST['subject']);```
```$cobj->compose_comment("links_page", "comment", $qs[1], $width, $subject, $showrate=FALSE);```
I agree, the page and news are too comlex to understand. I have no array_reverse() in my code and comments work.

**Comment by nesjett** [comment]
Thanks for your help, Ill take a detailed look to the links page because Ive missed it had comments enabled.

Anyway, your solution is not working for me, I still cant post comments, even if I call enter_comment directly, seems that the comment is not beign created.

**Comment by Jimmi08** [comment]
Do you have e_comment.php set?

**Comment by nesjett** [comment]
Yes but to be honest, it was made for v1 so I dont know if it will work now, but I dont have any  v2 e_comment example.

**Comment by Jimmi08** [comment]
Exactly. And I didn't find it either in documentation. And while there is new way with searching, searching in comments is going old way too. Probably waiting for changing in future. I will rewrite LP plugin if I find how, but for now it's enough and there important issues than this. If you find any problems with LP plugin and comments (or other), you can let me know.

**Comment by CaMer0n** [comment]
@nesjett Could you paste the old comment code you're plugin was using? (before any modifications for v2)

**Comment by nesjett** [comment]
I´ve not implemented the comment part of this plugin, so I cant reply to questions like "why you did this that way" hehe


And here is the function that was getting the comments and the comment form:

`
/**
* Add comments to a plugins
* <p>This method returns the HTML for a comment form. In addition, it will post comments to the e107v7
* comments database and get any existing comments for the current item.</p>
* @param   string   a unique ID for this plugin, maximum of 10 character
* @param   int      id of the item comments are allowed for
* @return  string   HTML for existing comments for an item and the comments form to allow new comments to be posted
*/
function ebGetComment($pluginid, $id) {
	global $pref, $e107cache, $tp;

	// Include the comment class. Normally, this file is included at a global level, so we need to make the variable
	// it decalares global so it is available inside the comment class
	require_once(e_HANDLER."comment_class.php");
	require(e_FILE."shortcode/batch/comment_shortcodes.php");
	$GLOBALS["comment_shortcodes"] = $comment_shortcodes;

	$pid = 0; // What is this w.r.t. comment table? Parent ID?

	// Define a comment object
	$cobj = new comment();

	// See if we need to post a comment to the database
	if (isset($_POST['commentsubmit'])) {
		$cobj->enter_comment($_POST['author_name'], $_POST['comment'], $pluginid, $id, $pid, $_POST['subject']);
		if ($pref['cachestatus']){
			$e107cache->clear("comment.$pluginid.{$sub_action}");
		}
	}

	// Specific e107 0.617 processing to render existing comments
	if (!isV07()) {
		$query = $pref['nested_comments'] ?
		"comment_item_id='$id' AND comment_type='$pluginid' AND comment_pid='0' ORDER BY comment_datestamp DESC" :
		"comment_item_id='$id' AND comment_type='$pluginid' ORDER BY comment_datestamp DESC";
		unset($text);
		$mysql = new db();
		if ($comment_total = $mysql->db_Select("comments", "*", $query)) {
			$width = 0;
			while ($row = $mysql->db_Fetch()) {
				// ** Need to sort out how to do nested comments here
				if ($pref['nested_comments']) {
					$text .= $cobj->render_comment($row, $pluginid, "comment", $id, $width, $subject, true);
				} else {
					$text .= $cobj->render_comment($row, $pluginid, "comment", $id, $width, $subject, true);
				}
			}
			if (ADMIN && getperms("B")) {
				$text .= "<div style='text-align:right'><a href='".e_ADMIN."modcomment.php?$pluginid.$id'>".LAN_314."</a></div>";
			}
		}
	}

	// Get comment form - e107 sends this to the output buffer so we must grab it and assign to our return string
	ob_start();
	if (isV07()) {
		// e107 0.7
		$cobj->compose_comment($pluginid, "comment", $id, $width, $subject, false);
	} else {
		// e107 0.617
		if (strlen($text) > 0) {
			$ns = new e107table();
			$ns->tablerender(LAN_5, $text);
		}
		$cobj->form_comment("comment", $pluginid, $id, $subject, $content_type);
	}
	$text = ob_get_contents();
	ob_end_clean();

	return $text;
}`

**Comment by CaMer0n** [comment]
@nesjett You mentioned "since v1.0.4 my comments in plugins got broken" - are you able to send me one of these plugins for testing?

**Comment by nesjett** [comment]
I found the problem, and its on this line of the function:

```PHP
require(e_FILE."shortcode/batch/comment_shortcodes.php");
```

Anyway, for further testings you can download the plugin here: https://github.com/qam4/ebattles
On default installations of this plugin you can check for comments on e_PLUGIN/ebattles/matchinfo.php

**Comment by Jimmi08** [comment]
I think that this is original version for 1.0.4
https://github.com/zigstum/ebattles

**Comment by nesjett** [comment]
It has not changed on the comments part, to be honest it has not changed almost nothink on the port from v1 to v2

**Comment by nesjett** [comment]
@CaMer0n sorry to disturb you with this again but I still need to know which lines are needed to include comments on a page.

Thank you.
- Nes

**Comment by CaMer0n** [comment]
Hopefully this will make it easier (see commit). This will render the form and the comments. There's nothing more to do. 

	 /*
	 * Returns a rendered commenting area. (html) v2.x
	 * This is the only method a plugin developer should require in order to include user comments.
	 * @param string $plugin - directory of the plugin that will own these comments.
	 * @param int $id - unique id for this page/item. Usually the primary ID of your plugin's database table.
	 * @param string $subject
	 * @param bool|false $rate true = will rendered rating buttons, false will not.
	 * @return null|string
	 */
	render($plugin, $id, $subject, $rate=false)

Example: 

    $text = e107::getComment()->render('myplugin', 3, "My Subject", true);
    echo $text;

**Comment by nesjett** [comment]
@CaMer0n thank you for your help, now its easier to understand.

In my case doesnt work yet, it displays coments and comment form, but seems that new comment system uses ajax to post comments and ratings, which is creating a conflict with the plugin page jquery, cause the plugin loads an old jquery library, Ill have to update it and retry. (Im talking about the ebattles plugin)

I think its all for now, If I find more problems related to this Ill post them.

Keeping the topic open because of the "documentation" mark.
- Nes
