### ISSUE TITLE
Enhancement: Admin>Pref>SiteIcon & Logo Media Picker - Allow Admin to choose any Img or Glyph.

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1407]
Hi All, 
We have lots of pre-loaded media files within the system, but Admin does not seem to be able to use many of these.
For Example: Admin > Prefs it would be useful to enable imagepicker any Image or Glyph in the Prefs for Site Icon & Logo. 
To do show the glyps, I tried  adding this option, '&glyphs=1' on line 377
$text .= $frm->imagepicker('sitebutton',$pref['sitebutton'],'','help='.PRFLAN_225**.'&glyphs=1'**);
It kinda works, sets the value, but does not close on save and does not display the selected glyph icon, but instead the path/filename. 
Thanks
Mike

**Comment by CaMer0n** [comment]
Point taken about the glyphs, but for the rest, setting any image to _common_image will make it available to the SiteIcon/Logo imagepicker.

**Comment by MikeyGMT** [comment]
Oh, cool, thank you!
