### ISSUE TITLE
Invalid list file error - how can this happen?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1409]
I checked my site first time today and got this error. "Invalid list file"  I found it's because this:
![image](https://cloud.githubusercontent.com/assets/5429548/13598602/0976530a-e51f-11e5-97b7-6252531ef14f.png)

after echo $filename , result was
![image](https://cloud.githubusercontent.com/assets/5429548/13598626/2dae6b18-e51f-11e5-9cf3-249106fff73c.png)
and after checking this path
![image](https://cloud.githubusercontent.com/assets/5429548/13598660/54f965d8-e51f-11e5-9af8-0c4b9d8870cb.png)

and file (it's empty)
![image](https://cloud.githubusercontent.com/assets/5429548/13598790/0ea04790-e520-11e5-8385-a6c58a187d6f.png)

There is nothing in log and my last activity at this site was:   Monday 07 March 2016 - 15:24:43 and everything was fine.

Site uses e107 github from 28.2., if this helps.

**Comment by CaMer0n** [comment]
Looks like something has emptied banlist.php. Try adding the `<?php `back to  it.

**Comment by Jimmi08** [comment]
Thanks. Done.
