### ISSUE TITLE
meta tags stopped work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1411]
I noticed this with my plugin, but it is happened with news too.  (on older version it works, on newest not)
I use e107::meta() function, but now it has be used before
` require_once (HEADERF);` 
otherwise meta tags are not loaded. 

It should work this way?  I like it :)

**Comment by lonalore** [comment]
And... by the way, I think we need to improve "meta-tag" section of e107. The best would be to provide support for commonly used meta tags, including the page title, canonical URL, description, etc, and for Facebook's Open Graph, Twitter Cards and Dublin Core.

The best would be to provide the ability to set default values for each meta tag under the "Meta Tags" section:
![kepernyokep - 2016-03-10 - 10 56 52](https://cloud.githubusercontent.com/assets/6043821/13665896/f617dcca-e6ae-11e5-959e-2adcb24e9fac.png)

Furthermore, to provide a way to override default values by each page/news/etc.. items. For example, on the "Create Page/Menu" form there would be a "Meta tags" tab to set unique values for the current page item. If not set, the default meta values would be used.
![kepernyokep - 2016-03-10 - 10 48 14](https://cloud.githubusercontent.com/assets/6043821/13665996/8071b49a-e6af-11e5-84d2-b9184e563d74.png)

I collected a large number of commonly used meta tags here:
https://gist.github.com/lonalore/fdffcfdc4148bf8cb829

**Comment by Jimmi08** [comment]
So news and other pages need to rewrite because they use HEADERF before e107::meta(), this was changed.

By the way, awesome list. Thanks. I needed it 2 days ago :)  From my experience (just used FB debugger and need only sharing plugin pages)
- FB tags needs right order of meta tags 
- you can't use description with  type article
- you should use type website just for homepage
- you can use your own types, so the list is neverending story.

I generate content of meta tags from other fields / not edited by user, there should still be this posibility. e107::meta() works fine, just to have possibility to add any of them in admin and set order and default value.

**Comment by Moc** [comment]
So news and others still require changing the order of e107::meta() and loading the header?

**Comment by Jimmi08** [comment]
No, I think that this was somehow solved, I can see meta description in news from latest github. In plugin you need at first use e107::meta() and then HEADERF

**Comment by Moc** [comment]
Alright
