### ISSUE TITLE
Feature Request: Forum Link Icon/Image

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1412]
Give admin the option to give forum thread parents options to add an image/icon/font into the name - like Links you can add a image/icon at the front of the link name.

Also give an option to select if the image can be at the front or behind the text.

**Comment by chory** [comment]
Like it?
http://i559.photobucket.com/albums/ss37/ch0ry/Captura_zpsz4xjlfgx.jpg

**Comment by LaocheXe** [comment]
^^^^^^ Add support for it then?

**Comment by chory** [comment]
Sorry I dont know how works github, and I do not want to spoil everything. So here I leave something I've done, I hope you serve.

**Database structure changes:  Add a field that content image url**
ALTER TABLE `e107_forum`	ADD COLUMN `forum_img` VARCHAR(250) NULL DEFAULT NULL;

**e107_plugins/forum/forum.php: Add new line to get image from DB:**
$fVars->FORUMNAME = "<a href='".$url."'>{$f['forum_name']}</a>";
// New line to get the image
$fVars->FORUMIMG = ( $f['forum_img'] != NULL ) ? "<img src='{$f['forum_img']}' />" :  "";
$fVars->FORUMDESCRIPTION = $f['forum_description'].($restricted_string ? "<br /><span class='smalltext'><i>$restricted_string</i></span>" : "");

**e107_plugins/forum/forum_admin.php: Add new line to enter URL:**
'forum_img'        =>   array ( 'title' => "Imagen", 'type' => 'text', 'inline'=>true, 'noedit'=>false, 'data' => 'str', 'width' => 'auto', 'help' => 'Leave blank to auto-generate it from the title above.', 'readParms' => '', 'writeParms' => 'size=xxlarge', 'class' => 'left', 'thclass' => 'left',  ),

Now add the shortcode {FORUMIMG}, in template file to show it
**e107_plugins/forum/templates/forum_template.php: Now add the shortcode {FORUMIMG}, in template file to show it**
$FORUM_TEMPLATE['main']['forum']			= 	"<tr>
											<td>{NEWFLAG}</td>
											<td>_{FORUMIMG}_ {FORUMNAME}<br /><small>{FORUMDESCRIPTION}</small>{FORUMSUBFORUMS}</td>
											<td class='hidden-xs text-center'>{REPLIESX}</td>
											<td class='text-center'>{THREADSX}</td>
											<td class='hidden-xs text-center'><small>{LASTPOSTUSER} {LASTPOSTDATE}</small></td>
											</tr>";

**Comment by CaMer0n** [comment]
@chory Thank you. Could you please post again, but wrap your code in ` ` ? (or better yet, paste it to a gist)

**Comment by chory** [comment]
Sorry I dont know how works github, and I do not want to spoil everything. So here I leave something I've done, I hope you serve.

**Database structure changes:  Add a field that content image url**
```SQL
ALTER TABLE `e107_forum`	ADD COLUMN `forum_img` VARCHAR(250) NULL DEFAULT NULL;
```
**e107_plugins/forum/forum.php line 408: Add new line to get image from DB:**
```php
$fVars->FORUMIMG = ( $f['forum_img'] != NULL ) ? "<img src='{$f['forum_img']}' />" :  "";
```
**e107_plugins/forum/forum_admin.php 148: Add new line to enter URL:**
```php
'forum_img'        =>   array ( 'title' => "Imagen", 'type' => 'text', 'inline'=>true, 'noedit'=>false, 'data' => 'str', 'width' => 'auto', 'help' => 'Leave blank to auto-generate it from the title above.', 'readParms' => '', 'writeParms' => 'size=xxlarge', 'class' => 'left', 'thclass' => 'left',  ),
```
Now add the shortcode {FORUMIMG}, in template file to show it
**e107_plugins/forum/templates/forum_template.php 110: Now add the shortcode {FORUMIMG}, in template file to show it**
```php
$FORUM_TEMPLATE['main']['forum']			= 	"<tr>
											<td>{NEWFLAG}</td>
											<td>{FORUMIMG} {FORUMNAME}<br /><small>{FORUMDESCRIPTION}</small>{FORUMSUBFORUMS}</td>
											<td class='hidden-xs text-center'>{REPLIESX}</td>
											<td class='text-center'>{THREADSX}</td>
											<td class='hidden-xs text-center'><small>{LASTPOSTUSER} {LASTPOSTDATE}</small></td>
											</tr>";
```

**Comment by CaMer0n** [comment]
@chory Thank you. How big is the image you usually add ?  32px ?

**Comment by chory** [comment]
Yes

**Comment by chory** [comment]
New Style:
Now we can use any image, with any size, but the width of the same is greater than specified in preferences, the text is hidden, and this is shown as image title.
![](http://i559.photobucket.com/albums/ss37/ch0ry/NuevoEstilo_zpshlr4sjgn.jpg)

**e107_plugins/forum/forum_admin.php 191**
```php
'maxwidth'	            => array('title'=> 'Ancho máximo', 'type'=>'text', 'data' => 'str','help'=>'Ancho máximo para mostrar el texto'),
```
***e107_plugins/forum/forum.php 408***
```php
$imagesize=getimagesize($f['forum_img']);
$FORUMIMG= ( $f['forum_img'] != NULL ) ? "<img src='{$f['forum_img']}' title='{$f['forum_name']}' />" :  "";
$fVars->FORUMIMG = ( $f['forum_img'] != NULL ) ? "<img src='{$f['forum_img']}' />" :  "";	
$fVars->FORUMIMGTXT = ( $imagesize['0'] > $forum->prefs->get('maxwidth') ) ? "<a href='".$url."'>".$FORUMIMG."</a>" : "<a href='".$url."'>".$FORUMIMG." {$f['forum_name']}</a>";
```
***.../forum_template.php 110***
```php
$FORUM_TEMPLATE['main']['forum']			= 	"<tr>
											<td>{NEWFLAG}</td>
											<td>{FORUMIMGTXT}<br /><small>{FORUMDESCRIPTION}</small>{FORUMSUBFORUMS}</td>
											<td class='hidden-xs text-center'>{REPLIESX}</td>
											<td class='text-center'>{THREADSX}</td>
											<td class='hidden-xs text-center'><small>{LASTPOSTUSER} {LASTPOSTDATE}</small></td>
											</tr>";
```

**Comment by CaMer0n** [comment]
Thanks. It is better to let the template determine the size using {SETIMAGE: w=100} for example and the toImage() method to render the image. .

**Comment by chory** [comment]
Ok

**Comment by chory** [comment]
I have tried to do as you say, but I do not understand properly how.
With {setImage :, we indicate what is the width that is to have the picture when displayed, is this correct?
But what I indicated is, from what image width has to hide the text.
Actually, the syntax e107, it's too big.

**Comment by CaMer0n** [comment]
I would suggest to put the image in it's own table column. (html)

**Comment by chory** [comment]
Yes that I know, that would be using only the short code {FORUMIMG}, adding a column in template.
My intention is to show only image {FORUMIMG}, show image and text, or display only the image, if the image exceeds a certain width {FORUMIMGTXT}.

**Comment by chory** [comment]
Well, some time later, and in a moment of inspiration (this does not create precedent), I have managed to do what I wanted, if, and with shortcodes.
I have created two new shortcodes, PARENTIMG and FORUMIMG, that support the parameters w = width, h = height, fmt = format, the latter can be specified if the text (txt) or image (img) is desired in any Order for example
Fmt = txt would only display text
Fmt = img would only display the image
Fmt = imgtxt would display the image and to its right the text
Fmt = img <=> txt would display the image and to your right the text separated by <=>

If you think it works well, I think you could modify the shortcodes, PARENTNAME and FORUMNAME, to accept those parameters and return the corresponding data, thus eliminating the shortcodes PARENTIMG and FORUMIMG.

Now to see if I remember how it made me to send you the code  :wink:

**Comment by rica-carv** [comment]
@chory Have you tried this issue with latest github files?
Maybe this issue is already solved.
Please do try latest giithub files.
Thanks.
