### ISSUE TITLE
Bug: Current Version - YouTube Video No Preview in TinyMce editor

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1414]
Latest update from GitHub no longer displays the selected YouTube video icon in the text field.

I use a YouTube video in my welcome message - there used to be an icon displayed but is no longer displaying.

**Comment by CaMer0n** [comment]
@LaocheXe Could you please elaborate. Which text field is that? Are you referring to the TinyMce interface?

**Comment by LaocheXe** [comment]
Yes TinyMce - The text area for the welcome message

**Comment by CaMer0n** [comment]
![welcome_admin](https://cloud.githubusercontent.com/assets/2825679/13711763/260d6c58-e775-11e5-8e79-afe86c730127.png)

I can see the insert media-manager video..  can you?

**Comment by LaocheXe** [comment]
Oh well I feel stupid, I'm not talking about the button - I'm talking about when you select a video - the white area where you put the text in - it would show an icon from that YouTube video as a place holder - right now I can't get it to display the icon any more - on the front end it shows the YouTube video.

**Comment by Jimmi08** [comment]
@LaocheXe  Do you mean this? Latest github.
![image](https://cloud.githubusercontent.com/assets/5429548/13714854/84286728-e7d1-11e5-9830-9cf8e51f3976.png)

**Comment by CaMer0n** [comment]
I see it! The YouTube preview image inside the TinyMce editor window is not displaying after selecting it via Media-Manager.  - due to the TinyMce version update. Will look into it.

**Comment by LaocheXe** [comment]
@Jimmi08 yes that's the one, and thanks @CaMer0n

**Comment by CaMer0n** [comment]
I have submitted a request with TInyMce to see what is going on: https://github.com/tinymce/tinymce/issues/2777
