### ISSUE TITLE
wrong day in datepicker() with locale day

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1417]
In English language value is correct. 
![image](https://cloud.githubusercontent.com/assets/5429548/13715794/67aea516-e7d7-11e5-9eac-cb756f0065e9.png)

In Slovak language, date in page is correct but in datepicker() is impossible day :)
![image](https://cloud.githubusercontent.com/assets/5429548/13715783/507e7ba0-e7d7-11e5-869b-6640a1bbdcb7.png)

**Comment by chory** [comment]
In Spanish fail too

**Comment by Jimmi08** [comment]
Solved. I suppose that by using just English names, but it's enough.

![image](https://cloud.githubusercontent.com/assets/5429548/14573230/03e02972-0354-11e6-950d-888599df874a.png)
