### ISSUE TITLE
installation - problem with htaccess

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1421]
This problem is server related, I just write this in case somebody else can the same problem.

After installation I got this error (internal error 500)
![image](https://cloud.githubusercontent.com/assets/5429548/13729543/98d1dcd8-e937-11e5-95ae-37c79855bcdf.png)

These settings are forbiden on my hosting:
![image](https://cloud.githubusercontent.com/assets/5429548/13729552/b6c7333c-e937-11e5-9f6c-fdf148106931.png)
![image](https://cloud.githubusercontent.com/assets/5429548/13729553/c4e02140-e937-11e5-8143-e46a02730c39.png)

(Options can use only Indexes, nothing more)

I needed to comment two lines in generated e107 .htaccess
![image](https://cloud.githubusercontent.com/assets/5429548/13729563/0069a9b6-e938-11e5-827e-0d1610b1017a.png)
![image](https://cloud.githubusercontent.com/assets/5429548/13729565/0db0c29e-e938-11e5-95d7-830f3878ba7f.png)

And then everything worked as should it have. I know nothing about this.

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please share details of the server configuration?

**Comment by Jimmi08** [comment]
Done, Cameron have access to phpinfo(); @Moc you could change label

**Comment by Jimmi08** [comment]
Closed by mistake, sorry

**Comment by Jimmi08** [comment]
What testing is required? I still need to remove those lines from htaccess on this hosting. On old one it works.

**Comment by CaMer0n** [comment]
@Jimmi08 Would you like to comment them out of e107.htaccess and send a pull-request?

**Comment by Jimmi08** [comment]
Yes, of course, but don't they have some purpose on other hostings? I don't want to complicate things for others. Thanks

**Comment by CaMer0n** [comment]
e107 doesn't use them, it's just for security.

**Comment by Jimmi08** [comment]
This is solved. Thanks
