### ISSUE TITLE
Cannot display all comments

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1422]
When I look at an user details
/user.php?id.42 for example
It shows at the end :
Forum posts 1387 ( 14.09% )
Comments posted 3 ( 2.88% )

With a link on the number to display these comments
But when I follow the link (/userposts.php?0.comments.42)
only 1 result is shown... (seems to be the more recent)

Maybe related to bug #1373

**Comment by CaMer0n** [comment]
@pierre0042 Could you please share your PHP and MySQL version? Thanks.

**Comment by pierre0042** [comment]
PHP Version 5.4.45

MySQL 5.5.46

**Comment by pierre0042** [comment]
The bug seems fixed with the last code version

**Comment by CaMer0n** [comment]
Thanks! Closing, but please re-open if it should happen again.
