### ISSUE TITLE
User Profile Template needs an upgrade. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#1423]
I have made a start on this (see commented out section), but it needs the talent of a more experienced theme artists. @mcpeace-maw would you consider taking a look at this?

**Comment by mcpeace-maw** [comment]
OK, please check the pull request.

**Comment by CaMer0n** [comment]
Thank you @mcpeace-maw . I fixed the LANs and here's how it looks with Bootstrap3 for me. 
![userprofile_1](https://cloud.githubusercontent.com/assets/2825679/13753782/b533d7ba-e9d1-11e5-9dc8-c1de36956e7c.png)

I believe we need tables for the data, or at least the appearance of tables (in terms of alignment). 
Perhaps the data should be organized into separate tabs?. I'm interested to get everyone's feedback on this. @Moc, @tgtje, @MikeyGMT, @Jimmi08, @LaocheXe, @lonalore. Of course, it has to look good with extended user fields also.

**Comment by LaocheXe** [comment]
Well Looking at the screenshot - maybe move the 'Click here to update your info' button down and align it with 'previous member' and 'next member'.

I have Private Message enabled on my website and it looks out of place

![capture](https://cloud.githubusercontent.com/assets/5818022/13755414/24e8b7ee-e9e9-11e5-939a-77c009897210.PNG)

I would adjust the private message - maybe even remove the little image button for private message and just make 'Send Private Message' a link or pop-up window to send a message, etc...

Also the "Member $id" should be moved down at the bottom below the 'previous member' button - it looks okay on the screenshot you took but on my you can't see it. You could also maybe hide it.

Also the image background - you got blue/green and mine is white/grey - maybe allow the users to change that either by selecting a set of pre-images or even allowing them to upload their own (but that might be off topic in this).

On another note, user extended fields - using tabs as the categories would be best but another thing to take into account and also maybe off topic but to allow the admin to arrange the user fields - such as allow admins to add to the general user profile section (Under Forum Post - or even add a table under Forum Post, etc).

**Comment by CaMer0n** [comment]
> Also the image background - you got blue/green and mine is white/grey - maybe allow the users to change that either by selecting a set of pre-images or even allowing them to upload their own (but that might be off topic in this).

Yes, this is the "User Photo" that is displaying in my screenshot.

**Comment by mcpeace-maw** [comment]
Please don't forget must be responsive. "Update your info" button must be visible, not a good idea to put it with other things in same row. The icon for send private message must be changed. Also used same font stars for user rating like in forum.

**Comment by LaocheXe** [comment]
Just a heads up - I don't know if it is related or not but when going to user.php - to see the Member's list - the avatars are out of place.

![capture](https://cloud.githubusercontent.com/assets/5818022/13757416/4a496ee4-e9f2-11e5-8b2e-7072f795896a.PNG)

I don't know if it was the resent changes that where done or if it is a social login issue.

**Comment by mcpeace-maw** [comment]
Yes it is for these changes, @CaMer0n please add inside user_template in inline css:
.panel-profile #user-profile-avatar { max-width: 150px; margin-top: -90px; ... }
This will fix the issue.

**Comment by mcpeace-maw** [comment]
I added visible borders, padding, aligned labels and data. Solved also the issue reported by @LaocheXe. BTW the id #user-profile-avatar must be removed from user-image shortcode (the image have user-avatar class) - in members page the id is not unique, every avatar image have it and page validation fail. Also lan_user file have many duplicates.

**Comment by CaMer0n** [comment]
@mcpeace-maw Thanks for the changes! I cleaned up the code a bit so it's clear what is v2.x and what is v1.x  . Css moved to e107.css

**Comment by lonalore** [comment]
Well done, it looks great. :+1: 
I think we should allow the users to reposition the background (cover) photo. Or provide a widget for selection based cropping an image after upload.

**Comment by Moc** [comment]
Looks a lot more up to date :) I don't have any specific feedback now on the user profile. 

Seeing how the PM icon looks outdated on the user profile, I checked the plugin code and it is need of a substantial rewrite to make use of all the new possibilities (e.g. userpicker). Some inspirational styling: https://almsaeedstudio.com/themes/AdminLTE/pages/mailbox/mailbox.html

**Comment by CaMer0n** [comment]
Closing this. We can start a new issue for PM if needed.
