### ISSUE TITLE
membersonly.php burps out some code/variables at the bottom which shows log path. Security issue?

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1426]
![image](https://cloud.githubusercontent.com/assets/15772899/13753962/1a4bd4e6-ea0d-11e5-992a-6768f6c26b90.png)

**Comment by CaMer0n** [comment]
@martyshep Thank you. Is this the bootstrap3 without modification? Does it display every time, or just sometimes?

**Comment by martyshep** [comment]
Yes, Bootstrap3 with minor cosmetic text modification. Yes it's done it since rolling out v2 as far as I know. I think the log plugin is standard/not altered in any way.

**Comment by CaMer0n** [comment]
@martyshep Would you have time to troubleshoot it? If so, please just me here: https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
Closing. Due to bad HTML markup in custom membersonly template.
