### ISSUE TITLE
Issue: Social Plugin - Twitter

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1428]
AS you may know I have a few social login options on my website (defiantz.org) and all seem to be working but Twitter, it could be that I screwed something up in the Twitter API registration but I am getting this error on my site when trying to login with Twitter

Error
[5]Authentication failed! Twitter returned an error. 401 Unauthorized.

Now I google and get this - [#335](https://github.com/hybridauth/hybridauth/issues/335)
It says it could be the web host server time is off - check the time and all is good so idk if it is script related or not.

**Comment by CaMer0n** [comment]
@LaocheXe I need to get Twitter working on a project too. Will try it and let you know.

**Comment by CaMer0n** [comment]
Failing for me too.

**Comment by LaocheXe** [comment]
@CaMer0n I also notice someone said something about a space in the config - as you said e107 doesn't use the config that the Hybrth uses.

**Comment by LaocheXe** [comment]
@CaMer0n Got it to work!!!! and great news - nothing is wrong with the code - it is a setting on Twitter's side that is causing the error.

Having Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url) checked will block the login - having it uncheck will allow people to login to site.

![capture](https://cloud.githubusercontent.com/assets/5818022/13791699/5e9ca558-eabc-11e5-8681-fa698e7da973.PNG)

**Comment by CaMer0n** [comment]
@LaocheXe Cool! I'm gonna try that! :+1:

**Comment by CaMer0n** [comment]
@LaocheXe It didn't fix it for me 

       [5]Authentication failed! Twitter returned an error. 401 Unauthorized.

**Comment by LaocheXe** [comment]
@CaMer0n Do you have your preferences set up? This is what I have:

![capture1](https://cloud.githubusercontent.com/assets/5818022/13800048/11471428-eaf3-11e5-9ff6-abfc420fcb38.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5818022/13800049/138926e0-eaf3-11e5-8744-25f4ae894cc1.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5818022/13800050/1557a2ee-eaf3-11e5-9527-2bf69f63c0c5.PNG)


If you have just Read & Wright access, change it and reapply your key to get a new key and salt

**Comment by CaMer0n** [comment]
Thanks @LaocheXe that helped! I did get a failure because there was no email. Do you have yours set to get email somehow? Or did you enable this requirement in e107?

**Comment by CaMer0n** [comment]
Found my answer: http://stackoverflow.com/questions/14080011/how-to-get-the-twitter-users-email-using-hybridauth

**Comment by CaMer0n** [comment]
This works like a charm now! Thank you for your help @LaocheXe . Closing...

**Comment by CNSKnight** [comment]
I just got past the 401 by

- Unchecking the Enable Callback Locking
- Regenerate keys
