### ISSUE TITLE
PHP 5.5 and 5.6

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1430]
Since my provider upgraded PHP tu v5.6, doesn't run e107, not v1.04 and not v2.0
Any suggestions???

**Comment by LaocheXe** [comment]
Is it a blank page? If so add this to your e107_config.php

`define('e_DEBUG', true);`

After that check the page again and see if any error's are displayed.

**Comment by TrueHatori** [comment]
No, no blank page and no error messages. It lacks content. Especially in the admin area. There is no safe buttons are sometimes displayed, sometimes it lacks user, it lacks sometimes News. But always different, it is always missing something different.
It is the same in PHP Version 5.5.32-1~he.0 and PHP Version 5.6.18-1~he.0.

And why can not import into v2.0 content from v1.0.4? The Update-Version does not work.

**Comment by CaMer0n** [comment]
@TrueHatori try adding this to e107_config.php : 

    define('e_PDO', true);

**Comment by TrueHatori** [comment]
I uploaded now v1.0.7, and write the two lines in e107_config.php
But the page loads not finished. It lacks content and lacks the entire right side, I can not login.
Where can I find a current version 1.0.4 -> 2.0? I have a lot of content, and I want to keep happy.
You can see it here: http://www.ninja4ever.de

**Comment by CaMer0n** [comment]
It could be an incompatible plugin causing an error which halts the rest of the script. Do you have a file called error_log in your root directory?

**Comment by TrueHatori** [comment]
No file called error_log.
And now is there the v1.0.4. This version was very good with PHP 5.3, but now its wrong, since the day of PHP 5.6. I try it also with PHP 5.5, its the same.
When I try the v2.0, I try it without 3rd Party Plugins, only with the plugins, which are included in the download of v2.0.

**Comment by CaMer0n** [comment]
@TrueHatori Would you like to troubleshoot in real-time? If so, you may join me here: https://gitter.im/e107inc/e107

**Comment by TrueHatori** [comment]
I found in the Error-Log from my Provider this:

[Wed Mar 16 15:19:02 2016] [error] [client 51.255.65.71] PHP Fatal error:  require_once(): Failed opening required '../../class2.php' (include_path='.:/usr/share/php5.6') in /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_plugins/agenda/agenda.php on line 18
[Wed Mar 16 15:21:02 2016] [error] [client 51.255.65.63] PHP Fatal error:  require_once(): Failed opening required '../../class2.php' (include_path='.:/usr/share/php5.6') in /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_plugins/agenda/agenda.php on line 18
[Wed Mar 16 15:21:13 2016] [error] [client 164.132.161.44] PHP Fatal error:  require_once(): Failed opening required '../../class2.php' (include_path='.:/usr/share/php5.6') in /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_plugins/agenda/agenda.php on line 18

Have deinstalled Agenda and any other Plugins, now it is better, but still it does not really work.
For real-time is my english to bad :(

**Comment by CaMer0n** [comment]
@TrueHatori We are a step closer! Your english is fine. Can you share a screenshot with the parts that are not displaying correctly?

**Comment by TrueHatori** [comment]
All lists ends sooner or later before the ends truly, although still should more points come.
In the edit view not the whole text is displayed, so that a processing is impossible.
Can't upload screenshots, he said "something went really wrong, and we can't process that file".
What I can do is a Admin CaMer0n establish, than you can look. Say me please, where I can send the password.

**Comment by TrueHatori** [comment]
All lists ends sooner or later before the ends truly, although still should more points come.
In the edit view not the whole text is displayed, so that a processing is impossible.
Can't upload screenshots, he said "something went really wrong, and we can't process that file".
What I can do is a Admin CaMer0n establish, than you can look. Say me please, where I can send the password.

**Comment by TrueHatori** [comment]
Since this moment I become in admin area this:
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php
Warning: file_put_contents(./../e107_files/cache/releasecheck_German.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/releasecheck_German.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Die Operation ist nicht erlaubt, Line 67 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_plugins/easybackup/plugin.php
Warning: file_put_contents(./../e107_files/cache/nq_admin_updatecheck_nq_ab52254519776825c7ffa557a5041dc2.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/nq_admin_updatecheck_nq_ab52254519776825c7ffa557a5041dc2.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Die Operation ist nicht erlaubt, Line 67 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_plugins/easybackup/plugin.php

**Comment by CaMer0n** [comment]
@TrueHatori Please go here: https://gitter.im/e107inc/e107

**Comment by TrueHatori** [comment]
Now I copied a fresh v1.0.4, deinstalled ALL plugins, tried any themes, but it is ever the same - the page is never fully charged. And in admin area:
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php
Warning: file_put_contents(./../e107_files/cache/releasecheck_German.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/releasecheck_German.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: file_put_contents(./../e107_files/cache/nq_admin_updatecheck_nq_09349c2b8071db22578813d4abe1bf2a.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/nq_admin_updatecheck_nq_09349c2b8071db22578813d4abe1bf2a.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php

Please, take a look, I say the password here: 19283746
Worse than it is, it can not come.

**Comment by rica-carv** [comment]
Can this be a cache issue?
Have you tried to clean the E107 cache?

**Comment by TrueHatori** [comment]
Yes, cache is deactivated, but I cleared regardless ...

**Comment by TrueHatori** [comment]
Ok, I'm just pretty sick (39 degree fever). I wait until Monday, then I have to think of something else. My students have to rely on the contents of the website. I hope CaMer0n has another idea. With the link, he wrote to me, I can not do anything, I have no idea what to do there. What I do not understand: How do these errors come from? I had everything completely erased and a clean v2.0 installed and had the same error, which now also shows the 1.0.4. Then I had an upgrade 1-> 2 installed on 1.0.4 because the settings in the e107_config.php were then allegedly not right, could not find the database.
I do not know how to continue.

**Comment by CaMer0n** [comment]
@TrueHatori https://gitter.im/e107inc/e107 is a chatroom so that I can troubleshoot the problem with you in real-time.

**Comment by TrueHatori** [comment]
I say it before - I can't chat with you. I need 30-45 mins for every answer here, must go to Google, search most of words. In chat I understand absolutly nothing.
Have you any other ideas, where the error can be? The v2 with a blank database also don't work :(

**Comment by TrueHatori** [comment]
I copy here again all error messages

**Admin area main:**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php
Warning: file_put_contents(./../e107_files/cache/releasecheck_German.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/releasecheck_German.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: file_put_contents(./../e107_files/cache/nq_admin_updatecheck_nq_09349c2b8071db22578813d4abe1bf2a.cache.php): failed to open stream: Keine Berechtigung, Line 117 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: chmod(): Datei oder Verzeichnis nicht gefunden, Line 118 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php
Warning: touch(): Unable to create file ./../e107_files/cache/nq_admin_updatecheck_nq_09349c2b8071db22578813d4abe1bf2a.cache.php because Keine Berechtigung, Line 119 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/cache_handler.php

**Settings Preferences**
Comes to Signup Page Options, then nothing more, no error messages

**Settings Cache**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php

**Settings Emoticons**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php

**Settings Frontpage**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php
Warning: Invalid argument supplied for foreach(), Line 43 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_admin/frontpage.php

**Settings Images**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php

**Settings Search**
Warning: Invalid argument supplied for foreach(), Line 271 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/notify_class.php
Warning: Creating default object from empty value, Line 23 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_handlers/shortcode_handler.php
Warning: Invalid argument supplied for foreach(), Line 49 of /is/htdocs/wp10477139_MJAUB0YEIY/www/e107_admin/search.php

And so it is in all admin area pages. Please, take a look in this. User CaMer0n, PW six messages on up.

**Comment by tgtje** [comment]
A repeated txtual message :  Unable to create file** ./../e107_files/cache  **
why should this happen on e107_files (leftover folder from v1 during overwrite for v2). 
Did upgrade not complete ? The folder should remain in place by upgrade, and config php should have the path to it...

**Comment by CaMer0n** [comment]
@TrueHatori If you can backup your original site (files and database), I would be happy to perform the v2 upgrade on your website for you. To do this, you would need you to send me your FTP, e107 and cPanel login information via the chatroom (in a private window)

**Comment by tgtje** [comment]
Remark/question due to some test results.. : using gzip compression ? what happens if site does not use it...

**Comment by TrueHatori** [comment]
Many, many thanks to CaMer0n, the problem is solved. He has invested a lot of work, great job.
