### ISSUE TITLE
Various permissions Error

### ISSUE THREAD

**Issue by Batatafrita** [e107inc/e107#1431]
After installing the system , I can not add users and change site links !

The error appears is: Unauthorized access!

**Comment by CaMer0n** [comment]
@Batatafrita I think we'll need to troubleshoot that in real-time. Please join me here, when you have time: https://gitter.im/e107inc/e107

**Comment by Batatafrita** [comment]
If i install the 2_0 Version the system the system works correctly but if I install the version 2_1 can not add users , post news and other features.

An html appears with the message:
Unauthorized access !

The site is: www.fpca.esp.br
use login: fpca and passwd fpca444 for your avaliation !

**Comment by Batatafrita** [comment]
I started a new installation with the latest github

After installation when trying to create a category appears the error of lack of authorization .

attachment error logs
![erro1](https://cloud.githubusercontent.com/assets/4342791/13993879/f63cf9f4-f100-11e5-8c3d-23909b1054d9.png)
![erro2](https://cloud.githubusercontent.com/assets/4342791/13993882/f9bfb288-f100-11e5-9460-9f69639987fb.png)

**Comment by realG** [comment]
I'm seeing the same issue as well, after updating to latest (24th march) from git master.

When trying to register a new user, after filling in details on signup.php, I click on "Register" and get an "Unauthorized access!" message. Same error gets logged in the admin panel as what @Batatafrita posted above.

I've just grabbed a backup of the site/db and got it running on a local XAMPP instance on my desktop and it works fine here, so must be tied somehow to apache/php config or file permissions on my host I assume..

Any suggestions on where to start looking?

**Comment by Batatafrita** [comment]
realG

which the domain name that is giving problems?

**Comment by Batatafrita** [comment]
Hello guys
after installing a new version , when I click on the site 's name, it is called the install.php I had already removed.I do not know what the reason .

But to solve the problem , the file e107_handlers / session_handler.php changed on line 897 the option true to false and the problems will be solved .

But I am afraid that this leave the vulnerable site .
What do you think ?

**Comment by CaMer0n** [comment]
@Batatafrita Does adding this to e107_config.php solve it also?  (after you revert your change of line 897)

`define('e_SECURITY_LEVEL', 0);`

how about.. 

`define('e_SECURITY_LEVEL', 5); `

**Comment by CaMer0n** [comment]
Also, could you please take a screenshot of /e107_admin/phpinfo.php and share? Thanks.

**Comment by Moc** [comment]
The session handling has had a lot of work in the past months. If you are still experiencing this issue, please join us in the Gitter chatroom so we can debug the issue together on your installation.
