### ISSUE TITLE
Question: Bootstrap

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1432]
What happen to the other Bootstrap theme? I just notice that it is no longer in the theme's folder.

**Comment by CaMer0n** [comment]
You mean boostrap the boostrap 2 theme? Yeah, it was removed.

**Comment by LaocheXe** [comment]
Yeah, will it be added to the e107 site then later on? It was a pretty good stock theme if you ask me

**Comment by Moc** [comment]
It was based on the outdated bootstrap 2 version. It will not be added back in core. 

I would not recommend using it. Instead, move onto bootstrap 3 (and soon 4) themes.
If you still want a copy of the bs2 theme, I can send you a copy.
