### ISSUE TITLE
TinyMce - Remote Image disappears

### ISSUE THREAD

**Issue by chory** [e107inc/e107#1433]
When I edit a post in a forum, images and videos disappear.
This is the return code
[html]<p>Que tiempos.<br><br>**<img src="/thumb.php?src=&amp;w=800&amp;h=0"**  alt="07 00001" title="07 00001" class="img-rounded bbcode bbcode-img" width="800" /></p>[/html]

**Comment by chory** [comment]
Image
http://s559.photobucket.com/user/ch0ry/media/ErrorEditPost_zpsezgl7m14.jpg.html

**Comment by chory** [comment]
What is question label?
Any more have this error?
You don't undesrstand post?
What is question label?
Thank you

**Comment by Moc** [comment]
Error on my part, sorry :)

**Comment by chory** [comment]
Not work

**Comment by chory** [comment]
Now disappear icons for add/edit images/videos, show code, ...

**Comment by CaMer0n** [comment]
This is correct. The correct way to add images is via the 'attachments' tab. (you may need to enable it in your forum preferences.)

**Comment by chory** [comment]
uhmmm, but then, we can not format the post as we wish. In addition to the
video / image will be uploaded to the server, but do not want, or that image have stayed in other sevidor, as http://photobucket.com/
_deactivating WYSIWYG now_

**Comment by Moc** [comment]
@CaMer0n Not sure if I understand this correctly, but in my opinion a forum post should be able to contain images and videos within the forum post. When I think of attachments they could indeed be images as well, but mostly other files such as zip, pdf, audio or video files, etc.

**Comment by CaMer0n** [comment]
@Moc, you mean from external sources I guess?

**Comment by chory** [comment]
@CaMer0n I think so, but also has to provide information, and it is necessary to access / show outside sources.
It can be a video itself, that a user has uploaded to your YouTube account, and to share it with the forum members. As it is now defined, it would have to upload the video to youtube, and upload it to the forum server, so it would be doubling, something unnecessary from my point of view.
@Moc Yes that's what I mean, As permitted by the previous version

**Comment by Moc** [comment]
@CaMer0n Yes :) But media manager integration could be nice as well. As @chory said, a YouTube video should also be possible.

**Comment by chory** [comment]
Media Manager, it is a wonderful idea.
Simplifies work, organize, assign it to certain content.
But only to control the media themselves forum.

**Comment by CaMer0n** [comment]
I'll tweak the public Tinymce config file to allow external media.

**Comment by CaMer0n** [comment]
Embedding YouTube will require the users have access to post HTML.

**Comment by CaMer0n** [comment]
@chory Please update and see how that works for you.

**Comment by chory** [comment]
@CaMer0n I think you do not understand me. From the beginning, the problem is that at some point, when editing the post, data reference file or video image is lost.
Make a simple test, you create a post, and an image, by clicking the Insert / edit image button and enter a URL to an image. Send post. The image is displayed correctly. Then edit the same post, the image is lost, and instead only a box with measurements of the image looks.
If it works for you well, it is that I am an unfortunate and unlucky not to do :pensive:

**Comment by CaMer0n** [comment]
@chory Thanks. It is why I didn't close the issue. First the user must be able to post an image. ;-) I will look at this issue soon.

**Comment by CaMer0n** [comment]
@chory This should be fixed now. Please re-open if necessary.
