### ISSUE TITLE
Private Message

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1434]
Can we get a Private Message link in the theme shortcode?

![capture4](https://cloud.githubusercontent.com/assets/5818022/13865983/0d6794e4-ec7f-11e5-8a60-19049e1d7cf6.PNG)

I know that the private Message plugin is lacking with updates - thought maybe a link can be added under Profile or add it next to the User Logged in section. In the screen shot you see Voice and LaocheXe - Maybe put it on the right side of user logged in - glyph (envelop) Messages (New Messages)(Total Messages)

Just a tought

**Comment by rica-carv** [comment]
I'm currently working in a workaround of this issue, using a plugin instead a theme.
I, personally, think the them should be only for general cosmetic of the site, and not to have logins menus, etc, has they now have.
I've got a plugin that deals with logins, users profiles, user listings, extended user settings, etc., but i had it in v1.4, and i'm trying to bring it to v2....
Lets see how it goes....

**Comment by LaocheXe** [comment]
But the theme code will be looking for it, so I don't know what you are meaning to do.

**Comment by rica-carv** [comment]
The theme code will only look for it if you have the shortcode on the theme...

And if instead of the shrotcode on the theme, you have a plugin menu (just like the regular e107 login_menu) that does the same thing???
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/13892268/29c180a8-ed4e-11e5-89d3-3ffa6b78f2ed.jpg)

**Comment by LaocheXe** [comment]
So you want the menus? The login shortcode for the theme is a graphical thing kinda like having a search menu displayed at the top. The pm plugin alread has a menu, this post is to request pm short code that is in the admin area some what

**Comment by rica-carv** [comment]
[See my related question on e107help here](http://www.e107help.org/2204/how-can-i-check-if-a-shortcode-name-is-already-defined?show=2208)

**Comment by mcpeace-maw** [comment]
@LaocheXe in Profile it is a link to send PM. In login menu, you can create a shortcode with the link to PM and notification for unread messages and add it in login menu template (copy in your theme) in the place you want. In bootstrap3 theme you need to add it in the custom login menu.
