### ISSUE TITLE
Login menu placeholder not showing

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1435]
On login_menu_shortcodes.php inside the login_menu plugin the placeholder ($this->usernameLabel) on line 86 is not displaying anything....

Can this be corrected on the plugin directly or has the shortcode to be redefined on a theme base?

The weird stuff ist that the password placeholder (on line 101) does show up....

**Comment by LaocheXe** [comment]
@rica-carv on my current version of e107 (github) on line 86 I see this:

`$maxLength  = ($this->allowEmailLogin == 1 || $this->allowEmailLogin) ? 100 : varset($pref['loginname_maxlength'],30);`

On line 87 I see this:
`return "<input class='form-control tbox login user' type='text' name='username' placeholder='".$this->usernameLabel."' required='required' id='username' size='15' value='' maxlength='".$maxLength."' />\n";`

This is for the shortcode for the username/email field is  `{LM_USERNAME_INPUT}` and for password it is `{LM_PASSWORD_INPUT}`

which are in the theme_shortcode.php in the Bootstrap 3 theme - make sure you have this as well `require(e_PLUGIN."login_menu/login_menu_shortcodes.php");`

**Comment by rica-carv** [comment]
@LaocheXe [Well, the line number seems to have changed again on github.....](https://github.com/e107inc/e107/blob/master/e107_plugins/login_menu/login_menu_shortcodes.php)
Now is in line 88, so, i'm back again to my original question, the $this->usernameLabel variable in the php code is returning nothing, therefore there's no placeholder on the final generated page HTML....
The login_menu_shortcodes.php is correctly loaded, since the  {LM_PASSWORD_INPUT} shortcode is correctly rendered and has its respective placeholder....
But the username field no......

**Comment by mcpeace-maw** [comment]
I'm not sure what exactly you want to do, but if you make a custom login menu shortcode, all core login menu shortcodes works, I have try it and it is OK. Now if you want a custom style login menu in a particular place in your theme, you can make a div in that place in theme.php and call core login menu there in that div with the shortcode {MENU=login_menu/login}. After that just use some css to style it in the way you want using the class you have on the wrapper div.

**Comment by LaocheXe** [comment]
@mcpeace-maw that is very useful information and maybe this should be added to some form of documentation later on down the line. @Moc what do you think?

**Comment by Moc** [comment]
@LaocheXe You mean the {MENU=login_menu/login} in theme.php?

**Comment by mcpeace-maw** [comment]
@LaocheXe  In a similar way works for all core plugins.

**Comment by rica-carv** [comment]
@mcpeace-maw , that's not a answer to my actual question, but anyway, it's an ideia for other issue i have with theme and login menu / bootstrap login menu...
Ahead, meybe with images i can clarify this....
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/13931976/d34fe1fe-ef9d-11e5-9e92-873e34d2b349.jpg)
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/13931980/d5d389b2-ef9d-11e5-8cb9-fd97c71f4f4a.jpg)

**Comment by LaocheXe** [comment]
@rica-carv you the field shows but no field help (idk what to call it - brain not working) - looks like maybe it is missing the LAN's?? what language are you using? Will it display using the English language? Even tho it does not display can you put in a username and or email address and try to login?

@Moc yes.

@mcpeace-maw thanks for the information, I need to save that info so when I come across any issues I know what to do.

**Comment by mcpeace-maw** [comment]
@rica-carv OK I see your problem. Check in plugins/login_menu/languages/  in your language file if you have translated LAN_LOGINMENU_50 that must have "Username or Email:" translation, if is not just add it. I checked with a few themes with English language and it is displayed normal. 
@LaocheXe OK, glad that help.

**Comment by rica-carv** [comment]
@mcpeace-maw Yes, i have the correct language file with the LAN_LOGINMENU_50 defined:
`define("LAN_LOGINMENU_50", "Nome de usuário ou E-mail:");`

**Comment by mcpeace-maw** [comment]
Strange, in English it is working.

**Comment by rica-carv** [comment]
GRRRRR...

Just tested on a clean install of v2, and got this:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/13951683/9517d53a-f02a-11e5-80f5-01b5975b5224.jpg)   ![untitled 3](https://cloud.githubusercontent.com/assets/17130530/13951682/9512c6ee-f02a-11e5-85f4-6a595d1ee3f3.jpg)

Why on earth is not this working on my development site???
Maybe is there any chance that LAN_LOGINMENU_50 is getting redefined???
As far as i can see, constants can't be redefined.....

In the mean time, on the same clean v2, on the admin area, i got this issue with the Portuguese language:
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/13951772/d2f5ff1c-f02a-11e5-979c-ae677ed9c59f.jpg)

**Comment by LaocheXe** [comment]
If you get an LAN_WHATEVER popping up means that it is missing from the language file.

**Comment by rica-carv** [comment]
@LaocheXe Thanks, i know that. so why is this happening on the admin area, with a core language that was supposed to be translated from the English language files??????

**Comment by LaocheXe** [comment]
Could be when the language translation was made it didnt get updated because they updated the LAN's in the code.  Example LAN_NEWNAME got changed to LAN_NAME

**Comment by rica-carv** [comment]
@LaocheXe Nope, i just did a check on the [lan_admin.php on the core](https://github.com/e107inc/e107/blob/524bed7a17b1f0f7790f6ffaa78b32faa3903a99/e107_languages/English/admin/lan_admin.php), and [lan_admin.php in the Portuguese language](https://github.com/rica-carv/e107-v2.x-Language-Packs/blob/master/Portuguese/e107_languages/Portuguese/admin/lan_admin.php), and there's a lot of lines missing!!!!
From 430 on the core, it only has 263 on the Portuguese!!!!!!

**Comment by Moc** [comment]
> What's more weird is that i did a search for LAN_CONTROL_PANEL in github on the language packs, and only six languages have that defined: Czech, Slovak, Hungarian, Russina, Norwegian and Dutch....

Not really weird, but not 'correct' indeed. The language packs are currently not strictly controlled (mostly due to a lack of resources). This means that language packs may be outdated (which is the case) while still being available for download. This will cause the LAN_XX to show up.

**Comment by rica-carv** [comment]
@Moc So, is there a way to quickly cross the core English language files with another language files, to see wich language definitions are missing???? And on the process, translate them???

**Comment by Moc** [comment]
@rica-carv Yeah. All the tools you need can be found in the admin area > Settings > Language > Language packs (/e107_admin/language.php?mode=main&action=tools). Personally, I haven't used them but there are others here who have more experience with them.

**Comment by Moc** [comment]
I am assuming this issue is no longer relevant. Let me know if it still is, then I'll re-open.
