### ISSUE TITLE
Make newforumposts_main plugin compatible with v2

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1436]
The newforumposts_main plugin is currently compatible with version 1.x only.

Could you make it "Made for v2"?

**Comment by Moc** [comment]
In terms of functionality, it should just work properly already due to backwards-compatibility. 

The reason as to why it doesn't have the 'made for v2' label is that the code still requires clean-up and potentially a rewrite.

**Comment by chory** [comment]
I've done this [Gist]( https://gist.github.com/chory/e63b1af77d7eec649343)

**Comment by pierre0042** [comment]
It now says compatible "6" ?
But the plugin seems to work.

**Comment by CaMer0n** [comment]
The newforumposts_menu now supports different templates (via the popup configuration in menu-manager). The 'main' template is the replacement for "newforumposts_main". The template still needs some work and enhancement.

**Comment by newwhitebear** [comment]
since the plugin 'newformposts_main' has been corrected, a strange text, 'LANDT_XAGO' appears instead of hours or days or years of the relative post or chat. Moreover it has requested the uninstallation of the plugin, because it is no longer compatible with version 2.x.
What I have to do? is a mistake?

**Comment by Moc** [comment]
@newwhitebear You are two issues which in fact are not bugs :) 


The LAN_XAGO is a recent change which is not related to the forum menu. It's related to all places where relative datestamps show ('X minutes ago' for example). If you use the English language pack, everything should display fine...

If it doesn't, without the LAN_XAGO, then please let me know. If you are using another language than English, you'll need to update your language pack once the translator has updated the language pack. 

The other issue is the fact that the newforumposts_main menu as a separate plugin has been removed. You need to remove this folder from e107_plugins. The newly updated menu is available in the forum plugin itself. You can add it through the menu manager. In the configuration options you can choose the template, so it matches with how it looked when you were using it as a separate plugin.

**Comment by newwhitebear** [comment]
ok. I have corrected it in the italian language file.

**Comment by Moc** [comment]
Closing this, see my previous reply.
