### ISSUE TITLE
Cannot add mp3 files in media manager

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1437]
I have an error when I want to add mp3 files in the Media Manager :

![e107media](https://cloud.githubusercontent.com/assets/4124597/13892216/1e659570-ed56-11e5-8999-6ead2b47437d.png)

**Comment by tgtje** [comment]
issue #1268

**Comment by TrueHatori** [comment]
You must edit the filetypes.xml in e107_system ...

**Comment by pierre0042** [comment]
Here is my filetypes.xml file 

<e107Filetypes>
<class name="253" type="zip,gz,jpg,jpeg,png,gif,xml,mp3" maxupload="8M"/>
</e107Filetypes>

**Comment by pierre0042** [comment]
I don't see any fix in #1268 ?

**Comment by tgtje** [comment]
Does it work using import ? (not direct)

**Comment by pierre0042** [comment]
You mean in /e107_admin/image.php?mode=main&action=import
or using FTP ?

**Comment by LaocheXe** [comment]
Yup tested it - Media Manager is blocking mp3 files

**Comment by LaocheXe** [comment]
I don't know why I keep getting invalid file when trying to upload a mp3 file - I've sync with github three times today

**Comment by pierre0042** [comment]
It's working now for me

**Comment by CaMer0n** [comment]
@LaocheXe You might need to clear your browser cache. (clear out the old js file that was limiting the file types)
