### ISSUE TITLE
Error 404: Document not found

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#1438]
When on /e107/e107_admin/language.php?mode=main&action=tools clicking on the link that says e107 Certified Translator it gets you to http://e107.org/content/About-Us:The-Team#translation-team which is a non-existant document.

**Comment by Moc** [comment]
Yeah this is a reference to a page on the old website. This particular page hasn't been transferred. 
It basically shows you a list of the translation team. Is there anything in particular you'd like to know?

**Comment by Norwayman** [comment]
@Moc  yes, I know this. I have used E107 for 10 years now. I just thought I would bring it to attention to you guys so that new users of E107 would get a good impression of the system and not ending up on a page that does not exist. I think either the link should be removed or one needs to link to the right place, don't you think?

**Comment by Moc** [comment]
O agree. Thanks for the feedback.

**Comment by CaMer0n** [comment]
I'd like it if we would use the wiki for the frontend docs, and all the list of translators. 
https://github.com/e107inc/e107/wiki
