### ISSUE TITLE
[Bug] No button to refresh plugins list

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1441]
Well, this button has disapeared, but plugins seems to still use some kind of timeout to refresh the "not installed" list.

(Latest github version, downloaded today)

Grts,
- Nes

**Comment by Moc** [comment]
Confirmed

**Comment by CaMer0n** [comment]
Enable debug, does it appear?

**Comment by Moc** [comment]
@CaMer0n Nope.
