### ISSUE TITLE
Theme not rendering on Frontpage....

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1442]
I've started my theme from scratch, so i can get it working with bootsrtap in e107 v2, but i've got a strange issue...
My theme displays correctly on any sub pages, but on the frontpage, it sipmly renders a simple page, without any menus, header or footer!!!!
My current theme.php $LAYOUT['default'] code is simply this:

``` html
<div class="navbar navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{SITEURL}" title="{BOOTSTRAP_BRANDING}"></a>
        </div><!--/.navbar-header -->
<div id="tagline">{SITEDESCRIPTION}</div>
<div id="search">{SEARCH}</div>
<div id="banner">{BANNER}</div>
        <div class="navbar-collapse collapse {BOOTSTRAP_NAV_ALIGN}">
            {NAVIGATION=main}
            {BOOTSTRAP_USERNAV: placement=top}
          {PBOOTSTRAP_USERNAV: placement=top}
        </div><!--/.navbar-collapse -->
      </div><!--/.navbar-container -->
    </div><!--/.navbar-fixed-top -->

    <div class="no-overflow">
        <div class="row max-height">

            <div class="span8 scrollable">


    {---}

</div> <!-- /container -->
                </div><!-- /.span8 -->

            <div class="span4 scrollable">
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
{SETSTYLE=menu}
{MENU=2}
        </div><!-- /.row -->
      </div><!-- /.container -->
            </div><!-- /.span4 -->

</div><!-- /row -->
</div> <!-- /container -->

{SETSTYLE=default}
<div class="navbar navbar-fixed-bottom" role="navigation"><footer>
    <div class="container">
        <div class="row">

            <div>
                <div class="col-lg-12">
                    {NAVIGATION=footer}
                </div>
                <div class="col-lg-12 text-right">
                    {XURL_ICONS: size=2x}
                    {BOOTSTRAP_USERNAV: placement=bottom&dir=up}
                </div>
            </div>
      <div>
                <div id="sitedisclaimer" class="col-lg-12 text-center">
                    <small >{SITEDISCLAIMER}</small>
                </div>
            </div>

        </div>   <!-- /row -->
    </div> <!-- /container -->
</footer></div>
```

Documentation doesn't help much, so any ideas what i'm doing wrong here???

**Comment by mcpeace-maw** [comment]
For front page (aka landing page) you have 2 possibilities, define in your theme.php file a layout for front page using $LAYOUT['default-home'], or use the default layout $LAYOUT['default']. To make the theme to use your layout(s), you need to declare the layout(s) in theme.xml file. Now to set what page is front page go to admin area/ Front Page and pick one from news, welcome message...

**Comment by rica-carv** [comment]
> For front page (aka landing page) you have 2 possibilities, define in your theme.php file a layout for front page using $LAYOUT['default-home'], or use the default layout $LAYOUT['default']. To make the theme to use your layout(s), you need to declare the layout(s) in theme.xml file.

@mcpeace-maw: I've already donne that, and it desn't work.... Or maybe i'm doing it wrong.....

**Comment by mcpeace-maw** [comment]
You can open theme.xml in bootstrap3 core theme and see the code and compare with your code. If that file is OK I see no reason for issues.

**Comment by rica-carv** [comment]
Grrrrrr. Now it appears.... Damn cache....
I've restarted my localhost development server, and it appears now as i'm intended.....
Grrrrrrrrrrrrrrrrr.........

Forget it....
Excuse me for all the trouble.....

**Comment by rica-carv** [comment]
@mcpeace-maw : My theme is directly copied from the Boostrap3 core theme, so the theme.xml is the original with my modifications....

Well, sung victory too soon....
"Bug" is back again, and the issue is indeed when rendering FRONTPAGE (ie, going to site index)...

**Comment by mcpeace-maw** [comment]
In bootstrap3 in xml file landing page layout is jumbotron_home (it have custompages FRONTPAGE). If you go to Theme Manager/Site theme you see on visibility filter FRONTPAGE at that layout? If not add it or reinstall the theme. Now you have  jumbotron_home layout in theme.php and you have {MENU=1} and is not rendered? I can't reproduce that issue.

**Comment by rica-carv** [comment]
There's an updated theme on my github area: https://github.com/rica-carv/e107_theme-selospt_v2
This is the one that's giving me this issues...

**Comment by mcpeace-maw** [comment]
OK I checked, first you need to cleanup theme.xml file, remove <stylesheets> section if your theme use just style.css and not alternative style. For <custompages> is like in v.1, put all pages in 1 row with 1 empty space between them, like this: <custompages>FRONTPAGE /news</custompages>
In theme.php in your LAYOUT['default'] you need menus areas like {MENU=1}, {MENU=2} and from MENU MANAGER activate some menus in these areas.

**Comment by rica-carv** [comment]
@mcpeace-maw I've just cleaned up the theme.xml (updated on github), and donne the changes you suggested, and still persists the problem....

**Comment by mcpeace-maw** [comment]
Add after < div class="span4 scrollable" > {MENU=1} and check. You can add haw many menus areas you need, but start with menu=1

**Comment by rica-carv** [comment]
@mcpeace-maw Just did that, no go... Still the same error.... I know i can add as many menu groups i want, but in my site i've got a custom login_menu on menu area 1 {MENU=1}, and all the remaining menus on menu area 2 {MENU=2}.....

**Comment by rica-carv** [comment]
@mcpeace-maw Just did that, no go... Still the same error.... I know i can add as many menu groups i want, but in my site i've got a custom login_menu on menu area 1 {MENU=1}, and all the remaining menus on menu area 2 {MENU=2}.....

Anywat, got a tip from @Jimmi08 and well, seems i got it working...
Just renamed the layout[´default´] to layout['main'], and it apparently seems to work...
Many thanks for all the help...

**Comment by Moc** [comment]
Reopening for documentation reminder

**Comment by rica-carv** [comment]
@Moc Indeed, documentation is still a litlle weak at this time, doesn't is?

**Comment by Moc** [comment]
> Indeed, documentation is still a litlle weak at this time, doesn't is?

Due to a lack of resources (time and people) yes. The focus thus far has been on technical developer documentation and I'd like to extend this to more user guides as well. An initiative of e107help.org to work on this was planned but not started due to lack of resources (yet again). See: http://e107help.org/update and https://plus.google.com/114157136655453277681/posts/J4694FDn481

**Comment by LaocheXe** [comment]
@Moc Wicked sweet!
