### ISSUE TITLE
How can I use "Profile aliases" in "Site links"?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1443]
My "Profile aliases" configuration:
![kepernyokep - 2016-03-21 - 14 25 42](https://cloud.githubusercontent.com/assets/6043821/13920194/15d0117e-ef72-11e5-8617-9e9235b2b82f.png)

And one of my site links:
![kepernyokep - 2016-03-21 - 14 26 55](https://cloud.githubusercontent.com/assets/6043821/13920208/254a2ce8-ef72-11e5-9795-d7886960e80d.png)

But I don't know how to use it in "Site links"... :) I would like to use "hirek" if language is hungarian, and "news" if english. How can I achieve this?

I also thought I have to make two (separated) links, one for hungarian language, and one for english, but I cannot set the language for menu item. :( In my opinion the best would be to provide a dropdown to select fixed language for menu items (If no language is selected, link will show regardless of language).

**Comment by tgtje** [comment]
I hope i do not misunderstand, but for sitelinks the method of v1 still applies, language tables...

**Comment by lonalore** [comment]
I think this belongs to "multilan" plugin. Moved here: https://github.com/e107inc/multilan/issues/7
