### ISSUE TITLE
Question: Contact Us - Shortcode

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1444]
In Admin Area - > Preferences - > Email and Contact Info - > Site Contact Information you can't put any Shortcode (example {MYPLUGIN_SHORTCODE} - is there an issue having shortcode in that field or is this something not thought of as of yet?

Easy way around it would to use a custom page with the shortcode so I don't know - Im getting myself confused now lol

**Comment by mcpeace-maw** [comment]
If I understand correctly, you want to display on contact page your shortcode? Add contact_template in your theme and add your shorcode,

**Comment by LaocheXe** [comment]
That not in the bootstrap 3 theme?

**Comment by mcpeace-maw** [comment]
I see bootstrap3 have no contact template, but you can add it.
