### ISSUE TITLE
Question: Edit mode link in page, filetype.xml and backup

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1445]
I want to have a link in each page, leads directly to the edit mode. For the news that was simple because it comes in the theme.php. What do I have while writing this to work?

I can my filetype.xml after editing not upload (FTP), the system says I can not do that.

I have made over the database tools a dump. I could download, but I can not delete it.

Any ideas on the three points?

**Comment by CaMer0n** [comment]
> I want to have a link in each page, leads directly to the edit mode. For the news that was simple because it comes in the theme.php. What do I have while writing this to work?

It depends on which kind of editing you are referring to. For news there is a particular shortcode (which should be there already) and for 'page' it will be another shortcode. 

> I can my filetype.xml after editing not upload (FTP), the system says I can not do that.

Could be related to the problem below. 

> I have made over the database tools a dump. I could download, but I can not delete it.

Your particular host has locked down your system so that files created by the PHP scripts (eg. cache, backups, image thumbnail etc) cannot be deleted via PHP.  Unless your hosting provider is willing to correct this, the only solution is to find another host which doesn't do this.

**Comment by TrueHatori** [comment]
I can't delete via FTP. Not the Backupfile and not the filetype.xml. In filetype.xml I need pdf.

Edit-Link - I mean, I want to have this in Frontend. When I logged in as Admin, I want a Link to Edit-Mode. In old version I had this. Which shortcode must I write in which file?

**Comment by TrueHatori** [comment]
Now I delete the two files with the help of desk from my provider. But I can't upload the filetype.xml via FTP. Whats this? What can I do?

**Comment by tgtje** [comment]
Just throwing it in : your hosting uses FTP-lock.. Are you sure you are able to work (have enough priviliges?) with that? (normaly in control panel there probably is a button that allows temporarely an unlock, or ip setting etc..).

**Comment by TrueHatori** [comment]
I haven't a control panel, I can only delete files from my hosting overview. I can try delete complete folder and the folder new upload.

**Comment by TrueHatori** [comment]
Yes, delete the complete folder was successful.

Now I want only please to know, which shortcode must I write in which file, that I become my edit-link in pages?

**Comment by CaMer0n** [comment]
For News it is `{ADMINOPTIONS}` if I remember well.

**Comment by TrueHatori** [comment]
For News I have in theme.php:
`if (ADMIN == TRUE) {
  $admin_news = ' - [<a href="e107_admin/newspost.php?action=create">'.LAN_THEME_11.'</a>] | [<a href="e107_admin/newspost.php?action=edit&id={NEWSID}">'.LAN_THEME_12.'</a>]';
	}`

And then in NEWSSTYLE
`<div class='news_title'>{NEWSICON} &nbsp;&nbsp; {NEWSTITLE} - (geschrieben am {NEWSDATE} von {NEWSAUTHOR})&nbsp;&nbsp;".$admin_news."</div>`

For pages is ADMINOPTION enough, but where must write this in?

**Comment by TrueHatori** [comment]
Can really tell anyone where I need to write down something in order to get the edit link in page?

**Comment by Moc** [comment]
Please be a little more patient, people are busy and you are not the only one with questions or issues :) 

> Can really tell anyone where I need to write down something in order to get the edit link in page?

This should be added to the page template, which can be found in e107_core/templates. As instructed here: http://e107.org/developer-manual/theme-basics#overriding-core-templates You should copy the template to the templates folder within your theme folder (e107_themes/yourtheme/templates/page_template.php)

**Comment by TrueHatori** [comment]
Thanks, but which I know still not WHAT I must WHERE write down. But retain your knowledge for you, the users will just see how he copes.

**Comment by Moc** [comment]
Answered here: http://e107help.org/2263/edit-link-in-pages
Closing issue on Github.
