### ISSUE TITLE
Captcha not rendered

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1446]
Yesterday I updated the themes Basic and Basic Light and made a finding unpleasant. Captcha is not rendered and displayed "Missing Code" text in login menu. When I put them on download, I have tested and everything was OK and their users did not report yet this bug. Bug apparently occurred after I updated yesterday e107 from here and I have no idea what causes this bug.

**Comment by CaMer0n** [comment]
@mcpeace-maw Thanks. I see it. Are you using PDO for your DB? You can test with this: var_export($sql->getPDO())

**Comment by mcpeace-maw** [comment]
I try it the themes online on test site and is the same. On local I use wampserver and extentions php_pdo_mysql and php_pdo_sqlite are checked, I don't see just php_pdo extention.

**Comment by CaMer0n** [comment]
@mcpeace-maw Are you able to meet at gitter?

**Comment by mcpeace-maw** [comment]
OK, I'm in.

**Comment by CaMer0n** [comment]
@mcpeace-maw It appears that the captcha in the login-menu functions if it is placed in the top navbar, but not the bottom.

**Comment by mcpeace-maw** [comment]
I'm not sure I understand the solution, Basic themes use regular login menu not a custom one.

**Comment by mcpeace-maw** [comment]
After some tests with Basic theme it seams that if the login menu is in a menus area placed before {---} the captcha is rendered, if is after {---} is not rendered.

**Comment by mcpeace-maw** [comment]
@CaMer0n thanks for fixing this.
