### ISSUE TITLE
How to rename bootstrap theme icons class?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1447]
For instance, on my current development theme i have:
`<i class="fa fa-comment"></i>`

How can this be changed to:
`<i class="custom custom-comment"></i>`

**Comment by LaocheXe** [comment]
the fa fa-comment are gyph (mispess) which are fonts that are images - https://github.com/FortAwesome/Font-Awesome

**Comment by mcpeace-maw** [comment]
What is wrong with font awesome that are supported by e107? 
Anyway just for news comment icon you can add in theme.php something like:
define('COMMENTLINK', e107::getParser()->toGlyph('fa custom custom-comment'));
and output is <i class="icon-fa custom custom-comment"></i>

**Comment by rica-carv** [comment]
@LaocheXe I know that, thanks...
@mcpeace-maw What's wrong with font awesome icons supported by e107? Simple, i din't like monochromatic icons, so i'll be using the FamFam icons instead of font awesome...
I though WE107 was all about easy customization, and that we can use anything we like in themes, instead of the "imposed" core icons....
Is there a list of the defines i can redefine with `define('COMMENTLINK', e107::getParser()->toGlyph('fa custom custom-comment'));` ????
Many thanks

**Comment by mcpeace-maw** [comment]
FamFam are png images, OK. I never try it with v.2, but... remove from theme define("FONTAWESOME", 	4); and the theme will load images icons not font icons, then go in e107_images and replace the icons from there with you icons.

**Comment by LaocheXe** [comment]
Remember that e107 v2 is built around bootstrap. However you can do anything if you know what to do.  My Voice plugin uses custom font icons i made from png images of the TeamSpeak3 logo, Mumble logo, Ventrilo logo, and Discord logo.

**Comment by rica-carv** [comment]
@mcpeace-maw Just removing the define("FONTAWESOME") won't do, since the theme is still bootstrap and it will bring the bootstrap default icons.... I've already tried that.
Despite, having a bunch of indepedent icons on e107_images folder [is not really good ideia](https://css-tricks.com/css-sprites/)....
Anyway, you can do that not in e107_images but on the images folder inside the theme itself (on v1.4 that's how it was...)

@LaocheXe I know E107 v2 is built around bootstrap, but [bootstrap itself allows this degree of customization](http://favbulous.com/post/1006/create-custom-icons-for-twitter-bootstrap-easily), and i also know i can do anything i want, sometimes is easy, other is really hard, since there's no documentation for helping us....

For instance, on this issue, my first thought was just use php's regexp replacement, but even that was quite hard to implement on a theme.....

**Comment by rica-carv** [comment]
Well, thanks for all the help, but i needed to change ALL the icons classes, so instead, i do this on my css:
`/* Mockup to remove Fontawesome icons, preserving class names */

.fa{font:unset}
.fa::before{content:unset}
`

Not very elegant, but on me, for now, it works.....
