### ISSUE TITLE
Documentation: List with permissions?

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1456]
Is there somewhere a list of the permissions? As an example: In gsitemap plugin are perms with P and 7 and 0 assigned. This could be within a plugins - particularly large plugins - occupy different functions with different permissions.

**Comment by CaMer0n** [comment]
There is no perms list for 3rd-party plugins. You need to save your own preferences for that. See the faqs plugin for an example.

**Comment by Moc** [comment]
Reopening for documentation check reminder
