### ISSUE TITLE
permission to URL configuration

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1458]
Hi,
I set admin permission to user (admin)
![image](https://cloud.githubusercontent.com/assets/5429548/14064215/3dcda024-f3fa-11e5-9b56-500bcd200e8d.png)

They see this:
![image](https://cloud.githubusercontent.com/assets/5429548/14064217/4dcb6434-f3fa-11e5-88c8-c5df8649238f.png)

But nothing happens when they clink on button or choose URL configuration from Setting menu.

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 please update and test. thanks

**Comment by Jimmi08** [comment]
Works. Thank you very much.
