### ISSUE TITLE
cannot save content with code inside text

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1460]
After submitting form I always get Error 500 or Unauthorized access! message.

error.log contains only this:
[Fri Mar 25 12:21:46.819578 2016] [core:error] [pid 32088] [client 188.142.226.249:42580] End of script output before headers: cpage.php, referer: http://xxxxxxxxxx/e107v2/e107_admin/cpage.php?mode=page&action=create

Reproducing:
1, Create custom page with this content: [plugin_xml.txt](https://github.com/e107inc/e107/files/199790/plugin_xml.txt)
2, Submit form

**Comment by CaMer0n** [comment]
Reproduced. If you find a solution, please let me know.

**Comment by lonalore** [comment]
I reproduced this bug on Apache and Nginx server too. so it's a PHP related issue. I tried to increase PHP limits, but no result, still the same. I will try to debug it tomorrow... or today If I will have time.

**Comment by lonalore** [comment]
The problem is in cleanHtml() method. If I comment `$data = $this->cleanHtml($data);` out in `$tp->toDB()` method, it works. Why don't you use 'HTML Purifier' to filter XSS and other malicious codes?

**Comment by lonalore** [comment]
Fixed, but testing required!!

Replace following code in **e_parse_class.php** (line 4411 - 4440):
```php
foreach($this->nodesToDisableSC as $node)
{
	$value = $node->C14N();

	if(empty($value))
	{
		continue;
	}

	$value = str_replace("&#xD;","\r",$value);

	if($node->nodeName == 'pre')
	{
		$value = preg_replace('/^<pre[^>]*>/','',$value);
		$value = str_replace("</pre>", "", $value);
	}

	if($node->nodeName == 'code')
	{
		$value = preg_replace('/^<code[^>]*>/','',$value);
		$value = str_replace("</code>", "", $value);
	}

	$value = str_replace('{','{{{',$value); // temporarily change {e_XXX} to {{{e_XXX}}}
	$value = str_replace('}','}}}',$value); // temporarily change {e_XXX} to {{{e_XXX}}}

	//  $value = htmlentities(htmlentities($value)); // Crashes apache.
	$node->nodeValue =  $value; // Crashes apache sometimes FIXME! .
}
```

to this:
```php
foreach($this->nodesToDisableSC as $key => $node)
{
	$value = $node->C14N();

	if(empty($value))
	{
		continue;
	}

	$value = str_replace("&#xD;", "\r", $value);

	if($node->nodeName == 'pre')
	{
		$value = preg_replace('/^<pre[^>]*>/', '', $value);
		$value = str_replace("</pre>", "", $value);

		$value = preg_replace('#<br\s*/?>#i', "\n", $value);
		$value = str_replace("</br>", "", $value);
	}

	if($node->nodeName == 'code')
	{
		$value = preg_replace('/^<code[^>]*>/', '', $value);
		$value = str_replace("</code>", "", $value);

		$value = preg_replace('#<br\s*/?>#i', "\n", $value);
		$value = str_replace("</br>", "", $value);
	}

	$value = str_replace('{', '{{{', $value); // temporarily change {e_XXX} to {{{e_XXX}}}
	$value = str_replace('}', '}}}', $value); // temporarily change {e_XXX} to {{{e_XXX}}}

	$newNode = $doc->createElement($node->nodeName);
	$newNode->nodeValue = $value;

	$node->parentNode->replaceChild($newNode, $node);
}
```

The main problem was about nodeValue property. There is a warning message too in documentation of DOM Document to avoid using it because it sometimes crashes.

**Comment by lonalore** [comment]
I can't commit my changes because it would be included into #1469 automatically...

**Comment by CaMer0n** [comment]
Thank you! I will run some tests with this code.

**Comment by Moc** [comment]
@lonalore Just so you know. You can create a new pull-request (which does not include your previous commits) by using a new branch. So you create a new branch on your fork, commit the changes to that branch, then you can submit a new PR from that branch to the master branch on the e107 repository.

**Comment by CaMer0n** [comment]
@lonalore I think we can close this one now, correct?

**Comment by lonalore** [comment]
Correct :)
