### ISSUE TITLE
suggestion for lang strings

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1461]
Could you consider to use separate lang string for empty value? Or have separate string of "no"  for news, comments, users?

define("LAN_LOGINMENU_26", "no");
- in plural form there is more translations than just "no"  - žiadne/žiadna/žiadni  
  I could use one word, but then I need singular form (and  LAN_LOGINMENU_15 is for plural)

![image](https://cloud.githubusercontent.com/assets/5429548/14065302/87294352-f424-11e5-8513-e720313d7f2e.png)

I can solve more plurals forms with template (with changing order of fields), but not this. 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please submit a pull-request with the proposed changes?

**Comment by Jimmi08** [comment]
@CaMer0n I will try. How I can test if some lang string is defined?

**Comment by Moc** [comment]
Closing in favor of #816
