### ISSUE TITLE
testing new site - user registration and problem with email

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1462]
Ok, again maybe I just get this  wrong.

I supposed that this:
![image](https://cloud.githubusercontent.com/assets/5429548/14066388/6044f410-f448-11e5-8979-cc5cab60d906.png)
means  that user didn't get password displayed in email. But they got. Is it bug or what is purpose of this field?
![image](https://cloud.githubusercontent.com/assets/5429548/14066398/e5952c2a-f448-11e5-9a03-39b5590a6bff.png)

In verification email is username as email (I have both user/email login allowed). Is this correct? Username is different. 

And last question:
with this settings
![image](https://cloud.githubusercontent.com/assets/5429548/14066429/47f288cc-f449-11e5-82cc-c1c6d88dfa19.png)
do I still manually add lines to htaccess (just to have one www version)?  

And if SiteUrl is with www, why adress in verification email is without it 
![image](https://cloud.githubusercontent.com/assets/5429548/14066442/7feba68c-f449-11e5-9d9e-d31b689e6a24.png)

Thanks

**Comment by CaMer0n** [comment]
The URL depends on how the user came to the website. (with www. or without)
