### ISSUE TITLE
hardcoded/not translated string in login.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1465]
In login.php is not translated message:

![image](https://cloud.githubusercontent.com/assets/5429548/14076807/6c055734-f4e5-11e5-9c1e-e6b0c568bdae.png)

Can I add new string LAN_LOGIN_32 in lan_login.php ?

**Comment by Moc** [comment]
I think so, yes.

**Comment by CaMer0n** [comment]
Perhaps e107_languages/English.php would be a better place, as it may be used throughout the whole site.

**Comment by tgtje** [comment]
Happens only 1 time (suppose this string : You are currently logged in.
 the other time is LAN_SIGNUP_112 >You are currently logged in as Main Admin

**Comment by Jimmi08** [comment]
@CaMer0n Sorry, I probably did something wrong. I pulled request, see it above, but I can't find it between waiting request and it wasn't merged. What happened to it? Thanks

**Comment by Jimmi08** [comment]
Closing. This message is only for main admins. 
```
if(getperms('0'))
{
echo "<div class='alert alert-block alert-error alert-danger center'> You are currently logged in.</div>";	
}
```
