### ISSUE TITLE
shortcodes, how they should work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1467]
Ok, this would be hard to explained, but I will try anyway. I just don't understand and I really tried to. (I am trying to replace plugin or code shortcode by theme shortcode)

- shortcodes are handled by shortcodes_handler.php file and classes in there
From this I can see order how they are loaded:
```
		$this->loadOverrideShortcodes();
		$this->loadThemeShortcodes();
		$this->loadPluginShortcodes();
		$this->loadPluginSCFiles();
```
Each shortcode should be loaded just once, so if the shortcode is defined/declared in theme (theme shortcodes), it shouldn't be overwritten by plugin.

With theme or plugin development is useless to use override functionality, because it needs next folder (in core/... etc). 
In loadThemeShortcodes() are loaded all theme shortcodes. Ok.

In loadPluginShortcodes() are loaded all shortcodes from e_shortcodes.php (in my case gallery, featurebox,page,siteinfo,social) and in loadPluginSCFiles() all old.sc shortcodes (in my case newforumposts_main,pm,tagwords)

**This works exactly as shoud have**, I am able f.e. rewrite sc_xurl_icons() from social plugin in theme.  Perfect.  They are global shortcodes, I get it.  And I notice correct test  `(!$this->isRegistered($code))`

But there are core shortcodes that I need to override with theme (mostly because they have harcoded html markup). When I use debugger, it shows that shortcode is registered by theme.
![image](https://cloud.githubusercontent.com/assets/5429548/14078793/dbb7f97a-f4f8-11e5-93fa-23b3a5172d88.png)
or if I print registered shortcodes
![image](https://cloud.githubusercontent.com/assets/5429548/14078783/c85fb642-f4f8-11e5-8d66-4e142c952ebe.png)

But doCode() at first tests addedCodes() method, if core shortcodes exists, it uses it, so I think to use override functionality wouldn't help too, because these shortcodes are as registered shortcodes and they are ignored (or they are tested later in doCode().  

Can somebody explain this to me?  I would expect order: theme (first), plugins, core...  Thanks

**Comment by CaMer0n** [comment]
It is possible that the order is incorrect for this to occur. But perhaps the question we should be asking is.. why override a shortcode at all? Why not just create a new shortcode and modify the template to use it?

**Comment by Jimmi08** [comment]
Example: login.php and login form.  Login shortcodes are hardcoded (html
code). How would you solve this with new shordcodes and template?  I would
try it if i know how. Or do you mean rewritting better way original core
shortcodes?
Dňa 28.3.2016 17:08 používateľ "Cameron" <notifications@github.com> napísal:

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please paste a gist of the hard-coded part you are referring to? Thanks.

**Comment by Jimmi08** [comment]
@CaMer0n  
```
	function sc_login_table_footer_userreg($parm='')
	{
		//$pref = e107::getPref();

		if(empty($this->userReg))
		{
			return null;
		}
		
		$text = "<a href='".e_SIGNUP."'>".LAN_LOGIN_11."</a>";
		$text .= "&nbsp;&nbsp;&nbsp;<a href='".e_BASE."fpw.php'>".LAN_LOGIN_12."</a>";
		return $text;

	}
```

and I need to use this markup:

```
 <a href="#" class="btn btn-success pull-right">Create Account</a>
 <a href="#" class="btn btn-warning">Password Recovery</a>
```

I will write you on gitter what I am trying to do. 

PS. The best solution is to do everything via templating, so if you tell me to try add more parms or new shortcodes, I could help.

**Comment by Jimmi08** [comment]
@CaMer0n Do you think I could suggest this change for sc_login_table_submit()  ?
It should have new name to not break already existing themes. But I think that just @mcpeace-maw has some.
![image](https://cloud.githubusercontent.com/assets/5429548/14090059/732230f2-f538-11e5-802c-ea30a7298543.png)

**Comment by CaMer0n** [comment]
@Jimmi08 You can just replace {login_table_footer_userreg} with your own shortcode in your login_template.php file, right?

**Comment by Jimmi08** [comment]
Yes, but I don' t know where to write it.
Dňa 29.3.2016 1:54 používateľ "Cameron" <notifications@github.com> napísal:

**Comment by Jimmi08** [comment]
@CaMer0n I found it! I need more testing, but there is not need for changing anything in core. I hope.

**Comment by Jimmi08** [comment]
@CaMer0n 
I am closing this. With easy theme you don't need this functionality. With more complicated theme I always create theme plugin anyway (to have one folder for each new menus and other reasons), so this was too easy.
- just use template system (f.e. news template in theme folder)
- create global shortcode in theme plugin (f.e. themeoptions plugin)
- replace core shortcode in theme template 
- global shortcodes can be overwritten in theme shortcodes if it's needed, but I created them fully parametrized
By the way, just 4 shortcodes needed to customize, after 2.1.1 I could send suggestion to improve core shortcodes.

**Comment by rica-carv** [comment]
I've recently tried to rredefine the GLYPH shortcode on my custom news_template.php, and it didn't work...
Maybe GLYPH is not a core redefinable shortcode?

**Comment by LaocheXe** [comment]
Are you trying to change the GLYPH's? Glyph's are the Fontawsome - follow the bread crumbs -> theme_shortcode.php and other templates. This is the cheat sheet - [https://fortawesome.github.io/Font-Awesome/cheatsheet/](https://fortawesome.github.io/Font-Awesome/cheatsheet/)

**Comment by rica-carv** [comment]
@LaocheXe : [Yes, i was trying to change the GLYPHS, because i want to use in my theme the FamFAm icons instead of the monochromatic Glyphs.](https://github.com/e107inc/e107/issues/1447) One approach was to change the class name on the hardcoded returned Glyph, but once i was unable to redefine the shortcode at the theme level, or worst (ie: use php regexp replacements), i give up and decided another approach, do it only with CSS....
It's a crumbersome approach, but it works for me....
