### ISSUE TITLE
Created page that is not seen in admin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1474]
I was somehow able to create page, which I can't  find in admin (either in pages, either in menus)

I use latest Github because I thought it was related with 2.1 version. It wasn't. After some testing I found that:

You can create page with empty title, there is no test. And because it's not menu (not menu title is filled) you are not able to find this page. 
 
I don't think it's worked this way before. One of these fields should be always filled.  I was able to find and correct this page only via page navigation menu and without using sef url (to see ID). This page wasn't displayed in book/chapter list. At least there should be the same rules what is page (content page versus page navigation menu). 

Thanks

**Comment by tgtje** [comment]
Yes it did work similar before, i mentioned posted it somewhere.(found it #1180  ) No title > no visible clues. Dbase however stores it..
