### ISSUE TITLE
Forum post returning http headers / strange output

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1476]
Hi there,

We've just had a user report strange output when posting or editing on the forum, returning lots of garbled characters / http header like output.

I personnally haven't expierenced this errror.

See:
https://www.crazy-fools.co.uk/e107_plugins/forum/forum_viewtopic.php?id=41960

Thanks!

**Comment by CaMer0n** [comment]
@Brooniee Could you please make sure that Admin > Preferences > Advanced Features > Compress Site Output Using gzip is disabled?

**Comment by Brooniee** [comment]
@CaMer0n done now. Is it currently bugged?

**Comment by tgtje** [comment]
Only mentioning : peeked in, login php is broken (test warn about ssl certificate)...

**Comment by CaMer0n** [comment]
@Brooniee So it was enabled? It's not necessary if your server is automatically gzipping content.

**Comment by Brooniee** [comment]
@CaMer0n yeah, it was enabled and has been since install with 1.x - disabled now though.

**Comment by CaMer0n** [comment]
Okay, please let me know if it occurs again. I suspect it was gzipping twice.

**Comment by Moc** [comment]
Closing as issue seems to be resolved. Please re-open in case it occurs again.
