### ISSUE TITLE
Enhancement: List of core plugins to export when exporting languagapacks

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#1481]
I have recently asked alot on how to use Github for submitting my languagepack that I tohught was 100% bullet proof. But I get the comment from developers that I should only include the core plugins in that language file and exclude all others. Well, even though I have been 10 years with E107 I still do not know/do not remember which plugins are core and which would be a 3rd party plugin. Wouldn't it be a good idea to have a list of the core plugins from which the export of languagepacks take place, and when it hits a folder not on that list it just jumps over it and does not export it?

I think this would be a much friendlier way for new and old users who help with languagepack.
Thanks!

**Comment by CaMer0n** [comment]
@Norwayman Normally when you generate a language-pack using the "Generate" button in the admin area, it should only include the core plugins by default. Is it including third-party plugins?

**Comment by Norwayman** [comment]
Yes, if you see my pull request for languagepack you can see it and comments from developers that they should ont be there.....

**Comment by CaMer0n** [comment]
@Norwayman  Where you in debug mode when you ran "Generate"?

**Comment by Norwayman** [comment]
@CaMer0n Yes, I believe it has been in debug mode. Should I turn it off and try again?

**Comment by CaMer0n** [comment]
@Norwayman Yes, it should zip only the core themes/plugins.

**Comment by tgtje** [comment]
Oops; thanks for the trust, but i am no developer... just a contributor too. I miss a lot of skills to call me so.. ;-)   just helping to save you a lot of work (hoping in doing so)

**Comment by Norwayman** [comment]
@tgtje Well, you know a lot more than me, so for that reason I consider you at least a programmer :)

**Comment by Norwayman** [comment]
@CaMer0n Is userlanguage_flags_menu a core plugin or a third party plugin? At any rate, when debug mode is turned off the flags (PNG) come out in the export as well as the language file. It is the same as was in the pull request I made where I took away the PNGs and just left the language file. Is it OK the way it is then or do you require me to do anything else?

**Comment by CaMer0n** [comment]
@Norwayman It's not a core plugin, so there's something to fix there.

**Comment by Jimmi08** [comment]
@CaMer0n It will be something with that plugin. I tried different non core plugin and it wasn't included. GA plugin from lonalore has langs in folders (English/ Hungarian/),  but userlanguage_flags_menu has just languages/English_global.php file (not English folder).

But what I noticed,  my custom theme lang files were included in pack too.

**Comment by Jimmi08** [comment]
@CaMer0n  the reason is that plugin name contain string 'user', this test fails
![image](https://cloud.githubusercontent.com/assets/5429548/14259394/f95fdfca-faa6-11e5-86b3-46fe2bd2acfd.png)

png files are included because they have language name in their name (English.png)

But I have other problem with this plugin -  while testing this I noticed it includes .git folder. I don't see this and I suppose it shouldn't be this way.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 Yes, I suspected it was something like that. Thanks for tracking it down.

**Comment by Jimmi08** [comment]
@CaMer0n you are welcome, it's a bit my plugin, I was afraid that I messed something.

Are you able to check zip that is downloaded in plugin manager? Because my zip doesn't include .git folder, only if I downloaded it from plugin manager, this folder is there. The same with links_page plugin.

**Comment by CaMer0n** [comment]
@Norwayman @Jimmi08 Please update and give it another try. Thanks.

**Comment by Norwayman** [comment]
@CaMer0n @Jimmi08 I believe this fixed it. At least the Userlanguage_flags_meny does not come out in the export anymore :)

**Comment by CaMer0n** [comment]
Thanks @Norwayman I'll close this, but feel free to open it if it occurs again with a plugin/theme etc.
