### ISSUE TITLE
Extended User Fields - Manage problem

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1483]
Hi, last changes work, i can create a Custum Field now.. but the 'required' field cannot be changed it stays on 'No - Will not show on signup page' .. 

Also when using a newly created Custum Field it does not save content into the DB trying to use it in Update user settings.. (text field plain simple) 

Github of today..

**Comment by CaMer0n** [comment]
@Alex-e107nl Thank you! Please give this a try.

**Comment by Alex-e107nl** [comment]
No Thank you!! It works!! Both problems solved..
