### ISSUE TITLE
Private Message - user not found

### ISSUE THREAD

**Issue by realG** [e107inc/e107#1485]
Hi, is anyone else having issues with private messages? When I try to send one as a standard user, I get a User not found message.

![image](https://cloud.githubusercontent.com/assets/1708326/14232823/569bd526-f9ae-11e5-8ac0-1462255a0cc6.png)

However, when I log in as admin, I can send a message to that user, and he can reply to it, that all works. This is on the latest git code. I see there were a few PM related commits recently, has something changed that could have caused this?

Also, as admin, I see this under the user drop-down:
![image](https://cloud.githubusercontent.com/assets/1708326/14232826/80d38d52-f9ae-11e5-9ea5-a3256b210993.png)

user_ban != 1 ... Is that supposed to be there?

**Comment by CaMer0n** [comment]
thanks @realG Yes, still working on it to get it cleaned up to v2.x standards.
