### ISSUE TITLE
Issue with Page editing in Version 2 Bootstrap

### ISSUE THREAD

**Issue by surfer45** [e107inc/e107#1490]
I recently upgraded our groups site with the new version. When going to create a page or edit an existing one, the full WYSIWYG tool bar is not visible.  Even though it has been activated in preferences. Only one visible is the html coding bar which does not allow proper formatting of the page. When first installed and I used the default theme, all worked perfectly.  However when I changed themes, it disappeared.  All previous themes have the same problem.  When I revert back to bootstrap one, all appeared again.  I have been told that it may be a JavaScript problem, but being new to this area, not sure how or what to do to fix.  Young people within our group are the ones undertaking editing of the site and they are also confused as to what to do. I only experienced this problem with I upgraded from an existing installation.  I even installed a fresh installation, but same problem. Are previous themes compatible and if not what would I have to do to make this work.  Any help appreciated. Here are couple of screen shots.  1 with the default theme that shows editor. Other one is using another theme and editor no longer available.
![screen 1](https://cloud.githubusercontent.com/assets/18274349/14268907/d60bdd6c-fb1e-11e5-8d3c-27f001f672dd.jpg)
![screen 2](https://cloud.githubusercontent.com/assets/18274349/14268917/e3075cc6-fb1e-11e5-8c48-89137db4777b.jpg)

**Comment by CaMer0n** [comment]
@surfer45 I'll be happy to take a look at that issue. Please meet me here: https://gitter.im/e107inc/e107
