### ISSUE TITLE
Banner plugin href not returning link...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1492]
The banner plugin renderer banner href is not returning the database stored banner url, instead it returns a link to the banner.php, ie: `<a target="_blank" data-original-title="" class="e-tip" href="/site_spt/banner.php?4" rel="external">`

**Comment by Moc** [comment]
I'm pretty sure that this is normal. It should automatically redirect you to the link which is stored in the database afterwards. 

Doesn't this happen? What page do you see?

**Comment by rica-carv** [comment]
My first tests showed me a blank page.
Now it seems to redirect correctly...
