### ISSUE TITLE
Plugin Tiny MCE lists problem a.o.

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1494]
Hi,
after testing there's a problem wilt tiny mce and some plugins, when you select a text and try to switch it to a list with bullets the whole text gets selected resulting in one bullet..
Selecting one line of text and try to use Formats Headings, whole text is a heading..
Blockquote same issue, you can select a line of text but the whole text gets it... 

Inline changes like BOLD etc do work normal.. Cannot tell sinds when this isnt working anymore but its a problem when you really want to use Tiny..

Github of today..

Alex

**Comment by CaMer0n** [comment]
If the selected text doesn't have full line-breaks, then it will result in a single bullet. Were these "problem plugins" using bbcodes prior?

**Comment by Alex-e107nl** [comment]
Not that i know Cameron, it's a test, new e107 installation new user coming from WIX ..  full line-breaks does the trick thx!
