### ISSUE TITLE
[Bug] Newsfeed plugin, custom image path

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1495]
I´m not sure 100% if Im missing somethink, but when you try to use a full path to the image directory, it doesnt shows up, the cause is that the plugin is saving the path with some numbers at the end, example:

http://localhost/images/partners/logo.jpg::4::4

So, in the img tag it adds "http://localhost/images/partners/logo.jpg::4::4" at the src param, including those numbers.

I tried deleting them manually from db, but then the plugin adds ::0::0 at the end.

Ive not looked into what those numbers do in code, but presumably they are referencing the number of rss items to load on menu and on main page (IDK why its defined on the image col, in order of on a separated one)

Grts,
- Nes

**Comment by willem010** [comment]
sounds like #1035.
we needed a full server reinstall to solve it.
