### ISSUE TITLE
PAGE_NAME, e_PAGETITLE - not able to use them in theme.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1497]
PAGE_NAME and e_PAGETITLE are global constants/variables.  Before I was able to use them in theme.php, now it's not possible. 
 
I tried both this way:
![image](https://cloud.githubusercontent.com/assets/5429548/14313273/e0a0e268-fbf0-11e5-88c7-a965fcc6c522.png)

How I can display these values in theme.php?
I understand that e_PAGETITLE is for title tag in header, it works. 
I tested that I can use PAGE_NAME in template and it works, but not e_PAGETITLE.
This is not caption field, so I can't use table_render() functionality.

So is this normal behaviour? If yes, is this correct way how to do this -  to create theme shortcode and render template with PAGE_NAME inside it?

Thanks 
(I included e_PAGETITLE  because f.e. new page system works with e_PAGETITLE, not with PAGE_NAME)

**Comment by Jimmi08** [comment]
Solved by using theme shortcode and return PAGE_NAME value. I can't use template (or didn't know what) because it needs to works for all pages.

**Comment by Jimmi08** [comment]
PAGE_NAME is not defined for login page (login.php). I mean in lan file...

**Comment by CaMer0n** [comment]
We no longer put "PAGE_NAME" inside language files. (if you load many language files, they will conflict)  However, PAGE_NAME can be defined inside the script, and point to an existing LAN.

**Comment by Jimmi08** [comment]
Correct. If I find page without defined PAGE_NAME (not in lang file) I will create separate issue. Now it's enough. For me solved.
