### ISSUE TITLE
request - Template file version 

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1500]
I think all template files (plugins included) need to have a version number, in this way it is more easy to check if you have latest template version copy in your theme. Custom changes in template files make even harder to check if you use latest template copy or not.

**Comment by Moc** [comment]
I agree, it needs to be very easy to compare the changes between template versions in order to support theme developers and to smooth out customization issues.

**Comment by CaMer0n** [comment]
Indeed, but remembering to change it each time could be a problem. Have you tried using diff?

**Comment by mcpeace-maw** [comment]
Diff I use right now, but you need to take in consideration the number of the template files in each theme and the number of the themes that I need to check time to time and when we speak of dozens (and the number is growing, if everything is OK for me) that means very long time to check. So the only solution that would ease my check, I think, is whether the template files have version.

**Comment by Moc** [comment]
Maybe we could provide specific links to the diffs in the changelog when changing templates. I agree with @mcpeace-maw that for theme authors these changes are really important. 

Something like this: https://github.com/e107inc/e107/compare/v2.1...v2.1.1 but maybe a way to specifically mention templates.

**Comment by mcpeace-maw** [comment]
I think I have a solution that I have not thought before. Here on E107 git, if you view files in a folder, on the last column is mentioned last change. This is all I need, thanks.
