### ISSUE TITLE
Login-System

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1501]
The login system is a disaster. If two administrators simultaneously in the admin area and stores a bit, the other will be logged out directly. It does not matter whether a news, a language file, or anything else is done. In v2.1 it was tolerable, but now with v2.1.1 is again extremely annoying. Could it help to switch from cookies to session?

**Comment by LaocheXe** [comment]
I've notice this - I was logged in with my account on the PC, then logged in with the same account on my smart phone - ended up getting logged out on my smart phone when I was trying to sync the site to github.

**Comment by CaMer0n** [comment]
Same account vs 2 different admins is a different scenario. Try switching to sessions @TrueHatori . I believe a LOT of your problems are to do with your host.

**Comment by TrueHatori** [comment]
In v1.0.4 it has functioned, not now. Change to Session has not helped. Not two Accounts ... two Admins, I and the radio operator - 450 km from me.

**Comment by Moc** [comment]
There have been various improvements to session handling. Please visit us in the Gitter chatroom to walk through the debug process if you are still experiencing this issue.
