### ISSUE TITLE
New Enhancement: News Grid Menu (Beta)

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#1512]
Adds a grid of the latest news items to your website. 

## End Result: 
![news_grid_menu_1](https://cloud.githubusercontent.com/assets/2825679/14406946/a8fb4920-fe6b-11e5-8b09-ed86f1069b54.png)

## Added to the theme layout via the Menu-Manager:  
![news_grid_menu_2](https://cloud.githubusercontent.com/assets/2825679/14406947/a8fd2f6a-fe6b-11e5-91c7-d5f491479637.png)

## Configuring the News Grid Menu in the Menu Manager: 
![news_grid_menu_3](https://cloud.githubusercontent.com/assets/2825679/14406948/a8ff3490-fe6b-11e5-881f-1a12b62d52be.png)

Leave the caption blank to skip using tablestyle(). 

@Todo: LANs in e_menu.php

**Comment by Alex-e107nl** [comment]
Hi Cameron, very nice feature again... one little thing, i cannot change the layout.. does it has something to do with line 54 in e_menu.php (plugin news) 
`$fields['layout']       = array('title'=> "Layout", 'type'=>'method', 'writeParms'=>'');` ?

**Comment by Alex-e107nl** [comment]
Cameron, this change:
```
$text .= "<tr><td>".$this->radio('layout', $k, $curVal, array('label'=>$k))."</td><td>".str_replace('{STYLE}',"class='alert alert-info' style='margin-bottom:0;text-align:center' ",$v)."</td></tr>";
+			$text .= "<tr><td>".$this->radio('layout', $k, ($curVal == $k), array('label'=>$k)."</td><td>".str_replace('{STYLE}',"class='alert alert-info' style='margin-bottom:0;text-align:center' ",$v)."</td></tr>";
```

gives this error :

```
Configure parameters

Parse error: syntax error, unexpected ';' in e107_plugins/news/e_menu.php on line 109
```

**Comment by CaMer0n** [comment]
@Alex-e107nl Thank you!

**Comment by CaMer0n** [comment]
### "Source" option added in Menu Manager: 

![gridsource](https://cloud.githubusercontent.com/assets/2825679/14547215/46dcce0a-0260-11e6-878e-ccbed80f8638.png)


### Assigning the new item: 

![newsgrid_assigned_template](https://cloud.githubusercontent.com/assets/2825679/14547095/3e0c2c18-025f-11e6-86e2-b4ac6cc55d95.png)

**Comment by rica-carv** [comment]
@CaMer0n Good job, but this for me has a few drawbacks:

- Missing pagination (or i'm missing something...)
- Needs a extra menu area. Anyhow, how can it be setup to have news grid on the frontpage, like the option to have the news at the frontpage at the admin ui?

Anyway, i've "created" a little mock up to recreate a news grid system, in custom news_template.php, inside my theme:
```
// Grid Menu
//  DOESN'T WORK BECAUSE DIV IS CREATED INSIDE NEWS SUMMARY SHORTCODE
//  $SC_WRAPPER['NEWS_SUMMARY'] = '{---}...';
$NEWS_TEMPLATE['list']['caption']	= ' ';
$NEWS_TEMPLATE['list']['start']    = '<div class="container-fluid"><div class="row">';
$NEWS_TEMPLATE['list']['item']		= '<div class="{NEWSGRID} col-sm-4">
												{NEWS_TITLE: link=1}<p>{SETIMAGE:w=250&h=250}{NEWSTHUMBNAIL}
              									<p>{NEWS_SUMMARY: limit=250}                               
            							   </div>';
$NEWS_TEMPLATE['list']['end']      = '</div></div>';
```
After simply use the list instead of default (which by the way doesn't use ['default']['start'] & ['default']['end']...)
It's kind of crude, but it works (with some persky bugs, which i'm trying to solve)....

**Comment by CaMer0n** [comment]
@rica-carv It's not meant to have pagination, anymore than "latest news menu" is meant to have it. 
The bootstrap home template has space to add the menu. It could also be hard-coded in the theme template if required.

**Comment by rica-carv** [comment]
@CaMer0n I know it's not meant to have pagination, since it's a menu, but if i want a similar thing o the news page itself, i can't....

Therefore, i'm trying another approach: make a similar thing for news as currently is at the bootstrap3 admin ui home page....

**Comment by CaMer0n** [comment]
@rica-carv Using the 'list' template as you have done is the right way to go about it. 
Here's what I have used in the past to have a thumbnail view of the news.  

    $NEWS_TEMPLATE['list']['caption']	= '{NEWSCATEGORY}';
    $NEWS_TEMPLATE['list']['start']	= '{SETIMAGE: w=400&h=350}';
    $NEWS_TEMPLATE['list']['end']	= '';
    $NEWS_TEMPLATE['list']['item']	= '

		<div class="row">
				<div class="span3 col-md-3">
                   <div class="thumbnail news-list-thumbnail">
                        {NEWSTHUMBNAIL=placeholder}
                    </div>
				</div>
				<div class="span9 col-md-9">
                   <h3 class="media-heading">{NEWSTITLELINK}</h3>
                      <p>
                       	{NEWSSUMMARY}
					</p>
                    
 				</div>
		</div>

    ';

**Comment by rica-carv** [comment]
@CaMer0n With that, you get a list view, with thumbnails on the left side:
```
[THUMBNAIL] [LINK + SUMMARY]
[THUMBNAIL] [LINK + SUMMARY]
[THUMBNAIL] [LINK + SUMMARY]
[THUMBNAIL] [LINK + SUMMARY]
```

What i'm trying to achieve is a "grid" view, with thumbnails of diferent news side by side, just like the admin ui main page:
```
[   THUMBNAIL  ]       [   THUMBNAIL  ]       [   THUMBNAIL  ]       [   THUMBNAIL  ]
[LINK + SUMMARY]       [LINK + SUMMARY]       [LINK + SUMMARY]       [LINK + SUMMARY]
```

**Comment by CaMer0n** [comment]
Sorry, you're right.  You can do that easily with bootstrap or use the grid template.  (replacing the shortcodes)

**Comment by rica-carv** [comment]
@CaMer0n That's what i already did:
```
// Grid Menu
$NEWS_TEMPLATE['list']['caption']   = ' ';
$NEWS_TEMPLATE['list']['start']    = '<div class="container-fluid"><div class="row">';
$NEWS_TEMPLATE['list']['item']      = '<div class="{NEWSGRID} col-sm-4">
                                                {NEWS_TITLE: link=1}<p>{SETIMAGE:w=250&h=250}{NEWSTHUMBNAIL}
                                                <p>{NEWS_SUMMARY: limit=250}                               
                                           </div>';
$NEWS_TEMPLATE['list']['end']      = '</div></div>';
```

The issue is that the news blocks can be different heights, and sometimes the blocks doesn't align horizontally correct on the grid row....
