### ISSUE TITLE
hardcoded/not translated string in e107_admin/users.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1513]
Is this hardcoded string? Or how I can translate it?

![image](https://cloud.githubusercontent.com/assets/5429548/14408662/57850cd2-fefe-11e5-89f4-664523bf5cc0.png)

`$caption = $tp->lanVars('Resend account activation email to unactivated users.',$count);`

**Comment by Jimmi08** [comment]
Next:

`<div class='form-inline'>Older than ".$frm->select('resendAge', $age, 24).$frm->checkbox('resetPasswords',1,false,'Reset all passwords').`

Existing strings:
`define("LAN_SEARCH_35", "Older than");`

**Comment by Moc** [comment]
As for your first question. Yes, it can be easily replaced

```php
define("LAN_WHATEVER", "Resend account activation email to [x] unactivated users"); 
$tp->lanVars(LAN_WHATEVER, $count); 

// value of $count will replace [x]
```

**Comment by tgtje** [comment]
Just a remark :(think outside box) dirty quick method (of course be aware) is adding a word to sentence. if it _displays_ after saving : probably textbased use... Not what normally would be the way, but its simple and after some testing its soon found out (**how** to replace by code and lan's **and if** it is a real **candidate**..thats another story.)

**Comment by Jimmi08** [comment]
@Moc 
It's core file, I can't replace that line.  Or you are trying to say this:
`define('Resend account activation email to unactivated users.', 'translated string');
`

**Comment by tgtje** [comment]
If  i may : 
`		);

		$count = $sql->count('user','(*)',"user_ban = 2 ");
		$caption = $tp->lanVars(LAN_WHATEVER,$count);

		$text = $frm->open('userMaintenance','post');

	
		<tr><td>".$caption."<td>
		<td>
		<div class='form-inline'>Older than ".$frm->select('resendAge', $age, 24).$frm->checkbox('resetPasswords',1,false,LAN_WHATEVER_2).
		" <div class='input-group'>".$frm->userclass('resendClass',false, null )."<span class='input-group-btn'>".
		$frm->button('resendToAll', 1, 'warning', LAN_GO)."
    
    
    ---------------------------------------------------------------------------------
    
   IN  language file (language English/admin/lan_admin > most likely guess)
    
    define("LAN_WHATEVER", "Resend account activation email to [x] unactivated users"); 
    define("LAN_WHATEVER_2", "Reset all passwords"); 
`
``

**Comment by Jimmi08** [comment]
@tgtje of cource you may.  :)
I understand if you build your plugin or shorcodes or something. But I don't understand how this can help to translate string that hardcoded in core files. f.e. users.php.  With your solution you have there still Older than hardcoded... 
How I can translate this:
![image](https://cloud.githubusercontent.com/assets/5429548/14410527/524801b4-ff32-11e5-9cd3-5a47584293fc.png)

**Comment by tgtje** [comment]
Older than is ALSO a candidate for a lan..; 
(will post back/testing)

**Comment by CaMer0n** [comment]
I'll be marking all of these as duplicates of #6. Pull-requests should be made for simple LAN issues.

**Comment by Moc** [comment]
@Jimmi08 No I mean exactly what I said haha. 
It's a hardcoded string which needs be put into a language file. Then, as @tgtje explained, the  $tp->lanVars() method will take care of replacing the [x].
