### ISSUE TITLE
hardcoded/not translated string in e107_admin/prefs.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1515]
Result:
![image](https://cloud.githubusercontent.com/assets/5429548/14409761/b7bb683a-ff1c-11e5-83e6-9bc5c8b5e68e.png)

Reason:
`e107::getNav()->admin("Basic ".LAN_OPTIONS.'--id--prev_nav', 'core-prefs-main', $var);`

**Comment by CaMer0n** [comment]
@Jimmi08 Pull Request :-)

**Comment by CaMer0n** [comment]
I'll be marking all of these as duplicates of #6. Pull-requests should be made for simple LAN issues.
