### ISSUE TITLE
Bug? Main Admin Login Failure

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1518]
So I set up a new site a few days ago and the main account was just fine. Well the other night the guy who owns that account went in and added them self's to all the admin privileges which they already have as main admin... He got on today and couldn't login, even re-generate his password from other admins a few times. I got on and notice he had all the privileges checked and was main admin. So I unchecked them, re-generate a password and gave it to him, he can get in now... I don't know if this is a bug or not, but I was able to reset the main account password and even remove his admin privileges in the Admin Area - Users

**Comment by CaMer0n** [comment]
Sound like he accidentally overwrote the password while modifying privileges. (no doubt due to browser auto-complete)
