### ISSUE TITLE
SEF with Forum Sub-Sub-Forum

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1519]
So I created a parent, then a forum, then a sub-forum, and then a sub-sub-forum inside the sub-forum. When I go to view it I click on the sub-forum and get sent back to the starting point.

So I go to Unit Training -> Training Schedules (Sub-forum) and get sent back to the forum index.

So I go to Training Schedules (Sub-forum) -> Basic Combat Training (sub-sub-forum) then I get sent back to the forum index.

**Comment by LaocheXe** [comment]
Found the issue - Using the URL config stuff, When going to the forum - the url is different than looking at the index.

So going into Unit Training's the link to the sub-forum is http://3rdcavregiment.com/forum/forum/view?forum_id=14&forum_name=BCT&forum_description=Basic%20Combat%20Training&forum_parent=8&forum_sub=9&forum_datestamp=0&forum_moderators=254&forum_threads=0&forum_replies=0&forum_lastpost_user=0&forum_lastpost_user_anon=&forum_lastpost_info=&forum_class=4&forum_order=702&forum_postclass=4&forum_threadclass=4&forum_options=&forum_sef=basic-combat-training&user_name

when it should be http://3rdcavregiment.com/forum/basic-combat-training  (got this link from the forum index)

**Comment by CaMer0n** [comment]
Thanks @LaocheXe If you do the same thing with v1.x - what is the URL ?

**Comment by LaocheXe** [comment]
This is version 2.x new install, no upgrade

**Comment by Moc** [comment]
@CaMer0n It's just the same link as a subforum with its ID, e.g. `/e107_plugins/forum/forum_viewforum.php?100`

**Comment by LaocheXe** [comment]
I also notice (but im sure you already know) that sub-forums don't use the friendly url's.(SEF URL)

**Comment by SimSync** [comment]
@LaocheXe Is this issue still an issue?
In my tests, it worked like expected, both with sef and legacy urls...

**Comment by Moc** [comment]
This seems to work fine here as well. Closing as I assume it's all fixed.
