### ISSUE TITLE
Download plugin enhancement

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1520]
When updating date on download core plugin, it displays erroneous date on the frontend:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14430046/e01db4dc-fff7-11e5-966b-25d5614689ab.jpg)

...and if i'm allowed a suggestion, why not "force" the bottom two options to **NO ONE (INACTIVE)** when status is set to **INACTIVE**, on submitting changes, even if user forget to manually change it???
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/14430201/82cdfbce-fff8-11e5-8a07-916a67a0ce7d.jpg)

**Comment by Moc** [comment]
Is this issue still occurring?

**Comment by Moc** [comment]
@rica-carv Is this issue still occurring?

**Comment by rica-carv** [comment]
@Moc No, teh date issue is solved, despite the second part of my question still persists...

**Comment by Moc** [comment]
Changes title and labelling for features request. Thanks for the update.

**Comment by Jimmi08** [comment]
This is correct behavior. You dont want to change your access settings if you set it inactive. It can be from some temp reason.  What should be checked is this settings is used everywhere for checking access. Mainly in e_ addons files. This should be closed.
