### ISSUE TITLE
prettyPhoto.js -  always loaded?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1521]
I noticed that prettyPhoto.js are loaded on each page, not only on gallery

![image](https://cloud.githubusercontent.com/assets/5429548/14433343/3da3c860-000e-11e6-998e-a7c497a946df.png)

Maybe I missed how to turn off in administration. 

Thanks

**Comment by lonalore** [comment]
Do you use v2.1.1 files? Or the latest github files?
If you update files to latest github version, you should see this: https://github.com/e107inc/e107/pull/1469#issuecomment-203409500
Just disable "Load prettyPhoto globally".

**Comment by Jimmi08** [comment]
Thanks, I was sure that I missed something. I checked media manager for new prefs, not gallery plugin.  Solved.

**Comment by CaMer0n** [comment]
@lonalore This should be disabled by default on upgrade. Currently it is enabled from what I can tell.

**Comment by CaMer0n** [comment]
@lonalore Thank you!
