### ISSUE TITLE
"Unauthorized access!" when trying to enable scheduled task

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1523]
Trying to enable a scheduled task (such as send a test email to x) returns a blank screen with "Unauthorized access!"

Logged in as Main Admin.

**Comment by CaMer0n** [comment]
Add this to your e107_config.php file: 
`define('e_SECURITY_LEVEL', 0);`

**Comment by Moc** [comment]
Please also check your PHP session.save path settings, and make sure that this folder is writable. This is very important and may resolve many of your issues.

**Comment by Brooniee** [comment]
@Moc thanks, ive checked session path is fine and writable, i'm seeing files there created by the host's user.

**Comment by Moc** [comment]
This issue is likely fixed in the latest release. Closing for now. If you are still experiencing the issue, then please visit us in the Gitter Chatroom to have the issue debugged.
