### ISSUE TITLE
Scheduled tasks do not appear to run

### ISSUE THREAD

**Issue by brwnie** [e107inc/e107#1534]
I added the required path to crontab, under the user that runs the site. This is set to run every minute as required.

e.g.
/home/xxx/public_html/cron.php token=xxx >/dev/null 2>&1

However this does not appear to run, with:
Status: Disabled
Active Crons: 3
Last cron refresh: Never

Even if I try to run the cron manually under the webuser, this does not produce any output (after removing >/dev/null 2>&1)

**Comment by Moc** [comment]
Is this issue still occurring?

**Comment by Moc** [comment]
Closing due to lack of feedback. Let us know if this is still an issue and I'll re-open.
