### ISSUE TITLE
Custom plugin template inside another plugin?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1536]
Hi

Is there any way that a plugin can have (and make it usable) a custom template for another plugin?
Like themes do?

For instance, imagine i have a plugin, that manages users, and Ii want to customize the core login form from that specific plugin, is it possible???

**Comment by CaMer0n** [comment]
You cannot modify the template directly, but this doesn't prevent you from applying javascript and css for that page. It really depends on what you have in mind.

**Comment by rica-carv** [comment]
Humm...

**Comment by Jimmi08** [comment]
@rica-carv  did you get my email?

By the way, there is some ways how to do this.  You can customize login template under theme and use it under your plugin. You can create your own login template for your plugin (as plugin template, not login template).

**Comment by rica-carv** [comment]
@Jimmy Yes, i did, but i haven't replyed yet...
My ideia was to customize a plugin template inside another plugin, without have to rely on the theme....

**Comment by Moc** [comment]
Is this issue still relevant?

**Comment by Moc** [comment]
Closing due to lack of feedback. Feel free to submit new information and I'll re-open.

**Comment by Jimmi08** [comment]
@Moc I think that there is duplicate issue by me, something about how to replace this from old code.  Discussion continued there.

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/3195
