### ISSUE TITLE
Custom menu template in themes?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1537]
Is it possible to have custom menu templates inside a theme, like it's donne for plugin templates???

**Comment by Jimmi08** [comment]
Do you mean menu template? If it's core template, just copy it theme/templates folder.

**Comment by rica-carv** [comment]
@Jimmi08 It's not that easy, since some core menus doesn't have templates: [search_menu](https://github.com/e107inc/e107/tree/master/e107_plugins/search_menu), [blogcalendar_menu](https://github.com/e107inc/e107/tree/master/e107_plugins/blogcalendar_menu).
Meanwhile, others do have: [rss_menu](https://github.com/e107inc/e107/tree/master/e107_plugins/rss_menu), [comment_menu](https://github.com/e107inc/e107/tree/master/e107_plugins/comment_menu), [login_menu](https://github.com/e107inc/e107/tree/master/e107_plugins/login_menu), and if their template is present in a theme, it will de loaded instead of the one in the plugin itself.

**Comment by Moc** [comment]
- As for those without a template, no it's not possible at this time but once they are prioritized for a rewrite a template will likely be made

- As for those that do have a template, yes you should be able to override core templates the normal way. If this does not work, then this is a bug. 
For example for the login menu, copying the `login_menu_template.php` file into `e107_themes/your_theme/templates/login_menu/` should override the template.

**Comment by Jimmi08** [comment]
Could you explain to me what do you consider as custom menus? I supposed that they are menus you can call by CMENU shortcode and they have their own template.
Otherwise they are plugins menus. Am I wrong?

**Comment by rica-carv** [comment]
@Jimmi08 _Custom_ menu templates.... Moc already clarified it a bit, so i'm up to some testing....

**Comment by rica-carv** [comment]
One of the ideias to have a specific menu inside a theme is to make this change on the forum area:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14983748/01abd692-1137-11e6-9ca3-1ebba240f829.jpg)

Or it's bad idea, and just create a menu inside a plugin???

**Comment by Jimmi08** [comment]
@Moc this could  be closed

There should be issue about adding menu to theme somewhere - like theme menus...  I asked for this long time ago. If it is not, it would be because I got answer on gitter that it is not possible...
