### ISSUE TITLE
how to correct way replace old classes from v 1.0.4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1539]
This code from old plugin still works but it has different result in version 2
`$TOPIC_FIELD = r_userclass("content_class",$row['content_class'], "CLASSES");`

After some testing it looks to me that correct way how to replace this is:

`$TOPIC_FIELD = r_userclass("content_class",$row['content_class'], "off", "public,new,guest,nobody,member,admin,readonly,classes");`

You can see screenshots here: https://github.com/Jimmi08/content/issues/11

Am I right?

**Comment by CaMer0n** [comment]
This is a bug.

**Comment by Jimmi08** [comment]
@CaMer0n Thank you, so I replaced it correct way to have the same values.
