### ISSUE TITLE
PHP errors in the Download plugin

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1541]
at the bottom of /e107_plugins/download/admin_download.php?mode=cat&action=list I get a lot of PHP errors :

Warning strlen() expects parameter 1 to be string, array given, Line 1530 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning strpos() expects parameter 1 to be string, array given, Line 1530 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning preg_split() expects parameter 2 to be string, array given, Line 1702 of /home/polyamou/www/e107_handlers/e_parse_class.php
Warning Invalid argument supplied for foreach(), Line 1703 of /home/polyamou/www/e107_handlers/e_parse_class.php
[...the same 4 errors displayed many times...]

**Comment by Moc** [comment]
Are these errors still occurring using the latest files?

**Comment by pierre0042** [comment]
I don't see this errors anymore but I have some others :


Deprecated mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead, Line 227 of /home/polyamou/www/e107_handlers/mysql_class.php
--
Notice Use of undefined constant LAN_dl_77 - assumed 'LAN_dl_77', Line 44 of /home/polyamou/www/e107_plugins/download/templates/download_template.php
Notice Use of undefined constant LAN_dl_72 - assumed 'LAN_dl_72', Line 306 of /home/polyamou/www/e107_plugins/download/templates/download_template.php
Notice Use of undefined constant LAN_dl_68 - assumed 'LAN_dl_68', Line 309 of /home/polyamou/www/e107_plugins/download/templates/download_template.php
Notice Use of undefined constant LAN_dl_77 - assumed 'LAN_dl_77', Line 367 of /home/polyamou/www/e107_plugins/download/templates/download_template.php
Notice Use of undefined constant LAN_dl_68 - assumed 'LAN_dl_68', Line 625 of /home/polyamou/www/e107_plugins/download/templates/download_template.php
Notice Undefined index: _depth, Line 190 of /home/polyamou/www/e107_plugins/download/includes/admin.php
Notice Undefined index: _depth, Line 190 of /home/polyamou/www/e107_plugins/download/includes/admin.php
Notice Undefined index: _depth, Line 190 of /home/polyamou/www/e107_plugins/download/includes/admin.php
[...]
