### ISSUE TITLE
Open pdf file in custompage

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1547]
When I insert embed or object html text into the texteditor (I'm using the BBcode editor and not TinyMCE/wysiwyg and I'm using the [html] tags) the editor delete the codes.

**Comment by CaMer0n** [comment]
@fizi Which html tags are you using? Have you checked Prefs> Rendering permissions?

**Comment by fizi** [comment]
Yes, I set the pref and I tried <embed> and <object> codes. The editor delete it.

**Comment by CaMer0n** [comment]
@fizi Could you please share the full code so that I can test with it? Thanks

**Comment by fizi** [comment]
Only one example: `<embed src= “MyHome.pdf” width= “500” height= “375”>`

**Comment by CaMer0n** [comment]
@fizi Please update and test again. Thank you.

**Comment by fizi** [comment]
I updated and tested with embed code. I insert the embed code, updated the custom page, after this I reopen, and editor again delete the code (code not in the textbox.

**Comment by CaMer0n** [comment]
@fizi Thanks. Could you please paste the full code of the embed? The one above appears to be incomplete. Thanks.

**Comment by CaMer0n** [comment]
@fizi Please update again and make sure your embed tag has a closing tag. ie. `/>`
`<embed src= “MyHome.pdf” width= “500” height= “375” />`

**Comment by fizi** [comment]
Embed and object work, ok. Now the editor don't delete it. Thanks!
I tried with script (jwplayer) and work with it. Player appears normally.
Thanks!

**Comment by CaMer0n** [comment]
Excellent! :+1:  Happy to hear it!
