### ISSUE TITLE
signup shortcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1556]
I noticed that signup shorcodes (input fields) use e107::getForm()->text()  and with comparing login shorcodes I am curios if using complex function (to much ifs) is not too complicated for so simple input fields (site performance)

Why this change? Will login shortcodes be rewritten the same way?  

My question is related with this pull request:
https://github.com/e107inc/e107/pull/1555

Only one missing param and login input fields work as should they have.

But signup shortcodes don't have parms, so I can't add new option class for form field and  I can't rid feeling that simple thing is doing by complicated way. 

Maybe a little explanation will help. 

Thanks

**Comment by CaMer0n** [comment]
Using the form-handler has many advantages, but mainly consistent markup. Also, if we need to add anything in future for bootstrap 4 etc.. it's a simple change to the form handler and not hundreds of files.
