### ISSUE TITLE
Gallery fatal error

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1558]
I updated with latest Github. The gallery worked right, but now I got fatal error:
Fatal error: Call to a member function parseTemplate() on null in /web/.../.../.../e107_plugins/gallery/gallery.php on line 81

**Comment by Jimmi08** [comment]
I see problem, it's my change caused this but why I haven't this issue...
change $tp to e107::getRender()  on line 81 and line 122

I have debug mode on, no errors...

**Comment by Jimmi08** [comment]
I am sorry for this...

**Comment by fizi** [comment]
Now ok.
