### ISSUE TITLE
Error in the comment display

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1559]
When I unlocked a comment, it is neither the Avatar to see, yet the number of comments is changed, it remains at zero. To see this is:
http://www.dragonland-radio.de/news.php?extend.29

e107 Version 2.1.1
PHP-Version 5.3.10-1ubuntu3.21

MySQL 5.5.47-0ubuntu0.12.04.1

**Comment by TrueHatori** [comment]
Can anyone please take a look at this problem? The avatar isn't important, but the number of comments should be displayed correctly.

**Comment by pierre0042** [comment]
Probably duplicate of #1422

**Comment by Moc** [comment]
Please be patient. There are only very few people working on e107 at the moment (Cameron mainly) so issues need to be prioritised. 

Thank you.

**Comment by Moc** [comment]
I am assuming this issue is fixed in the latest version. If not, please let us know and I'll re-open.
