### ISSUE TITLE
Preferences are empty

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1563]
Many Preferences are empty screen
![image](https://cloud.githubusercontent.com/assets/1758577/14675046/5041c882-0707-11e6-9904-3b43f3456963.png)

all yellow marked are empty screen
Version 2.1.2 (git) 

thx René

**Comment by CaMer0n** [comment]
@schlrech This looks like a javascript issue. Any third-party plugins in use?

**Comment by schlrech** [comment]
no, i have no third party plugin, only my own event manager without any javascript
![image](https://cloud.githubusercontent.com/assets/1758577/14686532/6baaea36-0739-11e6-8106-cad510a90b71.png)

**Comment by rica-carv** [comment]
What's that "Umfrage" plugin????

**Comment by schlrech** [comment]
Thats the Poll

**Comment by schlrech** [comment]
with the debu i see this warnings
![image](https://cloud.githubusercontent.com/assets/1758577/14698564/6188e268-0790-11e6-8f54-4dd1d2341c71.png)

**Comment by CaMer0n** [comment]
Thanks @schlrech These warnings are unrelated. Are you able to view your javascript error console in your browser?

**Comment by schlrech** [comment]
This one?
![image](https://cloud.githubusercontent.com/assets/1758577/14719604/75a0eec2-07fd-11e6-9b9c-3e8711c0115f.png)

**Comment by CaMer0n** [comment]
@schlrech I'm happy to troubleshoot it with you if you have time. https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
Traced problem to custom language file.
