### ISSUE TITLE
Bug: Edit Forum Post

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1564]
Issue: Editing a forum post made by another user.

Error
You are not authorized to post to this forum.

User Group to moderate forums is main admin (was Admin and Mods but changed to see if main admin can edit post).

This is happening in one forum area, the forum post can be moved to another forum and then can be edited from there. I am using the survey plugin which is to post the form a user fills out and submits.  https://github.com/septor/survey

System Debug
Attempting to Load: e107_plugins/forum/languages/English/English_front.php
Using Permlist cache: False

Array
(
    [action] => edit
)

e_URL in forum with key: post matched ^forum/post/? and included: e107_plugins/forum/forum_post.php with $_GET:

Array
(
    [f] => edit
    [id] => 36
    [post] => 43
)

**Comment by Moc** [comment]
Is this still an issue?

**Comment by Moc** [comment]
Closing this due to the lack of feedback. If it's still an issue, I'm assuming it will be fixed if this issue is fixed as well: https://github.com/e107inc/e107/issues/3525
