### ISSUE TITLE
Bug: Forums BBCode

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1565]
Currently only admin have the full bbcode table while normal users have a less than normal bbcode table.

Normal Users
![normaluser](https://cloud.githubusercontent.com/assets/5818022/14695687/1487b99a-073a-11e6-8bd5-db9de3e09792.png)

Admin Users
![adminuser](https://cloud.githubusercontent.com/assets/5818022/14695693/1e82325e-073a-11e6-9e3e-3c6c9ec0d1d4.png)

Notice the difference, is this a bug or a config issue that is somewhere in the admin to change?

**Comment by lonalore** [comment]
Set **"Class which can post HTML"** to **"Members"**. You can find this pref here: 
Admin -> Settings -> Preferences -> Security and Protection

**Comment by LaocheXe** [comment]
That is in Text Rendering now - no wonder I couldn't find it.
