### ISSUE TITLE
Language: Welcome message (cache bug)?

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1566]
Having Welcome message in multiple languages.
When switching the content should take over the language used as created.
Different scenarios tested; when Content Cache is ACTIVE welcome message refuses to display the language of choice. If content cache is disabled, all works as should.

**Comment by Moc** [comment]
Is this still an issue?

**Comment by tgtje** [comment]
Yes, as long as i do not switch my prefered language (aka sitelanguage) It Always seems to take the latter, cache setting on or off no diff.

**Comment by Moc** [comment]
How do you set the welcome message in different languages? The multilan plugin?

**Comment by tgtje** [comment]
Seems to be working (probably fixed by other issue related product) (hence ...date).
Closing this.
