### ISSUE TITLE
Mail Bounce Check --> clears my own mailbox

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1569]
if i run the "Mail Bounce Check" in sheduled Tasks then after my own mailbox are cleared, why?

before:
![image](https://cloud.githubusercontent.com/assets/1758577/14745652/9133d0f0-08ac-11e6-9fe8-ae7d5cb92207.png)

after: 
![image](https://cloud.githubusercontent.com/assets/1758577/14745672/ab901378-08ac-11e6-9cb0-ffec88df0ffb.png)

**Comment by Moc** [comment]
Very interesting and theoretically not possible.... Not sure what's going on here. 
@CaMer0n Do you have any idea?

**Comment by Moc** [comment]
I think this is a server configuration issue. Closing for now unless someone can add more relevant info to be used in narrowing down the cause of this issue.
