### ISSUE TITLE
If forum thread_name starts with a number forum tries to display that thread_id instead of correct thread_id

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1572]
Hi devs,  Since upgrade from 2.1 to 2.1.1 we experience an issue in Forum plugin.  We have a forum thread_id of 8359 and the thread_name is 2016 Rideouts.  When we click that forum link to display it, it actually pulls the details from thread_id 2016 rather than thread_id 8359

This happens with any thread where the thread_name (Title) has a number at the beginning.  If there is another thread which matches the thread_id such as 2015 or 2016 then it displays that thread_id instead of wht it should.  If there is no corresponding thread_id to the number in the thread_name, then it returns nothing.

**Comment by CaMer0n** [comment]
@martyshep I believe this was resolved already. Are you using the latest files from here?

**Comment by martyshep** [comment]
@CaMer0n I am using latest from v2.1.1 general release, http://sourceforge.net/projects/e107/files/e107/e107%20v2.1.1/e107_v2.x_to_2.1.1_upgrade.zip/download
Should I sync with github instead?

**Comment by CaMer0n** [comment]
@martyshep Yes, please sync with Github.

**Comment by martyshep** [comment]
Sync with latest on Github resolved issue.  Thanks @CaMer0n you rock Sir!

**Comment by CaMer0n** [comment]
@martyshep haha, thanks. :+1:  :-)
