### ISSUE TITLE
Bug: Link Image from Media Manager

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1580]
I just created a forum post on my website which link two images from the media manager when i submitted the post and go to it I see two image boxes that show no image. I copy the link and got this:
http://3rdcavregiment.com/thumb.php?src=&w=482&h=432

it is missing the image which should be 
http://3rdcavregiment.com/e107_media/e55dfae959/images/2016-04/donts.png

**Comment by Moc** [comment]
@LaocheXe Is this issue still present using the latest files from Github?

**Comment by LaocheXe** [comment]
I will check in the next few days, out camping right now

**Comment by LaocheXe** [comment]
Okay, just synced to github, and tested it, still getting the same issue.

This Image (URL) http://tf13arma.com/e107_media/a4da2c28c9/images/2016-10/dl_tablet.png

http://tf13arma.com/forum/website/84/testing/

Code: <img src="/thumb.php?src=&w=1222&h=705" width="1222" height="705">

Removing the full URL when submitting?

**Comment by CaMer0n** [comment]
@LaocheXe Is this still an issue?

**Comment by LaocheXe** [comment]
Yes, same issue.

![capture1](https://user-images.githubusercontent.com/5818022/33518793-ddf9e972-d760-11e7-8758-7d3ba1bbacff.JPG)

![capture2](https://user-images.githubusercontent.com/5818022/33518794-e00c5ba0-d760-11e7-89e1-23495a4e6ae6.JPG)

![capture3](https://user-images.githubusercontent.com/5818022/33518795-e20c1f12-d760-11e7-81b8-f846a7be76c9.JPG)

**Comment by CaMer0n** [comment]
Thank you @LaocheXe ! Could you please share here the following: 

1) Original Source URL you entered
2) The image SRC of the blank image. (666x666)

Thanks

**Comment by LaocheXe** [comment]
1: https://501stlegion-a3.com/e107_media/adca4031eb/images/2017-11/501stlogo_.png
2: https://501stlegion-a3.com/thumb.php?src=&w=666&h=666
2: 2: /thumb.php?src=&w=666&h=666

**Comment by CaMer0n** [comment]
@LaocheXe Can this one be closed? This code would have been rewritten a lot since 2017.

**Comment by Moc** [comment]
Closing as we assume it is fixed. If not, please let us know and I'll re-open.
