### ISSUE TITLE
Feature Request: Lack of BBcode

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1581]
I am using TinyMCE4 and was wondering how can I display code in forum post (no quote bbcode or code bbcode).

Is this just a e107 issue or is it TinyMCE 4 issue?

**Comment by CaMer0n** [comment]
It's usually under "Format" ?

**Comment by LaocheXe** [comment]
Now i do feel like a dumbass - make me as an idiot.... thanks @CaMer0n
