### ISSUE TITLE
Keywords does not support accented characters

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1584]
Keywords does not support accented characters.
If I click on the keywords, no results. 
If I write witout accented character, yes results.

**Comment by CaMer0n** [comment]
@fizi Thanks. Could you be a little more specific? Keywords where exactly? Are you referring to the admin area where keywords are entered as tags?

**Comment by fizi** [comment]
Yes. I added it on the admin area to news and on the news page I click on the keywords and no results. If I enter the keywords without, yes results. I think the system don't support the accented characters on the keywords.

**Comment by Jimmi08** [comment]
@CaMer0n  this:
![image](https://cloud.githubusercontent.com/assets/5429548/14929699/169e0064-0e5f-11e6-9df8-8d2879578def.png)
![image](https://cloud.githubusercontent.com/assets/5429548/14929703/1d406a56-0e5f-11e6-9893-10aa1dbf2e72.png)

Otherwise no problems (except than using meta keywords as tags instead normal tags system)

**Comment by CaMer0n** [comment]
I'm guessing it could be something to do with selectize. @lonalore do you have similar issues with tags?

**Comment by lonalore** [comment]
Yes, I have:
![nevtelen2](https://cloud.githubusercontent.com/assets/6043821/14934367/56bd7b12-0eae-11e6-95c4-6793d5677621.png)

Selectize works properly, beacuse saving the keywords in the database works flawlessly:
![nevtelen](https://cloud.githubusercontent.com/assets/6043821/14934420/5aec04b4-0eaf-11e6-852e-136050db4eb0.png)

In my opinion, we should save tags into a separated table, with ID, tag name, and with a **transliterated** SEF URL, then create a reference between news item and tags with using a switch table.

With this soultion, we would be able to select relevant tags from a separated database table, and display them in the selectize's autocomplete dropdown.

**Comment by Jimmi08** [comment]
@CaMer0n @lonalore 

> In my opinion, we should save tags into a separated table, with ID, tag name, and with a transliterated SEF URL, then create a reference between news item and tags with using a switch table.

This is exactly what tags plugin should do. Classic keywords should be used just in meta keywords.   

Updated to latest github, checked database, changing to use /tag/  not ?tag
![image](https://cloud.githubusercontent.com/assets/5429548/14934870/e9b889ec-0ebe-11e6-94d9-252bbd829765.png)

problem is here (added print_a()) - in news.php

![image](https://cloud.githubusercontent.com/assets/5429548/14934898/253ec566-0ec0-11e6-9b4d-84f5a1eeda2a.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/14934901/3445f08e-0ec0-11e6-8ce8-bbff26c7b500.png)

**Comment by lonalore** [comment]
Try to use `e107::getParser()->toDB()` instead of `preg_replace()`.

```php
$tagsearch = e107::getParser()->toDB($_GET['tag']);
```

This should solve this problem.

**Comment by Jimmi08** [comment]
Confirm. It helped. But it's core file news.php, I don't want to mess it.

**Comment by CaMer0n** [comment]
@Jimmi08 Does e107::getParser()->filter($_GET['tag']); work also?

**Comment by Jimmi08** [comment]
@CaMer0n   it works.

**Comment by fizi** [comment]
I tested and work. Thanks!
