### ISSUE TITLE
Native lang for TinyMce4

### ISSUE THREAD

**Issue by akogo1** [e107inc/e107#1585]
I need to change TinyMCE4 default language to another, how can I do this?

**Comment by CaMer0n** [comment]
@akogo1 Please update to the latest files on here, it should fix the problem.

**Comment by Alex-e107nl** [comment]
Please look at https://github.com/e107inc/e107/commit/23efdfd972e4f139ba07e216d7b1c8b399914c82 it's not working yet...

**Comment by CaMer0n** [comment]
@Alex-e107nl Would you mind testing with this?

**Comment by CaMer0n** [comment]
Tested by @Alex-e107nl and working.
