### ISSUE TITLE
Question: e_user.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1586]
Currently I have a plugin that uses e_user.php, on the dev documentation it doesn't say much.

When creating the plugin with plugin builder I selected the e_user.php page which gave me e_user.php with some default code which is used for the user forum post? I went in and added what I could, my question is can I make the option for users to change a few of the information?

Right now I have three label's that pull user information from the database from myplugin table, but I would like to allow a user to edit the information in the settings area without making extended user fields. Is this possible?

**Comment by CaMer0n** [comment]
@LaocheXe e_user.php data displays on the profile page (not the user-settings page). If you wanted to save data, you would need to use ajax on the profile page so that it saves when data is changed. Send a form element as the 'text' value. However, what you probably want is an extended-field that pulls from your plugins table ?

**Comment by LaocheXe** [comment]
Yes an extended-field that pulls from my plugins table.

**Comment by CaMer0n** [comment]
@LaocheXe Extended User Fields > Add Custom Field > Type: DB Table Field ;-)

**Comment by LaocheXe** [comment]
@CaMer0n So in the Basic - Name field put in myplugin database table (squadxml) and then steam id?

So it would be squadxml(plugin table) arma_id(column) ??? like that?

**Comment by LaocheXe** [comment]
@CaMer0n I did what you said, all it does is show the field but nothing to add/edit and displays the name but no value in profile.

**Comment by CaMer0n** [comment]
I think we may need a new type of extended user field. custom class/method from within e_user.php.

**Comment by LaocheXe** [comment]
Any Update on this?
