### ISSUE TITLE
New login menu changes incomplete.....

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1588]
Got some bugs after recent update with github files on login menu:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14828329/74466252-0bde-11e6-9ba1-7733b3c058b1.jpg)

Also got some missing strings in Portuguese language (in red):
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/14828345/86e78f4e-0bde-11e6-9c35-0e968086bb40.jpg)

**Comment by CaMer0n** [comment]
@Jimmi08 ?

**Comment by Jimmi08** [comment]
@CaMer0n  
This causes problem
![image](https://cloud.githubusercontent.com/assets/5429548/14830561/967975f4-0bf1-11e6-80ad-602f231f7208.png)

Otherwise no problems with translation
![image](https://cloud.githubusercontent.com/assets/5429548/14830578/a77cb668-0bf1-11e6-85a0-4e92c8d86daf.png)

My changes was 15 days ago.  I don't see what can cause problem from this commit:
https://github.com/e107inc/e107/commit/19cadb6a8f3f0b33882135fd26537393b0a9c7a3

**Comment by Jimmi08** [comment]
Weird thing is this config behaviour:
Click on configuration button
![image](https://cloud.githubusercontent.com/assets/5429548/14830758/9620504a-0bf2-11e6-9d55-c5b6277d8e01.png)

tick checkbox, next window, unchecked, after ticking in this window. prefs are saved
![image](https://cloud.githubusercontent.com/assets/5429548/14830785/c26b1f9a-0bf2-11e6-8835-98c976d68867.png)

**Comment by Jimmi08** [comment]
There are really that text:
![image](https://cloud.githubusercontent.com/assets/5429548/14831322/8713b350-0bf5-11e6-9c46-e4c398f648fa.png)

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 I knew you'd track it down!

**Comment by CaMer0n** [comment]
@Jimmi08 @rica-carv Just changed it, please test.

**Comment by Jimmi08** [comment]
@CaMer0n For me ok, only in menu manager I still need two clicks (2 modal windows, default BT theme)
 But you get me terribly scared that I messed something again. Not good feeling. Glad to help.

**Comment by CaMer0n** [comment]
@Jimmi08 Sorry about that. I hadn't touched the login shortcodes for quite some time, so I thought of you. Seems it's a pretty old problem though looking at that code.

**Comment by Jimmi08** [comment]
@CaMer0n No problem. Sometimes is double check good way. Good night

**Comment by rica-carv** [comment]
@CaMer0n Returns are gonne, now is just missing correct translation....

**Comment by rica-carv** [comment]
Regarding the incomplete translation and correct grammar, i'll give it a try as soon i can....
