### ISSUE TITLE
Issue: Plugin Prefs Make 403 Error

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1590]
So I am working on a new plugin and had set up the admin_config.php a few days ago, went and re-generated a new one with site prefs to add to the plugin, when I hit the submit button to submit my changes to the prefs I get error 403 forbidden You don't have permission to access /e107_plugins/squadxml/admin_config.php on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

/e107_plugins/squadxml/admin_config.php?mode=main&action=prefs

**Comment by CaMer0n** [comment]
@LaocheXe I take it this is a remote (production) server you used?

**Comment by LaocheXe** [comment]
@CaMer0n nope, live server - http://defiantz.org

**Comment by LaocheXe** [comment]
The odd part it works on another server so it might be a server issue after all
