### ISSUE TITLE
Comment menu

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1592]
I configure the comment menu on the admin area. But the system write "Nothing updated as no changes were made.".
In this case I don't configure the comment menu. (no caption on the menu and don't configure what appears and how in the menu.

**Comment by fizi** [comment]
I think connects to it that the number of comments not on the news (appears null) and latest news menu also (appears null) - the news has comments.

**Comment by fizi** [comment]
I'm not impatient, but when it will be fixed?

**Comment by Jimmi08** [comment]
@Moc 
confirm with comment menu
![image](https://cloud.githubusercontent.com/assets/5429548/22178077/db35e248-e02d-11e6-982c-a310cfd6746d.png)

**Comment by fizi** [comment]
I write comment to the news...but appears null comment on the news page in the news item. Appears null on the extend news, but all comment appears below the news.

**Comment by Jimmi08** [comment]
@fizi check status of your comments.   In options set displaying status value. Not approved comments are not displayed.
![image](https://cloud.githubusercontent.com/assets/5429548/22184061/2f7db518-e0cb-11e6-952a-a024f06dd7f0.png)

On frontend you should see something like this:
![image](https://cloud.githubusercontent.com/assets/5429548/22184069/3efb46cc-e0cb-11e6-8d23-c1d4660994dc.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/22184120/08c3ceac-e0cc-11e6-9625-0882d6bb738f.png)

**Comment by fizi** [comment]
All comments approved, but on the news comment count not.

**Comment by Jimmi08** [comment]
Your problem is with comment menu or with comments count in news = shortcode {NEWSCOMMENTS}? It's different. 
Is your site multilang? 
![image](https://cloud.githubusercontent.com/assets/5429548/22184958/97653c9e-e0dc-11e6-9001-5802510c960f.png)

**Comment by fizi** [comment]
Comment menu now work, the problem with comment count on news item, NEWSCOMMENTS. Yes my site is multilanguages.

**Comment by Moc** [comment]
@fizi Is this still an issue? I cannot see to reproduce it..

**Comment by fizi** [comment]
I think this is work. You can close it.
