### ISSUE TITLE
Gallery-Links false

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1594]
I wanted to test the gallery. The links, however, are wrong. It should look like this:
`http://www.ninja4ever.de/e107_plugins/gallery`

But they looks so:
`http://www.ninja4ever.de/gallery`

Where can I fix it?

**Comment by Jimmi08** [comment]
No, this is correct. It has something with URL configuration and SEF URL.  This `/gallery ` or `/e107_plugins/gallery/gallery.php`  but not` /e107_plugins/gallery` .   You can change this in Sitelinks.

**Comment by CaMer0n** [comment]
@TrueHatori Please check that your .htaccess file contains the contents of e107.htaccess

**Comment by TrueHatori** [comment]
I'm blonde, but not stupid.
I made screenshots, but can not upload it. Look here:
[http://www.ninja4ever.de/priv/gallery_1.jpg](url)
[http://www.ninja4ever.de/priv/gallery_2.jpg](url)
[http://www.ninja4ever.de/priv/gallery_3.jpg](url)

At the .htaccess I have not changed. It is the original file.

**Comment by tgtje** [comment]
Image 1 is auto generated  > the displayed line is identical to mine if SEF URL is ENabled. Just DISable SEF URL and it displays {e_PLUGIN}gallery/gallery.php. > its the FIRST basic link, all other links are adjusted to use sef. (see the e_url file in plugin)
Your site (gallery) behaves (just checked) as expected.

**Comment by TrueHatori** [comment]
I have now turned off SEF, it has not helped.
