### ISSUE TITLE
Old shortcodes not parsed correctly

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1597]
@CaMer0n  Are you sure that latest changes with shortcodes didn't have influence on old shortcodes?  It worked before, but maybe there is problem with old code itself.
this code:
![image](https://cloud.githubusercontent.com/assets/5429548/14938439/c218a18c-0f23-11e6-8407-c2b0899c791d.png)

returns 
![image](https://cloud.githubusercontent.com/assets/5429548/14938441/cd495088-0f23-11e6-9c68-45621d0e8598.png)

and debugger
![image](https://cloud.githubusercontent.com/assets/5429548/14938443/dc76d832-0f23-11e6-89db-d2110650ea96.png)

I vague remember that that was different text in debugger  before, something with legacy.

Just for your info, I can rewrite it to new way.

**Comment by CaMer0n** [comment]
@Jimmi08 It's possible. Could you send me your plugin to use as a test?
It's essential that nothing old is broken by new code.

**Comment by Jimmi08** [comment]
@CaMer0n How should I do it? I can't see possibility to send file in gitter.

**Comment by tgtje** [comment]
@Jimmi08 normally (windows) > drop target  (select, drag into/over chat,drop) should work...

**Comment by Jimmi08** [comment]
Yes, thank you, done,  @CaMer0n  file was sended.

**Comment by Jimmi08** [comment]
@CaMer0n  if latest github didn't solve this plugin issue, it's meant that problem is in plugin?
And I noticed this in debugger (very weird path)
![image](https://cloud.githubusercontent.com/assets/5429548/14944167/d9a3bd0a-0feb-11e6-81af-6abf2b865505.png)

**Comment by Jimmi08** [comment]
@CaMer0n  if I  added this line to shortcode_handler.php
(line number could be a bit different)
![image](https://cloud.githubusercontent.com/assets/5429548/14944368/f314679e-0ff0-11e6-99dd-5dc8ec1738e5.png)
it works as should be:
![image](https://cloud.githubusercontent.com/assets/5429548/14944371/1568cb46-0ff1-11e6-9077-16a3c245aef0.png)

**Comment by CaMer0n** [comment]
I think this may break the direct array option. Please test with: 

	$arrShortcodes = array('TESTARRAY'=> "test successful");
	echo $tp->parseTemplate("{TESTARRAY}", true, $arrShortcodes);

**Comment by Jimmi08** [comment]
@CaMer0n  - I really get how this works very slowly, but I can test. You are right. So another try.
This array:  `$this->legacyBatch.` is empty.  
 $code is correct `BDAY_DEMO`. - this is reason why my change worked.
But when I echo $this->legacyBatch. inside parse_scbatch() function, it has correct content. 
Maybe this helps.

**Comment by rica-carv** [comment]
Sorry for bringing this up, but actually i think i'm experiencing this same issue in two v1.4 plugins:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/19620788/0466681c-987c-11e6-84d4-e38735ccc02a.jpg)
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/19620789/04674e44-987c-11e6-835a-0f85b3f43f21.jpg)

Strangely it happens after succesfull upgrade to latest github files and database update, which is more weird....

**Comment by CaMer0n** [comment]
@rica-carv Please provide links to the 1.4 plugins so I can test. thank you!

**Comment by rica-carv** [comment]
@CaMer0n The first (Links) is the old v.14 core plugin links_page, the second is the [e_classifieds plugin](http://www.keal.me.uk/e107_plugins/download/download.php?action=view&id=230).

Anyway, after some more further testings, i found out that the output of the shortcodes is somehow correct (despite a litlle garbled) with v2 core themes (Bootstrap3 & Voux) but are all wrong (as my images above) with old v1.4 core theme Jayya.
So, as far i see it, it has to do with the theme.....

**Comment by CaMer0n** [comment]
Okay thanks. Core v1.4 plugins should not be used with v2. If they were removed it was because they are incompatible. I believe @Jimmi08 was working on a v2.x compatible version of links-page (if I remember well) . I'll check out the e_classifieds and to see what's going on.

**Comment by rica-carv** [comment]
@CaMer0n The @Jimmi08 version of the links-page plugin is still in beta version, and it gives a few errors (mainly all garbled display). Although i could help solving them, somehow....

**Comment by Jimmi08** [comment]
@CaMer0n @rica-carv I checked LP plugin with latest github, no problems.  But I use only new themes.

**Comment by rica-carv** [comment]
@Jimmi08 Just to not be off topic, i've posted my ideia on the LP plugin page...

**Comment by CaMer0n** [comment]
I tested the **Links Page** plugin with the jayya theme. There was no problem. (other than missing the bootstrap css)

**Comment by Jimmi08** [comment]
@CaMerOn I did the same. He means original 1.0.4 version not updated.

**Comment by rica-carv** [comment]
@CaMer0n @Jimmi08 Indeed, the problem is when using the old shortcodes files (ie .sc) off old plugins, on v2.x......

**Comment by Jimmi08** [comment]
@CaMer0n it just happend to me. It can be caused by old (bad) coding in some menus. This lines in menu file caused bad parsing:
```
?>
<script type="text/javascript" src="<? echo $plugin_dir."skypeCheck.js"; ?>">
</script>
<?
```
After moving js to e_header.php, parsing is correct.  I would consider to close this issue.

**Comment by rica-carv** [comment]
@Jimmi08 Indeed, after all this "problems", i'm porting all my v1.4 updated to v2.x to a clean v2.x install, to prevent tghis and some other legacy issues, so for me, this could also be closed....

**Comment by Jimmi08** [comment]
Ups, it's my issue. Mea culpa. Closing
