### ISSUE TITLE
Question about news_date shortcode

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1599]
Why the change on lines 363 / 364 of [news_shortcodes.php](https://github.com/e107inc/e107/blob/master/e107_core/shortcodes/batch/news_shortcodes.php) ????

Previously, with `return date($parm, $date);`, i could call the shortcode this way `{NEWS_DATE=d/m/y h:m}` and make a specific format based on [PHP date formats](http://php.net/manual/en/function.date.php)...
Now, with `return $tp->toDate($date,$parm);`, i can't use that shortcode call.....

**Comment by CaMer0n** [comment]
Please check the toDate() function, you'll see that you can do something similar.

**Comment by fizi** [comment]
I was so used: `{NEWSDATE=d}`
Now how need use?

**Comment by rica-carv** [comment]
@CaMer0n The toDate() fuction in [e_parse_class.php](https://github.com/e107inc/e107/blob/83cdda6004927f2ef5cfcc6adf6438d3d9e35100/e107_handlers/e_parse_class.php) calls `e107::getDate()->convert($datestamp, $format)`
Fetching the convert function, in [date_handler.php](https://github.com/e107inc/e107/blob/9d3e1ad5e70f3bcdec1f840e4ffeacbaef3f62e3/e107_handlers/date_handler.php) it calls this `$this->toTime($string, $mask)` if the $mask is not numeric (wich `d/m/y` is not indeed numeric on my shortcode call).
The toTime function in [date_handler.php](https://github.com/e107inc/e107/blob/9d3e1ad5e70f3bcdec1f840e4ffeacbaef3f62e3/e107_handlers/date_handler.php) will call `$this->strptime($date_string, $mask)`.
When it reaches strptime function on [date_handler.php](https://github.com/e107inc/e107/blob/9d3e1ad5e70f3bcdec1f840e4ffeacbaef3f62e3/e107_handlers/date_handler.php), it simply ignores the specific format `d/m/y` of the shortcode call....

So, how can i format NEWS_DATE with my custom format of DAY / MONTH / YEAR???
Or HOUR : MINUTE ???

**Comment by CaMer0n** [comment]
@rica-carv @fizi did you try `dd-mm-yyyy` ?

btw. @rica-carv I'm sure it wasn't your intention, but all caps text like this `DAY / MONTH / YEAR???` could be perceived as emotional and yelling.

**Comment by fizi** [comment]
Yes it work `{NEWSDATE=dd}` and `{NEWSDATE=M}` and `{NEWSDATE=MM}`
Thanks!

**Comment by rica-carv** [comment]
@CaMer0n No, i haven't tryed `dd-mm-yyyy`.
And no, the caps was just to show the intended output.... No shouting or yelling intended.... LOL

**Comment by rica-carv** [comment]
@CaMer0n Err, it works, more or less.....

How can i get rid of the span tag with data-livestamp on it?????
I'm tryint to use the shortcode on a tooltip (`<span class="e-tip" title="'.LAN_THEME_9.'{NEWS_DATE=dd/mm/yyyy}'.LAN_THEME_8.'{NEWS_DATE=hh:mm}">{GLYPH=date}&nbsp;{NEWS_DATE=dd/mm/yyyy hh:mm}</span>`), but it gives this error because of nested span tags...:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14943801/c89b2f18-0fda-11e6-92ca-dc3fe041da4f.jpg)

**Comment by rica-carv** [comment]
Forget it, solved it again with a custom shortcode inside my theme... Thanks all....
