### ISSUE TITLE
placeholder instead of images

### ISSUE THREAD

**Issue by gaz2644** [e107inc/e107#1601]
Hi iv recently upgraded to v2 from v1. now i cant post images at all on my site, they get replaced by placeholders.
How can i fix this please
Regards
Gaz

**Comment by Jimmi08** [comment]
More information would be great.  Example, screenshot, source code (what is image url now etc). Try use Console and Inspect element (F12) to identify possible source of problem. What theme do you use?  Link to your site could help too. With images there is very sometimes problem with htaccess ...

**Comment by gaz2644** [comment]
its ok thanks for the comment, iv started again back to v1.
