### ISSUE TITLE
how to insert raw html code

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1602]
I needed to insert this code in prefs (embed tweet). Type textarea, not bbarea and source code.  Is there way how I set use only raw html without striping part of code? Thanks

`<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"> 
.. embed tweet... 
</blockquote>`

**Comment by CaMer0n** [comment]
blockquote should work fine. Use Tools > Source Code in the TinyMce navigation.

**Comment by Jimmi08** [comment]
I tested it with news and it worked (I have no access to source now)  So I need to use bbarea type in prefs? I supposed that there is some params (write or read) where you tell use raw html . Thanks

**Comment by Jimmi08** [comment]
Tested in latest version in some textarea in prefs. It works. Thank you.
