### ISSUE TITLE
Tools - Notify - Remark: user_display_profile

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1606]
Hi,
under Tools - Notify - you can issue a warning when User views profile, should that not be when a user edits his profile, that would make a lot more sense, viewing does not change anything.. 

Oke i would like to use that :-)

Alex

**Comment by Moc** [comment]
Just a note for when I have more time:
- Event trigger already exists: userdatachanged
- Needs to be included in e107_handlers/event_classphp

**Comment by Moc** [comment]
Just going through old issues. This one has been implemented sometime in the past years :)
