### ISSUE TITLE
Enhancement forum new shortcodes???

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1607]
I've been customizing the templates for the forums inside my theme, and i would like to do [something like this](https://jsfiddle.net/Wc4xt/1052/) since i've got a lot of forums occuping the whole page, and scrolling it is quite crumbersome...
In orther to anchieve this, every collapsible div (or parent) must have a unique ID, and i can't use the forum name, because some forum names have spaces on it, and therefore, break the whole collapsible ideia...
I can do this easilly if the forums id as they're stored in the database could be returned via a shortcode, ie `{PARENTID}`.
I can see that the `{PARENTNAME}` & `{PARENTSTATUS}` shortcodes for the forum are donne diferently from the standard ones (lines 330 to 335 on [forum.php](https://github.com/e107inc/e107/blob/eaf23811f517963cea6963a6e579d5f1ec6d0ec5/e107_plugins/forum/forum.php)), so my proposal is just to add one more line there: `$pVars->PARENTID = [$parent['forum_id'];`
Of course i can do this also the hard way, by creating a theme shortcode, and make it go fetch the database again for retrieving the forum id, but why reinvent the wheel???

**Comment by rica-carv** [comment]
In the same file, around lines 447 to 477, is possible to have also a LASTPOSTNAME shortcode, with the last post name???

All this questions are due that currently besides the collapsible, i'm aiming to do something like this:
![boardindex 1](https://cloud.githubusercontent.com/assets/17130530/14978594/cfa2f8aa-1114-11e6-8c9f-366f3874528a.jpg)

**Comment by rica-carv** [comment]
Proposed here: #1614

**Comment by Moc** [comment]
@rica-carv can this issue be closed?
