### ISSUE TITLE
Hardcoded lans in forum plugin files

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1608]
[Hardcoded lan in view_forum template `<div class='panel-heading'>Status Keys</div>`](https://github.com/e107inc/e107/blob/master/e107_plugins/forum/templates/forum_viewforum_template.php#L356)
Status keys.....

[Hardcoded lan in forum_viewforum.php `<div class='panel-heading'>Viewable by</div>`](https://github.com/e107inc/e107/blob/209d68a6fe67464446998d99adad476ae8e5ef1b/e107_plugins/forum/forum_viewforum.php#L373)
Viewable by....

**Comment by Moc** [comment]
Feel free to submit pull-requests for this :)

**Comment by rica-carv** [comment]
@Moc I can do it, but where's the guidelines to how to create new LAN strings???

**Comment by Moc** [comment]
http://e107.org/developer-manual/plugin-basics/languages#languages
https://github.com/e107inc/e107/wiki/e107-Coding-Standard#loading-language-files

**Comment by rica-carv** [comment]
@Moc Frankly, i don't know if i should do it, mainly because is not all those hardcoded HTML a candidate for templating????

**Comment by Moc** [comment]
The part in forum_viewforum.php needs to go into a template eventually yes. It isn't an easy task though (see the lines below). Regardless, these hardcoded strings need translation. You can find LAN in templates as well. 

Cameron recently introduced a shortcode that can be used as well: {LAN: LAN_XXX)

**Comment by tgtje** [comment]
Just noticed post; there are more than these 2.. Admin needs some more too, @rica-carv Like to try or on my own todo (rework needed) list ?

**Comment by rica-carv** [comment]
@Moc @tgtje Just proposed the lan change here #1609

**Comment by Moc** [comment]
I think this one can be closed by now, right?

**Comment by tgtje** [comment]
Yes can be closed (looking for items from post 1 : they are present as LAN's ( yesszus committed on GitHub on 15 Sep 2016)
