### ISSUE TITLE
[Question] How does work e107 mail queue handler?

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1610]
Well, I´ve noticed that there is an email queue, which works with server chron jobs. That seems exaclty what I was looking for but I have a question.

How does it work? I mean, its only made to handle mass emails or can we use this queue to send emails from plugins, for example, in order of sending the email instantly from the code (which makes the page to load slowler)

Thank you!
- Nes

**Comment by CaMer0n** [comment]
From e107_handlers/mail.php 

     *	@param string $send_to - recipient email address
	 *	@param string $to_name - recipient name
	 *	@param array $eml - optional array of additional parameters (see BELOW)
	 *
	 *  @param string $eml['subject']           - Email Subject
	 * 	@param string $eml['sender_email']	    - 'From' email address
	 * 	@param string $eml['sender_name']		- 'From' name
	 * 	@param string $eml['replyto']			- Optional 'reply to' field
	 * 	@param string $eml['replytonames']	    - Name(s) corresponding to 'reply to' field  - only used if 'replyto' used
	 * 	@param bool $eml['send_html']		    - if TRUE, includes HTML part in messages (only those added after this flag)
	 * 	@param bool $eml['add_html_header']     - if TRUE, adds the 2-line DOCTYPE declaration to the front of the HTML part (but doesn't add <head>...</head>)
	 * 	@param string $eml['body']			    - message body. May be HTML or text. Added according to the current state of the HTML enable flag
	 * 	@param string|array $eml['attach']		- string if one file, array of filenames if one or more.
	 * 	@param string $eml['cc']			- comma-separated list of cc addresses.
	 * 	@param string $eml['cc_names']  		- comma-separated list of cc names. Optional, used only if $eml['cc'] specified
	 * 	@param string $eml['bcc']		    - comma-separated list
	 * 	@param string $eml['bcc_names'] 		- comma-separated list of bcc names. Optional, used only if $eml['bcc'] specified
	 * 	@param string $eml['bouncepath']		- Sender field (used for bounces)
	 * 	@param string $eml['returnreceipt']	    - email address for notification of receipt (reading)
	 * 	@param array $eml['inline_images']	    - array of files for inline images
	 * 	@param int $eml['priority']		        - Email priority (1 = High, 3 = Normal, 5 = low)
	 * 	@param string $eml['e107_header']		- Adds specific 'X-e107-id:' header
	 * 	@param string $eml['extra_header']	    - additional headers (format is name: value
	 * 	@param string $eml['wordwrap']		    - Set wordwrap value
	 * 	@param bool $eml['split']			    - If true, sends an individual email to each recipient
	 *  @param string $eml['template']		    - template to use. 'default'
	 *  @param array $eml['shortcodes']		    - array of shortcode values. eg. array('MY_SHORTCODE'=>'12345');
	 *
	 *  @param boolean $bulkmail - set TRUE if this email is one of a bulk send; FALSE if an isolated email
	 *	@return boolean|string - TRUE if success, error message if failure
	 */
	public function sendEmail($send_to, $to_name, $eml = array(), $bulkmail = false)

**Comment by nesjett** [comment]
Thank you for your time CaMer0n, but I already got into that function and nothing was discovered about what I'm asking.

What I want to know is if we can add an email to queue to be sent when the chron job executes.

I saw the bulk parameter, but I think it's not meant to add a single mail to queue, cause I saw somthing about keep open the SMTP connection inside the function.

So, calling  $instance->sendEmail()  will add it to the queue to be sent as soon as chron job executes or will the email be sent in real time (think I'm trying to avoid)


Thank you,
- Nes

**Comment by nesjett** [comment]
PD: I don't know how git works with closed issues, so I'm mentioning you for you to get notified.

@CaMer0n

**Comment by rica-carv** [comment]
I wonder if setting this param true (`@param boolean $bulkmail - set TRUE if this email is one of a bulk send; FALSE if an isolated email`) wouldn't add the email to the sent queue???

**Comment by nesjett** [comment]
maybe yes, but im not sure about how does this work, so maybe I would be making somethink poor optimized.

I hope @CaMer0n could tell us a little bit more about this param or about the way to add emails to queue in the right way.

**Comment by CaMer0n** [comment]
@nesjett the queue is not used at all unless `bulkmail` is set to true. Nothing is sent from the queue unless the cron for it is triggered.

**Comment by nesjett** [comment]
@CaMer0n nice, if there is no issues/bad smells by using "bulkmail" with a single one then that´s all.

Thank you again for your time
