### ISSUE TITLE
Question: Plugin Admin Order

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1613]
I am working on a plugin that allows the admin to create ranks and sort them (like the forums admin)

So the Forums admin area list has some white lines
![capture](https://cloud.githubusercontent.com/assets/5818022/15024950/a92eb27a-11fc-11e6-9f41-da796e1159ad.PNG)

While my plugin doesn't
![capture1](https://cloud.githubusercontent.com/assets/5818022/15024958/b1fd161c-11fc-11e6-8cbb-35cf183b1280.PNG)

How do I get it to look like the forums?

**Comment by Jimmi08** [comment]
@LaocheXe  Look at sitelinks how this is done

**Comment by Moc** [comment]
Do you still need help with this question?
