### ISSUE TITLE
Question: Can Shortcode wrapper handle Shortcode code inside itself?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1616]
I'm wondering if its possible to have a shortcode wrapper with shortcodes inside it, and have it parsed correctly, ie like this:
`$DOWNLOAD_WRAPPER['view']['DOWNLOAD_VIEW_DATE'] = '<span class="e-tip" title="{DOWNLOAD_VIEW_DATE_LAN}: {DOWNLOAD_VIEW_DATE=long}">{GLYPH=date}&nbsp;{---}</span>`

My main issue is that i don't want to render the tootip or the glyph icon associated to the shortcode,if the shortcode is blank....

Any ideias?

**Comment by CaMer0n** [comment]
No, it's not possible. Just use regular html markup to render the glyph.

**Comment by rica-carv** [comment]
@CaMer0n The main issue is not the glyph, is the title render: `title="{DOWNLOAD_VIEW_DATE_LAN}: {DOWNLOAD_VIEW_DATE=long}"`

**Comment by Moc** [comment]
Is this issue still relevant?

**Comment by rica-carv** [comment]
Solved in #2029
