### ISSUE TITLE
e107_class.php->set_urls and $_GET parameters

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#1619]
Within the last few days I updated all of my e107 files to the most recent copies in the GIT repository. I've encountered a problem that wasn't occurring before with my much older v2 install.

[Pastebin example script](http://pastebin.com/GqL5LPra)

At various points in my custom pages I make jQuery $.ajax requests that are serviced by PHP scripts that then pass back a result.

When some of these requests started failing, I began inserting a lot of

`"error_log(print_r($_GET, true));"`

...statements into my PHP pages to try to figure out what was going on.

What I've observed is that an array with values like

`Array\n(\n    [my_key] => Array\n        (\n            [myID] => 2\n))`

Is getting turned into

`Array\n(\n    [amp;my_key] => Array\n        (\n            [myID] => 2\n))`
- note the '**amp;**' added in front of the first array key. I've tracked this down to the file e107_class.php

And the function **set_urls** with the lines

```
if(e_MENU)
{
            $requestUri = str_replace('['.e_MENU.']', '', $requestUri);
            $requestUrl = str_replace('['.e_MENU.']', '', $requestUrl);
            if(defset('e_QUERY')) parse_str(e_QUERY,$_GET);
}
```

It is the last line - **parse_str** - that is causing the problem, and modifying my $_GET parameters. When I checked my older install of v2, I notice that this code segment does not execute at all (e_MENU appears to be FALSE), but I can't figure out where e_MENU is defined, what it's used for and whether I would want it to be true or false.

Thank you for any advice!

**Comment by CaMer0n** [comment]
Turn off debug and e_MENU should === false.  e_MENU is a query that contains [ ], currently used by the debugger. eg. mydomain.com/url.php?[debug=basic+]key=val&key2=val2

**Comment by sbwMikael** [comment]
Ah-huh! That's quick and easy, thanks **CaMer0n**!

**Comment by Moc** [comment]
Preferences > Advanced features > Developer mode should be disabled
Then if debug is still on, change the URL to *.php?[debug=none-]

**Comment by sbwMikael** [comment]
Thanks **Moc**. Hmm. Developer Mode is definitely marked disabled. I added the URL suffix as you indicated, but curiously that code-block is still executing.

**Comment by Moc** [comment]
Hmm... what about caching? Try to empty te e107 cache and disable it while you're at it, and also try to flush the browser cache (or try another browser). Any luck then?

**Comment by sbwMikael** [comment]
Appreciate the suggestions - I've been using Firefox. I emptied the cache (there _were_ several cached files), then tried the page with Chrome, and bizarrely I'm still getting the same result! But this is sounding like it's probably a configuration issue on my end?

**Comment by Moc** [comment]
Do you see any debug output on any of the pages? E.g. below the footer (or in the forum plugin for example if you have it installed). 

By "that code-block is still executing." do you mean the if statement for the e_MENU you quoted above? Or debug code? 

I'm out of suggestions haha

**Comment by sbwMikael** [comment]
I'm with you - no debug output I'm afraid. I didn't have the Forum plugin installed, but added it just now (I'm working on a local copy of my site on my LAMP server running in a virtual machine) to check if anything appeared there, but the page is blank (besides the text saying "No forums yet, please check back soon").

Sorry, yes, the code-block below "e_MENU" still appears to be executing according to the error_log statements I included in my test page (in the Pastebin link).

If I were to comment out those lines - the snippet of code that I quoted - would that have any dire consequences other than affecting the debugger? I realise that that's a horrid way to go about fixing a problem, but for the moment I'm just keen to get back to working on my site :)

**Comment by CaMer0n** [comment]
@sbwMikael Can you use post instead of get?

**Comment by sbwMikael** [comment]
Hey **CaMer0n** - I think that that would possible, I note that the jQuery ajax success/fail callbacks fire regardless. Actually I just had a read of this article:

[this article](http://www.sitepoint.com/key-differences-post/)

...and selecting GET vs POST seems to be primarily down to the intention behind the request (a philosophy I've been trying to adhere to) rather than anything mechanical that would get in the way by selecting one but not the other.

**Comment by Moc** [comment]
Closing this as I am assuming the question has been answered satisfactorily. If not, please let us know and I'll re-open.
