### ISSUE TITLE
Issue: Site Links and Plugin Shortcode

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1620]
So I got a plugin that uses custom shortcode, and I remember few months or last year asking about enabling Site Links to use Shortcode - and just for try/test it out I went and put in my shortcode {VOICE_EXE} and it works, just one issue and that is it is displaying the link title (" title=""> Voice) - since my navbar shrinks when scrolling down it displays that " title=""> Voice. idk if I should go and remove the name of the link or what.

**Comment by LaocheXe** [comment]
![capture](https://cloud.githubusercontent.com/assets/5818022/15062261/4763a83a-1304-11e6-80bf-a813f5723e74.PNG)

**Comment by LaocheXe** [comment]
Deleting the link name shows this     " title=""> instead of " title=""> Voice

**Comment by CaMer0n** [comment]
You don't need a shortcode. Use e_sitelink.php for a custom and dynamic drop-down menu.

**Comment by Moc** [comment]
Closing as I am assuming the question has been answered. Let us know if you need further help.
