### ISSUE TITLE
Smileyfaces all over

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#1621]
After downloading the latest Git this is how my homepage looks like :)
Turing on debug it says this:
Using Permlist cache: True
e107forum->loadPermList()()
C:\wamp\www\e107\e107_plugins\forum\forum_class.php line 71 

![smileyfacesallover](https://cloud.githubusercontent.com/assets/1757346/15064670/91354b36-131c-11e6-9614-c297195ebea7.JPG)

**Comment by CaMer0n** [comment]
@Norwayman please comment here if it appears again.

**Comment by Norwayman** [comment]
Thanks @CaMer0n this fixed it! :)
