### ISSUE TITLE
Issue: Site Looks Bad

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1628]
![capture](https://cloud.githubusercontent.com/assets/5818022/15094961/b4e51e72-1479-11e6-8ba6-29d53eb80b35.PNG)

Sync to Github on 5-7-2016 at 5:33 PM CST

**Comment by CaMer0n** [comment]
I'll need a bit more information than that to do on. Are emoticons enabled?

**Comment by LaocheXe** [comment]
The update was at 5:33 PM CST today which is 05/07/2016 - I went in and emoticons was enabled, disable it and site went back to normal.

**Comment by CaMer0n** [comment]
Thanks, are you using the default emoticon pack?

**Comment by fizi** [comment]
I have the same problem. I use default emoticon pack. If I disabled emoticons the site normal, if I enabled emoticons site wrong (no news body text, no chatbox text, no sitemenu text.

**Comment by Moc** [comment]
Confirmed, just updated using latest files. Same problem. Disabling emoticons fixes it.

**Comment by tgtje** [comment]
Also confirmed, replaced e_parse class (recently changed) > issue gone (no code knowledge so issue ? )

**Comment by CaMer0n** [comment]
@fizi @LaocheXe @Moc @tgtje Please update, this should fix it. (i hope)

**Comment by tgtje** [comment]
For me :+1:

**Comment by fizi** [comment]
I updated and I think the problem resolved.

**Comment by LaocheXe** [comment]
@CaMer0n issue has been fixed in latest update.

**Comment by CaMer0n** [comment]
okay, thank you. Closing now.
