### ISSUE TITLE
Language Bug : userclass

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1633]
As already mentioned by poster on e107 help (create issue > never done), and confirmed behaviour on e107.nl and myself on local.
Issue : Create a userclass
Using English > userclass IS created
Using Dutch > userclass is NOT created (mess ; nothing changed)

Now i do not know where the issue comes from, but iff language/admin/lan_admin.php >
define LAN_CREATE ...IS translated > the system does not work. If i use (trans = Aanmaken > dutch for create).
Now do i use the term Create in place ( Aanmaken back to Create). it is functional..

LAN_CREATE is used multiple all over ..

**Comment by CaMer0n** [comment]
This sounds like a symptom of someone translating a check for $_POST['create'] to $_POST[LAN_CREATE] or similar.

**Comment by tgtje** [comment]
LAN_CREATE itself is over 3 years old, did some search on possibilities, End up with differences between LAN_CREATE and the use of USCLAN_15 < this one should imo be the correct one).
Personally i am at a lost here... (the definition of USCLAN_15 is normally replaced ??? by the definition of LAN_CREATE)

**Comment by CaMer0n** [comment]
Normally this bug should be everywhere that the admin-ui is used. News, Pages, etc. 
I believe I have traced the problem. Please test all these areas including userclass creation and let me know. Thanks.

**Comment by tgtje** [comment]
Tested every (afaik) create button/menu link

*Works  as intended* !!

As issue : the button (definition) LAN_CREATE is used  (not as i would 
expect UCSLAN_15 ), but it works... (assume UCSLAN_15 becomes 
deprecated/no longer in use) ??

Since this will be read :
While running the test debugger running too, using the very last files 
this was worth mentioning

a)
warning :  in_array() expects parameter 2 to be array, null given, Line 
4736 of xxxxxxx\e107_handlers\e_parse_class.php
if((strlen($text) < 12) && in_array($text, $this->singleSearch)) // just 
one emoticon with no space, line-break or html tags around it.

b)
PROBLEM WITH CONVERSION from vrijdag, 13 mei, 2016 12:30 to unix timestamp

c)
SQL Error #1364: Field 'user_extended_struct_values' doesn't have a 
default value  > (create cat).

Issue (regarding above) seems solved, but some confirmation from others 
would be best ?


---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by Alex-e107nl** [comment]
Could create a new user class on e107.nl, works! So happy... thx!!

**Comment by CaMer0n** [comment]
Thank you @tgtje !! Issues a, b, c are not related to the LAN_CREATE issue. Yes, UCSLAN_15 is deprecated.

**Comment by tgtje** [comment]
Since no new comments or problems posted i think this may be closed (and reopened iff needed)
