### ISSUE TITLE
admins can change password for main admin?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1637]
On picture bellow I am logged as user that is set as admin (not main site admin). I  noticed they can change my password as main admin and block me out of site.
![image](https://cloud.githubusercontent.com/assets/5429548/15145230/abe16866-16b4-11e6-9461-4735fd2cd518.png)

Their rights are:
![image](https://cloud.githubusercontent.com/assets/5429548/15145356/56bda236-16b5-11e6-9973-2efc7c1860cd.png)

I need thay will be able to manage all user account except main site admin. So I need them be able other user passwords, but this they can do without permission manage all users

Maybe I missing some setting here..

**Comment by CaMer0n** [comment]
Regular admins can no longer edit pwds or admin-perms of main admin. 
If two admins are set as main-admin (perms=0) then the one with the lower USERID can edit the other. -  typically the one who installed e107 can edit anyone.
