### ISSUE TITLE
error message after update user account

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1639]
I don't use extented fields, but after updating user account there is this error:
![image](https://cloud.githubusercontent.com/assets/5429548/15145940/aee276f0-16b8-11e6-9844-d231d4ccea4d.png)

![image](https://cloud.githubusercontent.com/assets/5429548/15145955/c6ac28a8-16b8-11e6-9a07-a69042eff63c.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I believe I fixed this recently. Is it still an issue for you?

**Comment by Jimmi08** [comment]
@CaMer0n Thanks
