### ISSUE TITLE
upgrade from 1.4 to 2.0  

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1642]
I noticed before problem with never ending upgrade, but I can't find it now. I had the same problem and maybe I found reason.
1. on localhost, old 1.0.4 site, download upgrade package, unpacked 
2. upgrade process. Update core database structure OK,   Update from 1.x to 2.0 just didn't want to finish
3. checked debugger:
   ![image](https://cloud.githubusercontent.com/assets/5429548/15172321/b1da1672-1755-11e6-9c54-4c5335282518.png)
   ![image](https://cloud.githubusercontent.com/assets/5429548/15172337/c3c10062-1755-11e6-991b-14461405257d.png)

e_MEDIA was empty.
I added to e107_config.php :

```
$MEDIA_DIRECTORY       = 'e107_media/';
$SYSTEM_DIRECTORY    = 'e107_system/';
```

It didn't help. I checked if e107_media exists, but it was empty, just index.php. 
So I copied content from some v2 installation, renamed folder name (hash) according e107_system and upgrade finished and site is working  now. 

Else one note. I had error in Slovak lang file (too much ""), but 1.0.4 worked, but v2 not. Maybe it would be good idea to switch to English before upgrade (avoid blank page).

**Comment by Jimmi08** [comment]
Next observation. If somebody uses as Frontpage something different than index or news (in my case some AACGC plugin page), result after update is blank page, but it's not version 2 issue.  Old plugin needs to be rewrite this way:
```
//require_once("../../class2.php");    not working in v2 as frontpage

if(!defined('e107_INIT'))
{
	require_once('../../class2.php');
}
```
So good idea is switch to index.php before upgrade. (Or use debugger, but not all know how to use it)

**Comment by CaMer0n** [comment]
@Jimmi08 Since upgrade issues are so difficult to reproduce as every install is slightly different, if you can message me in cases like this BEFORE doing any modifications or work-arounds, then perhaps we can fix some of these issues.

**Comment by Jimmi08** [comment]
@CaMer0n It was on localhost. I didn't do any changes into core except e107_config. This post was most about what people should check before they start about how upgrade doesn't work and that they get white page. After upload files from localhost (full site) on server, upgrade went without problems (except paths, that was server issue).
But I still need to do database update each time when it checks something, I just don't have time to look at it. But update is always finished (green tick), not as before .

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 !! Normally these values:

    $MEDIA_DIRECTORY       = 'e107_media/';
    $SYSTEM_DIRECTORY    = 'e107_system/';
...should be automatically generated internally if they are missing from e107_config.php

**Comment by Jimmi08** [comment]
Probably fixed. Not have old version to test this.
