### ISSUE TITLE
Bug? Theme download not working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1643]
I've grabbed the newest files from here, and donne a clean install online, but somehow the theme download is not working:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/15175047/75f1862a-175c-11e6-82fb-5664c5109c49.jpg)

The download box simply shows the theme manager screen again....

**Comment by LaocheXe** [comment]
Updated the files via sync to github - didn't run into this issue.

**Comment by CaMer0n** [comment]
I can't reproduce it either. Server related issue?

**Comment by rica-carv** [comment]
Go figure out, now is working......
Grrr, these gremlins are really annoying.....

**Comment by Moc** [comment]
Welcome to the development world haha. 

Btw, I've had the same issue happen to me as well and I don't know what's causing it.

**Comment by willem010** [comment]
sound like a permission / ownership issue to me?

**Comment by LaocheXe** [comment]
heck you wanna talk about grimlins - new plugin I am working on, added site preferences and I can't edit them, when I do I get a 403 forbidden error lol funny as hell - works on another site tho lol

**Comment by CaMer0n** [comment]
@LaocheXe Do any of your preferences contain file-paths? Could be mod-security being triggered.
