### ISSUE TITLE
PHP errors in Custom Pages list

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1644]
In debug mode I see these errors at the end of the page :

Warning array_key_exists() expects parameter 2 to be array, boolean given, Line 58 of /home/polyamou/www/e107_plugins/log/e_shortcode.php
Warning in_array() expects parameter 2 to be array, null given, Line 4736 of /home/polyamou/www/e107_handlers/e_parse_class.php
[...]

**Comment by Moc** [comment]
Thank you, the developers are aware of these and will be worked through on lower priority. There is no need to report them in the future. Thanks though :+1:
