### ISSUE TITLE
Cannot update menu content

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1645]
I try to update the content of one of my menu entries but when I try to save (Update button) it blocks and the focus goes to the first field (Menu name), cf screenshot attached :

![e107menus](https://cloud.githubusercontent.com/assets/4124597/15176719/bb308870-176c-11e6-9d1a-52a6bbdbf9d0.png)

But I don't get why as the name uses only ASCI characters.

**Comment by Moc** [comment]
Maybe it is the dash (`-`) which is the troublemaker?

**Comment by pierre0042** [comment]
Removing the dash doesn't change anything

**Comment by Alex-e107nl** [comment]
Try it without capitals...

**Comment by pierre0042** [comment]
Without capitals it works, thanks. But why ?...

**Comment by CaMer0n** [comment]
@pierre0042 It's a coding reference key. I have updated the help tip.

**Comment by pierre0042** [comment]
Thanks
