### ISSUE TITLE
TinyMce JS Cache Issue. 

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1646]
With WYSIWYG enabled in preferences the buttons for font sizes (not sure of the correct term) appear momentarily then disappear when Forum new post or reply page loads.
![image](https://cloud.githubusercontent.com/assets/15772899/15177486/36bbfcae-1768-11e6-8966-13cc253a74a3.png)
If I Disable WYSIWYG the shorter menu appears and stays on the page:
![image](https://cloud.githubusercontent.com/assets/15772899/15177510/52b1d5be-1768-11e6-97ce-8dd6e0190b3f.png)

**Comment by CaMer0n** [comment]
Looks like javascript/Tinymce is failing to load.

**Comment by martyshep** [comment]
I disabled JS/CSS caching and the toolbar appears now.  What would each of the caching parameters enable/disable affect?
![image](https://cloud.githubusercontent.com/assets/15772899/15196470/4caf7f34-17c4-11e6-8cbc-6bea88eaabf3.png)

**Comment by CaMer0n** [comment]
JS/CSS caching will combine the local js files into a single file, and the same for local css files.

**Comment by Jimmi08** [comment]
Are you use English in admin area or other lang? I noticed that buttons are
only in English.  Or better som translated js in tinymce is missing in my
language.

Dňa streda, 11. mája 2016 martyshep <notifications@github.com> napísal(a):

**Comment by martyshep** [comment]
I am only using English as the language in all areas of the site.
