### ISSUE TITLE
Thumb.php - Images do not always appear..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1648]
Github today 8037 commits, images do not always appear on pages and news, only with a refresh, in the mediamanager they do not show anymore in the preview, clicking on a image does show it (popup)

PHP Version 5.6.17 on e107.nl cache is off debug is off English and Dutch doe snot change anything..
Cache on does not change it..

**Comment by CaMer0n** [comment]
Did you try clearing the thumbnail cache?

**Comment by Alex-e107nl** [comment]
Hi, deleting thumbnail cache dit not help.. using thump.php from 10-5 did.. all images show direcly and always now..

**Comment by CaMer0n** [comment]
@Alex-e107nl Please try the latest version from Github, thanks.

**Comment by Alex-e107nl** [comment]
Hi Cameron, tested with git 5 minutes ago... it did not helped, same problem, mediamanager does not show images, only links and on the front images sometimes disappear and only show after refresh.. 
Deleted thumbnail cache but no change.. sing thump.php from 10-5 again and everything is normal...

**Comment by CaMer0n** [comment]
@Alex-e107nl Could you please test again?

**Comment by Alex-e107nl** [comment]
Github of today works! THX!

**Comment by CaMer0n** [comment]
Thank you @Alex-e107nl
