### ISSUE TITLE
Search page does not find any result, never

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1649]
Even if I enable or not the "match full word" option, and If I use PHP or MySQL methods, all the results are "without results".

Doesn´t matter if I add the full word to mach or a partial word, nothing is found in any category, users nor custom plugins...

Could someone confirm if its only happening to me please?
- Nes

**Comment by Alex-e107nl** [comment]
Hi standard settings in Search on https://www.e107.nl/search.php?q=account&r=0&s= works...

**Comment by nesjett** [comment]
Thank you for your help, Then Ill have to find the issue by myself.

Grts,
- Nes

**Comment by Moc** [comment]
@nesjett Are you still experiencing this issue? :)

**Comment by Moc** [comment]
Closing due to the lack of feedback. If you are still experiencing the issue, please let us know and I'll re-open.
