### ISSUE TITLE
Question: Guidelines to plugin creation / modification.

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1650]
After [my question regarding the new vstore plugin](https://github.com/e107inc/e107/pull/1635#issuecomment-218731427), and since i really need to override forum shortcodes, i'm looking to see if someone could tell me wich are the guidelines to create / modify plugins...

- For instance, shortcodes & plugin code are to be on the same file, as is in [vstore.class.php](https://github.com/e107inc/vstore/blob/master/vstore.class.php) ??? No more shortcodes outside in external files???

**Comment by LaocheXe** [comment]
Ive worked on a few plugins and two of them use e_shortcode.php. nothing i know of about myplugin.class.php, could be that vstore needed that file to store stuff...

**Comment by CaMer0n** [comment]
@rica-carv I took a shortcut with vstore to put the shortcodes in the same file. chatbox menu does this also. But the standard way would be to have a separate file. The file-name is also unimportant. (vstore.class.php)

**Comment by rica-carv** [comment]
Wouldn't it also be need to store all the shortcodes variables in the scvars?
Because of allowing to override the shortcodes?
Or there's no need for the scvars to allow shortcodes override???

**Comment by Moc** [comment]
> shortcodes & plugin code are to be on the same file, as is in vstore.class.php ??? No more shortcodes outside in external files???

I would recommend sticking to the currently documented ways, and create a separate file for th shortcodes. This to prevent a mess, we need standardized ways. Either use a separate file, or add it to the documentation to also allow other ways. 

/ cc: @CaMer0n

**Comment by Moc** [comment]
@rica-carv Can this issue be closed or is there still info required?

**Comment by rica-carv** [comment]
@Moc Guess it can be closed. If i need it agian, i'll reopen it... Thanks.
