### ISSUE TITLE
Featurebox is not looking for featurebox_template.php in theme anymore..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1651]
Hi, Featurebox is not looking for featurebox_template.php in theme anymore.. i always place a copy of it in the theme templates folder because of the SETIMAGE: w=1140&h=460&crop=1 adjustment but it did not work anymore, the featurebox_template.php in e107_plugins/featurebox/templates does...

**Comment by CaMer0n** [comment]
@Alex-e107nl Is it in [yourtheme]/templates/featurebox/ ?

**Comment by Alex-e107nl** [comment]
Now it is... sorry :-)
