### ISSUE TITLE
gallery not working

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1652]
![image](https://cloud.githubusercontent.com/assets/1758577/15267379/fe6331b4-19c0-11e6-8519-097e44d0dc31.png)

if delete in gallery.php the line "gallery_load_prettyphoto();" the working the gallery

**Comment by lonalore** [comment]
Please check your `error.log` for more details. 

In my opinion the problem is in your `e107_languages/YOURLANGUAGE/lan_library_manager.php` language file. Check double quotes according to this issue: https://github.com/e107inc/multilan/issues/9

**Comment by schlrech** [comment]
@lonalore, thank you the language file was the problem :-)
