### ISSUE TITLE
what is wrong with this text? editing in admin UI issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1653]
I have own plugin, used plugin builder. Absolutely standard textarea field.
I need to copy a lot of strings in to record and with one I got this error (one maybe from 400). 
![image](https://cloud.githubusercontent.com/assets/5429548/15267981/434934b2-19d1-11e6-8447-6b50ed7346da.png)

If I use normal editing, after clicking update I get blank page (white).  Others paragrafs were copied absolutely without problems.  After narrowing to what words cause problem, I found that you can not insert these words
![image](https://cloud.githubusercontent.com/assets/5429548/15267990/9ad4a194-19d1-11e6-81e0-91c349166e5e.png)

Try it in news title, the same issue. Thanks

**Comment by Moc** [comment]
Its the 'fetch'. At the moment I don't have access to my PC but I think it's somewhere in the e_parse_class.php file

**Comment by Jimmi08** [comment]
You can insert "fetch"  but you can't insert fetch with space "fetch ".  Result is blank page if you insert it in normal edit window. If you use inline editing, result is Bad request from above. 

Could you label this as bug, please?

**Comment by CaMer0n** [comment]
The code is here on line 3333

	$regex = "/(wget |curl -o |fetch |lwp-download|onmouse)/i";
			if(preg_match($regex,$input))
			{
				header('HTTP/1.0 400 Bad Request', true, 400);
				if(deftrue('e_DEBUG'))
				{
					echo "Bad Request: ".__METHOD__." : ". __LINE__;
				}
				exit();
			}

To prevent commands like this: 

    fetch -o myfilename.blah http://someserver/somedir/afile.txt

Any suggestions?

**Comment by Jimmi08** [comment]
What about to add -o  similar as with curl? 
`$regex = "/(wget |curl -o |fetch -o |lwp-download|onmouse)/i";`

When I know about this, I can live with it. And  looks just I noticed this, so... it's not really important.

**Comment by Jimmi08** [comment]
@CaMer0n now this = insert text with word "fetch" in admin_ui in textarea field ends with blank page.  With bbarea type you can't insert text at all. 
Fetch is normal English word.
