### ISSUE TITLE
i can not send mail via smtp

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1655]
![image](https://cloud.githubusercontent.com/assets/1758577/15273082/e444b306-1a8e-11e6-9bf2-70f665382594.png)

i don't know where is the problem
i have the newest update from github

**Comment by tgtje** [comment]
Just was informed about same issue; update was setting system to use smtp (was php). Smtp does not function. ( not by smtp or smtp with tls/ssl). Can not actually confirm it (not tested), although it looks very similar...

**Comment by Jimmi08** [comment]
I have version from 30.4., smtp works (send test email)
Just updated latest github (manually, not from  admin area)
My setting:
![image](https://cloud.githubusercontent.com/assets/5429548/15273554/8a046cf6-1a9d-11e6-94f8-6ab1c757dd1b.png)
**If you use Firefox, and debugger, you can get this report**
![image](https://cloud.githubusercontent.com/assets/5429548/15273559/aba52918-1a9d-11e6-9cf7-4e15a28f4dc2.png)
Now I need to find why I get blank page after trying to github update.

**Comment by CaMer0n** [comment]
@schlrech Some hosting companies block sending email via SMTP. It may be worth checking with them.

**Comment by schlrech** [comment]
i checked my provider
![image](https://cloud.githubusercontent.com/assets/1758577/15274675/ae487830-1ab8-11e6-963e-622fda2a993e.png)

that is OK with e107 is this not working

**Comment by schlrech** [comment]
with debugging
![image](https://cloud.githubusercontent.com/assets/1758577/15274826/4d217756-1abc-11e6-9569-4f7ea2415371.png)

**Comment by CaMer0n** [comment]
@schlrech If this is still an issue, I'll be happy to troubleshoot it with you in the chatroom.

**Comment by Grimston** [comment]
Not sure if this is related to this issue, but the password field will convert any special characters like $ to the HTML entity. This will cause failures in authentication.

**Comment by schlrech** [comment]
Thanks @cameron

**Comment by cameron** [comment]
Wrong Cameron :0






On Thu, Jun 2, 2016 at 10:31 PM -0700, "René Schlegel" <notifications@github.com> wrote:












Closed #1655.
