### ISSUE TITLE
Media Manager no preview of pictures

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1656]
what do i have to do to get the preview? thx

![image](https://cloud.githubusercontent.com/assets/1758577/15275899/42fc197c-1ad8-11e6-8977-d53ca130fb76.png)

**Comment by CaMer0n** [comment]
Please open one of the image links in a new tab/window. Is there an error message?

**Comment by schlrech** [comment]
no. no errors
![image](https://cloud.githubusercontent.com/assets/1758577/15277280/a01c7468-1aff-11e6-832c-3742518c56b1.png)

**Comment by CaMer0n** [comment]
Are you using the latest files from today?

**Comment by schlrech** [comment]
No, Sorry
now using the newest and is ok, thx
