### ISSUE TITLE
problem with featurebox after update

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1657]
This was working before, now I can't get featurebox image displayed.  (latest github)

Admin is correct:
![image](https://cloud.githubusercontent.com/assets/5429548/15284418/6e851606-1b51-11e6-8897-42c076220e6f.png)

I am using template in theme:

```
  {SETIMAGE: w=900&h=900&crop=1}
       <div class="col-md-6 col-sm-5 hidden-xs carousel-img-wrap">
               <div class="carousel-img">
                    <img src="{FEATUREBOX_IMAGE=src}" class="img-responsive animated bounceInUp" alt="Image">
                    </div>
       </div>
```

Path is this:
![image](https://cloud.githubusercontent.com/assets/5429548/15284441/967e5bb8-1b51-11e6-8597-8883e5f4dcee.png)

Image is there:
![image](https://cloud.githubusercontent.com/assets/5429548/15284471/b34ed524-1b51-11e6-94e0-ede3acf3f315.png)

But images in news work
![image](https://cloud.githubusercontent.com/assets/5429548/15284513/f8b2659a-1b51-11e6-831e-ed70202a040f.png)

@CaMer0n  this is not site with server issues, so it can't be related.  Thanks

**Comment by Jimmi08** [comment]
I needed to hardcoded this and I noticed that if I remove "a" in image path, path to image works.
![image](https://cloud.githubusercontent.com/assets/5429548/15284704/4bb475fc-1b53-11e6-8764-a23be4e8e379.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Try changing crop=1 to crop=0

**Comment by Jimmi08** [comment]
Yes, this helped.

**Comment by Jimmi08** [comment]
@Moc Could you remove label about feedback please. 
@CaMer0n  Is using crop=0 way how it should work and this can be closed or is this just workaround to get this work 
Thans

**Comment by Jimmi08** [comment]
Closing, fixed for now.
