### ISSUE TITLE
No Avatar option and photo delete

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1658]
![image](https://cloud.githubusercontent.com/assets/1758577/15296965/1a031d52-1b98-11e6-870a-ed169ab61e96.png)

there is no tickbox to delete the phot and no option to upload an avatar

**Comment by tgtje** [comment]
Just commenting : synced just 5 minutes ago (wamp) (no issues).
Did same already yesterday.. also not replicable
I do miss a blank avatar on above screenshot. Error or issue lies deeper....(try debugging)
This is a normal NEW signup on the very latest files (15 minutes ago; dd 17-05)
![log](https://cloud.githubusercontent.com/assets/1811857/15336485/1e70d55c-1c77-11e6-9dbe-631cc207d7c0.jpg)

**Comment by schlrech** [comment]
![image](https://cloud.githubusercontent.com/assets/1758577/15347042/f071c2aa-1cbd-11e6-8c02-c09875c18d69.png)

**Comment by schlrech** [comment]
the thick box should always be visible which means also whilst having disabled the photoupload.

**Comment by tgtje** [comment]
The warning may be from browser, hard to tell. As for the Failing parts ?? i do see however width = 0 
Do not know where it comes from.

**Comment by schlrech** [comment]
i set the height in prefs with -1. But after having changed anything, the system automatically sets it to 0 because it's a numeric field. I don't want to fix the height e.g. to 100px because then the image becomes distorted. sorry for the confusion!
