### ISSUE TITLE
Question: Plugin Admin Nav

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1659]
I am working on a plugin that has a lot of manage/create functions. Right now the navigation looks like this (and it is some what ugly) (also this is all in one admin_config.php)

![capture](https://cloud.githubusercontent.com/assets/5818022/15298761/a277a0d6-1b66-11e6-89fe-ff4f881fb805.PNG)

The code used:
        'other1/create'     => array('caption'=> 'Create Awards', 'perm' => 'P'),
        'other2/create'     => array('caption'=> 'Create Badges', 'perm' => 'P'),
        'other3/create'     => array('caption'=> 'Create Medals', 'perm' => 'P'),
        'other4/create'     => array('caption'=> 'Create Patches', 'perm' => 'P'),
        'other5/create'     => array('caption'=> 'Create Pins', 'perm' => 'P'),
        'other8/create'     => array('caption'=> 'Create Ribbons', 'perm' => 'P'),
        'opt1'              => array('caption'=> 'Test1', 'divider'=> true),

I use the divider - is there another type to use to make it look like something like this:
![capture2](https://cloud.githubusercontent.com/assets/5818022/15298848/09b3fccc-1b67-11e6-8562-ed9d83233c51.PNG)

**Comment by CaMer0n** [comment]
FOr now, You'll want to use: 

     'main/opt1'         => array('header'=>"My Header"),

The styling on it still needs to be corrected for Bootstrap 3 in the core theme.

**Comment by Jimmi08** [comment]
```
		function init()
		{
			if(E107_DEBUG_LEVEL > 0)
			{
				$this->adminMenu['opt3'] = array('divider'=>true);
				$this->adminMenu['main/update'] = array('caption'=>"Redo v1.x Forum Upgrade", 'perm'=>0, 'uri'=>'{e_PLUGIN}forum/forum_update.php');



			}

		}
```
