### ISSUE TITLE
Blank screen github of today..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1660]
Github of today..     8,049 commits e107 blank screen, admin and front.. uploaded files 2 times to make sure its not a ftp problem... Going back to the git of 13-5..
 

```
<!doctype html>
<html lang="nl">
<head>
<meta charset='utf-8' />
```

**Comment by Moc** [comment]
Sounds like a PHP fatal error which is suppressed. Use the debug tool to get more info so it can be fixed. 
Change the url to `/index.php?[debug=basic+]`

**Comment by tgtje** [comment]
Just commenting : synced just 5 minutes ago (wamp) (no issues).

**Comment by Alex-e107nl** [comment]
Oke,
i've made a mistake... also dropped the vstore plugin in it.. with the debug tool i've got this message..
`Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/home/andrekoot/domains/e107.nl/private_html:.:/usr/local/lib/php') in /home/andrekoot/domains/e107.nl/private_html/e107_plugins/vstore/vstore.class.php on line 20`

Dropped it.. sorry :-)

**Comment by tgtje** [comment]
This is the second message having this using vstore.. Do not be sorry... it is at least helpfull ( message was on gitter)
