### ISSUE TITLE
Question - e_frontpage.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1663]
Is posible to have for one plugin more lines/entries in frontpage?  I am able to create multipage selection, but content plugin before had one line for each category and in each category more pages.  I looked like this:

![image](https://cloud.githubusercontent.com/assets/5429548/15373770/71e65574-1d47-11e6-92cb-664b94dda82a.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Did you try sending a multidimensional array? 
eg. 

    $opts['Content'] = array('content main page', ..... );
    $opts['Article'] = array('article main page',  ..... );
    $opts['Review'] = array('review main page',  ..... );

**Comment by Jimmi08** [comment]
@CaMer0n thanks, I tried something similar, but I have always problems with arrays (syntax), so I will try this. But there are other issues (neverending redirection), I think that maybe it's better to delete this and use custom link, if somebody wants this. 

By the way, do you want to know when I find old code  that doesn't work? I don't want you spend time on it, because it was easy to replace it with retrieve(), so just for your information (result was nothing): 

```
	if($sql -> db_Select('pcontent', "content_meta", "content_id='".intval($qs[1])."'")){
		list($row['content_meta']) = $sql -> db_Fetch();
   display metas
	} 
```

**Comment by Jimmi08** [comment]
@CaMer0n from the look at admin/frontpage.php I think that it's not possible for frontpage (other e_ files  use different way how to manage output from getaddons(). - 2x foreach, not one time as in frontpage.php. . I could be wrong, of course.
