### ISSUE TITLE
Feature Request: Social Login Preference to update DisplayName

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1670]
So can we make an option to enable or display the Steam Login auto-update user display name? Editing a user display name after they sign up/login with Steam it stays with what their Steam account is. Can we add a option to allow the auto-update and to disable it?

**Comment by CaMer0n** [comment]
Please try me in the chatroom.

**Comment by CaMer0n** [comment]
@LaocheXe Can we close this now?

**Comment by LaocheXe** [comment]
yes

**Comment by F1Racer68** [comment]
Steam login to my e107 site was working flawlessly until April 5th, 2018. Since then, all attmepts to login with Steam fail to login, and I am getting "User attempted to login with unrecognised user name" errors in the admin panel.

Any ideas on how I can resolve this?

**Comment by LaocheXe** [comment]
@F1Racer68 - Steam updated something that screwed stuff up - #3097 <--- I explain everything in that post - you will need to export the user database and make edits to the user_xup

**Comment by F1Racer68** [comment]
Thanks, just found that one and reposted my question there. Working on that now, thanks.
