### ISSUE TITLE
unserialize - doesn't work for arrays

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1671]
Hi, I am trying to replace deprecated

```php
$eArrayStorage->WriteArray($content_pref)
``` 
with 

```php
e107::unserialize($content_pref);
``` 

But it doesn't work, because $content_pref is array and unserialize() has this:

```php
        if(is_array($ArrayData))
        {    
            return false;
        }
```
This is not in deprecated WriteArray() function.   Is this change intended? Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 You're trying to replace writeArray with the opposite function. 
e107::serialize() = writeArray()
e107::unserialize() = readArray()

**Comment by Jimmi08** [comment]
@CaMer0n 
Thank you, just one line was replaced uncorrectly, I didn't notice it.  

But it still didn't want to work. The reason is this difference:
![image](https://cloud.githubusercontent.com/assets/5429548/15626490/2976405c-24c6-11e6-85bd-34c2ffe05a0b.png)

![image](https://cloud.githubusercontent.com/assets/5429548/15626492/2d5c7de4-24c6-11e6-82c3-e870b5afe51e.png)

**Comment by CaMer0n** [comment]
Most likely the doc needs updating. 
If this wasn't working, none of the site prefs would be loading correctly.

**Comment by Jimmi08** [comment]
Yes, I just wanted to let you know. Thank you for your help.
