### ISSUE TITLE
[Identified] [Bug] [Important] Twitter auth sometimes crashes the whole site

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1672]
For some reason, the auth works well sometimes, but other times I get a blank page with this message:

'''
Fatal error: Uncaught exception 'Exception' with message 'User profile request failed! Twitter returned an error. ' in C:\xampp\htdocs\pathToMySite\handlers\hybridauth\Hybrid\Providers\Twitter.php:117 Stack trace: #0 C:\xampp\htdocs\pathToMySite\handlers\hybridauth\Hybrid\Provider_Adapter.php(228): Hybrid_Providers_Twitter->getUserProfile() #1 C:\xampp\htdocs\pathToMySite\handlers\user_model.php(1747): Hybrid_Provider_Adapter->__call('getUserProfile', Array) #2 C:\xampp\htdocs\pathToMySite\handlers\user_model.php(1747): Hybrid_Provider_Adapter->getUserProfile() #3 C:\xampp\htdocs\pathToMySite\handlers\user_model.php(1806): e_user->tryProviderSession(false) #4 C:\xampp\htdocs\pathToMySite\handlers\user_model.php(1502): e_user->load() #5 C:\xampp\htdocs\pathToMySite\handlers\e107_class.php(881): e_user->__construct() #6 C:\xampp\htdocs\pathToMySite\handlers\e107_class.php(1551): e107::getObject('e_user') #7 C:\xampp\htdocs\nestor\desafiogamer\class2.php(1692): e107::ge in C:\xampp\htdocs\pathToMySite\handlers\hybridauth\Hybrid\Providers\Twitter.php on line 117
'''

Also, when I get this error, I cant access to the site anymore, even deleting site and browser cache throws it, not sure why...

I´m using Github latest rev

Seems that you forgot to add a tryCatch on class2.php, when I manually add this catch, and I prevent the next functions to execute (for example get user token, which tells me that is beign calling onto null) by adding a die() statement, the page never loads, I just get a blank page loading...

Related to #13 , similar to #34 ?
Thank you,
- Nes

**Comment by tgtje** [comment]
Just commenting : as far as i know , Google Plus, Facebook and the other Social features will ask you for a “return” URL you won’t be able to make the social features work locally . Best for this networking to run tests on live servers.. ( correct me if i am wrong).

**Comment by nesjett** [comment]
You can get it working if you configure your computer host to point, for example 127.0.0.1 local.mydomain.com so you set as callback url mydomain.com and if you request it from local.mydomain.com it will work.

As I said, it worked, I got signed up with twitter on my local page, the problem came when I logued out and loged in some more times to test it, exaclty when I pressed the signup/login button when I already was registered with twitter.

PD: I dont know what to do now, Im getting a blank page even with different browsers, disabling from db twitter keys, or setting the plugin as "unisntalled" with the flag doesnt make a difference

**Comment by CaMer0n** [comment]
@nesjett Using phpmyadmin you could try deleting the created user entry.

**Comment by nesjett** [comment]
@CaMer0n I´ve already deleted that user too, but site still doesnt works,  even restarting apache does not make a difference.

The site is down for wome reason.

**Comment by CaMer0n** [comment]
@nesjett Perhaps, you may need to revoke the twitter permissions for your site in your twitter account?

**Comment by nesjett** [comment]
Nope, I just revoked the app permisions and generated new Keys to force the site to fail if tries to call the api...

Really I cant mind what is happening, I just added a try catch to class2, but Its comented now...

**Comment by CaMer0n** [comment]
Recently upgraded hybridAuth version. Please create a new issue if necessary.
