### ISSUE TITLE
[Enhancement/Bug] Better error reporting on Hybridauth

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1675]
There are a lot of errors that should be catched up, more specifics, with better info.

Others, like comented here #1672 are real bugs, with uncaught exceptions.

And there should be an error message when a user tries to log in with a provider, but the email is already registered in the site (by normal registration), currently this does nothink, the user doesnt know what happens, its just like a "page reload", so we have to show a message about this.

Grts,
- Nes

**Comment by Moc** [comment]
I'm going to close this one since HybridAuth / social logins have had many changes in v2.3.0. Please open up a new issue if you still experience problems.
