### ISSUE TITLE
Missing Tinymce4 language files

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1678]
Error message:
![kepernyokep_2016-05-31_22-54-12](https://cloud.githubusercontent.com/assets/6043821/15690325/4e58bb9c-2783-11e6-9a0c-8a145c2063dd.png)

I fixed it with downloading this language file:
![kepernyokep_2016-05-31_23-07-29](https://cloud.githubusercontent.com/assets/6043821/15690584/7ea9e590-2784-11e6-862b-a5161218cb5e.png)

But it only worked after I renamed the file to "hu.js" and changed the key to "hu" from "hu_HU" in the file:
![kepernyokep_2016-05-31_23-10-36](https://cloud.githubusercontent.com/assets/6043821/15690666/e7f62c02-2784-11e6-8c97-733e09bffada.png)
...I think because of the wrong usage of language code in this line: https://github.com/e107inc/e107/blob/master/e107_plugins/tinymce4/wysiwyg.php#L232
In my opinion it should be "hu_HU" instead of "hu".

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/1585

**Comment by lonalore** [comment]
@aducom yes, but I want to use TinyMce editor in hungarian not in english. So this is not a fix for this issue. The fix would be that $tinylang array should contain correct language codes according to this: https://www.tinymce.com/download/language-packages/
```php
$lang = e_LANGUAGE; // 'English'; //Quick Fix e_LANGUAGE
$tinylang = array(
	"Arabic" 	=> "ar",
	"Bulgarian"	=> "bg_BG",
	"Danish" 	=> "da",
	"Dutch" 	=> "nl",
	"English" 	=> "en",
	"Persian" 	=> "fa",
	"French" 	=> "fr_FR",
	"German"	=> "de",
	"Greek" 	=> "el",
	"Hebrew" 	=> "he_IL",
	"Hungarian" => "hu_HU",
	"Italian" 	=> "it",
	"Japanese" 	=> "ja",
	"Korean" 	=> "ko",
	"Norwegian" => "nb_NO",
	"Polish" 	=> "pl",
	"Russian" 	=> "ru",
	"Slovak" 	=> "sk",
	"Spanish" 	=> "es",
	"Swedish" 	=> "sv_SE",
);
```
...and of course, tinymce4/lang folder should contain all language files for supported languages.

**Comment by aducom** [comment]
I agree. I reverted back the change as it solved the disappearance of the editor. But it's not 'the fix' obviously.

**Comment by Jimmi08** [comment]
**This file should be part of language pack**, with the correct name of file. My lang is correct, it's sk.js, but I see Hungarian had to be renamed. Tinymce itself shouldn't have both ways of file naming language files. It's weird. Why they use hu_HU but not sk_SK ?

**Comment by lonalore** [comment]
I think we should use original naming conventions from TinyMce's website. For example 'en_GB' is not equal with 'en_CA', or 'fr_FR' is not equal with 'fr_CH' ... etc. But you are right, these files should be part of language pack.

**Comment by CaMer0n** [comment]
:+1:  Pull-request welcome.

**Comment by lonalore** [comment]
Is that OK? Sorry for commit message, it was a Ctrl+C :D

**Comment by CaMer0n** [comment]
Thanks! Looks good. Btw. We're not limited to only those languages. Any language supported by TinyMce can be added to the array list, as long as it appears in e107's language_class.php

**Comment by lonalore** [comment]
Okay!

**Comment by lonalore** [comment]
Done! ;-)

**Comment by CaMer0n** [comment]
Thanks!

**Comment by kreossino** [comment]
hi,
After Updating with github does not work with Italian language, but yes with english.
in the directory langs I found a hit.js files and not it.js.
i have changed the filename but does not work with the new wysiwyg.php

**Comment by lonalore** [comment]
@kreossino please try this file: https://www.tinymce.com/download/language/it

**Comment by kreossino** [comment]
maked now but don't work with teh new wysiwyg.php

**Comment by lonalore** [comment]
I will try to debug it as soon as I get to the office. :)

**Comment by lonalore** [comment]
Okay, so here is what I did:
- I updated e107 files to the latest github files
- I downloaded [Italian language pack](https://github.com/e107inc/e107-v2.x-Language-Packs/tree/master/Italian) for e107
- I downloaded [Italian language file](https://www.tinymce.com/download/language/it) for TinyMCE4, and I extracted `it.js` file into `e107_plugins/tinymce4/langs/` folder
- I installed [Multilan](https://github.com/e107inc/multilan)
- I visited "Create news item" page on Admin UI and I switched to Italian language

Result:
![kepernyokep - 2016-06-23 - 09 01 26](https://cloud.githubusercontent.com/assets/6043821/16294624/e891adae-3921-11e6-81a3-387cb0313236.png)
