### ISSUE TITLE
Small issue with mail_manager_class.php

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#1680]
In mail_manager_class.php (in the /e107_handlers/ directory), and the **sendEmails** function, the parameter 'recipientData' can be specified as a string or an array.

If it is passed as a string, there's an instruction about 10 lines into the function that says:

```php
if (!is_array($recipientData))
{
  $recipientData = array('mail_recipient_email' => $recipientData, 'mail_recipient_name' => $recipientData);
}
```

But further down in the same function there's a foreach loop that reads like this:

```php
foreach ($recipientData as $recip)
{
...
if (false == $this->mailer->sendEmail($recip['mail_recipient_email'], $recip['mail_recipient_name'], $mailToSend, true))
}
```

If **$recipientData** is an array as constructed by:

```php
if (!is_array($recipientData))
```

...test, then "sendEmail" will fail with an error "You must provide at least one recipient email address" from class.phpmailer.php and the preSend function. So I _think_ it (the first quoted script section) should instead read:

```php
if (!is_array($recipientData))
{
  $recipientData = array(array('mail_recipient_email' => $recipientData, 'mail_recipient_name' => $recipientData));
}
```

EDIT: the code formatting doesn't seem to retain newlines so it looks a bit confusing - but I believe **$recipientData** should be returned as an array containing an array with the recipient email address and name, e.g.,

[Pastebin example](http://pastebin.com/YFDSVD0X)

**Comment by Moc** [comment]
@sbwMikael I've edited your issue to use the correct syntax, which allows for code highlighting and propper formatting. More info here: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by CaMer0n** [comment]
@sbwMikael Thank you for spotting this and providing the fix! :+1:
