### ISSUE TITLE
Why news editor cleans my "labels"?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1681]
I'm trying to use the tag `<label>` on news html editor. I succesfully do it in HTML, and after returning to the news list, it says the news is saved, but afterwards, the <label> tag is still missing from the news text!!!!
I'm currently using this string:
`<label for='work5'>Lorem ipsum dolor sit amet</label>`
News editor says it sucessfuly saves it, but it really deletes it......
Can't labels be used in news texts???

**Comment by Moc** [comment]
@rica-carv Still an issue?
