### ISSUE TITLE
/forum returns: Fatal error Call to a member function parse_scbatch() on a non-object e107_plugins/forum/forum_shortcodes.php on line 4

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1682]
/forum should display all forums available to the userclass to see what post totals are in each forum.  Since recent sync with github, /forum displays error:  
Fatal error: Call to a member function parse_scbatch() on a non-object in /home/threeper/public_html/3per/e107_plugins/forum/forum_shortcodes.php on line 4

Site version is v2.1.2Git

**Comment by rica-carv** [comment]
Something is wrong with that message, since forum_shortcodes.php should be located in e107_plugins/forum/shortcodes/batch/, and not in e107_plugins/forum/, as is in your error message...
Do you have the forum_shortcodes.php file in the folder i mentioned (e107_plugins/forum/shortcodes/batch/) ?

**Comment by martyshep** [comment]
Great spot thanks @rica-carv !  I did a combination of Sync from Git using Gitdesktop and developer mode on the website and it looks like it left files in /forum when they should be now in /shortcodes/batch.  I've deleted all these files from /forum now.
![cpanel file manager v3 2016-06-03 15-56-22](https://cloud.githubusercontent.com/assets/15772899/15782909/f09658d4-29a3-11e6-9dea-26c8eb3cc06b.png)

**Comment by rica-carv** [comment]
Weird how you got those files there..... Real weird....
The forum_shortcodes.php files is brand new, and never was located under e107_plugins/forum.......
Real weird!!!
Do you got forum working after deleted the files?
