### ISSUE TITLE
Issue: Forget Password

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1684]
I have people reporting of the Forget Password email is giving them a wrong password. They do the steps, get an email with a new password but that password doesn't work at all. They are getting incorrect login message.

**Comment by LaocheXe** [comment]
Correction, the site send an email with a link that take the user to the site which shows a new password but that password doesn't work*

**Comment by CaMer0n** [comment]
Please update and re-test.

**Comment by LaocheXe** [comment]
![capture](https://cloud.githubusercontent.com/assets/5818022/16317565/5c192304-3951-11e6-9f9b-307cc0398e63.PNG)

Shown this for account TestDummy - still cannot login with email address, but can with UserName

**Comment by CaMer0n** [comment]
Do you have user-audit turned on in your logs for user-login and password reset?

**Comment by LaocheXe** [comment]
Yes I do


![capture](https://cloud.githubusercontent.com/assets/5818022/16358541/5c43db54-3adb-11e6-8844-5d2ff00a272f.PNG)

**Comment by CaMer0n** [comment]
@LaocheXe Thanks. Please update and try again.
