### ISSUE TITLE
question how to work with pages in theme shortcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1685]
Hi,
with news I can do this in theme shortcodes:
```
  $sc = e107::getScBatch('news');
  $data = $sc->getScVar('news_item');
```
but what is code for using this for page?

I tried this, but $data is empty.
```
  $sc = e107::getScBatch('page');
  $data = $sc->getScVar('page');
```
Thanks

**Comment by CaMer0n** [comment]
I believe this should do it: 
     
    $data = $this->getVars();  // (ie. $this->var);

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/1484

Thank you

**Comment by Jimmi08** [comment]
For anybody who needs this. This works in theme_shortcodes.php:

```
	function sc_chaptersef()
	{
  		$sc   = e107::getScBatch('page', null, 'cpage');
  		$data = $sc->getVars();
		return vartrue($data['chapter_sef'],'chapter-no-sef');
	}	
```
