### ISSUE TITLE
[Question] Shouldn't theme shortcodes be global theme templates available?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1688]
I'm currently having an issue with a theme i'm designing for another project of mine, and as far i've tested before, theme_shrotcodes.php defined some shortcodes (and overrided others, if needed), that were available to all templates inside the theme (theme.php, news_templates, etc.)
The issue is that i'm using current github e107 version, always kept to date, and right now i can't use a defined theme shortcode outside the theme.php template (for instance, in custom theme news_template, it won't display...) and also i can't override core shortcodes as i did before (for instace, can't even override news_summary shortcode on my custom theme news_template....)
Has anything changed, that i missed it?

**Comment by Jimmi08** [comment]
I tried this one day ago and last change in shortcodes was 14 days ago. I used it the way you use it in your theme. Just be sure, didn't you forget override variable?

**Comment by rica-carv** [comment]
@Jimmi08 No, i'm using the override variable: `public $override = true;`
Somehow, it doesn't work.....

**Comment by rica-carv** [comment]
Goddamn it, definetly i'll stop using XAMPP.....
I've uploaded all the files i was working to a webserver, and it works!!!
GRRRR......
