### ISSUE TITLE
question Database utilities export options

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1689]
At first, awesome feature.  
I just notice that normally I can save file to my computer, but when I tick "convert paths and images" , then file is saved somewhere and without FTP I am not able to download it. 
Is it purpose?

**Comment by rica-carv** [comment]
Maybe it won't fit here, but i have a v1.4 plugin, that's working more or less in v2, with automated database backup & email.
For me, it really does better than the current core database backup system....

**Comment by CaMer0n** [comment]
@Jimmi08 It tells you where it saved it. In the 'install' folder of  the theme.

**Comment by Jimmi08** [comment]
I swear that I didn't see this message before:
![image](https://cloud.githubusercontent.com/assets/5429548/15911295/7fa2b41c-2dcf-11e6-9f52-3dcb2096192b.png)
Sorry. And I didn't get that "convert" means save xml file too. 
Thanks 

@rica-carv maybe because this is not about backup, but about more easier way how to move data beetween installations and about create theme install.xml file easier way than manually write xml file.
