### ISSUE TITLE
duplicate LAN string in English lan_mailout.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1690]
Just noticed this:
![image](https://cloud.githubusercontent.com/assets/5429548/15890381/8164b670-2d6f-11e6-8424-8a31d5721732.png)
Not important.

**Comment by tgtje** [comment]
Just help > suitable LAN would be LAN_MAILOUT_261  (not in use) for any of the 2.) (sorry pc in overhaul)
Line 277 = handlers/mailout_admin_class.php  > smtp port (= line 2159 )
Line 282 = handlers/ mailout_class php > User-type  (=line 274 'caption' )
