### ISSUE TITLE
default template for news - not working with SEF URL

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1692]
I use for news LIST template (set in news preferencies).
(by the way, only reason for this is that LIST template using start and end subtemplate and default doesn't. I don't know it it's intention or not)

If I use news.php,  list template is used
But if I set SEF URL for news and path is /news  ot /news/, default template is used.  

Variable $defTemplate is set as list. 
with news.php  action is 'all'  with /news/ action is 'default' .

problem is here (with SEF_URL is e_query set default.0.0 and so it ignores template set in preferences.

``` php
if (e_QUERY) //TODO add support for $_GET['cat'] and $_GET['mode'] and phase-out the x.x.x format. 
{
    $tmp = explode(".",e_QUERY);
    $action = $tmp[0];                      // At least one parameter here
    $sub_action = varset($tmp[1],'');           // Usually a numeric category, or numeric news item number, but don't presume yet
    //  $id = varset($tmp[2],'');                   // ID of specific news item where required
    $newsfrom = intval(varset($tmp[2],0));  // Item number for first item on multi-page lists
    $cacheString = 'news.php_'.e_QUERY;
}
else 
{
    $opt = array('default'=>'', 'list'=>'all');
    $action = varset($opt[$defTemplate],'');
}
```

**Comment by CaMer0n** [comment]
@Jimmi08 Is this still an issue?

**Comment by CaMer0n** [comment]
@Jimmi08 I just made some changes to 'news' yesterday which could affect this.

**Comment by Jimmi08** [comment]
Yes, it is working.  I see different output when I am changing news layout
