### ISSUE TITLE
question - how to get original url when SEF-URL is enabled?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1693]
Is there any way how to get original URL when SEF-URL is enabled?

I mean:  link is created by e107::url(),  final url is "sef",  but I would like to put in meta tag canonical url with original url (value of $redirect in e_url.php config). 

Thank you

**Comment by CaMer0n** [comment]
@Jimmi08 Is this for a custom plugin? I would include the primary_id in your URL and it will always be unique.

**Comment by Jimmi08** [comment]
@CaMer0n  It's not about unique url, it's about unique content. The same content is displayed with different unigue url (site/news, site/news.php, site/news/ etc)  And there can be parts where old path are used.  I noticed this with content plugin but it's general question 

Or other example - I don't use sef url for some time, then I switch to sef url (or back) -  with always the same <link rel="canonical" href=' original not sef url path'  > it says to google that it still the same content and not duplicate.   This way you don't need to have worry when you rebuild your urls in admin area.

**Comment by CaMer0n** [comment]
If you add $option['legacy'] = true; does that help now?

**Comment by Jimmi08** [comment]
This works, but I need exact opposite. I will try to explain it but maybe I am too forward, because correct place for this is e_header or header template. 

- in whole plugin I am using e107:url() with e_url.php file.  Still testing, but it works and was so easy to do, that I can't believe.  

- config looks for example this way:
```
    $config['categories'] = array(
		// Matched against url, and if true, redirected to 'redirect' below.
		'regex'    => '^content/categories/(.*)',
		// Used by e107::url(); to create a url from the db table.
		'sef'      => 'content/categories/{url_content_id}',
		// File-path of what to load when the regex returns true.
		'redirect' => '{e_PLUGIN}content/content.php?cat.list.$1'
	 );
```
- example of url http://localhost/e107demo/content/categories/200
- this value is in e_REQUEST_SELF constant 

- with this 	$tmp = e107::getAddonConfig('e_url');  I am able to get array of each definitions.  I know $plugin, but I don't know $key.  So I need to find value where $regex match with e_REQUEST_SELF or e_REQUEST_URI  to get $key and then return $tmp[$plugin][$key]['redirect']  

I just found that something similar is doing in index.php.

**Comment by CaMer0n** [comment]
I think it would be better to discuss in the chatroom. I'm sorry that I don't really understand what you're trying to achieve.

**Comment by Jimmi08** [comment]
For future using: e_URL_LEGACY

**Comment by Jimmi08** [comment]
https://yoast.com/metadata-and-seo-part-2-link-rel-metadata/
