### ISSUE TITLE
issue or wrong configuration with e_notify.php

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1696]
I create a notify e_notify.php 
![image](https://cloud.githubusercontent.com/assets/1758577/15926006/ed648614-2e39-11e6-8429-e68d267403f0.png)
if i send a notify to the mailing list and open this... at bottom is a link for unsubscribe.
When i click on this i get follow error
![image](https://cloud.githubusercontent.com/assets/1758577/15926043/2360895c-2e3a-11e6-80ff-b98cfe083805.png)
What is wrong?

**Comment by Moc** [comment]
Please post or link to your e_notify.php code so it can be reviewed

**Comment by schlrech** [comment]
here the code from e_notify.php

`<?php

class events_notify extends notify // plugin-folder + '_notify' 
{		
	function config()
	{
		$config = array();
		$config[] = array(
			'name'			=> 'Events',
			'function'		=> "eventspost",
			'category'		=> ''
		);	
		return $config;
	}
	
	function eventspost($data) 
	{
		$message = LAN_EVENT_65.' '.$data['verfasser'].'<br />';
		$message .= LAN_EVENT_25.' '.$data['event_name'].'<br />';
		$message .= LAN_EVENT_26.' '.$data['event_datum'].'<br />';
		$message .= LAN_EVENT_29.': '.$data['event_anmeldeschluss'].'<br />';
		$message .="<a href='http://www.whatyouwant.ch/e107_plugins/events/event_details.php?action=details&id=".$data['id']."' title='" . LAN_EVENT_67 . "'> <span class='btn btn-primary'>" . LAN_EVENT_67 . "</span></a>";
		$message .="<br /><br />" . LAN_EVENT_71;
		$message .="<br />" . LAN_EVENT_72;
		// echo $message;
		// exit;
		$this->send('eventspost', LAN_EVENT_66, $message);
	}
}
?>`

**Comment by schlrech** [comment]
and hier the call
`$info = array(
				'id'					=> $_GET['id'],
				'event_name' 			=> $titel,
				'event_datum' 			=> $datum,
				'event_anmeldeschluss'	=> $datum_anmeldeschluss,
				'verfasser'				=> $verfasser
				); 
	
	e107::getEvent()->trigger("eventspost", $info);`

**Comment by CaMer0n** [comment]
You need to add e_mailout.php if you want to handle unsubscribe links.

**Comment by schlrech** [comment]
it is too complex for me.... I'll wait for more examples
thanks
