### ISSUE TITLE
Moderate Chatbox list is empty

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1697]
I have chatbox entries but the moderate list nothing
![image](https://cloud.githubusercontent.com/assets/1758577/15927513/8963a70e-2e42-11e6-9334-021e4f89182d.png)

![image](https://cloud.githubusercontent.com/assets/1758577/15927546/bd5c5cfe-2e42-11e6-92a6-4d8feb0fe96d.png)

**Comment by Jimmi08** [comment]
I can't confirm this, it works for me. (latest github)

What is your moderator userclass? Or insert screen of your chatbox setting please to see what you have different.
![image](https://cloud.githubusercontent.com/assets/5429548/15927942/9a92d08e-2e44-11e6-9c75-849d7f2d853f.png)

**Comment by schlrech** [comment]
![image](https://cloud.githubusercontent.com/assets/1758577/15928409/f173bb5a-2e46-11e6-8030-eb5e8f0dc698.png)

**Comment by schlrech** [comment]
also the latest github

**Comment by Jimmi08** [comment]
Set the same way and it still works. Sorry, I can't help you more.I tried emoticons too, still works.

**Comment by Moc** [comment]
This need debugging. Please find @CaMer0n or myself on Gitter to look into this more closely.
