### ISSUE TITLE
Issue: Admin Area SiteLinks

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1698]
So the bug has returned, Admin Area -> SiteLinks -> (Click on ID will take you to the link) - But now it adds /e107_admin/ into the link that is set to. I added a link to /e107_plugins/myplugin/plugin.php  - front end of the site will go to sitename.com/e107_plugins/myplugin/myplugin.php - but in SiteLinks admin area it goes to sitename.com/e107_admin/e107_plugins/myplugin/myplugin.php

**Comment by CaMer0n** [comment]
Thank you! I see it. It must have been there for a few months at least. Fix coming shortly.
