### ISSUE TITLE
problem after last update

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1699]
I was logged in my site, I did github update and then admin.php signup.php and login.php stopped works. 

signup.php has HTTP ERROR 500  and I was able to find that problem starts on this line: 
$userMethods = e107::getUserSession();  

Problem is that I really don't know say where this happens, because I was logged in. After trying to upload older version from 7.6.2016, it logged me out too.

**Comment by Jimmi08** [comment]
Can confirm that site with last update 7.6.2016 has the same problem (different server).
On my demo site I upload version from 4.6.2016 and site is working correct way.

**Comment by CaMer0n** [comment]
Fixed the issue.

**Comment by Jimmi08** [comment]
Thank you again.
