### ISSUE TITLE
question - correct way how to add new php menu

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1703]
Just question  to be sure if I didn't miss something. 

If I need new menu (f.e list of latest faq questions) just for theme purpose, only way how to do it is to create new plugin folder and put new menu there?
Or is there way how load new menu right from theme? f.e frome menus folder?

Thanks

**Comment by rica-carv** [comment]
@Jimmi08 If i recall correctly, i've question that somewhere here or on e107help, and the reply i had is that it's REALLY needed to set up a new plugin to load any menu created....

**Comment by CaMer0n** [comment]
If you want the admin to be able to modify placement via the menu-manager, then it needs to be a plugin. If this is not necessary then you could make a theme shortcode, place it in your theme template and add a configuration file if required.

**Comment by Jimmi08** [comment]
I just have feeling that I am missing something and solve this one too complicated way.  Yes. Shortcode could be solution. Thanks.
