### ISSUE TITLE
Missing re-calculate option in Comments Manager

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1706]
Where is it? :)

I deleted my (test) comments, but 'user_comments' field had not been updated in DB. My profile page is pretty interesting:
![kepernyokep - 2016-06-16 - 13 35 15](https://cloud.githubusercontent.com/assets/6043821/16115855/e26a2eae-33c9-11e6-968f-803885376252.png)

**Comment by Moc** [comment]
related / duplicate: #2162 #1592

**Comment by Moc** [comment]
Option is there now: Comments Manager > Tools (/e107_admin/comment.php?mode=main&action=tools)

Also fixed the bug so that now the comment count is correctly updated when deleting a comment.
