### ISSUE TITLE
Tiny MCE is not loading

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#1707]
I have upgraded my installation to the latest github version. Then when you try to edit news or a custom page TinyMCE will not show up but the site looks like loading forever.
I recovered my old TinyMCE version to find out that it works then. 
I have used KDIFF3 to find differences and I found 6 files. I located the issue to:

$lang = e_LANGUAGE; // 'English'; //Quick Fix e_LANGUAGE

in the wysiwyg.php. 
I have uploaded the latest version again, but used the old wysiwyg.php. That works.
I suspect that e_LANGUAGE is not working well here, but I don't know enough of the internals to fix it. 

I'm running E107 with the Dutch language pack.

**Comment by lonalore** [comment]
Similar issue: #1678

**Comment by aducom** [comment]
Yes, but my issue is not the naming of the language file imho, but a wrong internal e_Language. At least I think so...

**Comment by Alex-e107nl** [comment]
Albert, did you do an upgrade? Of en new installation?

**Comment by Alex-e107nl** [comment]
Try https://e107.nl/e107_plugins/download/download.php have to ask Tgtje where the right files are to download so i've added them on e107.nl... have to finish that site soon...

**Comment by aducom** [comment]
Well the main issue is that I fixed the problem of not appearing the editor by reverting to the old version of wysiwyg.php. But this is not a permanent solution as Ionalore reported. I think he's right in his opionion however, I needed a quick fix. I'm sure the dev(s) will pick this up.

**Comment by Alex-e107nl** [comment]
Albert, there's no dev picking this up because there's no problem, there was a change in the language files for Tiny, as you can see in the github version there's an english language file in there for tiny, but in the older dutch translation there was no .nl file, i've changed that, the reason is that there are no translated files online on cdn.tinymce.com... so when you see no tiny in dutch that's because there's no nl.js file.. You can get the right dutch translation at the provided link a little higher..

**Comment by rica-carv** [comment]
Excuse me, but nl.js tinymce file is also available for download on [the tinymce page](https://www.tinymce.com/download/language-packages/).....

**Comment by tgtje** [comment]
Correct @rica-carv , but it is about having the correct file inside the language pack added. (Dutch pack, which is more up to date than the e107 available packs due to constant development/adjustments aka hosted on SourceForge).

**Comment by rica-carv** [comment]
Humm, maybe this can be a candidate for some auto updating script, if there's any????

**Comment by aducom** [comment]
Hi Alex, I will download the correct files and retry. Tnx, for your support.

**Comment by tgtje** [comment]
@rica-carv , will be troublesome to do... if multiple languages are in use you also need something that detects the language in use, and thus call the correct language ( so in possible live action suppose 3 languages in use at the same time by different users, you have to accompany that ...)
