### ISSUE TITLE
Using new admin UI

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#1715]
Currently I'm developing a plugin and I have hard time to get new admin UI functionality, and the lack of documentation isn't helpful at all. The plugin Front end is a fairly large form with 30 + fields so decided to have a very simple DB table with id and data fields id is auto increment field and data field contains all form submission data in a way similar to the how e107 core preferences are stored in the DB. The front end is working just fine, since it only puts data in the DB (no editing, no rendering etc. etc. ) just simple form to gather data. The problem however is in the Back end

``` php
protected $fields       = array (`
  `'checkboxes' =>   array ( 'title' => '', 'type' => null, 'data' => null, 'width' => '5%', 'thclass' => 'center', 'forced' => '1', 'class' => 'center', 'toggle' => 'e-multiselect',  ),`
`'record_id' =>   array ( 'title' => LAN_ID, 'data' => 'int', 'width' => '5%', 'help' => '', 'readParms' => '', 'writeParms' => '', 'class' => 'left', 'thclass' => 'left',  ),`
` 'record_data' =>   array ( 'title' => 'Data', 'type' => 'textarea', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => '', 'writeParms' => '', 'class' => 'left', 'thclass' => 'left',  ),`
` 'options' =>   array ( 'title' => LAN_OPTIONS, 'type' => null, 'data' => null, 'width' => '10%', 'thclass' => 'center last', 'class' => 'center last', 'forced' => '1',  ),`
`);
```

is working fine, but I want to be able to recreate Front end form with editing capabilities. My logic is to grab the array with keys=>values from record_data field then to unserialize it through e107::getArrayStorage() and populate corresponding form fields with the values. This is similar to how core preferences are edited, but just don't get how to do that using the new admin UI capabilities.

**Comment by CaMer0n** [comment]
@Serios I believe you'll want to use type=>'method' data=>'array' and a custom method containing the rendering of your form elements. Inside this method you'll want to use `e107::unserialize();  `

**Comment by Serios** [comment]
Thanks @CaMer0n, currently doing exactly that. After a bit fiddling trough system files I figured out that's the best way of achieve what I want :)

**Comment by CaMer0n** [comment]
@Serios Excellent! :+1:  If you find anything missing in the docs, please feel free to contribute. You just need to be logged into the site with your github account.
