### ISSUE TITLE
problem with SEF-URL menus vs pages: check for uniqueness required

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1716]
I really hope I would able to explain this:
1. I created custom menu About (page table), it automatically filled page-sef as "about" from title.  ID 10. I didn't noticed this. 
2. Later  I created custom page About (not  related with that menu), at first with sef-url about-us, then I changed it to "about" .  No warning, because there is no test with update. ID 13

But viewing page "about" -  /about  found ID 10 not 13 and displayed different content (empty of course).  I wasn't able find reason for this at first. In menus you don't see this field in row and in pages you don't see menus. 

So:
- there should be test of unique SEF-URL for update too
- there shouldn't be filled page-sef in menu section if page title is not filled (not fill page-sef from menu title)

Thanks

**Comment by rica-carv** [comment]
The sef url filed in custom menus is "hidden" in the second tab, but anyway, i agree with you, auto SEF URL should be tested for unique SEF URL site wide....

**Comment by Jimmi08** [comment]
I think that this one is fixed. Or I didn't notice any similar problem.
