### ISSUE TITLE
photo on user profile is uploaded only after second try

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1717]
Manually created user, admin logged as this user (if this is important)

First time in edit profile, no photo
![image](https://cloud.githubusercontent.com/assets/5429548/16172907/bcb68eda-3592-11e6-8a74-5e4e48ad2894.png)

Choosing photo, file name is correct
![image](https://cloud.githubusercontent.com/assets/5429548/16172911/ccb53e1c-3592-11e6-8656-9b691d98d4e3.png)

Saving changes
![image](https://cloud.githubusercontent.com/assets/5429548/16172914/d43e441c-3592-11e6-9806-2efc71b65632.png)

Second time doint the same thing, result - photo is uploaded.
![image](https://cloud.githubusercontent.com/assets/5429548/16172921/e03077c2-3592-11e6-988d-9cc495f0502c.png)

**Comment by rica-carv** [comment]
Did you use the same photo file on the second try?
Just in case to rule out cache issues....

**Comment by Jimmi08** [comment]
yes, the same photo

**Comment by CaMer0n** [comment]
Please test and check the database? It may just be a page-refresh thing.. or not checking $_POST.

**Comment by Jimmi08** [comment]
After first upload:
![image](https://cloud.githubusercontent.com/assets/5429548/21314928/edecc3dc-c5f9-11e6-852a-5d9add67f61b.png)
After page refreshing, photo is displayed.

**Comment by CaMer0n** [comment]
Right, it's a refresh issue.

**Comment by Jimmi08** [comment]
I think that this was fixed already.
