### ISSUE TITLE
BBcode issue using Edge browser

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1719]
BBCode will not be before and behind the selected area in text area on the admin (start and end tag - both tags before selected area).

**Comment by lonalore** [comment]
I tried to reproduce this on creating news item. But BBCode tags wrapped around the selected text properly.
![kepernyokep - 2016-06-20 - 13 39 05](https://cloud.githubusercontent.com/assets/6043821/16193017/01acf0dc-36ed-11e6-876b-6b07a68ca0b6.png)

How can I reproduce this?

**Comment by rica-carv** [comment]
@lonalore Maybe you can't use BBcode on the WYSIWYG editor part, try use them on the HTML source edit part of the WYSIWYG editor...

**Comment by fizi** [comment]
I made the images:
1. I selected the text:
![image1](https://cloud.githubusercontent.com/assets/86780/16204040/4fd257f4-371d-11e6-921f-aea952421779.jpg)

2. I pushed the "B" bbcode button and bbcode's tags appears before the selected text:
![image2](https://cloud.githubusercontent.com/assets/86780/16204105/8e9cf48a-371d-11e6-970d-710cb93c9447.jpg)

**Comment by Moc** [comment]
@fizi Which browser are you using?

**Comment by lonalore** [comment]
@fizi What e107 version you are using? Are you using the latest files?

**Comment by fizi** [comment]
I use edge and latest github

**Comment by Moc** [comment]
Confirmed as a browser incompatibility issue. On most browsers it works as expected (tested on Chrome and Firefox) but the issue occurs on Edge.

**Comment by LaocheXe** [comment]
Leave it to Microsoft to be different and difficult.

**Comment by Moc** [comment]
Closing this. With the new Edge version based on Chromium, I am confident this issue is resolved.
