### ISSUE TITLE
Question: AdminUI and table with NULL fields

### ISSUE THREAD

**Issue by dobem** [e107inc/e107#1722]
How can I save a field value as NULL?

I tried to set null at beforeUpdate/Create method but it sets 0 if it's an int field.

**Comment by lonalore** [comment]
Hi! Please copy your datbase table scheme here from your PLUGIN_sql.php file. And also copy your $field array element from your e_admin_ui class.

**Comment by rica-carv** [comment]
If in the database table schema, that field is not allowed to have null values, it will always default to 0.
It's a database table definition issue, as i can see it....

**Comment by CaMer0n** [comment]
@dobem Try using the value `_NULL_`  -  you'll need to make sure your DB table will accept NULL values of course.

**Comment by dobem** [comment]
Solved.

I'm sure the field accepts NULL.
Here is one of the tables:

CREATE TABLE IF NOT EXISTS `cup_item` (
  `cup_item_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cup_item_cup_id` int(10) unsigned NOT NULL,
  `cup_item_user_id` int(10) unsigned NOT NULL,
  `cup_item_download_id` int(10) unsigned DEFAULT NULL,
  `cup_item_accepted` tinyint(1) unsigned DEFAULT NULL,
  `cup_item_datestamp` int(10) unsigned NOT NULL,
  PRIMARY KEY (`cup_item_id`),
  UNIQUE KEY `cup_item_download_id` (`cup_item_download_id`),
  KEY `cup_item_cup_id` (`cup_item_cup_id`),
  KEY `cup_item_user_id` (`cup_item_user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

I did what CaMer0n said.
Using '_NULL_' solved the problem, but I had to make the field 'str', example:

protected $fields = array(
    ...,
    'cup_item_download_id' => array(
        'title' => 'Download',
        'type' => 'dropdown',
        'data' => 'str',
        'validate' => true,
        'nolist' => true,
        'tab' => 0
    ),
    ...
);

Thanks everyone.

**Comment by CaMer0n** [comment]
@dobem Glad it worked out for you. :+1:
