### ISSUE TITLE
Question: Allow downloads in main page?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1727]
Why can't the main page of downloads (core plugin) have a download item?
If i have, let's say, a general download, i'll have to create a category, and a sub category to put that download, which could be on the downloads root page itself instead, or simply just under the parent category...
Something [like this](http://demo.directorylister.com/)
![screenshot 1](https://cloud.githubusercontent.com/assets/17130530/16275567/7a791052-38a2-11e6-95ae-5605dda11ef7.png)
![fileaway-5 1](https://cloud.githubusercontent.com/assets/17130530/16275591/919ab3a8-38a2-11e6-8968-2e409b0814f9.jpg)

**Comment by Moc** [comment]
Haha this is a longstanding issue which was already the case in v1, but which should be relatively easy to solve. Labelled as enhancement.

**Comment by ihughes24** [comment]
That be security risk, only admin etc can post to public_html. permisions above 7 5 5
permissions below 7 5 0

**Comment by Moc** [comment]
@ihughes24 The screenshots are just to illustrate. The point of the enhancement request is to make downloads work without need a sub category.

Currently you need Parent > Child > Download item, whereas the request is to make it also possible to have Parent > Download item.

**Comment by rica-carv** [comment]
Or even just >Download item.....
For instance, allow a combined strucuture like this:
Parent > Child > Download item Parent Child 1, item Parent Child 2, so on...
Parent > Download item Parent 1, Parent 2, ...
Download item 1, Download item 2, ....

**Comment by Moc** [comment]
I am pretty sure this is now possible in the latest version. If not, please let us know and I'll re-open.
