### ISSUE TITLE
Issue: DisplayName and UserName

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1728]
I went to add a quick user, and have the site set up to allow DisplayName to be different than UserLoginName - I got this message when I added a new user: User name and display name cannot be different (based on the site configuration). Display name set to [b]TestDummy[/b].

**Comment by Moc** [comment]
2.5 years later but.... confirmed as a bug. 

By default, userclass is left empty even though it should always include the 'member' class (253). 

Therefore, this check fails https://github.com/e107inc/e107/blob/3f2a55114717b0f8865f83e6036307c6b8ba7da7/e107_admin/users.php#L1411:

`if (!check_class($pref['displayname_class'], $allData['data']['user_class']))`

**Comment by CaMer0n** [comment]
@Moc Looks like a good solution. Would you like to add it?

**Comment by Moc** [comment]
Done
