### ISSUE TITLE
Wrong path is set for style.css in my theme

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1731]
My theme's [folder structure](https://github.com/lonalore/bs3echat):
![kepernyokep - 2016-06-24 - 16 20 41](https://cloud.githubusercontent.com/assets/6043821/16340334/e0c33406-3a27-11e6-9ba0-b27440c690b7.png)

CSS file in my [theme.xml](https://github.com/lonalore/bs3echat/blob/master/theme.xml):
![kepernyokep - 2016-06-24 - 16 20 51](https://cloud.githubusercontent.com/assets/6043821/16340345/fee0bba2-3a27-11e6-8134-6d3638e54874.png)

Missing 'css/' from the path for style.css:
![kepernyokep - 2016-06-24 - 16 21 00](https://cloud.githubusercontent.com/assets/6043821/16340370/218f4c04-3a28-11e6-9a46-397d758c4991.png)

**Comment by rica-carv** [comment]
How are you inclunding the css on the theme template???
With e107::css???

**Comment by lonalore** [comment]
Mea culpa! I just realized that e107 loads `style.css` from the theme's root folder by default. These `<stylesheets>` items will be used for layouts:
![kepernyokep_2016-06-24_18-31-37](https://cloud.githubusercontent.com/assets/6043821/16343869/e8c0bfae-3a39-11e6-9393-8d1913e7c793.png)
