### ISSUE TITLE
Media manager download categories not working

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1732]
The Media manager download (core) plugin categories are not working.
I assign a image to the categories "downlad_image" or "downlad_thumb", and they are not visible when i use the image picker when editing a download item on the download plugin.....
Shouldn't they be present and available if assigned to those categories on the imagepicker inside the download admin interface?

**Comment by Moc** [comment]
@rica-carv Still an issue?

**Comment by rica-carv** [comment]
@Moc Yes, and i think it's worst. Now when picking an image, all the media manager images are displayed, and i haven't any chance to filter for any category, because simply it's not there!
![downloads_-_gerenciar_-_area_do_administrador_selos_portugal_-_2018-06-25_19 26 08](https://user-images.githubusercontent.com/17130530/41868386-e13f74dc-78ad-11e8-8dc7-13ee8ef3658e.png)

Furthermore, when i try change the image in the list view, i got a error page on the modal window....
![downloads_-_gerenciar_-_area_do_administrador_selos_portugal_-_2018-06-25_19 25 37](https://user-images.githubusercontent.com/17130530/41868426-f7adbabc-78ad-11e8-82d9-4ba1d924d14e.png)

**Comment by CaMer0n** [comment]
@Jimmi08 This is the opposite to the feature request you wanted. 
Workaround: 
To include 'common' images a '+' should be added to the media category. 
ie. `writeParms => "media=download_image+"`

**Comment by Jimmi08** [comment]
@CaMer0n If you think of this  FR -   
https://github.com/e107inc/e107/issues/3276

I had something different on mind.  To add new tab to media manager (to get it working everywhere) without category filter.  I want to see in news images uploaded to download category, but only on special tab, not first one.

Common images were always displayed - this was changed sometime?

**Comment by CaMer0n** [comment]
@Jimmi08 I understand. Common-images were NOT displayed, and then they were, and now we're back to "NOT" again. I think we need common displayed but on separate slides. This will be something for the new mediapicker()
