### ISSUE TITLE
Question: How to add a plugin to the frontpage?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1734]
I wonder how can i add a plugin to the list shown on the admin UI when selecting what to see on the frontpage...
By default, i can see news, welcome message, and customurl, but how can i add more plugins?

**Comment by Jimmi08** [comment]
with e_frontpage.php

**Comment by rica-carv** [comment]
Humm.... Thanks, i'll give it a try...

**Comment by Jimmi08** [comment]
I use it with links_page and content plugin. Be aware this:  https://github.com/e107inc/e107/issues/1663

**Comment by rica-carv** [comment]
Ok, thanks for the tip. I'll give it a try and let know how it ends up....
Thanks

**Comment by Moc** [comment]
Closing for now, please create a help topic on e107help.org or possible bugs in a new Github issue.

**Comment by rica-carv** [comment]
Sorry for bringing this up again, but i'm not getting this to work....
I've got e_frontpage.php on my plugin folder, with this content:
`class frota_frontpage{	function config()	{		$frontPage = array('page' => '{e_PLUGIN}frota/frota.php', 'title' => LAN_PLUGIN_FROTA_NAME);		return $frontPage;	}}
`
, pretty much like [these lines here](https://github.com/e107inc/e107/blob/9d3e1ad5e70f3bcdec1f840e4ffeacbaef3f62e3/e107_plugins/newsfeed/e_frontpage.php#L30). But when changing the frontpage for my plugin, from the admin UI, my frontpage just renders a blank page with this text: `Bad request - destination unreachable - e107_plugins/frotafrota.php`

I can see a missing backslash there, but even if i change in e_frontpage.php `{e_PLUGIN}frota/frota.php` to `{e_PLUGIN}news/news.php`, the frontpage still gives me the same error, with reference to frota.php!!!!
What am i doing wrong here??
