### ISSUE TITLE
Erro on log plugin frontend

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1736]
When trying to acces log plugin, through url <site>/e107plugins/log/log.php, got this error on a white screen: `Debug is Active
File: ../../e107_system/77dc419a1d/logs/logp_176.2016.phpCouldn't log data to: ../../e107_system/77dc419a1d/logs/logp_176.2016.php`
Using the e107 debug extension for Firefox also gives the same, without any further debug info....
Is this normal???

**Comment by rica-carv** [comment]
Sorry for bringing this up again, but now the link `MY_WEBSITE/e107_plugins/log/log.php` returns a blank page. Logged or unlogged, it simply returns a blank page...
Even debug returns a blank page, without any info....

**Comment by Moc** [comment]
@rica-carv Is this still the case?

**Comment by rica-carv** [comment]
@Moc Unsolved, same as before. White page, latest github as of today. No debug info, nothing.

**Comment by Moc** [comment]
- Did you try with `define('e_DEBUG', true);` in the e107_config.php file (and developer mode and debug mode on)? 

- Anything in the Apache error log?

**Comment by Moc** [comment]
Actually, I think it is supposed to be a white page. Let me check.

**Comment by Moc** [comment]
Yep, it says in the code of the file as well: 
> // Normally the file is 'silent' - if any errors occur, any error message appears in the page header.

It is used by the plugin to collect and store information but it does not display information. 
The page that is used to display information is `/e107_plugins/log/stats.php` or the SEF `t/stats`/

**Comment by rica-carv** [comment]
@Moc Then this is a little bit of a inconsistency and a "standards" runaway...

>  It is used by the plugin to collect and store information but it does not display information.
> The page that is used to display information is /e107_plugins/log/stats.php or the SEF /stats

Why not swap the code inside the two files (log.php & stats.php)?
