### ISSUE TITLE
Question: no render for specific menu, how?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1738]
Just wondering, if it's possible to not render a specific menu caption when on rendering, ie, like this: 

Original menu HTML:
`<li><h4><a href="e107_plugins/easygallery/gallery.php">Galeria</a></h4>
	<div style="text=align:center; vertical-align:middle;">
		<a href="e107_plugins/easygallery/gallery.php?entry=gallery/Fotos/caixa1~2.JPG" alt="" style="padding: 1px;"><img src="e107_plugins/easygallery/gallery/thumbs/Fotoscaixa1~2.JPG" alt="" style="display:block; margin:auto; border:0;"></a>
	</div></li>`

No caption menu HTML:
`<li><-----h4 removed---->
	<div style="text=align:center; vertical-align:middle;">
		<a href="e107_plugins/easygallery/gallery.php?entry=gallery/Fotos/caixa1~2.JPG" alt="" style="padding: 1px;"><img src="e107_plugins/easygallery/gallery/thumbs/Fotoscaixa1~2.JPG" alt="" style="display:block; margin:auto; border:0;"></a>
	</div></li>`

I know i can do it via css, and not display it, but allow to template a menu caption would be better and far more flexible, no?
Something like this:
`$NEWS_MENU_TEMPLATE['caption'] 	= "<h8>My own caption...</h8>";`

**Comment by Jimmi08** [comment]
Use tablestyle() function. Something like this:  (no $caption there)
```
	if($style == 'none')
	{
    echo $text;
		return;
	}
```
Just find ID of your menu (third parameter or look at result of this echo when your menu is rendered
`echo "<!-- tablestyle: style=".$style." id=".$id." -->\n\n";`

And then add test for your id or style. Look at bootstrap3 theme for example:
`if($id == 'featurebox') // Example - If rendered from 'featurebox' `

**Comment by rica-carv** [comment]
@Jimmi08 Thanks, i know that way to style menus, but with this particular menu, it had no $style, and i forgot tho search also for $id....
Thanks for the help...
