### ISSUE TITLE
Quick Add User 

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1740]
the fields are always pre filled out
how can i prevent this?

![image](https://cloud.githubusercontent.com/assets/1758577/16385742/409f65b2-3c8e-11e6-9cdb-2fca85bb3a52.png)

**Comment by Jimmi08** [comment]
I am not sure but I suppose it's your browser behaviour, something like automatic filling forms. Any forms, not just e107.

**Comment by schlrech** [comment]
you are right, is only in chrome ;-(

**Comment by schlrech** [comment]
my solution
<input style='display:none;' type='text' name='e-mail' />
<input class='form-control' type='text' id='e-mail' name='e-mail' maxlength='64' placeholder='" . LAN_TURNIER_ADMIN_EXTERNUSER_26 . "'>
