### ISSUE TITLE
Links Plugin is 2x downloadable from plugin list

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1741]
Hi, maybe I did something wrong, there was update of this plugin, but now there are both versions.  Is this correct? Thanks
![image](https://cloud.githubusercontent.com/assets/5429548/16386679/d514c4d2-3c91-11e6-9130-6ba2a265b67c.png)

**Comment by rica-carv** [comment]
Try to see if there's two directories with differente names but with the same plugin inside...
I've had issues like that, but it was plugins duplicated with diferent name, or even worst, plugins with install info from other plugin.... :dizzy_face:

**Comment by Jimmi08** [comment]
You are right. I didn't notice this before.
![image](https://cloud.githubusercontent.com/assets/5429548/16387625/d72b0b92-3c95-11e6-897d-6297546ac7c4.png)

**Comment by rica-carv** [comment]
:wink:

**Comment by CaMer0n** [comment]
@Jimmi08 Shall I delete the one with the bad folder name? "links_page-2.1.3 " ?

**Comment by Jimmi08** [comment]
@CaMer0n Yes, please. Thank you.

**Comment by CaMer0n** [comment]
@Jimmi08 Done! :+1:

**Comment by Moc** [comment]
Assuming this is fixed now.
