### ISSUE TITLE
Download plugin date issue

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1746]
Hi,
the download plugin always shows    01 jan 1970 : 01:00 as the date in the front ... but admin side shows the right date woensdag, 29 jun, 2016 .. 

https://e107.nl/e107_plugins/download/download.php?action=list&id=2

Site in progress..

**Comment by CaMer0n** [comment]
@Alex-e107nl Thanks. Are you using the default download template? The date appears fine for me using them Bootstrap3 theme.

**Comment by Alex-e107nl** [comment]
Hi Cameron, github of yesterday, default template (used standard bootstrap 3 theme) The date on the frontend 01 jan 1970 isn't the same as in the backend..Thursday, 30 Jun, 2016  Backend shows it right but when i try to change the date i get this... 
System Information Nothing updated as no changes were made. Please try again. 

So something goed wrong... standard linux server PHP Version 5.6.17

**Comment by CaMer0n** [comment]
Thanks @Alex-e107nl I did find an issue with saving the date. Could you please update and try editing the download item and then check again?

**Comment by Alex-e107nl** [comment]
Hi Cameron, thx, dates can be adjust now! Only the timestanp cannot... its always 00:00 in backend i can not enter a time.. :-)
