### ISSUE TITLE
Forum avatar incorrect after deleting user

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1748]
Hi when you delete a member but this member has posted some messages in the forum this becomes a anonymous user but the avatar that is showing is from the member that is reading the forum... gives a strange effect, Moc has seen it also... Its only showing when you are logged-in.. https://e107.nl/forum/vertaling_forum/2/instellingen-scherm-probleem/

**Comment by Moc** [comment]
Confirmed, fix incoming

**Comment by rica-carv** [comment]
@Moc What about something like this:
`if (!isset($this->postInfo['user_image'])) {$this->postInfo['user_image']=e107::getParser()->thumbUrl(e_IMAGE."generic/blank_avatar.jpg","w=".$width."&h=".$height,true);}`

 before this [line](https://github.com/e107inc/e107/blob/3c5019d29fe86eac538c494f3314cfa05ed48e66/e107_plugins/forum/shortcodes/batch/view_shortcodes.php#L221)?

**Comment by arunshekher** [comment]
I believe no fixes has been committed for this in repository so far.

I too can confirm this issue in at-least 4 local test installations and 1 production server test installation. I tested out with a 12 year old e107 site database and static contents which was upgraded to e107 v2.1.3

Going to test out @rica-carv's solution.

**Comment by Moc** [comment]
Yes, the bug has been confirmed and is on the list to be fixed before the next release.

**Comment by CaMer0n** [comment]
Should be working now. Good to see you @arunshekher ! 👍
