### ISSUE TITLE
Social Plugin needs an icon

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#1750]
The social plugin needs an icon. 16x16 and 32x32. 
fyi. "Nuvola" is where most of the other icons were taken from, but it can be from somewhere else as long as it has a similar style. 

I'm open to suggestions. 

Thanks.

**Comment by rica-carv** [comment]
I'm no graphic designer, but here goes some ideias...
From Nuvola icon set:
[![kdmconfig 1](https://cloud.githubusercontent.com/assets/17130530/16483201/48a48336-3eab-11e6-8f4f-947a6648adee.png)  ![kdmconfig 1](https://cloud.githubusercontent.com/assets/17130530/16483211/550fedcc-3eab-11e6-944c-84cc1b13da25.png)](http://findicons.com/icon/226865/kdmconfig)        [![remote 1](https://cloud.githubusercontent.com/assets/17130530/16483269/93263e0e-3eab-11e6-80ed-545b33c74bb8.png)  ![remote 1](https://cloud.githubusercontent.com/assets/17130530/16483276/9df2c3b6-3eab-11e6-8cb7-8f10702b83d2.png)](http://findicons.com/icon/227302/remote)

From other icon set:
[![user_network_2 1](https://cloud.githubusercontent.com/assets/17130530/16483708/83fb28e8-3ead-11e6-8e18-13eccdf73223.png)    ![user_network_2 1](https://cloud.githubusercontent.com/assets/17130530/16483717/8d614f20-3ead-11e6-93e3-523663c224c6.png)](http://findicons.com/icon/16700/user_network_2?id=16857)



From a google search (of course, would have to be resized...):
![social-network-icons 1](https://cloud.githubusercontent.com/assets/17130530/16483358/f538fa6e-3eab-11e6-8955-c76d24144d6c.png)   ![iyekqkcjf5q 1](https://cloud.githubusercontent.com/assets/17130530/16483402/2a4be806-3eac-11e6-88a7-c2650f6b8290.jpg)    ![pai 1](https://cloud.githubusercontent.com/assets/17130530/16483506/96c6d4fa-3eac-11e6-873d-ca932a4fc715.png)   ![affiliates-512-300x300 1](https://cloud.githubusercontent.com/assets/17130530/16483561/d9243b9e-3eac-11e6-976e-c32a2ff02e8b.png)    ![images](https://cloud.githubusercontent.com/assets/17130530/16483584/f896157e-3eac-11e6-8c14-5c8149235792.jpg)

In last case, it can be always atempted to do something similar to the above icons with the Nuvola set icons, by trying to join 2, 3 or more icons to compose a single one....

**Comment by CaMer0n** [comment]
Thanks. I like the concept of this one too: 
http://www.1001freedownloads.com/free-icon/generic-share-folder-icon

**Comment by rica-carv** [comment]
Background based nuvola icon, with a "upgrade" on top...
![icon](https://cloud.githubusercontent.com/assets/17130530/16497345/518faa50-3eee-11e6-8321-dfa832082392.png)

**Comment by CaMer0n** [comment]
nice work! This might be even cleaner? 

http://www.freepik.com/free-icon/earth-with-connections-grid_723822.htm#term=connection%20interface&page=1&position=7

**Comment by rica-carv** [comment]
I personally don't like it, it's too much "Bootstrap Glyph", and very different from the Nuvola icons already in use....
But it's your choice....

**Comment by CaMer0n** [comment]
@rica-carv Sorry, I meant cleaner to build a nuvola-style icon from (like you did above)

**Comment by rica-carv** [comment]
@CaMer0n Sorry, misunderstand you...
Something like this?
![icon](https://cloud.githubusercontent.com/assets/17130530/16501336/e63712d0-3f00-11e6-9e8b-2164ec52afec.png)

**Comment by CaMer0n** [comment]
Yes!!! :+1:

**Comment by rica-carv** [comment]
16x16 icon: ![icon16](https://cloud.githubusercontent.com/assets/17130530/16566851/31daf3e8-4210-11e6-92d1-5b947d92d284.png)

32x32 icon: ![icon32](https://cloud.githubusercontent.com/assets/17130530/16566850/31dabe96-4210-11e6-98be-129113e763c1.png)
