### ISSUE TITLE
ViewTopic missing pagination and bottom reply button

### ISSUE THREAD

**Issue by durandalwoz** [e107inc/e107#1751]
forum_viewtopic.php still using $tVars for $FORUMEND section of the template.
Only renders the {QUICKREPLY} shortcode
Thread pagination is missing completely.

**Comment by rica-carv** [comment]
Just got them....
Damn pesky vars...

**Comment by Moc** [comment]
@durandalwoz Please update with the latest files from Github and see if the issue is resolved.

**Comment by durandalwoz** [comment]
Confirmed working with latest files
