### ISSUE TITLE
Form API issues on Admin UI

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1753]
Spent an hour trying to find out... but nothing... :D

So, here is the rendered field:
![kepernyokep - 2016-06-30 - 16 14 48](https://cloud.githubusercontent.com/assets/6043821/16491787/a0afaf2c-3edf-11e6-96bd-b2cd2ba1484e.png)

...and here is my code:

``` php
'room_author' => array(
    'title'      => LAN_ECHAT_ADMIN_ROOMS_03,
    'type'       => 'user',
    'inline'     => true,
    'filter'     => true,
    'validate'   => true,
    'data'       => 'int',
    'width'      => 'auto',
    'thclass'    => 'center',
    'class'      => 'center',
    'writeParms' => array(
        'currentInit' => 0,
    ),
    'tab'        => 0,
),
```

As I look at this part, I have no chance of getting an empty field...
![kepernyokep - 2016-06-30 - 16 19 14](https://cloud.githubusercontent.com/assets/6043821/16491725/5b9c0d72-3edf-11e6-92cf-a95ac93ee8ff.png)

Form API is a mess! I think we need to clean its code. :/

**Comment by CaMer0n** [comment]
We might need to change empty($parms['default']) to !isset($parms['default'])

**Comment by lonalore** [comment]
This works for me:
```php
case 'user':
	if(!isset($parms['__options']))
	{
		$parms['__options'] = array();
	}

	if(!is_array($parms['__options']))
	{
		parse_str($parms['__options'], $parms['__options']);
	}

	// If no default value is provided. Or default is 'USERID'.
	if(empty($value) && (empty($parms['default']) || vartrue($parms['default']) == 'USERID'))
	{
		// 'currentInit' - use current user if no data provided.
		if(vartrue($parms['currentInit']))
		{
			// Include current user by default.
			$value = array(
				'user_id'   => USERID,
				'user_name' => USERNAME,
			);
		}
	}

	// 'current' - use ALWAYS! current user (editor).
	if(vartrue($parms['current']))
	{
		$value = array(
			'user_id'   => USERID,
			'user_name' => USERNAME,
		);

		$parms['__options']['readonly'] = true;
	}

	$colname = vartrue($parms['nameType'], 'user_name');
	$parms['__options']['name'] = $colname;

	if(!empty($parms['limit']))
	{
		$parms['__options']['limit'] = intval($parms['limit']);
	}

	$ret = $this->userpicker(vartrue($parms['nameField'], $key), $value, vartrue($parms['__options']));
break;
```

If it suits you, I will commit my changes.

**Comment by CaMer0n** [comment]
It should display the current user when no params are included. Where is $parms['currentInit'] set?

**Comment by lonalore** [comment]
No, it should not. I should display current user only if 'currentInit' is set. According to docs in _blank plugin:
https://github.com/e107inc/e107/blob/master/e107_plugins/_blank/admin_config.php#L208

**Comment by CaMer0n** [comment]
@lonalore Those docs are outdated and need to be modified. It should display the current user by default as I said above.

**Comment by lonalore** [comment]
So 'currentInit' need to be removed completely? Because it's outdated?

What about this?
```php
case 'user':
	if(!isset($parms['__options']))
	{
		$parms['__options'] = array();
	}

	if(!is_array($parms['__options']))
	{
		parse_str($parms['__options'], $parms['__options']);
	}

	// If no default value is provided. Or default is 'USERID'.
	if(empty($value) && (!isset($parms['default']) || vartrue($parms['default']) == 'USERID'))
	{
		// Include current user by default.
		$value = array(
			'user_id'   => USERID,
			'user_name' => USERNAME,
		);
	}

	// 'current' - use ALWAYS! current user (editor).
	if(vartrue($parms['current']))
	{
		$value = array(
			'user_id'   => USERID,
			'user_name' => USERNAME,
		);

		$parms['__options']['readonly'] = true;
	}

	$colname = vartrue($parms['nameType'], 'user_name');
	$parms['__options']['name'] = $colname;

	if(!empty($parms['limit']))
	{
		$parms['__options']['limit'] = intval($parms['limit']);
	}

	$ret = $this->userpicker(vartrue($parms['nameField'], $key), $value, vartrue($parms['__options']));
break;
```

**Comment by lonalore** [comment]
Only the Faq plugin uses 'currentInit=1'.

**Comment by lonalore** [comment]
Another issue/question: how can I set default value for a dropdown? Here is my dropdown field:

```php
'room_status' => array(
	'title'      => LAN_ECHAT_ADMIN_ROOMS_07,
	'type'       => 'dropdown',
	'width'      => 'auto',
	'readonly'   => false,
	'inline'     => true,
	'filter'     => true,
	'thclass'    => 'center',
	'class'      => 'center',
	'writeParms' => array(
		'default' => 1,
		'optArray' => array(
			1 => LAN_ACTIVE,
			0 => LAN_INACTIVE,
		),
	),
	'readParms'  => array(
		'optArray' => array(
			1 => LAN_ACTIVE,
			0 => LAN_INACTIVE,
		),
	),
	'tab'        => 0,
),
```

If I remove `'default' => 1,`, "Inactive" option will be selected. But, if I set default value, it creates another option for my dropdown:

![kepernyokep_2016-06-30_22-27-07](https://cloud.githubusercontent.com/assets/6043821/16503316/cef0dda6-3f12-11e6-9b5a-a17e29c12cad.png)

**Comment by lonalore** [comment]
Temporarily, I changed widget to "radio". At least it works. :D

**Comment by lonalore** [comment]
Fixed. Is that okay?

![kepernyokep - 2016-07-01 - 09 59 31](https://cloud.githubusercontent.com/assets/6043821/16515478/89854dbe-3f72-11e6-8327-9e667baf56d2.png)

**Comment by CaMer0n** [comment]
In this case 'default' is for something like "Please make a selection". 
What if you use 'value' => 1 ?

**Comment by lonalore** [comment]
Well, it doesn't work. Here is my code:
![kepernyokep_2016-07-02_08-04-11](https://cloud.githubusercontent.com/assets/6043821/16538673/ab06d840-402b-11e6-8c66-2ef990d30d42.png)

...and the result:
![kepernyokep_2016-07-02_08-03-45](https://cloud.githubusercontent.com/assets/6043821/16538676/b54a2ba4-402b-11e6-96fa-5fe7658909a7.png)

`'default' => 1` worked. In my opinion, we should use 'empty' or 'empty_option' for something like "Please make a selection". What is your opinion about this?

**Comment by lonalore** [comment]
Or how can we find solution to this? I reverted my changes related to 'dropdown' issue.

**Comment by Jimmi08** [comment]
@CaMer0n 
According your advice in my old  issue, default option should be use for setting default key value.  Something changed from that time.
@lonalore 
problem is in function select(). For you it should be easy to improve it.  Look for 	
	 
```
if(isset($options['default']))
		{
			if($options['default'] === 'blank')
			{
				$options['default'] = '&nbsp;';			
			}
			$text .= $this->option($options['default'], varset($options['defaultValue'],''));
		}
		elseif($defaultBlank)
		{
			$diz = is_string($defaultBlank) ? $defaultBlank : '&nbsp;';
			$text .= $this->option($diz, '');
		}
 
```
If you add the test if it's key (number) then avoid adding this code, it shoul be work.  Or you need to remove your default option from your dropdown array and add it as defaultValue option. Something like this:
![image](https://cloud.githubusercontent.com/assets/5429548/18548015/bf7e002c-7b46-11e6-9a34-971a6232f578.png)

**Comment by lonalore** [comment]
@Jimmi08  Thank you! But it doesn't work. 

![kepernyokep_2016-09-15_16-10-17](https://cloud.githubusercontent.com/assets/6043821/18552946/f741005a-7b5e-11e6-88d3-af285a5ac00d.png)

My Admin UI field definiation:
```php
'room_status' => array(
	'title'      => LAN_ECHAT_ADMIN_ROOMS_07,
	'type'       => 'dropdown',
	'width'      => 'auto',
	'readonly'   => false,
	'inline'     => true,
	'filter'     => true,
	'thclass'    => 'center',
	'class'      => 'center',
	'writeParms' => array(
		'default' => LAN_ACTIVE,
		'defaultValue' => 1,
		'optArray' => array(
			1 => LAN_ACTIVE,
			0 => LAN_INACTIVE,
		),
	),
	'readParms'  => array(
		'optArray' => array(
			1 => LAN_ACTIVE,
			0 => LAN_INACTIVE,
		),
	),
	'tab'        => 0,
),
```

And here is the generated HTML output:
```html
<select name="room_status" id="room-status" class="tbox select form-control ui-state-valid" data-original-title="" title="">
	<option value="1">Active</option>
	<option value="1">Active</option>
	<option value="0" selected="selected">Inactive</option>
</select>
```

But I need this:
```html
<select name="room_status" id="room-status" class="tbox select form-control ui-state-valid" data-original-title="" title="">
	<option value="1" selected="selected">Active</option>
	<option value="0">Inactive</option>
</select>
```

-----------------------------------------------------------------

The logical solution would be something like this:
```php
'writeParms' => array(
	'default' => 1,
	'optArray' => array(
		1 => LAN_ACTIVE,
		0 => LAN_INACTIVE,
	),
),
```

...and if someone wants to set empty value, then something this:
```php
'writeParms' => array(
	'default' => 1,
	'emptyValue' => 'blah',
	'optArray' => array(
		1 => LAN_ACTIVE,
		0 => LAN_INACTIVE,
	),
),
```

**Comment by Jimmi08** [comment]
I agree with you, somewhere during time some missunderstanding happend - DefaultValue is the key, Default is value/title , but in other part of code Default is still key for selected value. Maybe just change name to initial instead default would be better.    

You are right, your example doesn't work and my one just look to work, because my needed value was first in the order.  Sorry for mess.

**Comment by Moc** [comment]
@lonalore Is this issue still relevant? Has the above already been resolved in the latest version or is the discussion still open?

**Comment by CaMer0n** [comment]
@Moc It was fixed a while back.. the working code to use is: 
```
'room_status' => array(
    'title'      => LAN_ECHAT_ADMIN_ROOMS_07,
    'type'       => 'dropdown',
    'width'      => 'auto',
    'readonly'   => false,
    'inline'     => true,
    'filter'     => true,
    'thclass'    => 'center',
    'class'      => 'center',
    'writeParms' => array(
        'empty' => 1,
        'optArray' => array(
            1 => LAN_ACTIVE,
            0 => LAN_INACTIVE,
        ),
    ),
    'readParms'  => array(
        'optArray' => array(
            1 => LAN_ACTIVE,
            0 => LAN_INACTIVE,
        ),
    ),
    'tab'        => 0,
),
```
