### ISSUE TITLE
Question: How to replace menu content before render?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1754]
I'm working on a plugin that has the login_menu front end as before a user logs in, but has a diferent front end for when a user is logged in.
My question is, let's suppose i have the core login_menu on my menu area of my site, and after i install this plugin, with the modified login_menu. So, on order to have at least one login menu, i must have one or the other, right?
So on menus area i have:
_login_menu, etc...._
After plugin install:
_plugin_login_menu, login_menu, etc..._
Of course i can disable login_menu from the menu area, and leave:
_plugin_login_menu, etc..._
But if i uninstall the plugin, i'll have to remember to go back and reuse the regular core login_menu...

So my question is, isn't a possible way that my plugin_login_menu content replaces the login_menu, on the same menu area, without have to change the menus on that area, so i can always use: login_menu, etc...?

**Comment by Jimmi08** [comment]
@rica-carv message on gitter, I haven't notification from gitter, so you can mention my name on github.

**Comment by Moc** [comment]
@rica-carv Is this issue still relevant?
