### ISSUE TITLE
{CPAGERELATED} - how to format them?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1757]
With news {NEWSRELATED} there is $template as 4th parameter, but with {CPAGERELATED} there are just 3 parameters  and you can't use template for related pages. 
Or I don't see it.
Thanks

**Comment by Jimmi08** [comment]
I noticed not used fields with page: sub_title and page_images.  Are they planned?

**Comment by CaMer0n** [comment]
Template was only completed for news. Adding page template shortly.

**Comment by Jimmi08** [comment]
@CaMer0n Thank you

Please, don't open this again, this is just information for you, some kind of report. If you think so, I could create separated issues.

With new free theme I didn't want to use not core plugins so I really tested functionality of new page system.

I run to this missing functionality, but I was able to solve this with theme shortcodes (or maybe I am just blind as usually):
- missing shortcode for display just value of  menu_button_url field    
(you can use this if you need to display external link on your site or as next text field)
- missing shortcode for display page keywords (field page_metakeys similar way as news_shortcodes)
- for using isotope and filtering functionality missing shortcode PAGE_CHAPTER_SEF (there is shortcode CHAPTER_SEF, but in loop with pages I needed SEF of parent) - you can see using of it here: http://demo.e107.sk/solid/page/book/portfolio

With single page I run to missing functionality I wasn't able to solve for now:
- related pages with images -  it should be solved by your commit, I will see soon
- carousel of more images for page -  there is field page_images prepared for this but it's not used in cpage, so I can't use it in theme_shortcodes
- more separated text field - using body for more structured text is not good idea, but field sub_title is not used in cpage too
It should look like this: http://blacktie.co/demo/solid/single-project.html

Thanks  again

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 - you can make a pull-request for some of those missing shortcodes if you wish.
