### ISSUE TITLE
Site Admin cannot reply to private messages by default

### ISSUE THREAD

**Issue by brwnie** [e107inc/e107#1758]
All other users appear to be unaffected, but when a Site Admin tries to reply to a user:

You do not have access to send to this user.

I've attached my PM settings in a screenshot
![pm_issue](https://cloud.githubusercontent.com/assets/11775356/16540256/76f00a20-4055-11e6-8dce-521b5276bd70.PNG)

**Comment by arunshekher** [comment]
In my quick test with today's git clone I can not reproduce this issue. The admin was able to sent PM to user without issues when default PM plugin prefs are in place (tried with out of the box default PM prefs).

Whereas the Admin and users are getting the message "You do not have access to send to this user." when they try to reply a PM.

**Comment by arunshekher** [comment]
The issue with users and admin getting the error message "You do not have access to send to this user." when trying to reply PM buy clicking reply button  goes away if a bare 'Save' of PM preferences with the default set values is done at the PM admin Area - Admin > Private Messenger >  Preferences >  Click Button  'Save'

Tested after today's origin pull.

**Comment by CaMer0n** [comment]
Okay, so it's to do with the default prefs. We need to do a pref comparison between what is there after PM is installed, and what is there after clicking the "save" button in the Plugin's Preferences.

**Comment by madtrekker** [comment]
Hello

I encounter exactly this same problem on E107 V 2.1.5.

I have tried several things to check the database many times but nothing to do is impossible to reply to a private message I can only send.

Is there a solution to this very problematic problem?

**Comment by Moc** [comment]
I will do some testing right now. 

@madtrekker Does pressing the 'save' button in the Private Message admin area solve the issue? (/e107_plugins/pm/admin_config.php)

**Comment by Moc** [comment]
I reproduced the bug, there is an issue which will be fixed as soon as possible. 
@madtrekker A quick-fix it to save the preferences of the Private Message plugin in the admin area. 

@CaMer0n 
Prefs before: 
```
	allow_userclass	1
	animate	1
	attach_class	254
	attach_size	500
	dropdown
	multi_class	254
	notify_class	254
	perpage	10
	pm_class	253
	pm_limits
	pm_max_send	100
	popup
	popup_delay	3
	read_timeout
	receipt_class	253
	sendall_class	254
	sent_to_class	matchclass
	title	PMLAN_PM
	unread_timeout
```

Prefs after
```
        allow_userclass	1
	animate	1
	attach_class	254
	attach_size	500
	dropdown
	maxlength	0
	multi_class	254
	notify_class	254
	opt_userclass	255
	perpage	10
	pm_class	253
	pm_limits
	pm_max_send	100
	popup	0
	popup_delay	3
	read_timeout	0
	receipt_class	253
	send_to_class	253
	sendall_class	254
	sent_to_class	matchclass
	title	PMLAN_PM
	unread_timeout	0
	vip_class	255
```

**Comment by madtrekker** [comment]
c'est où que je dois changer ceci ?

**Comment by Moc** [comment]
Please keep the language in English. 

In the Admin Area, go to `Users > Private Messenger` and click the green 'Save' button.

**Comment by madtrekker** [comment]
Not for me, the use of the backup function of the private messaging settings does not change anything.

I still can not reply to my private message.

I'll wait for a fix to be available

**Comment by madtrekker** [comment]
I finally managed a trick to pass this bug.

To do this is a solution waiting for a fix.

To be able to reply to your private messages as an administrator tick the box "quote the message" and click on answer.

This will open another page with the quote of the message and the possibility of responding to it.
