### ISSUE TITLE
[New Feature] Library Manager: Ability to use CDN variant for a library.

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1759]

**Comment by lonalore** [comment]
Admin UI for CDN variants:
![screencapture-echat-lonalore-hu-e107_admin-prefs-php-1467551301144](https://cloud.githubusercontent.com/assets/6043821/16545596/037f1a82-4130-11e6-8c13-d6dacbd753fc.png)

**Comment by CaMer0n** [comment]
Please see comments on pull-request.
