### ISSUE TITLE
Error: Core Linkwords not inserting in DB

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1760]
The core linkwords plugin doens't let insert words in the database. I've got the latest github update, and when creating a new linkword, it gives this error: `ERROR: SQL insert error`

**Comment by CaMer0n** [comment]
@rica-carv Thanks. And with debugger active for SQL, what is the error?

**Comment by rica-carv** [comment]
@CaMer0n Here's the output of SQL analysis:

ID: 0
Action: create

```
Array
(
    [e-token] => 016411a1016aee9f57d22957491c460c
    [linkword_word] => teste
    [linkword_link] => teste.html
    [linkword_active] => 0
    [linkword_tooltip] => teste
    [linkword_limit] => 3
    [linkword_tip_id] => 0
    [linkword_newwindow] => 1
    [etrigger_submit] => create
    [__after_submit_action] => list
    [submit_value] => 0
    [mode] => 
)
```

SQL Error #0:
SQL QRY Error

```
Array
(
    [_FIELD_TYPES] => Array
        (
            [linkword_word] => str
            [linkword_link] => str
            [linkword_active] => int
            [linkword_tooltip] => str
            [linkword_limit] => int
            [linkword_tip_id] => int
            [linkword_newwindow] => int
        )

    [data] => Array
        (
            [linkword_id] => 0
            [linkword_word] => teste
            [linkword_link] => teste.html
            [linkword_active] => 0
            [linkword_tooltip] => teste
            [linkword_limit] => 3
            [linkword_tip_id] => 0
            [linkword_newwindow] => 1
        )

)
```

**Comment by CaMer0n** [comment]
@rica-carv I'm unable to reproduce it. You might want to check your db tables.

**Comment by rica-carv** [comment]
@CaMer0n Linkwords table is present on my database:
`CREATE TABLE IF NOT EXISTS `e107_linkwords` (
  `linkword_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `linkword_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `linkword_word` varchar(100) NOT NULL DEFAULT '',
  `linkword_link` varchar(250) NOT NULL DEFAULT '',
  `linkword_tooltip` text NOT NULL,
  `linkword_tip_id` int(10) unsigned NOT NULL DEFAULT '0',
  `linkword_newwindow` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`linkword_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;`

**Comment by Moc** [comment]
@CaMer0n: this is the same issue similar to my wrappper plugin (same sql error code)

**Comment by rica-carv** [comment]
@CaMer0n @Moc But this one was due to a database missing upgrade. After i did the database upgrade, all got back right again...
