### ISSUE TITLE
Error: e_frontpage.php not working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1761]
Sorry for bringing this up again, but i'm not getting this to work....
I've got e_frontpage.php on my plugin folder, with this content:
`class frota_frontpage{ function config() { $frontPage = array('page' => '{e_PLUGIN}frota/frota.php', 'title' => LAN_PLUGIN_FROTA_NAME); return $frontPage; }}`
, pretty much like these lines here. But when changing the frontpage to point to the frota plugin, from the admin UI, my frontpage just renders a blank page with this text: `Bad request - destination unreachable - e107_plugins/frotafrota.php`

I can see a missing backslash there, but even if i change in e_frontpage.php `{e_PLUGIN}frota/frota.php` to `{e_PLUGIN}news/news.php`, the frontpage still gives me the same error, with reference to frota.php!!!!
What am i doing wrong here??

**Comment by rica-carv** [comment]
After some debug, found out that the issue is in [these lines](https://github.com/e107inc/e107/blob/master/e107_admin/frontpage.php#L82):
`$multipage = str_replace(e_HTTP, '', $multipage);
$front_value = str_replace(e_HTTP, '', $front_value);`

The problem is that this str_replace changes `{e_PLUGIN}frota/frota.php` to `{e_PLUGIN}frotafrota.php`, since e_HTTP has the value "/" when it arrives at this point....

The solution of changing in plugins e_frontpage.php the right slashs to left slashes continues to give an error when rendering the front page: `Bad request - destination unreachable - e107_plugins/tours\tours.php`

My hardcore temporary solution: Completely remove those two lines.
My other approach was to redefine the e_HTTP, but where can i do it?

**Comment by Moc** [comment]
- Please provide your e_frontpage.php code in proper [Github formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) or link to it on your Github repo if available. 

- Disable and clear the caches when testing (one of your issues sounds like a caching issue. 

- See if the issue still remains.

**Comment by Moc** [comment]
Perfect, thanks for the extensive feedback. 

@CaMer0n What do you think about this one?

**Comment by Jimmi08** [comment]
@rica-carv is this still problem?

I tried this one
```
	function config()
	{
		$frontPage = array('page' => '{e_PLUGIN}creative_writer/cwriter.php', 'title' => CWRITER_A1);
		return $frontPage;
	} 
```
```
	function config()
	{
		$config = array();

		$config['title']    = CWRITER_A1;
		$config['page']     = array(
						0   => array('page' => '{e_PLUGIN}creative_writer/cwriter.php', 'title'=>CWRITER_A1),
		);

		return $config;
	}
```

both settings works.  Only weird thing was that first time using single setting caused the same error as you are describing. Then changing multiple setting (with one item) solved issue, but after it and using single setting works now too.

**Comment by Jimmi08** [comment]
related: https://github.com/e107inc/e107/issues/927

**Comment by rica-carv** [comment]
@Jimmi08 Sorry, but i haven't got this site up anymore, so i'll reopen it if this issue pops upa again...
Thanks....
