### ISSUE TITLE
Question: mediamanager choosing youtube video https problem

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1762]
Hi,.
when you select a video from youtube and your site is working with https there's a problem with the `$data['items'][0]['snippet']['thumbnails']['medium']['url'] = "http://i.ytimg.com/vi/".$searchQry."/mqdefault.jpg";` in e107_admin/image.php on line 1481, should http://i.ytimg.com/vi/ not be https://i.ytimg.com/vi/ ?

**Comment by oxigeno2** [comment]
Hele n ech toho fakt to přehánís proč mě urazis a ponizujes já nejsem vy
brumlici
