### ISSUE TITLE
Question: how to use core shortcodes in plugin's template?

### ISSUE THREAD

**Issue by dobem** [e107inc/e107#1763]
Example:

@e107_plugins/myplugin/templates/myplugin_template.php

```
$MYPLUGIN_TEMPLATE['start'] = '<ul>';
$MYPLUGIN_TEMPLATE['item'] = '<li>{USER_NAME_LINK} - {MYPLUGIN_SAMPLE}'</li>';
$MYPLUGIN_TEMPLATE['end'] = '</ul>';
```

@e107_plugins/myplugin/e_shortcode.php

```
class myplugin_shortcodes extends e_shortcode
{
    function sc_myplugin_sample()
    {
        return $this->var['myplugin_sample'];
    }
}
```

@e107_plugins/myplugin/list.php

```
$sql = e107::getDb();
$tp = e107::getParser();
$sc = e107::getScBatch('myplugin', true);
$template = e107::getTemplate('myplugin');

$sql->gen(
    'SELECT user_id, user_name, myplugin_sample
    FROM #myplugin_table
    INNER JOIN #user ON user_id = myplugin_user'
);

$text = $tp->parseTemplate($template['start'], true, $sc);

while ($row = $sql->fetch()) {
    // parse $template['item'];
}

$text .= $tp->parseTemplate($template['end'], true, $sc);
```

**Comment by rica-carv** [comment]
You're missing something like this:
`$sc->setVars($row);`

inside the while loop, before the template parsing...

**Comment by dobem** [comment]
I known. But it will parse only my shortcodes and not `{USER_NAME_LINK}`. Is there any way to parse my shortcode and core shortcode together?

**Comment by rica-carv** [comment]
Ah, now i got it. You need to mix two shortcodes from different plugins on the same template...
I'll be having this same issue soon on a plugin i'm writing also, so for now, without untesting them, i can only see two options:
Do a "merge" of both shortcodes, something like this:
`$sc = e107::getScBatch('myplugin', true);
$sc .= e107::getScBatch('otherplugin', true);`

The second option would be to simply "duplicate" the sc_user_name_link shortcode function to your e_shortcode.php file.... But that would be duplicating shortcodes, and if the core changes....
Another way would be to include the user_shortcodes.php in your e_shortcodes.php.....

Without testing (wich i can't do right now), i can't tell if these options works or not...

**Comment by dobem** [comment]
@rica-carv thanks for helping.
I'm already using the copy/past solution.
I dont think string concatanation will work with classes.
All the solutions are not ideal in my opinion.

I'm not confident that you guys will change the whole shortcode structure on my request but 
I will just leave my option how it should work.

_e107 should load every shortcode in the same plugin_class(child) that extends to core_class(parent).
Instead of having sc_example() as method, plugins should use sc_myplugin_example() (myplugin is the plugin name).
To create an shortcode for your plugin, instead of having myplugin_shortcodes class inside e_shortcode.php, we would have some kind of register_shortcode() that would create the method(s) inside the plugin_class(child).
To use shortcode we could specify the plugin/core on the shortcode it self.
Example:_

```
$MYPLUGIN_TEMEPLATE['test'] = <<<EOT
core shortcode: {USER_NAME}<br />
override core shortcode: {USER_NAME: plugin=myplugin}
override forum user_name: {USER_NAME: plugin=myplugin&override=forum}
override all user_name's: {USER_NAME: plugin=myplugin&override=all}
override user_name for multiple plugins: {USER_NAME: plugin=myplugin&override=forum,download}
EOT;
```

Anyway, if you find another solution, let me know.

**Comment by rica-carv** [comment]
Dumb, dumb, dumb.... I'm really stupid....
It's so simple. After some testing, i realized that it can be anchieved just by replacing ` class myplugin_shortcodes extends e_shortcode` in your e_shortcode.php file with 
`class myplugin_shortcodes extends user_shortcodes`

And i was trying to reinvent the wheel.... :dizzy_face:

**Comment by dobem** [comment]
Yes. I should have pointed it out. Thats what I'm doing to override `news_shortcodes`. My question was to use all core shortcodes availables. If you just extends `user_shortcodes`, you only will have access to `user_shortcodes`.

I've found an way to use multiple plugins shortcodes. Here is how:
```
$tp = e107::getParser();
$sc1 = e107::getScBatch('plugin_a', true);
$sc2 = e107::getScBatch('plugin_b', true);
$template = e107::getTemplate('myplugin');
$sc1->setVars($plugin_a_vars);
$sc2->setVars($plugin_b_vars);
// not passing $sc as reference seems to work
$text = $tp->parseTemplate($template);
```

**Comment by rica-carv** [comment]
There's also a more ["ugly" solution](http://stackoverflow.com/questions/356128/can-i-extend-a-class-using-more-than-1-class-in-php)....

**Comment by Jimmi08** [comment]
I am solving this in theme template. There you can use  core and global shortcodes together. And override them if you want.  This was big change already and it works now.

**Comment by rica-carv** [comment]
@Jimmi08 I know i can do that on theme template, and use theme shortcodes, but i want to do the same on a plugin basis, without having to mess around with the theme.
For instance, if i install a plugin that "wants" to override a core shortcode, it should do it on a plugin code basis, not change the theme to adjust a particular plugin. If i uninstall that particular plugin, i would still have the shortcode overriden on the theme.
Therefore i would have to delete that override on the theme....
Not practical....

Maybe have something to override core shortcodes like this:
Current override: Core shortcode -> Theme shortcode override core shortcode
Suggestion: Core shortcode -> Plugin shortcode override core shortcode -> Theme shortcode override core & plugin shortcode

**Comment by Jimmi08** [comment]
@rica-carv if your plugin shortcode extend core shortcodes class, you should be able to overrride it's method.

**Comment by rica-carv** [comment]
@Jimmi08 But if you have the same shortcode overriden in theme, it takes precendece, so the plugin override will be ignored...

**Comment by Jimmi08** [comment]
@rica-carv  I don't know, but it should work this way - to be able override core or plugin shortcodes in themes.

**Comment by CaMer0n** [comment]
Yes, this can be done when $override is set to true.

**Comment by Moc** [comment]
I am assuming the issue above has been answered adequately. If there are still any remaining questions, please let us know and I'll reopen.
