### ISSUE TITLE
Prefs are not saved

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1764]
i'm trying to save my prefs

```PHP
$turnier_prefs['rangliste_date'] = date("d.m.Y");
e107::getPlugConfig('turnier')->setPref($turnier_prefs);
e107::getPlugConfig('turnier')->save();
```
but is not save in the databasetable e107_core

what is wrong?

**Comment by schlrech** [comment]
i found the issue:
in the plugin table is the name of Plugin -> LAN_PLUGIN_TURNIER_NAME and not turnier
The LAN_PLUGIN_TURNIER_NAME  is defined in English_global.php and German_global.php
i rescan the Plugins but no change to the right name. Allways the name is LAN_PLUGIN_TURNIER_NAME

**Comment by tgtje** [comment]
Does the plugin use a xml file too ? (there name has to be too).

**Comment by schlrech** [comment]
i change the plugin.xml
From:
<e107Plugin name="Turnier System" lan="LAN_PLUGIN_TURNIER_NAME" version="1.0" date="2015-11-09" compatibility="2.0" installRequired="true">
to:
<e107Plugin name="Turnier-System" version="2.0" date="2015-11-09" compatibility="2.0" installRequired="true">

now i can save the prefs but with the command:
$lastrefresh = e107::getPlugPref('Turnier-System', 'rangliste_date');
i can't read the value

**Comment by CaMer0n** [comment]
@schlrech This may sound like a silly question, but is the plugin installed?

**Comment by schlrech** [comment]
My Plugin?
![image](https://cloud.githubusercontent.com/assets/1758577/16661557/ca70c6f4-4473-11e6-8d25-a1421bf2c9f4.png)

![image](https://cloud.githubusercontent.com/assets/1758577/16661596/f2f5dbd2-4473-11e6-9e57-ced1a32958c6.png)

**Comment by tgtje** [comment]
Umm do not know the content of your xml file, but what is added normally (afaik) is a descriptive line  as define.
Such line would be  
<description lan="LAN_PLUGIN_TURNIER_NAME">Adds options or whatever text........
</description> This is  normally called in global.

The line e107 plugin is plugin name (folder) and the lan piece (also sometimes in global to be found) is just the title (for language use); also possible, like in forum > the title is hardcoded in config function.... ??

**Comment by schlrech** [comment]
This is the content and in the e107_plugins is the name LAN_PLUGIN_TURNIER_NAME instead Turnier-System that are defined in the English global

```PHP
<?xml version="1.0" encoding="utf-8"?>
<e107Plugin name="Turnier System" lan="LAN_PLUGIN_TURNIER_NAME" version="1.0" date="2015-11-09" compatibility="2.0" installRequired="true">
	<author name="René Schlegel" email="rene.schlegel@sendto.ch" />
	<description lan="LAN_PLUGIN_TURNIER_DESCRIPTION" />
	<keywords>
		<word>date</word>
		<word>event</word>
		<word>calendar</word>
		<word>turnier</word>
		<word>poker</word>
		<word>holdem</word>
		<word>omaha</word>
	</keywords>
	<category>misc</category>
	<copyright>René Schlegel</copyright>
	<adminLinks>
		<link url='' description='' icon='images/turnier_32.png' iconSmall='images/turnier_16.png' >"LAN_CONFIGURE"</link>
	</adminLinks>
</e107Plugin>
```

but if i change manually also then the prefs are not working for read from prefs

**Comment by schlrech** [comment]
a bad day today, i have pick the wrong folder name.... sorry for the confusion
