### ISSUE TITLE
Admin link ending in an empty site

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1765]
Manage in user admin ending to an empty site --> e107_admin/users.php?mode=main&action=list

![image](https://cloud.githubusercontent.com/assets/1758577/16642831/f4abfcfa-440e-11e6-8f26-9f8b95f47b46.png)

**Comment by CaMer0n** [comment]
@schlrech Please enable debug and check for errors in the footer.

**Comment by schlrech** [comment]
is nothing any error on the footer with debug all in the firefox

**Comment by schlrech** [comment]
today i update from gthub and the problem was resolved
