### ISSUE TITLE
[suggestion] social auth should be marked as development only

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1771]
This plugin is very unstable and should not be used on production sites, atleast the social login/signup.

That should be stated on the plugin name, or on the social login tab (in plugin config)

Grts,
- Nes

**Comment by CaMer0n** [comment]
@nesjett Perhaps you can provide some details of the issues?. Some of us have been using it reliably for many months.

**Comment by nesjett** [comment]
I´ve already opened some tickets about that, mainly there are exceptions not being crontrolled, for example for twitter auth rate limit.
Sometimes I get different errors related to the auth.

Can you tell me which service providers are you using? twitter and twitch gaves me errors in some point.

**Comment by CaMer0n** [comment]
Github login. If you know where the exception handling should be, please feel free to add and send a pull-request.

**Comment by nesjett** [comment]
I know a place where adding it would solve the problem of the unhandled exception, but Im not sure if its the best place to do it, Ill get into it in some time

Plus I still dont know how to add a new service provider, doing the same as in Steam support pull request doesnt seems to add my new provider to the valid ones.... I suppose this is some point I´m failing on, but its really extrange I coudnt find the issue, I spent a lot of time on it... ¿?

**Comment by CaMer0n** [comment]
@nesjett Which provider would you like to add to e107?

**Comment by nesjett** [comment]
Twitch (I was forced to overwrite foursquare code in order to get twitch working) but I would like to get it working properly without hacking the core source, plus I´m getting some errors sometimes at the login phase

**Comment by LaocheXe** [comment]
@CaMer0n I would put Twitch in, maybe even add a a section to link a Twitch page, and a spot to link a Steam Group Page in the Pages section.

**Comment by Moc** [comment]
I'm going to close this one since HybridAuth / social logins have had many changes in v2.3.0. Please open up a new issue if you still experience problems.
