### ISSUE TITLE
Filetype not allowed

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1773]
![image](https://cloud.githubusercontent.com/assets/1758577/16707089/6c06bc98-45c4-11e6-9d2e-e9b151261b31.png)

but the filetypes.xml are
```PHP
<?xml version="1.0" encoding="utf-8"?>
<e107Filetypes>
	<class name="253" type="zip,gz,jpg,jpeg,png,gif,xml,pdf" maxupload="2M" />
</e107Filetypes>
```

**Comment by rica-carv** [comment]
Rename jpeg to jpg, and you'll be fine....
They're exactly the same filetypes...

**Comment by rica-carv** [comment]
If you have a .gif file and rename it to .jpg, of course you'll be asking for trouble....

**Comment by schlrech** [comment]
I'm aware of all you've written. But that can't be the solution because in my opinion, the users should have the possibility to upload their avatar themselves without problems. Otherwise it's not user-friendly. That's why I hop, that this can be fixed.

**Comment by rica-carv** [comment]
As far i see it, now .jpg is the standard for JPEG images. All the remaining extensions are legacy, so why it has to be so user "unfriendly" to use the now correct file extension?

**Comment by Jimmi08** [comment]
Could you give more details where you have this problem? I was able to upload jpeg file without problems in new media manager.
![image](https://cloud.githubusercontent.com/assets/5429548/17866056/5a5b42bc-68a5-11e6-822d-f3255c47d39c.png)

**Comment by schlrech** [comment]
hi Jimmi08
its not on the media manager, its by the upload the avatar for users

**Comment by Jimmi08** [comment]
Hi, I don't use this, so I don't know how to able this and where to find it.

**Comment by rica-carv** [comment]
It seems there's two file upload routines:

1. [The old file_upload legacy one](https://github.com/e107inc/e107/blob/ec3e92b0d680292ffe116c1aa76c13bccf94621d/e107_handlers/upload_handler.php#L484)
2. And the e107::getFile()->getUploaded(); (wich i failed to find with github search...)

**Comment by tgtje** [comment]
@rica-carv 2) > line 477 handlers/upload_handler   line = decommented > deprecated

do you mean (search for ...see line 484 of above

**Comment by rica-carv** [comment]
@tgtje As i stated previously, and as commenten on line 477,  `* @Deprecated use e107::getFile()->getUploaded();`, [e107::getFile()->getUploaded();](https://github.com/e107inc/e107/blob/ab683a8954b2c77eddbcd4bb28749a071cd94bee/e107_handlers/file_class.php#L1193) should be the upload routine. Real weird...

**Comment by tgtje** [comment]
@ all involved : i do believe (testing is positive) is is all up to the FILE MASK.
Idea behind search > all is happening in a user part related (template etc..). So tracking down what is done and where...
file : usersettings php  go to line 186 ; at the end is file mask.. ADD jpeg between, save , test.
If it works for you **_it is up to the dev_** if it would be a usable solution ... Greetz and happy testing.

**Comment by CaMer0n** [comment]
Thank you @tgtje ! Added. :+1:
