### ISSUE TITLE
i cn't find the iFrame Plugin 

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1776]
I know, that a few days/weeks ago there was such a plugin for iframing. I can't find it anymore.
Can anybody provide the link?

thx

**Comment by Moc** [comment]
This would be a question for e107help.org not for GIthub. 

Anyway, I think you mean the Wrapper plugin: https://github.com/moc/wrapper
I will be releasing a new major version next week as currently there are some bugs which require fixing. I recommend to wait for that update.
