### ISSUE TITLE
Datetimepicker manual set datetime is not correct

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1778]
if i change the date or time manually not per calendar-PopUp

``` PHP
<td>"  . $frm->datepicker("datum_turnier", vartrue($datum_turnier) ? $datum_turnier : time(), array('size'=>10,'class'=>'tbox e-datetime','type'=>'datetime','format'=>'dd.mm.yyyy - hh:ii','required'=>1)) . "</td>
```

![image](https://cloud.githubusercontent.com/assets/1758577/16724613/e050770c-4753-11e6-88d0-86478af169a6.png)
then the System not put the new datetime to the $_POST variable 
what is wrong here?

When it's only allowed with the popup for this function, how i can disable the manually input?

**Comment by Jimmi08** [comment]
@lonalore maybe you can help?
I can confirm this with news too. If I just rewrite date, without click on calender, new date is not saved.

**Comment by lonalore** [comment]
> ...how i can disable the manually input?

make the textbox readonly with: 

`readonly="readonly"` 

or via jquery:

`$('#datum_turnier').attr('readonly', true);`

**Comment by lonalore** [comment]
Or try to use else clause for [this if statement](https://github.com/e107inc/e107/blob/master/e107_web/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.init.js#L21-L26), with something like this:

```
  var id = $this.attr("id");
  var newTarget = "#" + id.replace("e-datepicker-", "");
  var newValue = $this.val();
  var timestamp = Date.parse(newValue);
  $(newTarget).val(timestamp);
```

**Comment by lonalore** [comment]
So I suggest you should use `datepicker()` with `'return => string'` option, and perform any kind of date-conversion on backend... and not on frontend with using javascript.
