### ISSUE TITLE
Links Plugin is 2x downloadable from plugin list 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1780]
Ok, this is new issue. I will update next plugin soon so I want to avoid my mistake.

Links page plugin has correct folder name, correct versioning (just 2 numbers)
![image](https://cloud.githubusercontent.com/assets/5429548/16818358/8dbec5ca-4947-11e6-91e5-59829d7298d0.png)

In admin area I see both:
![image](https://cloud.githubusercontent.com/assets/5429548/16818233/0a7dabb8-4947-11e6-94f9-8964ff41c3d4.png)

But both installations install 2.2 version.

On plugin area on e107.org I see just 2.1 version
![image](https://cloud.githubusercontent.com/assets/5429548/16818261/2bd366f4-4947-11e6-9553-58b05df8c5ca.png)

Thanks

**Comment by lonalore** [comment]
Well, it does not support pre-releases. :( On my website I installed Google Analytics v1.0-beta2 (this is the newest version of this plugin), but I always get the alert message about newer version is available. But there is not newer version...

![kepernyokep_2016-10-26_09-28-21](https://cloud.githubusercontent.com/assets/6043821/19716943/8cd1b3f2-9b5e-11e6-8789-36d9844b33a0.png)

And I noticed that the version is not a pre-release version on e107.org:

![kepernyokep_2016-10-26_09-29-30](https://cloud.githubusercontent.com/assets/6043821/19716972/b7a6a75e-9b5e-11e6-8fcb-733a85efa8dd.png)

... it's not v1.0 and v1.1, it's v1.0-beta1 and v1.0-beta2

**Comment by Jimmi08** [comment]
@lonalore I had asked about this too. e107.org supports just 2 numbers (1.1., 1.2).  So no beta releases. I can't find issue about this now, but it was confirmed by CaMerOn.  By the way, I use the numbering from e_version now, and its numbering is 1.1.0 - stable version, and anything other 1.1.1 ... 1.1.9 - it's beta version)

**Comment by lonalore** [comment]
Ok. So I should ask @CaMer0n to delete my uploaded plugins and I should change the release naming conventions? But what happens if I do not want to use 2 digits versioning? :)

Btw. The 3 digits versioning is the Semantic Versioning (SemVer):
- MAJOR version when you make incompatible API changes (when compatibility is broken)
- MINOR version when you add functionality (new feature)
- PATCH version when you make bug fixes

**Comment by lonalore** [comment]
I think we need to define a standard for release naming convention in case of plugins and themes. And add some extra validation to e107.org.

**Comment by Jimmi08** [comment]
@lonalore I found it:
https://github.com/e107inc/e107/issues/854

**Comment by lonalore** [comment]
Okay. So according to [this comment](https://github.com/e107inc/e107/issues/854#issuecomment-219443337), I must use 2 digits version number.

@CaMer0n can you please delete my uploaded plugins? :( :( And please add some extra validations to check version numbers before uploading. Thank you!

**Comment by CaMer0n** [comment]
@lonalore @Jimmi08 version check has been added to e107.org, as well as support for x.x.x  (had to add a whole other db column just for the sorting)  For pre-release/beta you can use 0.1 or 0.1.0 
I can modify any previously uploaded plugins, just let me know which version you would like them to be.

**Comment by Moc** [comment]
Thanks Cameron, I appreciate your work as always! :) 

Glad to see the semantic version support added.

**Comment by lonalore** [comment]
Thank you @CaMer0n ! And please modify:
Google Analytics 1.0-beta1 to 1.0
Google Analytics 1.0-beta2 to 1.1
...and there will be no confusion. Can you also please modify the version numbers in plugin.xml files? Thank you!

**Comment by CaMer0n** [comment]
Thanks guys! @lonalore I modified the plugin.xml in Google Analytics 1.0-beta2. It's the only one visible now. When a new version is uploaded and approved the old one now automatically disappears.

**Comment by CaMer0n** [comment]
btw. the Plugin Manager now alerts the user if a newer version of a plugin is available on e107.org.

**Comment by Jimmi08** [comment]
It was solved. Thanks
