### ISSUE TITLE
e107 Update from 1.x to 2.0 not working

### ISSUE THREAD

**Issue by csjjpm** [e107inc/e107#1783]
I am unable to update version 1.x to 2.0.  I click the 'Update' button and it says success:
"Success
Executed Update from 1.x to 2.0"

But it still says it needs updating.  Anyway I can do this manually or has it already worked?  How can I check?

**Comment by Moc** [comment]
To enable debug mode:

- Make sure developer mode is enabled in the `Settings > Preferences > Advanced features` 
- Use the Firefox e107 debug addon or manually change the URL to /e107_admin/admin.php?[debug=basic+]

Then, go back to the update section and press the update button again. It should now provide more debug information. Please copy the debug info here or show us a screenshot.

**Comment by CaMer0n** [comment]
@csjjpm I'll be happy to troubleshoot this with you in the chatroom if you wish. https://gitter.im/e107inc/e107

**Comment by Moc** [comment]
Closing due to lack of feedback. Please visit us in the Gitter chatroom if you are still experiencing this issue.
