### ISSUE TITLE
problem with banner shortcode

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1784]
I have localhost version, everything works
![image](https://cloud.githubusercontent.com/assets/5429548/17050163/be54aee2-4ff1-11e6-81f2-379ce8a1ae94.png)
Banner is displayed:
![image](https://cloud.githubusercontent.com/assets/5429548/17050177/ce947e2c-4ff1-11e6-92c9-9f3de1bd5fcd.png)

Then I uploaded everything on hosting (the same version of e107, the same theme code). And banner is not displayed.  I found that shortcode is loaded this way:
![image](https://cloud.githubusercontent.com/assets/5429548/17050211/fc9f9202-4ff1-11e6-97d2-0c507b81f3a4.png)

What can be reason for something like this? Theme folder and plugin folder are the same.

**Comment by rica-carv** [comment]
Is that path really ok?
`e107_core/shortcodes/single/banner.sce107_core/shortcodes/single/banner.sc` ?
Very weird....

Anyway, that path has changed drastically, even the final file is different (from `e_shortcode.php` has changed to` banner.sc.`...)
Very, very weird....

**Comment by Jimmi08** [comment]
No, point is that  on localhost is path different and correct. There is the same code on both sites.  On live site e107 is not able to find correct shortcode and fall in looking for old and it is missing.

**Comment by CaMer0n** [comment]
@Jimmi08 Do you find what caused this issue on a live site?

**Comment by Jimmi08** [comment]
@CaMer0n On live site I installed plugin via theme interface, not via plugin area.  It solved itself when I click on Scan plugin directories. Code was exactly the same. Different installation was only different thing I can remember (on localhost was plugin first, theme second, on live site I used theme with this plugin in theme.xml) But maybe I am wrong.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you for these details.

**Comment by rica-carv** [comment]
@Jimmi08 
> On live site I installed plugin via theme interface, not via plugin area. It solved itself when I click on Scan plugin directories. Code was exactly the same. Different installation was only different thing I can remember (on localhost was plugin first, theme second, on live site I used theme with this plugin in theme.xml)

Just curious, how can you install a plugin via theme interface?
Don't plugins have to be installed via admin UI?
Doesn't the theme.xml file is only used to reference theme plugins dependencies only?

**Comment by Jimmi08** [comment]
```
Just curious, how can you install a plugin via theme interface?
Don't plugins have to be installed via admin UI?
Doesn't the theme.xml file is only used to reference theme plugins dependencies only?
```
I really didn't think about it. I saw install required plugin in theme setting and I did it. Maybe that I had debug on? I will look at it with new theme and I let you know.

**Comment by rica-carv** [comment]
@Jimmi08 Maybe you only added a "plugin" that has no sql tables to the plugins folder (for instance, like a menu folder)....
Normally this is not really a plugin (wich requires install indeed), but a module, that doesn't need yo be installed, but is available once is located on the plugins folder (just like menus "plugins" does)...

**Comment by Jimmi08** [comment]
![image](https://cloud.githubusercontent.com/assets/5429548/17520148/e820b638-5e4e-11e6-85d1-9945f71815d3.png)

**Comment by Jimmi08** [comment]
@CaMer0n    I can confirm this now. After click on Install banner plugin in theme manager, shortcode didn't work. Scan plugin folder helped.

**Comment by rica-carv** [comment]
@Jimmi08 Well, that "install banner" button there is quite new for me....
But what it really does is install the plugin, just like it's done via plugin manager menu, right?

**Comment by Jimmi08** [comment]
@rica-carv standard xml as others
https://github.com/Jimmi08/e107-tbcore-theme/blob/master/tbcore/theme.xml
