### ISSUE TITLE
Upgrade - Database update won't complete

### ISSUE THREAD

**Issue by brhahlen** [e107inc/e107#1786]
After upgrading a (very) old e107 0.7.23 to V2.1.1, I am not able to complete the Database upgrades.
It says that the 'Update core database structure' has been completed, but the 'Update from 1.x to 2.0' is not able to complete.

**Comment by CaMer0n** [comment]
I believe you'll need to upgrade from 0.7.23 to v1.0.4 and THEN upgrade to v2.1.1

**Comment by brhahlen** [comment]
Hi CaMer0n,
I actually did that. The background is that I needed to update because of 0.7.23 not working anymore, with php7 and mysql5.
The connect-strings changed to mysqli_connect instead of mysql_connect (but you probably know this).
Anyhow: I tried fixing that and hoped 1.0.4 would solve my issues, but I think 1.0.4 also refers to the "old" way of connecting to MySQL, so the site wasn't working at all.

**Comment by brhahlen** [comment]
This is what I am getting from the debug:
`System Debug
Attempting to Load: ../e107_plugins/pm/languages/English_global.php
Attempting to Load: ../e107_plugins/forum/languages/English/English_global.php
Attempting to Load: ../e107_plugins/list_new/languages/English_global.php
Attempting to Load: ../e107_plugins/poll/languages/English_global.php
Attempting to Load: ../e107_plugins/log/languages/English_global.php
Attempting to Load: ../e107_plugins/download/languages/English/English_global.php
Attempting to Load: ../e107_plugins/banner/languages/English_global.php
Attempting to Load: ../e107_plugins/page/languages/English/English_global.php
Checking for SetUp File: ../e107_plugins/forum/forum_setup.php
Found setup file forum_setup.php
Executing setup function forum_setup :: upgrade_required()
Checking for SetUp File: ../e107_plugins/poll/poll_setup.php
Checking for SetUp File: ../e107_plugins/pm/pm_setup.php
Found setup file pm_setup.php
Setup function pm_setup :: upgrade_required() NOT found.
Checking for SetUp File: ../e107_plugins/log/log_setup.php
Checking for SetUp File: ../e107_plugins/list_new/list_new_setup.php
Checking for SetUp File: ../e107_plugins/download/download_setup.php
Found setup file download_setup.php
Setup function download_setup :: upgrade_required() NOT found.
Checking for SetUp File: ../e107_plugins/banner/banner_setup.php
Found setup file banner_setup.php
Setup function banner_setup :: upgrade_required() NOT found.
Checking for SetUp File: ../e107_plugins/user/user_setup.php
Checking for SetUp File: ../e107_plugins/contact/contact_setup.php
Checking for SetUp File: ../e107_plugins/tinymce4/tinymce4_setup.php
Found setup file tinymce4_setup.php
Executing setup function tinymce4_setup :: upgrade_required()
Checking for SetUp File: ../e107_plugins/siteinfo/siteinfo_setup.php
Checking for SetUp File: ../e107_plugins/news/news_setup.php
Checking for SetUp File: ../e107_plugins/page/page_setup.php
Update required in update_routines.php on line 1317 (Avatar paths require updating.)
Plugin: forum requires an update.
Update required in update_routines.php on line 465 (Missing pref: admin_separate_plugins)
`

**Comment by brhahlen** [comment]
Got it fixed!
The e107_files/public/avatars folders was not modifiable by the apache user, so that gave some trouble. After chmodding to 777 it completed successfully. Now onwards to my forum upgrade issue...

**Comment by CaMer0n** [comment]
Happy it worked out @brhahlen ! :+1:
