### ISSUE TITLE
Question: How insert db table data on plugin setup?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1789]
On former v1.4, it could be donne by using the **MPREFIX** constant:
`"INSERT INTO ".MPREFIX."table VALUES ('birthday','Birthday Data Cache','',0,0,0,0,0,0);",`

But how can that be anchieved on V2.x, since the whole string is evaluated directly as MySQL?

**Comment by tgtje** [comment]
I think faqs plgin has it as best example (setup)

**Comment by rica-carv** [comment]
@tgtje Thanks, i was hoping this had to be donne within the <plugin>_sql.php file, never thought it has to be donne via the <plugin>_setup.php file....

Anyway, on the faqs_setup.php i can see a install_post function, but how does it works if i want to remove the rows i added with that function, when uninstalling the plugin? I can see a commented out uninstall_post, but nothing more.... How does this functions specifically work???

**Comment by Moc** [comment]
@rica-carv Yes, it works exactly as you described. 

The `install_post()` method allows you to run SQL queries (or any other code for that matter) directly after the plugin has been installed. The same applies to the `uninstall_post()` method, which is run directly after the plugin has been uninstalled.  

There is an example of `install_post()` in my OweMe plugin as well, but I did not include an `uninstall_post()` example unfortunately. It would be similar code using the `e107::getDb()->delete()` method.

**Comment by Jimmi08** [comment]
@Moc this can be closed
