### ISSUE TITLE
Question: Is it possible to add more codes for user_ban field?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1791]
Right now, the user_ban field under the user db table uses 6 codes:
```
define('USER_VALIDATED',0);
define('USER_BANNED',1);
define('USER_REGISTERED_NOT_VALIDATED',2);
define('USER_EMAIL_BOUNCED', 3);
define('USER_BOUNCED_RESET', 4);
define('USER_TEMPORARY_ACCOUNT', 5);
```

Is it possible, for instance, at plugin level, to have more codes?
For instance:
`define('USER_SUSPENDED',6);`

Can it be donne?

**Comment by Moc** [comment]
At this point, no :)

**Comment by rica-carv** [comment]
Great.... So, got to try a workaround..... Maybe this will lead me back to this #1790 ....

**Comment by CaMer0n** [comment]
Closing. Questions like this are more suited to e107help.org
