### ISSUE TITLE
update to the db don't work correctly

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1792]
The first time
i get this one
![image](https://cloud.githubusercontent.com/assets/1758577/17432604/6139101c-5b00-11e6-9f6f-97c2ca375f20.png)

then i press F5 on the browser
i get this one and its correct
![image](https://cloud.githubusercontent.com/assets/1758577/17432631/882b1cf6-5b00-11e6-9898-d51535f57fbd.png)

i can reproduce this error if i clear the cache "empty db structure cache" I'm not sure it's the cache

i hope you can fix this issue as soon as possible
thx

**Comment by tgtje** [comment]
F5 _while in session_ is always tricky (not adviced).  System vs browser do differ in length of time. Where system can be finished, browser may retrigger 'command'. (long story in short).

**Comment by schlrech** [comment]
i don't know why in the first update is only 1 Record to update instead 3 records.
Only when i click F5 the data are correct.... i know that is no good the F5

**Comment by schlrech** [comment]
if i program properly it works.... sorry for my question....

**Comment by tgtje** [comment]
Do not be sorry, just curious : what was the issue ? sql sequence?
