### ISSUE TITLE
Upgrade 1.0.4 to 2.x Missing jslib_handler.php 

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1793]
Hi All

ED: before starting Saved backup of SQL and File System!

Upgrading an established site using the upgrade pack http://e107.org/get-started e107 1.x to 2.1.1 Upgrade (.zip) †.

Failed to update the admin theme so did not even record anything in Error Log. 

Checked Prefs, was not yet updated to bootstrap3.
So I edited Prefs in DB, changed admin theme to bootstrap3.
The error_log in the admin folder then reported that the file jslib_handler.php was missing.

[06-Aug-2016 11:20:55 UTC] PHP Fatal error:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '../e107_handlers/jslib_handler.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/site/public_html/e107_handlers/core_functions.php on line 130

Uploaded jslib_handler.php and it loads. 

Still being kranky - Admin Menus don't respond, just add # to the URL. LAN_Errors - e.g. on the browser title bar.

Hence going to upload the full pack svn master zip from git, unzip to temp folder, remove e107_config.php and install.php, move to public home, which overwrites.

Hope this helps someone. 

Mikey

**Comment by tgtje** [comment]
Just used it this week, no problems. Jslib is in the update pack (1>2.1.1 ; org)... Maybe some transport issues ??

**Comment by MikeyGMT** [comment]
Forgot to add... Before backups, logged into Admin and of course set site to maintenance mode. 

... @tgtje Yup I thought that, but checked the zip file on local machine ... is missing. Decompressed again on server (cpanel) nope not there.  

Next went to Admin, menu's still misbehaving - so used the URL path from a fresh 2. site to get where I need. 

Went to e107_admin/theme.php?mode=admin 
Saved to infopanel. 

Remove deprecated files per the Orange Box. 

Doing DB upgrade now. Received ... 

Error
Adding Media Category: banner_image

Before continuing, please manually delete the following outdated folders from your system:
... lots of old plugin menus. 

Refreshed page

Performing these DB Actions ... 
Update from 1.x to 2.0 ... success
Update core database structure ... success
Add new or missing core settings ... success	
Statistic Logging	Update ... success
Newsletter ... success

Now the Menus drop down OK

Admin > Infopanel working properly

Tools> DB > Check DB Validity  ... success

Check Charset > Convert from MyISAM latin1_swedish_ci (no idea why it is that...) ... Taking a long time. 
Opened a fresh browser in admin, navigated to the same, obviously don't press Convert. ... is the list getting shorter? Hmmm. No. Leave it and make coffee.

**Comment by MikeyGMT** [comment]
Second attempt at conversion. Checked phpmyadmin, no tables have changed. Not working. See #357

**Comment by MikeyGMT** [comment]
Check for updates ... success. 

Checked Permissions ... success. 

Checking Tools > File Inspector > Check Integrity ... expecting a long list here (site running since 2001 on .6 something :) !

16 missing core files. 
457 old core files ... wow. That's a big clean up job. Nice if it could be fixed in the UI. 
12k non core files. Don't think they are all photos etc. 
OK so many reported non-core from the year dot. e.g. e107_handlers/calendar/sample.php  e107_handlers/calendar/menuarrow.gif  
Tried to print list to pdf or google drive but colour key is lost - does bootstrap3 need print colour setup? 

OK fiddled with settings - got a list of missing core files. 

 e107_plugins/gallery/gallery_style.css 	0 b ... CheckGit: in folder /gallery/css/
 e107_plugins/gallery/jslib/jquery.cycle.all.js 	0 b  ... CheckGit: in folder /gallery/js/

These not in GIT. 
 e107_plugins/gallery/jslib/prettyPhoto/css/prettyPhoto.css 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/default_thumb.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/loader.gif 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_next.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_prev.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_x.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_y.png 	0 b
 e107_plugins/gallery/jslib/prettyPhoto/js/jquery.prettyPhoto.js 	0 b

 e107_web/js/bootstrap-editable/css/bootstrap-editable.css 	0 b ... CheckGit: in folder /bootstrap**3**-editable/css/
 e107_web/js/bootstrap-editable/img/clear.png 	0 b ... CheckGit: in folder /bootstrap**3**-editable/img/
 e107_web/js/bootstrap-editable/img/loading.gif 	0 b ... CheckGit: in folder /bootstrap**3**-editable/img/
 e107_web/js/bootstrap-editable/js/bootstrap-editable.min.js 	0 b ... CheckGit: in folder /bootstrap**3**-editable/js/

 e107_web/js/zrssfeed/jquery.zrssfeed.min.js 	0 b ... CheckGit: zrssfeed folder missing. 

How does the inspector identify the missing files? Guessing an official build/release has a list to compare with and since the last, stuff has moved around. 

Nothing much to worry about I think.

**Comment by tgtje** [comment]
Very strange... when i download the same (either zip or tar) i do have the file...
As for gallery list (not Git) correct > https://github.com/e107inc/e107/commit/5598c9e7339a3ae945f5bf6695261daf0c5c78fe
So the update back has old structure......

**Comment by rica-carv** [comment]
@MikeyGMT You should use the latest github files from here, not the one on e107.org... If i recall better, thet file form e107.org is outdated and not synched with the latest updates from github here....

@tgtje You must be using the github files, right? So that's why there's the diference from you both packages....

**Comment by CaMer0n** [comment]
@MikeyGMT Just confirming here that jslib_handler.php is in the .zip file mentioned above.

**Comment by MikeyGMT** [comment]
Do'h - what a muppet! I downloaded the e107_v2.x_to_2.1.1_upgrade - yes it is there. 
Sorry I wasted folk time.

**Comment by tgtje** [comment]
No waste ! I does show that the updatepack has different files (age); where Git is always new..
@rica-carv ( no personal issues with packs) 
but be aware when updating!, and one does _not_ have v1.0.4 the best routine would be update the older v7.x to v1.0.4 and then to v2  When update is succeeded at that point> v2 sync... (aka use github files) 
( is that a guarantee? nope, but most chance of success).

**Comment by MikeyGMT** [comment]
Hi All
I think there is an issue here... 
These core files look like they are missing from the core git rep, unless they are deprecated, can anyone advise? 

They are listed in here e107_admin/core_image.php

Correct me if wrong, but looks like 
From Line 19 $core_image shows current core files 
From Line 2802 $deprecated_image list old core files.

When upgrading from GIT (and not the released files from e107.org) then they do not get installed, and are listed as missing by file inspector.

Hence either the list in core_image.php is incorrect or they are missing from the e107/master repo.  

Thanks

Mike

**core_image Line No .... path / file - comments below ** 

169 e107_core/shortcodes/batch/download_shortcodes.php 
* Download now a plugin, 
* Line 1294 - now lives here e107_plugins/download/download_shortcodes.php
* should it actually live here e107_plugins/download/shortcodes/download_shortcodes.php 
* remove from line 169 core_image.php? 

1681 e107_plugins/gallery/gallery_style.css 
* Only referred to in core_image.php looks like it should be moved to deprecated list?
 
1650 e107_plugins/gallery/jslib/jquery.cycle.all.js 	
1627 e107_plugins/gallery/jslib/prettyPhoto/css/prettyPhoto.css 	
1635 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/default_thumb.png 	
1636 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/loader.gif 	
1637 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite.png 	
1638 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_next.png 	
1639 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_prev.png 	
1640 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_x.png 	
1641 e107_plugins/gallery/jslib/prettyPhoto/images/prettyPhoto/default/sprite_y.png 	
1647 e107_plugins/gallery/jslib/prettyPhoto/js/jquery.prettyPhoto.js 	
* Looks likely that all of jslib are missing from repo

2047 e107_plugins/online/online_menu_template.php
* The file is there but under online/templates not the plugin route. 
 
2549 e107_web/js/bootstrap-editable/css/bootstrap-editable.css 	
2553  e107_web/js/bootstrap-editable/img/clear.png 	
2554 e107_web/js/bootstrap-editable/img/loading.gif 	
2558 e107_web/js/bootstrap-editable/js/bootstrap-editable.min.js 	
Looks like all these may be replaced by bootstrap3-editable folder but still in the core_image file - do they need to be moved to the deprecated list?

2736 e107_web/js/zrssfeed/jquery.zrssfeed.min.js 	
* cannot see that this is referenced by any other code?

**Comment by lonalore** [comment]
`jquery.cycle` and `jquery.prettyPhoto` libraries were moved to `e107_web/lib/` folder because these libraries are managed by Library Manager.

**Comment by MikeyGMT** [comment]
Thanks @lonalore 

Another funny ... these two files are both current and deprecated ...

Lines 239 and 4118 e107_themes/templates/admin_icons_template.php 	
Lines 255 and 4120 e107_themes/templates/nextprev_template.php 

With some coaching and advice I can update the files when we establish the correct status.

**Comment by Moc** [comment]
@CaMer0n Is the core_image up-to-date? Will the fileinspector correctly identify incorrect/outdated/deprecated files?

**Comment by CaMer0n** [comment]
@Moc It should be auto-updated when I package the release. Obviously, this doesn't apply to a github version.

**Comment by Moc** [comment]
Testing required;  make sure file inspector functions correctly and identifies old/deprecated files on official releases.
