### ISSUE TITLE
Bootstrap3 - Page Content / Title Not floating down with header menu area as it changes in height.

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1794]
Hi Themers 

This looks great

![image](https://cloud.githubusercontent.com/assets/2847651/17457214/eeecb69a-5be9-11e6-95c6-62d8dad1c0f8.png)

But widen a touch ... 

![image](https://cloud.githubusercontent.com/assets/2847651/17457219/09d3f5e0-5bea-11e6-8d18-3193d9c57547.png)

Full width... 

![image](https://cloud.githubusercontent.com/assets/2847651/17457222/20100f42-5bea-11e6-967e-e8af206a342d.png)

I wonder how to ensure the menu/header zone does not overlay the content area?

Thanks

Mike

**Comment by rica-carv** [comment]
As far i see it, it might be a bootstrap3 css coding issue, not a e107 directly related one....

**Comment by MikeyGMT** [comment]
Does it on several sites - upgraded and fresh install - from today's git repo. 
Shortening the sitename pref seems to prevent it from happening. It would be nice if the content started below the menu/header. Looks like content starts at a fixed point, and the menu spills over.

**Comment by rica-carv** [comment]
Tested, definetly bootstrap3 css issue, since this css rule on bootstrap3 navbar.less fixes navbar class, overlapping content:
```
.navbar-fixed-bottom, .navbar-fixed-top {
    position: fixed;
    right: 0;
    left: 0;
    z-index: 1030;
```

[Solutions here](https://www.google.pt/search?q=boostrap+fixed+navbar+overlapping+conten&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=9R2mV777IZLS8AfYnJ3oCg#q=bootstrap+fixed+navbar+overlapping+content)

**Comment by CaMer0n** [comment]
@MikeyGMT You'll need to adjust your theme/css to accommodate the long site title.

**Comment by CaMer0n** [comment]
Closing

**Comment by MikeyGMT** [comment]
Quick update 
If the Jumbotron gets too big then overlays the content. 
This seems to be the cause 
`body { padding-top: 48px;  `

This seems to do the trick 
`body { padding-top: 4.5pc; `

It's not perfect, but at least the content does not get overlayed.

**Comment by MikeyGMT** [comment]
It's line 3 of bootstrap3/style.css actually it was 50px not 48px  (viewing in chrome)

Actually maybe a better alternative... Browse to this page http://www.w3schools.com/bootstrap/ resize the browser window gradually, and as you make the page narrower, then the left menu items drop off rather than as we have - shoving everything right and then forcing the right (login) menu downward.

**Comment by CaMer0n** [comment]
A theme pref for the nav-collapse break-point will fix this.
