### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by bebbolino** [e107inc/e107#1798]
Hi i downloaded the last commit, when i upload the unzipped folders and files in my webhost, and link the url to http://www.mywebsite.com/install.php it give me Error 500.

Can someone please have a fix to that?

Regards

**Comment by mostvotedplaya** [comment]
What PHP version are you running there?

**Comment by bebbolino** [comment]
In the server there is PHP Version 5.5.32, with the 2.0 alpha4 (old version) the installation works.

Thanks for the reply.

**Comment by mostvotedplaya** [comment]
I see, at first i thought you was referring to the change here: https://github.com/e107inc/e107/commit/0b06fbda62ab59003ab7af52dc702e47c7a8f419 but that probably is not your problem because your php version should already have that.

**Comment by Moc** [comment]
Please check the Apache error log. Every 500 error produces more information in the error log. Using this information we can find the cause of the error and a possible solution.

**Comment by bebbolino** [comment]
I haven't access to the error_log of the server, the domain cannot permit it.
The display error is off (from phpinfo() ) and i don't know how to do to reproduce the error to you.

**Comment by Moc** [comment]
You may want to contact your webhosting provider to gain access to the error log then.

**Comment by tgtje** [comment]
Or an actual url, maybe the server thows in some info..

**Comment by CaMer0n** [comment]
Usually it's a file permissions or ownership issue.

**Comment by bebbolino** [comment]
I opened a ticket to the customer care of the hosting, they said that their antivirus detected the file "class2.php" as a potential danger file and automatically it was blocked.

They restore the file and everything works now. 

Thanks a lot for the care and response.
Regards
