### ISSUE TITLE
Extended User Fields Read Access / Write Access not working

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1799]
Hi devs,  I experience an issue where I have Extended User Fields assigned to capture members phone number and address. I want the member to be able to update these fields and view their own but not able to see others unless they are Admin users.

The way it seems to operate is a normal member user can view an Admin users telephone number and address rather than the other way around. 

I have the Extended User Field set to **Applicable-MEMBERS**  **Read Access-Admin  Write** **Access-Member**:
![image](https://cloud.githubusercontent.com/assets/15772899/17564911/0b5faad0-5f2d-11e6-8ec5-24f9e3b67fb5.png)

**Comment by Moc** [comment]
What happens when you change 'applicable to' to admin?

**Comment by martyshep** [comment]
Hi @Moc when I change the 'applicable' to admin, regular members cannot access the field to fill it in, it is only presented to admin.

The same behaviour on my site is still present.  The 'applicable' field dictates who would be presented the field to fill in, in their settings.  Where it gets messy is that the Read field works opposite to how I would imagine it should.  I use the field for members phone number.  I do not want other regular members to view other regular members phone numbers, but 'admin' people should be able. 

At present my 'admins' they have to be website Admins and go into Admin mode to list users, but they then see all the details.  It would be useful if my admins could see the field in the normal operation of the website, as I don't want to give them 'proper' admin access. 

So to get this working, I need to set the extended field to applicable=Members / read=no-one  / write=members.

If I set read=userclass_read, I would expect only people with userclass_read to be able to see the phone field of the other members.  However, what I get is that regular members can then view the phone of the admins with userclass_read, but not the other way around, which one may think would be the behaviour.

**Comment by Moc** [comment]
@martyshep Sorry it took so long, but this bug is now fixed.

**Comment by martyshep** [comment]
Awesome thanks Tijn!  Your support is far better than some paid for support
I've received in the past from companies :)

**Comment by Moc** [comment]
@martyshep You're welcome! 👍  Glad to hear. 
Information on how to support e107 can be found here: http://e107.org/community (last section).
