### ISSUE TITLE
Feature request: Featurebox fade instead slide

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1807]
an optional feature for featurebox to fade the items and not slide
it's possible?

**Comment by rica-carv** [comment]
It can be donne via a custom featurebox shortcode....

**Comment by Jimmi08** [comment]
I can be done by theme template or by css. 

If you use standard bootstrap 3 carousel, it can be done by css. There are a lot of solutions, f.e.:
http://stackoverflow.com/questions/9526970/can-the-twitter-bootstrap-carousel-plugin-fade-in-and-out-on-slide-transition
http://codepen.io/Rowno/pen/Afykb
http://stackoverflow.com/questions/18548731/bootstrap-3-carousel-fading-to-new-slide-instead-of-sliding-to-new-slide

If you need to change html markup too, you can do it by creating new template in your theme.  This is example for nerve slider: https://github.com/Jimmi08/e107_snippets/issues/11

**Comment by CaMer0n** [comment]
Indeed, CSS is enough to do this. Closing.

**Comment by Crytiqal** [comment]
## featurebox_category_template.php

```
$FEATUREBOX_CATEGORY_TEMPLATE['bootstrap3_carousel']['list_start'] = '
	<div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel">  
		{FEATUREBOX_NAVIGATION|bootstrap3_carousel=loop&uselimit=1}
  		<!-- Wrapper for slides -->
  			<div class="carousel-inner">
    
';
```
_notice to add the carousel-fade class._

## featurebox.css
```

.carousel-fade .carousel-inner .item {
  -webkit-transition-property: opacity;
  transition-property: opacity;
}
.carousel-fade .carousel-inner .item,
.carousel-fade .carousel-inner .active.left,
.carousel-fade .carousel-inner .active.right {
  opacity: 0;
}
.carousel-fade .carousel-inner .active,
.carousel-fade .carousel-inner .next.left,
.carousel-fade .carousel-inner .prev.right {
  opacity: 1;
}
.carousel-fade .carousel-inner .next,
.carousel-fade .carousel-inner .prev,
.carousel-fade .carousel-inner .active.left,
.carousel-fade .carousel-inner .active.right {
  left: 0;
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
}
.carousel-fade .carousel-control {
  z-index: 2;
}
```
