### ISSUE TITLE
Feature request: to be able filter in failed logins by username

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1808]
Because I still didn't get alt auth plugin worked, I need to create to user manually and I would like to delete all failed logins from user I have already between user. 
Now I can't.  Filtering by description would be enough. Thanks

![image](https://cloud.githubusercontent.com/assets/5429548/17817323/345a56ca-663e-11e6-877c-b6e9ea9202a9.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Done! :+1:

**Comment by Jimmi08** [comment]
Perfect. Thank you.
