### ISSUE TITLE
Curved brackets in HTTP GET variables return 403 error

### ISSUE THREAD

**Issue by Threecos** [e107inc/e107#1811]
I need to send a GET query with curved brackets, like ?foo={bar}, but the e107 return a 403 error page.

**Comment by rica-carv** [comment]
[Curly (curved) brackeyts in URLs](http://meta.stackexchange.com/questions/79057/curly-brackets-in-urls)

**Comment by Moc** [comment]
This is most likely due to security measures in e107. See some extract of it here: https://github.com/e107inc/e107/commit/0b06fbda62ab59003ab7af52dc702e47c7a8f419

@CaMer0n What's the best way to do this? html entities?

**Comment by CaMer0n** [comment]
I believe it's `foo=%7Bbar%7D` or `$foo = urlencode("{bar}");`

**Comment by Moc** [comment]
@Threecos Does this answer your question?
