### ISSUE TITLE
download plugin -  problem with restricted to members

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1817]
I use download plugin on two different sites.  Some of them can be downloaded just by members. 

Download is visible, just request can be downloaded by member. But when they tried it, they get message about  You have been prevented from downloading this file; you have exceeded your download quota
not that they haven't permission.
![image](https://cloud.githubusercontent.com/assets/5429548/18028445/c6937160-6c7f-11e6-88db-dd6bbe938d48.png)

On second site quest see this:
![image](https://cloud.githubusercontent.com/assets/5429548/18028441/b22b5b02-6c7f-11e6-8ccb-980f5a59ed83.png)

Limits are set this way  (default)
![image](https://cloud.githubusercontent.com/assets/5429548/18028458/360b0616-6c80-11e6-822f-fdb80af76c1b.png)

Thanks

**Comment by Jimmi08** [comment]
Example on the same site:
![image](https://cloud.githubusercontent.com/assets/5429548/18028520/8fcd654e-6c81-11e6-8156-5e91e06e85c3.png)

first download
![image](https://cloud.githubusercontent.com/assets/5429548/18028521/9589cac2-6c81-11e6-99bf-27fc6c326959.png)

second download
![image](https://cloud.githubusercontent.com/assets/5429548/18028526/a30d0588-6c81-11e6-9439-522180627c7c.png)

**Comment by tgtje** [comment]
Just testing the hp site > last download (guest) > action=error&id=4  > chyba 4 ( General error #  ID is triggered)..
Are the files present and how is chmod and/or language ? 
(can not replicate issue myself)

**Comment by Jimmi08** [comment]
Hi, files are there, member can download them. 
You can try it here:
http://www.e107.sk/download/5/links-page-plugin-2-3-1
language is English to avoid language issue. 
But it's true that on this site I have a lot of problems with this plugin (in admin area too). Second site is on different server and except this issue download plugin works fine.  I will update everything and see,

**Comment by Jimmi08** [comment]
ok,  site is updated, problem with download plugin is there too.  Only change I made was to add this to htaccess because setting this in site prefs didn't work.
```
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]
```
I can't debug this because if I use Firefox e107 debuger, my admin is empty. Not on localhost, just on production site.

![image](https://cloud.githubusercontent.com/assets/5429548/18033599/d8c4abf6-6d29-11e6-995d-684e7c24a219.png)

Console is empty. No error.

I can't edit download now too.  Empty screen. Only on production site. My php version was 5.4.37, so I changed it to 5.5 (to be on the same version as localhost) and debugger started to work and edit download is possible too. 

The reason for that happened just now not before was that on my hosting I had 5.5 for e107.sk, but for *.e107.sk there was5.4  (and using www caused that problem) .   So there is problem with download plugin and php 5.4 version.

I will try to add more info to issue above.

**Comment by Jimmi08** [comment]
I was able to reproduce this error on localhost. Now I just confirm that if file is not present, message is correct
![image](https://cloud.githubusercontent.com/assets/5429548/18033876/a203449c-6d2e-11e6-8aed-90ff1129e3a0.png)

**Comment by Jimmi08** [comment]
I have it.
First part of this test is always true in my case
 
![image](https://cloud.githubusercontent.com/assets/5429548/18034126/4f258896-6d35-11e6-87da-8a8203d6365b.png)
 
But in old version there were 
![image](https://cloud.githubusercontent.com/assets/5429548/18034166/26369398-6d36-11e6-9224-d3c7e9a06146.png)

- there is mising "1" in url, but test is 
![image](https://cloud.githubusercontent.com/assets/5429548/18034170/4880ed18-6d36-11e6-977d-31fe663c2a6a.png)

so that is reason why I get generic error.

**Comment by tgtje** [comment]
Hmm error 5 on sk...
Just curious .. did/do you use sef troughout?(or external/mirrored)
Example of what i mean...2 links; 1 yours, 1 mine: both represent the Get it (download)

e107.sk/download/get/5/links-page-plugin-2-3-1
domain/e107_plugins/download/request.php?1
and
th.../e107World/css/bootstrap.min.css.map is called somewhere but not found..

**Comment by Jimmi08** [comment]
I found the reason, there is no code for error in request.php file. Do you see this:
 
![image](https://cloud.githubusercontent.com/assets/5429548/18035494/4c68e32e-6d57-11e6-8fc0-c7aadd1af1b0.png)

if my id is 5, my error will be 5  and error message is only for 1 or 2. So with download ID < 3 I've got message (wrong, but it's there) otherwise it's just error.

no SEF-URL
![image](https://cloud.githubusercontent.com/assets/5429548/18035489/30358ad6-6d57-11e6-9d6b-8254f0bb8268.png)

with SEF-url:
![image](https://cloud.githubusercontent.com/assets/5429548/18035487/2a352812-6d57-11e6-9ff3-4fe3a5e127b4.png)

**Comment by Jimmi08** [comment]
@CaMer0n Could you just look if I am right or not? In request.php there is no code for error (just action and download ID) and it uses download id as code error. It just happens where download is visible for all but file is restricted to download for members. Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Is this still an issue?

**Comment by Jimmi08** [comment]
@CaMer0n I updated to latest github, but problem is still there

![image](https://cloud.githubusercontent.com/assets/5429548/19452436/51737e8e-94b1-11e6-8024-9cfeb34f9d92.png)

**Comment by CaMer0n** [comment]
Thanks @Jimmi08. Could you please send a pull-request of your proposed fix so I can review it?

**Comment by Jimmi08** [comment]
@CaMeRon I have no idea how to fix this.

**Comment by cameron** [comment]
Neither do I! ;)

**Comment by Jimmi08** [comment]
@CaMer0n  

@cameron I am sorry.  I know about this problem, I am very carefully about this, but I was on mobile phone and there were capitals so...    They really should do something with checking nicks with case-sensitive.

**Comment by fizi** [comment]
I confirm the error.

**Comment by CaMer0n** [comment]
@Jimmi08 @fizi @tgtje Would you mind please re-testing with the patch?

**Comment by fizi** [comment]
On English - ok, on Hungarian the problem same.

**Comment by tgtje** [comment]
Did replace the file lines. for me NO actual change. I will need to investigate deeper as it still does point me to something doing something to the url's  (sef vs full paths).

As for fizi's site : i can confirm the error lines are changed to language eg displayed text. Clicking here and there (no point in describing which where, 1 example : lang switch) it will lead eventually to also url misbehaviour > ends in 404..  Very puzzled at the moment....

**Comment by Moc** [comment]
Make sure the caches are cleared when debugging this issue :)

**Comment by Jimmi08** [comment]
For me problem is solved:

![image](https://cloud.githubusercontent.com/assets/5429548/21566008/e9ac33d6-ce9e-11e6-84d9-158b875f204a.png)

Thanks to all.

**Comment by fizi** [comment]
Perfect in both languages! Thanks!
