### ISSUE TITLE
download plugin - batch changes - missing member userclass

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1818]
I noticed that in batch there is different list of userclass
![image](https://cloud.githubusercontent.com/assets/5429548/18028843/94a72184-6c88-11e6-8e62-5847767f544a.png)

then in inline editing 

![image](https://cloud.githubusercontent.com/assets/5429548/18028845/a46f08e8-6c88-11e6-9955-e882df70b47a.png)

plugindownload

**Comment by tgtje** [comment]
My 2 cents worth : maybe (could be related to boot/perms ;  basically there will be a reason for it ???; diversity for the 2 different methods in use > class vs visibility? # awareness ?  )
The array listing... > userclass2  lines 100; 102.
