### ISSUE TITLE
File Inspector > Setup > would be better named Scan

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1819]
Hi All, 
Opening the File Inspector, the left menu options are 
"Setup" 
"Results"

Setup is not really correct, it would be better to rename this to 
"Scan"

Does anyone disagree ?
Thanks
Mikey

**Comment by CaMer0n** [comment]
@MikeyGMT Okay to change it ! :+1:  Just make sure if you edit the LAN that it is not used anywhere else (as "Setup").

**Comment by MikeyGMT** [comment]
Slight mod proposed... Scan Now moved to the left menu, Scan Now was on the (renamed) Go button.

![image](https://cloud.githubusercontent.com/assets/2847651/18147132/29adb776-6fcb-11e6-81ff-9a69b563c856.png)

About On and Off, in prefs we use yes/no - shall we use yes/no instead?

**Comment by MikeyGMT** [comment]
>	function create_image($dir) {

I have not changed this section, no idea if it is used, but we should update the copyright data. Any thoughts? 

>	function snapshot_interface() 

Lots of TODO-LANS ... again, no idea if used / what it really does. 

>	function parsesize($size, $dec = 0) {

https://en.wikipedia.org/wiki/Megabyte
File Size in file inspector is lower case for KB, MB, GB etc., SI unit nomenclature should be corrected e.g. kB, MB, GB, TB etc. I does not need to be translated, being an international standard. 

Comments?

**Comment by MikeyGMT** [comment]
> function fileinspector_adminmenu() //FIXME - has problems when navigation is on the LEFT instead of the right. 
 
Unclear, is this still relevant seems ok to me?

**Comment by MikeyGMT** [comment]
define("FC_LAN_5", "Core Files");

define("FR_LAN_4", "Core files");

Why?

**Comment by MikeyGMT** [comment]
![image](https://cloud.githubusercontent.com/assets/2847651/18148657/ec45e55e-6fd2-11e6-9245-779a6b60db32.png)

How's that?

**Comment by MikeyGMT** [comment]
TODO LANS on snapshot_interface Done, but it isn't working - on unmodified site. There's a number of duplicate defines. Commenting those.

**Comment by MikeyGMT** [comment]
Redone the LANS work in File inspector. 

In Dev Mode - I played with the PREG String match function. Seems to do something odd, depending on the string - examples from the php page link in the help text. 

Sometimes never completes 

![image](https://cloud.githubusercontent.com/assets/2847651/19237426/bc656922-8ef4-11e6-916a-c96a52d8d401.png)
 

![image](https://cloud.githubusercontent.com/assets/2847651/19237385/7d50c650-8ef4-11e6-8bc9-ee6cc34c64e9.png)

All times it creates a massively long page, largely empty. Never has any file inspector results. 

Anyway, create snapshot does not appear to work - so I have not touched that area.

**Comment by MikeyGMT** [comment]
Aha it's max out the memory allocation. 

[10-Oct-2016 13:58:36 UTC] PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 58 bytes) in /home/site1/public_html/e107_admin/fileinspector.php on line 637

**Comment by Moc** [comment]
I think this issue can be closed now as the PR is merged. Let me know in case it still needs to be open.
