### ISSUE TITLE
different values for e_CURRENT_PLUGIN in frontend vs admin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1821]
e_CURRENT_PLUGIN has different value in admin area and in frontend

Admin:
- just plugin name
![image](https://cloud.githubusercontent.com/assets/5429548/18035607/379c6a04-6d59-11e6-8a24-e88f0b55fa04.png)

Frontend:  - plugin name with slash
![image](https://cloud.githubusercontent.com/assets/5429548/18035609/43af499c-6d59-11e6-8d77-a72939b658af.png)

Is this correct?

**Comment by CaMer0n** [comment]
@Jimmi08 It could be correct. It depends on which URL you are on. Could you please display the URL for each page as well?

**Comment by Jimmi08** [comment]
I was on localhost, but I did it on live site too
http://www.e107.sk/e107_plugins/download/admin_download.php
![image](https://cloud.githubusercontent.com/assets/5429548/18035662/35881e56-6d5a-11e6-84c8-8680d7e90fa7.png)

http://www.e107.sk/download
![image](https://cloud.githubusercontent.com/assets/5429548/18035664/431fcbcc-6d5a-11e6-93b5-95aa9dcc1ab5.png)

if I set sef-url OFF for this plugin:
http://www.e107.sk/e107_plugins/download/download.php
![image](https://cloud.githubusercontent.com/assets/5429548/18035674/7a5b472e-6d5a-11e6-80b9-4f1467854cba.png)

I need to be sure that in admin area there will be always the same value.

**Comment by CaMer0n** [comment]
@Jimmi08 Please update and try again. Thanks

**Comment by Jimmi08** [comment]
@CaMer0n Perfect! Thank you. I noticed this only because there is no plugin folder name in plugin.xml as before in plugin.php (yes, I know it's in plugin table). This solve it.

**Comment by Jimmi08** [comment]
Oh, I close this, I will reopened it if I find problem, but from look at your code I don't think it will be this case..

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 !
