### ISSUE TITLE
media manager with filtering files doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1823]
When I want to select file (already uploaded to server),  there is button Select
![image](https://cloud.githubusercontent.com/assets/5429548/18090953/4fc78c20-6ec7-11e6-8ee9-6fe9848bb3b0.png)

When I use filter, screen is changed and no select button there:
![image](https://cloud.githubusercontent.com/assets/5429548/18091051/995ee310-6ec7-11e6-907e-c542df5a8a6d.png)

I used MM in download plugin if it's somehow related.

**Comment by tgtje** [comment]
I  would suggest it being an Enhancement (add select (button and code), as filter works to display the corresponding characters found (only editable (versatile)/delete mode). 
The select marker in front also has no select/save using the Go function.
Would be very usefull as @Jimmi08 discovered. 👍

**Comment by Jimmi08** [comment]
Works in 2.1.7
