### ISSUE TITLE
sub-category of gallery

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#1824]
sub-gallery sub-category is possible?

for example:

gallery1 -->image1 .. image2 .. image3 sub of gallery1--->gallery2 {image4a ... image5a ... image6a}

gallery3 --> image4 ...image5 .... image6

 sub of gallery3---->gallery4 {image9...image10..image11}...

 sub of gallery3---->gallery5 {image12..image13...image14}...

 sub of gallery3---->gallery6 {image5 .... image6 .... image7 ecc.. }

**Comment by tgtje** [comment]
duplicate ? still open enhancement label : #1040

**Comment by Moc** [comment]
Closing in favour of #1040
