### ISSUE TITLE
Enhancement Plugin Builder - not check table if it's exluded

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1829]
Plugin builder is not able to working with FLOAT in SQL definition. So not to abort all proces and start again I set problematic table with Mode Exclude this table.  But validation still stops on this table. 
It's just annoying, problem was in sql, not in e107.

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please share your database "CREATE" sql dump so I can test it ?

**Comment by Jimmi08** [comment]
@CaMer0n I think it was with easyshop sql table. 
Here:  https://github.com/e107inc/e107-easyshop/blob/master/easyshop_sql.php

**Comment by Jimmi08** [comment]
Not needed anymore
