### ISSUE TITLE
$sc_style not working with new SC batch methods

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#183]
The problem is most noticeable on contact.php (secure image enabled) and usersettings.php (signature enabled) where the script has replaced the regular template include with the new method to load templates. 

I have added a new standard in contact_template.php which should be used in future instead of $sc_style. eg. 

```
$CONTACT_WRAPPER['form']['CONTACT_PERSON'] = "<tr><td>".LANCONTACT_14."<br />{---}</td></tr>";
```

ie. very similar markup to the template, and intuitive. The empty shortcode {---} being what will be replaced by the actual shortcode data (if it returns some). 

The $XXXXXXX_WRAPPER still needs to be assigned to the value $wrapper in the e_shortcode class and later split into pre/post later in the shortcode-handler where $sc_style is currently managed. 

```
ie. list($pre,$post) = explode("{---}", $wrapperValue); 
```

The goal being to have it working without the need for additional methods or code in contact.php or usersettings.php .

ie. integrate with e107::getCoreTemplate(), _getTemplate(), and e107::getScBatch()

**Comment by rica-carv** [comment]
Sorry for bringing this up again, but `$SC_WRAPPER` doesn't work on forum template shortcodes (`{FORUMTITLE} {SUBFORUMS}`) despites it does work on news template shortcodes (`{NEWSTHUMBNAIL} {NEWSIMAGE}`)....
Can it be the way forum shortcodes are built???
