### ISSUE TITLE
not able use php7 with e107

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1831]
Because testing I switch on my demo site to php7 and I got error about not able to connect to database.

This is instruction from my hosting:
![image](https://cloud.githubusercontent.com/assets/5429548/18227356/12d3035e-7222-11e6-80f3-75f01954cc4c.png)

When I do it this way, site is ok.
![image](https://cloud.githubusercontent.com/assets/5429548/18227359/2f65cc04-7222-11e6-86a4-18feb06d19df.png)

First problem:
mysql port is hardcoded.
![image](https://cloud.githubusercontent.com/assets/5429548/18227366/4ad51558-7222-11e6-97d5-9a2c90ec4a35.png)

Second problem: I don't see in original code database settings (dbname)
![image](https://cloud.githubusercontent.com/assets/5429548/18227373/694cda66-7222-11e6-8fa2-999f85e95420.png)

**Comment by CaMer0n** [comment]
e107_config.php 

    $mySQLserver = "mariadb55.websupport.sk:3310";

**Comment by Jimmi08** [comment]
@CaMer0n 
I didn't know what causes problem. I use config this way, always. But I will check it again. 

What about second problem? Missing database from PDO parameters? I am not able to test this now, but if you explain me where I am blind, it could help.

![2016-09-17_11-14-20](https://cloud.githubusercontent.com/assets/5429548/18607268/534699b8-7cc8-11e6-9c73-986fa94a9ebe.png)
![2016-09-17_11-14-02](https://cloud.githubusercontent.com/assets/5429548/18607270/6873057e-7cc8-11e6-9fed-2f7c79d4999f.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 We use: 

	if (!$this->database($this->mySQLdefaultdb))
	{
			return 'e2';
	}

What is the specific error message you are seeing?

**Comment by Jimmi08** [comment]
@CaMer0n  You can see yourself:
http://v2demo.e107.sk/
![image](https://cloud.githubusercontent.com/assets/5429548/18614427/deb19766-7d8e-11e6-858a-68447bdb55c6.png)

Updated latest github.  If I hardcoded new PDO parameters, it works (like on first picture).   I will send you access, it would be better.

**Comment by CaMer0n** [comment]
@Jimmi08 Please update, I believe this should fix it.

**Comment by Jimmi08** [comment]
@CaMer0n   Works. Thank you.
