### ISSUE TITLE
TinyMCE4 hidden HTML button

### ISSUE THREAD

**Issue by JohanKlos** [e107inc/e107#1832]
By default the TinyMCE4 interface is not showing the HTML button.

The code plugin from the tinymce.com website shows code how to show that button: https://www.tinymce.com/docs/plugins/code/

Maybe the admin config for TinyMCE4 could get an option to show/hide the HTML button?

**Comment by CaMer0n** [comment]
@JohanKlos It is usually in the "Tools" menu of the editor. Does it display there for you?

**Comment by JohanKlos** [comment]
@CaMer0n thank you for your reply.

Sometimes the tools menu is there (I'm guessing you mean the "Source code" option), such as:
/e107_admin/newspost.php?action=edit&id=8
![damnedifyoudo](https://cloud.githubusercontent.com/assets/639844/18607733/cb294b80-7cd5-11e6-9426-49a2bf3bc161.jpg)

Sometimes it isn't, such as here:
/e107_plugins/forum/forum_post.php?f=edit&id=1&post=1
![damnedifyoudont](https://cloud.githubusercontent.com/assets/639844/18607734/cb2cc152-7cd5-11e6-92ea-1685750a94c5.jpg)

**Comment by CaMer0n** [comment]
@JohanKlos Yes, this because the forum uses the 'members' TinyMce template. You may modify this template by copying it from the TinyMce folder to your theme folder. ie. --your-theme--/templates/tinymce/member.xml
