### ISSUE TITLE
News shortcodes

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#1833]
I have modified e107_core, shortcodes, batch:

Line 175 <a title='".LAN_COMMENTS."' href='

**Comment by CaMer0n** [comment]
@yesszus Thank you. I understand the folder/directory, but which file is that?

**Comment by yesszus** [comment]
Yes folder/directory. File: news_shortcodes.php

**Comment by rica-carv** [comment]
[Current line 175 on news_shortcodes.php](https://github.com/e107inc/e107/blob/master/e107_core/shortcodes/batch/news_shortcodes.php#L175):
`		return (!$news_item['news_allow_comments'] ? ''.($pref['comments_icon'] ? $NEWIMAGE.' ' : '')."<a title='Comments' href='".e107::getUrl()->create('news/view/item', $news_item)."'>".$param['commentlink'].intval($news_item['news_comment_total']).'</a>' : vartrue($param['commentoffstring'],'Disabled') );
`

**Comment by CaMer0n** [comment]
Thank you @yesszus @rica-carv ! :+1:
