### ISSUE TITLE
Admin shortcodes

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#1834]
I have modified e107_core, shortcodes, batch: admin_shortcodes.php
Line: 744  -> 752

https://github.com/e107inc/e107/blob/master/e107_core/shortcodes/batch/admin_shortcodes.php#L744

`<li class="dropdown">
            <a class="dropdown-toggle" title="'.LAN_PM.'" role="button" data-toggle="dropdown" href="#" >
                '.$tp->toGlyph('fa-envelope').$countDisp.'<b class="caret"></b>
            </a> 
            <ul class="dropdown-menu" role="menu" >
                <li class="nav-header navbar-header dropdown-header">'.LAN_PM.'</li>
                    <li><a class="e-modal" data-cache="false" data-modal-caption="'.LAN_PLUGIN_PM_INBOX.'" data-target="#uiModal" href="'.$inboxUrl.'" >'.LAN_PLUGIN_PM_INBOX.'</a></li>
                    <li><a class="e-modal" data-cache="false" data-modal-caption="'.LAN_PLUGIN_PM_OUTBOX.'" data-target="#uiModal" href="'.$outboxUrl.'">'.LAN_PLUGIN_PM_OUTBOX.'</a></li>
                    <li><a class="e-modal" data-cache="false" data-modal-caption="'.LAN_PM_35.'" data-target="#uiModal" href="'.$composeUrl.'">'.LAN_PM_35.'</a></li>
                </ul>`

**Comment by yesszus** [comment]
[https://github.com/e107inc/e107/blob/master/e107_core/shortcodes/batch/admin_shortcodes.php#L745](url)

**Comment by rica-carv** [comment]
And if i may ask, why?

**Comment by yesszus** [comment]
Add translation.
'.LAN_PM.', '.LAN_PLUGIN_PM_INBOX.' etc...

**Comment by CaMer0n** [comment]
@yesszus Thank you. Please fork e107, make your changes to your e107 repo, and then submit a pull-request explaining the benefits of the change.
