### ISSUE TITLE
TinyMCE Smileys do not appear in Forum posts

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1835]
Using TinyMCE4 plugin, in forum post creation, can select smiley from the menu. However this does not then show in the post itself. 
![image](https://cloud.githubusercontent.com/assets/15772899/18310974/8e3c1fb0-74f9-11e6-9595-1883d2983ee8.png)

**Comment by schlrech** [comment]
i think its the same issue https://github.com/e107inc/e107/issues/1700

**Comment by martyshep** [comment]
It is very similar but slightly different. I found that thread and applied
the suggestion to no avail. Funnily enough if I edit a page and include
tinymce smileys the one for wink works OK but others do not. But in forum,
even wink does not work. If I put the code ;) it does show the emote in
forum.

**Comment by CaMer0n** [comment]
Please right-click on the broken images and paste their IMG src paths here.. it may give some clues. 
Thanks.

**Comment by yesszus** [comment]
Broken images src path:
http://mydomain/thumb.php?src=&w=0&h=0

**Comment by martyshep** [comment]
When a smiley is used from TinyMCE in a forum post I see: <img src="/3per/thumb.php?src=&amp;w=0&amp;h=0" title="grin">

/3Per is a directory after my website root that E107 lives in.
