### ISSUE TITLE
Online + Last seen menus

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1855]
The 2 menus work together on the same page only if Online is first. If you use Last Seen first, Online is not displayed. The issue is the same with core themes too.

**Comment by mcpeace-maw** [comment]
Thanks @lonalore for the fix. @CaMer0n I think is safe to close this issue.

**Comment by lonalore** [comment]
It seems that the file (lastseen_menu.php) is missing.

**Comment by martyshep** [comment]
Ok so I created /plugins/lastseen and moved lastseen_menu.php to this directory and it starts working :)
