### ISSUE TITLE
User avatar shortcode issue

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1858]
I see now USER_AVATAR shortcode return blank avatar image even when you are logged in.

**Comment by chimcen** [comment]
E107-Team - any news about that? Got the same error here...

**Comment by Moc** [comment]
Yes, there appears to be an issue here. I'll test it asap and add it to the todo for the next release.

**Comment by Moc** [comment]
Confirmed the issue. Debugging gives some strange results. 
@CaMer0n Can you take a look to see if you can reproduce? Otherwise I can provide additional info.

**Comment by CaMer0n** [comment]
Thanks @Moc . I'm unable to reproduce it. I tried with a 'default' avatar and with an uploaded avatar and they display correctly. (in the bootstrap3 login menu at least).

**Comment by Moc** [comment]
Hmm, I use a standalone page with the {USER_AVATAR} shortcode: 

```php
<?php
require_once("class2.php");
require_once(HEADERF);

$sql = e107::getDb();
$ns = e107::getRender();
$frm = e107::getForm();
$text = '';

$text .= "{USER_AVATAR}";

$ns->tablerender("Test for avatar sc", e107::getParser()->parseTemplate($text));

require_once(FOOTERF);
exit;
```

**Comment by mcpeace-maw** [comment]
In bootstrap3 theme is used the shortcode with parameter shape, USER_AVATAR: shape=circle, try without parameter, just USER_AVATAR and will return default generic avatar image even when you are logged in.

**Comment by CaMer0n** [comment]
Was just testing that.. I reproduced it..  fix pending..

**Comment by Moc** [comment]
Confirmed! when using `{USER_AVATAR: shape=circle}` the correct avatar shows. Thanks @mcpeace-maw

**Comment by CaMer0n** [comment]
@mcpeace-maw @Moc Please re-test, thank you.

**Comment by Moc** [comment]
Fixed for me

**Comment by mcpeace-maw** [comment]
Working now. Thanks.
