### ISSUE TITLE
Missing "plugin status" check in cron handler

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1875]
Recently I noticed that rapidly running out of space. I started looking through the folders and noticed that my backup folder has a lot of zip files. Because of my "backup_dropbox" plugin. It also saves zip files locally before uploading to dropbox. But I uninstalled this plugin months ago (this may be the reason it couldn't upload backup files to my dropbox... missing plugin prefs). The point is that e107 left the cron job in the list:
![kepernyokep_2016-09-20_10-04-43](https://cloud.githubusercontent.com/assets/6043821/18662638/82129bb6-7f1b-11e6-98d5-8fdaabcd807a.png)
Now, I placed a check to my plugin (`e107::isInstalled('backup_dropbox')`), but I think we should also add additional checks into cron-handler in order to avoid such things.

**Comment by CaMer0n** [comment]
Indeed! :+1:

**Comment by lonalore** [comment]
@CaMer0n can you please review this commit? I think this will solve the problem.

**Comment by CaMer0n** [comment]
Thanks @lonalore I added something similar which uses less queries.

**Comment by lonalore** [comment]
Perfect! Thank you! :)
