### ISSUE TITLE
Visiting "Admin -> Emoticons -> Installed packs" ruins the database...

### ISSUE THREAD

**Issue by jornmo** [e107inc/e107#1879]
When visiting "Admin -> Emoticons -> Installed packs" the database is somehow ruined and both the admin panel and the front end is just displaying the theme without almost no content...

**Comment by Moc** [comment]
I suggest you contact @CaMer0n (main developer of e107) directly through Gitter: https://gitter.im/e107inc/e107  

This is a chatroom based on Github accounts. He'll be able to assist you in real-time to debug the issue.

**Comment by Jimmi08** [comment]
@Moc I can't confirm this. @jornmo it needs more information. Was it fresh install or update? Where did you use emoticons? F.e. only in chatbox plugin etc...
