### ISSUE TITLE
question update plugin from github

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1881]
I noticed possibility with update plugin from github with Links Page plugin.

This was result:
 
![image](https://cloud.githubusercontent.com/assets/5429548/18709373/136296c2-8000-11e6-8446-daa73cab019b.png)

I see some fatal error, but message is green.

What is wrong? This is nice feature, but how I can get it works?

**Comment by Moc** [comment]
As far as I know, this feature is not yet functional. The fatal error message (even though not recognized as an error) may be a result Git not being installed or being incorrectly configured on your server. This is just a guess. 

@CaMer0n Is there already a update routine available when Git is not installed on the server? (ie. recognize need for update, download zip, overwrite files routine?).

**Comment by CaMer0n** [comment]
@Moc this routine is for developer mode using a git repo. (no zip downloads). I just need to add some errors for people trying it without it being a .git plugin.

**Comment by Jimmi08** [comment]
@CaMer0n What is mean - without being a .git plugin?  That there should be .git repository left when I create zip package? Thanks

**Comment by Moc** [comment]
I think Cameron is referring to having a local machine or a shared hosting with git installed (the software). You then use git commands in the command shell to perform git actions (clone, update, checkout, merge, etc.). 

At this point there is no plugin update function available if git is not installed on the server.

**Comment by CaMer0n** [comment]
@Moc is correct. Git must be installed on the server and the plugin added using git commands.

**Comment by Jimmi08** [comment]
So I should create my zip from my local github repository and left .git folder there?

**Comment by Moc** [comment]
It's not just about the .git folder. In addition, the git software also has to be installed on your server and properly configured to point to the right folders.

**Comment by Jimmi08** [comment]
@Moc  That I understand. But if I delete .git folder from plugin, will it work? Because before I deleted it manually. It would be easier left it there.

**Comment by Moc** [comment]
No :)The git folder is not the only thing that's required. The server also needs to have the git software installed and properly configured. The .git folder only contains meta data. The actual commands like updating (pull) cannot be executed when the software is not installed. So this feature is really meant for developers or people who own their web hosting platform (dedicated servers etc.)

**Comment by Jimmi08** [comment]
@Moc We probably talk about that same thing. I need 2 things.
