### ISSUE TITLE
wrong action in form with userlanguage menu

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1883]
I noticed that with SEF-URL (via e_url.php) this code:

	`$action = (e_QUERY && ! $_GET['elan']) ? e_SELF.'?'.e_QUERY : e_SELF;`

return wrong path (adding e_QUERY to URL, path URL is already correct thanks SEF-URL)

Changing this to 
`$action = e_REQUEST_SELF;` 
helped

I am not sure it's correct or problem was somewhere else.

**Comment by CaMer0n** [comment]
@Jimmi08 That looks like the correct fix.

**Comment by Moc** [comment]
Fixed by pull-request #1908
