### ISSUE TITLE
not able upload media  - No HTML5 support.

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1886]
I have the same server, the same versions of e107, only diff is that on subdomain I have php 7 .

On site with php7 I get this error:
![image](https://cloud.githubusercontent.com/assets/5429548/18808139/29a4bc60-825a-11e6-81ae-46119cb275fc.png)

On site with php 5 it works.

And I noticed that with site on php 7 I have no problem with github update (it gets finished with green screen), on site with php 5 update is finished (I can see that files were updated) but latest message screen is not displayed and result is error (I noticed similar issue from somebody before).   I thought it's because my server settings, but both sites are on the same server, on the same domain, only diff is php version.

What should I check?

**Comment by lonalore** [comment]
Do you see any errors on your browser's console? It seems that plupload library is missing. "No HTML5 support." is the default rendered content, and plupload should replace it with file uploading widget. I tried to reproduce this issue with PHP 7.0.7 and 7.0.10, but everything worked properly.

**Comment by tgtje** [comment]
Just comment, i sometimes have  seen  it on php 5 X and 7 happen . A couple of times later it (message) dispappeared. cause or reason unknown.  Maybe.. just maybe the external calls..

**Comment by Jimmi08** [comment]
@lonalore   yes, I see.  


my jquery setting:
![image](https://cloud.githubusercontent.com/assets/5429548/18815564/03037844-8336-11e6-9c5e-9c67928c69b1.png)

![image](https://cloud.githubusercontent.com/assets/5429548/18815562/debc4db2-8335-11e6-9b0a-4fe10f734563.png)
it has something with Moxie
 
![image](https://cloud.githubusercontent.com/assets/5429548/18815618/0e6cd012-8337-11e6-88e5-66aea9aa4076.png)

Uff, there is else one different -  site on php7 has 3 languages (but I have English set for admin), site on php 5 just English. 

Screen from source code (click to enlarge):
![image](https://cloud.githubusercontent.com/assets/5429548/18815664/9b6a6380-8337-11e6-8e95-938b50a8733a.png)

**Comment by lonalore** [comment]
Please try to update your `plupload` files to the latest stable version: [v2.1.9 (security update)](https://github.com/moxiecode/plupload/releases/tag/v2.1.9)
You can find `plupload` files under your `e107_web/js/plupload` folder. Take care to delete/replace only `plupload` library files (upload.php is an integration file). 

@CaMer0n We should move these libraries to `e107_web/lib` folder, and left only integration files here. It would be easier to update them.

**Comment by Jimmi08** [comment]
@lonalore Thanks. Confirm it helped (Empty Cache was needed at first). Works unde php 7 and 5.5. too. 

You can close this after CaMerOn see this.

**Comment by CaMer0n** [comment]
Thank you!! @Jimmi08 would you mind re-testing with the committed changes?

**Comment by Jimmi08** [comment]
@CaMer0n Re-tested. Working. Thank you both.

**Comment by Kojack-59** [comment]
hello, I have the same bug but I downloaded the last version (2.3.0) on github
any ideas ?

**Comment by Jimmi08** [comment]
@Kojack-59 Did you clear cache? Check your console for any error (F12). You should create your own issue. PHP version, live or localhost etc...?
