### ISSUE TITLE
Not able download plugin with Find plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1907]
It's not my site, not my server.  

What can be reason for this? When I click on Find plugin, then f.e. Links (not related), result is  

![image](https://cloud.githubusercontent.com/assets/5429548/19016493/ff61b36e-881b-11e6-8baa-b014e60754e5.png)

PHP Version 5.4.45
Latest Github
Linux
USA

Thanks

**Comment by tgtje** [comment]
No idea if it will help ( common reports; most mentioned php 5.4...), but let search on (likely php.ini file) if magic_quotes_cpg=On   or register_globals = on (first : do decomment, second=deprecated).
So server related not e107

**Comment by Moc** [comment]
The easiest way to find the cause of a HTTP 500 error code is by checking the Apache error log file. This file contains a more detailed message.

**Comment by Jimmi08** [comment]
Closing. No feedback from site owner, but I see it works now.
