### ISSUE TITLE
Error at installation - MySQL Reported Error: SQLSTATE[42000]

### ISSUE THREAD

**Issue by A-Merlin** [e107inc/e107#1909]
Message:  

> Install complete. The installer couldnot select databaze "3056187-de". Sintax error 1064. 

This error repeated 4 times on 8 step.
Log:

> 1475444078, 16-10-02 21:34:38  Stage 1 started
> 1475444078, 16-10-02 21:34:38  Stage 1 completed
> 1475444083, 16-10-02 21:34:43  Stage 2 started
> 1475444083, 16-10-02 21:34:43  Stage 2 completed
> 1475444391, 16-10-02 21:39:51  Stage 3 started
> 1475444391, 16-10-02 21:39:51  Stage 3 completed
> 1475444399, 16-10-02 21:39:59  Stage 2 started
> 1475444399, 16-10-02 21:39:59  Stage 2 completed
> 1475444420, 16-10-02 21:40:20  Stage 3 started
> 1475444420, 16-10-02 21:40:20  Stage 3 completed
> 1475444441, 16-10-02 21:40:41  Stage 2 started
> 1475444441, 16-10-02 21:40:41  Stage 2 completed
> 1475444475, 16-10-02 21:41:15  Stage 3 started
> 1475444475, 16-10-02 21:41:15  Stage 3 completed
> 1475444485, 16-10-02 21:41:25  Stage 4 started
> 1475444485, 16-10-02 21:41:25  Stage 4 completed
> 1475444487, 16-10-02 21:41:27  Stage 5 started
> 1475444487, 16-10-02 21:41:27  Stage 5 completed
> 1475446026, 16-10-02 22:07:06  Stage 6 started
> 1475446026, 16-10-02 22:07:06  Stage 6 completed
> 1475446060, 16-10-02 22:07:40  Stage 7 started
> 1475446060, 16-10-02 22:07:40  Config file written successfully
> 1475446060, 16-10-02 22:07:40  Stage 7 completed
> 1475446064, 16-10-02 22:07:44  Stage 8 started
> 1475446064, 16-10-02 22:07:44  Errors creating tables: Программа установки не может выбрать базу данных: '3019132-de'
> <b>MySQL сообщила об ошибке:
> </b><i>SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '3019132-de' at line 1</i>
> 1475446064, 16-10-02 22:07:44  Stage 8 completed.
> 
> The problem described earlier here [http://www.1gb.ru/wiki/index.php?title=Joomla_-_%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0_%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8_%D0%B1%D0%B0%D0%B7%D1%8B](url).
> In what files to remove the database name validity checks?

**Comment by tgtje** [comment]
likely install php around line 503  Afaik it should work.

**Comment by A-Merlin** [comment]
All steps 1-8 completed successfully. An error occurs in the transmission of parameters from config.php to the database. The 503 line is pattern = '^ [a-zA-Z0-9 _-] *'

**Comment by A-Merlin** [comment]
See - [https://regex101.com/](url). 
"^ [a-zA-Z0-9 _-]"  and "3019132-de": full match!

**Comment by A-Merlin** [comment]
Version PHP was 7.07, e107 - 2.1.1. Easily install only the version e107 2.0.0 to PHP 5.6.  Thank you for your attention!

**Comment by Moc** [comment]
@A-Merlin Thank you for your feedback. This will be looked into as soon as possible.

**Comment by CaMer0n** [comment]
@A-Merlin Please try installing using the latest files from Github.

**Comment by Moc** [comment]
This should have been resolved by now. If not, please re-open.
