### ISSUE TITLE
Emoticons are too small in chatbox/chatbox2

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#1910]
Hi,

in chatbox2 the emoticons are to small - at selecting point in chatbox2 they are normal sized, but after then in chatbox2 post they are smaller then normal round about 75% smaller...

**Comment by Moc** [comment]
Even though this is a third-party plugin, let's see if this is an issue originating for the core of e107. 

Please answer the following questions:
- Which theme are you using on your website?
- Does the issue also occur when you use the bootstrap 3 theme? 

Thanks :-)

**Comment by chimcen** [comment]
Sry for the late reply.
Now i've used default bootstrap 3 them and default e107v2 chatbox - resultet in the same...
What it should like be:
![wanted](https://cloud.githubusercontent.com/assets/22658487/19440452/45e9d722-9482-11e6-8a67-1bc71797da3f.JPG)

What it resulted in:
![got](https://cloud.githubusercontent.com/assets/22658487/19440460/4a913bb2-9482-11e6-9a0d-3d0bd7990e06.JPG)

**Comment by chimcen** [comment]
Issue can be closed. Made a new installation (instead of an update) an imported only the necessary DB entrys) - now emoticons appear to be as they should in real size... seems to be an DB error...

**Comment by chimcen** [comment]
After configure the hole page it apears again - it seems only emote with a size of 18*18px will be displayed correctly - all others will be squashed to to a max size (longest side) to 18px...

Is this behavior controlled by any handler or someting?

**Comment by chimcen** [comment]
Btw. here is a screen - and its not a problem from the used theme - same behavior at default bootstrap3 theme...

![emote_problem](https://cloud.githubusercontent.com/assets/22658487/19929892/f4f791ac-a105-11e6-9ec0-a8cd4935c4bf.jpg)

**Comment by Jimmi08** [comment]
@Moc @chimcen  it because this:
![image](https://cloud.githubusercontent.com/assets/5429548/19939294/99eb396c-a128-11e6-8494-809165c6362d.png)

so this could be changed in theme css somehow. You could try in your style.css

```
img.e-emoticon {
    width: initial;
}

```

**Comment by chimcen** [comment]
[http://i273.photobucket.com/albums/jj222/Nonnie87/Smiley/210.gif](url)

**Comment by Moc** [comment]
Not sure why I reopened this. Closing. Let me know if it needs to be reopened.
