### ISSUE TITLE
problem with admin lang switcher on localhost

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1911]
I can't switch languages on localhost. I don't use subdomains
![image](https://cloud.githubusercontent.com/assets/5429548/19216027/8704b2f2-8dae-11e6-8394-7fd3ff7e7eed.png)

but this code is executed:
![image](https://cloud.githubusercontent.com/assets/5429548/19216035/ad99c9fc-8dae-11e6-89dd-d0d3dc3a6ce2.png)
![image](https://cloud.githubusercontent.com/assets/5429548/19216039/b907f96c-8dae-11e6-8bb6-4c4b82db27f1.png)

and result is that on localhost language switcher didn't work.

PHP 5.5

**Comment by tgtje** [comment]
Confirmed on php 5.x and php 7.x (local) . The alternate method is to either use lang menu on front or when in admin , change lang, save and click logo. Admin will refresh and display language chosen.

**Comment by CaMer0n** [comment]
@Jimmi08 I often wish I could copy the code you paste, but when you use an image, it makes it very difficult. Please just paste the code and wrap it in backticks. " ` " . I'm looking into the issue now.

**Comment by Jimmi08** [comment]
@CaMerOn I am sorry I will do it at future.  Thanks

**Comment by tgtje** [comment]
Commit working for me ( php 5 x and php 7 x) 👍

**Comment by Jimmi08** [comment]
Confirm that it works (php 5) Thank you.

**Comment by CaMer0n** [comment]
Thank you both! :+1:
