### ISSUE TITLE
Upgrading issue

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1912]
Suppose total backup of older v1 installation, zipped and stored (incl. dbase)running on php 5.x server.

In use ( move to) : a new sever running on php 7.x
Unzip and upload all (manually imported dbase).

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in ...handlers\mysql_class.php on line 144. ( existing file)
Result > no go. ( no checks can be done).

If overwriting on THIS stage takes place (aka upgrading to newest);  functionable (upgrade works with common reports).
Bug, enhancement feature or code change ? (how to address this to users).

**Comment by Moc** [comment]
I don't understand this fully. 

> Suppose total backup of older v1 installation, zipped and stored (incl. dbase)running on php 5.x server.

> In use ( move to) : a new sever running on php 7.x

So, does this mean the following?
- a v1 backup which is placed on a PHP 5.x server, then upgradded to v2 
- the v2 installation is then moved to a new server which runs PHP 7.x. 
- The MySQL error appears? 

But then I am confused by this:

> if overwriting on THIS stage takes place (aka upgrading to newest); functionable (upgrade works with common reports).

What do you mean 'this stage'. And I thought the installation was already updated? 

OR: do you mean a v1 installation which works on PHP 5.x is transferred to PHP 7.x, then throws an error, and starts working again after upgrade to v2? This would make sense as PHP v1.x is not compatible with PHP 7.

**Comment by tgtje** [comment]
A working v1 version on a php 5 server is moved to a new php 7 server.
After finishing uploading and adding dbase, one would like to run the 
site (eg test).

At this point the error occurs.. (site does not run).

Now when at that point in time i do upgrade (by ftp) the system files, 
the old files are overwritten.
 From there on all can be handled.

So issue lies is the older v1 handler file/mysql_class.php

partial line 142 up to 159
     else
         {

*if ( ! $this->mySQLaccess = @mysql_connect($this->mySQLserver, 
$this->mySQLuser, $this->mySQLpassword))*
             {
                 return 'e1';
             }
             else
             {
                 if ( ! @mysql_select_db($this->mySQLdefaultdb, 
$this->mySQLaccess))
                 {
                     return 'e2';
                 }
                 else
                 {
                     $this->dbError('dbConnect/SelectDB');
                 }
             }
         }

$Id: mysql_class.php rev  12047

The bold is the line that is reported. So it is the connection made 
(which will run into deprecated functionability).
Upgrade fixes it, but the user might not know what to do when he does 
the top part of post (zip,unzip upload,test)



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by Moc** [comment]
Right, this makes sense since e107 v1 simply does not support PHP 7. The issue here is not the upgrade process but rather the attempt to run v1 on PHP 7. 

An upgrade from v1 to v2 should only be attempted if the v1 installation is running correctly. If a user tries to update from a broken v1 installation, there is no telling what the result is.

**Comment by tgtje** [comment]
Correct, but (user point) i only have the backup (due to many possible causes). I'm stuck.. (yes Wamp or Xamp as alternative to fix things). But how to warn?. Procedure step (textual on main site ? Warning or  likely to get issue when.....  (so not the files but the knowledge)

**Comment by Moc** [comment]
The thing is, there is no way to put up a warning if a user tries to restore a v1 backup on a PHP 7 server, since it will immediately call for a PHP fatal error. Leaving this open for a while to discuss.

**Comment by CaMer0n** [comment]
There's nothing we can do here. (v1.x release is not an option). The procedure for a v1.x upgrade to PHP7 means the site will initially break at least up until the time that all the v1.x files are overwritten with v2.x files.

**Comment by Moc** [comment]
@CaMer0n Maybe a note on e107.org saying that v1 does not support PHP 7?

**Comment by tgtje** [comment]
As mentioned.. a message (somewhat eyecatching) would be sufficient i guess. Where some explanation of breakage untill steps taken..

**Comment by CaMer0n** [comment]
Got it, added it earlier today. http://e107.org/get-started

**Comment by Moc** [comment]
Perfect. Case closed :)

**Comment by tgtje** [comment]
👍
