### ISSUE TITLE
problem with standalone login page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1913]
if USER is already logged in, they are not redirected to index.php (or somewhere) as it was in version 1.

this is result on login.php after log in

![image](https://cloud.githubusercontent.com/assets/5429548/19234187/48d050a8-8eea-11e6-9339-2b2a7516d81b.png)

**Comment by lonalore** [comment]
It works as designed. This is not a bug. See end of this line: https://github.com/e107inc/e107/blob/master/login.php#L23

`!getperms('0')` allows main admin to see login page as a logged in user. Simple users will be redirected to the frontpage.

**Comment by Jimmi08** [comment]
Oh, thanks. I saw that, but it was too complicated "if" for my liking. Thanks for explanation.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/2513
