### ISSUE TITLE
not able install new e107 with php 5.5

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1917]
Sorry for this again.  I use port with connect to database:
`$mySQLserver    = 'mariadb55.websupport.sk:3310';`

This change 
https://github.com/e107inc/e107/commit/2420c979f8fb7b168baec791d3e230b45c0c6924
abled using e107 with php 7, but caused not able use it without pdo ($this->mySQLserver is not correct without pdo)

I will post fix that helped.

**Comment by Moc** [comment]
PR was merged: https://github.com/e107inc/e107/pull/1918

Assuming it's fixed. Closing.
