### ISSUE TITLE
Media manager blank page

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1921]
I upgrade the system from latest Github files. After this blank page on the media manager page (e107_admin/image.php).

**Comment by tgtje** [comment]
Just synced, can not replicate. All is there.

**Comment by fizi** [comment]
the all settings on the admin area works, only media manager don't work, only on this site blank page. All other admin pages works normally. This is after latest upgrade.

**Comment by fizi** [comment]
The media manager works. Thanks!
