### ISSUE TITLE
[Question] How to add file uploader for members

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1932]
Is there any form function or shortcode to add a multifile uploader?

Also, I tried using the filepicker() method, but it doesnt allows the upload to non admin accounts.
Maybe am I missing some param/config...?

Thanks,
- Nes

**Comment by Moc** [comment]
Hi, 

Some questions. 
- Do you use this code on the frontend or backend (admin area?). 

If its the admin area then you can use the Admin UI (see plugin builder) and use `type='files'` 
If it's for the frontend then I am not completely sure why the filepicker() method doesn't work. 

- Do you get any error message as a non-admin user?

**Comment by nesjett** [comment]
I dont get any error, it works, uploads the file, but when it reloads the modal, the file just uploaded its not there nor in the file sistem.
At first I noticed some kind of bug in the latest stable version, and It was that avatar uploading is not working. At first I thought that it could happen due to file permissions, but now Im wondering if that is related with the filepicker() too.

PD: As a small note, the profile link to update the avatar picture is not working as espected, it has a bad redirect.

I´m using latest stable version, not github one, Ill try to update and see if its solved.

**Comment by Moc** [comment]
> I´m using latest stable version, not github one, Ill try to update and see if its solved.

That should definitely solve a lot of issues. Hopefully also the one you are experiencing :)

**Comment by nesjett** [comment]
Well, updating the cms to the git version solved the problem about not to be able to upload avatars, but still cant upload files trought the filepicker() if you are not admin (on frontend)

Issue #1933 persists too.

**Comment by Moc** [comment]
Can you share the (extract of) code you are using to test this? Then I can try to replicate and debug it. 
You can post the code in a Gist for example: gist.github.com

**Comment by Moc** [comment]
Labelled as bug, this needs to be looked into. 

Test code:

```php
<?php
require_once("class2.php");
require_once(HEADERF);

$sql = e107::getDb();
$ns = e107::getRender();
$frm = e107::getForm();
$text = '';

if(isset($_POST['formname']))
{   
	print_a($_POST);
    $ns->tablerender("Test form", "Submitted!");
}
else
{
   $text .= $frm->open('formname', 'post', e_REQUEST_URI);
   $text .= $frm->filepicker('test', '');
   $text .= $frm->button('formname', LAN_SUBMIT);
   $text .= $frm->close();
   
   $ns->tablerender("Test form", $text);
}

require_once(FOOTERF);
exit;
``` 

- When logged is as admin user: everything is fine. File uploads properly. 
- When logged in as regular user without admin permissions:  modal opens but requires to login into admin area.

**Comment by CaMer0n** [comment]
Please see http://www.w3schools.com/tags/att_input_multiple.asp and `e107::getFile()->getUploaded();`
