### ISSUE TITLE
Forgot password not working in BS3 theme

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1937]
E107 updated from v1.4 to v2.x.

Forgot password form rendered with Bootstrap3 theme:
![bs3_forgot](https://cloud.githubusercontent.com/assets/17130530/19449525/cbb67674-949d-11e6-84b3-80739e3a656a.jpg)

Forgot password form rendered with my v1.4 theme:
![spt_forgot](https://cloud.githubusercontent.com/assets/17130530/19449533/dc28e942-949d-11e6-881b-d919fa7a0553.jpg)

Please also note the LAN_156 rendered button (i am using portuguese language files...)

Any ideias why this issue?

**Comment by Moc** [comment]
@rica-carv Please check if the issue is resolved after following the advice of @MikeyGMT in #1938 1938

**Comment by rica-carv** [comment]
@Moc Yes, this issue is also solved inside the Bootstrap3 theme with @MikeyGMT tip on issue #1938
