### ISSUE TITLE
[Suggestion] How to improve documentation

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1939]
I see that documentation is probably the worse lack of e107. as developer I saw a lot of very interesting and util methods, classes, etc but because of the lack on the documentation, I didnt knew about them when I needed it.

I know that for some methods you need to add extra documentation, like selectize, etc, but would be nice to have atleast  a developer reference of those functionalities.
Well, my suggestion is why you dont use some software that converts the comments place over function declarations into a complete html page with links, search and so on.

PD: Somethink like this documentation, that, even if they have not defined a detailed definition of what it does, atleast you know its name, params and returns: https://docs.unrealengine.com/latest/INT/BlueprintAPI/Game/SpawnActorfromClass/

Grts,
- Nes

**Comment by Moc** [comment]
Thanks for the suggestions. 

Software that could be used is phpDocs: https://www.phpdoc.org

In the code, a lot of methods have been documented using this style of documenting, but definitely not everything. The current developer reference manual already contains bits and pieces, but it's a work in progress. For example: http://e107.org/developer-manual/classes-and-methods
