### ISSUE TITLE
Permissions check error

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1942]
Updated site with latest github, when checking permissions on AU area, it gives me this error:
![perm](https://cloud.githubusercontent.com/assets/17130530/19469945/754eec58-9515-11e6-9534-b36186b5d445.jpg)

Any help aprreciated, or in the meanwhile, which are the correct CHMOD permissions i should set e107 files? Is there any guide for it around?

**Comment by Moc** [comment]
This really all depends on your server configuration. When properly configured, all files should be set to 644 and all folders to 755. This may vary depending on server configuration however. 

IIRC, the e107_media and e107_system folder needs to be writable by the server. Will see if I can some solid information on this.

**Comment by Moc** [comment]
@rica-carv Is this issue still relevant?
