### ISSUE TITLE
[Feature request] - Ability to disable/alter meta tags generated by core / core plugins.

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1946]
I have been working on my [Metatag](https://github.com/lonalore/metatag) project for a while, and I would like to generate all kind of meta tags with my plugin as soon as I finish it. But for achieving this, I need an option to disable all meta tags generated by core. How can I achive this? Thanks!

**Comment by lonalore** [comment]
Another suggestion: provide a way to alter meta tag array [before rendering](https://github.com/e107inc/e107/blob/master/e107_core/templates/header_default.php#L164).

**Comment by lonalore** [comment]
@CaMer0n can you review my commit? I think it's a pretty good solution for altering meta tags before rendering. And `e107::getAddonConfigAlter()` can be also used for altering `config()` method.

**Comment by CaMer0n** [comment]
@lonalore It's good, but I'm not a fan of meta_alter()..  I believe it would be more consistent with other core methods to find a way to use an `$override` parameter with e107::meta()

**Comment by lonalore** [comment]
Hmm. But I don't want to override e107::meta() because it works fine. I just want to alter the meta tag array before rendering. Anyway I'll look into how this `$override` paramter really works.

**Comment by lonalore** [comment]
Well, I have no idea how we could use `$override` for altering [$_meta](https://github.com/e107inc/e107/blob/master/e107_handlers/application.php#L3693) before rendering. :(

**Comment by CaMer0n** [comment]
@lonalore I understand better what you want. I have added a few methods to help.

**Comment by CaMer0n** [comment]
Example e_header.php content: 

        $front = eFront::instance();
		$response = $front->getResponse();
		$data = $response->getMeta();

		foreach($data as $m)
		{
			if($m['name'] == 'viewport')
			{
				$response->setMeta('viewport', 'replaced');
			}

		}

**Comment by lonalore** [comment]
Thank you @CaMer0n ! But with this I would be able to alter meta tags already added by core/plugins. But I cannot alter e.g the meta tags of social plugin, because its e_header.php is called after my e_header.php. I hope you understand it! :D

So, I need a solution I can use right before rendering: [here](https://github.com/e107inc/e107/blob/master/e107_handlers/application.php#L4056) 

For example an event triggering?
```php
	/**
	 * Render meta tags, registered via addMeta() method
	 * @return string
	 */
	public function renderMeta()
	{
		$attrData = '';
		
		$event = e107::getEvent();
		$event->trigger('render_meta_pre');

		foreach ($this->_meta as $attr) 
		{
			$attrData .= '<meta';
			foreach ($attr as $p => $v) 
			{
				$attrData .= ' '.preg_replace('/[^\w\-]/', '', $p).'="'.str_replace(array('"', '<'), '', $v).'"';
			}
			$attrData .= ' />'."\n";
		}
		return $attrData;
	}

```

Then I could use your code in my registered event callback:
```php
$event = e107::getEvent();
$event->register('render_meta_pre', 'my_callback');

function my_callback()
{
    $front = eFront::instance();
    $response = $front->getResponse();
    $data = $response->getMeta();

    foreach($data as $m)
    {
        if($m['name'] == 'viewport')
        {
            $response->setMeta('viewport', 'replaced');
        }

    }
}
```

**Comment by CaMer0n** [comment]
@lonalore It did cross my mind after I committed the code about the 'order of things' issue.
I like your solution. Commit coming shortly.

**Comment by lonalore** [comment]
Thank you very much! It works like a charm! :)

**Comment by Moc** [comment]
Re-opening for documentation reminder
