### ISSUE TITLE
[Support request] - How to alter action buttons on Admin UI?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1947]
How can I remove "create another" option from this list:
![kepernyokep_2016-10-19_16-42-30](https://cloud.githubusercontent.com/assets/6043821/19523569/36da9826-961b-11e6-9058-57d7f25106c7.png)

Here is [my Admin UI implementation](https://github.com/lonalore/metatag/blob/master/admin_config.php).

**Comment by tgtje** [comment]
You might probably already know it, but it is set in form_handler as submit opt..  see line 5611 (create)

**Comment by lonalore** [comment]
I need to override these options:
https://github.com/e107inc/e107/blob/master/e107_handlers/admin_ui.php#L5792-L5794

**Comment by lonalore** [comment]
In my case, I should change `'after_submit_options' => true,` to `false`:
![kepernyokep_2016-10-20_08-44-52](https://cloud.githubusercontent.com/assets/6043821/19548974/c8549730-96a1-11e6-99ad-9e8b56c5c3a0.png)

**Comment by lonalore** [comment]
@CaMer0n can I create a pull-request with this commit?

**Comment by CaMer0n** [comment]
@lonalore looks great! "list', 'edit', 'create' :+1:

**Comment by lonalore** [comment]
Yes, the default value is true, which results 'list', 'create', 'edit'. Thank you!
