### ISSUE TITLE
Configuration of the alt_auth plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1948]
I have two e107 sites (both v2 version).  I want to use alt auth plugin for users that are already registered on older site.  Is this correct setting?
![image](https://cloud.githubusercontent.com/assets/5429548/19533856/cb0cf1ee-9641-11e6-93c5-3e5ef792c2d5.png)

Is this mean that first is checked actual database, then older one?   I wasn't able to set it in reversed order - at first check older site (other e107 db) then new one (e107).  

Thanks

**Comment by Jimmi08** [comment]
Ok, so nothing again with alt auth plugin.
- connection to server works
- finding username works
But I wasn't able to get password checking to works. (error: Authentication failed - bad password
Password incorrect)
I think it's because changing in password encoding in core (missing PHP default in list). But it didn't work for salted too.

**Comment by Jimmi08** [comment]
@Moc maybe I should change title - there is bug too, password checking doesn't work

**Comment by Moc** [comment]
@Jimmi08 Done :) It's on my list to test but I need some more time. Maybe this weekend.

**Comment by Jimmi08** [comment]
@Moc Thank you! I understand it could be difficult with 2 different systems, but it should work with 2 the same version of e107 at least.

**Comment by CaMer0n** [comment]
Also, it won't work with PHP7 in it's current state.

**Comment by CaMer0n** [comment]
@Jimmi08 Please try with e107 salted again. I found an issue in the code which should correct it.

**Comment by Jimmi08** [comment]
@CaMer0n 
I tried. Not know if only with 2 e107 dbs or general, but I tried both.
I wasn't able to connect server (e_PDO set true). I tried Test functionality in admin area.

> 
> Authentication failed - could not connect to DB / service provider
> Cannot connect to remote DB; PDOException message: SQLSTATE[HY000] [2005] Unknown MySQL server host 'mariadb55.websupport.sk:3310' (2)

The instructions for PDO connect on my server are:
```
Example of use in PHP scripts with PDO connection
parameters are in order ("server+port/socket;database_name", "login", "password") 
Recommended connection (works everywhere):
$connection = new PDO("mysql:host=mariadb55.websupport.sk;port=3310;dbname=database_name", "login", "here_insert_password");

```
It could be related with this: https://github.com/e107inc/e107/issues/794  
After rewritting it worked before (before my moving to other server - I am back now - and changes in password managing).

**Comment by Moc** [comment]
@Jimmi08 What's the status on this one?

**Comment by Jimmi08** [comment]
Available ALT options:
- generated from files _auth.php in plugin folder (otherdb, radius, ldap, importdb, e107db)
- none (no authentification is used), it can't be used for primary source
- e107 - actual e107 installation.

e107 is added to primary sources list manually. 
No idea, why can't be used as a secondary source.  e107db is external/other e107 database, 

There is parameter for this in alt_auth_get_authlist(), but e107 is added manually only to primary source. 
 
https://github.com/e107inc/e107/pull/4002/commits/9889ad5e993231387b0f0a6f1ec06ac65ff6ec30

**Comment by Jimmi08** [comment]
Duplicate:
https://github.com/e107inc/e107/issues/3983

It's the same problem. No idea what plans were for this.   

Closing this one.
