### ISSUE TITLE
Errors @ Forum and Gallery directing

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#1950]
Hi,

i've installed e107v2.1.1 (tried also after then the last beta from github) on my webserver and activated the plugins "forum" and "gallery" (dafault plugins from e107).

When i klick on them i'll be rooted to a Server Error (adress not given).

**# Forum:**
Tap on Forum in menu -> seems ok:
![forum_bug1](https://cloud.githubusercontent.com/assets/22658487/19576336/eb9e8144-9712-11e6-8d95-eb06a7512eb6.JPG)

After tapping to the subforum -> not ok:
![forum_bug2](https://cloud.githubusercontent.com/assets/22658487/19576358/00b55ae4-9713-11e6-96d9-2d8cb6aa3e19.JPG)

**# Gallery:**
Tap on Gallery in menu -> not ok:
![gallery](https://cloud.githubusercontent.com/assets/22658487/19576383/121f7382-9713-11e6-9765-4e13691d83d2.JPG)

When i test the same on a local installation (xampp, same php and mysql version), it will work with same url's...

**Comment by pierre0042** [comment]
I have the same problem (with Forum, I don't use Gallery)

**Comment by chimcen** [comment]
If i'm enter the old-style link (not SEF friendly) directly - e.g. xxx.xxx.de/e107_plugins/forum/forum_viewforum.php?id=12 the subforum will be displayed correctly...

Can you fix this? Or is there a way to completely switch of the "SEF"-thin in e107v2?

**Comment by Moc** [comment]
This is probably due to not having configured `mod_rewrite` correctly on the server. 

The internal server error produces more information on the error in a so called log file: the Apache Error log. Please consult with your webhosting provider to access this log (you can do this through control panels such as cPanel and DirectAdmin normally). Once we have that info, it's easier to say what's wrong.

**Comment by chimcen** [comment]
> Or is there a way to completely switch of the "SEF"-thin in e107v2?
Yes. In Admin Area > Settings > URL Configuration

But there are not all Plugins listed. Forum e.g. isn't listed... i want to get for all links the old style from e107v1.0.4 back...without SEF feature... :(

Because the mod_rewrite - it seems this is a extra appache module from my hoster - and must be activated throught .htaccess file with the string "RewriteEngine On" ... but it doesn't work anyway...
Damn...i'm a noob...sry... :(

**Comment by Moc** [comment]
> But there are not all Plugins listed. Forum e.g. isn't listed... i want to get for all links the old style from e107v1.0.4 back...without SEF feature... :(

Hmm, you are right. Let me look into this for you, I'll get back to you. 

Do you know how to access your website through FTP? If yes, see if there is a file called `.haccess`. 
Also, please try to find the Apache error log. This will provide us with more information so I can help you out more effectively, as it will tell us more about the exact problem.

**Comment by tgtje** [comment]
Just adding  in case overseen.. 
htaccess file
### Uncomment it in case your server isn't able to rewrite proper 
	#RewriteBase /

your host: https://www.df.eu/int/support/df-faq/webhosting/weitere-technische-faq/htaccess/mod-rewrite/

**Comment by chimcen** [comment]
Thx @tgtje ... changed this befor 2hours... now it works.
This was the problem.
I had to set the RewriteBase Folder manually - my hoster seems to be not able to detect it automaticly...

@pierre0042 
Try this out - its evtl. also your problem...

**Comment by pierre0042** [comment]
I tried to change the rewrite parameters, but it didn't fix my problem, and created others... I will open a new issue
