### ISSUE TITLE
Forum plugin : error 500 on main page

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1953]
Hello,

Since last update, I cannot access /e107_plugins/forum/forum.php
It gives me a HTTP error 500...

What is strange is that accessing the topics are still working well,
for example /e107_plugins/forum/forum_viewtopic.php?id=12345 is working...

Any idea?

**Comment by lonalore** [comment]
Please check your error.log for more details.

**Comment by pierre0042** [comment]
I did, there isn't more details in it unfortunately...
Actually there is nothing in it.
I only see the error 500 in the access log

**Comment by lonalore** [comment]
Okay, so the request does not reach the PHP. What do you use? Apache or Nginx?

**Comment by pierre0042** [comment]
It's Apache

**Comment by lonalore** [comment]
Some debugging tips:
1, Make sure your .htaccess file exists. If you have not renamed: rename e107.htaccees to .htaccess
2, If you modified your .htaccess, revert all of your changes. If it contains some uninterpretable garbage you will get an Error 500.
3, Check your virtual host config file, make sure AllowOverride is not set to "None". It should be "All".
4, Make sure mod_rewrite is enabled on your server

**Comment by pierre0042** [comment]
For 1) & 2) : I replaced the .htaccess with e107.htaccess
I doesn't change the problem but breaks the links in the forum...

For 3) & 4) this is a shared hosting so I don't have direct access to the vhost files...

**Comment by pierre0042** [comment]
ok so it looks like my forum folder had some local modifications.
deleting the folder and uploading a fresh one solved the problem.
(thanks to Cameron for help)
