### ISSUE TITLE
[Question] Can a plugin override core functions?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1957]
For instance, is it possible to alter the function [toGlyph](https://github.com/e107inc/e107/blob/c9bf31cf268a0bf945038b9e5606f08fed5c2f46/e107_handlers/e_parse_class.php#L3475) at a plugin basis?
Let's say i want to use another icon fonts besides Glyphicons or Fontawesome globally, even with another tag output instead the only two alowed (span & i).
`e107::getParser()->toGlyph('fa-user-times','fw=1')`
Therefore i would need to redefine this core function at plugin (or module) basis.

Is it possible to do it?

**Comment by lonalore** [comment]
I think it is possible. Check e_parse.php addon files.

**Comment by lonalore** [comment]
No... I was wrong. It can be used only for extending [toHtml() functionality](https://github.com/e107inc/e107/blob/master/e107_handlers/e_parse_class.php#L1913-L1928).

**Comment by rica-carv** [comment]
@lonalore Maybe i've expressed myself wrong. I'm thinking of globally override a core function, to replace the original sitewide, not only in the plugin....

**Comment by Moc** [comment]
In general no, but there are many things implemented which allow for a huge amount of customization. It would be better to specify exactly what you'd like to change so we can give more specific advice. 

As for changing the toGlyph method, I don't think this is possible. What kind of icons do you have in mind? In general, such type of code (icons) use either the `<span>` or `<i>` tag.

**Comment by rica-carv** [comment]
@Moc My ideia is to use the `<svg>` tag....
And yes, this question is somehow directly related to #1958...
But it can also be of some use for somebody to change any core class function....

**Comment by Moc** [comment]
Alright, then my answer above still stands :) 

Regarding the SVG icons, we'll continue that discussion in the other issue. 
Closing this one.

**Comment by rica-carv** [comment]
Maybe another workaround for the toGlyph would be to template the toGlyph hardcoded html....
Just a athought....

**Comment by Moc** [comment]
Put that in the other issue haha 👍
