### ISSUE TITLE
[Question] SVG icons support, can it be possible?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1958]
Since i'm not great fan of monochromatic Bootstrap icons (Glyph or FA), i've been investigating, and read that [SVG might be the direction to go regarding icons](https://css-tricks.com/icon-fonts-vs-svg/).

Can this be supported globally (as is Glyphicons and Fontawesome) in e107?

**Comment by LaocheXe** [comment]
I had to make my own icons for my Voice eXe plugin - https://github.com/LaocheXe/Voice-eXeSystem/tree/master/voice/fonts

and I have a SVG file of the icons - I used a website that converts images into font icons, but cant remember the site off the top of my head. I would have to say yes to SCG icons support, all I had to do was add the css - https://github.com/LaocheXe/Voice-eXeSystem/blob/master/voice/voice.css

**Comment by rica-carv** [comment]
@LaocheXe Thanks, but in your case, you only ca use them in your plugin, outside of it we all are stuck to Bootstrap font icons, with it's drawbacks....

My question is goes a little bit further, since i want to use SVG icons site wide, ie, even inside the core icons....

A site with its icons based on boostrap and a plugin with SVG icons would be a little bit ankward and poorly designed one, don't you think?

**Comment by tgtje** [comment]
take a look at https://useiconic.com/open @rica-carv  or G.. for grunticon (not going into the pros and contras)

**Comment by rica-carv** [comment]
@tgtje That looks the way to go, but it seems i need to give a further look to it to find out how it works...
It seems it can have svg to replace the default bootstrap icons generated with i or span tags....
Until now i know that the only way to include svg in html was with the svg tag....

@LaocheXe I knew your approach, i'm using it on my [current theme development style sheet](https://github.com/rica-carv/e107_theme-selospt_v2/blob/master/fam-icons.css). Right now i'm not using svg, but plain & simple png.
But since png are "evil" in tablets and mobile devices, and also are not "bootstrap friendly", i decided the svg approach....

**Comment by Moc** [comment]
@rica-carv Is still issue still relevant?
