### ISSUE TITLE
[Question] How add to media manager plugin categories?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1959]
Is it possible to add to media manager a specific plugin categories?
For instance, myplugin_icons, myplugin_images?

If so, how can it be donne?
Even now, via the admin ui we can't add more categories to media manager....

**Comment by LaocheXe** [comment]
Yes, in your plugin.xml file > add the followingh
`<mediaCategories>
<category type="image" sef="myplugin_icons" perm="everyone" image='{e_PLUGIN}myplugin/images/image_icon.png'>Myplugin Icons</category>
<category type="image" sef="myplugin_images" perm="everyone" image='{e_PLUGIN}myplugin/images/image.png'>Myplugin Images</category>
</mediaCategories>`

An example can be found here: https://github.com/LaocheXe/Unit-eXeSystem/blob/master/unitexe/plugin.xml

**Comment by rica-carv** [comment]
Thanks.
But, err, might be a dumb question, but why categories descriptions have images associated with?
I don't remember see images for categories descriptions....

**Comment by LaocheXe** [comment]
well I copy that from one of the already made plugins, check some other plugins.xml

**Comment by Moc** [comment]
They may not be used in the main areas now, but perhaps for future options :)

**Comment by CaMer0n** [comment]
@rica-carv Gallery uses Media-Category Images and SEF Urls. ;-)

**Comment by rica-carv** [comment]
@LaocheXe Somehow, this is not working for me. Latest github files, and trying to create media categories in plugin.xml:
`  <mediaCategories>
    <category type="image" sef="links-page-icons" perm="everyone">Links Page Icons</category>
    <category type="image" sef="links-page-images" perm="everyone">Links Page Images</category>
  </mediaCategories>
`

Got only one media category under media manager:
`links_page 	links_page_image 	Links Page Icons 	links-page-icons 		Everyone (public) `

Anybody can please tell me why only one categoy is registered?

**Comment by CaMer0n** [comment]
@rica-carv Please update from Github and try to install (or use the "plugin repair" button) again.

**Comment by rica-carv** [comment]
@CaMer0n Now it seems to work, but with this lines inside plugin.xml:
```
    <category type="image" sef="links-page-icons" perm="everyone" image='{e_PLUGIN}links_page/images/linkspage_icons.png'>Links Page Icons</category>
    <category type="image" sef="links-page-images" perm="everyone" image='{e_PLUGIN}links_page/images/linkspage_images.png'>Links Page Images</category>
```
i got this message after plugin sucessfully installed:
```
Settings successfully saved.
Adding Link: Links with url [links_page/links] and perm everyone
Adding Media Category: links_page_image
Adding Media Category: links_page_image_2
```

Anyway, under media manager i got the two correct categories: Links Page Icons & Links Page Images....

**Comment by CaMer0n** [comment]
@rica-carv Correct. Use writeParms('media'=>'links_page_image'); etc.

**Comment by rica-carv** [comment]
@CaMer0n Is there anyway we can choose in the plugin.xml file the media category name that will be added when plugin is setup?
It seems that right now it's a name choosen by the system, and it's kind of ankwards, since a plugin developer will never knows which name will be choosen in each e107, to specify it at the admin.php file inside the plugin...

**Comment by CaMer0n** [comment]
It's to avoid conflicts. The developer can calculate it.  It's the plugindir + _type + (+ _x if more than one of this type)

**Comment by CaMer0n** [comment]
numbers correspond with the order in the plugin.xml

**Comment by rica-carv** [comment]
@CaMer0n Well, it seems the writeParms is not fun of me....
I've got right the line in admin_config.php as this:
`'link_category_icon' =>   array ( 'title' => LCLAN_CAT_22, 'type' => 'icon', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => '', 'writeParms' => array('media'=>'links_page_image'), 'class' => 'left', 'thclass' => 'left',  ),`

But the modal popup media box just keeps showing me icons....

What i'm doing wrong?

**Comment by Moc** [comment]
@rica-carv Make sure to keep clearing the caches (e107 and browser)

**Comment by rica-carv** [comment]
@Moc I'm on localhost, with caches disabled. Anyway i cleaned both, issue still persists....

**Comment by rica-carv** [comment]
Just a few more two cents on this issue.
When using image as type, this works:
`		  'link_category_icon' =>   array ( 'title' => LCLAN_CAT_22, 'type' => 'image', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => '', 'writeParms' => 'media=featurebox', 'class' => 'left', 'thclass' => 'left',  ),`

But when using icon as type, it doesn't!
`		  'link_category_icon' =>   array ( 'title' => LCLAN_CAT_22, 'type' => 'icon', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => '', 'writeParms' => 'media=featurebox', 'class' => 'left', 'thclass' => 'left',  ),`

**Comment by CaMer0n** [comment]
Custom MediaCategories only supports images and files, not icons. If you want to use it you'll have to set the type to 'image' .

**Comment by rica-carv** [comment]
@CaMer0n I've got another workaround, when still using icon as type: Just add images in media manager to icons_xx category, et voilá....
It's kind of "stupid", but since media manager allows a image to have multiple categories, it kind of works...

On a side note, why does the icon type can't be allowed as custom media category type? Legacy?

**Comment by Moc** [comment]
@rica-carv Is still issue still relevant?
