### ISSUE TITLE
LAN'S constant name in localhost

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1961]
I've got a real strange issue here.
My live site is all correct regarding LAN displays, but when i make a complete mirror copy of it to my localhost development environment, inclunding mirror the database, it displays at the admin UI the constant names insted the correct translation...

Anyone experienced this same issue?

Further more, the hyperlink in the admin area for changing the language, also is different in localhost from live server. For instance, to select english language, i have:
- In localhost: `http://en./selosptv2/e107_admin/admin.php`
- In live server: `http://www.site.address/e107_admin/admin.php?elan=en`

Why these differences if all the files and database are exactly equal (except file e107_config.php, of course...)?

**Comment by CaMer0n** [comment]
Multilanguage subdomain is enabled on localhost.

**Comment by Jimmi08** [comment]
It was probably solved  here:  https://github.com/e107inc/e107/issues/1911

**Comment by rica-carv** [comment]
@CaMer0n Sorry, but i did exactly a mirror copy of the database (where prefs are saved), so if it was enabled on localhost, it has to be enabled also on live server.
So why the different behaviour in both environments, if files and database are exactly equal?

**Comment by CaMer0n** [comment]
Does your localhost have a domain name associated with it? (ie. in your hosts file)

**Comment by rica-carv** [comment]
@CaMer0n Err, no... I'm currently thinking it might be the missing .htaccess file (wich is the only missing file from the live site), so i'm going to test this....

**Comment by CaMer0n** [comment]
Okay thanks @rica-carv . Without a domain name, you can't use the subdomain multilanguage feature locally.
