### ISSUE TITLE
Using quick add user

### ISSUE THREAD

**Issue by Worldwide7477** [e107inc/e107#1963]
Hi guys seems i have a small bug with quick add when i use it I always receive this error ---> Unauthorized access!

Any help on this would be great.

**Comment by MikeyGMT** [comment]
Hi @Worldwide7477 Which version are you using and does e107 Debug tell you anything, also check on your file system for files named error_log in the root or admin folder.

**Comment by Worldwide7477** [comment]
Hi MikeyGMT i'm using the very latest from github error log shows 0 so don't know if its grabbing the errors or not as for e107 debug using noticed a few showed up and i did see i did not have a tmp folder above site folder when i added that I was able to delete fail logins and proceed with quick add user...---> so big thanks for the help in solving this all fixed now.

**Comment by Moc** [comment]
For future reference: this is probably related to an incorrect setting of the php session.save path.
