### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1964]
I've been having some issues with my site so wanted to try deleting the preferences and copying across from a dummy site I have set up. However, I appear to have caused myself an issue by deleting some of the "admin..." (via the admin site) preferences and now the admin site won't load. It loops round until my browser errors and says "...redirected you too many times."

So how can I restore my preferences (which I back up before messing around with things), without access to the admin site? Are they stored in a db table or in a file?

Thanks

**Comment by tgtje** [comment]
No issue.. a post for e107help.org ;-)
Normally all in db core  table

**Comment by pricey1981** [comment]
Sorry, I appreciate that but I don't find e107help that useful for this type of question. Anyway, I tracked down a core.php file in the e107_system cache. I was able to restore by editing that as making changes directly to the e107_core db table had no effect

**Comment by CaMer0n** [comment]
@pricey1981 btw. you can export your site-preferences to a file under Tools > Database which can be imported to another site.
