### ISSUE TITLE
Bug (e107v2 2.1.1 & >) Page without Title isn't shown in Pages-List

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#1967]
Hi,

i've created a own page in menu/pages-panel and didn't give the page a name. Its possible to do this and the page will be created, but it won't be shown in pages-list -panel. The own page can only be reached to be edit by inserting the page id (hapefully you remember they)...

**Comment by CaMer0n** [comment]
The latest version is v2.1.2 - please update and let us know if the problem persists. 
 http://e107.org/get-started

**Comment by chimcen** [comment]
Sry for the delay. Tried also wit v2.1.2 - its the same...

**Comment by CaMer0n** [comment]
If the page doesn't have a title, then it is assumed it is not a page, but a menu. The reverse is also true.

**Comment by chimcen** [comment]
This means it should be seen (if it is without any title) menu list? But it isn't also there - it wont be displayed in page or menu list.

**Comment by CaMer0n** [comment]
Does it have a menu-title? Are you able to view the table via phpmyadmin?

**Comment by chimcen** [comment]
No. If it has a title-name it would be displayd in pages-list. If i remove the title-name (becaus i don't want to display a title on the frontend for this page), the page will disappear from pages-list (and also not be shown in menu-list).
After then, the page is usable and correct in db (visible also in phpmyadmin) and if i remember the page id i can also reach the edit screen for that page...

**Comment by chimcen** [comment]
Works as it should - page without title-name remains in pages-list visible. Thank you :)
