### ISSUE TITLE
[question] how to use e107::css() without e_header.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1969]
I have plugin that have just menu . I don't want to use e_header.php because this way css files are loaded in all site, not only on page with this menu. 
Plugin is done similar way as vstore - menu is calling file with class and before declaring class there is e107::css() used. 
But I noticed that my css file  is put in the footer and not between <head> tags (and before </html> tag, so it's totally wrong)
This doesn't happen with vstore because it calls this file in e_shortcode.php or in e_header.php (after removing it from these files, it happens with vstore too - plugin css is put in footer) .

```
<!-- ======= [JSManager] FOOTER: Remaining CSS ======= -->
<link rel="stylesheet" media="all" property="stylesheet" type="text/css" href="xxxx/vstore/vstore.css?1477744500" />
```
I was able to solve this for javascript by using "footer" as parameter. I tried to use "url" for css, but it's put in footer too.  
How to get css files between <head></head> in this case?

**Comment by Moc** [comment]
You could use the e_header.php file and include a check to see if the menu is loaded. 
The `e107::getMenu()->isLoaded()` method provides this ability. Example; https://github.com/e107inc/e107/blob/afbe20614b46805fc8fb169f5dd0a200bf600062/e107_plugins/news/e_header.php#L17

Would this work for you?

**Comment by Jimmi08** [comment]
Yes. Thank you. Closing.
