### ISSUE TITLE
social media Registration / signin

### ISSUE THREAD

**Issue by thunderlight411** [e107inc/e107#197]
i'm testing the social media registration and log in functionality
and i must say that the registration for Facebook and Twitter are working very well.
but after a log off i can't log in with any of the 2 accounts into the website

When i check out the DB i see that the username for a Facebook user is named 
something like FacebookXXXX

is it possible to add the Facebook log in functionality into the logon area ?

Thanks for the reply

**Comment by CaMer0n** [comment]
I have just upgraded hybridAuth and made some changes. Please test and let me know if it helps with the above. Thank you.
