### ISSUE TITLE
Welsh Language Code is associated incorrectly with Cyprus Flag

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1971]
Hi All 

So I have found a small issue, when the language selection menu is set to use flags, the incorrect flag in the drop-down choice shows the Cyprus flag, not the Welsh flag. No idea if this is an e107 issue or Bootstrap. 

![image](https://cloud.githubusercontent.com/assets/2847651/19832090/7a15f3de-9e12-11e6-8fa5-5c6f2af4f5b5.png)

Cyprus country code is CY but Welsh Language code is CY. 

So I started reading up on what is correct - an interesting topic.  

![image](https://cloud.githubusercontent.com/assets/2847651/19831303/c99fe54a-9dfe-11e6-99c5-9d88f3e13f4e.png)

English Wiki Pages use EN https://en.wikipedia.org/wiki/Welsh_language 
Welsh Wiki Pages use CY https://cy.wikipedia.org/wiki/Cymraeg 
Cyprus itself has CY as the country code, hence the clash https://en.wikipedia.org/wiki/Cyprus 

What's even more confusing is Wales is a Country within the UK which is actually GB and NI. 
http://www.i18nguy.com/unicode/language-identifiers.html Code for Welsh is hence cy-GB (Welsh). Equally Argentina has a region Patagonia which also uses Welsh hence cy-AR (Welsh). 

The iconic UK Union Flag, colloquially called the Union Jack is incorrect for English too, as this flag represents the constituent countries of the UK. The English flag is actually a white background with a red cross of St George. 
 
There are lots of points in this article http://www.flagsarenotlanguages.com/blog/ It explains why flags are generally a bad choice for Language selection on websites 

As a result, personally, I'm going turn flags off :) ... and we have that choice in prefs anyway. 

Interesting problem to read about. There have been lots of high profile gaffs to do with misuse of flags for language choices. I'm convinced they are inappropriate, possibly the only exception might be in an online shop, to choose the store in your country. 

It may be more flexible to allow the flags to be configurable so the site owner can choose as appropriate to there site? 

Thanks 
Mike

**Comment by Jimmi08** [comment]
@MikeyGMT How did you get these flags in navbar? I didn't know that it's possible in core. Thanks

**Comment by MikeyGMT** [comment]
Multilan plugin @Jimmi08 prefs > navigation > Display flags in dropdown menu

**Comment by MikeyGMT** [comment]
So this should actually be in the Multilan git space - my bad.

**Comment by rica-carv** [comment]
Optionally, for different countries with similar languages you can use something like this or similar:
![english-language-flag-1-icon 1](http://icons.iconarchive.com/icons/icons-land/vista-flags/256/English-Language-Flag-1-icon.png)
![](https://67.media.tumblr.com/tumblr_m4856hLUs21qz8q0ho1_1280.png)

It's not pretty, i know....

**Comment by MikeyGMT** [comment]
I'm happy with not using flags. It's fine for flags when a site has a store in Portugal or Brasil. It's never going to work to represent a language. I'm totally in agreement with the blogs posted above. Nationalism is a bit naff, especially after br-exit :( [verysadface]

**Comment by Jimmi08** [comment]
@MikeyGMT Thank you for point me to that plugin. Very nice solution for langs in navbar. I use different plugin (very old) so I can get inspired. I don't agree about not using flags but true is that I am used only to English, German and some other well know languages.  But that old plugin use for flags the language name, not the code (Slovak instead SK) so I suppose this will not be issue.

**Comment by MikeyGMT** [comment]
Hence why I think making the flag configurable would be an improvement. So Admins can choose which flag is appropriate for their site.

**Comment by CaMer0n** [comment]
@MikeyGMT you're referring to the multilan plugin? If so, please post the issue here: https://github.com/e107inc/multilan/issues

**Comment by MikeyGMT** [comment]
Done - closing here

**Comment by CaMer0n** [comment]
Thank you! :+1:
