### ISSUE TITLE
file (media) manager - not able remove file after using

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1974]
With images there is possibility to empty already used image fields.  But with files I don't see how to remove added file to field.  
![image](https://cloud.githubusercontent.com/assets/5429548/19835641/7b9cd8a0-9e8d-11e6-823d-018a07b47a64.png)
![image](https://cloud.githubusercontent.com/assets/5429548/19835643/88c7a546-9e8d-11e6-884c-b805ff80c735.png)

I can replace it with other file, but how to add something like this to files:
![image](https://cloud.githubusercontent.com/assets/5429548/19835654/a8a9c8c6-9e8d-11e6-9fcd-19821b39bbe3.png)

Thanks.

**Comment by CaMer0n** [comment]
@Jimmi08 Please update and try with this added code. Thanks.

**Comment by Jimmi08** [comment]
![image](https://cloud.githubusercontent.com/assets/5429548/21314727/e07908f6-c5f8-11e6-9dfb-674301d22622.png)

Works. Thank you.
