### ISSUE TITLE
IP ban doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1975]
These are new users (look at join date)
![image](https://cloud.githubusercontent.com/assets/5429548/19836108/7569353c-9e97-11e6-86fa-022962e3e1bd.png)

but one of these IPs are already on ban:
![image](https://cloud.githubusercontent.com/assets/5429548/19836119/9ced6d26-9e97-11e6-9ae1-511df71bd37b.png)

I changed Maximum Signups permitted from the same IP address to 1. All these spam users are from .pl adress, what can I do to prevent this? Except manually add them to .htaccess, of course.  Thanks

Oh and there are no entries in log table. Do I need to something check to add this to it?

**Comment by rica-carv** [comment]
I'm currently using ZB block on my live site, and since i set it up, spam bots stopped registering....

**Comment by Moc** [comment]
What about the SFS plugin? https://github.com/e107inc/sfs

**Comment by CaMer0n** [comment]
@Jimmi08 I would be interested in troubleshooting this with you over Teamviewer if you're interested. I have noticed something similar recently.

**Comment by Jimmi08** [comment]
@CaMer0n Of course. I will write you on gitter

**Comment by CaMer0n** [comment]
Closing this. The "banactions" file is an incomplete feature.
