### ISSUE TITLE
Bug: (e107v2.1.2) Plugin-Manager causes problem in e_marketplace.php on line 506

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#1977]
In v2.1.1 plugin manager works like a charm - in v2.1.2 ends the plugin manager call in:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' : failed to load external entity "http://e107.org/service?wsdl" in E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php:506 Stack trace: #0 E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php(506): SoapClient->SoapClient('http://e107.org...', Array) #1 E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php(182): e_marketplace_adapter_wsdl->__construct() #2 E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php(197): e_marketplace->adapter() #3 E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php(247): e_marketplace->call('getList', Array) #4 E:\XAMPP\htdocs\e107v2\e107_admin\plugin.php(1244): e_marketplace->getVersionList() #5 E:\XAMPP\htdocs\e107v2\e107_admin\plugin.php(447): pluginManager->pluginRenderList() #6 E:\XAMPP\htdocs\e107v2\e107_admin\plugin.php(189): pluginManager->pluginObserver() #7 {main} thrown in E:\XAMPP\htdocs\e107v2\e107_handlers\e_marketplace.php on line 506

**Comment by chimcen** [comment]
Sry...it seems it was a problem with my internet connection at work side... switching to another connection solves that. Anyway interesting there is a behavior change between v2.1.1 and v2.1.2/v2.1.3...

**Comment by CaMer0n** [comment]
Thank you @chimcen I have added a change to e_marketplace.php to try to catch that error.

**Comment by chimcen** [comment]
Changes works. Now its possible to open plugin manager even if there is no internet connection.

**Comment by CaMer0n** [comment]
@chimcen Thank you for checking.
