### ISSUE TITLE
<extendedFields> in plugin.xml ignoring system att for more fields than one

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1982]
I am plaing with plugin.xml and e_user.php. 
When I have more than one UE field, s_ystem_ attribute is taken from first and used for all fields. 

Example:
```
	<extendedFields>
			<field name="name" type='EUF_TEXT' default='' active='true' allow_hide='1' text='Skype Name' system='0'  />
			<field name="status" type='EUF_DROPDOWN' default='notset' active='true' allow_hide='1' text='Skype Status' system='1' 
      	values='notset,online,offline,notdisturb,away,e107' />
		</extendedFields>
```
- all fields are not system. So if my first field is set as system, all fields are system then.  

Otherwise it works as a charm. Great work. Thanks

**Comment by CaMer0n** [comment]
The default when the `system` attribute is not set is **system=true** 

When the `system` attribute IS set, it must be `system='true'` (not '1') to set it to **true**. 
Any value other than 'true' for the `system` attribute will set it to **false** (even a value of "1"). 
To set it to false, it would be best to use `system='false'`

So, there is no bug here, just an incorrect syntax in the plugin.xml example above.
