### ISSUE TITLE
[Question] Media picker category filter?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1983]
Maybe i'm going nuts or something like that, but wasn't there a category filter near the pagination and search box, at the modal box that pops up when we pick a media for any item in admin ui?
Or i've dreamed about it?

Furthemore, the search box is kind of bugged, since it doesn't search anything (at least in my localhost test site, with latest github files...)

**Comment by CaMer0n** [comment]
Enable DEBUG in basic SQL mode and it will display the search query.

**Comment by Jimmi08** [comment]
@rica-carv Go to Search Settings, edit f.e. news (just edit mode and save) and you will see results. 

![image](https://cloud.githubusercontent.com/assets/5429548/19938672/16c423ca-a126-11e6-9946-0833c7250936.png)

**Comment by rica-carv** [comment]
@CaMer0n Somehow, SQL debug on the modal box only gives me the yellow warnings below, nothing else... Even clicking on the go button has no effect....

@Jimmi08 I'm talking about this search box:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/19950173/c5983fc2-a14d-11e6-9099-bf3b94ed3605.jpg)

**Comment by Moc** [comment]
@rica-carv is this issue still relevant?

**Comment by Moc** [comment]
Closing as no feedback. Let me know if it needs to be reopened.
