### ISSUE TITLE
user.php shown as blanc

### ISSUE THREAD

**Issue by shepardNL** [e107inc/e107#1992]
hello,

i'm trying to find the problem for days but i cant find the problem..

when im on my site on the (clan)roster page and click on a members name in goes to user.php?id.1 but the page is shown as blanc http://scea-clan.eu/user.php?id.1
when i check the element it only shows 

<!doctype html>
<html lang="en">
<head>
<meta charset='utf-8' />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>Screaming-Eagles</title>

can somebody help me out ?
im getting sick of searching the problems ( also used the e107 debugger )

**Comment by Moc** [comment]
You say you also used the e107 debugger. Did you get any errors to show when using the debug mode and navigating to the /user.php page?

Are you using the latest files from Github? If not, try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by shepardNL** [comment]
Hello,

i did all you said me to do but it diddnt work out,
i diddnt get any error on the user.php with the debugger

**Comment by MikeyGMT** [comment]
Go to server root /home/sitename/error_log see if that has any hints. 

Have you copied e107_core/templates to e107_themes/templates? NOTE: If you have customised these, then take a backup and reapply the customisations to the new versions of the files.

**Comment by Moc** [comment]
Which theme are you using? Try temporarily switching to the default bootstrap3 theme?

**Comment by shepardNL** [comment]
im using a ground zero theme its a bought theme, but on the default theme
it doesn't work aswel,

@MikeyGMT do i need to do that ? because if i do that the templates will
change right ?

2016-11-04 10:54 GMT+01:00 Tijn Kuyper <notifications@github.com>:

**Comment by shepardNL** [comment]
@MikeyGMT well i did try it now but it diddn't work aswel

**Comment by MikeyGMT** [comment]
OK, as @Moc suggested:-

Change to the SiteTheme to e107 "BOOTSTRAP3" theme. 

Please confirm if the problem exists there too.

**Comment by shepardNL** [comment]
i allready tried that couple of times, that also doesn't work

might there be some mistakes in the /user.php ? ( i diddnt change anything )

<?php
/*
 * e107 website system
 *
 * Copyright (C) 2008-2010 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 * User information
 *
 * $URL$
 * $Id$
 *
 */
//HCL define('PAGE_NAME', 'Members');

require_once("class2.php");
include_lan(e_LANGUAGEDIR.e_LANGUAGE.'/lan_'.e_PAGE);

// Next bit is to fool PM plugin into doing things
global $user;
$user['user_id'] = USERID;

// BC for v1.x template
$bcList = array(
	'LAN_112'   => 'LAN_USER_60',// Email Address
	'LAN_138'   => 'LAN_USER_52', // Registered members
	'LAN_139'   => 'LAN_USER_57', // Order
	"LAN_142"   => "LAN_USER_58", // Member
	"LAN_145"   => "LAN_USER_59", // Joined
	"LAN_146"   => "LAN_USER_66", // Visits since...
	"LAN_147"   => "LAN_USER_67", // Chatbox posts
	"LAN_148"   => "LAN_USER_68", // Comments posted
	"LAN_149"   => "LAN_USER_69", // Forum posts
	"LAN_308"   => "LAN_USER_63", // Real Name
	"LAN_403"   => "LAN_USER_64", // Site Stats
	"LAN_404"   => "LAN_USER_65", // Last visit
	"LAN_419"   => "LAN_SHOW", // Show
	"LAN_425"   => "LAN_USER_62" // Send Private Message
);

e107::getLanguage()->bcDefs($bcList);



if(e_AJAX_REQUEST)
{
	if(vartrue($_POST['q']))
	{
		$db = e107::getDb();
		$tp = e107::getParser();

		$q = $tp->filter($_POST['q']);
		$l = vartrue($_POST['l']) ? intval($_POST['l']) : 10;

		$where = "user_name LIKE '". $q."%' ";

		//TODO FIXME Filter by userclass.  - see $frm->userlist().


		if($db->select("user", "user_id,user_name", $where. " ORDER BY user_name LIMIT " . $l))
		{
			$data = array();
			while($row = $db->fetch())
			{
				$data[] = array(
					'value' => $row['user_id'],
					'label' => $row['user_name'],
				);
			}

			if(count($data))
			{
				$ajax = e107::getAjax();
				$ajax->response($data);
			}
		}
	}
	exit;
}


// require_once(e_CORE."shortcodes/batch/user_shortcodes.php");
require_once(e_HANDLER."form_handler.php");

if (isset($_POST['delp']))
{
	$tmp = explode(".", e_QUERY);
	if ($tmp[0]=="self")
	{
		$tmp[1]=USERID;
	}
	if (USERID == $tmp[1] || (ADMIN && getperms("4")))
	{
		$sql->select("user", "user_sess", "user_id='". USERID."'");
		$row = $sql->fetch();
		@unlink(e_AVATAR_UPLOAD.$row['user_sess']);
		$sql->update("user", "user_sess='' WHERE user_id=".intval($tmp[1]));
		header("location:".e_SELF."?id.".$tmp[1]);
		exit;
	}
}

$qs = explode(".", e_QUERY);
$self_page =($qs[0] == 'id' && intval($qs[1]) == USERID);


$USER_TEMPLATE = e107::getCoreTemplate('user');
e107::scStyle($sc_style);

if(empty($USER_TEMPLATE)) // BC Fix for loading old templates. 
{
	e107::getMessage()->addDebug( "Using v1.x user template");
	include(e107::coreTemplatePath('user')); //correct way to load a core template. (don't use 'include_once' in case it has already been loaded).
}
else
{
	$USER_FULL_TEMPLATE         = $USER_TEMPLATE['view'];
	$USER_SHORT_TEMPLATE_START  = $USER_TEMPLATE['list']['start'] ;
	$USER_SHORT_TEMPLATE        = $USER_TEMPLATE['list']['item'] ;
	$USER_SHORT_TEMPLATE_END    = $USER_TEMPLATE['list']['end'];
}

$USER_FULL_TEMPLATE = str_replace('{USER_EMBED_USERPROFILE}','{USER_ADDONS}', $USER_FULL_TEMPLATE); // BC Fix

$user_shortcodes = e107::getScBatch('user');
$user_shortcodes->wrapper('user/view');




/*
if (file_exists(THEME."user_template.php"))
{
	require_once(THEME."user_template.php");
}
else
{
	require_once(e_BASE.$THEMES_DIRECTORY."templates/user_template.php");
}
  */

$user_frm = new form;
require_once(HEADERF);
if (!defined("USER_WIDTH")){ define("USER_WIDTH","width:95%"); }

$full_perms = getperms("0") || check_class(varset($pref['memberlist_access'], 253));		// Controls display of info from other users
if (!$full_perms && !$self_page)
{
	$ns->tablerender(LAN_ERROR, "<div style='text-align:center'>".LAN_USER_55."</div>");
	require_once(FOOTERF);
	exit;
}

if (isset($_POST['records']))
{
	$records = intval($_POST['records']);
	$order = ($_POST['order'] == 'ASC' ? 'ASC' : 'DESC');
	$from = 0;
}
else if(!e_QUERY)
{
	$records = 20;
	$from = 0;
	$order = "DESC";
}
else
{
	if ($qs[0] == "self")
	{
		$id = USERID;
	}
	else
	{
		if ($qs[0] == "id")
		{
			$id = intval($qs[1]);
		}
		else
		{
			$qs = explode(".", e_QUERY);
			$from = intval($qs[0]);
			$records = intval($qs[1]);
			$order = ($qs[2] == 'ASC' ? 'ASC' : 'DESC');
		}
	}
}
if (vartrue($records) > 30)
{
	$records = 30;
}

if (isset($id))
{
	$user_exists = $sql->count("user","(*)", "WHERE user_id = ".$id."");
	if($id == 0 || $user_exists == false)
	{
		$text = "<div style='text-align:center'>".LAN_USER_49." ".SITENAME."</div>";
		$ns->tablerender(LAN_ERROR, $text);
		require_once(FOOTERF);
		exit;
	}

	$loop_uid = $id;

	$ret = e107::getEvent()->trigger("showuser", $id);
	$ret2 = e107::getEvent()->trigger('user_profile_display',$id);

	if (!empty($ret) || !empty($ret2))
	{
		$text = "<div style='text-align:center'>".$ret."</div>";
		$ns->tablerender(LAN_ERROR, $text);
		require_once(FOOTERF);
		exit;
	}

	if(vartrue($pref['profile_comments']))
	{
		require_once(e_HANDLER."comment_class.php");
		$comment_edit_query = 'comment.user.'.$id;
	}

	if (isset($_POST['commentsubmit']) && $pref['profile_comments'])
	{
		$cobj = new comment;
		$cobj->enter_comment($_POST['author_name'], $_POST['comment'], 'profile', $id, $pid, $_POST['subject']);
	}

	if($text = renderuser($id))
	{
		$ns->tablerender(LAN_USER_50, $text);
	}
	else
	{
		$text = "<div style='text-align:center'>".LAN_USER_51."</div>";
		$ns->tablerender(LAN_ERROR, $text);
	}
	unset($text);
	require_once(FOOTERF);
	exit;
}

// $users_total = $sql->count("user","(*)", "WHERE user_ban = 0");



	// --------------------- List Users ------------------------  //TODO Put all of this into a class.

	$users_total=  $sql->count("user","(*)", "WHERE user_ban = 0");
	$query = "SELECT u.*, ue.* FROM `#user` AS u LEFT JOIN `#user_extended` AS ue ON u.user_id = ue.user_extended_id WHERE u.user_ban = 0 ORDER BY u.user_id ".$order." LIMIT ".intval($from).",".intval($records);

	if (!$data = $sql->retrieve($query,true))

	// if (!$sql->select("user", "*", "user_ban = 0 ORDER BY user_id $order LIMIT $from,$records"))
	{
		echo "<div style='text-align:center'><b>".LAN_USER_53."</b></div>";
	}
	else
	{
		// $userList = $sql->db_getList();
		$sc = e107::getScBatch('user');
		$text = $tp->parseTemplate($USER_SHORT_TEMPLATE_START, TRUE, $sc);

		foreach ($data as $row)
		{
			$loop_uid = $row['user_id'];

		//	$text .= renderuser($row, "short");
			$sc->setVars($row);
			$sc->wrapper('user/list');

			$text .= $tp->parseTemplate($USER_SHORT_TEMPLATE, TRUE, $sc);
		}

		$text .= $tp->parseTemplate($USER_SHORT_TEMPLATE_END, TRUE, $sc);
	}

	$ns->tablerender(LAN_USER_52, $text);

	$parms = $users_total.",".$records.",".$from.",".e_SELF.'?[FROM].'.$records.".".$order;
	echo "<div class='nextprev form-inline'>&nbsp;".$tp->parseTemplate("{NEXTPREV={$parms}}")."</div>";











function renderuser($uid, $mode = "verbose")
{
	global $pref, $sc_style, $user_shortcodes;
	global $EXTENDED_START, $EXTENDED_TABLE, $EXTENDED_END, $USER_SHORT_TEMPLATE, $USER_FULL_TEMPLATE, $USER_TEMPLATE;
	global $user;

	$tp = e107::getParser();

	if(is_array($uid))
	{
		$user = $uid;
	}
	else
	{
		if(!$user = e107::user($uid))
		{
			return FALSE;
		}
	}
	
	$user_shortcodes->setVars($user);


	if($mode == 'verbose')
	{
		return $tp->parseTemplate( $USER_FULL_TEMPLATE, TRUE, $user_shortcodes);
	}
	else
	{
		return $tp->parseTemplate($USER_SHORT_TEMPLATE, TRUE, $user_shortcodes);
	}
}

require_once(FOOTERF);
?>

**Comment by MikeyGMT** [comment]
Go to your server. 
Find file : "error_log" 
View in text editor.

**Comment by MikeyGMT** [comment]
![image](https://cloud.githubusercontent.com/assets/2847651/20011643/3de04bd0-a2a4-11e6-8605-794d0e556cbd.png)

**Comment by Moc** [comment]
@shepardNL I've removed the paste of /user.php, as we can view it ourselves too, assuming you are using the latest version.

As @MikeyGMT suggested, let's see if we can find an error log. The other alternative is that you provide us access to your website (admin area login + FTP login) so we can debug it manually. 
You can find the sitelog either in your FTP folders, or in your webhosting control panel (cPanel, DirectAdmin, Plesk, etc.) 



@MikeyGMT Sidenote: the availability of an error log depends heavily on the server configuration. A large amount of shared hosting providers only provide access to their error logs through their control panel and not directly through FTP.

**Comment by MikeyGMT** [comment]
Such as here 
![image](https://cloud.githubusercontent.com/assets/2847651/20011798/b40b3158-a2a4-11e6-840e-11db2c373c5c.png)

**Comment by Moc** [comment]
@shepardNL Could you also provide the PHP version that is used please? Thanks

**Comment by shepardNL** [comment]
wel the error that comes up is : 20161103T234227: www.scea-clan.eu/user.php
PHP Fatal error:  require_once(): Failed opening required 'e107_themes//templates/user_template.php' (include_path='.:/usr/local/lib/php-5.5.22-amd64/lib/php') in /hermes/bosnaweb05a/b1947/ipg.sceaclaneu/e107_plugins/aacgc_roster_adv/e_meta.php on line 25

and the php version im using is php 5.5

**Comment by Moc** [comment]
Yeah found it! :) There is an issue in the aacg roster plugin. Can you paste the contents of the `/e107_plugins/aacgc_roster_adv/e_meta.php` file please?

**Comment by shepardNL** [comment]
yea i was looking in to it aswel 

<?php

/*
#######################################
#     e107 website system plguin      #
#     AACGC Advanced Roster           #
#     by M@CH!N3                      #
#     http://www.aacgc.com            #
#######################################
*/

if (e_PAGE == "forum_viewtopic.php") {
	require_once(e_PLUGIN."forum/templates/forum_viewtopic_template.php");
	$forum_old = "{POSTS}";
	$forum_new = "{POSTS}{ADVRANKFORUM}";
	$FORUMTHREADSTYLE = str_replace($forum_old, $forum_new, $FORUMTHREADSTYLE);
	$FORUMREPLYSTYLE = str_replace($forum_old, $forum_new, $FORUMREPLYSTYLE);
}


if (e_PAGE == "user.php") {



	require_once(e_THEME."/templates/user_template.php");

	$user_old = "{USER_UPDATE_LINK}";
	$user_new = "{ADVRANKUSER} {USER_UPDATE_LINK}";
	
$USER_FULL_TEMPLATE = str_replace($user_old, $user_new, $USER_FULL_TEMPLATE);

}


?>

**Comment by Moc** [comment]
Change 
```php
 require_once(e_THEME."/templates/user_template.php");
``` 

to:

```php
 require_once(e_THEME."templates/user_template.php");
```

See if that fixes it.

**Comment by shepardNL** [comment]
first thing i tried when i saw it cause in the error it said // 

might it not be  require_once(e_THEME."e107_core/templates/user_template.php");  ?

**Comment by Moc** [comment]
Try 


```php
 require_once(e_CORE."templates/user_template.php");
```

Also, is your e107 installation upgraded from v1 or installed v2 from the beginning?
Probably this plugin is not updated to be compatible with v2 yet.

**Comment by shepardNL** [comment]
tried that now diddn't work aswel ( but the error is gone now ) 
even i go on the forum and click on a name it doesn't work aswel, looks like there has to be something wrong with my user.php i guess

**Comment by Moc** [comment]
No it's not likely to be /user.php, it's a template/plugin/theme issue which hooks into the user.php page. 

Which plugins are using? Can you temporarily try uninstalling the 'aacgc_roster_adv' plugin? During the uninstall options you can select to keep the database tables, so you don't lose any configuration/data.

**Comment by shepardNL** [comment]
that diddn't work

**Comment by tgtje** [comment]
No guru but just an idea (because of io error).. what happens if you disable htaccess file (i do think due to nature of site, some changes will be made there) ? Another idea was if some extended fields might be used, and throw in error... Just some ideas (brainstorming).

**Comment by Jimmi08** [comment]
Short of time, so just quickly. 
That plugins (aacgc) are not customized for version 2.  I thought that that plugin is not free, othewise I would look at it.  I just now found that plugins are free, I've spend weekend to update jbroster, they didn't tell me that aacgc have them too. 

By the way - Moc advices didn't work because you are using SEF-URL and that plugins test e_PAGE...   but there is different issue. 
 
This is related:
http://e107help.org/2811/how-this-is-solved-in-new-version

But I see you are using twitch plugin. It doesn't work at all, because twitch API. You need to use different API now. We had got API works, but it returns different values as before, so that plugin needs totally rewrite because new output (with new API and client ID there is still output as online). It's planned, I just don't know when.

**Comment by shepardNL** [comment]
Thanks man!! deleted Twitch and that solved the problem
