### ISSUE TITLE
Secure Image and Path 

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1994]
it's the path correct? see (image) and i have put the secure_image_custom.php file to e_Image folder and not to the Theme folder?
and the Font to the same folder?
thx
![image](https://cloud.githubusercontent.com/assets/1758577/19957808/34e5f562-a19a-11e6-8788-859a1d1cd3d7.png)

**Comment by Moc** [comment]
Just making sure, the "e_IMAGE" references to the default e107_images folder. 
Is this the folder that you put the secure_image_custom.php file in?

**Comment by schlrech** [comment]
The question was whether it is there in the right place. Perhaps a own folder for the extensions is more suitable?

**Comment by Moc** [comment]
Ah I assumed you had an issue with getting it to work. So it works correctly for you?

This 'functionality' is only used very little and it's also not really documented. Perhaps in the feature it could be expanded so for example plugins can use it. I'll put it on the future list of ideas.
