### ISSUE TITLE
[Enhancement] Enable news category to determine news category default template...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2000]
Right now, on the adnmin Ui we can only choose the template to be rendered on the news frontpage, but on any news category, it's always rendered the default news template.
Is there anyway to choose wich template to be rendered also at the news category?

And in the meantime, allow the default template to have start & end, just like the list template?

**Comment by CaMer0n** [comment]
News category can be rendered as a list or using default. It's just a matter of using the right links. 
Check the sitelink function for news.

**Comment by rica-carv** [comment]
@CaMer0n Err, i'm kind of lost on that [sitelink function for news](https://github.com/e107inc/e107/blob/afbe20614b46805fc8fb169f5dd0a200bf600062/e107_plugins/news/e_sitelink.php)....

I don't see any template being called there, but my previous statement was because i tested it within news_template.php, and therefore reached that conclusion....

**Comment by CaMer0n** [comment]
The template is called in news.php.  Try `News Category List` or `News Category Pages` as a sitelink function.

**Comment by rica-carv** [comment]
@CaMer0n Still confused.... And where do i try that as a sitelink function? In e_sitelink.php? In admin UI?

**Comment by fizi** [comment]
It's interesting to me. No template for category view. If I see all news in list (...news.php?cat.1) - ok, template exists...But if I want make template for news category (...news/category/kategoria-1.html) no template for this. The template for category hardcoded in news.php (example: $NEWSLISTCATTITLE = "<h1 class='newscatlist-title'>Category 1</h1>";
How make template for it?

**Comment by CaMer0n** [comment]
Thanks @fizi , that's a good point. We'll need to add something to news_template.php. 
@rica-carv Every sitelink has the option to use a function . For news the options are: 

- New Category List
- News Category Pages
- Last 10 News Items. 

.. are you able to see that? (eg. e107_admin/links.php?action=edit&id=1 )

**Comment by CaMer0n** [comment]
This came up again recently.. allowing a news-category to set the news template. I'll see what I can do.

**Comment by CaMer0n** [comment]
This has been completed. If you find any issues, please re-open. Thank you @rica-carv @fizi @Jimmi08
