### ISSUE TITLE
Undefined LANS Notice error. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2001]
e107_admin/newspost.php 

    Notice Use of undefined constant RL_LAN_088 - assumed 'RL_LAN_088', Line 6071 of e107_handlers\admin_ui.php
    Notice Use of undefined constant RL_LAN_127 - assumed 'RL_LAN_127', Line 6509 of e107_handlers\admin_ui.php
    Notice Use of undefined constant RL_LAN_128 - assumed 'RL_LAN_128', Line 6510 of e107_handlers\admin_ui.php
    Notice Use of undefined constant RL_LAN_129 - assumed 'RL_LAN_129', Line 6511 of e107_handlers\admin_ui.php
    Notice Use of undefined constant RL_LAN_130 - assumed 'RL_LAN_130', Line 6512 of e107_handlers\admin_ui.php
    Notice Use of undefined constant RL_LAN_131 - assumed 'RL_LAN_131', Line 6513 of e107_handlers\admin_ui.php

@yesszus  ( @MikeyGMT )
It appears the LANs for the admin-ui have been placed in the lan_admin_log.php file?
They should normally be in lan_admin.php for the admin-ui.

**Comment by yesszus** [comment]
I am moved undefined LANS to lan_admin.php.
Tested and works for me in admin_log.php, newspost.php files.

**Comment by Moc** [comment]
I think this issue can be closed?
