### ISSUE TITLE
Bug Settings>Search Incorrectly displays Config Option for Downloads when uninstalled.

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2003]
In Settings>Search the config form incorrectly displays the Search Option LAN_PLUGIN_DOWNLOAD_NAME (Downloads) even when the Downloads Plugin is uninstalled.

**Comment by CaMer0n** [comment]
@MikeyGMT Does removing e107_handlers\search\advanced_download.php
e107_handlers\search\search_download.php help?

**Comment by MikeyGMT** [comment]
The LAN has gone, but the download row and drop down choice box is still there
Will test further. 
Mikey

**Comment by MikeyGMT** [comment]
Confirmed on a second test upgraded site, both files removed, but Download option is still displayed in Settings > Search.

**Comment by MikeyGMT** [comment]
Removing comments_download.php is still in the GIT repo removes the LAN but leaves the dropdown choice.
![image](https://cloud.githubusercontent.com/assets/2847651/20716012/df752dbe-b648-11e6-88f3-cb5f46819549.png)

**Comment by MikeyGMT** [comment]
Inspect Element
![image](https://cloud.githubusercontent.com/assets/2847651/20716062/14be789a-b649-11e6-9825-89194e5f720d.png)

**Comment by Moc** [comment]
Issue is still occurring, it is caused by the `search_prefs`. This is the content directly after a clean install:

```
array (
  'comments_handlers' => 
  array (
    'news' => 
    array (
      'id' => 0,
      'dir' => 'core',
      'class' => '0',
    ),
    'download' => 
    array (
      'id' => 2,
      'dir' => 'core',
      'class' => '0',
    ),
  ),
  'core_handlers' => 
  array (
    'comments' => 
    array (
      'class' => '0',
      'pre_title' => '1',
      'pre_title_alt' => '',
      'chars' => '150',
      'results' => '10',
      'order' => '2',
    ),
    'users' => 
    array (
      'class' => '0',
      'pre_title' => '1',
      'pre_title_alt' => '',
      'chars' => '150',
      'results' => '10',
      'order' => '3',
    ),
  ),
  'google' => '0',
  'multisearch' => '1',
  'mysql_sort' => '1',
  'php_limit' => '',
  'relevance' => '0',
  'selector' => '2',
  'time_restrict' => '0',
  'time_secs' => '60',
  'user_select' => '1',
)
```

in default_install.xml

```` 
<search name="comments_handlers"><![CDATA[array (
  'news' => 
  array (
    'id' => 0,
    'dir' => 'core',
    'class' => '0',
  ),
  'download' => 
  array (
    'id' => 2,
    'dir' => 'core',
    'class' => '0',
  ),
)]]></search>
```

@CaMer0n Can this be safely removed? Will it be added back when the download plugin is installed?
