### ISSUE TITLE
search template in theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2007]
Could this in search.php :
```
			if (file_exists(THEME."search_template.php")) 
			{
				require(THEME."search_template.php");
			} 
			else 
			{
				require(e_CORE."templates/search_template.php");
			}
```

be changed for meantime to:
`require(THEME."templates/search_template.php"); `

It's confusing when theme search template is not loaded and you use it according new standards.

Thanks

**Comment by CaMer0n** [comment]
Yes, you can add that location so that it is checked first.  :+1:
