### ISSUE TITLE
action in search forms

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2008]
in search form in search.php there is this action in template:
`<form class="form-horizontal" role="form" id="searchform" method="get" action="'.e_SELF.'">`

it works if you are on search.php. But if you set search page as frontpage, you get wrong url after posting search form.
In search menu there is this action:

`<form class="form-inline" method="get" action="'.e_HTTP.'search.php">`

But because you can set SEF URL for search.php, there should be probably something else. 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 It should be an easy one to fix. Do you feel like doing it? Just add a new shortcode to search.php `sc_search_form_url() `and replace the e_SELF with it. `{SEARCH_FORM_URL}` then add this to the shortcode: 

`return e107::getUrl()->create('search');`

**Comment by Jimmi08** [comment]
@CaMer0n  You could check this:
https://github.com/Jimmi08/e107/commit/3c5bdbaf854d4e47cd7f03f41c6d705e12445466

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 I added it.
