### ISSUE TITLE
Windows8 Media-Manager Ajax Issues

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2010]
I have at least 2 people reporting that the media-manager navigation (left/right arrows) and the Youtube URL entry (which loads a thumbnail via ajax) is causing their browser to freeze. (Firefox and Chrome) 

As I don't use Windows 8, I have no means to test this. Any feedback from people who do would be appreciated. 

Thanks

@Moc @MikeyGMT @tgtje @lonalore @rica-carv ?

**Comment by lonalore** [comment]
I have a win8.1 (virtualbox) installation on my computer in the office. I will look into it tomorrow.

**Comment by tgtje** [comment]
Well, do not run win 8 anymore but 10 pro here are some mp4 screens..
First http://tgtje.eu/tijdelijk/Untitled%2012.mp4  is Chrome (no wysiwig)
second Chrome wysiwig http://tgtje.eu/tijdelijk/Untitled%2013.mp4
third Firefox  http://tgtje.eu/tijdelijk/Untitled%2014.mp4

No issues to be seen ( fresh synced; php 7)

**Comment by CaMer0n** [comment]
thanks guys!

**Comment by CaMer0n** [comment]
@tgtje I can't see why that would be occurring with the 'width' text. Maybe we can trouble-shoot it over gitter some time?

**Comment by tgtje** [comment]
@CaMer0n i wil do a basic test to see where it comes from (it happens also on local machine installs (php 5 and 7 based.. Some code will be posted by ???  If i can find issue i will report back by gitter. Of to earn a living ;-)

**Comment by CaMer0n** [comment]
Issue also occurring on Macbook Pro with Chrome.

**Comment by CaMer0n** [comment]
@tgtje If you didn't already, please create a new issue for the "width:... " issue.

**Comment by rica-carv** [comment]
@CaMer0n Sorry, but only got Vista and 10....

**Comment by MikeyGMT** [comment]
I have Windows 7 with me and a Windows 10 back home.
