### ISSUE TITLE
Image resize in forum post not working as expected

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2011]
Hi,

i'm not shure if its a bug or a feature - when i add images from external sites to my forum post with [img][/img] i thought they will be also resized as when they will be uploaded as attachment... or not?

![img_forum](https://cloud.githubusercontent.com/assets/22658487/20073800/f788eeee-a52d-11e6-98e0-bb4da171ee46.JPG)

**Comment by CaMer0n** [comment]
No, the image is added directly without further processing. You can do this via css though. img.bbcode { width: XXXpx }  or manually in the bbcode.  style=width:XXXpx

**Comment by chimcen** [comment]
Thank you for the hin - i've modified the bb_img.php to send with every added picture the parameter with800...
It would be sweeter if the bbcode could automaticly generate an thumbnail, past the thumbnail to the post an make it clickable so the original picture will be popup in a lightboxview or similar...

But for the first step this is also ok...

**Comment by chimcen** [comment]
Hi again,

removed it agin from bb_img.php, because the rule works for the complete page on every image - this isn't what i want.
I've added it instead into forum.css (as you recommended) - so it will only work at the forum.
But another thing is - posted images in profile signature will also be scaled to this new width.
Is there a chance to only rescale the pictures within a forum post?

**Comment by rica-carv** [comment]
Maybe those images ares sharing the same css rule.
Try to narrow the css rule to the forum post only...

**Comment by chimcen** [comment]
How?

**Comment by rica-carv** [comment]
omg...
With a custom template, i9nside your theme, encapsulate the post form in a div (or span) with a unique ID or class, and afterwards simply create the css rule to only activate inside that specific unique id or class...

**Comment by chimcen** [comment]
omg is not a good kind of conversation base - sry...

Thank you for your help - but i'm not skilled as you - i'm a beginner. This doesn't help me any further...

**Comment by rica-carv** [comment]
Well, let's give it one more try...
What's your current css rule? Please post all the rule code here.
Further more, where did you put that rule, in wich file and in wich folder?
