### ISSUE TITLE
Forum syntax error

### ISSUE THREAD

**Issue by fodor12** [e107inc/e107#2012]
Hy i download new v2.1.2

I opened forum and this error messanges

Parse error: syntax error, unexpected '[' in /wwwroot/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php on line 484

All file original don't edited

**Comment by MikeyGMT** [comment]
Hi @fodor12 
Maybe files are corrupt. 
Go to Admin Area > Tools > File Inspector
Check for errors. 
Thanks
Mike

**Comment by CaMer0n** [comment]
@fodor12 Would you mind please posting here the code from line 484 of that file?

**Comment by rica-carv** [comment]
Line 484 should be   `$caller = debug_backtrace()[1]['function'];`

**Comment by lonalore** [comment]
I think this was fixed in 50c78c65b5956f8dfa9d2bb9a6df4db49bc619cc

**Comment by Moc** [comment]
Closing because this should be fixed. If not, please comment and I'll re-open.
