### ISSUE TITLE
Question about e107::getMessage() Usage

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2013]
Hi All, 
I am trying to pick up a bit more about our code hence, attempting to debug #1712 because I would like to understand why plugin import works for some and not others (including me). This, however, is not the topic for this post. 

Here I am interested to know why plugin.php does not render debug messages. However when I add similar Debug messages in Languages Editor - which is also a popup modal admin form. In the lancheck edit form any number of Debug Messages appear OK.  

For example, I added some debug statements in pluginDownload function of plugin.php. 

`$mes->addDebug("plugin.php.pluginDownload.START - _GET contents:");`

We are in Debug Mode and on the Plugin Manager - I know this because the orange debug flag appears at the top of the page, and the Notices etc display after the main page. However in the popup pluginDownload form neither the custom debug messages or the usual debug data follows in the popup. The only e107 Message which does appear is EPL_ADLAN_95 "Unable to continue". 

I noticed the format is slightly different to elsewhere. This has echo before and the render stuff after ... 

`echo $mes->addError(EPL_ADLAN_95)->render('default', 'error');`

It does display message in red box ...  Unable to Continue

However when I duplicate the above for debug messages - it's ignored and not displayed - e.g. !

`echo $mes->addDebug("plugin.php.pluginDownload.START - _GET contents:")->render('default', 'error'); `

I can crack on with debugging using the more basic format below:- 

`echo ("plugin.php.pluginDownload.START - _GET contents:");`

Just interested to know lancheck renders debug messages without the fuss but pluginDownload refuses.  

Thanks
Mike

**Comment by CaMer0n** [comment]
Try e107::getDebug()->log("whatever") and make sure debug is set to "Basic".
