### ISSUE TITLE
Bug Figcaption

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#2018]
problem : instead if name (caption) of image width text is displayed.
![figcap](https://cloud.githubusercontent.com/assets/1811857/20119003/0d4264b6-a607-11e6-85d9-d8c4c065b66f.jpg)
result of search : 
NON wysiwig !!!(bcode editor)
posting select image from media manager (1920 px image)  :  displayed is :
[img style=width:300px;&alt=preview_frontend.png]{e_THEME}bootstrap3/preview_frontend.png[/img]

save the page and view
 displayed is image with below : width:300px;  (see posted img)
going back into edit mode : 
now the image link is displayed in editor as :

[img style=width%3A300px%3B&amp;alt=width%3A300px%3B]{e_THEME}bootstrap3/preview_frontend.png[/img]
look at the ALT !!! (changed from img name to width)

now manual removing the alt piece >  alt=width%3A300px%3B gives >
[img style=width%3A300px%3B&amp;]{e_THEME}bootstrap3/preview_frontend.png[/img]

now display (after save and view) is fine (no width etc.. below)
next step
going in _wysiwig_ mode : source code of link from posted img :  <figcaption>width:300px;</figcaption> !!!!! this one does it

when choosing the same image in wysiwig (media manager added) the alt = name of image > preview_frontend.png There is NO similar behaviour when using wysiwig the image name is displayed.

Cause ??

**Comment by CaMer0n** [comment]
Please try with the latest changes.

**Comment by tgtje** [comment]
**Confirmed working** as intendend. The actual name of image is now displayed..
Closing issue ? or waiting for confirmation from others?
