### ISSUE TITLE
Issue: Mail Preferences

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2025]
I am having an issue sending test emails, saying they have been sent but receive any emails, I've looked and I have 160 failed emails I sent a few days ago giving me the #5 Error. While in the Mail Preferences I notice that when selecting the Send bulk SMTP emails in blocks and Use VERP for bulk mailing as enabled, I saved settings, then notice the page says successfully saved but they are still disable, even refresh the page and still disable.

**Comment by LaocheXe** [comment]
Checked the System log and here is the list

 `
Array
(
    [mail_source_id] => 8
    [mail_content_status] => 10
    [mail_total_count] => 160
    [mail_togo_count] => 1
    [mail_sent_count] => 0
    [mail_fail_count] => 159
    [mail_bounce_count] => 0
    [mail_start_send] => 1478638547
    [mail_end_send] => 0
    [mail_create_date] => 1478630127
    [mail_creator] => 1
    [mail_create_app] => core
    [mail_e107_priority] => 0
    [mail_notify_complete] => 0
    [mail_last_date] => 0
    [mail_title] => eWL Back
    [mail_subject] => eWL Ladder League For MechWarriors
    [mail_body] => Hello Clan Coyote Member,\r
\r
LaocheXe here to inform all past and present Clan Coyote members that the ladder/tournament league eWL (eWarrior Leagues) is back up with ladders for any to all MechWarrior games - If you see a mech game that you and your friends would like to have matches and compete in but that game isn't on the current games list than just hit me up and I will get to work on adding the game and ladders for that game. The current league URL is http://league.clancoyote.com and yes this is the old eWL website and database, so if you had an account back in 2012 then the account is still on the database and you can login at any time, forgot the password, then use the Forgot Password function on the site.\r
\r
\r
Your fellow MechWarrior,\r
LaocheXe\r
\r
P.S. The league was brought back by demand from current MechWarrior 4 Merc players, so all the MechWarrior 4 Mercs ladders are open.
    [mail_media] => Array
        (
            [0] => Array
                (
                    [path] => 
                )

            [1] => Array
                (
                    [path] => 
                )

            [2] => Array
                (
                    [path] => 
                )

            [3] => Array
                (
                    [path] => 
                )

            [4] => Array
                (
                    [path] => 
                )

        )

    [mail_target_id] => 166
    [mail_recipient_id] => 127
    [mail_recipient_email] => goe_punk@hotmail.com
    [mail_recipient_name] => þÜñK™
    [mail_status] => 10
    [mail_detail_id] => 8
    [mail_send_date] => 1478638421
    [mail_target_info] => Array
        (
            [USERID] => 127
            [DISPLAYNAME] => þÜñK™
            [SIGNUP_LINK] => ap_127_punk_nuclear_blast_w_girl.gif
            [USERNAME] => þÜñK™
            [USERLASTVISIT] => 1426342143
        )

    [mail_sender_name] => LaocheXe
    [mail_sender_email] => forbiddenchaos@gmail.com
    [mail_send_style] => texthtml
    [mail_attach] => 
    [mail_include_images] => 0
    [mail_selectors] => Array
        (
            [user] => Array
                (
                    [email_to] => all
                    [last_visit_match] =>  
                )

        )

    [status] => SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
)
`

**Comment by CaMer0n** [comment]
Are you sure SMTP is allowed on your host? Some block sending this way. Also, be cause to check your hosts limits regarding outgoing mail.

**Comment by LaocheXe** [comment]
Yes SMTP is allowed and the site mail used to work (would send activation emails and admin notifications), now nothing is being sent.

**Comment by LaocheXe** [comment]
With POP before SMTP - it says all have been successfully sent but checking logs I see this:


`

Array
(
    [mail_source_id] => 9
    [mail_content_status] => 10
    [mail_total_count] => 162
    [mail_togo_count] => 3
    [mail_sent_count] => 159
    [mail_fail_count] => 0
    [mail_bounce_count] => 0
    [mail_start_send] => 1478965536
    [mail_end_send] => 0
    [mail_create_date] => 1478965503
    [mail_creator] => 1
    [mail_create_app] => core
    [mail_e107_priority] => 0
    [mail_notify_complete] => 0
    [mail_last_date] => 0
    [mail_title] => eWL Is Back
    [mail_subject] => To all MechWarriors
    [mail_body] => Hello Clan Coyote Member,\r
\r
LaocheXe here to inform all past and present Clan Coyote members that the ladder/tournament league eWL (eWarrior Leagues) is back up with ladders for any to all MechWarrior games - If you see a mech game that you and your friends would like to have matches and compete in but that game isn't on the current games list than just hit me up and I will get to work on adding the game and ladders for that game. The current league URL is http://league.clancoyote.com and yes this is the old eWL website and database, so if you had an account back in 2012 then the account is still on the database and you can login at any time, forgot the password, then use the Forgot Password function on the site.\r
\r
\r
Your fellow MechWarrior,\r
LaocheXe\r
\r
P.S. The league was brought back by demand from current MechWarrior 4 Merc players, so all the MechWarrior 4 Mercs ladders are open.
    [mail_media] => Array
        (
            [0] => Array
                (
                    [path] => 
                )

            [1] => Array
                (
                    [path] => 
                )

            [2] => Array
                (
                    [path] => 
                )

            [3] => Array
                (
                    [path] => 
                )

            [4] => Array
                (
                    [path] => 
                )

        )

    [mail_target_id] => 328
    [mail_recipient_id] => 127
    [mail_recipient_email] => goe_punk@hotmail.com
    [mail_recipient_name] => þÜñK™
    [mail_status] => 10
    [mail_detail_id] => 9
    [mail_send_date] => 1478965507
    [mail_target_info] => Array
        (
            [USERID] => 127
            [DISPLAYNAME] => þÜñK™
            [SIGNUP_LINK] => ap_127_punk_nuclear_blast_w_girl.gif
            [USERNAME] => þÜñK™
            [USERLASTVISIT] => 1426342143
        )

    [mail_sender_name] => LaocheXe
    [mail_sender_email] => forbiddenchaos@gmail.com
    [mail_send_style] => textonly
    [mail_attach] => 
    [mail_include_images] => 0
    [mail_selectors] => Array
        (
            [user] => Array
                (
                    [email_to] => all
                    [last_visit_match] =>  
                )

        )

    [status] => 1
)

`

**Comment by Moc** [comment]
> While in the Mail Preferences I notice that when selecting the Send bulk SMTP emails in blocks and Use VERP for bulk mailing as enabled, I saved settings, then notice the page says successfully saved but they are still disable, even refresh the page and still disable.

Confirmed this for the `Send bulk SMTP emails in blocks` option. Apparently changes are not saved properly. For me, saving the `Use VERP for bulk mailing` option works as intended.

**Comment by F1Racer68** [comment]
I'm also having the same issue. I am just completing an upgrade from e107 v1.0.4 to e107 v2.1.5. The system is running on a self hosted machine running TurnKey Lamp stack 14.6 (Jessie).

Since this is a direct upgrade, there have been no changes to the server configuration EXCEPT the version of E107. Under v1.0.4 the SMTP send mail works flawlessly. Under v2.1.4 and 2.1.5 it does not work at all. It says the test message was sent successfully, but I never receive it.

I upgraded to both v2.1.4 and then again to v2.1.5, with same issue under both.
