### ISSUE TITLE
Download page error messages

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2027]
In the versions before bootstrap the downloads page always used to give you meaningful messages when it wouldn't download.

Now however it just tells you as an example "Error 57" aka you need to log in. The same also happens for exceeding download quota. The number pertains to the download id

**Comment by tgtje** [comment]
realetd ?  #1817

**Comment by Aaronsss** [comment]
Apologies I believe it is the same issue. I did do a search but didn’t find it, my bad. 

Closed.
