### ISSUE TITLE
Facebook logins required fields & activation email

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2028]
When a user logs in with Facebook if their Facebook account does not have an email address then the email address field is unpopulated. If they try to login they just get forced to the userssettings page where it prevents them from updating their email address meaning the account is useless.

Furthermore, when logging in with Facebook it sends out an activation email and says click the link to validate your email, the problem is the email contains no link. I believe the site should not be sending out the email validation when users log in with Facebook. Or if this is intentional the email needs to contain the link and the site should prevent login until the email is validated.

**Comment by CaMer0n** [comment]
Normally no email should go out. This is odd behavior. I don't see how someone can have a facebook account without an email address.. unless Facebook is no longer sharing email addresses to third-party apps.

**Comment by Aaronsss** [comment]
To do this I had to disable email verification and set it to no verification. Otherwise the site would not let me change Email from required to display. I wasn’t able to test with no email from Facebook as I’m not sure how the chap in question did that but my suspicion is that changing email from display to required would fix it.

With regard to sending out an activation email even with email verification and email required it still sent me an email asking me to activate with no link.

**Comment by CaMer0n** [comment]
@Aaronsss Could you send me the URL to your signup page? (or privately via the chatroom if you prefer)

**Comment by Aaronsss** [comment]
@CaMer0n [http://sto-gaming.org/signup.php ](url)

**Comment by CaMer0n** [comment]
@Aaronsss Thanks.  Could you tell  me if you have anything active in Admin > Tools > Notify ?

**Comment by Aaronsss** [comment]
nope there is nothing active there

**Comment by CaMer0n** [comment]
@Aaronsss I believe this has been fixed recently, and with the pull-request I'm about to merge. Please re-open if necessary.
