### ISSUE TITLE
Open Site-Links options doesn't work

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2030]
Hi,

all the possible options for site-links opening style (e.g. "open in new window", "open in 640*480 window" or "open in 800*600 window") doesn't work - they will all open in same window... any advice?

![new_window_error](https://cloud.githubusercontent.com/assets/22658487/20230596/169f747e-a85d-11e6-9466-2e73e2ae42a2.JPG)

**Comment by CaMer0n** [comment]
It's possible the popups no longer  work. Does "Open in new window" still function for you? If not, which theme are you using?

**Comment by chimcen** [comment]
Sry, all is working - is a theme error - with default bootstrap3 theme it works...
