### ISSUE TITLE
e107 update - no admin (HTTP error 500)

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2034]
I updated with the latest Github and no admin page (500 error).

**Comment by lonalore** [comment]
Please check your error log.

**Comment by fizi** [comment]
How?

**Comment by lonalore** [comment]
Or try to enable debug mode with [debug=basic+] parameter:
/e107_admin/admin.php?[debug=basic+]

If you can't see the error details, check your error.log file on your server. What web server are you using? Apache?

**Comment by fizi** [comment]
PHP Fatal error:  Can't use function return value in write context in /chroot/home/.../.../html/.../e107_admin/includes/infopanel.php on line 170

**Comment by fizi** [comment]
PHP Version 5.3.3

**Comment by lonalore** [comment]
Please replace line 170. and 655. So replace this line:

```php
if(empty(varset($user_pref['core-infopanel-mye107'], array())))
```
with this:
```php
$myE107 = varset($user_pref['core-infopanel-mye107'], array())
if(empty($myE107))
```

here:
https://github.com/e107inc/e107/blob/master/e107_admin/includes/infopanel.php#L170
and here:
https://github.com/e107inc/e107/blob/master/e107_admin/includes/infopanel.php#L655

**Comment by lonalore** [comment]
Okay... same issue on PHP Version 5.4.39. Thanks for reporting i! Fix coming soon.

**Comment by fizi** [comment]
Now work. Thanks!

**Comment by CaMer0n** [comment]
Thanks for fixing @lonalore
