### ISSUE TITLE
HTTP ERROR 500 and no Admin

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2037]
I get this error message: 

Parse error: syntax error, unexpected 'caption' (T_STRING), expecting ')' in /customers/f/b/a/riocascadamedia.com/httpd.www/e107_handlers/core_functions.php(465) : eval()'d code on line 65

I use PHP version 7

On my frontpage there are no errors, but as soon as I try to log in og click on any menu this error shows

**Comment by Moc** [comment]
@lonalore can you check this please? Maybe related to your latest changes to the admin area panel.

**Comment by lonalore** [comment]
I already checked it not so long ago. This will be something else. I have no idea. :/

**Comment by tgtje** [comment]
Just commenting : a time difference between last 2 issues : 1 hour (by Gith)..  > 6 hours ago lonalore committed a change; 6 hours ago @Norwayman  reported.. (overlapping ?) since @rica-carv mentioned the same.. Did little test on php 7 with the latest... all running... (update 45 min. ago)
