### ISSUE TITLE
Possible two bugs.

### ISSUE THREAD

**Issue by WarheadDesignz** [e107inc/e107#2040]
Hey guys, no matter what I've tried (Been trying for 24 hours straight now). But no matter what I do, if I do a sitelink to upload.php, there's never any categories in it, so I can't do anything. (Haven't used E107 in years) but I could have sworn I remember the old 1x version had a Upload button somewhere in the Admin Panel to take care of categories and such, but I can't find that anywhere anymore either.

I've created categories everywhere I can find, still to no avail.
Also on upload.php even though the maxsize is set to 200M it's saying the max filesizes are 64M.
However in sitepreferences, it says 200M like it should. So something tells me Upload.php is having some sort of issue. (Yes Uploads are enabled).

Now potential bug #2.
The Media Manager, I can't upload even a 20 meg file, even if I add the file type (mp4) and make the max size 200M or even 200000000M. So I've had to use the html5 <video> tag just to play videos.

E107 is still by far my favorite CMS, I just wasn't expecting this being I haven't really made websites much lately. I just remembered how amazing it was, and it still is!

I just hope this is me making some sort of stupid mess-up on my end.
(Oh and yes I changed permissions), etc.

**Comment by CaMer0n** [comment]
If you update with the files from Github, the file-limit should now be respected by the Media Manager. 

For the upload categories on the frontend, this usually requires that the downloads plugin is installed. 
Do you have it installed?

fyi: developer chatroom: https://gitter.im/e107inc/e107

**Comment by N1warhead** [comment]
Thank you for getting back to me on this, much appreciated.
Awesome, glad to know the file-limit is fixed now.

Yes I do have Downloads plugin install. I will try re-installing downloads plugin to see if that helps at all.

And thank you for the chatroom, didn't know about that place.

**Comment by N1warhead** [comment]
Yeah reinstalling the plugin didn't help.

**Comment by Moc** [comment]
Issue related to filesize: #1809
Just putting it here to keep things organised :)

**Comment by CaMer0n** [comment]
@N1warhead If you can, please join us in the chatroom so we can work through the issue with you.
