### ISSUE TITLE
[Support request] - Admin UI 'userclass' field (classlist)

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2042]
I want to remove "Everyone" option from the dropdown (I want to restrict posting to authenticated users). So I set a custom classlist in 'writeParms':
```php
'room_write'  => array(
	'title'      => LAN_ECHAT_ADMIN_ROOMS_05,
	'type'       => 'userclass',
	'data'       => 'int',
	'writeParms' => 'classlist=member,admin,main,classes,nobody',
	'tab'        => 0,
),
```
But "Not ..." options are still available in the list. How can I remove "Everyone but.." gorup completely?

![kepernyokep_2016-11-17_10-44-46](https://cloud.githubusercontent.com/assets/6043821/20385238/fc2c8b50-acb6-11e6-91c1-cfd96f060b13.png)

Because a user e.g. in the "Not Members" group can be an anonymous user. Or not?

**Comment by CaMer0n** [comment]
`classlist=member,admin,main,classes,nobody,no-excludes`

(easy to find in the code, if you search for 'classlist') ;-)
