### ISSUE TITLE
problem with debugging 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2043]
I noticed this on other site, tested on my own.

1. when you run no debug mode (e_DEBUG is false) and you are not admin / user at all...  there shouldn't be debug info at all. But with sitelinks there is. 

http://e107hungary.org/signup.php?[debug=paths+]
![image](https://cloud.githubusercontent.com/assets/5429548/20391494/ea551a10-acd3-11e6-8e24-6c5625af8789.png)

2. when you set developer mode (e_DEBUG is true), I supposed that information from debugger are only for logged admin.  But not, all informations are available for anybody who know paths or use Firefox debugger.  Maybe this is correct, I just didn't know about this. 
![image](https://cloud.githubusercontent.com/assets/5429548/20391588/5e16b8a0-acd4-11e6-99c4-27046de3fbc2.png)

**Comment by CaMer0n** [comment]
1. This is an error. 
2. This is intended. Sometimes we need to see errors for guest users too.

**Comment by Moc** [comment]
I think it would be interesting to review which areas of debugging should be public and which ones should be private (eg. by admin login). For example, the `?[debug=sc+]` works on every e107 installation as a guest. This does not necessarily provide sensitive information, but it may be worth a discussion.

**Comment by Moc** [comment]
@Jimmi08 this should be fixed
