### ISSUE TITLE
Smiley Size

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2045]
So I beleive when I upgraded from 2.1.1 to 2.1.2 the smiley container got changed. Basically now it is forcing all my smileys to a fixed size, this is an issue as some are smaller and some need to be larger. Is there a way to change this back so smileys are displayed at their normal size?

**Comment by Moc** [comment]
This issue may be relevant: https://github.com/e107inc/e107/issues/1910

**Comment by Aaronsss** [comment]
excellent thanks and appologies for the duplicate. This has fixed it. Closing.
