### ISSUE TITLE
Admin > Prefs > Site Logo / Button > Media Preview image has DB details as file path 

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2051]
Hi All,
Go to Prefs > Blank Preview Image on Click > No previews shown. 

Right click the broken image and you will see it has the image url as the abbreviated location / type / size details e.g.

**/theme/img/a120xa120/**bootstrap3newpav/images/adminicons_32.png

This should be ( e_THEME_ABS/image from config file) hence /e107_themes/images/

![image](https://cloud.githubusercontent.com/assets/2847651/20483432/e82875b6-afe9-11e6-8c04-adcaed625d51.png)

Choose it and you get this in the Site Link Icon / Button pref.
![image](https://cloud.githubusercontent.com/assets/2847651/20483481/1e92944c-afea-11e6-944d-f71eadb7ad42.png)

Repeat opening in a new window and you see the incorrect path.
/theme/img/a120xa0/bootstrap3newpav/images/adminicons_32.png

I'm unclear from the code, where the muddle up is. 
Thanks
Mike

**Comment by Moc** [comment]
Sorry, I don't understand what you wrote. 

In your title: 
> has DB details as file path

What DB details are you referring to? 

I cannot reproduce the broken images at all, and I am not sure how they got there for you in the first place. I see you created a new theme "bootstrap3newpav". If you remove this theme temporarily by FTP, does the issue then disappear?

**Comment by MikeyGMT** [comment]
I was referring to the code and the HTML output. It does not make any sense to me either. Custom theme is only on the front end. Back end is latest git bootstrap3 standard. The point is ALL the images have the broken link.  Wherever they are located are not being displayed and have this weird meta data format in the HTML output... hence the dimensions are in this faux path.   

Look at another upgraded test site - hardly used for anything. The images seem to have weird abbreviated path. 

![image](https://cloud.githubusercontent.com/assets/2847651/20590011/3f90d4d0-b218-11e6-9707-7c3dcd5dc9fa.png)

I believe data path comes from admin/image.php. 
![image](https://cloud.githubusercontent.com/assets/2847651/20589967/ca46ae3e-b217-11e6-8871-319ff449a2cf.png)

The front end seems to behave itself. The little hit logo is neatly displayed top left. 
![image](https://cloud.githubusercontent.com/assets/2847651/20590160/650123cc-b219-11e6-8b96-f22a1540d127.png)

Although every time I sync with git, the e107/images/logo.png gets overwritten and the logo on the front end goes to default.
Aha ... 
![image](https://cloud.githubusercontent.com/assets/2847651/20590626/23838ea0-b21c-11e6-95e1-57fdf2d9fbb0.png)

Check pref editor... 
![image](https://cloud.githubusercontent.com/assets/2847651/20590672/74b19a2e-b21c-11e6-8753-ab32c2c87068.png)


Then go to prefs and we see this. 
![image](https://cloud.githubusercontent.com/assets/2847651/20590205/aea3617a-b219-11e6-946d-d7fc8268ee39.png)
And in the image picker we can see in the source {e_THEME} shortcode. 
![image](https://cloud.githubusercontent.com/assets/2847651/20590296/33f22a96-b21a-11e6-9942-79a031d6cd20.png)

Open the Prefs picker in debug mode and in a new window and you can see different values which I think it is gonna pass back to the pref. 

![image](https://cloud.githubusercontent.com/assets/2847651/20590500/524abbd8-b21b-11e6-9254-d90d4ea998af.png)


I am not clear as to why removing the custom them would be relevant... But I will do it and report back.  
 
![image](https://cloud.githubusercontent.com/assets/2847651/20590544/a3a82eac-b21b-11e6-8d6f-3c652ce48e4f.png)

There we are.

**Comment by MikeyGMT** [comment]
Let's check what's in Media Manager - filter on logo.png

![image](https://cloud.githubusercontent.com/assets/2847651/20590806/3f71f97a-b21d-11e6-9623-0af462f36c94.png)

Check our nplsc logo. 

![image](https://cloud.githubusercontent.com/assets/2847651/20590775/0183c6e8-b21d-11e6-9b9d-db4f403fa059.png)

**Comment by MikeyGMT** [comment]
Debug bit of code shows what the 4 boxes at the bottom of the picker are
![image](https://cloud.githubusercontent.com/assets/2847651/20591283/a72e94a4-b21f-11e6-80d1-823020e6520e.png)

![image](https://cloud.githubusercontent.com/assets/2847651/20591289/b40805b6-b21f-11e6-900c-510b312a0245.png)

**Comment by MikeyGMT** [comment]
Image selection is no better in edit news - on this site, one of my oldest sites, maybe as old as e107 itself.  
![image](https://cloud.githubusercontent.com/assets/2847651/20591491/b10e7812-b220-11e6-9fa1-43efc8f7a0a6.png)

**Comment by MikeyGMT** [comment]
Console in the Media Manager... 

![image](https://cloud.githubusercontent.com/assets/2847651/20601547/17969422-b251-11e6-9227-b45de6e00523.png)

Starting to debug this.

**Comment by MikeyGMT** [comment]
OK so this seems to be a problem with PHP 5.3 - Upgraded the site PHP software and the media manager displays images in Prefs and the media manager.
