### ISSUE TITLE
Sub forums when using legacy URL's

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2053]
So, a member reported a forum issue to me today. I believe it is an issue related with SEF URL's.

If you are on forum.php and click the sub forum everything works nicely
If you click on the parent forum so you are on forum_viewforum.php and then try to click the sub forum you get 404'ed. The URL it tries sending you too is a massive URL with loads of information that doesnt point to the right folder it tries going forum/forum/view?forum blahblah instead of e107_plugin/forum etcetc

I am not sure if this is a standard issue or if it arose when I tried playing about with SEF URL's (SEF URL's are currently back to being disabled as I can’t get them to work properly)

**Comment by CaMer0n** [comment]
To use SEF-URLs, you MUST have SEF-URLS defined for each forum in the admin area. 

For the broken legacy links, are you referring to the sub-forum link in the breadcrumb at the top?

**Comment by Aaronsss** [comment]
With regard to SEF URL's none of them work on my site even after setting modrewrite on in the htaccess file. Any SEF URL not just forum ones will 404 me.

The biggest problem is the forum, its not the breadcrumb thats broken its the main link inside the parent forum that doesn't work. Feel free to see it yourself:

http://sto-gaming.org/p/forum/forum.php

**Comment by rica-carv** [comment]
@Aaronsss Well, i just browsed your forum, and all links work.... Wich webbrowser are you using? Don't tell me it's IE???

**Comment by Aaronsss** [comment]
Firefox & chrome give the same results and a number of people reported it to me too. I think you missed it. Go to this link http://sto-gaming.org/p/forum/forum_viewforum.php?id=6 and try opening one of the sub forums.

**Comment by rica-carv** [comment]
Got it.
There's a bug on the shortcode.
Exterminator on the way....

**Comment by Aaronsss** [comment]
The forum folder is almost the latest on github except for the change cameron did which is mentioned above.

**Comment by rica-carv** [comment]
I'm not using SEF, so it might be really the issue here...

**Comment by Aaronsss** [comment]
I did just try with the latest forum files. It makes no diffrence. I also tried clearing the site cache this had no impact.

**Comment by Aaronsss** [comment]
```
function sc_sub_forumtitle()
		{
			$forumName = e107::getParser()->toHTML($this->var['forum_name'], true);
			return "<a href='" . e107::getUrl()->create('forum/forum/view', $this->var) . "'>{$forumName}</a>";
		}
```

Should $this->var not be $this->var['forum_id'] with a few other tweaks in that command? I have currently bodged it on my site to use 

`return "<a href='". e_SELF ."?id=".$this->var['forum_id'] . "'>{$forumName}</a>";`

That works fine but its not very elegant :)

**Comment by Moc** [comment]
> Any SEF URL not just forum ones will 404 me.

This indicates a sidewide issue, possibly caused by an incorrect .htaccess or server configuration.

> even after setting modrewrite on in the htaccess file.

Just to make sure, please download the latest e107.htaccess and replace your current .htaccess file with this one.

**Comment by rica-carv** [comment]
@Aaronsss When i first stated above that it was a bug, i though the problem was in the shortcode, but after some tests, i see it was not.
Anyway, if i recall correctly, that shortcodes was coded after the old forum vars code, and the only change was to make a shortcode of it, but guess only @CaMer0n can shed some light on how was the old code, so we can match the diferrences between the shortcode and the old code...

**Comment by Moc** [comment]
@rica-carv @Aaronsss The current shortcode uses the new `e107::getUrl()->create()` which should automatically create SEF URLs when applicable, but it should also generate non-SEF URLs correctly when a user has decided not to use SEF URLs. Now that I am looking through the Admin Area, I am currently not seeing the options that were there before to disable friendly URL.... I guess this has changed.

@CaMer0n Is it still possible to enable/disable friendly URLs for specific parts/plugin, e.g. forum?

**Comment by Aaronsss** [comment]
As a note I did get SEF URL's working thanks Moc. However the issue still happens even with SEF's enabled it tries to run the same URL

**Comment by CaMer0n** [comment]
Anything using `e107::getUrl()->create()` inside the forum code needs to be upgraded to use `e107::url('forum') `etc. 
@Moc No, there's no switch for plugin-specific SEF URL enable/disable at the moment.

**Comment by CaMer0n** [comment]
Untested, but please see if this last commit helps.

**Comment by Aaronsss** [comment]
The latest commit has fixed the issue thanks & closing :)

**Comment by CaMer0n** [comment]
Thank you @Aaronsss for all the valuable feedback! :-)
