### ISSUE TITLE
question how to set plugin page theme layout during plugin installation

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2054]
Is possible somehow to set for plugin theme layout?  Maybe in plugin_setup?
I would check if theme layout with name 'full-width' or 'full' is existing and then add plugin page to it. 
If not, warning would displayed about to set full layout manually. 
Where to look? Thanks

**Comment by CaMer0n** [comment]
In plugin_setup you can do whatever checks you like.

**Comment by Jimmi08** [comment]
Nice, where is clear now. I supposed to use sitetheme_layouts pref, but it's sitetheme_custompages pref too.
