### ISSUE TITLE
How to set a "scope" for Github provider in HybridAuth?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2055]
I enabled Github Auth, but it creates accounts without email address because of missing "user:email" scope. How can I set it without modifying core file:

https://github.com/e107inc/e107/blob/master/e107_handlers/hybridauth/Hybrid/Providers/Github.php#L15

If I am not wrong, it should be set in this constructor:
https://github.com/e107inc/e107/blob/master/e107_handlers/user_handler.php#L1102-L1119

Can I alter Hybrid Auth config somehow?

**Comment by lonalore** [comment]
Btw it's unable to save usersettings without email... email field is missing completelly:

![kepernyokep_2016-11-26_12-49-28](https://cloud.githubusercontent.com/assets/6043821/20640163/51d0f934-b3d7-11e6-80d3-32228aa2b453.png)

**Comment by lonalore** [comment]
@CaMer0n  Can I create a pull-request with these shortcode modifications?

Of course we can use `$options['disabled'] = true;` instead of `$options['readonly'] = true;`. But in that case need to change `usersettings.php` too.

**Comment by CaMer0n** [comment]
Yes thanks. Okay for the pull-request. 👍  For the 'scrope' please see social/admin_config.php - we could consider adding a form field for 'scope'.

**Comment by lonalore** [comment]
Tested on my website. Works properly! And the admin looks like this:

![kepernyokep_2016-11-30_19-24-59](https://cloud.githubusercontent.com/assets/6043821/20765736/eeff1efc-b733-11e6-9af8-7d225bbeb0bd.png)
