### ISSUE TITLE
multilan param question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2057]
I have plugin when I want to have some prefs multilan. So I set 'multilan'=>true in admin_config.php.  But if I use it on one language site (just English), it doesn't work. Prefs are empty. After remove this setting, prefs are back. 

Am I missing something here?
`'data' => 'string', 'multilan'=>true, 'writeParms' => array('size'=>'block-level'),`

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please try again.

**Comment by CaMer0n** [comment]
Closing, but please reopen if necessary.
