### ISSUE TITLE
Question: Is there a way to switch Banner & Site Name

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2058]
ATM the Site Name would be shown on every page at the top left and the banner on the top right - is it easy to switch them?

**Comment by Moc** [comment]
This type of questions (not related to coding or development) should be placed on e107help.org. Just an advice for the next time :) 

- You can change the 'contents' of the sitename and banner through the `Admin Area > Preferences >  Site Information` section: `Site Name` and `Site Logo`

- If you completely want to remove them, you would have to edit the theme. In case of the default `bootstrap3` theme you'll need to edit the `e107_themes/bootstrap3/theme.php` file. Look for the `{SITENAME}` shortcode.

**Comment by chimcen** [comment]
> If you completely want to remove them or change their position, you would have to edit the theme. In case of the default bootstrap3 theme you'll need to edit the e107_themes/bootstrap3/theme.php file. Look for the {SITENAME} shortcode.

this was i'm searching for - thank you :)
