### ISSUE TITLE
Question: How is it possible to change default behavior on e.g. pages-update

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2061]
Hi,
how is it possible to change default behavior on e.g. pages-update? This means, if i'm change e.g. a custom page within admin menu that i don't go back to admin main menu.
At the end of editing screen i can choos the behavoir - but how can i change the default value from
"go to list" to "edit current"?

![edit_default](https://cloud.githubusercontent.com/assets/22658487/20604714/16022038-b268-11e6-8d49-ceb21fa1d556.JPG)

**Comment by Moc** [comment]
I think at the moment this is not possible, although if I remember correctly, @lonalore made some adjustments or flexibility improvements here? Maybe he can elaborate. I may be wrong though haha.

**Comment by lonalore** [comment]
You can do it with `e_admin.php` addon file in a custom plugin. But this requires basic programming skills. Just create a custom plugin, and create `e_admin.php` file in its folder with these contents:
```php
<?php

/**
 * @file
 * Addon file to hook into Admin UI.
 */


/**
 * Class YOURPLUGINNAME_admin.
 */
class YOURPLUGINNAME_admin
{

	/**
	 * Extend Admin-ui Parameters.
	 *
	 * @param object $ui
	 *  Admin UI object.
	 *
	 * @return array
	 */
	public function config($ui)
	{
		// Event name, e.g: 'wmessage', 'news' etc. (core or plugin).
		$type = $ui->getEventName();

		switch($type)
		{
			case 'page':
				$ui->setDefaultAction('edit');
				break;
		}
	}

}

```

**Comment by chimcen** [comment]
Ok, sounds not as easy as supposed... :(
But thanks for that - is for me atm to much (not skilled as you)

**Comment by lonalore** [comment]
Here you are. :) Just...

- Unzip it
- Copy plugin folder to your e107_plugins folder
- Install it

[customization.zip](https://github.com/e107inc/e107/files/614603/customization.zip)

**Comment by chimcen** [comment]
Awesome - works.
But how i now the event name of every site where i would use this? (e.g. for media manager)?

If i change `case 'page':` to `case '':` this addon works for all sites in admin menu only or for the whole site (including frontend)?

**Comment by lonalore** [comment]
Change `case 'page':` to `default:` and the "edit" will be set for each (Admin UI) form. There is no Admin UI on the frontend.

**Comment by chimcen** [comment]
Perfect! 
![youare](https://cloud.githubusercontent.com/assets/22658487/20651760/271193ec-b4eb-11e6-8fe2-88465f401bf1.gif)

**Comment by CaMer0n** [comment]
@chimcen You would like your entire admin area to always default to 'Edit Current' ?

**Comment by chimcen** [comment]
Normaly not - but i don't now all the page names i've want to - e.g. the media manager - all i've tryed didn't work at all...
I need only for:
- Pages/Menu List = "page"
- Newslist              = "news"
- Medai Manager  = "???"

**Comment by Moc** [comment]
> but i don't know all the page names i've want to

Change 
```php
$type = $ui->getEventName();
```
to
```php
$type = $ui->getEventName();
print_a($type);
```

Then a new box should appear on every admin page with the names you need. 
After you found the names, either delete the newly added line or comment it out ( by putting `//` in front of the line)

**Comment by chimcen** [comment]
Thank you, this works - but not at every admin page there will be shown a extra box... e.g. on news list page  or pages menu (and some others) it works, but on media manager there will be shown nothing... :(

news menu:
![news](https://cloud.githubusercontent.com/assets/22658487/20677284/ddf27b4c-b592-11e6-8b38-8995e238be85.JPG)


media manger:
![mediamanager](https://cloud.githubusercontent.com/assets/22658487/20677293/e6ef8c3a-b592-11e6-9b7f-5f8fbf066b25.JPG)


It only works on the following pages:
ban
user
download
news
page
wmessage
comment

**Comment by lonalore** [comment]
Media Manager does not use `eventName`. Try to use `tableName` instead:

```php
$table = $ui->getTableName();

switch($table)
{
	case 'news': // News.
	case 'page': // Pages, Menu.
	case 'core_media': // Media manager.
		$ui->setDefaultAction('edit');
		break;
}
```

**Comment by chimcen** [comment]
works! :) thank you :)

**Comment by CaMer0n** [comment]
@lonalore @chimcen I'm just wondering if we should have a core pref to set the default throughout the entire admin area?

**Comment by Moc** [comment]
I doubt many people will change the default option to be honest. But hey, I'm generally positive towards customisation possibilities 👍

**Comment by lonalore** [comment]
It is already quite complicated to use the Admin UI. Quite complex. In my opinion it's not necessary to provide a core pref for each of these kinds of small customizations. Maybe a core plugin for it?

**Comment by Moc** [comment]
I agree. Maybe one customisation plugin where more advanced options can be selected.
