### ISSUE TITLE
Some people met with white screen after attempting to login

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2062]
I have reports now of two individuals who are unable to login on the site. They are met with a white screen after clicking login and are not logged in. What I / they have tried:

* They have tried using both firefox and chrome
* They have cleared cache and cookies
* One guy tried it on 4 diffrent PC's
* I cleared site cache
* I changed one of the user accounts passwords and managed to log in with it fine myself

I just cant think what else is causing it its strange that its only some users and that others can log in with the account.

**Comment by tgtje** [comment]
Similar to #1870 ?

**Comment by Aaronsss** [comment]
Potentially but I am unsure, sorry I meant to update this last night. I believe I have discovered the issue. The users IP's were banned for too many login attempts. Originally, I had assumed this not to be the case as the 'Banned users' section in the status menu in the admin area said there are 0 bans and also the users could still see the site as a guest. Is it worth having that menu fixed and potentially the ban thing too or is that intentional?

**Comment by Moc** [comment]
>  I believe I have discovered the issue. The users IP's were banned for too many login attempts.

> Is it worth having that menu fixed and potentially the ban thing too or is that intentional?

If being banned is indeed the cause for the blank page behaviour, then this needs to be fixed. Especially if you can still visit as a guest. Testing required to see what exactly happens and see what improvements need to be made.

**Comment by CaMer0n** [comment]
Please add define('e_DEBUG', true); to your e107_config.php file. Does it display any messages (other than a white page) ?

**Comment by Aaronsss** [comment]
No debug information is displayed when trying to login through the bootstrap menu or the login.php page.

@CaMer0n I have messaged you about it on Gitter.

**Comment by CaMer0n** [comment]
If there are no ban messages.. one needs to enter some here (if they desire)
/e107_admin/banlist.php?mode=main&action=times

**Comment by cainey** [comment]
I have this issue @ [#2275](https://github.com/e107inc/e107/issues/2275) i did the debug and it just say you ip is banned

**Comment by MikeyGMT** [comment]
One of my sites saying the same .... I appended the filename it was looking for: cache/banactions.php 
There isn't one. I could not find my IP in the other two banlist files or the table either. 
The filename appears to come from 
iphandler_class.php line 92 
const BAN_FILE_ACTION_NAME	= 'banactions';	
#1975 suggests that banactions is incomplete.

**Comment by MikeyGMT** [comment]
I got e107 to show my IP by adding this after line 177. 
echo ($this->ourIP); 
Commented my IP from the banlist table and the two ban files in the system/a1B2c3/cache folder.

I suspect logged in using a browser saved old password. I reset my password in the database - using the md5 action. Then re-logged in and updated the password.  All working.

**Comment by Moc** [comment]
@Aaronsss Is this issue still happening?

**Comment by rwjework** [comment]
Still happening with me. I have just downloaded the GIT version. I can log in on any other IP address apart from the one I did the update on. I did not want to remove the banlist which has 550 other entries. Any suggestions as to a quick fix?

**Comment by Moc** [comment]
I am assuming this issue is fixed. If not, please let me know and I'll re-open.
