### ISSUE TITLE
[Question] Manually checking menu visibility with SEF on/off....

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2067]
I know (or at least think i know... i might even be wrong, but correct me if i'm...) that the visibility menu check is donne by the [IsVisible function](https://github.com/e107inc/e107/blob/74221c1cd518ea646eb59ba92761f02bfc20e5f7/e107_handlers/menu_class.php#L312).

My question is how can i use this function to check a menu visibility agains original page php filename, when SEF is enabled.
For instance, a SEF url (for example: `www.site/forum/viewtopic`) calls the same file as the normal url (for example:` www.site/e107_plugins/forum/forum_viewtopic.php`) does, right?
So how does the menu visibility check deals with it? What names should i put on the menu visbility, besides for instance `forum_viewtopic.php`?

**Comment by Moc** [comment]
@rica-carv Have you already found the answer in the mean time?
