### ISSUE TITLE
list_new list.php?new not returning any new items

### ISSUE THREAD

**Issue by VR6Pete** [e107inc/e107#207]
I have created the following:

New Comment
New Forum Post 

None of these show in list.php?new  

However new chat box posts does show.

I've yet to test New Events, New Downloads, New News etc.... 

There is also the SQL error below noted with debug on...

SQL Analysis

1 Query Errors! 
Index Query / Error 
52  SELECT tp.thread_name AS parent_name, tp.thread_id as parent_id, f.forum_id, f.forum_name, f.forum_class, u.user_name, lp.user_name AS lp_name, t.thread_id, t.thread_views as tviews, t.thread_name, t.thread_datestamp, t.thread_user, tp.post_thread, tp.post_user, t.thread_lastpost, t.thread_lastuser, t.thread_total_replies FROM `vr6oc_forum_thread` AS t LEFT JOIN `vr6oc_forum_post` AS tp ON t.thread_id = tp.post_thread LEFT JOIN `vr6oc_forum` AS f ON f.forum_id = t.thread_forum_id LEFT JOIN `vr6oc_user` AS u ON tp.post_user = u.user_id LEFT JOIN `vr6oc_user` AS lp ON t.thread_lastuser = lp.user_id WHERE find_in_set(forum_class, '4,2,3,5,6,7,8,9,11,12,13,15,16,17,18,19,1,21,253,254,250,251,0') AND t.thread_lastpost > 1367573080 ORDER BY tp.post_datestamp DESC LIMIT 0,50  
Unknown column 'tp.thread_name' in 'field list' 

All items appear to load on "list.php" to view "Recent Activity" 

Thanks.

Pete

**Comment by Jimmi08** [comment]
@CaMer0n this can be closed. Tested with forum and news. I will create new issue if I find problem.
