### ISSUE TITLE
[Question] How to add a "dynamic" pull down submenu on navbar?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2072]
How can i add a "dynamic" pull down submenu to the site navbar navigational menu, at theme level?
For instance, something like this:
Forum
   - Forum 1 (visible to all)
   - Forum 2 (visible to users)
   - Forum 3 (visible to admin)
....

When i say "dynamic" i'm telling that the dropdown menu descriptions should come from the forums table (ie, the forums names itself!)
And don't tell to simply copy and paste the forum descriptions to the menu admin, since it's a bit "stupid" and not very "straight forward", since it's unecessary work duplication and adds some more error chances when manually creating the menu.
Further more, if more forums are created, the submenu has to be manually updated accordingly....
Is there a way that the dropdown/submenu can fetch its data automatically form the forum table, for instance?

**Comment by Moc** [comment]
You are referring to new 'Sitelinks' in the navigation area's right? 

As of yet, I think this is not possible. Listed as enhancement for future consideration.

**Comment by rica-carv** [comment]
I'm refering to the sitelinks generated by the {NAVIGATION} shortcode...

Well, if for now it's not possible, i'll try a "mock up" myself...

**Comment by Moc** [comment]
Yep those are the 'Sitelinks' in e107 terminology :) (Admin Area > Settings > Site Links)

**Comment by rica-carv** [comment]
Ok. 😆 
I think i can do it via the theme override shortcodes....

**Comment by rica-carv** [comment]
Well, i already have de data there, but now the question is the html coding... 😞

**Comment by rica-carv** [comment]
After some "battles", got it working....
