### ISSUE TITLE
Mailto link to website admin on registration page

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2074]
Is there a way to remove the mailto link to website admin on registration page? Or better, to replace this mailto link with link to contact form within e107v2?
![registration_mailto](https://cloud.githubusercontent.com/assets/22658487/20652486/97cfdef4-b4fa-11e6-92ec-c3494eba469f.jpg)

**Comment by tgtje** [comment]
core/templates/signup template line 194.
But remember : each update WILL overwrite the change you make.

**Comment by Moc** [comment]
It's a template so you can simply override it, which keeps the changes even if you update it. 

See the documentation on e107.org about overriding core templates.

**Comment by chimcen** [comment]
Thank you. Thats what i'm searching for. Yes, i know. I have many changes like this ;)
