### ISSUE TITLE
[Feature request] - possibility to use new admin_ui() with old admin_menu.php for menus

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2075]
With just partially updated old plugins it would be handy have both menus ways available. 

Now sc_admin_menu() ends when finds e107::getAdminUI();  and existed admin_menu.php in plugin folder is ignored. 

If I commented these 2 lines in admin_shortcodes.php, it works.

```
		// SecretR: NEW v0.8
		$tmp = e107::getAdminUI();
		if($tmp)
		{
			ob_start();
			$tmp->renderMenu();
			$ret = ob_get_contents();
		        //ob_end_clean();
			//return $ret;
		}
		unset($tmp);
```

Thanks. If there is reason for this, I am able to do it other way.

**Comment by CaMer0n** [comment]
Best way is to add renderMenu() to your admin-ui.

**Comment by Jimmi08** [comment]
Not needed anymore
