### ISSUE TITLE
ENHANCEMENT: Display System Last Updated Date (Git Sync Date) in About>PHP / Credits > Site Info Block

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2076]
Hi All
It would be handy to know when the last upgrade date was, or sync with git date. 
About>PHP / Credits > Site Info Block. 
A pref would be best but something like this could work too. It's not code for release obviously ... 
![image](https://cloud.githubusercontent.com/assets/2847651/20666925/96b4aa90-b55e-11e6-8b71-d52edbc6411d.png)
Any thoughts on this?
Thanks 
Mike

```
			if ( strpos($e107info['e107_version'], '(git)')>0 ) {
				echo "Last modified: ".date("F d Y H:i:s.",filemtime("index.php"));
				//echo ('Git Date Stamp'.filemtime("e107_system/a9b8c7/temp index.php") );
			}
```

**Comment by CaMer0n** [comment]
Done, but will only be seen by serious devs who used git to installed e107. ;-) (see e107.org)

**Comment by MikeyGMT** [comment]
Wow that was quick thanks :)
I use tools-db-sync with git. Tyre kicker helper ;)
Is there another method to sync then? 
Don't think this file is copied. 

$gitFetch = e_BASE.'.git/FETCH_HEAD';

**Comment by rica-carv** [comment]
@Cameron "Done, but will only be seen by serious devs who used git to installed e107. ;-) (see e107.org)"
Well, that excludes me....

@MikeyGMT That file is not copied because you might not be using git, just github, as it happens to me...

@all Why not use` $gitFetch = e_BASE.'.gitignore'; `instead? Or another ideia, when a user makes the update from the admin area, why not create that `.git` file, if it doesn't exists?

**Comment by Moc** [comment]
I agree with @rica-carv, there are many people using the update functionality while running on shared webhosting platforms with no possibility to use git functionalities. Those users are actively developing for and contributing to e107.

**Comment by CaMer0n** [comment]
@Moc Yes, it was a joke.. but I would like to see more of us using GIT like this - it's far more efficient. 
I have a few sites running on hostgator shared-hosting and they do provide shell access allowing for a git install.

**Comment by Moc** [comment]
I don't disagree, but the far majority of shared webhosting platforms currently simply do not allow for this option even though cPanel carriers the functionality.

**Comment by rica-carv** [comment]
@CaMer0n Sorry, but i simply can't use git.
I'm running a localhost server from a encrypted usb pen drive, so adding git will slow it more down....
Anyway, my live server is a free one, so many options are bare minimal....
I know git is more efficient, but right no is not a real pratical option for me...

**Comment by MikeyGMT** [comment]
:) Good Morning! This conversation made me smile :) 

Personally I seem to get in a muddle with command line git, and it does horrific unexpected weird things for me... Suspect I am better I stick to the comfy gui tools, for the bit of tinkering I do around the edges of the core development. I'm quite happy to do minor bug fix, lans, other maintenance and small repetitive type of tasks, rather than core major dev work at this stage. 

Anyway, these new features are great for non-dev e107 site admins and specifically I am thinking of folk who just want to help a friend with a web presence and have little or no interest in writing their own code. They are very likely to use the Admin Tools > DB > Git Sync Function, because it's quicker to use the core UI to run and maintain a site, rather than faffing about with ftp. For these people, remembering git commands you may use once a quarter or year is a big ask and risk. If you maintain a number of sites, then using the built in features it's ideal and quicker even than using cPanel, as are the theme and plugin download/install features within admin, which seem to work more consistently now at least for PHP 5.6. 

Thinking about that, it may be better for the Git Sync feature to live in the file inspector than in DB tools, I think someone mentioned that in another thread. 

I guess it would be useful for diagnosis in support too. 

Just saying, it maybe useful to show either value if present.

**Comment by CaMer0n** [comment]
> For these people, remembering git commands you may use once a quarter or year is a big ask and risk. 

Actually @MikeyGMT , there's nothing to remember. Once you install via git, everything else is performed via the admin area. So, we're talking about a one-time use of the following commands: 

    cd youraccount (eg. where 'youraccount' is the folder above your public_html folder)
    git clone https://github.com/e107inc/e107.git public_html	

Then, install e107 as usual. 
When the `.git` folder is detected in the home directory, the Git-sync option becomes available here: 

![github-update](https://cloud.githubusercontent.com/assets/2825679/20773402/779acfb4-b706-11e6-803f-2e017496d8f0.png)

Click the "Run" button and it downloads ONLY the files that got modified. (not the entire zip as the other method does) . It also displays the files that were replaced. 

I suck at command-line git, so if I can do it, I'm sure at least some of you guys can. Happy to help if you want to experiment on a server you have access to.

**Comment by MikeyGMT** [comment]
Thanks @CaMer0n. 
Wow another part of e107 I wasn't aware of! I have not looked at the Scheduled Tasks area for ages. Brilliant. I've been using Dev Mode + DB > Sync with Git and before that was working for me faffing about with upload, unzip, move files etc in cPanel File Manager. I'll certainly have a play around. 

Personally, I'm just about OK with command line, but only when regularly using commands I have clear understanding of what they do. Git processes / workflows lose me completely, git help is very convoluted.

**Comment by rica-carv** [comment]
Well, i keep saying, both options should be available.
For instance, why not a fallback, if git is not detected on the server?
That way, it would cover all the update options (git, github, ftp, etc...)...

**Comment by MikeyGMT** [comment]
Working with .git folder installed on server
