### ISSUE TITLE
Submit News

### ISSUE THREAD

**Issue by Worldwide7477** [e107inc/e107#2078]
When submitting news it does not go through it shows error:
"Warning Error uploading image"
When i'm not uploading a image? below is the debug from e107 debug.

![submit news tricitytorrents  #1](https://cloud.githubusercontent.com/assets/20016207/20695510/a561c1b6-b5ba-11e6-919c-b6c4c9dd4b7b.png)

![submit news tricitytorrents](https://cloud.githubusercontent.com/assets/20016207/20695485/5b58c632-b5ba-11e6-8cb3-be3982b433c2.png)

Any help on this would be great thanks in advance.

**Comment by chory** [comment]
I do not select any image to load and I get the same error, and ```Undefined index: submitnews_media, Line 390 of /home/xxx/yyy/clan-toro.es/submitnews.php```

**Comment by Jimmi08** [comment]
I think that problem is here:

```
		// ==== Process File Upload ====
		if (FILE_UPLOADS && !empty($_FILES['file_userfile']) && vartrue($pref['subnews_attach']) && vartrue($pref['upload_enabled']) && check_class($pref['upload_class']))
		{
			$uploaded = e107::getFile()->getUploaded(e_UPLOAD, 'unique', array('file_mask' => 'jpg,gif,png', 'max_file_count' => 3));

			if (empty($uploaded)) // Non-specific error
```

There is test:  !empty($_FILES['file_userfile'])    but $_FILES is array, so its not empty. 
 
![image](https://user-images.githubusercontent.com/5429548/30539529-2736965e-9c73-11e7-9563-3b9a405265b2.png)

**Comment by CaMer0n** [comment]
@chory Please try the updated file. Thank you @Jimmi08

**Comment by chory** [comment]
OK thanks, works fine

**Comment by Jimmi08** [comment]
No problems with php5. No blank page.

**Comment by CaMer0n** [comment]
Thank you both.

**Comment by chory** [comment]
I will try with php5

**Comment by rica-carv** [comment]
Clean caches (E107 admin area & browser), and try again, please...

**Comment by chory** [comment]
It's done
Everything remains the same

**Comment by CaMer0n** [comment]
A white page represents an error. Please check for error_log in the root directory.

**Comment by Moc** [comment]
> A white page represents an error. Please check for error_log in the root directory.

Or in your Apache error log through the webhosting control panel

**Comment by chory** [comment]
No log file, or empty file

**Comment by chory** [comment]
[Solved]
I activated **display_errors** in server and show me error in  _ /e107_languages/Spanish/admin/lan_newspost.php on line 142_

**Comment by CaMer0n** [comment]
@chory Is it a problem in the official v2.1.6 language pack? ( @Norwayman )

**Comment by bportotrix** [comment]
Yes, Solved removing the excess "" on 142 line
