### ISSUE TITLE
List_New "headers not expanding / collapsing

### ISSUE THREAD

**Issue by VR6Pete** [e107inc/e107#208]
When attempting to expand / collapse a section I.E Forum Posts, Downloads etc... 

It doesn't do anything.

The following error is displayed in the console:

SCRIPT5022: Syntax error, unrecognized expression: #[object HTMLDivElement] 
jquery.min.js, line 2 character 59313

**Comment by Jimmi08** [comment]
@CaMer0n this can be closed. If sections are hidden and they have no caption (nowhere to click), it doesn't work, otherwise it does. Tested on Recent page.
