### ISSUE TITLE
Wrappers not working on forum_post.php

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2080]
Template wrappers doesn't works on forum_post.php template (forum_post_template.php)

Tried this, with no luck:
`$SC_WRAPPER['FORUM_POST_AUTHOR'] = "<div class='form-group'><label for='name' class='col-sm-3 control-label'>".LAN_FORUM_3010."</label><div class='col-sm-9'>{---}</div></div>";`

`$FORUM_POST_WRAPPER['form']['FORUM_POST_AUTHOR'] = "<div class='form-group'><label for='name' class='col-sm-3 control-label'>".LAN_FORUM_3010."</label><div class='col-sm-9'>{---}</div></div>";`

**Comment by tgtje** [comment]
Oops, you asked this a long time ago with no answering back #183

**Comment by CaMer0n** [comment]
@rica-carv Please update and re-test.  (I didn't test wrappers, just that the page still loaded correctly)

**Comment by CaMer0n** [comment]
btw. If this works well, I believe we should update the other forum scripts so they do a similar check, instead of checking for Bootstrap as it does now.

**Comment by rica-carv** [comment]
@tgtje I've already reported that, but at that time, i was not yet knowing the forum_post issue, but thanks anyway. As it seems, all the forum code needs a lot of cleanup & optimization...

@CaMer0n It works, at least for me. Thanks. Now, with the wrappers working, we can get rid of those extra "label" shortcodes...
