### ISSUE TITLE
FEATURE REQUEST: Option to NOT delete language files when uninstalling a plugin

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2082]
I would really like to have the option of NOT deleting language files when I decide/need to to uninstall a plugin for some reason. I use quite a bit of time in translating to Norwegian and Spanish, and when I need to uninstall a plugin I lose all these translations that I made if there has not been a backup of some sort. So, please, just like one has the option of deleting plugin files ON/OFF, I would sure like to have the option of deleting language files ON/OFF.

**Comment by CaMer0n** [comment]
@Norwayman Normally you can delete a plugin without deleting the files?

**Comment by Norwayman** [comment]
@CaMer0n Yes, I am aware of that, but sometimes one would want to delete all the files EXCEPT the language files because one has used hours translating them.

**Comment by rica-carv** [comment]
@Norwayman And using FTP?

**Comment by MikeyGMT** [comment]
Think about sharing translated files to a repo.

**Comment by Norwayman** [comment]
@rica-carv Yes, there are many ways of doing things. Just that it is a lot easier for an admin if everything is in one place, and not needing to open up other programs to do things. This is always my opinion.

**Comment by Moc** [comment]
Going to close this old issue :) See alternatives listed in the comments.
