### ISSUE TITLE
'user_xup_login' event is not triggered?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2083]
I use Github authentication on my website, and I want to store/update Access Token when a user logs in... but 'user_xup_login' event is not triggered. :/

I use the new `e_event.php` addon file for registering my event callback functions (other events are triggered, so the addon file works properly):
```php
class PLUGIN_event
{

	function config()
	{
		$event = array();

		$event[] = array(
			'name'     => 'user_xup_login',
			'function' => 'PLUGIN_user_login_callback',
		);

		return $event;
	}

	function PLUGIN_user_login_callback($data)
	{
		e107::getLog()->add('XUP_LOGIN', (array) $data);
	}
}
```

**Comment by CaMer0n** [comment]
Please feel free to add it where it needs to go. 

	e107::getEvent()->trigger('user_xup_login', $userdata);
