### ISSUE TITLE
Feature Request: Ability to delete more than 10 failed logins

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2087]
Only being able to delete 10 failed logins at a time is annoying. Is there the possiblity to delete all fail logins or change the amount displayed to be user selectable allowing greater amounts of deletions.

**Comment by chimcen** [comment]
Change this Line `protected $perPage = 10;` in e107_admin/banlist.php to your desired list-lenght.
E.g. changing to 50 will display 50 entries per page.

But remember - every e107v2 update will remove this setting and you have to change this again...

**Comment by rica-carv** [comment]
Maybe a good time for a preference setting for this value, no?

**Comment by CaMer0n** [comment]
Done 👍
