### ISSUE TITLE
[Question] Frontpage directing doesn't work as it should

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2090]
Hi,

i've defined in admin section "frontpage" a homepage and a post-login-homepage.
In my case the welcome-page "index.php".

But it doesn't work - in all cases i'll rooted to the root dir of my page without any *.php page.
Also the same when clicking the homepage-button in admin area - i wouldn't be rooted to index.php.

Only when i'm loggin in as "normal member" i'll rooted to index-php - when i'm loggin out the rooting to index.php doesn't work anyway...

Any ideas? Is it a bug or a faulty setting of mine?

![default_page_rule](https://cloud.githubusercontent.com/assets/22658487/20791840/380c5890-b7bf-11e6-9f09-20c2ce586a01.JPG)

![homebutton](https://cloud.githubusercontent.com/assets/22658487/20791848/45464b9c-b7bf-11e6-8464-d2ab68336b89.JPG)

**Comment by tgtje** [comment]
Bug (not really) bit tricky.. let me try to explain. everything does what it has to do.

Only the admin index php link (Home) is 'devious' in its way.
Index php is main page (system) where Frontpage is also 'seen as' index php
Now when you call Home (admin / Home) it will try to load index.php but hey.... it is calling the 'set' Frontpage.
Trouble is (i am no dev, nor can oversee the actual calls,arrays etc.. throughout the system) index php is in htaccess, is in class2;  is in frontpage etc... So a real answer is not for me to give.

You may 'experience' the thought behind the explanation by changing the sitelink Home to f.e. download .php.. Than do some testing.. I hope it is any clearer (hence my answer about tricky one)

**Comment by chimcen** [comment]
Ah, thank you for helping to understand this behavior - e.g. with download page all work as expected/wished...
any ideas to get this with index.php working the same way as with download.php?

**Comment by Moc** [comment]
What content would you like to display pre and post login? You should not enter 'index.php' as a front-page because it serves as a 'container' for other content such as news, or the forum, the downloads page, or whatever you want.

**Comment by Moc** [comment]
Also if the URL does not contain the /index.php, but just the domain name, it means that the website has loaded the index.php (or any index/main.php/html file. This is a special file which is loaded by default (not e107 specific but on all websites in the world using Apache and I think also IIS).

**Comment by chimcen** [comment]
In simple words: using the index.php as "normal" content website isn't a good choice? Is this right?

The desired content i would display on pre and post login page is only:
- Website Name & Banner
- A Picture Slider (will get from my theme.css)
- A menu-band with some menu's

So, nothing special. If I'm creating a new custom page and applicate my theme style there i got what i want - the only problem is: between the slider and the the menu's the custom page will create a text-area field without any text (didn't entered text) and this looks very ugly (this area isn't needed)...

**Comment by chimcen** [comment]
Can be closed.
With the hints here i got what i've searched - eventually you can correct me if i'm making totaly bull ;)

I've copied the content of online.php to a new php page and changed the content to:

`<?php
/*
+ ----------------------------------------------------------------------------+
|     e107 website system
|
|     Copyright (C) 2008-2009 e107 Inc 
|     http://e107.org
|
|
|     Released under the terms and conditions of the
|     GNU General Public License (http://gnu.org).
|
|     $Source: welcome.php,v $
|     $Revision$
|     $Date$
|     $Author$
+----------------------------------------------------------------------------+
*/

/**
 *	@package    e107
 *	@subpackage	user
 *	@version 	$Id$;
 *
 *	Default welcome page styleable with theme menu
 */

require_once('class2.php');
include_lan(e_LANGUAGEDIR.e_LANGUAGE.'/lan_'.e_PAGE);

require_once(HEADERF);
	
require_once(FOOTERF);
`
After then i've defined a theme style in theme manager to this page - et voilà :)

**Comment by Moc** [comment]
> using the index.php as "normal" content website isn't a good choice? Is this right?

The index.php file is special because it serves multiple purposes. It basically displays what you want it to display. By default is shows the welcome message. There are several set options which you can choose (e.g, showing news items, or the downloads or forum page, and so on). 

In your case, if you want to show a custom page you can either use set the frontpage to the custom page created through the admin area, OR you could use a standalone custom page like you did now. The instructions for the latter are here: http://e107.org/developer-manual/getting-started#getting-started 

```php
<?php 
require_once("class2.php");
require_once(HEADERF);
 
$ns->tablerender("Welcome", "Hello World");
 
require_once(FOOTERF);
exit;
```

**Comment by chimcen** [comment]
You're awesome - thank you.
Hopefully i didn't annoying anybody...

**Comment by Moc** [comment]
Not at all. Glad to be of help. 
It's a bit tricky and hence difficult to understand but once you grasp it, it works brilliantly :)
