### ISSUE TITLE
Emoticons button not expanding 

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2091]
It seems there is a bug with `onclick="expandit('emote')` - when i click on this button behind the emotes won't be expand - it happend nothing.

In guestbook plugin i use the same operation `onclick="expandit('guestbook_sign')` and it doesn't work as the emotes, too.

Using latest github, when i'm switching some day back to an older github version all will be workin fine...

**Comment by Moc** [comment]
Probably caused by https://github.com/e107inc/e107/commit/7f27cf5bfdf89b78b4ca35bf3d1556993e44872b

**Comment by chimcen** [comment]
> Probably caused by 7f27cf5

Indeed - i've changed line 1375 back to `var href = '';` and it works again...
Thank you.

**Comment by CaMer0n** [comment]
I have a feeling there could be repercussions to that commit. Checking..
