### ISSUE TITLE
News carousel black on page.

### ISSUE THREAD

**Issue by inferno-prime** [e107inc/e107#2094]
I was told that this mite be a bug and to post here. The footer does load I also tried another theme and got the same result.

Link for example pic. https://s15.postimg.org/hidoafysb/Untitled.jpg

**Comment by chimcen** [comment]
Tried it already with default e107v2 bootstrap 3 theme?

**Comment by inferno-prime** [comment]
Yes

**Comment by tgtje** [comment]
@inferno-prime please test with the news items ( use min 2; setting prefs accordingly >per page ex. 2)
i have no issues WHEN i select a 'thumb' image (bottom editor window) and text in item. It ( for m) will display the First text line only !! (samne for newsitem 2 in carousel) where in carousel display > at left side the thumb will appear and right side the text ( is kind of link that switches the left side content, when/or sliding is off)
2 screenshots taken during sliding (look at left side top&bottom)
![172all](https://cloud.githubusercontent.com/assets/1811857/20951281/2a455c38-bc25-11e6-8127-2b10a5917629.jpg)
the only thing not happening is when in slide the little marker line (newsitem 'link') does not follow..

**Comment by inferno-prime** [comment]
Ok I will try that and get back to you in a few days thanks.

**Comment by inferno-prime** [comment]
Alright I will be dropping this issue until it is fixed. I will just stick to using the news grid for now. I do appreciate your help on the matter and want to say thanks.

**Comment by CaMer0n** [comment]
black is just the default, but you can style it with css.

**Comment by Moc** [comment]
Not considered to be a bug. Can be styled by the theme. Black is the default.
