### ISSUE TITLE
Deactivating of extended Userfields didn't work

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2095]
Using latest Git...
In Admin menu->extended user fields->add new field i'm able to activate/deactivate them.
Activating them works, but deactivate them afterwards didn't work and causes no message - when deactivating, site will relaod, but nothing happend...

![ext_fields](https://cloud.githubusercontent.com/assets/22658487/20828021/c0a34c8e-b875-11e6-872b-69f830c33eee.JPG)

**Comment by arunshekher** [comment]
I can confirm this in fresh v2.13 test installs as well as in v1.0.2 to 2.1.3 upgraded test installs.

This is true for system UEFs as well as custom UEFs.

Tested with different browsers.
