### ISSUE TITLE
[Enhacement] parseCount core function?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2100]
Maybe not the right spot, but got a small suggestion:
There's currently some old legacy code (in themes and in core) that use this stile to show counts:` (45)`
If that code is run in a bootstrap theme, for me it's a little bit of a "spoiler", since [bootstrap has some great way to show countings](http://getbootstrap.com/components/#badges).

My suggestion is to have a core function, like a parse function, that grabs the number and formats it accordingly to the current theme format, ie:
```
if theme is bootstrap
    return number in bootstrap format
else
    return number enclosed in circular brackets (legacy)
```

Or it's a "mad" ideia?

**Comment by CaMer0n** [comment]
@rica-carv It's a good idea. And I'd prefer to not have wrappers for numbers like this. The shortcodes should just return what this function returns. No one ever said that shortcodes shouldn't return HTML. (they do all the time)

**Comment by rica-carv** [comment]
@CaMer0n But if HTML is harcoded inside shortcodes, if for some reason whe don't want the returned HTML, just the plain text string, it's one more function just to get rid of that HTML (strip_tags).
Anyway, shouldn't the HTML be supplied & managed in the template?
Just my thoughts....

**Comment by CaMer0n** [comment]
We can add parms in some cases, but there is a LOT which can be done with CSS. (Including wrapping ( ) around numbers)

**Comment by rica-carv** [comment]
Indeed, but how can this deal with old plugins / themes that still hardcode wrap numbers with ()?
