### ISSUE TITLE
Not subforum after update v1 - v2

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2101]
I updated site from Github. Forums appears, but no subforums (blank page).
Server log: 
[Sat Dec 03 10:04:22 2016] [error] [client --------------] PHP Parse error:  syntax error, unexpected '[' in /chroot/home/------/------/html/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php on line 536, referer: http://---------/e107_plugins/forum/forum.php[Sat Dec 03 10:09:27 2016] [error] [client -------------] PHP Parse error:  syntax error, unexpected '[' in /chroot/home/-------/-----------/html/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php on line 657, referer: http://----------/e107_plugins/forum/forum.php

If I delete the part of code (viewforum_shortcodes.php): 
$caller = debug_backtrace()[1]['function']; - on line 536 
$caller = debug_backtrace()[1]['function']; - on line 657
subforum appears, but no last post, this cell is empty.

**Comment by rica-carv** [comment]
Which PHP version are you using?

**Comment by fizi** [comment]
PHP Verzió
5.3.3
mySQL
5.1.73

**Comment by rica-carv** [comment]
Hum, you upgraded from v1.x to v2.
Have you copied the templates from `e107_core\templates` to `e107_themes\templates`?
Beware, if you customized the `e107_themes\templates` they'll be overwritten, so make a backup copy of them first, and afterwards replace the customization in the new template files...
Give it a try, but for now i can't remember anything more that could solve this "bug"...

Mine subforums are fully working on a clean v2 install, so i can only figure it out as old legacy code remains giving this "bug"...

**Comment by fizi** [comment]
I deleted e107/templates folder.
I made a number of unique template and I placed into my theme/templates folder.

**Comment by CaMer0n** [comment]
> Have you copied the templates from e107_core\templates to e107_themes\templates?
This should NOT be necessary. If it is, then there is a bug to be corrected. 

I suggest upgrading PHP to 5.6 (or at least 5.4)

**Comment by fizi** [comment]
Unfortunately, the service does not want to upgrade. :(

**Comment by rica-carv** [comment]
@CaMer0n 
The copy might be necessary, since i've had real issues with wrong templates from a upgrade from v1.4 to v2, and that copy process simply solve it.
@fizi Try to restore the deleted folder, just to see if it works or not.

**Comment by tgtje** [comment]
@CaMer0n @fizi  helping out here (info) as i explained earlier: these files are remnants of older versions (where v2 does not use these anymore, and these do ( in relationship with the old php (and TYPE+Myisam use  ( i know the dbase) can not handle upgrade without mistakes.... I do believe (as mentioned in last send mail) for a godd working site the php version (and sql) has to be upgraded too...
(i did transformations on sql to engine= etc..) and get good results locally.. so it all point to there..

**Comment by Moc** [comment]
@tgtje: the type to engine replacement is no longer neccesary because it is automatically replaced during the installation :)

**Comment by tgtje** [comment]
I know @Moc but Fizi sent me the existing sql file to test with... It will throw errors when using higher versions than 5.3.3 as it sees the old files... (so error stop before continuing); it will not succed to restore the forum tables correctly... It is an upgrade and server has too much influence i guess, as i can get good results with all newer versions AFter the sql file is ok.. ( i had to restore and get a first good working site on Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 to get tings going and from there upwards....

**Comment by fizi** [comment]
tgtje: I made the update how you wrote, but the subforums messages in the sql file was wrong (not full messages only part of messages was in the table). In this way I made new update, the results it is. I wrote from it the mail for you.

**Comment by tgtje** [comment]
Thanks, just rerun and found your remark : something internal does happen; not sure what causes it.
When forum_t conversion **(sometimes)** >  `thread_thread`  to forum_post;post_entry   makes to 'cut' .. why ???

example from forum_t : (179, '', 'KÖSZ FIZI\r\n\r\nTE VAGY A LEGJOBB :D:D:D:D:D:D:D:D:D', 6, 1177434396, 82, '50.USERXXXXX', 0, 1, 1177434396, 0, 0, '', 0), 
 becomes in post_entry > (179, 'K', 82, 6, 0, 1177434396, 50, NULL, NULL, NULL, NULL, NULL, NULL),
SQL conversion?

**Comment by Moc** [comment]
@fizi How does it go with the most recent Github version? 

Also, if your provider is satisfied with using 7 year old software, which is no longer maintained, then I strongly recommend leaving this provider NOW. It is their responsibility to keep the internet safe, and using outdated software is a no-go. There is absolutely no valid reason for them not to update.

**Comment by CaMer0n** [comment]
@fizi Show them this: http://php.net/supported-versions.php

**Comment by CaMer0n** [comment]
> The copy might be necessary, since i've had real issues with wrong templates from a upgrade from v1.4 to v2, and that copy process simply solve it.

@rica-carv I believe this is fixed now. It won't try to use that legacy folder any more.

**Comment by fizi** [comment]
This is work on my site.

**Comment by CaMer0n** [comment]
Thanks @fizi Can someone else confirm, so we can close this?

**Comment by rica-carv** [comment]
I've got no issues on a fresh V2 setup, so for me it's working as usual...

**Comment by CaMer0n** [comment]
Good to know, thank you @rica-carv
