### ISSUE TITLE
Replace clickable URL

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2102]
After update v1 - v2 ...If I put into (example: chatbox) it link (URL) and I set on the admin the replace clickable URL: enabled...appears in chatbox the replaced text and if I step on the list news page the replaced URL crashes the page.

**Comment by CaMer0n** [comment]
@fizi Would you be available to discuss this in the chatroom ?

**Comment by fizi** [comment]
How?

**Comment by CaMer0n** [comment]
https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
The chatbox issue has been corrected. Closing
