### ISSUE TITLE
[BUG] Import from uploaded images into mediamanager failed

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#2115]
Using latest github version from today i get an error when try to importing images into mediamanager:

![upload_mediamanager](https://cloud.githubusercontent.com/assets/22658487/20901183/ab3096ea-bb31-11e6-8fc8-c7a556b77560.JPG)

As you can see on the screenshot the import-function "removes" all the points in the name and the minus between the date and picture number - when i look onto my server the files stored in folder e107_system/xxx/import looks pretty normal (point before fileending is there)...

Filename on the server e.g.: bxxxxx_lxx_2001.04.15-015.jpg

Tried the import function serval version before without any problem...

====

Update: uploading an user-photograph also doesn't work - i didn't get any message (upload error or sucessfull) and my profile uses the default blank image... (filename uploaded picture "Me.jpg")

**Comment by CaMer0n** [comment]
Please see if this fixes it. Just replace e107_admin/image.php

**Comment by chimcen** [comment]
Hi Cameron,
i've uploaded all changes in e107v2 from github against the last 15hours - the images import works now.

The only thing thats doesn't work anyway is uploading a user picture (the picture, not an avatar)...

**Comment by CaMer0n** [comment]
@chimcen You mean via the usersettings page?

**Comment by chimcen** [comment]
Yes

**Comment by chimcen** [comment]
Tied the photo upload with older versions from 2.1.3 github - and with this one it works.

[usersettings.php.txt](https://github.com/e107inc/e107/files/636720/usersettings.php.txt)

But i've no idea wich change would break up the upload... line 180-204?

**Comment by Moc** [comment]
Probably caused by this commit: https://github.com/e107inc/e107/commit/e22eb860f1941327e31f2871168c3dd017decec0

**Comment by CaMer0n** [comment]
Please re-test. This should have fixed it. Known issue: Picture change not visible until after a page refresh.

**Comment by Moc** [comment]
Working. Also, the image appears directly on the usersettings page, the navbar one loads after a refresh (chrome).
