### ISSUE TITLE
Enhancement > New Form Manager (customise templates within the application)

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2120]
Is it possible to make Forms Configurable from within Admin similar to Menus via Menu Manager?

Let's call it a "Forms Manager". Admins could drag and drop Fields around a Form, add columns, custom images, instruction text and the like. Maybe we can already do this with shortcodes - but a gui version would a be very nice feature.  

Eventually could this approach replace Templates and the maintenance (and support overhead) involved in copying from core to themes folders.

**Comment by CaMer0n** [comment]
I think you mean something like this. https://kevinchappell.github.io/formBuilder/

**Comment by MikeyGMT** [comment]
Very cool plugin indeed. 

I was simply thinking about Templates and the Accessibility #275 stuff we have looked at. It occurred to me that we move blocks of content (menus) around in a GUI, so why not provide the same for forms in e107 and eventually do away with Templates?

**Comment by rica-carv** [comment]
I think we can't really ever get away of templating forms, specially on the frontend.
How can this work with menus that have forms?
How would it work inside a template, when you have a form with variable content inside it?
How should the templates be saved (db or file)?

There's a lot of if's....

Now that's a great ideia, it really is, but make it work....

P.S.: [HTML GUI editor](https://html-online.com/editor/)

**Comment by Moc** [comment]
I would consider this plugin territory too. In my opinion, to have templates customisable through the admin area is something for a way longer-term to be integrated into e107, if at all. Not in the foreseeable future anyway.

**Comment by Moc** [comment]
Closing this. A form builder is plugin territory.
