### ISSUE TITLE
RSS error

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#2125]
XML processing error other than XML or text declaration at the start of entity
Location: http://site.net/feed/news/rss/0
Second row, column 58:

<?xml version="1.0" encoding="utf-8"?>
---------------------------------------------------------^

**Comment by CaMer0n** [comment]
Impossible to correct if you don't share the actual feed. What is on the 2nd row at column 58 ?

**Comment by yesszus** [comment]
http://e107.totalh.net/feed/news/rss/0

**Comment by tgtje** [comment]
Just comment, no solution : when viewing source code of error page the first visible text ( <? xml  etc....
is NOT on line 1 position zero, but starts somewhere  on line 2 So there are/is a lot of whitespace  (like bom)..

**Comment by CaMer0n** [comment]
@yesszus Please re-test. Thank you.

**Comment by yesszus** [comment]
Apply: d7ae17f

Unfortunately, there is no change.
The problem persists.

**Comment by yesszus** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fe107-hun.tk%2Fe107_plugins%2Frss_menu%2Frss.php%3Fcat%3Dnews%26type%3D2%26topic%3D0#l2

**Comment by CaMer0n** [comment]
Please run a plugin-scan and check for addons which are marked with a warning. 

/e107_admin/db.php?mode=plugin_scan

**Comment by yesszus** [comment]
Run and without errors.
![screen](https://cloud.githubusercontent.com/assets/17430115/21232540/4aba764c-c2ec-11e6-8354-5907c3cde683.png)

**Comment by tgtje** [comment]
Again just comment : nodejs throws error

---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by CaMer0n** [comment]
@yesszus Okay thanks. Please check any non-English language files for any empty space before `<?php` or empty spaces after `?>`  including any custom plugins with language files.

**Comment by yesszus** [comment]
Solved!
@Jimmi08 review this plugin userlanguage_flags_menu
Delete this plugin and work for me rss feeds.
