### ISSUE TITLE
signup with linkedin account failed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2127]
I've created linkedin account, I set ID and API key in admin area but after trying to signup up, I got error:

![image](https://cloud.githubusercontent.com/assets/5429548/21014615/07c9f408-bd5f-11e6-94e7-b195b5d923d1.png)

Thanks

**Comment by lonalore** [comment]
Try to update your files to the latest Github ones. There are some bugs in HybridAuth 2.8, so it was downgraded to 2.7 in the repo. It fixed my Facebook login. I think it will help for your LinkedIn login too.

**Comment by Jimmi08** [comment]
Thanks. Updated. Facebook login works (at least asking for login to FB, but it worked before too.  But linkedin not. The same error.

**Comment by lonalore** [comment]
I think the problem is here:
https://github.com/e107inc/e107/blob/master/e107_handlers/user_handler.php#L1126

Try to replace this line:
```php
$provider = ucfirst(strtolower($provider));
```

with this:
```php
$provider = strtolower($provider);

switch($provider)
{
	case 'amazon':
	case 'facebook':
	case 'foursquare':
	case 'github':
	case 'google':
	case 'live':
	case 'steam':
	case 'twitter':
	case 'yahoo':
		$provider = ucfirst($provider);
		break;

	case 'aol':
		$provider = 'AOL';
		break;

	case 'googleopenid':
		$provider = 'GoogleOpenID';
		break;

	case 'linkedin':
		$provider = 'LinkedIn';
		break;

	case 'myspace':
		$provider = 'MySpace';
		break;

	case 'openid':
		$provider = 'OpenID';
		break;
}
```

**Comment by Jimmi08** [comment]
Great. My site is down. White screen. No error, e_debug is true.

**Comment by Jimmi08** [comment]
I found the reason. I've banned myself; Auto-ban: More than 10 failed login attempts
I cleaned everything, I tried to signup with linkendin (one time) and I got ban again.

There are a lot of: 	User attempted to login with unrecognised user name 
User name: LinkedIn_xxxx  
User attempted to login with unrecognised user name 
User name: Facebook_xxxx 

But login.php was still white page (no error with debug). After disabling social login. login page was back.  When enabled social login again - no white page. 

First time there were LinkedIN user (without email) and I deleted it, but there never was facebook user.

**Comment by Jimmi08** [comment]
@lonalore @CaMer0n Thank you for all. I found the reason why after this change (improvement) signup to linkedin failed.

- first time I had my LinkedIn app set without access to user email. That was reason why user was created without email, but they were created
- second time I changed LinkedIn app with access to user email.  When you sign up and user with that email already exists, you will end with with User attempted to login with unrecognised user name (repeatedly). If you try it again, your IP adress get banned.  

I think that this is reason why I can log in with facebook account because adress is already used with another user.  I am not able to change user email to test it but behaviour is similar.

Next log in with LinkedIn is without problem.

**Comment by LaocheXe** [comment]
@Jimmi08 sadly as a security measure, some providers don't share email (Steam, Facebook, etc...) However, you can go to settings and place an email in there after you login.

**Comment by Jimmi08** [comment]
@LaocheXe I don't understand what you mean. Account is correct created if there is no user with this email. I have main account and then I tried to log in with FB button (used on FB the same email). You just got blank page, not error that that email is already used.   Blank page shouldn't be there. If you haven't account yet, your account is created with email too.

**Comment by CaMer0n** [comment]
@Jimmi08 If you are able, could you please re-test the LinkedIn login with the latest code? hybridAuth has been upgraded. thanks.

**Comment by Moc** [comment]
@Jimmi08 do you still have the possibility to test this? :)
