### ISSUE TITLE
Cannot list forums

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#2128]
The top forum topics display but clicking on the items does not display the posts it just flashes the screen and lands you back at the forum listing.

**Comment by chimcen** [comment]
Eventually corresponding with [https://github.com/e107inc/e107/issues/1950](url) and/or [https://github.com/e107inc/e107/issues/2053](url) ?

**Comment by rica-carv** [comment]
Just tested with default bootstrap3 theme, and all works fine...

**Comment by dimante** [comment]
Well not working with my existing install with older forums...  What are
the exact steps to disable these special Urls?


Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
PS. even going into the forum and letting it generate SEF urls did nothing to change this...

**Comment by dimante** [comment]
Cleared all the topics, no change.

**Comment by rica-carv** [comment]
@dimante Older forums? What e107 version you have setup? 1.x?
Anyway, if you have the v2.x, and upgraded from 1.x, do you have sucessfully upgraded the forums from 1.x to 2.x also?

**Comment by dimante** [comment]
Yes my install was upgraded from 1.x  I am using the newest E107 Release

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by rica-carv** [comment]
And you have all ok on the admin area? No warnings?
Did the forums upgraded also sucessfully from 1.x to 2.x?
Also, are you using a v1.x theme or a v2.x one?
