### ISSUE TITLE
weird behaviour when mainadmin change their email

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2135]
I needed to change main admin email. After click on edit user in adminarea , changing email, I was logged out from site. Then I wasn't able to get back. I needed to set password in phpmyadmin and saved with md5 coding.  Just change email back didn't help. 
I tried this next time and the same thing happened.

**Comment by CaMer0n** [comment]
Did you use this page to do the edit? e107_admin/users.php   
If so, were you using the 'edit' page, or was it via inline-editing?
Or did you use usersettings.php to edit the email account?

Do you allow login via username and email or just email?

**Comment by Jimmi08** [comment]
Hi,
this button:
![image](https://cloud.githubusercontent.com/assets/5429548/21082827/cf5c67cc-bfe3-11e6-8346-ae83f4e2e653.png)
and this setting
![image](https://cloud.githubusercontent.com/assets/5429548/21082832/ee365a0e-bfe3-11e6-8199-889251567c98.png)

**Comment by CaMer0n** [comment]
Thank you.

**Comment by Jimmi08** [comment]
Tested now. edit email via inline editor, then edit user normal way and saved. Loged out, but was able to log in back.  
For me solved.
