### ISSUE TITLE
problem with newflag in forum page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2137]
I noticed this:  
![image](https://cloud.githubusercontent.com/assets/5429548/21083552/1362323a-bff3-11e6-8f53-6d4de466d3c1.png)

 in this function:
```
	function sc_newflag()
	{

		if(USER && is_array($this->newFlagList) && in_array($this->var['forum_id'], $this->newFlagList))
		{
			$url = $this->sc_lastpost('url');
			return "<a href='".$url."'>".IMAGE_new.'</a>';
		}
		elseif(empty($this->var['forum_replies']) && defined('IMAGE_noreplies'))
		{
			return IMAGE_noreplies;
		}

		return IMAGE_nonew;

	}
```
if I echo $url, output  has already a tags: 
`<a href='/user.php?id.2'>username</a> <a href='/forum/dkdhvdbd/3/test/?last=1#post-3'><span data-livestamp="1481490078">36 mins ago</span></a>`

**Comment by tgtje** [comment]
No chance to test but forum_viewforum php line 821 : 

> $tVars->NEWFLAG = "<a href='".e107::getUrl()->create('forum/forum/mfar', 'id='.$subInfo['forum_id'])."'>".IMAGE_new."'</a>';

should it not be : > $tVars->NEWFLAG = "<a href='".e107::getUrl()->create('forum/forum/mfar', 'id='.$subInfo['forum_id'])."'>".IMAGE_new."'</a>**### "**;

**Comment by Jimmi08** [comment]
@tgtje I really don't know, first time working with forum plugin and I was able to find this code just by trying to change something and will see if something was changed.  
Problem is from forum_template.php
```
$FORUM_TEMPLATE['main']['forum']			= 	"<tr>
											<td>{NEWFLAG}</td>
```
and there is code from shortcode above.

**Comment by martyshep** [comment]
Same issue
![image](https://cloud.githubusercontent.com/assets/15772899/21097673/a32a6634-c05d-11e6-8bfd-e0aa80857970.png)

**Comment by rica-carv** [comment]
@Jimmi08 @martyshep As soon i can, i'll give it a look, to see if i can solve it.
@tgtje Aren't you using a old forum code? Those $tvars are long gonne...

**Comment by rica-carv** [comment]
@all there's something weird here...
I submited a pull (#2033), and it was merged.
The weird thing is that the [master viewforum_shortcodes.php](https://github.com/e107inc/e107/blob/master/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php) file wasn't updated....
What happened there???

**Comment by rica-carv** [comment]
@all Definetly, it's with sc_lastpost call. My fault...
Try change
`$url = $this->sc_lastpost('url');`
to this
`$url = $this->sc_lastpost(array( 'type'  => 'url'));`

Please test it.

**Comment by martyshep** [comment]
Hi @rica-carv I can't see the code similar to $url = $this->sc_lastpost('url'); within viewforum_shortcodes.php on master or on your branch of it.  Wait.. Master is same as your branch for viewforum_shortcode.php anyway.

What I do see are:
function sc_newflag()
		{
//--	global $newflag_list;
			global $forum;
			$newflag_list = $forum->forumGetUnreadForums();
			/*--
					if(USER && is_array($newflag_list) && in_array($this->var['forum_id'], $newflag_list))
				{
					return "<a href='".e107::getUrl()->create('forum/forum/mfar', 'id='.$this->var['forum_id'])."'>".IMAGE_new.'</a>';
				}
					return IMAGE_nonew;
			--*/

		//	$url = e107::getUrl()->create('forum/forum/mfar', 'id=' . $this->var['forum_id']);
			$url = e107::url('forum', 'markread', $this->var);
			return (USER && is_array($newflag_list) && in_array($this->var['forum_id'], $newflag_list)) ? "<a href='" . $url . "'>" . IMAGE_new . '</a>' : IMAGE_nonew;

and

	function sc_newflag()
			{
			global $newflag_list;
				if(USER && is_array($newflag_list) && in_array($this->var['forum_id'], $newflag_list))
			{
				return "<a href='".e107::getUrl()->create('forum/forum/mfar', 'id='.$this->var['forum_id'])."'>".IMAGE_new.'</a>';
			}
				return IMAGE_nonew;

		  }

**Comment by rica-carv** [comment]
@martyshep It's not in `viewforum_shortcodes.php`, it's in [forum_shortcodes.php](https://github.com/e107inc/e107/blob/bdff197b3dd465d3586cdd814b9e226f478d104d/e107_plugins/forum/shortcodes/batch/forum_shortcodes.php#L351).
Sorry for all this mess...

**Comment by tgtje** [comment]
Ok, my bad, files a little older. 
After deeper investigation i discovered it actually is a break not fully implemented ? ..

i changed line 352 forum_shortcodes  to  
`return "<a href='".$url."<br />".IMAGE_new."</a>";
`
outcome top 2 images 
the bottom one is same but AFTER applied proposed patch

![f5](https://cloud.githubusercontent.com/assets/1811857/21110211/98a36f64-c09c-11e6-98cd-1321c1b82dbe.jpg)

What to do ?

**Comment by martyshep** [comment]
Interestingly the issue shown in 'old screen' disappears after the forum
post is read, but then when someone posts again, I get the old screen image
again.

**Comment by rica-carv** [comment]
@all This issue was because of a commit made 6 days ago, therefore if you don't have the latest github files and after apply my patch, it will still give a error.
I've tested my patch with latest files, ina clean e107 setup, and it returns thnew forum flag with the correct url to the latest topic, as is intended to be...

**Comment by tgtje** [comment]
@rica-carv correct your patch works 👍 but what i meant to express : in pre patch there was also the author and the time (textual) (linkage IS divided in 2 url's, correct). (left 1st column).
What to do : keep that extra info ? or use the new patching (only fa-star)? ( do we need/want User + text time?) It is an extra pointer, but also happens on right side too....

@martyshep  the appearance of the old is correct by means of execute > when the post is 'read' the function is done,  and will only show up in right side from there on. This untill a newer post exists (unread).

**Comment by rica-carv** [comment]
@tgtje The appearence is exactly the same as was before this mess up.
The last poster name & date is always on the right, there's no need (or logic) to have it again on the left side, above the star.
[Old newflag code ($fVars->NEWFLAG)](https://github.com/e107inc/e107/blob/master/e107_plugins/forum/forum.php#L447): 
```
	if(USER && is_array($newflag_list) && in_array($f['forum_id'], $newflag_list))
	{
		$fVars->NEWFLAG = "<a href='".$e107->url->create('forum/forum/mfar', $f)."'>".IMAGE_new.'</a>';
	}
	elseif(empty($f['forum_replies']) && defined('IMAGE_noreplies'))
	{
		$fVars->NEWFLAG = IMAGE_noreplies;
	}
	else
	{
		$fVars->NEWFLAG = IMAGE_nonew;
	}
```

As you can see, the newflag shortcode has never returned the last post author or date....

**Comment by martyshep** [comment]
I'm no coder but I returned my forum to previous behaviour with this:

			$url = $this->sc_lastpost('url');
		      **return IMAGE_new;**
		}
		elseif(empty($this->var['forum_replies']) && defined('IMAGE_noreplies'))
		{
			return IMAGE_noreplies;
		}

		return IMAGE_nonew;

**Comment by tgtje** [comment]
Ok, before messup( harsh : code error) the code should NOT have been displayed in the first column. 
Hence the original post asked as it was visible.

quote : no need (or logic) ?? _hmmmm  it does trigger possible use for other things_ .... (despite wrong use presently). ( a keeper)
As for the eye of the beholder i leave it open. (logic = right = ok). I can vision users that are drawn to text instead of knowledge of the glyphs.

**Comment by rica-carv** [comment]
@martyshep If you have the latest github files, there's no way that code is acting correct... Have you cleaned cache before testing it?

@tgtje You can still have the lastpost user name & date via shortcode:
`{LASTPOST:type=username} {LASTPOST:type=datelink}`
You can put them wherever you like, even twice in the same template....
