### ISSUE TITLE
problem with bbarea field in theme preferencies (maybe my fault)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2138]
I have tinymce field in theme preferencies defined this way

```
$var[4]['caption'] 	= 'Footer Messages -  Line no.2';
		$var[4]['html'] 	= "<div class='form-inline'>".$frm->bbarea('foot2',e107::pref('theme', 'foot2'),3,35,array('size'=>'block-level', 'placeholder'=>LAN_DEFAULT))."</div>";
		$var[4]['help']		= "";
```
If I left it empty, content is always 'array'
![image](https://cloud.githubusercontent.com/assets/5429548/21083589/ca74afac-bff3-11e6-9b38-4be6c9dfb403.png)

**Comment by CaMer0n** [comment]
I would need to see how you process $_POST in your theme_config file
