### ISSUE TITLE
Suggestion for cleaning up old prefs and tables.

### ISSUE THREAD

**Issue by BillyBoy0823** [e107inc/e107#214]
Suggestion. I noticed when I was adding and deleting plugins, some of them left behind things like extended user fields, tables and prefs.  Extended user fields seem easy enough to handle in ADMIN, but tables and prefs of removed plugins are not so easy.  

I love that preference editor (remover). I was thinking, in the Preference editor, maybe if there was a check done of the plugin's status, as to whether it is still installed or not installed, and then that info displayed, it could offer an option to remove any prefs entry in the core table for any non-installed or removed plug-ins. 

Plus, I think, when plugins gets uninstalled and plugin devs don't add our own cleanup routine, or the routine somehow fails without finishing further clean-up, this would be a good alternative to clean up junk. 

Maybe something similar for Tables. 

SO, having a scan for removed plugins and a choice for deleting tables and prefs might be helpful in admin clean-up.

You can't always trust us rookie plugin developers to clean up after ourselves......

**Comment by Moc** [comment]
Closing this. If the plugin is using v2 standards, all prefs and remaining data will be cleaned up as part of the uninstall process.

**Comment by BillyBoy0823** [comment]
I understand about the pref's.  I could see some old ones are still in SitePrefs where other plugins have their own entry in the "core" table.

That would be work having to go through them to clean it up. But pref's laying around isn't that big a deal. As you said, there's bigger things.....

The problem comes with the "plugin" table getting out of sync because a plugin is deleted manually, or renamed, before it's uninstalled. Even if it is put back, or renamed back to the "installed" directory, there are invalid entries in the plugin table. It messes with the displaying of plugins.  Not sure it affects anything else. 

I was going to write an "Check Up" To add as a selection on the plugin manager page, and have it at least check plugin folders for their existence  and that they aren't empty, and compare that to the plugin table.  After it's cleaned I was going to correct the Pref holding the plugin list as well....

But  No problem. You guys know what's up. 
Oh well, I tried jumpin in....

**Comment by rica-carv** [comment]
@BillyBoy0823 You can always write that idea of yours as a add on plugin
I think it's not too bad ideia to "clean" things up inside e107....
