### ISSUE TITLE
weird behaviour after posting forum topic

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2141]
When I post new topic in forum 

url is f.e. /forum/post/?f=nt&id=6
click Create a new topic
topic is sended, created but URL is not changed and displayed only
![image](https://cloud.githubusercontent.com/assets/5429548/21153386/8c6a8dbc-c16a-11e6-88c7-88bd937ac544.png)

**Comment by rica-carv** [comment]
Have you tryed with bootstrap3 theme?
The url doesn't change after topic creation, it stays the same.
Below that Forums line, you should have two buttons:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/21153613/2b277030-c163-11e6-9772-e781f6570aaa.jpg)

As you can see, just tested with bootsrap3 theme, and it works....

**Comment by Jimmi08** [comment]
@rica-carv the same with bootstrap theme
but I find hardcoded string in forum_posted_template.php
`<h4>New topic created.</h4>`
Specific is that quest can post. not only registered user.

**Comment by Jimmi08** [comment]
forum_posted_template.php is never loaded because this:

**Comment by rica-carv** [comment]
Done a patch for this issue.
I think is something weird there, since there's a lot of template HTML that has been removed from the template itself and put inside the forum_post.php file, sometime ago, but i can't find that commit....
The issue could be starting with that HTML "injection"....
