### ISSUE TITLE
Latest e107 news in Admin panel do not display anything

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2149]
After upgrading to the latest Git version the "Latest e107 news" in Admin panel do not display anything:

![adminpanel01](https://cloud.githubusercontent.com/assets/1757346/21188774/14bd810c-c1e2-11e6-822e-8d26cd0bb61f.JPG)

**Comment by CaMer0n** [comment]
Sorry, my fault. I switch e107.org to SSL and think it doesn't like the auto-redirect. Switched it back and it should be working now.

**Comment by CaMer0n** [comment]
I have updated cURL so it will work still work in situations like this. Internal feeds URLs have been updated to use https also.
