### ISSUE TITLE
Forum button bounce and change the size

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2150]
If I logout and see the forum button "New Topic" - the button bounce and change the size.
Mouse out:
![forum_button_of](https://cloud.githubusercontent.com/assets/86780/21197744/d68b309a-c23c-11e6-979c-5e0397df7915.jpg)
Mouse on:
![forum_button_on](https://cloud.githubusercontent.com/assets/86780/21197758/e4a56588-c23c-11e6-8742-b42bb81d05f6.jpg)
Now I delete data-toggle='tooltip' (line: 97) from viewforum_shortcodes.php and button OK (no tooltip), if the button has tooltip the button bounce.

**Comment by rica-carv** [comment]
Bootstrap issue. Fetching a workaround...

**Comment by rica-carv** [comment]
@fizi Just to make sure, which bootstrap library version are you using on that theme?

**Comment by fizi** [comment]
I'm using 3.3.7

**Comment by rica-carv** [comment]
From wich CDN? Or is it local hosted?

**Comment by Jimmi08** [comment]
Confirmed.  
Local 3.3.7
I noticed that there is wrong html markup too. (not solved this) 
http://getbootstrap.com/components/#btn-groups
- dropdown should be in div with class btn-group too.

**Comment by rica-carv** [comment]
[Tooltips in button groups, input groups, and tables require special setting](http://getbootstrap.com/javascript/#tooltips)

I've tryed the `container: 'body'`, but for any unknown reason for me, it didn't work.
The weird thing is that i've tryed it in bootply, and it worked.
So, i came up with th extra HTML tag to solve it...
Not elegant, but it's the only way i find out to solve it...
And yes, i even tryed jquery javascript also...

**Comment by fizi** [comment]
I modified viewforum_shortcodes.php file (94):
`$text .=
			'<a href="'.($this->var['ntUrl'] ?:"#").
			'" class="btn btn-primary'.($this->var['ntUrl'] ?"":" disabled").'"'
			.($this->var['ntUrl'] ?"":" data-toggle='tooltip' title='".LAN_FORUM_0006."'
			style='cursor: not-allowed; pointer-events: all !important;'").'>'.LAN_FORUM_1018.'</a>
      <div class="btn-group">
			  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    	<span class="caret"></span>
			  </button>
		    <ul class="dropdown-menu pull-right">`

Because the original Bootstrap write than btn-group need in btn-group.
And I modified the btn-primary, btn-group (style.css in theme):
`#forum .btn-group > a.btn,
#forum .btn-group > .dropdown-toggle {
  padding-left: 12px !important;
  padding-right: 12px !important;
}
#forum .btn-group > a.btn.disabled {
  border-right: none;
}
#forum .btn-group > .dropdown-toggle {
  border-left: none;
}
#forum .btn-group .btn + .btn,
#forum .btn-group .btn + .btn-group,
#forum .btn-group .btn-group + .btn,
#forum .btn-group .btn-group + .btn-group {
  margin-left: 0;
}`

In this way seems the button ok and not bounce.
It might not be pretty, but it works for me.
I think this is a bootstrap style bug.

**Comment by rica-carv** [comment]
@fizi Tested your approach, and still keeeps moving the button, even if it's only 1px...

**Comment by Jimmi08** [comment]
@rica-carv I suppose we are talking about resizing button with mouse move (bounce effect), not about tooltips.  Markup should be rewritten according to bootstrap documentation.

**Comment by rica-carv** [comment]
@Jimmi08 Yes, the situation here is to prevent the resizing disabled button when tooltip is displayed.
Somehow, it should work with the simple add of `container: 'body'`, but for some reason, it doesn't work inside forum (maybe some not fully compiled bootstrap js or css in e107), because i've tested it in a simple bootply with bootstrap 3.3.7, and it worked like a charm...
Therefore it had to be solved with custom css and intag bootstrap tootltip data in order to work.

Yes, i agree with you on order to keep btn-group bootstrap standards, as is [defined by bootstrap](https://v4-alpha.getbootstrap.com/components/button-group/#nesting): 
```
<div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <a class="dropdown-item" href="#">Dropdown link</a>
      <a class="dropdown-item" href="#">Dropdown link</a>
    </div>
  </div>
```

**Comment by fizi** [comment]
But written in bootstrap that "Place a .btn-group within another .btn-group when you want dropdown menus mixed with a series of buttons."

**Comment by rica-carv** [comment]
@fizi There's some confusion there...
Dropdown menus mixed with series of buttons:
![](http://www.android-examples.com/wp-content/uploads/2016/03/dropdown-menu.png)

Single split button dropdown (as is in forum):
![](http://www.android-examples.com/wp-content/uploads/2016/03/split-buttons.png)

**Comment by fizi** [comment]
This is really bootstrap bug, I found this:
All button padding: 6px 12px...but
`.btn-group > .btn + .dropdown-toggle {
  padding-left: 8px;
  padding-right: 8px;
}`

**Comment by Moc** [comment]
Has this been submitted as a PR already? is still issue still present in the latest Github files?

**Comment by fizi** [comment]
Now the problem is not detected.
