### ISSUE TITLE
how to use featurebox shortcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2156]
I need to display featurebox items without {FEATUREBOX} shortcodes.  

After using something like this:
```
               $sc = e107::getScBatch('featurebox',TRUE);
		$rowArray = e107::getDb()->retrieve('featurebox', '*', $where, true);   		
			foreach($rowArray as $row)    // loop through the database results. 	
				$sc->setVars($row);	    // send the value of the $row to the class. 
				echo $tp->parseTemplate($template, false, $sc);    // parse the 'item' 
			}
		}
```
I've got error: 
Fatal error: Call to undefined method featurebox_shortcodes::setVars() in C:\xampp\htdocs\e107-master\e107_themes\freelancer\theme_shortcodes.php on line 36

What am I missing? Thanks

**Comment by rica-carv** [comment]
@Jimmi08 Working from memory right now, but it seems that the [e_shortcodes from featurebox doesn't extends e_shortcode](https://github.com/e107inc/e107/blob/master/e107_plugins/featurebox/e_shortcode.php#L13), therefore that `setVars` is unavailable during runtime....

**Comment by Moc** [comment]
@Jimmi08 Is this issue still relevant?

**Comment by Jimmi08** [comment]
@Moc  no idea, I don't use FB anymore.
