### ISSUE TITLE
Analytics code causing white page.

### ISSUE THREAD

**Issue by inferno-prime** [e107inc/e107#2158]
I have tried both the additional meta tags area and the showonpages plugin submitting the same script code that the analytic website generates for your website but I get a white page eveytime.

This is a new install mind you I am also getting some errors which I will include just in the event it mite be helpful to others.

I tried to see if I could insert this into a scroll-able box but I did not see on option for it. I am really unsure if its the php errors causing the issue or if it just wont take the script code I am looking forward to your opinion as I am really interested in the cause.

Again Really apperrciate your help. :)

```
`Deprecated mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead, Line 222 of /home/name/public_html/e107_handlers/mysql_class.php

Notice Constant LAN_IP already defined, Line 289 of /home/name/public_html/e107_languages/English/admin/lan_admin.php
	
Notice Undefined index: , Line 1272 of /home/name/public_html/e107_handlers/shortcode_handler.php

Notice Undefined offset: 0, Line 344 of /home/name/public_html/e107_handlers/db_debug_class.php
	
Warning Division by zero, Line 397 of /home/name/public_html/e107_handlers/db_debug_class.php
	
Warning Division by zero, Line 413 of /home/name/public_html/e107_handlers/db_debug_class.php
	
Warning Division by zero, Line 456 of /home/name/public_html/e107_handlers/db_debug_class.php
	
Warning Division by zero, Line 461 of /home/name/public_html/e107_handlers/db_debug_class.php
```

**Comment by Moc** [comment]
Please share the following information:

- Analytics code you are trying to insert (you can leave out sensitive info of course) 
- PHP version

**Comment by inferno-prime** [comment]
Sure no problem.

I am able to select my php anywhere from 5.2 to 5.6 I went with 5.6 because I figured there were bugs or fixes.

And the code I am using is : 


<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://www.example.com/owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', 'fb96ba8fdf3c2000737600e9d2db7e4e']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
	var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
	owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
	_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
	var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>

**Comment by tgtje** [comment]
Testing impossible if OWA is not present (is a product), but i do think it is best practice to put the code in a php file and 'include' it on a per page or alike ? Just tinkering..

**Comment by inferno-prime** [comment]
Tgtje : If it could be done to make less work for you then please explain to me in great detail how to apply it ?.

**Comment by tgtje** [comment]
Thanks for reply, i will take a look at it. Maybe theres something to do 
with it (either cakking the js or by means of plugin ?)
Anyway, please give me some time to tinker with it.
Note : this is NOT to be seen as issue imo. (so may be closed). This is 
third party implementation. Maybe better suited for e107help.




---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by inferno-prime** [comment]
No problem I will wait

Also I only came here because I was requested to do so.

**Comment by CaMer0n** [comment]
@inferno-prime Just wanted to double-check that you have the correct permissions to post `<script>` tags

**Comment by inferno-prime** [comment]
Just to be sure could you please let me know where they are and ill let you know if they are enabled.

**Comment by tgtje** [comment]
@inferno-prime  pm on help. 
Extra info:
Adding the js as call is no issue, source will reveal it is loaded..however it will not execute the rest).
Did some tinkering with plugin/menu based, got a working demo after some time...; not the nicest, but than again, it has a function, not a good look) Let's test it first tanh a more experienced coder may have it ;-)

**Comment by CaMer0n** [comment]
e107_admin/prefs.php#nav-core-prefs-textpost

**Comment by tgtje** [comment]
@CaMer0n thanks for replying, trackprogramm display > meant : standalone application with own admin etc.. Sorry should have made it more clear (There exists a wp thing, but hehe not going to examine that as no real example is present..

**Comment by inferno-prime** [comment]
Cameron yes both those options are enabled & I tried to post again and same result. I also tried making a dummy account to try posting the code with that and same result there too.
