### ISSUE TITLE
Can't add custom rank 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2159]
In User's Ranks
![image](https://cloud.githubusercontent.com/assets/5429548/21285568/81a85f24-c43c-11e6-826e-735f86e6439a.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/21285572/9e5f1f0e-c43c-11e6-8378-3538f82966a4.png)

But no Rank is added

**Comment by Moc** [comment]
PHP and MySQL version? Does debug show anything?

**Comment by Jimmi08** [comment]
PHP Version 5.5.38 5.5.45-MariaDB-log PDO: Disabled 
With debug enabled I see 2 user ranks:
![image](https://cloud.githubusercontent.com/assets/5429548/21289581/43405254-c4a1-11e6-8dc0-b2e47181de62.png)
no debug infor where add rank in normal User Rank.
when I click on user Rank experimental, I see new ranks there.  So problem is propably only in query in old User Ranks.

**Comment by Jimmi08** [comment]
This is fixed already
