### ISSUE TITLE
Number of comment not appears 

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2162]
The number of comment appears right on the news.php page, but not appears on the extend news page (example: comments: 1 - on the news.php page .... Comments (0) - on the extend news page).

**Comment by Moc** [comment]
Confirmed, there is an issue with the comments counting. Also in the search results.

**Comment by fizi** [comment]
The problem is still there.

**Comment by CaMer0n** [comment]
I believe this is fixed. Closing, but please re-open if necessary.
