### ISSUE TITLE
can't insert image via media manager in welcome message (tinymce)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2163]
- Welcome Message
- edit, insert Media Manager image  (jpg file)
- upload image , but not seeing it  . Because this happens via media manager sometimes, I know that I need to go and manually import this image.
![image](https://cloud.githubusercontent.com/assets/5429548/21293807/f349c0b2-c52e-11e6-8919-0eb999f2f94b.png)

PHP Version 5.6.27
MySQL 5.6

Thanks

**Comment by CaMer0n** [comment]
I think "Common Images" is the category you want ;-)

**Comment by Jimmi08** [comment]
Hahaha. Thanks.  I changed issue, so only why it is not imported  itself with tinymce.

**Comment by Moc** [comment]
Confirmed. Still an issue.

**Comment by CaMer0n** [comment]
@Jimmi08 Hopefully, it should be working for you now.  It's working here. Thanks.
