### ISSUE TITLE
"Country" user extended field not functional

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#2165]
Some issues:

1. Currently, when activating the 'country' user extended field, the new database with the country list is not created (`e107_core/sql/extended_country.php`)

2. After manually inserting the table into the database, basic functionality works. There are some issues with displaying the values however.
When editing the country EUF on `/e107_admin/users_extended.php`, the display value is set to `country_name` but it actually displays the `country_code`. 

3. When selecting one of the options in the dropdown (issue 2), the entire form field disappears (tested on Chrome). You can bring it back by changing the `Type` of the EUF.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/2017

**Comment by Moc** [comment]
@Jimmi08 It's a different issue and not entirely related... This issue is mostly about the admin area, whereas #2017 is about frontend (usersettings.php)

**Comment by Moc** [comment]
Working better now but the option array is not passed correctly. The field now appears as a textbox rather than a selectbox.

**Comment by Moc** [comment]
Nevermind, caching issue. The selectbox now shows. Thanks Cameron :) 

Would still be cool to have it autocomplete at a later stage, but for now this will do. 
Closing.

**Comment by Moc** [comment]
Working properly now. Thanks again.

**Comment by Alex-e107nl** [comment]
Moc, can you please verify that this still works? When i test it in admin it goes fine, get the list with country's to select, but in the users profile i only see 'nl' instead of Netherlands, in the database in the e107_user_extended table there's only the 2 letters in the user_country, so how do i get the full countryname in the profile? Also i do not have a table with countries in my database... 

Please help!
Alex

**Comment by Moc** [comment]
@Alex-e107nl Still seems to work fine for me. 

For me, the user_country in the e107_user_extended table also shows just the country letter code (nl). The frontend shows the full country name. It no longer needs a separate database table with the full country names. Instead the country names are hardcoded in the form handler here: https://github.com/e107inc/e107/blob/master/e107_handlers/form_handler.php#L203 based on the iso code (the country letter code, nl in our case)

Try deactivating and re-activating the 'country' UEF in the admin area, and clear your caches. 

Are you using a v1 or v2 theme?

**Comment by Alex-e107nl** [comment]
Hi Moc, thx for answering, 
there's a difference between usersettings.php and user.php?id.1 (profile) theme is v2, but tested with the standard bootstrap 3 theme, cache removed (cleared an switched off) No custom templates, php7, eng of dutch gives the same result... 
So what can i do now?
Alex
