### ISSUE TITLE
Bugged online shortcodes

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2175]
Actually, these online shortcodes on the online_menu returns nothing, even if there are members registered & online:
```
{ONLINE_MEMBERS_LIST_EXTENDED}
{ONLINE_ONPAGE}
{ONLINE_MEMBER_TOTAL}
{ONLINE_MEMBER_NEWEST: type=avatar}
```

**Comment by CaMer0n** [comment]
@rica-carv Can this be closed?

**Comment by rica-carv** [comment]
@CaMer0n Sorry, yes...
