### ISSUE TITLE
Contact menu - required not visible field subject

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2178]
Default contact menu (core template) has these fields:
 
![image](https://cloud.githubusercontent.com/assets/5429548/21366854/ee861872-c6fb-11e6-9e4a-614f4233fd9f.png)

But after sending:
 
![image](https://cloud.githubusercontent.com/assets/5429548/21366882/0cefda8c-c6fc-11e6-8e0f-57b51b854177.png)

But maybe is problem somewhere else. I didn't use this menu before, so I don't know if it should go to contact.php after submit. This check above is on field on contact page.  

Contact menu is displayed if contact person in prefs is set to no one (form on contact page is not displayed).  

Just to have it complet - how use contact form on one page theme? I can create new menu, but 

Thanks

**Comment by MikeyGMT** [comment]
Maybe me ... #2107 or #2170 - hope not :)

**Comment by chimcen** [comment]
On my website (using latest github version) the contact plugin works without any errors... but i use a own contact template...

Do you use the default template or a custom one?

**Comment by Jimmi08** [comment]
@chimcen contact page or contact menu?  Problem was with menu.

**Comment by chimcen** [comment]
Ah...dammit, sry - meant the page...

**Comment by Jimmi08** [comment]
@chimcen no problem. I still don't get how contact form in menu should work. It wasn't in version 1 (or I didn't find it)  You could just try to add it and write if it should work this way. Other opinion.

**Comment by chimcen** [comment]
If you use the default contact_template.php just replace line 39-56 with the following one and the menue should work (tested this on my site,too and after then it works as it should)...

`$CONTACT_TEMPLATE['menu'] =  '
	<div class="contactMenuForm">
		<div class="control-group form-group">
			<label for="contactName">'.LANCONTACT_03.'</label>
				{CONTACT_NAME}
		 </div>
		 
		<div class="control-group form-group">
			<label class="control-label" for="contactEmail">'.LANCONTACT_04.'</label>
				{CONTACT_EMAIL}
		</div>
		</div>
		<div class="control-group form-group"><label for="contactSubject">'.LANCONTACT_05.'</label>
			{CONTACT_SUBJECT}
		</div>
		<div class="control-group form-group">
			<label for="contactBody" >'.LANCONTACT_06.'</label>
				{CONTACT_BODY=rows=5&cols=30}
		</div>
		{CONTACT_SUBMIT_BUTTON}
	</div>       
 ';`

**Comment by CaMer0n** [comment]
The contact menu posts the data to the contact page.

**Comment by Jimmi08** [comment]
Thanks

**Comment by chimcen** [comment]
Does it work for you, too?
