### ISSUE TITLE
problem with lanvars

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2180]
Fresh install, only English, latest github, noticed this after deleting some records from sitelinks
![image](https://cloud.githubusercontent.com/assets/5429548/21387002/f0b97f7e-c775-11e6-844f-76523e59ff1e.png)

`RL_LAN_085`

**Comment by tgtje** [comment]
// FIXME lan ??
4515 handlers/admin_ui  (lan_admin_log. php line 85)

**Comment by yesszus** [comment]
Work this for me.

**Comment by Jimmi08** [comment]
The same string (RL_LAN_085)  is in lan_admin_log.php. Isn't this duplicate?

**Comment by tgtje** [comment]
The one in log is original; the handlers/ admin_ui has to put it there i guess. ???

**Comment by CaMer0n** [comment]
Hmm, someone put admin-ui terms into the adminlog language file.. which is completely unrelated.

**Comment by CaMer0n** [comment]
@Jimmi08 Please update and retest. Thank you.
