### ISSUE TITLE
Cannot send PM

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2182]
I am not able to activate the Recipient field to send a PM. (see screen shot)
Maybe it is more missing outside the margin?

![cannotsendpm](https://cloud.githubusercontent.com/assets/1757346/21414013/55a2b50e-c7c1-11e6-8558-8de191e353c7.JPG)

**Comment by lonalore** [comment]
I had similar (permission) issue on my website. I updated PM settings on Admin UI, and everything works fine now.
Try to update you settings on "e107_plugins/pm/admin_config.php".

**Comment by Moc** [comment]
No it's due to conflicting shortcodes. There is a folder you need to remove from the pm plugin folder. I don't know which one (not at the computer ATM). Deleting the pm plugin folder and reuploading it from github should work.

**Comment by Norwayman** [comment]
@Moc Yes this worked

**Comment by CaMer0n** [comment]
I'm guessing it was sendpm.sc

**Comment by Moc** [comment]
I found the issue to which I was referring above: https://github.com/e107inc/e107/issues/1747 
Apparently you had to remove the shortcodes folder. 

@CaMer0n Please confirm, so these two issues can be closed.

**Comment by Norwayman** [comment]
@moc
@cameron

What I did was to uninstall yhe entire plugin....deleting all the files and tables....only saving the lsnguage files so I didn't have to do all thosr again. Then I downloaded the latest from Github, indtalled tye plugin again and copied back inn the language files. So now it all eorks for me

**Comment by Moc** [comment]
Closing this as the admin area now shows a message if the old files are still there
