### ISSUE TITLE
Online users menu item not showing comma separated list of users online

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2187]
Menu item Show list of members online? Enabled = only shows number of online users, not a comma separated list as indicated in the tool tip.

Setting Show extended list of members online? to enabled shows users but also the page they are viewing.

Parameters (query string format): is set blank

Running latest 2.1.4 (Git)

**Comment by MikeyGMT** [comment]
Hi @martyshep 
In e107_plugins/online/templates/online_menu_template.php add {ONLINE_MEMBERS_LIST} at line 26 after {ONLINE_MEMBERS} hence... 

{ONLINE_MEMBERS} 
**{ONLINE_MEMBERS_LIST}**
{ONLINE_MEMBERS_LIST_EXTENDED}

It looks like {ONLINE_MEMBERS_LIST} was missing so I'll add and create a pull request as I am doing some lans tidy up in the area anyway. 

Merry Christmas!
Mikey

**Comment by MikeyGMT** [comment]
Testing : 
List Option Disabled 
![image](https://cloud.githubusercontent.com/assets/2847651/21472924/a52a6774-cae7-11e6-8c16-89fbee416023.png)

Now enable option 
![image](https://cloud.githubusercontent.com/assets/2847651/21472925/c69bd848-cae7-11e6-9226-0bbf865da4fb.png)

Also notice missing title is displayed (used "settings" from main English Lan - avoids duplicates)
![image](https://cloud.githubusercontent.com/assets/2847651/21472931/f0ac2c5a-cae7-11e6-838d-906e1789007e.png)

Result with option ON
![image](https://cloud.githubusercontent.com/assets/2847651/21472936/2c6ce61c-cae8-11e6-9f41-4efd5628cf67.png)

**Comment by martyshep** [comment]
Awesome thanks @MikeyGMT , your fix worked perfectly, Happy Christmas 👍
