### ISSUE TITLE
Attaching an image to a forum post puts the file in wrong directory

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2193]
On current commit and not sure when it broke.

When attaching a file to a forum post, the file is saved into **e107_media/<folder>/avatars/upload/user_** rather than **e107_media/<folder>/plugins/forum/attachments/user_**

resulting in **Missing File:** error message displayed in the forum post

**Comment by Moc** [comment]
Confirmed

**Comment by CaMer0n** [comment]
Pretty sure this should fix it. Please re-test.

**Comment by martyshep** [comment]
Works for me now @cameron, thank you

**Comment by CaMer0n** [comment]
Great. Thank you! 👍
