### ISSUE TITLE
User Creation Broken

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#2194]
When a new user registers, it returns the message:

Error
An error has occurred creating your user information, please contact the site admin

Any ideas where to look for the error?

Using latest git version

**Comment by CaMer0n** [comment]
I'm guessing line 879 of signup.php. Are you running MySQL STRICT MODE (In admin > About > PhpInfo ) 
And are your user tables okay? (Tools > Database > Check Database Validity)

**Comment by Brooniee** [comment]
@CaMer0n 

MySQL
5.7.16-0ubuntu0.16.04.1
Database: xxx
PDO: Enabled
Mode: ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

For DB check get:

Success
Tables appear to be okay!

**Comment by Brooniee** [comment]
@CaMer0n anything further i could try?

**Comment by CaMer0n** [comment]
I'm going to test with your MySQL Mode params and see if I can find the issue.

**Comment by CaMer0n** [comment]
@Brooniee Please update e107_handlers/mysql_class.php from here on Github and see if that helps.

**Comment by Moc** [comment]
@Brooniee Could you provide feedback on the changes made by Cameron? Is it working now?

**Comment by Brooniee** [comment]
Confirmed fixed in latest version

**Comment by Moc** [comment]
Thanks for letting us know :)
