### ISSUE TITLE
Unable to create x file. Please check your folder permissions

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#2195]
Unable to create ../e107_system/5eef33298a/cache/content/. Please check your folder permissions.
Unable to create ../e107_system/5eef33298a/cache/images/. Please check your folder permissions.
Unable to create ../e107_system/5eef33298a/cache/db/. Please check your folder permissions.
Unable to create ../e107_system/5eef33298a/cache/url/. Please check your folder permissions.
Unable to create ../e107_media/5eef33298a/avatars/default.
Unable to create ../e107_media/5eef33298a/avatars/upload.

These files already exist? Which I guess is why it is unable to create them...?

Using latest git

**Comment by CaMer0n** [comment]
Did you check the permissions on e107_system/5eef33298a/ and its subfolders?

**Comment by Brooniee** [comment]
@CaMer0n After migrating server to a PHP7 install, this appears to have gone.

**Comment by CaMer0n** [comment]
okay thank you. Which version of PHP were you migrating from ?

**Comment by Brooniee** [comment]
@CaMer0n 7.0.8-0ubuntu0.16.04.3
