### ISSUE TITLE
Being logged out, unable to do anything

### ISSUE THREAD

**Issue by cainey** [e107inc/e107#2199]
Good day all,

I have a small issue, I know it has been raised before but I haven't found a work around for me.
Im using e107v2 and all was going well and it was said by one of the members that when he logs in then views a different page it logs him out.

I tried logging in to the admin area, looked fine but click on anything and it just keeps asking for me to login again.

I have managed to change some settings via phpMyadmin but don't want to mess to much.
I have tried changing the cookies name, changed to session, I have deleted tables in the ban list.
disabled flood protection because the inputs were regarding hit counter.

Im at a bit of a dead end now.
All the support with this would be awesome because i currently have a lot of members shouting at me because they cant logon.

PHP - 5.6 
MYSQL - 5.6.29

Thanks for all/any support.

**Comment by CaMer0n** [comment]
Please try adding this to your e107_config.php file: 

`define('e_SECURITY_LEVEL', 0);`

**Comment by cainey** [comment]
Hi Cameron.
i have tried that alreay and nothing and that was something else i tried regarding the config file another line of code, so its gone out my head now but that never worked. 
not sure if its related but im also getting unauthorised access when i do manage to log in and try altering a news item or page. 
but there time ot does just log me out before i can do out.

**Comment by CaMer0n** [comment]
Could you check your phpinfo() ? Maybe the session save path ?

**Comment by CaMer0n** [comment]
hmm. Every server is different.. I'm using PHP5.6 without any problems. Please join me in the chatroom when you have time so we can try to troubleshoot it.  https://gitter.im/e107inc/e107

**Comment by Moc** [comment]
@cainey Are you still experiencing this issue?

**Comment by BigBoiJefe** [comment]
I'm experiencing this same issue @CaMer0n

**Comment by rica-carv** [comment]
Clean e107 cache and check if your IP is not flagged as bot by e107...

**Comment by Moc** [comment]
https://github.com/e107inc/e107/pull/2622

**Comment by Moc** [comment]
@CaMer0n What do you think about this one?

**Comment by Moc** [comment]
If anyone is still experiencing this issue using the latest files, please join us on the Gitter chatroom so we can debug the issue on your installation. 

https://gitter.im/e107inc/e107

**Comment by BigBoiJefe** [comment]
I am still experiencing this problem.  The session timeouts even if the user is still logged in.

**Comment by Moc** [comment]
@BigBoiJefe As requested, please join us in the Gitter chatroom so we can debug this real-time with you.
