### ISSUE TITLE
Forum plugin LAN rewrite

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#220]
The LAN files in the forum plugin are currently being rewritten. 
As a consequence, they are currently unorganized and may cause strange sentences (that do not fit into a particular context). 

It will be a major rewrite so backwards-compatibility is going to be an issue. Old forum templates will need updating to match the new LAN's. I'll probably provide updated LAN templates based on v1.x which can then be used for people to update their themes. 

**WORK IN PROGRESS**

- [x] icons_template (!) 
- [x] posted template (!)
- [x] preview template (!)
- [x] forum
- [x] forum_viewforum
- [x] forum_viewtopic
- [x] forum_post
- [x] forum_class
- [ ] forum_conf
- [ ] forum_mod
- [ ] forum_stats
- [ ] forum_uploads
- [ ] new forum posts menu

**Comment by CaMer0n** [comment]
@Moc I believe this is complete, unless you have spotted some LAN issues in forum recently?

**Comment by Moc** [comment]
@CaMer0n I've quickly skimmed through the files that were still remaining according to my checklist in the initial post. It appears all work has been completed. Closing :)

**Comment by CaMer0n** [comment]
Thanks :+1:
