### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#2204]
When logging into my site it redirects to a blank page. Viewing source, no data is returned. Error log says the following...
`[28-Dec-2016 16:35:01 Europe/London] PHP Strict Standards:  Declaration of e_tree_model::load() should be compatible with e_front_model::load($id = NULL, $force = false) in /<mysite>/e107_handlers/model_class.php on line 3445
[28-Dec-2016 16:35:01 Europe/London] PHP Strict Standards:  Declaration of e_front_tree_model::update() should be compatible with e_tree_model::update($from_post = true, $force = false, $session_messages = false) in /<mysite>/e107_handlers/model_class.php on line 3579`

I can login fine through admin, and once I'm logged in I can browse the main site; however, I see Array ( ) Array ( ) Array ( ) Array ( ) Array ( ) at the top of the page.

Usin version 2.1.3

**Comment by Moc** [comment]
PHP version?

**Comment by pricey1981** [comment]
5.3.13

some of my self-coded JSON functions have also stopped working since upgrading to e107 2.1.3

**Comment by rica-carv** [comment]
Minimum PHP for V2.x is PHP 5.4.....

**Comment by Moc** [comment]
Definitely need to upgrade to a more recent PHP version. PHP 5.3 is heavily outdated: http://php.net/supported-versions.php

I would recommend PHP 5.6 for now, but plan to migrate to PHP 7.x soon.

**Comment by pricey1981** [comment]
Sorry, was looking at the wrong page (my wampserver)

Current live site is on PHP 5.6.28

Will update wampserver though, but still having these problems with e107 2.1.3

**Comment by Moc** [comment]
So you are having these issues on an installation of 2.1.3 running on PHP 5.6? And these occured right after updating? Try downloading the ZIP file from Github again and replace all files. Possibly one got corrupted.

**Comment by pricey1981** [comment]
Yes, 2.1.3 on PHP 5.6

I've gone back to 2.1.2 and still having the issue with blank screen after logging in. The other issues (Array() & JSON) are no longer happening on 2.1.2)

**Comment by Moc** [comment]
Hmm, find @CaMer0n on Gitter then.... manual debug required

**Comment by rica-carv** [comment]
Firefox e107 debugger also gives nothing?

**Comment by pricey1981** [comment]
Using Chrome - debugger is empty. When I 'View Source' of the page, it's completely blank

**Comment by CaMer0n** [comment]
@pricey1981 Message me in the chatroom and I'll be happy to take a look.

**Comment by rica-carv** [comment]
Firefox has a plugin for debugging e107, with much more info than "normal" debugging.
Anyway, is your site a fresh v2, or a upgraded from v1.x?

For me, as it goes, it seems to be some PHP bug error...

**Comment by pricey1981** [comment]
it was originally a 1.x upgrade. But in trying to resolve this issue I've basically done a fresh 2.1.2 install.

**Comment by pricey1981** [comment]
Thanks to @cainey on gitter, it seems to be solved. my host's IP was on the banned list for some reason. Removed that and it appears to be working.

**Comment by CaMer0n** [comment]
I'm re-opening this in order to add a check during banning so that this cannot occur.

**Comment by CaMer0n** [comment]
Shouldn't happen again now. Closing.
