### ISSUE TITLE
problem with {GALLERY_PORTFOLIO} and bbarea field

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2205]
I am trying to insert gallery (one category) to news. 
If I do this in theme.php, shortcode works (partially, there is other issue)

```
     {SETSTYLE=portfolio}
      {SETIMAGE: w=700&h=500&crop=1}
{GALLERY_PORTFOLIO: placeholder=1&category=15}
```
parm looks like this
![image](https://cloud.githubusercontent.com/assets/5429548/21527023/ab54fd7e-cd28-11e6-8e7a-efba6674cfea.png)

it's correct. 

but if I use it in news (extended field)
![image](https://cloud.githubusercontent.com/assets/5429548/21527045/c4a11c90-cd28-11e6-8ba6-1ae8bd2cd5ca.png)

it's parsed like:
![image](https://cloud.githubusercontent.com/assets/5429548/21527056/d7e367fe-cd28-11e6-901d-9eeb197a04bd.png)

So you can't use category parameter there.

**Comment by CaMer0n** [comment]
@Jimmi08 Did this last commit fix it?

**Comment by Jimmi08** [comment]
@CaMer0n Fixed. Thank you
