### ISSUE TITLE
download plugin - screenshot image is not responsive

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2207]
In download plugin when you click on screenshot. 
It would be enough  to add class img-responsive to img tag but I am not able to find where.

![image](https://cloud.githubusercontent.com/assets/5429548/21528148/a591b212-cd30-11e6-9e14-71bfc585c32b.png)

Thanks

**Comment by rica-carv** [comment]
[img-responsive is already on the image shortcode](https://github.com/e107inc/e107/blob/master/e107_plugins/download/download_shortcodes.php#L586)... weird...

**Comment by Jimmi08** [comment]
Update to latest github, checking if I don't use theme templates for download plugin - no)

I don't see these class there.

![image](https://cloud.githubusercontent.com/assets/5429548/21528405/8a4401b6-cd32-11e6-8447-d858109c0324.png)

**Comment by rica-carv** [comment]
Weird, i do have it:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/21528458/9f3545f6-cd2a-11e6-8220-f75b8a8c769b.jpg)

**Comment by CaMer0n** [comment]
@Jimmi08 Does this commit fix it?

**Comment by rica-carv** [comment]
@CaMer0n And why not allow template for it? Let the user / theme decide to what wrap the image? Wouldn't it be some more versatile?
Just my 2 cents...

**Comment by Jimmi08** [comment]
@CaMer0n  fixed, thank you.  
@rica-carv  from look at what CaMerOn changed, there is no template for this. If you want it, create different issue as enhancement.
