### ISSUE TITLE
Download as visitor (members only downloads)

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2208]
The downloads on my page only for members. If I logout and I want download as visitors I got: On English "Error 83" and on Hungarian "Error 404". No text that "The download only for member"...or anything.

**Comment by rica-carv** [comment]
Can't test it right now, but try to change line 70 of download_class.php to this:
`$this->qry['error']		= intval(varset($tmp[2],0));`

**Comment by fizi** [comment]
Not good. I got same error page. 
Hungarian: http://fizithemes.hu/letĂ¶ltĂ©s?action=error&id=101
![hungariandownloaderror](https://cloud.githubusercontent.com/assets/86780/21550995/67e1e15c-cdfe-11e6-91d2-2be3719e8201.jpg)

English: http://fizithemes.hu/download?action=error&id=83
![englishdownloaderror](https://cloud.githubusercontent.com/assets/86780/21551002/7ceca4f6-cdfe-11e6-817c-d48fd9d9cd6c.jpg)

**Comment by tgtje** [comment]
Thanks to Jimmi08/Jimako pointing : similarities or based on same ?  #1817

**Comment by rica-carv** [comment]
Well, just tested in my site, and got something different.
If i set a download to be only downloadable by members, when logged out it doesn't even shows! As it should be!
I'm using latest github, so there's something real weird there....

**Comment by rica-carv** [comment]
Workaround. Replace [request.php line 252](https://github.com/e107inc/e107/blob/master/e107_plugins/download/request.php#L252) with this:
`$goUrl = e107::getUrl()->create('download/index')."?action=error&id=1";
`

**Comment by CaMer0n** [comment]
@fizi please re-test

**Comment by fizi** [comment]
On English - ok, on Hungarian - problem same.

**Comment by fizi** [comment]
Now, perfect in both languages! Thanks!

**Comment by Moc** [comment]
I am pretty sure this issue is resolved, closing. Let me know in case there's still an issue.
