### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#2209]
Is this page working ok?

If I'm logged in, it provides an error saying I'm logged in - good.
If I'm not logged in, it redirects to last page.

On line 23, should there be an ! before (empty($pref['user_reg']) && empty($pref['social_login_active']))) to check if either of those are not empty? Presumably, if they're empty the user is not logged in, if they are populated, the user is logged in?

**Comment by rica-carv** [comment]
Mine's working as it should:
If I'm logged in, it provides an error saying I'm logged in - PLUS shows me the empty login form again (wich shouldn't...)
If I'm not logged in, it shows me the empty login form (no redirect).

**Comment by pricey1981** [comment]
strange, I don't even see the login form. I've manually edited (as a test) the core file (and also had to do similar with the login_shortcodes.php file) to get it displaying.

**Comment by rica-carv** [comment]
Just wondering, maybe somethig due to the "upgrade" process?
Or some .htaccess file bug?

**Comment by tgtje** [comment]
@rica-carv  > you mentioned (or idea triggered for a possible htaccess bug : please keep that in mind... think about the download issues.. maybe theres some correlation.. (know it is off topic, but had to mention it).

**Comment by rica-carv** [comment]
@tgtje For sure, this is not related with the download issue. The download issue was a missing trigger in PHP & GET, that is solved.
This one is trickier, since mine is working right (despite showing the login form again if i'm logged in), but for some reason it doesn't work for @pricey1981 ...
Can be many things, from the htaccess file to server issues.
I've had issues long time ago, even with different localhost servers (WAMP, XAMP, etc.)...

**Comment by pricey1981** [comment]
I tried deleting htaccess temporarily but still had the same issue.

**Comment by rica-carv** [comment]
@pricey1981 and it happens with ALL users?

**Comment by pricey1981** [comment]
@rica-carv , well, if I'm not logged in, it doesn't know I'm a user.

**Comment by CaMer0n** [comment]
@rica-carv 
pricey1981 said 

> strange, I don't even see the login form. 

@pricey1981 Which theme are you using?

**Comment by arunshekher** [comment]
Wouldn't a notice like "You are currently logged in as Main Admin." like shown in signup.php be more appropriate to avoid confusion?

**Comment by pricey1981** [comment]
Sorry, missed the replies on this. @CaMer0n I'm using a self-designed theme based on the bootstrap 3 theme

**Comment by CaMer0n** [comment]
@pricey1981 Okay, are you using a custom login template? If so, try renaming it so it isn't loaded.

**Comment by pricey1981** [comment]
@CaMer0n yes, was using a custom template. Have renamed it, but still getting the same issue

**Comment by CaMer0n** [comment]
Okay thank you.  If you have time tomorrow, maybe we can go through it via the chatroom?

**Comment by pricey1981** [comment]
@CaMer0n where are you based? US or UK? (just checking time difference - I can only normally get on in the evenings in UK)

**Comment by CaMer0n** [comment]
@pricey1981 Westcoast USA. Usually between 9am and 5pm locally.

**Comment by pricey1981** [comment]
@CaMer0n I think time difference is 8 hours then so I'll try to be on around 11am-13pm your time.

**Comment by CaMer0n** [comment]
User Registration was completely disabled. Added a message to avoid confusion.
