### ISSUE TITLE
Posting Threshhold, Rank Name and Image

### ISSUE THREAD

**Issue by mortalites** [e107inc/e107#2222]
It would be nice if you could add a custom user class that did not have User rank based on a Posting threshold. Currently the Main Admin and Admin classes are the only one's that have no threshold and an can be assigned an image.

![screenshot_1](https://cloud.githubusercontent.com/assets/24235928/21573102/a8ce35e8-ceae-11e6-84e5-96d210f43c84.png)

**Comment by Moc** [comment]
Try enabling developer mode (preferences > advanced features) and then go back to the user ranks. There should be a new link to the new area of user ranks which is in development. Is the functionality you want available there? 

(note: this new area is not finished yet, so there may be unexpected results)

**Comment by rica-carv** [comment]
@Moc Tryed with and without developer mode enabled and always ended up with the same user admin menu options:
```
     Manage
     Quick Add User
     Options
     User Ranks
     Maintenance


```

**Comment by Moc** [comment]
Ah found it, it's debug mode. Enable the debug mode, e.g. `?[debug=basic+]` and check again.

**Comment by rica-carv** [comment]
@Moc Tested and working....
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/21594834/5597b1ba-d11f-11e6-91d8-8cf6d20a86d1.jpg)

**Comment by Moc** [comment]
@CaMer0n Is it time to move this feature from experimental to stable? 😄

**Comment by CaMer0n** [comment]
@Moc haha, yeah!! Was certainly overlooked. Thanks for mentioning it.
