### ISSUE TITLE
Content lost after saving (editor)

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2224]
When I try to store something in the Admin Menu, the e107 system always deletes something.

Example want to save (Menu Editor)-( /admin/cpage.php?mode=menu&action=list&tab=2):
```
<embed src="files/uhrzeit-digital.swf" wmode="transparent" height="40" width="155"></embed>
<script src="files/datum.js"></script>
```

After saving and open the Menu Editor:
```
<embed src="files/uhrzeit-digital.swf" wmode="transparent" height="40"></embed>
<script src="files/datum.js"></script>
```

width="155" is lost, how to fix this?

- Killer0561

**Comment by Jimmi08** [comment]
I can't confirm
![image](https://cloud.githubusercontent.com/assets/5429548/21577610/67689694-cf61-11e6-9fe6-30810771ae8a.png)

**Comment by Jimmi08** [comment]
![image](https://cloud.githubusercontent.com/assets/5429548/21577671/b60d536e-cf63-11e6-91bb-109965b237a4.png)

**Comment by Killer0561** [comment]
![img_0936](https://cloud.githubusercontent.com/assets/16360582/21577880/c464eb72-cf6b-11e6-9cfa-32470f6953d6.PNG)

My Menu looks like so, i cannot find a Source Code Button to paste in.

**Comment by tgtje** [comment]
The above posted images are from wysiwyg mode : yours is plain mode (bbcode sometimes called).
Go to admin/preferences/text rendering Here also some settings for who is able to post script or html (those CAN be dangerous)... find the setting for wysiwyg and enable it.
