### ISSUE TITLE
Userclass Images feature

### ISSUE THREAD

**Issue by mortalites** [e107inc/e107#2225]
Cameron said this should already be a part of the core of e107 but I dont think its the same thing. There is an option under User class management to assign a Class Icon, but I dont see where that actually shows up. 
![screenshot_2](https://cloud.githubusercontent.com/assets/24235928/21573892/304422cc-ceb8-11e6-8987-ee79a9b1f8ad.png)

This old plugin here http://e107.org/plugins/?id=771 actually lets you add a image under the user's avatar based on what userclass they are apart of. It would be cool if you could too if a user is part of more than one class that they would get both pictures. Example if they are a Member and a donator. They would have 2 images. I think at one point I saw some shortcode that you could put in the forum topic view that would allow you to give a user a image.

**Comment by Moc** [comment]
I think there should be a shortcode which allows you to display the userclass icon? I'll look into this asap.

**Comment by rica-carv** [comment]
And why not have a Class color too, in adittion to the icon, so the user name could also be colored sitewide according to it's class?

**Comment by Moc** [comment]
I've added a shortcode for this which can be used in the User Profile (user_template.php). 

```
	/**
	 * @example: {USER_USERCLASS_ICON} returns the icons of all userclasses the user belongs to, seperated by a whitespace
	 * @example: {USER_USERCLASS_ICON: amount=1} // returns only one icon
	 * @example: {USER_USERCLASS_ICON: seperator=|} // returns the icons seperated by |
	 * @param array $parm
	 * @return string
	*/
```

**Comment by Jimmi08** [comment]
@Moc your solution is a real improvement. Thanks. Maybe excluding parm would be handy, but now I can't see where to use it. 

Online info plugin is able to color user classes and user names (see in action on wrxxy site)
Classmembership plugin is able to add badges (in meaning to get background color, not text color) to classes (I use it with user list and profile)

**Comment by Moc** [comment]
@Jimmi08 Great! I am not sure what you mean with "excluding parm", can you clarify? 

I am tempted to create a plugin for this (showing both userclass icons and colors) using a global shortcode so it can be used site wide. I still feel that this functionality is not for core, but I don't mind doing some work on it.
