### ISSUE TITLE
Enhancement for SITEDISCLAIMER

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2228]
I use this for my theme with custom plugin but it maybe is good idea for core. 

I override core shortcode this way:

```
	function sc_sitedisclaimer($copyYear = NULL)
	{
		$default = "Proudly powered by <a href='http://e107.org'>e107</a> which is released under the terms of the GNU GPL License.";
		$sitedisclaimer = deftrue('SITEDISCLAIMER',$default);
 
    $copyYear = vartrue($copyYear,'2013');
	  $curYear = date('Y'); 
	  $text = '&copy; '. $copyYear . (($copyYear != $curYear) ? ' - ' . $curYear : '');
 
	  $text .= ' '.$sitedisclaimer;        
		return e107::getParser()->toHtml($text, true, 'SUMMARY');	
	}
```	
and use in theme:
`{SITEDISCLAIMER=2008}`

this look like this:
![image](https://cloud.githubusercontent.com/assets/5429548/21579240/f89cb4a4-cfa4-11e6-9093-26e3922710e1.png)

if I use actual year, it looks like this:
`{SITEDISCLAIMER=2016}`
![image](https://cloud.githubusercontent.com/assets/5429548/21579243/1e913b58-cfa5-11e6-9803-ee8c6276e93a.png)

**Comment by rica-carv** [comment]
Shouldn't it be using the new shortcodes parm?
Like this: `{SITEDISCLAIMER: year=2016}`

`function sc_sitedisclaimer($parm = NULL)` instead of `function sc_sitedisclaimer($copyYear = NULL)`
	
`$copyYear = ($parm["year"]?:'2013');` instead of `$copyYear = vartrue($copyYear,'2013');`

**Comment by Jimmi08** [comment]
@rica-carv it was example of my code. It's custom shortcode, not core. And yes, if it would be core shortcode, it should be done your way.

**Comment by rica-carv** [comment]
@Jimmi08 Just my two cents, trying to help....

**Comment by Jimmi08** [comment]
this was solved in core 
```
	/**
	 * YYYY is automatically replaced with the current year.
	 * @return string
	 */
```
