### ISSUE TITLE
File Inspector - install.php check

### ISSUE THREAD

**Issue by ExCeLLiuM** [e107inc/e107#223]
When scaning in File Inspector it says "Missing Core File" for install.php. But we manually delete it after installations. So that error so silly :)

**Comment by tgtje** [comment]
Knowing fileinspector results are not 100% i can not find install php reported as a missing core file after deletion ( file dates : 25-5-2015 and 1 older version) ...Solved ?:

**Comment by Moc** [comment]
I suggest to make the fileinspector working for the next release. It's a very useful tool to debug issues which relate to missing/corrupted/changed files.

**Comment by CaMer0n** [comment]
@Moc , @lonalore - If either of you have any idea as to why the non-core files are not being added/counted in the summary (on the right, when in tree mode) , I'm all ears.

**Comment by lonalore** [comment]
Is [this script](https://github.com/e107inc/e107/blob/master/e107_admin/fileinspector.php#L1560-L1591) what you think? :)

**Comment by CaMer0n** [comment]
@lonalore Yes, exactly. To replace this code with jquery. (also to make smooth animation transitions)

**Comment by CaMer0n** [comment]
I believe this original issue was corrected. Please re-open if necessary.
