### ISSUE TITLE
Auto newsimage size stopped working

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2230]
It was working previously, now with latest update it stopped giving a auto sized image:
`{SETIMAGE: w=auto&h=auto}{NEWSIMAGE}`
Now it returns this (HTML):

```
<img class="news_image news-image img-responsive img-rounded news-image-1" src="/site_spt/media/img/0x0/2016-04/livrocatedraisctt2016.png" alt="livrocatedraisctt2016.png" srcset="/site_spt/media/img/0x0/2016-04/livrocatedraisctt2016.png 0w" style="border:0px" width="0" height="0">
```

Furthermore, if i use this: `{SETIMAGE: w=auto&h=auto}{NEWSIMAGE: type=tag&item=1}`
It returns me dots before and after the tag:
```
.<img class="news_image news-image img-responsive img-rounded news-image-1" src="/site_spt/media/img/0x0/2016-04/livrocatedraisctt2016.png" alt="livrocatedraisctt2016.png" srcset="/site_spt/media/img/0x0/2016-04/livrocatedraisctt2016.png 0w" style="border:0px" width="0" height="0">.
```

P.S.: Since news is already in the plugin folder, why are it's shortcodes in core? IS there any reason for not everything be under the plugin folder?

**Comment by Moc** [comment]
> P.S.: Since news is already in the plugin folder, why are it's shortcodes in core? IS there any reason for not everything be under the plugin folder?

The news is kind of a hybrid version, in between core and plugin. In my opinion it should be turned into a standalone plugin (ie. move everything out of the core to its plugin folder), but I guess this is for further down the road.

**Comment by Moc** [comment]
@rica-carv Is this issue still relevant?
