### ISSUE TITLE
Bootstrap linking back to e107 insecurely for graphics...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#2233]
Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/thumb.php?aw=200&ah=160&src=e_PLUGIN/addons/addon_images/000852_preview_frontend.png'. This content should also be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/thumb.php?aw=200&ah=160&src=e_PLUGIN/addons/addon_images/000830_preview_frontend.png'. This content should also be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/thumb.php?aw=200&ah=160&src=e_PLUGIN/addons/addon_images/000829_preview_frontend.png'. This content should also be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/e107_plugins/addons/addon_images/000853__icon_128.png'. This content should also be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/e107_plugins/addons/addon_images/000846_youtube_128.png'. This content should also be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://<redacted>/e107_admin/admin.php' was loaded over HTTPS, but requested an insecure image 'http://e107.org/e107_plugins/addons/addon_images/000841_icon_128.png'. This content should also be served over HTTPS.

Why are these graphics not a part of the base software and linking back to you?  I see the benifit in the increased website hits but on my SSL site this is causing a mixed mode content problem.  Can you explain why these are not just local?

Thanks 
-D-

**Comment by CaMer0n** [comment]
Are you using the latest version from Github?
