### ISSUE TITLE
Frontend Inline-Editing

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2237]
The Frontend Inline-Editing set the no one (inactive) but the edit icon appear on the front page in cMenu (custom menu).

**Comment by Jimmi08** [comment]
But inline editing is for textarea fields in news for example (content, body and extendend fields). I suppose that those edit icons are for admins.

**Comment by fizi** [comment]
Yes, for admins and in the template. Sorry. You can delete or close the issue.

**Comment by fizi** [comment]
Sorry, I don't found it. Where I can delete it? I known for admin but it bothers me.

**Comment by Moc** [comment]
Can you show a screenshot of what you are referring to please?

**Comment by fizi** [comment]
This is, no need for me:
![edit](https://cloud.githubusercontent.com/assets/86780/21592987/e719a010-d112-11e6-8e1c-0a5c4e56d6fa.jpg)

**Comment by CaMer0n** [comment]
Please inspect the icon and share the css used on it.

**Comment by Moc** [comment]
Also, clear the e107 and browser cache. That should shrink the size of the icon back to normal.

**Comment by fizi** [comment]
The problem not the size, no need for me the icon. How I delete it from cmenu?

**Comment by Moc** [comment]
Currently not possible but will be added soon

**Comment by fizi** [comment]
Thanks!

**Comment by CaMer0n** [comment]
Recently modified. Closing.
