### ISSUE TITLE
FAQs plugin - syntax error after latest changes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2238]
Latest github. FAQs plugin.

`Parse error: syntax error, unexpected ';' in ...\e107_plugins\faqs\faqs.php on line 617`
`Parse error: syntax error, unexpected ';' in ...\e107_plugins\faqs\faqs.php on line 620`

error is related with this 
![image](https://cloud.githubusercontent.com/assets/5429548/21591249/a497be12-d102-11e6-9f8f-959d9c2431d3.png)

after replaced older lines, FAQs works.
https://github.com/e107inc/e107/commit/340e2ed73260b323b2d858b76477a5601d2b6bf1

**Comment by MikeyGMT** [comment]
Looking at it now... I think I spotted what's wrong.
