### ISSUE TITLE
Proper display for Random Avatar Menu with V2*.*

### ISSUE THREAD

**Issue by oui3kings** [e107inc/e107#2240]
Plugin as is renders nothing.

Temp fixes so far - 1. add global $pref; at line 23 in menu file. Then menu will be rendering (thx Jimako)
Cameron adjusting core to resolve
2. Change $text .= '<img s**"'.avatar($user['user_image']).'" /><br />'; 
to
$text .= avatar($user['user_image']).'<br />';

typo too. instead switch ($pref['rndava_dispaly_name']) there should be switch ($pref['rndava_display_name']) - line 48 (spotted by Jimako)

**Comment by Jimmi08** [comment]
©Moc this can be closed, everything else (look) is third part plugin related, not core

![image](https://user-images.githubusercontent.com/5429548/32247931-4c0de198-be84-11e7-8ffd-700b4345d58e.png)
