### ISSUE TITLE
enhancement - to be able template menu caption

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2247]
if menu caption is defined in template  (could be empty string)
`$MENU_TEMPLATE['default'][caption']`  = ''; 

this code in renderMenu() function:
```
			$caption = (vartrue($page['menu_icon'])) ? $tp->toIcon($page['menu_icon']) : '';
			$caption .= $tp->toHTML($page['menu_title'], true, 'parse_sc, constants');
			
			if(vartrue($page['menu_template'])) // New v2.x templates. see core/menu_template.php 
			{
				$template = e107::getCoreTemplate('menu',$page['menu_template'],true,true);	// override and merge required. ie. when menu template is not in the theme, but only in the core. 
				$page_shortcodes = e107::getScBatch('page',null,'cpage');  
				$page_shortcodes->setVars($page);
				  
				$head = $tp->parseTemplate($template['start'], true, $page_shortcodes);
				$foot = $tp->parseTemplate($template['end'], true, $page_shortcodes);
				  
			// 	print_a($template['body']);           
				$text = $head.$tp->parseTemplate($template['body'], true, $page_shortcodes).$foot;
			// 	echo "TEMPLATE= ($mpath)".$page['menu_template'];

				$ns->setUniqueId('cmenu-'.$page['menu_name']);
				$caption .= e107::getForm()->instantEditButton(e_ADMIN_ABS."cpage.php?mode=menu&action=edit&tab=2&id=".intval($page['page_id']),'J');

				$ns->tablerender($caption, $text, 'cmenu-'.$page['menu_template']);
			}
```

could load it similar way as it load start and end templates. 

This could reduced workaround templating and numbers of styles in tablestyle() function.  
Thanks

**Comment by rica-carv** [comment]
Indeed.
Furthermore, it would enable to template individually every menu, not globally via the tablestyle function.
And if a plugin menu has no class or id (that's possible!), tablestyle function is unusable....

Also, this ideia can provide a way to custom captions text, instead of the default ones, and prevent "hacks" [like this one](https://github.com/e107inc/e107/blob/master/e107_plugins/online/online_menu.php#L140)...

**Comment by rica-carv** [comment]
@CaMer0n A custom menu caption example, from my custom plugin "login" form:
![Example menu caption](http://www.e107help.org/?qa=blob&qa_blobid=13385412405266670964)

**Comment by CaMer0n** [comment]
@rica-carv I believe the proposal was regarding captions on Pages/Menus?

**Comment by rica-carv** [comment]
@CaMer0n Humm, i thought it was only regarding menu captions... @Jimmi08 ?

**Comment by Jimmi08** [comment]
Originally it was for $MENU_TEMPLATE, so for custom menus.  But from look at @rica-carv example it's the same for $ONLINE_TEMPLATE. 
If output ($text - f.e. start, body, end) is from new way template, there $caption should be from the same source. 
But menus are most used for styling site.

**Comment by Jimmi08** [comment]
Next example:
$caption for login page.  Now hardcoded: 
`$login_message = SITENAME; //	$login_message = LAN_LOGIN_3." | ".SITENAME;`
It would be nice to have $LOGIN_CAPTION in template to be able override this.

**Comment by CaMer0n** [comment]
function tablestyle($caption, $text, $id)
    {
        if($id == 'login_page')
        {
            echo "My Caption"; // render whatever caption the way you want. 
            echo $text; 
            return null; 
       }
    }

**Comment by Jimmi08** [comment]
It can be solved now, this is not bug.  I prefer to use no caption in tablestyle() and put Caption itself in start of template part.
The point was not to use tablestyle() for this.  Using just template file allow to reuse the same code with easy.  
You can close this if this is not planned.
