### ISSUE TITLE
Is $eMenuActive working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2250]
I'm trying to use the $eMenuActive variable to check if a menu is active or not, inside the e_header.php file, [just like this one here](https://github.com/e107inc/e107/blob/afbe20614b46805fc8fb169f5dd0a200bf600062/e107_plugins/chatbox_menu/e_header.php#L5).

But for some strange reason, $eMenuActive always return null...
I've tryed severall ways: `$eMenuActive['chatbox_menu'], $eMenuActive['my_menu'], $eMenuActive['inexistent_menu'], $eMenuActive`
Always the same return: null...

Is it working as intended?

**Comment by Moc** [comment]
Isn't there another method like e107::getMenu()->isActive or something? I thought I saw something like this.

**Comment by Moc** [comment]
`e107::getMenu()->isLoaded();` 

Currently appears to be a bug still which does not return the proper value. Closing this one in favour of #1871
