### ISSUE TITLE
can't remove end date from news

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2252]
I somehow get end date filled

![image](https://cloud.githubusercontent.com/assets/5429548/21726519/4b856926-d43d-11e6-9beb-ed3296709bc5.png)

I deleted it 
![image](https://cloud.githubusercontent.com/assets/5429548/21726528/5b761146-d43d-11e6-8df0-390d5ba3242e.png)

After saving (update button) date is back

![image](https://cloud.githubusercontent.com/assets/5429548/21726572/94bbb7c6-d43d-11e6-8d8f-7c0fa2868fef.png)

**Comment by CaMer0n** [comment]
@lonalore I'm assuming we just need a check for an empty text value and then a reset of the hidden value? (in `e107_web\js\bootstrap-datetimepicker\js\bootstrap-datetimepicker.init.js` )

**Comment by CaMer0n** [comment]
@Jimmi08 I think this was fixed recently.. yes?

**Comment by Jimmi08** [comment]
It works now. Thank you to all.
