### ISSUE TITLE
Notify Email - Session Events -user edits profile

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#2257]
Would it be possible to change the User views profile: into User edits profile because looking at a profile does not say much, when a user changes his profile it could be important (adress or something) 

Could you consider this?

Regards Alex

**Comment by CaMer0n** [comment]
@Alex-e107nl This should do it. Please test and let us know how it goes.

**Comment by Alex-e107nl** [comment]
Yessss it works! THX
![edit_user_mail](https://cloud.githubusercontent.com/assets/11962513/21762712/9b6379c8-d65a-11e6-80c8-247f141b635d.jpg)

Maybe the array should not me seen but the rest is perfect!

Alex
