### ISSUE TITLE
No avatar after the latest Github update today

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2259]
After the latest Github update today I lost the avatar/foto includet in the members info.

![lostavatar](https://cloud.githubusercontent.com/assets/1757346/21755009/4f69664c-d5d1-11e6-9e23-833c628979c8.JPG)

**Comment by Moc** [comment]
Related to #1748

**Comment by tgtje** [comment]
Having the latest files in use, in first upload of avatar, no success. Tried finding cause (it did keep the image url at thumb.php.. waited and tested here and there : made a second upload > working directly (path/media) However : on top nav icon = is img rounded/circle icon NOT the avatar   (not BS, not in Voux). (and if intended ??? as posted members info? (user php/settings) > user profile now has all ( working after second go),

admin/user/status manage bar (option enabled) avatar is not present> blank (if none : txt = none) This one ok ? or img displayed?

**Comment by Moc** [comment]
@Norwayman Please test again using the latest files :)

**Comment by Norwayman** [comment]
@Moc @tgtje :  I confirm that after I used the latest files the avatar/foto came back like normal. Thanks guys!  You can now close this! :)

**Comment by CaMer0n** [comment]
Thanks @Norwayman
