### ISSUE TITLE
Add wrapper to different shortcode returned values..

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2261]
Let's say i have a shortcode that only returns numeric values.
Can it be a way to for instance, add a wrapper if the value is 0 and another if the value is different for 0?

**Comment by Moc** [comment]
I don't think I understand your question. Can you provide an example if the question is still relevant? Thanks!

**Comment by rica-carv** [comment]
Err, it's been more than a year, but let me see if i can recall....
Imagine you got a shortcode that only returns numeric values: 0, 1, 2, 3, 100, 1000, etc...
Intead of complete overwritte a shortcode at theme level, can't it be a way in wrapping that value, with the shortcode wrapper, so that for instance, the value 0 shows in bold, and the 100 in italic, for instance?
