### ISSUE TITLE
Wrapper is also applied to parametized shortcodes

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2263]
I've got this shortcodes:
`{TEST}{TEST:type=text}{TEST:type=number}{TEST:format=long}`
If in template, i define this wrappers:
```
$TEMPLATE_WRAPPER['TEST']="Wrapping ORIGINAL {---}";
$TEMPLATE_WRAPPER['TEST:type=text']="Wrapping TEXT {---}";
$TEMPLATE_WRAPPER['TEST:type=number']="Wrapping NUMBER {---}";
$TEMPLATE_WRAPPER['TEST:format=long']="Wrapping LONG {---}";
```

I always end up with `$TEMPLATE_WRAPPER['TEST']="Wrapping ORIGINAL {---}"` wrapping all four shortcodes...
If i remove `$TEMPLATE_WRAPPER['TEST']="Wrapping ORIGINAL {---}"` from template, i do get the final three shortcodes wrapped with the indicated ones, but got no wrapping possible on the first one...
What am i doing wrong here?

**Comment by tgtje** [comment]
_Not into this i admit_, but looking thriugh files should it not be $TEST_WRAPPER['TEST'] = sc style ?
or like around line 907 of handlers/shortcode handler php

**Comment by CaMer0n** [comment]
Add a fake query to the first one: TEST:bla=bla and the problem is solved - you can style each one. 
 This is not a bug but a feature, See line 83 of the default news_template.php for usage example.

**Comment by rica-carv** [comment]
@CaMer0n Humm, thanks, i'll give it a try and test...

**Comment by rica-carv** [comment]
@CaMer0n Just tested, the `TEST:bla=bla` doesn't work, it is not even applied to any shortcode starting with `TEST`.....

**Comment by rica-carv** [comment]
@CaMer0n Your tip works. Sorry, it was my fault. Thanks...
