### ISSUE TITLE
User Extended Field for Date does not allow entry

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2265]
Field was working, but since a recent GitHub sync (not sure when) the field stopped allowing users to either change this in their profile or allow users to specify at signup. As we have it compulsory for signup no users can sign up. Previously users had to enter YYYY-MM-DD for it to accept the date. However, you can edit this field from User Admin, where it shows a calendar in addition to typing the date in
![extended user fields - manage - admin area three percenters mcc 2017-01-10 13-28-54](https://cloud.githubusercontent.com/assets/15772899/21808250/6117f9fc-d73a-11e6-8a12-ca3c1611c233.png)
 (attachment 2)
![users - manage - admin area three percenters mcc 2017-01-10 13-39-58](https://cloud.githubusercontent.com/assets/15772899/21808258/68fc5942-d73a-11e6-827c-5ace82475a05.png)

**Comment by CaMer0n** [comment]
I was unable to reproduce this. Which theme are you using on the frontend?

**Comment by martyshep** [comment]
Using default bootstrap3

**Comment by martyshep** [comment]
I've tried with different browsers, get the following error when I click Submit with any value in the field..

Error
19 - Birthday Enter YYYY-MM-DD is required: Empty value

**Comment by CaMer0n** [comment]
@martyshep Could you please share the URL to your signup page? (or privately on gitter)

**Comment by CaMer0n** [comment]
Please disable js/css cache. Does it help?

**Comment by martyshep** [comment]
Disabled js/css cache, now working ok, thank you @CaMer0n

**Comment by CaMer0n** [comment]
Any thoughts on this @lonalore ? When the js is cached an error is returned in the console, preventing the other js from executing.

**Comment by lonalore** [comment]
Sounds like a concatenation issue during merging JS files into one.

**Comment by Moc** [comment]
@lonalore Would you mind looking into this to see if you can provide a fix? thanks 👍

**Comment by CaMer0n** [comment]
@SimSync How's your javascript skills? Reckon you can fix this one?

**Comment by SimSync** [comment]
@CaMer0n I'll give it a try.
So this error happens when js is cached and only in frontend? Or admin area too?

**Comment by CaMer0n** [comment]
@SimSync Thank you! :+1:
