### ISSUE TITLE
Adding page tabs

### ISSUE THREAD

**Issue by cainey** [e107inc/e107#2269]
Good evening all,
Firstly, good work really starting to enjoy e107 not all my problems are fixed :D 

I have v2 using bootstrap3 and would like to add page tabs to the thread page
[http://hmp-clan.co.uk/Capture.PNG](http://hmp-clan.co.uk/Capture.PNG)
i would like to add the tabs just under the starters name if possible.

can this be done?

Thank you,

**Comment by CaMer0n** [comment]
You would need a custom shortcode and you could use e107::getForm()->tabs() to generate the tabs. 
See: https://e107.org/developer-manual/classes-and-methods#forms

**Comment by Moc** [comment]
I am assuming this question has been answered. If you still require more assistance, please let us know :)
