### ISSUE TITLE
Custom Extended User Fields missing

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2270]
My Custom Extended User Fields are missing. I have set it for all members, but they do not appear in the user settings and on the user profiles. Is there any way to fix this?

**Comment by Jimmi08** [comment]
Can be related?
https://github.com/e107inc/e107/issues/2017

**Comment by Moc** [comment]
Which theme are you using?

**Comment by Killer0561** [comment]
i use the theme*dragonhead* from free-source.net, but this site exits not longer.

**Comment by Moc** [comment]
Does this theme use a custom user_template.php file? You can find this in your theme folder. If yes, the extended userfields shortcode may be missing. 

You can confirm this by temporarily switching to the Bootstrap 3 theme, I suspect that the fields will appear then.

**Comment by Killer0561** [comment]
Found the custom user_template.php file. Renamed and now it works :) But how i can rework the user_template.php file for e107 v2.0?

**Comment by Moc** [comment]
Please copy the contents of the user_template.php in a SECRET gist and post the link to Cameron or me on Gitter. I am asking for the link this way because I don't want to make it public (since it's a premium theme).

**Comment by Killer0561** [comment]
I am now use the default user_template.php, need not longer the custom file. But the custom extended user fields are not displayed in usersettings.php (allready use the default template).

**Comment by Moc** [comment]
Do you use a custom usersetttings_template.php? Please test using the Bootstrap 3 theme.

**Comment by Killer0561** [comment]
The Bootstrap 3 theme display me custom extended user fields, but my theme „dragonhead“ not. No custom usersettings_template.php found in my theme dir.

**Comment by Moc** [comment]
Please contact me on Gitter: https://gitter.im/Moc or https://gitter.im/CaMer0n
