### ISSUE TITLE
Insert/edit image and Insert/edit media not functioning 

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2271]
on latest Git. Worked a few weeks ago as I embedded a youtube video in a forum post, can't get forum plugin to accept it now

**Comment by Moc** [comment]
> 'Media embed handler threw unknown error.' displayed

Can you please show a screenshot?

**Comment by martyshep** [comment]
If I go to Insert/edit media and put an embed link in from YouTube into the Embed tab in the window then it does not do anything when I click OK, as in it doesn't work nor throw error, just sits there. If I swap to the General tab it shows the URL to the YouTube video without the embed link detail, but still will not click OK. 
![forum - three percenters mcc 2017-01-13 10-15-27](https://cloud.githubusercontent.com/assets/15772899/21926606/68e47b00-d97a-11e6-98e7-ee67133b1bda.png)

However if I do it the other way, by pasting the URL from YouTube directly into the General Tab, this brings up the red error message shown in the second image before even pressing OK.  If I then swap to the Embed tab, I see the embed code displayed.
![forum - three percenters mcc 2017-01-13 10-16-19](https://cloud.githubusercontent.com/assets/15772899/21926620/73a0adb6-d97a-11e6-87f2-723683f72b04.png)

**Comment by tgtje** [comment]
i confirm this behaviour: related #1173 but : 
 (why the log way around : that is why mediamanager is for;  use 
![vidico](https://cloud.githubusercontent.com/assets/1811857/21937977/a05b8562-d9b9-11e6-89bb-127c00defdca.png) (most right one; media man..video)
(url  to use = addressbar url) or DIRECTLY in sourcecode (wysiwyg mode) ?
Alternatibe (bbcode AND wysiwyg editor) you can use directly the following

[   video    ]_j0b9syAuIk.youtube[    /    video]  please look at the 'build'.
[video]_j0b9syAuIk.youtube[/video]

**Comment by CaMer0n** [comment]
Looks like an issue in TinyMce.

**Comment by tgtje** [comment]
Probably is, but i keep wondering how media etc is combined throughout.... tiny itself always talks about the plugin media (which isn't in the pack for a realy long time..)

**Comment by durandalwoz** [comment]
I just fixed this by changing 'media_dimensions' to true in e107_plugins/tinymce4/templates/mainadmin.xml, member.xml and public.xml

**Comment by martyshep** [comment]
@durandalwoz Confirmed, thank you. Doing same has restored the Dimensions settings box for me which is ticked with constrain proportions by default. I can now paste in youtube links as I did before. This is the item that changed sometime recently, I couldn't remember what looked different, but it was this, the dimension settings 👍

**Comment by kraladam** [comment]
I still get the same error how did you fix it ?

**Comment by martyshep** [comment]
I edited my production server e107_plugins/tinymce4/
templates/mainadmin.xml, e107_plugins/tinymce4/templates/member.xml and
e107_plugins/tinymce4/templates/public.xml as per durandalwoz comment. I
will try to edit a local fork of e107 and do a pull request. I've done it
before on Github, can't remember how I did it, I am not experienced as I am
not a developer, but it would be fun to try, so you may see the fix end up
in a Commit on the master. I will credit durandalwoz

**Comment by Moc** [comment]
Closed through #2339
