### ISSUE TITLE
e_ADMIN_ABS has an extra slash, e_ADMIN has no problem

### ISSUE THREAD

**Issue by JohanKlos** [e107inc/e107#2274]
See image below. The lines are from .\e107_core\shortcodes\batch\admin_shortcodes.php

![e107_213_admintheme_issue](https://cloud.githubusercontent.com/assets/639844/21954110/b3fb091e-da48-11e6-8397-4b8c7728b8b5.jpg)

Because of the extra slash, the options listed won't work. There's likely to be other places where the issue arises as well.

**Comment by tgtje** [comment]
Note : the shortcode file HAS been changed 12 days ago... (maybe it is already internally solved)
How is your website url (domain).. ?

it should look like  (second/third) marked .........ef="/domain/e107_admin/admin.php?logout"><i class="S16 e-logout-16"></i>Logout</a>
Check your url behaviour (inspector used?) by hovering the links itself. All cases it should post/display the normal absolute (full) url.(clue?)

(case lines 1708,1719,1730 )

**Comment by JohanKlos** [comment]
My admin settings have /e107/ as site URL.
When I hover over it, it shows the complete URL but with two // as you can see in the screenshot. I've replace the admin_shortcodes.php file with the one from github, but the issue hasn't changed.

When I select options in the admin menu, I see the adress like http:/mysite.co.uk/e107//e107_admin/prefs.php

I've used inspect, it's where the screencap is from :)

**Comment by tgtje** [comment]
Sorry to mention, but not only the sc file has te be updated, all interacting files too. 1 change here..influence on another.. So i hope you did that too. Going to test a new install, will test the issue there too.

**Comment by JohanKlos** [comment]
I have, thank you for your help! It's a test install, so I've just overwritten everything except the config file. Still the same problem.
The session.save_path is not writable due to my host's security measures, could that be it?

**Comment by tgtje** [comment]
Do not think so, but who knows (also waiting for others to reply)
This could be done to test (post from dev) https://github.com/e107inc/e107/issues/1245#issuecomment-160783447  (30 nov 15)

**Comment by CaMer0n** [comment]
@JohanKlos Please try this url:  e107_admin/admin.php?[debug=paths+]
..then scroll down to the footer and check e_ADMIN, e_ADMIN_ABS, e_SUBDOMAIN and e_DOMAIN.

**Comment by JohanKlos** [comment]
Done, thanks! I've figured out the problem, it was me (duh).
As I did what you said, I decided to check the url for the logout, I noticed that the link was suddenly correct.

The difference was that I copy/pasted your link to get to the right place. Normally, I use a sitelink to get to admin, and I had made a typo in the sitelink URL, which contains two //.
As you can see from the screenshot in the top post, some links were affected, others weren't.

Thank you for your time and sorry for your trouble!

P.S. I also noticed that I couldn't change admin themes anymore, though I could still change the site theme. I thought that was related to the // problem, but that still persists, so it must be something else. I'll look into it and make another issue if I can't figure it out.

**Comment by CaMer0n** [comment]
As of v2.x the admin theme is locked in. There were just too many things that could go wrong if another theme was used.

**Comment by JohanKlos** [comment]
Ah, ok, that makes sense, 
Maybe that image needs to be removed from the admin section then, because I thought it was something wrong in my configuration and/or install ;)

I haven't looked, but are there plans to allow for different colour schemes of the one admin theme? That's something I could help with if needed.

**Comment by rica-carv** [comment]
> As of v2.x the admin theme is locked in. There were just too many things that could go wrong if another theme was used.

Earlier versions of V2.x still allowed it's change....

**Comment by Moc** [comment]
> Earlier versions of V2.x still allowed it's change....

Maybe in alpha or beta releases, but I highly doubt this was possible as of the first stable release (I may be wrong). Anyhow, it doesn't really matter to this issue. 

Closing it, as it appears to have been invalid.
