### ISSUE TITLE
White page/ unable to login

### ISSUE THREAD

**Issue by cainey** [e107inc/e107#2275]
OOOoo its me again,
this morning my site was running well and has been since @CaMer0n support the last major error.
I have gotten home and now im greeted by a blank page.
I have read some of the other posts but they come down to updating and i think i have the newest update.

I'v not really used Github before so i might be missing something.

The site is using bootstrap3 with some alterations, the sub domains are working fine.

Apache/2.4.7 (Ubuntu) mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.20 OpenSSL/1.0.1f

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.5.53-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10

Server charset: UTF-8 Unicode (utf8)

regards,

**Comment by cainey** [comment]
sorry i have tried on the following, IE/Chrome and iceweasel,  its all the same.
like i say its been fine for a while now and nothing has been changed on the site lately.
I', worried about making many changes and updates because of the issues i have had in the past.
the site was a fresh install, new server, i have also spoken with the other admins and they have now made any changes also.

**Comment by cainey** [comment]
I have define('e_DEBUG', true); in the cfg and on visiting the site, Your IP is banned!
now there are multiple people who have this. it stops me logging in to admin

**Comment by cainey** [comment]
i have people who have not been to the site before test it and it does the same for them.

**Comment by Moc** [comment]
@cainey This issue is now resolved right?
