### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2281]
If I set the user comment on the profile page (admin area)....the right menu area go below the news. Maybe miss the close div from it. If I disable the user comment, the page appears normally (not allowed user comment).  Where the comments on other pages no problem, only on profile page.
I think the problem in the user_template.php:
`$USER_WRAPPER['view']['PROFILE_COMMENTS']       = '<div class="panel panel-default clearfix">{---}';
	$USER_WRAPPER['view']['PROFILE_COMMENT_FORM']   = '{---} </div>';`

If I make:
`$USER_WRAPPER['view']['PROFILE_COMMENTS']       = '<div class="panel panel-default clearfix">{---}</div>';
	$USER_WRAPPER['view']['PROFILE_COMMENT_FORM']   = '<div>{---} </div>';`

page work normally.

**Comment by Moc** [comment]
@CaMer0n Is the above fix appropriate? If yes, I'll commit

**Comment by fizi** [comment]
If I allow user comment the right column go below the left column (not work).

**Comment by CaMer0n** [comment]
@Moc The code looks good.
