### ISSUE TITLE
User forum posts count not displayed correctly in user profile for some users.

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2284]
Forum posts count displayed in user profile does not get updated after a user start a new topics in a freshly installed forum. 

Strangely enough topic replier's forum post counts show up correctly. It may be a pattern I just thought up but for some users their forum post count remain 0 ( 0% ) even after their forum posts.

Admin > Forum > Tools > Recalculate user forum posts counts fixes the count. 

 I was tracking this issue for a week can reproduce it in today's github fetch as well.

**Comment by Moc** [comment]
@arunshekher Is this issue still occurring?

**Comment by arunshekher** [comment]
@Moc I’m devoid of a testing environment and proper internet awhile to give any feedback, will reply back as soon as I’m able to.

**Comment by Moc** [comment]
@arunshekher No rush, thank you for the quick reply.

**Comment by arunshekher** [comment]
@Moc, The issue still persists, I tested on a fresh install done yesterday.

Apparently it happens only for the site Admin(first user).

Other users' (created by admin) posts counts are displayed correctly in their profiles irrespective  of the fact that they are creating a new topic or replying to a topic created by admin or another user.

**Comment by Moc** [comment]
Cannot reproduce this on PHP 7.3. 

Clean install
Forum installed
Parent > Subcat created

Posted a new topic as Site Administrator (user created during install). `Forum posts` correctly shows up as `1 (100%)` in the User Profile.

**Comment by arunshekher** [comment]
Thanks @Moc, I'm closing the issue. Though I'm yet to test on a fresh install I'll report if I encounter it again.
