### ISSUE TITLE
All Forum Posts links from userposts.php does not correctly resolve.

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2285]
Links to user forum posts from userposts.php does not resolve the expected forum threads. 

I'm sorry if it already has been posted. A quick search couldn't find any such issues reported.

**Comment by CaMer0n** [comment]
Please re-test. Thank you @arunshekher !

**Comment by arunshekher** [comment]
You're welcome Cam. I can no longer reproduce the issue after the commit 17ef4494204fb69c1b5 in my tests with limited number of dummy users in new installation. Didn't test yet in an 1xxx upgraded installation).

Links to all forum posts from userposts.php resolve properly now.

**Comment by CaMer0n** [comment]
Cheers. Thank you! I'll close this, but please feel free to reopen if necessary.
