### ISSUE TITLE
Unsuitable System Information after PM send.

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2286]
System message says:

"System Information
You are not allowed to send attachments
PM Sent to user: siteUser"

I this case PM attachment is not on Using default PM Prefs). User is not offered to attach anything in his UI. And user did not attach anything with PM.

**Comment by CaMer0n** [comment]
Sounds like a possible LAN messup. @MikeyGMT @yesszus ?

**Comment by Moc** [comment]
No, it's jus not checking for the 'allow attahments" preference being set: https://github.com/e107inc/e107/blob/b8245793544fc1ba644dde7adfb3af6773809e00/e107_plugins/pm/pm.php#L537

**Comment by Moc** [comment]
Should be fixed now, please confirm

**Comment by CaMer0n** [comment]
Thanks @Moc !

**Comment by arunshekher** [comment]
Can no longer reproduce the issue after the commit 69d2d283f9dda6ca205

Only tested in a new installation. Thank you very much.
