### ISSUE TITLE
Debug message forum

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#2287]
Message is Systeem Debug
Couldn't load language file: e107_plugins/forum/languages/Dutch/English_front.php

So e107 is looking for an English language file in the Dutch folder...  something goes wrong :-)

Alex

**Comment by Moc** [comment]
is this everywhere on the forum or on a specific page (e.g. view_forum or view_topic)

**Comment by Moc** [comment]
Reproduced. Looking into a fix.

**Comment by Moc** [comment]
Error in the debug message. Will correct it.

**Comment by Moc** [comment]
This should now be fixed. Please let me know if it isn't.
