### ISSUE TITLE
Do not look for words in Cyrillic

### ISSUE THREAD

**Issue by HiTZz123** [e107inc/e107#2288]
Search Engines Do not look for words that are the Cyrillic

**Comment by HiTZz123** [comment]
How can I fix the problem?

**Comment by Moc** [comment]
This is probably a bug in the code and needs to be fixed by a developer. We'll provide updates as soon as possible.

**Comment by Moc** [comment]
Tested and confirmed. There is an issue here. Fix will be provided asap.

**Comment by Moc** [comment]
Bug still present when using these settings:

- Search sort method: php 
- Only match whole words: on/off (both)

**Comment by Moc** [comment]
I believe this has been fixed when using the MySQL search method.
