### ISSUE TITLE
Multi-language support for plupload

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#2290]
Add translations "e107_web/js/plupload/i18n" this used by Media Manager.
How to change this default languages?

https://gist.github.com/yesszus/d5b8fab89ee69237240ac2fbdde83ae9#file-header-php-L104
online 104 - 105

**Comment by CaMer0n** [comment]
Please update and see if this works for you.

**Comment by yesszus** [comment]
Big thanks @CaMer0n!
Work for me without errors.

**Comment by CaMer0n** [comment]
Great! 👍

**Comment by yesszus** [comment]
@CaMer0n it only works under v 2.1.8 (git)

Current:

`$plUpload = '{e_WEB}js/plupload/i18n/' . e_LAN . '.js';

	if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))
	{
		e107::js('footer', $plUpload, 'jquery', 5);
	}`  this is don't work for me.

Older:

`$plUpload = 'plupload/i18n/' . e_LAN . '.js';

	if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))	
	{
		e107::js('core', $plUpload);
	}`  tested and this is work for me.
Pls try this!
