### ISSUE TITLE
How add vars to e_shortcode?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2293]
How can we add vars to e_shortcodes, as we do with "regular" shortcodes files?
Can it be donne?
Thanks...

**Comment by Moc** [comment]
@CaMer0n Ideas?

**Comment by CaMer0n** [comment]
@rica-carv Did you work this out? If not, would you mind elaborating?

**Comment by rica-carv** [comment]
@CaMer0n No, i haven't investigated it more, to speak frankly. I'll try to see if i can figure out something, but not soon...
