### ISSUE TITLE
newforumposts_menu - Avatar size

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2294]
I updated my site from Github.
I see on the newforumpost menu that the avatar size not good.
I have custom layout on the homepage and the forum page (news is default) 
Example:
1. Avatar size on the news page
`<img class="img-circle user-avatar user-avatar-online" alt="ap_1_him4.gif" src="/media/avatar/40x0/upload/ap_1_him4.gif" width="40">`

2. Avatar size on the homepage
`<img class="img-circle user-avatar user-avatar-online" alt="ap_1_him4.gif" src="/media/avatar/350x200/upload/ap_1_him4.gif" width="350" height="200">`

3. Avatar size on the forum page
`<img class="img-circle user-avatar user-avatar-online" alt="ap_1_him4.gif" src="/media/avatar/100x0/upload/ap_1_him4.gif" width="100">`

It's very interesting
On the home page image size configured in the portfolio - theme.php
`{SETIMAGE: w=350&h=200&crop=1}
{GALLERY_PORTFOLIO: placeholder=1&category=2&limit=12}`

On the forum page image size configured in the template - forum_viewtopic.php
`{SETIMAGE: w=100&h=0&crop=0}`

It seems that the size of the avatar on the site following the set image size.
Interesting. :)
I nothing put into the css file, and I not configure the avatar image.
As if somehow the avatar inherit an image size.

**Comment by CaMer0n** [comment]
Yes, this is how `{SETIMAGE}` works. It determines image and avatar sizes. Please update and see if it helps - I have reset the size back to 40 if a width of over 250px is detected.

**Comment by fizi** [comment]
Work on home but not work on forum pages.

**Comment by rica-carv** [comment]
Try to put a {SETIMAGE} shortcode before the avatar in the forum template, ie: {SETIMAGE: w=100&h=100}{AVATAR}

**Comment by fizi** [comment]
The problem not with forum avatar. The problem with the avatar in the newforumpost menu avatar. This menu in menuarea. This below the main content.

**Comment by CaMer0n** [comment]
Place {SETIMAGE} inside theme.php where your sidebar begins.

**Comment by fizi** [comment]
I put `{SETIMAGE}` before footer and on all pages avatar width: 100px. I don't know from where get this width. If I put `{SETIMAGE: w=40&h=40&crop=1}` in this way the newforumpost menu avatar ok...but if I active to this menuarea example: other news menu...the news-image width will 40px? In this way I need always rewrite the theme.php, if I want active another menu to this menuarea?

**Comment by rica-carv** [comment]
@fizi You can use the tablestyles to make that {SETIMAGE} only present on the forum menu....

P.S.: Sorry my first comment, i don't use newforumpost menu...

**Comment by fizi** [comment]
CaMer0n reset the avatar size for 40px...it works on all page, only on the forum pages now the avatar size 20px (not 40px). rica-carv what You wrote not good for me, because if anybody want put another menu to this menuarea, need rewrite the theme.php file.

**Comment by CaMer0n** [comment]
@fizi What do you propose as a possible solution?

**Comment by rica-carv** [comment]
@CaMer0n One solution i can imediatly see is to template the newforumpost menu, as is already donne with the login_menu...

**Comment by fizi** [comment]
Would be good make the template for newforumpost menu. In this may set the avatar size.

**Comment by CaMer0n** [comment]
@rica-carv @Moc I have added a template for the `new-forum-posts menu`. During this process the confusion/chaos of the forum shortcodes was very apparent. So, I have started the (huge) task of creating a new batch of forum shortcodes from scratch. The idea is that they would be consistent across all forum pages: forum, forum-view and forum-topic (but not the forum-post/submit form) 

Please take a look at `view_shortcodes.php` . It is where I placed them for now, but in future they could be moved to `forum_shortcodes.php`.  The shortcodes are organized much the same was as the forum db tables, as follows:  

sc_forum_xxxx (forum table)
sc_topic_xxxx (thread table)
sc_post_xxxx (post table) 

Please feel free to expand on them as we move forward. 

The 'main' template of newforumposts needs some work/help. I think it could be simplified further than what I have added already.

**Comment by CaMer0n** [comment]
I believe this can be closed as the avatar size should no longer be an issue. Please re-open if necessary.
