### ISSUE TITLE
How to add HMTL to end (footer)?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2299]
How can i, from ANY template, add HTML to the end, ie before the `</body>` tag?

I ask this because i want to use the bootstrap modals, but they don't work if the modal dialog HTML is put in the middle of the page HTML.
It gives this result, without any chance to click on the dialog:
![](http://www.wowthemes.net/wp-content/uploads/2015/06/bootstrap-modal-hidden.png)

[It seems that the solution is](https://github.com/twbs/bootstrap/issues/16148):

> Easiest way is to just move the modal div so it is outside any elements with special positioning. One good place might be just before the closing body tag </body>

, since bootstrap itself has not come up with a solution itself

Therefore, my question. Any solution?

**Comment by CaMer0n** [comment]
The bootstrap modal is added by default, no need to add it again.

**Comment by Jimmi08** [comment]
create theme shortcode, put it at the end of layout.  In theme shortcode put your code for modal part.  You can there load your template standard way.

**Comment by rica-carv** [comment]
@CaMer0n Maybe i express myself wrong. I know the default modal grey area is already there by default, i just want to put my modal dialog HTML on the end of the HTML (ie, out of the normal HTML flow)...

@Jimmi08 I've already thought that aproach, but let's suppose i want only the modal to be, for instance, in forum thread page.
With "your" idea, the modal would be EVER rendered, even if i was in, for instance, news page. In news page i wouldn't need the modal dialog, since i only need it in forum thread page...
But with shortcode it would be always rendered in all the pages....

Furthermore, if you have several modals scatered along several pages, you would have to create a shortcode for every single modal? Not very user friendly....

We should be able to define that modal HTML in the forum thread custom theme template, and "send" it to the bottom of the HTML, before the closing <body> tag.
Maybe a special template name inside every template. We already have the special reserved wrappers inside templates, so why not a reserved modal inside template?

**Comment by Jimmi08** [comment]
It should use only on related layout. And you always can check on what page you are and then load needed code.
Or maybe I just don't understand what you need.

**Comment by rica-carv** [comment]
@Jimmi08 I've already tryed your ideia, even with or without shortcode, it simply doesn't work. At least, inside menu templates it doesn't....
I've tryed the shortcode version, and the plain HTML directly inside the template...
None works...

**Comment by rica-carv** [comment]
Issue solved. Thanks
