### ISSUE TITLE
print.php - Printer friendly page displays a news author as e107

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2300]
Despite the fact that the news author is different, printer friendly page shows the author as e107.
Is this a desired behaviour? 

Sorry if its already reported.

**Comment by CaMer0n** [comment]
@arunshekher Would you have a screenshot of this?

**Comment by rica-carv** [comment]
Html page:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/25772463/4ce6b066-3263-11e7-8095-69158d43334c.jpg)

Printer page:
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/25772462/4ce264f2-3263-11e7-905e-676309694cbf.jpg)

**Comment by arunshekher** [comment]
Mine is same as rica-carv

**Comment by CaMer0n** [comment]
Closing thanks to the pull-request, but please re-open if necessary
