### ISSUE TITLE
High Memory Usage in Admin

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2302]
Hi Cameron, 
As our per discussion some days back, am still getting high memory issues on navigating to admin. This generates entries in the error log, like these.  

```
[Fri Jan 20 10:15:49 2017] [error] [client x.x.x.x] (12)Cannot allocate memory: couldn't create child process: /opt/suphp/sbin/suphp for /home/xxx/public_html/error.php, referer: http://xxxx.co.uk/e107_admin/admin.php
[Fri Jan 20 10:15:49 2017] [error] [client x.x.x.x] (12)Cannot allocate memory: couldn't create child process: /opt/suphp/sbin/suphp for /home/xxx/public_html/e107_admin/admin.php, referer: http://xxxx.co.uk/e107_admin/admin.php
```

It also looks related or a failure as a result of out of memory... the e107 Latest News Tabs for Core, Plugin and Theme, load inconsistently. Any one of three can fail to load, there does not seem to be a pattern. This seems to be a symptom rather than a real problem.  

I did quite a bit of research on it and my hunch is it could be related to the use of require_once / include_once throughout the system. #125 I gather that the new method is more efficient and unloads the module once used.

I have a memory trace here... https://docs.google.com/spreadsheets/d/1zHye-8Mfs_cCbnMkFQzm9d2eI3DBSXHbkMMkWCac0js/ 

I've tried various PHP settings, and spoken to the host. They recommended increasing the memory through cPanel > Choose PHP Version advanced settings (slightly improved). 

(I have been getting similar with thumb.php on the front end, but clearing the cache out & re-enabling and gzip site output and relinking the images to posts seemed to alleviate that somewhat).  

I've opened this so we can share information on it, and to get some guidance as to how to implement #125 in with specific handler examples. 

Thanks
Mikey

**Comment by MikeyGMT** [comment]
Despite lots of debugging and analysis don't think it one particular thing in our code. It just seems to be that PHP 7 uses Memory differently (more) that earlier versions. I'll continue analysing and leave this open as it continues to be a problem, although I am not sure what can specifically be done... Search php 7 huge memory requirements ...  http://stackoverflow.com/questions/39740398/i-am-facing-more-memory-consumption-in-php-7-compare-to-php-5-6/39861791

**Comment by MikeyGMT** [comment]
After much investigation, I came across http://www.slideshare.net/jignesht/performance-tuning-in-php-presentation and saw that OpCache helps a lot. I noticed that in my cPanel > Select PHP Version OpCache was enabled on 5.6 OpCache but disabled on 7.0. I enabled it and found the performance improvement was incredible. Now the system runs on HALF the memory that it did on PHP 5, which was about 6 MB down to 2.7 MB. I hope this helps!

**Comment by MikeyGMT** [comment]
Here are the settings..... 
![Uploading image.png…]()

**Comment by Moc** [comment]
Be aware that with any caching tool, you may run into issues..So be sure to disable it if you run into strange bugs :)

**Comment by MikeyGMT** [comment]
Yes I can see that it could cause issues. However I use a fairly standard hosting package, and on 5.6 the default was OpCache ON and on 7 it was Off, hence when I set a site to 7, the cache for the scripts was not used and the memory usage to load admin went from 6MB to 12MB and was throttled, and Admin loaded improperly. Enabling the cache the similar to PHP 5 setup reduced the memory usage to load the page to less than 3. So I hope this tip helps folk who see a critical fall in performance when switching PHP versions.  

Not using the OpCache implies that we need to performance tune the code, especially around use of known slow functions and incl/require_once of scripts needed to run a page.   

To that end, I have found "xdebug" which is now part of the PHP Zend Framework. Place a start command near the top of class2 and a stop command at the foot and it unobtrusive produces a log of the cost/time of all activities which occur when any page loads. 

`xdebug_start_trace('/home/myaccount/public_html/tmp/nameoftrace.xt', XDEBUG_TRACE_COMPUTERIZED );
... ... 
xdebug_stop_trace();
`
You'll need to create a tmp directory and you can take the logs and put them in excel, do a bit of maths to work out the slow/costly steps. It computes the details of every step including native php functions and custom code. It tells you a little bit more than the built in e107 debug function. 

I am sure there are much fancier tools out there to use, but it's definitely an eye-opener. You don't want to leave it on a busy prod site, as it will create lots of logs very quickly. You could add criteria to limit when the logs are created, or add it to specific php scripts to limit the data to where or who you are interested in debugging.

**Comment by MikeyGMT** [comment]
Here is an example - after putting into Excel. You can see that loading the glyphs from the cache and running all those functions on the cached array is very expensive, because somehow the cache breaks the array format. 

![image](https://cloud.githubusercontent.com/assets/2847651/22423637/77181de4-e6ea-11e6-8a47-c2b82099be4c.png)

**Comment by MikeyGMT** [comment]
Prefs Cache is definitely worth investigating. Look at this. I added xdebug_start at line 112 after construct and at the end at line 206. Dumped to excel and did some filtering and maths.

![image](https://cloud.githubusercontent.com/assets/2847651/22572753/70e11c2c-e99d-11e6-89ee-b39ef73e9c41.png)

**Comment by CaMer0n** [comment]
This is great. Thank you @MikeyGMT .  Here's a script I just wrote to test the cache of the glyphs. 
It's using 2 different methods, the default storage which uses `eval()` inside `e107::unserialize()`, and json storage which uses `json_decode()` inside `e107::unserialize()`. 

On my tests both of them took less than 2/1000ths of a second.  What result do you get? (make sure opCache is disabled)  Maybe you can add some more lines to test memory usage? 


		$time_start = microtime(true);

			$data = e107::getCache()->retrieve('Glyphs_fa4',false,true,true);
			$glyphs = e107::unserialize($data);

		echo 'Glyph (default) load time in seconds: ' . (microtime(true) - $time_start);

		echo "<br />Glyphs: ".count($glyphs);
     
             // re-save as json. 
		e107::getCache()->set("Glyphs_json",e107::serialize($glyphs,'json'),true,true,true);

		echo "<hr />";

		$timeStart = microtime(true);

			$data = e107::getCache()->retrieve('Glyphs_json',false,true, true);
			$glyphs2 =e107::unserialize($data);

		echo 'Glyph (json) load time in seconds: ' . (microtime(true) - $timeStart);
		echo "<br />Glyphs: ".count($glyphs2);
		echo "<hr />";

**Comment by CaMer0n** [comment]
My results with php 7.1 (faster with json it seems) 

    Glyph (default) load time in seconds: 0.0019998550415039
    Glyphs: 786

    Glyph (json) load time in seconds: 0.0010001659393311
    Glyphs: 786

**Comment by MikeyGMT** [comment]
About 30% faster, 10ms default, 3ms json.  

OpCache off and on a test front page with PHP 7. With very little else in it, just the memory footer details. 

```
Glyph (default) load time in seconds: 0.001054048538208
Glyphs: 786Glyph (json) load time in seconds: 0.00031304359436035
Glyphs: 786
Render time: 0.287 cpu sec (37.00% load, 0.059 startup). Clock: 0.77 sec (1% of that for queries)  DB queries: 16. Memory: 8.45MB/10.00MB 
```

Now compare one with another. 

Default only. 

```
Glyph (default) load time in seconds: 0.001039981842041
Glyphs: 786
Render time: 0.300 cpu sec (38.00% load, 0.060 startup). Clock: 0.78 sec (2% of that for queries)  DB queries: 16. Memory: 8.39MB/10.00MB
```

Json only. 

```
Glyph (json) load time in seconds: 0.00034499168395996
Glyphs: 786
Render time: 0.287 cpu sec (40.00% load, 0.064 startup). Clock: 0.71 sec (1% of that for queries)  DB queries: 16. Memory: 8.39MB/10.00MB
```

I'll try xdebug trace next.

**Comment by MikeyGMT** [comment]
Performance back to normal

**Comment by CaMer0n** [comment]
Thank you for the good news! :-)

**Comment by MikeyGMT** [comment]
Thank you for letting me collaborate on this :) Interesting stuff.

**Comment by MikeyGMT** [comment]
Quick update, over the weekend my host has upgraded server to Centos 7 with Maria 10 and PHP 7.1 
Performance is much better with this configuration up to PHP 7.0, however e107 does not seem to work at all with PHP 7.1, I'll log a new issue about that, after some more investigation. 
I also had to change e107_config host value to the actual machine IP, as localhost did not work properly, there is a case open with the host about that.

**Comment by CaMer0n** [comment]
Thank you @MikeyGMT . I usually run my local tests with PHP 7.1. Maybe 7.1 on the machine is missing some required modules?
