### ISSUE TITLE
Enhancement  - add export to xml option to batch functions in admin_ui

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2309]
It would be nice to have possibility export site data in batch functionality in admin_ui. Output would be the same as with database export feature, just only checked rows would be exported to xml.

**Comment by Moc** [comment]
This can be achieved  by using e_admin.php (example: https://github.com/e107inc/e107/blob/master/e107_plugins/_blank/e_admin.php)  but maybe something inbuilt in the core may be useful here. 

Personally I was already planning on using the e_admin.php addon to have an export functionality (for the AnteUp plugin)

**Comment by Jimmi08** [comment]
@Moc Yes, I need it for core tables.  Maybe just in e_DEBUG or e_DEVELOPER mode.

**Comment by CaMer0n** [comment]
That's a nice feature - for exporting specific records. 
(keep in mind that the image paths etc. will be different, if you're planning to use it for theme install.xml)

**Comment by CaMer0n** [comment]
Done. Just a little js issue with the button activity that needs fixing now.

**Comment by Jimmi08** [comment]
Thank you
