### ISSUE TITLE
ISSUE: ALT Menu link issue

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2318]
On Clancoyote.com I made a custom Menu with the shortcode {SITELINKS=flat:2}. Issue is that a external link to another site gives a 404 page = http://clancoyote.com/www.othersite.com.blah.htm

In the SiteLinks menu in admin area shows the link as http://www.othersite.com/blah.htm

This used to work before last update.

Link = http://www.shadows-of-empirion.de/drupal/index.php
Link hover = javascript:open_window('/main/http://www.shadows-of-empirion.de/drupal/index.php',800,600)
Link Sent = http://clancoyote.com/main/http://www.shadows-of-empirion.de/drupal/index.php

**Comment by LaocheXe** [comment]
Heads up - The site was e107 v1.X - updated to v2.X, I've also changed the Link Open type, still an issue - tried to take the users to (site url/folder/http://toothersite.url)

The current settings for one of the links
![capture](https://cloud.githubusercontent.com/assets/5818022/22634079/3802da52-ebec-11e6-978c-b93e87d1b0a2.PNG)

Alt Menu
![capture2](https://cloud.githubusercontent.com/assets/5818022/22634113/7fb438d2-ebec-11e6-8310-57c0ef2988c2.PNG)

**Comment by LaocheXe** [comment]
Any update on this issue?

**Comment by LaocheXe** [comment]
e107_core/shortcodes/single/sitelinks_alt.php

Line 60: `$lk['link_url'] = '{e_BASE}'.$lk['link_url'];`

No check if the link_url has http in the field or www. - so it still places main website url in front.

**Comment by kreativmind** [comment]
Try removing '{e_BASE}'. and just leave line 60 as:
$lk['link_url'] = $lk['link_url'];
e_BASE is yourdomain.com and so it's including clancoyote.com with the link url. Not sure if this will work but worth a shot.

**Comment by LaocheXe** [comment]
Sadly that didn't work either, right now Im looking in e107_handlers/sitelinks_class.php

Line 324

`
               elseif($linkInfo['link_url'][0] != '/')
		{
			$linkInfo['link_url'] = e_HTTP.ltrim($linkInfo['link_url'],'/');
		}`

Changed to

`
                elseif($linkInfo['link_url'][0] != '/')
		{
			$linkInfo['link_url'] = /*e_HTTP.*/ltrim($linkInfo['link_url'],'/');
		}
`

Links in alt menus work if they are off site (to another site)

**Comment by kreativmind** [comment]
Yeah. That works fine because it's stripping the e107 site url off of it.

**Comment by Jimmi08** [comment]
It works for me. What I have different?

![image](https://cloud.githubusercontent.com/assets/5429548/22965522/3565ab2a-f35e-11e6-94ad-b3dc560210f3.png)


![image](https://cloud.githubusercontent.com/assets/5429548/22965500/234c8d82-f35e-11e6-929a-b1152700af40.png)

 
![image](https://cloud.githubusercontent.com/assets/5429548/22965555/5d1e5cde-f35e-11e6-94bf-9b7b3b316acf.png)

**Comment by LaocheXe** [comment]
I was told to use `{SITELINKS=flat:2}` back in v1.0.7 - been using that all the time, and a few months ago it stop working.

I changed like 324 to this: `elseif($linkInfo['link_url'][0] != '/') { $linkInfo['link_url'] = /*e_HTTP.*/ltrim($linkInfo['link_url'],'/'); }` and I have no issue with the links any more

**Comment by kreativmind** [comment]
Try using {SITELINKS=side} instead of {SITELINKS=flat:2} @LaocheXe and see if that works without commenting the section we spoke about. That's the only thing different. Maybe the shortcode has been updated since v1.0.7

**Comment by CaMer0n** [comment]
`{NAVIGATION=side}` is the correct shortcode to use. `{SITELINKS}` is deprecated and used only in old v1.x themes. It does not have a template.

**Comment by LaocheXe** [comment]
@CaMer0n using {NAVIGATION=side} removed the bullets images, there a template I would have to put into the theme to get the bullets back?

**Comment by CaMer0n** [comment]
Thanks @LaocheXe Please re-test with the committed changes and close this issue if corrected. Thank you.

**Comment by LaocheXe** [comment]
Everything seems to be working 100% now,. thanks @CaMer0n
