### ISSUE TITLE
how to avoid resizing images 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2319]
I need to insert on the same position different image for each record. 
So I can't use SETIMAGE and hardcoded width, because next page has image with different size.

**Comment by CaMer0n** [comment]
`{SETIMAGE: w=0&h=0}`


![screen shot 2017-01-23 at 13 14 50-fullpage](https://cloud.githubusercontent.com/assets/2825679/22223394/a64e8e66-e16f-11e6-8eeb-3c1f5572c84b.jpg)

**Comment by rica-carv** [comment]
@CaMer0n Great, for me it's working back again, despite previously i was using `w=auto&h=auto`, and now is `w=0&h=0`
Thanks
