### ISSUE TITLE
Pagination in news category listing page (default or list) doesn’t work as expected

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2322]
If you have SEF urls turned on for news and is viewing the news category 'misc' at http://site.com/news/category/misc  all the pagination links points to '/news/list/category?’ like so : <a class="hidden-xs" href="/news/list/category?”   tested in an 1x upgraded site as well as v2 GitHub clone.

Sorry if it is a known issue or it has already been reported.

**Comment by arunshekher** [comment]
Adding a screenshot to make my point clear. I believe its a bug, could reproduce with 2.1.5 also on various platforms.

![news-category-pagination](https://cloud.githubusercontent.com/assets/315195/25878205/1388c15e-353a-11e7-9862-f73b2f895e17.png)

**Comment by CaMer0n** [comment]
Please go to : /e107_admin/newspost.php?mode=cat&action=list  
What is the value for "SEF URL" next to "Misc" ?

**Comment by arunshekher** [comment]
It is 'misc'

This is after 2.1.6 git update.

![image](https://cloud.githubusercontent.com/assets/315195/26153253/994c341a-3b1b-11e7-9cc1-2332a44c20f9.png)

![image](https://cloud.githubusercontent.com/assets/315195/26153309/cd8d6b36-3b1b-11e7-8aab-5933df1ee898.png)

**Comment by CaMer0n** [comment]
Thanks. I haven't been able to replicate it yet. Could you please send me a screenshot of your News prefs and your SEF URL page ( /e107_admin/eurl.php ) ?

**Comment by arunshekher** [comment]
I'm sorry didn't see your reply. Here it is:
![screen shot 2017-05-18 at 2 12 16 pm](https://cloud.githubusercontent.com/assets/315195/26197674/1c5c6a38-3bd4-11e7-95d3-ff89316ea533.png)

**Comment by CaMer0n** [comment]
Thanks @arunshekher . Please re-test with committed changes.

**Comment by arunshekher** [comment]
Just synced with repo and the pagination in news category listing works as expected (for the particular SEF setting). Thank you very much @CaMer0n 


![news-category-pagination-working](https://cloud.githubusercontent.com/assets/315195/26436044/8ddc0970-4124-11e7-9c6a-372acbe90a1c.gif)

**Comment by CaMer0n** [comment]
Thank you! Closing.
