### ISSUE TITLE
Issue: Plugin Name LAN

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2324]
Theme and Language Menus plugin name shows the LAN name, LAN_PLUGIN_USER_NAME

**Comment by Moc** [comment]
Where exactly do you see this? Can you provide a screenshot?

**Comment by tgtje** [comment]
Please do a plugin scan. User (theme and language) is pre installed; while LAN's and defines are just been updated..

**Comment by Moc** [comment]
Reproduced on a clean install. Fixed after plugin scan.

**Comment by Moc** [comment]
I think this is fixed now.
