### ISSUE TITLE
Issue: Plugin Manager - Find Plugins

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2325]
So after going to the Find Plugins in Plugin Manager, I download/install one plugin, then the next one I get a Bad Link. After waiting a minute or two, I am able to download/install the plugin that gave me a Bad Link error. Is there a cool down time?

**Comment by Moc** [comment]
Yeah probably the cool-down time, there is one when directly downloading from e107.org. 
There should be a proper message though.

**Comment by LaocheXe** [comment]
@Moc will the message stay as an error (red), or are you going to use the warning (yellow) message? Also in that message, could you possible add a timer/count down till the admin can use the function again?

**Comment by yesszus** [comment]
Find Plugins blank page error and drop down menus doesn't work.

See this video:  https://www.youtube.com/watch?v=ibBst-fZmW8

**Comment by CaMer0n** [comment]
Thanks for the video. Please enable debug and check for errors. Also error_log inside e107_admin/

**Comment by yesszus** [comment]
Debug Log:
Using Cached Core Update Data
admin_shortcodes->sc_admin_update()()
/home/vol3_1/e107.totalh.net/htdocs/e107_handlers/shortcode_handler.php 

PHP Errors:
Deprecated mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead, Line 227 of /home/vol3_1/e107.totalh.net/htdocs/e107_handlers/mysql_class.php

**Comment by yesszus** [comment]
Missing Plugins Help Sections
Older:
![plug1](https://cloud.githubusercontent.com/assets/17430115/23094256/9920ba62-f5f5-11e6-9336-250f6368c1e2.png)

New:
![plug2](https://cloud.githubusercontent.com/assets/17430115/23094261/a263a7e2-f5f5-11e6-8d75-755a9815ff2e.png)

**Comment by yesszus** [comment]
@CaMer0n see this errors.

**Fatal error: Call to a member function getData() on null in /home/vol3_1/e107.totalh.net/htdocs/e107_admin/plugin.php on line 899**

https://github.com/e107inc/e107/blob/master/e107_admin/plugin.php#L899

Debug Log:
Using Cached Core Update Data
admin_shortcodes->sc_admin_update()()
/home/vol3_1/e107.totalh.net/htdocs/e107_handlers/shortcode_handler.php 

PHP Errors:
Deprecated mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead, Line 227 of /home/vol3_1/e107.totalh.net/htdocs/e107_handlers/mysql_class.php

**Comment by Moc** [comment]
@yesszus Which PHP version are you using?

Also, to get rid of the deprecated mysql_* errors, try putting this in e107_config.php: 
`define('e_PDO', true);`

**Comment by yesszus** [comment]
PHP version: 5.6.23

**Comment by yesszus** [comment]
No solution?

**Comment by Moc** [comment]
The plugin scan should not be needed anymore and is currently removed. If there are issues with the recognition of plugins, then please let us know. 

The fatal error is being looked into.

**Comment by CaMer0n** [comment]
@yesszus Please update your files again and submit the error message again. getData() is not on Line 899 which means your file must be outdated.

**Comment by yesszus** [comment]
Fatal error: Uncaught Error: Call to a member function getData() on null in /home/vol3_1/e107.totalh.net/htdocs/e107_admin/plugin.php:906

Stack trace: #0 /home/vol3_1/e107.totalh.net/htdocs/e107_handlers/form_handler.php(4275): plugin_form_ui->options(Array, NULL, 0, Array)

#1 /home/vol3_1/e107.totalh.net/htdocs/e107_admin/plugin.php(1383): e_form->renderValue('options', NULL, Array, 0)

#2 /home/vol3_1/e107.totalh.net/htdocs/e107_handlers/admin_ui.php(2140): plugin_online_ui->listPage()

#3 /home/vol3_1/e107.totalh.net/htdocs/e107_handlers/admin_ui.php(1291): e_admin_controller->dispatchPage()

#4 /home/vol3_1/e107.totalh.net/htdocs/e107_admin/plugin.php(1539): e_admin_dispatcher->runPage()

#5 {main} thrown in /home/vol3_1/e107.totalh.net/htdocs/e107_admin/plugin.php on line 906

**Comment by CaMer0n** [comment]
@yesszus Thanks. I am still unable to reproduce this error.  What is the URL in your browser when this occurs?

**Comment by yesszus** [comment]
@CaMer0n  This URL: e107_admin/plugin.php?mode=online&action=list

**Comment by CaMer0n** [comment]
Still can't reproduce. 

@LaocheXe @Moc @Jimmi08 @arunshekher 

Do any of you see a fatal error when visiting: 

`e107_admin/plugin.php?mode=online&action=list` ?

**Comment by Moc** [comment]
@yesszus Is this issue still occurring?

**Comment by yesszus** [comment]
Solved!
Work for me without errors!
