### ISSUE TITLE
can't delete menus (custom menus)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2327]
After click on delete button, I get question If I am sure, page is refreshed, but menu is still there. No error.
Only way how I am able menu is to fill page title and delete it via page listing.
Latest version of github

**Comment by Moc** [comment]
Cannot reproduce so far..

**Comment by Jimmi08** [comment]
@moc try to use custom fields with pages. Or i will do it when i will able to do.

**Comment by Jimmi08** [comment]
Fixed
https://github.com/e107inc/e107/commit/4463de3a373208ac3244b6bf15c3169f7829b5af
