### ISSUE TITLE
Question: About e107 Server Paths and Overrides 

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2330]
Is  $E107_CONFIG['WEB_HTTP'] = 'http://static.mydomain.com/e107_web/'; a valid override declaration (in e107_config.php) for e107_web directory?

In a 2.1.4 fresh install test it doesn’t seem to respect this declaration in e107_config.php and override the default paths in the generated html markup. 

Thank you.

**Comment by CaMer0n** [comment]
Normally it should be: 

`$WEB_DIRECTORY = 'e107_web/';`

These are directory paths, not URLs.. so http is not permitted.

**Comment by arunshekher** [comment]
Cam,
I'm sorry if my question was ambiguous. I'm referring to the server paths overrides that's permitted in the setDirs() method in e107_class.php

[https://github.com/e107inc/e107/blob/12ef80d4ae1f5bbf5eaea0442cdf2f09415717b4/e107_handlers/e107_class.php#L416](url)

**Comment by CaMer0n** [comment]
I didn't write that method.. I really don't know, you'd have to do some experimenting.

**Comment by arunshekher** [comment]
Cam, I tinkered a bit and found out that when JS/CSS cache is disabled in Admin > Cache then $E107_CONFIG[‘WEB_HTTP’] is ignored and server default paths are used. When JS/CSS cache is enabled it works as expected. 

Assuming that the logic is to purge cache from CDN and serve origin server copy of the static assets. 

But other path overrides continue to override the system default paths, for example the $E107_CONFIG[’THEME_HTTP’] declared as 'http://static.mydomain.com/e107_themes/' or $E107_CONFIG['IMAGES_HTTP'] declared as 'http://static.mydomain.com/e107_images/' will continue to serve the overridden url (CDN url) even after JS/CSS cache is disabled. That feels a bit counter-intuitive (as people can naturally think that these system path overrides can be turned on and off just by declaring it and taking it off in e107_config.php).

Ran a 'git blame' and saw these features where added to the core in 2011 but I doubt that there still is some bits of code in the core that's not taking this features into account as I found some doubled path declarations (like: http://site.comhttp://static.site.com/....) as the 'src' value of some core icons and emoticons when $E107_CONFIG['IMAGES_HTTP’] was declared in e107_config.php. 

Thank you.

**Comment by CaMer0n** [comment]
@arunshekher I recently did some work on static domains. 
Please see #2596 and #2600

**Comment by arunshekher** [comment]
Thanks CaM. Trying to comprehend.

**Comment by CaMer0n** [comment]
Try this in e107_config.php (modify as needed)

    define('e_HTTP_STATIC', 'http://static.mydomain.com/');

**Comment by arunshekher** [comment]
Sure.
