### ISSUE TITLE
Social icons bug

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#2338]
On news and extended news social icons are not displayed even on bootstrap3 core theme. The buttons are there but with no icons.

**Comment by CaMer0n** [comment]
Do you happen to have js/css cache enabled?

**Comment by mcpeace-maw** [comment]
No.

**Comment by LaocheXe** [comment]
I will back up that Social Login is not being displayed via mobile devices

**Comment by CaMer0n** [comment]
I believe some mobile devices block font loading.

**Comment by mcpeace-maw** [comment]
On the same row in each article I have also printer icon and comments icon that are visible, only social buttons are empty with no icons, in all browsers on Android and on Windows 10 PC.

**Comment by mcpeace-maw** [comment]
I downloaded last git and seams that now all is fine, the icons are displayed. Thanks, I'll close for now and if is needed can be reopened.

**Comment by rica-carv** [comment]
> I believe some mobile devices block font loading.

Maybe it's time to get icons in SVG format???

**Comment by CaMer0n** [comment]
@rica-carv I'll need your help for testing this.
