### ISSUE TITLE
Database Utilities Correcting File and Directory Permissions

### ISSUE THREAD

**Issue by TIDEngine** [e107inc/e107#234]
Error
Failed applying filemode '755' on directory '../' `-> the directory '../' will be skipped from recursive chmod Failed applying filemode '755' on file '../cron.php' 

OS: Freebsd
PHP:  5.4.13

I try to manually change permissions that shows in error, but error shown again.

**Comment by Moc** [comment]
Closing this due to the lack of feedback. Please re-open if the issue is still present.

**Comment by im-L0r3** [comment]
I had this same issue under Ubuntu 18.04 server. Clicking "Database Utilities > Correcting File and Directory Permissions" resulted in a huge wall of text of fails. Manually setting permissions via ssh to match the error text output did not solve it.

I tried several other things without success such as:
# chgrp -R www-data /var/www

The final solution that worked was:
# chown -R www-data:www-data /var/www/html

**Comment by CaMer0n** [comment]
Thanks for sharing @im-L0r3 . Every server is different.
