### ISSUE TITLE
Forum layout on Landing Zero 2.0 theme

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2343]
When I go into the forums, the high lighted forum description becomes hard to read, and when I go into a forum thread, I cant see the text of the first post, color for the background is white(ish) while the font is white(ish)....

![capture](https://cloud.githubusercontent.com/assets/5818022/22400526/4f810b2e-e57d-11e6-8089-3e0579abb5a0.PNG)

**Comment by mcpeace-maw** [comment]
@LaocheXe the forum background color is hard coded in from.css file from the plugin. Was tested on Boostrap3 theme (white background) and now for all other themes you need to add in style.css:
`#forum-viewtopic li.forum-viewtopic-post:nth-child(odd) { background:  your_color }`

**Comment by LaocheXe** [comment]
The reason why I brought this up because the site I have this up on is a fresh install, the theme is in the e107_themes folder right now, I'm not going to make my own style.css for this theme that should have the style.css already, I mean if this was straight out of the box, then this could turn a few people away - plus the fact that the theme itself is wonderful till one gets to the forums area.

**Comment by mcpeace-maw** [comment]
I had a pull request to correct this in forum plugin over a year ago, but I've deleted after a few months because it was not approved. Now I intervened because I thought you needed help, sorry my mistake.

**Comment by LaocheXe** [comment]
@mcpeace-maw that is okay, I didn't mean to sound rude or anything like that, I thought if this was going to be an theme anyone can use out of the box that it should be address and corrected some time within the future - I love how it looks, just a few flaws that a little style.css can fix like you said.

**Comment by Jimmi08** [comment]
@mcpeace-maw Thank you. Noted.

@LaocheXe do you really use this type of theme for forum?

**Comment by mcpeace-maw** [comment]
@Jimmi08 I'll make a new pull request to correct this in forum.css (in forum plugin), in this way all themes (with white or dark backgrounds) will have a forum basic style.

**Comment by mcpeace-maw** [comment]
OK made it, you can try the theme with the 2 forum files changed in my pull request.

**Comment by Moc** [comment]
https://github.com/e107inc/e107/pull/2349

**Comment by Moc** [comment]
@LaocheXe Please update from Github and provide feedback :)

**Comment by LaocheXe** [comment]
Alright, that works, I can now read the post, however, the hover over Forum catagory, and hover over topic, and sub-forums are still white (#ddd), maybe turn that to a grey or dark grey.

**Comment by mcpeace-maw** [comment]
@LaocheXe That background color on row hover is from bootstrap css and is specific for every theme, so will need to be fixed in the style of the theme and I think you can manage that.

**Comment by LaocheXe** [comment]
@mcpeace-maw again, if this is going to be a theme that is going to be used as out of the box, the mouse hover over style should be corrected via style.css of the theme, If e107 is ment for user friendly, someone might not know how to edit css files. Yes I could go and do that, and even do a pull request, however, I am not the theme author, nor do I know what the theme author wants the hover over color to be, and since the hover over seems to be from bootstrap 3 style sheet, then the theme author might not have known, and doesn't want a hover over effect.

Also a little note, the theme (video) uses a nice chunck of ram on server site - web host I am working on with the theme only allows 1GB of ram, and the video eats 2/4 of the ram - thought I'd share that info.

**Comment by Moc** [comment]
I agree with @LaocheXe. Considering this is now a core theme, it must look correctly, right out of the box.

**Comment by Jimmi08** [comment]
@LaocheXe As one of the author. It's ported theme, it wasn't tested with forum plugin.  You can pull request as you want. Or send me demo content for forum plugin to see this.
About RAM. I don't know, but maybe if you try original HTML theme on your server, you could say it's e107 related thing. If this happens with html theme too, maybe original author could help?

There are no rules. I tried get some here: http://e107help.org/2496/discussion-when-is-theme-finished 

@Moc It sometimes can't look out of box, because e107 bootstrap templates doesn't use the same rules. 
for example:  https://github.com/e107inc/e107/issues/2160

**Comment by tgtje** [comment]
Got it running as site theme (own site), just needed some added 'space'below the navbar.. it will overlap.
As for the ram use... might be related to the external call for the mp4 file ( from get it to post it).. I do not know how much i use (own uploaded).. Soem more tinkering would be needed for the 'still images' i can add them, nut never see them in use

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/2366

**Comment by Jimmi08** [comment]
Demo: http://landing-zero.e107.sk/forum
Check last version (needs core updated too). If it's OK, you can close this.

**Comment by LaocheXe** [comment]
@Jimmi08 everything looks great on that demo site.

**Comment by Jimmi08** [comment]
@Moc You can close this.
