### ISSUE TITLE
getScBatch not working in admin

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#2344]
Am using `$mem_sc = e107::getScBatch('members',TRUE);` to call the shortcodes for my plugin - this is working on frontend pages but doesn't seem to be working in when called via admin_config.php (returns null). Has only been happening since I upgraded to latest git version of e107.

Any ideas?

**Comment by CaMer0n** [comment]
Please update. Does it help?

**Comment by pricey1981** [comment]
yes, working again now. Thanks
