### ISSUE TITLE
problem with installation 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2347]
Latest github version on localhost. Admin user wasn't created.  

After testing I see the error:
`Parse error: syntax error, unexpected '{' in C:\xampp\htdocs\e107-master\e107_handlers\db_verify_class.php on line 780`

```
		foreach($match[1] as $c=>$k)
		{
			if(strpos($k,'e107_' === 0) // remove prefix if found in sql dump.
			{
				$k = substr($k, 5);	
			}
			
			$tables[$c] = $k;		
		}	
```

there is missing ) after if(strpos($k,'e107_' === 0) 
but it's weird, I am surprised that nobody reported this.  
Thanks

**Comment by Moc** [comment]
Interesting.. this wasn't changed for four years. What PHP version are you on?

**Comment by Jimmi08** [comment]
PHP Version 5.5.15
