### ISSUE TITLE
"Need Help?" notification/alert

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#2355]
I have made a fresh install 3 days ago, updated 3 times the installation in this period and the notification windows with "Need Help?" popup every time I open Admin Area. I close it, even I visited e107Help site and next time is there, seams hopeless. I know it is useful for newcomers, but there is a way to hide it for good, as I started to get on my nerves.

**Comment by Moc** [comment]
This message should disappear after three days, but you can also click the "don't show this again" button. Apparently this is not working properly currently..

**Comment by mcpeace-maw** [comment]
Well "don't show this again" button don't have and 3 days of forced display (remember no "don't show this again" button) perhaps it is too much, at least for me. Thank God now finally gone, I hope not occur again after the next update.

**Comment by Moc** [comment]
Which version were you on? The 2.1.4? It should have the 'do not show again' button.

**Comment by mcpeace-maw** [comment]
I use only downloaded git every night.
