### ISSUE TITLE
load time with 2.1.5 version

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2361]
I wasn't sure about this, but I noticed that latest version on localhost is slower, visibly slower (mainly admin area).
I could update online site, so I check time analyze:
version 2.1.4 (no warning, 
![image](https://cloud.githubusercontent.com/assets/5429548/22522410/c4c21ffe-e8bb-11e6-9548-e5a6ebd8951f.png)
update from github (files, update routines):
![image](https://cloud.githubusercontent.com/assets/5429548/22522467/f0462cf6-e8bb-11e6-8b1b-2992a14b3b47.png)
![image](https://cloud.githubusercontent.com/assets/5429548/22522484/faf1827c-e8bb-11e6-93db-dd4d41a80be2.png)

**Comment by Moc** [comment]
@MikeyGMT is working on optimizations in here: https://github.com/e107inc/e107/issues/2302

**Comment by CaMer0n** [comment]
@Jimmi08 Those warnings are a new feature..  If you're not using the dark admin theme, the admin could load slower.

**Comment by MikeyGMT** [comment]
@Jimmi08 If using PHP 7 check your OpCache module is enabled. I saw memory drop 75% (12MB to 2.7MB) per admin Page load.

**Comment by CaMer0n** [comment]
Be warned: opCache can cause issues while developing.  ;-)

**Comment by MikeyGMT** [comment]
OK - OpCache - for prod site only ;D

**Comment by Jimmi08** [comment]
@CaMer0n @MikeyGMT 
PHP 5.5 version
I use dark admin theme (default theme)
Oh, I didn't notice that this is different column as before.

**Comment by Moc** [comment]
@Jimmi08 What's the current status on the performance/load time of e107?

**Comment by Jimmi08** [comment]
@Moc how do I test this?  Admin is stilll loaded slowler...  Do you want to make the same pictures from debug?

**Comment by Moc** [comment]
@Jimmi08 Well I was wondering if you could still notice slower loading speeds. The debug data may help yes. 

As for the admin area, is it only the main dashboard (/e107_admin/admin.php) or also other pages in the admin area? I suspected the delay is caused by the updates check which happens on the main dashboard page (and which will be cached).

**Comment by Jimmi08** [comment]
just updated from github

it looks like Load plugin module is higher

![image](https://cloud.githubusercontent.com/assets/5429548/24196214/377ae884-0efd-11e7-8d82-c2206174be15.png)
![image](https://cloud.githubusercontent.com/assets/5429548/24196232/45b7513a-0efd-11e7-872f-4c95f2a53ac6.png)

You could be right. I think that I see it on localhost mainly.

**Comment by Jimmi08** [comment]
Closing. It doesnt look as problem now.
