### ISSUE TITLE
Issue: Missing Shortcode from e107_core

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2365]
I installed the plugin a few days ago and notice no featurebox on my front page, even in the area in the menu manager says {FEATUREBOX} - added the plugin into menu area 1 -  went to the front page and saw a warning.

![capture1](https://cloud.githubusercontent.com/assets/5818022/22551312/f783cfa6-e919-11e6-80c3-492b82135857.PNG)

So went into the admin area to look at the templates

![capture2](https://cloud.githubusercontent.com/assets/5818022/22551330/07fc6e9c-e91a-11e6-8fc2-eb86b44cbe1b.PNG)

Then I went to the front page and busted out the nice e107 Dev tool for FireFox and saw this

![capture3](https://cloud.githubusercontent.com/assets/5818022/22551349/1aab696c-e91a-11e6-8e65-c3bec588910d.PNG)

I checked the FTP, synced to GitHub, and check GitHub, there is no e107_core/shortcodes/single/featurebox.sc

**Comment by LaocheXe** [comment]
Also looking more at the e107 debug list, and notice that MENUI is missing shortcode as well.

MENUI: e107_core/shortcodes/single/menui.sce107_core/shortcodes/single/menui.sc MISSING!

**Comment by CaMer0n** [comment]
Please re-save your featurebox preferences, specifically: `Featurebox Menu Category`

Also, the theme must have a typo {MENUI} if it is searching for a shortcode which doesn't exist.

**Comment by LaocheXe** [comment]
@CaMer0n Okay so Menui was a typo, sorry


There are no featurebox items assigned to the bootstrap_tabs template

There are no featurebox items assigned to the bootstrap3_carousel template

I re-saved the featurebox preferences, still get the warning messages and no matter what I do, cant get it to show

**Comment by LaocheXe** [comment]
After uninstalling the plugin, and Installing it fix the issue, I originally installed the plugin via theme install.
