### ISSUE TITLE
[Question] Menu admin UI design help

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2369]
Sorry for posting this here, but i think it's a better place than in e107help.org.

I'm currently designing some menus admin ui, and i'm having a hard time on figuring out how to correctly setup fields (ie, preferences?) and retrieve them on the xxx_menu.php file.

For instance, i have the $fields array defined inside e_menu.php, which is correctly displayed in the menu manager config area.
1st question: How can i define a default value for those $fields? In plugin.xml? How?
2nd: How can i access those $fields values from xxx_menu.php? I've looked at the various menus.php coded here, and simply can't figure it out...

Any help appreciatted....
Thanks...

**Comment by CaMer0n** [comment]
This example (slightly modified from news_grid_menu.php) should answer both of your questions. 
    
    $gridSize  = vartrue($parm['layout'], 'col-md-4');

1) 'col-md-4' in this example
2) $parm in this example

**Comment by rica-carv** [comment]
@CaMer0n Once more, thanks for pointing me on the right direction.
Anyway, i'm thinking of making some use of the plugin.xml defaults:
```
$plugin_pref = e107::pref('plugin');
$gridSize  = vartrue($parm['layout'], $plugin_pref['layout']);
```
Any thoughts about this approach?

**Comment by rica-carv** [comment]
Err, might have called victory too soon...

I've got a small gremlin...
If the menu is rendered inside a regular menu area (ie: `{MENU=1}`), the `$parm` variable is correctly appended to the menu rendering, and therefore available for it's frontend code.
But if the menu is rendered outside of a regular menu area (ie: `{MENU=plugin\plugin_menu}`), there's no `$parm` available for frontend code....

**Comment by rica-carv** [comment]
Forget it, i ended up writing my own fetch parm function. Thanks.

**Comment by Moc** [comment]
Reopening to make sure this is documented somewhere
