### ISSUE TITLE
Admin Preferences Menu Style 

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#2374]
Question: This is CSS bug?

![settings](https://cloud.githubusercontent.com/assets/17430115/22591095/0299a3da-ea13-11e6-8044-c6822ffb0bbc.png)

**Comment by AdocArg** [comment]
No, **Advanced Options** is a separator, like <optgroup>

**Comment by yesszus** [comment]
See Basic Options caption.

**Comment by Moc** [comment]
It's not a bug, but it should be improved to be made better looking and easier to understand. 

The menu is divided into two sections (Basic Options & Advanced options). In my opinion, instead of having it all in one block, it would be best to separate them into two blocks.

**Comment by rica-carv** [comment]
On the "lazy" side, maybe add just a <HR> before it????

**Comment by CaMer0n** [comment]
It's a bit ugly.. I agree. What the correct 'bootstrap' way of doing it? I'll have to do some research.

**Comment by rica-carv** [comment]
With bootstrap accordion?
![responsive-navigation-menu 1](http://www.designerslib.com/wp-content/uploads/2015/11/responsive-navigation-menu.jpg)
Other ideias:
![responsive-navigation-menu 2](http://www.codescratcher.com/wp-content/uploads/2015/05/Vertical-Sidebar-in-Bootstrap-CODE-SCRATCHER.jpg)
![responsive-navigation-menu 3](http://seegatesite.com/wp-content/uploads/2014/12/how-to-create-dynamic-sidebar-menu-with-mysql-and-adminLTE-bootstrap.png)
