### ISSUE TITLE
Forum upgrade bug: Posts assigned to anonymous

### ISSUE THREAD

**Issue by durandalwoz** [e107inc/e107#2376]
When upgrading the forum from a pre 2.0 version, if an user name contains a dot "." all their forum posts will be assigned user id '0', and appear as anonymous.

Note: this bug was present at least in the 2.1.2 release version. I just now noticed the issue, have not checked if it persist in newer versions

**Comment by Moc** [comment]
Confirmed this before as well. I assume the bug is still there.

**Comment by CaMer0n** [comment]
@durandalwoz If you feel like tweaking and testing.. I believe this occurs at line 1526 of forum_update.php
ie.  `getUserInfo(&$info)`

**Comment by Moc** [comment]
I have worked on a patch for this. 

@CaMer0n I've send it to you on Gitter to confirm before I commit it.
