### ISSUE TITLE
[Issue] Doesn't appear blob type on plugin builder

### ISSUE THREAD

**Issue by AdocArg** [e107inc/e107#2381]
Hi, i was trying to create a plugin following the steps of http://e107.org/developer-manual/plugin-basics but in Plugin builder--> Table: myplugin, in "Type" doesn't appear MEDIUMBLOB and I have nothing to select, I can't continue (also, after the _image column_, i have a _type column_ and doesn't appear)

Image of the problem:

![problem](https://cloud.githubusercontent.com/assets/20747469/22621734/4d082fd0-eb09-11e6-9d4a-a82e2beb447d.jpg)

Columns:

`'image' mediumblob NOT NULL,
  'type' char(15) NOT NULL`

This is an issue/bug or i have something wrong?

Edit: And i don't understand very well why in 3 columns that they are int type says: "True/False"

Thanks.

**Comment by CaMer0n** [comment]
Thank you for posting this issue. Would you mind sharing your mysql "CREATE TABLE" so that I can test with it? Thank you.

**Comment by AdocArg** [comment]
Sure:

```
CREATE TABLE `e107_profile_gallery` (
  `id` int(6) NOT NULL,
  `user_id` int(6) NOT NULL,
  `width` smallint(6) NOT NULL,
  `height` smallint(6) NOT NULL,
  `image` mediumblob NOT NULL,
  `type` char(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `e107_profile_gallery`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `e107_profile_gallery`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT;
```
That was the result as it exported with phpmyadmin

**Comment by CaMer0n** [comment]
Perfect.. thank you.

**Comment by AdocArg** [comment]
Thanks to you. Well honestly something of that i know it but sometimes I had the same question of that user. I hadn't seen that post, thanks again Cameron.

**Comment by CaMer0n** [comment]
Thanks. Closing this. I recommend to use type 'image' with a varchar(255) - this will upload the image and save the path automatically.
