### ISSUE TITLE
Menu manager in admin displayed incorrectly

### ISSUE THREAD

**Issue by inferno-prime** [e107inc/e107#2382]
As you can see by the [picture](http://tinypic.com/view.php?pic=34g3cpg&s=9#.WJJZHFzavcd) the menu manager itself does not display correctly and I am unsure how to proceed on how to fix this ?.

ps I have tried the menus.php from github and they had no effect.

**Comment by AdocArg** [comment]
Have you modified the theme.php for your current theme? It had happened to me and it was because my theme.php was wrong

**Comment by rica-carv** [comment]
It seems that inside menu manager, the css from the theme is not applyed.
Do you have the latest github files installed?
If not, do it....

**Comment by inferno-prime** [comment]
I thought the files for github were for testing only this is for a live site.

**Comment by tgtje** [comment]
You can use github files for live as they are more up to date than a pack, but packs are seen as 'pretty stable'at THAT point in time (error/issue free... no) but github files are continously in a 'working on' state...
Eventually they too will become a pack (hence versioning towards v2.1.5)

**Comment by inferno-prime** [comment]
I tried but it only made it worse.

**Comment by inferno-prime** [comment]
Tried the files from github but it only made the problem worse now the admin area is messed up. As in there are duplicate menu's all over the place.

**Comment by CaMer0n** [comment]
@inferno-prime Please, if you have time, come to the chatroom, and I can work through this issue with you.  In the meantime, could you tell me which theme you are using?

**Comment by inferno-prime** [comment]
I want to thank you all for your help. This problem was caused by a permission problem I have never encountered before.
