### ISSUE TITLE
E107::lan ('plugin') not loading front language

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2384]
`E107::lan ('plugin')` is not loading front language file (`language_front.php`), instead of what's mentioned in the lan function start...
But `E107::lan ('plugin', 'front', true)` does loads it, as mentioned...

Also, `E107::lan ('plugin', true)` is not loading admin language file (`language_admin.php`), instead of what's mentioned in the lan function start...
But `E107::lan ('plugin', 'admin', true)` does loads it...

**Comment by yesszus** [comment]
Try this: E107::lan ('plugin', 'false', true)

**Comment by rica-carv** [comment]
> Try this: E107::lan ('plugin', 'false', true)

Err, this does the same: `E107::lan ('plugin', 'front', true)`
My issue is why the shorter version (`E107::lan ('plugin')`) doesn't work...
