### ISSUE TITLE
Admin UI display Help in boolean field

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2385]
It seems help text can't be displayed in boolean fields:

```
$fields['remembersections']  = array('title'=>LAN_EUSER_ADMIN_1, 'type'=>'boolean', 'help'=>LAN_EUSER_ADMIN_1H);
``` 
Doesn't work.

But with text fields it works:
```
$fields['remembersections']  = array('title'=> LAN_EUSER_ADMIN_1, 'type'=>'text', 'help'=>LAN_EUSER_ADMIN_1H);
```

Is this a bug or it's intended to be as is?

**Comment by rica-carv** [comment]
Further testing & HTML check, show that in regular admin ui pages, there's a `<div class="field-help" style="display: none;">Help text here...</div>`, that is not present in the menu manager admin ui HTML...

**Comment by Moc** [comment]
Closing in favour of #2874
