### ISSUE TITLE
[warning]Declaration of e_pref::update....

### ISSUE THREAD

**Issue by chory** [e107inc/e107#2387]
I need click continuously in the update button with label Update from 1.x 2.0.
I clicked 25 times or more, and button with label Core database structure, never active.

 Declaration of e_pref::update($pref_name, $value) should be compatible with e_front_model::update($from_post = true, $force = false, $session_messages = false), Line 28 of /home/clantoroxa/www/e107_handlers/pref_class.php

**Comment by CaMer0n** [comment]
Chory, could you please try clearing system cache and tell me if that corrects the issue for you?

**Comment by chory** [comment]
Not, I'm usin /e107_admin/e107_update.php?[debug=warn+] in URL

**Comment by CaMer0n** [comment]
The warning is unrelated to the update.

**Comment by chory** [comment]
👍 the warning, continue, but dont need click mor times the button.
Thank You
