### ISSUE TITLE
User Class name not appearing in manage Forum or User

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2388]
Since recent commit, now just see user class showing as class:4 or class:number of the actual class in the database. See images
![users - manage - admin area three percenters mcc 2017-02-06 22-55-51](https://cloud.githubusercontent.com/assets/15772899/22670290/770633aa-ecc0-11e6-9e24-8ac5a65ef98d.png)
![user classes - manage - admin area three percenters mcc 2017-02-06 22-56-17](https://cloud.githubusercontent.com/assets/15772899/22670295/7a76d710-ecc0-11e6-9edf-709995fa60c2.png)

**Comment by Moc** [comment]
I cannot reproduce this. 

Please try updating from Github again before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download ZIP' button at the top of this page: https://github.com/e107inc/e107

Then, clear all caches: 
- Browser cache
- e107 caches (Settings > Cache > Empty all caches > delete) 

Is the issue still present then?

**Comment by martyshep** [comment]
Thanks, I've re-sync'd and cleared cache, all is well now.
