### ISSUE TITLE
Update Manager - Fatal Error - Admin dashboard white page

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2389]
After I logged in to my website, I got a white page instead of Admin Dashboard. 

**error.log**
```
[Tue Feb 07 09:17:15.331839 2017] [fcgid:warn] [pid 29457] [client 188.142.226.249:59084] mod_fcgid: stderr: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://e107.org/service?wsdl' : failed to load external entity "http://e107.org/service?wsdl", referer: https://demo.lonalore.hu/e107v2/
[Tue Feb 07 09:17:15.331895 2017] [fcgid:warn] [pid 29457] [client 188.142.226.249:59084] mod_fcgid: stderr:  in /var/www/clients/client3/web70/web/e107v2/e107_handlers/e_marketplace.php on line 570, referer: https://demo.lonalore.hu/e107v2/
[Tue Feb 07 09:17:15.331899 2017] [fcgid:warn] [pid 29457] [client 188.142.226.249:59084] mod_fcgid: stderr: PHP Fatal error:  Call to a member function __setSoapHeaders() on a non-object in /var/www/clients/client3/web70/web/e107v2/e107_handlers/e_marketplace.php on line 618, referer: https://demo.lonalore.hu/e107v2/
```

I do not think it is a good idea to check available updates when visiting dashboard. The best would be creating a cron job to do this (with email notification (optional)).

**Comment by lonalore** [comment]
A few minutes later it became available again. Maybe e107.org was down? In this case, what about websites use e107? All of them become unavailable because e107.org is down? :/

**Comment by Moc** [comment]
I noticed this issue earlier as well and discussed it with @CaMer0n. Ideally we need to improve the error handling, so it does not throw a fatal error.

**Comment by CaMer0n** [comment]
Normally this shouldn't occur again.
