### ISSUE TITLE
the quick add user isn't worcking correctly

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#2394]
Hello guys,

Well. When you try créate a user using the quick add user option of the admin panel, the user is created correctly, but with the problema, that the password is filled correctly.

Example:

you add:
username pedrito
pass: passwordoffpedrito 

the user pedrito is correctly added, but if you logout, and try to login as pedrito, the system throug the error saying that the password or the username is invalid.
You have to forcé the login as pedrito (throug the panel) go to the settings of pedrito, and change the password (if you want put the same password, passwordoffpedrit on this example) sabe the settings, and try again. 

please if you can, fix this. because is anoying have to set the passwords of new users throug this method u.u.

Of course if you have public signup disabled xd.
thanks.

**Comment by Moc** [comment]
Hi, 

In `Admin Area > Preferences > Security & Protection`, what is the value of `Password encoding`?

**Comment by sanslash332** [comment]
Hello,

Sorry for the late of the answer. I have setted the security encoding as salted. :P 

And the transmission method as plaintext. Yea, I know, is a big security hole, but well :P 

 

Thanks for all :3

**Comment by Moc** [comment]
Hi, 

I would recommend taking a backup of your website before completing the following steps (also of the MySQL database). Your webhosting provider should have an option for this in your control panel (cPanel, DirectAdmin, Plesk, etc.) 

- Please change the `password encoding` to `PHP Default (preferred)`
- All of the currently stored passwords will be updated to this new format, don't worry. 

After doing this, please test the `Quick add user` option again.

**Comment by sanslash332** [comment]
Hello Tijn,

 

Sorry again for the delay. I have to find the time for can test the system with patient.

Well, these are the results:

 

1.       After I’ve changed the security option to php default, the quick add user is working like previously. You can’t log-in except if you force that login.

2.       And and extra problem that appened, with the new encoding system, when you change the password of the new user, forcing the login through the panel, the new password doesn’t work.

3.       When I returned to the salted option, the quick add isn’t working too, but the change password from settings of the users work again.

 

Thanks for all.

**Comment by CaMer0n** [comment]
@sanslash332 Please enable debug mode and then "Quick Add User". It should display the generated hash. 
Please post that hash here, thank you.

**Comment by sanslash332** [comment]
Hello Cameron,

 

Sorry for the long delay. I don’t know how to the plug-in works, but after some experiments I can discover that all the magic is on the second click :du 

 

Well, this is the generated hash:

 

 

System Debug

Attempting to Load: ../e107_plugins/pm/languages/English_global.php

Attempting to Load: ../e107_plugins/gsitemap/languages/English_global.php

Attempting to Load: ../e107_plugins/poll/languages/English_global.php

Attempting to Load: ../e107_plugins/linkwords/languages/English_global.php

Attempting to Load: ../e107_plugins/forum/languages/English/English_global.php

Attempting to Load: ../e107_plugins/trackback/languages/English_global.php

Attempting to Load: ../e107_plugins/list_new/languages/English_global.php

Attempting to Load: ../e107_plugins/rss_menu/languages/English_global.php

Attempting to Load: ../e107_plugins/log/languages/English_global.php

Attempting to Load: ../e107_plugins/chatbox_menu/languages/English/English_global.php

Attempting to Load: ../e107_plugins/featurebox/languages/English_global.php

Attempting to Load: ../e107_plugins/newsfeed/languages/English_global.php

Attempting to Load: ../e107_plugins/newsletter/languages/English_global.php

Attempting to Load: ../e107_plugins/download/languages/English/English_global.php

Attempting to Load: ../e107_plugins/banner/languages/English_global.php

Attempting to Load: ../e107_plugins/faqs/languages/English/English_global.php

Executing social_event :: config()

Executing social_admin :: config()

Attempting to Load: ../e107_plugins/social/languages/English/English_front.php

 

Debug Log

Message Function File Line

Using Cached Core Update Data admin_shortcodes->sc_admin_update()() /home/tiflojue/public_html/e107_handlers/shortcode_handler.php 1055 

 

 

And various other more things… ¿what other do you need? :P

**Comment by CaMer0n** [comment]
@sanslash332 Are you able to meet me in the chatroom to discuss? http://gitter.im/CaMer0n

**Comment by CaMer0n** [comment]
"PHP Default" mode failing due to the database upgrade not having been run yet (it increases the size of the password field otherwise password would not save)  ;-)

**Comment by CaMer0n** [comment]
Confirmed working by @sanslash332 . Closing.
