### ISSUE TITLE
proxy prevents login session to suddenly 'die' 

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2395]
please help, i have to use proxy to work with e107, i've contacted my hosting company, they suggest me to try using proxy to work with e107.. and it worked, login session not always 'die'

here is my video to explain the issue https://www.youtube.com/watch?v=FKd1_GM-QYU 

thank you in advance

**Comment by Moc** [comment]
Hi,

Sorry to read you are having issues. Let's get some more information first: 

- In `Admin Area > Settings > Preferences >  Security & Protection`, what are the values for: 
`User Tracking method` and `Session Lifetime`

- In `Admin Area > About > PHP Info` search for `session.save_path` (using CTRL + F in your browser)
Please consult with your webhosting provider to make sure that this path is correct and that is writable by your account.

**Comment by drasehat** [comment]
Hi @Moc  thank you

User tracking method > Cookies
Session Lifetime > 86400

session.save_path for both columns is **/tmp**

i talked to my hosting company .. i showed them your post in #1245  , but they said my hosting isn't the the problem, because they tested and it's working fine on their side.. 

thank you in advance

**Comment by Moc** [comment]
Can you try switching the 'user tracking method' to sessions? See if that makes any difference.

**Comment by drasehat** [comment]
no difference T_T .. i will talk to my hosting company once more..
i created a website for my client using e107 v.2 and it work fine until now.. 
but this new project on new hosting .. argggh

**Comment by Moc** [comment]
I don't really understand why it does work when using a proxy... This to me indicates that the hosting provider has some odd configuration. 

Which firefox plugin are you using specifically? Then I can see what exactly is done, to figure out if there's something to be improved in the e107 core.

**Comment by drasehat** [comment]
www.anonymox.net .. 
yes agree, i will show them this thread

**Comment by drasehat** [comment]
still no solution, hosting company said there are no issues on their side..
and it might my internet connection problem, big question is why i can still work with e107 on another hosting smoothly ?

**Comment by drasehat** [comment]
Hi again @Moc  ,
i think i solved this issue (for my case) ..
so i decide to trace (by echo) the cookie on admin, when i succesfully login, cookie was set normal (random numbers)
then i try visit other pages that cause logout suddenly and the cookie value is dissapear.
but now everything is fine!!  i decide to edit `session_set` function to `session_set(e_COOKIE, $cookieval,  0, '/');` in auth.php
`0` mean cookie will expire until i close the page 
and `/` mean cookie is available on all admin page..
i think `time()` function not work for everyone .. especially me :)

do you think this is save ? 
thank you in advance

**Comment by Moc** [comment]
Are the pages which log you out the same all the time? In other words, are there specific pages which do not work or is it random? 

I'm not sure what's going on with the cookie setting process. Apparently there's a server side setting which may conflict. I just don't understand why using a proxy would change this behaviour.

**Comment by drasehat** [comment]
all pages, it's not server side problem .. because i've tried two different hosting, and have same problem.
i think it's more like my internet connection problem. 
like PDO problem i've mentioned. when my client try to update usersetting, its working .. but on myside the result still PDO not found .. weird isn't it ?
most internet provider in my country, inject their ads (javascript) to user visited websites, so if i inspect element of a website in the browser i can see the script on the bottom. not sure either this can cause login problem with e107. but wordpress not affected to this.

**Comment by CaMer0n** [comment]
@drasehat please update from github, and then set the Session Lifetime to 0 here: e107_admin/prefs.php#nav-core-prefs-security

**Comment by drasehat** [comment]
working great @CaMer0n  thank you!

**Comment by CaMer0n** [comment]
Thanks! Closing. Probably something wrong with the time on the server. At least we have a workaround here now.

**Comment by drasehat** [comment]
hi again @CaMer0n 
this is what happen when session suddenly die .. 
![session-problem](https://cloud.githubusercontent.com/assets/25628686/25774138/f1353dcc-32b3-11e7-9b77-40863c57fea4.jpg)
