### ISSUE TITLE
[Question] Add color picker to admin ui fields, how?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2396]
How can i add a color picker for fileds in the user admin ui area? Mainly on the menu manager area?
Is there a option available for this, along with boolean, text, etc.?

**Comment by LaocheXe** [comment]
I think they would have to create a new admin theme for that, unless I am getting your question wrong. Are you talking about allowing admin to change the color of menus in the menu manager area?

**Comment by rica-carv** [comment]
@LaocheXe New admin theme is not necessary, since it would be simply a bootstrap add-on for admin ui fields input, just like datepicker:
![colorpicker](http://www.jquery-az.com/wp-content/uploads/2016/05/35.0_1-Bootstrap-color-picker.jpg)

**Comment by Moc** [comment]
#1267

**Comment by Moc** [comment]
Closing this in favour of #1267
