### ISSUE TITLE
Menu manager twitchs on small screens...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2398]
I'm working on a 1024x768 desktop screen resolution, and got these "twitches" with menu manager:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/22749338/df04c308-ee24-11e6-9f07-8198b2723dbc.jpg)

On red:
- Misplaced or over the edge text and iconized tabs (left side)
- And also the scroll bar on the modal that pops up when clicking menu configuration is outside of the "panel" itself... (right side)

Further more, isn't possible to have  a two column fields configuration, in order to take advantage of the empty space in the modal (green box)?

**Comment by CaMer0n** [comment]
I see why you need the tabs now! I'll see what I can do.

**Comment by CaMer0n** [comment]
Closing as this would appear to only occur on a custom plugin that isn't using tabs now. Please re-open if this occurs on core plugins.
