### ISSUE TITLE
Menu default prefs not saved

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2400]
Got the fields defined in e_menu.php:
`$fields['whatsnewpage']  = array('title'=> "Use plugin what's new page, instead of core", 'type'=>'boolean');`

The same field is defined in plugin.xml prefs:
`<pref name="whatsnewpage">1</pref>`

If i don't click on menu config for this menu, in admin menu manager, the field `whatsnewpage` will not be available as menu parm during rendering time, and therefore to get the default value, i got to go fetch it in plugin prefs.
But if there's no prefs defined in plugin, these default parms will never be available, unless admin clicks on menu configure...
Is this intended to be or really a bug?

**Comment by CaMer0n** [comment]
Menu prefs and plugin prefs are 2 different things.  Set the defaults in the xxxxxx_menu.php file.

**Comment by rica-carv** [comment]
Ok, but if i want to use that prefs in another part of the plugin?
I'm closing this since i'll use a workaround....
