### ISSUE TITLE
posibility to collect emails without using contact.php or registration

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2402]
It would be great to have safe solution for GET IN TOUCH form or SUBSCRIBE to newsletter without registration to site. 

"option to collect emails from people who want to receive the newsletter without having to sign up for an account" 

"Is it possible to make the get in touch form send an email rather than go to contact.php?"

**Comment by Moc** [comment]
I guess this can be included in the rewrite of the newsletter plugin. Labelled as enhancement.

**Comment by CaMer0n** [comment]
Just use the "NEWSLETTER" user class  (or another one) and auto-create a password. That way if they wish to subscribe or manage their subscriptions later-on they will have an account to do so.

**Comment by Jimmi08** [comment]
I don't understand what to do.
