### ISSUE TITLE
Issue: Admin area

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2406]
Cant access admin area with current version on github - get error

Fatal error: Call to a member function __setSoapHeaders() on null in /home/clancoy1/public_html/main/e107_handlers/e_marketplace.php on line 618

**Comment by Moc** [comment]
Resolved in the latest version on Github.

**Comment by Moc** [comment]
#2389 https://github.com/e107inc/e107/commit/c1930ab654ea51b2cee328aec5aa273b56c988b3
