### ISSUE TITLE
Question: SSL - Site Preferences

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2407]
What ever happen to the enable SSL (HTTPS) in site preferences? Wanted to enable this feature since the hosting provider has provided some SSL certificates

**Comment by CaMer0n** [comment]
It only displays if you are logged into the site with SSL.

**Comment by Moc** [comment]
Changing the Site URL in Preferences should do the trick. 

There is a preference called ''ssl_enable' which should be in the Security section of the preferences, but after some testing it's not showing up. Looking into it.

**Comment by Moc** [comment]
Yep that fix works for me 👍

**Comment by LaocheXe** [comment]
So no more option in the admin preferences? I've synced with GitHub and haven't see the option to enable or disable.

**Comment by CaMer0n** [comment]
Log in to your admin area using SSL. Then it should appear. This is a precaution because enabling SSL without SSL set up correctly will make the site unreachable.

**Comment by LaocheXe** [comment]
@CaMer0n tried that, didn't go to well, allow SSL option never showed up - went in with phpMyAdmin and change the 0 to a 1 for SSL - site now uses https

**Comment by Moc** [comment]
@LaocheXe And to be sure, you were logging in to your admin area (log out and relogin if needed) using a `https://` URL? For me the option showed up...

**Comment by LaocheXe** [comment]
@Moc - yes I tired that, no show for me

**Comment by LaocheXe** [comment]
Found an issue, with Clan Coyote website, there are two menus that use <iframes> - going to https:// the iframes dont show, going to http:// iframes show, idk much about https as I should but is this a bug for iframes?

**Comment by Moc** [comment]
@LaocheXe Yeah this is an issue with iframes and not with e107. 
here's some background info: http://www.tinywebgallery.com/blog/iframe-do-not-mix-http-and-https

Basically, you cannot load http:// iframes when using https://.

**Comment by LaocheXe** [comment]
No, same server, could be that my cache wasn't updating

**Comment by Moc** [comment]
Ok, assuming it was the cache then. Closing this issue.
