### ISSUE TITLE
Admin not working?

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#2408]
Am having problems getting into site admin. On the production site I just get a blank white page.

In the developer site (wamp server) I get the following error message

> Fatal error: Call to a member function __setSoapHeaders() on null in <path>\e107_handlers\e_marketplace.php on line 601

I haven't made any change to either setup, might this be caused by a remote change?

Am using git version of e107 on both dev & production sites.

**Comment by CaMer0n** [comment]
Replace e_marketplace with the one in Github. This should fix it.

**Comment by pricey1981** [comment]
sorted, thanks
