### ISSUE TITLE
Online Menu skewed latest GIT

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#2415]
Skewed with mystery number showing...

![image](https://cloud.githubusercontent.com/assets/4084331/22857183/f0b0502a-f065-11e6-999b-e33c2eed1da1.png)

**Comment by dimante** [comment]
So it's the {ONLINE_MEMBERS_TOTAL} line that generates the 34... Why it's missing the <ul>Total Members: 

Is escaping me..

**Comment by Reconix** [comment]
It's a typo, it's trying to get ONLINE_MEMBER_TOTAL when it should be ONLINE_MEMBERS_TOTAL 

hope that helps.
![yeah](https://cloud.githubusercontent.com/assets/559757/22869417/c5dba78c-f196-11e6-9c58-d9b17e559c04.png)
