### ISSUE TITLE
Unauthorized access! With Chrome and IE

### ISSUE THREAD

**Issue by w7snk** [e107inc/e107#2417]
Ok I will add as much detail as I can. 

Server is Ubuntu 16.04.1
PHP 7
Apache/2.4.18 
E107 v2.1.4
All are NEW installs tonight

Issue Unauthorized access! when quick adding users or deleting or moving menus on page, or making menus or pages, or basically any admin function, NOT all functions but quite a bit. 

I have done many many forum searches:
-  I have checked my sessions folder. It is writeable (infact owned by www_data) Files are being made there. 
- Setting define('e_SECURITY_LEVEL', 0); Works but is unsafe 
- I have used IE and Chrome to try and make changes, both get the Unauthorized access! error
- I have added ?[debug=basic+] to both IE and Chrome and got some debugging info but not much
so I decided to get firefox and get the e107 debug addon. 

when to cause the error and I was able to make quick user and move menus in FIREFOX. odd went back to chrome..... still broken. 
errors I am getting from firefox are as follows

```
Warning Declaration of e_pref::update($pref_name, $value) should be compatible with e_front_model::update($from_post = true, $force = false, $session_messages = false), Line 28 of /var/www/ahg/e107_handlers/pref_class.php
Warning Declaration of users_admin_ui::afterDelete($deletedData, $id = NULL) should be compatible with e_admin_ui::afterDelete($deleted_data, $id, $deleted_check), Line 235 of /var/www/ahg/e107_admin/users.php
Warning Declaration of users_ranks_ui::afterDelete($data) should be compatible with e_admin_ui::afterDelete($deleted_data, $id, $deleted_check), Line 2747 of /var/www/ahg/e107_admin/users.php
Warning stristr(): Empty needle, Line 1275 of /var/www/ahg/e107_handlers/validator_class.php
```

edit* chrome for android alar doesn't work

**Comment by CaMer0n** [comment]
Some servers already have security measures in place which won't be compatible with e107's. Setting e_SECURITY_LEVEL to zero doesn't mean you have no security, but minimal security. Your server may be doing the rest.

**Comment by w7snk** [comment]
@CaMer0n any way to verify that?
Also a bit I forgot. I changed from using sessions to cookies. When I did that I could no longer log in. I wasn't getting wrong password just looping. I did try wrong password and gave me a log in error. But correct login gave me login again

**Comment by Jimmi08** [comment]
@w7snk do you log in via modal login box or login page? Try to log in via login page (site/login.php) in private / incognito browser window.

**Comment by w7snk** [comment]
@Jimmi08 Logging in via login.php logs in but goes nowhere. Just at the top says "You are currently logged in as the Main Admin."

/e107_admin/admin.php is how I normally log in. 
incognito Does NOT change the results. 

Only once I change the security lvl to less than 5 It works

**Comment by Jimmi08** [comment]
@w7snk it's correct. Confusing, but correct.  I had the same reaction: https://github.com/e107inc/e107/issues/1913
(Now just return to main page - remove login.php from URL)

**Comment by w7snk** [comment]
@Jimmi08 Logging in incognito  from login.php produces the same issues

**Comment by CaMer0n** [comment]
@w7snk Does security Level 5 work okay for you?

**Comment by w7snk** [comment]
No lvl 5 is what causing the issue

**Comment by Moc** [comment]
If you are still experiencing this issue, please join us in the Gitter chatroom so we can debug this real-time on your installation. 

https://gitter.im/e107inc/e107
