### ISSUE TITLE
Website will not load in Chrome on certain 4G networks. net::ERR_INCOMPLETE_CHUNKED_ENCODING shown in debug console

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2424]
Have site logo set.
Am seeing errors for 
img class="logo img-responsive img-fluid" src="/3per/media/img/0x30/2017-02/3plogo.png" alt="Three Percenters MCC" srcset="/3per/media/img/0x120/2017-02/3plogo.png 120h 4x" height="30"

How does path /media/img/0x120/ come about? I can't see it in my file manager :?

**Comment by CaMer0n** [comment]
$tp->thumbSrcSet()

**Comment by martyshep** [comment]
Ah ok, thanks @CaMer0n, so it's like a 'virtual' path for want of the correct term. Can I negate this error by uploading different sizes of the logo to use for srcset? ( I've just researched what srcset actually does :) )

**Comment by CaMer0n** [comment]
Depends on what kind of errors. What is the error exactly?   
Ideally you want to upload a high resolution version of your logo and e107 will take care of the resizing automatically.

**Comment by martyshep** [comment]
That may be the issue then, it was not a high resolution / size image to
start with. Will retry with a higher size / resolution image.

**Comment by martyshep** [comment]
The error shows in a console screen of a browser. It's not a noticeable
issue on the website itself. I've been debugging recently to look into an
issue where I get a blank page and net:: ERR_INCOMPLETE_CHUNK ED_ENCODING
using Chrome browser with my e107 website. The Chrome issue only manifests
when using Chrome browser on Vodafone 4G network so I was looking more at
the networking side of the hosting to resolve this seperate issue. Or
should I log it as an issue on here? Thank you so much for looking into
this so quickly. Better than any paid support I've experienced :)

**Comment by Moc** [comment]
@martyshep Please try disabling the real-time anti virus protection on your device for testing purposes. Does the error still occur then?

**Comment by martyshep** [comment]
I've seen quite a few threads on websearches about this issue and quite often it is the real-time AV causing the issue, but I have tried it with the AV disabled and even on another android phone that does not have an AV. I've also disabled 'Use a prediction service to load pages more quickly' no change. If I keep refreshing the page sometimes it will load, but then none of the links will be clickable. Firefox on same phone works, but loads half of the page, then really slows, then loads the rest and it works. 

I've seen same issue with other users mentioning terminal 0-length chunk and some fixes are to:
//Gather output (if it is not already in a variable, use ob_start() and ob_get_clean() )    

// Before sending output:
header('Content-length: ' . strlen($output));

or put:
php_value opcache.enable 0

in .htaccess

????

**Comment by Moc** [comment]
Are you using cPanel or something similar? Can you check if an extension called OPCache is enabled?

**Comment by martyshep** [comment]
yes using cPanel. I can't see details of OPCache in the server config but that isn't a full view I have. I would need to log a case with the hosting co to ask.

**Comment by Moc** [comment]
I suspect that having this extension enabled is causing some issues, perhaps including the one you are experiencing now. It would be best if you could test it with OPCache disabled.

**Comment by martyshep** [comment]
Found PHP config, I don't see it enabled. I see:
Archive_Tar	1.4.0	 
Console_Getopt	1.4.1	
Crypt_Blowfish	1.0.1	
PEAR	1.10.1	
Structures_Graph	1.1.1	
XML_RPC	1.5.5	
XML_Util	1.3.0

I don't see OPCache on the list of available PHP extensions. I will check with the hosting co. Should I have OPCache enabled or is disabled the way forward?

**Comment by Moc** [comment]
I would suggest having it disabled (caching is always tricky). This is also recommended in one of your answers as quoted 

> or put:
php_value opcache.enable 0

in .htaccess

This essentially disabled the OPCache extension.

**Comment by martyshep** [comment]
thanks Moc :) I tried the php_value opcache.enable 0 in my .htaccess and I then couldn't access the website, got a 500 Internal Server Error message. Removed it, back up.

**Comment by Moc** [comment]
Please consult with your webhosting provider to check if OPCache is enabled, and if so, how it can be disabled.

**Comment by martyshep** [comment]
ok will do thanks Moc. Regarding caching, what is recommended for my e107 site? I don't have a lof of traffic. I currently have set:
![image](https://cloud.githubusercontent.com/assets/15772899/22932373/a455cada-f302-11e6-82b4-906f9f5c28c3.png)

**Comment by Moc** [comment]
I would personally disable everything, and clear it from time to time to be sure (as for some reason it keeps accumulating files in there even though it's disabled). Caching does the weirdest things in my experience. 

So especially when you're experiencing issues, I would disable caching as one of the first steps. 

For as long as you do not have any performance issues (slow loading etc.) I would keep the cache disabled in the future as well.

**Comment by CaMer0n** [comment]
e107 does force caching of some elements. So files will accumulate. (eg. prefs , glyphs etc) even if caching is disabled. Other caching is optional, and this is what these settings represent.

**Comment by martyshep** [comment]
header('Content-length: ' . strlen($output));
So I put this in my index.php and the website then loads in Chrome fine. Take it out.. Problem immediately occurs.

**Comment by martyshep** [comment]
Modified the issue title to be more specific to this issue now the logo item is not an issue. I also tried putting **header('Content-length: ' . strlen($output));** in class2.php and this also addresses issue.

**Comment by Moc** [comment]
Closing as issue is too specific and is not likely to occur again. Besides, the issue poster has moved infrastructure is not experiencing the issue anymore. Appears to be a network specific issue.
