### ISSUE TITLE
[Issue] Doesn't appear Next-Prev comment button on profiles

### ISSUE THREAD

**Issue by AdocArg** [e107inc/e107#2425]
Hi, this problem happened to me in all themes and before ask, i searched in all templates to see if i would find something but no, i didn't found anything.

How can i do to add the Prev - Next buttons in the comments of the profiles? Because they don't appear, so only i can see the last 5 comments

Yesterday I did a clean installation with the latest changes from github, using bootstrap3 theme and the problem persist.

Thanks.

**Comment by Moc** [comment]
@AdocArg Is this still an issue?

**Comment by AdocArg** [comment]
I just tried a clean installation with the latest changes and regrettably yes, still an issue =/.

**Comment by CaMer0n** [comment]
@AdocArg With which theme? 

Bootstrap 3: 

![image](https://user-images.githubusercontent.com/2825679/43164292-a7920624-8f45-11e8-9c9b-0c6b77656f75.png)

**Comment by AdocArg** [comment]
With any theme. I don't mean the Prev/Next user buttons, i mean the Prev/Next comment button (in the profiles).

![comments](https://user-images.githubusercontent.com/20747469/43351590-a245223a-91ea-11e8-877f-740e4fe9e1f3.jpg)

**The problem is** that only the last 5 comments are seen, I think there should be a button to go to the previous comments there in the red box.
