### ISSUE TITLE
import RSS with core import plugin doesn't import images

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2426]
Tried this RSS https://e107.org/xml/news/rss/
Images are not imported

![image](https://cloud.githubusercontent.com/assets/5429548/22935513/1206ca3c-f2d3-11e6-85d8-2c3e595cd2ce.png)

**Comment by CaMer0n** [comment]
Added a fix, but it needs testing with a fresh install.

**Comment by Jimmi08** [comment]
This is not my issue (it was created for somebody else). but I tried it with this setting:
![image](https://cloud.githubusercontent.com/assets/5429548/23396814/e1fa2a50-fd95-11e6-86b4-e86740bd2e83.png)
Images are not loaded.

**Comment by Jimmi08** [comment]
It was fixed. Thanks.
