### ISSUE TITLE
[Question] Amind ui table options rows, how?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2428]
Is it possible to have a "table" in admin ui, with two or more options in a row?
Kind of like this:
![](https://premium.wpmudev.org/blog/wp-content/uploads/2015/03/editing-site_admins-table-option.png)

**Comment by Moc** [comment]
I don't think that's possible at this time. Could you give us a use case for this?

**Comment by rica-carv** [comment]
Old v1.x admin ui, trying to replicate:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/22937017/289722f0-f2cf-11e6-85df-fb7cbb0b0d4f.jpg)

**Comment by rica-carv** [comment]
It can be donne via writeparms....

**Comment by CaMer0n** [comment]
type=json or type=array will save multiple values in a single field.. if that's what you mean?

**Comment by rica-carv** [comment]
@CaMer0n No, i can live with multiple fields values (just got to be sure i got no duplicates), what i want is to have related values together in the same row, as the picture above, instead of having a huge scrolling list of values on the admin ui....
