### ISSUE TITLE
MD5 password encryption on PHP

### ISSUE THREAD

**Issue by 214945** [e107inc/e107#2431]
In the admin left a message to go with the MD5 password encryption on PHP, I passed.
Now I can not login to the admin center, says not a valid password.

**Comment by MikeyGMT** [comment]
You could go to phpmyadmin. Find you user in the user table and update the password field. From the dropdown, choose MD5. 
![image](https://cloud.githubusercontent.com/assets/2847651/23028691/fdcacd28-f45f-11e6-8953-1ddb4b484053.png)

**Comment by 214945** [comment]
I've done differently.
I had a backup of the database, taken from there in your password and MD5 copied instead of PHP.
