### ISSUE TITLE
Debug smtp wrong connections

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#2432]
Hello guys,
I have a anoying error with my e107 syte, and my smtp hosting. I configure correctly my syte with the the smtp data, but the email doesn't working. If i view the logs, the only that the error says, is smtp connection error.

The extrange thing is, if I configure other application like Outlook or thunderbird with the same smtp data, the application can connect without any problem. Can send and receibe emails with that account.
But, if I configure e107 with other type of smtp server, like a Gmail account... ¡it Works fine!

How to I can view more details about the connection error, to try fix it?

I have the developer option enabled, but the information in the emailoutlog.txt is the same.

If someone have this problema, please help.
If this information will be useful, my hosting provider is sitegrounds :P 

thanks for all!

**Comment by LaocheXe** [comment]
Maybe its the port?

**Comment by sanslash332** [comment]
Na, isn’t the port.

As I said in the previous message, I configured my outlook with the same (exactly same) settings, and the outlook can connect fine.

 

Specifically port 465 with ssl.

**Comment by LaocheXe** [comment]
Maybe the same issue I posted about = #2025

**Comment by sanslash332** [comment]
Provably provably… The major differense is, that I have the send bulkmail in blocks options disabled, and the vrp option disabled too hmmm.

 

The other extrange thing is that you try the test email, the gui every time says that the email was send successfully, but in the log appear one or other error x3u.

**Comment by CaMer0n** [comment]
@sanslash332 Have you tried enabling debug mode? (Firefox e107 addon) It can provide full details of the SMTP connection sequence.

**Comment by sanslash332** [comment]
Hello, Sorry for the delay of the answer.

 

Firefox e107 add-on?

 

Am… I don’t know about the existence about that add-on. I have to download and try it.

 

Thanks, if I have more information, I’ll post here.

**Comment by CaMer0n** [comment]
Closing this, since an SMTP test option has been added. Please re-open if necessary.
