### ISSUE TITLE
[QUESTION] How to call shortcode parm in bb text area ?

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2433]
Hi again all,

i'm trying to break the SITECONTACTINFO values to array then make them shortcodes..
for example : 
if > {CONTACT_INFO=address,icon} the output is Address value with an icon.
if >{CONTACT_INFO=phone} the output is phone value without an icon
else > {CONTACT_INFO} the output is the whole SITECONTACTINFO value with some modification <div>
the shortcodes work perfect in theme.php with parm or not..

the problem is, when i try put it in the menu content in admin area (bbcode textarea), shortcode parm is not working.
when i try to write {CONTACT_INFO=address} it will result the whole SITECONTACTINFO values..
i tried a lot of possibilities of shortcode write styles, but nothing change..
help me out please,

thank you in advance
indra

**Comment by drasehat** [comment]
question solved !!  thanks

**Comment by Moc** [comment]
What was the answer? :)

**Comment by drasehat** [comment]
Hi @Moc 
i was wrong about bbcode can't deliver the shortcode's parm. it can
but it just can deliver one parm, not like in theme.php you can add parms as many as you like (CMIIW)
so i have to break the parm's string again if i want deliver 'address' and 'icon' {CONTACT_INFO=address,icon} /  {CONTACT_INFO=address} .. solved! :)

i'm working with html theme's files to convert it become e107's theme. i need a lot of single value  from SITECONTACTINFO (add,phone,email..etc) .. to maintain the look from original html theme.

**Comment by Moc** [comment]
Thanks @drasehat 

@CaMer0n Is this intended behaviour?

**Comment by rica-carv** [comment]
Have you tried with the V2.x standard way of delivering parms via shortcodes: `{CONTACT_INFO: address=true&icon=true}` ???

**Comment by drasehat** [comment]
thank you @rica-carv  that would work too !!
i'm sorry, i'm a newbie :)

**Comment by CaMer0n** [comment]
@Moc Correct. Shortcodes can't be parsed via TinyMce.
