### ISSUE TITLE
[Quest] It's possible that check_class() have a bug?

### ISSUE THREAD

**Issue by AdocArg** [e107inc/e107#2435]
Hi, recently i created an userclass called "Platinum", and then when i do this:

check_class($_GET['id'], PLATINUM) returns false in a user that have this class (Honestly i don't know how to get the id or profile name that the client is currently seeing if not is with $ _GET ['id']). I try with:

    check_class($_GET['id'], PLATINUM)
    check_class($_GET['id'], Platinum)
    check_class($_GET['id'], "PLATINUM")
    check_class($_GET['id'], "Platinum")
    check_class($_GET['id'], 4)       --> (4 is the id of that class)
    check_class($_GET['id'], "4")

And none works. If i try with:

check_class($_GET['id'], ADMIN) or check_class($_GET['id'], "255") works perfectly. So my real question is: what do i'm doing wrong? Is a bug?

**Comment by lonalore** [comment]
Please try with this:
```php
check_class(4, null, $user_id)
```

Furthermore, always filter input variables. For example:
```php
$user_id = e107::getParser()->filter($_GET['id'], 'int');
```

**Comment by AdocArg** [comment]
Works excellent, thank you! You're right with filter input variables. Before used check_class() i saw the e107-FAQ (http://e107coders.org/e107_plugins/faq/faq.php?cat.6.29) in which says:

> check_class() - Checks the user-class of the logged in User
> 	
> check_class($var, $userclass=USERCLASS)
> 
> $var =
> $userclass =
> 
> Check to see if a USER belongs to a particular user-class.
> 
> Returns either TRUE or FALSE.

Why you use 'null' as second parameter? What represent? (the above info it's update?)

**Comment by lonalore** [comment]
Because $userclass will be rebuilt if you use the tird parameter. According to [this](https://github.com/e107inc/e107/blob/master/class2.php#L1564).
Btw a [short documentation](https://github.com/e107inc/e107/blob/master/class2.php#L1546-L1549) is provided for the function.

**Comment by AdocArg** [comment]
Sorry! I could not find where the function was defined, now i know and understand. Thank you!
