### ISSUE TITLE
Register in Cyrillic

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#2440]
It does not work if you enter the login registration in Cyrillic.

**Comment by Moc** [comment]
Is this still an issue?

**Comment by Evgura** [comment]
Yeah, that's a problem. Registration for Cyrillic not working.
"03 - Login - The value contains invalid characters"

**Comment by Moc** [comment]
Thanks, listed as a bug

**Comment by Moc** [comment]
Related #2288

**Comment by Moc** [comment]
@SimSync could you take a look at this one please?

**Comment by SimSync** [comment]
@Evgura As I don't use Cyrillic characters, could you please post some Cyrillic usernames or words, that I could use to test and debug this issue? That would help a lot.

**Comment by Evgura** [comment]
Cyrillic is needed for login
Example Login - Евгений

**Comment by Evgura** [comment]
After entering the login in Cyrillic and fill in all the fields click "Register" and get a white screen.
If you refresh the page you will again form registration although registration was successful and the mail comes a confirmation letter.
Registration in the Cyrillic alphabet works but white screen all the spoils.

**Comment by Moc** [comment]
Perhaps an issue in the Russian language pack. Needs figuring out to see where it goes wrong.

**Comment by Evgura** [comment]
Now letters of confirmation began to come in this form.

```
Array
(
    [e-token] => 1aa9777c0fbd1351ee7fbfe04d0a88f2
    [loginname] => T***n
    [email] => Alfa_teh_import@mail.ru
    [email2] => 
    [register] => Регистрация
    [hideemail] => 1
    [email_confirm] => Alf***mport@mail.ru
    [username] => T***n
    [ue] => 
    [hide] => 
)
```

**Comment by SimSync** [comment]
Installed Russian languagepack and was able to signup without blank page...

**Comment by CaMer0n** [comment]
@Evgura That looks like a signup notification email. Check admin > Notify and resave your settings.

**Comment by Evgura** [comment]
Thanks. We will test. It seems to work normally.
