### ISSUE TITLE
Parent forum

### ISSUE THREAD

**Issue by 214945** [e107inc/e107#2442]
I can not create parent forum.
I create a parent - a forum and all. The admin panel is, in the database there. The site in the forums or anything is not present.

**Comment by rica-carv** [comment]
Are you using the latest github files?
Are you using a fresh install or upgrading from v1.x?

**Comment by 214945** [comment]
I use the update from version 0.7.26 to 2.1.4
What are the last files you have in mind?

**Comment by rica-carv** [comment]
Update from 0.7.26 to 2.1.4?
You should have updated from 0.7.x  to 1.x, and after to 2.x...
Do you have completelly updated sucessfully the forums in admin area?

**Comment by 214945** [comment]
"updated from 0.7.x to 1.x, and after to 2.x..." - I did just that.
All well-established and without errors.

**Comment by rica-carv** [comment]
So, there's no messages in the admin area, in the forum area, right?
You have 2.1.4, but can you sync it with latest github to see if it still has the error?

**Comment by 214945** [comment]
Now I will try to upload a folder with a forum to githab.

**Comment by 214945** [comment]
Nothing changed.
In version 0.7.26 was alone - to create the parent and to create a separate - forum.
How to create a parent in version 2.1.4?

**Comment by rica-carv** [comment]
If you already have the parent created via admin ui->forum-> create, on this same window you can create the parent child forum by specifiyng in the field parents the parent forum....
Voilá....

**Comment by 214945** [comment]
Nothing works.
The parent forum is created but it is only in the admin center. The site is not to the parent forum.
Even if you create a subforum in parent present it does not appear on the site.

**Comment by rica-carv** [comment]
Sorry, but i can't replicate your issue. I have latest github files installed, and works fine.
What's your PHP version?

**Comment by 214945** [comment]
I tried to put the latest version from githab but after the installation breaks down the top menu.
PHP version - 5.6

**Comment by rica-carv** [comment]
If you can, force the update, ie, donwload the zip from github, expand it and force copy overwriting all files form your server...

**Comment by 214945** [comment]
I tried, after the upgrade does not work admin center. The top menu is broken.

**Comment by rica-carv** [comment]
Top menu is broken, or is it hidden on the right side?

**Comment by 214945** [comment]
Top menu does not respond to pressing.

**Comment by rica-carv** [comment]
Even more weird....
Can you see if the page has any javascript errors?
Which theme are you using as admin theme?

**Comment by 214945** [comment]
bootstrap3

**Comment by 214945** [comment]
More is not working right, "the latest news E107"
and graphics.

**Comment by rica-carv** [comment]
Try to clean caches. Browser and e107, it might be a cache issue...
I simply can't think nothing else mioght be interfering....
Are you on a localhost server or a webserver?

**Comment by 214945** [comment]
Yes Yes Yes Yes Cleaning cache helped but only through the webserver.
