### ISSUE TITLE
Admin UI boolean field returns strange values

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2444]
Got a strange issue during admin ui runtime with same boolean type fields returning different values, using bootstrap3 theme as admin:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/23094522/8f3b3f02-f5f2-11e6-8e47-f7ffe27539ab.jpg)

admin_config.php prefs array data are exactly the same, only changes is the LAN:
```
'flashtext' => array('title'=> LAN_EUSER_ADMIN_104,'tab' => 0, 'type'=>'boolean', 'writeParms'=>array('class'=>'e-expandit')),
'new_icon' => array('title'=> LAN_EUSER_ADMIN_106,'tab' => 0, 'type'=>'boolean', 'writeParms'=>array('class'=>'e-expandit')),
```
Has anyone encountered this issue? Or is just me?

**Comment by rica-carv** [comment]
Furhtermore, i've tryed to change the prefs values manually via PHPMyadmin in e107_core table, and plain and simply the admin ui ignores the values on the database....
What's going on here?

**Comment by CaMer0n** [comment]
Unable to reproduce. @Moc how about you?
@rica-carv prefs are cached.

**Comment by Moc** [comment]
I've not seen this happening on my installations but I have not tested this issue specifically

**Comment by rica-carv** [comment]
@CaMer0n It thought also it might be a cache issue, since that on the same page, if i press the save button, i have the issue, but if i after do a manual page reload (F5), it's values are returned correctly.
So why does cache behaves like this?

**Comment by Moc** [comment]
Which browser are you using? If chrome, does it also occur on e.g. Firefox?

**Comment by rica-carv** [comment]
@Moc I'm already using Firefox, so the error occurs in Firefox...

**Comment by Moc** [comment]
@rica-carv does this issue still occur?

**Comment by rica-carv** [comment]
@Moc Will test as soon as possible... Thanks

**Comment by rica-carv** [comment]
@Moc It seems it's somehow related with #2631, but i switched from the checkboxes to bs3 switches, so now i got the issue in #2631....

**Comment by CaMer0n** [comment]
looks like a var_dump()

**Comment by Moc** [comment]
This looks like leftover debug information. I assume this issue is no longer present. If it is, please let me know and I'll re-open.
