### ISSUE TITLE
weird behaviour without using e107::library('load', 'bootstrap') in theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2445]
I have theme, that used e107::library('load', 'bootstrap')
everything worked.
Than I needed to use local version (and not 3.3.7) so I used old way:  (bootstrap css is changed) 

e107::css('theme','css/bootstrap.css');
e107::js("footer", "https://cdn.jsdelivr.net/bootstrap/3.3.5/js/bootstrap.min.js");

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/23095676/1c4b516e-f60e-11e6-90f8-9cc9d1f3bca0.png)

If I add library back, it's ok.

**Comment by Jimmi08** [comment]
@lonalore Don't you know what can be reason for this?

**Comment by lonalore** [comment]
Missing CSS styles for Bootstrap Modal?

**Comment by Jimmi08** [comment]
@lonalore why would somebody exclude it? But you are right. It occured me to check scripts, but not css.  Thank you
