### ISSUE TITLE
Social buttons not working after upgrading 2.12 to 2.14

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2457]
As the title says I now get a blank button instead of the icon appearing on my news page for add to facebook twitter etc. 

Tried clearing local and remote cache to no avail.

**Comment by Moc** [comment]
I'm having some issues with these buttons disappearing as well. Will do testing asap.

**Comment by CaMer0n** [comment]
re-scan the plugin directory.

**Comment by Aaronsss** [comment]
Confirmed this resolves the issues.

Closing.
