### ISSUE TITLE
Comments Manager Preferences issue

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#2458]
Settings doesn't not work me.
See this video:

https://www.youtube.com/watch?v=3W94VcYKIRk

**Comment by fizi** [comment]
This problem same on the news (on-off comment on news).

**Comment by Moc** [comment]
Confirmed, there is an issue with saving these prefers. It worked fine before the 'slider' on/off thing.

**Comment by Moc** [comment]
@yesszus is the issue fixed?

**Comment by fizi** [comment]
Works, fixed.

**Comment by yesszus** [comment]
Yes! Fixed.
