### ISSUE TITLE
setNewsFrontMeta() can't get it works

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2461]
I need to have correct e_PAGETITLE for all parts of news, but I can't get it works. 
I think that problem is in actions:

I tried:
**1. /news/**
action = default
subaction = 0
$this->renderDefaultTemplate();

**2. /news/view/...**
action = extended
subaction = id
$this->renderViewTemplate();

**3. /news/tag/Blog**
action:tag=Blog
subaction empty
$this->renderListTemplate();

**4. /news/month/201701**
subAction:201701
action:month
$this->renderDefaultTemplate();

**5. /news/category/1**
subAction:1
action:list
 $this->renderDefaultTemplate();
 
_renderDefaultTemplate()_ call _setNewsFrontMeta()_ only with action **item** or **list**, so never for **month**.
But it calls this way for **list**:
` $this->setNewsFrontMeta($newsAr[1], 'list'); ` 
 so $type is **list** but inside is  `if($news['category_name'] && !defined('e_PAGETITLE') && $type == 'category')`  

renderViewTemplate() call setNewsFrontMeta()  - this is correct

renderListTemplate() calls setNewsFrontMeta() only with action 'cat', so it's not set for tag

**Comment by Jimmi08** [comment]
/news.php
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

/news.php?extend.3
e_PAGETITLE:	Example News Items 3
PAGE_NAME:	News

/news.php?tag=welcome&page=0
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

/news.php?list.1.0
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

**Comment by Jimmi08** [comment]
/news.php?month.2017010
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

**Comment by Jimmi08** [comment]
/news/author/admin
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

**Comment by CaMer0n** [comment]
/news.php?day.20170116

**Comment by Jimmi08** [comment]
**news/month/201701**
e_PAGETITLE:	January 2017
PAGE_NAME:	News

**/news/author/admin**
e_PAGETITLE:	admin
PAGE_NAME:	News

**/news.php?list.1.0**
e_PAGETITLE:	Misc
PAGE_NAME:	News

**/news.php?day.20170121**
e_PAGETITLE:	21 January 2017
PAGE_NAME:	News

Noticed: /news.php?day.20170122
No news items for specified _month_
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News

**/news.php?extend.3**
e_PAGETITLE:	Example News Items 3
PAGE_NAME:	News

**/news.php**
e_PAGETITLE:	(unassigned)
PAGE_NAME:	News
