### ISSUE TITLE
how to create news pages with page header?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2462]
I need to do something like this:
![image](https://cloud.githubusercontent.com/assets/5429548/23406021/325b50e2-fdbd-11e6-9695-43d57e90da78.png)

so layout looks like this:
```
<section id="header-title"> 
  ....
</section>
<div class="container">
  <div class="row">         
    <div class="col-sm-8"> 
			{---} 
    </div>         
    <!--Sidebar-->          
    <div class="col-sm-4 sidebar">
    {MENU=1}
	</div><!--End Row-->
</div>
</div>
</section>
```

it should look like this in all news pages, only title and breadcrumbs are changed.

I can do this for tags because it uses tablerender()
I can do this for single post with special layout and theme shortcode

but how to get it for news and category list?  

I could try $NEWSCLAYOUT, but how to get title for all pages? 
e_PAGETITLE is not available in theme.php or theme_shortcodes.php.  

By the way, this e107::css("inline", $inlinecss);  stopped to work in _construct in theme_shortcodes.php too, was there some change to cause this? In LZ theme. 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I believe the recent news template changes (having 'start') should allow for this now?

**Comment by Jimmi08** [comment]
@CaMer0n Yes, I think. I will test it with next theme. Thanks
