### ISSUE TITLE
LZ theme - image background doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2465]
This doesn't work:

```
	function __construct()
	{

		if($img = $this->sc_videobackground('file'))
		{
			$inlinecss = 'header {     background-image: url('.$img.') }';
			e107::css("inline", $inlinecss);
		}

	}
```
inline css is not loaded.

Image in prefs is loaded.

If I move this code to theme.php, it works.

**Comment by Moc** [comment]
So the code works in theme.php, but in which file are you currently trying it where it does not work? Shortcodes?

**Comment by LaocheXe** [comment]
If this is a theme preference, then yes, theme.php will need to load that - that's what I've used for my themes.

**Comment by Jimmi08** [comment]
@Moc  in theme_shorcodes.php  This stuff was moved from theme.php by CaMeRon to theme_shortcodes.php and it worked before.   
You can check it LZ by upload background image and then inline css should be loaded. Now is not.

**Comment by Moc** [comment]
Ok, labelled as bug.

**Comment by LaocheXe** [comment]
theme_shortcode.php is for the top navigation area, correct? I would think, for the video, or image, this should be in the theme.php.

**Comment by Moc** [comment]
@LaocheXe No, theme_shortcodes.php is the file in which all the shortcodes are defined which can be used by and all throughout the theme. I assume (as I am not using the theme at the moment) that the video background is loaded through a shortcode. Hence it is in the correct place.

**Comment by Moc** [comment]
@Jimmi08 Do you know if this issue still occurs?

**Comment by Jimmi08** [comment]
@Moc it's still issue.   e107::css doesn't work in theme_shortcodes.php.   
It worked before, that code was done by CaMeRon, now it's not working. 

So something changed and I don't know how to fix this correct way.

**Comment by Jimmi08** [comment]
@Alex-e107nl  no, there is no exception, standard layout, everything. It doesn't work for me either.

**Comment by Alex-e107nl** [comment]
That's strange... but it has something to do with the Frontpage selected Welcome message.. with every other startpage its working..

**Comment by SimSync** [comment]
@Jimmi08 LZ is the "Landig Zero" theme?
And you want a different backgroung image on the frontpage?
You have defined an image in the theme preferences at "First frame of video"?

I've just activated the "Landing Zero" theme here on my local computer and when changing the "First Frame video" setting, the start page also changes.
Maybe you can zip your theme and send it to me, to see if it makes a difference...

**Comment by Jimmi08** [comment]
@SimSync 
 if you insert first frame, there is different code used.
Insert just first image, videobackground. 
![image](https://user-images.githubusercontent.com/5429548/42464047-31950d84-83a8-11e8-9ffd-bcef22167b02.png)

If you use First frame image, then you see image inserted in video tag itself.

This code doesn't work and it worked before. So either you can't use e107::css() and then theme should be fixed or there is something wrong.

```
	function __construct()
	{
 
		if($img = $this->sc_videobackground('file'))
		{
			$inlinecss = 'header {     background-image: url('.$img.') }';
			e107::css("inline", $inlinecss);
		}

	}
```
	 
This theme was just example because it's core theme. Question is where to insert/use e107::css() with values set in Theme preferencies.  

And I am sure it worked before, because I am one of the authors of that theme.

**Comment by SimSync** [comment]
@Jimmi08 The code works, but it looks like it doesn't deliver the expected result.
Do you have the original files, before it was switched to the shortcode file?

On my computer, the function delivers either the default background (if nothing different is defined) or the selected file with some kind of blur effect. And it's the setting videoposter (first frame video) that is checked and returned.
There is also a check for "Mobile device" which may interfere here on your computer. Did you check your browser, if it is not emulating a mobile browser?

**Comment by Alex-e107nl** [comment]
Hi, i've also been busy with the code so i could change some backgrounds in a theme from the theme preferences, ive got it to work but the inline css does not always appear in the code for the frontpage of the website, it looks like the front page (FRONTPAGE) does not look into the theme preferences and does not pick it up.. (sorry for my english but i hope you get the point) It should always be shown, it would be nice if someone can change the parralax image of a theme etc..

**Comment by Jimmi08** [comment]
@Alex-e107nl thank you very much, I started to think it's my imagination only.

@Moc Can you see inserted css in your source code?  Any inline css insterted in __costruct method of theme shortcodes.php?

**Comment by Alex-e107nl** [comment]
You can see it on http://fysid.nl/demo02/ the frontpage has different backgrounds (standaard css) and it should be like http://fysid.nl/demo02/news.php , the news page has the code... the frontpage not.. why?

```
<style rel="stylesheet" type="text/css" property="stylesheet">
		.navbar-white .top-header {     background-image: url("http://www.fysid.nl/demo02/e107_themes/landingzero/images/Traffic-blurred2.jpg") }
		.jumbotron {     background-image: url("http://www.fysid.nl/demo02/e107_themes/landingzero/images/background01.jpg") }
		.breadcrumb {     background-image: url("http://www.fysid.nl/demo02/e107_themes/landingzero/images/background01.jpg") }
		.home-1 {     background-image: url("http://www.fysid.nl/demo02/e107_themes/e107_exas_accessible_nck/img/demo/port11.jpg") }

	/* Gallery CSS */
	.thumbnails .span2:nth-child(6n+1) {
	margin-left:0;
	}</style>

```

**Comment by CaMer0n** [comment]
@Jimmi08 The IF appears to be functioning correctly here. Is it possible some javascript is overriding the css?

**Comment by Jimmi08** [comment]
Your code works.

No, js is not overriding anything,  there is something weird with LZ theme - like it's not finished.  (no, no changes in 2 years, I checked it)

But you see, others have the same problem.  You can close this but LZ theme is not fully working now as it should .  (I am not able to find where those 2 images are used at all, but they are in config )    

  I am not able to find where this is used:  
```
			'videobackground'       => array('title' => LAN_LZ_THEMEPREF_00, 'type'=>'image', 'help'=>''),
			'videomobilebackground' => array('title' => LAN_LZ_THEMEPREF_01, 'type'=>'image', 'help'=>''),
```
I tried to check developer repository too, nothing. But this was one of main feature - you could replace video on mobiles by image and the same on desktop - while video is loaded, image was displayed.   First frame was something different.

**Comment by CaMer0n** [comment]
I don't get video anymore, but I think that is because amazon removed the video file, correct?

**Comment by Jimmi08** [comment]
If I remember correctly, there is no default video, you need to insert some one.  You didn't want to have it as local path.  
Try this: https://coverr.co/s3/mp4/The-King.mp4

**Comment by CaMer0n** [comment]
It's working. I like it. 
If you have a URL to an mp4 that you think will not 'disappear' any time soon, I'd be very happy to add it as the default video. 

btw. I too cannot find any reference to those prefs.

**Comment by Alex-e107nl** [comment]
Still being busy with this, inline css is not loaded (from theme shortcode) on pages with news and contact and when using the welcome message on the index page. When changing the order in header_default.php 318 from 
$CSSORDER = deftrue('CSSORDER') ? explode(",",CSSORDER) : array('other','core','plugin','theme','inline'); 
to 
$CSSORDER = deftrue('CSSORDER') ? explode(",",CSSORDER) : array('other','core','theme','inline','plugin');
Problem is solved, hows that possible? Wil try to find the bugger :-) but a little help would be nice..

Alex

**Comment by SimSync** [comment]
Please check the visibility filter in the theme preferences.
At least here, this makes a difference.

**Comment by CaMer0n** [comment]
@Moc Perhaps the issue depends on when HEADERF is loaded? Haven't looks further into it recently. 
@SimSync Do you have steps to reproduce?

**Comment by tgtje** [comment]
Should this not be exported to https://github.com/e107inc/landingzero as LZ is no longer belonging to core ?

**Comment by Jimmi08** [comment]
Because this is my issue, I am closing it. And yes, if anybody has a problem with the LZ theme, it should be there. I don't have anymore.
