### ISSUE TITLE
Enhancement -  to add ID style for signup page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2466]
If signup page use full page layout, but it has no caption, it's not possible now to render it different way as other pages with full page layout.
To avoid creating new layout it's enough to add ID to tablerender:

line 1024 
`$ns->tablerender(LAN_SIGNUP_78, $text, 'coppa');`

line 1053 
`$ns->tablerender(LAN_SIGNUP_79, e107::getMessage()->render('default', true).$text, 'signup' );`

**Comment by Moc** [comment]
For the next time, you can submit the PR directly with the contents of the issue you created in the PR comments. If it needs to be discussed, it can be done there. No need to create a separate issue for it :) 

Thanks for all the contributions as always!

**Comment by Jimmi08** [comment]
@Moc You can search issues but not PR.  Then with milestone, there is the list of solved issues. I don't think it can be done only with PR.  Or I maybe understand you wrong.

**Comment by Moc** [comment]
PR's can be searched as well, and can be labelled and milestoned. They behave exactly like the 'regular' issues. 

The changelog is based on 'tags' added to commits. The commit will refer to the pull request, so for more info a user can easily click on that PR link in the commit message. 

This means that there is no need for an issue + PR, but instead a single PR suffices?

Does it makes sense? If not I'll try another way of explaining :D

**Comment by Jimmi08** [comment]
Why I thought that I can't search PR?  Understand.  Thanks
