### ISSUE TITLE
how to get book/chapter correct order

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2472]
I undestand that if I click on column labels in admin_ui, it's reordered, but how to get it back to get correct display of book/chapter hierarchy?

My query is this: /e107_admin/cpage.php?mode=cat&action=list
(so default)

 
![image](https://cloud.githubusercontent.com/assets/5429548/23512734/e77d41c4-ff61-11e6-9e4a-416017a84699.png)

but Our history is chapter of book Pages
 
![image](https://cloud.githubusercontent.com/assets/5429548/23512746/efe434bc-ff61-11e6-8b0a-0fec41e3f145.png)

It should look like this:
 
![image](https://cloud.githubusercontent.com/assets/5429548/23512749/f7b9a438-ff61-11e6-81b8-2e707513ec90.png)

I noticed that this happens mostly after importing records, not manual adding.

**Comment by Moc** [comment]
Is this fixed with the latest changes to the Admin UI tree ordering (forum)?

**Comment by Jimmi08** [comment]
Yes, thanks
