### ISSUE TITLE
Missing SSL option

### ISSUE THREAD

**Issue by Norwayman** [e107inc/e107#2474]
I cannot find the SSL option in preferences:
![missingssloption](https://cloud.githubusercontent.com/assets/1757346/23515729/aa9499c8-ff30-11e6-8fd2-0230b86f4b73.JPG)

**Comment by LaocheXe** [comment]
@Norwayman #2407 use https://yoursite.com and look at site preferences.

**Comment by LaocheXe** [comment]
@Moc, Should add this to the Knowledge Base on the E107 website.

**Comment by Moc** [comment]
It will be added as a user guide on 'how to enable SSL/HTTPS on your e107 website' 👍
