### ISSUE TITLE
Search.php as Front Page - No matches found 

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2478]
I've set search.php as the Front Page for Everyone.  I then disable Settings > Search > Preferences > Allow user to select searchable areas.  If I then reload the front page, it immedately shows No matches found, even though I never entered any search query.  I am running 2.14

**Comment by Moc** [comment]
Confirmed. Labelled as bug. 

I've set the preference to off and when navigating to /search.php it has automatically processed a search request. I have not tried the frontpage setting but I'm assuming it's unrelated as I can reproduce the issue based on the preference setting solely, 

![image](https://cloud.githubusercontent.com/assets/577978/23547873/328e644c-0005-11e7-8377-0405bfa1b23d.png)

**Comment by BigBoiJefe** [comment]
I'd like to expand on this bug in the admin area.  Some of the check boxes change to the opposite of what I select when I update the preference.

**Comment by BigBoiJefe** [comment]
I noticed that if I link to domain.tld/search?q=
The No matches found problem goes away.
