### ISSUE TITLE
 {GALLERY_THUMB} shortcode and W3C validation

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2484]
I use this shortcode in gallery template:  {GALLERY_THUMB=w=359&h=283}
It's used in {GALLERY_PORTFOLIO}

result is:
``` 
<img class='gallery-thumb img-responsive img-fluid' src='/media/img/c3JjPWVfUExVR0lOJTJGZ2FsbGVyeSUyRmltYWdlcyUyRmJ1dHRlcmZseS5qcGcmYW1wO2F3PTM1OSZhbXA7YWg9Mjgz.jpg' alt="butterfly.jpg" srcset="/media/img/c3JjPWVfUExVR0lOJTJGZ2FsbGVyeSUyRmltYWdlcyUyRmJ1dHRlcmZseS5qcGcmYW1wO2F3PTcxOCZhbXA7YWg9NTY2.jpg 718w" width="359" height="283"  />
```

But W3C validation says:
![image](https://cloud.githubusercontent.com/assets/5429548/23555617/e5342fe0-0029-11e7-8ebd-9e5935480b5c.png)

**Comment by CaMer0n** [comment]
At the time I worked on this, I couldn't get it to function correctly on iOS using 'sizes'. If you want to try adding it, please see thumbSrcSet in e_parser_class.php

**Comment by CaMer0n** [comment]
@Jimmi08 The issue still exists?

**Comment by Jimmi08** [comment]
It is fixed. Thanks
