### ISSUE TITLE
filtering on page title doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2485]
I have page
![image](https://cloud.githubusercontent.com/assets/5429548/23556974/a7bc4d96-002e-11e7-9e34-7de79d39ba47.png)

I can't find it with (either with About me)
![image](https://cloud.githubusercontent.com/assets/5429548/23556983/af4eff4a-002e-11e7-86c7-6495e2166d2c.png)

**Comment by CaMer0n** [comment]
I'm having trouble reproducing this. Could you please enable Debug -> Sql Basics, and then enter the text ('about') and click 'Filter'.

**Comment by Jimmi08** [comment]
I tried another word.
`
SELECT SQL_CALC_FOUND_ROWS p.*,u.user_id,u.user_name,pch.chapter_sef,pbk.chapter_sef AS book_sef FROM `e107_page` AS p LEFT JOIN `e107_user` AS u ON p.page_author = u.user_id LEFT JOIN `e107_page_chapters` AS pch ON p.page_chapter = pch.chapter_id LEFT JOIN `e107_page_chapters` AS pbk ON pch.chapter_parent = pbk.chapter_id WHERE (p.page_title != '' OR p.page_text != '') AND ( p.page_text LIKE '%meet%' OR p.page_password LIKE '%meet%' ) ORDER BY p.page_order asc LIMIT 0, 10 `

**Comment by Jimmi08** [comment]
Solved. Thanks
