### ISSUE TITLE
Download Categories Tree

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2487]
There is no hierarchy in the download categories plugin in the admin area.  In the same respect there is no hierarchy in the front end display as well.  There is hierarchy for site links, maybe use the same hierarchy in the downloads plugin? :)

**Comment by tgtje** [comment]
? yes there is 
![yes](https://cloud.githubusercontent.com/assets/1811857/23579348/fd808f90-00eb-11e7-94dc-1dd07f4996e9.jpg)

**Comment by BigBoiJefe** [comment]
Yeah, I'm looking for something like site links.  It's much more user friendly.

![2017-03-04_143750](https://cloud.githubusercontent.com/assets/25377269/23582813/35f913d2-00e8-11e7-9310-24cd8418742b.png)

**Comment by tgtje** [comment]
I think you would like to see a kind of tree...where cat = main and downloads belonging to is a sub item
In downloads it is differential where you can order by cat.
I get your point, but of it will/would be more usefull? (suppose you have tons of dl's..?
It does however gives you the ability to take the other way... when you are in Manage (= downloads) you CAN click on the title caption which than orders the downloads into the cat they are put in.. 
So ... it is in the eye of the beholder ... As both carry same, but where DL is more 'differential'.
Just my point of view...let's hear other voices too...

**Comment by rica-carv** [comment]
And why not let admin choose the display of it's own choice???

**Comment by tgtje** [comment]
Hierarchy does exist (be it different ways). (primary issue)
So change of title (new one) does reflect more the actual 'íssue/enhancement'.
The actual displayed view is the key.  (what do i want to see/like to use ?)

Would be a suitable item for a poll ;-)

**Comment by CaMer0n** [comment]
Confirmed. It is missing. We need a generic solution in the admin-ui for tree-structure.

**Comment by Moc** [comment]
This has now been added, but some more testing on various MySQL versions would be appreciated. 

Documentation has been updated as well: http://e107.org/developer-manual/plugin-basics#admin-ui

> Creating a tree structure
The admin UI allows to automatically create a tree structure based on parent/child relationship tables. Examples can be found in the forum and download plugin. In order to add a tree structure, add the following code:

```php
 protected $sortField  = 'field1';
 protected $sortParent = 'field2';
 protected $treePrefix = 'field3';
```
> In this case, field1 represents the fields which determines the order (for example an ID field). The field2 represents the field which is the parent, and field3 is the child.

**Comment by CaMer0n** [comment]
Maybe add an example?
```
		protected $sortField	    = 'download_category_order';
		protected $sortParent       = 'download_category_parent';
		protected $treePrefix       = 'download_category_name';
```

**Comment by BigBoiJefe** [comment]
I tested on mySQL Server 5.7.17.  Works great. :D

**Comment by Moc** [comment]
> Maybe add an example?

Done
