### ISSUE TITLE
How to get a general breadcrumb?

### ISSUE THREAD

**Issue by eduardocp** [e107inc/e107#2488]
There is any way to get a general breadcrumb? I've tried `{BREADCRUMB}` but it doesn't work

**Comment by rica-carv** [comment]
@eduardocp I think `{BREADCRUMB}` shortcode only works in `forum_viewforum_template.php`.
I also noticed there's a [legacy (?) core breadcrumb.sc](https://github.com/e107inc/e107/blob/afbe20614b46805fc8fb169f5dd0a200bf600062/e107_core/shortcodes/single/breadcrumb.sc) file, but i think it's not used anymore.
Anyway, i think devs can enlighten better this issue...

**Comment by tgtje** [comment]
Maybe form_handler line 2848 and on  can help out (it is the sc in use) ?

**Comment by eduardocp** [comment]
@rica-carv Exactly, I had seen the breadcrumb.sc file and tried to use it, but it did not work ... and in my template I have a breadcrumb section, however I did not want to have to check which page I am in and run a different shortcode depending on the value returned...

**Comment by Moc** [comment]
@CaMer0n Your thoughts please :)

**Comment by CaMer0n** [comment]
@Moc Here's an example to render a breadcrumb. 


```
$array = array(
	0 => array('text'=>"Files", 'url'=> e107::url('files', 'index'))
);

return e107::getForm()->breadcrumb($array);
```
