### ISSUE TITLE
fatal error with Plugin Builder

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2498]
I've got this error after genarate plugin with Plugin Builder:

Fatal error: Cannot redeclare class mode in ...  \admin_config.php on line 814

In generated admin_config.php there are:

```
class mode extends e_admin_ui
{
class mode extends e_admin_form_ui
{
```

thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please try again and close if fixed. Thank you.

**Comment by CaMer0n** [comment]
@Jimmi08 is this still an issue?

**Comment by Jimmi08** [comment]
I don't know now, I will open it if I am able to test it and it will not work. Thanks
