### ISSUE TITLE
problem with e107::getDB()->gen() function

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2502]
I know that I can rewrite this with retrieve() but this is too much time consuming to rewrite each old "SELECT..." . 

I found that you can't use second e107::getDB()->gen()  inside first one and listing results:
   while ($row = e107::getDB()->fetch($result)) 

second  e107::getDB()->gen() override first one object and iteration finish after first one record.

Problem is that if you don't know that there is called next one gen() further in code. Only solution I found is using  e107::getDB('sgl2'), e107::getDB('sgl3')... 

Is this correct?

**Comment by Moc** [comment]
I think this is correct, yes.

**Comment by Jimmi08** [comment]
Too soon .
With this:
`$result2 = e107::getDB('sql2')->gen("SELECT cid, title FROM ".UN_TABLENAME_LINKS_CATEGORIES." WHERE parentid='".$cid."' ORDER BY title", true);`

query is correct:
`** SELECT cid, title FROM `e107_links_categories` WHERE parentid='21' ORDER BY title `

but e107  returns in some case (in while ($row2 = e107::getDB('sql2')->fetch($result2)) { ):
![image](https://cloud.githubusercontent.com/assets/5429548/23746376/faccf15c-04bb-11e7-8ee0-a7f79447e632.png)

**Comment by Jimmi08** [comment]
@Moc
ok, replaced e107::getDB()->db_getList();  and foreach.   retrieve() function is fine, but it's hard to set correct way, everytime it returs something else and I am not able to remember all params.  Thanks
