### ISSUE TITLE
problem with database charset with national characters

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2503]
I didn't notice this before because e107 frontend somehow managed this. But I use the same database with other CMS and I noticed this:

If I use national characters in e107 admin (German, Slovak) they are saved in database this way:
![image](https://cloud.githubusercontent.com/assets/5429548/23792630/1349ba04-0588-11e7-9097-789d465dc04c.png)

I checked:
![image](https://cloud.githubusercontent.com/assets/5429548/23792657/340ee642-0588-11e7-8e75-ad5379831425.png)
![image](https://cloud.githubusercontent.com/assets/5429548/23792669/432c40c0-0588-11e7-9366-84f7f1036399.png)
![image](https://cloud.githubusercontent.com/assets/5429548/23792691/5dbf973e-0588-11e7-902b-d8d071d56889.png)
![image](https://cloud.githubusercontent.com/assets/5429548/23792707/6f7eb5b8-0588-11e7-88e9-edeee8b1d516.png)

If I insert data right in database,  
![image](https://cloud.githubusercontent.com/assets/5429548/23792871/089cdbd0-0589-11e7-97d2-c855bdae0446.png)
e107 is not able to manage it.
![image](https://cloud.githubusercontent.com/assets/5429548/23792890/1e872b58-0589-11e7-961d-a4c8d1c676c4.png)

Thanks

**Comment by Jimmi08** [comment]
Can't be this reason?

![image](https://cloud.githubusercontent.com/assets/5429548/23794120/dcf5b3ca-058e-11e7-98ad-5dbdf4a66819.png)

**Comment by Jimmi08** [comment]
Ok,  I has used MariaDB 10.  After export and import to MariaDB 5, it looks to work as should it be. 

Server version: 5.5.53-MariaDB-1ubuntu0.14.04.1 - (Ubuntu)

Server version: 10.1.21-MariaDB-1~trusty - mariadb.org binary distribution

**Comment by tgtje** [comment]
After reading into these things, and combining and extraction of answers i would assume, it could be  that while utf8mb4....is used for connection ...overall it seems that the collation  for database and server ALSO (at least proposed) have these set as utf8mb4 (maybe charset too).. As mentioned it is a extraction of answers..if it realy is that way...(no testground)..
also a (maybe pointer, but interesting : http://mysql.rjweb.org/doc.php/charcoll

**Comment by Jimmi08** [comment]
Confirmed with XAMPP for 7.0.15 / PHP 7.0.15.
It uses Server version: 10.1.21-MariaDB - mariadb.org binary distribution
Server charset: UTF-8 Unicode (utf8)
 Server connection collation: 
![image](https://cloud.githubusercontent.com/assets/5429548/25168631/a4f66df0-24e4-11e7-945e-b18991e8ecdb.png)
Database:

![image](https://cloud.githubusercontent.com/assets/5429548/25168884/651e251e-24e5-11e7-8d1b-31e8011850b3.png)



Table:
![image](https://cloud.githubusercontent.com/assets/5429548/25168805/2bb41d1a-24e5-11e7-8ba9-228db2a517fa.png)

Data in phpmyadmin:

![image](https://cloud.githubusercontent.com/assets/5429548/25168879/5ea73d38-24e5-11e7-9094-e6b87df0ff24.png)



Data in e107:
 ![image](https://cloud.githubusercontent.com/assets/5429548/25168786/17628acc-24e5-11e7-9961-d28623fbd5b0.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I haven't performed a fresh install yet, but I did take an existing install and run it on MariaDB10 and then post comments in the chatbox.  See below: 

![screenshot-localhost-2017-04-19-08-13-32](https://cloud.githubusercontent.com/assets/2825679/25188428/dbedd32a-24da-11e7-8e46-8d4f25ab6099.png)

![screenshot-localhost-2017-04-19-08-12-45](https://cloud.githubusercontent.com/assets/2825679/25188432/e3729ac2-24da-11e7-97d9-658599ada8b3.png)

![screenshot-localhost-2017-04-19-08-33-53](https://cloud.githubusercontent.com/assets/2825679/25188466/03a3b8e4-24db-11e7-9881-feee138e751a.png)

I suspect your problem may be due to the charset(s) you are exporting/importing with.

**Comment by CaMer0n** [comment]
Fresh install of e107 on MariaDB10 - still no problem found.  Posted Japanese via the admin > News area. 

![screenshot-localhost-2017-04-19-08-46-37](https://cloud.githubusercontent.com/assets/2825679/25189041/e15c3a48-24dc-11e7-815c-440139e97fb6.png)

**Comment by Jimmi08** [comment]
Check please your database. Or try insert them in via phpmyadmin. If they are correct in db,they are wrong in e107. If you use only e107 edit, they are saved wrong in database, but frontend is correct.  I used data from db version 5 and it was displayed wrong.

**Comment by CaMer0n** [comment]
Still no issue, if I paste Japanese directly into PHPMyadmin and it displays correctly.  If I post via e107's admin or chatbox it is stored correctly.

**Comment by Jimmi08** [comment]
Closing. I will open new issue this if this happens again.

**Comment by rica-carv** [comment]
I'm still havig this issue in parts of my theme, strangelly....
Haven't figured out how and why they happen only in that parts...
I got all files saved on UTF-8 charset, and it still happens...
