### ISSUE TITLE
Latest GIT news items have whitespace padded before text...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#2504]
![image](https://cloud.githubusercontent.com/assets/4084331/23833795/bbf512c0-0718-11e7-9e4d-cd2fa650d5ba.png)

**Comment by CaMer0n** [comment]
Thanks @dimante . Please post the corresponding HTML that was generated, and the content of the database entry. (news_body)

**Comment by dimante** [comment]
`<div class="default-item">
		<h2 class="news-title"><a style='' href='/news.php?extend.9'>AP Test Score Importer for eSchoolPLUS</a></h2>

        <hr class="news-heading-sep">
         	<div class="row">
        		<div class="col-md-6"><small><i class='fa fa-user' ></i> &nbsp;<a href='/user.php?id.1'>dimante</a> &nbsp; <span class='glyphicon glyphicon-time' ></span> &nbsp;<span data-livestamp="1486608044">08 Feb 2017 : 20:40</span> </small></div>
        		<div class="col-md-6 text-right options"><small><i class='fa fa-tags' ></i> &nbsp;None &nbsp; <i class='fa fa-folder-open' ></i> &nbsp;<a class='_category' style='' href='/news.php?list.1.0'>News</a> </small></div>
        	</div>
        <hr>
          <span class="news-images-main pull-left col-xs-12 col-sm-6 col-md-6"><a href='/news.php?extend.9'></a></span>

          <p class="lead">Use the AP Test Score Importer to create the test definition and then import College Board formatted AP test score files into eSchoolPLUS.</p>
          
          <div class="text-justify">
          <img class='img-rounded rounded bbcode bbcode-img bbcode-img-news' src='/thumb.php?src=e_MEDIA_IMAGE%2F2014-05%2Fap.jpg&amp;w=300&amp;h=0' alt="Ap" srcset="/thumb.php?src=e_MEDIA_IMAGE%2F2014-05%2Fap.jpg&amp;w=600&amp;h=0 600w" width="300" style="width:300px;"  /><br /><br /><h4>Use the AP Test Score Importer to create the test definition and then import College Board formatted AP test score files into eSchoolPLUS. You can then map the scores for CDRC (OCR) Civil Rights Data Reporting! (Version 6.0 Released 11/1/2016)<br><br>Get the importer <a class="bbcode bbcode-link bbcode-link-news" style="font-family: inherit; font-size: 17.5px; line-height: 20px;" href="/e107_plugins/download/download.php?action=list&amp;id=2">HERE</a> (LOGIN REQUIRED)</h4>
          </div>
          <div class="text-right">
          
          </div>`

**Comment by dimante** [comment]
Content of News_Body.  Sorry, it took me a bit to get back to this.  Latest GIT and I even recreated the news post, same problem:


[img style=width%3A300px%3B]{e_MEDIA_IMAGE}2014-05/ap.jpg[/img]

<h4>Use the AP Test Score Importer to create the test definition and then import College Board formatted AP test score files into eSchoolPLUS. You can then map the scores for CDRC (OCR) Civil Rights Data Reporting! (Version 6.0 Released 11/1/2016)<br><br>Get the importerÂ <a class=&quot;bbcode bbcode-link bbcode-link-news&quot; style=&quot;font-family: inherit; font-size: 17.5px; line-height: 20px;&quot; href=&quot;/e107_plugins/download/download.php?action=list&amp;id=2&quot;>HERE</a>Â (LOGIN REQUIRED)</h4>

**Comment by dimante** [comment]
Another good thing to note the heading that is off is being generated by e107... It is putting the first sentence from my post as a title heading.  That is where the code issue is.

**Comment by Moc** [comment]
> It is putting the first sentence from my post as a title heading. That is where the code issue is.

We are talking about news items right? For me, I cannot create any new news items without entering a title. Otherwise it would present with a warning indicator (red line) on the news title field after pressing the create button. Are you able to do so?

**Comment by dimante** [comment]
[image: Inline image 1]

You can see the paragraph is only there once.

[image: Inline image 2]
The E107 template is taking the first sentence and placing it where I am
depicting with the yellow arrow...  Where is that controlled?  I never told
it take the first sentence and put it there...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Moc** [comment]
Which theme are you using?

**Comment by dimante** [comment]
[image: Inline image 1]

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Moc** [comment]
Still a no go on the image. Apparently you need to post the images on the Browser version of Github and not through the email...

**Comment by dimante** [comment]
I am using bootstrap 3,

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Moc** [comment]
What about my previous question: 

- We are talking about news items right? For me, I cannot create any new news items without entering a title. Otherwise it would present with a warning indicator (red line) on the news title field after pressing the create button. Are you able to do so?

**Comment by dimante** [comment]
It's not the title...
The text is only listed once "Use the AP Test Score Importer to create the test definition and then import College Board formatted AP test score files into eSchoolPLUS." 

Yet the output is taking the first sentence of the news item and putting up there causing this skewed sentence... 


![image](https://cloud.githubusercontent.com/assets/4084331/24224699/929b9628-0f2a-11e7-8fdb-8462525ee527.png)

So the black arrow is the title, the red circle is the only place I am putting text, and the blue circle is taking the first sentence of the news post and that is where the skewed output is....  It is a bug..  

![image](https://cloud.githubusercontent.com/assets/4084331/24224745/e4919504-0f2a-11e7-839c-f99384a762d7.png)

**Comment by dimante** [comment]
This further supports the statement
![image](https://cloud.githubusercontent.com/assets/4084331/24224790/325cf044-0f2b-11e7-94f2-dc94ec3a1810.png)

**Comment by Moc** [comment]
Ah I think this is the summary... I'll need to look up exactly if there's a preference to disable this behaviour but you can get rid of it by removing the {NEWSSUMMARY} shortcode from the news template.

**Comment by dimante** [comment]
I would not mind the summary, but it can't left pad unnecessarily..

**Comment by Moc** [comment]
Point taken. I'll do some tests and see what's going on.

**Comment by dimante** [comment]
But yes if you could let me know where that {NEWSSUMMARY} resides I would remove it.

**Comment by dimante** [comment]
Thanks for your help with this!

**Comment by Moc** [comment]
- Copy `/e107_plugins/news/templates/news_template.php` to `/e107_themes/bootstrap3/templates/news/`
- Edit the file by removing the {NEWSSUMMARY} shortcode. Please note that you are now using a customised news template, so with any future e107 updates, it would be good to check if there are any changes. 

I'll check for the indentation/left padding issue asap.

**Comment by dimante** [comment]
Thanks!

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
The left space problem is contained in one of these shortcode elements

{NEWSIMAGE: item=1}

{NEWSVIDEO: item=1}

With these removed that space is gone!

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by rica-carv** [comment]
{NEWS_SUMMARY} is behaving as intended.
Now the "bug" of {NEWSIMAGE} & {NEWSVIDEO} might be related to empty mews image field & empty news video field, but with my testing, the padding situation doesn't occur.... even with the core bootstrap3 theme...

**Comment by dimante** [comment]
That space is also being realized on my other site using a different
theme.  When the video shortcodes are removed it looks as I would expect
even with news_summary enabled...



Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Moc** [comment]
@dimante Is this issue still occurring in the latest version?

**Comment by dimante** [comment]
I will have to check this evening.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>
