### ISSUE TITLE
Theme shortcodes not overriding forum plugin shortcodes

### ISSUE THREAD

**Issue by eduardocp** [e107inc/e107#2506]
With a theme that overrides the `forum_template.php` file, in the html used in the variable `$FORUM_TEMPLATE['main']['start']`, if the shortcode is unique to the theme, it is not displayed.

**UPDATE:**
Current list:

```
$FORUM_TEMPLATE['main']['start']
$FORUM_TEMPLATE['main']['parent']
$FORUM_TEMPLATE['main']['end']
```

Two more add (thanks @rica-carv): 
```
$FORUM_TEMPLATE['main']['parent']
$FORUM_TEMPLATE['main']['end']
```

**Comment by rica-carv** [comment]
On fetching the code, i think there's 2 more areas not rendering theme overriden shortcodes:
$FORUM_TEMPLATE['main']['parent']
$FORUM_TEMPLATE['main']['end']

If anyone could do some further testing, i would appreciatte...

Furthermore, there are also some "legacy" forum defined templates that might be affected by this issue...

**Comment by Moc** [comment]
@eduardocp currently your commit is not pushed as a pull request yet. Just making sure you know.

**Comment by Moc** [comment]
Nevermind, it was already merged. Closing this one.
