### ISSUE TITLE
enhancenment to login as main admin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2513]
new feature in login.php is good, but confusing. maybe this would help: 

> There should be at least button Go to Frontend in this message. Or you are seeing this message only because you are mainadmin. Continue to ...index.php

**Comment by CaMer0n** [comment]
Good idea! Pull-request welcome.

**Comment by Moc** [comment]
Looking like this now: 

![image](https://cloud.githubusercontent.com/assets/577978/24175758/42eec83a-0e98-11e7-9d79-ca8a34e6aa73.png)
