### ISSUE TITLE
Unable to use theme visibility filter on dynamic url data.

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2514]
I'm using the default namespace as Download, however, when I do that, there's no /download/ set in the URL so I'm unable to set download in the visibility filter.  I've tried using regex code as the urls created are https://mydomain.com/downloadid/sef-name however, that didn't work.

Your urgency would be greatly appreciated. 

Thanks.

**Comment by Moc** [comment]
Hmm, for me it works like expected. If I use the following settings, all the download plugin pages show up in the jumbotron full-width layout. 

![image](https://cloud.githubusercontent.com/assets/577978/24194455/77ab42ca-0ef6-11e7-9d15-c65b53800a41.png)

Is this not the case for you? Maybe I am misunderstanding your issue.

**Comment by CaMer0n** [comment]
Another way around this is to set THEME_LAYOUT inside e107_config.php

    if(check-whatever-you-like)
    {
        define("THEME_LAYOUT", 'my-layout');
    }

**Comment by BigBoiJefe** [comment]
I include regex in the if statement?

**Comment by BigBoiJefe** [comment]
Ok.  After thinking about this further, this is a non issue.  My simple workaround was the following:

1.  Set the default layout as the layout I wanted to use for the downloads. 
2.  Set the homepage theme layout visibility to FRONTPAGE.
