### ISSUE TITLE
Question: how to use mail function for the plugin's event

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2518]
Hi again all,
i'm on making a plugin, a loyalty card plugin..
it's done, but i want to make member get an email, when their card punched or when they got a reward.
when i see a default script for admin_config.php there is a function call afterCreate() .. how it work?
is it using any specific parms or just check a $_POST value ?

thank you in advance for your help
Indra

**Comment by Moc** [comment]
Hi! 

So there are two options here I think, depending on how your plugin works. 

1) The `afterCreate()` method is triggered after the manual creation of an entry/item in the admin area of your plugin. It will pass on the $_POST values of the new entry. There are some examples in the existing plugins and core areas such as 'news'. 

2) Use event triggers. They are documented here: http://e107.org/developer-manual/classes-and-methods#events 
You could use the `e_event` addon (such as the one here: https://github.com/e107inc/e107/blob/master/e107_plugins/news/e_event.php) to perform an action (ie. sending an email) after an event is triggered (ie. when their card is punched / when they receive a reward). 

Depending on how your plugin is structured, you would choose either option or a combination of both, but I suspect that in your case the 'events' option is the way to go. 

Hope this helps! 
Let us know if you have any further questions :)

**Comment by Moc** [comment]
Edit:

Actually, the `e_notify` addon may be the most suitable for you: http://e107.org/developer-manual/plugin-basics#extending-core-functionality (scroll down to e_notify.php)

Example: https://github.com/e107inc/e107/blob/master/e107_plugins/_blank/e_notify.php

It is similar to the functioning of the `e_event` addon, but in this case, it is used for triggering notifications (ie. sending emails) upon a certain action.

**Comment by drasehat** [comment]
awesoome! thanks a lot @Moc

**Comment by Moc** [comment]
No problem! 👍 Are you going to make the plugin public? 

I'm closing this issue as I assume it's all answered. If not, just reply here and I'll re-open.

**Comment by drasehat** [comment]
i'm not sure .. maybe when the all project done, i will share it to the public, right now it only support to my website.
ok .. thanks again

**Comment by Moc** [comment]
Sounds like a plan, you know where to find us if you need any help. Feel free to barge in on our chatroom: https://github.com/e107inc/e107 if you want to discuss ideas or get some inspiration or help.
