### ISSUE TITLE
forum.php- Error %20 on line 109 (FOUND & SOLVED)

### ISSUE THREAD

**Issue by nS56p3j** [e107inc/e107#2525]
I am using v2.1.1
    ​I created a fresh install with new database.
    Installed **forum plug-in**.
    Near the footer of the forum display shows...
[the error is the %20 when selecting my profile]

    Top Posters | Most Active Topics | My Posts | My Settings | # **My Profile**
    http://---------------/user.php**# %20**?id.1

The error is on **line 111** in forum.php
see below: just remove the space where the |*********| is ; 
then; save and upload.

$rules_text = forum_rules('check');

$fVars->USERINFO = "<a href='".e_BASE."top.php?0.top.forum.10'>".LAN_FORUM_0010."</a> | <a href='".e_BASE."top.php?0.active'>".LAN_FORUM_0011."</a>";
if(USER)
{
 $fVars->USERINFO .= " | <a href='".e_BASE.'userposts.php?0.forums.'.USERID."'>".LAN_FORUM_0012."</a> | <a href='".e_BASE."usersettings.php'>".LAN_FORUM_0013."</a> | [<]a href='".e_HTTP."user.php #  |*********|?id.".USERID."'>".LAN_FORUM_0014."</a>";
 if($forum->prefs->get('attach') && (check_class($pref['upload_class']) || getperms('0')))
 {
  $fVars->USERINFO .= " | <a href='".e_PLUGIN."forum/forum_uploads.php'>".LAN_FORUM_0015."</a>";
 }
}
if(!empty($rules_text))
{
 $fVars->USERINFO .= " | <a href='".e107::url('forum','rules')."'>".LAN_FORUM_0016.'</a>';

ORIGINALLY POSTED AT https://www.e107help.org/2636/forum-php-error-%2520-on-line-109-found-%26-solved?show=2636#q2636 ON - Asked Jul 25, 2016  AND WAS SINCE ASKED TO MOVE IT HERE.

**Comment by nS56p3j** [comment]
You may roll-over the ".LAN_FORUM_0014."";  _**ABOVE**_ to see the |**********|
 or look at this attachment........ 
[forum.php- Error %20 on line 109 (FOUND & SOLVED.TXT](https://github.com/e107inc/e107/files/870431/forum.php-.Error.20.on.line.109.FOUND.SOLVED.TXT)

**Comment by rica-carv** [comment]
@nS56p3j V2.1.1 is outdated, and $fVars are already been completely removed from forum plugin.
Update to latest version 2.1.5 and check if error persists...

**Comment by Moc** [comment]
@nS56p3j Thank you for your contribution. As mentioned by rica-carv, please check if the issue is present in the latest version of e107, which at the time of writing, is 2.1.5. It may well be that your issue is already resolved. 

Please let us know.

**Comment by Moc** [comment]
I am assuming this issue has been fixed as per the comments above. Please let us know if the issue still occurs and I'll re-open.
