### ISSUE TITLE
Issue: HTTPS and Plugins

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2526]
I've notice an issue, and I though that it was server side, but it's weird.

I have a site that uses https (https://clancoyote.com)

My Plugin Voice_eXe is enabled. That team just set up a Discord server,and in Voice I went in and added the info, when hitting submit/create I get a 403 Forbidden Error

You don't have permission to access /main/e107_plugins/voice/admin_config.php on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

https://clancoyote.com/main/e107_plugins/voice/admin_config.php?action=edit&id=2

is the url. Checking the error log all I see is that www/main/e107_plugins/voice/admin_config.php?action=edit&id=2 is not found.

After some trouble shooting I notice that the share link is https:// and http://- if I put in no https:// I can create the Discord, and edit it, but if I add the https:// or http:// I get that error. any ideas?

**Comment by Moc** [comment]
Can you check the file permissions on this file? They should be CHMOD 644.

**Comment by LaocheXe** [comment]
@Moc the file is 644, and just my plugin that I can tell, the field is set for text, is there a new field for links, or urls that has been added and I should use?

**Comment by Moc** [comment]
Ok, then my best guess is that a HTTP resource is being called on the HTTPS page. This may throw a 403 error. It is not an e107 error but rather an error in your plugin... 

Do you have a link to the code?

**Comment by LaocheXe** [comment]
https://github.com/LaocheXe/Voice-eXeSystem/tree/master/voice

**Comment by tgtje** [comment]
Just a listing of http links inside: 

> License (call for fsf) > textual.. should not be of influence

admin config > td align="left"><i> <a href="http://defiantz  (line. 137)

voice exefont svg (voice/font/ )
!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg">

English php
define("LAN_VOI_INFO_IN_VENT", "<a href='http://www.ventrilo.com
define("LAN_VOI_INFO_IN_BLE", "<a href='http://wiki.mumble.info

maybe (needs look into : Uri php (servername)

plugin xml
<author name="LaocheXe" url="http://defiantz.org" />

**Comment by Moc** [comment]
@LaocheXe Can you give me some example info to add a new discord server via Gitter. Then I can try and test if I can reproduce the issue here. 

Did you check the server error logs for any clues?

**Comment by LaocheXe** [comment]
Found the issue, my own stupidity - I don't use a URL for that, so if an invite URL is https://discord.gg/Ssn7n9h - use the last part - Ssn7n9h - god I screwed up.

**Comment by Moc** [comment]
Haha dont worry, we all make silly mistakes from time to time :D
