### ISSUE TITLE
Classic theme forum layout broken in latest git

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#2530]
![screen](https://cloud.githubusercontent.com/assets/11775356/24423478/fd740a74-13f4-11e7-8713-f00b0765f8d5.PNG)

Latest git seems to break legacy theme forum layouts

**Comment by Moc** [comment]
Hmm, strange. This was working fine before?

**Comment by Brooniee** [comment]
@Moc 

Yes, working before.
Yes, using a theme from v1.

**Comment by CaMer0n** [comment]
@Brooniee Which theme are you using? It would helpful if we could test with it, or something similar.

**Comment by Brooniee** [comment]
@CaMer0n 
The theme's based off of:
http://e107.org/themes/?id=85

**Comment by Jimmi08** [comment]
I've just installed this theme and it looks correct. Check you console for some css errors. It looks like your css is not loaded. After update to latest github too.

![image](https://cloud.githubusercontent.com/assets/5429548/26046484/660fdf98-394f-11e7-8c25-fc1ec685cf10.png)

**Comment by Brooniee** [comment]
@Jimmi08 Thanks Jimmi, I've updated to latest git but still no dice.

Any ideas where to look if CCS is not loading?

**Comment by Jimmi08** [comment]
@Brooniee of course. Check console (F12 and second button) . If your site is online, find me on gitter, I could look at it.

**Comment by Moc** [comment]
I am assuming this issue has been resolved. If the issue is still occurring, please let us know and I'll re-open.
