### ISSUE TITLE
Core Theme update to 2.1.0 results in error

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#2531]
![screen2](https://cloud.githubusercontent.com/assets/11775356/24423528/2b5026bc-13f5-11e7-9938-824c2fdecc5e.PNG)

Nothing is shown in apache error log

**Comment by Moc** [comment]
This is likely a server configuration issue. 

@BigBoiJefe since you have some experience with this error, could you give some advice here? :)

**Comment by CaMer0n** [comment]
@Brooniee Please join us in the chatroom if you have time. ( https://gitter.im/e107inc/e107 )  I'd be happy to work through the issues with you.

**Comment by Jimmi08** [comment]
Confirmed with plugin too (online site, 5.5.38):

![image](https://cloud.githubusercontent.com/assets/5429548/25069582/acb63a90-2285-11e7-8f34-1de03967af27.png)

![image](https://cloud.githubusercontent.com/assets/5429548/25069579/a0b76ae8-2285-11e7-9372-3c01993027cb.png)

**Comment by CaMer0n** [comment]
Please update and try again. Thank you.

**Comment by Jimmi08** [comment]
Tested, for me it worked with plugin.
