### ISSUE TITLE
Unable to add new menus (may be related to outdated core theme)

### ISSUE THREAD

**Issue by brwnie** [e107inc/e107#2532]
![capture](https://cloud.githubusercontent.com/assets/11775356/24423656/a2802368-13f5-11e7-8396-75e73b84544e.PNG)

Ticking box and clicking Go does not add menu's to page

Tried dragging and dropping too.

Firefox 53.0b6

**Comment by Moc** [comment]
When you click 'Go', do you get the screen which allows you to select a menu area?

**Comment by Brooniee** [comment]
@Moc Nothing happens with 'Go' button

I'll check console and get back to you.

**Comment by Brooniee** [comment]
@Moc 

Only thing in console is:

Empty string passed to getElementById().

**Comment by CaMer0n** [comment]
I'm unable to reproduce this problem.  (and I have heard it mentioned by others) 
Until someone who **can** reproduce grants me access to their admin, I don't believe there is much hope of correcting it.

**Comment by Brooniee** [comment]
@CaMer0n 
Could I have an e-mail address to send credentials too?

**Comment by CaMer0n** [comment]
Please paste here: https://gitter.im/CaMer0n

**Comment by Brooniee** [comment]
@CaMer0n credentials across to you now

**Comment by Moc** [comment]
@Brooniee Has this issue been resolved?
