### ISSUE TITLE
New Forumpost menu settings

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2533]
The menu not accept the new settings.
 I set number of items 6 (was 8) save it, after this open again and display 8 - I can not change it.
The latest News menu the problem same.

**Comment by CaMer0n** [comment]
I'm unable to reproduce this. Are you running 2 different menu tables by chance?

**Comment by fizi** [comment]
I have 4 layout: two columns (default), home, full width and extend news. The new forumpost menu on the footer (default). The settings work on all layout except of the two columns (default). This problem appears on the latestnews menu too. I can set the number on the home, full width, but I can not change it on the default layout (two columns). It is very interesting.

**Comment by Moc** [comment]
@fizi Is this issue still occurring in the latest version?

**Comment by fizi** [comment]
I think the problem solved.
