### ISSUE TITLE
News Tags

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2538]
I wrote more as one tag and appears tags with comma (between tags)

**Comment by Moc** [comment]
The comma between tags is the default separator, but which can be changes by changing the shortcode parameter. For example: 

`{NEWSTAGS: separator= &class=btn btn-white btn-xs}`

Does this allow you to achieve what you want?

**Comment by fizi** [comment]
This is the part of cource. No separator, only comma:
`<a class='news-tag' href='/v2/news/tag/culture'>culture</a>, 
<a class='news-tag' href='/v2/news/tag/carneval'>carneval</a>, 
<a class='news-tag' href='/v2/news/tag/rendezv%C3%A9ny'>rendezvény</a>, 
<a class='news-tag' href='/v2/news/tag/velence'>velence</a>`

**Comment by Moc** [comment]
But which shortcode are you using? Any parameters?

**Comment by fizi** [comment]
Ok, the {NEWSTAGS: separator=&nbsp;} work, if I not want the comma in the theme layout.
