### ISSUE TITLE
enhancement to be able use e107::js() with async

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2541]
I need to use e107::js()  for this:

```
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
		        async defer>
		    </script>
```
there are pre and post params but there are pre and post script tags. Something to add code inside script tags.
Thank you

**Comment by Jimmi08** [comment]
related:
https://github.com/e107inc/e107/issues/618

**Comment by LaocheXe** [comment]
I got to ask, what about rsync?

**Comment by Jimmi08** [comment]
@LaocheXe I would prefer any string where you can write what you need. like pre and post param.

**Comment by CaMer0n** [comment]
Did you use footer-inline and just paste the code above?

**Comment by Jimmi08** [comment]
@CaMer0n No, I used theme_foot() function, yes, I know it's deprecated.

**Comment by Jimmi08** [comment]
It works, just for others, full code:
```
      e107::js("footer-inline", '<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
		        async defer>
		    </script>' );
```
with this is loaded at zone 5. 
Thanks, for me solved.
