### ISSUE TITLE
HTML Title, META Description, META Keywords

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2544]
Is there anyway to ensure that each page has it's own html title, meta description and meta keyword?

**Comment by Moc** [comment]
@CaMer0n If I remember correctly this is possible right? Is there some documentation on this? 
@lonalore Maybe you know more about this? :)

**Comment by CaMer0n** [comment]
@Moc @BigBoiJefe Yes, if you look in header_default.php it should be pretty self explanatory. 

    if(empty($isKeywords))
    {
	    echo (defined("META_KEYWORDS")) ? "\n<meta name=\"keywords\"    content=\"".$key_merge.META_KEYWORDS."\" />\n" : render_meta('keywords');
    }
    if(empty($isDescription))
    {
	    echo (defined("META_DESCRIPTION")) ? "\n<meta name=\"description\" content=\"".$diz_merge.META_DESCRIPTION."\" />\n" : render_meta('description');
    }

Just add the constants to a specific page before the HEADERF.
