### ISSUE TITLE
shortcodes in links not working in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2545]
For homepage I need just icon home, so I use {SITEURL} as link in Sitelinks.
It works on Frontend, but in admin links there is wrong path

![image](https://cloud.githubusercontent.com/assets/5429548/24577917/2f90af50-16d7-11e7-83ca-516297980fb6.png)

here

![image](https://cloud.githubusercontent.com/assets/5429548/24577932/421c4a76-16d7-11e7-82b7-d7b1a8499903.png)

**Comment by CaMer0n** [comment]
Did you try using just ` / ` instead of `{SITEURL} ` ?

**Comment by Jimmi08** [comment]
Yes, of course.  Result was one reductant / on Frontend.  {SITEURL} works on Frontend, only not in admin. If this is correct, you can close it.

**Comment by Moc** [comment]
@Jimmi08 still an issue?

**Comment by Jimmi08** [comment]
Yes, at least {SITEURL} doesn't work.  Or I didn't find way how to insert home page to menu without index.php

**Comment by Jimmi08** [comment]
This is solved for me now using canonical plugin.
