### ISSUE TITLE
Preferences > Emailing Method > SMTP > Send Test Email - Looping

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2555]
I've tried 3 different SMTP hosts, each with varying security and every time I click on the send test email button it looks like the page just loops.

**Comment by BigBoiJefe** [comment]
I noticed that when the settings aren't correct looping occurs.

**Comment by Moc** [comment]
My guess is that this will be different for every server configurations. 
If this still is an issue, I'd recommend having someone like Cameron look at this through Gitter so he can debug it for you.

**Comment by BigBoiJefe** [comment]
Yeah, this is an odd one because I was able to use a different SMTP host and I no longer have this issue.  For me, i used mailgun, and I had no problems, though, I agree with @Moc that it may have just been a configuration issue with my previous SMTP host.
