### ISSUE TITLE
Block Certain Email Domains from Registering

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2557]
There's some email domains that I would like to block from registering.  Thanks!

**Comment by LaocheXe** [comment]
This is a good idea for an enhancement

**Comment by BigBoiJefe** [comment]
Looks like there's already a huge list of disposable email domains:

`https://github.com/martenson/disposable-email-domains/blob/master/disposable_email_blacklist.conf`

**Comment by LaocheXe** [comment]
If I recall, the stop forum spam site had a lis5 as well, and the gas plug8n uses such a list which also blocked ema8ls, but not email domains

**Comment by Moc** [comment]
Yeah, I don't think this is core area territory. Plugins such as the SFS plugin are very effective in stopping spambots from registering on your website (other examples are VisualCaptcha or reCaptcha).

**Comment by CaMer0n** [comment]
I was sure we had something built-in for this at some point. Can't find it now though.

**Comment by BigBoiJefe** [comment]
Maybe I wasn't clear what I was looking for?  What I'm talking about is blocking disposable domains from registering on your site.  Disposable domains aren't necessarily used my spambots.  I dunno ;)

**Comment by Moc** [comment]
In v1, this was done through the ban list... Not sure where it is located in v2 now.

**Comment by CaMer0n** [comment]
@Moc Yeah, I found it in the meantime. I've just upgraded the banlist admin area so it saves the email addresses/hosts etc. No idea if the ipHandler still manages the ban correctly though, will need some testing.

**Comment by BigBoiJefe** [comment]
So can I add @domain.com?

**Comment by CaMer0n** [comment]
`*@domain.com`

**Comment by CaMer0n** [comment]
@BigBoiJefe Did this work for you?

**Comment by Moc** [comment]
@BigBoiJefe can you please verify that this feature works now?

**Comment by BigBoiJefe** [comment]
I am sooo confused.  Where is the option to list *@domain.com

**Comment by Moc** [comment]
In `Banlist > Add to blacklist` - `/e107_admin/banlist.php?mode=main&action=create`
First row: `Enter IP, email address, or host`

Can you confirm if it works?

**Comment by BigBoiJefe** [comment]
If I add *@domain.com to the ban list and try to register a user account with an @domain.com email address, after I click the register button the page reloads and is blank.

**Comment by SimSync** [comment]
@BigBoiJefe Could you please check if this issue is fixed?

**Comment by SimSync** [comment]
@Reconix Did you update to the latest GitHub version? On my system, this issue (the white page) doesn't happen, even without the extension or the full domain...

**Comment by Reconix** [comment]
Just downloaded the latest version and tested again we get Invalid format Error 12 now for an email without an extension.
and banned emails working as expected.

Nice one, we can close this now ?
