### ISSUE TITLE
Installation issue at 8th step on byet.host !

### ISSUE THREAD

**Issue by JoePT** [e107inc/e107#2559]
I have this message when I try to install e107 v2.1.5 : 

CRITICAL ERROR:
Line 496 /home/vol10_8/byethost32.com/b32_19952812/htdocs/class2.php
[3]: Core settings saved - backup made active.

CRITICAL ERROR:
Line 498 /home/vol10_8/byethost32.com/b32_19952812/htdocs/class2.php
[4]: No core backup found. Check that your database has valid content. 

Any idea to solve this problem ? 
Thanks.
Joe

**Comment by CaMer0n** [comment]
@JoePT Which version of PHP are you using?

**Comment by JoePT** [comment]
Hello Cameron, thanks for your attention. 

My PHP and MySQL version are : 
PHP version: 	5.6.23
MySQL version: 	5.6.30

Thanks.
Joe

**Comment by CaMer0n** [comment]
@JoePT Did you try using the github version? I just ran a clean install of it using PHP 5.6 without any issues.

**Comment by JoePT** [comment]
Yes, I tried 3 times to install the version 2.1.5 : each time I deleted all files and re-uploaded them to the server and even deleted each time de SQL Database and re-created it each new install... I even tried installating 2.1.5 with 3 differents PHP version from 5.4 to 5.6 but no way :(

**Comment by atartagli** [comment]
check if your hosting antivirus delete class2.php file for any kind of stupid security reason.
It happened to me two times some months ago.

**Comment by tgtje** [comment]
Byet host install (2.1.5 with recently updated files) > SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB'  Byet does not use InnoDB

does this help for pinpointing ? (online uses it).

**Comment by JoePT** [comment]
@tgtje it was that problem and I was trying to install e107 on byethost server !

**Comment by CaMer0n** [comment]
@JoePT Bad host. Most of us are already using MySQL 5.6. 
> InnoDB is a storage engine for the database management system MySQL. **MySQL 5.5 and later use it by default**. It provides the standard ACID-compliant transaction features, along with foreign key support.

**Comment by CaMer0n** [comment]
@JoePT Could you try to find out which version of MySQL they are running?

**Comment by JoePT** [comment]
@CaMer0n they're using MySQL version: 5.6.30...

**Comment by CaMer0n** [comment]
@JoePT Thank you. Very odd. "Syntax error or access violation"  - maybe a syntax it doesn't like? If you have time, please join me in the chatroom, I'd be interested to try to install it for you on your host for you. 
https://gitter.im/e107inc/e107

**Comment by tgtje** [comment]
Just adding : here's what e107 install  reports (on Byet free)
![naamloos hersteld](https://cloud.githubusercontent.com/assets/1811857/25018656/1cedf3b6-2088-11e7-8c2b-86e977a539ff.jpg)

**Comment by JoePT** [comment]
yes man, I had same "pass" checked services but at step 8 ... bug !

**Comment by CaMer0n** [comment]
### Support Ticket to byet

**Question:** 

 _Is InnoDB disabled on the free hosting plan?_  

**Answer:** 

_That is correct, we run engine substitution on free hosting to make innodb queries transaction to myisam, however if you need full fat innodb you would need premium hosting._

**Comment by CaMer0n** [comment]
## Workaround for byet.host

### 1). Edit _e107_core/sql/core_sql.php_

Remove `ENGINE=InnoDB` from this query (currently on line 366) 
(Make sure you keep the **;** at the end) 

    CREATE TABLE online (
      online_timestamp int(10) unsigned NOT NULL default '0',
      online_flag tinyint(3) unsigned NOT NULL default '0',
      online_user_id varchar(100) NOT NULL default '',
      online_ip varchar(45) NOT NULL default '',
      online_location text NOT NULL,        
      online_pagecount tinyint(3) unsigned NOT NULL default '0',
      online_active int(10) unsigned NOT NULL default '0',
      online_agent varchar(255) NOT NULL default '',
      online_language varchar(2) NOT NULL default '',
      KEY online_ip (online_ip)
      ) ENGINE=InnoDB;

### 2) Install e107 normally. 

### 3) In PhpMyAdmin > SQL

`ALTER TABLE `e107_online` ENGINE = InnoDB`
