### ISSUE TITLE
Setting Downloads as Root namespace

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2563]
When setting Downloads as Root namespace in Settings > URL Configuration > Settings.  The Downloads appear on my home page even though I didn't specifically define the Downloads to appear in that menu.  Granted, I understand that this may be by design.  However, my goal is show files as 

https://domain.com/category-sefname/sub-category-sefname/downloadid/sef-name

**Comment by BigBoiJefe** [comment]
How does one access the categories for the downloads when this is set?

**Comment by CaMer0n** [comment]
You set 'downloads' as your frontpage, or you manually create a link to the categories in your navigation.
