### ISSUE TITLE
SMF to e107 Importer didn't import thread body

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2564]
I ran the importer and it didn't import the thread body

**Comment by BigBoiJefe** [comment]
I saw that the forums needed to be upgraded to version 1.2, so I clicked on that.  It looks like, there's something wrong here.

Error
Creating table forum_thread
Creating table forum_post
Creation of table(s) failed. You can not continue until these are created successfully!

**Comment by CaMer0n** [comment]
Was it a fresh install of e107 before you did the SMF import?

**Comment by BigBoiJefe** [comment]
No it wasn't, it was an upgrade from 0.7.15.  I just right now, removed the forum tables, removed the plugin, then reinstalled the plugin and re-imported, and it worked.  The thread body is show now.

**Comment by CaMer0n** [comment]
Sounds like you were trying to run an import on a v1.x forum database structure.  The forum needs to be fully upgraded to v2 before running an import on it.

**Comment by BigBoiJefe** [comment]
Yeah, that's what looks like exactly.
