### ISSUE TITLE
Forum and Sub Forum Not Showing after Import

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2566]
I don't know what's going on.  A forum and sub forum aren't showing.

![image](https://cloud.githubusercontent.com/assets/25377269/25030640/23ff0fee-207b-11e7-93a4-1eec6a4cb124.png)

**Comment by Moc** [comment]
Is this the same.installation you did the SMF import on?

**Comment by BigBoiJefe** [comment]
Yes.

**Comment by CaMer0n** [comment]
Like I said, there's a lot of guess work that happens with importing when we only have the table data to go on.  ;-)

**Comment by BigBoiJefe** [comment]
I understand.  I need to get this going though ;).  What now?

**Comment by CaMer0n** [comment]
If you can find the DB query that SMF uses to load the forum 'tree', that might provide clues.

**Comment by Moc** [comment]
@BigBoiJefe Any feedback on this?

**Comment by BigBoiJefe** [comment]
This was caused by the forum categories not having the correct permissions.
