### ISSUE TITLE
how I change/set admin theme?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2570]
How one can set new admin theme?

**Comment by BigBoiJefe** [comment]
e107_admin/theme.php?mode=main&action=admin

**Comment by Jimmi08** [comment]
I don't see there any possibility to change admin theme from bootstrap3 to other theme with different name.

**Comment by Moc** [comment]
Changing the admin theme is currently not possible and is not on the immediate roadmap. You can customise it through stylesheets as well as options such as Flexpanel.

**Comment by Jimmi08** [comment]
Problem is not in css, I need to change bootstrap 3 admin template (I am only one who dislike latest changes in top navigation and I am able to change it  back), but it will be overrriden by github update. Any workaround would be enough, setting something in prefs in database too.  Thanks

**Comment by Moc** [comment]
@CaMer0n thoughts?

**Comment by CaMer0n** [comment]
Admin theme changes (other than theme 'style') are not possible. And are not a planned feature.

**Comment by Jimmi08** [comment]
@CaMer0n how to get back titles in first level menu? why they are hidden on lg ?

**Comment by rica-carv** [comment]
@Jimmi08 Indeed, responsivness is bootstrap middle name....

**Comment by CaMer0n** [comment]
Closing. Original question answered.
