### ISSUE TITLE
problem with caching css

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2571]
I really don't know if this is e107 problem, so this is just warning

I have correct css file (style.css), but this .split a

![image](https://cloud.githubusercontent.com/assets/5429548/25062472/fb07ff08-21cc-11e7-9006-bc0ab26e3749.png)

is changed after caching to:
![image](https://cloud.githubusercontent.com/assets/5429548/25062475/07b92b82-21cd-11e7-8c14-8231266ad12e.png)

Only way how fix this was using > in css.

**Comment by CaMer0n** [comment]
I would like to copy/paste your example so I can test it, but it's an image. Can you please paste the original CSS? Thanks.

**Comment by Jimmi08** [comment]
Of course. Sorry. 
```
.split   a {
 color: white; 
}

```

**Comment by CaMer0n** [comment]
Please test with the changes in Github. Does it correct the issue?

**Comment by Jimmi08** [comment]
Closing. I already fixed it different way and it's live site. If it happens in future, I will reopen this. Thank you.
