### ISSUE TITLE
cached css is loaded after inline css

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2572]
If you use e107::css("inline", $inlinecss1);  in you theme  and set caching css files, 
cached file is loaded after inline css and so it doesn't work.

![image](https://cloud.githubusercontent.com/assets/5429548/25062648/335a12f8-21d0-11e7-9005-32cdf6141cbb.png)

**Comment by CaMer0n** [comment]
@Jimmi08 is this fixed now?

**Comment by Jimmi08** [comment]
@CaMer0n I will test it asap, I am doing different things now.

**Comment by CaMer0n** [comment]
okay, thank you!

**Comment by Jimmi08** [comment]
It's ok now. Thank you.
