### ISSUE TITLE
I can't insert image in forum post

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2577]
Probably doing something wrong.

Button insert image. Inserting full path (shortcodes doesn't work) to e107_media folder with hash in path

I see it's inserted correctly while editing:
 
![image](https://cloud.githubusercontent.com/assets/5429548/25069709/8e00f49c-2289-11e7-8161-a91abfbd72ab.png)

After posting there is just placeholder:
![image](https://cloud.githubusercontent.com/assets/5429548/25069722/e0944948-2289-11e7-8331-9d467ddc2617.png)

the same if I use different path f.e. to e107_images/

**EDITED:  if I use external path to other site, it works.** 

Thanks

**Comment by CaMer0n** [comment]
Pasting the full path to an image on the server is considered bad-practice. 
I have added a SEF-URL column in the Media-Manager so that admin can copy/paste it when needed into forum posts.

**Comment by CaMer0n** [comment]
Closing.
