### ISSUE TITLE
Change colors of glyphs in site links and download categories.

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2582]
I'd like to have an option to change the color of glyphs in the the site links and download categories.

Thanks.

**Comment by CaMer0n** [comment]
You can use CSS for this.

**Comment by BigBoiJefe** [comment]
I was wanting to change the color at the time of selection of the glyph

**Comment by rica-carv** [comment]
Add a custom class in the template and add a css rule to change color when on hover. Simple...

**Comment by Moc** [comment]
This is all modifiable through templates/themes. Adding this as an option in core would be too much. 

Closing.
