### ISSUE TITLE
[feature request] please make snippets folder in tinymce plugin like templates folder

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2584]
greetings all,
just found out the snippets folder (e107_plugins/tinymce/snippets) is have auto-read function..
snippets folder can read html/php files for tinymce template, you can try it in tinymce box (insert->template)
it will show you 2 templates (bootstrap table and column).
you can add more files in it, then you can select your files to make some html/php template to tinymce box,
for instance you can add template about call-to-action section with your own style, then drag it to tinymce!!
it would be great feature, if we can make e107 read snippets folder like plugin templates folder (mytheme/snippets), so the user with no-script skill can build their own pages based on our theme.
any suggestion ?

thank you in advance
Indra

**Comment by CaMer0n** [comment]
@drasehat Untested code. Please test. Thanks.

**Comment by drasehat** [comment]
thanks @CaMer0n  i will test it, and if it works .. i will post a tutorial video here

**Comment by drasehat** [comment]
did sync with latest github.
it's not working.. even with default template (e107_plugins/tinymce4/snippets/bootstrap_table.htm) became an empty field.

**Comment by CaMer0n** [comment]
@drasehat I made some changes, please try again. Thanks.

**Comment by drasehat** [comment]
working great, thank you !!
