### ISSUE TITLE
Incorrect admin-menu icon displayed on URL Configuration page. 

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2588]
Go to Admin Area > URL Configuration > Update (Click Update Button) 
![capture](https://cloud.githubusercontent.com/assets/5818022/25211209/b313ad52-2549-11e7-8893-d16b520d8f85.JPG)

The Icon for the Site URL's change, The image I shared shows the YouTube Plugin Icon, on another site I get the Social Icon

**Comment by CaMer0n** [comment]
It tried to grab another plugin icon for me. Something strange happening there.

**Comment by rica-carv** [comment]
Gremlins? 👹 😄
