### ISSUE TITLE
Download category link not work

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2589]
I click on the category of download page and the download list not open. (load only the categories page)

**Comment by 214945** [comment]
I confirm. Category pages do not open.
Error 404

**Comment by rica-carv** [comment]
If you don't use SEF's, it works....

**Comment by CaMer0n** [comment]
@fizi @214945 Do your download categories have SEF Urls assigned to them?

**Comment by 214945** [comment]
**CaMer0n:** I rebuilt SEF on downloads and earned categories.

**Comment by fizi** [comment]
My admin of downloads:
![download](https://cloud.githubusercontent.com/assets/86780/25343580/ce1140a0-290f-11e7-9c33-3bc5d5cfe2a8.jpg)
And when I click the download category I got URL: http://fizithemes.hu/download/category/11/fizi-themes-e107-v2/
but not open the category (the site only reload).

**Comment by CaMer0n** [comment]
@fizi Do you still have a 'url' folder in your downloads plugin folder?

**Comment by fizi** [comment]
Yes I have and blank.

**Comment by fizi** [comment]
Work! Thanks!

**Comment by CaMer0n** [comment]
@214945 Admin should now auto-detect this issue and resolve after running an upgrade of the "Downloads" plugin.
