### ISSUE TITLE
preferencies and multilang site

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2591]
If your prefs field is set as multilan, it's returned as array for each language. 
 I can get it this way:

```
$pref = e107::pref('theme');
$headertoptext		=  $pref['headertoptext'][e_LANGUAGE]; 
```
Is there other option?  Why so complicated? Why it doesn't return value for actual language directly?
Because I didn't know this before, I will need to change this in all my created items.

**Comment by Jimmi08** [comment]
@CaMer0n 
I need to know what is planned with this.  I could live with actual state and added multilan support to some prefs in my plugins or themes, but I need to know that this is rule for future:  Only plugins or theme developer decide what field is multilan and then customize their code.  So they will be responsible. 

Only problem is that  if somebody adds multilan setting later and you use this prefs somewhere  else, your result will be "array"  not at least English value. 

And I wasn't able to find how to get only one pref value  $onepref = e107::pref('theme',  'onepref' );  for one language.  Something like this: $onepref = e107::pref('theme',  'onepref', e_LANGUAGE); 

To be clear - using multilan setting for a field is better and improvement than using separate table.

**Comment by CaMer0n** [comment]
There is no change planned. Simply use the code that you first posted. 
$headertoptext		=  $pref['headertoptext'][e_LANGUAGE]; 
And if needed (upgrading).. check for string or array first.
