### ISSUE TITLE
Title of Download File isn't showing as HTML title.

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2592]
Not sure where this went, but it was, and now it's not

Thanks.

**Comment by Moc** [comment]
Can you give an example of a "HTML title"? Normally, HTML should not be allowed in items such as titles or descriptions.

**Comment by rica-carv** [comment]
@Moc Why?
What if i want something like this on a title or description: **Test description **(_For test purposes_)****
Or even more fnacy, like colorizing sentences?

**Comment by Moc** [comment]
Security mainly, but also compatibility. Styling should be done through themes and templates.

**Comment by rica-carv** [comment]
@Moc Ok, security i understand. But there's always bbcodes....
You can't style a part of a sentence with a theme or a template....
Or probably i'm missing something here....

**Comment by BigBoiJefe** [comment]
Sorry, apparently the subject of this issue is confusing.  What I'm talking about is when I'm looking at a Download, the HTML title normally changes to the title of the Download, however, for whatever reason it wasn't working.  After a github update, it's working again.
