### ISSUE TITLE
Issue: Plugin and Extended User Fields

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2593]
I have a plugin that requires a user to provide a ID from a game, now I wanted to add a e_user.php and allow them to put the ID in themselves, however, @CaMer0n pointed out the Extended User Fields > Add Custom Fields > Type > DB Table Field function. I set the Table, Field ID set to arma_id, Display Value is set to arma_id, and Order set to user_id - When I go to edit my profile I see the extended field but nothing is displaying:
![capture](https://cloud.githubusercontent.com/assets/5818022/25283299/e6ee7c94-2678-11e7-994b-6742dec6f133.JPG)

Going back into admin area, extended user fields > manage > edit the field and notice the values table is set to none:
![capture2](https://cloud.githubusercontent.com/assets/5818022/25283407/4e5a711c-2679-11e7-90fe-305ca6106d21.JPG)

So I set the values back up:
![capture3](https://cloud.githubusercontent.com/assets/5818022/25283416/56ccbeea-2679-11e7-889e-c637071a0ffe.JPG)

Still same issue when going to edit my profile, and this is what is stored into the database user_extended_struct
![capture4](https://cloud.githubusercontent.com/assets/5818022/25283516/ac90d41a-2679-11e7-98c7-cde0763def8b.JPG)

Noticing the forum plugin settings, I went back and edit the extended field again. However, no luck.

**Comment by CaMer0n** [comment]
Should be working now with the database fields.

**Comment by LaocheXe** [comment]
This is odd, I thought this was to allow an User Extended Field that uses a plugin database table - to allow the user to edit their own information. Ex: ArmA 3 ID - being stored in squadxml_exesystem - field id arma_id - Display arma_id  - I would think id's get a text field in the edit profile area, but get drop down menu.

Also notice a bug in the admin area to do this. First off I created the custom field - use the DB > added the table and entity (for field id) and saved, went to edit the custom field and selected for the display field - the Values area disappears - have to hit saved, and edit to get that section to display again.

**Comment by CaMer0n** [comment]
The dropdown `<select>` is the expected result for this type of extended field. Perhaps you can create a new issue (with screenshots?) for the display issue you are experiencing. Thanks.
