### ISSUE TITLE
Remove query strings from static resources

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2596]
Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources:

https://test.domain.com/e107_web/css/e107.css?1493004098
https://test.domain.com/e107_web/js/bootstrap-notify/css/bootstrap-notify.css?1493004098
https://test.domain.com/e107_web/js/bootstrap-notify/js/bootstrap-notify.js?1493004098
https://test.domain.com/e107_web/js/core/all.jquery.css?1493004098
https://test.domain.com/e107_web/js/core/all.jquery.js?1493004098
https://test.domain.com/e107_web/js/core/front.jquery.js?1493004098
https://test.domain.com/e107_web/js/rate/js/jquery.raty.js?1493004098
https://test.domain.com/plugins/featurebox/featurebox.css?1493004098
https://test.domain.com/plugins/linkwords/linkwords.css?1493004098
https://test.domain.com/themes/mytheme/css/bootstrap.min.css?1493004098
https://test.domain.com/themes/mytheme/css/font-awesome.min.css?1493004098
https://test.domain.com/themes/mytheme/css/responsive-tabs.css?1493004098
https://test.domain.com/themes/mytheme/css/style.css?1493004098
https://test.domain.com/themes/mytheme/custom.js?1493004098
https://test.domain.com/themes/mytheme/js/bootstrap.min.js?1493004098
https://test.domain.com/themes/mytheme/js/jquery.responsiveTabs.js?1493004098
https://test.domain.com/themes/mytheme/style.css?1493004098

**Comment by CaMer0n** [comment]
I'm too good to you. :-)
