### ISSUE TITLE
Download Plugin - Display Download Sub Categories Alphabetically - Frontend-ui

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2598]
Hi devs, 

I'd like to have an option in the Download plugin configuration to display subcategories alphabetically ignoring display order value

Thanks

**Comment by rica-carv** [comment]
As workaround option on the frontend, you could do [this](https://drvic10k.github.io/bootstrap-sortable/) on the downloads template....

**Comment by BigBoiJefe** [comment]
That should be the default view ;)

**Comment by CaMer0n** [comment]
I think what you want is an auto-sort function in the admin area. For most people they would just drag-n-drop the categories into the order they want.

**Comment by BigBoiJefe** [comment]
Oh, my gosh.... I didn't even know that's what the blue arrows were for!

**Comment by CaMer0n** [comment]
Okay, maybe we can consider this 'solved' :-)
