### ISSUE TITLE
Defer parsing of Javascript

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#2599]
I'm doing some optimization and I'm curious to know if there's a way to defer processing of these items until after the page load.  I know that this might not be optimal for most, but for me, I believe the benefits would be great.

```
https://cdn.jsdelivr.net/jquery/2.2.4/jquery.min.js (77.3KiB)
https://www.domain.com/e107_web/cache/a0f6a7d9.js (30.4KiB)
```

**Comment by Moc** [comment]
Maybe use asynchronous loading? There is an issue on github for this already somewhere

**Comment by BigBoiJefe** [comment]
Any idea where?

**Comment by Moc** [comment]
It depends on which sources you want to load. 

For the core jquery libraries it will be difficult because there are many dependencies. This needs to be checked and adjusted in core. 

If you are a plugin author you can use the html 'async' attribute when calling the code/js file.

**Comment by Moc** [comment]
@lonalore do you have any thoughts on this?

**Comment by CaMer0n** [comment]
Was added in commit. Closing.
