### ISSUE TITLE
Load resources from a cookie-less domain

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2600]
Hi there.  I'd like to be able to load static resources, like, css, js, and static images, from a sub domain, like static.domain.com.  Here's a list of files that I would like to load from static.domain.com

https://www.domain/e107_web/cache/84b3f96e.js
https://www.domain/e107_web/cache/a0f6a7d9.js
https://www.domain/e107_web/cache/af96e876.css
https://www.domain/themes/mytheme/images/bg-magnify.png
https://www.domain/themes/mytheme/images/bg-main.jpg
https://www.domain/themes/mytheme/images/bg-nav.png
https://www.domain/themes/mytheme/images/logo.png

**Comment by CaMer0n** [comment]
I believe this can be closed now. Please re-open if this still has issues.
