### ISSUE TITLE
Downloads Plugin - ignore decimal or round up or down

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#2601]
I'd like to request the ability to round the filesize either up or down, or ignore the decimal values

![image](https://cloud.githubusercontent.com/assets/25377269/25367202/f8be4b0e-2928-11e7-8b16-fb2b1828c1a8.png)

thanks.

**Comment by rica-carv** [comment]
Too bad that php is run before parsing the template, or you could do some [php round](http://php.net/manual/en/function.round.php) as you wish on the numbers

**Comment by Jimmi08** [comment]
@Moc Could you add label download plugin please? Thanks
