### ISSUE TITLE
json vs admin_ui

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2603]
I am trying to do similar thing as reference plugin do, but for prefs field not fields.

I use PrefsSaveTrigger() method in my admin_config.php, 
and inside something like this:

```
		if(!empty($data['x_ref']))
		{                             
				$data['ref_plugins'] =  json_encode($data['x_ref'], JSON_PRETTY_PRINT);    
				
		}
```
I checked that $data have correct value before
	$this->getConfig()->setPostedData($key, $val, false);

but they are saved in database this way:

![image](https://cloud.githubusercontent.com/assets/5429548/25427008/661dbd58-2a71-11e7-879c-d21ad77eeb95.png)

I checked that problem is not in database itself, because reference values are saved correctly.

![image](https://cloud.githubusercontent.com/assets/5429548/25427071/a64a9d6a-2a71-11e7-9253-c126daea0b9c.png)

Preferencies themself works correctly (admin ui part).   this works correctly:
`$vals = json_decode($curval,true);  `

so somehow $curval is able to get correct value from database, but I am not able to do it outside admin_ui.

I do it this way:
```
$values  = e107::pref('series','ref_plugins');   
$this->values  = json_decode($values,true);
```
What am I missing?  Thanks

**Comment by Moc** [comment]
Did you already find the answer to this?

**Comment by Jimmi08** [comment]
no

**Comment by CaMer0n** [comment]
You can't save prefs in json format, because they are saved in the 'array' format already. 
You can save DB fields in JSON format though.

**Comment by Jimmi08** [comment]
Thanks
