### ISSUE TITLE
[Problem] Auto-Generate SEF URL's

### ISSUE THREAD

**Issue by gonzalo-coda-edit** [e107inc/e107#2604]
When I installed the gallery plugin and the FAQ plugin, I had noticed that the SEF links were not generated correctly and therefore I set them manually. But now I see that causes some problem, for example, the "Back" button in gallery does not recognize the link well and goes to the root of the site.

In these links, when I edit and put them in SEF URL: index (auto generated) generates (i.e gallery) the link: e107_pluginsgallerygallery.php , just the opposite of SEF

The weird thing is that in localhost it works fine, what could be the error?

edit: The last time I updated the files was 3 days ago

**Comment by AdocArg** [comment]
I would like to add that by chance once, I take a picture to the gitter chat (I knew it would serve me in the future) and I think they talked about something similar (having activated SSL):

![doubt](https://cloud.githubusercontent.com/assets/20747469/25512680/e888256e-2ba5-11e7-9104-6e9ff0d31e7f.jpg)

**Comment by Moc** [comment]
Please make sure you test this on the latest files from github, with all the caches cleared. 

I've already milestoned this as this is an important issue but please verify that the issue happens on the latest github files.

**Comment by AdocArg** [comment]
Ready, i had updated all the files, cleared cache, and the problem persist.

**Comment by AdocArg** [comment]
I would like to add something, checking the configuration --> URL configuration, I noticed that I had selected Gallery in "Associate Root namespace", that was the reason why the "Back" button in the gallery returned to the root of the site, sorry, I didn't remember that I had changed that.

Another thing, I just downloaded the latest version of github but the sef url is still generating badly, it continues to generate the one that is not sef. Is not a big problem, simply generate the sef url manually

Thanks

**Comment by CaMer0n** [comment]
@AdocArg Is this still a problem at all?

**Comment by AdocArg** [comment]
Sorry for late answer, I had and have heavy days. I don't remember if i need to activate something, because appears me: 

![sefurl](https://user-images.githubusercontent.com/20747469/33787994-8d5bcbaa-dc4e-11e7-93c1-928ded241371.jpg)

(I have all the files updated)

**Comment by Moc** [comment]
Sorry for the late reply. 

> The weird thing is that in localhost it works fine, what could be the error?

Could you give us some more information on your live environment in which the problems occur? PHP version for example. Also, is mod_rewrite enabled? (Can be checked in the admin area > php info)

**Comment by AdocArg** [comment]
No problem. I will leave localhost and live information:

**Live environment:**

PHP Version: 7.0.33 (also i tried with 5.6)
System: Linux (i don't know which version)
Server API: LiteSpeed V7.1
Virtual Directory Support: Disabled
Thread Safety: Disabled

Given the Server API is not Apache, phpinfo() doesn't give me the Apache information directly. I followed this way [https://stackoverflow.com/questions/18310183/how-to-check-for-mod-rewrite-on-php-cgi](url) to check if mod_rewrite is enabled and yes, is enabled

In Core: 

disable_functions: exec, passthru, pcntl_exec, popen, proc_close, link, proc_get_status, proc_nice, proc_open, proc_terminate, shell_exec, system, symlink, socket_create


**Localhost:**

PHP Version: 7.0.13
System: Windows 10
Server API: Apache 2.0 Handler
Virtual Directory Support: Enabled
Thread Safety: Enabled
mod_rewrite: Enabled.

In Core:

disable_functions: no value

-------------------------------------------------

I left the most significant differences that I saw. Thanks

**Comment by Moc** [comment]
I suspect it is the `Virtual Directory Support` that does not allow for mod_rewrite (or rather the .htaccess file) to function properly. Is it possible for you to enable it?

**Comment by CaMer0n** [comment]
@Moc @AdocArg Normally re-installing the plugins should correct the problem. Or enable debug and click the "Repair" button in the Plugin Manager next to each of these plugins.

**Comment by AdocArg** [comment]
Is not possible for me enable the Virtual Directory Support.

I did what Cameron said but the problem persist. Yeap, this is old and not relevant because in my localhost works very well and it's not a lot of work to do it manually. It must be some configuration on my live environment so.. Can the problem be considered solved? 

Thanks!

PD: I also see that nobody else had this problem
