### ISSUE TITLE
Forum links not work

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2610]
The forum links after latest GitHub upgrade not work. I click in the parent name and nothing happening. Only site reload, not open the threads.

**Comment by CaMer0n** [comment]
@rica-carv Are you able to reproduce this? Me, not.

**Comment by Alex-e107nl** [comment]
Here's to, when i set forum on the page https://e107.nl/e107_admin/eurl.php?mode=main&action=simple on off it works like it should.. Maybe that helps...

**Comment by fizi** [comment]
I don't understand. If I set "off" the forum on the URL PROFIL...forum work. If I set "on"...not work. What make the URL PROFIL "ON-OFF"?

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/2604 Perhaps related?

**Comment by CaMer0n** [comment]
I have tried to reproduce this problem but have been unsuccessful.

**Comment by rica-carv** [comment]
This can be related to SEF's
I've completely disabled SEF's in htaccess, but they still are present on forum frontend url's.
Since they're disabled in htacces, the site simply can't find that URL and automatically redirects to frontpage
I also got sometimes a 404 error....

Just my 2 cents: why not check if SEF's are enabled or not and automatically use the corresponding correct url in links? Further more, why not make SEF urls rebuilds automatic?

**Comment by CaMer0n** [comment]
@Alex-e107nl @fizi Please go to /e107_admin/db.php?mode=pref_editor and tell me the value of **url_config**

**Comment by rica-carv** [comment]
@CaMer0n If it matters, here's mine:
`Array
(
    [index] => core
    [news] => core
    [page] => core
    [search] => core
    [system] => core
    [user] => core
    [forum] => plugin
    [gallery] => plugin
)`

**Comment by fizi** [comment]
my: Array
(
    [index] => core
    [news] => core/sef_noid
    [page] => core/sef_noid
    [search] => core/rewrite
    [system] => core
    [user] => core/rewrite
    [forum] => plugin
    [gallery] => plugin/rewrite
)

**Comment by chory** [comment]
my
Array
(
    [index] => core
    [news] => core
    [page] => core
    [search] => core
    [system] => core
    [user] => core
    [forum] => plugin
    [gallery] => plugin
    [pm] => plugin
)

**Comment by CaMer0n** [comment]
@fizi @Alex-e107nl @chory please update from github. An upgrade request should appear for 'forum'. Please run it and then post your **url_config** value here again. Thank you.

**Comment by chory** [comment]
It's ok.
For me, it works correctly.
Thank you very much
Array
(
    [index] => core
    [news] => core
    [page] => core
    [search] => core
    [system] => core
    [user] => core
    [gallery] => plugin
    [pm] => plugin
)

**Comment by fizi** [comment]
Forum work.
`Array
(
    [index] => core
    [news] => core/sef_noid
    [page] => core/sef_noid
    [search] => core/rewrite
    [system] => core
    [user] => core/rewrite
    [gallery] => plugin/rewrite
)`

**Comment by Alex-e107nl** [comment]
Also here it works perfectly again THX! (github of 5 minutes ago)

**Comment by CaMer0n** [comment]
Great. Thank you! @Alex-e107nl  @chory @fizi
