### ISSUE TITLE
News item date stamp

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#2611]
Running latest commit. The date stamp set for a news item does not apply itself to the news item when it is set to be published at a future date from _News>>Manage>>#xxxx>>Advanced Options._ The current date of saving the news item is set. However, the news item is published when expected to be.

**Comment by CaMer0n** [comment]
@NZCyrus Thank you. So do I understand well that you set the 'date stamp  and 'start' dates to a future date/time but the 'date stamp' saved the current date/time instead?

**Comment by NZCyrus** [comment]
That's correct

**Comment by CaMer0n** [comment]
@NZCyrus This appears to be a 'feature'. ie. it automatically sets the datestamp (on the frontend) to the 'start date' even if the 'date stamp' is set to a different date/time entirely.

**Comment by NZCyrus** [comment]
Ah OK. I was under the impression that, if I saved a news item on the 1st to be published on the 5th, it would be published on the 5th and the date stamp would show the 5th as well.

**Comment by Moc** [comment]
That would appear logical to me as well :)

**Comment by CaMer0n** [comment]
@NZCyrus Sorry, maybe I didn't explain well. It will display the 'start' datestamp regardless of the original datestamp. So if you set it for the 5th, it will display the 5th (on the frontend) and the original datestamp (defaulting to time of record creation) in the admin area.

**Comment by Jimmi08** [comment]
@CaMer0n is right. It should be that way. Datestamp  -  date when you create record (for admin purpose)
Start date - first day of publish and publish date on frontend.

**Comment by NZCyrus** [comment]
Thanks @CaMer0n and @Jimmi08, yes that makes sense. 

Subsequently I have posted a couple of news articles to be published at a forward date and I think that they do get published when expected however, the date stamp is one day behind. For example, I set the publish date as 10 June. When the news is published the date stamp is 9 June.

I have noticed this a couple of times and will have to determine this again to clarify that this is really the case. Anyone else getting a published date of one day behind?

**Comment by rica-carv** [comment]
So, if a news item has a end date on it, it won't be displayed after that date, correct?
The only way to display that new item after the end date is not to set any end date at all, right?
Couldn't it be a admin option to keep displaying the new item even after the end date?

**Comment by Jimmi08** [comment]
@rica-carv point of use End day is not to have something displayed after this date. Just let it empty.

**Comment by NZCyrus** [comment]
> I have noticed this a couple of times and will have to determine this again to clarify that this is really the case. Anyone else getting a published date of one day behind?

My error. I had to set the 'Timezone' in 'Site Preferences' to my current location, Auckland. It was initially set as a timezone of my dedicated server in the US.

**Comment by CaMer0n** [comment]
No worries @NZCyrus Thanks for letting us know. 👍
