### ISSUE TITLE
you can set menus in theme.xml only for one layout

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2613]
This works:

```
		<layout name='sidebar_right' title='Blog sidebar-right' default='true' >
			<custompages>/news</custompages>
			<menuPresets>
				<area id='1'>
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
			</menuPresets>		
		</layout>
```

![image](https://cloud.githubusercontent.com/assets/5429548/25653819/d88c1024-2fee-11e7-9dec-3a64f370b643.png)

But if I do the same for next layout:

```
		<layout name='sidebar_right' title='Blog sidebar-right' default='true' >
			<custompages>/news</custompages>
			<menuPresets>
				<area id='1'>
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
			</menuPresets>		
		</layout>
		<layout name='sidebar_left' title='Blog sidebar-left' default='false' >
			<custompages>/page</custompages>
			<menuPresets>
				<area id='1'>
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
			</menuPresets>		
		</layout>
```

result is:
![image](https://cloud.githubusercontent.com/assets/5429548/25653954/77f85dd4-2fef-11e7-9d65-1c61230086ea.png)

Does it works only for default layout?

**Comment by Jimmi08** [comment]
I don't know if this is related, but after adding menus via menu manager and switch default themes, I've got this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to e_pref::loadData() must be of the type array, string given, called in C:\xampp\htdocs\e107\e107_handlers\pref_class.php on line 475 and defined in C:\xampp\htdocs\e107\e107_handlers\pref_class.php:417 Stack trace: #0 C:\xampp\htdocs\e107\e107_handlers\pref_class.php(475): e_pref->loadData('', false) #1 C:\xampp\htdocs\e107\e107_handlers\pref_class.php(450): e_pref->_load(false) #2 C:\xampp\htdocs\e107\e107_handlers\pref_class.php(1041): e_pref->load() #3 C:\xampp\htdocs\e107\e107_handlers\e107_class.php(1109): e_theme_pref->__construct('starter', '', true) #4 C:\xampp\htdocs\e107\e107_handlers\theme_handler.php(1835): e107::getThemeConfig('starter') #5 C:\xampp\htdocs\e107\e107_handlers\theme_handler.php(2423): themeHandler->renderThemeConfig() #6 C:\xampp\htdocs\e107\e107_admin\theme.php(600): themeHandler->renderTheme(1, Array) #7 C:\xampp\htdocs\e107\e107_admin\theme.php(334): theme_admin_ui->renderThemeConfig('front') #8 C:\xampp\htdocs\e107\e107_handlers\admin_ui. in C:\xampp\htdocs\e107\e107_handlers\pref_class.php on line 417`

Switching themes didn't help. I will see if I find the reason.

**Comment by aducom** [comment]
Not sure if this is the same issue I have. I migrated a site from php 5.4 to php 7.0. It works well under 5.4 but I get above error under php 7.

**Comment by CaMer0n** [comment]
@aducom @Jimmi08 please update from Github. Does the recent commit fix the issue?

**Comment by aducom** [comment]
I don't know exactly what I did, but I got it running. I think it has to do with some entry in the pref table which was reset while selecting another theme and reverted back to the original. I tested the git on another site, but under php 7 the site is empty. Currently investigating the issue.

**Comment by aducom** [comment]
Ok, I redid the git and I can confirm that my issue is gone. Also it solved an old issue where upgrading from php 5.6 to 7.0 resulted to a blank landing page. For me this is a great fix. Thanks.

**Comment by CaMer0n** [comment]
Thank you @aducom . I'll leave this issue open as there is still the actual menuPreset issue.

**Comment by Jimmi08** [comment]
Confirm, original issue is solved. 
Only problem is that if your setting is this way (example)

```
      <menuPresets>
				<area id='1'>
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
				<area id='2'>
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
			</menuPresets>	
		</layout>
```
Only area2 is correct, area1 has no menus. It's because I used the same menus on both areas.

When you change theme.xml, you need to reinstall theme to see changes in menus.

**Comment by CaMer0n** [comment]
@Moc It appears so. Haven't tested it recently.

**Comment by Jimmi08** [comment]
Just tested. For one layout only latest set is used.  (area 31 was ignored)
```
        <layout name='default' title='Default layout' default='true' >
             <menuPresets>
				<area id='31'>
                    <menu name='online' />
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
                <area id='51'>
                    <menu name='online' />
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
					<menu name='blogcalendar' />
				</area>
			</menuPresets>
        </layout>  
```

**Comment by Jimmi08** [comment]
This is solved. Tested with theme.php layouts.

```
        <layout name='default' title='Default layout' default='true' >
             <menuPresets>
				<area id='1'>
                    <menu name='login' />
					<menu name='search' />
					<menu name='news_categories' />
					<menu name='other_news' />
					<menu name='other_news2' />
				</area>   
                <area id='2'>
                    <menu name='online' />
					<menu name='blogcalendar' />
				</area>    
			</menuPresets>
        </layout>  
``` 

Thanks
