### ISSUE TITLE
Enhancement menus vs menu_layouts

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2614]
It was said that menus are related to layouts.  But there is exception and I think that it shouldn't work this way.

If your layout is set as default, menu_layout value in menu table is not filled. F.e for sidebar_right layout

![image](https://cloud.githubusercontent.com/assets/5429548/25656930/a5048daa-2ffb-11e7-95c9-9ead4cbf103b.png)

But when you change your default layout in theme manager, you will have displayed in fact menus belonged to last default layout and not menus added before to actual default layout. And you need to set menus again. You switch back and you have the same problem.

Yes, I can renumbered menu areas for layouts, but then we are back to question why menuareas depends on layouts.

**Comment by Moc** [comment]
@CaMer0n Your thoughts on this one please? :)

**Comment by Jimmi08** [comment]
Closing without any feedback for more than a year. Probably stupid idea. I myself don't need this anymore.
