### ISSUE TITLE
PM menu button

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2615]
Appears only link instead of button on PM menu (Latest GiHub update).
![pm_button](https://cloud.githubusercontent.com/assets/86780/25667124/d9b4b0e4-3022-11e7-9feb-208163665344.jpg)

**Comment by rica-carv** [comment]
@fizi Do you have custom template for pm_menu on that theme? Custom pm_menu_template.php file?
Plugin default template doesn't render like that, only if you have old custom pm_menu_template.php file on your theme...
Customized pm_menu_template.php file on my theme, corrected to match plugin default:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/25676901/c714f548-303b-11e7-9f9a-4071ddf7b56b.jpg)

**Comment by fizi** [comment]
I don't have, I use default ...no template for this.

**Comment by CaMer0n** [comment]
Closing as it wasn't a fresh install but deprecated files in use.

**Comment by rica-carv** [comment]
When updating manually (ie: simple copy over old files) you'll have to do a cleanup of old deprecated files, if there's any.
Best thing to do is a mirror sync (with any good free program) instead of simple copy over...

**Comment by fizi** [comment]
Thanks help!
