### ISSUE TITLE
New admin ui boolean switches class bug

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2617]
New admin ui boolean switches are not keeping original input class...
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/25682695/fdf5562e-3050-11e7-9d9e-5dd7758f7590.jpg)

**Comment by CaMer0n** [comment]
Correct. What are you trying to do?

**Comment by rica-carv** [comment]
I'm trying to anchieve this:
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/25772779/121b0e08-326a-11e7-86b9-7b9db29565d3.jpg)

Currently, with this code:
```
protected $prefs = array( 
  				'redirect_usersettings'  => array('title'=> LAN_EUSER_ADMIN_501, 'type'=>'boolean', 'writeParms'=>array('class'=>'pull-left')),
 	);
```
& this:
`	$this->prefs['redirect_usersettings']['writeParms']['post'] = "&nbsp;<span class='label label-important label-info'>".LAN_EUSER_ADMIN_501I."</span>";`

it renders like this:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/25772789/3a0b5c74-326a-11e7-8179-f00ab3b52682.jpg)

Of cousre i could wrap all this inside a div, and add aditional style to put all them side by side, but it's ankward and not very HTML sintax friendly...

**Comment by CaMer0n** [comment]
Try changing the class of the `<td>` they are both in. 'form-inline' or 'input-inline' .  (see docs for details)

**Comment by rica-carv** [comment]
Form-inline works. Thanks
