### ISSUE TITLE
istallation

### ISSUE THREAD

**Issue by zaydharith** [e107inc/e107#2618]
**Helo every body
i tried an installation of e107 -2.1.5-full on my local server, 
Wampserver 3.0.6-32bits, apache2.4.23, php5.6.25 and MYSQL5.7.14
all step was succefull  until the end, but a the last step which is to access to the home page, i get this warning;**
====
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at wampserver@wampserver.invalid to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Apache/2.4.23 (Win32) PHP/5.6.25 Server at e107 Port 80 
```=====
I need your help please.

**Comment by tgtje** [comment]
Probably related to the htaccess file. To be sure in your case > read the server error log It should provide clues or indicate where it goes wrong. There are normally no issues using wamp.

**Comment by zaydharith** [comment]
hi, i found the problem now Thank you **tgtje**
in my log i have this error:
`[Thu May 04 04:13:35.375746 2017] [core:alert] [pid 8860:tid 1104] [client ::1:65516] C:/wamp/www/e107/.htaccess: Invalid command 'AddOutputFilterByType', perhaps misspelled or defined by a module not included in the server configuration`
so I have enable the Appache **filter module** and everything are ok now.

But I wonder if  it is correct to proccess so? or can you have the best way to solve this ?

**Comment by tgtje** [comment]
It is a correct way to do so. (it offers kind of work around between versions in apache ( in some it is a deprecated function (2.2), and has been brought back in newer versions(2.4)

**Comment by tgtje** [comment]
I think this issue can be closed (do believe it is strictly a localserver issue); normally on live servers this will not happen..
