### ISSUE TITLE
Download Plugin - Download Button for each class and membership upgrade path

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2621]
Ohhh @CaMer0n ;) lol.  

We have 3 different user classes that can download - Guest, Member, Premium.  All downloads are visible to everyone, however, if a guest, or member (if the member tries and download a premium member file) tries to download a file, no matter what download class is defined, it just takes them to the message that's defined in the Download Preferences > Custom Download-denial message or URL, in my case I've set that to "Sorry about that.  You don't have permission to download this file.  Why not create an account?  It's FREE"

The problem with that is it doesn't tell the user which member type they have to be to download, and while most files can be downloaded by members, some can only be downloaded by premium(which is a paid for membership type).

My goal is to be able to have an upsell button for each userclass:
If you're a guest downloading show: <downloadbutton-guest> Want to download faster? Sign up, it's free.  But, that message can't be shown if the file is downloadable by only Premium members.

If you're a member downloading show: <downloadbutton_member> Want to download faster?  Upgrade to a premium membership, it's just $30 a year.

I'm really not sure the best way to handle this, but maybe just have a text field in the file page, that says what user class can download each file?  Thoughts?

**Comment by rica-carv** [comment]
Hummm, just thinking out of the box, and just theory.
Can this be anchieved via a custom "module" on the plugins folder, to "catch" the redirected page, check user type, and display a message accordingly.
All this without "messing" the downloads plugin?

Or is changing the downloads plugin a option?

**Comment by tgtje** [comment]
Also thinking out of the box here, idea is good (usage might be to fewer users though) but why not something ala rating system (on front) where download itself has a ala rating/option which indicates class on forehand... ? ( ideas enough helas not skill to code it helas..)

**Comment by Jimmi08** [comment]
Something similar has http://www.aacgc.com/e107/ on his site. If I haven't gold membership I've got message about to upgrade ...  If it was possible in version 1, maybe it's possible in version 2.

**Comment by Moc** [comment]
I agree that this is too much customisation for a core plugin. Ideally a hook such as rica suggested should be used.

**Comment by Moc** [comment]
I am going to close this one as I think it is outside core territory. If a plugin author wants to add some event hooks in the download plugin for example, please feel free to let us know or even better feel free to submit pull-requests with additions to core.
