### ISSUE TITLE
Checkboxes in admin ui not working....

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2631]
Got a bunch of checkboxes in admin ui, but they aren't saved on submit.
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/25968463/7985d578-3689-11e7-8df4-f456165ee4f4.jpg)

The code i'm using to generate it is a copy from log, and is like this:
```
		$frm = e107::getForm();
		
		$groupCheckboxes = array("memberlist_column_avatar" => LAN_EUSER_ADMIN_624, "memberlist_column_online" => LAN_EUSER_ADMIN_625,"memberlist_column_realname" => LAN_EUSER_ADMIN_626,"memberlist_column_loginname" => LAN_EUSER_ADMIN_627,"memberlist_column_email" => LAN_EUSER_ADMIN_628,"memberlist_column_join" => LAN_EUSER_ADMIN_629,"memberlist_column_lastvisit" => LAN_EUSER_ADMIN_630,"memberlist_column_visits" => LAN_EUSER_ADMIN_631,"memberlist_column_timezone" => LAN_EUSER_ADMIN_632,"memberlist_column_userip" => LAN_EUSER_ADMIN_633);
	
		$groupOpts = e107::pref('euser');
		foreach($groupCheckboxes as $k => $t)
		{
			$checked = isset($groupOpts[$k]);
			$text .= $frm->checkbox('check_opts['.$k.']',$k, $checked, array('label'=>$t));	
		}
```

Any admin ui gurus could help? What am i missing here?

**Comment by Moc** [comment]
@rica-carv Is this issue still relevant?

**Comment by rica-carv** [comment]
Yes...

**Comment by CaMer0n** [comment]
@rica-carv Is this a pref or a database field? I'm assuming you're using a type='method' ?

**Comment by rica-carv** [comment]
@CaMer0n It's a pref:
```
$groupOpts = e107::pref('euser');
		foreach($groupCheckboxes as $k => $t)
		{
			$checked = isset($groupOpts[$k]);
			$text .= $frm->checkbox('check_opts['.$k.']',$k, $checked, array('label'=>$t));	
		}
```

**Comment by CaMer0n** [comment]
@rica-carv Thanks. is check_opts the name of the pref? Also, does $pluginName match your plugin folder?

**Comment by rica-carv** [comment]
@CaMer0n Yes, check_opts#### is the name of the prefs... And$pluginName match the plugin folder, yes...

**Comment by CaMer0n** [comment]
@rica-carv Could you paste the $prefs value here? Silly question, but the plugin is actually installed, correct?

**Comment by rica-carv** [comment]
@CaMer0n Well, i might have some mixed up things here, but anyway here it goes.
I'm defining the $prefs array as this:
`....  				'_checkboxgroup0'  => array('title'=> LAN_EUSER_ADMIN_623, 'tab' => 0, 'type'=>'method','help' => LAN_EUSER_ADMIN_623H),....`

and the checkboxgroup0 function is this one:
	```
function _checkboxgroup0($curVal,$mode)
	{
		$frm = e107::getForm();
		
		$groupCheckboxes = array("memberlist_column_avatar" => LAN_EUSER_ADMIN_624, "memberlist_column_online" => LAN_EUSER_ADMIN_625,"memberlist_column_realname" => LAN_EUSER_ADMIN_626,"memberlist_column_loginname" => LAN_EUSER_ADMIN_603,"memberlist_column_email" => LAN_EUSER_ADMIN_604,"memberlist_column_join" => LAN_EUSER_ADMIN_605,"memberlist_column_lastvisit" => LAN_EUSER_ADMIN_606,"memberlist_column_visits" => LAN_EUSER_ADMIN_607,"memberlist_column_timezone" => LAN_EUSER_ADMIN_632,"memberlist_column_userip" => LAN_EUSER_ADMIN_633);
	
		$groupOpts = e107::getPlugPref('euser');
		foreach($groupCheckboxes as $k => $t)
		{
			$checked = isset($groupOpts[$k]);
			$text .= $frm->checkbox('check_opts['.$k.']',$k, $checked, array('label'=>$t));	
		}

		$text .= $frm->admin_button('check_all', 'jstarget:check_opts', 'checkall', LAN_CHECKALL)."&nbsp;&nbsp;".$frm->admin_button('uncheck_all', 'jstarget:check_opts', 'checkall', LAN_UNCHECKALL);
	
		return $text;
  }
```
It renders the admin_ui correctly, but it simply won't handle the fields settings.
And i might think why....
It has to do something with this line: `$frm->checkbox('check_opts['.$k.']',$k, $checked, array('label'=>$t));	`, because check_opts is a javascript to check/uncheck all fileds, and the checkbox name is different from the standard on to save its value...
What really annoys me is that this exact code works on the log core plugin, but in mine it doesn't.....
Grrrrrrrrrrrrrrrrrrrrrrr....

**Comment by CaMer0n** [comment]
Correct. If your field is called `_checkboxgroup0` then e107 will attempt to save `$_POST['_checkboxgroup0']`, but that's no what you're posting. You're posting `check_opts`, so unless you have a field called `check_opts`, nothing will be saved.

**Comment by rica-carv** [comment]
@CaMer0n Thank you, but maybe i'll end up using this, but with several options, of course...: https://www.jquery-az.com/boots/demo.php?ex=34.0_1
I think it's more user friendly in all platforms, what do you think?

**Comment by rica-carv** [comment]
This is really getting me off....
I've switched to radio_switch, the pref is correctly on the database plugin prefs, the $_POST outputs a different value from the on in the database, and plain and simply it's not updated!!!!!!!!!!

What the heck i've got so special that this plain and simple isn't updated?
If i put the radio_witch on a regular table line fields, it's updated!!!!!!!

How i miss the old V1.x admin_ui...... :(

**Comment by CaMer0n** [comment]
v1.x had no admin ui at all. If you want to manually save, place your code inside init() with a check for $_POST.

**Comment by rica-carv** [comment]
Yes, v1.x had no core admin ui, but it was way more flexible, we could do almos anything in admin ui....
Now we need to go deep in the code to accomplish simple things, like the checkboxes groups above....

Anyway, no need to cry because spilled milk, i got to get over it....

On my way to the drawing board....

**Comment by rica-carv** [comment]
> If you want to manually save, place your code inside init() with a check for $_POST.

I was hoping not to have to reinvent the wheel...
Make a custom save prefs, when they already are defined in the plugin xml and on the database, is anklward, since that is already hadled in the core, no?
Why doesn't the core save the pref when it's present in the POST?
Currently it's what's happening....
The POST has the value and name correct, as it its in the database and plugin xml, but it simply ignores it when the form is submitted....

**Comment by CaMer0n** [comment]
Did you try using this code?

    $text .= $frm->checkbox('_checkboxgroup0['.$k.']

**Comment by rica-carv** [comment]
@CaMer0n I'm using this one: `$text .= $frm->checkbox('check_opts['.$k.']',$k, $checked, array('label'=>$t));`
I need it's id to be check_opts because of the core js, to check and uncheck all checkboxes from the same group...
Isn't almost the same thing?

**Comment by rica-carv** [comment]
I hope someone could make me understand this, because i'm really getting lost in this...

This issue happens also on checkboxes, but currently i'm testing it on switches, so the issue applies to both (checkboxes & switches)...

The $_POST var has this on form submit:
` ["e-token"]=> string(32) "6e8bac9ed8ba6dd255488b204efaaeab" ["friends"]=> string(1) "1" ["friends__switch"]=> string(1) "0" ["frcol"]=> string(1) "4" ["fr_req_sendpm"]=> string(1) "0" ["fr_req_sendpm_all"]=> string(1) "1" ["fr-req-sendpm-all__switch"]=> string(1) "0" ["fr_req_sendemail"]=> string(1) "0" ["fr_req_sendemail_all"]=> string(1) "1" ["fr-req-sendemail-all__switch"]=> string(1) "0" ["etrigger_save"]=> string(6) "update" `

All the fields are on the database, and registered upon plugin install, so the odd this is:
- _friends_ is updated to 1 (note there's present the friends_switch field - why, it beats me...)
- _fr_req_sendpm_all_ is **not** updated to 1 (and note the respective switch field is present there..)
- _fr_req_sendemail_all_ is also **not** updated to 1 (and note the respective switch field is present there..)

All the fields are inside the form are in the admin_ui, so why aren't them accepted to be saved to the plugin prefs?
Can anyone help me scavenge the "bug" on the code?

Further more, to add more confusion, second test, same form:
` ["e-token"]=> string(32) "6e8bac9ed8ba6dd255488b204efaaeab" ["friends"]=> string(1) "1" ["friends__switch"]=> string(1) "0" ["frcol"]=> string(1) "4" ["fr_req_sendpm"]=> string(1) "1" ["fr-req-sendpm__switch"]=> string(1) "0" ["fr_req_sendpm_all"]=> string(1) "1" ["fr-req-sendpm-all__switch"]=> string(1) "0" ["fr_req_sendemail"]=> string(1) "1" ["fr-req-sendemail__switch"]=> string(1) "0" ["fr_req_sendemail_all"]=> string(1) "1" ["fr-req-sendemail-all__switch"]=> string(1) "0" ["etrigger_save"]=> string(6) "update" `

- _friends_ is updated to 1 (note there's present the friends_switch field - why, it beats me...)
- _fr_req_sendpm_ is updated to 1 (still present the switch field)
- _fr_req_sendpm_all_ is **not** updated to 1 (and note the respective switch field is present there..)
- _fr_req_sendemail_ is updated to 1 (still present the switch field)
- _fr_req_sendemail_all_ is also **not** updated to 1 (and note the respective switch field is present there..)

An image of the _troubled_ admin_ui form:
![euser_-_extensao_de_utilizadores_-_friends_system_-_area_do_administrador_selos_portugal_-_2018-03-26_19 47 00](https://user-images.githubusercontent.com/17130530/37926305-e96d8980-312e-11e8-8795-04ce291a3f7c.png)

Why is this "discrimination"???

**Comment by Moc** [comment]
@rica-carv Please share your full admin_config.php code through Github (either a private gist or a public github repository) if you'd still like someone to help with this.

**Comment by CaMer0n** [comment]
Closing. Please re-open if necessary.
