### ISSUE TITLE
PM plugin, show nothing

### ISSUE THREAD

**Issue by chory** [e107inc/e107#2635]
I installed the PM plugin, and when I click on the button send new message, to create a new one, nothing is shown sealed with the plugin, on the screen.
I am not using any template, only those that incorporates the own plugin.

**Comment by rica-carv** [comment]
Mine's working fine, using latest github version. Which version of e107 are you using?

**Comment by chory** [comment]
Latest github Versión 2.1.6 (git)

**Comment by fizi** [comment]
Earlier I installed the v2. The latest GitHub pm menu not has any folders (attachments, url), pm_template.php, private_msg_menu.php, test.css, test.js and textboxlist.js....but the earlier version has it.
I think need delete these. See this how it is. This is just an idea.

**Comment by chory** [comment]
@fizi I do it, but no work

**Comment by rica-carv** [comment]
Pm plugin is intact (https://github.com/e107inc/e107/tree/master/e107_plugins/pm), so as i see it, or it's a cache cleaning issue (try clean your caches - browser & e107) or a confliciting third party plugin,,,,

**Comment by chory** [comment]
caches are clear, no third party plugins.
In local works fine, ploblem is with remote server

**Comment by arunshekher** [comment]
@chory Are you having issues just with the PM 'send new message' page ie.`pm?mode=send` or the Inbox and Outbox as well? Is it a blank page that you are get? Is your remote server a VPS that you configured? Mind sharing the environmental details? 

I too have similar problem on a particular setup (remote) but almost similar environmental parameters locally worked fine with PM plugin when tested except for one test setup (vagrant virtual box) and I got the below posted errors. Didn't get a chance to investigate more.

In my case got blank pages on PM Inbox ( `pm?mode=inbox`) and Outbox (`pm?mode=outbox`) but send page is accessible. But just after sending a PM send page also goes blank. PM reaches recipient. Problem persist in v2.1.6 git too.

Parameters used:
![image](https://cloud.githubusercontent.com/assets/315195/26099558/232d73c8-3a3c-11e7-85ac-0a556360d064.png)

Have  cli, intl, xml, mbstring, gd php extensions installed

Inbox:
![image](https://cloud.githubusercontent.com/assets/315195/26098281/4016919e-3a38-11e7-9518-aa9d4a9f0359.png)

Outbox:
![image](https://cloud.githubusercontent.com/assets/315195/26098510/030fafe6-3a39-11e7-8fec-531deeab88b2.png)

**Comment by rica-carv** [comment]
@all Please be aware, not every live servers out there are fully setup & prepared to host e107, so always check servers status and loaded modules against e107 minimun requirements...

**Comment by arunshekher** [comment]
@rica-carv this is the strength and bitterness of open source collaborative dev. model

**Comment by chory** [comment]
inbox, outbox & send, same page
![errore107](https://cloud.githubusercontent.com/assets/4314070/26120509/4eddf404-3a71-11e7-9954-2d0076001c7f.jpg)
**gd** _enabled_
**mbstring** _enabled_
**intl** _enabled_
**xml** _enabled_
DirectiveLocal          Value 	Master Value
**opcache**.enable_cli    _Off_    	_Off_

**Comment by rica-carv** [comment]
@chory That theme is v2 or v1? Does it has a custom pm_template file in it?

**Comment by chory** [comment]
@rica-carv theme is v2, based in other theme by mcpace, and it has no pm_template

**Comment by rica-carv** [comment]
@chory There's something weird there, really weird. Can you show the HTML after that breadcrumb?

**Comment by chory** [comment]
@rica-carv  I don't undestand You. breadcrumb?
The HTML from page is
[html.txt](https://github.com/e107inc/e107/files/1005603/html.txt)

**Comment by rica-carv** [comment]
@chory There's something breaking that theme, there's div's at the end of the HTML left open and empty. Might be a theme fault, so i can really tell anything more without real live testing that theme, so...

**Comment by chory** [comment]
@rica-carv I think it, but I don't understand, if in local server works correctly, in remote server, if the theme contains the same files, it should work correctly.
And if e107 is equal, in servers, it should work correctly, too. Or not?
I'm going crazy with this nonsense 😩

**Comment by rica-carv** [comment]
@chory If it works on local, and not on live, the only logic approach is there's something with the servers.
I've had some issues with some servers, with the same PHP versions, same modules activated, and all equal, and it simply had errors.
So, for me, no surprise if the issue is the server itself.
Your local server is what?
And the live one, is what?

**Comment by CaMer0n** [comment]
@arunshekher Did the last commit fix your issue?

**Comment by 214945** [comment]
You need to install a version of PHP 7 or lower, then the PM plug-in will work

**Comment by arunshekher** [comment]
Yes commit  65ca5af fixes the issue with my setup. 

**Inbox:**
![image](https://cloud.githubusercontent.com/assets/315195/26152611/a838d45e-3b18-11e7-8ebe-f55024eda463.png)

**Outbox:**
![image](https://cloud.githubusercontent.com/assets/315195/26152646/cff74d90-3b18-11e7-9723-b5d93671feb1.png)

**Compose:** 
![image](https://cloud.githubusercontent.com/assets/315195/26152683/01bfd3c4-3b19-11e7-803a-3349d85f40d2.png)

**Setup:**
![image](https://cloud.githubusercontent.com/assets/315195/26152720/310d8e46-3b19-11e7-8b89-73265d53be54.png)

**Comment by arunshekher** [comment]
@chory if you're still having blank screen after upgrading your installation to the current github repo state (after the commit: 65ca5af) try if changing the PM plugin preference **Number of PMs to show per page**  from 0 to, say 10 or 20 fix the issue.

![image](https://cloud.githubusercontent.com/assets/315195/26155813/7fdcac9e-3b25-11e7-8041-52e52618f3ca.png)

**Comment by CaMer0n** [comment]
Thank you @arunshekher .

**Comment by chory** [comment]
@CaMer0n last commit, works fine.
I'm happy again 😀 
Thanks for all

**Comment by CaMer0n** [comment]
@chory could you please share more details? Are you trying to send a PM from the frontend or admin area?

**Comment by chory** [comment]
I'm tryin send from the frontend
![errore107-2](https://cloud.githubusercontent.com/assets/4314070/26425176/32e5ca7e-40d4-11e7-956a-17cb071b2651.jpg)

**Comment by CaMer0n** [comment]
@chory Please check the files here : https://github.com/e107inc/e107/tree/master/e107_plugins/pm
.. and make sure there are no other files in your PM folder.

**Comment by CaMer0n** [comment]
@chory Please update your files from github.. it should fix the template load issue.

**Comment by chory** [comment]
@CaMer0n nothing, I delete plugins/pm folder, I clear all caches, update from github, and this don't works for me.
Remains the same as before

**Comment by rica-carv** [comment]
@chory Just my two cents, and thinking out of the box.
If you have said already that on local it works fine, and it's not working on remote server, then, as i see it, it's a server issue, and not with e107 code itself....

**Comment by chory** [comment]
@rica-carv Totally agree with you, but we will have to know what are the very strict requirements that are needed so that it does not work remotely.
If when I installed it has passed all the tests, it would have to work correctly.
Or the tests, are they just appearance?

**Comment by rica-carv** [comment]
@chory There must be something different between both servers.
For instance, what's your local server? XAMMP? WAMP? Other?
And the remote one?
There's a lot to see, because both servers might be the same, but might have slight installation changes that prevent the correct display of e107 on it.
I've said it, and keep it saying, i've had long time ago issues like that, and just changing servers solved the issue, so....

**Comment by chory** [comment]
I'm trying to explain to me (OVH) how I can modify the configuration of my server, so I try to run e107 correctly, but I think I'm going to have to change, hosting, or CMS.
And I honestly do not fancy either one or the other.
I hope I can solve it. 😠

**Comment by Crytiqal** [comment]
@chory are you using the same php version on local and remote?

**Comment by chory** [comment]
I have tried the same version in both, and it only works for me in local.
So I'm already looking for another server

**Comment by CaMer0n** [comment]
@chory please message me on gitter and we can work through it.

**Comment by chory** [comment]
well, I moved mi site to other host, and PM works correctly.
Thank U

**Comment by CaMer0n** [comment]
Okay, thank you for letting us know.
