### ISSUE TITLE
update plugin from e107.org - report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2636]
Ok, maybe something is wrong with plugin itself, so this is what I checked

- actual version 1.0  (on e107.org is 1.1)
- click on Available update box
![image](https://cloud.githubusercontent.com/assets/5429548/26045865/7fbe4072-394c-11e7-85a2-19dde2210155.png)
- everything looks normal
![image](https://cloud.githubusercontent.com/assets/5429548/26045888/9f1cc79a-394c-11e7-8cd9-44b462552c53.png)
- but message is back and nothing new in Plugin Manager. Plugin still have version 1.0

After checking:
zip was downloaded correctly (inside is 1.1.)
![image](https://cloud.githubusercontent.com/assets/5429548/26045966/0c62ab94-394d-11e7-9756-85b0dce4eeed.png)
 

Atributtes are set this way (for e107_plugins and folders inside):
 
![image](https://cloud.githubusercontent.com/assets/5429548/26045968/0f4ab036-394d-11e7-92ea-13a08b6c368c.png)

What is wrong?

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Does clearing system cache fix it?

**Comment by Jimmi08** [comment]
This was duplicate. No problem with latest updates.
