### ISSUE TITLE
FAQ plugin lang files are missing from verify pack

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2639]
![image](https://cloud.githubusercontent.com/assets/5429548/26199809/b1e53a48-3bcb-11e7-9b1a-83f5bb7e555e.png)

**Comment by CaMer0n** [comment]
You'll notice FAQs is not part of the official release, hence, not part of the official language pack.

**Comment by Jimmi08** [comment]
Thank, I didn't notice this. So only core plugin can be translated via verify option?

**Comment by CaMer0n** [comment]
That's correct. If you want to temporarily hack it for others, you can.. see 'thirdPartyPlugins' method.
