### ISSUE TITLE
e_menu - dropbox always has to have default value?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2641]
I don't know if this is correct behaviour.

-  I have dropbox field in e_menu.php filled from database.  Because I didn't want to have empty option, I didn't fill default value at first
`    $fields['section']     = array('title'=> 'Section', 'type'=>'dropdown', 
			'writeParms'=>array('optArray'=>$sections,'default'=>'blank' ));`

Result was in html correct:
![image](https://cloud.githubusercontent.com/assets/5429548/26239198/543f1574-3c7c-11e7-834c-470408297c3c.png)

but it wasn't in database  and parm wasn't sended
![image](https://cloud.githubusercontent.com/assets/5429548/26239324/dbc0404a-3c7c-11e7-8ea1-537bc80d0554.png)

After changing to (adding default value):
 
```
     $fields['section']     = array('title'=> 'Section', 'type'=>'dropdown', 
			'writeParms'=>array('optArray'=>$sections,'default'=>'Select option' ), 'help'=>'Select section used with menus');

```
result was correct:
![image](https://cloud.githubusercontent.com/assets/5429548/26239272/a00adc18-3c7c-11e7-95c2-207c2465e526.png)

**Comment by Moc** [comment]
Yeah I guess it always needs a default option..

**Comment by Jimmi08** [comment]
It looks like fixed, create with normal array from retrieve(), no default option. 
 
```
      		  $fields['menutypeid']        = array('title'=> "Content Category", 
              'type'=>'dropdown', 
              'writeParms'=>array('optArrays'=>$catarray ));
```
