### ISSUE TITLE
backup doesn't export core table right way

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2643]
After backup this is result in SQL file:

![image](https://cloud.githubusercontent.com/assets/5429548/26277059/ca7596e2-3d84-11e7-9a15-1da44963f64d.png)

All records are empty.

**Comment by Jimmi08** [comment]
Oh, all text fields are empty:
![image](https://cloud.githubusercontent.com/assets/5429548/26277382/542de8de-3d86-11e7-9c49-a8d3b2c01a35.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Please re-test with latest changes.

**Comment by Jimmi08** [comment]
@CaMer0n I can't now. You can close it and I will reopened it. I know about this, maybe in next week

**Comment by Jimmi08** [comment]
@CaMer0n It looks correct now.
![image](https://cloud.githubusercontent.com/assets/5429548/26695637/d8cc43fe-470b-11e7-8533-c8d45c2efbef.png)

Thank you
