### ISSUE TITLE
Avatar in usersettings.php (button missing) not changeable

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2650]
Hi,

I have a problem with uploading the avatar in usersettings.php: I´m trying to change it but there is no upload button available. In Admin settings, (Settings > Signup Page Options > Options > Avatar is required) and (User > Options > Allow Members to Upload an avatar? > YES). Does anyone have an idea how to fix this?

- Killer0561

**Comment by tgtje** [comment]
Logical mismatch in usage (you just have to know it:
Explanation : logical >Options > Avatar is required OK but >  Allow Members to Upload..
Notice the logic...MEMBERS > not a person who likes to BECOME a member....

Only workaround : upload (admin work) some avatars to choose from (with those settings) in folder 
e107_media/namenumber.../avatars/default/.
**When member** (textual info ??) they are able to change it and upload there own..
;-)

**Comment by Killer0561** [comment]
I've done it as described, but it does not work.

**Comment by Killer0561** [comment]
problem is solved! - copyied the bootstrap.js to my theme js dir and load it, now works the avatar upload and select :)

**Comment by rica-carv** [comment]
If tyour theme his bootstrap based, theoretically you shouldn't need to copy the bootstrap.js file to it.... E107 can provide the bootstrap.js file inside the theme, there's no need to copy it to theme js dir, and load it manually....
Just my two cents...

**Comment by tgtje** [comment]
The possibility of the layouts influence seems to be the culpritt> (as discussed at an earlier state (gitter/e107help)  Good to know (using a v1 based template)... _If you are satisfied with result_ please close this issue.
