### ISSUE TITLE
Keywords characters not working on frontpage

### ISSUE THREAD

**Issue by Liszur** [e107inc/e107#2653]
Hi,
I tried to show my keywords on the frontpage with Tag Cloud 1.3 plugin, but if i add 'közlemény' tag in the SEO subpage, the plugin show me on the frontpage 'koezlemeny'... How can I fix this? Everywhere else working fine. 

Thanks!

**Comment by Liszur** [comment]
I found it in tagcloud_class.php. If anyone else has this problem, just edit this:
`protected $transliterationTable = array();`

**Comment by CaMer0n** [comment]
A pref to enable/disable this would be better so you don't have to modify it again after each upgrade of e107.
