### ISSUE TITLE
Do you have any idea how can I make two (or more) columns news_categories menu?

### ISSUE THREAD

**Issue by Liszur** [e107inc/e107#2654]
Hi,
I would like to make a two or more columns news categories menu (for my frontpage) but I am clueless how can I make such a look and how could I copy the categories menu (i would like to maintain the original for right sided menu purposes).
Thanks for your help!

**Comment by tgtje** [comment]
According to post on e107 help too, i think this issue can be closed. ( https://e107help.org/3513/you-have-idea-can-make-two-more-columns-news_categories-menu )

**Comment by tgtje** [comment]
According e107 help (https://e107help.org/3513/you-have-idea-can-make-two-more-columns-news_categories-menu ) think this issue can be closed, as marked solved there..
