### ISSUE TITLE
[Feature Request] - Previous polls page heading

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2658]
When viewing oldpolls.php the heading says '**Previous Polls**' while you're viewing the index or a single past poll item. I feel it would make more sense if the heading read '**All Previous Polls**' instead. 

I think so because it feels a bit recursive and confusing when you are viewing a single item and that currently viewed item is still listed in the index below it (without index numbering).

**Old Polls Index:**
![image](https://cloud.githubusercontent.com/assets/315195/26532171/e4b7e172-440a-11e7-82bc-e370d1b2b3c8.png)

**Old Polls Item View:**
![image](https://cloud.githubusercontent.com/assets/315195/26532188/3837f21a-440b-11e7-8473-3eb471e85110.png)

**Comment by CaMer0n** [comment]
okay for the change! 👍  Pull-request welcome :-)
