### ISSUE TITLE
Admin 'Preview button' for poll plugin doesn't do anything?

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#2660]
Admin 'Preview button' for poll plugin doesn't do anything? (Or it just show up the create button...) Is it supposed to be like this.

![poll-preview-button](https://cloud.githubusercontent.com/assets/315195/26532338/fa3bc546-440e-11e7-81a8-11c7779ccd7f.gif)

**Comment by CaMer0n** [comment]
It used to render the poll. Not sure why it stopped.
