### ISSUE TITLE
feature request - ability to use 'multilan' param for admin_ui fields

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2663]
Now, multilan param works only for preferencies. it would be great to have this possibility for fields too.

It's more for plugin developer, when table is the same for all languages and only title is changing. Or something like that.  Use multilang tables is not good option. 

Thank you

**Comment by Moc** [comment]
I guess this needs to go as a feature request into https://github.com/e107inc/multilan

**Comment by Jimmi08** [comment]
This is impossible to do. Discussed with CaMeRon already.
