### ISSUE TITLE
feature request - multilang tables

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2666]
if table is set as multilang, with adding new record in one language (default), possibility to mark it and create copy with the same ID under language tables.

**Comment by Jimmi08** [comment]
Next one:
if multilang tables exists, admin shouldn't be able so easy change default site language - maybe little warning or disabled this while tables exist

**Comment by tgtje** [comment]
Post 1 : although i seldom used the Multi-Language tools plugin (Cameron's) it was afaik designed to at least ( option) mark them to be translated.
post 2 ?  if multilang is set, the switch still should be working; Site default is the one you see at first visit and cookie not yet set...  ( aka whenever someone visits that language should be the one running..)
_I do believe that when an admin.. you do have some understanding what happens (consciousness)._ and can act accordingly ....

**Comment by Jimmi08** [comment]
@tgtje by mark it I thought that to check it (first column) and than copy to other language. What I am missing is possibility to copy from one lang to other after creating multilang table. When you have table with only one multilang field and 10 others, it's nightmare to set everything again when the fields are the same.

You can change site language by mistake because now there are two switcher (for admin too). This mistake cost you all your data in other language, so little warning would be handy.

**Comment by tgtje** [comment]
Yup that is trouble (well trouble, more an issue) using table copies ..it is a 1 way 1 direction.
As for the change...aha.. you mean like keep everything 'locked' till save state is made.. ok, good one

**Comment by CaMer0n** [comment]
Multi-language Sync option in the multilan plugin does this. And it can also be done manually with that plugin. A lot of people only run one language, so I don't see such a feature being added to the core of e107.
