### ISSUE TITLE
news_shortcodes.php not working on php7

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#2667]
> **Site Info**
> e107
> Version 2.1.5
> 
> Server
> Apache/2.4.18 (Ubuntu)
> (host: videodocker.com)
> 
> PHP Version
> 7.0.18-0ubuntu0.16.04.1
> 
> MySQL
> 5.7.18-0ubuntu0.16.04.1
> Database: videoDocker_www
> PDO: Enabled
> Mode: NO_ENGINE_SUBSTITUTION
> 
> Charset
> utf-8
> 
> Server Time
> Wed, 31 May 2017 20:03:32 +0000

```
function sc_newscommentlink($parm=null)
{

	if($this->commentsDisabled || ($this->commentsEngine != 'e107'))
	{
		return null;
	}

	$class = varset($parm['class']) ? " ".$parm['class'] : "";

	if(empty($this->param['commentlink']))
	{
		$this->param['commentlink'] = e107::getParser()->toGlyph('fa-comment');
	}		
	// When news_allow_comments = 1 then it is disabled. Backward, but that's how it is in v1.x
	$text = ($this->news_item['news_allow_comments'] ? $this->param['commentoffstring'] : "<a title='".$this->sc_newscommentcount()." ".LAN_COMMENTS."' class='e-tip".$class."' href='".e107::getUrl()->create('news/view/item', $this->news_item)."'>".$this->param['commentlink']."</a>");
	return $text;
}
```

    var_dump ($this->param['commentlink']); // string(0) ""

Apparently, in php7.0 you can't use the same variable for string and array, which imho is a good thing ;)
This means the that the {NEWSCOMMENTLINK: glyph=comments&class=btn btn-default} shortcode in the news_template.php does not work.

```
$NEWS_TEMPLATE['default']['item'] = '
{SETIMAGE: w=400&h=400}
<div class="default-item">
	<h2 class="news-title">{NEWS_TITLE: link=1}</h2>

        <hr class="news-heading-sep">
         <div class="row">
       		<div class="col-md-6"><small>{GLYPH=user} &nbsp;{NEWSAUTHOR} &nbsp; {GLYPH=time} &nbsp;{NEWSDATE=short}</small></div>
        	<div class="col-md-6 text-right options"><small>{GLYPH=tags} &nbsp;{NEWSTAGS} &nbsp; {GLYPH=folder-open} &nbsp;{NEWSCATEGORY} </small></div>
        </div>
        <hr>
        {NEWSIMAGE: item=1}

        <p class="lead">{NEWS_SUMMARY}</p>
        {NEWSVIDEO: item=1}
        <div class="text-justify">
        {NEWS_BODY}
        </div>
        <div class="text-right">
        {EXTENDED}
        </div>
	<hr>
	<div class="options">
		<div class="btn-group hidden-print">{NEWSCOMMENTLINK: glyph=comments&class=btn btn-default}{PRINTICON: class=btn btn-default}{PDFICON}{SOCIALSHARE}{ADMINOPTIONS: class=btn btn-default}</div>
	</div>
</div>
';
```

**Comment by Crytiqal** [comment]
The same issue for ```$this->param['itemlink'];``` and possibly others

**Comment by CaMer0n** [comment]
Test with PHP 7.0 and 7.1. Works fine for me with Bootstrap3. Do you have fontawesome loaded?

**Comment by Crytiqal** [comment]
I believe so yes. All the other icons below the news item are working.

**Comment by Crytiqal** [comment]
Doing a var_dump just below the assignment of commentlink returns an empty string.

var_dump ($this->param['commentlink']); // string(0) ""

**Comment by Crytiqal** [comment]
http://php.net/manual/en/migration70.incompatible.php

```
Expression 	        PHP 5 interpretation 	PHP 7 interpretation
$$foo['bar']['baz'] 	${$foo['bar']['baz']} 	($$foo)['bar']['baz']
$foo->$bar['baz'] 	$foo->{$bar['baz']} 	($foo->$bar)['baz']
$foo->$bar['baz']() 	$foo->{$bar['baz']}() 	($foo->$bar)['baz']()
Foo::$bar['baz']() 	Foo::{$bar['baz']}() 	(Foo::$bar)['baz']()
```

I think this is what is causing the issue.

**Comment by CaMer0n** [comment]
> So there is definitely something wrong with assigning the value (e107::getParser()->toGlyph('fa-comment')) to the variable ($this->param['commentlink']).

Why?

`$this->param` is an array. 
`$this->param['commentlink']` is an empty string

`e107::getParser()->toGlyph('fa-comment')` returns a string to replace the empty one.  

What am I missing ?

**Comment by Crytiqal** [comment]
e107::getParser()->toGlyph('fa-comment'); works, but assigning this to $this->param['commentlink'] does not. Check my previous comment about PHP 7 expression interpretation. I think that shows $this->param['commentlink'] gets differently interpretate than with PHP 5.

**Comment by Crytiqal** [comment]
I don't know why, because imo it should work correctly, however none of the values are assigned to the array. I am using the latest php7.0 on Ubuntu 16.04

**Comment by CaMer0n** [comment]
PHP Bug? Try upgrading to 7.1?

**Comment by Crytiqal** [comment]
PHP Version 7.1.5-1+deb.sury.org~xenial+2

Same issue still.

**Comment by Crytiqal** [comment]
![screenshot-videodocker com-2017-06-03-12-20-15](https://cloud.githubusercontent.com/assets/1153508/26752726/18d16064-4857-11e7-91ba-592d48bc061a.png)

**Comment by Crytiqal** [comment]
Doing a var_dump just below the assignment of commentlink returns an empty string.
Assigning it to $randomVariable returns the string with the actual icon.
Referencing $randomVariable in $text actually works. 

```
function sc_newscommentlink($parm=null)
{

	if($this->commentsDisabled || ($this->commentsEngine != 'e107'))
	{
		return null;
	}

	$class = varset($parm['class']) ? " ".$parm['class'] : "";

	if(empty($this->param['commentlink']))
	{
		$this->param['commentlink'] = e107::getParser()->toGlyph('fa-comment');
                var_dump ($this->param['commentlink']); // string(0) ""
                $this->param['commentlink'] = "HARDCODED STRING";
                var_dump ($this->param['commentlink']); // string(0) ""
                $this->param['itemlink'] = "HARDCODED STRING";
                var_dump ($this->param['itemlink']); // string(0) ""

                $randomVariable = e107::getParser()->toGlyph('fa-comment');
                var_dump ($randomVariable); // string(31) "<ICON> " 
	}		
	// When news_allow_comments = 1 then it is disabled. Backward, but that's how it is in v1.x
	$text = ($this->news_item['news_allow_comments'] ? $this->param['commentoffstring'] : "<a title='".$this->sc_newscommentcount()." ".LAN_COMMENTS."' class='e-tip".$class."' href='".e107::getUrl()->create('news/view/item', $this->news_item)."'>".$this->param['commentlink']."</a>");
	return $text;
}
```
So it really has to do something with assigning the value to the $this->parm['commentlink'] for some reason.

```
var_dump ($this->param); // array(14) { ["caticon"]=> string(0) "" ["commentoffstring"]=> string(0) "" ["commentlink"]=> string(0) "" ["trackbackstring"]=> string(0) "" ["trackbackbeforestring"]=> string(0) "" ["trackbackafterstring"]=> string(0) "" ["itemlink"]=> string(0) "" ["thumbnail"]=> string(10) "border:0px" ["catlink"]=> string(0) "" ["current_action"]=> string(0) "" ["template_key"]=> string(7) "default" ["image_nonew_small"]=> string(61) "" ["image_new_small"]=> string(60) " " ["image_sticky"]=> string(111) " " } 
```

**Comment by Crytiqal** [comment]
The commentlink works in bootstrap3 theme, so I checked the theme.php and found the following line:

```define('COMMENTLINK', e107::getParser()->toGlyph('fa-comment'));```

So apparently I need this for all my custom themes to make it work?

**Comment by CaMer0n** [comment]
Please re-open if needed.
