### ISSUE TITLE
why is for og:image used sitelogo but tested sitebutton?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2669]
I noticed this:

```
$siteButton = (strpos($pref['sitelogo'],'{e_MEDIA') !== false) ? $tp->thumbUrl($pref['sitelogo'],'w=800',false, true) : $tp->replaceConstants($pref['sitelogo'],'full');
if($pref['sitebutton']) e107::meta('og:image',$siteButton);
```
I couldn't get og:image tag to get working and reason was that it is ignored image in sitebutton field (although by description this image should be used for facebook)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Did you try changing `if($pref['sitebutton'])`to `if($pref['sitelogo'])` ?

**Comment by Jimmi08** [comment]
@CaMer0n yes, it worked.

**Comment by Moc** [comment]
This bugfix didn't make it into core yet right?

**Comment by Jimmi08** [comment]
I think that no.

**Comment by CaMer0n** [comment]
@Jimmi08 Should be fixed now. sitelogo is used as a fallback of sitebutton is empty.
