### ISSUE TITLE
enhancement - mimified core css files

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2672]
Could be core css file minified?

![image](https://cloud.githubusercontent.com/assets/5429548/26729281/66460656-47ad-11e7-9d61-24fb0e2a5b0f.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 And what if you enable JS/CSS caching - does it fix it?

**Comment by Jimmi08** [comment]
@CaMer0n sorry for delay.  Just js/css caching enabled.
 
![image](https://user-images.githubusercontent.com/5429548/27319532-3deb88aa-5592-11e7-8f4b-89c5ef9cdf7f.png)

![image](https://user-images.githubusercontent.com/5429548/27319508-1f7acbce-5592-11e7-8b73-b0bdb5690742.png)

**Comment by Jimmi08** [comment]
Oh, I just found that there is preferencies for this in Advanced features.  Result after enabling it:
![image](https://user-images.githubusercontent.com/5429548/27320240-9245395c-5595-11e7-993e-142b53767bbe.png)
