### ISSUE TITLE
Plugin visual captcha error with contact.php

### ISSUE THREAD

**Issue by Batatafrita** [e107inc/e107#2673]
Hello
The visual captcha does not work correctly with contact.php
The image always of the authentication error

**Comment by Jimmi08** [comment]
@Batatafrita how many VC do you have on page? If you have bootstrap nav menu, there are 2 captchas.  Check if this is that problem or not.

**Comment by CaMer0n** [comment]
Here's where visual-captch issues should be posted: https://github.com/e107inc/visualcaptcha/issues
