### ISSUE TITLE
Is {SETIMAGE} working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2676]
I'm trying to use `{SETIMAGE}` inside a template like this: 
`{SETIMAGE: w=20}{PHALBUNS_STATUS}`

The `{PHALBUNS_STATUS}` function is this:
```
	function sc_phalbuns_status($parm='')
	{ 
    $image = $this->tp->toImage("./images/album-valid.png", $parm);
    return ($this->var['book_complete'] > 0?$image.(isset($parm['title'])?"&nbsp;".phalbuns_11:""):(isset($parm['title'])?"&nbsp;".phalbuns_10:""));
  }
```

But the image (stored on own plugin image folder) is always rendered with it's original size! What am i doing wrong here? Or `{SETIMAGE}` only works with media?

The weird thing is that i can make a workaround using the shortcode like this:
`{PHALBUNS_STATUS:title&w=20&class=img-fluid}`

But i really wanted to use `{SETIMAGE}`, since that in theory it would set width for next images rendered after it's definition, right?

**Comment by CaMer0n** [comment]
Try using the full path inside toImage() eg. `{e_PLUGIN}whatever/images/album-valid.png`
If it's just an icon, then use `toIcon()` instead.

**Comment by rica-carv** [comment]
@CaMer0n Thanks, it works...... 👍

**Comment by CaMer0n** [comment]
Okay great.
