### ISSUE TITLE
news_menu templates - templates are no merged from theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2678]
There are six news_menu templates now (CORE)

category,months,latest,other,other2,carousel

All except carousel are called only with 3 parameters, so  it should use:
$override = true, $merge = false,

Carousel menu template is called with:
$template = e107::getTemplate('news', 'news_menu', 'carousel', true, true); 
so $merge is true

At first -  there should be the same rule for all menus, in template you should change only template for menu you need.  So if core months_menu template is good, why to copy it to theme unchanged?

Second -  merging doesn't work.  You can try this on LandingZero theme.

Thanks

**Comment by CaMer0n** [comment]
Merging was failing if a 'key' was provided. If no key was provided, then merging occurred.  Fix coming shortly.

**Comment by CaMer0n** [comment]
@Jimmi08 Please test merging of plugin templates. Thanks.

**Comment by Jimmi08** [comment]
Ok, If I got this correct way.

Landing Zero use theme  $NEWS_MENU_TEMPLATE['months']  in theme template files.  
If I remove it, it should merge core $NEWS_MENU_TEMPLATE['months']  from plugin.

Result:
menu is not displayed. 

If I tried to find the reason:   PHP 7.0

```
	$template = e107::getTemplate('news', 'news_menu', 'months');	
	var_dump($template);
```
![image](https://user-images.githubusercontent.com/5429548/35140956-6af53846-fcf9-11e7-9a9b-d6f5bb8f4fde.png)

**Comment by CaMer0n** [comment]
@Jimmi08 All news menu should now be 'merging' .

**Comment by Moc** [comment]
@Jimmi08 This can be closed now right?
