### ISSUE TITLE
Update from 1.0.4 to 2.1.5

### ISSUE THREAD

**Issue by ajaybhargav** [e107inc/e107#2682]
Before Update:
![before_update](https://cloud.githubusercontent.com/assets/927133/26818953/679e1574-4aba-11e7-801f-9b8c7fe4bbf1.PNG)

I am getting following error when I click update button.
![after_update](https://cloud.githubusercontent.com/assets/927133/26818963/6cf1a748-4aba-11e7-9b98-700fdd67ac1b.PNG)

Please help me out with the update.

**Comment by ajaybhargav** [comment]
I have tried with multiple versions (git)
I tried checking out v2.0.0 v2.1 and latest.. same error in all. Am I doing something wrong?

**Comment by Jimmi08** [comment]
Try to use only core plugins. That first warning are about this. Only warnings.
And you have there mysql error about creating media tables. Something about key long. I would try to check via phpmyadmin your database and try to insert that SQLs manually.  Maybe you get more info. Or maybe tables are there ...  this is only warning.

**Comment by ajaybhargav** [comment]
I fixed the issue. It was due to wrong collation. In order to accommodate emojis I change collation to utf8mb4 which increased size of varchar(255) to > 1000 bytes. So I had to change it back to utf8 and that fixed. Now only thing pending is migrating site theme.
