### ISSUE TITLE
Extended User Fields 

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2686]
I made Extended User Fields for registration.
Label: How many five plus six? (written with text) 
Type: Text box
Applicable: Members
Read access: Members
Write access: Members

The field appears on registration page. User write "eleven" (this is right) but the system does not want to accept it and he will not let go.
Maybe I need made something on the admin set.

**Comment by fizi** [comment]
Please make it, because only the usersettings page appears. The system will not allow you to continue, only this page appears.

**Comment by Jimmi08** [comment]
Maybe related:  https://github.com/e107inc/e107/issues/2884

**Comment by Moc** [comment]
@fizi I believe this is fixed. If it is not, please let me know and I'll re-open.
