### ISSUE TITLE
enhancement - to have news date as link 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2691]
Now, there is shortcode` {NEWSDATE} ` but I would like it as link to display all news from the same date.  Something like when you click in blogcalender_menu on day and it displays news.
`e107::getUrl()->create('news/list/day', 'id='.formatDate($req_year, $xmonth, $xday));`
Thanks

**Comment by rica-carv** [comment]
Have you already tryed to create a custom shortcode inside the theme?

**Comment by Moc** [comment]
Feel free to submit this as a PR with a new shortcode

**Comment by Jimmi08** [comment]
Not needed anymore. If others need this, they should create their own issue.
