### ISSUE TITLE
question - news_months menu

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2693]
I noticed that news_months menu displays news only from one year (you can set in menu config or it is from actual year)

Is this intention?  Why would be reason for something like that?  In menu config you should be able to set how many months you want to display, but it should be cross the years.

How I can get something like this:
![image](https://user-images.githubusercontent.com/5429548/27286620-1b68188e-5501-11e7-88b0-04ce8acac515.png)

Thanks

**Comment by Moc** [comment]
Is this solved by #2808?
