### ISSUE TITLE
news_months menu vs list news by months - different counts

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2694]
news_months menu displayed some counts (news count), but after clicking on link, nothing was displayed.

Reason is that news_months menu don't respect  news_render_type , but news listing displays only type 0 or 1.

```
	if(!$sql->select("news", "news_id, news_datestamp, news_render_type", "WHERE news_class IN (".USERCLASS_LIST.")
		AND (FIND_IN_SET('0', news_render_type) OR FIND_IN_SET(1, news_render_type))  ORDER BY news_datestamp DESC", true, true))
```
blogcalender_menu - the same problem.
and displays wrong message (there should be day)
![image](https://user-images.githubusercontent.com/5429548/27288682-ba9e7ca8-5507-11e7-8b92-462f9872138e.png)

**Comment by Moc** [comment]
I have corrected the info message (day vs month) but I cannot reproduce the issue with the link not working correctly. The news items are shown fine. Both when using news_months_menu as well as blogcalendar_menu.

**Comment by Jimmi08** [comment]
@Moc 
Still problem.  Just set for some news template f.e. other news but not default.  
Menu displays all post, news page only news default (and probably 1) template.
Tested with 2.2.1

**Comment by Moc** [comment]
Looks like this is done pretty deliberately. 

https://github.com/e107inc/e107/blob/11b87ff17474902cded3d8fa50e503ce03e1388a/e107_plugins/news/news.php#L1420

This line means that it will check if the news_render_type (location) is set to either 0 or 1 (`Default` & `Default - Title`)

@CaMer0n Is this done deliberately? Should all news items be shown, regardless of the set render type?
