### ISSUE TITLE
question about signin

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#2695]
Hello people,
Currently exist a plugin that allow other apps log-in with some e107 application?

This is my situation. I have a small syte done in e107, but currentli i wanna to create a other complementary web App using laravel, but instead of use a completely new users database, I wanna let the users log-in with the e107 credentials.
Currently exist a method to do this?
Thanks for all.

**Comment by LaocheXe** [comment]
Social plugin, or go to Admin Area > Database > Multi-Site

**Comment by sanslash332** [comment]
Em… How to I can use these options for my purpose?

 

In the social plugin, I only see options for use with my syte.  Let the people login with fb, twitter, or other social things like tweets, shares, etc, but nothing of that I need.

And in multy-syte, the options that appear in the panel, are for make a new fresh copy of e107 database in a new URL, but nothing of create a login api.

 

Do you know if is possible create an api, or something similar, to let a new website, login with my e107 syte.

 

Like that you do in a regular syte with facebook, login. In this case, with my syte login.

 

Thanks for all.

**Comment by tgtje** [comment]
Not my street : but sounds like the Alt Auth plugin might be of use ?

**Comment by sanslash332** [comment]
Em, nop.

 

Alt Auth, is for let the users login in to my e107 websyte using alternative methods like ldap, radius, import users from a old website, etc.

 

That I want, is the opposite side. Let the users from a other non e107 websyte, login using the e107 user data base.

**Comment by Moc** [comment]
The 'leading' system (non e107 in this case) needs to provide a solution. There is no API in e107 to support this.

**Comment by Moc** [comment]
At least, to my knowledge :D

**Comment by sanslash332** [comment]
Am, OK… thanks

 

I have to look What I can do.

Thanks
