### ISSUE TITLE
HEADERF bug?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2699]
I didn't spot it anywhere, but if i'm wrong, please correct me:
I've had some weird issues with templates on my plugin, and i found out that if i have my templates inside the $template variable, and have called the HEADER before rendering the template, they are rendered with only the first char of the template string.....
Just wondering if this is a bug or should be documented...

**Comment by G4HDU** [comment]
I discovered today that HEADERF throws errors if it is called from inside a class. I wanted a function in my class to render the page but it was having none of it.

**Comment by Moc** [comment]
@CaMer0n Your thoughts please :)

**Comment by CaMer0n** [comment]
It's normal that errors will be thrown since global variables (used in HEADERF) are not available inside functions unless specified. Call it a limitation of PHP. ;-)

**Comment by Moc** [comment]
Not considering this a bug. Please re-open or submit pull-requests if you'd like to change this behaviour.
