### ISSUE TITLE
Plugin pref 0 value bug?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2700]
I got a plugin that has this in the plugin.xml prefs section: `<pref name="sale">0</pref>`
Everytime i install it, that pref is stored in the database as `''` !!!!
Why?
I've checked the core prefs in the database and in the xml, and when it's 0 on the xml, it's 0 in the db...

**Comment by tgtje** [comment]
Just an idea popped up : is SALE a pref or a title ? (sale seems more a fieldname).
(way of thinking : if sale is the underlying hidden 'box/field' and 0 has to be stored.. it would need a table with a name it belongs to? Maybe i am mistaken sorry then, else i blame it on the temperature here.. bwaa tropical)

**Comment by rica-carv** [comment]
@tgtje Sorry, but it's really a pref, like [this](https://github.com/e107inc/e107/blob/master/e107_plugins/pm/plugin.xml#L12)
Here is also too hot... :fire: 🚒

**Comment by tgtje** [comment]
Sale = 'tab'=>1, 'type' => 'number', 'data' => 'int'  ??  (just trying to grasp)

**Comment by rica-carv** [comment]
@tgtje No, it's a xml pref. Still not admin area designed, so....

**Comment by tgtje** [comment]
maybe i have the wrong idea...
![table](https://user-images.githubusercontent.com/1811857/27453471-e3574652-5796-11e7-9616-04402516d2b8.jpg)
this is what you want (afaik) in this image the únknown table (does it exist?).. varchar  or int (if it is to use as calcs it should be int /? ( it is a combi of above post) it has to store something somewhere.. Else no idea and wait for more comments....

**Comment by rica-carv** [comment]
@tgtje No, you're on the wrong direction....
I haven't yet designed the admin ui, but that `<pref name="sale">0</pref>` is supposed to render a boolean field in the admin area (the on/off ones), not numeric at all....

**Comment by CaMer0n** [comment]
@rica-carv please see https://github.com/e107inc/e107/issues/2803 which is a duplicate of this bug I think.

**Comment by rica-carv** [comment]
@CaMer0n Yes, it is....
