### ISSUE TITLE
forum template - missing parent end part

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2707]
I am porting theme that needs "start" and "end" of parent forum (main forums are inside it).  
Quickly fix would be add this:
`	$FORUM_MAIN_PARENT_END 		= $FORUM_TEMPLATE['main']['parent_end'];`

to this part of forum.php file:
```
	$FORUM_MAIN_START		= $FORUM_TEMPLATE['main']['start'];
	$FORUM_MAIN_PARENT 		= $FORUM_TEMPLATE['main']['parent'];
	$FORUM_MAIN_FORUM		= $FORUM_TEMPLATE['main']['forum'];
	$FORUM_MAIN_END			= $FORUM_TEMPLATE['main']['end'];
```
Tested, works, I woudl create PR, but... 

@rica-carv helped me with it and he was able to solved this by adding code to `$FORUM_TEMPLATE['main']['end'];`  -  it shouldn't work, I double checked original code.  

So I did fresh install of e107 and use his version of theme (not changing a line). Of course it looks like this (this can be fixed by that line from above):
![image](https://user-images.githubusercontent.com/5429548/27515272-ae4852b6-599f-11e7-8a85-2cda3853ca1f.png)

But it works for him:
![image](https://user-images.githubusercontent.com/5429548/27515277-ce8f37a6-599f-11e7-8716-3b07cbd47f8e.png)

What is different?  Why I have bootstrap icons there and he has images?  I used exact code as him. 
Thanks

**Comment by tgtje** [comment]
Pfff  investigating forum moderator related things ( no results there yet...getting confused with forum), but if i may add since you mention the icons... looks like iconkey use **viewforum**  maybe the wrong template??  (those icons are legacy from v1 (forum images/dark/light/icons))

**Comment by Jimmi08** [comment]
Solved icons questions.

**Comment by Jimmi08** [comment]
@CaMer0n 
Can I pull that change?

`$FORUM_MAIN_PARENT_END 	= $FORUM_TEMPLATE['main']['parent_end'];`

**Comment by CaMer0n** [comment]
@Jimmi08 Yes please! 👍
