### ISSUE TITLE
forum_viewforum_template.php and wrong/missing lang string

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2710]
It looks like this before:
![image](https://user-images.githubusercontent.com/5429548/27517539-a7d732ce-59ce-11e7-8ed3-d8d1aeaec1d0.png)

Now there is string "Topic"  for the same shortcode `{THREADTITLE}` and it looks like this:
![image](https://user-images.githubusercontent.com/5429548/27517563-08b890ec-59cf-11e7-8b76-1b13fb11a7df.png)

I didn't find string "Thread" to replace this shortcode in template.

**Comment by tgtje** [comment]
Do not know how the template was build, 
but if it is using legacy v1 stuff go for  "LAN_1"  (in use with 0.6-1) and still is in lan_top php. 
Thesedays LAN_1 =Normal (by definition commented out IN forum and replaced by LAN_FORUM_3038)
 (forumheader calls also make use of lan_1)(top php)
And lan top etc uses LAN_1 with define as Thread...

**Comment by Jimmi08** [comment]
`define("LAN_FORUM_3038", "Normal"); // LAN_1`  

Thanks, I checked all source code for that string and I didn't find it.  How should I load get this loaded from lan_top.php?

More info:
Now:
```
		function sc_threadtitle()
		{
			return LAN_FORUM_1003;
		}
define("LAN_FORUM_1003", "Topic"); // LAN_55
```

before:
```
$THREADTITLE = LAN_53;
define("LAN_53", "Thread");
```

template is build this way: 
```
	<td style='width:3%' class='fcaption'>&nbsp;</td>
	<td style='width:47%' class='fcaption'>{THREADTITLE}</td>
	<td style='width:20%; text-align:center' class='fcaption'>{STARTERTITLE}</td>
	<td style='width:5%; text-align:center' class='fcaption'>{REPLYTITLE}</td>
	<td style='width:5%; text-align:center' class='fcaption'>{VIEWTITLE}</td>
	<td style='width:20%; text-align:center' class='fcaption'>{LASTPOSTITLE}</td>
```
Thanks

**Comment by Moc** [comment]
Just FYI, maybe not needed but just in case, in V2 we use only the word 'topic' not 'thread'. So far this is only resembled in the LAN, the actual code and db structure still use 'thread' occasionally

**Comment by tgtje** [comment]
If i understand correctly it is/becomes a theme present forum template ? If yes.. overcome all (since not core issue) by hardocding (as text instead of LAN?)

**Comment by Jimmi08** [comment]
To use theme LANs strings occured me just now. Solved. Thank you to all.
