### ISSUE TITLE
online plugin - not able to use new template way with non-bootstrap theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2712]
There is test for BOOSTRAP  defined to use new templates:

```
if(deftrue('BOOTSTRAP'))
{
	$LASTSEEN_TEMPLATE = e107::getTemplate('online','online_menu', 'lastseen'); // $ONLINE_MENU_TEMPLATE['lastseen'];
}
else
{
	if (is_readable(THEME.'online_menu_template.php'))
	{
		require(THEME.'online_menu_template.php');
	}
	else
	{
		require(e_PLUGIN.'online/templates/online_menu_template.php');
		$LASTSEEN_TEMPLATE = $ONLINE_MENU_TEMPLATE['lastseen'];
	}

}
```
It should be probably test for THEME_LEGACY, not BOOSTRAP.

**Comment by rica-carv** [comment]
Furthermore, can't the `e107::getTemplate` nativelly handle that?
I mean, decide how to load a template if it's legacy coded or v2.x coded?

**Comment by CaMer0n** [comment]
Changing the first line to: 

`if(THEME_LEGACY === true)`

..should fix it.

**Comment by Jimmi08** [comment]
@CaMer0n  shouldn't it be ?
`if(THEME_LEGACY === false)  `

**Comment by CaMer0n** [comment]
Sorry, you're correct.

**Comment by CaMer0n** [comment]
@Jimmi08 Did this actually fix it?

**Comment by Jimmi08** [comment]
I don't use anymore legacy themes, only bootstrap, so I don't have where to test this. But it should.

**Comment by CaMer0n** [comment]
Thanks, committed.
