### ISSUE TITLE
form handler double dollar

### ISSUE THREAD

**Issue by G4HDU** [e107inc/e107#2715]
In the form handler search function line 2715
`$text .= $this->selectbox($$filterName, $filterArray, $filterVal);`
should be
`$text .= $this->selectbox($filterName, $filterArray, $filterVal);`

viz filterName is preceeded by 2 $ instead of one.

incidentally, selectbox is deprecated, use select instead.

**Comment by arunshekher** [comment]
Father Barry,
It was fixed by @CaMer0n alongside the search filter issue you reported in this commit --> 39e340caa7c7503d29af

**Comment by G4HDU** [comment]
I suppose I should have checked the latest source - sorry my bad :p
