### ISSUE TITLE
Issue: Plugin Manager > Upload Plugin

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2717]
Trying to upload the vstore plugin via plugin manager. I go to the Upload, select the file, hit upload, get sent to the installed plugins page in like 2 secs, no vstore plugin in the installed, and not installed areas - have no clue if it is uploading or not.

**Comment by CaMer0n** [comment]
Was the .zip downloaded from github? If so, this is likely the reason.

**Comment by LaocheXe** [comment]
Yes, I also change the name of the folder, and removed the -master, and that didn't work either.

**Comment by CaMer0n** [comment]
Did you test with other plugins (eg. downloaded from e107.org) ?

**Comment by Moc** [comment]
@LaocheXe Any feedback?

**Comment by LaocheXe** [comment]
Tried a few from e107 website, and some from github, and even tried some that I've made on my end, no error - page refreshes to installed plugins, and I went looking and could not find any of the plugins I tried to upload in plugin manager.

**Comment by CaMer0n** [comment]
@LaocheXe github zip files will fail. They need to be extracted and zipped with the correct folder names etc.
