### ISSUE TITLE
Strange chars in login menu strings

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2719]
I'm using latest github files, with portuguese language, and the login menu fields & text have wrong accented portuguese chars rendered:
![untitled 1](https://user-images.githubusercontent.com/17130530/27733179-a330ef14-5d8c-11e7-8dd8-c8bfbaf92e4b.jpg)

This happens either in localhost and live hosting

**Comment by tgtje** [comment]
Just information : see differences between browsers? (Chrome v59 ..nahh)

**Comment by CaMer0n** [comment]
@rica-carv please check language file encoding.

**Comment by rica-carv** [comment]
@CaMer0n Language files were downloaded from here.... and unaltered....

**Comment by tgtje** [comment]
Just tested the lang pack on fresh 2.1.6 git (pack is for v2 compat) verify : 887 issues; however no errors to be seen (local).
![login](https://user-images.githubusercontent.com/1811857/27839134-49ca2858-60ef-11e7-9168-8928fb9069b5.jpg)

**Comment by rica-carv** [comment]
Hummmm, guess this requires further investigation...
Just tryed swap themes, and with my custom theme, situation still persists, while with bootstrap3 theme it is displayed correctly, so i'm wondering if this is a theme issue...

**Comment by Moc** [comment]
Sounds like a theme issue. Did this get fixed or is it still an issue?

**Comment by rica-carv** [comment]
@Moc Yes, it is theme issue, but i haven't narrow it more... Maybe i need to call Sherlock Holmes....

**Comment by Moc** [comment]
Closing for now, let us know if need further help.

**Comment by rica-carv** [comment]
Even forcing the theme to UTF-8, it still persists.....
Anyone has any more ideias?
Thanks...

**Comment by CaMer0n** [comment]
Looks like a language file saved with the wrong encoding.

**Comment by rica-carv** [comment]
I've checked all the enconding on the language files, inclunding the one on the theme itself, and are all encoded as UTF-8.....
