### ISSUE TITLE
Mediamanager 2e page thumbs not selectable..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#2720]
Hi, when i use the mediamanager to select an image and it is one on the second of third page it will never appear in the custom page, it does not work, only the first page. Under appeareance also the dimensions are not filled.. 

Help please... Leo has the same problem, php version 5.6.30 Github of today..

Alex

**Comment by tgtje** [comment]
I confirm (php version does not matter); no clue when this started. Example : page/tab 1 selected image becomes greyish, saving ok > editor has image; page/tab 2 or 3 the image is not selected (mouse hovers ), no save/transfer to editor.

**Comment by CaMer0n** [comment]
@Alex-e107nl For me it adds the thumbnail but doesn't close the media-manager popup window. Which area are you testing with.. news?

**Comment by Alex-e107nl** [comment]
Hi no custom page just try to place an image with the mediamanager from the 2e page with thumbs..

**Comment by CaMer0n** [comment]
So you mean a "Page"? Are you adding the image via TinyMce or are you adding the image to a custom field in a "Page" ?

**Comment by CaMer0n** [comment]
@lonalore Could this be related to recent changes to the MediaManager .js file?

**Comment by tgtje** [comment]
As mentioned i tested too, before Alex posted it; it is in plain editor field (either in wysiwig mode or plain/bb) using the Insert an Image from the Media Manager (bb) or Insert image from Media-Manager (tiny/wysiw).  (which opens the pane window with thumbs).

(identical if using editor creating menu) Using an elder mm js stops page 'shift (eg next page, no go)

**Comment by lonalore** [comment]
With the latest github files it works fine for me. I tried to add image via TinyMce and BBarea. Both of them worked.

What browser do you use? Can you provide me a step-by-step procedure to reproduce this?

"Next page" button only works if you have more than 20 images. The only thing I found wrong is the "Previous page" button (it works even if there is only one page).

**Comment by tgtje** [comment]
(me) php 5.6.24 & php 7.1  local &live  : creating a page (or menu)  editor > text typed. enter> adding image > (present 84) so 3 tabs exist > from tab2 and tab 3 no images can be selected _(or does not save it_ to editor  ) in both versions of php... (and sites) 
(the ditor window BELOW, does react when clicking save..(border changes colour) but no result)

I have no issues using the prev next buttons (<<  >>)

**Comment by lonalore** [comment]
Sorry for the late answer / commit.

**Comment by tgtje** [comment]
@lonalore 
Better late then never :) 
Although still a PR i apllied/tested the fix : result after emptying cache 👍 working (local + live) Thank you.
@Alex-e107nl please also test and share your findings

**Comment by Alex-e107nl** [comment]
Tested and it works perfectly!! Many thx!!!
