### ISSUE TITLE
[FEATURE REQUEST] Unique string AREA's name in the menu manager

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2723]
Hi again,

is there any change we can change the type of AREA's name to string instead of numeric ? 
for example i have an area in top bar, i want to named it to AREA 'topbar' instead of AREA 1 in the menu manager, so we can easily manage the areas both in the menu manager and theme.php

thank you in advance

**Comment by CaMer0n** [comment]
@drasehat Did you find a work-around?

**Comment by rica-carv** [comment]
@drasehat I would also like to know, since i can't really understand what you're trying to accomplish...
