### ISSUE TITLE
Forum mentions

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#2725]
Hello guys.
A small question, currently exist any plugin that implements mentions to the fórum post in the e107 system?
For example, if you put @username in any fórum post, that user is advised, and the @username text appear as a link to the userprofile. Well, like the mentions in github, or other fórum system xd.

Thanks.

**Comment by rica-carv** [comment]
Isn't that already displayed in a forum post when you quote a user post?
Or i understand wrong?

**Comment by sanslash332** [comment]
Nop, one thing is quote a user post, and other thing is mentions like twitter.

 

I simply want is can write @username and with that, that text is converted to a link to the userProfile, and the user is notificated that is mentioned on that thread :3 

 

VBulleting and ZenForum have that.

**Comment by arunshekher** [comment]
@sanslash332, Could extend core e_parse in a plugin by means of the plugin addon e_parse.php to achieve this I suppose. 

That would be the most less obtrusive way of doing it without altering much of data going to the database.

**Comment by sanslash332** [comment]
Is the idea. Any direct modification of the database. Only parse the text at renderin time… :P 

 

Thanks

**Comment by CaMer0n** [comment]
I believe @Moc may have been working on something.

**Comment by arunshekher** [comment]
@CaMer0n That's good to know.
@sanslash332, Any of these javascript libraries can be leveraged along with e_parse add-on I believe.

https://github.com/ichord/At.js
https://github.com/jakiestfu/Mention.js

**Comment by sanslash332** [comment]
Thanks, I’m gonna give a try :P

**Comment by arunshekher** [comment]
@sanslash332,
Were you able to get something started? I just played for some time with this idea (as I was revamping a similar old plugin of mine called NoFollow) and came up with this - https://github.com/arunshekher/Mentions

So far does the parsing and displaying of mentions decently. Autocompletion suggestion barely accomplished at this time used At.js implemented on chatbox only. For forum, integration with TinyMCE need to be looked into. Should be able to integrate with comments too I suppose. Selection of the JS library and the javascript usage might benefit from some rethinking. Currently its polling the server heavily. Hopefully won’t kill a database.

User notification part could be done by listening to native event triggers upon form submission (same logic used for parsing could be used), will explore that as next step. I’m also looking into caching of result data and call user table only when cached data is exhausted.

There is room for lots of improvement so contributions are welcome. Hope it will not discourage Moc from doing his version, having freedom of choice isn’t bad after all.

**Comment by Moc** [comment]
I won't be expanding on my version anytime soon. For the near future I'll be very little involved in coding projects but when I have some spare minutes I'll take a look at your version. 

Great job so far!

**Comment by arunshekher** [comment]
@Moc, Great! and thank you.

**Comment by sanslash332** [comment]
O, thanks!

 

I’m gonna tri it!

 

 

It looks that I need :P

**Comment by arunshekher** [comment]
@sanslash332, Please post issues related to the plugin directly in that repo and close this thread if you wish so.

**Comment by sanslash332** [comment]
Ok, perfect!

**Comment by Jimmi08** [comment]
@Moc this can be closed.

**Comment by Jimmi08** [comment]
Just to have everything together:  There is now plugin for this. 
https://github.com/arunshekher/mentions
