### ISSUE TITLE
e_emailprint issue

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2726]
I'm currently writing a few plugins that require the e_emailprint.php file.
Strangelly i got this error:
`Fatal error: Cannot redeclare print_item() (previously declared in ......\e107_plugins\forum\e_emailprint.php:4) in .......\e107_plugins\phil_lis\e_emailprint.php on line 103`
and an unrendered page content (white content) after the header...
Any thoughts?

**Comment by tgtje** [comment]
Maybe included more than one time ? try using include_once (just an idea)

**Comment by rica-carv** [comment]
Include e_emailprint.php?
It's a system plugin file, so there's no include....

**Comment by rica-carv** [comment]
Further investigation, just found out where's the issue:
```
function sc_phalbum_email($parm='')
{ 
     require_once(e_HANDLER.'emailprint_class.php');
     return emailprint::render_emailprint('phil_alb', $this->var['book_id'], 1, array("class"=>" btn btn-default"));
}
```
If i remove the require, i got the error emailprint is not defined.
Of course, if i remove the return line also, all is fine, but no shortcode output....

So my question is: What am i doing wrong here?
Those lines are almost identical to these ones on news_shortcodes.php:
https://github.com/e107inc/e107/blob/baaa766bc7a4a794eefc2e51815e842412ac7cee/e107_core/shortcodes/batch/news_shortcodes.php#L486
https://github.com/e107inc/e107/blob/baaa766bc7a4a794eefc2e51815e842412ac7cee/e107_core/shortcodes/batch/news_shortcodes.php#L495

**Comment by tgtje** [comment]
meant was : the include_once() and require_once() functions will not include the file a second time if it has already been included.

What happens if you only use require()  (error messg) or include() (warning messg). Mind just trying to bring in idea.

**Comment by rica-carv** [comment]
@tgtje I know, that's why i'm using `require_once(e_HANDLER.'emailprint_class.php');`
The weird thing is that if i enable that line, it does include the emailprint_class, and got the error.
If i remove the line, of course it's not included and the i got the error that emailprint is not defined....
So how can i use that? Or i can't?

**Comment by rica-carv** [comment]
Furthermore, what should be the email button behaviour?
On news, when clicking on email news, it goes and opens the pc system email program with a email prefilled.
On any plugin, it redirects to a page inside e107 to send an email from inside the site itself.....

It's kind of ankwards to have both options at the same time, no?

**Comment by tgtje** [comment]
Both at same time (ha used that often (ages ago))  It is psychology > Trusted or not, like your pc or rather through internet etc..  eye of beholder how you want to 'serve' him/her .... aka what do you want it to represent (at which level).

As for issue pjoehh  guessing : taken in consideration alike  ? https://github.com/e107inc/e107/blob/baaa766bc7a4a794eefc2e51815e842412ac7cee/e107_core/shortcodes/batch/news_shortcodes.php#L22  +23,24

Just noticed : posted : quote error  : phil_lis    and phil_alb     influence/typo/intended  or (= var) ... nearly out of ideas

**Comment by rica-carv** [comment]
@tgtje They're two plugins, sharing common database, and both "should" have e_emailprint.php...
But since there's the option of a button with emailto, i find rather "redundant" the presence of e_emailprint on a plugin.
Furthermore, the prin might also be redundtant, sionce now we have bootstrap css styles for print and non print, right?

Anyway, i ended up using the emaito, since if i left it's management ant core, it might lead to some "abuse"....
This way, i "force" the user to use it's own email program, and all is donne via the user pc.....

**Comment by Moc** [comment]
@rica-carv Do you still need help with this issue?

**Comment by rica-carv** [comment]
The problem still persists, but i've solved my issue the way i stated above....

**Comment by CaMer0n** [comment]
css print media is the better way to go.

**Comment by rica-carv** [comment]
@CaMer0n css print media can't handle email sending.
That was my primary question. The issue is that all the functions declared in e_emailprint.php conflict each other if called from different plugins...

**Comment by CaMer0n** [comment]
@rica-carv Indeed. It's all still using the v1.x specifications. A new v2.x specification needs to be made. 
And I believe email and print should be separated.

**Comment by Jimmi08** [comment]
Related:
https://github.com/e107inc/e107/issues/4452

**Comment by CaMer0n** [comment]
Closing. 
@Moc please re-open if you think it necessary.
