### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by gyoodev** [e107inc/e107#2729]
Hi I got this install problem

Installation Complete
e107 was unable to create all of the required database tables.
Please clear the database and rectify any problems before trying again.

MySQL Reported Error:
SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB'

**Comment by CaMer0n** [comment]
This could be related: https://github.com/e107inc/e107/issues/2559

**Comment by gyoodev** [comment]
Thank you sir,
I'll try to install the github version

**Comment by CaMer0n** [comment]
@gyoodev I believe you'll need to use the workaround explained in https://github.com/e107inc/e107/issues/2559

**Comment by gyoodev** [comment]
Installation Complete
e107 was unable to create all of the required database tables.
Please clear the database and rectify any problems before trying again.

MySQL Reported Error:
SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB'

the same problem with the github version

**Comment by CaMer0n** [comment]
@gyoodev InnoDB is not available. Please use the workaround as explained in #2559
