### ISSUE TITLE
XML in admin area...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2733]
I found out also a "strange" behaviour of plugin.xml files in admin area.
If you have a plugin with sitelinks defined in plugin.xml, they appear correctly in admin links. If you make any  change inside the links in sitelinks area in plugin.xml, it is reflected in the admin area without the need of scan or anything else, it just updates correctly.
So why can't this behaviour be replicated for the media manager?
If i add a media category in the plugin.xml, i've got to uninstall th eplugin and reinstall it to get the media categories for the plugin. Can't it be "scanned" like the site links are???

**Comment by CaMer0n** [comment]
In debug mode there is a plugin "Repair" button which should appear. Did it do what you need?

**Comment by rica-carv** [comment]
@CaMer0n Yes, it works.... Thanks...
