### ISSUE TITLE
e107::user bug...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2734]
I've got a very small shortcode, inside a $sql loop, with this code:
```
$AlbuserData = e107::user($this->var['book_author']);
            return (isset($parm['name'])?$AlbuserData['user_name']:"<a href='".e_SELF."?0.sbio.0.".$this->var['book_author']."' >".$AlbuserData['user_name']."</a>");
```

The weird thing is that my current db has 6 rows, and if i remove the line `$AlbuserData = e107::user($this->var['book_author']);`, it displays the 6 rows in a table correctly (but with user name missing)
![sem nome](https://user-images.githubusercontent.com/17130530/28320229-ed776fc8-6bc7-11e7-9832-d2cdf88bea58.jpg)

If i add that line, it only displays the first row, with the correct username....
![sem nome1](https://user-images.githubusercontent.com/17130530/28320239-f1afb190-6bc7-11e7-9d97-8db50d727bf0.jpg)

Can anyone test this bug? Thanks...

**Comment by CaMer0n** [comment]
Use `$sql->retrieve` (instead of a 'while' loop) for your table data, and see if that helps.

**Comment by rica-carv** [comment]
I can't use `$sql->retrieve` because i'm using a `left join` in the sql syntax, and `$sql->retrieve` only works with simple table fetch....
Currently i've solve the issue by adding one more `left join `to the core user table, but if that table changes name in the future, it will be useless...

**Comment by CaMer0n** [comment]
Try: 

    $sql = e107::getDb('yourplugin');

**Comment by rica-carv** [comment]
@CaMer0n I ended up using `getSystemUser`, like this:
`e107::getSystemUser(intval($this->var['book_author']))->getData()['user_name'])`

So for now, it works as intended.
Thanks for the help...
