### ISSUE TITLE
sorting images

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#2736]
hi, I would like have the chance for sort all images into plugin gallery 
for example by media_name or other field

**Comment by CaMer0n** [comment]
Umm.. /e107_plugins/gallery/admin_gallery.php  "Order images by" ?

**Comment by kreossino** [comment]
yes this is correct, but when i update a website this file  overwrited

**Comment by kreossino** [comment]
add a  new field only for sort images and gallery?

**Comment by CaMer0n** [comment]
It's a pref. Is it not working?

**Comment by kreossino** [comment]
Is it possible to  add in "gallery" an order field like the one in "Site Links" area "link-order"?

**Comment by CaMer0n** [comment]
Currently there is no field for this in the core_media table.

**Comment by Jimmi08** [comment]
@CaMer0n Media functionality is used for simple gallery. Its ok, and normal gallery plugin should just have image/images field and then it can have order field too.  Medias are used everywhere...  

So external plugin is solution for this, I would close this.
