### ISSUE TITLE
Feature Request: Override Code

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2742]
While looking into e107 code some more, and working on themes, I notice that templates can help change the view of the site. Example of this, the login_template I have set up to not show the regular fields to login, but instead to only show the social login buttons, using just the custom theme templates.

I would like to have the option for plugins, to have the option to override other code, or other shortcode.

Example: I have a plugin that would use this function, I would add a user_settings short code, and add my plugin stuff. Now I know we have user extended fields, and e_user.php, etc..... However, allowing for over riding the shortcode, I can also remove options in there as well such as email, etc...

The example could be a bad example, and editing shortcodes can become an issue if you sync the core site code with github/etc.....

**Comment by rica-carv** [comment]
I don't know if i understand you correctly, but currently you can override a core or plugin shortcode in the template, via theme_shortcodes.php.....

**Comment by CaMer0n** [comment]
You can also override some core functions. See the `visualcaptcha` plugin (e_module.php): 


	e107::getOverride()->replace('secure_image::r_image',   'visualcaptcha_module::blank');
	e107::getOverride()->replace('secure_image::renderInput', 'visualcaptcha_module::input');
	e107::getOverride()->replace('secure_image::invalidCode', 'visualcaptcha_module::invalid');
	e107::getOverride()->replace('secure_image::renderLabel', 'visualcaptcha_module::label');
	e107::getOverride()->replace('secure_image::verify_code', 'visualcaptcha_module::verify');

**Comment by rica-carv** [comment]
Hummmmmm.....

**Comment by Moc** [comment]
Please search for other issues on Github regarding overriding, there's documentation available there. Let us know if you have any remaining questions.
