### ISSUE TITLE
Unable to uninstall TinyMCE plugin

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2743]
I want to remove TinyMCE plugin, because I would like to use another editor.... but I can't... becuase of missing uninstall button. If I remember well, I could uninstall it a couple of months ago. What happened?! :O 

![kepernyokep_2017-07-24_22-20-03](https://user-images.githubusercontent.com/6043821/28543056-d83fc014-70be-11e7-8c5b-51662b479565.png)

**Comment by tgtje** [comment]
I confirm and checked : v2 yes (+repair); v212 yes; v214 yes;  v215 & v217 NO

**Comment by CaMer0n** [comment]
@lonalore Most likely the rewrite of the Plugin Manager in admin.

**Comment by lonalore** [comment]
I think it would be enough to set [installRequired](https://github.com/e107inc/e107/blob/master/e107_plugins/tinymce4/plugin.xml#L2) attribute to **true**. What do you think?

**Comment by CaMer0n** [comment]
Yes, as long as TinyMce is still pre-installed directly following e107 installation.

**Comment by lonalore** [comment]
TinyMce is still pre-installed according to the [default config schema](https://github.com/e107inc/e107/blob/master/e107_core/xml/default_install.xml#L221).

**Comment by CaMer0n** [comment]
@lonalore I'm closing this. It's still working as you expected?
