### ISSUE TITLE
how to move other core js to footer

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2745]
I was able to move jquery to footer by using library  this way:

```
		$libraries['cdn.jquery']['path'] = '3.1.1'; 
		$libraries['cdn.jquery']['path'] = '3.1.1';
		$libraries['cdn.jquery']['files']['js']['jquery.min.js']['zone'] = '1';
		$libraries['cdn.jquery']['files']['js']['jquery.min.js']['type'] = 'footer';
```
but these scripts are hardcoded at header:

```
e107::js('core',	'bootstrap-notify/js/bootstrap-notify.js','jquery');
e107::js('core', 	'rate/js/jquery.raty.js', 'jquery', 2);
e107::js("core",	"core/front.jquery.js","jquery",5); // Load all default functions.
e107::js("core",	"core/all.jquery.js","jquery",5); // Load all default functions

```
Maybe they should use library too (to local version) or because there is already jquery dependency set on, they shoudl be loaded after jquery (loaded already in footer)

documentation:
https://github.com/e107inc/e107/issues/1725

Thank you

**Comment by lonalore** [comment]
Yeah, they should be removed from `default_header.php` file and should be loaded via Library Manager. There is a ton of hardcoded JS/CSS file in the core. :/ It would be great to manage all these 3rd party libraries and core files in one place using Library Manager.

**Comment by rica-carv** [comment]
Just in theory, can't this do the trick:
```
e107::js('footer',	'bootstrap-notify/js/bootstrap-notify.js','jquery');
e107::js('footer', 	'rate/js/jquery.raty.js', 'jquery', 2);
e107::js("footer",	"core/front.jquery.js","jquery",5); // Load all default functions.
e107::js("footer",	"core/all.jquery.js","jquery",5); // Load all default functions
```

**Comment by Jimmi08** [comment]
@lonalore if I add bootstrap-notify.js to library_manager (just playing to understand this, f.e. bootstrap.notify), I see it correctly in preferencies, how I include (envoke) it in footer_template.php?  
I thought it would be inserted itself when type is footer. 
I know I am changing core, it's just playing because change this via theme or plugin is so powerfull that I can't believe it works. Thanks

**Comment by lonalore** [comment]
@Jimmi08 just load it with `e107::library('load', 'bootstrap.notify');`

**Comment by Jimmi08** [comment]
Perfect, it works. Thank you all
