### ISSUE TITLE
Forum - BBCode in titles, is becoming part of the URL and Breadcrumbs

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2751]
Hey guys!  It's been a while since I've been active here, but Immmmmmmmm back.  lol.  Anyway, I'm using bbcode to enhance the titles of the forum categories.  The problem is that the bb code is becoming part of the url for each category, as well as part of the breadcrumbs.

Please see the attached image.  Thanks!
![2017-07-30_103230](https://user-images.githubusercontent.com/25377269/28755570-bb7da45c-7512-11e7-9798-b9772f4af06c.png)

**Comment by Jimmi08** [comment]
You should use css for bold and green color of your titles. Or add class to title field in template (tr.yourclass in css)
or try something like .forum-parent th:first-child

**Comment by Moc** [comment]
Agree. The styling of titles and such should be done through the theme (css) not by adding bbcodes. 
Closing.

**Comment by Jimmi08** [comment]
@Moc FYI - basic core forum templates were tested and all should have unique ID, so styling via css should be possible.

**Comment by rica-carv** [comment]
But allowing bbcodes is more flexible and more directly visible, and wouldn't need more css styles & id's....
Just my two cents....
