### ISSUE TITLE
after update images are not displayed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2752]
Hi, github update on localhost (php 5.5) problem, update on live site (php7) no problem. No idea if php version is related. 

Paths looks correct, no errors in console

Cache cleared.  It looks like htaccess problem but it was just github update.  

Click on preview is correct:

![image](https://user-images.githubusercontent.com/5429548/28756809-1d52ac78-7576-11e7-8aeb-d1df2099c480.png)

![image](https://user-images.githubusercontent.com/5429548/28756830-7106ccdc-7576-11e7-9268-465e92a0bd8b.png)

![image](https://user-images.githubusercontent.com/5429548/28756848-da29bf6c-7576-11e7-9b70-f1aac8388450.png)

Sorry, too late to check more.

**Comment by Moc** [comment]
I know you said cache cleared, I assume it's both browser and e107?

**Comment by Jimmi08** [comment]
yes, because I know that there were key changes in javascript in last days. I will try fresh install (now I have access only to php7 xampp version and I am really short of time). But I could try to find reason for this (there is similar issue on e107help now) if I know where to look.  My version uses a lot of old plugins, maybe some can cause this? This issue happens if you have wrong hash folder for media/system, but site wasn't moved.

**Comment by Jimmi08** [comment]
I found it.  These lines in config file caused it:
error_reporting(E_ALL);
//error_reporting(E_ERROR, E_PARSE); 
ini_set('display_errors', 1);

After removing, images are back. Only E_ALL causes this.

**Comment by CaMer0n** [comment]
To be expected if your image data is filled with errors.
