### ISSUE TITLE
Frontend forms created from admin ui

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2754]
Is it possible to have a frontend form html generated as they are in the admin ui?
I want to give users the ability to edit some content, and i was thinking of using the same forms as they're used in the admin ui....

Is it possible? How can i anchieve that?

**Comment by CaMer0n** [comment]
Do you mean a simple form, or the whole search/edit/filter also ?

## Simple Form from admin-ui fields. 

     $frm = e107::getForm();
     $fields = array(.... ); // same array format as admin-ui  

	foreach($fields as $key=>$att)
	{
		$text .= "<div class='form-group'>
	         <label for='".$frm->name2id($key)."' class='col-sm-3 control-label'>".$att['title']."</label>
		        <div class='col-sm-9'>".
		              $frm->renderElement($key,varset($_POST[$key]),$att)
		             ."
			</div>
	      </div>";
	}

**Comment by rica-carv** [comment]
Err, my ideia is if could use the same array data for the fields from admin_config.php.
For instance, on a frontend file, make a include admi_config.php and use it's fields definition, instead of duplicating the same array for the frontend and add duplicated stuff....
Just my ideia for usefull code reuse....

**Comment by CaMer0n** [comment]
Then you can just put the array into a separate file. (called with a function) .. include the file in the admin and frontend, and then call the function inside init();

**Comment by rica-carv** [comment]
I can use init in the admin ui, but there's no init on the frontend....
On the frontend i can have anything.....
Guess i'll have to scavenge the admin_handler to find out a solution....

**Comment by CaMer0n** [comment]
include(your file)
    $fields = getFields(); 

;-)

**Comment by rica-carv** [comment]
@CaMer0n Just to be sure, the `your file` is the admin_config file?

**Comment by CaMer0n** [comment]
No, it's a new file in which you place YOUR function getFields() which returns the $fields array. 
There's nothing special or 'e107 specific' about this, it's just basic PHP.

**Comment by rica-carv** [comment]
> No, it's a new file in which you place YOUR function getFields() which returns the $fields array.

@CaMer0n I think i might explained me wrong, or probably i'm misuderstandig your proposal.
What i want is to "include" the admin_config.php file in a, let's call it, frontend.php file, and use the $fields array along with admin_ui handler to render a form so a user can edit fields in the frontend...
Ie: admin_config.php -> frontend.php

With your approach, i would have another aditional file, with the $fields array, and i would need to include it in both admin_config.php and frontend.php, right?
fields_array_file.php -> admin_config.php
fields_array_file.php -> frontend.php

**Comment by CaMer0n** [comment]
@rica-carv You understand correctly. There's no way to do what you are suggesting, because the admin-ui is exactly that - for that admin user interface.
