### ISSUE TITLE
How to force e107 to use pre-defined hash for folders?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2756]
How to force e107 to use pre-defined hash for `e107_media` and `e107_system` folders? Something global variable to set in `e107_config.php` file?

**Comment by rica-carv** [comment]
I think you can't force it, since it is supossed to be random generated for security issues....

**Comment by lonalore** [comment]
I do not have a problem with generating it randomly, but it should be stored in a global variable in `e107_config.php`. Generate the same hash on each request is having a negative impact on performance. In my opinion it should be generated once (during installation) and stored in `e107_config.php`. Furthermore, I don't know what method the generation is based on, but the 'hash' changes after migrating a site to another host. Things like this should not be allowed to happen.

**Comment by rica-carv** [comment]
Once more, it is allowed to happens as it is now, because of security reasons, i think....

**Comment by CaMer0n** [comment]
@lonalore The hash is generated from the database name if I remember well.

**Comment by lonalore** [comment]
Once more: I do not have problem with hiding files behind a folder whose name is generated randomly. (Although, it's not the best way to serve public and hide private files).

If someone hacks your site and gets the (random generated) name for your folders, how would you change the hash afterwards? :) 

I just want to have the ability to use custom 'hash' for those folders.

**Comment by lonalore** [comment]
Thank you @CaMer0n I found it:

```php
// Create a unique hash for each database configuration (multi-site support)
function makeSiteHash($db, $prefix) // also used by install.
{
	return substr(md5($db . "." . $prefix), 0, 10);
}
```
@rica-carv So it is because of multi-site support and not because of security reasons. e107 takes care of the security by using a htaccess file (I think).

**Comment by lonalore** [comment]
@CaMer0n It would be possible to override 'hash' by [changing this line](https://github.com/e107inc/e107/blob/master/e107_handlers/e107_class.php#L385) to something like this:
```php
// unique folder for e_MEDIA - support for multiple websites from single-install. Must be set before setDirs()
if (!empty($e107_config_override['site_path']))
{
	// $E107_CONFIG['site_path']
	$this->site_path = $e107_config_override['site_path'];
}
else
{
	$this->site_path = $this->makeSiteHash($e107_config_mysql_info['mySQLdefaultdb'], $e107_config_mysql_info['mySQLprefix']);
}
```
So it would be possible to define custom 'hash' in `e107_config.php` with:
```php
$E107_CONFIG['site_path'] = 'some random generated string';
```
What do you think?

**Comment by CaMer0n** [comment]
Looks good! 👍

**Comment by rica-carv** [comment]
@lonalore Don't take me wrong, i also would like to have the files on the same locations for my both sites, the development one and the live one.
Currently i have to make a copy of the development dir to the live one, and can't use direct synchronization....
This would really be a plus, so....

**Comment by lonalore** [comment]
If you override `site_path` in your `e107_config.php` file on a **Multisite**, you should define `site_path` for each website manually, as well as you define global database config for each website.
For example here is a very simple logic for handling multi-site configs:

```php
if(strpos($_SERVER['HTTP_HOST'], 'banana.com') !== false)
{
	// Global variables for database connection.
	...

	// Use custom path for e_MEDIA and e_SYSTEM files.
	$E107_CONFIG['site_path'] = 'hash for banana.com...';
}

if(strpos($_SERVER['HTTP_HOST'], 'pineapple.com') !== false)
{
	// Global variables for database connection.
	...

	// Use custom path for e_MEDIA and e_SYSTEM files.
	$E107_CONFIG['site_path'] = 'hash for pineapple.com...';
}
```
But if you leave `$E107_CONFIG['site_path']` undefined or empty, e107 will generate the hash from database name and prefix for each website.

**Comment by lonalore** [comment]
Anyway, I've never used e107 for Multisite, so I'm not sure how to configure it, but I think that should be done this way. :)
