### ISSUE TITLE
Issue: Social Login - edit profile

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2761]
Since I am an admin - I've not run into this issue, however, other have on my website - I use the social login plugin - which saves users details in the database (userlogin/password) - they have an issue when updating their profile - since social account, it has no email - and I cant disable require emails on the site. If they put in the email, the site wants them to confirm the email with their password - and since its using another format for the password than the encryption that e107 uses, adding any changes to their profile wont work unless an admin adds an email.

**Comment by arunshekher** [comment]
@LaocheXe, Just being curious. Have you got a resolution for this problem? Thanks.
