### ISSUE TITLE
Theme layout for news and extend news

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2763]
I made layout for News (without sidemenus) and layout for extend News (with sidemenus). I put it into the the xml file (part of xml file):
`<layout name='blog_news' title='Blog News' default='false'>
<custompages>/news</custompages>
</layout>
<layout name='blog_extend_news' title='Blog Extend News' default='false'>
<custompages>/news/view/</custompages>
</layout>`
URL set on admin for extend News and I can put menus to menuarea on the admin.
I think all ok but no sidemenus on the page (extend News).
The body ID blog-news on both page (News and extend News).
It seems the System ignored the blog-extend-news layout.

Full layout in xml file:
`<layouts>
    <layout name='blog_home' title='Blog Homepage' default='false'>
			<custompages>FRONTPAGE</custompages>	
		</layout>     
    <layout name='blog_full_page' title='Blog Full Page' default='false'>
      <custompages>forum</custompages>	
    </layout> 
    <layout name='blog_news' title='Blog News' default='false'>
      <custompages>/news</custompages>
    </layout>
    <layout name='blog_extend_news' title='Blog Extend News' default='false'>
      <custompages>/news/view/</custompages>
    </layout>
		<layout name='blog_default' title='Blog Default' default='true' />
  </layouts>`
How can I make this? 
Thanks!

**Comment by drasehat** [comment]
@fizi i think it's not about the xml config, but it's about admin configuration..
when you set /news to Blog Homepage layout, system will treat all URL that start with /news have Blog homepage layout..
so system will ignore another config if you have another config layout that start with /news 
cmiiw

**Comment by Jimmi08** [comment]
@drasehat but this is often problem (and news are not Frontpage).   
You need list of news without sidebar but detail of news with sidebar.  Or opposite. 

I have next problem with layout for news - if header (caption, title, date) has full width, but body (list, body, extend)  has sidebar. But list of news doesn't use tablerender() function so you can't solve this in theme.php.

**Comment by Jimmi08** [comment]
@fizi system doesn't ignore blog-extend-news layout, just first condition /news  is true for /news/view too, so this layout is used.

**Comment by CaMer0n** [comment]
@fizi @Jimmi08 Is this resolved?

**Comment by fizi** [comment]
I think I found a solution for this.

**Comment by CaMer0n** [comment]
Okay Thanks. Closing.

**Comment by Jimmi08** [comment]
@fizi How did you solve this? Could you share?

**Comment by fizi** [comment]
I put in theme.xml all variant:
`<layout name='blog_full_page' title='Blog Full Page (no Menubar)' default='false'>
      <custompages>forum news.php news/?</custompages>    
		</layout> 
    <layout name='blog_extend_news' title='Blog Extend News with Right Menubar' default='false'>
      <custompages>news/ news.php?</custompages>
    </layout>`
I don't known right or not but work. :)
