### ISSUE TITLE
not sending emails to specific email format

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2768]
Hi,
I don't know how this is called, but if email has format  name@domain.co.za  registration email never come.

User is registered, so I can test sending email from admin area. After click on Test email, blank page is result, after return to user page, 
there is error emailadreass@domain.co.za - Invalid

![image](https://user-images.githubusercontent.com/5429548/29262794-6ac111e6-80d6-11e7-813c-a812a873cfda.png)

**Comment by CaMer0n** [comment]
I'm not sure what is going on there. Did you try enabling the rolling log for more details?

**Comment by Jimmi08** [comment]
I will try. 
But this email was able to activate
 
![image](https://user-images.githubusercontent.com/5429548/30581778-9abe4fa0-9d21-11e7-90d6-88e8a9f74d82.png)

Weird thing.  If i try to send test email, i've got white page . Going back (browser button) after refresh that email is invalid. 
 trying with Firefox debugger too, just white page
![image](https://user-images.githubusercontent.com/5429548/30582140-ee8c8c18-9d22-11e7-86b2-39e2ae39702d.png) 

something in that adress?
 
![image](https://user-images.githubusercontent.com/5429548/30582207-276bdd72-9d23-11e7-8c30-42a67013c064.png)

**Comment by Jimmi08** [comment]
there is nothing in logs, max I was able to find by print_a();

![image](https://user-images.githubusercontent.com/5429548/30582838-65402232-9d25-11e7-8134-900aefcbcbc3.png)

**Comment by CaMer0n** [comment]
Email testing (with resolvers) is not done during signup afaik.

**Comment by Moc** [comment]
@CaMer0n Is there something we can do to improve error handling here?

**Comment by Jimmi08** [comment]
This is probably fixed. No issues from that time.
