### ISSUE TITLE
multicheck in news doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2769]
Latest github, but I noticed this before too. If I check more templates for news, it will save only last one.

![image](https://user-images.githubusercontent.com/5429548/29273389-660636a8-8104-11e7-9192-fb07540364fb.png)

![image](https://user-images.githubusercontent.com/5429548/29273396-6b83fc50-8104-11e7-9272-c67f69aa1d15.png)

![image](https://user-images.githubusercontent.com/5429548/29273406-6fb4810a-8104-11e7-938a-729283965ea7.png)

**Comment by Jimmi08** [comment]
@CaMer0n 

Data are sended correctly. Problem is here:
`'news_render_type'		=> array('title' => LAN_TEMPLATE, 	'type' => 'dropdown',  'data'=>'int',  'tab'=>0,  `
news_render_type is set as integer, so it saves only first value, not 0,1,2..
after changing it to str, it worked.

![image](https://user-images.githubusercontent.com/5429548/30564432-33ca3cb6-9cc5-11e7-8337-334945c5cf82.png)

Question: why is dropdown used? Checkboxes are better. Multiple dropdown doesn't work with inline editing, but checkboxes do.

**Comment by CaMer0n** [comment]
This sets the type to 'checkboxes' when in 'read' mode (which is used on the listing page) 

    'type' => 'dropdown', 'data'=>'str',  'inline'=>true, 'readParms'=>array('type'=>'checkboxes'),
