### ISSUE TITLE
Q. Why not let theme developer to decide if to use bootstrap templates?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2770]
Because this code

```
		if((strstr($data,'bootstrap.css') || strstr($data,'bootstrap.min.css')) && !defined("BOOTSTRAP")) // detect bootstrap is enabled. - used in nextprev.sc and forum currently. 
		{
			define("BOOTSTRAP", true);	
		}
```
if bootstrap.css is loaded, constant BOOSTRAP is set true. What is point to set this in theme too?   

I would prefer just let this constant to be set in theme.php.  

in e107_class.php

**Comment by Moc** [comment]
@CaMer0n Your thoughts please :)

**Comment by CaMer0n** [comment]
@Jimmi08 If I remember well, this code is reading the theme.xml file and enabling BOOTSTRAP, so the theme developer still decides, only via theme.xml and not theme.php

**Comment by Jimmi08** [comment]
Just note. After removing it from theme.xml, you need to use:
`define("BOOTSTRAP", 	false);`
in theme.php
