### ISSUE TITLE
Error with NoFollow-Plugin for v1 in v2

### ISSUE THREAD

**Issue by AlexL777** [e107inc/e107#2771]
Hello Developers,

I just upgraded from 2.1.5 to the version 2.1.6. In the Backend I still had the noFollow Plugin for v1 installed and that had to be updated.

Now I have in the front end this Error and do not know more.

`Fatal error: Call to a member function nofollow() on null in /xxxxxxxxxxxxxxxxxxxx/e107v2.wpzweinull.ch/e107_handlers/e_parse_class.php on line 1928`

I have already deleted all directories in the FTP Account completely, uploaded, Database Backup of yesterday, but nothing helps.

Do you have a tip for me?

Thanks in advance.

**Comment by arunshekher** [comment]
Hi @AlexL777,
If I understand you correctly you were using NoFollow for e107 v0.7.xx right? Can you tell which version was it v0.3 ?

As a first step in troubleshooting could you check if you have the preference `'tohtml_hook' => 'nofollow'` is still present in your SitePrefs in the `'e107_core'` table. If yes remove that and clear all cache and see.

Its strange that you did not face any issues with it in e107 v2.1.5

As the plugin NoFollow is not affiliated or part of e107 repository I guess you could post future issues [here](https://github.com/arunshekher/nofollow) or at [e107help.org](https://e107help.org/)

**Comment by AlexL777** [comment]
Hello ,

Thank you for posting the issue here. I have now removed everything with "nofollow" in the mentioned database table and still no success.

At https://e107v2.wpzweinull.ch unfortunately the same error.

What else can I do to correct the error or to generate more helpful error messages?

It was so that I used this old NoFollow plugin in e107 v2.1.5. But after the upgrade to v2.1.6 came this error.

The error is from the same file e_parse_class.php.

Maybe you can help me.

Thank you!

**Comment by arunshekher** [comment]
Just to be sure, did you have an entry like `'tohtml_hook' => 'nofollow'` in your **SitePrefs** in `e107_core` table ??

If that entry was there in SitePrefs and removing that and clearing cache didn't fix the issue try to remove it manually from this file in this path, as well.

`e107_system/{xxxxx}/cache/content/S_Config_core.cache.php`

Where {xxxxx} is sitehash and it differs with each installation.

Optionally you might want to empty the `e107_value` column of `SitePrefs_Backup` row in `e107_core` table

**Comment by arunshekher** [comment]
I see your site is loading now but you probably removed some prefs related to bootstrap3 theme as well I believe.

**Comment by AlexL777** [comment]
Yes, the website loads again and I had the theme "Voux" before. Also, I have restored the site from older MySQL / FTP backup and reinstalled it.

Unfortunately, it does not function with the media files, that is, these were no longer found. Since the theme has its own settings and demo content, I will probably have to re-adjust all content.

Also, I saw that this noFollow plugin is classified as v0.3 for e107 v2.1.6 as compatible. The noFollow plugin I have updated and the previous error is now gone.

Ok, then the problem has turned out to be solved for me and I will then set up the website again.

Thank you for your time and the important tips. At least I know now, where I can change something in the database, if times is not so.

**Comment by arunshekher** [comment]
NP, The ability to override sitehash/path was recently added to e107. Utilizing that feature might help you solve your media loading issues. Please [read this thread](https://github.com/e107inc/e107/issues/2756) to get some idea about it.

**Comment by arunshekher** [comment]
@AlexL777, Could you please close this issue. Please post future issues [here](https://github.com/arunshekher/nofollow/issues).

**Comment by arunshekher** [comment]
Thank you.
