### ISSUE TITLE
Custompage img responsive

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2772]
I put the image into the custompage with bbcode.
The cource of the image not responsive:
`<img class="img-rounded rounded bbcode bbcode-img bbcode-img-page" src="/testsite/media/img/500x0/2017-08/article1.jpg" alt="Article1" srcset="/testsite/media/img/1000x0/2017-08/article1.jpg 1000w" width="500">`
Originally the ddcode put this code:
`[img style=width:500px;]{e_MEDIA_IMAGE}2017-08/article1.jpg[/img]`
In this way source:
`<img class="img-rounded rounded bbcode bbcode-img bbcode-img-page" src="/testsite/media/img/500x0/2017-08/article1.jpg" alt="Article1" srcset="/testsite/media/img/1000x0/2017-08/article1.jpg 1000w" style="width:500px;" width="500">`
Width appears two times in code.
And I don't put class for the image.

**Comment by CaMer0n** [comment]
`.bbcode-img { max-width:100%}`

**Comment by Jimmi08** [comment]
@Moc  This can be closed

**Comment by fizi** [comment]
Ok that closed but not solved (I think), because if I add max-width: 100% but the width: 500px - the image not will wider than 500px and not responsive if the screen smaller.

**Comment by Jimmi08** [comment]
I dont think you can use 500px width if you want responsive images. Responsive images fill container, just max-width. Just copy the same css for your images as img-responsive use. If you want something like this, you could use media-queries.
