### ISSUE TITLE
problem with sync with github 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2777]
First sync left this in temp folder:
![image](https://user-images.githubusercontent.com/5429548/29997623-ff0287c2-9017-11e7-9781-30d84a438e46.png)

After next try of sync, result is  "blank" page (no white)
![image](https://user-images.githubusercontent.com/5429548/29997627-1618b5a8-9018-11e7-9978-f087a6aa284f.png)

After manual deleting of content of temp folder, sync is finished correct way.

**Comment by Moc** [comment]
I think from the screenshot that a fatal error is thrown and therefore the rest of the page is not displayed. 
Can you reproduce the issue? Are errors shown?

**Comment by Jimmi08** [comment]
this was solved in other issue
