### ISSUE TITLE
Statistics logging plugin throws fatal error 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2779]
In chrome localhost version normally works (log in user)
Using Firefox evokes this error:  (with debugger on + off)

`Fatal error: require(): Failed opening required 'e107_system/189189b5b6/logs/logi_208.2016.php' (include_path='.;C:\xampp\htdocs\e107sk2.1.6;.;C:\xampp\php\PEAR') in C:\xampp\htdocs\e107sk2.1.6\e107_plugins\log\consolidate.php on line 167`

Folder looks like this:
![image](https://user-images.githubusercontent.com/5429548/30002536-c50125f8-90ab-11e7-9add-088ba3c8bae1.png)

After manually renamed logp file to logi, site works. 

Latest Github, php 5.6

**Comment by tgtje** [comment]
Just as comment : find it strange that you have old log files, is there something wrong when transfering data to database?  (no other way to describe) log file should transfer data to... and than be erased...(afaik this has always been the case ...(my logs folders running xampp are empty) And the one you address is a very old one (2016)

**Comment by Jimmi08** [comment]
On live site there are only actual files. 
![image](https://user-images.githubusercontent.com/5429548/30002849-996002c2-90b3-11e7-8826-947c4f323a18.png)

Used local version maybe 3 months, no problem - weird it that it was looking for old file. Maybe that I use more than one browser as mainadmin? I really can't say.   I just wanted to note this.

**Comment by tgtje** [comment]
The error does seem weird, but than again, if it was not present, no error. I (suppose move a site to diff. server) i always delete them (nowadays)... They never seem to have an impact (and should long be part of dbase) when not present, but yes.. sometimes do have an impact (when  finding error cause like no display etc.. if present).. Cause: will be something it wants to include from that file, but throws stuff in which triggers again something else, no longer present or so... ) Trying to describe what i experience when such happens...

**Comment by Moc** [comment]
I have had two reports lately with the same issue. Needs to be looked into.

**Comment by CaMer0n** [comment]
@Jimmi08 @tgtje @Moc Please retest with the committed changes. Thanks.

**Comment by Jimmi08** [comment]
2 days ago I wasn't able to update on localhost, yesterday update without problems. So for me solved.

**Comment by tgtje** [comment]
Info: i can not retest such a setting as i did not have this issue presently. The other times i had similar is quite a while ago..So have to assume all is correct (or solved with commit).

**Comment by CaMer0n** [comment]
Thank you both. Will close, but please re-open if it becomes necessary.
