### ISSUE TITLE
Q. How to fix something like this? $parm insert text Array 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2780]
This shortcode:
```
	/**
	 * Display class for event display block - to manage expansion/contraction
	 * When displaying a single event, or a single day's events, block to be expanded
	 * For event lists, block to be contracted
	 * 
	 * @param int $param - optional supplementary list of classes to apply
	 *
	 * @return string - 
	 */
	public function sc_ec_event_displayclass($parm='')
	{	
		if (($this->ds=='event') || ($this->ds=='one'))
		{	// Single event or one day's events - block expanded
			return " class='{$parm}'";
		}
		return " class='e-show-if-js e-hideme {$parm}'";	// Block contracted
//		return " class='e-hide-if-js e-showme {$parm}'";	// Block contracted
	}
```

insert this if no parameter is used:
![image](https://user-images.githubusercontent.com/5429548/30019880-4cdf9566-9162-11e7-84cd-66037de78c71.png)

How to fix it?  Tested on php 7.  Thanks

**Comment by rica-carv** [comment]
`return ($parm?" class='{$parm}'":"")`

**Comment by Jimmi08** [comment]
@rica-carv 
Its called this way (for me no parameters, if I add some f.e =bg-primary, it works)

`<div id='{EC_EVENT_ID}' {EC_EVENT_DISPLAYCLASS} style='padding-top:10px; padding-bottom:10px; text-align:left;'>`

so for me no parameter is send, and somehow $parm is empty array (maybe this is legacy thing, I really don't know).

**Comment by rica-carv** [comment]
@Jimmi08 If that's it what it cames with `$parm`, do a empty check on it:
```
return (empty($parm)?"":" class='{$parm}'")
}
return " class='e-show-if-js e-hideme {".(empty($parm)?"":$parm)."}'";
```

**Comment by Jimmi08** [comment]
@rica-carv thank you, fixed.

**Comment by rica-carv** [comment]
Glad i could help....

**Comment by Jimmi08** [comment]
Or $parms = eHelper::scParams($parm);
