### ISSUE TITLE
Forum rules page, rendering link in title goes wrong

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#2782]
Enhancement / "small bug"
I was looking for a possibility to add the forum rules as a link to the forum. Imho that should be visible in the small links regarding posting below. I tried to make a page and a link to that page in the title of the main forum. But `<a href="something">` is generated as `mysite.com/"something` which generates a 404. The first is an enhancement request. The second looks like an error to me. 

Of course I can create a sticky posts etc. So there are loads of alternatives. But I think it would be nice to have them under a link on the forum page.

**Comment by rica-carv** [comment]
Working from memory here, i think you can add that link customizing the forum template in your theme....

**Comment by aducom** [comment]
Yes, that's a solution too. Loads of possiblities ;-)

**Comment by rica-carv** [comment]
That's the "beauty" of e107, you can customize almost anything without touching the core files...
E107 provides you the working core files, and it's flexibility allows you to customize everything you need... or almost...

**Comment by aducom** [comment]
Indeed.

**Comment by Moc** [comment]
- You cannot post links in the title of a forum category or topic 
- Forum rules is a core feature and in the default template there should automatically a link to the forum rules if I remember correctly (same for forum statistics if enabled. 

Closing for now, let us know if you have any more questions.
