### ISSUE TITLE
problem with spam users 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2783]
I don't know if this is related to latest update or not.   I use recaptcha plugin and it works.  I have notification about new user created. After using signup.php page notification looks like this (it's correct sign up):
![image](https://user-images.githubusercontent.com/5429548/30252968-ff8fe1c0-967b-11e7-8212-99f32ad20469.png)

But maybe week or two ago spam users started with this notification:
![image](https://user-images.githubusercontent.com/5429548/30252976-246ba7ae-967c-11e7-9c04-747f6ebe65c1.png)

As you see, it's a bit different (order of fields is different). How they are able to register? I have set email verification, and I just set off Auto-login. These users are able to be activated. 

Thanks

**Comment by Jimmi08** [comment]
I switched to core captcha. And tried this:

Form:

![image](https://user-images.githubusercontent.com/5429548/30288970-d6cb4b9e-972a-11e7-8158-68d7afa9afb6.png)

If I remove captcha field on Frontend 
![image](https://user-images.githubusercontent.com/5429548/30289055-242caba8-972b-11e7-9c26-229301de23de.png)

and I fill form (no captcha)
![image](https://user-images.githubusercontent.com/5429548/30289088-4198859a-972b-11e7-9a88-65e0688d6dbd.png)

form is submitted
![image](https://user-images.githubusercontent.com/5429548/30289102-49e5e292-972b-11e7-8008-78a68dcdad76.png)
and notification looks the same as with spam users:
![image](https://user-images.githubusercontent.com/5429548/30289132-5b71c5f8-972b-11e7-9f96-ad06a0d88709.png)

I tried this on other site with captcha and it wasn't succesful.

**Comment by Moc** [comment]
Sounds like the signup procedure is missing a check somewhere.

**Comment by rica-carv** [comment]
You can also use an additional "line of defense".
I, with v1.x was using ZBlock, now i'm using CIDRAM, and just let me tell you, spammers and fake registrys simply are gonne....

**Comment by CaMer0n** [comment]
@Jimmi08 on Line 599 of signup.php. 
Try changing it from: 

	if (isset($_POST['rand_num']) && $signup_imagecode)

to

	if ($signup_imagecode)

Does it help?

**Comment by Jimmi08** [comment]
@CaMer0n Yes, it helped.  

Only no Error message is displayed (but error about duplicate email adress is displayed) - but $extraErrors is filled correctly, only not displayed.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! Please update and let me know if it fixed it.

**Comment by Jimmi08** [comment]
Works. Thank you
