### ISSUE TITLE
Blank Menu - (newforumposts_main) plugin

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2785]
Hello all,

i have a question about the newforumposts_main plugin:

since i have updated on php 7.0 (from php 5), my newforumsposts menu is empty.
no errors found, anyone have idea to fix that?

https://github.com/e107inc/e107/blob/master/e107_plugins/newforumposts_main/

— Killer0561

**Comment by Killer0561** [comment]
Screenshot

![24190f77-1ad2-482d-a335-13df919f1ec4](https://user-images.githubusercontent.com/16360582/30516518-b20d74d8-9b41-11e7-91bb-7b3419ea71c1.jpeg)

— Killer0561

**Comment by Moc** [comment]
Please use the debug mode to find any warnings or errors: https://e107.org/developer-manual/getting-started/debugging

**Comment by Jimmi08** [comment]
@Killer0561 I meant this screen:
![image](https://user-images.githubusercontent.com/5429548/30519001-83190b4c-9b8c-11e7-8a27-4ca5273129a8.png)

**Comment by tgtje** [comment]
@Jimmi08  That (EDIT) mode screen are all fields  **to be filled** in.. they are empty

**Comment by Jimmi08** [comment]
@tgtje it was my mistake, it was menu from forum plugin that worked for me, not setting is needed in fact, it works.  There is different configuration window for that plugin. I asked for admin part, not for frontend screen :)

**Comment by tgtje** [comment]
Ok, the admin configure part has to be called from plugin screen GEAR icon (just info) (would be a (bs3) balck page with only some fields...

**Comment by Jimmi08** [comment]
That plugin doesnt work under php 7

Reasons:
```
$text = preg_replace("/\{(.*?)\}/e", '$\1', $NEWFORUMPOSTSTYLE_HEADER);
$text .= preg_replace("/\{(.*?)\}/e", '$\1', $NEWFORUMPOSTSTYLE_MAIN);
$text .= preg_replace("/\{(.*?)\}/e", '$\1', $NEWFORUMPOSTSTYLE_FOOTER);
```

To get it work under php 5.6 , $pref was needed to add
`global $sql, $ns, $pref;`

**Comment by tgtje** [comment]
Stiil a strange thing @Jimmi08  (although local) it works out of the box (for me) in both versions,...

**Comment by tgtje** [comment]
Since it works for me did some more searching maybe this is happening there ? 

php 7.0.0 | Support for the /e modifier has been removed. Use preg_replace_callback() instead.

(do have no testcase)

**Comment by Jimmi08** [comment]
@tgtje I wrote this 2 comments above.  This is way how I fixed this, but I am sure its not correct way, just workaround. 
 
![image](https://user-images.githubusercontent.com/5429548/30644733-a76b5296-9e13-11e7-8445-a7941d7a83b6.png)

**Comment by Killer0561** [comment]
Its not the same, many features are missing. I am like more the newforumsposts_main plugin.

— Killer0561

**Comment by CaMer0n** [comment]
@Killer0561 Thanks. Which features are missing? (it may be easier to add them)

**Comment by Killer0561** [comment]
Missing or required (in order left to right in table):

— Icon (new Post, no new post, popular, etc.)
— Thread Name + Forum Name (Poster)
— Poster Name (Who wrote it) + Date
— Views (Thread) Counter
— Replays (Thread) Counter
— Last Poster (Who wrote it) + Date

This my template for good view too see new posts in forum.

— Killer0561

**Comment by rica-carv** [comment]
All that info in a menu? Isn't that a copy of the forum template?

**Comment by CaMer0n** [comment]
@Killer0561 I have fixed some of the shortcodes. 
Please make sure you have the **main** template configured in _Menu-Manager_ for the New Forum Posts Menu. (forum plugin) 

![new_forum_posts_menu](https://user-images.githubusercontent.com/2825679/30761754-43b6ef12-9f94-11e7-80cb-30a8a1292721.png)

**Comment by Killer0561** [comment]
Thanks, the newforumposts_menu works perfect.
