### ISSUE TITLE
single shortcodes with old fontawesome code

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2789]
there are old single shortcodes (used in forum plugin too)

```
return $tp->parseTemplate("{PRINT_ITEM=".LAN_GLOSSARY_EMAILPRINT_02."^plugin:glossary.{$glo_id}}");
return $tp->parseTemplate("{EMAIL_ITEM=".LAN_GLOSSARY_EMAILPRINT_01."^plugin:glossary.{$glo_id}}");
return e107::getParser()->parseTemplate("{PRINT_ITEM=" . LAN_FORUM_2045 . "^plugin:forum.{$this->postInfo['post_thread']}}");
return e107::getParser()->parseTemplate("{EMAIL_ITEM=" . LAN_FORUM_2044 . "^plugin:forum.{$this->postInfo['post_thread']}}");

```
those shortcodes returns:
```
$img = "<i class='icon-envelope'></i>";
$img = "<i class='icon-print'></i>";
```	

It's code from old Fontawesome, so it displays nothing.

**Comment by CaMer0n** [comment]
@Jimmi08 Did this commit fix it?

**Comment by Jimmi08** [comment]
@CaMer0n 
Why did you use glyphicons and not FontAwesome?  I mean - there are not used in bootstrap 4 and FontAwesome is. 
I like more solution for comment icon - if it is not defined in theme, then it uses 
e107::getParser()->toGlyph('fa-comment'));
Boostrap themes could use images too, not only icons.

**Comment by rica-carv** [comment]
@Jimmi08 I've proposed that ideia long ago, i can't find it now... Regular png or svg icons could / should be allowed to be used with bootstrap (my theme repalces all fontawesome with png's, for instance...)
By the way, BS4 can also use any icon font you want: Octicons, Fontawesome, etc...

**Comment by CaMer0n** [comment]
@Jimmi08 Right now (and before) the code checks for bootstrap, but not for FontAwesome. This is why I used glyphicon. However I'm not opposed to changing it to FA if you think its easier for theme developers.

**Comment by rica-carv** [comment]
And why not let admin install the bootstrap font, instead of "forcing" the use of fontawesome?

**Comment by CaMer0n** [comment]
e107 needs a default. See landingzero/plugin.xml for adding custom gyphs.

**Comment by rica-carv** [comment]
Indeed, but the default should / could be defined by the admin, ie at install time or after....

**Comment by Jimmi08** [comment]
@rica-carv I agree with @CaMer0n  on this.  You should be able to override settings in theme, but default font should be boostrap font.

I don't know if I can override single shortcode in theme 

Problem is that you can use image or icon - different html markup.  And it has nothing with BOOTSTRAP (you can have bootstrap theme with images and not bootstrap theme with icons)

So solution is to have constant ICONMAIL in theme and shortcode detect somehow that it is image use 
```
//default $icon = ... email.png";  
$img = "<img src='".ICONMAIL."' style='border:0' alt='{$parms[0]}' class='icon S16 action' />";
```
 or 
```
//default:  $img = e107::getParser()->toGlyph('fa-envelope');
$img =ICONMAIL;

```
So only defaults depends on BOOTSTRAP...

**Comment by Jimmi08** [comment]
Solved
