### ISSUE TITLE
Custom theme page_template wrapper issue

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2792]
Wrappers in custom theme page_template.php file aren't loaded / used.
It's always used the default wrapper present in core page_template.php file....

**Comment by CaMer0n** [comment]
Please share the custom page_template.php code.

**Comment by rica-carv** [comment]
It's the same as [core](https://github.com/e107inc/e107/blob/master/e107_core/templates/page_template.php) with just this changes in lines 25 & 26:
```
/*
$sc_style['CPAGENAV|default']['pre'] = '<div class="f-right pull-right col-md-3">';
$sc_style['CPAGENAV|default']['post'] = '</div>';
*/
$sc_style['CPAGENAV|default']['pre'] = '<div class="col-md-12">';
$sc_style['CPAGENAV|default']['post'] = '</div>';

$PAGE_WRAPPER['CPAGENAV'] = "<ul>{---}</ul>";
$PAGE_WRAPPER['default']['CPAGENAV'] = "<ul>{---}</ul>";
$PAGE_WRAPPER['default']['body']['CPAGENAV'] = "<ul>{---}</ul>";
```

None of those custom wrappers work....

**Comment by CaMer0n** [comment]
@rica-carv What value does the CPAGENAV shortcode return to the template?

**Comment by rica-carv** [comment]
@CaMer0n Debugging it, it returns this:
```
Array
(
    [class] => cpage_shortcodes
    [function] => sc_cpagenav
    [path] => (already loaded)
)
```

**Comment by CaMer0n** [comment]
@rica-carv I mean, what does it output.. Does it output some html? If it returns nothing then there will be no wrapper.

**Comment by rica-carv** [comment]
@CaMer0n Yes, it returns the HTML it's supposed to return...

**Comment by rica-carv** [comment]
@CaMer0n I just found out what's the issue.... 
If i use `{CPAGENAV|default}` on the custom theme template, it always renders the shortcode wrapped int the default core wrapper, ignoring the one on the custom theme template.
If i use `{CPAGENAV}`, it will use the custom theme template wrapper...

A little weird, but i supposse this is the intended behavior...
