### ISSUE TITLE
500 Error on front page and admin

### ISSUE THREAD

**Issue by JPLiggett** [e107inc/e107#2793]
I was working on the welcome page that had some nested tables, and after the last save, every page is not reachable, throwing 500 internal server error.  I've checked the logs, used boot.php, tried different PHP versions and re-installed 2.1.6.  I tried to locate the welcome page in sql but I didn't see them in the pages or menu tables.  I tried removing the plug-ins, replacing htaccess and checked the file permissions. 
Any advice would be greatly appreciated.

**Comment by Jimmi08** [comment]
Check in database and file with banned IPs,  if your IP is not banned.  Welcome message is in generic table if I am not mistaken.

**Comment by JPLiggett** [comment]
Banned IP is empty, I found the latest welcome page in the generic table, I tried updating the html via phpadmin...NG, so I deleted the wmessage row in sql.....still 500

**Comment by Jimmi08** [comment]
banned IPs is on 2 places...  is it public adress or localhost?

**Comment by JPLiggett** [comment]
the banlist table is empty...I have to use direct sql, the e107 UI is thowing the 500 on the home page and admin.

**Comment by Jimmi08** [comment]
second place: (system folder/hash/cache/)
![image](https://user-images.githubusercontent.com/5429548/30710066-9f1131c8-9f04-11e7-8c7d-db1c388bfd24.png)

**Comment by JPLiggett** [comment]
the folder on my site is laid up like this, /public_html/e107_system/b80379a785/cache, and it has the subfolders like your example, but no php files.

**Comment by Jimmi08** [comment]
So -i am sorry, I cant help more.  Try gitter.

**Comment by JPLiggett** [comment]
Thank you for trying Jim

**Comment by CaMer0n** [comment]
I'm in the chatroom if you need help. In the meantime, I would check the apache logs.

**Comment by JPLiggett** [comment]
Thanks for Camerons expert help, found files missing and version anomolies, Cameron validated the files and its all good to go.
