### ISSUE TITLE
Feature request - newforumposts_menu

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2802]
Hello again,

I need a function which gives you an alternative text, if there are no last answers and the date is still unknown from the last poster.

Here is an example:

else
{
$TOPIC_LASTPOST_AUTHOR = 'No posts';
$TOPIC_LASTPOST_DATE = 'Date unknown';
}

Thanks for this possible feature!

— Killer0561

**Comment by rica-carv** [comment]
There's always the possibility of rewriting the shortcode at theme level, so....

**Comment by Killer0561** [comment]
Is there already news?

— Killer0561

**Comment by CaMer0n** [comment]
@Killer0561 Untested, please let me know how it goes. Thanks.

**Comment by Killer0561** [comment]
It works, great work @CaMer0n !
This must be changed (hotfix for TOPIC_LASTPOST_AUTHOR):

![6476c099-735f-4155-9f1a-9766a76bcb44](https://user-images.githubusercontent.com/16360582/31580512-1b70b784-b152-11e7-801d-ea9e08872c7a.jpeg)
