### ISSUE TITLE
prefs with value 0 in plugin.xml are not saved 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2803]
Probably php7 issue:
this setting:
![image](https://user-images.githubusercontent.com/5429548/31115605-4c015ee0-a823-11e7-957a-f7ac58892f09.png)
is saved as

![image](https://user-images.githubusercontent.com/5429548/31115626-5f0c3820-a823-11e7-83b1-05f6ad5e6d3c.png)

and then no value is set in admin_ui
![image](https://user-images.githubusercontent.com/5429548/31115653-73f88fcc-a823-11e7-93f9-2c7ec47fe1c4.png)

**Comment by rica-carv** [comment]
I have this same issue in PHP 5.6.....

**Comment by CaMer0n** [comment]
@Jimmi08 @rica-carv please re-open if necessary.
