### ISSUE TITLE
Setting SEF for News Listing doesn't work

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#2804]
When I set the News preferences to List news items and I set Settings > URL Configuration > News > 
Friendly: /news/news-title, the /news URL shows the news as expected, in a List Form.  

However, when I set Settings > URL Configuration > News > Friendly: /news/news-category/news-title, the news page doesn't show it in the List mode even though the News preferences are set to do so.

**Comment by CaMer0n** [comment]
Please check your news categories have SEF values.

**Comment by Moc** [comment]
@BigBoiJefe Any feedback? :)

**Comment by BigBoiJefe** [comment]
I'm confirmed that this is working now.  While the news category had SEF values it could have just been an issue with the cache, or my brain.  ;)
