### ISSUE TITLE
Unable to post News after 2.1.7 (git) update

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#2805]
After updating from 2.1.6 (git) to 2.1.7 (git)

Site Theme RideBlue2 (have tried baba as well to see if it is a theme issue)
PHP Version 7.0.19-1 
MySQL 10.1.26-MariaDB-0+deb9u1

After syncing with github I have updated the database core functions. Subsequently, I cannot create a news item and get the error message 'SQL insert error' I can update previous news items and all other functions appear to be OK. All database checks you offer from the admin menu are OK.

I have to restore a backup of 2.1.6 (git) to post news again.

Two other e107 sites of mine with very little content have no problems when creating a news item. The site in question that throws an SQL insert error has 2500+ news items (if that's of any help)

**Comment by CaMer0n** [comment]
@NZCyrus It sounds like your news database table upgrade failed. Please check /e107_admin/db.php?mode=verify_sql

**Comment by NZCyrus** [comment]
Thanks for your response. Yes, I had checked all the functions including 'check database validity' after updating the db.

I restored a backup of 2.1.6 (git) and tried again. This time I checked database validity (verify sql) before updating the db and got these errors.

![screenshot_2017-10-08_08-27-04](https://user-images.githubusercontent.com/7886491/31311290-b372c92a-ac05-11e7-9ba9-aa3c5c7e32e6.png)

I selected and fixed those items, after which the database showed as updated. 

However, on attempting to create a new news item, I still get the 'SQL insert error' 

![screenshot_2017-10-08_08-56-32](https://user-images.githubusercontent.com/7886491/31311336-dccacd58-ac06-11e7-986c-e748f85c4553.png)

**Comment by Moc** [comment]
Enable debug mode with SQL options (see e107 Dev manual). It should show more detailed information that will help us determine the cause of the error.

**Comment by NZCyrus** [comment]
Success
Executed Update core database structure
×
System Debug
Update required in update_routines.php on line 550 (Database Tables require updating: news, news_category)

Array
(
    [news] => Array
        (
            [_status] => error
        )

    [news_category] => Array
        (
            [_status] => error
        )

)

Successfully updated [ALTER TABLE `e107_news` ADD `news_template` VARCHAR(50) NOT NULL DEFAULT '']
Successfully updated [ALTER TABLE `e107_news_category` ADD `category_template` VARCHAR(50) NOT NULL DEFAULT '']
Update required in update_routines.php on line 550 (Database Tables require updating: news, news_category, admin_log, audit_log, banlist, comments, core_media, core_media_cat, cron, dblog, generic, links, mail_recipients, mail_content, menus, online, page, page_chapters, plugin, rate, submitnews, tmp, upload, user, userclass_classes, user_extended, user_extended_struct, banner, featurebox, featurebox_category, gsitemap, links_page_cat, links_page, logstats, rss, tagwords)

**Comment by NZCyrus** [comment]
**When I try to create a new 'News item'**

Error
SQL Insert Error
×
System Debug
Admin-ui Trigger fired: admin_news_create
SQL Error #23000: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'news_template' cannot be null
SQL QRY Error

Array
(
    [_FIELD_TYPES] => Array
        (
            [news_id] => int
            [news_category] => int
            [news_title] => str
            [news_summary] => str
            [news_template] => str
            [news_render_type] => str
            [news_body] => str
            [news_thumbnail] => str
            [news_sef] => str
            [news_meta_keywords] => str
            [news_meta_description] => str
            [news_allow_comments] => int
            [news_start] => int
            [news_end] => int
            [news_author] => str
            [news_datestamp] => int
            [news_class] => str
            [news_sticky] => int
            [news_comment_total] => int
            [news_extended] => str
        )

    [data] => Array
        (
            [news_id] => 
            [news_category] => 2
            [news_title] => checking again
            [news_summary] => 
            [news_template] => 
            [news_render_type] => 0
            [news_body] => [html]<p>checking again</p>[/html]
            [news_thumbnail] => ,,,,
            [news_sef] => checking-again
            [news_meta_keywords] => 
            [news_meta_description] => 
            [news_allow_comments] => 0
            [news_start] => 0
            [news_end] => 0
            [news_author] => 1
            [news_datestamp] => 1507410539
            [news_class] => 0
            [news_sticky] => 0
            [news_comment_total] => 0
            [news_extended] => 
        )

)

**Comment by CaMer0n** [comment]
@NZCyrus Please open e107_core/sql/core_sql.php and replace the 2 sections at line 300 with these lines. 

```
CREATE TABLE news (
  news_id int(10) unsigned NOT NULL auto_increment,
  news_title varchar(255) NOT NULL default '',
  news_sef varchar(200) NOT NULL default '',
  news_body longtext NOT NULL,
  news_extended longtext NOT NULL,
  news_meta_keywords  varchar(255) NOT NULL default '',
  news_meta_description text NOT NULL,
  news_datestamp int(10) unsigned NOT NULL default '0',
  news_author int(10) unsigned NOT NULL default '0',
  news_category tinyint(3) unsigned NOT NULL default '0',
  news_allow_comments tinyint(3) unsigned NOT NULL default '0',
  news_start int(10) unsigned NOT NULL default '0',
  news_end int(10) unsigned NOT NULL default '0',
  news_class varchar(255) NOT NULL default '0',
  news_render_type varchar(20) NOT NULL default '0',
  news_comment_total int(10) unsigned NOT NULL default '0',
  news_summary text NOT NULL,
  news_thumbnail text NOT NULL,
  news_sticky tinyint(3) unsigned NOT NULL default '0',
  news_template varchar(50),
  PRIMARY KEY  (news_id),
  KEY news_category  (news_category),
  KEY news_start_end (news_start,news_end),
  KEY news_datestamp (news_datestamp),
  KEY news_sticky  (news_sticky),
  KEY news_render_type  (news_render_type),
  KEY news_class (news_class)
) ENGINE=MyISAM;


# --------------------------------------------------------

#
# Table structure for table `news_category`
#

CREATE TABLE news_category (
  category_id tinyint(3) unsigned NOT NULL auto_increment,
  category_name varchar(200) NOT NULL default '',
  category_sef varchar(200) NOT NULL default '',
  category_meta_description text NOT NULL,
  category_meta_keywords  varchar(255) NOT NULL default '',
  category_manager tinyint(3) unsigned NOT NULL default '254',
  category_icon varchar(250) NOT NULL default '',
  category_order tinyint(3) unsigned NOT NULL default '0',
  category_template varchar(50),
  PRIMARY KEY  (category_id),
  KEY category_order (category_order)
) ENGINE=MyISAM;
# --------------------------------------------------------
```

Then run the database verification again, modify as necessary and try inserting a new record again. 
Thank you and sorry for the trouble.

**Comment by NZCyrus** [comment]
Did what you suggested above. I can now create new news posts, thank you. However the database validity constantly shows those two errors in the image I posted earlier, even though I have attempted to fix them with the option.

Also, the database constantly asks me to update on fresh logins, even though I have done so, and still shows as requiring an update.

**Comment by NZCyrus** [comment]
All OK now, thank you :) The missing field has been included.

**Comment by NZCyrus** [comment]
Sorry to bring this up again. After doing a git update now (Latest commit c37852f) my core database functions do not pass and I cannot update the database. 

Database Utilities - SQL Verification - core > 2 tables have problems

This time it shows as follows: (with the opposite mismatch to my original image earlier in the post. However, with your earlier corrections above, I am able to create new news items)

![screenshot_2017-10-10_17-36-30](https://user-images.githubusercontent.com/7886491/31369865-d5ba00f4-ade3-11e7-87f0-3b76c3b66ca7.png)

When I try to fix the selected problems via the browser option:

System Debug
Successfully updated [ALTER TABLE `e107_news` CHANGE `news_template` `news_template` VARCHAR(50) ]
Successfully updated [ALTER TABLE `e107_news_category` CHANGE `category_template` `category_template` VARCHAR(50) ]

When trying to update the database:

System Debug
Update required in update_routines.php on line 550 (Database Tables require updating: news, news_category)

Array
(
    [news] => Array
        (
            [_status] => mismatch
        )

    [news_category] => Array
        (
            [_status] => mismatch
        )

)

Successfully updated [ALTER TABLE `e107_news` CHANGE `news_template` `news_template` VARCHAR(50) ]
Successfully updated [ALTER TABLE `e107_news_category` CHANGE `category_template` `category_template` VARCHAR(50) ]
Update required in update_routines.php on line 550 (Database Tables require updating: news, news_category, admin_log, audit_log, banlist, comments, core_media, core_media_cat, cron, dblog, generic, links, mail_recipients, mail_content, menus, online, page, page_chapters, plugin, rate, submitnews, tmp, upload, user, userclass_classes, user_extended, user_extended_struct, banner, featurebox, featurebox_category, gsitemap, links_page_cat, links_page, logstats, rss, tagwords)


However, on going back to check core functions of the database validity, it shows the same error again and the database has the orange update button to Update core database structure, stating, 'Update required in update_routines.php on line 550 (Database Tables require updating: news, news_category).'

![screenshot_2017-10-10_17-59-57](https://user-images.githubusercontent.com/7886491/31370040-0a433e52-ade5-11e7-81a7-cbb020af05d8.png)

**Comment by CaMer0n** [comment]
@NZCyrus Please try with this: 

```
CREATE TABLE news (
  news_id int(10) unsigned NOT NULL auto_increment,
  news_title varchar(255) NOT NULL default '',
  news_sef varchar(200) NOT NULL default '',
  news_body longtext NOT NULL,
  news_extended longtext NOT NULL,
  news_meta_keywords  varchar(255) NOT NULL default '',
  news_meta_description text NOT NULL,
  news_datestamp int(10) unsigned NOT NULL default '0',
  news_author int(10) unsigned NOT NULL default '0',
  news_category tinyint(3) unsigned NOT NULL default '0',
  news_allow_comments tinyint(3) unsigned NOT NULL default '0',
  news_start int(10) unsigned NOT NULL default '0',
  news_end int(10) unsigned NOT NULL default '0',
  news_class varchar(255) NOT NULL default '0',
  news_render_type varchar(20) NOT NULL default '0',
  news_comment_total int(10) unsigned NOT NULL default '0',
  news_summary text NOT NULL,
  news_thumbnail text NOT NULL,
  news_sticky tinyint(3) unsigned NOT NULL default '0',
  news_template varchar(50) default NULL,
  PRIMARY KEY  (news_id),
  KEY news_category  (news_category),
  KEY news_start_end (news_start,news_end),
  KEY news_datestamp (news_datestamp),
  KEY news_sticky  (news_sticky),
  KEY news_render_type  (news_render_type),
  KEY news_class (news_class)
) ENGINE=MyISAM;


# --------------------------------------------------------

#
# Table structure for table `news_category`
#

CREATE TABLE news_category (
  category_id tinyint(3) unsigned NOT NULL auto_increment,
  category_name varchar(200) NOT NULL default '',
  category_sef varchar(200) NOT NULL default '',
  category_meta_description text NOT NULL,
  category_meta_keywords  varchar(255) NOT NULL default '',
  category_manager tinyint(3) unsigned NOT NULL default '254',
  category_icon varchar(250) NOT NULL default '',
  category_order tinyint(3) unsigned NOT NULL default '0',
  category_template varchar(50) default NULL,
  PRIMARY KEY  (category_id),
  KEY category_order (category_order)
) ENGINE=MyISAM;
```

**Comment by NZCyrus** [comment]
Thank you, that worked. Integrity check passed and database showed as updated. New news item could be created as well.
