### ISSUE TITLE
First portion of news body is duplicated

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#2807]
Something weird is going on with the news posting. Each news post displays a duplicate portion of the body before each initial body text... Look at each of these posts. https://www.romuniverse.com/news

**Comment by CaMer0n** [comment]
Try clearing cache.

**Comment by BigBoiJefe** [comment]
I tried clearing the cache.  Still having the same issue.

**Comment by rica-carv** [comment]
I've had that once, and solved it customizing the news_summary shortcode in my theme...

**Comment by BigBoiJefe** [comment]
Do you know what specifically I need to change?

**Comment by Moc** [comment]
@BigBoiJefe Is this still an issue?
