### ISSUE TITLE
Enhancement: {NEWS_IMAGE} Auto Carousel option

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2809]
Automatically generates a sliding carousel of images based on the 5 image containers/slots in the news item admin area. 

## Usage Examples: 

    {NEWS_IMAGE: carousel=1}
    {NEWS_IMAGE: carousel=1&w=800&h=400&crop=1}
    {NEWS_IMAGE: carousel=1&interval=5}

## Frontend Example (Voux Theme)

![news_image_carousel_voux](https://user-images.githubusercontent.com/2825679/31361912-b9d13530-ad0a-11e7-9f45-a950b3f00b24.jpg)

## Admin Area for the item
![news_image_carousel_admin](https://user-images.githubusercontent.com/2825679/31361914-bd1ddafe-ad0a-11e7-967c-19beeee11d27.png)

**Comment by CaMer0n** [comment]
@fizi @Jimmi08

**Comment by CaMer0n** [comment]
Live demo: http://themes.e107.org/voux/

**Comment by fizi** [comment]
I tried it and work great.
