### ISSUE TITLE
Library stylesheet being loaded in admin area when it should be excluded. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2810]
@lonalore Please take a look if you have some time. 

e107_themes/bootstrap3/theme.xml

    <libraries>
     <library name="bootstrap" scope="all"/>

This mostly works as intended, unless we choose an admin style such as "Superhero" which requires that the regular bootstrap CSS NOT be loaded (as indicated by `exclude="bootstrap"` in the line below). 

     <css file="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" name="Superhero" scope='admin' exclude='bootstrap'/>

What is occurring right now is that the default bootstrap.min.css is being loaded AFTER the Superhero bootstrap.min.css, which basically cancels most of the styling of "Superhero". (see below)

![superhero_screenshot](https://user-images.githubusercontent.com/2825679/31373451-f37bad3a-ad4e-11e7-93aa-665c8106f970.png)

So, what SHOULD happen is that 'exclude=bootstrap' is observed and this should override the default `scope="all"`, causing the regular bootstrap file (/lib/bootstrap/3.3.7/dist/css/bootstrap.min.css) to NOT be loaded, while still loading the regular bootstrap javascript file. 

When we disable the regular bootstrap.min.css file, we get the following (correct) result: 

![superhero_screenshot_2](https://user-images.githubusercontent.com/2825679/31373528-453db8b6-ad4f-11e7-9b19-a7a2727f04ad.png)

**Comment by lonalore** [comment]
Sorry, I forgot to comment this in the morning. It must work now! :)

**Comment by CaMer0n** [comment]
Excellent! Thank you @lonalore will merge and test. 👍

**Comment by CaMer0n** [comment]
Working! 👍
