### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by chory** [e107inc/e107#2812]
Form yesterday 10/10/2017, when try access to my website, this return error 500.
www.aaa.bb -> 500
www.aaa.bb/forum -> 500
www.aaa.bb/news -> 500
but
www.aaa.bb/e107_plugins/forum/forum.php -> OK
www.aaa.bb/e107_plugins/news/news.php -> OK

**Comment by CaMer0n** [comment]
@chory Please check your apache error log or look for error_log in the root or forum directory.

**Comment by kreossino** [comment]
in ssh write
chown yourname:yourname -R www.aaa.bb
find . -type f -exec chmod 644 {} +
find . -type d -exec chmod 755 {} +

i'm sure you resolve with this

**Comment by chory** [comment]
**error.log**
with 128M Memory Limit
[13-Oct-2017 11:45:43 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 100611336 bytes) in _class2.php_ on line 2454
with 512M
[13-Oct-2017 11:47:38 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 215212032 bytes) in _e107_core/templates/footer_default.php_ on line 250

**Comment by Moc** [comment]
Sounds like a (redirect) loop that's happening. 

- Make sure you are using the latest `.htaccess` file from Github. Clear all caches. 

You can also try the Rebuild function on `/e107_admin/eurl.php` but I must admit that I am not entirely sure what it does.

**Comment by chory** [comment]
@Moc 
- Make sure you are using the latest .htaccess file from Github. Clear all caches.

That was the problem
I thought that all files are updated from the admin panel, but I see that it is not so.

**Comment by 214945** [comment]
Which file latest .htaccess and works fine?
