### ISSUE TITLE
problem with update to 2.1.7

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2814]
It was new install (some months ago), now update to 2.1.7  (no version 1 before)

I got this info:
![image](https://user-images.githubusercontent.com/5429548/31513297-3a332442-af8e-11e7-8c38-f6b5145f5f68.png)

After updating from 1 to 2.x
![image](https://user-images.githubusercontent.com/5429548/31513334-5d645cb0-af8e-11e7-9079-4483e5a6c7c0.png)

but it still needed update  from 1 to 2.

Only error I could find was:
![image](https://user-images.githubusercontent.com/5429548/31513395-85d89594-af8e-11e7-9435-cd958c0d8615.png)

I have not installed download plugin.  After installation download plugin, update info looks like this:
![image](https://user-images.githubusercontent.com/5429548/31513489-cba317de-af8e-11e7-94c4-ca93f1ea1343.png)

but update from 1 to 2 is still there. 
![image](https://user-images.githubusercontent.com/5429548/31513577-11101dbc-af8f-11e7-83ef-c8eab0b5e932.png)

**Comment by Jimmi08** [comment]
@CaMer0n I just posted PR to show what I changed to get this work.  Only `if(e107::isInstalled('download')) { ... }  `
was added in that block, from PR it looks like everything was changed.  

Do it your way please.

**Comment by CaMer0n** [comment]
Thank you!. Yeah, we can't use that because 'download' is not a plugin in v1.x ;-)
