### ISSUE TITLE
Change Breadcrumb name on gallery plugin

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#2816]
i have modified in e107_plugins/gallery/template/gallery_template.php
`$GALLERY_TEMPLATE['list']['caption']` = `LAN_PLUGIN_GALLERY_TITLE;`
in 
`$GALLERY_TEMPLATE['list']['caption'] = LAN_PLUGIN_GALLERY_NEWTITLE;`
now in 
../e107_plugins/gallery/languages/English_global.php
 i have added this row

`define("LAN_PLUGIN_GALLERY_NEWTITLE", "Collection");`

but the breadcrumb and the catpion don't change  i see "gallery"  not "Collection"

**Comment by tgtje** [comment]
It is not that easy as LAN_PLUGIN_GALLERY_TITLE is used on multiple positions throughout files.. Your case would be using (change aka hacked/renamed plugin)  the lang file; template; xml file; admin_gallery; controllers/index and e_shortcode, and some more to reflect each change ( about 15 i guess) The above mentionded is NOT enough.

**Comment by kreossino** [comment]
ok i do some test, but ok,  is a very good solution if in admin-panel of e107 the admin can create a new "media owner"

**Comment by Jimmi08** [comment]
media_owner should be plugin name, so you need to set this in plugin.xml

**Comment by kreossino** [comment]
OK Jimmi08. but I do not know how to do. can you send me an example?

**Comment by Jimmi08** [comment]
Hm, I am maybe wrong.  Its limited. 
```
		$this->restricted = array(
			"_common" 	=> "_common",
			"_icon"		=> "_icon",
			"news"		=> "news",	
			"page"		=> "page",
			"download"	=> "download"					
		);
```

**Comment by CaMer0n** [comment]
It's not limited, those are the core ones during upgrade. See the banner plugin.xml for an example.

**Comment by CaMer0n** [comment]
That should fix it @kreossino . Please let me know how it goes.

**Comment by kreossino** [comment]
for me is perfect!!! thank you 😜
