### ISSUE TITLE
missing unserialize in cpagefieldtitle shortcode

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2817]
I couldn't get it works:
```
	function sc_cpagefieldtitle($parm=null)
	{
		if(empty($parm['name']) || empty($this->var['page_fields']))
		{
			return null;
		}
		$chap       = $this->var['page_chapter'];
		$key        = $parm['name'];
		if(!empty($this->chapterData[$chap]['chapter_fields']) && is_string($this->chapterData[$chap]['chapter_fields']))
		{
			$this->chapterData[$chap]['chapter_fields'] = e107::unserialize($this->chapterData[$chap]['chapter_fields']);
		}
		if(!empty($this->chapterData[$chap]['chapter_fields'][$key]['title']))
		{
			return $this->chapterData[$chap]['chapter_fields'][$key]['title'];
		}
		return null;
	}

```

I think that reason is this:

value of $this->chapterData[$chap]['chapter_fields']  is: 
![image](https://user-images.githubusercontent.com/5429548/31546839-5586f75e-b025-11e7-85b4-20757ba201ab.png)

after using `$chaptfields =  e107::unserialize($this->chapterData[$chap]['chapter_fields']);`
and
`return $chaptfields[$key]['title'];`
output is correct

![image](https://user-images.githubusercontent.com/5429548/31546898-93c68d04-b025-11e7-9c55-eaa466fbea60.png)
 
and shortcode works.

**Comment by CaMer0n** [comment]
@Jimmi08 Are you all up-to-date with Github? I think I fixed this recently.

**Comment by Jimmi08** [comment]
@CaMer0n I was sure that I had latest files. But I see that function there...  I will open this if not.

**Comment by CaMer0n** [comment]
Here's the commit. For a moment there I thought I may not have saved the changes! ;-)
 https://github.com/e107inc/e107/commit/2d43b87b81387446045e9ccfb787bd754c108d9b

**Comment by Jimmi08** [comment]
Sorry, I was sure I did github sync.   Apparently not.

**Comment by CaMer0n** [comment]
No worries!
