### ISSUE TITLE
Exhaustive Feature List

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2829]
So, this is quite an undertaking. 

### The idea is to **list every feature of e107** or at least close to it. 

Starting with the common features and then eventually going deep into the less used/known options. This list will eventually appear as a page on e107.org

It could almost mean an entry on this wiki page for every core and plugin preference and more!

I have made a start, but I think if each of us could add at least **10 items or more** to the wiki entry, it will grow very quickly. Here it is: 

https://github.com/e107inc/e107/wiki/Exhaustive-Feature-List

Please feel free to modify and add to the wiki entry. 

Thank you. 

@e107inc/honorary-contributors

**Comment by Jimmi08** [comment]
Sorry, I don't know what put where, so just ideas:

Review system (stars)
Dashboard (customizable)
Search system (it's unique in comparing with other CMS)
Notification system
RSS
Chat
Pretty urls
Maintenance 

I don't know if this is feature:
-  Easy installation with database creation

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 !! I added most of them.  👍 

## No need to worry too much about sorting and categories at this stage.. we'll tidy up as we go along and probably again at the end.

**Comment by lonalore** [comment]
### System
- Error pages (customizable)

### For Developers
- JS/CSS Manager (e107::js() and e107::css())
- Javascript Framework (e107.behaviors)
- Ajax API (for making Ajax requests without writing a single line of JS code)
- Libraries API (for managing any kind of 3rd party libraries)
- Event handler?

**Comment by oxigeno2** [comment]
1 to 3 - For me the path of hearts, advantage comprehensiveness of services. Sometimes at the expense of rapid development.
4 - Excellent access for users!
5 - Ease of use!

I'm sorry, I had to find out in my memory why I went back to e107

**Comment by Crytiqal** [comment]
The customizability of every plugin or menus by using a custom folder in the theme folder. This is an amazing feature that I think no other cms offers so easily.

**Comment by tgtje** [comment]
Ah a thinking one, needs time... Just adding ( NOT as a feature 'yet') I do miss a (imo) very 'strong' item which seems to 'become' forgotten (or not being looked at often) the IMPORT function (X to e107). Hardly any posts or user feedback on that one.....

**Comment by rica-carv** [comment]
Isn't IMPORT already on the core? Or i miss something here?

**Comment by CaMer0n** [comment]
@tgtje @rica-carv Indeed, I'll add it to the list.

**Comment by tgtje** [comment]
Yes it is @rica-carv , but for me it is unsure if it actually has good results made ( hardly no messages to find of those who did or succeeded). So yes it is there, and should (if working good) have a prominent position.
EXport however i do not find that important.( That is something third parties should worry about).

**Comment by LaocheXe** [comment]
Export Database, Database Backups via Cron, Sync to Github (Developer Mode), Plugin Update Check, Download Themes/Plugins from e107.org to website (idk what to call it). Developer Documents.

**Comment by tgtje** [comment]
A (not always known) feature is the ability to change positions of **_menus_** by use of table copies WHEN using multiple languages.

**Comment by CaMer0n** [comment]
@tgtje Yes, one could change the menu layout according to the language.

**Comment by arunshekher** [comment]
**SEO Features**
- Valid and semantic HTML5, CSS3
- Search Engine and Human friendly URLS (*already mentioned)
- Integrated social sharing options
- Search Engine Crawler ping utilities on content publish
- XML Sitemap creator
- Meta Content (Tags) generation tools

**Responsive Features**

- can respond according to device screen-size
…….

**Architected for Speed and Performance**
- Configurable Content Delivery Network (multiple data centers) options for static content and improved network availability
- Caching 
- Quick optimized(compressed) site rendering and serve options

**Developers**
- override core methods

**Comment by kreossino** [comment]
contact page with a personalizable fields
[https://ceraunavoltabeb.it/contact.php]see this page

**Comment by MikeyGMT** [comment]
Sounds like the old wiki - we had lots of this in there, is it totally dead? (I only ask as I spent weeks if not more on that).  :)

**Comment by Moc** [comment]
The content of the v1 wiki has been imported to the Github wiki here: https://github.com/e107inc/e107v1/wiki

It's not perfect, but it's a start. The backup with all the data is kept safe so nothing's lost. The way to display it is tricky because of the vulnerabilities in the wiki software.
