### ISSUE TITLE
Survey: Which features of e107 save you the most time?

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2830]
From the perspective of the user (not developer), which features of e107 save you the most time?

For me it is "Inline-Editing", "Batch Modification" and "On-The-Fly Image Resizing" . 

Can you think of others?

@e107inc/honorary-contributors

**Comment by kreossino** [comment]
of my user e107 is now very good, but my customers needs a new beautifull "themes" to choose them quickly

**Comment by tgtje** [comment]
I honestly can not answer this one, as i am (as user) not going for a time saviour. The only negative (sorry) is tiny editor; this one 'holds'me back, as i am often 'seeking' (solving) how to do things i like to see happening. (from editorial/content point of view). The only real time saviour (for me as user) is the ability to click an edit button on 'article' and go right into the edit mode.. (is it inline editing? (translation of english understanding/meaning ?)

**Comment by rica-carv** [comment]
Sorry on this one, but i'm with @tgtje ...
If i'm stuck with something, i go direct to phpmyadmin / MySQL and solve the issue... for me is faster than anything else...

**Comment by CaMer0n** [comment]
Thank you @tgtje @rica-carv - Could you tell me what kind of 'issue' you mean? Is there a problem with the HTML markup ? Maybe you can post it as a bug with TinyMce.

**Comment by arunshekher** [comment]
For me one is the XHR based form submissions in the chatbox, forum quick reply, comments and rating/like etc. In actuality even if this doesn’t really save much time it gives the user an ever so slightly satisfying feeling of being quick. Even though the question doesn’t ask for it in my opinion we should adopt these much more in other areas like poll, private messages etc where the whole page refresh is not necessary. Shifting to a dev’s perspective I think making available an ‘infinite scroll’ pagination API using XHR for plugin and theme developers is also much useful.

**Comment by rica-carv** [comment]
@arunshekher If the "legacy" pagination is to be mantained, i agree with the "facebook like infinite scroll", but i personally won't use it, since on heavy content page, it will become crumbersome and not very functional...
Even in facebook, if you scroll down a lot, it is also not very functional to return to the top....
Just my thoughts...

**Comment by arunshekher** [comment]
@rica-carv Yes of course, I mentioned it as an added experimental feature, not replacing the legacy pagination. I apologize if I hyjacked the topic of the thread.

**Comment by LaocheXe** [comment]
I would have to say the Plugin Builder is a nice feature, this allows for none developers to try and build their own plugin, without needing to code the admin area. The theme manager is also something to point out, depending on the theme, the theme's options could help customize the theme's look without needing to add/edit the theme's code. Only thing I tend to have an issue as a user would be the TinyMce - I wish there was some other alternatives than using TinyMce - I could go with the default but I have issues with adding some html code from time to time, such as embed, and/or iframes.

**Comment by CaMer0n** [comment]
Thank you @LaocheXe , good points. Please post an issue when these TinyMce problems arise, the tweaks to fix them are likely to be very small.

**Comment by LaocheXe** [comment]
@CaMer0n is there no other alternatives to TinyMce? Having more than one might be better, or at least in my opinion.

**Comment by CaMer0n** [comment]
@LaocheXe Yes, there's SimpleMDE, which uses MarkDown (like here on Github)
