### ISSUE TITLE
Choosing a FontAwesome icon for a custom menu also places it into TinyMce Editor

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2835]
@lonalore I believe this could be a new issue that arose after some of the javascript was rewritten by yourself? 

There are two modes ($_GET):
* bbcode = 1 elements are placed into TinyMce editor. 
* bbcode = 0 elements are placed back into their container.  eg. image-selector etc.

**Comment by lonalore** [comment]
I think it was an old issue, but now it has to work properly. :)

**Comment by CaMer0n** [comment]
okay! Thank you @lonalore . Much appreciated!
