### ISSUE TITLE
[enhancement]  plugin builder - generate local shortcodes file

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2837]
Something like this would really save me a lot of time... 

Generate local shortcodes file (not only global e_shortcodes.php) this way:
in folder batch/shortcodes
file name:  plugin_name_shortcodes.php
**Note**: _it depends on what is standard, because there is shortcut with shortcode class in the same file as plugin class file.   OR some plugins use file pluginname_shortcodes.php in main folder._

Inside this file create class
class plugin_name_shortcodes extends e_shortcode

and for each table field generate method according file type (or for most of them like text, textarea) - ideally  alphabetically

```
/*
 @example {PLUGIN_TABLEFIELD}
 */
function sc_plugin_textfield()
{	
 if(!empty($this->var[['plugin_tablefield'])) {
  return e107::getParser()->toHTML($this->var[['plugin_textfield'], 'TITLE); 
 }
}
```
for image field it would be something like this (but method with //something here would be enough
`return $tp->toImage($this->var['plugin_textfield'], $att);`

This could be help to do plugins by using standards in version 2.

Not mention saving time with templates - just copy example of shortcode and put it to template

**Comment by CaMer0n** [comment]
@Jimmi08 This is a great idea!!

**Comment by rica-carv** [comment]
Excuse me the off topic, but take note that the plugin builder has some issues when importing some v1 plugins admin areas....

**Comment by CaMer0n** [comment]
@rica-carv What kind of "importing". Do you mean importing of the plugin.php meta data?

**Comment by rica-carv** [comment]
@CaMer0n No, when the plugin builder converts the admin area of old legacy v1.x plugin, it converts only what's based on the sql, it ignores the preferences and only creates a sql admin front end (in v2.x, the list / create admin ui section...), if you know what i mean...
This happened with me, at least with one legacy plugin: calendar_menu

**Comment by CaMer0n** [comment]
@rica-carv That's because it doesn't 'convert' a v1 plugin, it just uses MySQL to build a new one. This is why it's called Plugin Builder, not Plugin Converter ;-)

**Comment by rica-carv** [comment]
@CaMer0n But since it needs to have a old plugin as base to build a v2 one, shouldn't it "build" everything?
I know that sometimes old legacy admin area are hard to get and "convert", since old admin could be freely created with anything (i've had my major headaches in the past moths converting a old admin ui area that had the most ankward admin area i ever see... but after a lot of fighting, i did it fully functional in v2 style...) but it should be easy to grab old preferences and "convert" them to a v2.x admin ui, i think...

**Comment by CaMer0n** [comment]
@rica-carv No, it doesn't need a v1 plugin. The idea is that we build a mysql table or _sql.php file (using Phpmyadmin) and the builder does the rest. While some use it to upgrade old plugins, it was not the original goal.

**Comment by rica-carv** [comment]
@CaMer0n Ok, i got the point, but for a complete functional plugin builder from scratch, it should also include a preferences "generator", no?
Or it already does?

P.S.: Once more excuse me for the "off-issue"....

**Comment by CaMer0n** [comment]
@rica-carv Yes, it already generates preferences in the admin-ui. Or are you referring to inside the plugin.xml as defaults? (that could probably be added)

**Comment by rica-carv** [comment]
@CaMer0n Yes, i was talking inside the generated admin_config file and also inside the xml...

**Comment by Jimmi08** [comment]
I am lost in discussion here...  plugin builder generated preferencies in plugin.xml and in main class in admin_config.xml.  Only limit I can see is limited number of them.

**Comment by rica-carv** [comment]
@Jimmi08 When upgrading plugin, it didn't generate the prefs neither in plugin.xml or admin_config.php!
Remember why i had to write admin_config.php prefs for calendar_menu plugin?

**Comment by Jimmi08** [comment]
This is solved. CaMeRon used this for bullet plugin, it's easy to find the solution in code.
