### ISSUE TITLE
Form submission with ajax

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#2841]
Hi there,
I'm developing a plugin and have a form which must be ajax submitted.
Problem is that, the form has some required fields fields that first must be validated before submitting.
This working fine:
`

$html = $form->open('test-form', 'post', e_SELF, );

$html .= $form->text('pname', '', 255, array('class'=>'form-control','placeholder'=>'Enter your name','required' =>1) );

$html .= $form->text('pcity', '', 255, array('class'=>'form-control','placeholder'=>'Enter your City','required' =>1) );

//etc etc

$html .= $form->button(	'info-send', 1, 'submit', 'Subscribe');

$html .= $form->close();

The above code working fine, validating and submitting the form if all required fields are populated with data, but it reloads the page
`

if I try:

`
$html = $form->open('test-form', 'post', e_SELF, );

$html .= $form->text('pname', '', 255, array('class'=>'form-control','placeholder'=>'Enter your name','required' =>1) );

$html .= $form->text('pcity', '', 255, array('class'=>'form-control','placeholder'=>'Enter your City','required' =>1) );

//etc etc

$html .= $form->button(	'info-send', 1, 'submit', 'Subscribe', 'options' => array(
					'class'   => 'e-ajax',
					'data-src' => e_SELF,
					'data-ajax-type' => 'POST',
					'data-target' => '#test-form',
					'data-method' => 'replaceWith'
				),);

$html .= $form->close();
`

This is working too, it is submitting the form, but now required fields are not validated checked for data (well actually the are, since validation is firing but it doesn't matter since form is submitted with or without required fields populated. )

How can I make it work, so if required fields are empty ajax call don't fire until validation is complete and all required fields have some data. 

I searched the documentation and core files for couple of hours but can't find anything on the matter. This must be something very easy to get it working, yet it seems is quite hard.

**Comment by CaMer0n** [comment]
How about adding 'pattern' to the form elements?

**Comment by Serios** [comment]
@CaMer0n sorry, but can't understand what you mean, can you give me a simple example. Again very sorry, maybe me grinding on this take its toll but really I cant't get what you mean by 'pattern'

**Comment by CaMer0n** [comment]
@Serios https://www.w3schools.com/TAGS/att_input_pattern.asp

 You can add` 'pattern'=>'whatever'` , next to where you see `placeholder`

**Comment by Moc** [comment]
@Serios Has this issue been resolved? Do you have any remaining questions?

**Comment by Serios** [comment]
Hi @Moc yep the issue is no more.
