### ISSUE TITLE
Question  .htaccess Options -MultiViews error 500

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2845]
I am trying installation on new hosting (3 months for testing)

After installation I got error 500. The reason was that Options -MultiViews is forbidden on that hosting.
I found correct setting:
`On some shared hostings, the negotiation module might not be enabled. That would give you then a 500 error. To avoid this error, you can, by default, encapsulate the directive in an IfModule block.`

```
<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>
```
https://stackoverflow.com/questions/25423141/what-exactly-does-the-the-multiviews-options-in-htaccess

Could somebody explain me why e107 uses Options -MultiViews?

Solution above doesn't help me, I need to manually change .htaccess after installation, but maybe it could help others. What happens if I remove this options?

**Comment by CaMer0n** [comment]
Yes, MultiViews will break the SEF Urls in e107. Most systems have it disabled by default.

**Comment by CaMer0n** [comment]
More info: https://github.com/e107inc/e107/issues/2797

**Comment by Jimmi08** [comment]
Thank you. I understand now.
