### ISSUE TITLE
newforumposts_main.php doesn't work in php 7 - because deprecated function

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2849]
`$text = preg_replace("/\{(.*?)\}/e", '$\1', $NEWFORUMPOSTSTYLE_HEADER);`

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in

**Comment by CaMer0n** [comment]
Yes, the whole thing should be removed. newforumposts_menu is the replacement.

**Comment by Jimmi08** [comment]
Menu maybe. 

But there is separate page for displaying latest post, not only menu. I didn't find it in forum plugin.

**Comment by CaMer0n** [comment]
@Jimmi08  Where is this separate page? (file name)

**Comment by Jimmi08** [comment]
`newforumposts_main.php ` 

it has not _menu in file name, so I supposed it displays something as separate page.  

Maybe I am wrong, but it's good feature.

**Comment by CaMer0n** [comment]
No, it's an old feature where it would display it on the home page in the main body area. It doesn't function as a standalone page though. (class2.php, header/footer not loaded) 

We have no need for this now with all the template options we have. If this is required, the new menu could simply be added to a theme layout in this same area. eg. just before `{---}`

**Comment by Jimmi08** [comment]
Agree, so I moved it as standalone page to theme plugin. I needed it as separate clickable link. You should remove this plugin from repository.
