### ISSUE TITLE
Problem when overwriting core methods

### ISSUE THREAD

**Issue by AdocArg** [e107inc/e107#2853]
Hi, I tried to overwrite the method: **sc_user_lastvisit** (e107_core -->shortcodes-->batch-->user_shortcodes.php) in my theme_shortcodes.php file but it doesn't work. After overwriting, the lastvisit user field (in user profile) its show me: "without information". The same happen with sc_user_join. Is it possible to overwrite these methods?

**Comment by Jimmi08** [comment]
How you did it? (how you loaded user data?)
https://github.com/e107inc/e107/issues/1685

**Comment by AdocArg** [comment]
I was doing it too badly, i didn't know that i has to load the batch shortcodes in this way:

`$sc = e107::getScBatch('user');  `

Sorry, now it makes all the sense. So the solution is (or at least this works for me):

`$sc = e107::getScBatch('user');  `
`return $sc->var['user_currentvisit'] ? e107::getDate()->convert_date($sc->var['user_currentvisit'], "inputdate") : "<i>".LAN_USER_33."</i>";`

Thanks for that reference Jimako!

**Comment by Jimmi08** [comment]
@AdocArg You are welcome. I was there...  thanks for example with users
