### ISSUE TITLE
news menu styling enhancement

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2855]
- news_archives_menu.php doesn't have ID to be able to use table_render() functionality

- shortcode 	
```
public function sc_news_category_news_count($parm = '')
	{
		if(!$this->is('category_news_count'))
		{
			return '';
		}
		return (string) e107::getParser()->toBadge( $this->cat('news_count'));
	}
```
always returns html code:  `<span class="badge">1</span>`
I can't do this:  `<span class="ml-auto badge-pill badge-pill-info">25</span>`
just parameter return only value would be fine

- add possibility use shortcodes {CLASS} in news too. 

- add possibility to template archive_news menu or other set off expandit functionality (news_months_menu display only one year)

- add possibility to set off sizing in tagcloud menu (to have all tags the same size)

**Comment by CaMer0n** [comment]
Thank you!! Yeah, I think I'll need to template the new_archive_menu. It's complex, but I think it can be done.

**Comment by Moc** [comment]
@Jimmi08 Is this still relevant?

**Comment by Jimmi08** [comment]
No idea, I will create new one if I run on this again.
