### ISSUE TITLE
Help to get the word out about e107!!

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2857]
If you haven't already, please rate us here. 5-stars are preferred. :-)

https://www.softaculous.com/apps/cms/e107

@e107inc/honorary-contributors

**Comment by LaocheXe** [comment]
Posted my review!

**Comment by rica-carv** [comment]
I could have a few more screenshots. A single one doesn't make justice to e107....

**Comment by CaMer0n** [comment]
@rica-carv Indeed. Do you want to make some?

**Comment by Reconix** [comment]
Done, might've added a couple more for extra awesomeness. 
Keep up the great work guys.

PS: what happened to the text in the main admin menu ?

**Comment by Jimmi08** [comment]
@Reconix do you mean this: https://github.com/e107inc/e107/issues/2578
by the way, what is with you version of Corlate theme? It looks not finished.

**Comment by Reconix** [comment]
@Jimmi08 Thanks, I did mean that yes.

Regarding the Corlate theme, I struggled with the preferences a bit and no it's not finished. Since you asked though, might upload what I've done and see if I can finish it. It's not a bad looking free theme.

**Comment by Jimmi08** [comment]
@Reconix It was originally planned as new theme for 2.1.6 but then I found your version...  
https://e107.sk/corlate-theme

**Comment by Reconix** [comment]
@Jimmi08, In that case, I'll put my head down and finish what I can. Will pop by in chat later today once I'm done for confirmation.

**Comment by rica-carv** [comment]
> @rica-carv Indeed. Do you want to make some?

@CaMer0n It seems there's some "oldies" lying around:
![Image of e107 admin ui](https://a.fsdn.com/con/app/proj/e107/screenshots/ss5.png/1)

**Comment by tgtje** [comment]
Yep that's an oldie... (2015)

**Comment by yesszus** [comment]
Posted my review!
