### ISSUE TITLE
question:  time for database queries

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2860]
Hi, maybe this localhost problem or develop mode, but this time for executing queries looks too much:

![image](https://user-images.githubusercontent.com/5429548/32722632-c9f7be72-c86a-11e7-9e4d-da0c277143f0.png)
and a bit later:

![image](https://user-images.githubusercontent.com/5429548/32722623-c592f874-c86a-11e7-9703-4f937e672f6b.png)

**Comment by rica-carv** [comment]
It might also be related to the database table size...
If the table has a huge amount of records, it's slower to execute....

**Comment by Jimmi08** [comment]
@rica-carv on localhost there is only one record

**Comment by rica-carv** [comment]
If it's a local machine, might be some hidden process working in the background...
Have you tryed with a online server to see if it happens also?

**Comment by Jimmi08** [comment]
That was point of question. How this is possible on localhost - other queries was normal. Just to e107_online was so slow.  

Online debug looks differently (both was php7)
![image](https://user-images.githubusercontent.com/5429548/32747531-504589c0-c8b9-11e7-9bac-bb7f85a67369.png)

Why is on localhost looking for user_id =0 ? I am logged in.

**Comment by rica-carv** [comment]
Just guessing, but might be a localhost mysql server related issue.
It's indeed weird why in localhost your logged id is 0 and on live site is 1....

**Comment by lonalore** [comment]
By default, only `online_ip` has indexing. You need to add more indexes manually. Add indexing to all the fields you use in query conditions. In your case, add indexing to `online_user_id` and `online_timestamp`.

```
ALTER TABLE `e107_online` ADD INDEX(`online_user_id`);
ALTER TABLE `e107_online` ADD INDEX(`online_timestamp`);
```
You will experience significant acceleration in case of page loading time.

@CaMer0n I think we need to add more indexing in the default SQL file (`core_sql.php`). Without these indexes e107 can be really slow.

**Comment by lonalore** [comment]
If I remember correctly, I also applied these indexes when I created the e107projects.com. Node.js plugin uses the online table, and it was a bit slow.

**Comment by lonalore** [comment]
Yes, I remembered well... my table also has extra indexes:

![kepernyokep_2017-11-14_21-26-42](https://user-images.githubusercontent.com/6043821/32803081-b66b346a-c982-11e7-9812-86dfe0add517.png)

**Comment by CaMer0n** [comment]
Thank you! Merged! 👍

**Comment by lonalore** [comment]
Thank you, but you merged my other PR, not the PR for this issue. :D

**Comment by CaMer0n** [comment]
haha! You're right. I should be careful when having 2 windows open. :-)

**Comment by CaMer0n** [comment]
@Jimmi08 Did this fix it? For me it brings it down from 5 msec from 3 msec.

**Comment by Jimmi08** [comment]
yes, it's better now

![image](https://user-images.githubusercontent.com/5429548/32836931-cdf91e10-ca0b-11e7-8a6f-5f2bd487b9ad.png)

**Comment by lonalore** [comment]
Could you please provide avarage values instead of the current ones? For example "the average of 10 query times" before / after.

**Comment by CaMer0n** [comment]
@Jimmi08 Did this fix it? For me it brings it down from 5 msec from 3 msec.

**Comment by lonalore** [comment]
I did a quick banchmark, and unfortunately, I have to say that **it's slower with indexes**. Interesting... :/

**Before update (avg 1,3203):**
![kepernyokep_2017-11-15_21-15-29](https://user-images.githubusercontent.com/6043821/32858060-66cc8580-ca4a-11e7-9088-206f2e5f19b6.png)

**After update (avg 1,3694):**
![kepernyokep_2017-11-15_21-15-19](https://user-images.githubusercontent.com/6043821/32858079-7a01f324-ca4a-11e7-93fd-c03f09cc991e.png)

**The diff is ~0,049.**

**Comment by CaMer0n** [comment]
Thanks @lonalore , at the least I am happy that someone else got that result too, so I'm not going crazy after all ! haha

**Comment by lonalore** [comment]
I made new banchmark (on the same website the previous banchmarks were made on) with indexing suggested by @fwhcat on Gitter, and this is the best so far.
```
...
KEY online_ip_user_id (online_ip, online_user_id),
...
```

**Results (avg ~1,261)**
![kepernyokep_2017-12-09_21-00-54](https://user-images.githubusercontent.com/6043821/33799039-15a25a9e-dd24-11e7-868c-be0c4ef3c863.png)

**Comment by Jimmi08** [comment]
Thank you guys.

**Comment by fwhcat** [comment]
Thanks @lonalore and @Jimmi08. Glad I could help with that :)

**Comment by CaMer0n** [comment]
@lonalore @fwhcat  It appears this change has been disastrous for performance on one of the sites I manage.  User tracking had to be disabled entirely.

**Comment by Moc** [comment]
@CaMer0n @lonalore @Jimmi08 @fwhcat Where are we on this issue? Can it be closed? Are there still issues open?

**Comment by CaMer0n** [comment]
@Moc I believe it requires further testing.

**Comment by Jimmi08** [comment]
Hi, after update to latest GitHub, localhost version became visibly slower. I noticed this:

![image](https://user-images.githubusercontent.com/5429548/52959132-ccc33680-3395-11e9-930e-1add0d2b7eb1.png)

![image](https://user-images.githubusercontent.com/5429548/52959169-e1073380-3395-11e9-86ab-6b689fe47d2f.png)

**Comment by Jimmi08** [comment]
@Moc I would close this one.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/discussions/4970
