### ISSUE TITLE
Alt auth problem with php 7.019

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#2861]
Hi i use the altauth plugin to get usernames and passwords from an external database. When i use php 5.6 it works perfectly the data gets transported to the e107 database and user can login. When i switch the working website to php 7.0.19 it does not, i only get a blank page, debugging is also not working. So what can i do, i need to switch to 7.0.19 but i really do not know how to solve this.. Also tried to place define("e_PDO", true); in config.php but the username and password does not get into the e107 database and i am left with a blank page. 

(i use e107 github from yesterday and dutch and english give the same result with the otherdb auth)
Thx
Alex

**Comment by CaMer0n** [comment]
Thanks Alex. Did you check your apache error logs?
Also, try commenting out line 106 of alt_auth_login_class. 

ie. 	$username = mysql_real_escape_string($username);   <-- this is not PHP7 compat.

**Comment by Alex-e107nl** [comment]
Cameron, commented out 106 and now i do not get an blank page but the message Error
_Your credentials could not be added to the system_. 

In the admin it says 
_User attempted to login with unrecognised user name  User name: info@nu-online.net
Alt_auth: Error adding new alt_auth user to DB User name: info@nu-online.net_

So when everything works with php 5.6 it looks like it that the @ in the username gives the troubles now with php 7.0.19? I have made sure that all settings are the same as my working copy on 5.6. All usernames in this setup are emailadresses.. 

When i test the database acces i get the right data.. 

Authentification successfulRetrieved parameters:  user_email=>info@nu-online.net

So how can i go on now.. thx :-)
Alex

**Comment by fwhcat** [comment]
Hi @Alex-e107nl,

I'm currently testing with 2 copies of the master branch installed on 2 different databases,
I cannot reproduce the bug you experienced while running php 7.1.11

Can you check if mysqli extension is activated ?

Also, are you sure of the auth method and parameters you chose ? e107db?

**Comment by Alex-e107nl** [comment]
Hi fwhcat, whats happening here is that i can switch between php 5.6 and php 7.0.19, with 5.6 and everything works as expected, when i switch to php 7 it does not, all the settings are the same, i've commented out line 106 and now i get a message that says 'Error Your credentials could not be added to the system' just being puzzled here want to get it to work. Debugging brings the answer (as always) so i get the message SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_class' cannot be null.. 

How can i solve that? using only Username and Password.. in the alt-auth plugin i do not see an option for that..

Thx
Alex

**Comment by CaMer0n** [comment]
@fwhcat I think we have our answer. Try testing with MYSQL STRICT mode active.

**Comment by Alex-e107nl** [comment]
Hi.. i still find it strange that with php 7 i need to assign a initial userclass for een new member when with php 5 it does not mention this but just works... So the solution for my problem is to in Admin Area - > User Classes - > Initial User Class select one class and it works... The only thing is that it does not apply to new members who are using the site to get a membership. Maybe it's a little bug?

But at least it's working for me now!
Thx

**Comment by CaMer0n** [comment]
@Alex-e107nl Has this improved? I made changes to alt-auth recently.

**Comment by Alex-e107nl** [comment]
Hi Cameron,
i wil test it asap! Thx!

**Comment by Alex-e107nl** [comment]
Moc,
not yet, time is not really on my side these days.. i will test it on a domain of myself and hope to do it sunday..

Alex

**Comment by Moc** [comment]
No rush. Just curious. Thanks Alex!

**Comment by Alex-e107nl** [comment]
Oke, tested it, it does not work yet, placed the git of today on a testing site and i get a blank screen when entering an existing account in the external database, when i upload the backup of the alt-auth plugin it works directly.. and takes over the user credentials in the local database, so no go yet...

**Comment by Jimmi08** [comment]
@Alex-e107nl  I tested alt_auth with php 7.2
I found the issues I posted.  Maybe somebody will overview fixes there, so I could PR them.

I fully tested:
primary source: otherdb
secondary source: e107db

Versions:
user from primary source with correct password
user from primary source with wrong password
user only from secondary source with correct password
user only from secondary source with wrong password

**Comment by Alex-e107nl** [comment]
Oke when its available i will test it as soon as possible.... THX Jimmi08!

**Comment by Jimmi08** [comment]
@Alex-e107nl @Moc could this be closed? There is the only problem I know with e107 as the secondary source. 
Tested from 7.2. to 7.4  Thanks
