### ISSUE TITLE
question how to fix style issues with flatly look in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2862]
I want to use Flatly theme in admin area. But there are issue. 

Only css I can change is admin_style.css but then it has influence on other admin themes. 

Not mention it will be overriden with next update.

**Comment by rica-carv** [comment]
I remeber that @CaMer0n said sometime ago that bootstrap3 was the only admin theme allowed.
Has this changed latelly?

**Comment by Jimmi08** [comment]
No, I meant this themes. There is Flatly css or Flatly theme, but still in bootstrap3 folder

![image](https://user-images.githubusercontent.com/5429548/32747085-fcb1ba0a-c8b7-11e7-98b1-05826b322ce7.png)

**Comment by tgtje** [comment]
Not sure, but think it is 'ruled'by theme config, as Flatly (and others) are 'read'from CDN/bootswatch

**Comment by Jimmi08** [comment]
Yes, but original flatly.css from CDN display some elements wrong way. So this is useless then.

**Comment by rica-carv** [comment]
It's weird that flatly stylesheet displays elements wrong, since it's a bootstrap based theme.
Can this be related to the latest mods in css made in e107?
Which elements are displayed wrong?

**Comment by Jimmi08** [comment]
But bootstrap3 theme is customized. Switch and look at tabs on dashboard or user dropdown options or search icon in admin_ui.  Maybe I do something wrong.

**Comment by rica-carv** [comment]
@Jimmi08  Sorry, but it seems i can't reproduce that issue using the V2.1.6 & PHP 7....
![admin_area_my_website_-_2017-11-14_16 19 20](https://user-images.githubusercontent.com/17130530/32790978-c1775f62-c957-11e7-96d3-00b1dc2d7dbb.png)

**Comment by Jimmi08** [comment]
@rica-carv Why are you trying to convice me that there is not issue?   You know that there are tabs, but first time user doesn't do.  Small contrast. Try use that style some time, you will see what I am talking about.

My question was general -  I would like to have it solved similar way like normal themes solve css custom changes without new theme  - by loading custom-style.css file or something like tht.  Admin theme doesn't have this functionality. 

![image](https://user-images.githubusercontent.com/5429548/32792611-1204005a-c964-11e7-9e09-9b76a8ae0639.png)

![image](https://user-images.githubusercontent.com/5429548/32792714-5728bc02-c964-11e7-8707-0c1957929dd5.png)

I want my tabs look this way because my friend I am building site for dislike black admin  :
![image](https://user-images.githubusercontent.com/5429548/32792752-76152ab0-c964-11e7-95b3-fe53e1b94bd6.png)

Nevermind, I found workaround.

**Comment by rica-carv** [comment]
> @rica-carv Why are you trying to convice me that there is not issue?

@Jimmi08 I wasn't trying to convice you that this is not a issue. I was trying to replicate your issue in order to help, but was unable to do it...
Sorry for the misunderstanding....

**Comment by CaMer0n** [comment]
@Jimmi08 If you find a generic way to place that 'search' icon in the input box that will work across the different bootstrap themes, please let me know. Thank you!

**Comment by Jimmi08** [comment]
@CaMer0n you have message on gitter
