### ISSUE TITLE
question problem with git sync

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2867]
I am really sorry for this dumb question, but sometimes sync works and sometimes it ends with black screen.

I am testing new server.  zip was downloaded correctly
![image](https://user-images.githubusercontent.com/5429548/32889801-8e4ece60-cacc-11e7-875f-7e72dec46bb6.png)

But I noticed rights to folders :
![image](https://user-images.githubusercontent.com/5429548/32889917-07f3061e-cacd-11e7-93cf-5ec88da025d3.png)

Couldn't this be problem?

**Comment by CaMer0n** [comment]
@Jimmi08 Maybe? I haven't had an issue, but I use the 'git' command version, not the zip download version. We can't control how github makes the zip, so maybe you can try running some chmod commands after and see if they help?

**Comment by Jimmi08** [comment]
I just use Sync functionality in Tools/Database.  Only vague idea what you are talking about but I will check this on server where sync is working.  Thanks

**Comment by Moc** [comment]
@Jimmi08 Can this be closed with the PR?
