### ISSUE TITLE
The forum does not work restrictions.

### ISSUE THREAD

**Issue by 214945** [e107inc/e107#2868]
Hello
Moved the site from engine 0.7.26 2.1.5. On the old engine on the forum could write at all, it was now necessary to limit those who can post only to registered users. I put in the settings of the forum who can post and who can create topics - only users, but it doesn't work to write and create threads can still any visitor.
Put the same 2.1.6 there is the same but also download do not work.
P.S. And return the URI in the address of website line - Loading: default site.ru/e107_plugins/download/download.php

**Comment by rica-carv** [comment]
What is your server PHP version?
Also, do you did a complete database update from old version to new?

**Comment by 214945** [comment]
PHP  5.6.32
Of course database was updated. During installation it is required to do.

**Comment by CaMer0n** [comment]
@214945 You need to move to the latest v1.x release before upgrading to v2.

**Comment by 214945** [comment]
And so I did. First put 1.0.0 => 1.0.4 => 2.0.0 then then then 2.1.3 then 2.1.4 and 2.1.5.

**Comment by CaMer0n** [comment]
Closing this, but please re-open if the problem persists with this version on Github.

**Comment by 214945** [comment]
I found the error in it. Normal work interfered with two plug-ins from the old version 0.7.26 engine. "spoiler" and "my gallery" After they were deleted, everything worked except for downloads, with friendly URLs and they do not work in version 2.1.16 and by default you can not select, there is no such item in version 2.1.16
