### ISSUE TITLE
Enhancement: Convert to jpeg during import 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2869]
Using large PNG or GIF images for website content will mean larger images and a slower site. 
Media-Manager should include an option to auto-convert during import.

**Comment by rica-carv** [comment]
Just be aware that PNG & GIF files *might* have trsnaparencys (alpha channel), that are removed when converting to JPG file format...

**Comment by CaMer0n** [comment]
Indeed. I recently discovered that a website I set up for someone was having PNG uploaded in news items by a less-tech-savvy admin. Now the site has 14 meg news items. :/
