### ISSUE TITLE
2.1.6 download select the default URL

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#2877]
Make in version 2.1.16 download line select the default URL. Because friendly URL is not always working.

**Comment by Jimmi08** [comment]
This happens if download categories don't have sef-url filled.

**Comment by 214945** [comment]
I think that it is not in sef-url fields.
In version 2.1.15 everything works fine.

**Comment by Moc** [comment]
Is this still an issue in the latest version?

**Comment by Evgura** [comment]
It's okay.
