### ISSUE TITLE
wrong LAN in advanced download search

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2879]
![image](https://user-images.githubusercontent.com/5429548/32988784-88bd48fa-cd0b-11e7-992b-89f26f9b5ecd.png)

`'cat'	=> array('type'	=> 'dropdown', 		'text' => LAN_SEARCH_55, 'list'=>$catList),`

`define("LAN_SEARCH_55", "Search in news category");`

**Comment by tgtje** [comment]
Not sure on this one as it is already on oldie (2015) best guess it should be
 LAN_SEARCH_51  > define = All categories.. ?
 (download/e_search php line 44) and as define>  lan_search.php  line 81)

**Comment by Jimmi08** [comment]
I have no idea. It should be maybe Search in download categories. All  categories is one of the options.

**Comment by tgtje** [comment]
Me neither  can take a pick out of 
define("LAN_SEARCH_63", "Search in category");
define("LAN_SEARCH_64", "All Download Categories");

define("LAN_SEARCH_67", "All downloads details");
define("LAN_SEARCH_69", "Relevance");

**Comment by CaMer0n** [comment]
Untested. Did it help?

**Comment by tgtje** [comment]
Testing later...(sorry) but as proposed it was just the 'change'on the LAN (eg the textual representation > which one should be in use ), so should work as i did test it before when posting).

**Comment by tgtje** [comment]
For me it does ( displaying : search in category).

**Comment by CaMer0n** [comment]
Closing. Thanks @tgtje !
