### ISSUE TITLE
problem with facebook comments in firefox with debugger enabled

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2880]
without debugger (Firefox addon)

![image](https://user-images.githubusercontent.com/5429548/32989762-f9e9ff3a-cd1c-11e7-9b59-fb58d899c3fa.png)

With debugger

![image](https://user-images.githubusercontent.com/5429548/32989766-098499fa-cd1d-11e7-8c57-0639a5982c87.png)

**Comment by CaMer0n** [comment]
With debugger it shows generic comments. Intentional. ;-)

**Comment by Jimmi08** [comment]
Generic comments from facebook?

**Comment by lonalore** [comment]
If I know well, Facebook loads comments for a page by URL, and it makes a difference between URL with and without parameters. So: `"example.com" != "example.com?[debug=...]"`

**Comment by Jimmi08** [comment]
@lonalore I removed it from url. The same url was used. The advantage of debugger is that it works without adding parameters to url (only first time, but they can be removed)

**Comment by lonalore** [comment]
Ahhh, now I understand what the problem is. So, when you enable debug mode, e107 renders facebook comment box with generic URL like:

```html
<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>
```
...and not with the URL of your page. In my opinion, this is because you don't have to create comments for testing. As @CaMer0n said: Intentional.

**Comment by Jimmi08** [comment]
@lonalore Your explanation I understand. Thanks.
