### ISSUE TITLE
admin without rights can change full admin permissions

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2883]
I have admin with this permissions:
![image](https://user-images.githubusercontent.com/5429548/33187522-965813e8-d092-11e7-837f-6047894b50a6.png)
Double check:
![image](https://user-images.githubusercontent.com/5429548/33187531-aa1285da-d092-11e7-90d0-c7007dfd86b3.png)

Admin options now looks correct:
![image](https://user-images.githubusercontent.com/5429548/33187583-160cf02c-d093-11e7-9e30-99eb24580a7c.png)

But with editing option there is this:
![image](https://user-images.githubusercontent.com/5429548/33187600-2c6d09ec-d093-11e7-9402-db30ee3e271c.png)
and they are able to add new admin rights (tested, they are saved)

![image](https://user-images.githubusercontent.com/5429548/33187645-7ef47e8e-d093-11e7-9d38-3842912b4563.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Please re-test and close if working.

**Comment by Moc** [comment]
@Jimmi08 Did you find some time to test the fix already? :)

**Comment by SimSync** [comment]
@Moc @Jimmi08 Tested it here and limited admin has no access to the permissions page anymore with the given permissions.

**Comment by Jimmi08** [comment]
Confirm, it's fixed. Sorry again, where I was in March?  I normally didn't miss things like this.

**Comment by Moc** [comment]
@Jimmi08 It's this thing called 'life'. It gets in the way sometimes 😄
