### ISSUE TITLE
Extended user fields doesn't work on already existed users

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2884]
I added new extended field.  It wasn't saved to database after user edited their profile.
Reason was that user existed before adding this field.  
When I manually edited all existed users via admin area, extented fields now work correctly

**Comment by SimSync** [comment]
@Jimmi08 I'm unable to reproduce this issue.
I've created "normal" and "custom" extended fields and both values were saved.
Maybe this is fixed in the meanwhile?

**Comment by Jimmi08** [comment]
It was. Thanks.
