### ISSUE TITLE
with flexpanel admin layout for dashboard not all options are displayed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2886]
flexpanel:
 
![image](https://user-images.githubusercontent.com/5429548/33205963-0d4159a8-d109-11e7-8f84-f129ddbcec15.png)

but that user has admin rights to more options:
![image](https://user-images.githubusercontent.com/5429548/33206023-43224bf4-d109-11e7-85a5-e6c9ab543510.png)

Edit: the same with infopanel layout

**Comment by lonalore** [comment]
Just a tiny note: Flexpanel is based on Infopanel, it just extends Infopanel's functionality with drag-n-drop ordering. So the problem should be somewhere in Infopanel.

**Comment by Jimmi08** [comment]
It can be set by Personalize:
![image](https://user-images.githubusercontent.com/5429548/33454695-e8e291ce-d619-11e7-939c-8d4fc645f6e2.png)
