### ISSUE TITLE
Mailout - User sent process failed displayed in log even though mail sent

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2887]
Fills my log up with error messages, although mail is sent successfully.  Occurs regardless of mailing method selected, PHP, SMTP or SendMail.  I noticed it stopped at one stage with a commit but has come back.

Array
(
    [mail_source_id] => 294
    [mail_content_status] => 10
    [mail_total_count] => 1
    [mail_togo_count] => 1
    [mail_sent_count] => 0
    [mail_fail_count] => 0
    [mail_bounce_count] => 0
    [mail_start_send] => 0
    [mail_end_send] => 0
    [mail_create_date] => 1511545482
    [mail_creator] => 1
    [mail_create_app] => core
    [mail_e107_priority] => 0
    [mail_notify_complete] => 0
    [mail_last_date] => 0
    [mail_title] => test12
    [mail_subject] => test12
    [mail_body] => [html]&lt;p>test&lt;/p>[/html]
    [mail_media] => Array
        (
            [0] => Array
                (
                    [path] => 
                )

            [1] => Array
                (
                    [path] => 
                )

            [2] => Array
                (
                    [path] => 
                )

            [3] => Array
                (
                    [path] => 
                )

            [4] => Array
                (
                    [path] => 
                )

        )

    [mail_target_id] => 19339
    [mail_recipient_id] => 1
    [mail_recipient_email] => webmaster@threepercentersmcc.org
    [mail_recipient_name] => Marty
    [mail_status] => 10
    [mail_detail_id] => 294
    [mail_send_date] => 1511545485
    [mail_target_info] => Array
        (
            [USERID] => 1
            [DISPLAYNAME] => Marty
            [SIGNUP_LINK] => 
            [USERNAME] => marty
            [USERLASTVISIT] => 1511535589
        )

    [mail_sender_name] => Marty
    [mail_sender_email] => webmaster@threepercentersmcc.org
    [mail_send_style] => default
    [mail_copy_to] => 
    [mail_bcopy_to] => 
    [mail_attach] => 
    [mail_include_images] => 0
    [mail_selectors] => Array
        (
            [user] => Array
                (
                    [email_to] => self
                    [last_visit_match] =>  
                )

        )

    [status] => 1
)

**Comment by MikeyGMT** [comment]
Hi @martyshep I am having similar issues, did you resolve it? Debug isn't giving me any clues. Cheers, Mike

**Comment by MikeyGMT** [comment]
Aha - For me - I found it - with some debugging. 
Go to Mailout > Prefs > Mailout Logging > 
On a fresh Install it was set to 3 Logging only with no errors. At least do not remember changing it! 

![image](https://user-images.githubusercontent.com/2847651/39084740-84e9ce36-4571-11e8-858c-ef1eff440817.png)

Maybe worth adding a reminder to check the setting if you get send mail success message, whilst not receiving a mail! 

![image](https://user-images.githubusercontent.com/2847651/39084797-4339990c-4572-11e8-92a1-99b85fc04423.png)

Actually the testing function helped too.

**Comment by MikeyGMT** [comment]
Weirdly however, test mailer works, but Signup Mail and Resend Signup User Confirmation mail fails. 
![image](https://user-images.githubusercontent.com/2847651/39084963-ade8ee22-4574-11e8-9a61-f835a8a121f9.png)
Went to Prefs Emailer and it was PHP and whilst Mailer Pref was SMTP.
Set the General Pref to SMTP and it's now working.

**Comment by Moc** [comment]
Is this still an issue?

**Comment by martyshep** [comment]
Yes still an issue for me.  Mailshots do actually get sent, the process is working, but my log fills with error messages to say User sent process failed.

I have preferences set to SMTP, using TLS, when I use Test SMTP connection it shows all good and TLS supported.  Just fills my logs up with errors :/

**Comment by SimSync** [comment]
@martyshep Are you able to implement some lines to a file for a test? I'm not able to test it here, so it would be nice if you could test it...

**Comment by martyshep** [comment]
Sure yes, thanks for your willingness to help, much appreciated :)

**Comment by SimSync** [comment]
Add the following method after method "showSelect()" around line 371 to file e107_plugins/user/e_mailout.php:

```	
/**
	 * Manage Sent. 
	 */
	public function sent($data) // trigerred when email sent from queue.
	{
		if($data['status'] == 1) // Successfully sent
		{
			// e107::getLog()->add($this->mailerSource . ' email sent', $data, E_LOG_INFORMATIVE, 'SENT');		
			return true;
		}
		else // Failed 
		{
			// e107::getLog()->add($this->mailerSource . ' email not sent', $data, E_LOG_FATAL, 'SENT');		
			return false;
		}
	}
```

**Comment by SimSync** [comment]
This should fix the issue regarding the error messages in the admin log regarding "user sent process failed". At least if the send mail was successfull ...
