### ISSUE TITLE
not able to debug $sql->insert()

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2890]
I can't get insert to work, so I set debug true.

Result is:

![image](https://user-images.githubusercontent.com/5429548/33265206-0570701e-d371-11e7-9326-25edf04385ef.png)

You can test it with submit news too. I changed 
`if(!$sql->insert("submitnews", $insertQry)) `
to 	
`if(!$sql->insert("submitnews", $insertQry, true))`

debug result is text array, no query is displayed. 

PHP 7.0, PDO

**Comment by Jimmi08** [comment]
Is there no possibility to use mysqli instead pdo? 

this doesn't work: ` define('e_PDO', false);`  if your php PHP_MAJOR_VERSION > 6

if I change it manually, I've got error about  Call to undefined function mysql_connect()

**Comment by Jimmi08** [comment]
If I use old way - values separated by comma - debug works.

**Comment by CaMer0n** [comment]
@Jimmi08 Please re-open if necessary.
