### ISSUE TITLE
Firefox Debugger Flagged as Legacy and Disabled

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#2891]
Hi Team, 
Seems the debugger has been disabled by the latest mozilla firefox update. https://addons.mozilla.org/en-GB/firefox/user/camer0n/?src=api  As an alternative I wonder could its functions be encorporated into an admin menu - under the orange bug icon? 
Thanks
Mike

**Comment by Moc** [comment]
Work is in progress by @lonalore on new extensions for Firefox and Chrome: https://github.com/e107inc/e107-dev

**Comment by Moc** [comment]
Until that time, you can manually change the URLs using these commands: https://e107.org/developer-manual/getting-started/debugging

(I'll add the missing ones tonight, such as time and SQL analysis)

**Comment by MikeyGMT** [comment]
Thanks, yes I was aware of https://e107.org/developer-manual/ :) 
Closing as it's in hand

**Comment by lonalore** [comment]
I finished the work on it last week and I sent a pre-release to @CaMer0n for testing and uploading it to Mozilla, but he was out of town. But I think the extension will be available soon. Maybe on this week.
But if you do not want to wait, I can send you the files, and you can install it manually.

**Comment by LaocheXe** [comment]
@lonalore can you hit me up with the files?

**Comment by lonalore** [comment]
**Installation in Firefox Quantum**
- Visit `about:debugging` page in your Firefox
- Click to _Load Temporary Add-on_ button
- Select `e107-dev.xpi` file

**Installation in Google Chrome**
- Visit `chrome://extensions` page in your Chrome
- Drop the `e107-dev.crx` file into the browser

**Extension files:**
[e107-dev.zip](https://github.com/e107inc/e107/files/1516885/e107-dev.zip)

**Note:** In Firefox, you can only install it as a temporary addon (because it has not been published on Mozzilla yet), so it will be removed after restarting your browser.

**Note:** My english is not the best, so please review the sentences to be grammatically correct, and report it [here](https://github.com/e107inc/e107-dev/issues)... if not...

Thank you for testing! :)

**Comment by Jimmi08** [comment]
@lonalore Tested. It works. 
But I have still problem with how many information see quest!  
If I set debug mode ON (because github sync)  then any quest with this can see everything. Or I am wrong, but there should be rules who can see what and when to be able to check if it works this way.

**Comment by LaocheXe** [comment]
Got it in Chrome, but FireFox complaining about missing installation manifest

**Comment by lonalore** [comment]
@Jimmi08 yes, debug mode should be available only if developer mode is On. But this is an e107 related issue.
@LaocheXe please download e107-dev.zip again, I attached wrong file first, but I replaced it. You may downloaded the wrong one.

**Comment by Jimmi08** [comment]
@lonalore I understand, but it (or e107) should check if I am logged as admin or with the same IP with incognito like quest).  OR at least allow git sync without developer mode. This is reason why I often forget to set it OFF.

**Comment by lonalore** [comment]
This extension just a tool to swtich between debug modes, so e107 should handle what information is displayed and to whom. In my opionon e107 should only display debug info if Developer Mode is On. To forget to turn off Developer Mode on a live site is the developer's responsibility.

**Comment by Jimmi08** [comment]
@lonalore I agree with you, I just don't understand. Check it on e107.org - I am pretty sure that there is no developer mode set ON but I can see some debug information. So it depends on something else too.  Do you have set Developer mode on e107hungary too?

**Comment by lonalore** [comment]
@Jimmi08 currently, e107 shows debug info even though Developer Mode is Off. So, I think this is a bug in the core. That's why I wrote that e107 should only display debug info if Developer Mode is On.

**Comment by LaocheXe** [comment]
Got it working, thanks!

**Comment by Moc** [comment]
I think I remember Cameron saying that this behaviour was intentional but I agree that no debug info should be displayed unless the developer mode is enabled.

**Comment by CaMer0n** [comment]
Re-opening until published.

**Comment by Moc** [comment]
Chrome extension has been published: 
https://chrome.google.com/webstore/detail/e107-dev/ikpmmbnjfndjmpmehlgeeinfkiaafdkf?hl=en

Firefox is still in publishing process as far as I know.

**Comment by Moc** [comment]
Firefox has been published as well: https://addons.mozilla.org/en-US/firefox/addon/e107-dev/
Thanks @lonalore 

Closing this issue. For more feedback on the extensions, please use https://github.com/e107inc/e107-dev/

**Comment by rica-carv** [comment]
I'm using Firefox Quantum 58.0.2 (64-bit), and currently the download page of the debugger states that the debugger is not compatible with my FF version.....

**Comment by Moc** [comment]
Please post this up as an issue in this repo: https://github.com/e107inc/e107-dev/

**Comment by rica-carv** [comment]
@Moc Done. Thanks for pointing the right direction...
