### ISSUE TITLE
Q/I: News Page Inline Edit?

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2892]
This is the first time I notice this, but are we so post to get an inline edit for news items on news.php? I had someone post something, went to click on the title to go to the page, end up getting a red dotted line edit option then a go to link option.

![capture-news](https://user-images.githubusercontent.com/5818022/33330114-9c7d4aba-d423-11e7-850c-d62702b18d58.JPG)

So clicking on the title should bring me to /news.php?extend.{News ID}  but why am I getting an edit option? (Main Site Admin)

**Comment by CaMer0n** [comment]
Disable "Frontend Inline-Editing" in admin > Preferences.

**Comment by LaocheXe** [comment]
Thanks!
