### ISSUE TITLE
Issue: Gylphs

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2896]
Well, some just aren't showing, even if you type the name 'youtube' you get three boxes, you cant see em, but then you can.... screenshots

![capture-glyph](https://user-images.githubusercontent.com/5818022/33527465-239bf040-d817-11e7-85fb-32d477084eec.JPG)

Now you can see it:
![capture-glyph2](https://user-images.githubusercontent.com/5818022/33527471-328923b6-d817-11e7-837a-0f2b99cbf28b.JPG)

But then you cant:
![capture-glyph3](https://user-images.githubusercontent.com/5818022/33527472-3883ac1e-d817-11e7-987c-dd15ef77a111.JPG)

Final result:
![capture-glyph4](https://user-images.githubusercontent.com/5818022/33527475-4059a56a-d817-11e7-8c83-1f47deef42b2.JPG)

**Comment by CaMer0n** [comment]
@LaocheXe Thanks. Please re-open if needed.
