### ISSUE TITLE
bootstrap4  - report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2898]
Defined version 4 this way:

`define("BOOTSTRAP", 	4);`
loaded files this way:
```
e107::css('url', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css');
e107::css('url', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
e107::js("footer", 	    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js', 'jquery' );
e107::js("footer", 	    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js', 'jquery' );
```
I can't rid the "plus" at the beginning of site:
![image](https://user-images.githubusercontent.com/5429548/33577363-06c37740-d943-11e7-973f-5c119d942a9b.png)
![image](https://user-images.githubusercontent.com/5429548/33577375-109122a4-d943-11e7-8764-f0a4c568f9c3.png)

similar problem was if bootstrap 3 js wasn't fully version, modal script was missing or something like this.

Thanks

**Comment by Jimmi08** [comment]
btn-default - replaced by btn-secondary
But correct replace is use btn-primary for all buttons in e107, only second button should be btn-default

**Comment by Jimmi08** [comment]
this needs to be fixed for bootstrap 4 too:
```
function breadcrumb($array)
{

$sep = (deftrue('BOOTSTRAP') === 3) ? "" : "<span class='divider'>/</span>";

}
```

**Comment by Jimmi08** [comment]
With bootstrap 4 there is problem with using fade class in alert debug message.  Quick fix in theme style.css
```
.s-message.fade {
    opacity: 1;
    visibility: inherit;
}
```
Without it there is just empty place, no message

**Comment by Jimmi08** [comment]
**Comment buttons**
`{COMMENT_REPLY} {COMMENT_EDIT} {COMMENT_MODERATE}`
have different classes
`e-comment-reply btn btn-default btn-secondary btn-sm btn-mini btn-xs`
`btn btn-default btn-secondary btn-mini btn-xs e-comment-edit`
`e-comment-delete btn btn-default btn-secondary btn-sm btn-mini btn-xs`

there is missing btn-sm from COMMENT_EDIT and button has different size in bootstrap4
![image](https://user-images.githubusercontent.com/5429548/113485042-eeb3a080-94ab-11eb-8203-fcebeb287151.png)

**Comment by Moc** [comment]
@Jimmi08 This one can be closed I think?
