### ISSUE TITLE
e107::getForm() and using secure image?

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#2900]
Is it possible to render secure image on form generated trough e107::getForm() ? I cant't find anything in the documentation or in form_handler class

**Comment by lonalore** [comment]
Not tested, but I hope it helps:

```php
<?php

require_once("../../class2.php");

$form = e107::getForm();
$msg = e107::getMessage();

if(isset($_POST['rand_num']) && isset($_POST['code_verify']))
{
	$invalid = e107::getSecureImg()->invalidCode($_POST['rand_num'], $_POST['code_verify']);

	if($invalid)
	{
		$msg->addError('Validation failed.');
	}
	else
	{
		$msg->addSuccess('Validation success.');
	}

	echo $msg->render();
}

require_once(HEADERF);

echo $form->open('captcha_test_form', 'POST', e_SELF);

echo e107::getSecureImg()->r_image();
echo e107::getSecureImg()->renderInput();

echo $form->submit('submit', 'Submit');
echo $form->close();

require_once(FOOTERF);
exit;
```

**Comment by Serios** [comment]
Thanks @lonalore  will try it. Looking at it, it should work fine.

**Comment by Jimmi08** [comment]
You should look at visual captcha plugin, its used there.

**Comment by lonalore** [comment]
@Jimmi08 If I remember well, `e107::getSecureImg()->r_image()` is not used in VisualCaptcha plugin.

**Comment by Jimmi08** [comment]
@lonalore 
Yes, but there was something with secure_image.  I see now that is different. Thanks
`e107::getOverride()->replace('secure_image::r_image',   'visualcaptcha_module::blank');`
