### ISSUE TITLE
image is not deleted from server 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2904]
Uploaded new image:
![image](https://user-images.githubusercontent.com/5429548/33798850-87e227e6-dd20-11e7-810a-6cd45430abbe.png)
Its there:
![image](https://user-images.githubusercontent.com/5429548/33798853-951e92a0-dd20-11e7-9e49-09e00f53a579.png)
After click on delete and confirm Are you sure
![image](https://user-images.githubusercontent.com/5429548/33798858-bbd522b0-dd20-11e7-84a4-164b0ccc8c5c.png)
nothing (no message), just list of images without this image, but file is still there.

With debug, the same. No next message, only normal debug in media manager.
![image](https://user-images.githubusercontent.com/5429548/33798889-1ecad7f2-dd21-11e7-8bc6-6a023cfac3e1.png)

**Comment by Moc** [comment]
Duplicate https://github.com/e107inc/e107/issues/802
