### ISSUE TITLE
SQL verification fails after latest commit

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#2909]
`online | online_ip, online_user_id | Index missing! | should beINDEX `online_ip_user_id` (online_ip, online_user_id);`

On an attempt to fix this issue the warning message is:

```
Update Unsuccessful [ALTER TABLE `e107_online` ADD INDEX `online_ip_user_id` (online_ip, online_user_id); ]
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'online_ip_user_id'
```
I cannot offer any further information as https://addons.mozilla.org/en-US/firefox/addon/e107-dev/ is not compatible with Firefox Quantum 57.0.2 (64-bit) Mozilla Firefox for Arch Linux.

**Comment by lonalore** [comment]
@NZCyrus Cameron is already working on this issue.

Btw @CaMer0n what happened with e107 Dev v2.0.0? As I see it is not available from Mozilla: https://addons.mozilla.org/en-US/firefox/addon/e107-dev

**Comment by CaMer0n** [comment]
@lonalore Addon was rejected. Please see Gitter for reasons.

**Comment by CaMer0n** [comment]
@NZCyrus @lonalore Please re-open if necessary.
