### ISSUE TITLE
Issue: Admin Area Timeout Unauthorized Access

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2911]
After going past a time limit while in the admin area form - you try to make changes, you get a white page that says Unauthorized Access! - Example: creating news - working on a long pried of time on the one news post. Hitting the submit button will give you a white page with Unauthorized Access. I've had this show up when I'm in the preferences area, and in plugin admin area's as well.

**Comment by Moc** [comment]
Did you try tweaking your settings? 

`Admin Area > Preferences > Security & Protection > Session Lifetime`
