### ISSUE TITLE
confusing setting (visual) of comment setting

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2913]
Comment manager:

 
![image](https://user-images.githubusercontent.com/5429548/33931565-a67c1036-dff0-11e7-821d-80645a619fe7.png)

Site preferencies:
![image](https://user-images.githubusercontent.com/5429548/33931532-958da01e-dff0-11e7-9f55-a39ba52ba525.png)

I was looking for blue yes.

**Comment by Moc** [comment]
@oxigeno2 can you please submit your fix as a pull-request?
