### ISSUE TITLE
Select box styling issue in FF Quantum and Chrome

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2916]
The drop-down menus display differently after the Firefox upgrade, causing some text to be unreadable due to a change of background color to gray and white for the optgroup labels.  

![image](https://user-images.githubusercontent.com/2825679/33963777-07a7bf58-e00b-11e7-9976-24d1854ece2b.png)

![image](https://user-images.githubusercontent.com/2825679/33963864-60b23bf0-e00b-11e7-80aa-d67ed6595310.png)

I'm looking for CSS suggestions/solutions so that the background color and test color remains dark, as it appears in its original (unselected) form: 

![image](https://user-images.githubusercontent.com/2825679/33964051-fdbb9ad6-e00b-11e7-9e6f-9f9620be5805.png)

**Comment by LaocheXe** [comment]
In bootstrap-dark.mini.css - On line 1479 - remove background:rgba(0,0,0,.3).  

.breadcrumb,.darkwell,.form-control,.hero-unit,.progress,.uneditable-input,code,input[type=date],input[type=time],input[type=datetime-local],input[type=month],input[type=text],input[type=password],input[type=datetime],input[type=week],input[type=email],input[type=url],input[type=tel],input[type=color],input[type=number],input[type=search],pre,select,textarea{box-shadow:0 1px 0 rgba(255,255,255,.1),0 1px 7px 0 rgba(0,0,0,.8) inset;background:rgba(0,0,0,.3)}

**Comment by tgtje** [comment]
Grr LaocheXe is fast  👍 ...  changing the LAST value (.3) is sufficient as test so far give. (personal taste which value where 255 is black)

**Comment by CaMer0n** [comment]
Thank you! Looks like it was some left-over css from the original darkstrap theme (bootstrap 2) 

Here's what I have now...

![image](https://user-images.githubusercontent.com/2825679/33966881-0dc521ae-e016-11e7-8913-7c5936d1a598.png)

**Comment by rica-carv** [comment]
CSS leftovers can be real headache... 👍
