### ISSUE TITLE
e107 forum error

### ISSUE THREAD

**Issue by CaptPot** [e107inc/e107#2919]
Hi,
I've just uploaded e107 and set a site up but when I click on the forum link i get this error

Warning: require_once(../../class2.php): failed to open stream: No such file or directory in /customers/f/1/6/uk-clan.com/httpd.www/forum/forum.php on line 14 Fatal error: require_once(): Failed opening required '../../class2.php' (include_path='.:/usr/share/php') in /customers/f/1/6/uk-clan.com/httpd.www/forum/forum.php on line 14

I'm new to this so I don't have a clue what I need to do to fix this, can anybody help with this problem.

**Comment by LaocheXe** [comment]
Sounds like u dont have all the files, reupload em

**Comment by rica-carv** [comment]
Weird why class2 is only missing in forum plugin.
If class2.php is not there, it should give an error in any page, even in index, no?

Anyway, try to reupload all files, as @LaocheXe stated, and if problem persists, let us know php and server version....

**Comment by Jimmi08** [comment]
Doesnt forum as your frontpage?

**Comment by CaptPot** [comment]
I've re-uploaded the folder from my original e107 download, no change, still get the same error. I then over-wrote the forum folder with a one from 2013!! and got this screen
![image](https://user-images.githubusercontent.com/34254497/34061136-bd25e9fc-e1de-11e7-857a-332c46101e46.png)

so it's trying to show the forum and not just the original error screen
"Warning: require_once(../../class2.php): failed to open stream: No such file or directory in /customers/f/1/6/uk-clan.com/httpd.www/forum/forum.php on line 14 Fatal error: require_once(): Failed opening required '../../class2.php' (include_path='.:/usr/share/php') in /customers/f/1/6/uk-clan.com/httpd.www/forum/forum.php on line 14"

anymore ideas as to how to fix this?

**Comment by rica-carv** [comment]
Check if permissions are correct on the folders....

**Comment by CaptPot** [comment]
Ive checked the folders and the permission are 776. I've checked the plug in and get the following
![capture](https://user-images.githubusercontent.com/34254497/34072530-cb2d7d38-e280-11e7-81b9-62cd1a8e0af5.JPG)

Any ideas??

**Comment by Jimmi08** [comment]
What is your url for forum? e107_plugins/forum/forum.php or forum/ or?

**Comment by CaptPot** [comment]
The links did show uk-clan.com/forum, so I uploaded folder to the main e107 folder and not the plugin folder, the url now shows uk-clan.com/index.php

**Comment by CaptPot** [comment]
I've went back into my admin area and got this warning
![capture1](https://user-images.githubusercontent.com/34254497/34072769-3479716c-e285-11e7-9017-07972a3cfcf5.JPG)
????help pls

**Comment by Jimmi08** [comment]
this is mistake:  "The links did show uk-clan.com/forum, so I uploaded folder to the main e107 folder and not the plugin folder, the url now shows uk-clan.com/index.php"

/forum -  is sef-url version of forum.   put everything back to e107_plugins folder

**Comment by Jimmi08** [comment]
Now, check if legacy path works:
uk-clan.com/e107_plugins/forum/forum.php
if not, you have problem with e107 and forum plugin itself  
if yes, problem is somewhere else. I've just installed forum plugin and path in sitelinks was /e107_plugins/forum/forum.php,  so you had to changed something after installation.
What did you do after it?

**Comment by Jimmi08** [comment]
@CaptPot here is your problem:  in /customers/f/1/6/uk-clan.com/httpd.www/forum/forum.php 
- there is missing one level in your paths  - e107_plugins folder (or any name for plugin folder), so path to class.php is wrong.

**Comment by rica-carv** [comment]
Somehow you messed the folder strucuture of e107. Just upload everything again as it is by default, and don't change the file structure or location....

**Comment by CaptPot** [comment]
Thanks for all of the help fellas, it's nearly working. I uninstalled the forum folder, reinstalled it in the plugin folder, it now points to "uk-clan.com/e107_plugins/forum/forum.php" I've been into the forum manager and created a couple of test parents
![capture](https://user-images.githubusercontent.com/34254497/34119981-f959dcd2-e41b-11e7-8ca0-854772d6874a.JPG)
but when I try to add forum sections the parent dropdown at the top of the screen is blank
![capture2](https://user-images.githubusercontent.com/34254497/34120057-436c62f4-e41c-11e7-9a1c-6f8b3da73213.JPG)

what am I missing? again thanks for all the help :)

**Comment by CaMer0n** [comment]
@CaptPot You might want to try the chatroom: https://gitter.im/e107inc/e107

**Comment by rica-carv** [comment]
Try clean browser & e107 caches...

**Comment by Jimmi08** [comment]
@CaptPot What version of e107 do you use? My forum page in admin looks different:
![image](https://user-images.githubusercontent.com/5429548/34123207-15a63ca6-e42f-11e7-9f5e-57acc399c949.png)

**Comment by CaptPot** [comment]
I'm not sure what version it was but I cleared all of the caches, reloaded and then updated it to this version
![capture3](https://user-images.githubusercontent.com/34254497/34128799-da149a10-e439-11e7-8e18-4a58132c2f03.JPG)
Ive created some parent and child topics, which now show on the site
![capture](https://user-images.githubusercontent.com/34254497/34128859-04d5d7dc-e43a-11e7-9762-2d56c387e2a7.JPG)
but when you click on the title nothing happens. I've changed the permissions to 777 but that hasn't made a difference.

**Comment by Jimmi08** [comment]
Now it looks correct. Check your SEF-URL setting and URL configuration for forum.

**Comment by CaptPot** [comment]
I left that box blank so it auto created

**Comment by CaMer0n** [comment]
@CaptPot They are auto-created when you save.

**Comment by CaptPot** [comment]
Guy's sorry for the delay. Thank you so much for your help fixing this problem, 1 last thing when people post it shows them as anonymous?, what setting do I need to change?

Merry Christmas :)

**Comment by Moc** [comment]
Please create a new issue if the 'anonymous' issue still occurs.
