### ISSUE TITLE
report speed 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2920]
Hi,
 again no idea why. I just noticed this.

this line in header_template.php  

`$body_onload .= " id='layout-".e107::getForm()->name2id(THEME_LAYOUT)."' ";`

causes this time delay
![image](https://user-images.githubusercontent.com/5429548/34056046-e3553a40-e1d1-11e7-8a0a-11e10a4428f2.png)
I was just curious why some of my themes have this and some not, the reason was that some of them had BODYTAG defined, so this part of code wasn't executed.

**Comment by CaMer0n** [comment]
@Jimmi08 Did it resolve itself or was something else causing it?

**Comment by Jimmi08** [comment]
It was moved (time) to next load of e107::form().   So it's time of first loading any object (or better handler) and time is used for require_once().    I was only surprised that e_form is always loaded as object not singleton, other handlers behave different way. But because I don't understand this, I closed it.
