### ISSUE TITLE
Bug: LAN Missing

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2921]
Admin Area - Database - Scan Plugins - Missing Lans

![capture](https://user-images.githubusercontent.com/5818022/34064347-e35cc94a-e1bd-11e7-956f-f2ae704f0eda.JPG)

**Comment by CaMer0n** [comment]
@LaocheXe Please try again, it should be fixed now.

**Comment by LaocheXe** [comment]
It's fixed
