### ISSUE TITLE
wrong path in search in download plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2923]
I noticed that search in download plugin didn't work with sef url /download

path there is:  `action='".e_BASE."search.php'>";`

![image](https://user-images.githubusercontent.com/5429548/34073420-c8a02c64-e299-11e7-82b2-7dc70f6a38b6.png)

if I use: /e107_plugins/download/download.php
![image](https://user-images.githubusercontent.com/5429548/34073431-f7bd07ec-e299-11e7-91d8-558228a0b916.png)
adn search works

**Comment by CaMer0n** [comment]
@Jimmi08 Try changing to ```action='".e_HTTP."search.php'>";```  
Does it help?

**Comment by Jimmi08** [comment]
Yes, it's correct now

**Comment by Moc** [comment]
I thought this was already fixed a long time ago... Meh.. haha
