### ISSUE TITLE
News image 

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2924]
I put the code into the news_template.php:
`<div class="default-item-mainimage">
      <a href="{NEWSURL}">
        {SETIMAGE: w=1200&h=1000}
        {NEWSIMAGE: item=1&type=tag}
        <div class="default-item-category">{NEWSCATEGORY}</div>  
        <div class="default-item-bottom-box">    
          <div class="default-item-date">{NEWSDATE=yyyy. M dd.}</div>
          <h2 class="default-item-title">{NEWS_TITLE: link=1}</h2>
        </div>  
      </a>           
    </div> `

And on the page: 
No < /a> on the end ... and < /a> after the image (I insert the type=tag in the image).
Why appears wrong?
Thanks help!

**Comment by CaMer0n** [comment]
I don't think divs are permitted inside `<a>` tags.  ;-)

**Comment by fizi** [comment]
please delete this issue.

**Comment by rica-carv** [comment]
You can also close it yourself..... It was you who opened it, you can also close it....
