### ISSUE TITLE
Custom pages and SEF URL's problem

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#2928]
I have a very strange problem with system properly detecting which template to assign to a custom page. For example I have two pages with somehow similar SEF url's taxation-procedures and taxation-options they both are set to use different custom template, however the system assigns same template to both of them if I change SEF to for example  taxation-procedures and options-taxation the custom template is properly assigned to second one.

**Comment by CaMer0n** [comment]
@Serios Are you referring to the theme settings page, where you change theme layout depending on the URL ?

**Comment by Serios** [comment]
Yes, I set the url's there and then on front end they gets messed up.

**Comment by CaMer0n** [comment]
If you remove the hyphen from both SEF Urls.. does it fix the problem? I suspect the hyphen may be causing issues.

**Comment by Serios** [comment]
@CaMer0n, yep that's the problem I think. When there is no hyphen, everything works as it should.

**Comment by CaMer0n** [comment]
@Serios Thank you. I'll look into it.

**Comment by CaMer0n** [comment]
@Serios I have been unable to reproduce this problem. Have you tried adding `/` before each URL ?
ie.

    /taxation-options

    /taxation-procedures

**Comment by Moc** [comment]
@Serios Any feedback? :)

**Comment by Serios** [comment]
@Moc the suggestion from Cameron solved the issue

**Comment by Moc** [comment]
Thanks for letting us know!
