### ISSUE TITLE
Jquery exception

### ISSUE THREAD

**Issue by mattexb** [e107inc/e107#2931]
Hi everybody,

i'm haveing this message when i call a plugin page, core or custom ones:

```
VM1473 jquery.js?0:1468 Uncaught Error: Syntax error, unrecognized expression: http://test.marsupiogroup.it/e107_plugins/newsletter/admin_config.php?mode=main&action=list
    at Function.Sizzle.error (VM1473 jquery.js?0:1468)
    at Sizzle.tokenize (VM1473 jquery.js?0:2125)
    at Sizzle.select (VM1473 jquery.js?0:2546)
    at Function.Sizzle [as find] (VM1473 jquery.js?0:869)
    at jQuery.fn.init.find (VM1473 jquery.js?0:2792)
    at new jQuery.fn.init (VM1473 jquery.js?0:2909)
    at jQuery (VM1473 jquery.js?0:75)
    at HTMLAnchorElement.<anonymous> (VM1490 admin.jquery.js?0:548)
    at Function.each (VM1473 jquery.js?0:365)
    at jQuery.fn.init.each (VM1473 jquery.js?0:137)
```

i saw the issue starts in a call:

`var id = $(this).attr("href"), hash = id.split('#')[1], form = $('.admin-menu')[0]; // FIXME - a better way to detect the page form`

at line 545 of e107_web/core/admin.jquery.js

browser chrome  63.0.3239.84 64bit

P.S.
very nice work guys e107 is a lot of work very well done.
The only comment i want to do is that i feel it could be better documented; there are a lot of powerful funtionalities for coders and is a shame there is no documentation for them.
Anyway ty for your work!

**Comment by fwhcat** [comment]
Here is a direct link to the part of code in fault:

https://github.com/e107inc/e107/blob/14345358b17f60b2352e41c9eb55416b68f2889f/e107_web/js/core/admin.jquery.js#L552

**Comment by Moc** [comment]
@lonalore any idea?

**Comment by Moc** [comment]
@SimSync Not sure if it's still relevant but any idea on this one?

**Comment by mattexb** [comment]
I still have the same issue if anyone needs to know

**Comment by CaMer0n** [comment]
@mattexb Thank you! Do you have some third-party plugins installed?

**Comment by mattexb** [comment]
I have some plugin I have written following examples and watching main plugins

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
