### ISSUE TITLE
Feature request - to be able download theme from e107.org from github repository

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2935]
- similar way how languages or core works
- without need to upload full theme to e107.org - just adding url to theme.xml to zip archive or repository (no idea what is easier)
- upload size on e107.org is limited, with demo content (images) theme zip could be too big.

**Comment by CaMer0n** [comment]
@Jimmi08 How large is your .zip?

**Comment by Jimmi08** [comment]
4,7 MB.  demo images do this size.  
Just idea - how to do this similar way like maw his paid themes.  
I would put there link for download zip from github.

**Comment by CaMer0n** [comment]
@Jimmi08 It's reserved only for paid themes. I'll increase the upload limit in the meantime. ;-)

**Comment by Jimmi08** [comment]
I still don't get it.  So if I say that my theme is paid for 0,01 €, then I can use it?  The paid theme goes to the other site where is blocked download link or does something more? 

My point of view is:  if I upload theme to e107.org, it looks like theme is finished or complete or fully tested.  Or better words - e107.org has this way some responsibility for the quality of themes. 
But if I put there only link to github repository, after clicking on download link e107.org will be able to count the number of downloads, I will know that theme is used and I will have motivation to finish it.  Or made paid pro version.  

Nevermind, "paid" theme solves this.  Thanks for tip.

**Comment by CaMer0n** [comment]
@Jimmi08 The number of downloads should display for each of your themes here: 
https://e107.org/developers

**Comment by Jimmi08** [comment]
I know, it's great,  I just don't know if it counts paid theme with redirect to url, not real download.
