### ISSUE TITLE
Menus are added twice when adding

### ISSUE THREAD

**Issue by ghost** [e107inc/e107#2936]
Hi Developers,

can you please check with e107 v2.1.7 the addition of the menus in the backend. When I do this, all menus are added twice and three times.

Thanks in Advance.

P.S. Maybe it's a bug, but I do not know exactly.

**Comment by Jimmi08** [comment]
After you add one menu, it is still checked, so if you add new one, that first one is added too.  This is because adding one menu to more layouts.  
I can't confirm that something is wrong.

**Comment by Moc** [comment]
@AlexL777 Did you re-check to make sure the checkboxes are correctly set?

**Comment by Jimmi08** [comment]
@Moc this can be closed. It works correctly.
