### ISSUE TITLE
5 comments on the page

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#2937]
Почему на страницах появляются только 5 комментариев?
Если пишут шестой то пятый комент пропадет.

Why do pages appear only 5 comments?
If you write the sixth the fifth koment lost.
Somewhere in the settings maybe there are limitations? All checked - not found.

**Comment by Jimmi08** [comment]
What theme and e107 version do you use?
Do you mean "страницa" like pages or comment page?  I have no problem to post 6 comments to page.

**Comment by 214945** [comment]
Version 2.1.7
The theme of the website BS_Magazine_01
So far seen on the pages page php. And this is on two sites. Both sites were migrated from version 0.7.26

**Comment by Jimmi08** [comment]
Have it. Maybe.
If you set Turn on nested comments OFF (no nested comments), it works correctly on news. Pagination is displayed if there are more than 5 comments.
But with pages there is no pagination, only last 5 comments are displayed.
This is missing with pages:
![image](https://user-images.githubusercontent.com/5429548/34457181-9a50b0ca-eda9-11e7-9308-26c3d710f34e.png)

**Comment by 214945** [comment]
Jimmi08 - Write in your language. With English not exact translation is impossible.

**Comment by Jimmi08** [comment]
I just confirmed your issue  -  for pages and only with pref _Turn on nested comment_ set OFF.  I am not able to fix it.
Sorry, they are already used to my English. 

Я только что подтвердилa вашу проблему - для страниц и только с pref // Параметр Turn on nested comment//Включить вложенные комментарии  OFF // Нет .  Я не могу это исправить.

**Comment by Moc** [comment]
Closing in favour of #2425

**Comment by Moc** [comment]
Related #2425
