### ISSUE TITLE
Issue with thumbs.php?

### ISSUE THREAD

**Issue by foxbg** [e107inc/e107#2939]
I've updated from 1.x to 2.1.7.
Uploaded files and executed dbupgrade.

I've noticed that thumb images are missing.

Following similar issues from help I've updated to 2.1.8 (git), but issue persist. 

PHP Version 5.6.32

Here is variable part from e107_config.php

$ADMIN_DIRECTORY     = "e107_admin/";
$FILES_DIRECTORY     = "e107_files/";
$IMAGES_DIRECTORY    = "e107_images/";
$THEMES_DIRECTORY    = "e107_themes/";
$PLUGINS_DIRECTORY   = "e107_plugins/";
$HANDLERS_DIRECTORY  = "e107_handlers/";
$LANGUAGES_DIRECTORY = "e107_languages/";
$HELP_DIRECTORY      = "e107_docs/help/";
$DOWNLOADS_DIRECTORY = "e107_files/downloads/";

Where to look?
Did I miss a step in upgrade?
Any other information needed?

In addition in admin I have message for new version 2.1.0 even I have newer.
Could this be related?

**Comment by Jimmi08** [comment]
check htaccess  (there needs to be one one) - compare with e107.htaccess
try to insert new image (fe. in news) if this is general problem or only update problem
missing information -  do you use default or your own folder names?

**Comment by Moc** [comment]
In addition to checking the htaccess file, also try clearing the cache(s). Then also check for database updates in 'tools > check for database updates'

**Comment by foxbg** [comment]
After upgrade I've replaced old .htaccess files with the one from new package.
Added 2 variables - did not help.
Tried to add new image - after clicking on upload I got popup saying there was an error.

Cache was cleared, there are no DB updates.

**Comment by Jimmi08** [comment]
Check updates manually In Tools/Databases/Check updates
See Console errors (F12) and put screen here what is path for thumbnail

And -  resave preferencies.  Images are now under hash folder.  In fact, if you go to preferencies, to File uploading, you will see how your hash looks. 
![image](https://user-images.githubusercontent.com/5429548/34482657-ad3008f0-efb9-11e7-8dce-fe34a7d3c21d.png)

Check if you have the same folder under e107_media folder.

**Comment by Jimmi08** [comment]
And check if this is not the same issue
https://github.com/e107inc/e107/issues/2752

**Comment by foxbg** [comment]
In console I have error 500 for images source is in /media/img/60x0/<date>/<image>
I've checked .htacces and it has rewirite rule.
RewriteRule ^media\/img\/([-A-Za-z0-9+/]*={0,3})\.(jpg|gif|png)?$ thumb.php?id=$1 [NC,L]


for 2752 in what file to check?

**Comment by Moc** [comment]
Please check the Apache error log, HTTP 500 errors usually put a full error message in that error log. This may help us narrow down the cause of your issue.

**Comment by foxbg** [comment]
Unfortunately my provider does not provide error logs. :(
Will have to copy somewhere else and test again.

**Comment by foxbg** [comment]
Found the issue...

After review of .htaccess
uncommented line 57 to
RewriteBase /
