### ISSUE TITLE
Members only site, forgot password email sends to login page

### ISSUE THREAD

**Issue by Talnz** [e107inc/e107#2948]
When user clicks on email link to fpw.php, it sends them to the login screen - where they forgot password.  Page is being redirected to index.php instead of fpw.php code.

**Comment by CaMer0n** [comment]
@Talnz Thanks for posting the issue. Please update your files with the ones here on Github.  (specifically, fpw.php) and let me know if the change helped. Thank you.

**Comment by CaMer0n** [comment]
Fix confirmed. Thank you @Talnz
