### ISSUE TITLE
Downloading and installing plugin from https hosted site does not work

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#2951]
If you want to install a plugin from the admin section then you cannot do that when your site is running under https. You get an error that the link is wrong.
Might be a server issue to as I also got link error while running under http. Metatag installed under http, not https, goto-top give error in both situtations. Did not check all plugins.
Also got errors like 'unable to continue'. No clue why.

**Comment by 214945** [comment]
Normally with HTTPS all the plugins downloaded and installed, three site work.
goto-top - buggy plugin.

**Comment by aducom** [comment]
Tnx, for reply.Must be on my side then...
