### ISSUE TITLE
Feature box: problem with install on multilang site

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2953]
Result after installation:

![image](https://user-images.githubusercontent.com/5429548/34603155-04aab382-f203-11e7-9bfe-07b2ad85b95a.png)

**Comment by tgtje** [comment]
related? #2985

**Comment by tgtje** [comment]
Do not know if any progress was made or fixed; testedApache/2.4.39 (Win64) OpenSSL/1.1.1b
(host: localhost) PHP Version 7.3.5 MySQL 10.1.40-MariaDB Database: xxxxx 
PDO: Enabled
Mode: NO_ENGINE_SUBSTITUTION
Running English, German and Dutch, all fine

**Comment by Jimmi08** [comment]
@tgtje Thanks
