### ISSUE TITLE
gallery image - I can't get image tag or src with correct size

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2954]
I need thumb of gallery image with desired size.
This worked before:

```php
{GALLERY_THUMB=w=200&h=200&thumbsrc}
```
in this:
```php
<img src="{GALLERY_THUMB=w=200&h=200&thumbsrc}" alt="{GALLERY_CAPTION=text}" class="img-fluid" />
```

But now there is code e_shortcode:

```php
		$srcFull = $tp->thumbUrl($this->var['media_url'], $this->attFull);
    
 ...
		if(isset($srcFull))
		{
			return $srcFull;
		}
		elseif(isset($parms['thumbsrc']))
		{
			return $tp->thumbUrl($this->var['media_url'], $att);
		}
```
which always returns src with $this->attFull  options, so it returns full image size.

**Comment by CaMer0n** [comment]
Did you try `{GALLERY_THUMB: w=200&h=200&thumbsrc}` ?

**Comment by Moc** [comment]
@Jimmi08 any feedback? :)

**Comment by Jimmi08** [comment]
I solved it somehow, no idea how now.  I will create new issue if this happens again. Thank you
