### ISSUE TITLE
with multilan true 'post' for write array option doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2973]
Code:
```
			'site_slogan'		=> array('title'=> 'Site Slogan', 'tab'=>0, 'type'=>'text', 'data' => 'str', 'help'=>'', 'multilan'=>true,
				'writeParms' => array( 'size'=>'block-level',
				 'post' => 'xxx'),
			), 
```
with multilan false:
![image](https://user-images.githubusercontent.com/5429548/34738959-0e7e3bec-f57b-11e7-9544-30b7edc7588d.png)

 
![image](https://user-images.githubusercontent.com/5429548/34739099-7f5ca45c-f57b-11e7-925b-13486732139d.png)

**Comment by CaMer0n** [comment]
True, because 'post' is replaced by the 'multilan' icon. So you want 'post' to appear after the icon, correct?

**Comment by Jimmi08** [comment]
Yes, or be able to get help rendered under field not as tooltip.

**Comment by CaMer0n** [comment]
@Jimmi08 Can this be closed now?
