### ISSUE TITLE
Q  how to display full image in page custom field

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2974]
How to set parameters to display image with full size (or any size)

![image](https://user-images.githubusercontent.com/5429548/34847645-5452e986-f71c-11e7-8d52-3e95740868e7.png)

I tried w=auto, aw=auto, w=600, still zero. 
I can't find the link to example for sizing images (how to get full size)

![image](https://user-images.githubusercontent.com/5429548/34847599-338e3e30-f71c-11e7-9e40-d228ec5192be.png)

Thanks

**Comment by CaMer0n** [comment]
Did you try w=0 ?

**Comment by Jimmi08** [comment]
Yes, still zero.  No priority, I can solve it by inserting full url.

**Comment by tgtje** [comment]
Inquiry/remark/notice : I can understand the need for easy param setting; however in a normal setting (suppose it works) it will conflict with responsive design (eg fitting) ??? The only setting for the params i can find that handle large sizes are set in bb_youtube. Possible that core has limits on w ??

On the other hand : when i add an image by media manager (and it is full size) i can by appearance give the size in px. That works , but again responsive fits the outcome.... (you see the true size on a 'full page display" (as handled by viewport)

**Comment by Jimmi08** [comment]
@tgtje not fully understand, but pixels should be never used in responsive design and only way how to rid them is use w=0 or w=auto (I still don't have time to check what works) and it should use 100% then.
e107 defaults are 20px or 100px if you don't set size, it displays nothing

**Comment by tgtje** [comment]
(little explain) I just set pixels (if needed) for image via insert media manager/appearance. If i would use a full page layout, the image then is displayed in the max available width (by viewport). 
The responsive part does still its work (as ruled by system). 
So not using pixels as design feature, but as display size. Which in principle is kind of same as param.
However using param as eg w= auto should (in meaning) do the same..but than again how to overcome the default AND the thumb involvement.... (maybe that is reason youtube bb uses different params.

**Comment by Jimmi08** [comment]
params are ignored
this works>  {SETIMAGE: w=0&h=0}
