### ISSUE TITLE
Issue: DB Verify

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2975]
As a developer works on a plugin, that plugin sql table entities may change. Using the Database Verify to update/fix missing entities is good, but doesn't remove any entities that have been removed from the plugin_sql.php.

Example:

Before:
Table  planets
~p_id
~type
~location
~system
~color
~area

We remove ~area, but add ~image

File gets updated:
Table planets
~p_id
~type
~location
~system
~color
~image

After DB Verify/Fix the table keeps ~area, and add's ~image. There no way to add remove from table in the future?

**Comment by CaMer0n** [comment]
This is because there is a high likelihood of data-loss when removing a field.  As a precaution, it is limited to the xxxx_setup.php file instead.

**Comment by LaocheXe** [comment]
Roger that
