### ISSUE TITLE
Forum template

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2978]
The all forum items have caption in template (forum_viewforum.php etc.) exception - forum main page, tracked page, stat page. Please make the caption for all page templates. Thanks!

**Comment by fizi** [comment]
To this: forum id. forum main page  and all other forum pages  no ID

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/2960

**Comment by fizi** [comment]
And some pages have < ! -- tablestyle: style=maincontent id=default -- >

**Comment by fizi** [comment]
Jimako: Can You make the template for forum stat?

**Comment by Jimmi08** [comment]
@fizi please,  create separate issue, maybe @rica-carv can help too.  Somebody was maintain  forum templates, I think it was him, not sure.

**Comment by rica-carv** [comment]
I've tryed to remove and update all harcoded html & old templates to v2.x standards, but i might missed something along the way...
Sorry...

**Comment by Moc** [comment]
I am pretty sure all ID's have now  been added correctly. If there are specific missing, please let us know.
