### ISSUE TITLE
using {SITELOGO: h=xx}  - errors in console

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2981]
I thought that this was already fixed but it's back again

![image](https://user-images.githubusercontent.com/5429548/35033417-dca7289a-fb6a-11e7-87c5-0bfdcb8657d2.png)

using shortcode {SITELOGO: h=xx}  only with height param is standard way used in default bootstrap3 theme too.  Check boostrap branding shortcode.

**Comment by LaocheXe** [comment]
In Defiantzstrap3 (Modified Bootstrap3 theme) I have in theme_shortcodes.php 

return e107::getParser()->parseTemplate('{SITELOGO: h='.$prefh.'}',true);

I have not hit that issue yet

**Comment by Jimmi08** [comment]
This is still issue. Maybe theme.php is parsed differently.

Using {SITELOGO} - no errors in console
Using {SITELOGO: h=100} - the same errors

![image](https://user-images.githubusercontent.com/5429548/41795181-27dcc316-7662-11e8-8f19-dc25ebd592d5.png)

**Comment by Moc** [comment]
@LaocheXe Is this still an issue?

**Comment by LaocheXe** [comment]
@Moc I don't know, never had the issue, should check with @Jimmi08

**Comment by Jimmi08** [comment]
Still problem. Used directly, not parsing template:

`{SITELOGO: h=100}`
in Gameplus theme from Fizi in $LAYOUT['_header_'] 

![image](https://user-images.githubusercontent.com/5429548/52526611-a3cae380-2cbb-11e9-81b3-cc3f83abe1fb.png)

**Comment by Jimmi08** [comment]
Confirmed with the latest version: 
But only Chrome has a problem. Firefox no errors.

![image](https://user-images.githubusercontent.com/5429548/53400654-a4979100-39ae-11e9-988a-c4ea44ae4b28.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I'll fix this after 2.2.1 is out  Please remind me. 
https://stackoverflow.com/questions/26928828/html5-srcset-mixing-x-and-w-syntax

**Comment by CaMer0n** [comment]
@Jimmi08 @LaocheXe This commit should fix it. Please re-open the issue if you notice any unexpected behavior.
