### ISSUE TITLE
e107::css(), e107::js(), etc. in myplugin_menu.php not working

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#2983]
```
<?php

if (!defined('e107_INIT')) { exit; }

e107::css('inline','div { background-color:#000000; }');
e107::js('inline','window.alert("Hello World");');

$ns 	= e107::getRender();
$caption = '<h2>Some caption</h2>';
$text = '<div>Some text</div>';

$ns->tablerender($caption, $text, 'myplugin_menu'); 

?>
```

AFAIK: This should render all div on the page with a black background and give an Hello World alert popup.

**Comment by CaMer0n** [comment]
Short answer: it's not meant to.   Use e_header.php to load the css/js.

**Comment by Jimmi08** [comment]
@CaMer0n slideshow_menu in gallery does this.  Problem with e_header.php is that then that css and js is loaded on whole page. You can't test if you are on plugin page because menu can be at contact page etc.  Why load google maps script on all pages when I need it only in one menu on contact page?

**Comment by CaMer0n** [comment]
Actually, you can. 

```
if(e107::getMenu()->isLoaded('slideshow'))
{
   e107::css('inline','div { background-color:#000000; }');
}
```
