### ISSUE TITLE
The problem with the entrance to the site.

### ISSUE THREAD

**Issue by 214945** [e107inc/e107#2984]
If you disable in the settings of the website "monitor users" on the website log in does not work, error "the username and password already in use".
Turn the tracking back and the entrance to the site is working fine.
Engine version 2.1.7

**Comment by CaMer0n** [comment]
Thank you @214945 . Could you please send a screenshot of this "monitor users" preference page?

**Comment by 214945** [comment]
![78999](https://user-images.githubusercontent.com/25720089/35167100-04de3896-fd76-11e7-9dbf-30a781c9a289.jpg)

**Comment by CaMer0n** [comment]
Thank you @214945 Would you mind updating from Github, and trying again?

**Comment by 214945** [comment]
Updated from Github, all works well. Did the update and checked on two sites.
Thank you.

**Comment by CaMer0n** [comment]
Excellent! Thank YOU @214945 !!

**Comment by Evgura** [comment]
Yesterday I updated the website with Github, and again the same thing happened as written above. If the "Enable online tracking of users," it is impossible to enter the site.
"This combination of user name and password is already in use."
