### ISSUE TITLE
tinymce plugin 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2985]
Latest github, result after installing plugin. Only English site (one language)

![image](https://user-images.githubusercontent.com/5429548/35153982-c86aa482-fd28-11e7-9ec9-7355cb3e9ee9.png)

**Comment by 214945** [comment]
e107 Версия 2.1.8 (git) 
Everything is normal. Russian language is.
![34560](https://user-images.githubusercontent.com/25720089/35155591-f2492478-fd4f-11e7-9360-49bf69153c01.jpg)

**Comment by Jimmi08** [comment]
Do you have Russian and English languages or only Russian?

**Comment by 214945** [comment]
Is and English.
![345600](https://user-images.githubusercontent.com/25720089/35155750-880b8672-fd50-11e7-9dcb-1ac382ef795e.jpg)

**Comment by Jimmi08** [comment]
It works for me on multilang site too. But not on only English site.

**Comment by 214945** [comment]
PHP 5.4.45

**Comment by CaMer0n** [comment]
@Jimmi08 I am unable to reproduce it either. Did you try Debugging 'Includes' ?

**Comment by 214945** [comment]
@Jimmi08 You have a refresh icon at the top, try to update the database.

**Comment by Jimmi08** [comment]
@214945 Core db is updated, that icon is from plugin I am working on.

![image](https://user-images.githubusercontent.com/5429548/35167553-4b40bd7e-fd56-11e7-834f-0f46938a3077.png)
/e107_plugins/tinymce4/admin_config.php 
/e107_plugins/tinymce4/e_header.php 

English_admin.php it's not listed in included files. 

It's not important now (not have time) but I will look for more details.

**Comment by tgtje** [comment]
The post refers to a **locale folder**( which github file does not have; nor in translations)
Sorry mentioned it before in relationship, yes or no locale or root...

**Comment by tgtje** [comment]
Just adding some testing.... (2.1.7/2.1.8) Notices : 
Notice Use of undefined constant TMCEALAN_1 - assumed 'TMCEALAN_1', Line 1403 of XXXXXX \e107_handlers\admin_ui.php  (2; 3;4 5 and 6 too)..
Further testing showed me this : use of lan call : ` e107::lan('tinymce4','admin', 'true'); `

TRUE is surrounded with quote (single prime)...But i am unsure (tests do give good results...afaiks) when set to _true without quote_ OR commented the line out completly> all works as should (either english only, or added language). 
Maybe (just maybe) the lan call is in this case of no use, but interfers in certain conditions?)

**Comment by CaMer0n** [comment]
Corrected the 'true' in quotes. @Jimmi08 does it help?

**Comment by Jimmi08** [comment]
the same. Nevermind, it's not so important (looks like only I have problem)
But I noticed this:
![image](https://user-images.githubusercontent.com/5429548/35199267-412e70ae-fefc-11e7-9e9e-bd625845a59b.png)

If I click repair plugin setting, it says Repaired (green message) but that icon is still there.
Reinstallation didn't help. 

I will debug this when I will time.
