### ISSUE TITLE
Issue: e_user.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2986]
Fatal error: Cannot declare class forum_user, because the name is already in use in /e107/e107_plugins/roster/e_user.php on line 14

In line 14 is this: class roster_user // plugin-folder + '_user'

Got this for testing, got a table that has user_id in it, idk if I need a filter, the e_user.php in forum plugin I dont see such query...

if (!defined('e107_INIT')) { exit; }

// v2.x Standard 
class roster_user // plugin-folder + '_user'
{		
		
	function profile($udata)  // display on user profile page.
	{
		$sql = e107::getDB();
		$service_records = $sql->retrieve('service_records_sys', '*', true);
		//$query1 = "SELECT * FROM ";

		$var = array(
			0 => array('label' => "Clone Number", 'text' => $service_records['clone_number'], 'url'=> e_PLUGIN_ABS."roster/roster.php")
		);
		
		return $var;
	}
}

**Comment by CaMer0n** [comment]
@LaocheXe Could you please send me your plugin? I guess you were viewing user.php when this error occurred?

**Comment by LaocheXe** [comment]
yes on user.php - I no longer get that error after doing other test with the query.

$service_records = $sql->retrieve('service_records_sys', '*', true);  <--- that caused the issue

The Fix: $service_records = $sql->retrieve('service_records_sys', '*', 'WHERE user_id = ' .$udata('user_id'), true;


For future reference, having $udata(user_id) should be added to the documentation for e_user.php <--- had no idea on how I should filter the user_id for the pages till I went looking and compaired the forum and chatbox plugins.

**Comment by Moc** [comment]
@LaocheXe Is this still an issue?

**Comment by CaMer0n** [comment]
@Moc I'm not sure.. I was never able to reproduce it. Would need someone experiencing the issue to test.

**Comment by CaMer0n** [comment]
I believe it can.
