### ISSUE TITLE
Log plugin stats template

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2987]
Jimako: can You make the template for log plugin stats page? (the template is hardcoded)

**Comment by Jimmi08** [comment]
@CaMer0n   Any plans for this plugin?

**Comment by CaMer0n** [comment]
@Jimmi08 No, it's one of the oldest ones. Myself I use Awstats.

**Comment by Jimmi08** [comment]
I can do it this way:
https://github.com/e107inc/e107/pull/2988
step by step. time issue.
