### ISSUE TITLE
Log plugin stats - report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2989]
While templating I noticed this  (I don't want to mix this with templates)

- frontend delete button doesn't work (404) - alltimevisits
![image](https://user-images.githubusercontent.com/5429548/35182914-63bf789a-fddd-11e7-8737-f730d7365175.png)
`<a href='".e_SELF."?{$action}.rem.".rawurlencode($key)."'`

- browser link doesn't work - browser stats
![image](https://user-images.githubusercontent.com/5429548/35182929-a7df79f8-fddd-11e7-8c5a-ae4f7786ec7d.png)
`e_SELF."?".($show_version ? "3" : "14").($this -> order ? "" : ".1" )`

- I don't see any ouput difference in this code (why is there test for $entries?):
```
($entries == 1 ? "<td class='forumheader3' style='width: 70%;'>".$this -> bar($percentage, $info)."</td>" : 
          "<td class='forumheader3' style='width: 70%;'>".$this -> bar($percentage, $info)."</td>")
```

- operating system
hardcoded strings
`($this -> order ? "sort by total" : "sort alphabetically")`

**Comment by CaMer0n** [comment]
@Jimmi08 What if you replace `e_SELF` with `e_REQUEST_SELF` ?

**Comment by Jimmi08** [comment]
I will try but I don't want to mix different things.

**Comment by Jimmi08** [comment]
@CaMer0n no, it didn't help
Correct path should be `/e107-master/e107_plugins/log/stats.php?3.1`
but with e_REQUEST_SELF there is still:
`/stats/?3.1`
 
Couldn't be problem here in e_url.php ?
regex'			=> '^{alias}/\?([\d]*)$'
d is digit and there is "3.1" - string

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, this appears to be the problem.

**Comment by Jimmi08** [comment]
Closing this, because log plugin has separate repo and this is too old, no idea how it works now and if this is still issue.
