### ISSUE TITLE
weird error e107::unserialize() Parser Error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2990]
dimante have site where xml import did weird things, So I asked  for user account as admin.
And I ended with this error. But original mainadmin (first) doesn't see anything like this.

![image](https://user-images.githubusercontent.com/5429548/35185702-bc0a78e4-fe08-11e7-9e94-056731659ed0.png)
Only not familiar message is this one:
` Undefined index: SERVER_ADDR, Line 174 of C:\inetpub\wwwroot\e107_JMG_DEV\e107_handlers\iphandler_class.php`

**Comment by Jimmi08** [comment]
If I check Correct Permission in Tools, I get this error:
`Failed applying filemode '755' on directory '../' `-> the directory '../' will be skipped from recursive chmod Failed applying filemode '755' on file '../cron.php'`

**Comment by CaMer0n** [comment]
@Jimmi08 @Moc I believe this one has been fixed. Hopefully it doesn't break other prefs.
