### ISSUE TITLE
fetch() vs php 5 and php 7.1

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2992]
I have this code (in init() filling dropdown values):

```
  		if(e107::getDb()->select('element_type'))
  		{ 
  			while ($row = e107::getDb()->fetch())
  			{      print_a($row);
  				$id = $row['element_type_id'];
  				$categories[$id] = $row['element_type_id']." - ".$row['element_type_note'];
         
  			}
  		}
```
It works normally in php 5.6 - $row is printed
but in php 7.1  is not and dropdown is empty

If I debug SQL  -  no error and 3 rows are returned (correct)
![image](https://user-images.githubusercontent.com/5429548/35192681-ab5bb65e-fe97-11e7-9f70-ffde8a7d7dcd.png)

If I replace it by retrieve() this way, it works:
```
  		if($allRows = e107::getDb()->retrieve('element_type', '*', '', true))
  		{  
  			foreach($allRows as $row)
  			{  print_a($row);  
  				$id = $row['element_type_id'];
  				$categories[$id] = $row['element_type_id']." - ".$row['element_type_note'];
           
  			}
  		}
```
but there is problem with  dropdown then.
```
      print_a($categories);
  		$this->fields['element_type_id']['writeParms']['optArray'] 		= $categories;	   // in case you want to add other parms?
```
$categories are filled on php 5 and dropdown works
$categories are filled on php 7.1 but dropdown doesn't work,  is empty

After changing to:
`$this->fields['element_type_id']['writeParms'] 		= $categories;`
dropdown works with 7.1 too

Field is defined this way (nothing unsual)
```
		  'element_type_id'       =>   array ( 'title' => "Category", 'type' => 'dropdown', 'data' => 'int', 'width' => '5%', 'help' => '',  'filter'=>true,  'inline' => true,
       'readParms' => '', 'writeParms' => '', 'class' => 'left', 'thclass' => 'left',  ),
```
This 
```
  $this->fields['element_type_id']['writeParms']['optArray'] 		= $categories;
```
has output at 5.6: 
![image](https://user-images.githubusercontent.com/5429548/35192881-5f6954ec-fe9a-11e7-9884-1ec61e64ae5c.png)
in 7.1
![image](https://user-images.githubusercontent.com/5429548/35192888-6f91171a-fe9a-11e7-8456-e49e99a17858.png)

but If do this in 7.1, it's correct:
      $this->fields['element_type_id']['writeParms'] 		= $categories;
      $this->fields['element_type_id']['writeParms']['optArray'] 		= $categories;

**Comment by CaMer0n** [comment]
Make sure `writeParms` is an array in your `$fields` array. 

`$fields['element_type_id'] = array(.....'writeParms' => array() ); `

**Comment by Jimmi08** [comment]
Yes, this was problem.   Thanks
