### ISSUE TITLE
media manager php 5  vs 7.1.12

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2993]
The easiest solution is that I am blind and I don't see difference between data.

I have **preferencies** and there are 2 image fields defined (imported) this way:
```
<appstrap name="slide_01_bg_image">{e_THEME}jmgservices/install/slides/app_bg.jpg</appstrap> 		
<appstrap name="slide_03_bg_image">{e_THEME}jmgservices/install/slides/office_cover.jpg</appstrap> 
```
At localhost, with php 5.5  no problems,  images are displayed in admin area and on frontend
second one: 
![image](https://user-images.githubusercontent.com/5429548/35195324-2a4f87ea-fec2-11e7-8ac8-61093cd159e6.png)

On live site with 7.1.12  
![image](https://user-images.githubusercontent.com/5429548/35195331-40803b72-fec2-11e7-935f-1777be7570b9.png)

But Frontend works, preview is displayed
But first image is displayed in admin too:
![image](https://user-images.githubusercontent.com/5429548/35195349-796173fc-fec2-11e7-8373-4a50402ad0a5.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Please post what is in the e107_core database table for your theme.

**Comment by Jimmi08** [comment]
I maybe found it.   Record in media table wasn't created for this image.
With reinstallation of theme it was fixed (I quess that then it checks install folder for images or something like that)
There should be export option in media manager for separate items.

**Comment by CaMer0n** [comment]
In debug mode the theme-manager should rescan for new images.
