### ISSUE TITLE
Strange with the forum.

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#2994]
At three sites, after some updates with Github
1 Not to count the posts from users on the forum.
2 Not getting notifications in the mail about new posts on the forum.
Does anyone have this problem?
e107 version 2.1.8 (git)

**Comment by Moc** [comment]
1. https://github.com/e107inc/e107/issues/2284
2. #2888

**Comment by Evgura** [comment]
The issue has been resolved.
After clearing the database table "e107_forum_track" messages from the forum began to work well.
Engine version 2.1.7
