### ISSUE TITLE
Page navigation menu

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#2995]
HI!

I activated the page_navigation menu on my site, like this (right area): http://www.kephost.com/images/2018/01/22/e107.jpg

I would like the menu not to show pages, just books and chapters. How can I do that?

Thx!

**Comment by tgtje** [comment]
So you like kind of tree menu but without seeing the pages itself (by title) A block consisting of eg 10 links (which can be book names or chapter names) which then point to a page listing showing all pages/contents of that book or chapter?

Page nav menu is coupled, so would need changes on core files; update> pff gone..
Easiest way to do so is a self created menu.. and that is easy.
Suppose you have 3 books and 7 chapters.
The choice is yours either books or chapters in menu OR combi
Calling the books and chaptes are basically links/urls.. BUT they all are pages !!! (see your custompages/menus lists

For Book 1  you use the ID of that book and make it a link ala `page.php?bk=1` .
For Chapter 2 you use the ID of that chapter and make it a link `page.php?ch=2`
Looks like : see image ; plain simple and easy and clicking leads to a book overview of the present of chapters; and the chapter link provides overview of all pages IN that chapter
![navi](https://user-images.githubusercontent.com/1811857/35246972-011b3434-ffc9-11e7-8c0c-a371b3e54ccf.jpg)

**Comment by tgtje** [comment]
Hmm either you do misunderstand of the above where such a title already 'holds'a lot of internal links (pages)  (see them as containers, where you are pointed too  > eg see a list).

As for changing this in (no it will not just be 1 file), and you like it _automated_, you will need a true coder AND a specialized sql  handler (call/querie changes ; verify ; create links out of them..etc). This is way out of my league.

Could it be done,? yes if knowledge (and time) is available . Open source likely not... (customized plugin or alike)
The issues comes within the class sytems, user priviliges, Changing/reflecting items when ID's become changed, And there will be some more (user priviliges is in editting mode, viewable by...  templating .

**Comment by Jimmi08** [comment]
That menu uses {PAGE_NAVIGATION} shortcode but you can't set parameters in menu manager.
This way it's used on e107.org:
`{PAGE_NAVIGATION: template=navdocs&book=7&pages=true}`
- you can set if pages are displayed od not 

Because it uses templates, maybe remove list pages from template would be enough. Not tried.

**Comment by tgtje** [comment]
As i understand Jimmi08; a **tree nav** where only first few items (titles if you like) for books and chapters reside (automated created  > querie ID from dbase, populate plug/menu; update these and make each ID a link ) would be a live session each time if ID is changed new tree is displayed, (and how to calculate 'hidden/members only' pages/chapters/books )

**Comment by Jimmi08** [comment]
pages=false -  I just know that with this pages weren't displayed 
-  that shortcode is written "new way"  - for me very hard understand. I tried to play with templates, but no results.   But I will need this too, only not now, maybe in some weeks.

**Comment by KiraTheUltimate** [comment]
So, should I create a template in my theme folder? E.g.: page_navigation_menu_template.php ?

**Comment by tgtje** [comment]
Partially possible; as Jimmi08 posted: params.. So for displaying you might be able to limit the outcome (visible) for the bookchapters and/or/chapters, ( so only the titles) but not the amount (example id 1 and 2 of content as subs) because these are prone to be always present, but if deleted..failures.(not tested)

**Comment by Moc** [comment]
1. Override the core template
2. Use this shortcode `{PAGE_NAVIGATION: template=navdocs&book=7&pages=true}` or `{PAGE_NAVIGATION: template=navdocs&book=7&pages=false}`

**Comment by KiraTheUltimate** [comment]
@Moc  
I can't find the core template file. Can you help me?
Thx!

**Comment by Moc** [comment]
e107_core/templates/page_template.php

@KiraTheUltimate Do you still need help with this?
