### ISSUE TITLE
type layout vs inline true

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2996]
I have template field defined this way:

```
 'element_type_template' =>   array ( 'title' => 'Template', 'type' => 'layouts', 'data' => 'str', 'width' => 'auto',
'inline' => true, 'help' => '', 
 'writeParms' => 'plugin=appstrap&id=appstrap&merge=1', 'class' => 'left', 'thclass' => 'left',  ),
```
edit more works
listing
![image](https://user-images.githubusercontent.com/5429548/35238104-cf06fca6-ffac-11e7-969a-dab336087fa4.png)
inline editing
![image](https://user-images.githubusercontent.com/5429548/35238096-cc0985b4-ffac-11e7-9188-ea79df746211.png)

You can try this by adding inline=true to featurebox category template. The same result. 
no readParms is set there.

![image](https://user-images.githubusercontent.com/5429548/35238192-1450f866-ffad-11e7-93b4-9baf7bcafa87.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Please try again with the latest commit. thanks.

**Comment by dimante** [comment]
I can give this a go.  It's for the site template I am using.  Will post back here.

**Comment by dimante** [comment]
This is now working Latest GIT downloaded 3/17/2018 - Thanks!

**Comment by CaMer0n** [comment]
Thank you @dimante ! :+1:
