### ISSUE TITLE
custom fields on contact form

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2997]
I know that I can use custom fields on contact page (f.e.  phone)
It's very usefull and handy feature.

But I noticed problem and I don't know how to solve it.

If you use captcha, and wrong code is entered, then there is javascript message and then form is refreshed.
Core fields save filled values, but custom fields don't and you need to fill again.

**Comment by CaMer0n** [comment]
Are you using a custom shortcode for 'phone' ?

**Comment by Jimmi08** [comment]
no. Just HTML code  
```
<div class='form-group'>
                  <label class='sr-only' for='contactPhone'>Company Phone</label>
                  <input type='text' class='form-control' name='contactPhone'  id='contactPhone' placeholder='Company Phone' required='required'>
                  <small id='contactPhone-help' class='form-text text-muted'>Your Telephone Number.</small>
                </div>
```
