### ISSUE TITLE
Importing plugin generated URL's in gsitemap

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#3009]
I have a plugin generating content pages, which urls I want to be added to the Sitemap, but currently gsitemap plugin  only support importing of site links, pages, and forum plugin links. 
I know, can add them by hand - one by one, but for 70+ pages will be painstaking process. Is there any way  to extend my plugin code, so it can work with gsitemap plugin on importing url's?

**Comment by CaMer0n** [comment]
@Serios Please give me a few days.. and I'll work on a solution for you.

**Comment by Serios** [comment]
@CaMer0n thank you

**Comment by CaMer0n** [comment]
@Serios Please take a look at e107_plugins/forum/e_gsitemap.php . If you have any questions, please ask them here. Thank you!
