### ISSUE TITLE
Multi-language support for plupload

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#3010]
@CaMer0n it only works under v 2.1.8 (git)

Current:

`$plUpload = '{e_WEB}js/plupload/i18n/' . e_LAN . '.js';

if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))
{
	e107::js('footer', $plUpload, 'jquery', 5);
}`  this is don't work for me.

Older:

`$plUpload = 'plupload/i18n/' . e_LAN . '.js';

if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))	
{
	e107::js('core', $plUpload);
}`  tested and this is work for me.

Pls review this!

**Comment by CaMer0n** [comment]
Thanks @yesszus . I'll let @lonalore reply to you as it is his code.

**Comment by lonalore** [comment]
I don't think this is my piece of code, plupload integration was not done by me, I just moved the JS to the footer. But it looks good, but please try to keep JS files in the footer. Did you try the following code?

```php
$plUpload = 'plupload/i18n/' . e_LAN . '.js';

if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))
{
    e107::js('footer', $plUpload, 'jquery', 5);
}
```
Or if this does not work then try to load JS language file to another JS area, e.g.:

```php
$plUpload = 'plupload/i18n/' . e_LAN . '.js';

if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))
{
    e107::js('footer', $plUpload, 'jquery', 4);
}
```

**Comment by yesszus** [comment]
Only this work for me:

`$plUpload = 'plupload/i18n/' . e_LAN . '.js';

	if(e_LAN != 'en' && file_exists(e_WEB_JS . $plUpload))	
	{
		e107::js('core', $plUpload);
	} `
