### ISSUE TITLE
PHP 7.2: Installation blocked by theme thumbnails not loading

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#3018]
## Problem
It is not possible to install e107 v2.1.8 preview on PHP 7.2 because no thumbnails show up on step 6 of 8 for selecting a theme.

## Screenshot
![fireshot capture 81 - e107 installation __ step 6 - website pr_ - https___dev deltik org_install php](https://user-images.githubusercontent.com/1364268/35731933-2b54820c-07dd-11e8-9ff1-80771cadae24.png)

**Comment by CaMer0n** [comment]
With this change in the pull-request, it actually caused the problem referenced. (PHP 5.4 and 7.1) Removing the change brought back the screenshots. Please retest, running the installation in debug mode. Theme caching is now disabled during debug. Perhaps this was related to the issue. 

`/install.php?debug`

**Comment by Deltik** [comment]
If the expected output in PHP 5.4 through PHP 7.1 was
```php
    [screenshots] => Array
        (
            [image] => Array
                (
                    [0] => preview_frontend.png
                )

        )
```
… PHP 7.2 would have produced this:
```php
    [screenshots] => Array
        (
            [image] => Array
                (
                    [0] => Array
                        (
                            [@attributes] => 
                            [@value] => preview_frontend.png
                        )

                )

        )
```
… because `$tags = get_object_vars($xml);` in `xmlClass::xml2array()` would have contained the key `0` instead of being empty, and `0` would be interpreted further down in `if($tags)` as a tag.

`$tag` would be equal to `0` in `switch($tag)`, which causes the first case, `case '@attributes'`, to be triggered, and this leads to the undesired blank `@attributes` key and the undesired `@value`.

**Comment by tgtje** [comment]
I use this issue post to keep you update, else it is allover : (issue php 7.2 and 7.2.2) all in one go:
4 screen captures (mp4) where is described the following (all is fresh; wamp and e107 latest)
nu1 = wamp64 php 722  WITHOUT xml commit (not accepted)  > fails at 6
nu2 = xampp php 7.2      WITHOUT xml commit (not accepted)  > fails at 6
nu3 = xampp php 711  (sorry typo movie)  WITHOUT xml commit (not accepted) > success...
nu4 = wamp 64 php 7.22  WITH xml commit > install ok, but sitelinks issue remains

https://tgtje.nl/video/nu1.mp4
https://tgtje.nl/video/nu2.mp4
https://tgtje.nl/video/nu3.mp4
https://tgtje.nl/video/nu4.mp4
