### ISSUE TITLE
Debug tools should require admin auth before allowing them to be run

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#3024]
You can go to any E107 site and get full server drive paths, MYSQL Queries with table names, etc....  I think an admin login should be required before the tools work on any site.  This is adding an attack vector that a bad actor can use to gain information to breach the system.

-D-

**Comment by Jimmi08** [comment]
Related - point 2:  
https://github.com/e107inc/e107/issues/2043

-  you need to set debugger mode off

**Comment by Moc** [comment]
Duplicate, closing in favour of #2043 . 

Short answer: developer mode option is key here. When disabled, only basic information will show without authentication.
