### ISSUE TITLE
Admin UI Does not order the results

### ISSUE THREAD

**Issue by chory** [e107inc/e107#3029]
my URL = /e107_admin/users.php?from=0&field=user_id&asc=asc
result:
![error107](https://user-images.githubusercontent.com/4314070/35877423-899df7da-0b75-11e8-8a47-722265919b43.jpg)

**Comment by Deltik** [comment]
Can you visit the same URL again, except add `&[debug=sql+]` to the end?

We would need to see the "SQL Analysis" farther down the page to get a better idea of why this issue is happening.

**Comment by Deltik** [comment]
Caused by #3025

**Comment by chory** [comment]
Now, it shows nothing
URL =/e107_admin/users.php?mode=main&action=list
![imagen](https://user-images.githubusercontent.com/4314070/36046472-5285d98c-0dd9-11e8-9ece-eed97d8231f7.png)

**Comment by CaMer0n** [comment]
@chory Please try this URL:

`e107_admin/users.php?[debug=showsql]&field=user_id&asc=asc&from=0`

..then paste the listQry value here in the comments here.

**Comment by chory** [comment]
> 
> searchQuery:
> 
> Array
> (
> )
> 
> Using Custom listQry
> QRY=SELECT SQL_CALC_FOUND_ROWS u.*,ue.* from e107_user AS u LEFT JOIN e107_user_extended AS ue ON u.user_id = ue.user_extended_id ORDER BY u.user_id ASC LIMIT 0, 10
>

**Comment by Deltik** [comment]
I messed up.  I'll have a commit to fix this in a few minutes.

**Comment by Deltik** [comment]
Fixed in #3032

**Comment by chory** [comment]
Ok, works fine for me. Show members in correct order.
Great work
