### ISSUE TITLE
newforumposts_main plugin not functioning correctly.

### ISSUE THREAD

**Issue by InebriatedUK** [e107inc/e107#3030]
If using the newforumposts_main plugin, the admin control for display location does not have any action on the page.

If set to "Top of Page" it has no effect on the page and the output is displayed at the bottom (below content) regardless of setting.

**Comment by CaMer0n** [comment]
@InebriatedUK Please try with this change. Thanks.

**Comment by InebriatedUK** [comment]
@CaMer0n awesome, that seems to have fixed it.

Thanks
