### ISSUE TITLE
FR - for forum and mainadmin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3035]
to add button source code in forum tinymce editor for main admins  

OR 

in the backend  Latest Post to add possibility edit post (not only delete) with full tinymce options

**Comment by Evgura** [comment]
I support the request.
You can also add to the forum, the numbering of messages and a link to this post.

**Comment by Jimmi08** [comment]
This can be closed. it is from 2018!
- to add this button member.xml in tinymce can be changed
- Latest post menu can be added in admin area via Personalize admin dashboard
