### ISSUE TITLE
Again - "This combination of user name and password is already in use."

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3036]
Yesterday I updated the website with Github, and again the same thing happened to what he wrote 23 days ago - https://github.com/e107inc/e107/issues/2984
. If the "Enable online tracking of users," it is impossible to enter the site.
"This combination of user name and password is already in use."

**Comment by CaMer0n** [comment]
@Evgura Try clearing your 'online' table. ie. TRUNCATE.

**Comment by Evgura** [comment]
@CaMer0n I can't check. I rolled back to the previous backup while it was working.

**Comment by Moc** [comment]
I am assuming it is fixed now, if not please let us know and I'll re-open

**Comment by Evgura** [comment]
Yes, everything works well now.
