### ISSUE TITLE
Menu areas in menu manager disappear after 1 sec...

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#3038]
Hi,
i've been using a custom theme with latest e107 version. My theme has more menu areas than one - but the problem is: when i open the menu manger in admin panel, all menu areas will be shon, but they disappear after 1 second - for more details, see the screenshots.

Can anyone help?

![menu_visible](https://user-images.githubusercontent.com/22658487/36259423-7357efb8-125e-11e8-9393-0987af166681.jpg)
![menu_invisible](https://user-images.githubusercontent.com/22658487/36259430-7688644c-125e-11e8-9210-2077c150aa2d.jpg)
[theme.php.txt](https://github.com/e107inc/e107/files/1727823/theme.php.txt)

**Comment by tgtje** [comment]
Since you are using self refreshing background... is it possible they get hidden ? top image has none, while bottom has.. Else : you are using language switch, and on that part = does it differ in view when you switch to German?

**Comment by Jimmi08** [comment]
In your theme load some scripts (or css) only for USER_AREA, not for admin. Check console, mainly there is reason. And if you are using any css bodytag, it's stripped in menu manager.

**Comment by chimcen** [comment]
@tgtje nope, both are using self refreshing background - the pictures are sampled out of a screen video capture - wen the menu page refreshes itself (after klicking default menu style eg.) i see the picture above - after one second the menu areas are gone and i'll see my background image...

i can try - but i've set admin language to english to prefent errors caused by faulty language files...

@Jimmi08 
in the chrome browser console i got no errors...
to test if the background slider is the problem, i've disabled the lines in theme.php wich are calling the java script for that... after this a got a blank backgrund in menu manager - but the menu area behaviar is the same...

**Comment by Jimmi08** [comment]
@chimcen you need to open iframe and there check console. You menus are displayed in iframe, not in menu manager page. This way you can displaye preview theme without menus (admin) and then you will see if it is problem with preview display or with menu manager. 2 different things.

**Comment by chimcen** [comment]
thank you - got the problem - caused by a java scrip file at theme side itself. if diabling thios one java script, i'll now see all the menu areas... :)
