### ISSUE TITLE
Fatal error: Call to private method e_tree_model::multiFieldCmp

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3039]
Hi, using github of today, featurebox does not show anything anymore and also leaves index.php empty.. it shows nothing anymore, in the admin with the comments manager, mediamanager, plugin manager schedule tasks, system logs etc.. i get the message (white screen) Fatal error: Call to private method e_tree_model::multiFieldCmp() from context 'e_admin_tree_model' in e107.nl/private_html/e107_handlers/model_class.php on line 3461

PHP Version 5.6.30 - mysqlnd 5.0.11 (with php7 its the same result..)

I use https://e107.nl to test.. 

Alex

**Comment by Moc** [comment]
@Deltik can you take a look at this please?

**Comment by Deltik** [comment]
I completely forgot about the subclasses.  #3041 should fix this.

**Comment by Alex-e107nl** [comment]
Oke i willl test it when it comes available! THX!
