### ISSUE TITLE
Forum latest posts menu doesn't shows real avatars and wrong post date

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#3040]
Hi,

i've enabled the latest forum posts menu on my site - but since update to e107 v2.1.7 it will show me the default blank_avatar image instead of the user avatar from post owner/writer...

And it shows me the wrong post date...

btw. i changed the default blank_avatar image to an bf1 char image... ;)

Can anyone help?

![latest posts](https://user-images.githubusercontent.com/22658487/36270893-39601082-127d-11e8-8697-949a023a04be.JPG)

**Comment by chimcen** [comment]
I've downloaded the lates forum plugin files from git and the problem remains...
![image](https://user-images.githubusercontent.com/22658487/36969278-5445ffd8-2065-11e8-91ff-8c1abbea9930.png)

when print out the data within the array looks good - 10 digit unix timestamp...
![image](https://user-images.githubusercontent.com/22658487/36969399-aac3cb6a-2065-11e8-9fd0-9154fb342ad1.png)


does anyone have the same problem?

**Comment by chimcen** [comment]
Found the solution - some errors in "newforumposts_menu_template.php".
I use the template "minimal".

In e107git you use `{POST_DATESTAMP}` and `{POST_AUTHOR_NAME}` 
-  if you use `{TOPIC_DATESTAMP}` and `{TOPIC_AUTHOR_NAME}` instead, it works...

Another failure is the used class `<h4 class='media-header'>`
- if you use `<h4 class='media-heading'>` instead, the user icon will be centered correctly (source w3schools).


But i don't know how to get the post message also visible... you use `{POST_CONTENT}` but this didn't work...

**Comment by Moc** [comment]
Confirmed the above as bugs. 

There is also an issue with the menu title. If left empty, it will display `Array (`

**Comment by Moc** [comment]
Fixes in #3132 and just added some additional template changes from `media-header` to `media-heading`. 
All issues reported here should be fixed now
