### ISSUE TITLE
News Image automatically resize problem

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3042]
Hello!

So, when I write a news and I upload an image in Media Manager (e.g.: 1024x600 px)  and paste in the textbody area the image size is OK. Then when I save the news, the system automatically resize the image.

Sample: http://www.kephost.com/images/2018/02/18/sample.jpg

Is this an e107 problem or my settings is wrong? What can I do to work normally? Thank you!

**Comment by tgtje** [comment]
**beware > ultimate image display is dependant on viewing 'port' size (responsive)**
plain editor :
[img style=width:300px;]{e_MEDIA_IMAGE}2018-02/1x.jpg[/img]  (basic size)
change this to nearest size eg 800px ? 
[img style=width:800px;]{e_MEDIA_IMAGE}2018-02/1x.jpg[/img]
or
wysiwig editor (tiny)
source will tell : [img]{e_MEDIA_IMAGE}2018-02/1x.jpg[/img]</   = basic 300)
solution : click image right use image and change dimension  
or click image and 'pull'  to desired size  (again viewport might give diff end result..)
Thumb image is always running, hence the changes . pasting full size image/link is also possible, but than again presponsive will add to viewport (opening an image on another window will normally display in original size)

**Comment by CaMer0n** [comment]
@KiraTheUltimate You can set the default size in the Media-Manager preferences. 

As you can see in the image below, the maximum width for a News post would be 800px wide and 500 pixel high. 

![image](https://user-images.githubusercontent.com/2825679/36395594-c18437b0-156e-11e8-8bd3-522673d672a5.png)

**Comment by KiraTheUltimate** [comment]
I don't fill in the default image size, so this doesn't mean it shouldn't resize it?

Cameron: otherwise what you say it works.

But what about the pages? When I paste an image in a table it's work correctly, then I saving the page, it's not work... ->>

1: http://www.kephost.com/images/2018/02/19/1c9ded0d171df7216.jpg
2: http://www.kephost.com/images/2018/02/19/21aaf30d8d2066b24.jpg

**Comment by CaMer0n** [comment]
@KiraTheUltimate These are default image sizes but they can be overridden by the theme template. Please check your page_template.php file for `{SETIMAGE: .... } ` . If you cannot find it, add it to the 'start' . 

eg

    $PAGE_TEMPLATE['default']['start'] = '{SETIMAGE: w=200&h=0}<div id="{CPAGESEF}" class=
