### ISSUE TITLE
Edit forum posts

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3043]
When I edit a forum post, I get the following error message:

http://kepkezelo.com/images/swyh9u1r4ypywx8st3up.jpg

**Comment by tgtje** [comment]
Please see https://github.com/e107inc/e107/issues/1476 as it seems identical..

**Comment by KiraTheUltimate** [comment]
On my site, in admin area compress site output using gzip is disabled, but the problem is still there.

**Comment by Moc** [comment]
Does this only happen when editing a forum post or also on other pages? 

Did you test with multiple browsers? 

Try clearing the caches (both e107 and browser)

**Comment by KiraTheUltimate** [comment]
deleting the browser's cookies solved the problem... thx ^^

**Comment by Moc** [comment]
Please let us know if the issue returns. It is still likely to be related to gzip encoding, but perhaps on the server side.
