### ISSUE TITLE
Forgot Password as Admin

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3047]
Hello!

When I want to reset my password, I only receive an email with the following text:

"someone tried to reset your password"

And I can't get a link to reset my password. Did I set up something wrong?

**Comment by tgtje** [comment]
Two things: 
a) this phrase as posted does not exist in e107.
 (For very good security reasons it's impossible to reset your password unless you're logged in.)

b) reset your password manually using phpMyAdmin or another similar MySQL manager. Go to the users table, the main admin should be user number 1. Click on the edit button and change the password to 4cb9c8a8048fd02294477fcb1a41191a, this will change your password to changeme. Now log in and [b]update your password immediately[/b]

**Comment by CaMer0n** [comment]
For b) You could also enter a password and set the function to MD5.

**Comment by Jimmi08** [comment]
@tgtje  this message is in email:
title:  Attempted password reset
content:  Someone with IP address  xxx   attempted to reset the main admin password. 

@KiraTheUltimate main administrator can't change their password. Annoying but it's for safety. Only way is use phpMyAdmin.  The explanation in code:

```
		// Main admin expected to be competent enough to never forget password! (And its a security check - so warn them)
		// Sending email to admin alerting them of attempted admin password reset, and redirect user to homepage.
```
