### ISSUE TITLE
img in sitelink scale problem?

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3048]
Hi, when you use an image with a sitelink and there's an {SETIMAGE: w=400&h=350&crop=1} in a template for instance news on the news page, the image in the sitelink is shown with 400x350px but should be much smaller.. Using a glyph does not give this problem.. 

Placing a {SETIMAGE: w=22&h=22&crop=1} in the navigation template solves it but it took me some time to figure this out :-)

**Comment by CaMer0n** [comment]
Thanks @Alex-e107nl Was the sitelink in question in the sidebar or somewhere else? I'm curious to see the theme layout where this occurred.

**Comment by Alex-e107nl** [comment]
I think it's already solved Moc, you cab close this... thx!
