### ISSUE TITLE
PHP Fatal error: Call to a member function getVars() on null in download_class.php

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#3056]
I'm seeing the below error in the nginx error log, i'm running PHP 5.6.31.  Any ideas what's causing this?  I'm also running the latest github version of e107.  Thanks!
``
2018/02/28 14:33:44 [error] 1363#1363: *956286 FastCGI sent in stderr: "PHP message: PHP Fatal error: Call to a member function getVars() on null in /var/www/html/domain.com/plugins/download/handlers/download_class.php on line 566" while reading response header from upstream, client: 46.229.168.68, server: www.domain.com, request: "GET /download/72014/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "domain.com"
``

**Comment by Jimmi08** [comment]
this is correct fix:

```
		/** @var download_shortcodes $sc */
		$sc = $this->sc; 
		// @see: #3056 fixes fatal error in case $sc is empty (what happens, if no record was found)
		$count = empty($this->rows) ? 0 : $sc->setVars($this->rows);;

		if(empty($count))
		{
			return $ns->tablerender(LAN_PLUGIN_DOWNLOAD_NAME, "<div style='text-align:center'>".LAN_NO_RECORDS_FOUND."</div>", 'download-view', true);
		}
```

if you would add the latest menu (or any download menu) that is uses download shortcodes, and put it on the left side (before the main page), your view would always display the latest item from the menu.
