### ISSUE TITLE
Line break in comments

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3057]
HI!

When I comment to a news and put a line break in my text, then edit my comment and save, the system is automatically remove line breaks and merge the text together.

**Comment by Moc** [comment]
Do you use the TinyMCE / WYSIWYG editor? Can you provide a screenshot?

**Comment by CaMer0n** [comment]
@KiraTheUltimate Please test again with the most recent changes.

**Comment by KiraTheUltimate** [comment]
It's okay now. :)

**Comment by CaMer0n** [comment]
Great! Thank you! :+1:
