### ISSUE TITLE
Issue: Boolean values are rendered differently if inline editing is enable or not

### ISSUE THREAD

**Issue by SimSync** [e107inc/e107#3058]
Boolean values are rendered different in the admin tables. 
- In case inline editing is disabled it will be rendered using fontawesome:
![grafik](https://user-images.githubusercontent.com/7572616/36915307-800d0920-1e50-11e8-8fe0-2ef1b0ac07ab.png)
- In case inline editing is enabled, html entities `&check;` (&check;) and `&cross;` (&cross;) will be used for rendering:
![grafik](https://user-images.githubusercontent.com/7572616/36915567-752e574c-1e51-11e8-8146-1e411aadb818.png)

- Overwriting this values with fontawesome tags e.g. `<i class="fa fa-times"></i>` or glyphicons doesn't work, because it is replaced onload by javascript by reading the value with element.text() instead of element.html() which result in an empty result as the `<i>` tags has no text value. 
In the file admin.jquery.js line 234ff Issue #2351 is mentioned.

**Comment by Moc** [comment]
Cannot find the other issue now but I am pretty sure this has been already mentioned. I will keep this issue open until I can find the other one.

**Comment by Jimmi08** [comment]
It was discussed on gitter too

**Comment by Moc** [comment]
I think this can be closed now
