### ISSUE TITLE
Language list error

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#3059]
Not loading available language list.
Blank page.

![lang](https://user-images.githubusercontent.com/17430115/36943823-640c2544-1f90-11e8-8885-ac740efadefa.png)

**Comment by tgtje** [comment]
Iff blank is meant as no connection to org, i confirm  (no versions to be seen available) 
Using the v 2..1.6 files of admin/LANCHECK php and all is there...

**Comment by SimSync** [comment]
There was a bug, but in case that there is no language pack for the e107 version that is currently running, the list will be empty again (which is than not a bug).

**Comment by rica-carv** [comment]
Just wondering if #3219 might be related....

**Comment by CaMer0n** [comment]
@SimSync I believe Github changed their feed URLs. Should be fixed now on e107.org. 
https://e107.org/languagepacks.xml
