### ISSUE TITLE
e_form::number() allows only positive integers?!

### ISSUE THREAD

**Issue by SimSync** [e107inc/e107#3063]
Is there a reason why e_form::number() renders an input field that allows only positive integers? 
At least i have the need for negative integers now and than.
Wouldn't it be a possibility to add an option ot "overwrite" the pattern attribute of the input? This could keep the default "no negative integers" behavior, but add the chance to allow also negative integers or double values by setting a different validation pattern.

**Comment by CaMer0n** [comment]
Indeed, changing the pattern is a good idea, or a 'pattern' option added. Normally we can use min = 0 to restrict to only positive numbers.

**Comment by SimSync** [comment]
Maybe this is a possible solution? https://stackoverflow.com/questions/19011861/is-there-a-float-input-type-in-html5#19012837

``<input type="number" step="0.01">`` to generate an input that allows a float value with 2 decimals.
``<input type="number" step="1" min="-1">`` to allow only integer values starting from -1
No need to use pattern.

**Comment by CaMer0n** [comment]
Great! Feel free to send a pull-request if you wish. Default behavior should remain as it is now.

**Comment by SimSync** [comment]
Hmm, unfortunatly the min attribute is ignored if you enter a negative number via keyboard. You can enter a negative number and submit even if min is set to 0.
Pattern is not a full solution, because you (i) can't create a pattern that limits the allowed values to a certain range (e.g. -1 to 20 or 10-20).
Need to do some further investigations.
