### ISSUE TITLE
Users able to verify email and sign in without admin approval when admin approval is set

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#3069]
![image](https://user-images.githubusercontent.com/4084331/37175275-a8bf049e-22de-11e8-814d-ac83ff096ce0.png)

With the settings above users are immediately able to log in without admin approval.. Latest Git.

-D-

**Comment by CaMer0n** [comment]
@dimante is e107 sending an email during signup? (with your settings)

**Comment by dimante** [comment]
Yes, the email is functioning, the people are verifying the account then it
is going active instead of waiting for admin approval...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

**Comment by SimSync** [comment]
Is this issue still alive with current github version?
I'm unable to reproduce this issue ...?!?

**Comment by Moc** [comment]
I cannot reproduce this. If I try to login I get this message:

![image](https://user-images.githubusercontent.com/577978/52130843-99657580-263b-11e9-83b4-228804e2c357.png)

It does need to be tweaked in case there admin verification set, so the LAN resembles that (rather than 'email sent').

**Comment by Moc** [comment]
Closing this issue as I assume it has been fixed. 

@dimante If you are still experiencing the issue, please let us know.
