### ISSUE TITLE
missing LAN string after install Featurebox

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3070]
![image](https://user-images.githubusercontent.com/5429548/37241885-c89013b6-2460-11e8-9c84-276d15c91b1e.png)

```
FBLAN_INSTALL_01
FBLAN_INSTALL_02
```

latest github, only English, just installing FB

**Comment by yesszus** [comment]
Solved!  #3071

**Comment by tgtje** [comment]
Beware of closed issue;it is still a commit; not merged !!
