### ISSUE TITLE
Friendly url problem

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3073]
Hi!

When I using friendly url on news, the system creating signs in the url, like this (%0A):

https://starwarsmedia.hu/hirek/star-wars-lazadok-%0As04e15-16-magyar-%0Afelirat.html

Then when I edit the post and save, the url restored. ->

https://starwarsmedia.hu/hirek/star-wars-lazadok-s04e15-16-magyar-felirat.html

It's a problem, because when I share the post on facebook, then edit the post, the url changes...

**Comment by CaMer0n** [comment]
@KiraTheUltimate What should the URL look like for your news item?

**Comment by KiraTheUltimate** [comment]
The question refers to what?

In the url settings, I using this: "https://starwarsmedia.hu/news/news-title"

So in this case, the correct url should be this: https://starwarsmedia.hu/hirek/star-wars-lazadok-s04e15-16-magyar-felirat.html

But when I save the post, the url still this: https://starwarsmedia.hu/hirek/star-wars-lazadok-%0As04e15-16-magyar-%0Afelirat.html

So in the url, these characters should not be included: %0A

In the news title I using accented characters, because the hungarian language requires that. But I do not think this is the problem.

**Comment by Evgura** [comment]
> In the news title I using accented characters
This is probably the problem. Try without these " accented characters"

**Comment by KiraTheUltimate** [comment]
The original news title is: Star Wars Lázadók s04e15-16 Magyar Felirat

Accented characters is only in one word: Lázadók

But when I creating a news post, and in the settings creating friendly url, the system generating this url: star-wars-lazadok-s04e15-16-magyar-felirat

So it's look like good. But when I save the post, the url is wrong and put in the signs: %0A

The Hungarian language is requires the accented characters, so so I can not deny it.

**Comment by SimSync** [comment]
@KiraTheUltimate Tried to reproduce this issue with the news title you submitted here and everything was fine on my side. Could you please check if this issue is still there?

**Comment by Moc** [comment]
@KiraTheUltimate I am assuming this issue is already fixed. If you are still experiencing the issue using the latest files, please let us know.
