### ISSUE TITLE
Issue: Featurebox Error

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3074]
On a website im working on, everyone can see an error about the featurebox plugin, issue is - that plugin is not installed....

"There are no featurebox items assigned to the bootstrap_carousel template."

https://f4fgame.com

**Comment by tgtje** [comment]
Probably it is (supposing Gameplus v1? theme php > Shortcode :  {MENU=featurebox} li 187,222 that interferes

**Comment by Moc** [comment]
Probably hardcoded in theme or plugin as shown by Tgtje. 

Interesting to see if we need to add a check whcih verifies if a plugin is installed if a shortcode of that plugin is called by a third party theme or plugin. @CaMer0n What do you think?

**Comment by tgtje** [comment]
@LaocheXe did this step help you in suprresing the issue? if yes, than we might conclude it is the ' pre ' present of the coded  (let's call it custom) menu plugin
