### ISSUE TITLE
white page on install - bug

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#3076]
e107_handlers/session_handler.php

PHP Fatal error: Can't use method return value in write context in e107_handlers/session_handler.php on line 904

Errors parsing e107_handlers/session_handler.php
For correct could write “defined” not empty. (http://php.net/defined)

**Comment by Moc** [comment]
PHP version please?

**Comment by kreossino** [comment]
two webserver:
the first with 2 php-versions. PHP 5.6 and PHP 7.0.27-0+deb9u1 (cli)..
the next this: PHP 5.4.45-0+deb7u2 (cli)

**Comment by CaMer0n** [comment]
@kreossino Please try with the latest commit. Thanks

**Comment by SimSync** [comment]
@kreossino Could you please verify if the issue is gone?

**Comment by CaMer0n** [comment]
Closing this. Line 904 is no longer reachable unless debug is active.
