### ISSUE TITLE
Google sign in

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#3077]
Google
https://developers.google.com/identity/sign-in/web/sign-in

Step 1
![screenshot-2018-3-16 integrating google sign-in into your web app google sign-in for websites google developers](https://user-images.githubusercontent.com/1153508/37542594-fbea65c4-295e-11e8-8a14-859a2fc97d9f.png)

Step 2
![inkedscreenshot-2018-3-16 integrating google sign-in into your web app google sign-in for websites google developers 1 _li](https://user-images.githubusercontent.com/1153508/37542664-429f4598-295f-11e8-88aa-f5ed7dacd702.jpg)

e107 Social Plugin

![inkedscreenshot-2018-3-16 social - admin area videodocker_li](https://user-images.githubusercontent.com/1153508/37542440-7b837de4-295e-11e8-9505-bb67f365e153.jpg)

Sign in:

![screenshot-2018-3-16 videodocker](https://user-images.githubusercontent.com/1153508/37542929-262aecae-2960-11e8-8a9a-404df4fffd97.png)

Result: Error 400

![inkedscreenshot-2018-3-16 error 400 oauth2 error 1_li](https://user-images.githubusercontent.com/1153508/37542997-735cfdc8-2960-11e8-964e-c4ca4cf95cfb.jpg)

**Comment by Crytiqal** [comment]
When I add the redirect URI to the oauthclient credentials in the google developer console, I get redirected to a blank page on my website.

**Comment by Crytiqal** [comment]
What I like to achieve is that people can not register to my website, but only log in using their Google account.

**Comment by LaocheXe** [comment]
@Crytiqal I use something simular but with Steam - I also used the theme templates, which removes the user login details for the menu and login.php - all they see is the Steam Link button. 

Now your one screen shot, ur missing the Scope, for me I have Scope set as email

maybe try that, if nothing, then create a new ID/Secret and try them

**Comment by Crytiqal** [comment]
I added 'profile email' (without quotes) in the scope.
I also added https://www.videodocker.com/index.php AND https://www.videodocker.com/?route=system/xup/endpoint&hauth.done=Google in the allowed redirect URI's.

I get to login screen to choose which google account to use. I login there, and I return to an error 500 blank page, and consequently I can't access any page on my website anymore until I clear all cookies.

**Comment by Moc** [comment]
In process of debugging, replicated your process thus far. Also getting the 500 error. 
Will pick this up later again. 

500 error: 
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'User profile request failed! Google returned an invalid response:stdClass::__set_state(array(\n   'error' => \n  stdClass::__set_state(array(\n     'errors' => \n    array (\n      0 => \n      stdClass::__set_state(array(\n         'domain' => 'usageLimits',\n         'reason' => 'accessNotConfigured',\n         'message' => 'Project 442368003382 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=442368003382 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',\n         'extendedHelp' => 'https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=442368003382',\n      )),\n    ),\n     'code' => 403,\n     'message' => 'Project 442368003382 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https: in /home/osprovid/domains/futurecities.academy/public_html/e107_handlers/hybridauth/Hybrid/Providers/Google.php on line 90, referer: https://accounts.google.com/signin/oauth/consent?authuser=0&part=***
```

**Comment by Moc** [comment]
After enabling the `Google+ API` in the Google developer console. Sign in with my googel account worked. 

I have my scope set to `https://www.googleapis.com/auth/plus.login`
