### ISSUE TITLE
White page on install - php-xml package needed

### ISSUE THREAD

**Issue by rainecc** [e107inc/e107#3078]
PHP 7.1.3 

I followed the instructions to install e107 fairly carefully and phpinfo() showed that "xml" was installed. However, install.php failed immediately with a white screen. The error in the logs was: 

> Uncaught Error: Class 'DOMDocument' not found" in /path/e107_handlers/e_parse_class.php:3664.

It seems that e107 also requires the **php-xml** package which has dom, xmlreader, xmlwriters and others.

Please improve the error handling on install startup - if php-xml (or any other hard dependency) is not installed, a clear message is needed.  It might also be worth adding a note to the documentation to indicate that the "php-xml" package is needed and that this shows up in phpinfo() as "xmlreader".

**Comment by CaMer0n** [comment]
@rainecc Thank you! :+1:
