### ISSUE TITLE
multisite feature ignores database prefix

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3081]
This develop feature:

![image](https://user-images.githubusercontent.com/5429548/37652693-a3336e90-2c3c-11e8-9a44-4ded448e1e67.png)

is ignoring database prefix for inserting data.

Tables are created correctly, but data are inserted  with the main site prefix
(this happens with version if you have one database for more multisites  and only difference is prefix)

**Comment by CaMer0n** [comment]
I need to deactivate that.. or move it to the multisite plugin.
