### ISSUE TITLE
plugin name vs. regex in e_url.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3082]
Custom plugin name is gold_download  

I notice this error:

![image](https://user-images.githubusercontent.com/5429548/37674637-a25591ce-2c73-11e8-9bb4-554f116c8db0.png)
 
I think it's because word "download"  in plugin name.

But path is /e107_plugins/gold_download/gold_dl.php 
-  so why is eurl config for different plugin used?

**Comment by CaMer0n** [comment]
@Jimmi08 Does the last commit help?

**Comment by Jimmi08** [comment]
@CaMer0n Thank you, closing, if I notice it again, I let you know (reopen).
