### ISSUE TITLE
Istallation Themes issue

### ISSUE THREAD

**Issue by Abidkatib** [e107inc/e107#3083]
Hi,
i'm istalling the e107 cms on my localhost but why the themes don't shown up in the step 6 of the istallation of e107?

![abid_e107](https://user-images.githubusercontent.com/37679893/37808695-a9106a6c-2e43-11e8-9ab7-1587ab808db0.jpg)

**Comment by tgtje** [comment]
@Abidkatib what files do you use, best to overwrite or use the files here from github.
You can find more about this issue in recent (closed) posts #2933 #3018 #3027

**Comment by Abidkatib** [comment]
Hi
I downloaded the files from github and again still can't see the themes in STEP 6 and can't move on.

please advice me
thanks

**Comment by tgtje** [comment]
What is the 'build'for your localhost? Wamp, Xampp Ubunut, etc...

**Comment by rica-carv** [comment]
And PHP version?

**Comment by tgtje** [comment]
That is the correlation @rica-carv ; since the previous issues were on xml (and step 6 involvement (uses) and again recent issues when php xml is not running (or installed). "it all looks" alike... (and such opens up the case for..)

**Comment by Moc** [comment]
@Abidkatib Please provide your PHP version and if possible more information on your server configuration (installed modules for example)

**Comment by Oding81** [comment]
Hi Moc i have the same problem as above.. with new install of a server..
I tryed PHP 7.1.16 and failed
I Tryed PHP 7.2.4 and failed.

Other CMS(Not e107 are working). 

Then i checked after reading above issues youre talking about .. xml comments.
I checked PHP INFO function. and libXML is enables..

libXML support | active -- | --
libXML Compiled Version | 2.7.6
libXML Loaded Version | 20706
libXML streams | enabled

Below Compile settings PHP
./configure --prefix=/opt/php-7.1.16-fastcgi --with-pdo-pgsql --with-zlib-dir --with-freetype-dir --enable-mbstring --with-libxml-dir=/usr --enable-soap --enable-calendar --with-curl  --with-gd --with-pgsql --disable-rpath --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-sysvsem --enable-sysvshm --enable-pcntl --enable-mbregex --with-mhash --enable-zip --with-pcre-regex  --with-pdo-mysql --with-mysqli --with-jpeg-dir=/usr --with-png-dir=/usr --with-openssl --with-fpm-user=apache --with-fpm-group=apache --with-libdir=lib64 --enable-ftp --with-imap --with-imap-ssl --with-kerberos --with-gettext --enable-cgi --enable-fpm --enable-exif  --enable-mbstring

**Comment by Moc** [comment]
@Oding81 thanks for the feedback and detailed information. Is there any chance you can test the issue with PHP 5.6.x? Or PHP 7.0? I think it's a compatibility issue with PHP 7.1+

**Comment by Spadgerian** [comment]
I was asked to add my php version to this thread because my issue was closed as a duplicate.
PHP version 7.2.2

**Comment by Spadgerian** [comment]
Having read the above I thought I'd better try again.
Using the git hub master works
![textx](https://user-images.githubusercontent.com/36604083/38467497-9d89d45a-3b39-11e8-8b6f-ea39f9585dad.PNG)
But using the zip download from the link on the e107 website (see below) still fails
 http://sourceforge.net/projects/e107/files/e107/e107%20v2.1.7/e107_2.1.7_full.zip/download
![test2](https://user-images.githubusercontent.com/36604083/38467511-f71d10fe-3b39-11e8-8546-1ac3500a569a.PNG)
For reference my local system versions are
![test](https://user-images.githubusercontent.com/36604083/38467517-0ddf38a8-3b3a-11e8-99a1-7931c4b6c73c.PNG)

**Comment by tgtje** [comment]
Thank you for supplying information There is indeed a (likely due to updated files > xml related) a difference in the ones from the zip file, and those from Github master. The Zip pack has to be seen as a fully working version (however at point in time it did not fully support the newest php versions). The github master files are the latest and are a little ahead on the zip packs, but are not 'stable' in means of any time an update can happen...

**Comment by Moc** [comment]
Closing, fixed on Github. Will be part of 2.1.7 release.

**Comment by CaMer0n** [comment]
Closing.
