### ISSUE TITLE
News grid menu shortcode no work

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#3084]
If I use this shortcode:
`function sc_bootstrap_grid_news_latest(){
  
    $template = "
        
        {MENU: path=news/news_grid&limit=4&category=0&source=latest&featured=0&layout=latest-news}

    ";

    $text = e107::getParser()->parseTemplate($template,true);

    return $text;  
  
  }  `
and put { BOOTSTAP_GRID_NEWS_LATEST } the shortcode break my site.
and if I acivate the News menus (either) the site break.
All other menus work normally, only the News menus the problem.
Earlier the shortcode worked.
I reinstalled the System but the problem same.
What I make wrong?
Thanks help!

**Comment by Moc** [comment]
Please elaborate what you mean by 'break':
Can you show a screenshot? Do you try the debug mode to see if there's an error message?

**Comment by fizi** [comment]
Where I put the shortcode, after this not show the page and all JavaScript break (not work).

**Comment by Moc** [comment]
'Not show the page'. Does this mean you get a completely blank/white page? 

Also, please check the browser console for JavaScript errors.

**Comment by fizi** [comment]
Ok, I put back the code now and show page: http://fizithemes.hu/testsite5/index.php

**Comment by Moc** [comment]
Ok, this looks like a PHP fatal error because the footer is not rendered. Please enable debug mode and use the e107 browser addon to locate the PHP error. This will tell us what is wrong, and provide clues on how to fix it

**Comment by Moc** [comment]
I manually debugged this as far as I could. 

I traced the problem here, in `news_class.php` around line 474:

```php
if($legacyTemplate  = e107::getTemplate('news', 'news_menu', 'grid')) // BC
{
	$template = $legacyTemplate;
	$parms['tmpl']      = 'news_menu';
	$parms['tmpl_key']  = 'grid';
}
else // New in v2.1.5
{
	$tmpl = !empty($parms['layout']) ? $parms['layout'] : 'col-md-4';
	$template = e107::getTemplate('news', 'news_grid', $tmpl);
	$parms['tmpl']      = 'news_grid';
	$parms['tmpl_key']  = $tmpl;

}
```

If I remove the if else, and only load the second part (the 'else' statement) like below, it all works properly: 

```php
$tmpl = !empty($parms['layout']) ? $parms['layout'] : 'col-md-4';
$template = e107::getTemplate('news', 'news_grid', $tmpl);
$parms['tmpl']      = 'news_grid';
$parms['tmpl_key']  = $tmpl;
```

@CaMer0n What does this mean? How to fix this?

**Comment by CaMer0n** [comment]
Thanks @Moc . 

@fizi It appears you have a legacy grid template inside news_menu_template.php ?
If so, I believe that if you delete it, the error should stop. 
Perhaps you have 2 grid templates which are conflicting in this way.

**Comment by fizi** [comment]
No grid template in News_menu_template.php ( writen in it that the Moved to news_grid_template.php).
The grid template only in the News_grid_template.php.

**Comment by fizi** [comment]
Grrr! The php start was two times ( <?php ) in the News_menu_template.php. I delete it and problem solved. I don't remember how it in......

**Comment by Moc** [comment]
Hahaha I missed that completely
