### ISSUE TITLE
Book (costom page)

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#3086]
A make the book category and it not appears on the admin.

**Comment by tgtje** [comment]
Not studied behaviour before, but i can add and see a new created book (by title in listing).
When i want to add a custom page to a book (or chapter) i first have to create a chapter.. Than all works.. 
Do not know if this is normal..

**Comment by fizi** [comment]
If I make the parent BOOK, not appears on the list. If I add chapter ...not appears in the list.
I can make the page and can set the chapter (appears in the setting's - dropdown menu)
But the book, chapter lisnt not on the right area on the admin. The list of books empty.

**Comment by fizi** [comment]
This problem will be fixed?

**Comment by Moc** [comment]
@Deltik can you take a look please?

**Comment by Deltik** [comment]
Fix is ready in #3091

**Comment by fizi** [comment]
The problem not solved.
I tried all version of the model_class.php and the latest workrd version was on Feb 23, 2018.
The latest modified version (Mar 6, 2018) not work, not list of book/chapters.

**Comment by Deltik** [comment]
@fizi: An e107 member has not yet merged in the changes in #3091.  (I don't have access to do this.)  If you need the fix now, you can apply [the changes](https://github.com/e107inc/e107/pull/3091/files) manually.

**Comment by tgtje** [comment]
Applied fix manual ( no issues to be seen now). Needs confirmation from others too 👍

**Comment by Alex-e107nl** [comment]
Yess it works now! Tested on new install..

**Comment by Moc** [comment]
I've merged it in by exception as multiple people have tested it and it seems to work fine without breaking other areas.

**Comment by fizi** [comment]
Work! Thanks!
