### ISSUE TITLE
Feature request :Support PFI( PSR )?

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#3092]
I just study https://www.php-fig.org/
does e107 road map support PSR?
https://www.php-fig.org/psr/

**Comment by Moc** [comment]
Some related info: https://github.com/e107inc/e107/wiki/e107-Coding-Standard
https://stackoverflow.com/questions/44690377/how-to-set-up-two-different-codestyles-inside-phpstorm-project

**Comment by Moc** [comment]
Closing. Code is gradually moving towards PSR but this is a longer term process.
