### ISSUE TITLE
Linkwords plugin problem

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3093]
Hi!

When I using Linkwords plugin and I set up a word to a link, like this: {CPAGE}etc
then on the news.php the link show like this: http://starwarsmedia.hu/news/page/etc
and this is a wrong url.

Otherwise, how can I disable the news.php in the Linkwords plugin settings?

**Comment by CaMer0n** [comment]
@KiraTheUltimate Would you mind sharing a screenshot of your linksword record?

**Comment by KiraTheUltimate** [comment]
Ok!
So here it is:

http://www.kepfeltoltes.eu/images/hdd1/2018/05/12/66901.jpg

And this: http://www.kepfeltoltes.eu/images/hdd1/2018/05/12/82102.jpg

And the link is on the news.php is wrong... ("hirek" in the url = news, just hungarian languange)

**Comment by CaMer0n** [comment]
Thank you! Okay, so you need to use the absolute URL, not variables like {CPAGE}

eg.  /my-news-item

**Comment by KiraTheUltimate** [comment]
Ok, but if I using the absolute url, example: http://starwarsmedia.hu/pages/johnpowell
then, suppose I have a thousand pages and a thousand linkwords, and at some point I decide that I change the site domain name... so this is my problem and therefore it makes sense for the variables, but if it doesn't work in this situation...

**Comment by CaMer0n** [comment]
Correct. If you begin it with a `/` then it will be appended to whatever domain name you use. 
ie. 

     /pages/johnpowell

**Comment by KiraTheUltimate** [comment]
Oh, it works! Thx-thx! :)

But, on the left side in linkwords admin (help area) this is the text: "Link: If its a link within this site, the normal {e_XXX} constants may be used."

In this case, this is a wrong instruction.

**Comment by CaMer0n** [comment]
@KiraTheUltimate {e_XXX} is applicable if you're NOT using SEF URLS. 
You are using SEF URLs in your set up. 
If this solved your issue, you may close it.
