### ISSUE TITLE
Latest Zip download shows no themes

### ISSUE THREAD

**Issue by Spadgerian** [e107inc/e107#3094]
I've downloaded and started to install the latest zip version from the downloads page (on Windows 10 running XAMPP and the latest MySQL server). Everything works fine including step 5 Select Admin Skin
and there are 4 options 
![e107-5](https://user-images.githubusercontent.com/36604083/38435414-d54caa84-39d1-11e8-83e5-771afb56345f.PNG)

but it fails on step 6 Website Preferences because Website Theme doesn't work since there are no theme choices available. 
![e107-6](https://user-images.githubusercontent.com/36604083/38435634-8601b6bc-39d2-11e8-8bc1-c1dca7855191.PNG)

**Comment by Moc** [comment]
Thank you, this issue has been reported in #3038 as well. Could you please provide your PHP version in that issue?

I'm closing this one as a duplicate.
