### ISSUE TITLE
user theme

### ISSUE THREAD

**Issue by ericc-dream** [e107inc/e107#3096]
I already related this problem in the help site.
I try to upgrade a e107 website installed since nearly 10 years. 
Upgrade was done regularly until 1.0.4. Now I try to upgrade to 2.7.1

It was impossible to customize some template for, by example, the forum.
I copied the file from the plugin to folder 'e107_themes/<theme>/templates/forum', and made some very simple modifications to it, but nothing appear on the web page
However, when I applied the same modifications to the corresponding file in the plugin folder, everything was fine.

After some investigation, I found that issue was coming from method (or public function) "getTemplate" of object "e107" or to be more precise from method "**getThemeInfo**".

In this last method, the path of the theme used is defined. Mainly at this line :

> $for = isset($user_pref['sitetheme']) ? $user_pref['sitetheme'] : self::getPref('sitetheme');

As I said, my site is installed since a very long time, probably around v0.6 ... 
at one moment, I activated the possibility to change the theme of the site just for me 
I wanted to change the theme of the site, so I installed a lot of various theme and the droplist on the front page allowed me to test them easily and quickly without going to the admin page and without changing everything for everyone.
When done, I went back to the main theme

Fact is that in the database, I had, in table "e107_user", for value "user_prefs" :
array (
  'sitetheme' => '',

so the variable "$user_pref['sitetheme']" was set ... with an empty value ! 

reason why, "e107::getTemplate" was unable to find my modified file in the theme, as it was thinking that I used a "personal theme" 

I removed the variable in the database and now everything was fine again

On the v1, I deleted the content of this value in the database, then from the site, I change my theme and select something different than the default theme of the site 

This change is visible in the DB.

I go back to the default theme and the variable in the database go back to the empty value 

I feel that, in this case, "**empty($user_pref['sitetheme'])**" should have been better than "isset" 

I tried to do the same on V2, to check if the value was also set to an empty string, but, when I select a different theme, some custom page are automatically configured and I can't revers ... my only choice is to delete the content of the variable in the database ... bad :-(

**Comment by ericc-dream** [comment]
Yes, I know, thanks ! 
In fact, this is what I wrote , but used some < > around "my_theme" , and it seems that "markdown" have replaced them by an empty string 
if you look closely, you will see 2 // 

Please refer to this thread [https://www.e107help.org/3997/theme-and-template](url)

**Comment by net1313** [comment]
The same issue with user_template.php.
Imossible to acces when you put it in  e107_themes/my_theme/templates/user_template.php
Even in folder named user.  e107_themes/my_theme/templates/user/

**Comment by CaMer0n** [comment]
@ericc-dream Thanks for your feedback. I modified the code to use 'empty'

**Comment by Moc** [comment]
@ericc-dream @net1313 can this issue be closed?

**Comment by ericc-dream** [comment]
if you think that you solved the problem, why not !

ericc
