### ISSUE TITLE
Knowledge: Steam Social Login

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3097]
Just wanted to inform anyone who uses Steam Social Login (Social Plugin) that it will create new accounts even if you have an existing account on e107 websites - they (Steam) updated openid to where the user_xup in the e107 user database has changed.

Before it was: Steam_UserID (example: Steam_76561198006790310)

Now it is: Steam_https://steamcommunity.com/openid/id/UserID (example: Steam_https://steamcommunity.com/openid/id/76561198006790310)

What I did to fix this is to extract user database, use a program such as Dreamweaver or Notpad++ - search for Steam_ and replace with Steam_https://steamcommunity.com/openid/id/   this should allow you to replace the Steam_ but leave the user's UserID (SteamID) in place.

**Comment by F1Racer68** [comment]
Steam login to my e107 site was working flawlessly until April 5th, 2018. Since then, all attempts to login with Steam fail to login, and I am getting "User attempted to login with unrecognised user name" errors in the admin panel.

Will this address that issue?
