### ISSUE TITLE
i have problem when other websites open my website in iframe

### ISSUE THREAD

**Issue by marceil5** [e107inc/e107#3101]
when news aggregator add my website using ifram to show my news then a blank page apear no news and the rss of my site is correct but what is the problem ??when news aggregator website add my website news directly to their databse there is no problem??please help me with this??

**Comment by Jimmi08** [comment]
It's maybe related to this:
`Refused to display xxx  in a frame because it set 'X-Frame-Options' to 'sameorigin'.`
Check your console (F12 in chrome, second tab), if this is it.
It was changed sometimes ago. 
I was sure it was my issue about this, but maybe I asked only on gitter.

**Comment by marceil5** [comment]
Solved i omit SAMORGIN header

**Comment by Jimmi08** [comment]
@marceil5 could you explain what did you do?  Where do you omit that header?

**Comment by Jimmi08** [comment]
Oh, so you changed core files. I hoped you found different way. I was looking for solution without it.  Maybe this should be in preferencies.  It wasn't this way before.

**Comment by Moc** [comment]
@CaMer0n Is this an intentional security/privacy measure?

**Comment by CaMer0n** [comment]
@Moc Yes, perhaps we can add a flag inside e107_config.php to disable it for people who need that option.

**Comment by Jimmi08** [comment]
This starts to be a bit annoying.  You can't use heat maps without changing core file.

Why this is not part .htaccess anymore?  Or set it as prefs.

**Comment by CaMer0n** [comment]
A pull-request is always welcome @Jimmi08. ;-) Not a complicated fix if you check the changes.

**Comment by Moc** [comment]
Closing, still requires documentation (tracked in Documentation project)

**Comment by CaMer0n** [comment]
@Moc I think we should add all these flags into e107_config.php when it is generated during install. Even though not enabled, it will educate as to what can be configured this way.

**Comment by Moc** [comment]
@CaMer0n I added some but there may be more to add
