### ISSUE TITLE
How can I display on the pages the custom fields?

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3103]
Hi!

I create a page category (book) and set up the custom fields, then I create a page and fill in the custom fields and save the page, but then nothing to show on the page.

How can I display on the pages the custom fields?

**Comment by Jimmi08** [comment]
![customfields5](https://user-images.githubusercontent.com/5429548/39241320-c533759c-4886-11e8-85cd-6996d8c5dfc8.png)

**Comment by KiraTheUltimate** [comment]
Thank you! Works!

2 question:

1. When I using an image field, the picture isn't clickable... how can I make it clickable? (to display the full size)

2. When I using an url field, it only shows: -link-
but I want the link to be named, like: "Next" ( {CPAGE}other ) or Buy it (external link)...

**Comment by Jimmi08** [comment]
@KiraTheUltimate In Chrome it is clickable.   It opens in https://user-images.githubusercontent.com/5429548/39241320-c533759c-4886-11e8-85cd-6996d8c5dfc8.png
if this helps

**Comment by KiraTheUltimate** [comment]
Oh, sorry, not this image... but, when set up an image custom field on my site.

**Comment by CaMer0n** [comment]
@KiraTheUltimate 
1. What URL do you wish to use for the 'clickable' image?
2. `<a href='{CPAGEFIELD: name=myurl&mode=raw}'>Buy It</a>` or.. to wrap it, so it only displays when populated:  
`$PAGE_WRAPPER['default']['CPAGEFIELD: name=myurl&mode=raw'] = "<a href='{---}'>Buy It</a>";`

**Comment by KiraTheUltimate** [comment]
@CaMer0n the url of the image... like on github. When I insert an image here this is clickable to the original size.

**Comment by CaMer0n** [comment]
Fixed on github and an example added to the bootstrap3 `page_template.php` file.

**Comment by CaMer0n** [comment]
@fizi I think you'll like these changes ;-)

**Comment by fizi** [comment]
I like it. :)

**Comment by CaMer0n** [comment]
## Bootstrap3 "custom-fields" rendered example: 

![image](https://user-images.githubusercontent.com/2825679/44302243-7f2c1b00-a2d9-11e8-99c6-9349ca6f19aa.png)
