### ISSUE TITLE
using bootstap4 in theme.xml causes wrong order of files

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3104]
If I use 

```
	<libraries>
		<library name="bootstrap" version="4" scope="all"/>
		<library name="fontawesome" scope="all"/>
	</libraries>
```
Bootstrap4  css is loaded after all "url" files:
this is loaded before bootstrap files: 
`e107::css("url", "" );`

**Comment by CaMer0n** [comment]
@Jimmi08 Please test and let me know. Thank you! :+1:

**Comment by Alex-e107nl** [comment]
Hi, when i install with this change, i lose all icons in navigation menu top in the admin screen.. cleaned cache, only database update for download plugin, do i have to change a setting to get it right? Reverted to git without this it works again..

**Comment by Jimmi08** [comment]
Confim. 
In admin area there is order of css , look like bootstrap itself is missing. It's header, why there are notes about footer?

![image](https://user-images.githubusercontent.com/5429548/39957374-55ffe4ac-55f2-11e8-9135-eacb28fb735a.png)

**Comment by Alex-e107nl** [comment]
Problem solved!

**Comment by CaMer0n** [comment]
Thank you @Alex-e107nl ! Closing. :+1:
