### ISSUE TITLE
how i can add alexa certification code to my website header??please help

### ISSUE THREAD

**Issue by marceil5** [e107inc/e107#3106]

**Comment by MikeyGMT** [comment]
Quick solution would be to add it to the your theme header, https://e107.org/developer-manual/theme-basics ... 
Including JS, CSS and Meta in the head
See the section on including Javscripts, Stylesheets and Meta information. https://e107.org/page.php?ch=11#javascript

Also check https://e107help.org first as there are lots of tips and tricks here. Such as https://e107help.org/3105/customheader-and-customfooter?show=3105#q3105 https://e107help.org/3040/easy-way-to-paste-analytic-code-in-theme-php?show=3040#q3040

**Comment by LaocheXe** [comment]
could always create a simple plugin and use e_header.php

**Comment by Moc** [comment]
This type of question is best asked on our e107help platform here: e107help.org 
I'm closing the issue here on Github.
