### ISSUE TITLE
i want to add this javascript code widget to newstemplate page

### ISSUE THREAD

**Issue by marceil5** [e107inc/e107#3112]
<div id="Mpi_WIDGET_555"></div>
<script data-cfasync="false">
(function(R,e,c,s,W,i,d){R['RecsWidgetObject']=W;R[W]=R[W]||function(){ (R[W].q=R[W].q||[]).push(arguments)},R[W].l=1*new Date();i=e.createElement(c),d=e.getElementsByTagName(c)[0];i.async=1;i.src=s;d.parentNode.insertBefore(i,d) })(window,document,'script','//widget.yallarec.com/_yalla_loader.js','__recsWidget');
__recsWidget('createWidget',{wwei:'Mpi_WIDGET_555',pubid:1000,webid:10000,wid:20302,on:'yallarec'});
</script>

**Comment by rica-carv** [comment]
Have you tryed to use e107::script ?

**Comment by CaMer0n** [comment]
@marceil5 One way.. add this to your theme.php file
```
if(e_PAGE === 'news.php'))
{
   $JS = <<<JS
(function(R,e,c,s,W,i,d){R['RecsWidgetObject']=W;R[W]=R[W]||function(){ (R[W].q=R[W].q||[]).push(arguments)},R[W].l=1*new Date();i=e.createElement(c),d=e.getElementsByTagName(c)[0];i.async=1;i.src=s;d.parentNode.insertBefore(i,d) })(window,document,'script','//widget.yallarec.com/_yalla_loader.js','__recsWidget'); __recsWidget('createWidget',{wwei:'Mpi_WIDGET_555',pubid:1000,webid:10000,wid:20302,on:'yallarec'}); 
JS;

e107::js('inline', $JS);
}
```

**Comment by Moc** [comment]
Closing, assuming this answers your question, if not please let us know.
