### ISSUE TITLE
Feature Request: Admin UI checkboxes

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3117]
I know e107 has a checkbox type in the admin ui - but I was wondering if we select multiple check boxes - like the userclasses type - checkboxes for multiple userclasses. checkboxes type - checkboxes for multiple (whatever id's).

**Comment by CaMer0n** [comment]
Did you try type=checkboxes?

**Comment by LaocheXe** [comment]
It's not in the documentation (e107.org developer manual)

**Comment by CaMer0n** [comment]
okay, but does it work for you?

**Comment by LaocheXe** [comment]
How would I set the values for the check boxes? I'm using the dropdown menu - 

			$sql = e107::getDb();
			$this->award_id[0] = 'Select Award';
			if($sql->select("awards_sys", "*"))
			{
				while ($row = $sql->fetch())
				{
					$this->award_id[$row['award_id']] = $row['award_name'];
				}
			} 
        	$this->fields['award_id']['writeParms'] = $this->award_id;

**Comment by rica-carv** [comment]
#2631 Maybe related?

**Comment by Moc** [comment]
https://www.e107sk.com/knowledge_base/multicheckbox-field/?content.111

This may help. If not, please let us know and I'll re-open.
