### ISSUE TITLE
just note - Maintenance Setting - bbarea 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3118]
in uflag.php there is code:
`".$frm->bbarea('maintainance_text', vartrue($pref['maintainance_text']), 'maintenance', 'small')."`

but size is 5th parameter
`function bbarea($name, $value, $template = '', $mediaCat='_common', $size = 'large', $options = array())`

thanks

**Comment by Moc** [comment]
Thanks @Jimmi08
