### ISSUE TITLE
Doesn't show forum posts number on profil

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3120]
Hi guys!

So... the line that shows how many forum posts has a user, shows 0 on the main admin profil page, who installed the site. But just the main admin, it shows normal value for everyone else.

**Comment by Moc** [comment]
Cannot reproduce on a clean install so far...

**Comment by Moc** [comment]
Can you try running the recalculate tools in the forum plugin? (`/e107_plugins/forum/forum_admin.php?mode=main&action=tools`)
Does it make any difference?

**Comment by yesszus** [comment]
Run and recalculated.
All forums are correct.
Comments error is still up.

![firefox_screenshot_2018-05-11t04-21-16 519z](https://user-images.githubusercontent.com/17430115/39906616-0c6cab90-54e4-11e8-9e92-ee7e72ed3582.png)
