### ISSUE TITLE
uploads

### ISSUE THREAD

**Issue by net1313** [e107inc/e107#3122]
There is an issue with uploads. 
Download plugin is installed. I've created a category and subcategory. Everything works fine.
When uploading (upload.php) got success message and the file exists in e107/system/temp directory. 
But there are no uploaded files visible in admin panel.

Tried to do with fresh installation and default bootstrap3 theme. Same result.
php.ini file - OK for uploads.
filestypes.xml - OK. 
folders permissions - OK.
Tested on:
e107 - v 2.1.7
e107 v 2.1.8 (git)
php - 7.0 and  7.1
DB -MariaDB
Nginx

two differents installations.

**Comment by KaeLhun** [comment]
I've experienced the same, reported in #3189 (It depends on php version. At 5.6 and bellow it is okay but 7.0 and above goes wrong unfortunately.)

**Comment by Moc** [comment]
@net1313 @KaeLhun I am assuming this as fixed as the other issues referenced in this issue are also fixed. 
Please let me know in case the issue persists, then I'll re-open.

**Comment by net1313** [comment]
by reinstalling e107 the bug has gone

**Comment by Moc** [comment]
Thanks for confirming.
