### ISSUE TITLE
VIEWABLE_BY could break forum layout in forum_viewforum_template.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3123]
This happens only if you set visibility in forum for members (not for everyone)

Layout is broken because this shortcode:  {VIEWABLE_BY} `and` this in forum_viewforum_template.php :

`$SC_WRAPPER['VIEWABLE_BY'] = "<div class='panel panel-default' style='margin-top:10px'><div class='panel-heading'>".LAN_FORUM_8012."</div><div class='panel-body'>{---}</div></div></div>";`

There is one more closing div.
```
$SC_WRAPPER['VIEWABLE_BY'] = "
<div class='panel panel-default' style='margin-top:10px'>
  <div class='panel-heading'>".LAN_FORUM_8012."</div>
   <div class='panel-body'>{---}</div>
</div>
</div>";
```

**Comment by CaMer0n** [comment]
Thank you @rica-carv ! :+1:
