### ISSUE TITLE
Wrong LANs in online_menu.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3125]
If you use **not extended** version of online menu

There is 3x the same LAN for different value:

```
$ONLINE_MENU_WRAPPER['default']['ONLINE_MEMBERS']                  = "<li>".LAN_ONLINE_2."{---}</li>";
$ONLINE_MENU_WRAPPER['default']['ONLINE_MEMBERS_TOTAL']             = "<li>".LAN_ONLINE_2."{---}</li>";
$ONLINE_MENU_WRAPPER['default']['ONLINE_MOST_MEMBERS']             = LAN_ONLINE_2."{---}";
```
So there is always label Members
`define("LAN_ONLINE_2", "Members: ");`
 
 
![image](https://user-images.githubusercontent.com/5429548/39890608-955c5b9c-549b-11e8-983e-0a9317d2bf08.png)

**Comment by Jimmi08** [comment]
@tgtje no idea. I only know, that actual strings are correct for extended version, so they shouldn't change.

**Comment by SimSync** [comment]
@Jimmi08 So is anything to do here, or can it be closed?

**Comment by Jimmi08** [comment]
I don't think this was fixed. But if you think this is correct , close it. I can fix it by theme template.

**Comment by SimSync** [comment]
No, that wasn't my intention. When i read thru this thread, it looked to me like as if it is a misunderstanding and not a bug. But maybe you can explain it to me in detail and i'll ave a look into it.

**Comment by Jimmi08** [comment]
See screenshot. There is 2x lan Members.  One of this should be Total member. But with extended Online menu this is correct.

**Comment by SimSync** [comment]
There is already a LAN (LAN_ONLINE_11) with content "Total registered members:".
Isn't this the correct caption for this field?

**Comment by Jimmi08** [comment]
Do you mean this change?
`$ONLINE_MENU_WRAPPER['default']['ONLINE_MEMBERS_TOTAL']             = "<li>".LAN_ONLINE_11."{---}</li>";`

latest github
switch to bootstrap 3  theme

normal view:
![image](https://user-images.githubusercontent.com/5429548/42636553-60ebfce4-85e9-11e8-9e9e-52e863da7ef3.png)

extended: (there is only one member, so I don't know why there is 2x Members)

![image](https://user-images.githubusercontent.com/5429548/42636839-00974532-85ea-11e8-91f9-30b9238bbb4a.png)

**Comment by SimSync** [comment]
2x members is because the extended version uses the same LANS as the normal version.
So is this the the right LAN for this field in your opinion. I personally think so...
If yes, i'll update the menus, default and extended.

**Comment by Jimmi08** [comment]
Of course, it solved my issue.  I was just curious - so first members are online members, second members are online members detailed, and last one are total members. 

PS. I am updating one old plugin and I need to get the same results.  Thanks.
