### ISSUE TITLE
problem with changing password for user as admin in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3126]
I noticed this.

I have user. I need to change password for them. I did it via admin (password field in user profile).
They couldn't log in.
So then I log in as that user (via admin log as this user, not via login.php), I went to settings and set the same pasword there (password and retype password fields). Then everything was correct and user was able to log in.

php 7.2.4

**Comment by Moc** [comment]
I think there is an issue with the password encryption somewhere. I had a similar issue yesterday on one of my websites where I could not login properly even though I was using the correct user/pw combination.

**Comment by MikeyGMT** [comment]
I have a similar issue on a test/dev instance. I think I did a git update last night, then tried logging on in a separate browser, not working, I tried resetting the password via db using MD5 method. Nope. 

I got to the point last night where I reinstalled and created in a fresh db, kept the file structure, deleted the old system folder. I logged in on first install. I cannot login, save prefs, edit pages, clear cache, basically nothing is working. I have tried:
Clear Browser Cache - Edge. 
PHP Debug on/off. 
e107Debug on/off via the url. 
Increased server memory to 512M. 
I have reverted from PHP 7.2 down through 5.6 versions too. 
Tried http and https. 
Checked for error_log's ... only the tree model messages. 
I thought it could be something with the session cookie location, which on my host, when you use MultiPHP Editor sets it to a master account location which is not accessible from the server user account - so you need to change it to something like /home/YOURACCT/.cagefs/var/cpanel/php/sessions/ea-php72. 

I shall try a fresh install somewhere else today or over the weekend.

**Comment by MikeyGMT** [comment]
Aha - ok, so I found via phpinfo that session.save_path was not writeable. 
/home/YOURACCT/.cagefs/var/cpanel/php/sessions/ea-php72 ~ was not there so created it. 
I still got the message, so changed the perms to 0700 the same as the other version folders. And now I can save prefs. But still cannot login via admin page, the login page or home login widget. 
"Incorrect login. The entered data doesn't match to a registered user. Check if you have the CAPS-LOCK key activated as logins on this site are case sensitive"

OK so quick add user (a main admin), frontend login.php, wierdly logs in but re-displays the  login page. 

![image](https://user-images.githubusercontent.com/2847651/41469695-2152874a-70a6-11e8-999f-642e62fe1586.png)

But I am logged in at least, so seems it is something to do with password change. Now I really have to go.

**Comment by MikeyGMT** [comment]
I suspect a number of my issues were related to e107 and browser caching and differences across multiple browsers - saving prefs is now behaving. 

I'll do further tests on change admin passwords using different routes - and I'll clear my caches!!!
