### ISSUE TITLE
[Removed by Moc for security reasons]

### ISSUE THREAD

**Issue by TopScrew** [e107inc/e107#3128]
[removed by Moc for security reasons]

**Comment by Moc** [comment]
Please send your security vulnerability reports to security@e107.org
I've removed (and saved) the contents of your issue report for security reasons.

Thank you for your report. Please submit any future security issues by email to the address above.

**Comment by zentery** [comment]
Is there a corresponding vulnerability patch here? Can someone provide it?

**Comment by Moc** [comment]
It has been included in a previous release. Please update to the latest version of e107.
