### ISSUE TITLE
New Forum Posts plugin : excerpt not shown and author infos incorrect

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#3132]
Hi, after an upgrade on Github last sources, the New Forum Posts plugin doesn't display anymore the excerpt of the forum posts, and shows "48 years ago" instead of the username.

The forum is still working properly.

![ss-plugin](https://user-images.githubusercontent.com/4124597/40134607-3b2f1180-5943-11e8-9f3b-58eee9c22615.jpg)

("derniers sujets" means "last topics" in french FYI)

**Comment by CaMer0n** [comment]
@pierre0042 Try using the new forum posts menu which is part of the 'news' plugin.

**Comment by pierre0042** [comment]
I can't find it, are you sure about the name?

**Comment by Moc** [comment]
Confirmed as a bug. This issue occurs with the default `newforumposts_menu (forum)` menu, part of the forum plugin. 

There is another newforumposts menu in it's own folder `e107_plugins/newforumposts_main` which is not recognized by the menu manager as a menu, but instead is used by older themes or plugins by calling the shortcode `{ NEWFORUMPOSTS}`

**Comment by SimSync** [comment]
@pierre0042 This is happens if the options for this menu haven't been touched after adding the menu to the menuarea. Due to that, the wrong query is executed and the menu is "empty".
I'll add a fix for the wrong query...

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/3040

**Comment by pierre0042** [comment]
I updated my version. The author information is now correct, but the excerpt is still not displayed.

**Comment by Moc** [comment]
Yeah.... these forum shortcodes are a mess. Looking into it.

**Comment by pierre0042** [comment]
Now the plugin title isn't displayed correctly as well

![screenshot](https://user-images.githubusercontent.com/4124597/41911034-cac0f1ce-794b-11e8-9a65-f2ef7434f76c.png)

**Comment by SimSync** [comment]
@pierre0042 Please check in the menu settings which layout is used and also try the other layouts.

**Comment by pierre0042** [comment]
It is set to "Default"

**Comment by SimSync** [comment]
Did you test the other layouts?

**Comment by pierre0042** [comment]
Yes, it's not better. There are "Minimal" and "Main".
Main tries to display the whole forum in the small box...

Minimal looks like this :
![screenshot2](https://user-images.githubusercontent.com/4124597/41921053-46363ff6-7962-11e8-90b6-d514aff9a043.png)

**Comment by SimSync** [comment]
Ok, I'll look after it.

**Comment by SimSync** [comment]
Just submitted a pull request, which should fix both issues: The missing excerpt and the malformed caption.

**Comment by Moc** [comment]
I think there will still be an issue with the actual excerpt not showing...

**Comment by Moc** [comment]
All fixed for me. 
@pierre0042 Can you confirm it's working? :)
