### ISSUE TITLE
fatal error in download preferencies

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3135]
Latest github
Download/Preferencies

php 5.6

Fatal error: Arrays are not allowed in class constants in xxx\e107_plugins\download\handlers\NginxSecureLinkMd5Decorator.php on line 13

**Comment by CaMer0n** [comment]
@Deltik Thoughts?

**Comment by Deltik** [comment]
This is fixed in #3142.

**Comment by CaMer0n** [comment]
Thank you @Deltik  :+1:
