### ISSUE TITLE
insert media-manager glyph doesn't insert anything in tinymce editor

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3136]
You can select Icon, but click on button Save doesn't insert anything
Latest github version
php 5.6
not visible errors in debug mode, nothing in console

It works on version from Apr 20, 2018

**Comment by CaMer0n** [comment]
As a result of the TinyMce upgrade pull-request most likely.

**Comment by MikeyGMT** [comment]
Ditto for images from cpage>insert media from media manage. Can select, but no code added to page.

**Comment by SimSync** [comment]
@CaMer0n Do you still have an older version of the tinymce to compare? The new one is trying to reach so many elements which are not available (any more?) and i need some ideas how it worked in the old one.
