### ISSUE TITLE
Plugin "News"

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3137]
What is the plugin on the way site. ru \ e107_plugins \ news \ in the folder "News"?

**Comment by Jimmi08** [comment]
Hi, if I know -  it's replacement of old news from version 1 -  if you look at news.php, you will see require_once(e_PLUGIN."news/news.php");  
Some related news menus was moved there etc. 

Only if you use e_LEGACY_NEWS constant, old news.php is loaded.

**Comment by Evgura** [comment]
Can you delete it? Who's tried, who knows?

**Comment by Evgura** [comment]
This plugin slowed down the loading of the site. But yesterday I updated the engine to 2.1.8 with Github and it seems the problem is gone.
