### ISSUE TITLE
Issue: Banners Plugin

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3141]
I enabled the Banners plugin, added the menu into the menu manager in area 2, wont show, did the same in area 104 - no show, even clicked on the e107promo in menu manager banners config - (by the way, broken lans in the menu manager banners config area) - still nothing is showing up. - even tried to debug, and nothing is showing for the banners plugin

**Comment by Moc** [comment]
Confirmed

**Comment by LaocheXe** [comment]
I notice {BANNER} shortcode works, sort of - didn't add any parameters to it

![bannertest](https://user-images.githubusercontent.com/5818022/42973019-2b422df0-8b77-11e8-99b0-38ae0acc6b53.JPG)

**Comment by Moc** [comment]
I've made some changes:

- LAN fixed
- The only thing you need to do after activating the menu in a particular area, is configure which campaign needs to be shown.

**Comment by Moc** [comment]
@CaMer0n is it possible to set a default value for a menu pref? Perhaps we can improve the banner plugin by making the default banner (that is inserted during plugin install) show by default.

**Comment by CaMer0n** [comment]
@Moc Usually I use varset($pref, 'defaultvalue'); inside the menu itself.
