### ISSUE TITLE
Admin login problem

### ISSUE THREAD

**Issue by erenay93** [e107inc/e107#3143]
Hi,
I have a strange problem. I recently did a fresh install of e107 and when I try to login admin area it's redirects me to the login page again. If I enter password wrong it says "Incorrect login" but if credentials are correct it says nothing and redirect me back to the admin login.

Thank you for your helps.

**Comment by erenay93** [comment]
Sorry I for

**Comment by erenay93** [comment]
Also I noticed that, sign in function is not working.

**Comment by Moc** [comment]
Are you using version 2 1.7 as downloaded from e107.org? Or are you using the latest files from GitHub?

**Comment by erenay93** [comment]
Hi,
thanks for your reply @Moc. I used v2 1.7 from e107.org when the problem occurs I switched to the latest GitHub version. But the problem is still exist.

**Comment by erenay93** [comment]
By the way my system specs are,

Server : Apache/2.4.18 (Ubuntu)
PHP version : 7.0.25-0ubuntu0.16.04.1
MySql : 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
