### ISSUE TITLE
Add "canonical"

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3147]
Is it planned to add rel="canonical" to the site engine ?

**Comment by Jimmi08** [comment]
Hi, this is so important for SEO  and they didn't understand me.  See:
https://github.com/e107inc/e107/issues/1693

For custom plugin there is e_URL_LEGACY   but it's doesn't work for core plugins (news etc). 

This should be basic part of engine, to get original not SEF-URL link, most of old plugins doesn't work without this. e_PAGE is not set either.

**Comment by Evgura** [comment]
rel= "canonical" needed in the engine, without it a lot of duplicates of pages. It is strange that the developers do not understand what is going on.

**Comment by CaMer0n** [comment]
I just uploaded a plugin I wrote a few years ago. Haven't tested in a while. 
Please give it a try. @Evgura @Jimmi08 (make sure your plugin folder is called "canonical" )

https://github.com/e107inc/canonical

**Comment by Jimmi08** [comment]
@CaMer0n I appreciate it, but it's not solution. Old legacy urls are already canonical urls. 
This is double work, for any combination of categories etc.  In that plugin you need manually create canonical ulrs and it's impossible in big site. 

In fact  SEF URLs should be solved this way and not changing with title etc.

**Comment by Evgura** [comment]
Can't adjust.
The plugin itself was installed normally. When you assign a canonical page in the source code of the site rel= "canonical" I do not see.

**Comment by Jimmi08** [comment]
@CaMer0n I take it back, this could be useful. But how it will work? If you have data in canonical table, when and how they are inserted into head?

**Comment by Jimmi08** [comment]
@Evgura can this be closed?
