### ISSUE TITLE
User email must be visible in user profile?

### ISSUE THREAD

**Issue by oudoken** [e107inc/e107#3150]
Hi there,
The current shortcode {USER_EMAIL} hide email also for the user itself.
Maybe will be better to show the FULL email for the logged in user when in user profile? ie:

	function sc_user_email($parm='')
	{

		$tp = e107::getParser();
		
		$aCurUserData = e107::user(USERID);

		if( ($this->var['user_hideemail'] && !ADMIN ) && ( $this->var['user_email']!=$aCurUserData['user_email'] ) )
		{
			return "<i>".LAN_USER_35."</i>";
		}
		else
		{
			if($this->var['user_email']!=$aCurUserData['user_email']){
				return $tp->emailObfuscate($this->var['user_email']);
				//list($user,$dom) = explode('@', $this->var['user_email']);
				//return "<span class='e-email' data-user='".$user."' data-dom='".$dom."'>&#64;</span>";
			}else{
				return $this->var['user_email'];
			}
		}

	}

Thanks
Rob

**Comment by Jimmi08** [comment]
Then how user will know that the hidding works?  As admin I got confused to see all emails (hidden too) , I thought that hidding part doesn't work.  There should be warning like "You see this email because it's your email, for others it's hidden).  Otherwise good point.

**Comment by oudoken** [comment]
Hi Jimmi,
Well Yes adding maybe an "(hiddend for other users)" will be more clear!
It's a little implementation btw
Thanks

**Comment by Moc** [comment]
Feel free to submit this as a pull-request :) 👍

**Comment by oudoken** [comment]
Hi @Moc pull request made thanks
