### ISSUE TITLE
Feature request  - coppa confirmation

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3156]
To possibility change coppa text in preferencies not as lang translation

- this functionality is very good for receiving consent with conditions of registration, to possibility change that text online would be very helpfull

**Comment by CaMer0n** [comment]
We could use the LAN as the default and a pref to customize.

**Comment by Moc** [comment]
@Jimmi08 Is this still needed with the new GDPR options/shortcodes/texts for ToS and Privacy Policy?

**Comment by Jimmi08** [comment]
It is not needed anymore
