### ISSUE TITLE
shortcode in textarea field with more than 1 parameter doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3161]
I want to insert to Welcome message this shortcode:
`{CHAPTER_MENUS: name=mobile-games&template=mobile-games}`

it's changed to:
`[html]<p>{CHAPTER_MENUS: name=mobile-games&amp;template=mobile-games}</p>[/html]`

&amp; - it's not taken as second parameter.

```
Array
(
    [name] => mobile-games
    [amp;template] => mobile-games
)
```
I thought this was solved already, but it's happened again.

**Comment by outlaw16151** [comment]
looks like chapters of the mobile games show on every page

**Comment by Jimmi08** [comment]
This is similar issue for gallery, it was fixed:

https://github.com/e107inc/e107/issues/2205

**Comment by SimSync** [comment]
@Jimmi08 Just submitted a fix for this issue.
