### ISSUE TITLE
problem with news tags -  not existings urls in WMT

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3162]
I have tag with space:  "custom theme"
in tag menu (correct):  /news/tag/custom%20theme
in news detail is wrong path :  
`<a class="news-tag" href="/news/tag/custom%2520theme">custom theme</a>`
{NEWSTAGS} is used

in tag_menu:
`$url = e107::getUrl()->create('news/list/tag',array('tag'=>$word)); // SITEURL."news.php?tag=".$word;	`

in news_shortcodes:
`$url = e107::getUrl()->create('news/list/tag',array('tag'=>rawurlencode($val))); // e_BASE."news.php?tag=".$val`

**Comment by SimSync** [comment]
Unfortunatly, all the above referenced commits are not belonging to this issue 3162 as there is a typo in the issue number. They are fixing issue 3161. Sorry.
Will check for this issue soon.

**Comment by SimSync** [comment]
The new PR will fix this.

**Comment by Jimmi08** [comment]
Fixed here (this one was closed by mistake):

https://github.com/e107inc/e107/issues/4682
