### ISSUE TITLE
Issue: RSS - e_rss.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3165]
Found an issue, maybe it's something I did, I don't know.

So I'm working on my roster plugin, went to check out e_rss.php that was generated by the Plugin Manager - went and edit my fields, enabled it via RSS plugin and went to the feed - notice it only showed one out of the 7 entries - so I added ORDER BY loa_id DESC - came into an issue with that. Updated the rss feed and no data. Enabled e107 debugger tool and notice this at the bottom of the page:

Software defect detected; ob_*() level 0 at end instead of (1). POPPING EXTRA BUFFERS!

**Comment by Moc** [comment]
You should only get this message when you are in developer mode. 

To be sure, what is your PHP version?

**Comment by LaocheXe** [comment]
PHP 7.2
