### ISSUE TITLE
Feature Request: toDate - not time

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3167]
Using 'long' or 'short' both show the time as well - is there a way to get it just to display the date and not the time?

**Comment by LaocheXe** [comment]
https://501stlegion-a3.com/feed/loa/rss/0

using "short" (want to remove the time -  : 00:00  <--- I don't want that to be displayed)

**Comment by CaMer0n** [comment]
@LaocheXe The 'short' format is defined in` admin > preferences > date display options`. If you wish your plugin to force the display of a different format, simply replace 'short' in `toDate()` with the format itself. eg. `%d %b %Y`

**Comment by LaocheXe** [comment]
Thanks @CaMer0n didn't see that in preferences - sorry
