### ISSUE TITLE
problem with $sql->update

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3168]
Just warning, maybe this is intention.  

I use this canonical plugin, there is this code:

```
				 if(!$sql->update("canonical", "can_url='".$data['x_canonical_url']."' WHERE can_pid= ".$id))
			  	{              
					$insert = array("can_id"=>0, "can_pid"=> $id, "can_table"=>$type, 'can_title'=>$data['news_title'],'can_url'=>$data['x_jm_canonical_url']);
                            
					if($sql->insert("canonical", $insert))
					{          
						e107::getMessage()->addDebug(print_a($insert,true));
					}
					else
					{
						e107::getMessage()->addError("Couldn't update Canonical URL");
					}
				}
```

Maybe this is php related (I use 5.6), but if nothing is updated (only news is resaved), double record in related table is created. It because $sql->update() returns 0 if there is no update.  If I change field value or  insert new value, it works.

**Comment by CaMer0n** [comment]
Please post it in the canonical repo issue tracker.

**Comment by Jimmi08** [comment]
@CaMer0n it's not canonical plugin problem. 
Is there anywhere mention that $sql->update() returns 0 if no fields were changed?  Is this correct behaviour?

**Comment by CaMer0n** [comment]
Standard behavior if I remember well. You could test the same in v1.x if you wish.

**Comment by Jimmi08** [comment]
Fixed by using code from referal plugin
