### ISSUE TITLE
forum_viewtopic.php - problem with e_QUERY and pagination

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3171]
With SEF-URL forum.

First page (no parameter page)
**forum_viewtopic.php**
example: 
URL:  /forum/subforum/35/forum-topic
- e_PAGE is not set (so no possible test like with news if e_PAGE = forum_viewtopic.php (minor issue)
- e_LEGACY_URL is available so test can be with string:  
   e107_plugins/forum/forum_viewtopic.php?id=38&
- without pagination e_QUERY id=35&  
But with pagination:
` /forum/subforum/35/forum-topic/&p=2`
`e_QUERY id=35&&p=2`

So you can't use list($id,$p) = explode("&&", e_QUERY); - because it doesn't work for url without paging, and you can't use  list($id,$p) = explode("&", e_QUERY); because it doesn't work for paginated urls.

I think that problem is in e_QUERY, it shouldn't have first &  
Thanks

**Comment by Jimmi08** [comment]
I just found that google bots are able to find next url without e_LEGACY_URL filled 
 

![image](https://user-images.githubusercontent.com/5429548/42529222-30959d96-847e-11e8-956b-d34c9cf85ec7.png)

**Comment by SimSync** [comment]
@Jimmi08 Where does this url come from `/forum/subforum/35/forum-topic/&p=2`?
Is it manually entered or did you copy it somewhere and if so: where?

**Comment by Jimmi08** [comment]
@SimSync  try this:
https://www.e107.sk/forum/canonical-plugin/35/canonical-plugin/
down is pagination
https://www.e107.sk/forum/canonical-plugin/35/canonical-plugin/&p=2

**Comment by SimSync** [comment]
Ok, than it looks like a bug.
