### ISSUE TITLE
Forum visibility - weird behaviour

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3176]
Today I noticed somebody else forum (version 2)
https://www.digioso.com/baod/
![image](https://user-images.githubusercontent.com/5429548/41031446-ecc4f61a-6980-11e8-9a0c-093410f81ca5.png)

so there is possibility to set Visibility to members and display forum for quest.  
I did it with more complicated forum:

all forums are visible for quest
**I set one to members (parent forum):** 
 
![image](https://user-images.githubusercontent.com/5429548/41031548-32c4e184-6981-11e8-86f3-8256c66f12b9.png)

Searching doesn't work:
 
![image](https://user-images.githubusercontent.com/5429548/41031610-59d5b41a-6981-11e8-9a1e-e736ecf520b2.png)

Forum is hidden for quests and text Restricted area is displayed with other forums
 
![image](https://user-images.githubusercontent.com/5429548/41031673-8e705b12-6981-11e8-9a95-74f862a06aef.png)

**I set child forum (subforum, 2 level) for  members**

![image](https://user-images.githubusercontent.com/5429548/41031719-b7ba28e0-6981-11e8-8ef6-6d300c1effd3.png)

Searching still doesn't work

![image](https://user-images.githubusercontent.com/5429548/41031776-da494fee-6981-11e8-963c-2858c17d14dd.png)

Restricted is displayed with all forums

![image](https://user-images.githubusercontent.com/5429548/41031839-05d29b0c-6982-11e8-9c32-70ee96f51774.png)

Subforum is not displayed for quests

**I set child-child forum (forum, 3 level) for  members**

![image](https://user-images.githubusercontent.com/5429548/41031971-6448326e-6982-11e8-84fb-0c17c1971ebc.png)

the same behaviour.

How this should work?

**Comment by Digioso** [comment]
![grafik](https://user-images.githubusercontent.com/10660450/41032477-c7117846-6983-11e8-86f3-67a9146c4214.png)

This is a screenshow from how I set this up in the above mentioned baod-Forum.

**Comment by Jimmi08** [comment]
@Digioso so you have it wrong too - Your first forum Öffentlich  is marked as  (Restricted Access), but you have visibility to Everyone.

**Comment by SimSync** [comment]
@Jimmi08 @Digioso No i don't think that this is wrong.
Forum visibility is public, but Post permission and Thread creation is limited to Members (so there is a restriction).
For me "Restricted access" doesn't mean "No access at all". The access is just somehow restricted, in his case to "read only" for guests.
And the filter for userclass should be working now after the treeview search/filter issue has been fixed.

**Comment by Jimmi08** [comment]
@SimSync 
logic is missing.
If there is **no forum** without restrictred visibility (all forums are public), then no "Restricted access" is displayed.
![image](https://user-images.githubusercontent.com/5429548/41848227-0057cae4-787d-11e8-8b67-e9b9bbb11606.png)

If there is only one forum with Visibility for members, all forums are marked as Restricted accss.

**Comment by SimSync** [comment]
@Jimmi08 It says "Restricted access", not "restricted visibility". And part of the access (write access) is limited to "Members". I didn't test it, but is the message "Restricted access" also visible if "post permission" and "thread creation class" is set to everyone?
BTW: Can't find this message at all in default bootstrap3 theme ... 😜

**Comment by Jimmi08** [comment]
If you change visibility to members, forum will not be visible at all, so no point to display message Restricted visibility.

So bug is that this message is not displayed at all if all forums are public, but access is restricted ?

**Comment by SimSync** [comment]
@Jimmi08 I think we are talking about different things.
You are talking about visibility and this is what the "Visibility" column defines. So if you set it to "Everybody", the colum should be readable by everyone incl. guests. 
So far so good.

"Access" doesn't only include the chance to read or see the forum, but also if you are able to write to it.
In your case, this is **limited** or **restricted** to "Members" => "Restricted access".

But as i said before, i'm unable to find a similar area as shown in post 1. I've setup some forums here on my systems to have no restrictions (Everyone, Everyone, Everyone) and some as you have it (Everyone, Member, Member) and i can see them all, without the message "Restricted access". Only if i enter a "restricted forum", i'm unable to create a thread (as guest) and i get the message (as tooltip) that the access is restricted and i can't create a new thread.

Maybe this all is only with old/converted themes? Like i said, with the included bootstrap3 theme, i can't find this sentences. But maybe i'm just looking at the wrong places ...?!?

**Comment by SimSync** [comment]
Ah, now i found it ... 
But this is only on the main forums and not on the subforums.
And if you set them to (Everyone, Everyone, Everyone) this message will go away. But you are still able to limit the access to the subforums ...

**Comment by rica-carv** [comment]
So, to see if i get it right (and make a test scenario): if i make a main parent forum restricted, it won't display the message? Is that it?
Or the ideia is that since a main parent forum is set to restricted, all the childs must inherit it's restriction (as it should be, no?)?

**Comment by SimSync** [comment]
@rica-carv At least on my install it is as follows:

On a main forum:
- Visibility, Post permission & Thread creation to Everyone:
Main and sub forums visible; All users and guests can can post and create threads (if not defined otherwise in the subforum); No "Restricted access" appended to main forum name.
- Visibility to Everyone, Post permission & Thread creation to Members:
Main as sub forums visible; Only members can can post and create threads (if not defined otherwise in the subforum); "Restricted access" appended to main forum name. 
- Visibility, Post permission & Thread creation to Members:
Main as sub forums visible only for Members; Only members can can post and create threads (if not defined otherwise in the subforum); "Restricted access" appended to main forum name.

And for me this sounds right...

**Comment by Jimmi08** [comment]
@SimSync Do you have more than one main forum?    Second one with no restrictions? Is that text displayed only with one forum or with both?

PS. I don't know why but now I can't get displayed it with any combination.

**Comment by SimSync** [comment]
I'm not in the office this morning, but in the afternoon, I'll create some screenshots of my settings and how it looks on the front page.
What I already can say is, that I have more than one main forum and above are my combinations.
The "Restricted" message is only on main forums and only when the restrictions are applied to the main forum itself.

**Comment by Jimmi08** [comment]
So it's has to be fixed with latest changes. not spend time on it. If I notice that it appers in all forum again, I will create new one. Thanks.
