### ISSUE TITLE
Multilanguage site, SEO urls and site url question

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#3177]
What I'm trying to achieve is fairly simple at first look, but I think is kind of complicating on other hand... or maybe some ideas to point me in right direction will be enough.

The idea is that I have a multilingual site  with two language versions the second one under subdomain. All set, tables duplicated, content filled, site links set, etc. etc. the problem is that some of the content for example the News doesn't need to be translated so they stay the same. Other content for example "About us" page on other hand is translated and should be ( I know that in the perfect world all site content form the basic lang version should be mirror copy and translated in other lang versions, but we don't live in the perfect world unfortunately ) My site navigation should be the same in each lang version, so I can't just remove the News section url from second lang. I have set URL paths so news  is behind www.mysite.com/news, but for English version it became en.mysite.com/news and this is quote a issue with SEO since Google will take this as two different  urls and count it is as duplicated content. 

My Idea was to point the sitelink of News in the second lang version to  www.mysite.com/news this is working but doesn't change the site language, so everything else stays in English which is again very bad. So I revert back to using {SITEURL} in Sitelinks

Currently Site links in both language versions are set like {SITEURL}/news, so I was thinking like something of
{SITEUR_BASELANG}/news that will generate  www.mysite.com/news and this link will switch to base lang instead of just load untranslated news content in English version of the site. I'm kind of stuck here since don't have any idea how to make this work.

**Comment by Jimmi08** [comment]
Are you using table News and related tables as single table? Not multilan?

**Comment by Serios** [comment]
Yes @Jimmi08 news and related tables are single tables for main lang, I don't duplicated them for the second Lang version.

**Comment by Jimmi08** [comment]
@Serios weird, maybe because you are using subdomains.  I don't .  I have with 3 languages and news are displayed only in one languages.

**Comment by Serios** [comment]
Fiddling a little bit I actually noticed something strange if I type the en subdomain en.mysite.com the site get translated in English as it should be, then if I try to go to basic lang by www.mysite.com  it doesn't switch to basil lang, it stays in english, BUT if I go without www prefix, for example just mysite.com the site get loaded in basic lang. This is kind of strange, since my logic was that it gets the first part of the subdomain and match it against installed languages and if match is found it loads the lang version for the match and www should be ignored or load the default lang,
