### ISSUE TITLE
plugin sql changed - weird behaviour while update

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3178]
Installed plugin with this SQL (example)

```
CREATE TABLE canonical (
  `can_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `can_table` varchar(50) NOT NULL DEFAULT '',
  `can_pid` int(10) unsigned NOT NULL DEFAULT '0',
  `can_title` varchar(250) NOT NULL DEFAULT '',
  `can_url` varchar(250) NOT NULL DEFAULT '',
   PRIMARY KEY  (`can_id`),
   KEY `can_pid` (`can_pid`)
) ENGINE=MyISAM;
```

There is wrong index `KEY `can_pid` (`can_pid`)`, it needs to be changed to:      
`UNIQUE KEY `can_unq` (`can_table`,`can_pid`) `
(similar like in reference plugin)

I got correct Update info in admin area. After update it said Plugin was updated but info about update was still there.

Each click on Update causes new index in database this way:

![image](https://user-images.githubusercontent.com/5429548/41060759-de8585ce-69d0-11e8-9235-20deab89c5dc.png)

PHP 5.5
What is correct syntax for something like this?

**Comment by SimSync** [comment]
@Jimmi08 So the keyname is always the name of the first key column?

**Comment by CaMer0n** [comment]
@Jimmi08 If it's specific to the canonical plugin, best to post it here. 

https://github.com/e107inc/canonical/issues

**Comment by Jimmi08** [comment]
No, I disagree.  I noticed this on canonical plugin but it's general question.
How to change index correctly in any plugin sql file.
This could happens with any plugin 

Plugin update is not able to manage this code : UNIQUE KEYcan_unq(can_table,can_pid)

**Comment by SimSync** [comment]
@Jimmi08 You will have to delete indexes manually with a "DROP INDEX" statement.
I did some tests and adding index works, but changing not... At least orphaned indexes will not be deleted.

Put this statement into the "<plugin>_setup.php" into the update_required method. See "forum_setup.php" for further reference.

**Comment by SimSync** [comment]
Did some more tests... adding a unique index with db update adds the index, but doesn't recognize an existing index. It just adds a counter to the indexname.
Unfortunatly, the update procedure doesn't recognize that the table is updated and OK and continues to show the "Update required" button...
And for each click on update an additional index will be added t othe table.
This only happens during update, not while creating a new table.

**Comment by Jimmi08** [comment]
@SimSync I removed first one form database (I mean this:   KEY `can_pid` (`can_pid`))  then I run update.  I didn't help.
I am not able to write this in _setup.php , There is not enough examples for me.    But I posted it to canonical plugin, @CaMer0n should be write this _setup file.

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n I assume that the key definition retrieved from the database during db update doesn't match the key definition (order, uppercase, lowercase, etc.) that is used in the _sql.php
Not sure if i'm able to debug this... But i would give it a try tomorrow evening (if Cameron isn't quicker).

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n I did some debugging and what i can say is, that fields and indices can't be removed from the database, just by removing (or renaming) the field or index from the "*_sql.php" file.
It's simply not implemented at the moment. 
You need to do this manually in the "*_setup.php". I can help you with this if you want.

I still need to find out why a (unique) index with more than 1 field seems not to be recognized which results in implenting the index again and again.

**Comment by Jimmi08** [comment]
@SimSync thank you for your effort. There should be at least some message before run update (they you need manually change you tables) 

I let original index (not unique) and do more checks while updating to avoid doubles.   You should add examples to _basic plugin. There are now only install options. - how to check if there is new version, where put these checks etc.  It would be great help to everybody. Thank you.

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n Yes, a hint in the _sql.php about updateing, renaming, removing indexes and also regarding renaming and removing fields would be of help.
Plus some examples in the _blank plugin showing how to check fields and indexes and how to remove them.

**Comment by rica-carv** [comment]
I don't know if i understand it correctly, but isn't this a issue wiht [MySQL itself](https://dev.mysql.com/doc/refman/8.0/en/constraint-primary-key.html)?

Or did i miss the point somewhere?

**Comment by Moc** [comment]
Am I correct in saying that this issue can be closed thanks to #3190 and #3191 ?

**Comment by SimSync** [comment]
@Moc More or less. Indexes are still not deleted, updated or renamed automatically (simply because it is currently not supported), but i've added methods for detecting and checking of indexes and also some documentation about what is supported and how to "work around" in the "_Blank" plugin (files: _blank_sql.php, _blank_setup.php).
With the new method and the documentation, @Jimmi08 should be able to solve her issue.

**Comment by Jimmi08** [comment]
Not tested, but I will create new one if I notice something similar. Thanks to all
