### ISSUE TITLE
problem with SEF-URL and layouts

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3184]
I just notice this:

my URL was:

`https://www.e107.sk/news/view/33/industrial-theme-now-available-for-download`

and it takes layout for download plugin with full page
`<body id='layout-full-page' >`

Original layout was default (sidebar-right).

I now know about it, I will change url but it shouldn't work this way. Or there should be at least some warning that you layout will be changed because sef-url.

**Comment by CaMer0n** [comment]
@Jimmi08 In your theme preferences, try using "/download" as the selector to change to full-page.

**Comment by Jimmi08** [comment]
@CaMer0n Thank you. I didn't get this.  Solved,
