### ISSUE TITLE
Posts in category sort my pages

### ISSUE THREAD

**Issue by JoniPeti** [e107inc/e107#3185]
Dear dev team!

How can you make comment_type in the comment database a page, instead of chapter_id or chapter_sef?

Thanks!

**Comment by Moc** [comment]
Hi, 

Can you describe what the end result is that you are trying to accomplish? There may already be a way to do what you want.

**Comment by JoniPeti** [comment]
I would like to make a rating system.
Users are evaluated by the posts in the chapter of the selected book and by the user's ranking set values. 

To work properly, the database comment_type field in the comments panel should replace the page_chapter instead of the page.

Sorry if I can not understand, I use a google translator.

**Comment by rica-carv** [comment]
Isn't there already a v1.x plugin with a working rating system, if i remember correctly?

**Comment by JoniPeti** [comment]
Version 4.1 was successfully installed. Has anyone converted it to Version 2? How do I download it?

**Comment by rica-carv** [comment]
You can always upload a plugin via ftp to the e107_plugins directory, it always worked and will work, as last resort....
