### ISSUE TITLE
upload not working properly under php 7.0+

### ISSUE THREAD

**Issue by KaeLhun** [e107inc/e107#3189]
I've tested this issue on a site with php version selector. 
Until php 5.6 the upload.php works normally. 
7.0 and above only seems to success the uploading but it isn't appear on admin uploads page to approval. In the temp directory (e107_system/uniqueID/temp) there is the uploaded file in both cases. 

It would be very important to make it work and I don't want to switch back to older php. 
Is there any workaround until this problem fixed?

**Comment by KaeLhun** [comment]
update: I've tested on 2.1.8 version and it works but only one download category choosable. (We can live with this, the essence of the issue is solved)

**Comment by CaMer0n** [comment]
Thanks @KaeLhun :+1:
