### ISSUE TITLE
meta description with forum post and tinymce

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3192]
Hi,
it's e107 thing or my setting issue? Code [html] is part of meta description
Thanks

![image](https://user-images.githubusercontent.com/5429548/41541169-1f93adbc-7312-11e8-9c42-1ba06b8ebe1e.png)

Result:
 
 
![image](https://user-images.githubusercontent.com/5429548/41541403-a30db7d2-7312-11e8-91a1-ec7c5f04ae29.png)

**Comment by Moc** [comment]
I think I noticed the same thing happening on one of my installations.
