### ISSUE TITLE
Issue on the off-chance a plugin is renamed or deleted.

### ISSUE THREAD

**Issue by BillyBoy0823** [e107inc/e107#3193]
If a plugin gets renamed or deleted without uninstalling it first, there will be a semi-blank entry showing in the "Installed" section of the Plugin Manager and the OPTION to "Upgrade to version 1.0". I was not able to find an easy way to clear it out. 

![renaming a plugin](https://user-images.githubusercontent.com/4243062/41546653-3ed21e64-72ec-11e8-827f-718df4d3f760.PNG)

**Comment by Jimmi08** [comment]
Confirmed. I noticed this too in lately.  Rescan doesn't help.

**Comment by BillyBoy0823** [comment]
Seems the easiest solution is to set-up the Database Utilities - SQL Verification Do a Plugins Folder Check. This could checks if a plug-in's  directory is empty, renames, or deleted, If so, then remove it from e107_plugin table and give a warning "WARNING - xxx Folder empty or no longer exists - Removed Entry".

This solved it for me, and cleared out any erroneous entries.

I may tackle it if you guys don't beat me. (Retired, and looking for things to do.) I'm ready and eager to help!

Should I keep my fingers out of it? It's been a while.

**Comment by Moc** [comment]
You're always welcome to submit pull-requests! :+1:

**Comment by CaMer0n** [comment]
Clearing system cache should now solve this issue.
