### ISSUE TITLE
menu name is filled with username when editing custom page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3196]
I noticed this some days ago.

I edit page (menu title is empty), I click on Save button, and I am stopped on third tab (Menu)  because menu name is filled with my username (Menu title is empty, so it stops - thanks for it, but it's annoying)

Chrome.

**Comment by MikeyGMT** [comment]
Mine too #3131 I found that chrome sees we have a password (in page settings) and it wants us to have a username, and guesses that menu_name is our username field and it also ignores autocomplete=off

**Comment by Jimmi08** [comment]
I didn't notice it here.   It happened it to me with menu configuration too:

field:  
```
		$fields['shortcode_menuTableStyle']        = array('title'=> "ID for tablestyle", 'type'=>'text', 
		'writeParms'=>array('size'=>'xxlarge')); 
```

Output:
`<input type="text" name="shortcode_menuTableStyle" value="" maxlength="255" id="shortcode-menutablestyle" class="tbox form-control input-xxlarge" data-original-title="" title="">`

And username is prefilled.

**Comment by Jimmi08** [comment]
This can be fixed by using placeholder.

**Comment by Moc** [comment]
Fixed in https://github.com/e107inc/e107/commit/9dfe6728a83477f480b4b6d3d82f8cda43187566
