### ISSUE TITLE
problems  with forum

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3198]
1. I still get this message (it's new installation)
![image](https://user-images.githubusercontent.com/5429548/41619555-ff16f422-7406-11e8-8c6a-78593d91ee70.png)

2. I can't find forum 
I see on Frontend that they are existing, but they are not displayed in admin area. I exported forum xml data and missing forum is there, it's not just displayed in admin area
 
Forums are there:
![image](https://user-images.githubusercontent.com/5429548/41679060-3b84c422-74cd-11e8-9316-09ff20775fa6.png)

**But they are not in admin area (only parent forum)**
- there is forum with similar structure and subforums are displayed

No idea what to do.  Sef-urls checked, no missing, no doubles. 
I fixed this by set forum_parent and forum_sub to 0 in PhpMyAdmin, then moved all topics a deleted problematic forums.

**Comment by Moc** [comment]
@SimSync I suspect there are some PHP 7 incompatibilities. Perhaps you are interested in looking into this?

**Comment by Jimmi08** [comment]
Hi, I am sometimes blind, I was so desperate yesterday, that I didn't see this, yes 27 records, you are right. 

On localhost was latest github,  the same issues as on server version. 

On server I fixed it by setting all missing forums as main (in phpmyadmin), then moved topics and deleted those problematic forums.  I checked similar structured forums, no difference, only word meta in name. 

If I find xml with problematic data, I will catch you on gitter.   And I will clean this issue and make separate issues as soon as I confirm them after update.  

Thank for help.

**Comment by Jimmi08** [comment]
Ordering moved:  
https://github.com/e107inc/e107/issues/3203

**Comment by Jimmi08** [comment]
Searching moved here:
https://github.com/e107inc/e107/issues/3204

**Comment by SimSync** [comment]
@Jimmi08 
1. is only an orphaned message. I've fixed this already in my install.
2. For this point, it would be great if you can send me the data from the table e107_forum (maybe as .sql file?)
I can send you my email address in private message on gitter if you like.
