### ISSUE TITLE
Upload category No display

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3199]
![feltolteshiba](https://user-images.githubusercontent.com/35248010/41625719-0a2cdf30-741a-11e8-8084-a39c70c7e58c.png)

**Comment by Jimmi08** [comment]
Do you try to upload to download categories or custom plugin?  
 
![image](https://user-images.githubusercontent.com/5429548/41646017-00af388c-7473-11e8-9820-1b8c39217ef9.png)

Insert image of your download categories.

**Comment by Jimmi08** [comment]
it could be related
https://github.com/e107inc/e107/issues/3201

**Comment by tyupika93** [comment]
Smooth download extension is in use and this problem ..

**Comment by tubbis2** [comment]
I think my problem is related. Upload is only showing some of the download categories. See attached printscreens.
![downloads](https://user-images.githubusercontent.com/29007419/48588676-5cd98600-e938-11e8-96e7-a50aa2784626.png)
![upload](https://user-images.githubusercontent.com/29007419/48588677-5cd98600-e938-11e8-876c-6be61fa1c69d.png)

**Comment by Moc** [comment]
This should now be fixed. Please let us know if it is not.
