### ISSUE TITLE
download category - icon in admin s not displayed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3205]
After upload png icon  to icon category: 

![image](https://user-images.githubusercontent.com/5429548/41679974-38373a7c-74d0-11e8-9572-9a0b83656fb6.png)

After saving, list and next edit is correct. So just only little detail. 
Thanks

**Comment by Moc** [comment]
@Jimmi08 Can you still reproduce this? I just tested and it worked fine for me.

**Comment by Jimmi08** [comment]
It's ok.
