### ISSUE TITLE
gallery - how this is possible or how find the reason?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3207]
Clean install, only core plugins.
Cache cleared (from admin and from browser too)

I couldn't get gallery templated (no changes were applied), so I did this:

![image](https://user-images.githubusercontent.com/5429548/41739326-05827eb4-7595-11e8-9564-a283ea214fb8.png)

On this path:
![image](https://user-images.githubusercontent.com/5429548/41739345-15e37bfa-7595-11e8-8b31-7d90fb223ad1.png)

But on this path gallery still works:

![image](https://user-images.githubusercontent.com/5429548/41740158-741f0156-7597-11e8-8285-c79d565f693c.png)

**Comment by Jimmi08** [comment]
Ok, I found the reason - with sef-url it's going to index.php, not original gallery.php file. 
 
this is really confusing

**Comment by rica-carv** [comment]
That's why i hate use SEF URLS in e107 (and anyway, i still don't use them...)

**Comment by Moc** [comment]
The gallery is quite special in this case. The SEF URL implementation is different to other plugins if I remember correctly

**Comment by Jimmi08** [comment]
Yes, but FAQs uses controllers too. 
And this solution restricts template system - you can use only caption, start, item and end template item. 
Otherwise, magic :) 
But I prefer to have code under control. 

PS. Almost with each plugin there is different version how e107 constants work.  I have done news, page and forum_thread.  No the same rules.
