### ISSUE TITLE
php 7 compatibility - preg_replace() with /e

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3216]
The reason:

`$textstring .= preg_replace("/\{(.*?)\}/e", '$\1', $ONLINE_TABLE);`

> preg_replace(): The /e modifier is no longer supported” error in PHP7

**Comment by Jimmi08** [comment]
But they can be uncommented...
![image](https://user-images.githubusercontent.com/5429548/51196768-1c729600-18f0-11e9-9ac9-1d5d5e06565d.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I haven't found any others. A lot of the files you have listed have already been corrected. The code you found exists as comments only.

**Comment by Jimmi08** [comment]
@CaMer0n Yes, it's possible, I didn't check them then.   Thank you.
