### ISSUE TITLE
Language admin ui bug

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#3219]
The second option of the side menu doesn't allow the display of the admin ui dropdown menus....
1st menu option, correct:
![lingua_-_preferencias_-_area_do_administrador_selos_portugal_-_2018-06-25_20 07 43](https://user-images.githubusercontent.com/17130530/41870337-b03f7886-78b3-11e8-8f9f-624b7dc50d76.png)

2nd menu option, incorrect:
![untitled 1](https://user-images.githubusercontent.com/17130530/41870350-be983b84-78b3-11e8-8e2e-2ea5ce7826cf.jpg)

Furthermore, the second option currently doesn't displays nothing.

Today's github files...

**Comment by tgtje** [comment]
I just mention it: please check : The Portugese lang pack is 3 years old>  LANG_LAN_04 (admin/lan_language php) 
;listing of file 
define("LANG_LAN_03", "Tabelas");
define("LANG_LAN_05", "Não instalado");

English : define("LANG_LAN_04", "Deprecated LANs");

**Comment by rica-carv** [comment]
@tgtje Not quite, it was updated in 2017, by me.
And now, when i was trying to update it, the admin ui has these errors, which were not there previously....

Furthermore, this happens either in English o Portuguese, so it must be a non language related bug...

**Comment by tgtje** [comment]
Yes i thought you worked on it, i use the pack available from content management ..., most of the files are 3 y. :;)
Anyway : fresh github new install (local 7.1.1)  
![pgall](https://user-images.githubusercontent.com/1811857/41994648-6d088484-7a4f-11e8-9481-c28445c11a62.jpg)

**No issues**  not in English, not in Dutch and also not to be seen using P. (lang check reports 736 issues with v2 lang pack P. )....... ?????

**Comment by rica-carv** [comment]
@tgtje Beware, you're testing it in php 7.1.1, i'm with 5.4.....
I already expressed my fears bacause all the cjanges made to suit php 7.x
It's the direction to go, but if almost everything is stop working in 5.4, why not make minumum requirements php 7.x???

**Comment by tgtje** [comment]
@rica-carv  did install a local wamp (php 5.4.12) After enabling curl and exif all worked fine.
However your issue appears indeed in this version.
after fiddling around i (mind my liitlte coding experience) it comes to line 899 of the E107_admin/lancheck php  >  	if(!empty(e_VERSION))   (it is the empty (think defined would be better according coders??) and the last ).  _commenting (disabling) this line has result (for me and page appears)_

**Comment by rica-carv** [comment]
After clean install of today's github files, CURL enabled in php 5.4, problem still persists....

**Comment by tgtje** [comment]
Just tested on a existing 5.6.32  (local) site d.d. feb 2018  no issues.

However i synced it now to github (2.1.9) and above  mentioned issue is present > debug shows no error.
applying the same 'fix' does NOT help. So error is likely somewhere else....

**Comment by rica-carv** [comment]
Tested in PHP v5.6, and working...
