### ISSUE TITLE
after update problem with SSL

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3221]
After update to latest github I see this in admin (frontend is correct). Cache cleared.
What else check?

![image](https://user-images.githubusercontent.com/5429548/41974131-55d55266-7a17-11e8-9117-d665ac16e54d.png)

**Comment by Moc** [comment]
Looks like the fronts are loaded over HTTP instead of HTTPS

**Comment by Jimmi08** [comment]
Yes, I know, but I don't know why. It was correct before update. but site is running php 7.2, I have other problems, so I switched to 7.1 and I will see in 15 minutes.

**Comment by SimSync** [comment]
@Jimmi08 Please verify once the PR is merged. Thanks!

**Comment by Jimmi08** [comment]
@SimSync I tested it manually, it fixed it, so I am closing it now not to need to watch this. Thank you for quick fix.
