### ISSUE TITLE
problem with ['writeParms']['optArray']  and php 7.1 and 7.2 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3222]
I have dropdown defined this way for prefs:
```
$this->prefs['link_open_all']['writeParms']['optArray'] = array(
      '5'=>LCLAN_OPT_42,
      '0'=>LCLAN_ITEM_17,
      '1'=>LCLAN_ITEM_18,
      '4'=>LCLAN_ITEM_19
      );
```

It works without problem.

But then I have similar dropdown defined for admin_ui field:
```
$this->fields['link_open']['writeParms']['optArray'] = array(
      '0'=>LCLAN_ITEM_17,
      '1'=>LCLAN_ITEM_18,
      '4'=>LCLAN_ITEM_19
      );
```
and it works only in php 7.0.   In php 7.1. and 7.2 dropdown is emty.

**Comment by Jimmi08** [comment]
https://github.com/rica-carv/links_page/issues/6

**Comment by SimSync** [comment]
@Jimmi08 How is the "writeParms" initialized in the field definition? This way: `'writeParms'=>array()` or `'writeParms'=>""` or something different?
Try initializing writeParms with array().

**Comment by CaMer0n** [comment]
@Jimmi08 Like @SimSync said, PHP 7.1+ won't let you turn a string into an array.

**Comment by Jimmi08** [comment]
But then you should change generating of dropdown field -  'writeParms'=>array() -  if it's already this way., sorry, I didn't notice.

**Comment by CaMer0n** [comment]
@Jimmi08 I did some time ago. The default is an array();

**Comment by Jimmi08** [comment]
Good to know, I didn't notice this. Thank you.

**Comment by Jimmi08** [comment]
Just note. Used plugin builder just now:
`'orientation'		=> array('title'=> 'Orientation', 'tab'=>0, 'type'=>'dropdown', 'data' => 'str', 'help'=>''),`

no 'writeParms'=>array()  for preference there.

**Comment by CaMer0n** [comment]
hmm, thanks for letting me know. @Jimmi08

**Comment by Moc** [comment]
I think this is fixed in: https://github.com/e107inc/e107/commit/6201c906a69e8d45b92999e5e37195738daf3046#diff-feabae59a9072ebff57fcc4f13b6d0e6R5643
