### ISSUE TITLE
user extended fields doesnt work with non bootstrap themes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3228]
Version 1:

![image](https://user-images.githubusercontent.com/5429548/42078550-38ce72da-7b7d-11e8-9be8-9b330ef61c39.png)

Version 2:
![image](https://user-images.githubusercontent.com/5429548/42078572-4fde38de-7b7d-11e8-8df9-01b277380800.png)

Switch to bootstrap3:
 
![image](https://user-images.githubusercontent.com/5429548/42078772-0aeeb16c-7b7e-11e8-9f5b-914d1dc4eb17.png)

Adding to not boostrap theme:
define("BOOTSTRAP", 3);

fields are displayed:
 
![image](https://user-images.githubusercontent.com/5429548/42078756-fb0c4868-7b7d-11e8-8e03-cee82dacf756.png)

**Comment by Jimmi08** [comment]
I was table to narrow problem to this line:  
`$text = $this->sc_userextended_cat($cat['user_extended_struct_id']);`

**Comment by Jimmi08** [comment]
My mistake.  
```
			$legacy = (file_exists( e_THEME_ABS.$themeArray[$id].'/theme.xml') === false);
			define('THEME_LEGACY',$legacy);
```
if my theme has theme.xml file, it can't use legacy version.   I can't override this in theme.php

so it leaves only with bootstrap and not bootstrap templates.

**Comment by Jimmi08** [comment]
`e107::getCoreTemplate('usersettings', 'extended-field');`

returns something only with bootstrap defined.

**Comment by SimSync** [comment]
Does this theme have a theme.xml?

**Comment by Jimmi08** [comment]
yes, theme has theme.xml  so THEME_LEGACY is false. 
It's updated theme, it just doesn't use bootstrap.

**Comment by SimSync** [comment]
@Jimmi08 Are you able to test something for me by changeing a codeline in the following file?
`e107_core\shortcodes\batch\usersettings_shortcodes.php` line 465
Replace 
`if(THEME_LEGACY === true)` 
with
`if(THEME_LEGACY === true || !deftrue('BOOTSTRAP'))`

Make sure, you don't have defined 'BOOTSTRAP' somewhere in your theme.

**Comment by Jimmi08** [comment]
THANK YOU!

function sc_userextended_cat($parm = '') has the same test, shouldn't it be the same? To avoid problems if there will no new array for cats.

but this work too.

**Comment by SimSync** [comment]
I'll check it.
