### ISSUE TITLE
how to display debug info from plugin_setup.php during installation?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3229]
I have set debug mode on (I tried info too).
Using this in  install_post($var)  method :
```
$mes = e107::getMessage();
$mes->addDebug("Converting $k to $nk");
```
doesn't display anything.

I tried to add $mes->render();  to this method, but it didn't help. There is always message about succesful installation, nothing more.

**Comment by Jimmi08** [comment]
It would be nice to have a method in setup where to put all checks for some plugin (f.e. if other plugin is installed, if something was generated, minimal core version) or at least place where it's is outputed.  If you put it admin_ui (admin_config.php), it's outputed 2x or on wrong places..  
Something like renderHelp() but in place where now are core messages displayed. 
Just idea.

**Comment by Moc** [comment]
There are several options for this in core already, plugin.xml dependencies (for php modules, other plugins). Not sure about e107 core version requirement. 

Custom requirements can be done in plugin_setup: `function install_pre()` (see `_blank` plugin)

**Comment by Jimmi08** [comment]
That was just example.  I look for option to display messages when you are in admin area of plugin itself. Above table Admin UI.

**Comment by Moc** [comment]
I think putting it in the `init()` method should do the trick, I'll look up an example.

**Comment by Moc** [comment]
```php
function init()
{
	e107::getMessage()->addInfo("Testing for Jimmi");
}
```

**Comment by Jimmi08** [comment]
I tried this with featurebox as example now. It took me 10 minutes to get why it didn't work for me. Of course, my mistake. Thanks
