### ISSUE TITLE
question to legacy user and user_extended fields

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3231]
Old site updated to version 2.1.8 (maybe 1/2 year ago first update)

I tried to copy users to localhost and noticed that there are left old legacy fields in table users.
`user_timezone, user_viewed, user_forums, user_new `
I needed to add these fields manually to database to be able run import to new install. 

I noticed that user_timezone, user_viewed are moved to user_extended table.   What about user_forums, user_new ?

Can I delete those fields from user table? There is risk - old plugin could still work with old data (no error that it uses old field not new one)

Thanks

**Comment by Moc** [comment]
I think they are safe to delete.
