### ISSUE TITLE
question - how to set admin_ui over 2 tables

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3232]
You can use new admin_ui over 2 tables using LEFT JOIN

Example:
```
    protected $listQry      	= "SELECT   u.user_id, 
    u.user_name, u.user_loginname, u.user_email, u.user_image,    
    ue.user_birthday, ue.user_timezone FROM #user AS u 
    LEFT JOIN #user_extended AS ue ON ue.user_extended_id = u.user_id
      ";
```
![image](https://user-images.githubusercontent.com/5429548/42107164-ad058a4a-7bd6-11e8-86f8-0729d3bd3cf6.png)

Only problems are filtering and sorting.  It adds alias "u" to all fields.   The same with filtering. 
![image](https://user-images.githubusercontent.com/5429548/42107224-d53a8a88-7bd6-11e8-8d07-0a80e66c707d.png)

Maybe there is some setting I missed .  I could probably use 2 fields with method type but this would be great to get this work.

Thank you

**Comment by CaMer0n** [comment]
@Jimmi08 Here are the examples in the e107_admin directory. 

![image](https://user-images.githubusercontent.com/2825679/43095342-5a96c570-8e6a-11e8-81b8-001bf533317d.png)

**Comment by Jimmi08** [comment]
@CaMer0n
 I saw this, I did left join the same way. I am able display those fields. 

**Filtering and sorting** don't work for me - see screen above how order query looks (I mean when you click on field name in admin UI to sort data or you use searching functionality in admin UI).

**Comment by CaMer0n** [comment]
I think it could be because of the order you are doing things. Are you joining user_extended to the user table, or the user table to user_extended?

**Comment by Jimmi08** [comment]
```
protected $listQry      	= "SELECT   u.user_id, 
    u.user_name, u.user_loginname, u.user_email, u.user_image,    
    ue.user_birthday, ue.user_timezone FROM #user AS u 
    LEFT JOIN #user_extended AS ue ON ue.user_extended_id = u.user_id
      ";
```

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks, but what is the value of `$table` ?

**Comment by Jimmi08** [comment]
`protected $table			= 'user';`

>  Are you able to replicate the filtering problem in the above admin areas? (eg. news etc)
I missed this one. What do you mean by this?

**Comment by CaMer0n** [comment]
@Jimmi08 What I meant is - does this problem you mentioned occur in the 'news' area?

> Filtering and sorting don't work for me - see screen above how order query looks (I mean when you click on field name in admin UI to sort data or you use searching functionality in admin UI).

**Comment by Jimmi08** [comment]
Tested in user area (displayed field Timezone). Result by clicking on Timezone column label (nothing is displayed) :
 
![image](https://user-images.githubusercontent.com/5429548/43538936-b1ed7304-95c3-11e8-955a-005baec310a1.png)

With news -  fields u.user_id,u.user_name  are not as field in listing form.

**Comment by Jimmi08** [comment]
Fixed
