### ISSUE TITLE
add option DELETE to unistalled plugins

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3238]
Unistalled plugins don't have option Delete

If you remove them via FTP, they left in plugin table and are displayed

Rescan doesn't help

![image](https://user-images.githubusercontent.com/5429548/42131832-c56d17b6-7d0b-11e8-8024-7a032e4f1931.png)

**Comment by rica-carv** [comment]
I think a purge plugin or command would be in order.
For instace, it would scan the database / core and clean it up. Something like ccleaner. but for e107....

**Comment by Jimmi08** [comment]
too complicated, just option remove record from table plugin in database would be enough.  Or plugin rescan should remove all records if path is not available.

**Comment by rica-carv** [comment]
I also agree, plugin rescan should automatically do a db cleanup of orphaned plugins.

**Comment by Moc** [comment]
Closing as duplicate in favour of  #3193
