### ISSUE TITLE
CSS Bug in (admin) theme

### ISSUE THREAD

**Issue by ajaybhargav** [e107inc/e107#324]
If two radio buttons side by side, when hovering over the first one, second radio button shifts to left side.. see images below

Normal:
![css-issue-1](https://f.cloud.github.com/assets/927133/526195/82df1220-c11b-11e2-9dab-9aef54b79f21.jpg)

When hover second radio button shifts a little left
![css-issue-2](https://f.cloud.github.com/assets/927133/526196/9400014a-c11b-11e2-854f-4e80f45772aa.jpg)

**Comment by Moc** [comment]
Replaced by on/off switch
