### ISSUE TITLE
question - what is different or what needs to be set - <br> vs \n

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3240]
I have v1 site with this disclaimer:
![image](https://user-images.githubusercontent.com/5429548/42137880-5517574c-7d74-11e8-8fa6-e6baf443f627.png)
each line is displayed on new line.

But the same content in version 2 is displayed in one line, no new line.
To get the same result, I needed to add <br> tags after each line.
Is this correct behaviour?

Thank you

**Comment by SimSync** [comment]
Yes, if you use TinyMCE on your new site and bbcode or just a textbox on your old site.
TinyMCE is a html editor and html doesn't know the new line charater that is used by bbcode or a plan textbox.
So you need to add the new line tag <br/> manually.

**Comment by Jimmi08** [comment]
Oh, settings are the same, they do everything to have exact copy of v1 site. 
 I can check this at the evening (all sets are in Text rendering option, aren't?).  I will ask them for screenshot from old site, I have access only to new one.

**Comment by SimSync** [comment]
Your screenshot shows bbcode. If you didn't change it, it was bbcode in v1 too.

**Comment by Jimmi08** [comment]
yes, but parsing of this field was probably changed. Or I don't know...  I notice somewhere setting to replace /n by <br> but it was in tinymce I think.  When I know that it should work the same way, I will try to find what is different.

**Comment by Jimmi08** [comment]
This is setting from new site:  Tinymce is not installed either.
 
![image](https://user-images.githubusercontent.com/5429548/42208597-da67353c-7eac-11e8-8fc5-2daebf51b56a.png)

What I know - they just CTRL-C text from version 1 and copy it to sitedisclaimer field.  Originally it was updated, but result was the same. 

This is happened with forum post too.

**Comment by Jimmi08** [comment]
original setting from version 1:

![image](https://user-images.githubusercontent.com/5429548/42213263-8c3c8f7c-7eb8-11e8-8a04-787b66da74a1.png)

**Comment by SimSync** [comment]
Just did some tests with the site disclaimer on my install here.
As long as the disclaimer doesn't contain any html tags, the `\n` where translated to `<br/>`.
Once i added a html tag (`<i>` in that case), the `\n` wasn't translated anymore and all was on one line.

That behaviour is definitely different against v1. Maybe @CaMer0n can say if this is a bug or a feature ...

**Comment by Jimmi08** [comment]
The updated forum (this is original of forum post, just bbcodes used)
http://www.outlawsracing.com/e107_plugins/forum/forum_viewtopic.php?4293.last
![image](https://user-images.githubusercontent.com/5429548/43048884-66948ec8-8def-11e8-8afb-f24addd44379.png)

to version 2 (no WYSIWYG):
http://www.outlawsracing.xyz/e107_plugins/forum/forum_viewtopic.php?4293.last
- it removed new lines

![image](https://user-images.githubusercontent.com/5429548/43048866-0d2d84c0-8def-11e8-9bd3-6536d3a4887a.png)

![image](https://user-images.githubusercontent.com/5429548/43048875-47c7f0f2-8def-11e8-8f36-a098b412ddeb.png)

**Comment by CaMer0n** [comment]
I'd need to see the bbcode data (directly from the database), before and after upgrade, so I can test with it.

**Comment by Jimmi08** [comment]
@CaMer0n Probably no problem,  they say you did update.  They will contact you soon.

**Comment by Jimmi08** [comment]
I was able to narrow problem.  I inserted bbcodes from version 2 to some my old forum and result is displayed correctly:
![image](https://user-images.githubusercontent.com/5429548/43154123-8cb8f582-8f73-11e8-9524-9b6581cedaf8.png)

Example of data:

```
[color=#00ff00][size=22]Outlaws Racing rF2 Event Packages [/size][/color] 
[link=https://mega.nz/#F!dBNl3IZJ!3Q8AxxylYFtLEswY6SbS7g][size=14]AM_FIAGT3_2012_0935[/size][/link]
[link=https://mega.co.nz/#F!8IFwyACL!rLVp8xU0g8h83pnDVgelsA][size=14]BTCC[/size][/link]
[link=https://mega.co.nz/#!RV1zHLiD!gQGmqjLX-Fqx8Ln7M4hT7FCKPVzTZV_g9OkhPqGpN4Y][size=14]BMWE90[/size][/link]
[link=https://mega.nz/#!VN9xybaD!M1X5GAoQ5cpLioeSjYflOw27BTR5930qmQ0zPgLH9HQ][size=14](Camaro)ISI_Chevrolet_CamaroGT3_2012_v1.61[/size][/link]
[link=https://mega.nz/#!QFUlTASa!Lt5RuNuxXImO8oxjUjSnHmDTfyXhm-3yV7KkMfygv2U][size=14]Celica_GTO v2.00[/size][/link]
[link=https://mega.nz/#!cEsACQZY!jfHb6goEwsN91WEah61p7wWMHkHFkfcNqGv8jFU4-eQ][size=14](Covette)ISI_Corvette_C6RGT2_2009_v1.62[/size][/link] *^(/)
[link=https://mega.co.nz/#F!QBUH1aqQ!bAE1cL6rWTQwR5IBiZ828g][size=14]DTM T5s[/size][/link]
[link=https://mega.nz/#!QIVimAgD!ksTiwI-OoJfiJEgpBC72Omavzjsop1KPYhMW5jXz4lM][size=14]Endurance Series[/size][/link]
```

**Comment by CaMer0n** [comment]
This is helpful, thank you @Jimmi08

**Comment by CaMer0n** [comment]
@Jimmi08 You have HTML mixed with BBCODEs. I believe this is your problem. 

    [center]<b><a href=..

**Comment by Jimmi08** [comment]
@CaMer0n there are over 7000 forum posts, why this wasn't problem before?

**Comment by CaMer0n** [comment]
@Jimmi08 Because there was a security hole in earlier versions which has since been patched.

**Comment by Jimmi08** [comment]
@CaMer0n 

This is just display, data are already saved.  I get this check when you post data.  But if you forbid html mixed with bbcodes, what is purpose of this preference?

![image](https://user-images.githubusercontent.com/5429548/43184026-78761cde-8fe7-11e8-8ec0-b2a08b1da8de.png)

**Comment by Jimmi08** [comment]
@SimSync I have no idea.  I just can't tell somebody with 7000 post to rewrite them manually.  They will stick with version 1 because this. 

br tags are missing at all if you have mixed content. 

V1: 2x br tag if you use html, 1x br after [link]
![image](https://user-images.githubusercontent.com/5429548/43188581-ba2b568c-8ff4-11e8-96d0-991472f1f48f.png)

v2: no br tags
![image](https://user-images.githubusercontent.com/5429548/43188604-d32beb06-8ff4-11e8-8c57-64bf6cd239f1.png)

I thought that something was wrong with update but it's not this case. 

If I remove that html part,  links works correctly [links] is replaced with <br>.  So why it mess all content not only that html part? 

And this is reason why I can't switch from tinymce to bbcodes (to set wysiwyg off) - all newlines are ignored and text is messed then.  And I am sure that there is setting for tinymce - convert newlines to br.

**Comment by Jimmi08** [comment]
I found reason:

```
		if($this->isHtml($text)) //BC FIx for when HTML is saved without [html][/html]
		{
			$opts['nobreak'] = true;
			$text = trim($text);
		}
```

and then:
```
		if(preg_match('#(?<=<)\w+(?=[^<]*?>)#', $text))
		{
			return true;
		}
```

It removes lines if I put html code inside <code> tag too.

**Comment by Jimmi08** [comment]
@wrxxy

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/3793

**Comment by Jimmi08** [comment]
There is no point to have this issue opened, it is too old. I am not able to check if this is still issue and no similar problem was reported. And tinymce4 had many updates from that time. Thanks
