### ISSUE TITLE
e_bb.php is not supported addon ?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3241]
I have plugin with e_bb.php.  Scan plugin directory shows it's not supported anymore. 

How to replace it?

**Comment by Moc** [comment]
I think this has not been migrated to v2 yet

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please share a screenshot of what you're seeing?

Still supported here in plugin_class :

	protected $_addon_types = array(
		'e_admin',
		'e_bb',
		'e_cron',
		'e_notify',
		'e_linkgen',
		'e_list',

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/43166160-20f69c78-8f96-11e8-81f0-01079e53234f.png)

Content of e_bb.php

```
      <?php
      $bb['name']        = 'sp';
      $bb['onclick_var'] = "[sp][/sp]";
      $bb['icon']        = e_PLUGIN."spoiler/images/spoiler.png";
      $bb['helptext']        = "Spoiler: [sp=subject]Text to be hidden[/sp]";
      $BBCODE_TEMPLATE .= "{BB=sp}";
      $BBCODE_TEMPLATE_SUBMITNEWS .= "{BB=sp}";
      $BBCODE_TEMPLATE_NEWSPOST .= "{BB=sp}";
      $BBCODE_TEMPLATE_ADMIN .= "{BB=sp}";
      $BBCODE_TEMPLATE_CPAGE .= "{BB=sp}";
      $eplug_bb[] = $bb;
      ?>
```

**Comment by Jimmi08** [comment]
But with my plugin - later done (the same site):

![image](https://user-images.githubusercontent.com/5429548/43166275-68d047b0-8f96-11e8-94ef-cf2d4a56a195.png)

**Comment by Moc** [comment]
Check for empy lines before and after the PHP tags. This will cause the red cross to show instead of the green checkmark. The functionality should not be affected however.

**Comment by Jimmi08** [comment]
This works now. Tested with Advanced BBcodes plugin.
