### ISSUE TITLE
feature request - possibility to use bbcodes for specific areas

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3242]
I need tinymce for news, pages, but for forum bbcodes should be enough.

It would be great to have using wysiwyg for bbarea as parameter, if it's null, use core setting  

Or separate setting of wysiwyg for forum plugin

**Comment by SimSync** [comment]
Not only for forum, but maybe also for PM and other plugins.
That was the reason why i never used the wysiwyg editor in e107... it was always system wide.

**Comment by Jimmi08** [comment]
this should be fixed now. Thanks
