### ISSUE TITLE
forum view - is this correct?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3243]
this test: `if (empty($FORUM_VIEW_START))`

What is the point? It's always empty, because template is loaded after this test.

```
if (empty($FORUM_VIEW_START))
{
	if(THEME_LEGACY !== true)
	{
		 $FORUM_VIEWFORUM_TEMPLATE = e107::getTemplate('forum','forum_viewforum');
	}
	else
	{
		if(file_exists(THEME.'templates/forum/forum_viewforum_template.php'))
		{
			require_once(THEME.'templates/forum/forum_viewforum_template.php');
		}
		elseif (file_exists(THEME.'forum_viewforum_template.php')) //v1.x
		{
			require_once(THEME.'forum_viewforum_template.php');
		}
		elseif (file_exists(THEME.'forum_template.php'))  //v1.x
		{
			require_once(THEME.'forum_template.php');
		}
		else
		{
			require_once(e_PLUGIN.'forum/templates/forum_viewforum_template.php');
		}

	}
}
```

**Comment by SimSync** [comment]
Looks like some orphaned code lines.

**Comment by rica-carv** [comment]
@SimSync Not quite, more some old legacy code, to allow v1.x themes to work with forum....
If i recall correctly, that variable is for v1.x theme templates...

**Comment by SimSync** [comment]
Yes, you are right. But the templates are loaded after that line. But in case the template is defined and loaded elsewhere it should stay as it is for the moment. It is not a real performance killer... :wink: :laughing:

**Comment by Jimmi08** [comment]
@SimSync is right.    Just my 2 cents  

You can have template only with variables (legacy, no array - for example copy template from v1), 
then you can have template only with arrays (f.e. in new theme) 
and you can have combination (both version in the same file like core forum template now)

To solve this:  the core is trying to decide what template to use by testing THEME_LEGACY.   

THEME_LEGACY is true if you haven't theme.xml, so yes, it's old theme from v1 (CORRECT - it has influence on other things too) 

How this should work with forum:
if it is THEME_LEGACY - load template by require_once()
else if $FORUM_VIEW_START is empty - load e107::getTemplate()
otherwise load template by require_once(). 

But how you know that $FORUM_VIEW_START is empty?  You don't know before loading template by require_once().  

Do you see that there is not logic/system in this?  Only waste of source?  Because as soon as you fix this and you will load template file directly as the first, there is no point to use e107::getTemplate() at all, because arrays are already loaded.

How this should work:
- old theme, no theme.xml,  THEME_LEGACY is true, use old way with old paths (like in v1)
- define in your new theme with theme.xml that you want to use old variables for forum (it needs to be separated for each plugin) -  use old way with new paths (templates folder in theme)
- otherwise always use only new way

But rest of code needs to work with any variations. And it works with forum plugin because after using new way, it still fills old variables and uses them. 

Oh, and please don't advise me to rewrite variables to arrays in theme templates.  It's fix but not solution.

**Comment by Moc** [comment]
Yeah this is a matter of supporting backwards compatibility or not. We continuously have issues because in the past there were only a few standards. Themes and plugins were coded in different ways. Trying to ensure backwards compatibility is therefore quite the challenge.

**Comment by Jimmi08** [comment]
@SimSync you can rewrite half of core code then.  Code above is mistake - somebody tried to solve back compatibility wrong way. 

 I have never seen this and I saw a lot of old themes:
> In your old theme.php, there is an require_once on the forum template or maybe somebody placed the template code directly in the theme.php.

Solve this with forum is easy because there is already code that put arrays back to variables (so I just change variables to arrays in template according it. Double work? Nevermind, at least it's clear). 

@Moc  I say this with all seriousness:  there was more rules (in fact only one - where to put your template in theme) and more clear code related to templating than now where there is mixing way.  V2: there is not enough documentation to manage all variants and it doesn't support overrriding by other plugins.  And different parts use different approach (Familiar?) And after seeing real code that returns templates...  sorry, this is total mess. What is improvement?  time loading?  nope. Maybe from the beginning, but not now. 

I respect new standards (directory system)  but  I don't see improvement with e107::getTemplate() against required one file (no problem with arrays).  Instead loading one php file you now have with each element request to server.  And you repeat yourself.  

There was great idea at the beginning of v2. I remember that. But during time how more complicated situation  and more compability issues appeared they tried to solve it by exceptions...  if I don't know how to call correct template - or better what parameters for _getTemplate() means, who will know?

**Comment by Moc** [comment]
No matter what, we need to: 

- Outline what ways of loading a template and overriding templates there are
- Set a standard or preferred way
- Document this 
- Make sure core applies these standards

**Comment by CaMer0n** [comment]
The standard is: 

    $FORUM_VIEWFORUM_TEMPLATE = e107::getTemplate('forum','forum_viewforum');

Everything else is a backward compatibility fix which will be different for every plugin. 
Forum is an exceptional case. Some old theme.php files include forum template code directly without any separate file. These exceptional cases apply to very old plugins like this.

**Comment by rica-carv** [comment]
Just my two cents (I know i'll be painting a bullseye on me, but here goes anyway)
Instead of keepeing and maintainig code to keep old plugins & themes working, why not discard that?
For me it's frustrating and time consuming, not to mention that a lot of v1.x themes and plugins are not maintained anymore....
I know there's a lot of work from v1.x, and it shouldn't be dumped, but why not take orphaned themes and plugins code and upgrade them? IT's time consuming? Yes, but if everybody uses that old plugin or theme yet in v1.x and don't want to upgrade to v2.x because of that old plugin / theme, we'll always be stuck with old legacy code in v2.x and a lot o people still using the unmaintende v1.x of e107.....
Just my two cents... (now, shoot me.... :dart:)

**Comment by CaMer0n** [comment]
@rica-carv I won't shoot you, but the person who has a custom v1.x theme they spent a lot of time on might feel like it if we were to do that. Perhaps you can explain the frustrating part, so we can address that.
