### ISSUE TITLE
bbcodes in forum titles and breacrumb issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3245]
If you use bbcodes in forum title, it works  (images and emoticons):
![image](https://user-images.githubusercontent.com/5429548/42209509-19c6b02a-7eaf-11e8-9477-e02bd258efb8.png)

But breadrumb title is not able to display emoticons:

![image](https://user-images.githubusercontent.com/5429548/42209514-1eb8f3ea-7eaf-11e8-8aef-96b075fd50f5.png)

And in links  it looks like this (the same in version 1)
![image](https://user-images.githubusercontent.com/5429548/42209566-457e8cce-7eaf-11e8-96cb-8acc5ec42d52.png)

Shoudln't be titles in breadcrumbs displayed just text (remove bbcodes?)

Hm, what then left there if there is no text, just bbcode?  Any idea how to get titles this way?

**Comment by SimSync** [comment]
@Jimmi08 The not parsed emoticon looks like a bug.
But the issue on the drop down isn't so easy solvable. The standard select/option doesn't support images...

**Comment by Jimmi08** [comment]
@SimSync Thanks.  
It should be stripped somehow  - only text should left for dropdown. The same for breadcrumbs in my opinion or meta title tag (I didn't check this one).  Using only image as forum title should be deprecated/forbiden (in meaning - if you do it, its your problem) . Title should be stripped and if nothing left, forum ID could be displayed (or nothing).  

So solution is not parsing this to display those images or emoticons, but displays it in readable form - only form.

**Comment by SimSync** [comment]
@Jimmi08 @Moc My proposal would be to restrict the forum title to plain text only and to strip all html or bbcode, incl. emoticons.
In a second step i could imagine to add a new field e.g. `forum_image` where an image can be assigned to the forum, which will be displayed in the forum table next to the name (before or after is up to the theme designer). This way, the site admins can use images in their forums, but it doesn't interfere with the breadcrump, sef url, jump-to-forum-dropdown, and so on...
@Moc What do you think?

**Comment by Moc** [comment]
I agree :)

**Comment by SimSync** [comment]
@Moc see #1412 (once the PR is merged)

**Comment by CaMer0n** [comment]
I think you mean PR #3378 ;-)   To be merged for v2.2.0
