### ISSUE TITLE
weird url in location of guest users

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3258]
I noticed this in admi area too, but now I did it manually and it happens to me too:

Code:
```
	$ol = e107::getOnline();
	$quests = $ol->guestList();
	foreach($quests as $val)
	{
		$online_location = $val['user_location'];
	}
```
Result: 
`<a href="/e107_themes/Race-cars/Array?1530392436">... </a>`

**Comment by CaMer0n** [comment]
If you add `print_a($val['user_location']);` inside the loop, what is returned?

**Comment by Jimmi08** [comment]
It doesn't happen always, just sometime.
But because `'<a href="' . $online_location . '">' . $online_location_page . '</a>`
that value would be `/e107_themes/Race-cars/Array?1530392436`

**Comment by CaMer0n** [comment]
I'm curious what the "Array" contains.

**Comment by SimSync** [comment]
@Jimmi08 Once it happens again, is it possible for you to check the e107_online table? Just to find out, if the string "Array" is already in the database or is happening somewhere later ...

**Comment by Jimmi08** [comment]
@SimSync  Of course.
Just to have it complet:
https://github.com/e107inc/e107/issues/3239

**Comment by SimSync** [comment]
Does this happen only if the user is on forum pages? Or also on other places.

**Comment by Jimmi08** [comment]
I would quess it's more bot spiders -  I noticed it with theme name in path.  I will watch this. Thank you for fix that arrays.

**Comment by Jimmi08** [comment]
Now it's with users, trying to get to sql, but in Database Tools I don't see option export table online.

![image](https://user-images.githubusercontent.com/5429548/42734758-bdbe177e-8849-11e8-84c9-72bbb791ea13.png)

Could you check why is not possible to export table online from Database tools?

**Comment by Jimmi08** [comment]
I was able to get this:
![image](https://user-images.githubusercontent.com/5429548/42734809-434ce6d6-884a-11e8-8c10-cc9199e6dd6b.png)

EDIT: sql (but data are already different) sent via gitter

**Comment by Jimmi08** [comment]
This code you find is inserted here:

```
		// Load stored in preferences theme lib paths ASAP
		// TODO - decide if THEME should directly use themeLib() or
		// we store paths in 'e_jslib_theme' on theme installation only (theme.xml)!
		$theme_libs = e107::getPref('e_jslib_theme');
		if(!$theme_libs)
		{
			$theme_libs = array();
		}
		$this->themeLib($theme_libs);

```
So I checked e_jslib_theme pref.
On site without problem:   (new install)
![image](https://user-images.githubusercontent.com/5429548/42736501-a6d0501c-8868-11e8-958b-215c48a38a12.png)

On site with problems:  (updated from version 1 - php 5.6.35) 

![image](https://user-images.githubusercontent.com/5429548/42736548-b736d070-8868-11e8-832e-b0a6a25a09ed.png)

And this "array" is inserted.

**Comment by CaMer0n** [comment]
@SimSync While that would fix the problem, I would prefer to fix the cause, ie, the upgrade routine that produced it, rather than just a 'band-aid' fix for what could be a larger problem.

**Comment by SimSync** [comment]
@CaMer0n No question, the cause has to be found and fixed. But the problem itself has also to be fixed.

**Comment by SimSync** [comment]
@CaMer0n Just checked the prefs on an older site, that was converted from v1 to v2.1.7 a year or so ago and the prefs where OK.
The only pref that is a string of "array()" instead of an array is "social_login". But this is also in my clean v2 installation on my local computer...

**Comment by CaMer0n** [comment]
@Jimmi08 @SimSync I believe it probably occurred during a plugin upgrade. For example 'linkwords' which uses an array as a pref value.  From what I can see, it was not being converted correctly in the plugin_class. 
Commit coming up.

**Comment by Jimmi08** [comment]
New update, it's there again:
![image](https://user-images.githubusercontent.com/5429548/45038555-bc2a3880-b061-11e8-9622-bebf992738d0.png)

**Comment by Moc** [comment]
@CaMer0n @SimSync Is there anyway to test this further to confirm whether the issue is resolved?

**Comment by Jimmi08** [comment]
I will reopen it if it happens to me again. Not important now.

**Comment by CaMer0n** [comment]
Deleting the prefs and then running the update might be the best workaround for now.

**Comment by SimSync** [comment]
As i already said. I would put a test for this string into the update routine and just change the value from "array" to "array()". With this, i'm sure that all prefs containing the illegal value are fixed.
Unfortunatly, that means that we will never find out where this error comes from.
On the other side, i don't even know where to start searching...
