### ISSUE TITLE
system information on not boostrap theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3259]
You can't click and close system messages on not boostrap theme

![image](https://user-images.githubusercontent.com/5429548/42412203-f8c0fa82-8207-11e8-9211-54a4819ef3aa.png)

**Comment by Moc** [comment]
Does this happen on every non-bootstrap theme? If not, there may be a JS incompatibility

**Comment by Jimmi08** [comment]
I did this:
-  update to latest github
- remove loading bootstrap from theme.xml in bootstrap3 theme
- but loading bootstrap css  (otherwise you don't see it)
- remove {ALERT} to get some message 
RESULT: you can't close this message because it depends on boostrap script

![image](https://user-images.githubusercontent.com/5429548/42586568-b588ec50-8538-11e8-8306-959747278890.png)

without bootstrap css:
![image](https://user-images.githubusercontent.com/5429548/42586657-e28a48b6-8538-11e8-968e-1c38d7fba493.png)

And I confirm next problem with tooltip: (yes, I removed tooltip from theme.php in bootstrap3  in footer-inline - otherwise this error is there 2x)
![image](https://user-images.githubusercontent.com/5429548/42586739-118c8b06-8539-11e8-86f3-11575feff7d0.png)

**Comment by Jimmi08** [comment]
I found it:   issue about tooltip, it's related to need of bootstrap script
https://github.com/e107inc/e107/issues/3187

**Comment by CaMer0n** [comment]
@Jimmi08 I believe a test for 'tooltip' needs to be added to the javascript, before the 'tooltip' function is called. @SimSync Does this one interest you?

**Comment by SimSync** [comment]
I can look into it. But...
1. There are 2 issues: js and css as also the whole formatting is gone and you can not see a difference between different message types or even see that it is a message at all. To disable the function call to tooltip is the smallest issue.
2. Which result is desired? Just fix the js error or the styling issue or both.

@CaMer0n All those workarounds for non bootstrap themes are hurting the e107 source code...

**Comment by CaMer0n** [comment]
@SimSync I agree about the source code. I think fixing the js to check for tooltip should be enough.

**Comment by Jimmi08** [comment]
@SimSync tooltip error in console is away, but original issue is still there.

**Comment by SimSync** [comment]
You have to include the bootstrap js to have the close functionality on messages.
Another question: Has the styling of the message changed? Please check if the backcompat.css file is loaded. This should be loaded automatically on legacy and non bootstrap themes.

**Comment by Jimmi08** [comment]
@SimSync I agree but...   if core is outputing something what depends on script what can be not included in frontend, than without bootstrap constant defined it should output this part of bootstrap script itself if debug is on.  

And what I really dislike is this:  https://github.com/e107inc/e107/issues/2770

It's opposite situation, I have theme with boostrap files  but I want to use not boostrap templates (Bootstrap constant is not defined).   bootstrap is not just name of framework, it's general word,  everything should be related on constant, not on file name.  
(PS not tested lately, if this is changed already, I missed it)

Or another example:  a lot of html themes use bootstrap.css and js but not full code. Bootstrap version should be used only if there is full bootstrap functionality.  Yes, I know how to fix this, but it's about principles.

**Comment by Jimmi08** [comment]
This was solved as @SimSync said. It wasn't so hard in the end.   
Just part of bootstrap javascript was needed - alert.js.  Everything else works. Thanks.
