### ISSUE TITLE
Forum statistics - Top Posters, Top repliers

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3260]
I got weird numbers for Forum statistics

If I get it right, top posters are thread (topic) + posts, topic starters are just threads (topic creating) and top repliers are just post (answers to topic)

**Top repliers**

![image](https://user-images.githubusercontent.com/5429548/42414264-d089491e-8231-11e8-9a25-da1328b86ad6.png)

Query is correct,
But there is this:
`$poster['post_count'] = $poster['post_count'] - $top_repliers_data_c[$uid]['thread_count'];`

**Top topic starters, -**  these numbers are correct.

 What is different between top posters, if user extended field sums just posts?

**Comment by rica-carv** [comment]
I wonder if that's some old v1.4x forum code left behind......

**Comment by Jimmi08** [comment]
I looked at it. Before there was one table, in version 2 there are 2 tables.  So in user_forums value were before all "posts", you got topics/threads as first post of thread and you got replies as all posts (user_forums) minus threads. 

But now in user_forums value they are just answers, not topics, so you get the same values posters = repliers. And because they are already "cleaned" from first topics, you got negative values.  

You can see this on my forum too. I haven't noticed this before, only when I compare plugin results (updated old queries) with actual forum statistics. 

For me fix for this would be:
- sum threads and post to user_forum field (extended) (I didn't notice recalculate option for this in admin) - this fix poster statistics
- and repliers are just posts.

But maybe I get this all wrong.

**Comment by Jimmi08** [comment]
Yes, this is what I did in plugins. But forum_posts are repliers,  forum_threads are topics.  Problem is that you can't order both together - reason why user_forum should be sum of them (forum_posts + forum_threads) and then you can order them.   If you look at original code from v1, you will see there were just 3 big queries, now it's so complicated with arrays, that I wasn't able to fix it.

**Comment by rica-carv** [comment]
I think it's dummy to grab data from the database and make calculations in arrays...
I'll try to have a look into it, as soon i can...

**Comment by Moc** [comment]
Maybe too late but still adding. This is how I interpret these terms: 

- Top Posters: those with the most amount of forum posts (regardless of whether they started a topic or not)
- Top Topic Starters: those who created the most amount of topics (new discussions, not replies)
- Top Repliers: Those who created most posts - the amount of topic starts (first post in a topic)

**Comment by Jimmi08** [comment]
@Moc  Are you aware that now you can't have post that starts topic, they are in separate tables now.  Otherwise your text is confusing or I got it wrong (not used to old forum)

> Top Topic Starters: those who created the most amount of topics (new discussions, not replies)

this is clear and correct **(no problem),**  sum of forum threads (or before first post that started topic)

> Top Posters: those with the most amount of forum posts (regardless of whether they started a topic or not)

Yes, I think the same, so this is sum of threads (before first post) and all posts (replies)
State:  it's doesn't work this way. This should be in extended field user_forums like before. Then you can order it.  
Fix:  change counting user_forums field

> Top Repliers: Those who created most posts - the amount of topic starts (first post in a topic)

Not sure, sometime first reply is not reply at all,  but still better then now.

**Comment by rica-carv** [comment]
Well, just theoretically, i think it's this:

> Top Topic Starters: those who created the most amount of topics (new discussions, not replies)

Agree, and counted from table forum_thread, which theoretically holds the threads started...

> Top Posters: those with the most amount of forum posts (regardless of whether they started a topic or not)

Agree, and counted from table forum_posts, which theoretically holds the replies posted...

> Top Repliers: Those who created most posts - the amount of topic starts (first post in a topic)

Disagree. Repliers for me are the ones who replie AFTER a thread is started and has the first post. Therefore, it should be counted from table forum_posts, which theoretically holds the replies posted, MINUS each thread first post (that theoretically should / is the thread starting post)...
Or, alternitavelly, it should be `Top Posters MINUS Top Topic Starters`, i think....

I really need to give a pratical look at it, with data, to see what's going on....

**Comment by Moc** [comment]
Hmm not sure if I understand you correctly, we might be meaning the same thing. I used the `-` sign which may be ambiguous. 

I meant that replies are all posts excluding the very first post in a topic (the topic start post). I made a function for it here: https://github.com/e107inc/e107/commit/c15c22ad7d7a154c7d3cb632ed28f7b5a3f86b68

**Comment by Jimmi08** [comment]
This is change that rica-carv did and it looks like correct number now.
Weird thing is that Total Commander file comparation didn't show this change. Very disturbing for me.

![image](https://user-images.githubusercontent.com/5429548/42655365-3539b1da-861c-11e8-941a-7375cc7ae0df.png)
