### ISSUE TITLE
question:  how to get tables responsive with bbcode or tinymce?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3266]
I am now testing tinymce editor vs bbcode (without tinymce)

I noticed problem with tables with using bbcodes
- there should be tag <div class="table-responsive">  around table if bootstrap3 is defined.

The same in tinymce (I noticed this in news).

Is this somewhere in core or can I change this in theme? If I can, how?

I can do it manually this way with bbcodes:
 
![image](https://user-images.githubusercontent.com/5429548/42628540-b7285de6-85d0-11e8-9906-658284e67052.png)

**Comment by CaMer0n** [comment]
I suggest using only TinyMce with an html template.

**Comment by Jimmi08** [comment]
Solved with javascript or not needed anymore
