### ISSUE TITLE
download plugin - meta description tag

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3270]
Download plugin use Tinymce on description field. 

but more than year ago you started to use this field for meta tag Description. 
Yes, you remove html tags
`e107::meta('description',       $tp->toText($metaDescription));`

but description (with changelog) can have many words and for this tag is recommended 

`Meta descriptions can be any length, but Google generally truncates snippets ~300 characters (this limit increased in December 2017). It's best to keep meta descriptions long enough that they're sufficiently descriptive, so we recommend descriptions between 50–300 characters.`

so can you at least strip it and not insert full description?  And remove new lines or what is it?
It looks just weird to have description this way in source code:

![image](https://user-images.githubusercontent.com/5429548/42636002-ec743738-85e7-11e8-81fe-05c04458dff1.png)
And you can't use code tags  `{JM_DISABLEBLOCK_CODE}` , because result is:

![image](https://user-images.githubusercontent.com/5429548/42636030-02002a94-85e8-11e8-998f-68815e392250.png)

**Comment by Moc** [comment]
Please check if it's ok now
