### ISSUE TITLE
Hardcoded text color e107_admin/menus.php

### ISSUE THREAD

**Issue by Axeia** [e107inc/e107#328]
The e107_admin/menus.php page seems to contain quite a bit of styling in the HTML itself which is causing issues with my theme. Not impossible to work around with the theme css style. But I somewhat doubt it's intentional to work like this in the first place.
The page shouldn't fiddle with color:/background-color: imo.
![hardcoded](https://f.cloud.github.com/assets/1092845/541903/ccbd59da-c218-11e2-88e4-40684db9506d.png)

**Comment by CaMer0n** [comment]
A lot of this was rewritten. Closing, but re-open if necessary.
