### ISSUE TITLE
featurebox_menu displays alert box without debug mode 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3290]
I just installed BS GAME PLUS theme by fizi
he uses this code in theme.php

```
<div class='col-md-12'>
      {SETSTYLE=slider}
      {MENU=featurebox}
    </div>
  </div>
```

There was alert box displayed for all visitors because this code in featurebox_menu.php:

```
if(!$text)
{
	echo "<div class='alert alert-block alert-warning'>".$message = e107::getParser()->lanVars(FBLAN_25, array('x'=>$type))."</div>";
//	e107::getMessage()->addDebug("There are no featurebox items using the ".$type." template");
}
```

Why is there direct echo?

**Comment by tgtje** [comment]
related #3074

**Comment by CaMer0n** [comment]
@Jimmi08 @tgtje It's from a pull-request from @yesszus . 

I'll fix it.. It was only ever meant to be for debugging. 

![image](https://user-images.githubusercontent.com/2825679/43038440-6f9a8c5c-8ccd-11e8-974e-a0a2552145e2.png)
