### ISSUE TITLE
gsitemap

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3291]
Hello.
Why created news can be added to gsitemap only manually or by creating a link.
Why did not the news automatically appear in the gsitemap?

**Comment by Jimmi08** [comment]
@Evgura I wanted this long time ago, but it's not possible without changing database or creating new plugin for this.  
gsitemap table saves only url not table name ('news') and IDs and relations based on string...    not good idea.

**Comment by Evgura** [comment]
This is a very sad mistake.

**Comment by Jimmi08** [comment]
It was this way in version 1 too. In fact there is big improvement in new version with e_gsitemap addon.

**Comment by Jimmi08** [comment]
@Moc this can be closed or at least testing required or waiting for feedback
