### ISSUE TITLE
Nothing next to "To:" field in mailout creator

### ISSUE THREAD

**Issue by PMKielstra** [e107inc/e107#3303]
Whenever I go to create a new mailout, it has all the fields -- sender name, subject, et cetera -- ready to go, but there's nothing next to the To: field.  I'm using e107 2.1.8 on PHP5.  Thank you for taking a look at this.
![capture](https://user-images.githubusercontent.com/4313413/43043841-e204b28e-8d92-11e8-9e1e-decc9bc511aa.PNG)

**Comment by Michaelkielstra** [comment]
Never mind -- I figured it out.  If anyone else has this issue and wants to send an email to their users, you have to go to "Preferences" and enable "Registered users" as an email address source.

**Comment by Michaelkielstra** [comment]
My other e107 install has just developed the same problem, but it isn't fixed even when I select "registered users".  When I deselect "registered users", it says "settings not saved as no changes were made", which leads me to believe that the database has not properly been updated.  Which option is changed in the database to enable sending mail to registered users?  Thanks.

**Comment by CaMer0n** [comment]
@Michaelkielstra I have just updated it so that it will revert to 'users' if no option is checked.
