### ISSUE TITLE
e107::unserialize() Parser Error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3305]
Updated to latest github to have latest version but it was there before update

Logged as main admin, debug mode, no errors.

Logged as user (via admin area), debug mode on and user see this:
![image](https://user-images.githubusercontent.com/5429548/43046840-341e6880-8dcf-11e8-997d-c9ea4bf60450.png)

![image](https://user-images.githubusercontent.com/5429548/43046865-8ce7450e-8dcf-11e8-8100-365c92db3f41.png)

I tried to log as other user, it's ok, problem is only with this user. Profile looks correctly, it's real user.

**Comment by CaMer0n** [comment]
@Jimmi08 The data is buggy. This commit should fix it.
