### ISSUE TITLE
how to insert html code to menu?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3307]
This code 
`<div id="lr-servers" theme="dark"></div>`
is stripped to 
`<div id="lr-servers"></div>`

How to insert html code to editor?

![image](https://user-images.githubusercontent.com/5429548/43048989-c0384dc4-8df0-11e8-85a7-70d4d7f9be6e.png)

**Comment by CaMer0n** [comment]
@Jimmi08 AFAIK 'theme' is not a valid HTML5 attribute, which is why it is automatically stripped. 
Also, if you wish to use HTML directly in the bbcode editor, you should use `[html] [/html]` around your code.

**Comment by Jimmi08** [comment]
@CaMer0n but it will be still stripped, won't be?...  it's update from V1 site, they used it this way before

**Comment by CaMer0n** [comment]
@Jimmi08 Yes. It's invalid and will be stripped. If it were me, I would find out how the 'theme' attribute is used (by javascript?) and then replace it with data-theme="dark" etc.

**Comment by Jimmi08** [comment]
@CaMer0n  there is more parameters. 

I used textarea field (no editor) for inserting javascript code and then using e107::js()... 

this way:  `$code = html_entity_decode($plugPrefs['liveracers_script'], ENT_QUOTES);`

I noticed weird thing:
this code:
`lr.src = window._lr.url + '/Scripts/api.js';`

is saved correctly (echoed $code): 
![image](https://user-images.githubusercontent.com/5429548/43096485-8cb92f9e-8eb9-11e8-924e-8003470b663d.png)
but then plus is stripped in prefs (displayed in pref)
 
![image](https://user-images.githubusercontent.com/5429548/43096554-c0582cc4-8eb9-11e8-9a36-294679346944.png)

**Comment by Evgura** [comment]
@Jimmi08 The script in the menu can be added as follows...
Create folder = > xxx_menu = > there file = > xxx_menu.php => file write this code =>

<?php

$text = <<<EOF
<div style="text-align: center;">
<script ..............<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div>
EOF;

$ns->tablerender("Menu Name",$text);

?>

All this is placed in the folder " Plugins"

**Comment by Jimmi08** [comment]
@Evgura I know.  I already made plugin for this.  That user is not able to modify php file.

**Comment by Evgura** [comment]
Ок

**Comment by CaMer0n** [comment]
@Jimmi08 Please update and test again, thank you.

**Comment by Jimmi08** [comment]
It works. Thank you.

**Comment by CaMer0n** [comment]
@SimSync Here's the test: https://github.com/e107inc/e107-test/blob/master/tests/unit/e_parseTest.php#L93
