### ISSUE TITLE
Issue: Database Update from 2.1.8 to 2.1.9+

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3311]
So I just updated my site (sync to github) - updated the database from 2.1.7 to 2.1.8 - then 2.1.8 to 2.1.9 - says it's complete but the button to update the database to it is still available.

Next thing, I went to Preferences - Notice this:
![capture1](https://user-images.githubusercontent.com/5818022/43049770-e9dfee26-8dc2-11e8-8692-7ce8f66ab117.JPG)

Viewing the Image
![capture2](https://user-images.githubusercontent.com/5818022/43049772-f115d3e0-8dc2-11e8-89c8-143a00b68538.JPG)

I don't know if this was intended - use to display the images in the first screenshot.

**Comment by CaMer0n** [comment]
@LaocheXe The thumbnail issue should be resolved. 
For the update, please check if you have a _common_videos entry in the e107_core_media_cat database table.

**Comment by LaocheXe** [comment]
I do not see a _common_videos entity - _common_image and _common_file

![db-capture](https://user-images.githubusercontent.com/5818022/43162634-4352b7ce-8f51-11e8-9f39-7b9086ab103e.JPG)

**Comment by CaMer0n** [comment]
@LaocheXe Thanks. Did you run the update already?

**Comment by LaocheXe** [comment]
Yes I did

**Comment by CaMer0n** [comment]
@LaocheXe Are you still seeing a button to update 2.1.8 > 2.1.9 ? (after upgrading from github)

**Comment by LaocheXe** [comment]
Yes

**Comment by CaMer0n** [comment]
@LaocheXe Should be fixed now. Thank you!!!
