### ISSUE TITLE
Language strings not rendering

### ISSUE THREAD

**Issue by Michaelkielstra** [e107inc/e107#3312]
I set up a contact form on the default contactus.php page, but, instead of the title being "Contact Us" or something similar, it's "LANCONTACT_02".  Picture attached.  I was able to quickly fix it by adding `require_once("e107_languages/English/lan_contact.php");` to the start of the contactus.php file, but this obviously isn't maintainable and doesn't support changing the language.

![localisation bug](https://user-images.githubusercontent.com/4313413/43066957-fca81cf4-8e5d-11e8-8e51-34a9239b159b.PNG)

**Comment by tgtje** [comment]
There is no contactus.php file helas, only contact.php.
This file is fitted to use the languages ( e107::includeLan(e_LANGUAGEDIR.e_LANGUAGE.'/lan_'.e_PAGE);)
Now assuming there is a "mistake"in new file by title?? (saved as contactus.php ??? ), there is no call for the languages (as you mentioned added)

As there has been no issues for a long time, this issue could be talked about at https://e107help.org/

**Comment by rica-carv** [comment]
You shouldn't mess with core files directly, they'll be overwritten with every update.
Instead, you should make a custom contact template in the theme you're using currently, that's the correct way to do it....

**Comment by CaMer0n** [comment]
@Michaelkielstra It should be fixed now, please update from github. Thank you.
