### ISSUE TITLE
question - what to check - related with user_currentvisit  

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3313]
There is plugin that display today's members. 

Problem is that it "switches" to next day not in midnight .  

Code looks like this:
`"SELECT user_id, user_name, user_currentvisit FROM " . MPREFIX . "user WHERE DATEDIFF(FROM_UNIXTIME(user_currentvisit),CURRENT_TIMESTAMP()) = 0 ORDER BY user_currentvisit DESC"; `

user_currenvisit is filled correctly (checked)
server time in INFO shows:  `Server Time Tue, 24 Jul 2018 06:18:22 +1000  ` 

Timezone is set this way:
![image](https://user-images.githubusercontent.com/5429548/43101411-a1fa4c76-8ec8-11e8-99dc-b00903af932e.png)

`SELECT CURRENT_TIMESTAMP();  ` returns
![image](https://user-images.githubusercontent.com/5429548/43101949-0cbb1508-8eca-11e8-82e5-535ce90e4f50.png)

There is difference about 17 hours behind.  

How to fix this?  

Is user_currentvisit related to timezone (general and user timezone?) How this works?

Thanks

**Comment by rica-carv** [comment]
Shouldn't that CURRENT_TIMESTAMP be add the timezone setting to get the correct time?
Or am i seeing wrong?

**Comment by Jimmi08** [comment]
@rica-carv I have no idea.  That CURRENT_TIMESTAMP is from database , and it's 17 hour behind real time (main admin time). Site timezone is 10 hour. Each user can have different timezone too.  Maybe that query should be different - it just checks if user_currentvisit is from today.

**Comment by wrxxy** [comment]
Is there a fix for this CaMeRon?
