### ISSUE TITLE
e107 social setting problem

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3320]
Hello :) My problem I can not set facebook login and registration because it writes url disabled and everything is well defined :(

Messanges:  "URL is blocked: This redirect fails because the redirected "URI" is not in the white list in the application's "Client OAuth" settings. Make sure Customer and Web OAuth Login are included and add all your application domains as valid OAuth Redirect URIs."
 

Images:

https://files.gitter.im/e107inc/e107/EgxM/kep.png
e107 version 2.1.8

**Comment by net1313** [comment]
e107 social plugin works. Your problem is that you can't understand what is callback URI OAuth in Facebook application settings.  
Must be something like that:  https://your-site.com/?route=system/xup/endpoint&hauth_done=Facebook

**Comment by tyupika93** [comment]
who is callback URI OAuth settings?

**Comment by net1313** [comment]
Go to settings of your app in "Facebook Login" link.

**Comment by tyupika93** [comment]
![kep](https://user-images.githubusercontent.com/35248010/43279397-206aac58-910e-11e8-8fe3-a632c7a4092d.png)
I'm just setting up an error message

**Comment by net1313** [comment]
Force WeboAuth Reauthentication = No
Use Strict Mode for redirect Uris = No

Deauthorize = ???? Why u're using the same callback uri ???
For example https://your -site.com/index.php?logout

And add to "Valid OAuth Redirect URIs" : https://your-site.com/index.php

**Comment by net1313** [comment]
Sorry !
Force WeboAuth Reauthentication = No
Use Strict Mode for redirect Uris = Yes

**Comment by tyupika93** [comment]
![kep](https://user-images.githubusercontent.com/35248010/43280528-64b018c8-9111-11e8-99e0-c0f663a71177.png)
It is now configured and the same error

**Comment by tyupika93** [comment]
Pls send me screenshoot your app settings basic and advanced.

**Comment by net1313** [comment]
No. Try to use your brain.

**Comment by Jimmi08** [comment]
@net1313 Are you using latest version?  
I had working FB signup (working App), I set it off before GDPR. Today I set it back ON and it didn't work.

**Comment by tyupika93** [comment]
now this is messange

Unsecured login disabled: You can not get access codes or access this application from an unsafe site. Try reloading the page with https: // prefix. 

what is problem?

**Comment by net1313** [comment]
> @net1313 Are you using latest version?
> I had working FB signup (working App), I set it off before GDPR. Today I set it back ON and it didn't work.

Have just tested Facebooik login and registration. e107 V2.17.  Works fine.

**Comment by Jimmi08** [comment]
@net1313 
`Use Strict Mode for redirect Uris = No`
This is not possible anymore
![image](https://user-images.githubusercontent.com/5429548/43281578-58fe67a2-9114-11e8-950d-5a17bf15620f.png)
![image](https://user-images.githubusercontent.com/5429548/43281594-64e0e6c6-9114-11e8-84b3-85c504643519.png)

Your comment was a bit hard because tyupika93  really tried to solve this before with me and when I found that FB SDK was updated and library has new version, I asked to create issue. 

@tyupika93 I will try it related to this:
https://stackoverflow.com/questions/49412342/how-to-turn-off-use-strict-mode-for-redirect-uris-in-facebook-app

**Comment by net1313** [comment]
> @net1313
> Use Strict Mode for redirect Uris = No
> This is not possible anymore

Yes, I know. See my previous comment.

> 
> Sorry !
> Force WeboAuth Reauthentication = No
> Use Strict Mode for redirect Uris = Yes

**Comment by net1313** [comment]
> Your comment was a bit hard because tyupika93 really tried to solve this before with me and when I found that FB SDK was updated and library has new version, I asked to create issue.

Maybe my comment slightly hard. But I solved this issue with Facebook after 3 days of testing. Everything and everywhere.

Yes  "FB SDK"  was updated but not OAuth mode.
And more, each Social media has its own application settings. I mean that Shitbook login/register application settings are different and incomrehesnive if u compare it with Twitter or Github.
But if your are humain and you can read (at least) the problem can be solved.

**Comment by Jimmi08** [comment]
@net1313   Yes, it works now for me.  I added your version of URIs to my old ones.

**Comment by net1313** [comment]
> now this is messange
> 
> Unsecured login disabled: You can not get access codes or access this application from an unsafe site. Try reloading the page with https: // prefix.
> 
> what is problem?

**tyupika93** There is search engine called Google. If you are not banned there try to type: 
"Facebook Unsecured login disabled: You can not get access codes or access this application from an unsafe site. Try reloading the page with https: // prefix"

**Comment by tyupika93** [comment]
do not let me turn off https

**Comment by net1313** [comment]
Something is wrong with the Github authorization.
It does not work for me anymore. What i have to enter in the field "Authorization callback URL" in application settings page?

**Comment by Moc** [comment]
@net1313 please create a new issue for this

**Comment by net1313** [comment]
I'm not entirely sure, because it used to work. Perhaps this is related to my Nginx settings. All I want to know is what's in the field "Authorization callback URL".

**Comment by net1313** [comment]
Sorry. It's OK now. I have update app settings, it works. Authorization callback URL = https://mysite.com/index.php 
(this is strange because before I got an error message)
