### ISSUE TITLE
TODO: Add jQuery 3 and Fontawesome 5 to the core. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#3321]
As it says. Pull-requests welcome. :-)

**Comment by net1313** [comment]
Yes, you can add more heavy scripts to the core and more other scripts to plugins, so your website loads more than 8 sec (as official e107 site uses - 12 css scripts and 12 js scripts). Even Github says NO to jQuery but you persist.  Maybe it would be better to offer users the possibility to switch any other css or js frameworks.

**Comment by CaMer0n** [comment]
@net1313 Thank you for raising this issue.  While your comment came across somewhat hostile and rude, I'll consider that as an unintended consequence of translation. 

### Firstly
May I ask, are you using js/css cache? 

Please see the following report for e107.org with js/css caching enabled: 
https://gtmetrix.com/reports/e107.org/v8vpwm5P

![image](https://user-images.githubusercontent.com/2825679/43351545-9d029220-91c8-11e8-8ecc-4eb53287fa1b.png)

There are a few recommended solutions for improvement, which are solved under the following conditions: 
1) Don't use github for the avatar images in the testimonials area. (Pagespeed: Leverage browser caching)
2) Use server-side image optimizer apps to improve compression. (Pagespeed: Optimize images)
3) Don't use github, paypal or google for content (Yslow: Add Expires headers)
4) Use a professional Content Deliver Network (Yslow CDN)

I have had js/css caching disabled because there is a small styling bug which affects the showcase page which I have not yet find a solution for.  However, for most other sites I have not found any issue with using the js/css cache feature. 

### Secondly
Regarding choosing other js frameworks.. 
jQuery is used by 73.3% of all websites
jQuery has a JavaScript library market share of `97.1%` .
https://w3techs.com/technologies/overview/javascript_library/all

As you can see, e107 "persists" in catering to the **vast majority** of users. 

Since, your comment appears to be provoked by my wish to allow theme and plugins developers to utilize  jQuery 3 and FontAwesome 5, please consider the following file-size comparisons:  

Jquery 2.2.4:  `83.57KB`
Jquery 3.3.1:  `84.89KB`

FontAwesome 4: `30.27KB`
FontAwesome 5:  `45.83KB`

Now, do you still believe that additional **16.88KB** of js/css code added to the core (and loaded once, then cached by the browser) is going to have a negative impact on performance? On the contrary, newer versions of scripts tend to be further optimized and improved for speed and performance. 

### And btw. 
Github's **login page** (WITHOUT all the other functionality) got this score: 
https://gtmetrix.com/reports/github.com/VXU8lJUX
![image](https://user-images.githubusercontent.com/2825679/43351848-8c0a198e-91cd-11e8-9835-fc8fe71e1601.png)

..so I don't consider it the best example to aspire to.
