### ISSUE TITLE
Deleted plugins icon 

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3327]
![kep](https://user-images.githubusercontent.com/35248010/43354342-acdb6cd0-924a-11e8-8ad4-85849b0a1080.png)

The plugin has been deleted and its icon remains between uninstalled plugins

**Comment by Evgura** [comment]
Try scanning the plugin directory.

**Comment by tyupika93** [comment]
who?

**Comment by tyupika93** [comment]
Verifying extensions after, they're there in the same way icons here

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/3238

**Comment by Jimmi08** [comment]
I am sure that was else one similar issue -  rescan plugin directory doesn't help.

**Comment by CaMer0n** [comment]
@tyupika93 How did you delete the plugin? 
1) Uninstall in the plugin-manager (and checking the box 'delete plugin folder' ) 
OR
2) Manually deleting the folder in e107_plugins?

**Comment by CaMer0n** [comment]
@tyupika93 It should be resolved for when you remove plugins in future. However, for these existing entries you'll need to manually remove them from the e107_plugin database table with phpmyadmin or similar.

**Comment by tyupika93** [comment]
I got the problem. After removing the original plugin, the tables will stick to the database.

**Comment by CaMer0n** [comment]
@tyupika93 Yes, exactly, the database table entry was remaining. This should now be solved.
