### ISSUE TITLE
Feature request - form_handler -  wysiwyg

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3330]
Possibility to use wysiwyg editor for custom plugin field without setting core pref.  So the rest of e107 can use bbcodes.  

This way
$frm->textarea - return simple textarea
$frm->bbarea - returns bbcodes (because wysiwyg prefs is set OFF)
$frm->wysiwyg() returns tinymce regardless central setting  (not changes for core, it's for plugin development).

Thanks

**Comment by CaMer0n** [comment]
Not quite what you suggested, but similar. You can now use wysiwyg = false in the bbarea to disable the global pref. 

    e107::getForm()->bbarea('post',$text,'forum','_common','large', array('wysiwyg' => false));

**Comment by Jimmi08** [comment]
Ha, this is else better! I just didn't think you would change so much used method.  Thanks.

**Comment by CaMer0n** [comment]
You're welcome @Jimmi08 :+1:
