### ISSUE TITLE
FR possibility to install older language packs

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3345]
Now there is 2.1.9 e107 version.
You got this if you want to install lang packs:

![image](https://user-images.githubusercontent.com/5429548/43674106-6769f340-97ce-11e8-8b2a-ceda4cf73851.png)

**Comment by CaMer0n** [comment]
It's already there for 2.1.8. 

https://e107.org/languagepacks.xml

**Comment by Jimmi08** [comment]
But admin displays nothing.
