### ISSUE TITLE
rescan plugin directory has different results as are in prefs

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3349]
I couldn't get news menus listed after update.
Reason:  news plugin is considered as not installed.

Rescan plugin:
![image](https://user-images.githubusercontent.com/5429548/43683828-955245c0-9894-11e8-8f57-fe53ac97adaf.png)

This in menu manager:
`print_a(e107::isInstalled('news'));`

![image](https://user-images.githubusercontent.com/5429548/43683833-a6c95118-9894-11e8-812c-70a83482295f.png)

Check in database: 
![image](https://user-images.githubusercontent.com/5429548/43683837-b7561d04-9894-11e8-91dd-e54300f8c041.png)

Prefs:
![image](https://user-images.githubusercontent.com/5429548/43683840-d88451ee-9894-11e8-995d-9fdaf9944964.png)

Those plugins are not there anymore, so rescan should them remove or something.  

I deleted this prefs and import via xml manually with manually created list.  Now is plugin news installed and I see menus. 

PHP 7

**Comment by Jimmi08** [comment]
Just info. On next day there was new information about updates.  After run this, menus started to work. 
Only problem left with plugin log.  It was listed as installed, but it wasn't  in prefs. It wasn't able to unistall (blank content after clicking on unistall).   It was fixed after manually changing this pref.

**Comment by Moc** [comment]
@Jimmi08 Were you able to reproduce this more often?

**Comment by Moc** [comment]
Should be fixed. Please re-open in case it's not.
