### ISSUE TITLE
relative datetime and translation 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3355]
if you use relative format of date, this is used:

`return ($mode ? $outputArray : implode(", ", $outputArray) . " " . LANDT_AGO);`

Order in my and Czech language is different
 LANDT_AGO +  relative date.

Is possible to add this to prefs?

**Comment by CaMer0n** [comment]
@Jimmi08 This should have been made like this.. `define("LANDT_XAGO", "[x] ago");`
We'll have to introduce a new LAN and use this existing one as a fallback.

**Comment by Jimmi08** [comment]
Thanks.  I fixed it by using different word. Now it doesn't look stupid, just weird. So it can wait.

**Comment by Moc** [comment]
@CaMer0n Why do we need a fallback? Can we not change it like this?

```php
define("LANDT_XAGO", "[x] ago");
define("LANDT_INX", "in [x]");
```
and
```php
if($older_date < $newer_date) // past
{

	$replace = implode(", ", $ret);
	$xago = e107::getParser()->lanVars(LANDT_XAGO, $replace);
	return ($mode ? $ret : $xago);
}
else // future
{
	$replace = implode(", ", $ret);
	$inx = e107::getParser()->lanVars(LANDT_INX, $replace);
	return ($mode ? $ret : $inx);
}
```

**Comment by CaMer0n** [comment]
Looks good @Moc ! :+1:

**Comment by KiraTheUltimate** [comment]
@CaMer0n @Moc 
With the latest github update:

![kepkivagas](https://user-images.githubusercontent.com/12445784/52912841-826b8800-32b7-11e9-8757-56a5f217b2f1.JPG)

**Comment by Moc** [comment]
@KiraTheUltimate This is probably because your language pack has not been updated yet. When you switch to the English language, what do you see?

**Comment by KiraTheUltimate** [comment]
It's good, thank you, then I waiting the hungarian language update.

@yesszus
