### ISSUE TITLE
Image resize on pages

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3356]
Hi! 

I know this is a frequently mentioned problem by me... but... since I've updated the system to 2.1.8 resizing the image doesn't work on the pages. I using WYSIWYG by the way.

When I edited an existing (or a new) page and saved, the size of the images changed to page width.
For example: https://starwarsmedia.hu/oldalak/star-wars-i-resz-baljos-arnyak (scroll down)

It should look like that (Not edited page. It remained at 2.1.7 version): https://starwarsmedia.hu/oldalak/star-wars-ii-resz-a-klonok-tamadasa

Editorial page: https://i.imgur.com/rxat8HC.jpg

https://i.imgur.com/3E5q3t9.jpg

I give any size to the image, it doesn't resize it, after I saved.

I don't remember to have edited the core files before the upgrade. When I change bbcodes, the resize is working and the problem is only on the pages, it works on news. What can I do?

**Comment by Evgura** [comment]
@KiraTheUltimate These sizes are most likely set in the theme file.

**Comment by CaMer0n** [comment]
@KiraTheUltimate fyi. You can simply drag images straight into the text editor here in Github. 
Are you using the "Appearance" tab to resize the image?
If you enable debug, you should see some placeholders below the selection in the media-manager modal window. You should see the size change there. (see below)

![image](https://user-images.githubusercontent.com/2825679/43810112-e6e6302c-9a6a-11e8-98ff-aa65832ffe29.png)

**Comment by KiraTheUltimate** [comment]
Usually I using this tab to resize the image. ->

![01](https://user-images.githubusercontent.com/12445784/43826194-080fba16-9af7-11e8-9697-a7c6cb4df381.JPG)

But if I using the appearance tab, the problem is the same.
Where can I find the debug option?

**Comment by KiraTheUltimate** [comment]
Didn't work, and the pages doesn't loading anymore, juts white page...... -> https://starwarsmedia.hu/oldalak/star-wars-i-resz-baljos-arnyak

:(

**Comment by KiraTheUltimate** [comment]
I put back the 2.1.7 version, and everything works well again.

https://starwarsmedia.hu/oldalak/star-wars-i-resz-baljos-arnyak

**Comment by CaMer0n** [comment]
@KiraTheUltimate Please message me on Gitter when you have time. I want to make sure that 2.1.9 doesn't break your site.

**Comment by CaMer0n** [comment]
Traced to css in custom theme style.css. Once removed the image widths were correct. TinyMce is behaving correctly.
