### ISSUE TITLE
question - 302 redirect with forum jump

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3359]
Why is with jump  used 302 redirect?

![image](https://user-images.githubusercontent.com/5429548/43829490-5ac2d2e0-9aff-11e8-8951-38fd57082b25.png)

```
	function checkForumJump()
	{
		/*if(isset($_POST['fjsubmit']))
		{
			$this->redirect(e107::getUrl()->create('forum/forum/view', array('id'=>(int) $_POST['forumjump']), '', 'full=1&encode=0'));
			exit;
		}*/

		if (!e_QUERY || empty($_GET['id']))
		{
			$url = e107::url('forum','index',null,'full');
			$this->redirect($url);
		//	header('Location:'.e107::getUrl()->create('forum/forum/main', array(), 'full=1&encode=0'));
			exit;
		}

	}
```

```
	public static function redirect($url = '', $http_response_code = 302)
	{
		self::getRedirect()->go($url, true, $http_response_code);
	}

```

**Comment by SimSync** [comment]
@Jimmi08 @Moc If i see it correctly, it should be 404 (Not found) as the requested resource (forum topic) is not found on the system (at least in the shown method `checkForumJump()` where it redirects if no e_QUERY or id to redirect to is given).

I opened this url `https://www.e107.sk/e107_plugins/forum/forum_viewtopic.php?f=post&id=412`and it redirected me to it's sef friendly pendant `https://www.e107.sk/forum/canonical-plugin/141/little-help-for-news-gsitemap-and-canonical-plugin-import-option/?p=1#post-412`.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
Maybe the default code should be changed to 307 as the 302 is sometimes not properly implemented in the browsers and can be used for URL-Highjacking (at least the german wikipedia page mentioned this).

@CaMer0n What do you think?

**Comment by Jimmi08** [comment]
@SimSync from the last time I have new 57 ulrs with 302 errors. 

Most of those ulrs exist and they are displayed by clicking on url.  Maybe they are from other place than from checkForumJump(). Maybe there is somewhere redirect to sef-url without 301.

![image](https://user-images.githubusercontent.com/5429548/44311140-46c43400-a3e2-11e8-97fe-72158f8cceca.png)

I found this for example: 
```
// NEW - force ssl
if(e107::getPref('ssl_enabled') && !deftrue('e_SSL_DISABLE') && empty($_E107['cli']))
{
	// NOTE: e_SSL_DISABLE check is here to help webmasters fix 'ssl_enabled'
	// if set by accident on site with no SSL support - just define it in e107_config.php
	if(strpos(e_REQUEST_URL, 'http://') === 0)
	{
		// e_REQUEST_URL and e_REQUEST_URI introduced
		$url = 'https://'.substr(e_REQUEST_URL, 7);
		e107::redirect($url);
		exit;
	}
}
```

**Comment by SimSync** [comment]
Just to be clear, a 302 status code is not an error. All 30x codes just tells the browser that he gets redirected. 302 tells the browser, hey the resource at this address has been moved, but the address is still valid and I take you to the right address.
Instead of questioning the status code, you should ask yourself where are those legacy urls from and can I do something about it.
As I said, per definition 302 is no error. It tells the browser exactly what happened and why.

**Comment by Jimmi08** [comment]
@SimSync 
I know difference between 302 and 301 redirect. 
Redirect from non ssl to ssl version with 302 is error/problem for SEO.  Not php error.
Redirect from legacy urls to sef-urls is problem too, because you don't want double content and 301 can help with it. 

Yes, I understand, why you use 302. 301 is permanent and maybe site will be set back. Or somebody switch back to legacy urls.   

But there is preference to redirect all urls to SSL version, if this is set ON, 301 should be used.

**Comment by SimSync** [comment]
> But there is preference to redirect all urls to SSL version, if this is set ON, 301 should be used.

Yes, that makes sense.

> Those links are from newforumposts_main plugin, what is part of core.

Are you sure? On my install it uses sef urls and also on your site..

> Redirect from legacy urls to sef-urls is problem too, because you don't want double content and 301 can help with it.

I looked a bit around and all resources i've found recommend to use a 301 as long as the requested resource is not really temporarily unavailable (e.g. a product is sold out and you get redirected with a 302 to the main category until the product is available again). Yes i know, the example is not 100% but shows the intention.
The main factor pro 301 is, that the ranking will move over to the new url and the old url will be removed from Google's index, while with a 302, the ranking will stay with the original url and will also be kept in Google's index.
@CaMer0n What do think?

**Comment by Jimmi08** [comment]
@SimSync 
I mistaken it with other file with similar name:

But this is still there:
https://github.com/e107inc/e107/blob/master/e107_plugins/newforumposts_main/newforumposts_main.php
```
	$THREAD = "<a href='".$path."forum_viewtopic.php?{$thread_id}.last'>$thread_name</a>";
	$FORUM = "<a href='".$path."forum_viewforum.php?{$forum_id}'>$forum_name</a>";
```

but I should have this fixed now (by using other menu).

**Comment by SimSync** [comment]
Yeah, i just investigated a bit on this plugin... and there is quite a lot of work to do to make it work correctly.
It's not only the sef urls, but also it's not php 7.x compatible and still a v1 plugin...

**Comment by Jimmi08** [comment]
My opinion:   It should be removed from core and put it separate directory.   This way it doesn't break site and if anybody wants, they can work on it.  There is already replacement by menu in forum plugin itself.

Problem with plugins in separate directory is that they are not able to download from e107.org and people don't know about them.
