### ISSUE TITLE
Sync from Github runs but then error message returned when browsing site

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#3361]
My production site is running a commit from Apr 6 2018  v2.1.8(git) commit 5216eda.  When I try to sync from latest Github commit 604cda1 using the developer mode tool in Admin I then get this error when trying to access my site in user or admin mode.  Clearing browser cache does not help.  DB is still present in phpmyadmin.  Reverting to last nights backup clears issue.

![error 2018-08-08 12-30-11](https://user-images.githubusercontent.com/15772899/43835973-ba8e27f4-9b0b-11e8-94c4-fcb067816a62.jpg)

**Comment by martyshep** [comment]
Cameron advised "Make a copy of “core_functions.php”, then upgrade your files with GIT and then replace core_functions.php with the copy you made."

This fixed it 💯

**Comment by CaMer0n** [comment]
@martyshep I still need to incorporate a fix into the current class, or your problem will return after upgrade. ;-)

**Comment by Moc** [comment]
@CaMer0n This is fixed by using the 2.1.9 bc patch right?

**Comment by CaMer0n** [comment]
@Moc Yes!
