### ISSUE TITLE
behaviour and plugin unistall

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3364]
It just happened that I did similar plugin as somebody else (Output looked totally different and I didn't go to deep)

Now I found it and I wanted to see what it does. 
That plugin uses behaviours or how it's called.

```
		e107::js('settings', array('cookie_consent' => $settings));
		e107::js('cookie_consent', 'js/cookie_consent.js', 'jquery', 4);
```

After uninstalling it still displayed cookies
![image](https://user-images.githubusercontent.com/5429548/43894955-0231d7cc-9bd4-11e8-82e4-a128ead32995.png)

After check, that behaviour part was still in code:
![image](https://user-images.githubusercontent.com/5429548/43895019-406b2c1e-9bd4-11e8-9a67-e3bce953dfc7.png)

I unistalled my version and it was still there.

Only way how to rid it was to use Rescan plugin directory option.

Is this problem of that plugin or in e107 or this is standard and rescan is needed?

Why after uninstalling any plugin can't be rescan use everytime?

**Comment by CaMer0n** [comment]
@Jimmi08 Normally it does rescan after every install and uninstall. And I assume you don't have js/css cache enabled, correct?

**Comment by Jimmi08** [comment]
Is there already long time (rescan after unistall)?

I tried it on new comp. No problem. Differencies are latest github version and php 7.
