### ISSUE TITLE
plugin_setup and deleting table

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3369]
I am trying to delete not used table via plugin_setup because upgrade

in method upgrade_pre()

`e107::getDB()->gen("DROP TABLE #canonical_request_urls", true);`

At first it emptied table instead drop and then it is not able to drop table at all.

Debug:
`Failed: SHOW CREATE TABLE `e107new_canonical_request_urls``

But table is correct. 
![image](https://user-images.githubusercontent.com/5429548/43955859-310dff84-9ca2-11e8-8e9e-e454046f0d81.png)

Thanks

**Comment by LaocheXe** [comment]
Try

$qry = "DROP TABLE '#canonical_request_urls'";
e107::getDB()->gen($qry, true);

**Comment by rica-carv** [comment]
I don't get it, what's the difference on using a variable : 
```
$qry = "DROP TABLE '#canonical_request_urls'";
e107::getDB()->gen($qry, true);
```
and using directly the text: 
`e107::getDB()->gen("DROP TABLE #canonical_request_urls", true);`

???

Isn't this last way much more user friendly and more understandable?

**Comment by Jimmi08** [comment]
That debug error is only on comp with php 7 (pdo used).  I tried it on php 5 and no error there. 
Table wasn't deleted because my stupidity - I left it in plugin sql file, so it was created again. Probably. 
Nevermind, I will try it again on Monday with php7. If this happens again, I will reopen this. 
Thanks
