### ISSUE TITLE
Failed to update v1.0.4 to 2.1.8 due to non-alphanumeric chars in user_extended table

### ISSUE THREAD

**Issue by JoniPeti** [e107inc/e107#3373]
Hi!

I would have a problem.
Failed database update.

I get the following error message:

> Sikertelen frissítés! [ALTER TABLE `e107_user_extended` ADD `user_extended_id` INT(10) UNSIGNED NOT NULL DEFAULT '0']
> Duplicate column name 'user_extended_id'
> Sikertelen frissítés! [ALTER TABLE `e107_user_extended` ADD PRIMARY `user_extended_id` (user_extended_id); ]
> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`user_extended_id` (user_extended_id)' at line 1
> Sikertelen frissítés! [ALTER TABLE `e107_user_extended` ADD `user_hidden_fields` TEXT ]
> Duplicate column name 'user_hidden_fields'
> Sikertelen frissítés! [ALTER TABLE `e107_faq_info` CHANGE `faq_info_icon` `faq_info_icon` VARCHAR(200) DEFAULT '' PRIMARY KEY (FAQ_INFO_ID)]
> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(FAQ_INFO_ID)' at line 2

I do not know what to do.

**Comment by CaMer0n** [comment]
hi @JoniPeti ! Sorry for the problems. Every installation is a little bit different, so occasionally something slips thru the upgrade routine and causes problems. 
If you can send me a private-message on Gitter: https://gitter.im/e107inc/e107  I'll be happy to work thru the issue with you and get it resolved.

**Comment by CaMer0n** [comment]
@tgtje @Jimmi08 If you could please run "Check Database Validity" on some of your sites to check for consistent behavior after this commit, I would much appreciate it.  Thank you.

**Comment by tgtje** [comment]
Sorry just read it, just after i upgraded live site with fresh github sync > outcome > no issues to be seen (site is quite fresh, and practilly being updated, so actually 'new' ) but as mentioned no issues to be seen.
Will test on local whith older stuff... (other than minor use issues with tinymce, but needs more investigation : use of bar alignment vs format bar use .. one works ; other not)...
