### ISSUE TITLE
server time question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3374]
Why is server time changing with user timezone?  

Shouldn't it be the same for all users. Or maybe just label is wrong and it should be label User time.

Before using user timezone:
![image](https://user-images.githubusercontent.com/5429548/43993222-762b2c16-9d8a-11e8-892b-f8ab5f8c3259.png)

After using user timezone:
![image](https://user-images.githubusercontent.com/5429548/43993247-b0ad17b4-9d8a-11e8-8e3c-34b00d2b70d0.png)

![image](https://user-images.githubusercontent.com/5429548/43993265-f0825b74-9d8a-11e8-8478-9277d1bcaf4f.png)

**Comment by tgtje** [comment]
No server time would be correct : 

Slovakia : Central European Summer Time (CEST) +0200 UTC        suppose 22.02 > UTC/GMT is 20:02
Melbourne: Australian Eastern Standard Time (AEST) +1000 UTC  suppose 22.02 > UTC/GMT is 06:02 next day (am)

**Comment by Jimmi08** [comment]
@tgtje   Those screnshots are from php Info page in admin area.  

This is related:  
https://github.com/e107inc/e107/issues/3313
https://github.com/e107inc/e107/issues/3331

In version 1  there were 3 different times:   server, site and user time.
![image](https://user-images.githubusercontent.com/5429548/44006608-721c783e-9e87-11e8-907a-56bf3c5bf336.png)

This was changed in version 2.  It sets default timezone according site timezone or user timezone, so all times are users time in fact.  

If I get you right -  that label is wrong.  It's site time, if you don't use user timezones, or it's usertime, if you use set user timezone.   Your time should be better choice. r

There were problem what is 'today' for user, but I hopefully fixed this. 

When you never heard about timezones (in detailed view), it's confusing if all sources are talking about server time one way (like you) and e107 says something different.   Now we use that time (in fact date())  and it looks correct for now.

**Comment by Moc** [comment]
Caused by this code in class2.php:

```php
// If user timezone is valid.
	if (varset($tzUser, false) && systemTimeZoneIsValid($tzUser))
	{
		// Sets the default timezone used by all date/time functions.
		date_default_timezone_set($tzUser);
		// Save timezone for later use.
		define('USERTIMEZONE', $tzUser);

		unset($tzUser);
	}
```

When a user sets their timezone settings, it calls the `date_default_timezone_set()` function, which then is the base for all date/time functions in e107. Meaning, all times will now be displayed based on the timezone of that user. 

The timestamp in the Server Info bar, also use the PHP default `date()` and is therefore changed as well.

To be honest, unless other areas are negatively impact, I'd like to leave it as it is. Perhaps we could change the naming/label 'Server time' to something more accurate but well...

**Comment by Jimmi08** [comment]
@Moc I don't want to change anything with dates / timezones. In meanwhile I figured it myself .  It works correctly.
This issue left open only because label in admin info part. It was really confusing.  Maybe "Your time"?
You can close this, if you want.

**Comment by Jimmi08** [comment]
It was solved long time ago.
