### ISSUE TITLE
PM notifications not visible on V2 (viewed & unviewed)

### ISSUE THREAD

**Issue by wrxxy** [e107inc/e107#3384]
Ok first 2 pics I have here are from V1 website which has now been changed over to new V2.
You'll see the notifications via the little icons denoting which PM's have been opened and others which are yet to viewed....
![image](https://user-images.githubusercontent.com/13065217/44232847-a7d2e880-a1e5-11e8-823e-15cb6c8e77d9.png)

![image](https://user-images.githubusercontent.com/13065217/44232818-8d007400-a1e5-11e8-886c-10bf33ad4a03.png)
Ok now here is the new V2 website showing that I have unread PM's

![image](https://user-images.githubusercontent.com/13065217/44232877-bcaf7c00-a1e5-11e8-9749-6b237d3ac4ca.png)
You'll notice on the 2 pics below outbox & inbox, that there's nothing there showing which PM's has been viewed and unviewed....
![image](https://user-images.githubusercontent.com/13065217/44232888-c20cc680-a1e5-11e8-885f-db8260b50889.png)
![image](https://user-images.githubusercontent.com/13065217/44232905-cc2ec500-a1e5-11e8-8054-37e5c09c6831.png)

**Comment by SimSync** [comment]
@wrxxy I'm sorry, but the resolution of the last 2 images is so bad, i can't recognize anything on that pictures.
Usually, unread messages are with a bold font.

**Comment by wrxxy** [comment]
![image](https://user-images.githubusercontent.com/13065217/44273031-ace57580-a281-11e8-8ad4-170f4ad2ba88.png)
Ok I can just see it in Inbox....
![image](https://user-images.githubusercontent.com/13065217/44273114-dbfbe700-a281-11e8-9993-c4d612394a47.png)
But outbox cant see it

**Comment by wrxxy** [comment]
I hope I helped
thx

On Thu, Aug 23, 2018 at 11:17 AM Cameron <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #3384<https://github.com/e107inc/e107/issues/3384> via 0329b5f<https://github.com/e107inc/e107/commit/0329b5f3b98ab11bb84eac19af077d68331547e5>.

**Comment by wrxxy** [comment]
Hi again I just did an update to my website to 2.2.0 git but haven't noticed the change in the inbox /outbox pm visibilty... In other words no change... not sure what happened.

**Comment by wrxxy** [comment]
Ok just to update on this issue I have noticed the update finally, but I feel that this is insufficient and could be more noticeable I guess, but my be ok to you guys..... 

![image](https://user-images.githubusercontent.com/13065217/44954637-3a62cf80-aee8-11e8-8875-fea4a28c156d.png)

**Comment by rica-carv** [comment]
You can completely rewrite those PM output shortcodes at theme level to suit your needs, even include icons, etc.
Furthermore, you can use css to add some more efects to it (change color, font style, size, etc)....

**Comment by Moc** [comment]
This is now something you'll need to change in the theme as rica-carv pointed out. Closing the issue.
