### ISSUE TITLE
 How to save array in pref ?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3393]
This is value from $_POST, I need to save in prefs

```
    [my pref] => Array
        (
            [0] => 30
            [1] => 60
            [2] => 90
        )
```

This value comes from custom method for this preference. 

How to do it  with new admin_ui?  

I don't know if this is related with new admin_ui or e107::getPref();

Thanks

**Comment by rica-carv** [comment]
Maybe merge this array with the getprefs array, and use a saveprefs?

**Comment by Moc** [comment]
I think you can use the serialize method for this but I'm not sure where to place this is in the admin UI

**Comment by CaMer0n** [comment]
@Jimmi08 Use type='str', it should automatically save the array.

**Comment by Jimmi08** [comment]
@CaMer0n 
you probably thought this: 
`data='array' `

It looked like solution:

$_POST is correct
but pref is not saved.

**Comment by Jimmi08** [comment]
This is not feature request.  Admin_UI is not for all cases.  I solved it other way.

**Comment by CaMer0n** [comment]
@Jimmi08 See `e107_admin/image.php` `protected $prefs` `resize_dimensions`
resize_dimensions is an array in the form.

**Comment by Jimmi08** [comment]
Thanks. It's done by method and setting:
`		'resize_dimensions'				=> array('title'=> IMALAN_184, 'type'=>'method', 'data'=>'str'),`
so no data...

**Comment by CaMer0n** [comment]
@Jimmi08 Sorry, maybe I misunderstood you. I thought you wanted to save posted array data in a pref. 
`media_form_ui:resize_dimensions` does this by submitting an array to `$_POST['resize_dimensions']` which is saved in its pref.
