### ISSUE TITLE
bbcode template on forum - removed custom bbcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3394]
Latest changes in forum template vs bbcodes - not all, just this one:

> fixes #3317 moved the forum template from core to plugin

https://github.com/e107inc/e107/pull/3365/commits/c1bec2b6d75445354028a858f98f0c51f5c69a41

caused that e_bb.php doesn't work and custom bbcodes are not displayed.

The reason is using $tpl = e107::getTemplate($template, 'bbcode', $template);
instead $BBCODE_TEMPLATE_FORUM;

**Comment by SimSync** [comment]
@Jimmi08 can you send me such an e_bb.php please or better the whole plugin that implements the e_bb.php?

**Comment by Jimmi08** [comment]
@SimSync 
Forum is set to use bbcodes (system editor is Tinymce, forum plugin use bbcodes)

With version 2.1.9 it looks like this:
![image](https://user-images.githubusercontent.com/5429548/44626320-6398c400-a91a-11e8-90c3-6f0770307619.png)

Before it looks like this:
 
![image](https://user-images.githubusercontent.com/5429548/44626447-d7d46700-a91c-11e8-877e-499889b16ab7.png)


That last one is from this plugin: 
https://www.e107.sk/download/18/spoiler-plugin

It's just fixed some old plugin. 
bbcode is defined this way (one plugin = one bbcode):

```
      <?php
      $bb['name']        = 'sp';
      $bb['onclick_var'] = "[sp][/sp]";
      $bb['icon']        = e_PLUGIN_ABS."spoiler/images/spoiler.png";
      $bb['helptext']        = "Spoiler: [sp=subject]Text to be hidden[/sp]";
      $BBCODE_TEMPLATE .= "{BB=sp}";
      $BBCODE_TEMPLATE_SUBMITNEWS .= "{BB=sp}";
      $BBCODE_TEMPLATE_NEWSPOST .= "{BB=sp}";
      $BBCODE_TEMPLATE_ADMIN .= "{BB=sp}";
      $BBCODE_TEMPLATE_CPAGE .= "{BB=sp}";
      $eplug_bb[] = $bb;
      ?>
```

but then you can have more bbcodes in one plugin.

I tried to add:
```
      $BBCODE_TEMPLATE_FORUM .= "{BB=sp}";
```

It's related to using getTemplate().
