### ISSUE TITLE
Question: SiteLink Plugin " title=""> 

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3395]
Doing some testing and tried using my Voice eXe plugin in Site Links, using {VOICE_EXE} in the Url place - hit save, (no name) - notice that it displays in the main nav bar - just showing " title=""> (Also, it stretches the navbar so it can fit)

Now if I remove the Url - and put #  then use the Function (Voice) - I get this: {VOICE_EXE}  (No drop down menu).

**Comment by SimSync** [comment]
@LaocheXe What is the return value of the shortcode {VOICE_EXE}?
Could you post some screenshots, how the "create sitelink" page looks before and after saving?

You could also have a loook into the vstore plugin:
In `e_header.php` https://github.com/e107inc/vstore/blob/master/e_header.php the menu item html is defined.
And in  è_sitelink.php` https://github.com/e107inc/vstore/blob/master/e_sitelink.php the submenu get's defined.

**Comment by LaocheXe** [comment]
https://github.com/LaocheXe/Voice-eXeSystem

![voice1](https://user-images.githubusercontent.com/5818022/44868938-e50d9080-ac51-11e8-8040-b216c4af6d44.JPG)

![voice2](https://user-images.githubusercontent.com/5818022/44868942-e76fea80-ac51-11e8-8b05-8e53adf6b2e8.JPG)

![voice3](https://user-images.githubusercontent.com/5818022/44868946-e939ae00-ac51-11e8-9914-cf7e2916d43a.JPG)

Above images shows the Shortcode working via theme_shortcodes.php
Below shows the Site Link Plugin Shortcode

![capture1](https://user-images.githubusercontent.com/5818022/44868994-0c645d80-ac52-11e8-8f17-020345c3ce45.JPG)

![capture2](https://user-images.githubusercontent.com/5818022/44868996-0e2e2100-ac52-11e8-846a-a62c1443d75a.JPG)

![capture3](https://user-images.githubusercontent.com/5818022/44869000-125a3e80-ac52-11e8-818c-e7a3f54b38b2.JPG)

Below shows what I have used/tried in Site Links in Admin Area

![capture4](https://user-images.githubusercontent.com/5818022/44869029-2140f100-ac52-11e8-9920-fdebad241352.JPG)

**Comment by CaMer0n** [comment]
@LaocheXe The 'title' displaying indicated broken HTML markup earlier on. 
Whatever is in VOICE_EXE, please add the following right before your shortcode returns data. 
Replace `$text` with whatever you use in the shortcode. 

    e107::getDebug()->log($text);

then, enable 'basic' mode in the debugger to view the output in the footer.

**Comment by LaocheXe** [comment]
First thing First. I did what you said, but I did not try the SiteLink Shortcode just yet.

![capture1](https://user-images.githubusercontent.com/5818022/45175365-e6e7ce80-b1d2-11e8-9c41-f87625c39a61.png)

With it On

![capture2](https://user-images.githubusercontent.com/5818022/45175375-ee0edc80-b1d2-11e8-9d5b-321dbd7b4db7.png)

**Comment by CaMer0n** [comment]
@LaocheXe I suggest to use e_sitelink only and not place a shortcode in the URL field.

**Comment by LaocheXe** [comment]
@CaMer0n I already have one - and tried it, same results - https://gist.github.com/LaocheXe/6a6b9314673f5e064cca895adbe48992   <-- whats in my e_sitelink.php

**Comment by LaocheXe** [comment]
@CaMer0n Also, since I should use {SHORTCODE} in the url - what do I put there? Because URL is required.

**Comment by LaocheXe** [comment]
@CaMer0n that works some what.

Before:
![before](https://user-images.githubusercontent.com/5818022/45271059-6e4e6f80-b469-11e8-916d-5724fa42ad5d.png)

Admin:
![admin](https://user-images.githubusercontent.com/5818022/45271069-87efb700-b469-11e8-9bf5-8e30283d9dc1.png)

After:
![after](https://user-images.githubusercontent.com/5818022/45271072-8c1bd480-b469-11e8-8152-f667354d6a72.png)

Last Picture you see the 'Voice Plugin' name as a dropdown menu, but nothing is there - then you see 'Comms' dropdown (yes it works) - but breaks the navbar.

**Comment by CaMer0n** [comment]
@LaocheXe I'm sorry, I can only guess now without seeing the source code.

**Comment by LaocheXe** [comment]
@CaMer0n https://github.com/LaocheXe/Voice-eXeSystem/tree/master/voice

https://github.com/LaocheXe/Voice-eXeSystem/blob/master/voice/e_shortcode.php#L384

https://github.com/LaocheXe/Voice-eXeSystem/blob/master/voice/e_sitelink.php#L85

**Comment by CaMer0n** [comment]
@LaocheXe Okay, so this code is wrong: 

```
<ul class="nav navbar-nav navbar-right">
			<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">'.$VoiPlug_Name.' <b class="caret"></b></a>
			<ul class="dropdown-menu">
			<li>
			'.$voice_exe.'
			<p></p>
			</li>
			<li class="divider"></li>
			<li>
			<a href="'.e_PLUGIN.'voice/voice.php">'.LAN_VOICE_VIEWERS.'</a>
			</li>
			</ul>
```

The sitelink function places code INSIDE the dropdown-menu. What you're providing is the code in the main-menu and the drop-down menu code. I suggest you replace this with a simple "hello world" and make your changes gradually and test regularly, so you'll know what in your code causes a break. 
Please see e107_plugins/_blank/e_sitelink.php for working examples.

**Comment by LaocheXe** [comment]
@CaMer0n everything in the code looks fine but the <p> - which I should change that. only thing I can think of is maybe the <ul>

**Comment by CaMer0n** [comment]
You need to remove this: 

```
<ul class="nav navbar-nav navbar-right">
			<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">'.$VoiPlug_Name.' <b class="caret"></b></a>
			<ul class="dropdown-menu">
```

`</ul>`

And replace your `<li>` items with `<div> `

See if that helps.

**Comment by LaocheXe** [comment]
One step closer, just need to re-do the css for it, and kept the old style as well - thanks you your help/guidance.
