### ISSUE TITLE
Updated the site from 2.1.8 to 2.1.9 and now this error

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3397]
Updated the site from 2.1.8 to 2.1.9 and now this error:
http s: //***.ru/e107_admin/cache.php

CRITICAL ERROR:
Line 522 /home/kuznecru/public_html/class2.php
[3]: Core settings saved - backup made active.

and

CRITICAL ERROR:
Line 524 /home/kuznecru/public_html/class2.php
[4]: No core backup found. Check that your database has valid content. 

Database checked. what backup is he looking for?
The problem is solved if you replace the folder (e107_handlers) from 2.1.8

https://***.ru/e107_admin/image.php
Fatal error: Can't use method return value in write context in /home/admin/web/***.ru/public_html/e107_admin/image.php on line 2000

**Comment by CaMer0n** [comment]
Please try the following patch. 

[e107_2.1.9_bc_patch.zip](https://github.com/e107inc/e107/files/2315138/e107_2.1.9_bc_patch.zip)

**Comment by Evgura** [comment]
Yes, Yes, Yes the patch works.
CaMer0n - thank you.

**Comment by Evgura** [comment]
Another mistake.
https://***.ru/e107_admin/users.php
Parse error: syntax error, unexpected '!' in /home/admin/web/***.ru/public_html/e107_admin/users.php on line 2838

**Comment by Moc** [comment]
@Evgura Which PHP version are you using?
