### ISSUE TITLE
Issue: Update core database structure

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3406]
On my Defiantz site, I haven't been keeping it up to date. Updated via github today and got Update core database structure update button, I push it and get this Warning Message:

Update Unsuccessful [ALTER TABLE `dg_submitnews` CHANGE `submitnews_id` `submitnews_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT]
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key
Update Unsuccessful [ALTER TABLE `dg_submitnews` ADD PRIMARY `submitnews_id` (submitnews_id); ]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`submitnews_id` (submitnews_id)' at line 1
Update Unsuccessful [ALTER TABLE `dg_submitnews` ADD `submitnews_media` TEXT ]
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'submitnews_media'

**Comment by Moc** [comment]
@SimSync any idea on this one?

**Comment by SimSync** [comment]
Sure, but ai'm a bit handycapped at the moment.

**Comment by CaMer0n** [comment]
@LaocheXe Please enable debug mode, then go to `/e107_admin/db.php?mode=verify_sql` then paste a screenshot here of the debug information relating to `submitnews.`

**Comment by LaocheXe** [comment]
![annotation2](https://user-images.githubusercontent.com/5818022/45260020-dab16c00-b3a0-11e8-9c34-4f01ed4a8efc.png)

![annotation1](https://user-images.githubusercontent.com/5818022/45260021-dc7b2f80-b3a0-11e8-8341-3aac939a3940.png)

**Comment by CaMer0n** [comment]
@LaocheXe Thanks, will look into it.
