### ISSUE TITLE
Error in user php

### ISSUE THREAD

**Issue by iscf2019** [e107inc/e107#3407]
after my users done their registration, I can't activate them and my e 107 show this error
Parse error: syntax error, unexpected '!' in public_html/e107_admin/users.php on line 2838
please help me to correct this issue
this problem made after I upgrade my e107 to 2.1.9 version

**Comment by Evgura** [comment]
@iscf2019  https://github.com/e107inc/e107/issues/3397

**Comment by iscf2019** [comment]
thank you
