### ISSUE TITLE
Issue: $ns->tablerender()

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3409]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function e107table::tablerender(), 1 passed in /usr/www/taskforce13tsw/501st/e107/mods.php on line 213 and at least 2 expected in /usr/www/taskforce13tsw/501st/e107/class2.php:1072 Stack trace: #0 /usr/www/taskforce13tsw/501st/e107/mods.php(213): e107table->tablerender('\r\n <body>\r\n ...') #1 {main} thrown in /usr/www/taskforce13tsw/501st/e107/class2.php on line 1072

Code use:
$ns -> tablerender($text);

https://gist.github.com/LaocheXe/4385e8b656a9eac6c5b8be5c6b4d353f

Issue is, this worked before 2.1.9

**Comment by Moc** [comment]
Thanks, which PHP version are you using?

**Comment by LaocheXe** [comment]
PHP Version 7.1.18

**Comment by tgtje** [comment]
Just commenting, meant read somewhere you als have to add  $ns = e107::getRender(); in file..; Sorry if i am mistaken

**Comment by LaocheXe** [comment]
It's odd because it worked two months ago.....
