### ISSUE TITLE
RSS plugin -  weird lan values

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3410]
I noticed this:

`define("RSS_LAN_ERROR_1", "This is not a valid rss feed.[br][br][Return to rss feed list]");`

(in my case [br] was changed to url, but it can be done not by core, it's test version)

And while you see this, next string looks weird too -  

>  ï»¿﻿ 

`define("RSS_LAN_ERROR_2", "Your e107_config.php file or your language files contain spaces or ï»¿﻿ characters before the &lt;? characters. You should remove this with a non-utf8 text-editor if you wish to have a valid RSS feed.");`

thanks
Edit. I just found why it was changed to urls in rss.php:
```
		$repl  = array("<a href='".e_REQUEST_SELF."'>", "</a>");
		$message = str_replace(array("[","]"), $repl, RSS_LAN_ERROR_1);
```

**Comment by tgtje** [comment]
At the strange code :  @Jimmi08 :  it is the output (eg start) iff a file is encoded with BOM. (likely file saved as unicode and thus interferes with utf8 not expecting this ).

**Comment by Jimmi08** [comment]
@tgtje if this is correct, it's ok, it just looked weird for me.  Those br tags are real issue.

**Comment by CaMer0n** [comment]
@Jimmi08 It was poorly done. "Return to rss feed list" should be a separate LAN. @yesszus 
 `[br]` should be avoided in LANs and especially in this case where str_replace is being used on` [` and `] `
