### ISSUE TITLE
Feature request - after plugin scan update core pref

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3411]
After running scan plugin directory core pref stays the same:
`plug_installed`

So there is still warning:
![image](https://user-images.githubusercontent.com/5429548/44953764-137cad00-ae98-11e8-9675-cbb652d6f3ea.png)

Only way how to fix it is manually delete it from database

It would be great to have possibility to update this pref manually or after rescan plugin directories

**Comment by Jimmi08** [comment]
@wrxxy

**Comment by Moc** [comment]
Related: https://github.com/e107inc/e107/issues/3349

**Comment by CaMer0n** [comment]
@Moc Maybe this one can be closed too?

**Comment by Moc** [comment]
@Jimmi08 Still an issue?
