### ISSUE TITLE
problem with $E107_CONFIG['site_path']

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3412]
After update (changing source database) everything worked except images.
This should be fix:

`$E107_CONFIG['site_path'] = 'oldhashfolder';`

I used it in e107_config.php  (with old media folder name). 
I checked it in prefs and I cleared cache.
Path is ok, to old hash folder:
![image](https://user-images.githubusercontent.com/5429548/44954332-d7017f00-aea0-11e8-9bda-c5b871f78113.png)

I have problem with featurebox:
There are still thumbnails: (in frontend too)
![image](https://user-images.githubusercontent.com/5429548/44954358-0c0dd180-aea1-11e8-8fec-be00e9af8f10.png)

Only way how to fix it was upload image folder to not used hash media folder.
![image](https://user-images.githubusercontent.com/5429548/44954366-2cd62700-aea1-11e8-8f9d-7cfe8b68aa78.png)

And images are back:
![image](https://user-images.githubusercontent.com/5429548/44954374-411a2400-aea1-11e8-93cc-7856f22490a2.png)

this is path to image on frontend:
`<img id="featurebox-image-3" src="/thumb.php?src=e_MEDIA_IMAGE%2F2018-07%2FOldies.png&amp;aw=2205&amp;ah=510" alt="Oldies" class="featurebox img-responsive img-fluid">`

**Comment by CaMer0n** [comment]
@Jimmi08 Please enable debug mode with "Paths + Variables". 
Please paste here any values starting with e_MEDIA. Perhaps e_MEDIA_IMAGE is incorrect?

**Comment by Jimmi08** [comment]
@CaMer0n no, everywhere is correct old hash. I checked Frontend and Admin too.

**Comment by Jimmi08** [comment]
Just note after new moving.
if you add this to config before moving, I didn't notice any problems.
But if you change it later, there are some problems

**Comment by CaMer0n** [comment]
@Jimmi08 I believe this was recently corrected. If you have the opportunity, please test again, otherwise, I suggest we close this and you may re-open later if necessary.

**Comment by Moc** [comment]
@Jimmi08 Please re-open if needed
