### ISSUE TITLE
problem with login page template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3420]
I am creating new issue to have this in separate thread 

Login form is not displayed if login template used this:  `{LOGO=login}`

Core template:
```
// Starter for v2. - Bootstrap 
$LOGIN_TEMPLATE['page']['header'] = "
	<div id='login-template'>
		<div class='center'>
			{LOGO=login}
		</div>";
```

Without it:
 
![image](https://user-images.githubusercontent.com/5429548/45141316-cfe6b380-b1b5-11e8-9364-23664aac4590.png)

With it:
 
![image](https://user-images.githubusercontent.com/5429548/45141476-3bc91c00-b1b6-11e8-8607-bd604dd3af5d.png)

No errors in console
Tested with php 5 and 7
Changing to {SITELOGO}

**Comment by Moc** [comment]
Is there somewhere (by the browser?) an error such as "Clickable elements too close together?"?

**Comment by Jimmi08** [comment]
I think he wrote about google mobile usage test.

**Comment by BlastFM** [comment]
Be aware that this issue will also cause you problems with Google search console, it will fail mobile compatibility checks with: ‘Clickable elements too close together’ and so it needs to be fixed.

**Comment by CaMer0n** [comment]
@Jimmi08 Did the commit help?

**Comment by Jimmi08** [comment]
Yes, thanks.
