### ISSUE TITLE
forum - split functionality is missing

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3421]
just note

I can't find split functionality. Is somewhere in setting or it is not supported for now ?

**Comment by Evgura** [comment]
@Jimmi08 There is such function.
You need to enable the admin developer mode and then the forum will be split mode.

**Comment by Jimmi08** [comment]
Thank you. I was sure I saw it somewhere.

I got this result, but forum is splited.

![image](https://user-images.githubusercontent.com/5429548/45158226-a47abd80-b1e3-11e8-9201-4a70402abaec.png)

**Comment by rica-carv** [comment]
So forum can only be split in developer mode? In a live site???

**Comment by Moc** [comment]
I think it's still to be tested and further finished before it can be used without developer mode. On the roadmap for 2.2.

**Comment by Jimmi08** [comment]
@rica-carv it's correct. It's not fully implemented so it's on your own risk. With debugger in browser it's quick a short time lived. I needed this first time and this was big help.

**Comment by Jimmi08** [comment]
This can be closed
My suggestion would be to change e_DEVELOPER to main admin check, but the split functionality is working correctly.
I only noticed some warning/error like above if I use preview by mistake before confirmation (something about recounting), but a new topic is created normally.

If something, a new issue should be created. This one is too old and too general.
