### ISSUE TITLE
question - I can't get chapter url work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3423]
I am working on page listing without shortcodes (like for rss )

Data:
```
Array
(
    [page_id] => 10
    [page_title] => News Shortcodes (core/batch)
    [page_author] => 1
    [page_sef] => news-shortcodes-core-batch
    [page_chapter] => 6
    [chapter_id] => 6
    [chapter_sef] => news-shortcodes
    [chapter_name] => News shortcodes
    [book_id] => 5
    [book_sef] => e107-shortcodes
)
```
chapter url (similar like in sc_chapter_url())
`$rss[$i]['category_link']   = e107::getUrl()->create('page/chapter/index', $value, array('full'=>1, 'allow' => 'allow=chapter_id,chapter_sef,book_sef')); `

result is:
` [category_link] => http://localhost/e107sk2.1.6/chapter?`

What am I missing?
Thanks

**Comment by CaMer0n** [comment]
`'allow' => 'allow=chapter_id` looks strange to me. ;-)

**Comment by Jimmi08** [comment]
Thanks, I was sure that I am missing something trivial.
