### ISSUE TITLE
Problems with pages

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3426]
Hi Guys!

I have three problems with pages. (version git)

First:

If I upload a new image on pages, the system does not add a category (custom page category) so the image does not appear in the selection.

![01](https://user-images.githubusercontent.com/12445784/45263385-ca44d400-b428-11e8-95ec-1d1e611fd9c3.JPG)

Second:

In TinyMCE editor, the youtube videos doesn't appear. But just in the editor...

![02](https://user-images.githubusercontent.com/12445784/45263395-0710cb00-b429-11e8-9578-e5fcf6cad5e8.JPG)

![03](https://user-images.githubusercontent.com/12445784/45263396-0bd57f00-b429-11e8-840e-082290d14b94.JPG)

Third:

If I creating a new page and add custom fields, the system doesn't save the fields in first time, just when editing an existing page.

**Comment by CaMer0n** [comment]
Thank you @KiraTheUltimate !! Please give it a try now.  (Issue 1 and 2)

**Comment by KiraTheUltimate** [comment]
@CaMer0n Thank you very much! The first two issue is solved then.

**Comment by CaMer0n** [comment]
@KiraTheUltimate It should be fixed now. Please re-open if it is not.
