### ISSUE TITLE
question -  cachevars()

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3430]
Hi,
I am using code form old plugin.  It uses cachevars this way:
```
cachevars('contactform_post', $p_vars);
cachevars('contactinfo_data', $contactinfo);
cachevars('contactform_data', $field);
```

This is deprecated.  But with new setVars I can replace only last one.
`$contactus_shortcodes->setVars($field);`
You can't use this more than one time (in foreach after pulling data from database)

I tried this too in foreach:
```
     $contactus_shortcodes->setVars($field);
     $contactus_shortcodes->setVars($contactinfo);
```
Only last one is applied.

I solved it by using:
```
e107::setRegistry('core/cachedvars/contactform_post', $p_vars);
e107::setRegistry('core/cachedvars/contactinfo_data', $contactinfo);
e107::setRegistry('core/cachedvars/contactform_data', $field);
```
My question is what is advantange of using setVars() and then $this->var?  Or better: is there problem with using way from above?

Thanks

**Comment by CaMer0n** [comment]
setVars is used within the shortcode class, registry doesn't require shortcodes to be used and can be shared across plugins.

**Comment by Jimmi08** [comment]
Thanks. But those 3 var sets are used in one shortcode class.  Not in other plugins.

**Comment by CaMer0n** [comment]
I think what you're looking for is..  `setScVar()` and `getScVar()`

**Comment by Jimmi08** [comment]
Yes, it likes like correct. Thank you.
