### ISSUE TITLE
theme info is ignoring xml atributtes price

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3432]
![image](https://user-images.githubusercontent.com/5429548/45538759-38621000-b808-11e8-8440-9a284aaba799.png)

$theme['price'] is not filled in function renderThemeInfo($theme)();

those icons are not displayed (wrong html markup)
`<i class='icon-shopping-cart icon-white'></i>`

**Comment by CaMer0n** [comment]
@Jimmi08 @Moc The price displays for me. However in PHP7 the modal popup is blank. Same for you?

**Comment by Jimmi08** [comment]
@CaMer0n new install, php 7.0, I still don't see the price

![image](https://user-images.githubusercontent.com/5429548/49854461-80cea100-fdea-11e8-87e4-dc2e2ccded7c.png)
