### ISSUE TITLE
problem with smtp gmail settings

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3435]
I am creating this issue in favor for wrxxy

He says he uses correct password and email. He tried 587 port with TLS too.

![image](https://user-images.githubusercontent.com/5429548/45613103-760fa480-ba65-11e8-8290-5e64fecc12ff.png)

If I try to send test email from Prefs:
![image](https://user-images.githubusercontent.com/5429548/45613145-a8210680-ba65-11e8-95d0-e481051e1d16.png)
But email never comes.

If it try SMTP test:  **Why is there port 25?**

![image](https://user-images.githubusercontent.com/5429548/45613316-34cbc480-ba66-11e8-8db0-95fde96a83a2.png)

If I try to send test email from Mailout Prefs:

 
![image](https://user-images.githubusercontent.com/5429548/45613340-4614d100-ba66-11e8-86d1-b7d76e7919a0.png)

**Comment by Jimmi08** [comment]
It's updated site. Prefs look like this:

![image](https://user-images.githubusercontent.com/5429548/45614838-14523900-ba6b-11e8-8499-43a2e1c318b3.png)

**Comment by CaMer0n** [comment]
@Jimmi08 You can play around with the port number on line 998 of mailout.php . I would first check what the pref value is for it.

**Comment by CaMer0n** [comment]
Some providers prevent PHP using SMTP.  It's an option in WHM/cPanel to block it, if I remember well.

**Comment by simplythomasjay** [comment]
To send email with gmail and smtp you have to activate something like "enable legacy email sending" in gmail options.
Per default it is deactiviated.
The standard way to connect with gmail is oauth.

Here is a very useful list - it is in german but I think the main content is readable.
https://www.patrick-canterino.de/pop3-smtp/   

Port 465 and port 587 both are fine.

**Comment by Jimmi08** [comment]
He has GoDaddy and they probably block it (I don't fully understand everything)

**Comment by Moc** [comment]
GoDaddy is known to have odd and very limited server configurations. I recommend finding a proper hosting provider. Pay a few more dollars/euros whatever and it will save you a lot of headaches.

**Comment by Jimmi08** [comment]
@wrxxy  @Moc 
I was able to set correct SMTP settings to GoDaddy SMTP server.    

**GoDaddy allow mail flow only through their own SMTP servers: secureserver.net**

before there was error:  Error info: SMTP connect() failed. 
Now there is success: Send to Test address  *** Mail-ID= - Success

_But emails never come._ 

The same for php mail()  settings.

DEBUG looks correct.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 So if I understand well, we can close this issue?

**Comment by Jimmi08** [comment]
Sorry, I didn't notice I was author. Of course.
