### ISSUE TITLE
Duplicated LAN's...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#3438]
[LAN_ERROR_3](https://github.com/e107inc/e107/search?q=LAN_ERROR_3&unscoped_q=LAN_ERROR_3), [LAN_ERROR_6](https://github.com/e107inc/e107/search?q=LAN_ERROR_6&unscoped_q=LAN_ERROR_6), [LAN_ERROR_9](https://github.com/e107inc/e107/search?q=LAN_ERROR_9&unscoped_q=LAN_ERROR_9), [LAN_ERROR_12 ](https://github.com/e107inc/e107/search?q=LAN_ERROR_12&unscoped_q=LAN_ERROR_12)& [LAN_ERROR_15 ](https://github.com/e107inc/e107/search?q=LAN_ERROR_15&unscoped_q=LAN_ERROR_15)are exactly equal, letter by letter.
Why such duplicates?

**Comment by Moc** [comment]
Not sure why, but definitely something that needs to be corrected.

**Comment by rica-carv** [comment]
@Moc And how? Replace all duplicated LAN with LAN_ERROR_3?

**Comment by rica-carv** [comment]
@tgtje LAN_ERROR_3 is used in a message, right? But it can also be used in templates or anything else, right?
So why not clean all this up?
And i just stumble on these ones, it might be some more lying around....
