### ISSUE TITLE
Issue: <siteLinks> no longer generates

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3439]
In Plugin.xml the <siteLinks> no longer generates Site Links.

```
<siteLinks>
        <link url="#" function='Voice' icon="" description="Voice Plugin" perm="everyone" >LAN_VOIPLUG_NAME</link>
    </siteLinks>

```
Tried other plugins as well (multilang) and no link was created for either plugin. However, forum plugin works (generates the forum link).

**Comment by LaocheXe** [comment]
I tried the Forum plugin, it works, checked the code out on it, and made the changes in mine (removed icon, and description, and added lan - but still not working, even turned on the debug tool and nothing came up. 

added sef='index' and it's created - issue is, I don't have e_URL.php (never really needed it)


e_url.php in e107_plugins/gallery is missing the key: gallery. Or, you may need to scan your plugin directories to register e_url.php
e_url.php in e107_plugins/voice is missing the key: index. Or, you may need to scan your plugin directories to register e_url.php

Site Links > Edit Voice

* URL | Auto-generated
-- | --
SEF URL | Not available

Cant edit them two, and function does not work.

**Comment by CaMer0n** [comment]
@LaocheXe Please try again

**Comment by LaocheXe** [comment]
@CaMer0n okay it generates the site link.

```
<siteLinks>
        <link url="#" function='Voice' perm="everyone" lan='LAN_VOIPLUG_NAME'>Voice</link>
  </siteLinks>
```

But still won't put the function in.
![annotation](https://user-images.githubusercontent.com/5818022/45703165-226e8b00-bb39-11e8-99e6-1584edc9bf22.png)

![annotation1](https://user-images.githubusercontent.com/5818022/45703171-24384e80-bb39-11e8-8a2c-2169018cf77a.png)

Should have Voice selected, I even tried to lower case the v to see if that worked, no go

**Comment by CaMer0n** [comment]
@LaocheXe This is normal when a function can't be found. Your function is called `voiceEXE`

**Comment by LaocheXe** [comment]
@CaMer0n but in the list it shows up as voice - should I change it in the xml to voiceEXE?

![annotation3](https://user-images.githubusercontent.com/5818022/45720539-44343600-bb6a-11e8-92b4-e29c7dcc5bff.png)


It's listed - but doesn't set the link function to voice when a user installed the plugin.

**Comment by LaocheXe** [comment]
So using voiceEXE work, thanks again!

**Comment by CaMer0n** [comment]
@LaocheXe Great! Yes, it has to match the **actual** function name, not the label ("Voice") associated with it.
