### ISSUE TITLE
problem with e_PAGE.php and pages

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3440]
I have installation from time just after 2.1.9. 
Everything works.  With SEF-URL e_PAGE is defined.
![image](https://user-images.githubusercontent.com/5429548/45650680-590fbb80-bacf-11e8-9c70-d97d77477ff2.png)

But then I have new site, where there is index.php as e_PAGE.php
![image](https://user-images.githubusercontent.com/5429548/45650727-89575a00-bacf-11e8-9113-1a22b430d999.png)

URL settings are the same. 
New site is part of multisite. 
When I switch to legacy ulrs, e_PAGE is correct on this site.

**Comment by Jimmi08** [comment]
@CaMer0n 
I was able to track this. It's only on multisite for now.

Reason is this:

```
			if(deftrue('e_SELF_OVERRIDE')) // see multisite plugin.
			{
				define('e_PAGE', basename($_SERVER['SCRIPT_FILENAME']));
			}
```

if I comment that e_PAGE defination, it's correct then.
$_SERVER['SCRIPT_FILENAME' is :
`/e107.sk/sub/v2demo/default/index.php`

I supposed it's because I have set Associate Root namespace  as PAGE, so I set it off, but for pages there is still index.php.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. I don't recall why this was added, but most likely to prevent something from breaking.
