### ISSUE TITLE
Issue: Maybe? Sync with git warining after

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3442]
Syncing up with github, and got two messages after it success and I go back to the main admin area:

Warning: Declaration of e_tree_model::load($force = false) should be compatible with e_front_model::load($id = NULL, $force = false) in /usr/www/defiantz/e107_handlers/model_class.php on line 3774

Warning: Declaration of e_front_tree_model::update($field, $value, $ids, $syncvalue = NULL, $sanitize = true, $session_messages = false) should be compatible with e_tree_model::update($from_post = true, $force = false, $session_messages = false) in /usr/www/defiantz/e107_handlers/model_class.php on line 3908

**Comment by CaMer0n** [comment]
Just because you have debug enabled. 
See #2146
