### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by humhubuser** [e107inc/e107#3452]
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-kibi' at line 1

php 7.2.10
mysql 5.6.37-82.2
e107 2.1.9

steps 1-7 of the installing routine are OK. Step 8 failed

**Comment by humhubuser** [comment]
Thank you. That solved the problem!

**Comment by Moc** [comment]
You're welcome 👍
