### ISSUE TITLE
Forums with  Admins and Mods class can not be seen anymore

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3457]
When you use classes in the forum plugin and you've got the right class it's still not showing, used 
Admins and Mods to hide it from the public but it's also been hidden from me :-)

(Tgtje see e107.nl forum..)

Alex

**Comment by Jimmi08** [comment]
try to check user hierarchy.  I needed to move Admin and Mods under Main Admin. Or something like that.

**Comment by Moc** [comment]
@Alex-e107nl Is this still an issue with the latest files?

**Comment by Alex-e107nl** [comment]
Hi Moc, just updated with git from today on e107.nl it is solved!! 
THX You are the best (You-all!!)

Alex

**Comment by Moc** [comment]
Thanks for the feedback!
