### ISSUE TITLE
inline editing in sitelinks doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3459]
I tried to change template:
![image](https://user-images.githubusercontent.com/5429548/46038477-77973780-c10b-11e8-98d2-62acf4b90cfd.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please test inline editing in other areas? It could be related to the last pull-request involving inline editing.

**Comment by CaMer0n** [comment]
@Jimmi08 btw. If you enable debug there's an inline editor log generated in the e107_system folder.

**Comment by Jimmi08** [comment]
[uiAjaxResponseInline.log](https://github.com/e107inc/e107/files/2416849/uiAjaxResponseInline.log)
Neither news.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. In the `<a>` tag of the inline-editor text, you should find an attribute `data-token`. What value does it have for you?

**Comment by Jimmi08** [comment]
`  data-token="$2y$04$LKF7eGp/65/W.a2WbjcMKOBPVORbjlCQa9QnGMrQXk9fIYN8tMSuO"  `  
Could this be related to php 5.5?

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, if that is what you are using, 5.6 is the minimum. I just tested this under 5.6 and it is working for me.

**Comment by Jimmi08** [comment]
@CaMer0n Good to know, I will need to live with it. Thank you.

**Comment by rica-carv** [comment]
Isn't that `data-token` field a [HTML "thing"](https://www.w3schools.com/tags/att_global_data.asp)?
What does PHP has to do with it?

**Comment by CaMer0n** [comment]
@rica-carv PHP generates the value inside it ;-)

**Comment by Jimmi08** [comment]
@CaMer0n I can't confirm for sure because I don't use latest version, but with php 7.0  I can edit without error, but values are not saved. I tried it on caption  in media manager.  They looks like replaced, but after refresh, old value is there.
