### ISSUE TITLE
alt_auth - it can't connect to server

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3463]
I got error:

server is defined the same way like in config file. 

Cannot connect to remote DB; PDOException message: SQLSTATE[HY000] [2005] Unknown MySQL server host 'mariadb55.websupport.sk:3310' (0)

Is this plugin working in php 7 ?

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/2861

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you. This was very helpful. Please test with the committed changes.

**Comment by CaMer0n** [comment]
Closing. Please re-open if necessary.
