### ISSUE TITLE
error message with notify settings

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3464]
There is probably just something forgotten...

if I save notify settings without any change, it looks like this:

 
![image](https://user-images.githubusercontent.com/5429548/46083508-e7580180-c1a1-11e8-833b-bf644773f90f.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I'm unable to reproduce this. 

![image](https://user-images.githubusercontent.com/2825679/48922892-a9ecb900-ee5e-11e8-9d2c-afe293c94792.png)

How about you @Moc ?

**Comment by Moc** [comment]
Not able to reproduce yet. Not on an existing install (with some plugins) and not on a clean install (just installed from Git). 

PHP 5.6

**Comment by Jimmi08** [comment]
PHP 7.0
Closing without testing. I just noticed that there is custom plugin used, maybe there is something wrong.
That plugin doesn't use events, so I didn't notice that `dng::config()` is executed before.

I will create new issue if this happens again. I really can't remember where this happened.
