### ISSUE TITLE
e_ADMIN_AREA === ADMIN_AREA ???

### ISSUE THREAD

**Issue by oudoken** [e107inc/e107#3465]
Hi Team,
Spoked with @Jimmi08 To not include e_module.php from a custom plugin in admin area to not load unnecessary modules.

The suggested fix is:

```
if( ADMIN_AREA ) {
   return '';
}
```
It's not working, from what i see in:
https://github.com/e107inc/e107/blob/master/e107_handlers/e107_class.php

There's maybe some old code to be fixed? A lot of references to e_ADMIN_AREA and only one reference to ADMIN_AREA.

Emitting from log via:
```
$x_log = e107::getLog();
$x_log->add('is admin area??', 'ADMIN_AREA: '.ADMIN_AREA.' | e_ADMIN_AREA: '.e_ADMIN_AREA, E_LOG_INFORMATIVE, '999');
```
Lead to:
(LOGGED USER)
Administrator | 999 | is admin area?? | ADMIN_AREA: ADMIN_AREA | e_ADMIN_AREA: 1

(NON LOGGED USER)
Anonimo	999	is admin area??	ADMIN_AREA: ADMIN_AREA | e_ADMIN_AREA:

So ADMIN_AREA seems NOT defined??
Thanks Kind Regards 
Rob

**Comment by rica-carv** [comment]
Have you cleaned e107 caches, after that changes and before testing?

**Comment by oudoken** [comment]
Hi @rica-carv 
Not changed anything...
The point is where is defined ADMIN_AREA because e_ADMIN_AREA works, but seems old for V2.0?What's the use of ADMIN_AREA is there's e_ADMIN_AREA?
Maybe @CaMer0n can help?

**Comment by rica-carv** [comment]
e_ADMIN_AREA might still be present for legacy purposes, i think....

**Comment by CaMer0n** [comment]
@oudoken **ADMIN_AREA** is old and **e_ADMIN_AREA** is new. However, both should work. 
I suggest sticking with **e_ADMIN_AREA** for your `if()` statement.

**Comment by oudoken** [comment]
Hi @CaMer0n 
Thanks this clarify! I was thinking that the "e_Something" will be deprecated in future.
There's a line in :
https://github.com/e107inc/e107/blob/master/e107_handlers/e107_class.php

Where ADMIN_AREA is deffed:

`			  || (vartrue($eplug_admin) || deftrue('ADMIN_AREA'))		// Admin forced`

Btw Thanks a lot as always @CaMer0n !
Bye
Rob

**Comment by CaMer0n** [comment]
Thanks Rob, yes, it's a legacy check.

**Comment by oudoken** [comment]
Thanks @CaMer0n
