### ISSUE TITLE
login shortcodes - easier templating

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3466]
{LOGIN_TABLE_SUBMIT}

parameter class is missing

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/pull/3467

**Comment by Jimmi08** [comment]
{LOGIN_TABLE_SIGNUP_LINK}

class is missing, parameter class is missing

**Comment by Jimmi08** [comment]
{LOGIN_TABLE_FPW_LINK}
class is missing,  parameter class is missing, e_BASE used

**Comment by CaMer0n** [comment]
Merged. Thanks.
