### ISSUE TITLE
login error message is loaded 2x 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3470]
Errors after submit login form are displayed twice
![image](https://user-images.githubusercontent.com/5429548/46147071-bbea1b00-c264-11e8-9a1e-324320c1f2ed.png)

removing 	{LOGIN_TABLE_LOGINMESSAGE}  from template didn't help
![image](https://user-images.githubusercontent.com/5429548/46147110-d91ee980-c264-11e8-95d5-ab55fed150b1.png)

If this is duplicate issue, sorry, I couldn't find it, but I think that this was mentioned already.

**Comment by BigBoiJefe** [comment]
I'm experiencing this bug as well.  Any possible fix would be lovely :D

**Comment by Moc** [comment]
Is this still an issue? I cannot reproduce it atm.

**Comment by mostym** [comment]
@Moc Yes, it's still an issue for me.

**Comment by Moc** [comment]
Confirmed. I have the same issue on my theme. Caused by LOGINMESSAGE. 
Not sure what the best fix is.

**Comment by Jimmi08** [comment]
Possiiblefix is removing this:
`e107::getMessage()->reset()->addError($message); // prevent duplicates.`
and left only
`e107::getMessage()->reset();`
because after it
`define('LOGINMESSAGE', $message);`

If you use correct shortcode in template, shortcode output is used

If not,  echo from login.php is used 

OR  let core message functionality and remove support for LOGINMESSAGE.

**Comment by Jimmi08** [comment]
Not sure when this was fixed, but it looks correct now.   At least with core templates
