### ISSUE TITLE
SITEURL vs e_BASE and e_HTTP

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3473]
How to get full path in database field?

There is only available shortcode version for e_BASE:  {e_BASE}
e_BASE is not defined (or empty) in browser debugger output

SITEURL has correct value, but it can't be used in shortcode version {SITEURL}
e_HTTP (what should be replace for e_BASE) doesn't have shortcode version too.

I am trying to get full path in menu button url. 

Thanks

**Comment by rica-carv** [comment]
[e_HTTP??? ](https://github.com/e107inc/e107/issues/1309#issuecomment-264278521)

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/46223034-70159f80-c352-11e8-8a40-e0af70d7fd75.png)

**Comment by rica-carv** [comment]
If it's not in core shortcodes, what prevents you of making it globally available via plugin shortcode (e_shortcode.php) or via theme shortcodes?

**Comment by Jimmi08** [comment]
@Jimmi08 I can fix things, if I understand what is correct way and what is not.

e_BASE should not be used, but shortcode {e_BASE} is still there. And e_HTTP is new, but shortcode e_HTTP is missing.  Or maybe SITEURL should be added.  With SEF-URL there should be shortcode to full site url. 

I need answer from core developers, not to find next workaround.

**Comment by rica-carv** [comment]
@Jimmi08 I know that workaround is not the ideial solution, but if developers don't give a reply, you'll need a backup solution, no? I do that a lot on my plugins and theme.... If you can't hunt with a dog....

Anyway, can't the e_BASE shortcode be there for legacy purposes, maybe? I can't figure out why make a shortcode for a empty return, indeed....

Furthermore, instead of making a single shortcode to output every single constant, what's the issue on using the constant instead of the shortcode?
Or make a single shortcode, to output the constant needed, like `e_CONSTANT: const=e_BASE`

Just my two cents...

**Comment by Jimmi08** [comment]
@rica-carv 
try to put full path to news into menu button url and display. With sef-urls you need to full path  and my question was how to do it.  I have already fixed this but inserting full path (hardcoded).  If you can use {e_ADMIN) and so, maybe there is way how to get siteurl (mainpage). 

{SITEURL} shortocode already exists, you can use it with templating. But if you put it in field, replace constant is used, not parse template.  
Maybe there is other problem, why is not replaced in template...  

But something is there wrong.    So if I get answer what is correct, I can test if it works or not.  I don't need to workaround for this. 

Developers will not answer in issue with so long discussion...

**Comment by CaMer0n** [comment]
@Jimmi08 
> I am trying to get full path in menu button url.

Did you try using `/`  ?

**Comment by Jimmi08** [comment]
@CaMer0n 
**/news** - didn't worked
![image](https://user-images.githubusercontent.com/5429548/46261933-ebb25080-c4fa-11e8-9373-a9ead6292d7a.png)
**news** - worked on homepage
but not with sef-url:
![image](https://user-images.githubusercontent.com/5429548/46261948-05539800-c4fb-11e8-9b83-43e98c0ed445.png)
![image](https://user-images.githubusercontent.com/5429548/46261966-38962700-c4fb-11e8-8048-ee82fa745a54.png)

So what constant has now site path (like siteurl) and can be used as field value?

**Comment by CaMer0n** [comment]
@Jimmi08 Please try changing line 344 of page_shortcodes.php from this: 

    return e107::getParser()->replaceConstants($this->var['menu_button_url']);

to this

    return e107::getParser()->replaceConstants($this->var['menu_button_url'], 'abs');

and use `{e_BASE}news` for the menu button url.

**Comment by CaMer0n** [comment]
@Jimmi08 This should fix it, but please re-open if necessary.  Just use `{e_BASE}news` for your value.

**Comment by Jimmi08** [comment]
You are quicker than my test. I just test it before commit. But on line 298 is the same code.

**Comment by CaMer0n** [comment]
@Jimmi08 

    abs = /news
    full = https://domain.com/news

**Comment by Jimmi08** [comment]
This was confusing :)  First example is in fact relative url. And I thought abs means absolute, so full.  So I asked.   Nevermind. 
Full is correct option or abs only with {e_BASE}. 
Thank you. This is big improvement.

**Comment by Moc** [comment]
Will add to documentation (on backlog for now)

**Comment by CaMer0n** [comment]
@Jimmi08 Updated above. abs != relative, which is why it worked on the home page, but not others. ;-)

**Comment by Jimmi08** [comment]
@Jimmi08 No much changed. Still not clear. I had to google what is absolute url to be sure. And it's url started with http(s).  But if I need to add {e_BASE} to it, it's something different.  Relative url is without protocol.  
So example of "full"  is for me absolute url.  
I can live with it, it's not problem.

**Comment by CaMer0n** [comment]
@Jimmi08  https://stackoverflow.com/questions/10659459/starting-with-a-forward-slash-in-html-for-href#10659501

**Comment by Jimmi08** [comment]
For me both examples (with slash and without slash are relative).   Absolute path has to start with protocol and it's synonym for full path. Generally. Check wiki or any other source. 
  
Ok, in e107 enviroment you call this full path.  I pointed this just because this can confuse somebody else too.  
So if you write that "abs" starts with backslash and "full" is url with protocol, is ok.
