### ISSUE TITLE
weird behaviour - pagination using default template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3476]
I can't use ` define("BOOTSTRAP", 	3);`  because it breaks form.  So I use default pagination.

From some reason I have there word Go to Page, it looks like out off html markup. English is used.
 
![image](https://user-images.githubusercontent.com/5429548/46233464-fc37bf00-c372-11e8-939a-590a09a4acda.png)

Core template is used, not from theme.

Output is:
![image](https://user-images.githubusercontent.com/5429548/46233519-3903b600-c373-11e8-9bf6-fb237ec5bc05.png)

```
<div class="btn-group nextprev ">
Go to page&nbsp;<a class="btn btn-default btn-secondary nextprev-item prev" href="/e107v2.1.9/relive/news?page=0" title="Go to the previous page">previous</a>&nbsp;<a class="btn btn-default btn-secondary nextprev-item" href="/e107v2.1.9/relive/news?page=0" title="">1</a>&nbsp;<a class="btn btn-default btn-secondary nextprev-item current active" href="#" onclick="return false;" title="Currently viewed">2</a>&nbsp;<a class="btn btn-default btn-secondary nextprev-item" href="/e107v2.1.9/relive/news?page=6" title="">3</a>&nbsp;<a class="btn btn-default btn-secondary nextprev-item" href="/e107v2.1.9/relive/news?page=9" title="">4</a>&nbsp;<a class="btn btn-default btn-secondary nextprev-item next" href="/e107v2.1.9/relive/news?page=6" title="Go to the next page">next</a>
</div>
```

**Comment by CaMer0n** [comment]
It is legacy theme behavior. See v1.x

**Comment by Jimmi08** [comment]
Posted fix. Now it looks this:
![image](https://user-images.githubusercontent.com/5429548/46261883-236cc880-c4fa-11e8-8c53-054a42bd278a.png)

What is desired and similar like in version 1.
