### ISSUE TITLE
problem with {NEWSIMAGE} shortcode

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3478]
there is always attribute style 
![image](https://user-images.githubusercontent.com/5429548/46246360-909a3400-c3fc-11e8-90df-7bfc2c5b32fa.png)

because it's inline styling, it can't be fixed in css

This is correct:
```
		$imgParms = array(
			'class'=>$class,
			'alt'=>basename($srcPath),
			'style'=>$style,
			'placeholder'=>varset($parm['placeholder'])
		);
```

but $style is filled this way:
`$style = !empty($this->param['thumbnail']) ? $this->param['thumbnail'] : '';`

and this is filled from this:
`param['thumbnail'] =(defined("NEWSLIST_THUMB")) ? NEWSLIST_THUMB : "border:0px";`

only way how to fix it was to define constant
`define('NEWSLIST_THUMB', '');`

Is this desired way or it's something old?

**Comment by rica-carv** [comment]
Agree, but as a remark, if you use ` !important` in your css rule, won't it override the inline style?

**Comment by CaMer0n** [comment]
It's a backward compatibility thing. Maybe you can try removing 'border:0px' from the code above on some of the v1.x upgraded sites (using v1 themes) and see how they look? (eg wrxxy )

**Comment by Jimmi08** [comment]
Not able to test this anymore.
