### ISSUE TITLE
Custom Extended User Field checkbox - "delete" button unavailable after save/reload

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#3483]
Hey guys: I'm still using using version 2.1.8 but don't see anything in the release notes for 2.1.9 which mentions this explicitly.

I've just added used the "Add Custom Field" features under "Extended User Settings" to insert a single checkbox to the user signup form. I managed to click the "Add new value" button accidentally after typing the text for my checkbox, but didn't realise this until after I'd then clicked "Create" at the bottom of the page.

When I noticed my error during a test signup, I returned to the "Extended User Settings" page, went to "Manage" and clicked the Edit button for my new item, but found that the [x] _delete_ button, which had been available when I was first creating the custom field, was now missing.

Is this by design? Of course, it's trivially easy to just delete the custom field and re-create it without the unwanted second line, but I thought I'd point it out in case it isn't intended!

Thank you all for your fantastic work on the project.

![extendeduserfields](https://user-images.githubusercontent.com/6110212/46278043-f7366380-c55c-11e8-8593-46da43b6724c.jpg)

**Comment by CaMer0n** [comment]
Thank you @sbwMikael  Have you tried simply clearing out the value on that line? If that fixes it I'll mark this as an enhancement, otherwise it is a bug.

**Comment by sbwMikael** [comment]
Hi CaMer0n - thanks for the reply. I can confirm that deleting the text from the second input, and then clicking 'Update' had the effect of deleting the second checkbox. So that works exactly as you described, thank you.

**Comment by Moc** [comment]
Reminder: same for deleting forum attachments: https://github.com/e107inc/e107/issues/3496
 Maybe a core method could be created.
