### ISSUE TITLE
Question - $_GET parameter with pages

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3487]
I just need to confirm that this is correct and it's not bug and it will not changed in future. 
If I am on url related with pages, than e_PAGE has value page.php.  
With SEF-URL you can get where you are with **$_GET** (lonalore uses this with metatag plugin)

Book (correct):
```
    [bk] => 1
    [name] => portfolio
    [id] => 1
    [type] => bk
```
Chapter: (correct)
```
    [ch] => 2
    [book] => portfolio
    [name] => e107-bootstrap-themes
    [id] => 2
    [type] => bk
    [bk] => 
```
Page (why page ID - 10 - is in name and ID is not filled?) 
```
    [book] => portfolio
    [chapter] => e107-bootstrap-themes
    [name] => 10
    [id] => 
    [bk] => 
    [ch] =>
```
Standalone page (correct):  
```
    [id] => 8
    [name] => privacy-policy
    [type] => id
    [bk] => 
    [ch] => 
```

Code from lonalore plugin:
```
/**
 * Determines if the current page is a page item.
 *
 * @return mixed
 *  Page ID if the current page is a page, otherwise false.
 */
function metatag_entity_page_detect()
{
	$page = defset('e_PAGE', '');
	$query = defset('e_QUERY', '');

	if($page == 'page.php' && isset($_GET['id']))
	{
		return (int) $_GET['id'];
	}

	if($page == 'page.php' && (int) $query)
	{
		return (int) $query;
	}

	return false;
}
```

**Comment by CaMer0n** [comment]
@Jimmi08 This is not a good way to check if page is used. 
Please see `e107_plugins/page/e_shortcode.php` inside `__construct() ` for a good way to check.

**Comment by Jimmi08** [comment]
I got it, thanks.

**Comment by Jimmi08** [comment]
I am back to this problem.

Now is not the problem to detect that I am on book/chapter/page.

I just need the book id.  

Do I really need to do the next query to the database like here? When there is that information in $_GET, just not correctly filled?

Thanks

```
			$this->request = e107::getRegistry('core/page/request');
			
			$action = varset($this->request['action']);
			
			if(($action == 'listPages' || $action == 'listChapters') && vartrue($this->request['id']))
			{
				$this->var = e107::getDb()->retrieve('page_chapters','chapter_name, chapter_meta_description, chapter_sef','chapter_id = '.intval($this->request['id']).' LIMIT 1');	
			}
			
			if($action == 'showPage' && vartrue($this->request['id'])) // get chapter and description from current. 
			{
				$query = "SELECT p.page_id,c.chapter_name,c.chapter_meta_description FROM #page AS p LEFT JOIN #page_chapters AS c ON p.page_chapter = c.chapter_id WHERE p.page_id = ".intval($this->request['id'])." LIMIT 1 "; 
				$rows = e107::getDb()->retrieve($query,true);
				$this->var = $rows[0];	
			} 
```

**Comment by CaMer0n** [comment]
@Jimmi08 Ideally, you shouldn't use GET and you shouldn't do a database lookup (since it has already been done for this page)  Where is your code running from?

**Comment by Jimmi08** [comment]
In theme shortcodes on the book page,  I need the book ID

the chapter page should be fixed now, not tested
But I don't know what is correct -  always test e_ROUTE and then use e107::getScBatch('page', null, 'cpage');  
 
the page itself is ok

**Comment by Jimmi08** [comment]
But what is worrying me... on page.php are theme shortcodes loaded 2x - the first time after construct and before init and second time after init.  I let you log the screen on gitter.    

just log f.e. sitetheme value pref in branding shortcode...

**Comment by Jimmi08** [comment]
This was fixed, or changed with e_ROUTE introduced.
