### ISSUE TITLE
tinymce removed my text

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3488]
I am trying to insert this text:  It's in Czech.  Directly from Word. No special hidden characters there:
![image](https://user-images.githubusercontent.com/5429548/46436870-4695b300-c75a-11e8-8da5-c434e8b5a693.png)

```
„A já se budu chovat stejně a za pár týdnů…“ Lenka pokrčila rameny, „po nás ani pes neštěkne.“
„Ať si políbí.“
„Kéž bychom mohli my,“ řekla mu Lenka. „Jenomže pak by lidi jen těžko uvěřili-“ 

```
 Result (there is missing one line)
![image](https://user-images.githubusercontent.com/5429548/46436895-5a411980-c75a-11e8-9f42-55c1773b5fbb.png)
```
[html]<p>&bdquo;A j&aacute; se budu chovat stejně a za p&aacute;r t&yacute;dnů&hellip;&ldquo; Lenka pokrčila rameny, &bdquo;po n&aacute;s ani pes ne&scaron;těkne.&ldquo;</p>
<p>&bdquo;K&eacute;ž bychom mohli my,&ldquo; řekla mu Lenka. &bdquo;Jenomže pak by lidi jen těžko uvěřili-&ldquo;</p>[/html]
```

But if I copy text from code above , it's inserted:
![image](https://user-images.githubusercontent.com/5429548/46436981-98d6d400-c75a-11e8-88e4-0a0c6bdacef0.png)

**Comment by Jimmi08** [comment]
Maybe related
https://github.com/e107inc/e107/issues/4105

- removing paste plugin from tinymce

**Comment by CaMer0n** [comment]
@Jimmi08 Does the problem occur if you copy from Word to Notepad and then from Notepad to TinyMce?

**Comment by Jimmi08** [comment]
I am not able to test this anymore. It could be some word issue.  I was  looking for paste from Word functionality and I found:

"paste_word_valid_elements has been deprecated as of TinyMCE version 5.10 and removed in version 6.0. Now there seems only to be the PowerPaste plugin provided as a premium feature for paid cloud plans"

It is not first feature moved to paid plans with tinymce. 

This can be closed.
