### ISSUE TITLE
Maybe it's time to change hybridauth to the new version?

### ISSUE THREAD

**Issue by net1313** [e107inc/e107#3492]
3.0 instead of outdated?
More features and more providers. Fewer connectivity issues and more modern approach to authentication through social media.

**Comment by CaMer0n** [comment]
Yes! @net1313 Are you okay to test all the e107 social logins for  FB, Twitter etc.. and report back here?

**Comment by net1313** [comment]
Yes! with great pleasure.

**Comment by CaMer0n** [comment]
@net1313 Excellent! :+1:  I'll commit the new hybrid version to git so you can test it.

**Comment by CaMer0n** [comment]
@net1313 v3 appears to be VERY different to v2 of HybridAuth. It could require a major rewrite of how e107 utilizes it (which I have no time to do). So, this is not a simple upgrade unfortunately.  If you wish to try it yourself and send a pull-request once it is working, it would be very welcome! I don't want to risk breaking everyone's social logins by simply committing it. 

The best I could do for now is to upgrade to the latest v2, since it is primarily a simple overwrite of the files/folders.

**Comment by net1313** [comment]
Sorry, i didn't mention this before. I've already tested new hybridauth. i'm not totally sure (it was one month ago) but it seems that only one thing to change is one function in /handlers/e107_class.php (and then to add more options in social plugin)

**Comment by CaMer0n** [comment]
Okay, that's good news. Would you be okay to upgrade to fork e107 and upgrade hybridAuth on your fork it to the latest version? Then others here could also test it out. And once everything is confirmed working, a pull-request could be made.

**Comment by net1313** [comment]
just give me one week. I'll test it locally.

**Comment by net1313** [comment]
Here is what I tested during the last week. 
Version 3.0.0. RC - apart from declaring namespaces, there are many changes to be made in many of e107 files. Does anybody want?

Version 2.12.0 I have not finished testing yet.

Version 2.11.0 succeffully checked. It works. It has a lot of new providers. I've tested with Facebook, Twitter, Github, Google, Yandex, Vkontake ...

The **"additional providers"** folder goes with version 2.11 of Hybridauth. 
But it is not part of the "Providers" folder and you have to copy the file you need from "adittional providers" into "Hybrid/Providers" folder.
I propose to copy all providers files there.

So the 2.11.0 is OK and could be integrated in without changing e107_class and other files of the system except only one file in Social plugin.
_But at this stage integration would not be done automatically._

In e107_plugins/social/admin_config file in: 
```
$this->social_logins = array (
.....
"New Provider" => array (
					"enabled" => true,
					"keys"    => array ( "id" => "", "secret" => "" )
				),
```
This way may be added a new provider.

In order to prevent inexperienced users from modifying Social plugin files manually it would be better to implement in Social plugin _admin_config.php_ a new function which checks all available providers.
Something like this 

```
getFilename()
....
$filename = end(explode(".", $file));
.....

```
Then the user can select only those that he needs.

But there is another small issue. e107_core/shortcodes/batch/signup_shortcodes

`$button = (defset('FONTAWESOME') === 4) ? ......$tp->toGlyph('fa-'....`

There are no glyph icons of new providers in "old" Font Awesome versions. And instead of "fa fa-" we must write **fab**. Even if the version matches, and in case when you want to display buttons, not glyphs, then `src='".e_IMAGE_ABS."xup/{$p}.png'` does not display the provider's button. 
You need to add your prefered social button to the directory e107_images/xup but to force the button displaying we need change (defset('FONTAWESOME') === 4) to something else.

**Comment by CaMer0n** [comment]
Thank you @net1313 ! I agree for the configurations. Like you said - I believe we should add all configurations and then display the ones that are detected in the file system.

**Comment by LaocheXe** [comment]
@net1313 should we work on v3.0 for e107? FONTAWESOME should have most, if not all of the providers on that list, and the one's missing we could get and add to the xup images folder. I can work on the social plugin, and add the additional providers.

**Comment by Moc** [comment]
Fontawesome has been updated in core as well, so that's not an issue. Integrating a newer version of hybridauth will be the challenge.

**Comment by LaocheXe** [comment]
I Checked Fontawesome site, searched for Blizzard, and Steem (came up with nothing) - yes the real challenge would be that.

**Comment by net1313** [comment]
@LaocheXe thanks for invitation. I can't promise to begin immediately. So after this summer it will be probably possibly.

**Comment by net1313** [comment]
Google+ is dead, but if you want to keep social plugin update and allow users login/register through Google account (eg. gmail) just replace a file Google.php in Providers directory of Hybridauth by this file
(https://github.com/hybridauth/hybridauth/blob/e7fb724aea4822b48e6d484e58ac8e541b205086/hybridauth/Hybrid/Providers/Google.php)
was successfully tested and works.

**Comment by CaMer0n** [comment]
@net1313 I was just wondering if you would like to test the pull-request of @Deltik with some social media logins? It is a full upgrade of HybridAuth as you requested. :-)

**Comment by net1313** [comment]
@CaMer0n Thanks. I'll try during this month

**Comment by CaMer0n** [comment]
@net1313 Cheers! :+1:
