### ISSUE TITLE
issue in markup of poll plugin

### ISSUE THREAD

**Issue by net1313** [e107inc/e107#3494]
Line 676:` $opt = ($count==1) ? "id='poll_answer'" : "";`
and line 679:
`".$frm->text('poll_option[]', $_POST['poll_option'][($count-1)], '200', array('placeholder' => POLLAN_4, 'id' => $opt))."`

the markup render is **id='id='poll_answer'**

**Comment by Moc** [comment]
Let me know if this commit solves it

**Comment by net1313** [comment]
Now the rendering is like this:
`<div class='form-group' poll_answer>`

I think the better way is:

                                    ```
  $opt = ($count==1) ? "poll_answer" : "";
					$text .= "<div class='form-group' **id='".$opt."**'>
".$frm->text('poll_option[]', $_POST['poll_option'][($count-1)], '200', array('placeholder' => POLLAN_4, 'id' => $opt))."
```

**Comment by Moc** [comment]
Hmm I assumed the text method worked differently. I'll fix it .

**Comment by Moc** [comment]
Followed your suggestion. Feel free to submit fixes like these in the future by using pull-requests 👍
