### ISSUE TITLE
Weird behaviour with news urls

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3503]
I noticed this on e107.sk
I always use for news sef-url in this form: 
![image](https://user-images.githubusercontent.com/5429548/46981108-2d382380-d0d7-11e8-91b5-bba164e23bbf.png)

I really don't know when but it started looks like this:
https://www.e107.sk/news/view/40/themes/relive-e107-blog-boostrap-theme
 
I had to delete news category Themes with slug "themes"  to get it works correctly.  
Edit: too soon. It worked because it has no category. Now it's back.
Those shortcodes are used:
{NEWSURL}
{NEWS_TITLE: link=1}

view link in admin area is correct

**Comment by Jimmi08** [comment]
I did more tests.  

In admin area I have this code in custom plugin:
`$url = e107::getUrl()->create('news/view/item', $row, array("full"=>1));`
and it generates correct url
result: `http://localhost/***/news/view/1/welcome-to-e107`

so I created custom theme shortcode for news url and used the same code.
`$url = e107::getUrl()->create('news/view/item', $data , array("full"=>1));`
`result: ttp://localhost/***/news/view/1/misc/welcome-to-e107`

Used latest github.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you!. What is the value of `$row` and the value of `$data`? How do they differ?

**Comment by Jimmi08** [comment]
```
 $sc = e107::getScBatch('news');  
    $data = $sc->getScVar('news_item');
```
this was fix:
`$data['category_sef'] = ''; $data['category_id'] = NULL; $data['category_name'] = '';`



$row is result of direct query:
```
$query = "SELECT *  FROM #{$table} WHERE news_id=" . $id . " LIMIT 1";
```

**Comment by Jimmi08** [comment]
@Moc remove awaiting feedback label, please.

**Comment by Jimmi08** [comment]
This was probably fixed.  Not needed anymore.
