### ISSUE TITLE
Download Limits Not Working

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#3504]
I set a user group to only be able to download 5 files per 7 days, however, I've just downloaded 8 files.  I'm running version 2.2 github

**Comment by Deltik** [comment]
I cannot reproduce this with the limit of 2 downloads per 2 days:

![screenshot_2018-11-14 downloads - admin area test site](https://user-images.githubusercontent.com/1364268/48494854-4de9bb00-e7f4-11e8-90bc-2a5d4b77c087.png)

After I made 2 unique downloads, I got this error message upon trying to download a 3<sup>rd</sup> file:

![screenshot_2018-11-14 downloads - test site](https://user-images.githubusercontent.com/1364268/48494856-4de9bb00-e7f4-11e8-862d-3a1893a245ea.png)

**Comment by BigBoiJefe** [comment]
Thanks @Deltik for thinking out of the box.  The problem is that the download Status has to be set to Active - File is subject to download limits
