### ISSUE TITLE
Can't Change User Class from Users>>Manage

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#3505]
When I try and change a user's class from the admin area as the main admin, it shows Forbidden in red lettering below the selection of user classes.  Running github version 2.2, nginx 1.14.0 and PHP 5.6

![2018-10-15_101127](https://user-images.githubusercontent.com/25377269/47072026-ff6fdf00-d1a9-11e8-804f-6d9f6bcce0aa.png)

**Comment by BigBoiJefe** [comment]
I'm still having this issue.   When I click on the check mark after I've updated the user class I get this in the console debugger in chrome:

```
jquery.min.js:4 POST https://www.domain.com/admin/users.php?mode=&action=inline&id=571258&ajax_used=1 403
send @ jquery.min.js:4
ajax @ jquery.min.js:4
save @ bootstrap-editable.min.js:5
submit @ bootstrap-editable.min.js:5
f @ jquery.min.js:2
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

**Comment by Moc** [comment]
What's your PHP version?

**Comment by BigBoiJefe** [comment]
PHP 5.6

**Comment by CaMer0n** [comment]
POST URL is missing the token. Most likely the site is out of sync with the github repo.

**Comment by BigBoiJefe** [comment]
I updated it yesterday.

**Comment by CaMer0n** [comment]
@Moc Tested here with 5.6. Working.  
@Jimmi08 @tgtje Are either of you able to reproduce this issue?

**Comment by Jimmi08** [comment]
@CaMer0n No, I have available only 5.5 and 7.0

**Comment by BigBoiJefe** [comment]
I tried with FF Quantum 63.0 (64-bit) and it works fine.  I'm running Chrome Version 70.0.3538.77

**Comment by Moc** [comment]
Working here on PHP 5.6 (and Chrome). 

Try clearing your Chrome cache.

**Comment by BigBoiJefe** [comment]
I updated from Github again and it's working.  I don't get it.  Maybe my update didn't take or something...
