### ISSUE TITLE
Q: how e107::js('inline', $script);  exactly works?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3506]
I need to insert generated script from third party.

I use textarea field and insert it this way:

```
$script =  html_entity_decode($my_code, ENT_QUOTES);  
e107::js('inline', $script); 
```

I noticed that this code has to starts with <script> and </scripts>  tags, but most of those scripts starts 
with comments.  If you use full code, output is not correct.

`<!-- Smartsupp Live Chat script -->`
![image](https://user-images.githubusercontent.com/5429548/47075004-ded07500-d1fb-11e8-9ae9-ee149dfde9c2.png)

if I removed that note, it's correct.

**Comment by CaMer0n** [comment]
Use `//` for comments inside javascript and `<!--` for inside HTML. (but outside of tags) 
`e107::inline()` wraps the submitted code in `<script>` tags automatically.

**Comment by Jimmi08** [comment]
Is there way just output what I inserted? 
In most case you should place full code, not want for people to change something.

**Comment by CaMer0n** [comment]
@Jimmi08 Just strip the script tags, and it should be fine.

**Comment by Jimmi08** [comment]
I know this.  I think about users who just does what "help of third part" says - copy code and paste it.
Is there other way - insted js::iniline()?  echo in e_footer.php?

maybe there is something what can strip those html comments before I use js::inline(). I am not able to write this regex myself. 

by the way, it works with tags too, because code check if it starts with tags and only then it inserts them itself.

**Comment by nesjett** [comment]
Whats exaclty de difference between using e107::js() for adding inline code or using <script> tags directly into code? I noticed it works differently and I´m getting problems because of that, using tags works fine, but using js() makes my code not to load/wait in the right order so some code gets broken...

**Comment by CaMer0n** [comment]
@nesjett Have you tried using footer-inline? or switching the 'zone' ?

* @param string $type core|theme|footer|inline|footer-inline|url or any existing plugin_name
* @param string|array $data depends on the type - path/url or inline js source
* @param integer $zone [optional] leave it null for default zone
* @param string $dep dependence :  null | prototype | jquery

**Comment by nesjett** [comment]
Thank you cameron, I tried with footer-inline and seems working now, but I´m still a bit concerned about how it works in the back and if it would be possible to add some more dependencies for custom plugins or so.

**Comment by CaMer0n** [comment]
You're welcome. 
`$dep` was mostly for backward compatibility, since jquery is the standard now. 
What did you have in mind regarding dependencies?

**Comment by nesjett** [comment]
This think about using librarys not beign loaded or "downloaded" yet made me think about kind of system that allows you to execute code only after the needed dependency has been loaded.

In normal jquery that could be somethink like making a require with a callback function to execute the code after finishing download.

That would be usefull if some plugins use the same library, to prevent duplicates and be sure the code will work, also to load libraries on specific pages in a "safe" way
