### ISSUE TITLE
Something wrong with admin log

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3508]
Hi Guys!

I think something wrong with admin log. a few days ago, I noticed that the admin logging creates more than 100 entries every day. In database the admin log table is 2 gigbyte size. There are 5 administrators on the site, but we do not do so many activities one day. And in vain, I delete the admin log, the size of the database will not decrease.

Sample:

![01](https://user-images.githubusercontent.com/12445784/47111501-02270e80-d254-11e8-99ef-8a2ddbd170d6.JPG)

![02](https://user-images.githubusercontent.com/12445784/47111514-05ba9580-d254-11e8-8871-e6a0b9b4d8c9.JPG)

![03](https://user-images.githubusercontent.com/12445784/47111525-094e1c80-d254-11e8-8013-9f84c911d5c8.JPG)

**Comment by CaMer0n** [comment]
@KiraTheUltimate Are you using any old plugins? Also, do you recognize the IP addresses?

**Comment by Evgura** [comment]
@CaMer0n There is such problem. The administrator log in the database eventually grows to a huge size.

**Comment by KiraTheUltimate** [comment]
@CaMer0n 
Just one, the "On This Day " plugin. But this plugin was updated by @Jimmi08

**Comment by Jimmi08** [comment]
@KiraTheUltimate @CaMer0n 
I wouldn't say "updated".  It's not on my list of plugins I care or use.  
I just fixed blank page.  

Here is source code:
https://github.com/Jimmi08/e107-old-plugins/tree/master/onthisday_menu

But if you say me what to look, I could do it. 
And @KiraTheUltimate  php version please.

**Comment by Moc** [comment]
What does the 'detail' tab say on each entry? (last column)

**Comment by Jimmi08** [comment]
Yes, and switch to English in admin area please.

**Comment by KiraTheUltimate** [comment]
Oh, I think maybe the on this day menu is the problem.

`No differences found
Backup of core (SitePrefs) successfully created. - Success
LAN_SETSAVED - Success
Array
(
    [0] => Array
        (
            [file] => /home/starwar1/public_html/class2.php
            [line] => 1833
            [function] => save
            [class] => e_pref
            [type] => ->
            [args] => Array
                (
                    [0] => 
                    [1] => 1
                )

        )

    [1] => Array
        (
            [file] => /home/starwar1/public_html/e107_plugins/onthisday_menu/onthisday_menu.php
            [line] => 33
            [function] => save_prefs
            [args] => Array
                (
                )

        )

)`

**Comment by Jimmi08** [comment]
@KiraTheUltimate 
There was bug(?) in original version, fixed now. It used core save_prefs() function, instead custom that is saving correct variables. Just change this line:

![image](https://user-images.githubusercontent.com/5429548/47170473-660a0f80-d306-11e8-893a-979359c51a95.png)

**Comment by KiraTheUltimate** [comment]
Now it's OK with "On this Day" menu, thank you very much!

And is this OK in admin log?

![01](https://user-images.githubusercontent.com/12445784/47213094-4de3d000-d39a-11e8-8992-2f627fdc74db.PNG)

And in vain, when I delete the admin log, the size of the database will not decrease, not delete database entries.

**Comment by Jimmi08** [comment]
Do you check it via phpmyadmin? 
![image](https://user-images.githubusercontent.com/5429548/47213868-93a19800-d39c-11e8-9acf-d50953fb8602.png)
I used Empty table
![image](https://user-images.githubusercontent.com/5429548/47213877-9ac8a600-d39c-11e8-9690-9e30f4c8e1a7.png)

And there is option Optimize too.  

Yes, that log should be correct (I have theme there too), I think you can set somewhere this OFF.

**Comment by Moc** [comment]
> And is this OK in admin log?

Yes. This message confirms an automated database update.

**Comment by KiraTheUltimate** [comment]
Okay, thank you for your helping! I close this.

**Comment by CaMer0n** [comment]
@Evgura @KiraTheUltimate Does this function still work for you?

e107_admin/admin_log.php?mode=main&action=maintenance

![image](https://user-images.githubusercontent.com/2825679/47240782-432b3a00-d39e-11e8-931a-70ef6de5be45.png)

**Comment by Evgura** [comment]
![default](https://user-images.githubusercontent.com/25720089/47250705-cc467d80-d43f-11e8-8838-ad11d2331d5e.png)

**Comment by CaMer0n** [comment]
@Evgura Thanks. I just tested it and the function is working here. Please enable debug and try again.
