### ISSUE TITLE
e_search is wrong on Pages

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3511]
In plugin check, I found this (version git):

![02](https://user-images.githubusercontent.com/12445784/47214499-6655e980-d39e-11e8-845d-ed4a0a1e136d.PNG)

**Comment by Moc** [comment]
Minor issue (not related to functionality) but fixed anyway :)

**Comment by KiraTheUltimate** [comment]
@Moc 
Thx, but I updated from github, and it's still a problem... (I clear the cache on my website)
hmm

**Comment by CaMer0n** [comment]
@KiraTheUltimate Please try again. Thanks.
