### ISSUE TITLE
missing ID in e_QUERY with forum_viewforum.php  and SEF-URL

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3512]
SEF-URL is not unique, and it could be changed later

forum_viewforum.php is only one example for now I found that it doesn't contain ID in some way.

This is not good if you need to find related table and relation is via ID

```
e_PAGE forum_viewforum.php
e_QUERY sef=plugins-in-active-mode&
```

**Comment by Jimmi08** [comment]
Any forum with SEF-URL on.

f.e. 
```
e_REQUEST_URL https://www.e107.sk/forum/ideas/
e_REQUEST_URI /forum/ideas/
e_URL_LEGACY e107_plugins/forum/forum_viewforum.php?sef=ideas&
 
e_PAGE e_PAGE
e_QUERY sef=ideas&
```


if I displays debug variables  (for sure they are not defined later as in e_meta.php)
![image](https://user-images.githubusercontent.com/5429548/47309020-9ff35280-d633-11e8-8f38-35d8dba5986b.png)

**Comment by CaMer0n** [comment]
oh right. Yes, this is normal. The duplicate check should be done in the admin area.

**Comment by Jimmi08** [comment]
Great, how to find forum ID on Frontend then?   Without next query with sef-url ?  The rest of e107 uses ID in e_QUERY, why not here? Maybe it's normal , but it's not standard  or usual.

**Comment by CaMer0n** [comment]
The ID is not in the query. There are other parts of e107 that work like this also. It depends on the SEF-URL scheme being used. 

Line 67 of forum_viewforum.php

```
if(!empty($_GET['sef']))
{
	if($newID =  $sql->retrieve('forum', 'forum_id', "forum_sef= '".$tp->toDB($_GET['sef'])."' LIMIT 1"))
	{
		$_REQUEST['id'] = $newID;
	}
}
```

**Comment by Jimmi08** [comment]
Example from live site:

![image](https://user-images.githubusercontent.com/5429548/47559949-2e5b2300-d917-11e8-8115-be47e52cba0e.png)

There is no warning, nothing.  What posts are selected by clicking on url?  
It can be easily fixed but there is possibility that the records with the same url can exist.  
ID should be used.
