### ISSUE TITLE
FR - could add some check for user mistake

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3519]
It was my fault and I gave wrong instruction.  
Plugin folder was renamed wrong name (instead survey-master there left only master)
But this mistake takes all site down.

Error was:
`Fatal error: Class 'master_url' not found in   ***public_html/e107_handlers/e107_class.php on line 2545`

Couldn't you add check if class exists before it's first time used?

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please give that a try. thanks

**Comment by Jimmi08** [comment]
Thank you
