### ISSUE TITLE
thumb.php failing when custom site_path in use. 

### ISSUE THREAD

**Issue by wrxxy** [e107inc/e107#3520]
I have just updated website but now have lost the preview of media manager images , however it does work when i click the gray box to preview I guess the thumbnail doesn't work as it should...

Is this a bug and is it known to you guys...

![image](https://user-images.githubusercontent.com/13065217/47553321-89f6d200-d952-11e8-8bef-dc6af70d443a.png)

**Comment by Jimmi08** [comment]
Just info:
`$E107_CONFIG['site_path'] = '***';  `

**Comment by rica-carv** [comment]
Or have you tryed to clean e107 caches?

**Comment by wrxxy** [comment]
![image](https://user-images.githubusercontent.com/13065217/47958360-39e8d100-e01e-11e8-82a4-bbe78aed9b93.png)

**Comment by CaMer0n** [comment]
Sorry, to clarify, the URLs for the IMG tag, not the A tag.

**Comment by wrxxy** [comment]
LOL I am not web savvy Cameron as you know,
I think its these
{e_MEDIA_IMAGE}2018-11/click-info.png
{e_MEDIA_IMAGE}2018-10/e-packchampweb.png

or might be this
http://www.outlawsracing.com/thumb.php?src=e_MEDIA_IMAGE%2F2018-10%2Fe-packchampweb.png&w=800&h=0

**Comment by CaMer0n** [comment]
Please try me on gitter. I'm going to need FTP access to your site.

**Comment by wrxxy** [comment]
you must be looking for this 
![image](https://user-images.githubusercontent.com/13065217/48168206-809e3a00-e342-11e8-8a47-0a2b53aed733.png)
