### ISSUE TITLE
what is correct value for empty e_jslib_plugin and e_jslib_theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3524]
This was discussed in  August.

Site updated from version 1 has wrong values of those 2 prefs and it causes javascript error and wrong path in some urls.

Fix in August was to import this:
 
```
	<prefs>
		 <core name="e_jslib_plugin"><![CDATA[Array]]></core>
		<core name="e_jslib_theme"><![CDATA[Array]]></core>
	</prefs>
```
 I tried this too:
```
		<core name="e_jslib_plugin"><![CDATA[array()]]></core>
		<core name="e_jslib_theme"><![CDATA[array()]]></core>
```

It doesn't work anymore. 
there are always '' around value
 
I tried to change this directly in database (both siteprefs and backup of siteprefs)
 
![image](https://user-images.githubusercontent.com/5429548/47711837-8a36ec00-dc36-11e8-9aad-dc7781f855de.png)

but result is the same:
![image](https://user-images.githubusercontent.com/5429548/47711846-91f69080-dc36-11e8-8b69-f0f134151a36.png)
it should look like this:
![image](https://user-images.githubusercontent.com/5429548/47712091-252fc600-dc37-11e8-92d4-2e109c6f53d0.png)

![image](https://user-images.githubusercontent.com/5429548/47711906-afc3f580-dc36-11e8-8c95-73c54e81f405.png)

![image](https://files.gitter.im/wrxxy/A8mD/image.png)

**Comment by CaMer0n** [comment]
Here's what's in the default_install.xml file.

		<core name="e_jslib_plugin"><![CDATA[array ()]]></core>
		<core name="e_jslib_theme"><![CDATA[array ()]]></core>

 I believe the problem was that the export was printing "Array" instead of "array ()".

**Comment by CaMer0n** [comment]
@Jimmi08 Please close this if the above changes fixed it. Thank you.

**Comment by Jimmi08** [comment]
Closing without testing. I will reopen this if this doesn't help.
