### ISSUE TITLE
Add support for hosting providers that disable readfile()

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#3528]
Issue came from Gitter, where @wonozhong had this issue:

![screenshot_2018-10-31 gitter](https://user-images.githubusercontent.com/1364268/47778227-66ba8280-dcc4-11e8-9c79-d2fea07eb900.png)

There are two usages of `readfile()` in e107 that can be abstracted to use an alternative to `readfile()`:

![screenshot_20181031_042308](https://user-images.githubusercontent.com/1364268/47778349-b26d2c00-dcc4-11e8-91cb-34ab1837d7b3.png)

**Comment by CaMer0n** [comment]
Hoping this change is unrelated to  #3520

**Comment by Deltik** [comment]
@CaMer0n: #3520 looks unrelated.

In that issue, the user referenced this thumbnail URL:

`http://www.outlawsracing.com/thumb.php?src=e_MEDIA_IMAGE%2F2018-10%2Fe-packchampweb.png&w=800&h=0`

That translates to this source URL:

`http://www.outlawsracing.com/e107_images/2018-10/e-packchampweb.png`

At the time of writing, that URL returned HTTP 404, which explains the by-design behavior of `thumb.php` redirecting to `https://placehold.it/800x0`.
