### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by JoniPeti** [e107inc/e107#3535]
Hi!

I would have a problem!
My hosting provider has changed my server and has problems with e107 since then.

There is eg. a marikanet.hu. If you want to sign in to the page, you will not be allowed as administrator or user. Reset to reset. https://marikanet.hu/e107_admin/admin.php

I have the site jonaspotalstudio.hu. if I log in as a user or administrator, I get a white screen. You are rolling back to the site for multiple updates.

My other pages do this on this server.
Currently, 5.6 is the php version. I also tried with 7.2.
Which modules should I plug in?
What could be the problem?

(google translate)

**Comment by Jimmi08** [comment]
marikanet.hu  -  Don't you have facebook log in available?  There is error on console.  I created account on your site, this problem is familiar.  From version did you do update?  Did you run database update?

**Comment by JoniPeti** [comment]
No facebook logging set. The latest stable version is v2.1.9.
Update was successful and regular. The database has also been successfully updated.

The service provider answered my problems:

> Dear Peter!
> 
> Please look at any of these issues in the forums, try to find the errors on the site.
> 
> There are quite a few websites running on this server, we only experience e107 errors in earlier versions.
> 
> I have now looked through the web in the forums and, based on that (https://github.com/e107inc/e107/issues/2062), inserted the line in the config file. From here you can see the following message instead of whitescreen:
> 
> Your IP is banned!
> 
> As we run a number of servers and storage sites, unfortunately we do not have the capacity to look at and fix all the web pages. Please find out why the website engine is forbidden (as this error message is not provided by the server "cloudlinux", but the web engine itself interferes with the process, our firewall never generates such a screen message).
> 
> We ask the webmaster managers to:
> 
> If you experience a problem, please upgrade your CMS to the LAST version. CPanel is updated daily to the latest version, along with updates to all php, apache versions, antivirus databases, etc. We will not turn it off because security is the most important to us, even if the failure to update some websites will lead to malfunctioning of the page. Regularly update your website engine and components!
> 
> Find the optimal PHP version for your website! This can be done by the publishing organization's recommendations. Choosing an incorrect PHP version may lead to malfunction.
> 
> In the PHP Selector, select the required components from the PHP extensions. Ask the software publisher for assistance to select the appropriate extensions.
> 
> Please check the error logs. Typically, defective operation finds its description and description of causes.

**Comment by Jimmi08** [comment]
`Please check the error logs. `
Yes, exactly, but where if you have no access to logs?

Did you check php info of e107 section if there is everything ok? (In admin, under About icon)

Look at last message:  (I switched to Firefox to have this message in English)
![image](https://user-images.githubusercontent.com/5429548/47911841-d5e7d080-de96-11e8-8777-30f7c1ae9de0.png)

This message is from Facebook login app.  

Not mention how it looks in google Chrome:
![image](https://user-images.githubusercontent.com/5429548/47912009-69b99c80-de97-11e8-8468-0ec7daacd0c6.png)

**Comment by JoniPeti** [comment]
No facebook access is on! I looked at the database.
I asked the server for the server error log

**Comment by JoniPeti** [comment]
> Did you check php info of e107 section if there is everything ok? (In admin, under About icon)
I do not know because I can not log in.
I look at another website where I can log in.

**Comment by JoniPeti** [comment]
> Did you check php info of e107 section if there is everything ok? (In admin, under About icon)

I do not know because I can not log in.
I look at another website where I can log in.

**Comment by CaMer0n** [comment]
@JoniPeti Do you have access to cPanel? Check server access log and errors.

**Comment by JoniPeti** [comment]
I asked the service provider to make the server error log available because it is not currently visible.

**Comment by JoniPeti** [comment]
marikanet.hu:

> [Sat Nov 03 13:17:03.602498 2018] [core:error] [pid 1395869:tid 140233207170816] (36)File name too long: [client 46.229.168.154:0] AH00036: access to /\xc3\x81llatokat boncoltak fel egy keszthelyi gimn\xc3\xa1zium biol\xc3\xb3gia-szakk\xc3\xb6r\xc3\xa9ben, el\xc5\x91fordult, hogy kiscsib\xc3\xa9ket \xc3\xa9lve daraboltak a di\xc3\xa1kok \xe2\x80\x93 der\xc3\xbcl ki a hvg.hu birtok\xc3\xa1ba ker\xc3\xbclt vide\xc3\xb3b\xc3\xb3l. A foglalkoz\xc3\xa1sokra m\xc3\xa1r 13 \xc3\xa9ves kort\xc3\xb3l j\xc3\xa1rtak gyerekek, s\xc5\x91t a szomsz\xc3\xa9dos katolikus \xc3\xa1ltal\xc3\xa1nos iskola tanul\xc3\xb3it is bevont\xc3\xa1k. Amint elkezdt\xc3\xbck felder\xc3\xadteni az \xc3\xbcgyet, a szakk\xc3\xb6rt vezet\xc5\x91 tan\xc3\xa1r hirtelen t\xc3\xa1vozott az iskol\xc3\xa1b\xc3\xb3l, a tanker\xc3\xbclet vizsg\xc3\xa1latot ind\xc3\xadtott, az \xc3\xa1llatv\xc3\xa9d\xc5\x91k b\xc3\xbcntet\xc5\x91feljelent\xc3\xa9st tesznek. A vide\xc3\xb3 alapj\xc3\xa1n maguk a di\xc3\xa1kok is megsajn\xc3\xa1lt\xc3\xa1k olykor a \xe2\x80\x9em\xc3\xa9g csipog\xc3\xb3\xe2\x80\x9d madarat boncol\xc3\xa1s k\xc3\xb6zben. Felh\xc3\xadvjuk olvas\xc3\xb3ink figyelm\xc3\xa9t, hogy cikk\xc3\xbcnk tartalma felkavar\xc3\xb3 lehet. failed (filesystem path '/home/marikanet/public_html/\xc3\x81llatokat boncoltak fel egy keszthelyi gimn\xc3\xa1zium biol\xc3\xb3gia-szakk\xc3\xb6r\xc3\xa9ben, el\xc5\x91fordult, hogy kiscsib\xc3\xa9ket \xc3\xa9lve daraboltak a di\xc3\xa1kok \xe2\x80\x93 der\xc3\xbcl ki a hvg.hu birtok\xc3\xa1ba ker\xc3\xbclt vide\xc3\xb3b\xc3\xb3l. A foglalkoz\xc3\xa1sokra m\xc3\xa1r 13 \xc3\xa9ves kort\xc3\xb3l j\xc3\xa1rtak gyerekek, s\xc5\x91t a szomsz\xc3\xa9dos katolikus \xc3\xa1ltal\xc3\xa1nos iskola tanul\xc3\xb3it is bevont\xc3\xa1k. Amint elkezdt\xc3\xbck felder\xc3\xadteni az \xc3\xbcgyet, a szakk\xc3\xb6rt vezet\xc5\x91 tan\xc3\xa1r hirtelen t\xc3\xa1vozott az iskol\xc3\xa1b\xc3\xb3l, a tanker\xc3\xbclet vizsg\xc3\xa1latot ind\xc3\xadtott, az \xc3\xa1llatv\xc3\xa9d\xc5\x91k b\xc3\xbcntet\xc5\x91feljelent\xc3\xa9st tesznek. A vide\xc3\xb3 alapj\xc3\xa1n maguk a di\xc3\xa1kok is megsajn\xc3\xa1lt\xc3\xa1k olykor a \xe2\x80\x9em\xc3\xa9g csipog\xc3\xb3\xe2\x80\x9d madarat boncol\xc3\xa1s k\xc3\xb6zben. Felh\xc3\xadvjuk olvas\xc3\xb3ink figyelm\xc3\xa9t, hogy cikk\xc3\xbcnk tartalma felkavar\xc3\xb3 lehet.')

**Comment by JoniPeti** [comment]
Hi!
I migrate websites to another hosting provider! I will not go on with the current service provider. So my problem will also be solved. Thanks for the help!
