### ISSUE TITLE
Languages>Verifier>Editor>Edit Plugin lan files failing

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#3541]
Hi Team
Still working on Welsh translation, slow because I am a learner of the language myself! 

When we choose a plugin file to edit, we get an extra couple of dots at the start of the path, in the file parameter, hence:

language.php?mode=main&action=tools&sub=edit&lan=Welsh&file=..%2Fe107_plugins%2Fblogcalendar_menu%2Flanguages%2FEnglish.php&iframe=1&type=P

When I remove the two dots manually, I can at least get the editor page to open, but then it complains about the CHMOD of the file. I have CHMOD'd file and folder to 0777 without success. 
![image](https://user-images.githubusercontent.com/2847651/47967584-b5ff0b00-e056-11e8-83f6-86a52ec2ea36.png)

/e107_plugins/blogcalendar_menu/languages/Welsh.php is not writable, you need to CHMOD 777 the file or folder first.

I'm taking deeper look into it.
Mike

**Comment by Moc** [comment]
I've not been able to reproduce this yet on several environments, both Linux and Windows.

There's two issues: 
- The extra dots should be fine. There's something environment (your hosting setup) specific that prevents this from functioning ok 
- The file not being writable

As for the file not being writable, does chmodding to 666 help?
