### ISSUE TITLE
Sorting User list in Admin by anything in Extended User Fields shows no results

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#3544]
User listing in Admin shows all my users all good.  By selecting the Options arrow at the end, I can add my Extended User Fields to this Admin View.  If I click on any of the column headers that are Regular User fields, such as Display Name or Join Date etc, it sort my User Listing by those Columns, real useful!  However if I click any column that is an Extended User Field, it does not sort by that column and actually shows No Records Found.  This would be really useful to me to be able to sort via an Extended User Field.  Thanks Devs!

**Comment by Deltik** [comment]
I went back to commit 02d026a28f7488da694c1bd6c2ddb588c80d49e5, before changes in the model sorting core feature were made, and found that sorting by Extended User Fields has never worked.

The sorting system is not aware of JOINs, as Extended User Fields come from a different table.

**Comment by CaMer0n** [comment]
@martyshep Normally this should be functioning for you now, but please re-open if necessary.

**Comment by martyshep** [comment]
Awesome thank you Cameron. As always, amazing support from you and your co-devs.
