### ISSUE TITLE
Index - welcome message as a startpage gives a problem with fbclid..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3546]
When using the welcome message as a startpage (index.php) and placing a link from for example facebook to a e107 website not the whole index page is showed, facebook ads a fbclid query string to the url.

When using a custom page or news as a starting page there's no problem.

Example - http://fysid.nl/?/klmnbv
or http://fysid.nl/ 

Confirm?
Alex

**Comment by Moc** [comment]
Confirmed. 

@CaMer0n What are your thoughts on how to fix this?

**Comment by Moc** [comment]
Should be fixed by https://github.com/e107inc/e107/commit/9237f254c78d6e5e36cd7ffff444cc92ffd6f802

**Comment by Alex-e107nl** [comment]
Hi Moc,
i've uploaded the git from one minute ago, it dit not solve the problem... you can check it with the links provided in my first message.. I assume that my theme is not the reason.. did also try it with the standard bootstrap 3 theme, same result..

I really hoped that it was the solution.. 
Alex

**Comment by Moc** [comment]
@CaMer0n Can you review please?

**Comment by CaMer0n** [comment]
Thanks @Alex-e107nl Yes, I noticed this issue also. I'm working on it. 
The following $_GET vars are now filtered, at least for SEF detection, and now I'm working on correcting it for THEME_LAYOUT detection. 
```
'fbclid','utm_source','utm_medium','utm_content','utm_campaign'
```

If you know of more, please share them.. Thanks.

**Comment by Alex-e107nl** [comment]
Hi Cameron,
its also a problem when you switch languages with for example.. ?elan=German with index.php ...

**Comment by CaMer0n** [comment]
Thanks @Alex-e107nl . I have filtered that out also now.  Please re-open this issue if you find others.
