### ISSUE TITLE
March 2011 regression causes e_parse_shortcode::parseCodes() to forget added global shortcodes

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#3547]
Issue came [from Gitter](https://gitter.im/e107inc/e107), where @BigBoiJefe had this issue:

![screenshot_2018-11-08 e107inc e107](https://user-images.githubusercontent.com/1364268/48219286-be568f00-e351-11e8-99fa-b80633a8b6bd.png)

On-site debugging revealed that `e_parse_shortcode::parseCodes()` forgets any known/global shortcodes, essentially requiring the optional parameter "`$extraCodes`" to be specified in all calls to this method.

The regression was introduced on 24 March 2011 in commit 13f51c79c34acf3454064daa1f64b6b186b6149a.  Commenting out [this line](https://github.com/e107inc/e107/commit/13f51c79c34acf3454064daa1f64b6b186b6149a#diff-2aa7b877e814353724b4a60f72da70b5R512) resolves the issue and lets @BigBoiJefe call a shortcode from the source code of another one.

**Comment by CaMer0n** [comment]
Here's how it should be done in v2. No core changes required. As far as I know, "glyphicons' do not support the 'size' option, so I have retrieved the URL and rendered the glyph manually using FontAwesome instead. 

	function sc_download_test()
	{
		/** @var download_shortcodes $sc */
		$sc = e107::getScBatch('download',true);
		$url =  $sc->sc_download_view_link(array('type'=>'href'));
		return "<a href='".$url."'><i class='fa fa-download fa-5x' ></i></a>";
	}

**Comment by Deltik** [comment]
@CaMer0n: That does appear to be an alternative approach for the user's particular problem, but this is more of a bug regarding the unexpected behavior of `e_parse::parseTemplate()`.

I just found that this works:

```php
return e107::getParser()->parseTemplate("<a href='{DOWNLOAD_REQUEST_URL}'><button type='button' class='btn btn-success'><font color='white'>Slow Download</font></button></a>", true, e107::getScBatch('download',true));
```

But this only works with my patch in #3548:

```php
return e107::getParser()->parseTemplate("<a href='{DOWNLOAD_REQUEST_URL}'><button type='button' class='btn btn-success'><font color='white'>Slow Download</font></button></a>", true);```
```

This confusion leads to a few items of concern:

- Is `e_parse::parseTemplate()` meant to be called with a minimum of 3 arguments?  If so, why is only 1 argument required?
- Is `e107::getParser()` (gets instance of `e_parse`) meant to be called by any non-core code at all?
- Why shouldn't non-core code run `e_parse::parseTemplate()`?  It's more intuitive to fire-and-forget the parsing of `{DOWNLOAD_REQUEST_URL}` than to find the shortcode object (`$sc = e107::getScBatch('download',true)`) and then call the shortcode function (`$url =  $sc->sc_download_request_url()`).

**Comment by CaMer0n** [comment]
parseTemplate() is working as expected. It should only parse **core** shortcodes `e107_core/shortcodes/single` (not plugin shortcodes) when the second argument is true.  The third argument is required if third-party shortcodes are to be processed. (in the form of a class or array) . This is how it has worked since the very beginning and I believe your fix is not necessary because nothing is actually broken or malfunctioning.

**Comment by Deltik** [comment]
Okay, I understand now.

[The phpDoc documentation](https://github.com/e107inc/e107/blob/ec3a2e28b515deeceb28faaa54ddac2220e25297/e107_handlers/shortcode_handler.php#L745) doesn't match the actual behavior:

```php
	/**
	 *	Parse the shortcodes in some text
	 *
	 *	@param string $text - the text containing the shortcodes
	 *	@param boolean $useSCFiles - if TRUE, all currently registered shortcodes can be used.
	 *								- if FALSE, only those passed are used.
	 *	@param array|object|null $extraCodes - if passed, defines additional shortcodes:
	 *			- if an object or an array, the shortcodes defined by the class of the object are available for this parsing only.
	 *	@param array|null $eVars - if defined, details values to be substituted for shortcodes. Array key (lower case) is shortcode name (upper case)
	 *
	 *	@return string with shortcodes substituted
	 */
```

I was expecting "`if TRUE, all currently registered shortcodes can be used.`" to mean that all currently registered shortcodes, including those of the `download` plugin, could be used.

My confusion was further amplified by [how `pluginsTest::testBanner()` was written](https://github.com/e107inc/e107-test/blame/4edf0519455885e41b12284b1d42fdb12910eb8e/tests/unit/pluginsTest.php#L128).  As you can see in the test, `e_parse::parseTemplate()` is called with only two arguments, yet the `banner` plugin shortcodes are used.

That's why I was perplexed that `{DOWNLOAD_REQUEST_URL}` of the `download` plugin returned a blank string when I tried to use the method in the same way.

**Comment by Deltik** [comment]
@CaMer0n: [I added some combinations of `e107::getParser()->parseTemplate(…)` to `pluginsTest::testBanner()`.](https://github.com/e107inc/e107-test/commit/eec2feb8b30a6936a6b7f9094b07e7b25e350e5a)

As you said `e_parse::parseTemplate(…, true)` should only parse core shortcodes from `./e107_core/shortcodes/single`, can you update the `XXX` commented part of the test with the desired assertion for the correct expected output?

**Comment by CaMer0n** [comment]
@Deltik Sorry, I forgot to mention e_shortcode.php registered shortcodes are included in the "True" option - these are classed as 'core addons', they are 'site wide'.

**Comment by Deltik** [comment]
@CaMer0n: I wrote tests to cover what you described!

Here they are: https://github.com/e107inc/e107-test/commit/48654804bdcceb28e1882fe2f4b6c55e5b8dee28
