### ISSUE TITLE
problem with attachments  on forum thread

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3549]
Could you explain @wrxxy  where to set this:
on backup of the same site  is every
http://www.outlawsracing.xyz/e107_plugins/forum/forum_viewtopic.php?&id=7231
 
![image](https://user-images.githubusercontent.com/5429548/48252438-0edaf480-e405-11e8-98df-5f97270e5be6.png)

`<img src="http://www.outlawsracing.xyz/e107_files/public/1516192003_9_FT1975_clean_racer18.png" class="bbcode" alt="" width="75" height="170" onload="NcodeImageResizer.createOn(this);">
`

but on active site there is code:
`<a data-modal-caption="FT1975_clean_racer18.png" data-target="#uiModal" rel="external" href="/thumb.php?id=c3JjPSU3QmVfTUVESUElN0RwbHVnaW5zJTJGZm9ydW0lMkZhdHRhY2htZW50cyUyRnVzZXJfMDAwMDA5JTJGMTUxNjE5MjAwM185X0ZUMTk3NV9jbGVhbl9yYWNlcjE4LnBuZyZhbXA7dz0xMDAwJmFtcDtoPTA=" class="forum-attachment-image e-modal" target="_blank"><img class="thumbnail" src="/thumb.php?id=c3JjPSU3QmVfTUVESUElN0RwbHVnaW5zJTJGZm9ydW0lMkZhdHRhY2htZW50cyUyRnVzZXJfMDAwMDA5JTJGMTUxNjE5MjAwM185X0ZUMTk3NV9jbGVhbl9yYWNlcjE4LnBuZyZhbXA7dz01MDAmYW1wO2g9MA==" alt=""></a>`
and result is:
![image](https://user-images.githubusercontent.com/5429548/48252419-02569c00-e405-11e8-91f5-093a0cf76702.png)

plugin nCode Image Resizer is used on both sites

**Comment by wrxxy** [comment]
I am still getting these ultra big images does any one know why?

And when I go to the code that shows these images, those bigger image codes are not there....

![image](https://user-images.githubusercontent.com/13065217/49531482-7a35ba80-f90e-11e8-868c-dea639069165.png)

**Comment by Jimmi08** [comment]
I found reason.  It's attachment

![image](https://user-images.githubusercontent.com/5429548/49790510-b3b35f00-fd2e-11e8-8c3c-7004306779d8.png)

But I don't see any option to remove it

![image](https://user-images.githubusercontent.com/5429548/49790565-cfb70080-fd2e-11e8-9134-a6990ed82fd4.png)

**Comment by Jimmi08** [comment]
After removing this shortcode {ATTACHMENTS: modal=1}, problem is way.
