### ISSUE TITLE
Getting this error message when updating to latest github version

### ISSUE THREAD

**Issue by wrxxy** [e107inc/e107#3551]
Hi all I am getting this error message when updating to latest github version
can anyone elaborate pls
![image](https://user-images.githubusercontent.com/13065217/48301219-6466ec80-e53e-11e8-8989-74ce590315e3.png)

I get this so I update
![image](https://user-images.githubusercontent.com/13065217/48301254-e35c2500-e53e-11e8-9a4c-3437ad72bfe9.png)

then i click this and get ,
![image](https://user-images.githubusercontent.com/13065217/48301230-99733f00-e53e-11e8-81b8-cf945d0e4a8b.png)

what does this mean? Also getting strange things happening on website. If anyone is willing to help....

**Comment by CaMer0n** [comment]
@wrxxy It means one of your forum names is the same as the other. Specifically the SEF URL value. Modify the SEF of the duplicate and then run the upgrade again.

**Comment by Moc** [comment]
I tried doing that on his website but no luck... Not sure what's going on there.

**Comment by CaMer0n** [comment]
@Moc Hmm, you modified 'ksr' ?

**Comment by Moc** [comment]
Yes. There are no duplicates in the sef_url column. Still gave that error.

**Comment by CaMer0n** [comment]
I would try running the ALTER TABLE command directly on the table using PhpMyadmin.

**Comment by Moc** [comment]
Yeah no luck. I think the only option is to make a backup of the table, drop it, re-create it using the new structure with the unique key and then import the rows again from the backup.

**Comment by CaMer0n** [comment]
I logged into phpmyadmin and fixed it for him. MySQL kept referring to the wrong key 'ksr'. There were multiple forum-sef URLs that were identical.
