### ISSUE TITLE
backcompat.css vs THEME_LEGACY

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3557]
Why backcompat.css  is loaded on not bootstrap themes and not only on legacy themes?
```
if(THEME_LEGACY === true || !deftrue('BOOTSTRAP'))
{
	$e_js->otherCSS('{e_WEB_CSS}backcompat.css');
}
```

Sometimes I need to use bootstrap theme without BOOTSTRAP constant. 
`define("BOOTSTRAP", 	false);`

and because backcompat.css is styling bootstrap classes (why?  they weren't used in legacy themes), it has influence on my theme css. 

Theme author should decide if to use back compatibility css.  Or at least to decide not to use it.  
Constant THEME_LEGACY is for this.  What this have common with bootstrap?

**Comment by Moc** [comment]
@CaMer0n your thoughts on this one?

**Comment by CaMer0n** [comment]
@Jimmi08 Because bootstrap classes are hardcoded into the core of e107, and without the backcompat.css file some things would look seriously broken.

**Comment by Jimmi08** [comment]
Ok, thanks
