### ISSUE TITLE
forum view shortcodes and icons problem

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3559]
I have theme without glyphicon icons.  It doesn't use library for loading bootstrap, because bootstrap css is already customized.

Result is:
![image](https://user-images.githubusercontent.com/5429548/49139509-46e1a300-f2f2-11e8-83cd-9dda91e429a8.png)

The reason is that icon output is glyphicon set 

`text .= "<li class='text-right'><a href='" . $url . "'>" . LAN_FORUM_2041 . " " . $tp->toGlyph('share-alt') . "</a></li>";`

by looking at e_parse_class handler there was change in glyphs are loaded. 

So either forum shortcodes should be customized to use Fontawesome (add fa prefix there)
or this should be let on theme developers. 

**Quick fix:**
- if fontawesome is defined than callback should be "fa fa-" not this:	
`$prefix     = 'glyphicon glyphicon-'; // fallback`

But there is other problem.  With hardcoded glyph names I can't use getThemeGlyphs(), because theme glyphs use different name.  

I somehow need to change icon name. It would be great to have possibility set this in theme and replace all hardcoded icons.

```
$icons['share-alt']  = 'pe-7s-share';
$icons['envelope'] = 'pe-7s-mail';
```

**Comment by Jimmi08** [comment]
I tried to set this at least for icon with the same name.
I found this problem:
`if(strpos($text, $glyphConfig['prefix']) === 0)`

strpos returns false, so it should be ==  not ===.

**Comment by Jimmi08** [comment]
It doesn't work for me.  My glyphs settings:

```
	<glyphicons>
		<glyph name='pixeden' pattern='\.(pe-7s-[a-z-0-9]*):before\{'  path='assets/css/fonts/pe-icon-7-stroke.css' class='pe' prefix='pe-7s-'   tag='span' />
	</glyphicons>
```
I don't need class, but I added it to see difference.

Output should be:
`<span class="pe-7s-trash"></span>`

But it is:
`<span class="pe trash"><!-- --></span>`

**Comment by Jimmi08** [comment]
The way how to load glyphicons without bootstrap:
`e107::css("url", "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"); `

**Comment by Moc** [comment]
@Jimmi08 Can this issue be closed?

**Comment by Jimmi08** [comment]
Yes, I will create a new one if I find something new.
