### ISSUE TITLE
$NEWS_INFO is not able to be overridden in theme news template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3561]
If I put this into news/news_template.php, it works.
```
$NEWS_INFO = array(
	'section-card' 	=> array('title' => LAN_DEFAULT, 	'description' => 'unused'),
	'section-card-blog' 	    => array('title' => 'Section Blog Cards', 		'description' => 'Section Blog Cards'),
	'section-blog-horizontal'  => array('title' => 'Section Blog Horizontal',     'description' => 'Section Blog Horizontal'), 
);
```

As soon as I do it only in theme template, it doesn't work. 
But template itself is changed ($NEWS_TEMPLATE['section-card']['item']) after changing this in core template.

**Comment by CaMer0n** [comment]
@Jimmi08 Please define "it doesn't work". Do you mean that the options listed in the theme's template file do not appear in the admin area when editing the news post?

**Comment by Jimmi08** [comment]
@CaMer0n Yes, but it's in news settings (or preferences),  template for news list (not one post), there is default, list and column 2 - not used - something like this.

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n Just digged a bit into it and i think i found the issue.
The getTemplateInfo() method was configured to look for the var in the admin theme and not in the frontend theme. I'll submit a PR that loads the data from the frontend theme (if available) and merges it with the default options.
