### ISSUE TITLE
Can't post in forum

### ISSUE THREAD

**Issue by gsandys** [e107inc/e107#3563]
![forum](https://user-images.githubusercontent.com/36930002/49198040-0e959f80-f39a-11e8-970c-a980f466613d.png)
I can not write anything as the main admin on the forum, it simply does not offer anything! Meanwhile, the spams on the forum go to the hole!

**Comment by Jimmi08** [comment]
Add screenshot of your forum settings

**Comment by Evgura** [comment]
@Jimmi08 This is the main forum page, there doesn't have to be.
You need to create a subcategory category. This is all done through the admin panel.

**Comment by gsandys** [comment]
It's shows "only members can post" but permisions is set on Admin ... so as I'm admin & can't post it

**Comment by gsandys** [comment]
![screenshot_20181130-032331](https://user-images.githubusercontent.com/36930002/49262758-98a03f80-f450-11e8-83d7-32726d589a35.png)
![screenshot_20181130-032402](https://user-images.githubusercontent.com/36930002/49262769-9f2eb700-f450-11e8-9859-07edf7872e11.png)

**Comment by Moc** [comment]
What is your PHP version?

**Comment by gsandys** [comment]
PHP - 7.1.24

**Comment by gsandys** [comment]
Ok I think its ok now!

After Forum moderator(s) add admin as Moderator...
