### ISSUE TITLE
a lot of php warnings after plugin rescan

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3564]
Latest github
PHP 7.0.29

![image](https://user-images.githubusercontent.com/5429548/49207991-d2bd0300-f3b6-11e8-863b-bf0e02433490.png)

Not sure if this can be caused wrong written plugin or there is other problem. It just surprised me.

**Comment by Moc** [comment]
Most likely a third party plugin causing trouble

**Comment by CaMer0n** [comment]
Added a check which might help things.

**Comment by Jimmi08** [comment]
Could it be after deleting plugin folder manually and there is still record in plugin table?   I quess from your fix.

**Comment by Jimmi08** [comment]
Thank you
