### ISSUE TITLE
Contact page without SEF URL

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3566]
As i see it the only way to link to the contact page is with /contact.php right? There's no /contact defined somewhere or am i overlooking something?

Should be possible i think?

Alex

**Comment by Jimmi08** [comment]
If this is in core, there should be option to set this and in languages too

In custom plugin you can add e_url.php with

```
$config['contact'] = array(
			'alias'         => 'contactus',                         
			'regex'			=> '^{alias}\/$', 					 
			'sef'			=> '{alias}/', 						 
			'redirect'		=> '{e_BASE}contact.php',  
		);
```

  
![image](https://user-images.githubusercontent.com/5429548/49254785-7a274d80-f42a-11e8-8360-2443d431bb55.png)

![image](https://user-images.githubusercontent.com/5429548/49254866-b8bd0800-f42a-11e8-9427-140d0de2a6af.png)

 
![image](https://user-images.githubusercontent.com/5429548/49254973-020d5780-f42b-11e8-8ac6-bddf848210f1.png)

**Comment by Alex-e107nl** [comment]
Thx Jimmi08!! will try it!

**Comment by Moc** [comment]
Would be a question for e107help rather than Github :) For the next time.

**Comment by Moc** [comment]
Actually, I think it might be missing from the core settings

**Comment by Alex-e107nl** [comment]
Moc,
i've placed it here because i think it's not right that all the links can be SEO but not the contact page.. so it's a bug, forgotten or anything but it needs to be adressed..

**Comment by Moc** [comment]
Yeah you're right, my mistake, sorry 👍

**Comment by Alex-e107nl** [comment]
Tested, works perfectly thx Cameron!!

**Comment by Jimmi08** [comment]
@CaMer0n    e_PAGE is changed, now it's index.php.   
How to test that you are on contact page?

**Comment by Moc** [comment]
@CaMer0n Can you help @Jimmi08 with the constant when using SEF URLs? e.g. this issue and #3567
