### ISSUE TITLE
in theme.php e_PAGE for news view is not defined

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3567]
With contact page e_PAGE is contact.php

With news homepage e_PAGE is news.php

But in news view (extend) e_PAGE is e_PAGE 

but in debug I can see it's defined, so it has to be done later.

How to test in theme.php that news detail is displayed?

I did it for now this way:
```
if (!defined('e_PAGE') AND strpos(e_REQUEST_URI, 'news') !== false)     {
  define("e_PAGE", 'news.php');
}    
```

**Comment by Moc** [comment]
We need a list with these ID's as well anyway

**Comment by Jimmi08** [comment]
Solved with e_CURRENT_PLUGIN and magic shortcode for page CAPTION
