### ISSUE TITLE
signup.php missing support for shortcode wrapper

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3569]
login and signup templating is very different now.

with signup tempate you can't use wrapper, only old $sc_style

**Comment by CaMer0n** [comment]
@Jimmi08 I could upgrade it for you, but I'd need you help to have the changes tested extensively.

**Comment by Moc** [comment]
Can this be closed with the latest files?

**Comment by Jimmi08** [comment]
Thanks
