### ISSUE TITLE
non-standard template for news layout is rendered before header

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3570]
Using:
Use non-standard template for news layout causes that news are rendered before header (before html tag)
 
![image](https://user-images.githubusercontent.com/5429548/49360633-0c08b200-f6da-11e8-82e4-7521a9a3e687.png)
 
![image](https://user-images.githubusercontent.com/5429548/49360708-42dec800-f6da-11e8-8af4-f56e6089afe8.png)

I tried to find reason but code looks correct. Maybe some constant is missing?

I have defined 
```
$NEWSCLAYOUT
$NEWSCOLUMNS
$NEWSSTYLE
$ALTERNATECLASS1 =  'c';
```
I know that this is outdated, but this is unique feature, I would  like to use it.  Thanks.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. Please close this issue if the commit fixes it.

**Comment by Jimmi08** [comment]
I couldn't get it work. It was because this:
https://github.com/e107inc/e107/issues/3562

After fix this for php 7, it worked.  Thank you.
