### ISSUE TITLE
Can't SETSTYLE comments

### ISSUE THREAD

**Issue by fsLeg** [e107inc/e107#3577]
I'm writing my own theme. The process has some hiccups, but I manage. But I can't defeat the following problem.

The comments are being output this way: $COMMENTSTYLE is inside whatever comment_class.php outputs, which in turn is inside whatever tablestyle() renders. comment_class.php can't be touched. comment_template.php is ignored. However, the template is used only if you don't define $COMMENTSTYLE. Which is strange, because $NEWSSTYLE works nicely with a template, at least with news_view_template.php. Does that mean these variables are legacy and you aren't actually supposed to use them in theme.php and should use templates instead?

Even if that's the case, it still leaves the problem of comments using the default $style with no obvious way to override it. How can I at least apply {SETSTYLE} to comments so I could tell tablestyle() to output them differently? I couldn't find where I can put the shortcode, and it doesn't work in comment_template.php.

**Comment by CaMer0n** [comment]
`$COMMENTSTYLE` is deprecated and used only for old themes. 

Copy `e107_core/templates/comment_template.php` to `e107_themes/YOURTHEME/templates/comment_template.php` and then modify that. 

This should give you full control over how it looks. 
Hope this helps.

**Comment by fsLeg** [comment]
Except it doesn't give me full control. comment_template.php resides within $text variable of whatever tablestyle() renders. I need to tell tablestyle(), that I want to change style of comments so it wouldn't treat them as general content (default $style). So far I did this with {SETSTYLE} shortcode. But with comments I have no idea where to put it.

**Comment by CaMer0n** [comment]
@fsLeg Thanks for your feedback. What page are you testing with? News comments?

**Comment by fsLeg** [comment]
Yes, news comments.

**Comment by CaMer0n** [comment]
Thanks.. checking...

**Comment by CaMer0n** [comment]
Here's an example for theme.php: 

    function tablestyle($caption, $text, $id='', $info=array()) 
    {
       if($id === 'comment')
       {
             echo $caption;
             echo $text; 
             echo "<hr />custom style used only on comments";
             return null; 
       }

    }

**Comment by fsLeg** [comment]
@CaMer0n That seems to be working perfectly. Thanks!

Is there a list of those id's? Mayhaps they'll come in handy in the future.

**Comment by Moc** [comment]
I tend to use this: 

```
function tablestyle($caption, $text, $id='', $info=array())
{
    $style = $info['setStyle'];
    
    echo "<!-- tablestyle: style=".$style." id=".$id." -->\n\n";
    ....
}
```

So in the source code, the ID's are visible. Having said that, the documentation should indeed include a list of id's...
