### ISSUE TITLE
modal forum attachments are too big

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3587]
Because this:
`$full = $tp->thumbUrl($baseDir . $file, 'w=1000&x=1', true);`

smaller forum attachment image looks like this:

![image](https://user-images.githubusercontent.com/5429548/50305569-820b6800-0493-11e9-99ce-72e751fd803d.png)

There should be used real image size .

**Comment by CaMer0n** [comment]
@Jimmi08 Changed to 0. Please test.

**Comment by Jimmi08** [comment]
Sorry, I have no data to test this anymore.
