### ISSUE TITLE
Latest Git, Repeated reminders Update Required: user/e_user.php need to be registered

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#3592]
Hi All, 
Update one of my sites to latest git today and keep getting reminders in Admin.

* Update required in update_routines.php on line 693 (user/e_user.php need to be registered)

Running the update appears not to fix it. 
Print_a of $e_user_list after it is read from prefs (686) returns null. 
The plugin sits in Not-Installed, but cannot be installed. 
Taking a look at a few other installations to see if I can spot anything. 
Mike

**Comment by MikeyGMT** [comment]
Happy New Year!

A little digging into this done today.  So one site has no pref value in e_user_list but two other sites do.

![image](https://user-images.githubusercontent.com/2847651/50574987-59686400-0deb-11e9-937f-52617943d202.png)


![image](https://user-images.githubusercontent.com/2847651/50574981-42c20d00-0deb-11e9-84b0-c2042f49d379.png)

I am not sure what fills that array, I can only see e_user_list referenced once in all our code. It looks like it was new in September when update routines was tidied up by @CaMer0n  

https://github.com/e107inc/e107/commit/b60f9950caadd8a9ed1ee9f67bcf5613192e99aa#diff-6c8a6349fe096898b86cd0b07ae96949 

It's not an urgent issue, I can just ignore the error. Pub is calling!

**Comment by MikeyGMT** [comment]
I tried manually populating it via db core prefs, but that was ignored, it was reset straight away.

**Comment by Moc** [comment]
I'm getting the same issue on one of my websites.

**Comment by CaMer0n** [comment]
Please re-open if this doesn't solve it.

**Comment by MikeyGMT** [comment]
Just refreshed from GIT, checked several times, e_user_list remains null and system still requesting update.

**Comment by Moc** [comment]
@MikeyGMT Cameron and I are live testing as we speak :)

**Comment by Moc** [comment]
We found the cause of the issue, and a workaround but it would be better to solve the issue at the core. Updates coming soon :)

**Comment by MikeyGMT** [comment]
Thanks @CaMer0n 

Downloaded the fresh git today. 

After pressing update, the page reports it has completed successfully, however, the pref is still missing  

`\'e_user_list\' => array ( \'user\' => \'user\', )`

 I have this error:

`Warning array_key_exists() expects parameter 2 to be array, string given, Line 208 of /home/zzz/public_html/e107_handlers/core_functions.php`

Debugging (ALL Details), I can see the SQL to update the prefs (REPLACE INTO e107_core ... ) numerous (16) times, 8 for SitePrefs and 8 for the backup step, as expected it does NOT have same prefs in each statement.

The last logged statement does have the new pref but it is updating the backup (hence is incorrect).
 
`REPLACE INTO e107_core (e107_name,e107_value) values ('SitePrefs_Backup',`

The prior to last update does NOT have the new pref which is updating 'SitePrefs'.  

`REPLACE INTO e107_core (e107_name,e107_value) values ('SitePrefs', `

So it looks like the Backup HAS the new value for e_user_list but the new SitePrefs looks like it is updated with the backup. 

Are they being Pref/Backup updates being inversed? 

( Odd that the system is updating the same records so many times in one user transaction ).

**Comment by CaMer0n** [comment]
@MikeyGMT Please delete the pref `e_user_list` and then have e107 recreate it (it should request an update for that). Thanks.

**Comment by MikeyGMT** [comment]
I have, several times, via pref editor. 

Admin offered two options to update prefs - tried both - with Chrome and FF.
![image](https://user-images.githubusercontent.com/2847651/51893030-99474a80-239b-11e9-9bd0-89670ed041f1.png)
Clearing cache, set cache off, clear webcache. Open fresh browser.

I have tried update via phpmyadmin in SQL before and after the update button. I have also updated the backup pref at the same time.

I have also removed the e107_plugin \ user folder temporarily. Disabled multilan, wrapper, TinyMCE, featurebox & cookie consent (i.e. no plugins). Switched down from PHP 7.2 to 7.1 to 7.0 - lower versions seem unavailable. 

It does recreate the deleted pref but without the array populated with user => user. 

Whilst it keeps reverting back, it's not causing an issue as such. Hmm, odd.

**Comment by CaMer0n** [comment]
Thanks @MikeyGMT 
@Moc are you still able to reproduce this issue?

**Comment by Moc** [comment]
@CaMer0n Yes, same results as @MikeyGMT. The user plugin is still missing from the e_user_list preference. The user plugin is still listed as NOT installed.

**Comment by MikeyGMT** [comment]
Great e462759 Fixed it! Thanks @CaMer0n @Moc !!!

**Comment by Moc** [comment]
👍 Welcome!
