### ISSUE TITLE
Custom forum_post_template.php not working

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#3594]
Hi,

I'm having problems with my own forum template. I'm already using the new path (e107_themes/THEME/templates/forum/forum_post_template.php). However, my own template does not work there.

The default forum_post_template.php in e107_plugins/forum/templates/ work without problems ...

Here my file: 
https://pastebin.com/RyPL9XCW

greeting

Killer0561 (Sascha)

**Comment by Moc** [comment]
A blank page means that there is a PHP fatal error. In this case you probably have a syntax error in your custom template, as illustrated by the example of Jimmi on Gitter. The PHP server error log will show you exactly the errors you have in the custom template.

I'm closing this issue on Github,as  it's not a core issue.
