### ISSUE TITLE
Theme Manager blank modal with PHP 7.x

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#3596]
Theme Manager:-
Latest install of e107 from github 

When trying to install a theme from the find themes tab, upon clicking the theme i wish to install, the popup box is empty and nothing happens / installs.

Any help in resolving much apreciated.

Regards.

Gary

**Comment by Jimmi08** [comment]
@gary231178 PHP version? or other enviroment settings.

**Comment by gary231178** [comment]
Thank you for the reply. I was initially using php version 7.0 i have also tried using both 7.1 and 7.2 all of which wouldn't work. I was able to change the php version to 5.6 and then the theme manager would work correctly as intended, here is my issue though for me to be able to use https with my domain my webhost (1&1) insists that i have to use php version 7.0 or above, using any other version risks my site being insecure which they will not allow.

Do you know if there is a workaround, or alternatively is it known when the latest version of e107 will support php 7.0 and above?

Regards,

Gary

**Comment by Jimmi08** [comment]
I can confirm this with php 7.2.  Officially e107 support php 7.1. and I think that there is already issue about this created.
My advice - download theme manually from e107.org and use ftp.

**Comment by Moc** [comment]
e107 should work fine with PHP 7.0 and 7.1. Compatibility with 7.2 is improving but not complete yet. Please do keep on reporrting these issues as it will help to speed up the process ;)

**Comment by gary231178** [comment]
Just to confirm i get the same problem on a clean install  using php 7.0

**Comment by CaMer0n** [comment]
@gary231178 @Jimmi08 Please re-test with latest changes. Thank you.

**Comment by CaMer0n** [comment]
@Jimmi08

**Comment by Moc** [comment]
I am assuming this is fixed, if not, please let me know and I'll re-open.
