### ISSUE TITLE
sitedown template logo

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#3597]
When activating the sitedown flag, there is a missing logo error at top of page.
When i view the url for it is http://www.allotmentguide.com/theme/img/0x300/voux/install/logo2B252832529.png
there is no such directory as theme as it is e107_themes and in anycase it refers to the voux theme which isnt even the one im using.

Any advice greatly appreciated, just come back to e107 after a 5 year break from webhosting.

Regards,

Gary

**Comment by Jimmi08** [comment]
For that URL you need to look at e107_themes/voux/install    
It's new in version 2 with Media Manager.  
Voux theme is there by default. When you change theme and theme doesn't override this image by install.xml, your data (path) is not changed.  Check your logos in Preferencies.

**Comment by gary231178** [comment]
Thankyou for the reply, im still having sitewide issues with images, wherever an image is supposed to be i just get the missing image logo, and even when uploading and or viewing images in admin area  i see the filename of the image but no preview, if i right mouse click any of the affected images and i try to open the filepath i get a 500 internal server error, ive have gone through all settings and cant see anything i have missed.

This is using a clean install today with php version 7.0 with latest github build.

Regards,

Gary

**Comment by CaMer0n** [comment]
hi Gary, I'd be happy to take a closer a look at what is occurring for you. 
Please send me a private message on Gitter when you have time.

**Comment by gary231178** [comment]
ok ive never tried to do that, but ill give it a go thankyou

**Comment by Moc** [comment]
Closing due to lack of feedback. Please re-open if necessary.
