### ISSUE TITLE
ERROR 1286 (42000) Unknown storage engine 'MyISAM' 

### ISSUE THREAD

**Issue by 2214445407** [e107inc/e107#3598]
What should I do if I encounter this situation? 
The final step of the installation suddenly prompts this!
Please help me, I am using a Cpanel host.

**Comment by Moc** [comment]
You should contact your webhosting provider. It's weird that it lists MyISAM as an unknown storage engine as it is the default in MySQL installations. Your webhosting provider will be able to explain it and find a workaround.
