### ISSUE TITLE
wysiwyg

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#3599]
Apologies if this has been answered before but i couldn't find an answer,

So im using e107 again after a break from the web for a couple of years, my html knowledge is very basic, and always relied on wysiwyg for both the news, welcome message & new pages, in preferences i have wysiwyg set to on (was by default) and post html for main admin, however, in all the areas where i previously used wysiwyg in the places i mentioned it will only let me post html, i understand that still you can change the text type and align text etc, but becomes an issue for me when i want certain text in bigger letters, or underlining or aligning a certain part of text then it uses the [size=15][/size] but i really did find wysiwyg a great help for me with this cms, is it a bug, or was the feature removed? or is there another setting ive missed somewhere?

Regards,

Gary

![screenshot_1](https://user-images.githubusercontent.com/12760959/50730131-b2aefb00-113d-11e9-9fc8-4b3b5f2c086e.png)

**Comment by gary231178** [comment]
![screenshot_2](https://user-images.githubusercontent.com/12760959/50730146-e8ec7a80-113d-11e9-8862-91c02f04ae69.png)

**Comment by Jimmi08** [comment]
Do you have installed Tinymce between your plugins?

**Comment by gary231178** [comment]
Aah thats the issue then ill do that now, thankyou.

**Comment by Jimmi08** [comment]
@gary231178 what I know -  I have never tinymce installed (maybe because I use git version). There is other editor too, so maybe this is reason. Or it depends on e107 version? No idea. But I always wonder after new install where is my wysiwyg when I set to use it ON.  So you are not only one :)

**Comment by CaMer0n** [comment]
A javascript error (caused by an old plugin etc) can cause TinyMce to fail to load.
