### ISSUE TITLE
Impossible to login as admin with 2.1.9 fresh install on wamp

### ISSUE THREAD

**Issue by jipem01** [e107inc/e107#3602]
Hello,

Trying a fresh install today on a **wamp server** for local developpment. After successully installing e107 2.1.9, i try to login with login and password provided during installation, with no success (Login and password does not match an existing user etc...).
I could create a new user, and copy his encrypted password as admin password directly with phpMyAdmin, and then, it was possible to connect with admin login.
Something went wrong with password encryption during install?
I've try several installation and still same problem...

**Comment by Moc** [comment]
I think I had the same issue. Will need to reproduce again to be sure. Will get back to this.

**Comment by jipem01** [comment]
I work with wampserver 3.1.3 :
Apache 2.4.33
PHP 5.6.35
MariaDB 10.2.14

**Comment by CaMer0n** [comment]
@Moc Would be good to see the actual password string after install to determine which algorithm was used.

**Comment by Moc** [comment]
Clean install with Github files, PHP 7.1. 

During installation:
- All checks passed
- Username: admin
- Password: testing

Frontend login: Works
Admin login: Works

Will do more testing with different environments asap.

**Comment by Moc** [comment]
Just tested this with PHP 5.6.40 and MariaDB 10.3.12. Still no luck reproducing. Logged in both on frontend and admin area. 

I am sure I had a similar issue but then I only could login via frontend and not directly via admin area.

**Comment by Moc** [comment]
@jipem01 Could you try and reproduce the issue on your environment and share the encrypted password strings please?

**Comment by jipem01** [comment]
Today I try the following : 
- My personal server,  Centos with php 5.4.16, Appache 2.4.6 and mariaDB 5.5.60,
- Fresh install of wamp on my w10 computer (with MariaDB 10.3.9, PHP 5.6.38 and Appache 2.4.35, as close as i can of my office computer...).
For both, no problem.
I'll try monday with my office computer.

**Comment by Moc** [comment]
@jipem01 Any luck trying to reproduce it? :)

**Comment by Moc** [comment]
> And then no more success

You mean, you couldn't login?
Can you please check the password hashes in the database? Directly after install and then after the success attempt, and after the failed attempt?

**Comment by Moc** [comment]
I am assuming this was caused by #4004 and that is fixed. If the issue still occurs for you, please let me know and I'll re-open.
