### ISSUE TITLE
toDate() and time in future - relative time is wrong

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3605]
I have those data:

```
    ".$row2['ecds_date']." <br>
    ".$tp->toDate($row2['ecds_date'], "relative")." <br>
    ".$tp->toDate($row2['ecds_date'], "long")."
```
Result:
![image](https://user-images.githubusercontent.com/5429548/50786155-04c55d00-12b3-11e9-9698-690104ee7b03.png)

Date is correctly saved in Unix forum.  Manual checking:
![image](https://user-images.githubusercontent.com/5429548/50786253-448c4480-12b3-11e9-8e79-aa6b336cdbee.png)
![image](https://user-images.githubusercontent.com/5429548/50786262-4d7d1600-12b3-11e9-9bfd-53b7deacf15f.png)

What could be wrong?
Server time is correct  (user timezone is not used)
 
![image](https://user-images.githubusercontent.com/5429548/50786467-f592df00-12b3-11e9-8cd6-f88777dbbbb5.png)

Checked html code:
`<span data-livestamp="1546988400">1 day ago</span>`

**Comment by Moc** [comment]
Confirmed

**Comment by Moc** [comment]
So it works properly when I install the plugin "Livetime" by @arunshekher which includes the actual JS files required to make use of the 'livestamp' plugin (http://mattbradley.github.io/livestampjs/)

I'm just wondering why by default it does support "x time ago" but not future. Researching....

**Comment by Moc** [comment]
When using 'relative', by default the `toDate()` method calls the `computeLapse()` method in date_handler.

This by default returns `LANDT_AGO` which is defined as `define("LANDT_AGO", "ago");`

**Comment by CaMer0n** [comment]
@Moc I agree. :+1:

**Comment by Moc** [comment]
@CaMer0n Can you check if my fix is OK please? I am pretty sure it could be done more efficiently but I didn't want to break anything as it such a core method.

**Comment by CaMer0n** [comment]
@Moc I ran the test and it failed. It appears to be placing 'in ' in all cases for me. How about you?

**Comment by CaMer0n** [comment]
@Moc I found some time to rewrite it. Please give it a try. Thanks.

**Comment by Moc** [comment]
@CaMer0n Thanks! Just tested and it seems to work fine 👍
