### ISSUE TITLE
FR (Q)  - admin UI - check only allowed actions

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3606]
Ok,
maybe there is other way how to do it.  But I want to allow only edit mode. 

I was able to do it with: 
```
protected $afterSubmitOptions = array('edit');
$this->setDefaultAction('edit');
```

it works. 
![image](https://user-images.githubusercontent.com/5429548/50792918-db163100-12c6-11e9-8da0-99c2aa1c2416.png)

But if somebody manually change url to list - list mode is displayed. 

I solved this by checking $mode in form (method type is used) and return Cheating warning with empty options,  I am just curious if there is other option available.  

I suppose the question what you are trying to do :) - so imagine this like when one json pref is one record in database and only edit mode is available, no list, no delete etc.  Thanks

**Comment by Moc** [comment]
I think this needs a check in the Admin UI controller to check the URL/query string.

**Comment by CaMer0n** [comment]
@Jimmi08 See e107_plugins/faqs/admin_config.php for an example of settings the access permissions.

**Comment by Jimmi08** [comment]
Do you mean this? If yes, it's something else, but nevermind.  I found other way. 

'main/pending'	=> array('caption'=> LANA_FAQ_UNANSWERED, 'perm' => 'P', 'uri'=>"admin_config.php?mode=main&action=list&filter=pending"),

```
	    if(!empty($_GET['filter']))
	    {
			$action = $_GET['filter'];
			$this->adminMenu['main/'.$action]['selected'] = true;
	    }
```

**Comment by CaMer0n** [comment]
No, this... 

```
$this->access = array(
			'main/create'   => varset($pref['admin_faq_create'],   e_UC_ADMIN),
			'main/edit'     => varset($pref['admin_faq_edit'],     e_UC_ADMIN),
			'main/delete'   => varset($pref['admin_faq_delete'],   e_UC_ADMIN),
			'cat/list'      => check_class($pref['admin_cat_create']) || check_class($pref['admin_cat_edit']) ? e_UC_ADMIN : e_UC_MAINADMIN,
			'cat/create'    => varset($pref['admin_cat_create'],   e_UC_ADMIN),
			'cat/edit'      => varset($pref['admin_cat_edit'],     e_UC_ADMIN),
			'cat/delete'    => varset($pref['admin_cat_delete'],   e_UC_ADMIN),
		);
```

**Comment by Jimmi08** [comment]
Oh, thanks.
