### ISSUE TITLE
admin login with email address not working

### ISSUE THREAD

**Issue by Bobbycharlton1** [e107inc/e107#3616]
I just installed latest clean version. I logged in on the main page no issue.  but when I select admin area, it asked me to login again.  I did but had to use a different login.  once at the admin page, no matter what area of the admin I select, I get redirected to the login page.  once logged in again, its sends me back to the main admin page

**Comment by Bobbycharlton1** [comment]
PHP 7.0.33
SQL 5.6.41-84.1

**Comment by Moc** [comment]
>  I did but had to use a different login

What do you mean by this?

**Comment by Bobbycharlton1** [comment]
So if I login on the main page it insists on using my email address
If I select admin it takes me to the admin login page where I have to use the username setup in the install process. It won't accept the email address

**Comment by Moc** [comment]
Ok, and logging into the admin area with the username and password you entered during installation works fine? Just not with the email address, correct?

**Comment by Bobbycharlton1** [comment]
No. Once logged in I got the main admin page. Now if I select any admin item it takes me back to the admin login page and I have to login again and it just takes me back to the main admin page again

**Comment by Moc** [comment]
Ok. I confirmed the bug of not being able to login to the admin area with an email address (only username and password). 

As for your second issue. Are you being redirect back to the Dashboard or to the admin login page? 

Also, I'm on Gitter for real-time chat: https://gitter.im/e107inc/e107

**Comment by Bobbycharlton1** [comment]
So once logged into admin dashboard. I select any admin item such as welcome message. It sends me to the admin login page. I login again and it sends me back to the dashboard. Just a circle

**Comment by Moc** [comment]
Ok, so this sounds like your server configuration may be incorrect. Can you check (or let your hosting provider check) the PHP session save path, to see if it's set correctly and whether the folder is writable for the server?

**Comment by Bobbycharlton1** [comment]
Sorted with a fresh install
