### ISSUE TITLE
Download Plugin:  Reported links goto non SEF urls

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#3622]
When clicking on the  There are unmoderated administrator messages link, download urls are not SEF but instead plugins/download/download.php?view.84963

**Comment by Moc** [comment]
This is heavily outdated and needs to be moved in Download plugin code and database rather than still using the generic table.

**Comment by Moc** [comment]
Just finished the rework of 'Broken download reports' functionality in the admin area:

- Moved away from e107_admin/message.php to its own place in the Downloads admin area. 
- Notification of broken downloads now controlled by e_notify (see Admin Area > Settings > Notify) 
- Updated notification message
- Added e_dashboard addon to show latest status on broken download reports

@mostym @Jimmi08 Please test and let me know what you think :)

**Comment by Moc** [comment]
Oh, you probably have to go to Tools > Database > Scan plugin folders. This way, the system will recognize the new addons (e_notify, e_dashboard). 

I still need to add a check somewhere to force that scan.

**Comment by Jimmi08** [comment]
> I still need to add a check somewhere to force that scan.
Good luck with it. I would use this too :)

By the way, great work, but only way I could test this, is to sync on live site and then you will report something and we will see results.  I am sort of time and this is only way how I can help you. Sorry.,

**Comment by Moc** [comment]
Self-note, todo:

- Make sure that when `download_mail` pref was selected, the notify is set to admin (or main admin?)
- Add check for addon changes

**Comment by CaMer0n** [comment]
@Moc Can this one be closed? Thanks.

**Comment by Moc** [comment]
> f-note, todo:
> 
> * Make sure that when `download_mail` pref was selected, the notify is set to admin (or main admin?)
> * Add check for addon changes

This is still open.

**Comment by CaMer0n** [comment]
okay, thanks.

**Comment by Moc** [comment]
Actually, I am going to close this one. 

> Make sure that when download_mail pref was selected, the notify is set to admin (or main admin?)

For now I will not implement this, but we can add it in the future. Manually setting this configuration option would be best, because I cannot predict what the user would like to set (main admin, admin, another class, etc.).
