### ISSUE TITLE
Admin area home icon, doesn't redirect to Frontpage URL

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#3624]
I defined a new frontpage url /home for all users.  For the most part it works flawlessly.  There is one exception, and that's when an admin goes to the admin area and clicks on the home icon to go home.  This instead goes to / instead of /home.  In most cases this would be fine, however, i have an index.html in my root directory.

**Comment by BigBoiJefe** [comment]
@Achim I created a directory called home and placed it in my root directory, and created a custom index.php and placed it in that folder.  Is that what you did?

**Comment by BigBoiJefe** [comment]
Please also remember that I'm using a static index.html in my root directory.

**Comment by BigBoiJefe** [comment]
Hi @Moc .  The goal is to have a static index.html in the root directory to improve performance and site load time.  If I setup a directory called /home with a  index.php with the following contents the user once logged in, redirects them to https://www.domain.com/home, and loads the welcome message.  Is that the incorrect way to do stuff?

```
<?php
require_once("../class2.php");
require_once(HEADERF);

if (!USER) {
    header("location:".e_BASE."");
    exit;
}

if($pref['user_tracking'] != "session"){
        session_start();
}

require_once(FOOTERF);
?>
```

**Comment by SimSync** [comment]
I tried it once again and i can't reproduce your issue.
Here is what i did:
1. Created a subfolder "home"
2. Added a file caled "index.php" with the contents from your previous post.
3. Updated the frontpage setting by selecting "Disabled or Enter Custom URL" with value "home" (without any slashes!).

It always redirects me now to /home and it doesn't matter if i click on the "home" button in the admin area or on the sitelogo on the frontpage.

**Comment by mostym** [comment]
@SimSync The reason you're not having an issue is because you don't have a static index.hml in /.

**Comment by Jimmi08** [comment]
@Moc this can be closed
@SimSync is right.  index.html should be renamed to something else.  There can't be index.html and index.php on the same level.

**Comment by Moc** [comment]
Closing this due to lack of feedback.
