### ISSUE TITLE
Where to add code right after the opening <body> tag

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#3629]
I'm using Google Tag Manager and they want this line immediately after the opening <body> tag, where do I add this in my template?  Thanks!

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by LaocheXe** [comment]
Well Google's Tag Manager seems to have two sets of code - one called <head> and the other <body> - <head> would be the header - which can be done with a plugin using e_header.php. Or you can do this in the theme.php and look for the header layout. Example of that is in line 171 in Bootstrap 3 theme.php.

<body> would be the main section of the website - so if you are using the bootstrap 3 theme, in the theme.php check out the layouts - there are a few of them, you don't want the code in the _header_ and the _footer_ layouts. You want to add the code to jumbotron_home, modern_business_home, jumbotron_full, and jumbotron_sidebar_right, I suggest putting it up near the top of each layout code.

**Comment by CaMer0n** [comment]
@mostym You can paste this code directly into the Meta/Tags area of admin as of v2.3.1. 

/e107_admin/meta.php

"Custom tags (after <body>)"
