### ISSUE TITLE
Media mаnager not open selection dialog to a local file to Nokia N9.

### ISSUE THREAD

**Issue by nickypn** [e107inc/e107#363]
As I wrote in forum here: http://e107.org/e107_plugins/forum/forum_viewtopic.php?246051 ,
I test e107 v.2.0 by browsing through Nokia N9.
For now I found is that when I tried attempt to upload a file in media mаnager the selection dialog to a local file to the phone does not open.

**Comment by Moc** [comment]
Please re-open if this is still an issue in the latest version.
