### ISSUE TITLE
[Proposal] Render avatars for chatbox_menu plugin posts in chat.php 

### ISSUE THREAD

**Issue by arunshekher** [e107inc/e107#3630]
Would like to see a custom template-able list view for chat.php page with user avatars and user profile links rendered just like in the chatbox_menu. But this plugin has been left un-updated for so long, if there are specific reasons for it someone please let me know. 

I worked a bit on it and was able to add an external template in templates directory inside this plugin  and a shortcode class following  the e107 conventions advised in the developer manual.  A screenshot of the result is posted below. Is it acceptable @CaMer0n et al? If yes shall I submit a merge request for it? Thanks

![screen shot 2019-01-19 at 12 51 31 am](https://user-images.githubusercontent.com/315195/51412948-bb182480-1b86-11e9-9bdd-1d05b6c9ebc7.png)

**Comment by CaMer0n** [comment]
@arunshekher Looks fine. Pull-request welcome.

**Comment by Moc** [comment]
Looking good! Great work!

**Comment by arunshekher** [comment]
@CaMer0n & @Moc, Just submitted these changes via #3631

**Comment by CaMer0n** [comment]
Merged! Closing.
