### ISSUE TITLE
Language verify question

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#3632]
Verify my language pack in localhost (windows 10 and xampp).
This is bug?

All errors: Non UTF-8 Characters Found

![lan](https://user-images.githubusercontent.com/17430115/51426202-6b1d7a00-1be7-11e9-9668-b5c7f65f6fba.png)

![php](https://user-images.githubusercontent.com/17430115/51426204-71abf180-1be7-11e9-9d12-3fd34acb65f2.png)

**Comment by yesszus** [comment]
Perfect for the language pack and only for windows under this error.
Not find <php (points are blank) OR after closing tag.

**Comment by tgtje** [comment]
I suppose it is the Hungarian latest lang pack you are referring to. 
Just downloaded it, installed and did run a check. 
I too get 81 mistakes. Using the edit mode i do see that NOT all defines eg translations are read/displayed... Very strange....

@Moc can you please have a look into the Hungarian lang pack too ?

![example](https://user-images.githubusercontent.com/1811857/51495471-c6549580-1dbc-11e9-868e-2f2261c690bb.jpg)

**Comment by Moc** [comment]
Two issues:

1. Issue reported by @tgtje that not all defines are read/displayed

2. The non-UTF8 error is caused by the `ő` and `ó`. Looking into it.

**Comment by Moc** [comment]
@CaMer0n Can you take a look at this please?

Test code:
```php
<?php

function is_utf8($str) {
	/*
	* @see http://hsivonen.iki.fi/php-utf8/   validation.php
	*/
	if(strtolower('CHARSET') != "utf-8" || $str == "")
	{
		return TRUE;
	}

	return (preg_match('/^.{1}/us',$str,$ar) == 1);
}


$strings = array(
		"Főadminisztrátor",
		"Hői", 
		"Rendszerinformáció", 
		"Felhasználó", 
		"Regisztrált felhasználó"); 


echo "Test 1: mb_check_encoding() <br />"; 
foreach($strings as $string)
{
	if(mb_check_encoding($string, "UTF-8") == false)
	{
		echo "Error: ".$string." is NOT UTF-8 <br />"; 
	}
	else
	{
		echo "Success: ".$string." is UTF-8 <br />"; 
	}
}

echo "<br /><br />";
echo "Test 2: is_utf8() - e107 method <br />"; 

foreach($strings as $string)
{
	if(!is_utf8($string))
	{
		echo "Error: ".$string." is NOT UTF-8 <br />"; 
	}
	else
	{
		echo "Success: ".$string." is UTF-8 <br />"; 
	}
}
``` 

But in `e107_admin\lancheck.php` on line 1310 `$this->is_utf8($check[$k][$sk])` returns false..... 
No idea where the issue is....

**Comment by Moc** [comment]
@SimSync Maybe you have an idea on this one?

**Comment by SimSync** [comment]
@CaMer0n @Moc On line 1926 (lancheck.php), the string from the language file get's malformed for some reason.
I think it's because of the regex used to extract the define values.

**Comment by yesszus** [comment]
Solved problem!
Great job  @SimSync !

**Comment by tgtje** [comment]
Just to confirm it does work here too 👍 (all  (81) errors are gone.. (Hungarian)

**Comment by CaMer0n** [comment]
Thank you @SimSync @Moc 
We should add that test code into e107-tests

**Comment by SimSync** [comment]
@CaMer0n Could you provide the test class for lancheck.php? I will add than the tests

**Comment by CaMer0n** [comment]
@SimSync Done!
