### ISSUE TITLE
Lan issue with log plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3634]
Today update 

/e107_plugins/log/stats.php?1

![image](https://user-images.githubusercontent.com/5429548/51498977-d5d9db80-1dc8-11e9-89c4-77ab61f07455.png)

After set debug ON  (in Chrome browser)
/e107_plugins/log/stats.php?[debug=showsql+]&1
![image](https://user-images.githubusercontent.com/5429548/51499023-00c42f80-1dc9-11e9-9d1a-27720cc43bd5.png)

It is fixed after changing url without debug parameters, but weird thing is that LAN is changing.

**Comment by SimSync** [comment]
The used url is wrong. Use `/e107_plugins/log/stats.php?[debug=showsql+]1` (without the ampersand after the debug argument) to correctly select the stats area.

**Comment by Jimmi08** [comment]
> The used url is wrong. Use `/e107_plugins/log/stats.php?[debug=showsql+]1` (without the ampersand after the debug argument) to correctly select the stats area.

It's added by e107 debugger, I didn't do it manually. Yes. It helped.

**Comment by Moc** [comment]
Going to close as invalid. Needs a bug report for the debugger addon though.
