### ISSUE TITLE
theme_shortcodes from frontend are loaded in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3635]
I needed to require custom file in theme_shortcodes.php in frontend theme. 
But then I got error in admin area and system is trying to require:
`Fatal error: require(): Failed opening required '../e107_themes/bootstrap3/settings/jmtheme_icons.php`

of course, that file doesn't exist. 

In Frontend theme it is used this way:

```
require_once(THEME."settings/jmtheme_icons.php");
 
class theme_shortcodes extends e_shortcode
{
```

Thanks

Edit.  
While trying go around this by testing if it's user area, I got error (correct error, file wasn't included)
`Fatal error:  **** not found in ***\e107_themes\material\theme_shortcodes.php on line 22`
so later is loaded class  theme_shortcodes  from frontend theme

php  7.2 latest github

**Comment by SimSync** [comment]
To test if you are in the user (frontend) area, try this:
```
if (USER_AREA){
    require_once(THEME."settings/jmtheme_icons.php");
}
```
This should avoid to load the file when in admin area.

**Comment by Jimmi08** [comment]
I tried,  then I get fatal error because theme_shortcodes.php needed this file.  See above.  

But I think that USER_AREA was not defined,  if I used print_a(), then USER_AREA was printed. Maybe 7.2 problem?

I fixed it different way (loading file in __construct() and using arrays.  But this is at least wasting of sources. Why frontend theme is loaded in admin at all?

**Comment by CaMer0n** [comment]
@Jimmi08 `print_a` is short for "print array". `var_dump(USER_AREA)` is what you want to use.

**Comment by SimSync** [comment]
Hmm, the constand "USER_AREA" seams not to be defined when in "ADMIN_AREA".
Try using the "deftrue()" method to test if the constant is defined and has a value.

```
if (deftrue("USER_AREA")){
    require_once(THEME."settings/jmtheme_icons.php");
}
```

**Comment by SimSync** [comment]
@Jimmi08 did you try my last proposal or did you find another solution?

**Comment by Jimmi08** [comment]
@SimSync sorry, I am not able to test this anymore.  You can close it if this is not an important issue.

**Comment by SimSync** [comment]
@Jimmi08 I'm not able to close this issue. But you could. 😄
