### ISSUE TITLE
country type field

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3644]
I have plugin with country field, but this field is not mandatory

```
	'team_country'            => array (  'title' => _WCOUNTRY,  'type' => 'country',  
      'data' => 'str',  'width' => 'auto',  'batch' => true,  
      'filter' => true,  'help' => '',  'readParms' =>  array (),  
      'writeParms' =>  array (),  'class' => 'left',  
      'thclass' => 'left',),
```
Edit mode is OK:
![image](https://user-images.githubusercontent.com/5429548/51705199-3c563800-201b-11e9-99bf-e707d4b2ffc6.png)

But edit mode, if country is not selected
![image](https://user-images.githubusercontent.com/5429548/51705253-66a7f580-201b-11e9-8c6e-14858bb66506.png)

I suppose I missed something in field array. Thanks for help.

**Comment by Moc** [comment]
@Jimmi08 what happens when you leave readParms and writeParms empty?

**Comment by Jimmi08** [comment]
php 7.1

```
'team_country'            => array (  'title' => _WCOUNTRY,  'type' => 'country',  
      'data' => 'str',  'width' => 'auto',  'batch' => true,  
      'filter' => true,  'help' => '',     'class' => 'left',  
      'thclass' => 'left',),
```
the same result 

tried:   'writeParms' =>  array ('default'=>''),

**Comment by SimSync** [comment]
This is how we did it in th vstore plugin:

`'cust_country' =>   array ( 'title' => 'Country', 'tab' => 0, 'type' => 'method', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => '', 'writeParms' => '', 'class' => 'center', 'thclass' => 'center',  ),`

And that is the method that is used to fill the country select and to display the countryname in the list instead of the country iso code:

```
function cust_country($curVal,$mode)
	{
		$frm = e107::getForm();		
		 		
		switch($mode)
		{
			case 'read': // List Page
				return  $this->getCountry($curVal);
			break;
			
			case 'write': // Edit Page
				return $frm->country('cust_country', $curVal);
			break;
			
			case 'filter':
			case 'batch':
				return  null;
			break;
		}
```

**Comment by CaMer0n** [comment]
Normally a custom method should no longer be required since `type='country'` was introduced.

**Comment by Moc** [comment]
So, then there apparently is an issue with `type='country'` returning array in read mode.

**Comment by CaMer0n** [comment]
Fixed. getCountry() needed some tweaking.
