### ISSUE TITLE
country type user extended field is not correctly displayed in user profile

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3646]
This returns correct country name:
`e107::getForm()->getCountry($opp_country);`

But user profile displays country code, not country name

![image](https://user-images.githubusercontent.com/5429548/51769802-3aa47700-20e4-11e9-85cb-fb77d53e0d78.png)

**Comment by Jimmi08** [comment]
I noticed that if country code is wrong, array of countries is returned.
```
        if(!empty($iso) && !empty($c[$iso]))
        {
            return $c[$iso];
        }
```
I think that if $iso is filled, but value doesn't exist, it should return "" not array. 
If I want country list, it's easy without parameter.

**Comment by CaMer0n** [comment]
@Jimmi08 pull-request welcome.

**Comment by Moc** [comment]
Fixed. 

I didn't change the default output of an array if the iso code is not found, because I was afraid of breaking functionality. Not quite sure if that array output is used somewhere.

**Comment by CaMer0n** [comment]
@Jimmi08 @Moc I believe this has been fixed now in the getCountry() method.
