### ISSUE TITLE
Note - db_Delete()/delete() inside db_Fetch() causes Fatal Error in php 7.1 and 7.2 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3649]
Code is working in php 5.6 

this example:
$sql->db_Delete("clan_wars_lineup", "available='0' and wid='$clwid'");
causes 
`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error in G:\php72\htdocs\e107-fresh\e107_handlers\mysql_class.php:1555 Stack trace: #0 G:\php72\htdocs\e107-fresh\e107_handlers\mysql_class.php(1555): PDOStatement->fetch(2) #1 G:\php72\htdocs\e107-fresh\e107_handlers\mysql_class.php(1573): e_db_mysql->fetch(2) #2 G:\php72\htdocs\e107-fresh\e107_plugins\clanwars\clanwars.php(54): e_db_mysql->db_Fetch() #3 {main} thrown in G:\php72\htdocs\e107-fresh\e107_handlers\mysql_class.php on line 1555`

Full code:
```
$sql->db_Select("clan_wars");    
	while($clrow = $sql->db_Fetch()){
		$clwid = $clrow['wid'];     
		if($clrow['status']){
  		$sql->db_Delete("clan_wars_lineup", "available='0' and wid='$clwid'");
 		  $sql->db_Update("clan_wars_lineup", "available='2' where available='1' and wid='$clwid'");
		}else{     
			$sql->db_Update("clan_wars_lineup", "available='1' where available='2' and wid='$clwid'"); 
		}    
	}
``` 

Adding $sql = e107::getDB(); didn't help, replace with names neither. 
Fix was to replace select() +  fetch() by retrieve().

**Comment by CaMer0n** [comment]
PDO doesn't like that old code. Some plugins will need to be upgraded to work with PHP 7.

**Comment by Jimmi08** [comment]
Yes, I know, - it's reason why I marked it as Note. I don't need to fix this, it's just more as info for others.

**Comment by Moc** [comment]
Labelled as documentation. Closing as there is nothing be fixed.
