### ISSUE TITLE
Filetypes.xml not loaded correctly 

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#3655]
Clean install 

Admin area debug on first login:
`Setting default filetypes: zip, gz, jpg, png, gif, pdf`

e107_system/*hash*/filetypes.xml is accessible:

```
<?xml version="1.0" encoding="utf-8"?>
<e107Filetypes>
	<class name="253" type="zip,gz,jpg,jpeg,png,gif,xml,pdf" maxupload="2M" />
</e107Filetypes>
```

It does not load the filetypes.xml but it loads the defaults as defined here:
https://github.com/e107inc/e107/blob/dbbfe17e9f5d4bcb4281d8271c26afdb35727ca8/e107_admin/admin.php#L652

@CaMer0n  Shouldn't it load the filetypes.xml instead? 

Perhaps related: #550 #959

**Comment by CaMer0n** [comment]
@Moc I believe this may be caused by the order in which these checks are run.

**Comment by Evgura** [comment]
Confirm.

**Comment by Moc** [comment]
Issue is fixed now with the latest files.

Still open issue with `plupload` (media manager upload modal) not recognizing the filetypes.xml. See #550. 
Closing this one.
