### ISSUE TITLE
PHP 7.3 compatibility fixes 

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#3668]
This issue acts as a reminder for after the 2.2.0 release

https://wiki.php.net/rfc/continue_on_switch_deprecation

Examples:
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?, Line 2637 of ../e107_handlers/theme_handler.php

**Comment by Moc** [comment]
https://e107help.org/4588/e107-web-site-does-not-work-with-php-7-3-3

**Comment by CaMer0n** [comment]
@Moc I haven't encountered any issues recently. (other than PHP notices) Have you?

**Comment by Moc** [comment]
The one in theme_handler seems fixed. I do notice this one: 
`Warning "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?, Line /e107_handlers/admin_ui.php`

**Comment by CaMer0n** [comment]
@Moc Thanks. Yeah, I've been putting that one off until after 2.2.0 (now 2.2.1)

**Comment by CaMer0n** [comment]
@Moc I believe this one was fixed. Closing, but please re-open if necessary.
