### ISSUE TITLE
no Pm menu

### ISSUE THREAD

**Issue by Bobbycharlton1** [e107inc/e107#3670]
i have a theme called basic-light which I downloaded from the theme area

however, when I install the PM menu from the menu manager, no PM options appear so I can not access any PM functions

**Comment by tgtje** [comment]
Not replicable.
Fresh installment; added Basic-light; installed pm
Placed pm in area 1 
MIND !!! what are your settings (pm prefs) for who may see/use it ??? 
![basicl](https://user-images.githubusercontent.com/1811857/52585940-76567500-2e36-11e9-906f-1dba0bdf6415.jpg)

**Comment by Bobbycharlton1** [comment]
my settings seemed ok.  but I had tagged useage into a custom userclass.  see my other issue #3657

it seems when my site reset everyone to default user class, it also removed the PM menu. I had to change use in the settings to standard 'member' save it, then change back to my custom userclass and now it is working again

**Comment by Moc** [comment]
> I had to change use in the settings to standard 'member' save it,

Do you mean that the "Restrict PM use to" setting (see screenshow below) changed after the issue with the userclasses happened? 
![image](https://user-images.githubusercontent.com/577978/52665988-4a59f300-2f0d-11e9-9372-3db662bbf0da.png)
