### ISSUE TITLE
Issue with text being squashed up

### ISSUE THREAD

**Issue by wrxxy** [e107inc/e107#3675]
Hi all since the new updates 2.1.9 I have been having Issues with my old V1 updated website with text being squashed up now Jimmi has been implementing a fix for me every time we do an update , however the last update this fix didn't work and I had other issues so I have resorted to [br] in each line to fix it....

Below are some images of my issue and some coding for the fix
![image](https://user-images.githubusercontent.com/13065217/52786169-4addbf80-30ae-11e9-9dfa-e6cb889cbf87.png)

here is a before shot
![image](https://user-images.githubusercontent.com/13065217/52786225-7365b980-30ae-11e9-9088-e8eddeeb6c82.png)
and here is an aftershot with our fix
![image](https://user-images.githubusercontent.com/13065217/52786271-942e0f00-30ae-11e9-85b9-a399592fcf2d.png)
And here is a sample of the coding fix in order to space it out correctly...
![image](https://user-images.githubusercontent.com/13065217/52786374-ca6b8e80-30ae-11e9-957f-20a8d038e49f.png)

**Comment by CaMer0n** [comment]
@wrxxy Could you please paste a sample of a post that has this issue. (unmodified with [br] of course). 
Please paste the entire text in the text area here. Thank you.

**Comment by wrxxy** [comment]
Ok here is an example 

http://www.outlawsracing.com/forum/rsm-v8-championship/10331/outlaws-2018-vasc-championship/

![image](https://user-images.githubusercontent.com/13065217/52931005-d8ffc180-339e-11e9-85c4-304eb96f1ecf.png)



[center][img:width=700&height=175]{e_FILE}public/1519825158_12_FT9705_2018v8rsm.png[/img][/center]

[center][size=24][b][color=#ffff99]Outlaws 2018 Supercars Championship.[/color][/b]

Welcome to the 2018 Outlaws Supercars Championship.

This season starts 7th March using the RSMV8 mod, and follows the championship on the Wednesday following the action. Endurance Races will be contested the Saturday following.

Races will be held at half distance, for the same number of races that weekend, excepting Enduros. Enduros (Sandown 500/Bathurst 1000) will be held at full distance with driver swaps. Qualifying will be a single flying lap, and reverse top 10 from the previous race for the 2nd/3rd races.

Points will be awarded by finishing position, with 1st earning 25, 2nd = 24, 3rd = 23 continued to 25th = 1. Dropping your worst 2 rounds. Points kept here as backup https://docs.google.com/spreadsheets/d/1hxpLYUFpsNv9jgmBURHWHdCgEyynBie7-7GwHmXhq9s/edit?usp=sharing


Usual Rules apply as per Outlaws Server Rules[/size][/center]



[center][size=22][color=#00ff33]All drivers must be on team speak, or no race.[/color]

[color=#ff0000]Team Speak IP 103.192.173.112
Team Speak P/W ouTLawS[/color][/size][/center]

[center][size=22][color=#00cc00]Checkout the [link=http://www.outlawsracing.com/e107_plugins/forum/forum_viewtopic.php?4290.last][size=22]Server Rules[/size][/link] so you don't get pinged at the end of the race[/color][/size][/center]


[center][size=28][color=#00ff00]CLEAN RACER[/color][/size][/center]
[center][size=18]A rating of [color=#ffff00]EXCELLENT RACE[/color] will get you [color=#ffff00]2 points[/color], to get this rating you have to have no infringements for that race.

A rating of [color=#00ff00]PERFECT RACE[/color] will get you [color=#00ff00]5 points[/color], to get this rating you have to have no infringements and no contact with anything or anyone that is your fault.[/size]

[size=22]If you get 2 or more perfect races, you will get a tag in your signature saying [color=#00ff00]CLEAN RACER[/color]. If you get the most points over the year of Outlaws events you also get, your car in the BANNER the next year and [color=#cc3300]$100[/color], 2nd [color=#cc3300]$50[/color] and 3rd [color=#cc3300]$25[/color].[/size]
[/center]
[center][size=30]Supercars 2018 Sim-Season[/size][/center]
[center][size=26][color=#00ffff]Round 1 - [color=#ffff00]Adelaide[/color] - 7th March [color=#ff0000][/color] [size=24][color=#ffff00]COMPLETED[/color][/size]
Round 2 - [color=#ffff00]Melbourne[/color] - 28th March [color=#ffff00][/color] [size=24][color=#ffff00]COMPLETED[/color][/size]
Round 3 - [color=#ffff00]Symmons Plains[/color] - 11th April [color=#ffff00][/color] [size=24][color=#ffff00]COMPLETED[/color][/size]
Round 4 - [color=#ffff00]Phillip Island[/color] - 25th April [color=#ffff00][/color]
Round 5 - [color=#ffff00]Barbagallo[/color] - 9th May [color=#ffff00][/color]
Round 6 - [color=#ffff00]Winton[/color] - 23rd May [color=#ffff00][/color]
Round 7 - [color=#ffff00]Hidden Valley[/color] - 20th June [color=#ffff00][/color]
Round 8 - [color=#ffff00]Townsville[/color] - 11th July [color=#ffff00][/color]
Round 9 - [color=#ffff00]Queensland[/color] - 25th July [color=#ffff00][/color]
Round 10 - [color=#ffff00]Eastern Creek[/color] - 5th August [color=#ffff00][/color]
Round 11 - [color=#ffff00]The Bend (TBC)[/color] - 29th August [color=#ffff00][/color]
Round 12 - [color=#ffff00]Sandown 500[/color] - 22nd September (Saturday Special Event)[color=#ffff00][/color]
Round 13 - [color=#ffff00]Bathurst 1000[/color] - 13th October (Saturday Special Event)[color=#ffff00][/color]
Round 14 - [color=#ffff00]Gold Coast[/color] - 24th October [color=#ffff00][/color]
Round 15 - [color=#ffff00]Pukekohe[/color] - 7th November [color=#ffff00][/color]
Round 16 - [color=#ffff00]Newcastle[/color] - 28th November [color=#ffff00][/color][/color][/size][/center]

[size=24][color=#ff0000]INFORMATION[/color][/size]
[size=18]Mod: RSMV8[/size]
[size=18][color=#00cc00] Vehicle Class: [color=#cc66ff]Virgin Australia Supercars[/color]  
 Date: [color=#ffff00]First Round 7th March[/color] 
 Official Start time: [color=#ffff00]6pm[/color]
 Qualifying Time: [color=#ffff00]8:00pm[/color]
 Race Start: [color=#ffff00]8:15pm[/color]
 Matchmaker Listing: [color=#ffff00]OutlawsRacing VASC2018[/color]
 Session Password: [color=#ff0000]raceday[/color][/color][/size]
 
[size=24][color=#ff0000]RACE FORMAT[/color][/size]

 [size=18][color=#00cc00] Practice: [color=#ffff00]Any Time You Want[/color]
 Qualifying Format: [color=#ffff00]5 minutes, Closed 1 Lap flier[/color]
 Warm-up: [color=#ffff00]5 Minutes[/color]
 Race: [color=#ffff00]1/2 Real Race Distance[/color]
 Pit Stops: [color=#ffff00]More than likely[/color]
 Start Type: [color=#ffff00]Standing[/color]
 Tyre Wear: [color=#ffff00]1x[/color]
 Fuel Burn: [color=#ffff00]2x[/color]
 Virtual Start Time: [color=#ffff00]2 PM[/color]
 Time Multiplier: [color=#ffff00]Normal[/color]
 Race Flags: [color=#ffff00]Black Only[/color]
 Mechanical Failures: [color=#ffff00]Time Scaled[/color]
 Damage: [color=#ffff00]50%[/color]
 Setups: [color=#ffff00]Open[/color]
 Driving Aids: [color=#ffff00]Auto Clutch[/color] [/color][/size]

[center]=================================
=================================[/center]
[center]<b><a href="http://www.outlawsracing.com/e107_plugins/pm/pm.php?send.9"title="INCIDENT REPORT" target="_blank">[img]{e_IMAGE}custom/Traffic_Logo_100x100.png[/img]</a></b>[/center]
[center]=================================
=================================[/center]

[center][size=30]Please Register Below[/size][/center]

**Comment by CaMer0n** [comment]
@wrxxy I believe this is your problem here: 

```
[center]<a href="[http://www.outlawsracing.com/e107_plugins/pm/pm.php?send.9"title="INCIDENT](http://www.outlawsracing.com/e107_plugins/pm/pm.php?send.9%22title=%22INCIDENT) REPORT" target="_blank">[img]{e_IMAGE}custom/Traffic_Logo_100x100.png[/img][/center]
```

Replace the `<a href=''` HTML line with the [link] bbcode.

**Comment by wrxxy** [comment]
Yes this has done the trick. Just had to workout what the exact code required now all good...

Thx Cameron.

**Comment by CaMer0n** [comment]
Happy it worked out @wrxxy . Basically, e107 checks for HTML and if found, it ignores line breaks unless they are specified using `<br />` tags.
