### ISSUE TITLE
not able to copy forum 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3678]
It's because unique  key 'forum_sef'  

```
System Debug
Searching for custom batch method: handleListCopyBatch(Array,)
SQL Error #23000: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '***' for key 'forum_sef'
```

**Comment by CaMer0n** [comment]
Once we switch to the new e_db_pdo_class, this should be fixed.

**Comment by Moc** [comment]
@Jimmi08 This is fixed for me, can you confirm with the latest files?

**Comment by Jimmi08** [comment]
Latest github

```
QRY=SELECT a. *, CASE WHEN a.forum_parent = 0 THEN a.forum_order ELSE b.forum_order + (( a.forum_order)/1000) END AS Sort FROM `e107_forum` AS a LEFT JOIN `e107_forum` AS b ON a.forum_parent = b.forum_id ORDER BY Sort,forum_order LIMIT 0, 30
Searching for custom batch method: handleListCopyBatch(Array,)
SQL Error #23000: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rand-867' for key 'forum_sef'
$SQL Query
```

You can copy it one by one. but as soon as marked 2 forums, you got SQL error.

**Comment by Deltik** [comment]
The duplicate key avoidance implementation from b2fffa7838e7e3a1c46ad17e683cfcda6bf1f603 gets less reliable the more copies are made.  ([More details](https://github.com/e107inc/e107/commit/b2fffa7838e7e3a1c46ad17e683cfcda6bf1f603#r36553019))

**Comment by Deltik** [comment]
[The hypothesized bug](https://github.com/e107inc/e107/issues/3678#issuecomment-568534184) was observed during testing:
```
---------
1) e_db_pdoTest: Db_copy row unique
 Test  tests/unit/e_db_pdoTest.php:testDb_CopyRowUnique
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rand-445' for key 'media_cat_category'
Failed asserting that false is greater than 1.
#1  /__w/e107/e107/e107_tests/tests/unit/e_db_pdoTest.php:119
```

In the above test, the number `445` was generated twice in a row.

The unique value randomization must be reimplemented.

**Comment by Deltik** [comment]
@CaMer0n: Commit [fabb0c27571a3d887e45b5917cff269a5e167446](https://github.com/e107inc/e107/commit/fabb0c27571a3d887e45b5917cff269a5e167446?w=1) changes the ≈ <sup>x</sup>/<sub>1000</sub> collision chance to ≈ <sup>x</sup>/<sub>59<sup>11</sup></sub> (≈ <sup>x</sup>/<sub>30,155,888,444,737,842,659</sub>) by replacing `rand(0,999)` with <code>e107::getUserSession()->generateRandomString('***********')</code>.

Even if a collision happens, the copy will be retried two more times with a new kinda-random string before giving up.

Tests have also been written to [simulate collisions](https://github.com/e107inc/e107/commit/fabb0c27571a3d887e45b5917cff269a5e167446?w=1#diff-11ba6376e0f6647717c5b2c17f85c27fR122) and [simulate a broken random number generator](https://github.com/e107inc/e107/commit/fabb0c27571a3d887e45b5917cff269a5e167446?w=1#diff-11ba6376e0f6647717c5b2c17f85c27fR149).

[![Dilbert 2001-10-25](https://user-images.githubusercontent.com/1364268/71532669-4b87da80-28a9-11ea-8192-81a128f04525.png)](https://dilbert.com/strip/2001-10-25)
