### ISSUE TITLE
Epson Printer Error Code 0x9d

### ISSUE THREAD

**Issue by lj962500** [e107inc/e107#3679]
Sometimes you may face printer issue due to some ransomware attacks. When you are trying to print something it displays a message an Epson Printer Error Code 0x9d message on your computer's screen. If this is happening with you then follow this quick fixes from this link [Easy Steps To Fix Epson Printer Error Code 0x9d](https://errorcode0x.com/fix-epson-printer-error-code-0x9d/) and get rid of the problem within a short span of time.

**Comment by Evgura** [comment]
Spam?

**Comment by tgtje** [comment]
Yes Evgura, quite a busy one it seems. Well if you like...click his profile > under the user's profile picture, click Block or report user  ( or just wait... it ( issue) will suddenly disappear ;-) ) hihi
