### ISSUE TITLE
Comment turned off

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#3680]
If I turned off the comment (cpage) the comment turned off message not appears ("comment rurned off for this item").

**Comment by Moc** [comment]
@fizi Which LAN is supposed to display? I can only find LAN_THEME_1 which is specific to the _blank theme

**Comment by fizi** [comment]
If I disable the comment example on the nesw item - "Comments are locked" - not appears the text on the News. If I enable the comment the number of comments appears.

**Comment by Moc** [comment]
I found the reason why, but question (perhaps also for @Jimmi08): when comments on news items are disabled, do you really want to show the text that comments are locked? I can make it like this for example:

![image](https://user-images.githubusercontent.com/577978/65438957-b4813180-de26-11e9-8744-f1c65cbe00e1.png)

and for non-bootstrap:
![image](https://user-images.githubusercontent.com/577978/65438990-c367e400-de26-11e9-9c20-2264f5e252f5.png)


BUT, I can also imagine that you may want to display nothing at all... Ideally, this should be defined by templating but as far as I can see, this method is called anyway regardless of the template.

**Comment by Moc** [comment]
For custom pages. It can be controlled through templating. 
I guess we need to modify the news template to do the same thing, so the display of the locked message can be controlled by the template. 

Do you agree? @fizi @Jimmi08

**Comment by Jimmi08** [comment]
@Moc 
The correct solution for me (it doesn't mean it's good):

- new post/page - comments  OFF, no message
- post with comments, then you set comment OFF, message - commenting was set off. 

OR

Allow users to post comments NO -   no message  (general off, commenting is not available)
Allow users to post comments YES - message, if commenting  is set off.

I have no idea (no tested) what happens if there are already comments and you change post/page settings.

**Comment by Moc** [comment]
@Jimmi08 Yeah I would agree with your second option. I am not a fan of option 1 because it would require storing the 'history' of news items.

**Comment by fizi** [comment]
I test it...the shortcode [code]{NEWSCOMMENTS}[/code] on/off with text work on News page but not work on extend news.

**Comment by Moc** [comment]
Done. Please test and let me know if this is how you want it.

**Comment by fizi** [comment]
I tested it but… if the comments disabled the text appears on the News page (see it)
![news1](https://user-images.githubusercontent.com/86780/66058206-3f0a1500-e53a-11e9-98fd-9a21bf95701c.jpg)
but not appears on the extend news page (see it)
![extend_news1](https://user-images.githubusercontent.com/86780/66058250-53e6a880-e53a-11e9-8171-8e0e9c2b302e.jpg)

**Comment by Moc** [comment]
@fizi Well this doesn't look good haha. Which theme are you using in the screenshot? What is the shortcode that is used in the news template to display that bit that you circled?

**Comment by Moc** [comment]
I see this is your own theme. Does it use a custom news template? If yes, can you share that news template code with me please? You can send it by email or on Gitter.

**Comment by Moc** [comment]
@fizi can you please give me some feedback on this? :) What is the shortcode that is used to display the text that you circled in your screenshot?

**Comment by fizi** [comment]
I use [code]{NEWSCOMMENTS}[/code] shortcode.

**Comment by Moc** [comment]
@fizi I cannot reproduce this at all. The {NEWSCOMMENTS} will output ''Disabled" when the comments are disabled.  I do not see why it would output "Comments are turned off for this item" in that place. 

What are your settings for:
- "Allow users to post comments" in the Comments manager.
- News item "Free theme - BS Gaming 03" > Advanced options > Comments

**Comment by Moc** [comment]
@fizi Do you still experience this issue with the latest files?

**Comment by Moc** [comment]
Reminder: add pref to enable/disable showing the comments locked message

**Comment by Jimmi08** [comment]
@Moc 
for pages there is no scenario when you want to displays this message. Either it is standalone page and you don't want comments at all or you want comments and you set them on.

It is something different than for news. 

So part solution is changing only cpagecomments() for now.
```
	// Not a shortcode really, as it shouldn't be cached at all :/
	function cpagecomments()
	{
		$com 		= $this->var['comments'];
		$comflag 	= $this->var['page_comment_flag'];
 
		//if($parm && isset($com[$parm])) return $com[$parm];
		if($comflag)
		{
			return e107::getComment()->parseLayout($com['comment'],$com['comment_form'],$com['moderate']);	
		}
        else return '';
		
	//	return $com['comment'].$com['moderate'].$com['comment_form'];
	}
```

**Comment by Moc** [comment]
Reminder. Make this a debug message.

**Comment by Moc** [comment]
> Reminder: add pref to enable/disable showing the comments locked message. Or debug message? Admin only?

Changed the message to a debug message which is shown to admins only. 

I think this issue can now be closed. Please let me know if there are any questions or suggestions related to this issue. 

@fizi If you can still reproduce the issue you posted in your screenshot, let me know and I'll figure it out.

**Comment by Jimmi08** [comment]
@Moc Why don't you test e_DEBUG?  It is annoying for admins too...

**Comment by Moc** [comment]
It should only display when debug mode is enabled (because of `e107::getMessage()->addDebug()`). 

It may occur on non-bootstrap themes though, you have point there.

**Comment by Moc** [comment]
Done

**Comment by Jimmi08** [comment]
@Moc 
Could you or somebody check/test condition in  function cpagecomments() ?

there is code for comments off:

`if(e107::getPref('comments_disabled') == 0 && !$comflag)`

but comment_class uses (for not to display comment form)

```
		if(isset($pref['comments_disabled']) && $pref['comments_disabled'] == TRUE)
		{
			
        	return FALSE;
		}
```

It could be confusing because comment manager uses this in inverse way...

That shortcode should maybe look like this:

```
	function cpagecomments()
	{
		$com 		= $this->var['comments'];
		$comflag 	= $this->var['page_comment_flag'];
 
        if(isset(e107::getPref('comments_disabled')) && e107::getPref('comments_disabled') == TRUE) {
            return '';
        }
 
		if($comflag)
		{
			return e107::getComment()->parseLayout($com['comment'],$com['comment_form'],$com['moderate']);	
		}
        else {
        
            if(ADMIN && deftrue('e_DEBUG'))
  			{
  				if(defined('BOOTSTRAP') && BOOTSTRAP)
  				{
  					return e107::getMessage()->addDebug(LAN_PAGE_17)->render(); 
  				}
  				else
  				{
  					return "<br /><div style='text-align:center'><b>".LAN_PAGE_17."</b></div>";
  				}
  			}
        }
		
	//	return $com['comment'].$com['moderate'].$com['comment_form'];
	}
```

Or like with news (there is different logic/order of checks)
```
// Only show message if global comments are enabled, but current news item comments are disabled
if(e107::getPref('comments_disabled') == 0 && $news['news_allow_comments'] == 1)
```
