### ISSUE TITLE
online tracking turned off vs online menu

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3681]
If you turn online tracking off and forget to remove the online menu, the result is this:

![image](https://user-images.githubusercontent.com/5429548/52974578-5983e980-33c2-11e9-991e-e4b0c5196b96.png)

There should be a similar message like with stats plugin at least for main admin that tracking is off and for others, this shouldn't be displayed at all.

**Comment by Moc** [comment]
The code for this is already there, but not working because `e_TRACKING_DISABLED` is not defined properly in the `goOnline()` method in online_class.php.

Working on it.

**Comment by Moc** [comment]
@CaMer0n 

This check in class2.php is not triggered for me:

```
if(!isset($_E107['no_online']) && varset($pref['track_online']))
{
	e107::getOnline()->goOnline($pref['track_online'], $pref['flood_protect']);
}
```

It's because `varset($pref['track_online'])` returns false, because it is 0 when disabled

Now, another issue is the flood_protect pref. It seems this pref is not used at all but instead: 
`define("PRFLAN_35", "Enable flood protection?");` is used for the pref `antiflood1`. 

I propose changing 
```php
if(!isset($_E107['no_online']) && varset($pref['track_online']))
{
	e107::getOnline()->goOnline($pref['track_online'], $pref['flood_protect']);
}
```
to
if(!isset($_E107['no_online']))
{
	e107::getOnline()->goOnline($pref['track_online'], $pref['antiflood1']);
}

or use the constant `FLOODPROTECT` which seems to be defined earlier. 

Now a last issue in online_class.php is this:
```php
	if($online_tracking === false && $flood_control === false)
		{
			define('e_TRACKING_DISABLED', true);		// Used in forum, online menu
			...
``` 

This means that aside from changing the preference 'Enable online user tracking` (`track_online`), one ALSO has to disable to flood protection. Is this really needed? 

As these are pretty important defines and methods in class2.php I am not changing it myself...

**Comment by Moc** [comment]
Looking at this commit https://github.com/e107inc/e107/commit/d5711fd325ea5c8b193c948931e6c0df3d04f69f

This 
```php
if($online_tracking || $flood_control)
```


was replaced with:
```php
if($online_tracking === false && $flood_control === false)
```
I'm guessing it should be || (OR) not && (AND)

**Comment by CaMer0n** [comment]
@Moc I believe you're correct.

**Comment by Moc** [comment]
@CaMer0n @Deltik Do you foresee any negative effects when applying the 3 changes I listed above?

**Comment by Deltik** [comment]
Looks good to me.  I was curious about why there are two different variables for flood protection (`flood_protect` and `antiflood1`).

`flood_protect` has been a pref since before 02 October 2002 (release version 0.5.4), before [any releases available on SourceForge](https://sourceforge.net/projects/e107/files/e107/).

`antiflood1` was introduced on 08 July 2004 by loloirie, apparently as a replacement for `flood_protect`:

```diff
$ git show 19468aec78
commit 19468aec789ded31d397796f045803c0eb14509b (HEAD)
Author: loloirie <loloirie@8cb2f43a-d3f2-4d94-9ba2-05e386d4b0b9>
Date:   Thu Jul 8 15:55:16 2004 +0000

    Use prefs for antiflood (antiflood func) and autoban (online func) and cleaned for old flood prefs

diff --git a/e107/class2.php b/e107/class2.php
index 86aad3cab..ef4b816f1 100644
--- a/e107/class2.php
+++ b/e107/class2.php
@@ -342,8 +342,8 @@ if(e_QUERY == "logout"){
 ban();
 
 define("TIMEOFFSET", $pref['time_offset']);
-define("FLOODTIME", $pref['flood_time']);
-define("FLOODHITS", $pref['flood_hits']);
+//define("FLOODTIME", $pref['flood_time']);
+//define("FLOODHITS", $pref['flood_hits']);
 
 if(strstr(e_SELF, $ADMIN_DIRECTORY) && $pref['admintheme'] && !$_POST['sitetheme']){
         if(strstr(e_SELF, "menus.php")){
@@ -365,7 +365,8 @@ if(strstr(e_SELF, $ADMIN_DIRECTORY) && $pref['admintheme'] && !$_POST['sitetheme
 
 if($pref['anon_post'] ? define("ANON", TRUE) : define("ANON", FALSE));
 if(Empty($pref['newsposts']) ? define("ITEMVIEW", 15) : define("ITEMVIEW", $pref['newsposts']));
-if($pref['flood_protect']){  define(FLOODPROTECT, TRUE); define(FLOODTIMEOUT, $pref['flood_timeout']); }
+
+if($pref['$antiflood1']==1){  define(FLOODPROTECT, TRUE); define(FLOODTIMEOUT, $pref['antiflood_timeout']); }
 
 define ("HEADERF", e_THEME."templates/header".$layout.".php");
 define ("FOOTERF", e_THEME."templates/footer".$layout.".php");
@@ -884,7 +885,7 @@ function online(){
                 }
         }
 
-        if(ADMIN){$online_pagecount=1;}
+        if(ADMIN || $pref['autoban']!=1){$online_pagecount=1;}
         if($online_pagecount > $online_bancount && $online_ip !="127.0.0.1"){
                 $sql -> db_Insert("banlist", "'$ip', '0', 'Hit count exceeded ($online_pagecount requests within allotted time)' ");
                 exit;
@@ -955,7 +956,7 @@ class floodprotect{
                 # - scope                                        public
                 */
                 $sql = new db;
-                if(FLOODPROTECTION == TRUE){
+                if(FLOODPROTECT == TRUE){
                         $sql -> db_Select($table, "*", "ORDER BY ".$orderfield." DESC LIMIT 1", "no_where");
                         $row = $sql -> db_Fetch();
                         return ($row[$orderfield] > (time() - FLOODTIMEOUT) ? FALSE : TRUE);
```

Perhaps we should introduce a database migration that chooses one pref name and removes the other we don't want?

**Comment by Moc** [comment]
Done. This could use some testing. I hope no negative affects arise when it comes to flood protection and automated banning of those triggering the flood protection. 

The online menu menu now functions correctly. 

@CaMer0n The only thing that needs to be done I guess is removing the `flood_protect` pref which was not used anymore, like you said @Deltik. Where do we add such a routine?

**Comment by Deltik** [comment]
@Moc: In `e107_admin/update_routines.php`, most likely.  Do a check for the existence of the pref and then remove it if it is present.  I think perhaps like:

```php
if (e107::getConfig()->has('flood_protect'))
{
        if ($just_check)
        {
                return update_needed("Unused pref for flood protection");
        }
        else
        {
                e107::getConfig()->remove('flood_protect');
        }
}
```

**Comment by Moc** [comment]
@Deltik @CaMer0n I noticed `update_core_prefs()` in the upgrade routines: https://github.com/e107inc/e107/blob/618db455ec4bf2c58d1e428e920523b751572e9e/e107_admin/update_routines.php#L467

If I read it correctly, it will check for missing core prefs. Perhaps we expand this function to also delete core prefs that exist in the table, but are no longer present in the install.xml file (`get_default_prefs()`)
