### ISSUE TITLE
sitecontactinfo and contact form have the same style ID

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3684]
![image](https://user-images.githubusercontent.com/5429548/53093009-7b8e8080-3516-11e9-88a2-6f96650a087a.png)

```
$ns -> tablerender(LANCONTACT_01, $text,"contact");
$ns -> tablerender(LANCONTACT_02, $text, "contact");
```

could it be changed to contact-info ?
they use already different templates 

```
$CONTACT_TEMPLATE['info']
$CONTACT_WRAPPER['form']
```

Thanks

**Comment by Jimmi08** [comment]
Tablerender about successful email has no id:
At least "contact" would be nice.
	`$ns->tablerender('', "<div class='alert alert-success'>".$message."</div>");`

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/2980

**Comment by Moc** [comment]
@fizi @Jimmi08 

@CaMer0n and I were thinking to use three new ID's: `contact-info`, `contact-form`, `contact-menu`. This may some break existing themes but it will increase consistency and allow styling for all areas. What do you think?

**Comment by Jimmi08** [comment]
It would be great if it has some logic :
plugin and template key
yes, that suggestion is ok.  And yes, it will break some themes, but it can be easily fixed.   There should be a list of what to check when you update.

**Comment by fizi** [comment]
I agree with Jimmi08.

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 @fizi . 

Yes, I believe the correct logic for the render ID would be template name and template key. 

ie. 
```
$CONTACT_TEMPLATE['menu'] = contact-menu
$FORUM_VIEWTOPIC_TEMPLATE['replies']  = forum-viewtopic-replies
```

**Comment by Moc** [comment]
Updated contact. If you come across other inconsistencies then please list them here
