### ISSUE TITLE
Plugin Manager: Plugin Description is corrupted if there's a long discription and you click 'More'

### ISSUE THREAD

**Issue by jburns131** [e107inc/e107#369]
The string '...' stays in the description after you press more.

This is before clicking 'More'
![plugin_description_corruption_01](https://f.cloud.github.com/assets/1120974/595862/2114299e-cb3a-11e2-9323-bccb5b9eea42.png)

This is after clicking 'More'
![bbcode editing page buttons 02](https://f.cloud.github.com/assets/1120974/595861/21109f18-cb3a-11e2-9af5-4809ca5705d3.png)

**Comment by Moc** [comment]
@lonalore Would you mind taking a look at this issue when you have a spare few minutes? Much appreciated!

**Comment by lonalore** [comment]
Okay, I'll fix it tomorrow. :)

**Comment by lonalore** [comment]
Merged. Please test it... :)
It works fine for me.

**Comment by Moc** [comment]
Hmm for me, when using Chrome, the button does correctly expand and hide but the text stays 'More..'. When expanded, it should change to Less..

**Comment by lonalore** [comment]
I tested it with:
- Mozzilla Firefox for Linux v44.0.2
- Chrome v48.0.2564.109 (64-bit)
- IE 11

And it works properly. o.O 
Please clear your cache and try again. It should work.

**Comment by Moc** [comment]
I guess there was a caching issue indeed. It's working fine now. Thanks a lot.
