### ISSUE TITLE
FR - be able to add favicon via Prefs

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3692]
Now is the favicon hardcoded this way in header_template:

```
// ---------- Favicon ---------
if (file_exists(THEME."favicon.ico")) 
{
	echo "<link rel='icon' href='".THEME_ABS."favicon.ico' type='image/x-icon' />\n<link rel='shortcut icon' href='".THEME_ABS."favicon.ico' type='image/xicon' />\n";
}
elseif (file_exists(e_BASE."favicon.ico")) 
{
	echo "<link rel='icon' href='".SITEURL."favicon.ico' type='image/x-icon' />\n<link rel='shortcut icon' href='".SITEURL."favicon.ico' type='image/xicon' />\n";
}
```
With client without FTP access is not possible to change it.  And with theme it could be overriden with next update.

**Comment by rica-carv** [comment]
You can always drop a favicon inside a theme zip file, if you can upload a theme via admin area....

**Comment by Jimmi08** [comment]
> You can always drop a favicon inside a theme zip file, if you can upload a theme via admin area....

The user wants to change favicon yourself and one theme is used for more site. In fact favicons now works a bit different ways, not mention they can be not only .ico file.

**Comment by LaocheXe** [comment]
Well, using the site preferences > button as an example.

// for PNG
echo "<link rel='icon' href='"{SITEBUTTON}"' type='image/png' />\n<link rel='shortcut icon' href='"{SITEBUTTON}"' type='image/png' />\n";

of course the type would change to image/jpg, etc....

I don't know if {SITEBUTTON} is the correct shortcode (also, Site Button is used for Facebook, so maybe add a new section there to add favicon????)

**Comment by Jimmi08** [comment]
closing in favor
https://github.com/e107inc/e107/issues/4276
