### ISSUE TITLE
unserialize parse error 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3693]
After login as another user, I got the error:

![image](https://user-images.githubusercontent.com/5429548/53333976-b23e0f80-38f7-11e9-946c-71c0007025ab.png)

New latest e107 installation on php 7.0

**Comment by Evgura** [comment]
> After login as another user, I got the error:

@Jimmi08 If you log in as another user from the admin panel or from the site, I do not see such an error.

**Comment by Moc** [comment]
Cannot reproduce either here...  PHP 7.3.1.

**Comment by Jimmi08** [comment]
@Moc I know, it's something in data. I am not able to read/understand that parser error. Password was 12345678 and the user was added via Add quick user with Chrome  browser debug on.

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please copy/paste the `$data` part of the error in here. (Please be sure to use "Insert code" button above ie **<>** )  Thanks

**Comment by Jimmi08** [comment]
@CaMer0n 
Just happened on total new site, installed 2.1.9 by user version from e107.org, updated to 2.2.0 by me with git sync.  

```
$data = array (
  \'email_password\' => \'$2y$10$IpizFx.gp5USl98SLXwwbeod3SYF3M3raAQX0y01ETexzoutvdyWW\',
);
```

![image](https://user-images.githubusercontent.com/5429548/57613549-72420c80-7577-11e9-8248-621a66268282.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please paste here exactly what is in the user_password field for the user you tried to login as? (ie. You'll need to use Phpmyadmin)
