### ISSUE TITLE
Q - was something changed how e_admin works?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3695]
I have the plugin that extends pages.  It worked without problems some time already.
- tab is correctly displayed
- value is correctly rendered

 
![image](https://user-images.githubusercontent.com/5429548/53412976-239ac280-39cb-11e9-8545-4338b4d60f63.png)

But those fields can be displayed in listing form too now
![image](https://user-images.githubusercontent.com/5429548/53413070-5644bb00-39cb-11e9-9401-a7737ac365d0.png)
 but the value is not rendered correctly.
![image](https://user-images.githubusercontent.com/5429548/53413165-90ae5800-39cb-11e9-9fe2-d9cab4579946.png)

I checked _blank plugin, there is nothing about READ mode or how to not display those field on options.

**Comment by CaMer0n** [comment]
@Jimmi08 Is my simple canonical plugin still working for you? Nothing has changed as far as I now. Has your PHP version changed?

**Comment by Jimmi08** [comment]
@CaMer0n 
the same with your canonical plugin -  tested with news
![image](https://user-images.githubusercontent.com/5429548/53585680-c6e40700-3b86-11e9-90aa-f785a7a48b6d.png)

then I tried Reference plugin and the same problem
![image](https://user-images.githubusercontent.com/5429548/53585824-1aeeeb80-3b87-11e9-845d-3807c49d8623.png)

Now tested with php 7.2 , but original problem was with 5.6.

**Comment by CaMer0n** [comment]
@Jimmi08 Okay. Thank you!

**Comment by CaMer0n** [comment]
@Jimmi08 Did it work in 2.1.9 ?

**Comment by CaMer0n** [comment]
@Jimmi08 To summarize: The listing aspect of the e_admin addon was never implemented. This has now been added in the last commit. Please see the canonical plugin for a working example. (or _blank) 
btw. I don't foresee support for inline editing being added any time soon.

**Comment by Jimmi08** [comment]
@CaMer0n Thank you very much. I am sorry, but I didn't ask to add listing mode at all. What was changed was adding those fields to option values (and so the ability to display them).

**Comment by CaMer0n** [comment]
@Jimmi08 I have just updated e107's core again and updated the reference plugin. Custom 'read' method is now supported.
