### ISSUE TITLE
Fatal error:Uncaught Error: function getTimezone()

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3698]
Fatal error: Uncaught Error: Call to a member function getTimezone() on null in /usr/www/taskforce13tsw/501st/e107-test/class2.php:1925 Stack trace: #0 /usr/www/taskforce13tsw/501st/e107-test/class2.php(702): init_session() #1 /usr/www/taskforce13tsw/501st/e107-test/index.php(58): require_once('/usr/www/taskfo...') #2 {main} thrown in /usr/www/taskforce13tsw/501st/e107-test/class2.php on line 1925

**Comment by Moc** [comment]
PHP version please?

**Comment by Moc** [comment]
Also, it appears you are not using the latest files. Pease update to the latest version from Github to see if the issue is resolved.

**Comment by LaocheXe** [comment]
PHP Version 7.1.26

Odd - must have been a corrupted file from upload yesterday.
