### ISSUE TITLE
function makeClickable() deletes the whole message for forum/pm/chatbox/menu/...

### ISSUE THREAD

**Issue by phibel** [e107inc/e107#3699]
Since my upgraded to php 7.3.2, a few hours back, my e107 forum, private messages, chatbox and top-navigation menu are empty! I have done a little research and the function makeClickable() in e107_handlers/e_parse_class.php has a bug. When I remove the code from the function and return $text the forum/pm/menu are back (without clickable links), but the chatbox entries are still gone (another bug).

The preg_replace(...) functions seem to work different than before. http://php.net/manual/en/doc.changelog.php

I have fetched the latest version (53b9714e6b5bf8d4fd2f9957a710f5d35de1718f), but this does not help. At the moment I have no idea to fix this... the preg_replace lines are a little hardcore at 01:30 in the morning. gn8

**Comment by CaMer0n** [comment]
Thank you @phibel !! Will certainly look into it asap.

**Comment by CaMer0n** [comment]
@phibel This should be fixed, but if after updating e107 from Github the issue is not resolved, please re-open this issue. Thank you!
