### ISSUE TITLE
How to uninstal extension ?

### ISSUE THREAD

**Issue by Darkicross** [e107inc/e107#3700]
https://gyazo.com/544a4036154014fda2a92e2a1751f838

![image](https://user-images.githubusercontent.com/577978/53875538-fec6d080-4004-11e9-9f52-bd3c8911ac1f.png)

pls help

**Comment by Jimmi08** [comment]
Normally you would see this
![image](https://user-images.githubusercontent.com/5429548/53624352-4bbf3700-3c00-11e9-9859-b0f8e1c6d196.png)

Check your permissions maybe, switch to English in admin...  
With core plugin do you see uninstall buttons?

**Comment by Darkicross** [comment]
No plugins

Si extension

**Comment by Jimmi08** [comment]
Are you main admin?  Post here the full screenshot of your plugin manager.

**Comment by rica-carv** [comment]
In old v1.x, extensions needed to be deleted via ftp, there was no delete button in admin area...

**Comment by Moc** [comment]
> But it is fixed now or they are working on it. I lost track of it.

Should be fixed.

**Comment by Moc** [comment]
@Darkicross Did you manage to solve this issue? If not, can you please answer the questions by Jimmi posted above?

**Comment by Moc** [comment]
Closing, assumed to be fixed. If not, let us know and I'll re-open.
