### ISSUE TITLE
FR - possibility to add custom panel to admin dashboard

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3703]
If there is a predefined name for admin custom dashboard, then one can customize dashboard without changing core files. 

I mean this:

`if(in_array($pref['adminstyle'], array('infopanel', 'flexpanel', 'custompanel')))`

For example:  remove big chart when log plugin is not used

**Comment by Moc** [comment]
You can already switch to flexpanel and change the layout including removing unused panels I think...

**Comment by Jimmi08** [comment]
@Moc Where? You can only set personalize icons and menus.  How to rid the graph and e107 news?
Or I didn't find this.

**Comment by Moc** [comment]
Theme manager - admin theme I think. Not at my computer atm.

**Comment by Jimmi08** [comment]
Clean installation
![image](https://user-images.githubusercontent.com/5429548/53679984-cfe2ee80-3cd4-11e9-8839-ef4fcdf7a886.png)

**Comment by CaMer0n** [comment]
You can drag-n-drop panels and plugins can add panels using e_dashboard.php . There is no option to hide panels at this time.

**Comment by Jimmi08** [comment]
@CaMer0n This is something similar to custom_style.css.   This way I can avoid changing core code.   Why there can't be this option?  Just to count with a file of this name. Nothing more. If the file doesn't exist, it's not listed in the dropdown. 

If this is not welcomed, this issue should be closed.

**Comment by CaMer0n** [comment]
@Jimmi08 I'm sorry, I must not have understood your request. "possibility to add custom panel to admin dashboard" is exactly what e_dashboard.php allows a plugin to do.

**Comment by Jimmi08** [comment]
@CaMer0n Hi, no, you get it right. e_dashboard add only left menu part. 
That request was to have the option to have a custom dashboard. 
If I remember correctly, I needed to remove stats (graph) and RSS from e107.org.

**Comment by CaMer0n** [comment]
This is on the right. Just drag-n-drop where it is needed. 

![image](https://user-images.githubusercontent.com/2825679/59722009-7cd76d80-91d7-11e9-963f-b99621cfc5e5.png)

**Comment by Jimmi08** [comment]
Solved with customized KA admin look and some css tricks. I don't need this anymore.  Thanks
