### ISSUE TITLE
Q - plugin icons on dashboard - what are rules?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3704]
infopanel and flexpanel are new admin dashboard layouts

with legacy layout f.e. compact there are all plugins to what admin have admin access.
but with infopanel and flexpanel there is only user plugin (core), not not core plugins. 

Layouts
categories: only core
classis: core + non core plugins
combo: core + non core plugins
compact: core + non core plugins
infopanel: only core
flexpanel: only core 

After copy infopanel  file  under the different name (and replaced "info" related stuff), non core plugins are displayed:  (probably because something is related on layout name, not haven't time to check this, but html output is different)

Before:
![image](https://user-images.githubusercontent.com/5429548/53627620-37cc0300-3c09-11e9-83e1-6b1d961ba4be.png)

After:
![image](https://user-images.githubusercontent.com/5429548/53627658-503c1d80-3c09-11e9-9702-178e034f0ab5.png)

**So question is :  why new layouts display only core plugins?**

**Comment by Jimmi08** [comment]
Ok, with new layouts you need to add plugins icons manually via Personalize options

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, you need to use /e107_admin/admin.php?mode=customize and if this is empty it should revert back to core + plugins.
