### ISSUE TITLE
Automatic update from plugin from e107.org may overwrite 'not registered' plugin 

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3711]
Sorry if it's not completely clear, i use the survey plugin to make forms, it's an oldy but functions, someone has placed a plugin in the system with the same name and everywhere i have installed the old survey the new one (it's really not the same) is overwriting the old one. 

Can someone do something about that?

Thx
Alex

**Comment by Jimmi08** [comment]
Yes, it was discussed on Gitter.   You can't click on update.

**Comment by Moc** [comment]
This is caused by the fact that the plugin author chose not to upload the plugin to e107.org. In this case, it is not 'registered'. In the mean time, another plugin author uploaded a plugin with the same name (with a newer version). This new plugin then overwrites the older 'not registered' plugin. 

I do agree that there should be some form of warning or enhanced checks in order to avoid this situation from happening.

**Comment by Jimmi08** [comment]
That new survey plugin should be removed from e107.org. In fact, it's the only copy of the poll plugin and renamed tables.  There should be a list of e107 plugins with reserved names.   

I started to add "jm" to my plugins to avoid this problem, but the same thing could happen to the canonical plugin.  I could upload mine, then CaMeRon's one could be overwritten.  But I knew that there is the unregistered plugin with this name, so I changed its name.  

And from curiosity -  how is checked compatibility with e107 core?  One version is compatible with f.e. 2.1.9, but then there is new version only for 2.2.0.  Will user get the notification about to update to new version although is not compatible with their core?

**Comment by LaocheXe** [comment]
Maybe we could add a unique id to the plugin xml, that would be use to cross check plugins, themes, etc... Just throwing out ideas here

**Comment by Jimmi08** [comment]
Easier is check plugin name and plugin author. Both values.

**Comment by CaMer0n** [comment]
@Alex-e107nl If you reinstall the septor version of survey, e107 should no longer suggest an updated version from e107.org.  (following the changes I just made)

**Comment by Alex-e107nl** [comment]
Very nice Cameron THX! Will test it of course!!

**Comment by CaMer0n** [comment]
@Alex-e107nl Thanks.
