### ISSUE TITLE
Site navigation links resize their icon to 800px when using uploaded images.

### ISSUE THREAD

**Issue by HatchlingByHeart** [e107inc/e107#3712]
As title says.

Icons work as intended (they don't get resized) *if* they came pre-installed with e107 or belong to a plugin. The issue only affects images uploaded via media manager.

The issue was not solved by using another theme or removing all plugins, so I can only guess it is not theme or plugin related.

Example Image: https://www.dropbox.com/s/44bqam45l2qgdg0/ss_e107.png?dl=0
(News is using an uploaded 64x64 png file, the rest of the links are using the icon from the ReCaptcha plugin)

e107 Version: 2.1.9
OS: Debian 4.9.130-2
Apache Version: Apache/2.4.25
PHP Version: 7.1.26-2+0-20190216175340.13+stretch-1.gbpc20626
MySQL (MariaDB) Version: 10.1.37-MariaDB-0+deb9u1

**Comment by CaMer0n** [comment]
Thank you @HatchlingByHeart If you update from github and then re-upload the icon, it should now be placed in the correct folder (icons) and render correctly.

**Comment by HatchlingByHeart** [comment]
Thank you, @CaMer0n. It works perfectly now after replacing e_parse_class.php and media_class.php with latest versions from github.

**Comment by CaMer0n** [comment]
@HatchlingByHeart Great! Thank you for the feedback.
