### ISSUE TITLE
Q:  how forum views (number) works

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3713]
I have a problem with forum views. 
It gots very weird values when user click on mark as viewed in the custom plugin. 

That plugin uses only
`$forum->threadMarkAsRead($splitoutthreads);`
where $splitoutthreads is forum ID.
 

No idea where to look. 
I see that it's displayed: 
`$this->var['thread_views']`

but threadMarkAsRead()  has nothing with views...

and only way when thread_views are increased is in  threadIncView() 
```
//Only increment thread views if not being viewed by thread starter
if (USER && (USERID != $thread->threadInfo['thread_user'] || $thread->threadInfo['thread_total_replies'] > 0) || !$thread->noInc)
{
	$forum->threadIncview($thread->threadInfo['thread_id']);
}
```
And they say that number is 6x increasing exactly. 

And I can't find anywhere core functionality mark this forum as viewed (at frontend)

But I starting to think that it has nothing with my plugin.

I just looked at their forum:  - views 105
![image](https://user-images.githubusercontent.com/5429548/53820063-629cbb00-3f6b-11e9-8da2-83f4c5d8a631.png)

I viewed forum, going back and then
![image](https://user-images.githubusercontent.com/5429548/53820127-7ba56c00-3f6b-11e9-9e7b-3967cc527902.png)

So my one view is calculated 6 times.

**Comment by Moc** [comment]
So far, I cannot reproduce the views being counted 6 times. For me, the view is only counted once as it should be. Will do more testing.

**Comment by wrxxy** [comment]
@Moc I understand that it may be working on your end and but just wondering how would we go repairing it. Whats required please?

**Comment by Moc** [comment]
In my previous reply I said I'd do more testing :) I'll get back to it asap.

**Comment by Jimmi08** [comment]
@Moc  I found the reason, it's caused by 404 errors

**With not sef-url forum**  everything works (old legacy urls)

**With sef url** I checked log access and noticed 404 from some old plugins.  
![image](https://user-images.githubusercontent.com/5429548/54083463-23cc8380-4324-11e9-9ce8-165c40006a25.png)

After uninstall resizer plugin and delete sc_clock_menu  (I couldn't find where this one is used, no menu was there),  problem with view is fixed.

Only 404 with javascript files causes that page is reviewed (refreshed) 2 x javascript missing files. Tested after uninstall resizer - views were increased only 4x.

**Comment by Moc** [comment]
Hmm, interesting. So I guess the javascript refreshes the page or something. But the difference between the SEF en non-SEF URLs is strange.

**Comment by Jimmi08** [comment]
Live site returns 200, although path is definitely wrong:

![image](https://user-images.githubusercontent.com/5429548/54083806-00580780-4329-11e9-81f4-cc003b646663.png)

How this is possible?
Hm, because sef-url.  There is no check what is after forum ID. 
With all those wrong script forum is displayed and page views  + 1 happens. 

http://www.outlawsracing.com/forum/racingevents/11149/new-fvr-mod-up-for-testing/e107_plugins/sc_clock_menu/greetings.js

**Comment by Jimmi08** [comment]
it was caused with log plugin.  to old to be able track this anymore
