### ISSUE TITLE
FR - improve membersonly behaviour

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3719]
It just notes, not to forget to look at this when there will be more time

- if you have the membersonly site
 
![image](https://user-images.githubusercontent.com/5429548/53957989-29398c00-40e0-11e9-80af-95a25b29d7ea.png)

you will have displayed:
 
![image](https://user-images.githubusercontent.com/5429548/53958090-7a498000-40e0-11e9-8627-addf9d1ccc0d.png)

but link Click here to return to front page. is useless because frontpage is the membersonly page. 
There should be the check that if that prefs is set (membersonly page instead homepage or login ), then this link shouldn't be displayed

**Comment by Jimmi08** [comment]
Membersonly uses old paths to templates: 
There should be used THEME_LEGACY maybe.  

```
	if(deftrue('BOOTSTRAP')) //v2.x
	{
		$MEMBERSONLY_TEMPLATE = e107::getCoretemplate('membersonly');
	}
	else // Legacy
	{
		if(is_readable(THEME."membersonly_template.php"))
		{
			require_once(THEME."membersonly_template.php");
		}
		else
		{
			require_once(e_CORE."templates/membersonly_template.php");
		}
 
	}
```

**Comment by Moc** [comment]
Added a fix. 

@Jimmi08 I think the templates are set fine. This check is used as backwards compatibility with v1 themes, which may have their templates stores in their theme folder. Do you see any issues with your themes? 

I am not a fan of THEME_LEGACY because it simply checks whether the current theme has a theme.xml file in their theme folder. It this case, it would then assume that all themes with theme.xml are Bootstrap theme. I'd rather use the BOOTSTRAP constant here, as it is using now.

**Comment by Jimmi08** [comment]
@Moc  how new theme without bootstrap support will work?   You can have new theme structure without BOOTSTRAP defined.

I had information that you can use define("THEME_LEGACY", 1);  in your theme.php 

It's nice to think about old themes, but most of them use e_PAGE and it's not supported anymore.  So they will not work out of box.

**Comment by Moc** [comment]
I am going to look into e_PAGE and e_PAGETITLE soon. It's pretty broken at the moment indeed. 

I am not saying that non-bootstrap theme support is working properly now. I'm just trying to avoid more and more integration with Bootstrap personally. I'd like e107 to be flexible in the future to use also non-bootstrap frameworks (but again, that is future). 

For now, I think the current check of the templates as you quoted above, should work fine. Or do you have an issue with your themes when this check is used?

**Comment by Jimmi08** [comment]
> I am not saying that non-bootstrap theme support is working properly now. I'm just trying to avoid more and more integration with Bootstrap personally. I'd like e107 to be flexible in the future to use also non-bootstrap frameworks (but again, that is future).

Exactly, why I dislike this check about template structure depends on bootstrap and not on legacy theme.   
I could check this with old theme I should update now for new version. So new template structure but not boostrap.
