### ISSUE TITLE
unsecure page if i use thumbnail - http://placehold.it

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#3720]
i receive in gallery o other area with thumbnail loaded from http://placehold.it 
 "connection page not secure" 

files:
e107_admin/includes/infopanel.php    
thumb.php
resolve with https://placehold.it
could you update repo? thanks

**Comment by Moc** [comment]
You are using HTTPS on your own website, right?

**Comment by kreossino** [comment]
ok my version is to old
thank you

**Comment by Moc** [comment]
Closing. But let us know if you still have the issue after updating from Github.
