### ISSUE TITLE
avatar thumbnails in wrong aspect ratio after update

### ISSUE THREAD

**Issue by realG** [e107inc/e107#3721]
Hi everyone, can you please help me troubleshoot this issue?

I was massively behind with my e107 code so did a git pull today from the master branch and after a few tweaks and a db update it all seems to be working, except the thumbnails of user avatars (in chatbox, user profile page, etc) are now shown in a square aspect ratio so look a bit distorted.

Tried clearing the cache through the admin pages and the browser cache. I'm using a very lightly modified bootstrap3 theme, I also tried switching to the clean bootstrap3 theme shipped with e107 but that doesn't make a difference so it's probably not theme-related. I'm on Ubuntu 18.04, nginx + php 7.2 with GD2 if that matters.

The html I end up with (this is from the member profile page) looks like this:
`<img class="img-circle user-avatar" alt="avatar.jpg" src="/thumb.php?src=avatar.jpg&w=200&h=200" width="200" height="200">`

Please help :)

**Comment by Moc** [comment]
Very interesting.. the css class still shows correct as 'img-circle' but apparently the image is rendered as square instead. 

Can you please verify that the bootstrap.css version that is loaded is 3.x? and not 4.x?

**Comment by realG** [comment]
Yes it appears to be, inspecting one of the thumbnails in Chrome the bootstrap.css that's loaded points to 3.3.6

**Comment by Moc** [comment]
Interesting, then I have no idea what is causing this. 

@CaMer0n Any thoughts?

**Comment by CaMer0n** [comment]
@Moc I'd need to see the actual page. @realG Can you post a URL?

**Comment by realG** [comment]
Hm that might be difficult it's currently not accessible from outside my network... I'll see if I can spin up a sanitised copy that I could make accessible online. In the meantime please let me know if you can think of any other place in css or the code I could look at to debug what's going on.

**Comment by CaMer0n** [comment]
Closing, as the added crop support should fix it. Please re-open if necessary.
