### ISSUE TITLE
last seen menu - default value for created but not log in user yet

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3723]
49 years ago - 
maybe it's because user for created manually and log in from admin area, but this shouldn't be displayed - default value should be some other text. 

`$this->currentUser['user_currentvisit'] `has value:   
`string(1) "0"`

**Comment by Moc** [comment]
Cannot reproduce. If a user has value "0" in the database field `user_currentvisit` in `e107_user`, the user is shown in the last seen menu without any date. See screenshot below:

![image](https://user-images.githubusercontent.com/577978/146822971-06bad0d5-e0f7-4a32-be2f-87810378ae13.png)

Let me know if this is still an issue for you and then I'll investigate.

**Comment by Jimmi08** [comment]
It looks like fixed

**Comment by Moc** [comment]
Actually, maybe it's better not to display the user at all if the value is 0? What do you think?

**Comment by Jimmi08** [comment]
You are maybe right. 
Yes:  They never were logged in, so they never saw anything and they shouldn't be listed... 
No:  You see them only because of the small count of users, otherwise they are at the end of the list. 

So suggestion - if they are created by admin, they shouldn't be listed there. 
:)
But I can live with an actual solution.
