### ISSUE TITLE
chatbox notify title -  html code is there

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3726]
Subject of chatbox notify email

![image](https://user-images.githubusercontent.com/5429548/54213029-080fdb80-44e4-11e9-97e4-6f0562764b9f.png)

**Comment by Moc** [comment]
Hmm, I cannot reproduce this. I do not see any reason in the code that would cause this. 
I assume you are using the latest files?

Which theme are you using?

**Comment by Jimmi08** [comment]
@Moc RideBlue2

**Comment by Moc** [comment]
Reproduced the issue on RideBlue2.

**Comment by Moc** [comment]
Ok, took a while but I found the issue. Not sure about the fix though:

@CaMer0n 
in e107_handlers/mail.php on line 856, this is done:
```php
$this->Subject = $tp->parseTemplate($tmpl['subject'], true, varset($eml['shortcodes'],null));
```

It merges with this in the RideBlue2 theme.php, used for the `$COMMENTSTYLE` in theme.php.
```php
$sc_style["SUBJECT"]["pre"] = '<td class="forumheader">';
$sc_style["SUBJECT"]["post"] = '</td></tr>';
```

I see a note here:
```php
if($tmpl = e107::getCoreTemplate('email', $eml['template'], 'front', true))  //FIXME - Core template is failing with template 'notify'. Works with theme template. Issue with core template registry?
```

Can you take a look please?

**Comment by CaMer0n** [comment]
@Moc Thanks for the tips. 

I believe the commit should fix it, but if not, please re-open. Thank you both!
