### ISSUE TITLE
problem with user rating

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3727]
Result with the attempt to add 0.5 stars.  The normal user (not in debug mode) can see this. 

![image](https://user-images.githubusercontent.com/5429548/54262414-5ff32480-456e-11e9-8437-1356396b1b3b.png)

4.5 stars  works.

**Comment by Moc** [comment]
Duplicate #1933

**Comment by Jimmi08** [comment]
Fix:
`if (!$qs[0] || USER == FALSE || $qs[3] > 10 || $qs[3] < 1)`
to 
`if (!$qs[0] || USER == FALSE || $qs[3] > 10 || $qs[3] < 0)`

Or 0,5 - because this is mininal valur, not 1

**Comment by Moc** [comment]
Still, the data is saved as 0... not 0.5, causing issues when viewing the result (displays as 0).
