### ISSUE TITLE
Grammarly extension and tinymce issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3728]
When you use Chrome Grammarly extension,  g tags are inserted.  
I am aware this is the 3rd plugin issue, but there are already solutions about to fix this. 

https://github.com/tinymce/tinymce/issues/3625
https://stackoverflow.com/questions/43383100/tinymce-generating-random-g-tags

As you see, it was mainly reported in 2017, so I don't know if e107 is using the latest TinyMCE version or this is caused by some e107 customization in TinyMCE... 

Could you add removing g tags to TinyMCE filter?  There is still no option to set my own HTML tags to be valid or not. 

Thanks

**Comment by Moc** [comment]
My initial thought is that this should be fixed by Grammarly themselves. The issue posted in TinyMCE is not closed, but they indicate that they also require the 3rd party (Grammarly) to fix it. 

If you have a ready to use fix to use in e107, we could consider (temporarily) implementing it.

**Comment by Jimmi08** [comment]
@Moc there is somewhere already filter for TinyMCE input.  I was not able to find it to test this.   Do you remember? - old html4 tags are removed sometimes where they are needed.  It was discussed there.

**Comment by Moc** [comment]
I guess e107_plugins/tinymce4/wysiwyg.php but I am not really into TinyMCE at all :)

**Comment by Jimmi08** [comment]
I don't think so. it has something with e107 parsing :)

**Comment by Jimmi08** [comment]
I found it:
https://github.com/e107inc/e107/issues/3353#issuecomment-411018659

The correct fix is to add pref to be able to add my own allowed tags.

**Comment by Jimmi08** [comment]
I can't reproduce this again. Closing, I will reopen it if this happens again. Thanks for your time.
