### ISSUE TITLE
category template is changing news frontend template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3739]
As soon as the category news template is used, the news frontpage template is ignored. 
Maybe this is the intention.
but the problem is that you can change the news category template without knowing about it.

![image](https://user-images.githubusercontent.com/5429548/54742169-e50ab900-4bc0-11e9-8dd0-0af0fe935739.png)

An empty template is prefilled with value list when you are in edit mode
![image](https://user-images.githubusercontent.com/5429548/54742198-066ba500-4bc1-11e9-8fb3-44b36b7e82cb.png)

and changed just by changing the title or anything on the first tab.

Default value for most of existing themes is:
`<field name="category_template"></field>`

**Comment by CaMer0n** [comment]
Okay, so the problem is the drop-down doesn't have an empty value.
