### ISSUE TITLE
Q:  update() result

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3740]
I have this code (from documentation on e107.org)
```
$insert_data = array(
	 'calculation' => $result, 
	  'WHERE' => 'userdata_id='.(int)$id 
 );

$status = e107::getDB()->update('dia_userdata', $insert_data, true);
		 return $status; 
```
debug mode is ON, but result is:
![image](https://user-images.githubusercontent.com/5429548/54759717-f2d73300-4bee-11e9-8997-b1011a26cff1.png)

Note: when I used a version like this from mysql_class.php file:
`e107::getDb('sql2')->update("user", "user_viewed = '$u_new' WHERE user_id = '".USERID."' ");`
it didn't work if $result is serialized array. 

Nevermind, I can see with browser debug that there are not wrong queries and data are updated.

And $status is 1.  But if I refresh page and confirm resending data, I got value 0.  I suppose it's because no data was changed, but this is not mentioned anywhere only with insert() method. 

Is this correct?  Thanks

**Comment by SimSync** [comment]
The `$insert_data` array must look like follows:

```
$insert_data = array(
   'data' => array('field1' => 'val1', 'field2' => 'val2'),
   'WHERE' => 'id=1'
);
```
The keys 'data' (lowercase) and 'WHERE' (uppercase) are required when using an array for updating data.

Your example `e107::getDb('sql2')->update("user", "user_viewed = '$u_new' WHERE user_id = '".USERID."' ");` is the other possibility to do an update.

**Comment by Jimmi08** [comment]
@SimSync 
with old format debug mode is not working
with the third possibility - if $u_new is serialized array, it doesn't work
I will test the first option, thank you

**Comment by SimSync** [comment]
The problem with serialized arrays is, that strings get surrounded with double quotes ("). That means, the double quote in the serialized string will "escape" the query and could make it fail.
I would propose to use the array format (old or new format doesn't matter). Due to the PDO handling of the data, the escaping of the quotes in the (serialized) string data is done automatically.

**Comment by Jimmi08** [comment]
closing in favour of #3763

**Comment by Jimmi08** [comment]
> I would propose to use the array format (old or new format doesn't matter). Due to the PDO handling of the data, the escaping of the quotes in the (serialized) string data is done automatically.

@SimSync I am not sure if I get this correct way 
I have this:
$insert_data = array(   
  'userdata'   =>  e107::serialize($user_data),
  'agencydata'   => $user_data,
 );

$user_data - is array after retrieve() method
Result:
![image](https://user-images.githubusercontent.com/5429548/55705158-67c3ae80-59de-11e9-8af8-183f74694314.png)

PDO is enabled, php 7.0.  What do you mean by array format then?

Thank you

**Comment by SimSync** [comment]
This is how the `e107::serialize($array);` is working. It creates a string from the array, that can be safely saved to the data base. On retrieve, you should use `e107::unserialize($string);` on that field to get back the string data as array.
If you prefer to save the data in json format to the database, you should use `e107::serialize($array, 'json');`

**Comment by Jimmi08** [comment]
@SimSync you wrote to let serialize on PDO... - or I got it wrong.  $user_data is a normal array and I wasn't able to save it without serialize.  It saved the word "Array" instead of.

**Comment by SimSync** [comment]
@Jimmi08 PDO will not serialize the data. It only "sanitizes" the data for use with a database. 
You need to serialize and unserialize on your own.

**Comment by Jimmi08** [comment]
Thanks. I knew this but I was a bit confused with your answer about array and PDO.  Thank you for your time.
