### ISSUE TITLE
FR -  pref to set display e107 links for admins

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3743]
![image](https://user-images.githubusercontent.com/5429548/54808404-683f1400-4c80-11e9-929c-68d42d346770.png)

It's a bit confusing for just admins that are not developers.  Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 What is confusing about it?

**Comment by Jimmi08** [comment]
If I do website for a client, they don't need to know this e107 stuff (in good meaning). In fact, they would like to have there their links to their own sites.  Nothing important, I am just trying to avoid core changes.

**Comment by CaMer0n** [comment]
A small price to pay for free software. :grinning: 

However, I believe these links may be more appropriate in a new 'Support' area, which could be added here. 

![image](https://user-images.githubusercontent.com/2825679/58913200-838ebc80-86d0-11e9-8c1c-795ee3a7f5a6.png)

I would also add a link to the gitter chatroom in there.

**Comment by Moc** [comment]
Closing in favour of: https://github.com/e107inc/e107/issues/5124
