### ISSUE TITLE
Cookie and pages link button

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#3745]
Hello ... I can not replace the pages link button in the preferences. Uploading an image works, but it can not be exchanged. Neither click on selection nor on the picture itself brings success. Back to the default settings, I then only with the back button of the browser. What can I do?
In addition, I get after saving: "Warning! Unauthorized characters found in the cookie name (they are only alphanumeric characters). Cookie name was not saved."

e107 2.2.0 (git)
PHP 7.2.16 - MySQL 5.6.43-84.3-log

**Comment by TrueHatori** [comment]
I see the problem, I just do not know where to change it. It works in News and own pages. In the preferences page no pop-up opens, but a new page. Where can I change that?
And where do I turn for the cookie?

**Comment by Moc** [comment]
> I can not replace the pages link button in the preferences. 

I don't know what you mean with this. What are you referring to? Can you show me a screenshot?

> In addition, I get after saving: "Warning! Unauthorized characters found in the cookie name (they are only alphanumeric characters). Cookie name was not saved."

Can you show me a screenshot of this message as well please?

- Which browser are you using?

**Comment by TrueHatori** [comment]
No, does not go with screenshot, apparently this does not work for me :(
Example: I put a tick on "Show page setup time" and click on "Save change". Then there is this:

warning
Unauthorized characters found in the cookie name (they are only alphanumeric characters). Cookie name was not saved.

System information
Settings were not saved because no changes were made.

In the meantime, I simply overwrote the page link button and have copied my own button.png into the directory e107_images.

**Comment by TrueHatori** [comment]
And why do I have empty pages in the "Comments / Post", "File Uploading, Security & Protection", "Javascript Framework" and "Advanced Settings" presets?
When I call the presets altogether, many things are missing, in the middle of the page is canceled.
We had the same problem a long time ago, because it was due to a memory setting.

**Comment by TrueHatori** [comment]
"Something went really wrong, and we can't process that file". This is the message when I try upload a jpg. The problem is still the same.

**Comment by TrueHatori** [comment]
Ok, it's a Problem with Firefox, with Edge I can send Images.
![image](https://user-images.githubusercontent.com/17859550/58288282-6cd49580-7db3-11e9-8629-196dca2e0bb0.png)
This after all savings.
And here is the end of preferences.
![image](https://user-images.githubusercontent.com/17859550/58288371-b1f8c780-7db3-11e9-9fbe-02cb563ea064.png)
No more come after this.

**Comment by Moc** [comment]
@TrueHatori Are these issues still occurring with the latest e107 files, and the English language pack?

**Comment by TrueHatori** [comment]
Yes, with english language pack it works.

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
