### ISSUE TITLE
Editing member info with extended user fields gives an error

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3746]
Github of today, when i try to edit a member with extended user fields the following error is thrown at me..
Fatal error: Unsupported operand types in ****private_html/e107_admin/users.php on line 2446

When reverting e107_admin_user.php to the version of 26-2-2019 everything works.. So that's how i have it working for now.. but please help!

Alex

**Comment by Moc** [comment]
What's your PHP version?

**Comment by Alex-e107nl** [comment]
PhP 5.6.30 is used on that server..

**Comment by LaocheXe** [comment]
What extended user fields do you have?

**Comment by LaocheXe** [comment]
Also notice, once you disable any extended user fields, you can edit the user account.

**Comment by Jimmi08** [comment]
there is mistypo on that line

`$extData = -$controller->getExtended();`

it should be (not -$controller-)
`$extData = $controller->getExtended();`
