### ISSUE TITLE
Request - update hybridauth

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3749]
I don't mind putting in work on the social plugin to add other providers - updating the current providers we run into an issue.Example, updating the Steam provider in e107, I return this error: Fatal error: Class 'Hybridauth\Adapter\OpenID' not found in /usr/www/e107-test/e107_handlers/hybridauth/Hybrid/Providers/Steam.php on line 31

^^That is the updated php file I just added.
Added the Adapter folder which has OpenID and  some others in the e107_handlers/hybridauth folder, but still no go.

It would be great to add additional providers - including gaming ones such as Blizzard, Discord, and TwitchTV - but also have BitBucket, GitLab, Foursquare, Instagram, etc...

**Comment by Moc** [comment]
Closing in favour of #3492
