### ISSUE TITLE
forum/newforumposts_menu.php  - SQL error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3757]
adding new newforumposts_menu.php to bootstrap3, I got  SQL error 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ORDER BY p.post_datestamp DESC LIMIT 0, 10' at line 12

```
Array
(
    [0] => Array
        (
            [file] => G:\php72\htdocs\e107-whisper\e107_handlers\mysql_class.php
            [line] => 551
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => 
					SELECT
					p.post_user, p.post_id, p.post_datestamp, p.post_user_anon, p.post_entry,
					t.*,
					u.user_id, u.user_name, u.user_image, u.user_currentvisit,
					lu.user_name as thread_lastuser_username, 
					f.forum_name, f.forum_sef
					FROM e107_forum_post as p
					LEFT JOIN e107_forum_thread AS t ON t.thread_id = p.post_thread
					LEFT JOIN e107_forum as f ON f.forum_id = t.thread_forum_id
					LEFT JOIN e107_user AS u ON u.user_id = p.post_user
					LEFT JOIN e107_user AS lu ON t.thread_lastuser = lu.user_id
					WHERE  p.post_forum IN ()
					ORDER BY p.post_datestamp DESC LIMIT 0, 10 
                )

        )


```

There are no posts yet, so maybe this is the reason?

**Comment by Moc** [comment]
Cannot reproduce so far, it shows the "No posts yet" message for me. 

![image](https://user-images.githubusercontent.com/577978/55013028-9efe8c80-4fe8-11e9-885b-159bf11c2da3.png)

PHP 7 and MySQL with PDO?

**Comment by Moc** [comment]
This is the issue for you 

`WHERE  p.post_forum IN ()`

for me it says:

`WHERE p.post_forum IN (1,2,3,4,5)`

1-5 are forum categories.

**Comment by Jimmi08** [comment]
@Moc I found it when used the empty forum, so no forum categories. Just installed forum plugin. There is no test if any forum exists.  I double checked that it's that new menu, but I will do it again.

**Comment by Moc** [comment]
Whoops, that makes sense.... sorry, should have thought of that. 
So we need to add a check if there's categories added indeed.

**Comment by Jimmi08** [comment]
@Moc no problem,   it's just happened...  it's not common to have this menu before any forum records.  I just wanted to report it :)
