### ISSUE TITLE
bbcodes and bootstrap4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3758]
How to style or fix something like this?

![image](https://user-images.githubusercontent.com/5429548/54886530-246b2b00-4e89-11e9-876b-719ae8ac112b.png)

fa fa-picture-o is not supported
some of bbcodes have e_bb class and some e_pointer class.  No idea, if e_pointer is used somewhere else, why is there missing e_bb class?

@Moc How did you style bbcodes?  If yours are correct, what is your css for them? Thanks

**Comment by Jimmi08** [comment]
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by Moc** [comment]
I'm not using BBCodes but I do know that FontAwesome 5 has been integrated properly now, with the fallback files included. So anything from FA4 should still work correctly. Will take a closer look later

**Comment by Jimmi08** [comment]
Still issue. The problem is not in FA icons, there are different core classes for buttons.

Signature where bbcodes are used always, if I am not mistaken: 

![image](https://user-images.githubusercontent.com/5429548/84858301-311a0700-b06b-11ea-851a-fbeac9dae093.png)

**Comment by Moc** [comment]
@Jimmi08 Can this be closed?
