### ISSUE TITLE
parms doesn't work with new Admin UI  with datestamp field

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3759]
Now you need to put  "mask"  to ReadParms, "parms"  is ignored in renderValue().  You can try this on news in admin UI.  	

```
'news_datestamp'		=> array('title' => LAN_NEWS_32, 	'type' => 'datestamp', 'data'=>'int', 'tab'=>2,  
		 'writeParms'=>'type=datetime',   'width' => 'auto', 	'thclass' => '', 				'class' => null, 		'nosort' => false,
		  'parms' => 'mask=%A %d %B %Y', 'filter'=>true),
```

**Comment by CaMer0n** [comment]
Looks like old code to me. There is only readParms and writeParms.

**Comment by Jimmi08** [comment]
@Moc should be labeled core:news.  Problem is news code, not in AdminUI.

**Comment by CaMer0n** [comment]
@Jimmi08 Is there a functional issue? If not, I believe this old code could simply be removed.

**Comment by Jimmi08** [comment]
I agree, I was just looking through files for an example of parms with mask and I noticed this.
