### ISSUE TITLE
update() problem and PDO

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3763]
I have still problem with update method.  PDO, php 7.0

```
$insert_data - normal array
$insert_data['WHERE'] = 'id='.(int)$newid; 
$result = e107::getDB()->update($table, $insert_data );
```

after sending form without changing data, it still returns that data was updated, not that there is no change

I found this:
`$result = $this->mySQLresult = $this->db_Query($query, NULL, 'db_Update', $debug, $log_type, $log_remark);`

return int(1)

so this check fail : ` if(is_object($result)) for pdo`
and this fails because php 7 too:
` $result = mysql_affected_rows($this->mySQLaccess);`

**Comment by Moc** [comment]
Possibly related to the change made here https://github.com/e107inc/e107/commit/96a84a1e93d0bf675f40df51ffe277ce4097e027 (to fix https://github.com/e107inc/e107/issues/3550)

@SimSync Do you have any ideas on this?

**Comment by SimSync** [comment]
@Jimmi08 `$insert_data['data']` should contain the array with the data to update. `$insert_data['WHERE']` has to contain the where clause. Please be aware of the upper-/lowercase keys. Not sure if you already did it this way. Your first post isn't clear about this...

**Comment by Jimmi08** [comment]
@SimSync I did it according this and I checked with other examples in core plugins...

![image](https://user-images.githubusercontent.com/5429548/55016696-8fcf0d00-4fef-11e9-9776-831fe597f6df.png)

I will do it again, this is really annoying for me... 
This could be related:  
https://github.com/e107inc/e107/issues/3740

I knew that doc could be outdated, but the code like mine is still  used in core.

**Comment by SimSync** [comment]
I just copy over my comment from #3740:

The `$insert_data` array should look like follows (this is the "new" format):

```
$insert_data = array(
   'data' => array('field1' => 'val1', 'field2' => 'val2'),
   'WHERE' => 'id=1'
);
```
The keys 'data' (lowercase) and 'WHERE' (uppercase) are required when using an array for updating data.

Old format looks like you found it in the docs:

```
$insert_data = array(
   'field1' => 'val1', 
   'field2' => 'val2',
   'WHERE' => 'id=1'
);
```
The 'WHERE' must be uppercase.

Third possibility is this:
Your example `e107::getDb('sql2')->update("user", "user_viewed = '$u_new' WHERE user_id = '".USERID."' ");` is the other possibility to do an update.

**Comment by Jimmi08** [comment]
@SimSync  No change
$arg  parm-  sent to update()
```
Array
(
    [data] => Array
        (
            [agency_user] => 1
            [timestamp] => 1553674226
 
        )

    [WHERE] => id=8
)
```
after prepare $arg..

```
`agency_user`= :agency_user, `timestamp`= :timestamp ...   WHERE id=8 
```

var_dump($result);
int(1)

**Comment by SimSync** [comment]
@Jimmi08 Which result do you expect from your update? Is the database record updated? Did you check with phpmyadmin or Heidi if the query worked?
A result of 1 would be ok for me as it tells me that 1 record was affected by the query.
I'm not sure what you expect?

**Comment by Jimmi08** [comment]
@SimSync   No problem with the normal update.
The problem is when the form is sent without any change. I would expect something like in the admin area (that blue info box)  -  no changes were made.   It returned 0 before...  Maybe this was wrong before. No idea, but it behaves differently now.  At least I think (but why I had there test if it returns >0 or 0 or rest (false)).  

I still got message that record was updated.

**Comment by SimSync** [comment]
@Jimmi08 You can test the result with `$sql->update(foobar) === false` if an error occured during update and than get the error with `getLastErrorNumber()` or `getLastErrorText()`.
If the result of the `update()` is 0 (zero), it just means there was nothing to update/ no records has been changed (without error).

**Comment by Jimmi08** [comment]
I just got it where is the problem.  The timestamp is changed every time when the form is posted, although no visible data are changed,  so it returns 1. Sorry, but at least I have the correct new way of update and insert arrays. Thank you for your time.
