### ISSUE TITLE
Voux welcome page hardcoded admin page

### ISSUE THREAD

**Issue by nlstart** [e107inc/e107#3775]
e107/e107_themes/voux/install/install.xml
contains hardcoded text to the admin page (around line 1101):
`<a class=&quot;btn btn-primary btn-large &quot; href=&quot;e107_admin/admin.php&quot;>Go to Admin area</a>`
To make it follow the settings from e107_config.php this might be better:
`<a class=&quot;btn btn-primary btn-large &quot; href=&quot;{e_ADMIN}admin.php&quot;>Go to Admin area</a>`

**Comment by CaMer0n** [comment]
Happy to see you @nlstart! :+1:

**Comment by nlstart** [comment]
Thank you for the warm welcome @CaMer0n, it has been way too long! :-)

**Comment by Moc** [comment]
Good to see you!

**Comment by nlstart** [comment]
Identical problems in:
e107_themes\bootstrap3\install\install.xml (line 12)
e107_themes\landingzero\install\install.xml (line 50)

**Comment by CaMer0n** [comment]
Unfortunately, it seems this broke the link in v2.2.0. Reassigned for 2.2.1
