### ISSUE TITLE
Polls In Threads

### ISSUE THREAD

**Issue by wrxxy** [e107inc/e107#3779]
Why I am not able to add a poll to a new thread as it was possible in V1 and now with V2 its not??? Unless I am doing something wrong.  Has this feature been disabled?

**Comment by Moc** [comment]
It still seems to work for me. 

- Do you have the poll plugin installed?
- Is the option enabled in the Forum preferences?
- Which theme are you using?

**Comment by wrxxy** [comment]
Yes @Mocha my bad it wasn't enabled...
