### ISSUE TITLE
MariaDB server port

### ISSUE THREAD

**Issue by chory** [e107inc/e107#3782]
I am trying to install e107 on a new server, but I can not connect to the database server, because I can not indicate the necessary port for it

**Comment by Moc** [comment]
In the host field use the : sign. 

localhost:3306

**Comment by chory** [comment]
e107 was unable to establish a connection to the MySQL server using the information you entered. Please return to the last page and ensure the information is correct.

MySQL Reported Error:
SQLSTATE[HY000] [2002] No such file or directory

**Comment by Moc** [comment]
Sounds like a server configuration issue

**Comment by chory** [comment]
Yes it is. My test server is giving me configuration problems, and until I solve it, I can not do anything 😭

**Comment by Moc** [comment]
I'm sorry but I don't think this is e107 specific. I'm closing the issue but in case you do think there is an issue with how e107 handles ports, please let us know. 

There should be some other issues here on GitHub which discussed the port configuration. 

(Sidenote, you may want to check the firewall on your server to make sure the incoming port is open)
