### ISSUE TITLE
Q:  ajax call and problem with $_POST

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3783]
I had this code in js file I am using:

```
    jQuery.ajax({
        url: this.options.ajaxUrl + '?use_ajax=1',
        type: 'POST',
        data: dataToSend,
        processData: false,
        contentType: "application/json; charset=utf-8",
        dataType: 'json',  
```

The problem was that $_POST was empty in the called file.  (File was called correctly).

After looking for a solution it was fixed by adding 
`beforeSend: function(xhr){xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded")}   `

My question is why I needed to add this code. The code without e107 worked correctly.

Thanks

**Comment by Moc** [comment]
Don't have the answer for you but check my mailbox repository, it may help.

**Comment by Jimmi08** [comment]
you have type: 'post', with small letters.   And you are using behaviours.  It's too much for me.

**Comment by Moc** [comment]
I'm just copying it from the forum plugin. I have no idea how the behaviours thing exactly works. Lonalore built it.

**Comment by Jimmi08** [comment]
I have an idea, it started as a plugin and I was there at the beginning...  Now with libraries, it's overcomplicated for normal users. Nevermind, this just happens too often - in meaning many other people have this problem. I posted it here to remember the solution.

**Comment by Moc** [comment]
You don't have to use libraries.. and the basics are not hard. Using Ajax calls is not for beginners in general.

**Comment by SimSync** [comment]
@Jimmi08 It looks to me as if you are "overwriting" the standard content type `application/x-www-form-urlencoded` with `application/json`. If you remove this key completely of set it to the default `application/x-www-form-urlencoded; charset=UTF-8`, it shouldn't be needed tom use `beforeSend` anymore.

Usually, if i need to post somethig with ajax, i use the "shortcut":
`$.post(url, data, success, dataType);`
e.g.
```
$.post(
   'url/to/ajax_handler.php',
   {id: 3, update: true}, 
   function(response) { 
      alert(response.msg); 
   },
   'json'
);
```
If you don't need the success callback, just remove it or set it to null.

**Comment by Jimmi08** [comment]
@SimSync but it is not my code, I am afraid to change anything. Without e107 it works.

**Comment by SimSync** [comment]
@Jimmi08 I'm not sure what `dataToSend` contains. Usually this is a json object like `{field: value, anotherfield: anothervalue}`. In this case, `processData: false` could break the ajax call from what i've found online so far. Just from the small code snippet i can't see what should break here and i'm also unsure what you mean whth "The code without e107 worked correctly."

**Comment by Jimmi08** [comment]
https://github.com/Jimmi08/visualbuilder/blob/master/qoob-e107-driver.js
line 50

**Comment by SimSync** [comment]
Without having tested this (of course not...;)), i think it should look like this:
In the original, the dataToSend was converted to a string, instead of posting the json object (Of course, i don't know what `data` contains, i assume it's a string, array or json object).
When processData is not set or true, the conversion to a string is done automatically and fitted into "application/x-www-form-urlencoded" (see https://api.jquery.com/jQuery.ajax/). That's why i removed a unnecessary or redundant lines.
```javascript
Qoobe107Driver.prototype.savePageData = function(data, cb) {
    var dataToSend = {
        func : 'qoob_save_page_data',
        pageId: this.options.pageId,
        data: data     
    };
 
    jQuery.ajax({
        url: this.options.ajaxUrl,
        type: 'POST',
        data: dataToSend,
        dataType: 'json',  
        success: function(response) {
            if (response.success) {
                cb(null, response.success);
            } else {
                cb(response.error, response.success);
                if (response.error) {
                    console.error(response.error);
                } else {
                    console.error("Error in 'Qoobe107Driver.savePageData'. Sent data from server failed.");
                }
            }
        },
        error: function(xrh, error) {  
            console.error(error);     
        }      
	});
	
};
```

**Comment by Jimmi08** [comment]
Thank you 👍 

My notes to this part when I tried to understand how it works:
```
/*******************************************************************************************/
/***   SAVE PAGE DATA   - called from savePageData Warn: function is part of string!     ***/
/*******************************************************************************************/
$incoming = file_get_contents( 'php://input' );  //result is stringed json (stringify)
$decoded = json_decode( $incoming, true );       //result is array
$blocks_html = trim( $decoded['data']['html'] ); //result is array - preparing for caching
if ($decoded['func'] == 'qoob_save_page_data') { 
...
```

I have really no idea why they convert JSON to string, then use ajax and decode back to JSON...

**Comment by SimSync** [comment]
with my proposal, you can just use the `$_POST` php array to access the single "elements" like 'data', 'func' or 'pageId'. I don't know why they (you?) did it so complicated...?!

**Comment by Jimmi08** [comment]
Not me, I don't understand this stuff. It's from HTML or WP version of this. I am not able to remember now.
