### ISSUE TITLE
Report -  fatal error related to event class

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3790]
This is not a bug because I installed that plugin by mistake.

This plugin
![image](https://user-images.githubusercontent.com/5429548/56860513-acb48280-6997-11e9-977b-98e2947a2b09.png)

uses event addon. 
On the download page in admin area I got the error:
`Fatal error: Uncaught Error: Cannot use string offset as an array in G:\php72\htdocs\***\e107_handlers\event_class.php:322 Stack trace: #0 G:\php72\htdocs\***\e107_handlers\form_handler.php(4234): e107_event->triggerHook(Array) #1 G:\php72\htdocs\***\e107_plugins\download\includes\admin.php(1623): e_form->renderHooks(Array) #2 G:\php72\htdocs\***\e107_plugins\download\includes\admin.php(590): download_main_admin_ui->create_download() #3 G:\php72\htdocs\***\e107_handlers\admin_ui.php(5921): download_main_admin_ui->createPage() #4 G:\php72\htdocs\***\e107_handlers\admin_ui.php(2182): e_admin_ui->EditPage() #5 G:\php72\htdocs\***\e107_handlers\admin_ui.php(1291): e_admin_controller->dispatchPage() #6 G:\php72\htdocs\***\e107_plugins\download\admin_download.php(240): e_admin_dispatcher->runPage() #7 {main} thrown in G:\php72\htdocs\***\e107_handlers\event_class.php on line 322`

it was caused by this method
```
	/*
	* add form field
	* @param array $data
	*/
	function event_form($data)
	{
		return $this->tag->tagwords_form($data['table'], intval($data['id']));
	}
```
The return value is NULL.

and this ends with fatal error:
```
case 'form':
if(method_exists($class, "event_{$data['method']}"))
{
	$ret = $class->event_form($data);
	if(!isset($ret[0]))
	{
		$text[$hook][0] = $ret;		
	}
	else 
	{
		$text[$hook] = $ret;
	}

}
break;
```
I am posting it here just maybe some test are missing in event handler or admin UI.  It didn't happen on news edit window, only on edit download. And it didn't happen before you added event name there.

**Comment by CaMer0n** [comment]
Appears to have fixed it.
