### ISSUE TITLE
Double prefix database table names when creating e107 plugin

### ISSUE THREAD

**Issue by BlastFM** [e107inc/e107#3791]
When you create a plugin with the plugin manager and you select a database table with a prefix name, you will need to edit admin_config.php and the whatever_sql.php files in the plugin folder, the database table names will have a prefix on them, for example _e107 and this will actually create the wrong table in the database, it will add the prefix again so the table will be named _e107_e107_whatever in the database, so delete the prefix in these files. If you have already created plugins in Ver 2.x you will also need to check your database for double prefix table names, using PhpMyadmin or similar and delete as required.

This is unexpected behaviour since you can only select a database table with a prefix name when building the plugin but the prefix will be added again when accessing via admin_config.php and the whatever_sql.php files.

This assumes that you used a prefixed database table name when you created the table for the plugin, but even if you didn't, I'm pretty sure that you would end up with a prefixed table name and the original non-prefixed table name which seems just as bad to me, still one un-used database table.

**Comment by Jimmi08** [comment]
Try don't use the table with text "e107" in name and check this again.  If it works (I know for sure that it does, I use PB very often), then the question/issue is different.

**Comment by BlastFM** [comment]
Well, for some unknown reason this issue seems to have resolved itself. If only it was always that simple eh.
