### ISSUE TITLE
poll menu and not installed poll plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3792]
poll menu is causing neverending redirection and site stops to work

if you have a theme with demo data 
```
    		<item>
			<field name="menu_id">143</field>
			<field name="menu_name">poll_menu</field>
			<field name="menu_location">12</field>
			<field name="menu_order">1</field>
			<field name="menu_class">0</field>
			<field name="menu_pages"></field>
			<field name="menu_path">poll/</field>
			<field name="menu_layout">magazine_full_width</field>
			<field name="menu_parms"></field>
		</item>
```

and the poll plugin is not installed, then site stops to work

I think it's because of this in poll_menu.php:
```
if (!e107::isInstalled('poll'))
{
	e107::redirect();
}
```

**Comment by CaMer0n** [comment]
@Jimmi08 btw. links_page plugin has a menu with something similar.

**Comment by Jimmi08** [comment]
@CaMer0n Thank you, I fixed it in my local version now, but I didn't want to maintain this plugin anymore.  But it looks like who else would do, doesn't it?  But this could explain some problems.
