### ISSUE TITLE
Captcha disappeared after logout

### ISSUE THREAD

**Issue by sparuj** [e107inc/e107#3795]
Hello everyone!

Today I wanted to check my 4 years old website that I did back in the day, so I downloaded the newest version of xampp. Knowing that there won't be any way of me to make it work with the latest php version right of the bat I downgraded to 5.6.23 and everything worked. I saw the captcha on the login page and I logged in. However for some reason, after I logged out I could not see any captcha. Is there any way to fix this? Now I'm stuck and can't login.
I don't know if you can see it clearly, but there is a small dot between Code and Login. This is where the captcha is supposed to show up.
![Untitled2](https://user-images.githubusercontent.com/50428238/57414102-8399ba80-71ff-11e9-941c-9d0005e1084f.png)

Cheers!

**Comment by Jimmi08** [comment]
This happened to me on my old Nuke site too with PHP 5.6. I spent days on it, it's a common issue if you look for it. But it happened on live site too, so...  then I found it has something with error reporting. I set it off on live site, but hosting has its own settings.  Try to set PHP error reporting off at first and you will see. And error log on xampp.

**Comment by Moc** [comment]
Also check if the GD extension is enabled

Btw, e107 should work fine with PHP 7.1 and 7.2. The 7.3 release is more challenging.

**Comment by sparuj** [comment]
> This happened to me on my old Nuke site too with PHP 5.6. I spent days on it, it's a common issue if you look for it. But it happened on live site too, so... then I found it has something with error reporting. I set it off on live site, but hosting has its own settings. Try to set PHP error reporting off at first and you will see. And check error log on xampp.

The thing is I tried different versions of php and it was the same.
Error reporting on xampp was off by default.
This is what I found in the error log
[error.log](https://github.com/e107inc/e107/files/3161759/error.log)

**Comment by Jimmi08** [comment]
@Moc he uses old version, not version
Did you try PHP 5.5?  Because I still think it was something with xampp related vs 5.6

**Comment by Jimmi08** [comment]
I use 1.0.4 with php 5.6.39  on live site with captcha.  And I had to have on localhost 5.3  because xampp. 
 
![image](https://user-images.githubusercontent.com/5429548/57449804-22083900-725d-11e9-94cf-fa28e3b8e4f3.png)

**Comment by sparuj** [comment]
@Jimmi08 Yes. I tried downgrading every php version from latest to 5.3. Also my e107 version should be 0.7

**Comment by Jimmi08** [comment]
@sparuj did you downgraded only PHP version or did you install XAMPP with that PHP version? Maybe on live site, it will work.  By the way, there is recaptcha plugin for version 0.7:  https://github.com/Jimmi08/recaptcha

**Comment by Moc** [comment]
Issues with v1 should be posted here: https://github.com/e107inc/e107v1/issues

- Make sure you are using 1.0.4 (and not 0.7)
- PHP 5.6 max for v1 (perhaps even 5.3)

In fact, I recommend using v2. 

Closing this issue to avoid confusion with v2.
