### ISSUE TITLE
fpw.php and problem with hash

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3796]
This is link for pasword reset

![image](https://user-images.githubusercontent.com/5429548/57432875-4f41f080-7237-11e9-93ba-f163af8da126.png)
but because this test:

`	$tmpinfo = preg_replace("#[\W_]#", "", e107::getParser()->toDB(e_QUERY, true));			// query part is a 'random' number`

user is always redirected to frontpage
`	if ($tmpinfo != e_QUERY)`

![image](https://user-images.githubusercontent.com/5429548/57432935-6b459200-7237-11e9-93d7-8f9a11d3ed70.png)

Latest sync version of e107 is used

**Comment by Moc** [comment]
Discussed on Github. Code was changed in February: https://github.com/e107inc/e107/issues/3443

New hashes should only generate with `AaBbCcDdEeFfGgHhIiJjKkLMmNnPpQqRrSsTtUuVvWwXxYyZz` and no hashes or numbers. Probably used outdated/cached code which caused the hash to be there, which triggered the check and redirect. 

Closing
