### ISSUE TITLE
files to edit after backuping

### ISSUE THREAD

**Issue by sparuj** [e107inc/e107#3797]
Hello everyone!

I was wondering after I backup a website and upload it to another domain, host and etc. do I have to edit anything else besides e107_config.php or are there more files that I need to edit?

Cheers!

**Comment by Jimmi08** [comment]
You need to fix your hash folder. Or move everything from old to the new one (media and system folders)

See:
https://www.e107.sk/knowledge_base/hashed-names-for-media-and-system-folders/?content.50

**Comment by sparuj** [comment]
Thank you!
