### ISSUE TITLE
Report  - problem with installation

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3800]
> I am not able to use latest version on xampp php 7.2 - neverending update, database check says that tables are missing, but update says it can't update because tables already exists. It started with featurebox (installed with installation), after unistalling, core tables have problem. 

The reason is at the end, this is report.   

Without debug mode:
![image](https://user-images.githubusercontent.com/5429548/57569711-4b5dcc00-73f9-11e9-8355-383ba8cd1cac.png)

Just to show how long is this:
![image](https://user-images.githubusercontent.com/5429548/57569726-7811e380-73f9-11e9-9b38-20578c583c0d.png)

It starts:
```
Update Unsuccessful [CREATE TABLE `e107_admin_log` (dblog_id int(10) unsigned NOT NULL auto_increment, dblog_datestamp int(10) unsigned NOT NULL default '0', dblog_microtime int(10) unsigned NOT NULL default '0', dblog_type tinyint(3) NOT NULL default '0', dblog_eventcode varchar(10) NOT NULL default '', dblog_user_id int(10) unsigned NOT NULL default '0', dblog_ip varchar(45) NOT NULL default '', dblog_title varchar(255) NOT NULL default '', dblog_remarks text NOT NULL, PRIMARY KEY (dblog_id), KEY dblog_datestamp (dblog_datestamp)) ENGINE=MyISAM;]
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'e107_admin_log' already exists
Update Unsuccessful [CREATE TABLE `e107_audit_log` (dblog_id int(10) unsigned NOT NULL auto_increment, dblog_datestamp int(10) unsigned NOT NULL default '0', dblog_microtime int(10) unsigned NOT NULL default '0', dblog_eventcode varchar(10) NOT NULL default '', dblog_user_id int(10) unsigned NOT NULL default '0', dblog_user_name varchar(100) NOT NULL default '', dblog_ip varchar(45) NOT NULL default '', dblog_title varchar(255) NOT NULL default '', dblog_remarks text NOT NULL, PRIMARY KEY (dblog_id), KEY dblog_datestamp (dblog_datestamp)) ENGINE=MyISAM;]
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'e107_audit_log' already exists
```

With debug mode:
```
Missing table on db-verify: admin_log
Missing table on db-verify: audit_log
Missing table on db-verify: banlist
Missing table on db-verify: comments
Missing table on db-verify: core
Missing table on db-verify: core_media
Missing table on db-verify: core_media_cat
Missing table on db-verify: cron
Missing table on db-verify: dblog
Missing table on db-verify: generic
Missing table on db-verify: links
Missing table on db-verify: mail_recipients
Missing table on db-verify: mail_content
Missing table on db-verify: menus
Missing table on db-verify: news
Missing table on db-verify: news_category
Missing table on db-verify: online
Missing table on db-verify: page
Missing table on db-verify: page_chapters
Missing table on db-verify: plugin
Missing table on db-verify: rate
Missing table on db-verify: submitnews
Missing table on db-verify: tmp
Missing table on db-verify: upload
Missing table on db-verify: user
Missing table on db-verify: userclass_classes
Missing table on db-verify: user_extended
Missing table on db-verify: user_extended_struct
Update required in update_routines.php on line 554 (Database Tables require updating: admin_log, audit_log, banlist, comments, core, core_media, core_media_cat, cron, dblog, generic, links, mail_recipients, mail_content, menus, news, news_category, online, page, page_chapters, plugin, rate, submitnews, tmp, upload, user, userclass_classes, user_extended, user_extended_struct)
```
Check database validity:

![image](https://user-images.githubusercontent.com/5429548/57569745-e191f200-73f9-11e9-8b47-cd66378c6e79.png)

![image](https://user-images.githubusercontent.com/5429548/57569760-14d48100-73fa-11e9-8c00-e7b9b7351f5d.png)

after attempt to fix:
`Update Unsuccessful [CREATE TABLE `e107_admin_log` (dblog_id int(10) unsigned NOT NULL auto_increment, dblog_datestamp int(10) unsigned NOT NULL default '0', dblog_microtime int(10) unsigned NOT NULL default '0', dblog_type tinyint(3) NOT NULL default '0', dblog_eventcode varchar(10) NOT NULL default '', dblog_user_id int(10) unsigned NOT NULL default '0', dblog_ip varchar(45) NOT NULL default '', dblog_title varchar(255) NOT NULL default '', dblog_remarks text NOT NULL, PRIMARY KEY (dblog_id), KEY dblog_datestamp (dblog_datestamp)) ENGINE=MyISAM;]`

SQL debug:
```
Array
(
    [0] => Array
        (
            [file] => G:\php72\htdocs\e107-gaia\e107_handlers\mysql_class.php
            [line] => 551
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => SHOW TABLES FROM  e107-gaia LIKE 'e107_%' 
                )

        )
```

After using query directly in phpmyadmin:
`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-gaia LIKE 'e107_%'' at line 1`

After changing the database to e107gaia -  without dash, it works.  No idea why this is a problem now, I used a database with dash on localhost very often.

**Comment by CaMer0n** [comment]
@Jimmi08 Server related maybe? e107 will support hyphens, but I believe some servers don't like it.

**Comment by Jimmi08** [comment]
@CaMer0n It was xampp installed on localhost.  And it happened only update from 2.1.9 to 2.2.0

**Comment by tgtje** [comment]
Hi, found a remarkable issue in regards to this when answering and testin an issue from Veskoto.( in working with language packs).
I used for different installs (and tests) the newest xamp php 7.3.5 10.1.40-MariaDB (PDO). and Git version about 1/2 hour old

2 things (after a lot of installs....pfff) 
case 1 : Now assume i did not read good enough when let create sql dbase during install and used **numbers only... No problem installs runs nice.**. all things go as should. Entering admin it will check for db updating (rotating gif) Using BS3 or Voux is equal. Now i get a response there's update available (core on boith themes and only 1for featurebox on Voux. Now hitting either core or featurebox (does not matter) will display the identical listing as posted above.

case2 : Now i install with dbasesql name starting **with letter;** agin on BS3 and Voux.
BS3 db update has NO update needed. Voux does need core db update. Now hitting that core update in Voux works fine (no errors). Mind difference..featurebox update is not in this db update..

In case 2 there ar no issues to be seen...  Case 1 throws those errors... 
Makes any sense ??

**Comment by CaMer0n** [comment]
Thank you @tgtje . This is helpful. Are you referring to the prefix, the database name or both? (re : numbers)

**Comment by tgtje** [comment]
When installing the _name for the database_ (sql) when (by accident... if not read the tooltip) only numbers are put in. 
When starting (as in tooltip displayed! ) with a Letter (capital or normal) no issues.

Strange that sql (or install) is accepting the 'wrong' primary input (identifiers...guess that the name for it?...unknown area for me) in a later stage (after install) it messes up things.

**Comment by tgtje** [comment]
@CaMer0n In addition; took the time to do some more installs (not upgrading) but now used a 2.2.0 Git version (dd 03-30-19) and run some.
To eliminate any possible closed issues/commits between 30-3 v 2.2.0 and latest 2.2.1 i also used some with and without Voux theme (as that is 'pre install select).
Outcome ( testing ONLY the databasename with numbers vs letters).

I may conclude that when using ONLY numbers the auto update check (install works) triggers to update.
(those will give issues... strange that always core and featurebox appear).

repeating with starting letter : ok (On using Voux > dbase update appears, but hitting core update = fine)

Now the outcome presented is.. does the position of the letter have influence ?... 
NO  either the first one or any where in between does NOT matter. 
_As long (so it seems) there IS a letter in there_ somewhere it will give me an ok result. 

Now did also some extra php version (5.6.3 and 7.2.2) same.
Last test and maybe this should be tested with the problematic sites since i can only do it on installs.
Last ( with success ! i _renamed the database names (which had numbers only) to have a letter in there_.
Adjusting  the config file to new name.. ehh voila **refresh**... my issues are gone

**Comment by CaMer0n** [comment]
Thank you @tgtje I have a made a minor change to install.php

**Comment by CaMer0n** [comment]
@Jimmi08 What is your database name?

**Comment by Jimmi08** [comment]
@CaMer0n  e107-gaia

**Comment by CaMer0n** [comment]
@Jimmi08 Okay Thanks. So just the hyphen is causing the issue.
