### ISSUE TITLE
Q - how to style / choose theme layout for error page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3801]
How to set layout for error page?

I found that not the existing page is using the default layout.  So if default layout is with sidebar,  how to get full page layout for error page?   

EDIT:
if I use Redirect to System not found page, then URL is /error/  and it can be set in theme layouts. But not without this setting.  Am I missing something?

**Comment by CaMer0n** [comment]
@lonalore may know more about this.

**Comment by Moc** [comment]
Does setting  `error.php$` help?

**Comment by Moc** [comment]
@Jimmi08 Can this be closed?

**Comment by Jimmi08** [comment]
Not sure
 
with wrong url there is no redirection to error.php, URL is still the same, so layout with the sidebar is displayed (because it is default)

with system redirection ON (Redirect to System not found page) is final ulr
/?route=system/error/404&type=routeError
so error$ is working

On second thought... maybe the problem is in the old approach to layouts... blog layout was mostly the default one.   
Not important now. Closing.
