### ISSUE TITLE
Q how to make captcha more darker

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3802]
I was asked this question. I can see that color CCCCCC is used, but is it possible to change to something darker?

![image](https://user-images.githubusercontent.com/5429548/57694356-ccac9d00-764b-11e9-9cec-59d6cba6e49e.png)

With 222222 it looks like this:
 
![image](https://user-images.githubusercontent.com/5429548/57694573-5f4d3c00-764c-11e9-997a-ff6975ae3790.png)

How to change this?  Or it's theme thing?

Thanks

**Comment by Moc** [comment]
`define('e_CAPTCHA_FONTCOLOR','#222222');` in theme.php

**Comment by Jimmi08** [comment]
Thank you. It works.

**Comment by Jimmi08** [comment]
Just note, this is normal?
First change:
![image](https://user-images.githubusercontent.com/5429548/57711743-9bde5f00-766f-11e9-812a-d5f21837c092.png)

refresh page:

![image](https://user-images.githubusercontent.com/5429548/57711769-ad276b80-766f-11e9-815a-016272f2c63a.png)

**Comment by Moc** [comment]
I think so, yes
