### ISSUE TITLE
menu manager error for themes with dash in name

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3807]
Tested with Basic light too (basic-light is theme name), not only Gaia and Denice.

The error looks like this:
 
![image](https://user-images.githubusercontent.com/5429548/57911142-3f558c80-7887-11e9-9874-818b57c58914.png)

Error is caused by this line:

`$themeFileContent = str_replace('tablestyle', $theme."_tablestyle",$themeFileContent); // rename function to avoid conflicts while parsing.`

  Manual testing:    
![image](https://user-images.githubusercontent.com/5429548/57911321-c4d93c80-7887-11e9-8622-510f04f4acc5.png)

after removing dash
 
![image](https://user-images.githubusercontent.com/5429548/57911368-e20e0b00-7887-11e9-8199-892b5555741e.png)

my quick fix:
```
		$search = array("_","-");
		$replace = array("","");
		$theme2  = str_replace($search,$replace,$theme);	
   	$themeFileContent = str_replace('tablestyle', $theme2."_tablestyle",$themeFileContent);

```

Thanks

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 !! :+1:
