### ISSUE TITLE
V2.2 Available in Softaculous?

### ISSUE THREAD

**Issue by ithinkmatt** [e107inc/e107#3810]
We like using Softaculous to easily deploy and backup software.

We are looking and currently testing CMSs to use instead of WordPress on basic websites. The version on Softaculous is 2.19.

Will V2.2 be available on Softaculous in the future?

**Comment by Moc** [comment]
Yes! We are working with them to make sure the latest version is available through Softaculous as well. Unfortunately there's a minor issue preventing them from being able to update, and we are fixing it shortly. 

I expect 2.2.0 to be available on Softaculous within two weeks.

**Comment by ithinkmatt** [comment]
@Moc Great. Thanks for the update.

**Comment by Moc** [comment]
@ithinkmatt We have just released an update (v2.2.1) which solved an issue that prevented Softaculous from updating their package. They will be testing the v2.2.1 update shortly. Once that is done, the latest version will be available through Softaculous.

**Comment by Moc** [comment]
I recently had some other people asking me about the update on Softaculous, as it is still on 2.1.9. I will check what the status is on this.

**Comment by CaMer0n** [comment]
Sent another email and a tweet. We wait and see.

**Comment by Moc** [comment]
@ithinkmatt It took a while but they have finally updated e107 to v2.2.1. 
Closing this issue :)
