### ISSUE TITLE
Database Test

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#3811]
Can everyone tell me, what this is and how I can repair it? This is for 32 tables the same, I want not make a so big Picture.

![image](https://user-images.githubusercontent.com/17859550/58248508-9a422480-7d5c-11e9-82ef-cd5ac170a7d3.png)

**Comment by tgtje** [comment]
Related or identical #3800

**Comment by TrueHatori** [comment]
Not quite. My English is not so good, but if I understood correctly, it is in xampp. For me it's about a live server.
Apache API Version 20120211, MySQL Server Version: 5.6.43-84.3-log, PHP Version 7.2.18-he.0
I do not know if that is relevant, but something should be done … ;)

**Comment by Moc** [comment]
Are you using the latest files from Github?

**Comment by tgtje** [comment]
Yes testcases are primary local, but (can be sql related for you too) If it happens local, it could indicate (hence tests) live has/gets issues too... This case similarity is to be seen in both cases...

**Comment by TrueHatori** [comment]
@Moc: Whether it's the very latest, I do not know, got the last time in mid-March, all files from Github.

**Comment by Moc** [comment]
@TrueHatori In that case, I do recommend updating to the latest files from Github to make sure you have all fixes included. 

Then clear your e107 cache and see if the issue persists.

**Comment by TrueHatori** [comment]
Ok, I did, the problem is the same as before. In addition, the admin theme tabbed does not work anymore.

**Comment by Moc** [comment]
@TrueHatori This should be fixed with the latest files. Please check.

**Comment by TrueHatori** [comment]
Yes, with v2.2.1 it works ;)
