### ISSUE TITLE
Fatal error in Menu Manager

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#3815]
Hello all,

i have a problem about my Menu Manager, site is blank and have this error:

PHP Fatal error: Uncaught Error: Call to undefined function deftrue() in /var/www/_[EGU]Seiten/homepage/class2.php:2385\nStack trace:\n#0 /var/www/[EGU]_Seiten/homepage/e107_config.php(41): error_handler->handle_error(8, 'Constant eDEBU...', '/var/www/[EGU]...', 41, Array)\n#1 /var/www/_[EGU]Seiten/homepage/class2.php(218): include('/var/www/[EGU]...')\n#2 /var/www/_[EGU]_Seiten/homepage/admin/menus.php(40): requireonce('/var/www/[EGU]...')\n#3 {main}\n thrown in /var/www/_[EGU]_Seiten/homepage/class2.php on line 2385

any idea? ;)

greeting, Killer0561 (Sascha)

**Comment by Moc** [comment]
Confirmed. I have the same issue on my local windows installation. I don't have the issue on my live Linux installations.

**Comment by CaMer0n** [comment]
@Moc Please confirm. Thanks.
