### ISSUE TITLE
SQL insert error after adding language packs

### ISSUE THREAD

**Issue by Naktsputns** [e107inc/e107#3816]
Hello, I upgraded to version 2.2 and everything was fine, but after language packs was added, cant create new page/menu. News, chapter pages and everything else working fine. Aswell i can directly create new page in SQL table. After that i can copy/modify that page inside e107 without any trouble.

**Comment by Moc** [comment]
Which language?

**Comment by CaMer0n** [comment]
@Naktsputns Please go to this URL on your site: `e107_admin/page.php?[debug=showsql+] ` and then reproduce the issue. What errors do you see?

**Comment by Naktsputns** [comment]
To Moc: I fixed latvian language pack

To CaMer0n: System Debug
searchQuery:
Array
(
)
Using Custom listQry
QRY=SELECT SQL_CALC_FOUND_ROWS p.*,u.user_id,u.user_name FROM e107_page AS p LEFT JOIN e107_user AS u ON p.page_author = u.user_id ORDER BY p.page_order asc

**Comment by Naktsputns** [comment]
To Moc: I fixed latvian language pack

**Comment by Naktsputns** [comment]
System Debug
Admin-ui Trigger fired: admin_page_create
SQL Qry:
Array
(
    [_FIELD_TYPES] => Array
        (
            [page_id] => int
            [page_title] => str
            [page_chapter] => str
            [page_template] => str
            [page_author] => int
            [page_text] => str
            [page_datestamp] => int
            [page_class] => str
            [page_rating_flag] => int
            [page_comment_flag] => int
            [page_password] => str
            [page_sef] => str
            [page_metakeys] => str
            [page_metadscr] => str
            [page_order] => str
            [page_fields] => json
            [menu_name] => str
            [menu_title] => str
            [menu_text] => str
            [menu_template] => str
            [menu_class] => int
            [menu_button_text] => str
            [menu_button_url] => str
            [menu_icon] => str
            [menu_image] => str
        )

    [data] => Array
        (
            [page_id] => 
            [page_title] => asd
            [page_chapter] => 0
            [page_template] => default
            [page_author] => 1
            [page_text] => 
            [page_datestamp] => 1559068976
            [page_class] => 0
            [page_rating_flag] => 0
            [page_comment_flag] => 0
            [page_password] => 
            [page_sef] => asd
            [page_metakeys] => 
            [page_metadscr] => 
            [page_order] => 4
            [page_fields] => 
            [menu_name] => 
            [menu_title] => ffff
            [menu_text] => 
            [menu_template] => default
            [menu_class] => 0
            [menu_button_text] => 
            [menu_button_url] => 
            [menu_icon] => 
            [menu_image] => 
        )

)
SQL Error #23000: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'menu_name' cannot be null
SQL QRY Error
Array
(
    [_FIELD_TYPES] => Array
        (
            [page_id] => int
            [page_title] => str
            [page_chapter] => str
            [page_template] => str
            [page_author] => int
            [page_text] => str
            [page_datestamp] => int
            [page_class] => str
            [page_rating_flag] => int
            [page_comment_flag] => int
            [page_password] => str
            [page_sef] => str
            [page_metakeys] => str
            [page_metadscr] => str
            [page_order] => str
            [page_fields] => json
            [menu_name] => str
            [menu_title] => str
            [menu_text] => str
            [menu_template] => str
            [menu_class] => int
            [menu_button_text] => str
            [menu_button_url] => str
            [menu_icon] => str
            [menu_image] => str
        )

    [data] => Array
        (
            [page_id] => 
            [page_title] => asd
            [page_chapter] => 0
            [page_template] => default
            [page_author] => 1
            [page_text] => 
            [page_datestamp] => 1559068976
            [page_class] => 0
            [page_rating_flag] => 0
            [page_comment_flag] => 0
            [page_password] => 
            [page_sef] => asd
            [page_metakeys] => 
            [page_metadscr] => 
            [page_order] => 4
            [page_fields] => 
            [menu_name] => 
            [menu_title] => ffff
            [menu_text] => 
            [menu_template] => default
            [menu_class] => 0
            [menu_button_text] => 
            [menu_button_url] => 
            [menu_icon] => 
            [menu_image] => 
        )

)

**Comment by Naktsputns** [comment]
That strange, i named Menu, but it all the time reverting menu_name to my user name

**Comment by CaMer0n** [comment]
@Naktsputns Thank you! If you update to this version on github, and run the database update, normally this error should no longer occur.

**Comment by Naktsputns** [comment]
Thank you! Everything is fine now.

**Comment by Jimmi08** [comment]
> That strange, i named Menu, but it all the time reverting menu_name to my user name

It's because of Chrome behaviour and prefilling input fields a weird way.  I would kill sometimes for this and sometimes I notice this only in menu manager when I see a weird menu with the user name.  And it's not only this field.  There is already an issue about this.
