### ISSUE TITLE
question  - mysql gen() function

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3820]
I have a question to gen() 
the description says: Function to handle any MySQL query 

I know that I can use `count()` method, but this is about saving time - to use the original query from the script I am trying to adapt.

My query is "SELECT COUNT(*) FROM #table"  

but using gen() never returns 0, it always return 1,  because there is no error in query. 
	
> Returns TRUE if the query is successful, and it does not return a row count

but I can see it uses this part
```
		else
		{	// Successful query which does return a row count - get the count and return it
			$this->dbError('db_Select_gen');       
			return $this->rowCount();
		}
```
 
Maybe you should add the warning to the description that this doesn't work for SELECT COUNT...  and not for any query. 

```
      // something wrong with insert data
      if ( $sql->gen( "SELECT COUNT(*) FROM #table" ) == 0 ) {
        return true;
      }
```

If this helps:
```
PDOStatement Object
(
    [queryString] => EXPLAIN SELECT COUNT(*) FROM e107_redirection_groups  
)
```
returned value:
`int(1)`
$this->rowCount()); has value 1
it's PDO and php 7.2

**Comment by SimSync** [comment]
If you want the "value" from the `COUNT(*)` column, you need to use the `fetch()`command to get the value from the `COUNT(*)` column. That's why it is easies to use the `e107::getDb()->count('table', '(*)')` command.

With `e107::getDb()->gen('SELECT COUNT(*) FROM table')` you need this commands:

```
if ($sql->gen('SELECT COUNT(*) FROM table')) {
   $row = $sql->fetch(PDO::FETCH_NUM); // Fetch row from query
   $row_num = $row[0]; // It's field 0 from that row that contains the result from the COUNT(*) function
}
```

**Comment by Jimmi08** [comment]
@SimSync I understand, but I am a problem with this in the documentation:  the description says: Function to handle any MySQL query. It doesn't handle **any** MYSQL query.

**Comment by SimSync** [comment]
@Jimmi08 Which query is not handled?
It handles the (any) query (tablename only or complex sql string) by fixing the tablenames (prefix), but it doesn't return a result (in terms of returning the queried fielddata). 
It only returns if the query failed (false), the number of records (on SELECT queries) or true on INSERT, UPDATE, etc. queries.
If you want to get the result (the queried field data) out of your query in one go, you must use `$sql->retrieve()`.
In the end, it's just a definition of what "handles" could be meant with. If you have a better term...?

**Comment by Jimmi08** [comment]
Hm, maybe I understood the word "handle" wrong way.  Ok, so I should use this only to execute the query and don't wait for any data back. Yes, it's clear now, and using fetch() too. 
Thank you
