### ISSUE TITLE
Preferences are not complete

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#3821]
I still can not do all the presets.
![image](https://user-images.githubusercontent.com/17859550/58761075-3a0f6780-8540-11e9-9f9a-e342d9e87edb.png)

There is no more, nothing more. I can not activate the tinymce. But I have to write something urgently. Can I somehow activate the TinyMce differently? Before the update to v.2.2.1 he was active.
![image](https://user-images.githubusercontent.com/17859550/58761267-b0ad6480-8542-11e9-8395-0cff920fd464.png)

**Comment by Moc** [comment]
Please check the browser console for any errors or warnings

**Comment by TrueHatori** [comment]
TinyMCE has done it, there is a new JavaScript in it from yet another source. That was not yet released in the FF plugin NoScropt, sorry.

Konsole:
SyntaxError: unexpected token: identifier - prefs.php:1860:5
TypeError: $(...).find(...).once is not a function - selectize.init.js:67:52
    attach http://www.ninja4ever.de/e107_web/js/selectize/js/selectize.init.js?1559481688:67
    each jQuery
    attach http://www.ninja4ever.de/e107_web/js/selectize/js/selectize.init.js?1559481688:66

Then this, can not copy ist:
![image](https://user-images.githubusercontent.com/17859550/58763190-06403c00-8558-11e9-8165-3d8c9c4b1eed.png)

**Comment by Moc** [comment]
So did you fix it now or is it still broken?

**Comment by TrueHatori** [comment]
TinyMCE is ok, but not the preferences. There are even more, where nothing is in it.
Security & Protection is completely empty, as well as Javascript Framework and Advanced Settings.

I do not think it's great that you include so many javascripts from different sources, this time Cloudflare. Any source I need to share with Javascript is a potential risk.

**Comment by Moc** [comment]
> TinyMCE is ok, but not the preferences. 

What does the console say on the preferences page? Is that the extract you posted in your previous reply? 

> I do not think it's great that you include so many javascripts from different sources, this time Cloudflare. 

e107 uses CDN's, which is a common method to optimise performance (loading times mostly) for visitors. You can change this to 'local files' in the preferences (when they are working again for you).

**Comment by TrueHatori** [comment]
![image](https://user-images.githubusercontent.com/17859550/58802303-1f56f480-860d-11e9-9551-35515b41df9d.png)

That is all that can be read in the console.

And the Plugins:
![image](https://user-images.githubusercontent.com/17859550/58802490-98564c00-860d-11e9-9bf8-3c65e688d504.png)

The presets did not work right after installation, without any plugins installed. The problem was and is always the same. Ok, I do not need comments and file uploads, but the rest is important.

![image](https://user-images.githubusercontent.com/17859550/58802900-9345cc80-860e-11e9-9049-fe1b6adf88bb.png)

![image](https://user-images.githubusercontent.com/17859550/58802964-ab1d5080-860e-11e9-829e-e3e945c3ec40.png)

![image](https://user-images.githubusercontent.com/17859550/58802718-292d2780-860e-11e9-95cc-f991c9bac5f5.png)

![image](https://user-images.githubusercontent.com/17859550/58802763-4104ab80-860e-11e9-87a9-7f8014eb0622.png)

![image](https://user-images.githubusercontent.com/17859550/58802796-51b52180-860e-11e9-8c67-0c1484ed45f0.png)

**Comment by Moc** [comment]
Can you switch back to the English language temporarily to see if that makes a difference? 

If not, please enable debug mode by editting the URL to /e107_admin/prefs.php?[debug=basic+]

Now PHP warning or errors may show up.

**Comment by Moc** [comment]
So there's an error in the German language pack somewhere. Are you using the latest Language pack for 2.2.1? https://github.com/e107translations/German/

I have asked @Killer0561 to upload the latest files, rather than to just upload a ZIP file in the releases section. For now you will need to upload the latest files manually until the files on Github are updated.

**Comment by TrueHatori** [comment]
I have this: https://github.com/e107translations/German/releases/tag/v2.2.1
Have copied the files over the old ones.

**Comment by Moc** [comment]
Please submit this as an issue here: https://github.com/e107translations/German/issues

Did you download this file? https://github.com/e107translations/German/releases/download/v2.2.1/e107_2.2.1_German_de_DE-utf8.zip

**Comment by TrueHatori** [comment]
Yes, exactly this file ... I downloaded it this morning, unzipped it and copied the new files over the old ones.

**Comment by Moc** [comment]
You don't need to click install. Then it will retrieve the outdated files again. So simply overwrite it, and leave it as it is. If that doesn't fix it, please create an issue for it in the German translation repository linked above. 

I'm closing this issue here, as it is not a core issue. I'll help you further in a new issue in the German translation repository.
