### ISSUE TITLE
question - replace constants

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3822]
Just note.

I noticed that from shortcodes replaced in replaceConstants() 
those are not replaced in relative mode
{e_MEDIA_VIDEO}
{e_MEDIA_IMAGE}
{e_MEDIA_ICON}
{e_WEB_IMAGE}

But they are correct in the absolute mode.
It's not probably the intention, because there is $e107->getFolder() used and not '' like with not replaced shortcodes.

I use the only full path, so it's not a real problem for me,  but maybe you would like to know about this.

**Comment by Jimmi08** [comment]
@Moc Invalid, not needed anymore (2019!)
Thanks

**Comment by Moc** [comment]
I think this was corrected since, or at least made more consistent, but not sure. Keeping it closed.
