### ISSUE TITLE
feature request -  templating contact page 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3826]
Actual state:
- content of contact.php is displayed in {---) and you can use tablerender()
- 2 parts have different templates already (contact info and contact form

Problem:
- contact info is always rendered before form 

With different position, it's a bit complicated to get this right (in fact contact info code has to be moved to form template in theme)

Suggestion:
- to use contact _page_ template for layout with 2 shortcodes - (CONTACT_INFO} and {CONTACT_FORM}  
- there is already contact plugin, so maybe make those shortcodes as global {e_shortcode} would be a good idea
- default template would be exactly the same as is now hardcoded in contact.php
- {CONTACT_INFO} would use already existing info template and {CONTACT_FORM} form template
- it's similar like with comment $COMMENT_TEMPLATE['layout'] so this could be called similar way - $CONTACT_TEMPLATE['layout']

Thanks

**Comment by CaMer0n** [comment]
`$CONTACT_TEMPLATE['layout']` sounds like a good approach. Similar to the comments template.

**Comment by Jimmi08** [comment]
In this commit, you have an example how it should work. (don't mind fix for 2.2.1)
https://github.com/Jimmi08/bootstrap4/commit/1b7061f08c62e40d3db942d7bd76398a959d3179

The second problem is that both tablerenders have the same IDs. I think there is already an issue about this. 
Layout for contact is only header and footer, everything else is managed with contact template. 

For me, this is solved because I am able to use it now with 2.2.1.  So milestone this in the future, if you want.

**Comment by Jimmi08** [comment]
No needed anymore

**Comment by Jimmi08** [comment]
It is solved
