### ISSUE TITLE
forum templating - probably ranks ?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3827]
Sorry, I haven't time to look from where is this now, but there is some shortcode what output empty HTML code.  
PS. I am trying to avoid custom theme template. 

If the value is empty, it should return nothing or there should be some default value (f.e. user, quest) so there would be always something displayed.

![image](https://user-images.githubusercontent.com/5429548/58951196-c6b06480-8790-11e9-957f-dd01b6f25faa.png)

**Comment by CaMer0n** [comment]
Yes, if there is no value is should return null, so that shortcode wrappers can know not to render.

**Comment by Jimmi08** [comment]
> so that shortcode wrappers can know not to render.

Correct.  The problem is that wrappers render something or it doesn't return null. There is reductant html code, but <span> tag.

**Comment by Moc** [comment]
Wasn't able to reproduce on a test install, but added a fix which which may help. 
@Jimmi08 When you have time, can you check to see if this solves the issue?

**Comment by Jimmi08** [comment]
Solved.
