### ISSUE TITLE
Feature request - possibility to use e_help with theme manager

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3834]
With Site theme adding new menu like with e_help.php with plugins. 
Just if this file exists inside the theme folder, load it.  (if it's possible :) )
Thank you

**Comment by CaMer0n** [comment]
@Jimmi08 e_help.php (which was always specific to the admin area) has been deprecated in favor of the Admin-UI renderHelp() method. 

Theme Manager will display an extra tab for Help if the help() method is found in the theme_config.php.

**Comment by Jimmi08** [comment]
Thank you. e_help is easier to maintain and copy than the method in admin UI but what to do.
