### ISSUE TITLE
not working comments

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3836]
Tested, it works with php 5.6
But I have new demo site on version 7.2 (not sure if it's related)

- version 2.2.1 from e107.org is used, not latest github version

- I switched to bootstrap3 to be sure it's not theme related or bootstrap version.

After click on button Send it looks like nothing happened, but comment is visible after refresh.

There is error in console: 
 
![image](https://user-images.githubusercontent.com/5429548/59225208-6d04cb80-8bd0-11e9-9e43-8cf4e27ea196.png)

Thanks

**Comment by Moc** [comment]
Yeah reproduced, still need to test this further to see what's causing it.

**Comment by CaMer0n** [comment]
I just tested submitting a news comment using Firefox. I had no issue.

**Comment by CaMer0n** [comment]
@Moc Traced this to debug code attempting to be parsed as json.

**Comment by Moc** [comment]
I think this only occurred in debug mode, right?

**Comment by Jimmi08** [comment]
Yes, and only in one case. It was probably related to multisite version of site. Some weird debug output code was there (I probably messed up something, not problem in plugin itself)
Fixed now with CaMeRon help. Thanks
