### ISSUE TITLE
problem with checkbox, discussion

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3838]
I am missing something somewhere.... 

Standard checkboxes work but look ugly.  My theme uses very nice checkboxes (nothing special, only CSS). 

code is here:
```
<div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>
```

I am trying to fix this shortcode:
{LOGIN_TABLE_REMEMBERME}

 I am not able to rid label tags. From the code it should be inserted only if _label_ parameter is used, but it's always there.  
Normally I use javascript to change some hardcoded classes, but I wasn't able to do this now.

So I gave up and hardcoded this in the template this way.
```
        <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="autologin">
                <label class="custom-control-label" for="autologin"> '.LAN_LOGIN_8.'</label>
        </div>
```
It looks good, but first checkbox is not clickable (second one is original code)
![image](https://user-images.githubusercontent.com/5429548/59273707-1d1e1700-8c59-11e9-8596-e174c37eb715.png)

Problem is caused with ID autologin, as soon as I changed it to something else, it worked. 

So:
- how to rid the label around checkboxes or how to get only input value for checkbox tag?
- has somebody idea why ID autologin cause problem? (I checked code, theme doesn't use it at all)

Thanks

**Comment by Jimmi08** [comment]
There is no way how to get only input code for checkboxes. For example Remember me. 

I have again the similar code:  Label tags are after input tag
```
<div class="col-6 col-12-small">
	<input type="checkbox" id="checkbox-alpha" name="checkbox">
	<label for="checkbox-alpha">Checkbox alpha</label>
</div>
```
 
I had to use HTML code to fix this in login template:
```
 <div class="col-12">
			 <input type="checkbox" id="autologin" name="autologin">
			 <label for="autologin">'.LAN_LOGIN_8.'</label>
</div>
```

**Comment by tgtje** [comment]
I just throw it in, maybe related maybe not.. because you mentioned at first line missing somewhere

login_menu_shortcodes.php  line 185 ......196 maybe there's something that has influence on behaviour (so maybe a change on more instances needed ?? (possibly i miss something too, but i thought about that...

**Comment by Jimmi08** [comment]
No, it's something different. I often fix your problem (login_table_footer_userreg shortcode) with the theme shortcode or direct editing login template.  It's the shortcode for one use.  

My problem is that you can't use remember me {checkbox} without a label to fix this:

See? parameter label is always filled:
```
	function sc_login_table_rememberme($parm=array())
	{
		if(empty($this->userReg))
		{
			return null;
		}
		if(!isset($parm['label']))
		{
			$parm['label'] = LAN_LOGIN_8;
		}
		return e107::getForm()->checkbox('autologin',1,false,$parm);
	}
```

and then if parm label is filled, then form handler does this:

```
		$pre = (vartrue($options['label'])) ? "<label class='".$labelClass.$active."'{$labelTitle}>" : ""; // Bootstrap compatible markup
		$post = (vartrue($options['label'])) ? "<span>".$options['label']."</span></label>" : "";
...
return $pre.$text.$post;
```

But it's one type of behavior (label around input tag).  In most cases I have, the label tag is after the input tag.  I don't know how to override form handler with theme or other plugin. 

What I need is return this:  return $text.$pre.$post;  Or be able to use remember me without a label (I put the label to template then)

**Comment by CaMer0n** [comment]
@Jimmi08 Did you try this? 

```
{LOGIN_TABLE_REMEMBERME: label=}
```

**Comment by Jimmi08** [comment]
Great, It is working. Thanks
