### ISSUE TITLE
news vs tablerender - problem with {NEWSCATEGORY}

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3842]
{NEWSCATEGORY} - if it's used for **default layout** (not tried yet list layout)
returns category of some post  on news homepage (news.php)  

it should return some LAN  News or something 

`$NEWS_TEMPLATE['default']['caption'] =   '{NEWSCATEGORY} this is caption';  // add a value to user tablerender()`

![image](https://user-images.githubusercontent.com/5429548/59337815-93765400-8d01-11e9-8956-f9fccfa85a5a.png)

![image](https://user-images.githubusercontent.com/5429548/59339870-3da3ab00-8d05-11e9-80d5-200e12d1ac62.png)

EDIT: it works correctly for list layout. It returns NEWS then.

**Comment by CaMer0n** [comment]
@Jimmi08 You mean, when no category has been selected, you want {NEWSCATEGORY} to fall-back to "News". Is this correct?

**Comment by Moc** [comment]
@Jimmi08 Still relevant. Any feedback to Cameron's question?

**Comment by Jimmi08** [comment]
I think that using {NEWSCATEGORY} is confusing. And if it would return News, it was a workaround only.

It should be the News page title - and if you are on the category page, then NEWSCATEGORY should be returned..  
If you are on the News frontpage, then the News title should be returned (not sure if you can set the title in News preferences now)

**Comment by Jimmi08** [comment]
This is not relevant anymore
