### ISSUE TITLE
news category list - how to use category template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3843]
I have a news category listing

`/news/category/Fashion`

it's still using default template, but $NEWS_TEMPLATE['category'] exists.

Where to set this or how?

![image](https://user-images.githubusercontent.com/5429548/59339709-f74e4c00-8d04-11e9-88a3-40a33b3e59ed.png)

![image](https://user-images.githubusercontent.com/5429548/59339714-f9b0a600-8d04-11e9-9d71-5d76b6e4d208.png)

**Comment by CaMer0n** [comment]
@Jimmi08 The debug table is missing information. Please use the github version and repost. Most likely the database category has another template set.

**Comment by Moc** [comment]
@Jimmi08 Please check if it is still an issue

**Comment by Moc** [comment]
Please re-open if necessary.
