### ISSUE TITLE
contact page is redirecting to homepage

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3844]
version 2.2.1  from e107.org

```
$active = varset($pref['contact_visibility'], e_UC_PUBLIC);
$contactInfo = trim(SITECONTACTINFO);

if(!check_class($active) && empty($contactInfo))
{
	e107::getRedirect()->go(e_HTTP."index.php");
}
```

but my site contact info is filled

 
![image](https://user-images.githubusercontent.com/5429548/59342115-688ffe00-8d09-11e9-8d54-31fb7dd6f058.png)

**Comment by Jimmi08** [comment]
It's not caused with this. class2.php is doing this.

**Comment by CaMer0n** [comment]
@Jimmi08 What is the value for "Contact Form Visibility" ?

**Comment by Jimmi08** [comment]
Closing, because it's htaccess or something like this problem. After renaming file contact.php to something else, it works. So it's not in data
