### ISSUE TITLE
How to load language in Frontend theme config file in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3846]
in file theme_config.php  this doesn't work:  (you can this in bootstrap3 theme)

`e107::lan('theme', 'admin',true);`

it loads bootstrap3 theme LANs.  

This works:
`e107::themeLan('admin','bootstrap4', true);`

**Comment by CaMer0n** [comment]
That makes sense. It is being used in the admin area. :+1:

**Comment by Jimmi08** [comment]
@Moc this should be marked as documentation, it is not the issue (bootstrap3 is admin theme, so it's work), for any other theme with config file second calling is needed to use.
