### ISSUE TITLE
pdf icon has different classes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3861]
![image](https://user-images.githubusercontent.com/5429548/59765589-b3c48680-929e-11e9-8f5f-5248c447ba85.png)

**Comment by Moc** [comment]
it needs `btn-secondary` right?

**Comment by Moc** [comment]
Fixed in https://github.com/e107inc/pdf/commit/2bd28c3b171f6ba12aa03ecbb0dce9ecceea6c08
