### ISSUE TITLE
gsitemap manual entry doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3866]
Because this:
	`'WHERE'             => ' gsitemap_id= '.intval($_POST['gsitemap_id']) `
gsitemap_id is always 0 with new record, so no record is created.

**Comment by sudakk** [comment]
![1](https://user-images.githubusercontent.com/11300090/60599622-7809e080-9db7-11e9-9298-e892c2e0d052.jpg)

comment as I did - no need gsitemap_img & gsitemap_cat... and averything will work.

**Comment by Moc** [comment]
Please re-test and let me know, should be fixed :) 
If not, it should proper error information when debug is active.

**Comment by Jimmi08** [comment]
@Moc 
Debug ON, result:
It wasn't created.

![image](https://user-images.githubusercontent.com/5429548/66667851-42954e80-ec54-11e9-9f1c-666ef4256278.png)

**Comment by Moc** [comment]
Double check you updated the file correctly and clear your caches. This is still old information that is displaying.

**Comment by Jimmi08** [comment]
> Double check you updated the file correctly and clear your caches. This is still old information that is displaying.

Yes, I just noticed you posted fix.
