### ISSUE TITLE
e107_class -> set_paths(), infinite loop if invoking e107 from script in another directory

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#3867]
Hello; I'm not sure how worthy this is of attention, or how it might be fixed if it is.

I have some PHP scripts that I wish to be executed once per day, and I'm using a cron job for this purpose. Obviously I don't want these scripts to be accessible from the outside world, so per advice on Stackoverflow (and elsewhere) I've placed them into a directory separate from the web root, with a folder structure something like:

```
/--
   |---/cron_scripts
   |---/www (e107 lives here)
```

Some of these "cron scripts" make use of various e107 features, and I _require_once('class2.php')_ where this is so.

When one of these scripts is invoked, and processing reaches class2 line 286 (per commit b726dde), it passes to e107_class and the set_paths() function at line 4198 (per commit 1cca064).

There's a FIXME note here which highlights my issue:

```
// FIXME - Again, what if someone moves handlers under the webroot?
```

The 'while' at line 4212 (e107_class.php) enters into an infinite loop because the $path variable is never built into a viable file location for class2.php (it just keeps appending additional sets of '../' indefinitely).

Devs are clearly aware that this could be a problem because of the existence of the note. But I imagine that there are other more pressing issues currently under investigation in the code base. 

What's the best strategy for me here? Is it reasonable in such circumstances to simply place 'private' scripts in the web directory and use .htaccess to limit external visibility? Thank you.

**Comment by Moc** [comment]
> What's the best strategy for me here? Is it reasonable in such circumstances to simply place 'private' scripts in the web directory and use .htaccess to limit external visibility? Thank you.

Yes, I would recommend this as a temporary solution. The issue needs to be fixed in core, but as you said that are many other things that require attention. But now it is tracked here on Github, so that's good! :)

**Comment by sbwMikael** [comment]
Thanks Moc, I appreciate the feedback, I'll go ahead with this interim solution for now.

**Comment by Moc** [comment]
I'm keeping the issue open so it can be tracked on the future and fixed at some point :)

**Comment by Jimmi08** [comment]
Something similar is happennig to me but e107 is installed in subdirectory. 

/www - main site
/www/e107/  - e107 installation

I can't include / require class2.php in main site anymore.   And it worked before 2.0 or 2.1, not sure...  

I can confirm that it fails on line 286 class2.php and then on set_paths() ;

**Comment by Moc** [comment]
@CaMer0n @Deltik your thoughts please?

**Comment by Jimmi08** [comment]
I knew that I saw this somewhere else:
https://www.e107help.org/4996/including-e107-core-class2-outside-e107-directory-working

**Comment by CaMer0n** [comment]
Btw. set_paths was moved into e107_class.php in 2009.

**Comment by Deltik** [comment]
This is where the infinite loop is happening: https://github.com/e107inc/e107/blob/072c2a129a1134dc4acae9a38f8014752de0299f/e107_handlers/e107_class.php#L4503-L4507

**Comment by CaMer0n** [comment]
@Deltik And only a couple of complaints about it in 15 years. haha
