### ISSUE TITLE
Social login does not work?

### ISSUE THREAD

**Issue by sudakk** [e107inc/e107#3873]
![4](https://user-images.githubusercontent.com/11300090/60533661-d2983380-9d08-11e9-9f01-9a523729e939.png)
![3](https://user-images.githubusercontent.com/11300090/60533666-d6c45100-9d08-11e9-8ee4-60eb5dc59819.jpg)
After enable & testing /?route=system/xup/test I get false.
"Forbidden
You don't have permission to access /system/xup/login on this server."

**Comment by LaocheXe** [comment]
You got your Key/ID, Secret, and Scope set for Facebook?

**Comment by nesjett** [comment]
Social login works, I just tested a fresh install from git repo.
As LaocheXe said, you need to fill your facebook API data.

About accessing your site url, maybe you have some permission on some file wrong, I can access there properly

**Comment by sudakk** [comment]
@LaocheXe Yes, everything is filled in. But if it works, I will try to find what’s wrong by myself.
