### ISSUE TITLE
Question about social login

### ISSUE THREAD

**Issue by sudakk** [e107inc/e107#3875]
![1](https://user-images.githubusercontent.com/11300090/60593638-dfba2e80-9dab-11e9-838c-2fc5d446b04f.png)
![2](https://user-images.githubusercontent.com/11300090/60593645-e47ee280-9dab-11e9-996b-3ac27ba7c6aa.png)
I receive such mistake from any login provider. Why can the problem be?

**Comment by LaocheXe** [comment]
Might be server issue with permissions?

**Comment by sudakk** [comment]
Yes. Thank you for detailed answer.

**Comment by LaocheXe** [comment]
@sudakk well was it the issue, or not?

**Comment by sudakk** [comment]
![C2EDBBC8-FD18-40BE-90BE-288A6AE447EB](https://user-images.githubusercontent.com/11300090/60645735-36724780-9e42-11e9-9374-96f5dce8c32f.jpeg)
@LaocheXe Not completely understand: deny from all added for securities reason? Nobody uses social login now? It works without this rule.

**Comment by LaocheXe** [comment]
Odd, I use  it, for Steam Login - I've had the issue once, and dont remember what caused it.
