### ISSUE TITLE
Extended user fields saving data translated, (not supporting multinlang?)

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#3881]
Im trying to use the extended field gender and I find that I'm setting the values as, for example "UE_LAN_MALE" which is a constant for translations, thats ok.

The problem comes that when storing the value into the DB, the real value beign stored is "Male", in order of "UE_LAN_MALE"

Is there an easy solution/workaround to this?

** EDIT: I tried setting the value to "UE_LAN_MALE" in database by hand and is not beign recognized when in the usersettings.php (because it is trying to match by translated content and not by the lang code)

Thx

**Comment by CaMer0n** [comment]
This appears to be fixed. Closing, but please re-open if necessary.
