### ISSUE TITLE
comments in news return word Array

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3891]
php 5.6
latest github from 2.7.
pages works

 
![image](https://user-images.githubusercontent.com/5429548/60967912-1cda6f80-a31c-11e9-8a74-bd0a750f06d0.png)

no custom view news template, no  custom comment template

**Comment by Moc** [comment]
Confirmed

**Comment by CaMer0n** [comment]
hmm, I thought I fixed this already.

**Comment by Moc** [comment]
Hmmm, just updated again and cleared cache. Now it now longer appears. Seems fixed.

**Comment by Jimmi08** [comment]
Fixed.  No idea why I have to sync always 2x.
