### ISSUE TITLE
indexes in plugin_sql.php

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#3893]
Hello, seems that you cannot create indexes from this file (or I couldn't find a way)

Would be good and a great improvement for plugin developers to be able to configure table indexes for better performance.

Example of index creation for a plugin table in sql:
```
create index index_name
on plugin_table (table_cell);
```

Thank you

**Comment by Jimmi08** [comment]
you can use plugin_setup.php file  - see _blank plugin for inspiration
in plugin_sql.php you should have SQL for table with index already.

**Comment by Moc** [comment]
What happens when you use `INDEX (......)` within the CREATE TABLE statement in plugin_sql.php?

If you want to add it after the table already has been created, you need to use the setup file indeed: plugin_setup.php.

**Comment by nesjett** [comment]
Solved with plugin_setup.php

Thank you
