### ISSUE TITLE
breadcrumbs - problem with pages

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3894]
Reported by user with standard page template  (no chapter, single page)
Template without breadcrumb shortcode outputs:
```
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="/"><i class="fa fa-home"><!-- --></i></a></li>
</ul>
```
In my case, only {CHAPTER_BREADCRUMB} is used. 

Now confirmed with magic shortcode
For single page, output is only

```
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="/"><i class="fa fa-home"><!-- --></i></a></li>
</ul>
```

For page with chapter, page breadcrumbs and magic breadcrumbs are correct.

**Comment by CaMer0n** [comment]
This has been corrected to it's previous output which is **null** when no chapter is in use. 
However, the magic shortcode is a "universal breadcrumb" and the output should be: 

```
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href='/e107v2/'><i class='fa fa-home' ><!-- --></i></a></li>
<li class='breadcrumb-item'>My Page Title</li>
</ul>
```
