### ISSUE TITLE
question - why this old code doesn't work?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3895]
Normally, old shortcode way still works. 
But now I hit on plugin what uses this way:

```
include_once(e_HANDLER . 'shortcode_handler.php');
$cat_shortcodes 	 = e107::getParser()->e_sc->parse_scbatch(__FILE__);
$global_shortcodes = e107::getParser()->e_sc->parse_scbatch(SSHOP_SC."global_shortcodes.php");
$cat_shortcodes = array_merge ($cat_shortcodes, $global_shortcodes);
```   

If this $tp->e_sc->parse_scbatch  is used only one time, everything works (of course global shortcodes are missing). 
After second using, the result is:

![image](https://user-images.githubusercontent.com/5429548/61215195-61924c00-a70a-11e9-9675-3e2fad7720ce.png)

Thanks

**Comment by Jimmi08** [comment]
Not needed anymore.

**Comment by CaMer0n** [comment]
This looks like an upgrade issue..

**Comment by Jimmi08** [comment]
@CaMer0n  Nobody will use those plugins anymore (it was problem with 2 of all I tried). Data are correct, the issue was in the parser itself.  I fixed this by using the old parser handler. 
I wouldn't waste time on this. Really. It's not worth your time. Those plugins don't work under php 7, so forget it.

**Comment by CaMer0n** [comment]
okay, thank you @Jimmi08 :+1:
