### ISSUE TITLE
download plugin - loading templates for not bootstrap theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3903]
no legacy theme but theme without bootstrap defined

because of this test, only theme templates are not loaded 

```
		if(deftrue('BOOTSTRAP')) // v2.x 
		{
			$template = e107::getTemplate('download','download','categories');
```

**Comment by Moc** [comment]
@Jimmi08 Is this still the case with the latest changes?

**Comment by Jimmi08** [comment]
@Moc No idea. Closing, I don't have the theme for this now.
