### ISSUE TITLE
e107 port v1 plugins to current v2 

### ISSUE THREAD

**Issue by gothicdude1044** [e107inc/e107#3915]
I found a plugin that shows the members user class. However i would like to see some way we can port v1 plugins over to v2

**Comment by Moc** [comment]
Hi, 

This question is more suitable for e107help.org. Some contributors around here are working on porting over plugins to v2 standards. However, all v1 plugins should be functional (to the most extent) on v2. 

You can find our regular contributors on Gitter as well: https://gitter.im/e107inc/e107
