### ISSUE TITLE
Users searching in the admin panel

### ISSUE THREAD

**Issue by akogo1** [e107inc/e107#3920]
User search don't work in the admin panel. I can't find a user. I put a nickname, email, ip etc. and nothing, no results...

**Comment by Moc** [comment]
Are you using the latest e107 version?
Which PHP version are you using?

So you get the "No Records Found" message right? Even when you type just two letters in the search bar (first two letters of your username for example?)

**Comment by akogo1** [comment]
Latest e107 - 2.2.2 git
PHP 5.3
![screenshot-blueknights6 pl-2019 08 12-11_55_14](https://user-images.githubusercontent.com/3391851/62857642-70175780-bcf8-11e9-82f4-2e628b647814.png)

![screenshot-blueknights6 pl-2019 08 12-11_56_02](https://user-images.githubusercontent.com/3391851/62857655-786f9280-bcf8-11e9-973f-a3a0e8d52c09.png)

**Comment by Moc** [comment]
And your MySQL info?  (`/e107_admin/phpinfo.php`)
Version, using PDO or not, and mode

**Comment by akogo1** [comment]
MySQL - 5.6.36
PDO: Enabled
Mode: NO_ENGINE_SUBSTITUTION

**Comment by Jimmi08** [comment]
I can't confirm this, but I use extended fields. Tested 7.0 latest github and 5.6 github 2.2.2. from - who knows, there is no date. 

Set debug on `[debug=showsql+]` and check sql query;
![image](https://user-images.githubusercontent.com/5429548/62863684-d8bb0000-bd09-11e9-9e85-264e6a60811a.png)

**Comment by akogo1** [comment]
I have this result

![screenshot-blueknights6 pl-2019 08 12-14_10_50](https://user-images.githubusercontent.com/3391851/62864110-22f0b100-bd0b-11e9-9c0a-221f4163b656.png)

**Comment by Jimmi08** [comment]
@akogo1 After insert name in searching box?

**Comment by akogo1** [comment]
Yes, user search engine finds nothing :/

**Comment by Jimmi08** [comment]
@akogo1 Could you do some test? 
Add birthday as extended field, try search.  
If nothing, add it to list form (like on my picture - with right option button) and try.  
Oh, and check your URL, this should work too:
e107_admin/users.php?searchquery=yourtext

**Comment by Moc** [comment]
@akogo1 Does this issue occur only in the Users area, or also other areas using the Admin UI?

**Comment by akogo1** [comment]
So on quickly... Now I can see that the search only works properly in news section. Welcome message, pages/menus, media searching don't work.

**Comment by Moc** [comment]
@akogo1 That makes sense. The areas in which your search is not working, are using the Admin UI. So I suspect there's something wrong in the Admin UI handler or the MySQL/PDO class. 

@CaMer0n Any ideas?

**Comment by CaMer0n** [comment]
@Moc This was fixed a while back. Closing, but please re-open if you are able to reproduce it again.
