### ISSUE TITLE
How do I set navcount for NEXTPREV shortcode?

### ISSUE THREAD

**Issue by fsLeg** [e107inc/e107#3924]
I'm still working on my theme and now I encountered another issue: pagination is too long. It gives access to the first page, previous page, 10 adjacent pages, next page and the last page. And all of that doesn't fit the screen of a mobile device, so it either looks weird or stretches the screen.

After a lot of digging I found what I was looking for: NEXTPREV shortcode. Or, rather, its parameters. The one I'm interested in in this case is navcount. Some grep'ing showed me that this parameter is either hardcoded (bad, but at least I can directly edit it) or uses some constant (or whatever it is, I'm not proficient in PHP), like NEWS_NEXTPREV_NAVCOUNT. Except I don't exactly understand how and where I can define it. There's no setting in admin panel and templates aren't exactly easy to understand.

Let's take a look at news. news.php has this code:

`$nitems = defined('NEWS_NEXTPREV_NAVCOUNT') ? '&navcount='.NEWS_NEXTPREV_NAVCOUNT : '' ;`

How do I define NEWS_NEXTPREV_NAVCOUNT? Preferably in a template or admin panel. I hardcoded it at the moment, but I'd like to avoid it.

And is there a proper way of defining NEXTPREV navcount?

**Comment by Jimmi08** [comment]
Maybe this helps you.
https://www.e107sk.com/knowledge_base/example-of-using-pagination/?content.84

Check nextprev single shorcode to get idea.

**Comment by fsLeg** [comment]
@Jimmi08 Nope, I already knew that by checking nextprev.php. What I was looking for is a way of setting `navcount` in the `$parms` of existing plugins, specifically news, which, according to your link, has "wrong" pagination.

After reading more closely, it turns out `navcount` is undocumented and it does exactly what I need: limits amount of adjacent pages available for navigation. So, there's that. And since it's undocumented, hardcoding is probably the only solution for me for the time being...

**Comment by Jimmi08** [comment]
I learnt something new :)  
` * - navcount (integer) [optional]: number of navigation items to be shown, minimal allowed value is 4, default is 10`

there are examples:
	$parms = "total={$thread->pages}&type=page&current={$thread->page}&url=".urlencode($url)."&caption=off&tmpl=default&navcount=4&glyphs=1";

**Comment by fsLeg** [comment]
@Jimmi08 Yes. And my question is, how do I set it for news?

**Comment by Jimmi08** [comment]
According this:
`		$nitems 	= defined('NEWS_NEXTPREV_NAVCOUNT') ? '&navcount='.NEWS_NEXTPREV_NAVCOUNT : '' ;`

define it in your theme. Not tested. I need to add this to docs, I never noticed this.

**Comment by Jimmi08** [comment]
`define('NEWS_NEXTPREV_NAVCOUNT', 	6);`
it works
![image](https://user-images.githubusercontent.com/5429548/63214346-71d98480-c117-11e9-8c5e-d5fbfbf3a25e.png)

**Comment by fsLeg** [comment]
> `define('NEWS_NEXTPREV_NAVCOUNT', 6);`

Thank you! That what I was looking for. I had no idea define() existed and how to use it.

**Comment by Jimmi08** [comment]
Neither me. Added to constants list.

**Comment by fsLeg** [comment]
It's not necessary to define the constant in theme.php, I defined it in a template (news_template.php, to be exact) and it works too while keeping theme.php cleaner.

Also, it you're looking to adding more parameters, here's a bunch straight from nextprev.php:

```
* - caption (rawurlencode'd string) [optional]: Label, rawurldecode'd after parameters are parsed to array, language constants are supported
 * - pagetitle (rawurlencode'd string) [optional]: Page labels, rawurldecode'd after parameters are parsed to array,
 * separated by '|', if present they will be used as lablels instead page numbers; language constants are supported
 * - plugin (string) [optional]: plugin name used for template loading
 * - tmpl_prefix (string) [optional]: template keys prefix; core supported are 'default' and 'dropdown', default depends on 'old_np' pref
 * - navcount (integer) [optional]: number of navigation items to be shown, minimal allowed value is 4, default is 10
 * - nonavcount (no value) [optional]: if is set it'll disable navigation counting (navcount will be ignored)
 * - bullet (string) [optional]: currently it should contain the markup to be prepended to the navigation item title
 *
 * WARNING: You have to do rawuldecode() on url, caption and title parameter values (before passing them to the shortcode)
```

**Comment by Jimmi08** [comment]
Yes, I know.  But constants should be defined in theme.php, not template file. The template file can be loaded more times and you get php warning that constant is already defined.  Yes, you can test this to avoid this warning, but I still think that this shouldn't be in template. But it's on you.
