### ISSUE TITLE
Private Message title setting doesn't seem to do anything

### ISSUE THREAD

**Issue by fsLeg** [e107inc/e107#3925]
Today, a friend of mine who came up with a theme I'm working on asked if I could change pm_menu's title. Apparently, I could, as there's a field just for that in admin panel.
![image](https://user-images.githubusercontent.com/9852210/63224855-defe2000-c1d2-11e9-82a3-6086b7e99dbd.png)

Or so I thought, because changing the field does absolutely nothing, menu's title (the one tablestyle() sees as $caption) is still being pulled from LAN_PM. I clicked seemingly everywhere within the plugin, both menu and a dedicated page, but the title I set was nowhere to be seen.

Am I missing something or is it a bogus setting?

**Comment by Jimmi08** [comment]
Yes, you are right.  And there is not used PMLAN_PM value used too.
Quick fix:

replace

`$ns->tablerender(LAN_PM, $txt, 'pm');`

with 

```
	$caption = varset($pmManager->prefs()['title'],LAN_PM);
	$ns->tablerender($caption, $txt, 'pm');
```

**Comment by Moc** [comment]
Fixed. Also cleaned up the code a bit. Thanks @fsLeg and @Jimmi08!
