### ISSUE TITLE
FR - menu manager versus HTML layouts

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3932]
There is a small limitation for Menu Manager now because it parses only {MENU=x} in theme.html and _layout.html files.  

Now you can have different footer per layout very easy, so it's easier now. But there can exist a more complicated theme where you need to change footer or header on the fly or by extended functionality.  But if they have menu areas (footers mainly), they are not displayed in Menu manager.

It would be great to have 2 special theme shortcodes that are parsed in Menu manager too if they are used in html layouts (theme or layouts).
 
Normal parsing (Frontend) works without any problems.  Something like  {THEME_CUSTOMHEADER} and {THEME_CUSTOMFOOTER} 

Thanks

**Comment by CaMer0n** [comment]
Modify `bootstrap4/theme_shortcodes.php` , method:  `sc_footer()` to test.
