### ISSUE TITLE
Where is the .css for define("BOOTSTRAP", 	3); located?

### ISSUE THREAD

**Issue by sparuj** [e107inc/e107#3933]
Hello everyone!

Can someone please tell me where the .css for 
`define("BOOTSTRAP", 	3);` 
`e107::library('load', 'bootstrap');`

in 107_theme/TEMPLATENAME/theme.php is located? I just can't seem to find it.

I'm trying to edit my custom theme from 1.4 version and without these two lines for example when I try to register a new user and if I enter already existing username/email an error message pops out. However after that my signup.php text gets bigger and changes it's color to white.

Cheers!

**Comment by Jimmi08** [comment]
Settings / Libraries  
define("BOOTSTRAP", 3);  - this has nothing with css, only with templates and html markup
e107::library('load', 'bootstrap'); - you can deleted it. New way is set to set in xml file. Or load with e107::css from CDN or from theme folder.  

Here:  (you have probably only icons in main menu, not titles)
![image](https://user-images.githubusercontent.com/5429548/63509821-66060d80-c4dd-11e9-85b4-a119fb4359dc.png)

I will add this to e107sk documentation asap.  I thought that I have there all information about theme basics, but this one is missing :)

**Comment by sparuj** [comment]
Thank you for responding!

The thing is, when I delete `e107::library('load', 'bootstrap');` from my theme for example on signup.php when I enter a duplicate username an error pops out in the upper part of the screen. That's okay. However when I click close on the popup it redirects me to the signup page, but my text turns white and it gets bigger. In addition when I try to post a reply on the forum it doesn't show me the message "view your post" or "return to forum", nothing. Probably a lot other stuff is messed.
If I add `define("BOOTSTRAP", 3); e107::library('load', 'bootstrap');` on signup it shows the error in a boxed message right above username without changing my text style.
Unfortunately if these two lines are added, my theme gets all wonky and my theme's JS doesn't work.

I also did Theme manager > Tools > Converter > MyTheme

This is the reason I asked if there is some sort of a way to edit this bootstrap.

**Comment by Jimmi08** [comment]
You have something else wrong.  Do you updating old theme? What e107 version do you use? Upload your theme to your repository to see what us wrong. No core files shouldnt be changed.

**Comment by sparuj** [comment]
I updated from e107 v1.4 to v2.2.1 and I'm currently editing a theme that I used in 1.4.

**Comment by sparuj** [comment]
It seems that I've found a solution to this, however I feel that it isn't the correct one, but it works. No idea how I did it tho. :D

Thank you for taking time to help!

**Comment by Jimmi08** [comment]
You can look at core, khatru or Nightvision themes, they were updated from 1.0.4 versions. Of course, now I would do it a different way, but they still work. And there is Blackv2 theme in my repositories, next example.  And you always can ask on my site forum. Oh, and RideBlue, of course. It's the best one :)
