### ISSUE TITLE
fatal error with boolean admin UI after using batch option

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3936]
Boolean field defined this way:

```
			'element_active' => array ( 'title' => LAN_ACTIVE,
			'type' => 'boolean',
			'data' => 'int',
			'width' => 'auto', 
      'batch'=> true,
			'readParms' => array (),
		  'writeParms' => array (),
			'class' => 'left',
			'thclass' => 'left',
			),
```
Set yes / no on modify Active is working
There 20 records on one page
After using Invert batch option:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function e_admin_ui::handleListBoolreverseBatch(), 2 passed in xxx\e107_handlers\admin_ui.php on line 3444 and exactly 3 expected in xxx\e107_handlers\admin_ui.php:5329 Stack trace: #0 xxx\e107_handlers\admin_ui.php(3444): e_admin_ui->handleListBoolreverseBatch(Array, 'element_active') #1 xxx\e107_handlers\admin_ui.php(4925): e_admin_controller_ui->_handleListBatch('boolreverse__el...') #2 xxx\e107_handlers\admin_ui.php(2094): e_admin_ui->ListBatchTrigger('boolreverse__el...') #3 xxx\e107_handlers\admin_ui.php(1264): e_admin_controller->dispatchObserver() #4 xxx\e107_handlers\admin_ui.php(1074): e_admin_dispatcher->runObservers(true) #5 xxx\e107_plugins\jmelements\admin\admin_config.php(439): e_admin_dispatcher->__construct() #6 {main} thrown in xxx\e107_handlers\admin_ui.php on line 5329`

Confirmed with clean generated admin_config by plugin builder (no custom changes, only added batch)

**Comment by CaMer0n** [comment]
@Jimmi08 I now this is a long time ago, but would you remember if the plugin was installed after being generated?

**Comment by Jimmi08** [comment]
> @Jimmi08 I now this is a long time ago, but would you remember if the plugin was installed after being generated?

It is still there.  Elements plugin.   Are you able to download it from e107sk.com?

**Comment by Jimmi08** [comment]
The same error with news  -  try to mark more records and use invert on sticky field.
