### ISSUE TITLE
 option to disable author and date stamps on new pages

### ISSUE THREAD

**Issue by cjmccormick** [e107inc/e107#394]
In e107v1 there was an option to enable or disable the author and date stamps on newly created pages. Would like to see this option added on  v2 as a possible enhancement.

As noted here: http://e107.org/e107_plugins/forum/forum_viewtopic.php?246336

**Comment by Moc** [comment]
Unless there is a lot of demand for this, I'm closing this. 
There is the option to customize the page layout through templates (page_template), which also controls whether or not the author and datestamp is displayed.

This then affects all pages, so I guess the feature request could be to have this set per individual page. Closing for now, but feel free to comment if you'd like to see this feature.
