### ISSUE TITLE
Getting Forbidden in /e107_admin/prefs.php

### ISSUE THREAD

**Issue by sparuj** [e107inc/e107#3942]
Hello everyone!

Strangely I am getting this when I try to save something in /prefs.php:

> Forbidden
> You don't have permission to access this resource.
> 
> Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

On my localhost/xampp I don't get this error. However when I transfer e107 to my live server I get the Forbidden error.
In addition to this: if I try to edit the settings directly from the DB, after I relog it changes them back to the previous ones.

Does anyone have any suggestions as to what the cause might be?

**Comment by CaMer0n** [comment]
@sparuj Does your server have mod_security enabled? If so, please check the mod_security logs.

**Comment by sparuj** [comment]
Thank you for replaying.

Mod_security is enabled, however I don't seem to have access to the logs. I also tried google searching and still coudn't find them.

**Comment by Moc** [comment]
Try and contact your webhosting provider to see if they can see something in the mod_security logs.

**Comment by sparuj** [comment]
I contacted my provider and received this message from him:

[Tue Sep 03 06:43:08.388785 2019] [:error] [pid 1972:tid 47704743311104] [client IP.Address:60479] [client AP.Address] ModSecurity: Access denied with code 403 (phase 2). Match of "rx ((?:submit(?:\\+| )?(request)?(?:\\+| )?>+|<<(?:\\+| )remove|(?:sign ?in|log ?(?:in|out)|next|modifier|envoyer|add|continue|weiter|account|results|select)(?:\\+| )?>+)$|^< ?\\??(?: |\\+)?xml|^<samlp|^>> ?$)" against "ARGS:sitedisclaimer" required. [file "/etc/apache2/conf.d/modsec/modsec_rules/10_asl_rules.conf"] [line "1091"] [id "350147"] [rev "155"] [msg "Atomicorp.com WAF Rules: Potentially Untrusted Web Content Detected"] [severity "CRITICAL"] [hostname "WebSite URL"] [uri "/e107_admin/prefs.php"] [unique_id "XW3hTDaslgEiP9fAZ1cGbQAAAAc"], referer: https://WebSiteUrl/e107_admin/prefs.php

**Comment by Moc** [comment]
Ah that's good! 

What is the value you put in the sitedisclaimer field?

**Comment by sparuj** [comment]
I've put Copyright e107 Inc. 2008-2019. in theme.php and in sitedisclaimer field I have Theme by ---. Additional coding by ---. 

Does Copyright e107 has to be in the sitedisclaimer in order to not get an error?

**Comment by Moc** [comment]
> Does Copyright e107 has to be in the sitedisclaimer in order to not get an error?

No, you can fill in anything you want. 
I was wondering why the mod_security rule is being triggered, and thought it was related to the contents of the sitedisclaimer field, but this may not be the case. 

For the quickest solution, I'd advise you to ask your webhosting provider to turn off that specific mod_security rule.

**Comment by sparuj** [comment]
After contacting the hosting provider, everything is okay.
