### ISSUE TITLE
access denied and & issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3943]
I got access denied on some urls.
I was able to narrow problem to this:
```
	public function set_request($no_cbrace = true)
	{
    
		$inArray = array("'", ';', '/**/', '/UNION/', '/SELECT/', 'AS ');
		if (strpos($_SERVER['PHP_SELF'], 'trackback') === false)
		{
			foreach($inArray as $res)
			{  
				if(stristr($_SERVER['QUERY_STRING'], $res))
				 {
					die('Access denied.');
				}
			}
		}
```
`$_SERVER['QUERY_STRING'] :   rt=product/product&product_id=123`
failed test:
`$res : ';'`

it looks like stristr test `&amp;` instead of `&` 
No idea what to do.  
Not for 100% sure, but I have integrated e107 with Nuke with similar URLs and it worked when the request part was in class2.php not in e107 class.  Thanks

**Comment by Deltik** [comment]
@Jimmi08: How did you find this issue?  I can't reproduce it unless I explicitly type `&amp;` into the query string, which should not happen under normal circumstances.

**Comment by Jimmi08** [comment]
@Deltik I use e107 with abantecart system.  
It fails with & in URL.
No idea what to check if `$_SERVER['QUERY_STRING']`  value is correct &  but 
stristr is checking &amp;
Hm, not sure now if I var_dumped that value or used print_a for that $_SERVER['QUERY_STRING']. 

But while this test was in class2.php, it worked. 

I fixed it by using e107_class without this test. And I will have the next case with other CMS, so I will see what is causing the problem.   
 
It's one of the e107 advantages, you don't need some bridges, you just include class2.php and you can extend other CMS with e107 features.  I know, not standard, but this is the first issue I run with it.

**Comment by Deltik** [comment]
@Jimmi08: I still don't see how just a `&` triggers the access denied error.

As for the `;` match in the query string, I suspect there may be legitimate uses for it.  That matching code was written [wa-a-a-ay back in 2008](https://github.com/e107inc/e107/commit/b88bbcd5d2ccc6db1d357a4b0c0d677fd0bdd33b#diff-3db6f36618bfcbe7ebc001c2b5e03c81R200).  Maybe @CaMer0n can provide some input on whether that code is still good to have today.

**Comment by Deltik** [comment]
@Jimmi08: I still don't see how just a `&` triggers the access denied error.

As for the `;` match in the query string, I suspect there may be legitimate uses for it.  That matching code was written a very long time ago, [before e107 v0.8 was created](https://github.com/e107inc/e107/commit/e149b35fcc6a882ad812d9a7ca9c4b7cf4cfd0f7#diff-3db6f36618bfcbe7ebc001c2b5e03c81R141).  Maybe @CaMer0n can provide some input on whether that code is still good to have today.

**Comment by Jimmi08** [comment]
@Deltik that's the point 
While it was in class2.php, it worked.  After moving to e107_class.php I run to this issue.  

It's not important, but if there is little chance that somebody uses `&amp;` instead of `&` in URL, I thought it would be good to mention this. Or it's maybe related to the environment, no idea.   
Thanks for your time.

**Comment by CaMer0n** [comment]
I believe the semi-colon check can be removed. Commit coming shortly. 
https://stackoverflow.com/questions/2366260/whats-valid-and-whats-not-in-a-uri-query

**Comment by Jimmi08** [comment]
Thank you!
