### ISSUE TITLE
Feature Request: e_user help(tool-tip)

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3944]
so in e_user.php we have an array with stuff in it - example:

$var = array(
			0 => array('label' => "Clone Number", 'text' => $sr['clone_number'], 'url' => ""));

Adding 'help' => "" to the mix (like in admin area) but doesn't show the tool-tip like it does in the admin area.

**Comment by Moc** [comment]
Seems like a duplicate :) Closing in favour of #3134.
