### ISSUE TITLE
Feature Request: User Delete Option

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3945]
Admin Area -> Users -> Options:
Allow users to delete account: enable/disable

(enable will show the delete button)
(disable will hide the delete button)

**Comment by LaocheXe** [comment]
I don't know if you guys want this or not, but pull request has been made #3946

**Comment by Moc** [comment]
It will be looked into asap :) thank you!

**Comment by Jimmi08** [comment]
How your solution solves related user records? Extended fields, forum posts, chatbox etc.

**Comment by Moc** [comment]
This PR just adds a preference that controls whether the delete button is shown or not. It does not change any of the current functionality.

**Comment by CaMer0n** [comment]
Merged. Thank you! Closing.
