### ISSUE TITLE
weird issue with e107::js()

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3954]
I have the normal plugin shortcode {WEBTICKER} .
it uses:

```
e107::css("jmelements",  "js/jquery.webticker.min.css"); 
e107::js("jmelements", 			"js/jquery.webticker.min.js", "jquery");  
e107::js("footer-inline",  $code);
```
Normally it works. 

if I put it into _layouts, theme.html, it works.
But if put it into magic shortcode {---HEADER---} e107:js() is not loaded.
e107::css(), inline code are, only e107::js() is missing.

{---HEADER---} is sc_header() in theme_shortcodes.php

Thanks

**Comment by Moc** [comment]
@Jimmi08 Still relevant?

**Comment by Jimmi08** [comment]
I stopped using this
