### ISSUE TITLE
{USER_EXTENDED=location.text_value}  is not working in forum plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3957]
Could somebody confirm this?

If you use extended field location, it should be displayed inside 
`{USERCOMBO}`

this way:
`$ue = $tp->parseTemplate("{USER_EXTENDED=location.text_value}", true);`

it return empty value. string(0) ""

It could be used directly in template too:
` {USER_EXTENDED=location.text_value}`

In news  EUF is used this way:
`e107::getParser()->parseTemplate("{USER_EXTENDED={$field}.{$type}.{$userid}}");`

so I think this should be fixed in forum plugin

**Comment by Jimmi08** [comment]
This works:
<div>	 {USER_EXTENDED=location.text} : 										{USER_EXTENDED=location.value}</div>

Now I have a problem with gender:
Options are not translated (neither in admin)
Gender : M => UE_LAN_MALE
After manually changing values in admin area, result is displayed (key and value):
Gender : M => Man
Should those options be changed manually?

**Comment by Moc** [comment]
For me, on a clean install, the location EUF is shown in the usercombo. No modifications. 

![image](https://user-images.githubusercontent.com/577978/65410727-64d14480-ddeb-11e9-83a7-d92e5644b4d7.png)

**Comment by Moc** [comment]
I think your second (separate) issue with the translation of EUF labels and values, is related to this issue, which is a bug: https://github.com/e107inc/e107/issues/3881

**Comment by Jimmi08** [comment]
> For me, on a clean install, the location EUF is shown in the usercombo. No modifications.

it is displayed without label. Like with only "value".  But it has "text.value" settings and label "Location:" is missing.

**Comment by Moc** [comment]
Oops, missed that, I'm sorry, Doing more testing :)

**Comment by Moc** [comment]
Fixed, was an issue in the user_extended shortcode, not in forum. 

The translation issue, I consider a separate issue. Probably #3881. Please check if that is indeed your issue as well, or open a new issue, so we can keep this one clean :)
