### ISSUE TITLE
bbarea field and wysiwyg issue 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3965]
I am not able to load 2 bbarea fields on the same page - one with wysiwyg and second one with bbarea code.

Central Wysiwyg ON:
First field:
`e107::getForm()->bbarea('post','','forum', 'forum', 'tiny', array('id' => 'forum-quickreply-text', 'wysiwyg' => false));`

Second field:
`e107::getForm()->bbarea('xx', 'Some bb value' , null, null, 'small', array('id' => 'someid', 'wysiwyg' => true));  `

I am able to check that HTML output from form handler is correct, but than some javascript is fired and both fields have Wysiwyg.

If central WYSIWYG is Off, 
both fields have only bbcodes. 

Thanks.

**Comment by Moc** [comment]
Any errors in browser console?

**Comment by Jimmi08** [comment]
No, I think that this wasn't tested.  Parameter Wysiwyg is new, it was done for the forum plugin, but then all bbareas in forum are on/off.  Not a combination.

**Comment by Moc** [comment]
@Jimmi08 Is this issue still happening?

**Comment by Jimmi08** [comment]
I really couldn't wait. I don't know an example of how to test this. Give me some time.

**Comment by Jimmi08** [comment]
Not needed anymore. I will create new issue if I run on this again.
