### ISSUE TITLE
add tbox class to input calendar form

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3966]
other input elements use tbox form-control classes, 
calendar only form-control by default

for better styling it would be good to use both classes

`<input class="e-datetime input-xlarge form-control" type="text" size="40" id="e-datepicker-last-visit-date" value="Friday, 04 Oct, 2019 11:03 AM" data-date-unix="true" data-date-format="DD, dd M, yyyy HH:ii P" data-date-ampm="false" data-date-language="en" data-date-firstday="0">`

tested with 
`e107::getForm()->datepicker('last_visit_date', time(), array('type'=>'datetime'));`

**Comment by Moc** [comment]
Is this for better compatibility with v1 or non-bootstrap themes?

**Comment by Jimmi08** [comment]
Mainly to have one rule for all input form fields. Now it's tbox form-control (check other type form field).

**Comment by Moc** [comment]
Please test, but this should do it :)
