### ISSUE TITLE
Anonymous posting - wrong user displayed in Comments Manager

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3971]
When Anonymous post new comment, you can see it as:
![image](https://user-images.githubusercontent.com/5429548/66666628-5be8cb80-ec51-11e9-9d62-5a3434f58439.png)

In edit mode you see there your nick as author:
![image](https://user-images.githubusercontent.com/5429548/66666666-74f17c80-ec51-11e9-9faf-6296d71b89c4.png)

But if you delete it, then author name is deleted too:
![image](https://user-images.githubusercontent.com/5429548/66666744-9fdbd080-ec51-11e9-8133-0bbcb67ac7a4.png)

It looks like some mess between author and user.

**Comment by Moc** [comment]
@CaMer0n Can you take a look at this? Seems to be a generic Admin UI issue related to the 'user' type.
