### ISSUE TITLE
premium themes  question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3973]
**On e107.org:** 
There is no info that theme is paid. And download button downloads zip file, it's not redirecting to Purchase URL. 

Edit: this is only on hover and download button. On view detail, the More info button works correctly.

**In Theme manager:**
Purchase/Download link is opened in the iframe, it should open in a new tab. 

Thanks

**Comment by Moc** [comment]
Will look into it. 

Btw, it seems I cannot find you on Gitter anymore... I signed up on e107sk website, can you send me a PM? Cannot find you in the userlist to send a pm to.

**Comment by Jimmi08** [comment]
@Moc next theme posted for approval

**Comment by Moc** [comment]
@CaMer0n Can you take a look at this for e107.org functionality?

The theme manager seems to be fixed on the latest git.

**Comment by CaMer0n** [comment]
@Moc @Jimmi08 On e107.org, I have added the "price" and "release date" info. 
The download/more-info button was working correctly, see here: 

https://e107.org/themes/?iframe=1&id=980 // premium
https://e107.org/themes/?iframe=1&id=978 // free

**Comment by Jimmi08** [comment]
It works correctly now. Thank you
