### ISSUE TITLE
Forum permissions for creating topics (+announcements/sticky)

### ISSUE THREAD

**Issue by JenovaOnline** [e107inc/e107#3974]
I was wondering if there is a way to change forum permissions. Regular users can create announcements. I don't want that functionality. Any way to edit or fix this?

**Comment by Indylogan** [comment]
Hello,

I use e107 2.2.1 with the built in Forum engine. I'd like to ask how to prevent users to open their own topics? I mean, only me, the admin should create topics, then the members could write comments to only these topics. Thank you.

**Comment by Jimmi08** [comment]
@Indylogan 
Change for your forums Thread creating access to admins or forum moderators class. Or any class.
![image](https://user-images.githubusercontent.com/5429548/75633665-2bf19300-5c07-11ea-8781-4acc622c3add.png)

You can use batch option for this, not to do it for each forum separately.

**Comment by Moc** [comment]
@JenovaOnline good suggestion! That's currently not possible in the forum plugin but it is great feature request. Hopefully someone will have time to work on this. Pull requests are always welcome!

**Comment by Jimmi08** [comment]
@Moc This is definitely a bug.

forum_threadclass is exactly for this and if you check forum update, you can see it is filled from 
`$tmp['forum_threadclass'] = $tmp['forum_postclass'];`

function sc_newthreadbuttonx() is checking this:
`if ($this->var['ntUrl'])`

and this is checking permission this way:

```
//-- if($forum->checkPerm($forumId, 'thread')) //new thread access only.
	if($forum->checkPerm($forumId, 'post')) //new thread access only.
	{
		$forumSCvars['ntUrl'] = e107::url('forum', 'post') . "?f=nt&amp;id=" . $forumId;
	}
```

The correct way is: (no idea why it is commented now): 
```

	if($forum->checkPerm($forumId, 'thread')) //new thread access only.
	{
		$forumSCvars['ntUrl'] = e107::url('forum', 'post') . "?f=nt&amp;id=" . $forumId;
	}
```
If you check 1.0.4 code for this:

```
if (check_class($forum_info['forum_postclass']) && check_class($forum_info['parent_postclass']))
{
	$NEWTHREADBUTTON = "<a href='".e_PLUGIN."forum/forum_post.php?nt.".$forum_id."'>".IMAGE_newthread."</a>";
}
```
but legacy forum_postclass is not forum_threadclass
