### ISSUE TITLE
contact form and 2x hidden input name rand_num  

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3980]
Hi, 
could somebody check if you have on contact form

<input type="hidden" name="rand_num"  >
twice times?  

On latest github.

Recaptcha plugin replaces one of them but one still stays there and spams are coming through the contact form.

Thanks

**Comment by sudakk** [comment]
Hi!
I have one in login form on modal window and another on contact form and also 2x hidden input name code_verify... Or you mean something else?

**Comment by Jimmi08** [comment]
Hi, no, you have 2 forms on one page, so you have it there 2x. And you can have it as menu too. 

With one form there is code:
Modal:
```
<input type="hidden" name="rand_num" value="1571664677000493900" id="rand-num-1571664677000493900">
<input type="text" name="code_verify" value="" maxlength="20" id="code-verify" class="tbox form-control" size="20" required="required" placeholder="Enter code">
```

But with contact form:
```
<div class="control-group form-group">
<label for="code-verify">Enter code</label> 
<input type="hidden" name="rand_num" value="1571664856090046600">
<img src="/e107_demo/e107_images/secimg.php?id=1571664856090046600&amp;clr=cccccc" class="icon secure-image" alt="Missing Code" style="max-width:100%">
<input type="hidden" name="rand_num" value="1571664856090046600" id="rand-num-1571664856090046600">
<input type="text" name="code_verify" value="" maxlength="20" id="code-verify" class="tbox form-control" size="20" required="required" placeholder="Enter code"></div>
```

Something is wrong. It wasn't this way before.


And recaptcha plugin uses this code:
```
	  e107::getOverride()->replace('secure_image::r_image',     'e107recaptcha::input');
		e107::getOverride()->replace('secure_image::renderInput', 'e107recaptcha::hiddeninput');
		e107::getOverride()->replace('secure_image::invalidCode', 'e107recaptcha::invalid');
	 	e107::getOverride()->replace('secure_image::renderLabel', 'e107recaptcha::blank');
		e107::getOverride()->replace('secure_image::verify_code', 'e107recaptcha::verify'); 
```

And result is:
 
![image](https://user-images.githubusercontent.com/5429548/67210075-c26fa580-f418-11e9-8a07-4cb079fd3b87.png)

**Comment by sudakk** [comment]
Yes, you are right!
I have the same twin. One with id='rand-num, another without.

```
<div class='control-group form-group'>
  <input type='hidden' name='rand_num' value='1571675922092261800' />
  <img src='/images2/secimg.php?id=1571675922092261800&amp;clr=cccccc' class='icon secure-image' alt='Missing Code' style='max-width:100%' />
  <input type='hidden' name='rand_num' value='1571675922092261800' id='rand-num-1571675922092261800' />
  <input type='text' name='code_verify' value='' maxlength=20  id='code-verify' class='tbox form-control' size='20' required='required' placeholder='Введите код' />
</div>
```

**Comment by sudakk** [comment]
Shortcodes in contact_template:
```
	{CONTACT_IMAGECODE}
	{CONTACT_IMAGECODE_INPUT}
```
contact_shortcodes.php:
```
function sc_contact_imagecode($parm='') 
{
	//return e107::getSecureImg()->r_image()."<div>".e107::getSecureImg()->renderInput()."</div>"; 
	return "<input type='hidden' name='rand_num' value='".e107::getSecureImg()->random_number."' />".e107::getSecureImg()->r_image();
}
```
This is first. And secure_img_handler.php:
```
function renderInput()
{
	if ($user_func = e107::getOverride()->check($this,'renderInput'))
	{
	 		return call_user_func($user_func);
	}
			
	$frm = e107::getForm();	
	return $frm->hidden("rand_num", $this->random_number).$frm->text("code_verify", "", 20, array( "size"=>20, 'required'=>1, 'placeholder'=>LAN_ENTER_CODE));
}
```
This is second.

**Comment by Jimmi08** [comment]
Just overview of using image captcha:

this is code from admin auth and it should work this way:
```
				$sec_img->renderImage().
				$sec_img->renderInput()."	
```

**Login shortcodes (confusing, but correct)**
Core template: 	`{LOGIN_TABLE_SECIMG_SECIMG} {LOGIN_TABLE_SECIMG_TEXTBOC}`
![image](https://user-images.githubusercontent.com/5429548/67262483-3eafca80-f4a5-11e9-8bca-72eddd32cad4.png)

**Signup shortcodes:** 
 (r_image() is alias of render_image())
Core template:  `{SIGNUP_IMAGECODE}`
![image](https://user-images.githubusercontent.com/5429548/67262506-54bd8b00-f4a5-11e9-854a-1aa25199bdcf.png)

**Contact shortcodes:**
core template: 	`{CONTACT_IMAGECODE} {CONTACT_IMAGECODE_INPUT}`
![image](https://user-images.githubusercontent.com/5429548/67262580-a239f800-f4a5-11e9-8ab1-a66433cbfc59.png)

I understand why there should be 2 shortcodes (to be able to use $sc_style for HTML markup) but why it can not be done the same way in all places?  

Thanks

**Comment by Jimmi08** [comment]
Ok, I replaced it with theme shortcodes. I am noting it here just to know from time to watch spam problem.

**Comment by Jimmi08** [comment]
@CaMer0n I had a feeling you asked me to check this with VisualCaptcha, but I can't find it now.

I did it. It looks correct

![image](https://user-images.githubusercontent.com/5429548/74232643-84e59f80-4cc9-11ea-894a-e436a65cd1ba.png)

 I think you are using in one method and r_image is blank:

```
	e107::getOverride()->replace('secure_image::r_image',   'visualcaptcha_module::blank');
	e107::getOverride()->replace('secure_image::renderInput', 'visualcaptcha_module::input');

		$element = '<div class="visual-captcha"></div>';
		$element .= $form->hidden('rand_num', 'x'); // BC compat.
```

but ReCaptcha is:

```
e107::getOverride()->replace('secure_image::r_image',     'e107recaptcha::input');
		e107::getOverride()->replace('secure_image::renderInput', 'e107recaptcha::hiddeninput');


static function input()
		{
		 $text = '<div class="g-recaptcha"  ></div> ';
			return $text;
		}
		
		static function hiddeninput()
		{	 
			$frm = e107::getForm();	
			return $frm->hidden("rand_num", 'google' );
		}
```

**Comment by Moc** [comment]
Has this been fixed already?

**Comment by Jimmi08** [comment]
> Has this been fixed already?

I am not aware of fix.  I don't use core contact.php anymore, so I really don't know.

**Comment by CaMer0n** [comment]
It's likely a bug in reCaptcha if VisualCaptcha works without a problem.

**Comment by Moc** [comment]
@CaMer0n There definitely is an issue somewhere: https://github.com/e107inc/visualcaptcha/issues/5

**Comment by Moc** [comment]
@Jimmi08 @sudakk Please re-test with the latest files and confirm whether the issue is fixed. Thanks!
