### ISSUE TITLE
alt_auth plugin and not able to create user from other db + FIX

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3982]
This code
`$userMethods->addNonDefaulted($newUser); `

causes wrong array for insert user:

![image](https://user-images.githubusercontent.com/5429548/67604408-c6cef200-f77b-11e9-9e89-45c3f578f149.png)

Insert debug didn't return any error
Changing to:
`$userMethods->addNonDefaulted($newUser['data']);  `

it fixed it.  Again, no idea if this is correct and why this change.

**Comment by CaMer0n** [comment]
@Jimmi08 Closing. Thank you. Please use "Fixes #(number)" in the description when submitting pull-requests to trigger auto-closing.
