### ISSUE TITLE
alt_auth plugin - using e107 as secondary authorisation causes blank page + FIX

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3983]
If primary authorisation fails, e107 causes blank page

![image](https://user-images.githubusercontent.com/5429548/67616693-0cbba280-f7dc-11e9-88df-aa2a4c6704ed.png)

Reason for this is that method value is e107db and not e107 like is done in this test:
in handlers/login.php

`        if ($method == 'e107' )`

this fixed it:

`if ($method == 'e107' OR $method == 'e107db')`

**Comment by Jimmi08** [comment]
This shouldn't be closed.

I am trying to get how this should work.

e107 - is your actual e107 installation
e107db  - is other e107 installation.

You can't now select e107 as a secondary installation. 
![image](https://user-images.githubusercontent.com/5429548/71556749-8bcb9200-2a3c-11ea-9cdf-a68158ebbaef.png)

That second PR was solving this, but it wasn't merged and after rebase it's not there anywhere.

**Comment by Jimmi08** [comment]
@CaMer0n @Moc 
What is planned or what was the intention when you want to use your actual e107 as a secondary authorization type? 

for example, there is used:
```
	if($pref['auth_nouser'])
	{
		$cfg->set('auth_method2', 'e107');
	}
 
```
 
but dropdown values for auth_method2 field are:
```
<option value="none">none</option>
<option value="e107db">e107db</option>
<option value="importdb">importdb</option>
<option value="ldap">ldap</option>
<option value="otherdb" selected="selected">otherdb</option>
<option value="radius">radius</option>
```

And fix was:
`<td>".$altAuthAdmin->alt_auth_get_dropdown('auth_method2', $pref['auth_method2'], 'none,e107')."`

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Pull-request welcome. Nothing planned.
