### ISSUE TITLE
Strange issue creating custom menu

### ISSUE THREAD

**Issue by Serios** [e107inc/e107#3986]
Using latest v.2.2.1 I can't create custom menu to use in menu manager with my theme. Menu is actually created trough Custom pages/Menus but menu_name field is not saved to the DB even if I try to modify existing one the menu_name field gets blank and thus is not listed in Menu manager under custom menus. Menu is created with name, title, text and icon.

**Comment by sudakk** [comment]
I can 't repeat this problem. The menu is created and renamed without problems. And it's visible in the Menu Manager.

**Comment by Serios** [comment]
@sudakk on new install or on updated system?

**Comment by sudakk** [comment]
@Serios on updated.

**Comment by Jimmi08** [comment]
@Serios  2.2.1 from e107.org?  Check database validity and export one of the problematic records and put it here. If you use Chrome, use a different browser. 
My guess is that you have already menu name with the same name or it saved your username as menu title if you are using Chrome. 
2.2.1 doesn't have this problem, I would notice this, your data could be a problem. 
If it is not problem, you can export your cpage table to xml (Database/tools) and put it here, I could try to import it to my 2.2.1 version.

**Comment by Serios** [comment]
@Jimmi08 @sudakk I managed to track the problem in relation with the php version of the server. On php ver 7.3 the problem exist. If php version is set to the minimum required 5.6 the problem no longer exist and menu_name is properly submitted to the DB. Confirmed it by trying both on my local server and on production server as well.

**Comment by Jimmi08** [comment]
@sudakk try 7.2,  e107 officially support only this version,  I use only this one or 5.6.   I will need to install xampp with 7.3.   Yes, today I can :)

**Comment by Serios** [comment]
@Jimmi08 It's working properly on 7.2 

You can setup your xampp to run different versions of php for different projects. If you are interested, you can check this [guide](https://stackoverflow.com/a/49586592)

**Comment by Jimmi08** [comment]
Thanks, too complicated.  I know better and easier way :)  for somebody who is not server/administrator guy :)

**Comment by Jimmi08** [comment]
Confirmed only for Chrome 
![image](https://user-images.githubusercontent.com/5429548/67679820-3adee500-f98a-11e9-9055-5671a76da7af.png)


Firefox:

![image](https://user-images.githubusercontent.com/5429548/67679770-24d12480-f98a-11e9-8fd8-f4a9fd75867e.png)

It's old not solved problem with prefilled fields in Chrome:
https://github.com/e107inc/e107/issues/3196
https://github.com/e107inc/e107/issues/3131

With php 7.3 it is worse, because you can't edit .

**Comment by Jimmi08** [comment]
Hm, now I can edit it in Chrome too. I couldn't before.

**Comment by Jimmi08** [comment]
Next problem:
 I am using only name, title and description. 
first time record was saved (closed editing) without any error but record didn't exist.
second time this error appeared and only way how to save menu was adding sef-url to page. 
![image](https://user-images.githubusercontent.com/5429548/67681083-e7ba6180-f98c-11e9-9e52-f08dce8af580.png)

**Comment by Jimmi08** [comment]
That SEF-URL error is because of this:
`$newdata['page_sef'] = eHelper::title2sef($newdata['menu_name']);`
$newdata['menu_name'] has value NULL, so it's not generated correctly.
So this is the result, not cause.

**Comment by Jimmi08** [comment]
NULL value for menu_name is caused by this line:

`$newdata['menu_name'] = preg_replace('/[^\w-*]/','-',$newdata['menu_name']);`

before this, it has the correct value.

**Comment by Jimmi08** [comment]
This is fix (2 places):
`$newdata['menu_name'] = preg_replace('/[^\w\-*]/','-',$newdata['menu_name']);`

For php 7.3. hyphen has to be escaped. 

"It is advised to check all the regex you are using in your applications and test them with PHP 7.3."

**Comment by sudakk** [comment]
The ability to save a menu\page with an empty both fields menu_name & page_title occurs because there is no check in function beforeUpdate (in cpage.php) as when creating a menu\page in function beforeCreate. If you add this code, you will receive an error when you try to save an empty both fields menu_name & page_title:
```
function beforeUpdate($newdata,$olddata, $id)
{

	if(isset($newdata['page_title']) && isset($newdata['menu_name']) && empty($newdata['page_title']) && empty($newdata['menu_name']))
	{
		e107::getMessage()->addError(CUSLAN_79);
		return false;
	}
	$newdata = e107::getCustomFields()->processDataPost('page_fields',$newdata);

	if(isset($newdata['menu_name']))
	{
		$newdata['menu_name'] = preg_replace('/[^\w-*]/','',$newdata['menu_name']);
	}
	return $newdata;	
}
```

**Comment by Jimmi08** [comment]
@sudakk your code will not work in php7.3, see post above yours.  And NULL value was able to get through.

**Comment by sudakk** [comment]
@Jimmi08 post updated according to your note.
