### ISSUE TITLE
font URLs in corporate.css (/e107_themes/bootstrap3/css)

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#3998]
I don't know how much of an issue this is, but the Glyphicons Halflings paths in corporate.css are pointing to a non-existent location (../fonts/bootstrap/ rather than ../fonts/) - presumably a throwback to earlier iterations of e107.

I'm including this CSS file via themes.php on one particular page, and was wondering why my Apache error.log file was full of debug messages from my index page. It seems that when the browser accesses corporate.css, and attempts to reach the Halflings files, my web server responds to this "miss" by serving up the default site page. But this might be unique to my configuration, I haven't probed very far into the what and how.

**Comment by Moc** [comment]
Thanks, fixed it :)
