### ISSUE TITLE
Radio buttons?

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4003]
Maybe someone has an example for radio buttons? This does not work:
`'verein_mitglied_aktiv'	=> array(
			'title'=> 'aktiv?',
			'tab'=>0,
			'type'=>'radio',
			'data' => 'str',
			'help'=>'ist das Mitglied aktiv',
			'validate' => true,
			'writeParms' => array('value' => 'ja',)
			),`
I want a simple yes / no choice.

**Comment by Moc** [comment]
You are looking for the type `boolean` not `radio` :) 
By default, it will use the "Enabled" and "Disabled" text, but if you really want to, you can change the labels by using `'writeParms' => 'label=yesno',`

More info here: https://e107.org/developer-manual#admin-ui

You can also use the Plugin Builder in the Admin Area to help you automatically build your admin area. 

Let me know how it works ;)

**Comment by TrueHatori** [comment]
Thx, now it works.

**Comment by Moc** [comment]
You're welcome!

**Comment by Jimmi08** [comment]
I know, too late, but maybe this helps too  :)
Here you have working examples:
https://www.e107sk.com/documentation/admin-ui-stuff/?cat.110#boolean-field
