### ISSUE TITLE
strong password not being hashed correctly

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#4004]
Issue: special characters in password break the hash

Steps to reproduce:
I installed the latest released version (e107 V2.2.1) and during setup I used a randomly generated strong password for the Administrator account: 

H?r}Fz^bT4N"`DU8

Upon completing the installation, I was unable to log in to the admin account. (Wrong password)

I changed the password in mysql via the cli to the md5 hash of "changeme" (4cb9c8a8048fd02294477fcb1a41191a) and was able to log into the admin account with this password.

I immediatly changed the password back to the originally intended strong password H?r}Fz^bT4N"`DU8 and again was not able to log back in and had to manually reset it back again to "changeme".

**Comment by Moc** [comment]
Perhaps related:
- https://github.com/e107inc/e107/issues/3602
- https://github.com/e107inc/e107/issues/168

**Comment by Moc** [comment]
Confirmed. 

This happens because `"` is transformed into `&#34;` in one of the e107 methods. The new password actually is `H?r}Fz^bT4N&#34;`DU8`. 

Doing more testing to see how we can fix this

**Comment by Moc** [comment]
This has now been fixed. It is not the cleanest method, and perhaps we need to adjust the e107::getParser()->filter() method to include the FILTER_FLAG_NO_ENCODE_QUOTES flag but for now this works.
