### ISSUE TITLE
Q  while main admin debugs FPW, password is real changed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4007]
I was logged in as main admin 

After click on forgotten password, I got message You are logged in as main admin. 

I don't know, but I would suppose that it is for testing purposes, that password will not be changed when I am log in although I use this functionality.

**Comment by Moc** [comment]
As far as I can see in the code, this is intentional. Once you click the "Click to Continue with test" button, you actually follow the link to the password reset page, which one would also get when actually resetting their password. 

I'm adding a message to clarify this.
