### ISSUE TITLE
plugin builder - shortcode file, class name issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4008]
Was something changed in how shortcodes files work?

Plugin builder generated shortcodes file as pluginname_shortcodes.php  (not in batch folder like lonalore uses, neither e_shortcode file). In my case:

efiction_news_shortcodes.php
and inside:
`class plugin_efiction_news_efiction_news_shortcodes extends e_shortcode`

I wasn't able to load those shortcodes, 
`$sc = e107::getScBatch('efiction_news',TRUE);`
only after changing  class name to: 
`class efiction_news_shortcodes extends e_shortcode`

but this way is not possible to add e_shortcode.php file, because it has the same class name. 

I thought that the problem is that class should be used in  shortcodes/batch files, in this file you should use the class with the plugin name in.
this worked before (pattern plugin_pluginname_pluginname_shortcodes)
`class plugin_pnews_pnews_shortcodes extends news_shortcodes {}`

but then I looked at metatag plugin and lonalore uses in batch shortcodes class
`class metatag_shortcodes extends e_shortcode`

I checked function getScBatch description - there are example only for shortcodes/batch/ version.
I checked function getScObject , again example only with shortcodes/batch/

If class generated with plugin builder is correct, could you add example how to use e107::getScBatch() to be able load those shortcodes without changing class name?

Thank you

**Comment by CaMer0n** [comment]
Examples of Usage: 

`$sc = e107::getScBatch('post',  'forum'); `
plugin: forum
class: plugin_forum_post_shortcodes
path: e107_plugins/forum/shortcodes/batch/post_shortcodes.php

`$sc = e107::getScBatch('pm', true 'pm'); `
plugin: pm
class: plugin_pm_pm_shortcodes
path: e107_plugins/pm/pm_shortcodes.php

`$sc = e107::getScBatch('_blank'); ` (returns false if not installed)
plugin: _blank
class: blank_shortcodes
path: e107_plugins/_blank/e_shortcode.php

`$sc = e107::getScBatch('page', null, 'cpage'); `
plugin:  n/a
class: cpage_shortcodes
path: e107_core/shortcodes/batch/page_shortcodes.php

**Comment by Jimmi08** [comment]
I need more time to test this, but:

1. it's confusing that in batch plugin option (forum example) is not plugin name as the first parameter 
 
2. there are exceptions that work (see metatag plugin), I think they shouldn't be supported, it's confusing. Or my example above.

3. it confirms that you can't have the same file name in main and batch folder. For example
```
path: e107_plugins/pm/pm_shortcodes.php
$sc = e107::getScBatch('pm', true, 'pm');
```
```
path: e107_plugins/pm/shortcodes/batch/pm_shortcodes.php
$sc = e107::getScBatch('pm', 'pm');
```
4. example generated with plugin builder doesn't work 
(I called it without 3rd parameter, but it should be default plugin name)

**Comment by Jimmi08** [comment]
This is another way for batch shortcodes (local) for a simple plugin without global shortcodes:

**File:**
`shortcodes/batch/pluginname_shortcodes.php`

**Class naming:**
`class pluginname_shortcodes extends e_shortcode`

**Using:**
`$sc = e107::getScBatch('pluginname', TRUE);`
