### ISSUE TITLE
Question.  Why you can't use file admin.php in admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4015]
if you call your file admin.php, admin theme is not loaded, because e_ADMIN_AREA is not true.

The reason is this:
```
		if	(
			 (!$isPluginDir && strpos($e107Path, $ADMIN_DIRECTORY) === 0 ) 									// Core admin directory
			  || ($isPluginDir && (strpos($curPage,'_admin.php') !== false || strpos($curPage,'admin_') === 0 || strpos($e107Path, 'admin/') !== FALSE)) // Plugin admin file or directory
			  || (vartrue($eplug_admin) || deftrue('ADMIN_AREA'))		// Admin forced
			  || (preg_match('/^\/(.*?)\/user(settings\.php|\/edit)(\?|\/)(\d+)$/i', $_SERVER['REQUEST_URI']) && ADMIN)
			  || ($isPluginDir && $curPage === 'prefs.php') //BC Fix for old plugins
			  || ($isPluginDir && $curPage === 'config.php') // BC Fix for old plugins
			  || ($isPluginDir && strpos($curPage,'_config.php')!==false) // BC Fix for old plugins eg. dtree_menu
			)
		{
			$inAdminDir = TRUE;
		}
```

Is this intention?  you can use anything_admin.php, and anything_config.php,  admin_anything.php or folder /admin/admin.php  but not only admin.php in plugin folder.

Thanks

**Comment by Jimmi08** [comment]
Is this still true? the plugin admin area is detecting by file name? Manually defined ADMIN_AREA is not working.  The only filename with admin_  works.  Correct?

**Comment by Jimmi08** [comment]
@Moc it is not possible for the complex plugin to use one admin file.  Do you have any idea what is it to manage more than 20 classes in one file? One mistake/problem and you kill all admin area.  

There is a different solution in vstore plugin but nobody explained it.  
Look: https://github.com/e107inc/vstore/tree/master/inc

All classes / admin menus  are in separate files, but $modes use parameters that are not documented at all.

**Comment by Moc** [comment]
Ah, that looks like the recommended way to do it then. I'll label it for documentation.

**Comment by Jimmi08** [comment]
Funny, I just run on a situation where this is very welcomed and admin.php needs to be managed by frontend.
