### ISSUE TITLE
Question. Is there way how to use smaller icons in admin UI?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4016]
Now icons are 32px. I would like to have them 16px width. 

it is a waste of place if you have a lot of records

Rows are so height only because icons
 
![image](https://user-images.githubusercontent.com/5429548/68764592-459ca980-061b-11ea-9cfe-999d5fbf3079.png)

**Comment by Jimmi08** [comment]
this is removed this code and it looks that those buttons are always called from admin_icons_template.php 

```
/*                            
		if($attributes['grid'])
		{
			$editIconDefault = $tp->toGlyph('fa-edit');
			$deleteIconDefault = $tp->toGlyph('fa-trash');
		}
*/
```
So either I switch to KA Admin style or I rewrite those buttons in form_ui class. 
If there is another way, I would like to know it.

**Comment by Moc** [comment]
I think you can do this in the admin ui code. Will give you an example asap.

**Comment by Moc** [comment]
For consistency and usability reasons, we want all the Admin Area to look the same across all areas. This is way the buttons cannot be modified through the Admin UI code directly. 

Instead, you can copy the `e107_core/templates/admin_icons_template.php` to the bootstrap3 theme folder, and edit it to your liking. 

E.g.: 
```php
define("ADMIN_EDIT_ICON", "<i class='fa fa-edit fa-2x fa-fw'></i>");
define("ADMIN_DELETE_ICON", "<i class='fa fa-trash fa-2x fa-fw text-danger'></i>");
```

**Comment by Jimmi08** [comment]
Thanks, it will be overridden with next sync.  So custom css is the only solution :)

**Comment by Moc** [comment]
It will not be overriden because the bootstrap3 theme does not contain the template yet. The sync will not delete files.

**Comment by Jimmi08** [comment]
@Moc 
Just letting you know that this is not possible anymore. With a false parameter, you can't override the core template. 

`$ADMIN_ICONS_TEMPLATE = self::getCoreTemplate('admin_icons', null, false);`
