### ISSUE TITLE
Templates (theme templates)

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#402]
I moved forum_icons_template.php in my theme and make changes but seems this template is not used from the theme. I moved the file in templates folder inside the theme and nothing. I think an alternative solution to customize the forum icons is to use a custom forum_icons_template.php inside templates folder in the theme (active theme) that use png, svg  or font icons from the theme. And another thing, please move all templates file inside templates folder of the theme in individual folders like news template, now some templates files like login_menu_template are in the theme root.

**Comment by rica-carv** [comment]
Sorry to say, but i think i got this same issue....
I'm trying to customize the news_template.php from the news plugin, and until now, i got no luck....
I even got 3 copies of news_template.php spread acrross my theme:
-  one on the themes parent folder,
-  other on the `template `folder inside the theme,
-  and other on the `template/news` folder inside the theme....
Without any luck, the news always renders with the news plugin template.....

I've got the latest github core files, so any ideias what's happening???

**Comment by LaocheXe** [comment]
you try renaming it to news.php in your mail theme folder?

**Comment by mcpeace-maw** [comment]
This was resolved log time ago.

**Comment by rica-carv** [comment]
@LaocheXe In my mail theme folder????
@mcpeace-maw It could be resolved long time ago, but it seems to have come back.....

**Comment by mcpeace-maw** [comment]
Working properly.
No offense but I think you should do distinction between real e107's issues which are posted here and your learning problems. Please use e107Help for that.

**Comment by rica-carv** [comment]
@mcpeace-maw In my setup, a custom news_template.php inside a theme doesn't work, despite e107 runs the php file (i know it runs it, since i've placed echo's inside and they are shown...).
So, for me, this is a bug, not my learning problems.....

**Comment by Moc** [comment]
@rica-carv Please see this issue for an explanation of how the template overrides work. I'll integrate this in the documentation on e107.org over the coming few days. 

In your case:

> The news template is located in e107_plugins/news/. To override this template, copy the file over to e107_themes/your_theme_folder/templates/news/.

**Comment by rica-carv** [comment]
@moc 

> In your case:
    The news template is located in e107_plugins/news/. To override this template, copy the file over to e107_themes/your_theme_folder/templates/news/.

This doesn't work.
Check the code of news.php, lines 774-777:
`if(isset($pref['news_unstemplate']) && $pref['news_unstemplate'] && file_exists(THEME."news_template.php"))
{
	// theme specific template required ...
	require_once(THEME."news_template.php");`

As i've stated before, i've tried several approaches:

> I even got 3 copies of news_template.php spread across my theme:
-     one on the themes parent folder,
-     other on the templatefolder inside the theme,
-     another on the template/news folder inside the theme....

After these tests, i found out that the news_template.php has to be on the base theme folder (as per code inside news.php above...), not inside the e107_themes/your_theme_folder/templates/news folder....

**Comment by mcpeace-maw** [comment]
Install bootstrap3 core theme (original one not the one you mode), copy news_template.php from news plugin folder in bootstrap3/templates/news/ folder, open it and search for $NEWS_TEMPLATE['default']['item']=' '; , put some text inside before first div, after open news page and the text added will be before every news.

**Comment by Moc** [comment]
@rica-carv Having multiple templates with the same name in there is of course not the way to go, but I suppose you did this for testing.

> So your ideia doesn't work

It is not my idea. This is the new standard in v2. If this doesn't work then it's simply a bug which needs fixing. 

I'll do some testing asap and I'll get back to you.

**Comment by rica-carv** [comment]
@mcpeace-maw 

> Install bootstrap3 core theme (original one not the one you mode), copy news_template.php from news plugin folder in bootstrap3/templates/news/ folder, open it and search for $NEWS_TEMPLATE['default']['item']=' '; , put some text inside before first div, after open news page and the text added will be before every news. 

[The bootstrap3 core has no such template, check here in github source....](https://github.com/e107inc/e107/tree/master/e107_themes/bootstrap3/templates)

**Comment by mcpeace-maw** [comment]
"copy news_template.php from news plugin folder"

I waste my time to teach you how to test this issue and you can not even read my post? You can not create news folder in bootstrap3/templates and paste a copy of that file in it?
Forget it.

**Comment by rica-carv** [comment]
@mcpeace-maw Sorry, but i misuderstand you, i thought i had to fetch news_template on the bootstrap 3 theme/templates/news, and copy from there...
Now i understand, so i'll try and let you know....

**Comment by rica-carv** [comment]
What the heck?
Now it works as intended.
Simply, i can't understand it....
Got E107 cache off, got browser cache off.....
Can't really figure out what the hell happened....

Please excuse me for all this trouble, but seriously, this morning this wasn't working, and now it is....

**Comment by mcpeace-maw** [comment]
It is OK, right? Well that is the way to test an issue, change the theme with a core one (now bootstrap3 is the only one) and if you can replicate the same issue with the core theme, it is an e107 issue and post the issue here, if not then the issue is in your theme.

**Comment by rica-carv** [comment]
Errr, sorry to bother again, but it seems that the custom news_template.php bug is back again, and this time, with a little twist:
If i'm logged in, news_template.php comes from the core:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14425311/2d810478-ffde-11e5-8900-6d9e93724c20.jpg)

If i'm logged out, it loads from the theme folder:
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/14425306/1e236bba-ffde-11e5-9c7a-e0e0746cacd7.jpg)

Images when testing with bootstrap3 core theme...

**Comment by Moc** [comment]
@rica-carv Do you have caching enabled in the admin area? If yes, disable and clear all of them and see if that makes any difference.

**Comment by rica-carv** [comment]
@Moc I've got cache disabled, and cleaned...
I've got files for 2.1, but i was unable to do the update from admin area today (gives error), so got to download them directly from github and update. Now got version 2.1.2 (git).
And yes, template is in the correct location: (`e107_themes/bootstrap3/templates/news/news_template.php`).
Issue still persists.....

**Comment by CaMer0n** [comment]
@rica-carv news.php, lines 774-777 dates back to v1.x. It's a possibly candidate for removal. 
In your news preferences, make sure "Use non-standard template for news layout" (also a candidate for removal) is "Disabled"

**Comment by rica-carv** [comment]
@CaMer0n I've already tried enable & disable on the "Use non-standard template for news layout" switch.
Issue still persists with any of the options....

**Comment by rica-carv** [comment]
Goddamn, forget it....
My fault (once more).
For the record, i was updating v2.1.2 with the upgraded v1.4 to v2 database data, and on the user table, i had on my username row, this data on the user_prefs field: `a:1:{s:9:"sitetheme";s:0:"";}`
Seems it was old v1.4 data, so i cleaned it up and issue solved....
Sorry for all the trouble....
