### ISSUE TITLE
main menu in admin area on lg size

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4020]
There was an issue about this, I am not able to find it.  

On LG size menu displays only icons.  I don't know but it's pretty annoying and I am sure new users could be confused where options are. 

![image](https://user-images.githubusercontent.com/5429548/69225677-1936df00-0b7f-11ea-8436-fb7d594ff121.png)

On smaller screen titles are displayed

![image](https://user-images.githubusercontent.com/5429548/69225824-66b34c00-0b7f-11ea-88be-e071579f0f2b.png)

I am solving this with the plugin, but I don't understand why this is this way.  There is a reductant hidden-lg class only. 
 
```
if (ADMIN_AREA) {   
    //coloured navigation submenu header
    $js = "
		$(document).ready(function() {
    $('ul.nav-admin').find('span.hidden-lg').each(function() {
  	 $(this).removeClass('hidden-lg');
  	} ); 
		});		
	";}
    e107::js('footer-inline', $js); 
}
```

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/2578

**Comment by Moc** [comment]
After extensive testing, I decided to remove the hidden-lg class altogether. It serves no actual purpose. On larger screens the link text is now shown again, instead of just the icon buttons. 

On smaller devices, < 1000 px width, it will default to the hamburger menu (default bootstrap behaviour) and show the labels correctly. I think this makes sense.

**Comment by CaMer0n** [comment]
@Moc The label should probably be hidden on all screens. They were intentionally removed to avoid scenarios like this: 

![image](https://user-images.githubusercontent.com/2825679/71548263-b811e080-2960-11ea-879a-03ab04cd2330.png)

**Comment by Moc** [comment]
@CaMer0n What's your screen/window resolution on that screenshot?

**Comment by CaMer0n** [comment]
@Moc It's around 1120px wide. Also, once an admin has become accustomed with the interface, the labels serve no purpose other than taking space, and for newbies there's the hover descriptions.

**Comment by Jimmi08** [comment]
@CaMer0n It was re-appeared because titles were displayed for portrait tablets but not for larger screens (above 1200px).   Your example has nothing with @Moc fix.  That problem was there already and it is still there after this fix. There is no reason not to display labels on lg size screen.

![image](https://user-images.githubusercontent.com/5429548/71548595-29797f80-29b1-11ea-885f-ddb7eb6ae07c.png)

In my opinion, the correct fix is to use smaller font sizes for those media queries, not remove labels, but do it anyway, just do it the same way.

**Comment by CaMer0n** [comment]
@Jimmi08 It has been removed from all devices now, but you can add it back in using CSS, if needed. 

    ul.nav-admin a.navbar-admin-button:after { content: attr(title) }

**Comment by Jimmi08** [comment]
This is intention too?
![image](https://user-images.githubusercontent.com/5429548/71719808-c445e400-2e1f-11ea-8c09-a82c696d7f7b.png)
