### ISSUE TITLE
pagination and e_QUERY [FROM] value

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4024]
I can't find the issue where this was mentioned or maybe it was on gitter.

I don't consider this as correct pagination:
page is 3, but URL says 20, because it displays offset, not current page

![image](https://user-images.githubusercontent.com/5429548/69532925-1ec56800-0f77-11ea-840e-637d8c612f8b.png)

I use this parms:

`$parms  = "tmpl_prefix=bootstrap&total={$items_total_count}&amount={$items_per_page}&current={$current_page}&url=" . e_SELF . "?page=[FROM]";`

`$pagination  = $tp->parseTemplate("{NEXTPREV={$parms}}"); `

You can see this with news too. 

Old forum pagination works correctly. 

Maybe some setting? parameter type=page is pagination by one page. 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please test and close if resolved. Thanks.

**Comment by Jimmi08** [comment]
No idea how to test this, From the fix I am not able to get how to use it with some custom plugin, and the original plugin  is not developed anymore. 
Thanks
