### ISSUE TITLE
Question: Logic check

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4026]
I need a logic check, how do I do that? e.g. here, there is an entry date and an exit date. It must not happen that the quitting accidentally before joining.

`'verein_mitglied_beitritt'	=> array(
	'title'=> 'Beitritt',
	'tab'=>0,
	'type'=>'datestamp',
	'data' => 'int',
	'help'=>'Beitritt',
	'validate' => true,
	'writeParms' => ''
),
'verein_mitglied_austritt'	=> array(
	'title'=> 'Austritt',
	'tab'=>0,
	'type'=>'datestamp',
	'data' => 'int',
	'help'=>'Austritt',
	'validate' => false,
	'writeParms' => ''
),`

**Comment by Moc** [comment]
I am not sure if this can be done using the writeParms, will look into that. 

You can definitely check for this using the beforeCreate/beforeUpdate methods, verifying the values before saving and throwing an error if you want.

**Comment by TrueHatori** [comment]
Thanks, that's how it works. However, a system message is used and not my error message. I can live with that ;)

`public function beforeUpdate($new_data, $old_data, $id)
{
	if(($new_data["verein_mitglied_beitritt"] > $new_data["verein_mitglied_austritt"]) AND ($new_data["verein_mitglied_austritt"] != 0)) {
		$mes = e107::getMessage();
		$mes->addError('Austrittsdatum liegt vor dem Beitittsdatum - kann nicht sein!', true);
		$new_data["verein_mitglied_austritt"] = $old_data["verein_mitglied_austritt"];
	}
	return $new_data;
}`

**Comment by Moc** [comment]
> Thanks, that's how it works. However, a system message is used and not my error message. I can live with that ;)

Hmm, it should work with your error message as well. I'll do some testing. 

> Why are your codes formatted and mine not ???

See https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown - Syntax Highlighting.

**Comment by Moc** [comment]
Just tested this on my installations and it's showing the custom error text that I entered. What is the system message that is showing? Can you show your full beforeCreate method code?

**Comment by TrueHatori** [comment]
`public function beforeUpdate($new_data, $old_data, $id)`
		`{`
			`if(($new_data["verein_mitglied_beitritt"] > $new_data["verein_mitglied_austritt"]) AND ($new_data["verein_mitglied_austritt"] != 0)) {`
				`e107::getMessage()->addInfo('Austrittsdatum liegt vor dem Beitittsdatum - kann nicht sein!', true);`
`$new_data["verein_mitglied_austritt"] = $old_data["verein_mitglied_austritt"];
			}`
			`if($new_data["verein_mitglied_beitritt"] < $new_data["verein_mitglied_geburtstag"]) {`
				`e107::getMessage()->addInfo('Beitrittsdatum liegt vor dem Geburtstag - kann nicht sein!', true);`
				`$new_data["verein_mitglied_geburtstag"] = $old_data["verein_mitglied_geburtstag"];`
			`}`
			`return false;`
		`}`
So I get no message, but the system does nothing. If I set return true; , the system enters the incorrectly entered date. Now I do not know what to do, I can only rely on never making a mistake while typing.

**Comment by Moc** [comment]
Why are you using a second parameter in the addError and addInfo methods?
See my example. 

Do you have your plugin in a github repository? If yes, please send me a link so I can test with all your code. 

Also, you are making the code highlighting too complex in your reply ;) It's rather simple as explained here: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
Just use:
`  ```php .... ``` `

**Comment by Moc** [comment]
Try this:
```php
public function beforeUpdate($new_data, $old_data, $id)
{
	if(($new_data["verein_mitglied_beitritt"] > $new_data["verein_mitglied_austritt"]) && ($new_data["verein_mitglied_austritt"] != 0)) 
	{
		e107::getMessage()->addInfo('Austrittsdatum liegt vor dem Beitittsdatum - kann nicht sein!');
		$new_data["verein_mitglied_austritt"] = $old_data["verein_mitglied_austritt"]; 
	}

	if($new_data["verein_mitglied_beitritt"] < $new_data["verein_mitglied_geburtstag"]) 
	{
		e107::getMessage()->addInfo('Beitrittsdatum liegt vor dem Geburtstag - kann nicht sein!');
		$new_data["verein_mitglied_geburtstag"] = $old_data["verein_mitglied_geburtstag"];
	}

	return true;
}
```

**Comment by TrueHatori** [comment]
Now it works, thanks. The second parameter I had read somewhere, then the message should be displayed. I had probably misunderstood something.

**Comment by Moc** [comment]
You're welcome!
