### ISSUE TITLE
html import is not working 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4027]
PHP Fatal error:  Uncaught Error: Class 'tidy' not found in ***e107_plugins\\import\\providers\\html_import_class.php

**Comment by Moc** [comment]
I've added a check. This will allow the import to continue, but without the tidying functions. Not sure what effect this has, still testing.

**Comment by Jimmi08** [comment]
Thanks, I set tidy false to get further, I got available links listed (preview), then select import to news for one of it and ... nothing... just displaying again provider list.  Did HTML import work before at all? XML was working, DB too.  I wasn't able to pin where import for HTML is done.  Saving local copy is working, parsing too.

**Comment by Moc** [comment]
No idea. Doing testing for the first time with it now.

**Comment by Moc** [comment]
I think this code was never finished to begin with. The 'continue' button calls the `doConversion` method which is only printing data (or so it should, it isn't doing that for me now).

**Comment by Jimmi08** [comment]
The problem was fixed by enabling the tidy extension in php.ini  But it's good to have this test. Tidy is necessary 
"You may want to use PHP tidy extension which can fix invalid XHTML structures (in which case DOMDocument load crashes) and also extracts body only".

I will create a new issue if I run in the exact issue (I mean, not generally that it's not working) In my opinion import plugin should be in a separate directory and not in core pack too.
