### ISSUE TITLE
Question:use cdn problem 

### ISSUE THREAD

**Issue by wangxu1144** [e107inc/e107#4034]
I used CDN to speed up the domain name of the website, but after the acceleration, the website will log out when it logs in and refresh the page. What's the problem

**Comment by wangxu1144** [comment]
$this->cookieDelete()->destroy(); 
If you don't use this place, there will be no problem, but I'm afraid there will be some problems, so I want to ask how to solve them

**Comment by Moc** [comment]
This has probably been resolved already in the latest release. Please re-open if the issue still occurs!
