### ISSUE TITLE
php 7.3. regex and  hyphen has to be escaped.

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4036]
Just note.

It was mentioned here already:
`https://github.com/e107inc/e107/issues/3986`

But I found next regex with an unescaped hyphen.  In e107_admin/dp.php file

```
if(isset($_GET['mode']))
{
    $_GET['mode'] = preg_replace('/[^\w-]/', '', $_GET['mode']);
}

if(isset($_GET['type']))
{
    $_GET['type'] = preg_replace('/[^\w-]/', '', $_GET['type']);
}
```

**Comment by Moc** [comment]
Went through all `preg_replace` and think these are all (except for the one in #3986 for which a PR is open).  Not sure about this one:

e_parse_class.php

```php
	if($type === 'file')
		{
			return preg_replace('/[^\w\d_\.-]/',"-",$text);
		}
```

**Comment by Moc** [comment]
Self-note: also good potential for unit testing

**Comment by Moc** [comment]
Think we got them all. Otherwise hopefully they'll be caught by the unit tests.

**Comment by tgtje** [comment]
@Moc  i assume you are talking about caught them all in present files? Helas.. just use preg_replace as search item for this repo (here) There are still some present.. Sorry...

**Comment by Moc** [comment]
Which ones? You need to look specifically for those that cause an error in PHP 7.3

**Comment by tgtje** [comment]
Noticed some hyphens, but probably mistaken. (likely they are already done; understanding as mentioned before).

**Comment by Moc** [comment]
Feel free to let me know which ones you saw. Maybe you are right :)
