### ISSUE TITLE
Q batch option for generate sef-url

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4039]
you can generate sef-url from field in edit mode by using correct write parameters

How to add this functionality as batch option in admin UI (like Export, delete etc) 

It's supported in admin UI already but how to add it to generated admin_config.php file?

I can see that there is trigger sefgen and handleListSefgenBatch method, but how to use it in plugin?

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 This functionality is already there: 

![image](https://user-images.githubusercontent.com/2825679/70357310-6d062100-182b-11ea-9188-5dd308d38950.png)

See line 464 of `e107_admin/newspost.php`

	'news_sef' => array('title' => LAN_SEFURL, 'batch'=>1,  (....)  'writeParms'=>array('size'=>'xxlarge', 'show'=>1, 'sef'=>'news_title')),

**Comment by Jimmi08** [comment]
Thanks, noted.

What 'show'=>1 in writeParms do?  Not mentioned in the documentation.

**Comment by CaMer0n** [comment]
@Jimmi08 I think 'show' could be removed. It's used on 'hidden' fields. 

	case 'hidden':

				$value = (isset($parms['value'])) ? $parms['value'] : $value;
				$ret = (vartrue($parms['show']) ? ($value ? $value : varset($parms['empty'], $value)) : '');
				$ret =  $ret.$this->hidden($key, $value);
			break;

**Comment by Jimmi08** [comment]
Thanks
