### ISSUE TITLE
Cancel option doesn't work in js warning 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4041]
![image](https://user-images.githubusercontent.com/5429548/70248159-d2e6a000-177a-11ea-84ef-0414a6fbbd05.png)

When you generate SEF-URL and you click Cancel, SEF-URL is generated 
(image is only example, it was changed already)

You can test this with news

**Comment by Moc** [comment]
Chrome right?

**Comment by Jimmi08** [comment]
Yes, and Opera too.
