### ISSUE TITLE
datestamp readonly field is editable if empty

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4042]
Is this correct behavior?

`'date_added'              => array (  'title' => 'Added',  'type' => 'datestamp',  'data' => 'int', 'readonly' => true ),`

if this field is empty, then field is able to be edited

![image](https://user-images.githubusercontent.com/5429548/70263401-8f019400-1796-11ea-8dd8-2c81c7e1f446.png)

![image](https://user-images.githubusercontent.com/5429548/70263423-97f26580-1796-11ea-9b23-a7e86620666b.png)

Dumped value: 
` ["date_added"]=> string(1) "0"`

**Comment by CaMer0n** [comment]
@Jimmi08 Readonly has 2 modes: 
1 = read-only, but only when there is a value, 
2 = read-only regardless.
ie. 

    'readonly' => 2

**Comment by Jimmi08** [comment]
Thanks, noted.
