### ISSUE TITLE
search result and HTML markup

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4048]
Some problems.

in this case:
```
					if(!empty($this->search_info[$key]['sfile']) && file_exists($this->search_info[$key]['sfile'])) // Legacy
					{
						$text .= '<div class="search-block">';
						require_once($this->search_info[$key]['sfile']);
						$text .= '</div>';
					}
```
there are missing `<ul>` tags.
![image](https://user-images.githubusercontent.com/5429548/71074829-45944a00-2183-11ea-9381-8d7b763cfa3e.png)

but with not legacy way:
```
						$text .= '<ul id="search-results" class="list-unstyled search-block">';
						$text .= $ps['text'];
						$text .= '</ul>';
						$results = $ps['results'];	
```

is id="search-results"  used for each section and then there are duplicate ids on one page. 

The solution is either add $key to #id to have it unique or move this to class.

And there is different output if there are no results
```
Pages
<div class="alert alert-danger">No matches found</div>
Comments
<div class="search-block">No matches found</div>
```

And this markup is not HTML valid:
```
 <ul id="search-results" class="list-unstyled search-block">
   <div class="alert alert-danger">No matches found</div>
</ul> 
```
https://stackoverflow.com/questions/11755628/can-i-use-div-as-a-direct-child-of-ul

**Comment by Moc** [comment]
@Jimmi08 Is this still the case or has it already been updated?

**Comment by Jimmi08** [comment]
Yes, too much Ids
![image](https://user-images.githubusercontent.com/5429548/106654652-b1f52700-6598-11eb-84fa-3a526c2ef62b.png)

**Comment by Moc** [comment]
Open issues: valid HTML
