### ISSUE TITLE
media manager - url value for files

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4049]
If your path for files (download files or manual upload files, not images) has value {e_MEDIA_FILE},
then URL field displays the wrong value. 

`thumb.php?src=e_MEDIA_FILE%2F2019-12%2Ffilename.pdf&w=800&h=0`

with path {e_MEDIA_IMAGE} , URL value is correct (pretty URL for image) 
Maybe is better doesn't display anything that this. It's confusing. For example, with zip file result ends with 
`https://placehold.it/800x0`
but with pdf, you get error File is not a valid image, but displayed URL is correct.
`File is not a valid image:  e107_media/***/files/2019-12/filename.pdf`

**Comment by Moc** [comment]
What's the status on this one?

**Comment by Jimmi08** [comment]
@Moc No change

**Comment by CaMer0n** [comment]
@Jimmi08 Please try now. (check the media-type value in the database is correct)
