### ISSUE TITLE
Questions to signup template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4055]
1. why is used defined and not isset() for variables? (empty is better choise in fact)
`if(!defined($SIGNUP_BEGIN))`

2. at the end of template is correct template array used:
```
$SIGNUP_TEMPLATE['start'] = $SIGNUP_BEGIN;
$SIGNUP_TEMPLATE['end'] = $SIGNUP_END;
$SIGNUP_TEMPLATE['body'] = $SIGNUP_BODY;
$SIGNUP_TEMPLATE['extended-user-fields'] = $SIGNUP_EXTENDED_USER_FIELDS;
$SIGNUP_TEMPLATE['coppa']= '';
```

but inside signup.php are variables used:
`$text = $tp->parseTemplate($SIGNUP_BEGIN.$SIGNUP_BODY.$SIGNUP_END, TRUE, $signup_shortcodes);
`
Couldn't be they changed to new array?

Why do I ask?  Thank require_once there is the way how to extend template with another plugin. But it fails with signup page because those variables are hardcoded at the beginning of the file:

```
$SIGNUP_BEGIN = null;
$SIGNUP_BODY = null;
$SIGNUP_END  = null;
$COPPA_TEMPLATE = null;
$COPPA_FAIL = null;
```

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 On new themes you can remove `$SIGNUP_BEGIN`, `$SIGNUP_BODY` and `$SIGNUP_END` from the template and place your html code directly into the array, as you would with other templates. 

The intended behavior is that old themes/templates that use only `$SIGNUP_BEGIN`, `$SIGNUP_BODY` and `$SIGNUP_END` continue to function, while new templates should use the array format. 

Ideally, `$SIGNUP_BEGIN`, `$SIGNUP_BODY` and `$SIGNUP_END` should be removed from the core TEMPLATE to avoid confusion.

**Comment by Jimmi08** [comment]
@CaMer0n problem is in signup.php, not in templates

1. last sync e107, bootstrap3 theme,  signup looks ok

2. used core signup template removed $SIGNUP_BODY and content put into $SIGNUP_TEMPLATE['body']  
Form is not displayed.
The reason is:  

`$text = $tp->parseTemplate($SIGNUP_BEGIN.$SIGNUP_BODY.$SIGNUP_END, TRUE, $signup_shortcodes);`

After changing it to:
`$text = $tp->parseTemplate($SIGNUP_BEGIN.$SIGNUP_TEMPLATE['body'].$SIGNUP_END, TRUE, $signup_shortcodes);`
it works again.

Those _new array templates are not used at all_, after loading templates there is missing something like
`$SIGNUP_BODY = $SIGNUP_TEMPLATE['body'];`
after loading templates.

And this:
`$SIGNUP_BODY = null;`
breaks old functionality of overriding template variables, so if this is for old themes, they will not work correctly with old plugins.  Different issue, just commented here.

**Comment by CaMer0n** [comment]
> Those new array templates are not used at all, after loading templates there is missing something like
> $SIGNUP_BODY = $SIGNUP_TEMPLATE['body'];
> after loading templates.
> 
> And this:
> $SIGNUP_BODY = null;
> breaks old functionality of overriding template variables, so if this is for old themes, they will not work correctly with old plugins. Different issue, just commented here.

Thank you @Jimmi08 !! Would you like to make the above changes and submit a pull-request?

**Comment by Jimmi08** [comment]
@CaMer0n can I change the test of defined in signup template to empty? (isset is not enough, it could be empty string)
