### ISSUE TITLE
menu manager and admin folder with _menu file.

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4056]
## Question to menus and menu manager
This is the question because I don't know if this is the intention or not. Maybe for some functionality in admin area? No idea.

I thought that you can create menu files only in the main plugin directory with the name _menu.php.  

But if you create folder "admin" and put there admin_menu.php file, then menus records are created.  It doesn't work for another subfolder name, only for _admin_. Otherwise, this would be nice feature with subfolder _menus_.

It loads admin_menu from main folder too (legacy plugins):
![image](https://user-images.githubusercontent.com/5429548/71586714-737e7480-2b1b-11ea-9c94-df6821d28d13.png)

Problem is that you don't know about those records via Menu Manager (only latest one is displayed)

![image](https://user-images.githubusercontent.com/5429548/71586815-bf311e00-2b1b-11ea-92a8-88ec129e5456.png)

## Expected Source
I tried to check the documentation about rules for creating PHP menus files. 

## Additional Context
If this is the intention, no problem, I will rename my files.  I just want to know the rules.

**Comment by CaMer0n** [comment]
It's a bug. It should not be detected _menu.php files inside 'admin'.

**Comment by Jimmi08** [comment]
> It's a bug. It should not be detected _menu.php files inside 'admin'.
But nothing important, nobody else uses this and I changed the name for that file.

**Comment by Jimmi08** [comment]
Still bug.
@Moc Could you remove label question? Thanks
![image](https://user-images.githubusercontent.com/5429548/131391583-6e29e8e6-2e02-4399-932d-27d10b0f93d4.png)
