### ISSUE TITLE
Menu manager has different markup and doesn't work in some case

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4057]
## Bug Description
Menu manager has no scrollbar on right side and I can't select the needed menu then.

This problem is specific for my new theme and I have no idea what could cause it. 

## Checks done:

- I switched to bootstrap3 frontend theme and MM works
- I tried to new bootstrap4 frontend theme and MM works (to be sure it's not caused with bootstrap4 theme or new HTML layout
- It can't be caused by some plugin because it wouldn't work with another theme either
- no errors in the console
- it's admin theme, it shouldn't be influenced by Frontend theme but it looks like it is.
 

## Screenshots
Not working markup (it looks like tablerender is used)
 
![image](https://user-images.githubusercontent.com/5429548/71585561-4f209900-2b17-11ea-9562-f784a046e0fc.png)

Working version:
![image](https://user-images.githubusercontent.com/5429548/71585645-9ad34280-2b17-11ea-950f-1817e28747bc.png)

## e107 Version

```
latest 2.3 git version
```

### PHP Version

```
PHP Version 7.2.24
```
 
Where to look?  Thanks

**Comment by Jimmi08** [comment]
I have it.

I used custom header and footer shortcodes long time (for variable headers and footers). 
And I used parseTemplate() there. 

But with new theme shortcodes sc_header and sc_footer you can't use parseTemplate there!  It could break menu manager. 

It's correct because those 2 shortcodes are already parsed in 
`if($lm = e_theme::loadLayout($key, $theme))`
 thanks this: 
`	$LAYOUT['_footer_'] = str_replace('{---FOOTER---}', $tp->parseTemplate('{FOOTER}', true), $LAYOUT['_footer_']);`
 
I just didn't know about this. You don't run to any problem if you use core shortcodes (NAVIGATION, SIDEDISCLAIMER, theme shortcodes), only if you use plugin shortcodes. Otherwise I would notice this sooner.

**Comment by Jimmi08** [comment]
@Moc It was solved, problem on my side, but @CaMer0n  should read reason and confirm that this is correct behavior.

**Comment by CaMer0n** [comment]
@Jimmi08 Do you mean that plugin shortcodes defined in e_shortcode.php were causing parseTemplate() to fail under these conditions?

**Comment by Jimmi08** [comment]
@CaMer0n Hard to remember.

No, I don't know what caused this.  But I know that it was fixed by removing parseTemplate() in footer magic shortcode (because those shortcodes are already parsed in $LAYOUT so useless double work and it's not needed anymore )  -  that other issue.

Yes, it caused problems only with plugin shortcodes...  but I can't remember what ones, so maybe they were badly written.  

I remember you added this (parsing {---HEADER---}) to Layout because I use variable headers/footers with shortcodes in files. So it's logical that you don't need to parseTemplate() again in those shortcodes in theme.php
 
After release 2.3.0 I can test this more. Nobody other uses this.

**Comment by CaMer0n** [comment]
@Jimmi08 Okay. Thank you!!
