### ISSUE TITLE
not able to use <pre><code> syntax in tinymce area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4058]
## Bug Description
For  highlight.js I need to use code `<pre><code> </pre></code>` in tinymce area  
Now it's changed to 
`<pre>&lt;code&gt;pre2&lt;/code&gt;</pre>`
by e107. 
I already know that 
`<pre>` and `<code>`
 tags have exceptions and they should not be converted to HTML entities, but if you combine them, this happens

## How to Reproduce
1. Go to news with tinymce plugin activated
2. Either use source button to insert needed code
3. Or insert code, than use button for inserting` <code>` tags, and then button for `<pre>` tags 
4. Check source code before saving that code is inserted correctly
5. After saving check source code again or saved value in database

## Expected Behavior
<code> tag shouldn't be converted to HTML entities

### e107 Version

```
latest github 2.3
``` 

### PHP Version

```
PHP Version 7.2.16
```

**Comment by Jimmi08** [comment]
Tested with simplemde plugin by lonalore that have already this script supported. Before 3 years ago it worked. Now the same result:  `<pre>&lt;code&gt;test&lt;/code&gt;</pre>`

**Comment by Jimmi08** [comment]
@Moc change label to question, this is probably the intention.   I don't need this anymore.

**Comment by CaMer0n** [comment]
@Moc I believe this is the parser error we saw on e107.org.  It should normally be fixed now.

**Comment by Jimmi08** [comment]
It is not. I tried it after that fix.  You don't see it normally because HTML entities are displayed correctly, but you can't use it for js <pre><code>  test doesn't work. 
But as I said, I don't need this anymore.

**Comment by CaMer0n** [comment]
TinyMce also seems to be adding `<br>` instead of `\n` inside the `<pre>` tag.

**Comment by CaMer0n** [comment]
Should be working now. 
See example: https://e107.org/developer-manual/getting-started/hello-world

btw. 

> For highlight.js I need to use code `<pre><code> </pre></code>` in tinymce area

I think you mean: 

`<pre><code> </code></pre> `

**Comment by Jimmi08** [comment]
@CaMer0n 
try to use
```
 /* {THEME_PREF: code=header_width&default=container} */
  /* way how to use theme prefs as shortcodes in HTML layout */
```

Result:
![image](https://user-images.githubusercontent.com/5429548/80745535-bc255900-8b20-11ea-9497-72ab4bb57e0c.png)

```
<pre>&lt;span&gt;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/span&gt;&lt;span&gt;/*&nbsp;{THEME_PREF:&nbsp;code=header_width&amp;default=container}&nbsp;*/&lt;/span&gt;</pre>
<pre>&lt;span&gt;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/span&gt;&lt;span&gt;/*&nbsp;way&nbsp;how&nbsp;to&nbsp;use&nbsp;theme&nbsp;prefs&nbsp;as&nbsp;shortcodes&nbsp;in&nbsp;HTML&nbsp;layout&nbsp;*/&lt;/span&gt;</pre>
```

**Comment by CaMer0n** [comment]
@Jimmi08 I tried what you suggested:

![image](https://user-images.githubusercontent.com/2825679/80836695-26361080-8baa-11ea-9c9f-f1b550161925.png)

TinyMce Source (before saving and after saving/re-editing): 
`
[html]<pre class="line-numbers language-javascript">/* {THEME_PREF: code=header_width&amp;default=container} */
/* way how to use theme prefs as shortcodes in HTML layout */</pre>[/html]
`
I'm not seeing an issue. Can you provide more details?

**Comment by Jimmi08** [comment]
It was adding spans after inserting text, before saving itself. I had to switch to source code, insert that text there, switch back, and then use preformatted code button. 

Now I can't reproduce it. I don't understand. Closing.

**Comment by CaMer0n** [comment]
@Jimmi08 Maybe you copy/pasted from elsewhere? (so it pasted additional tags)

**Comment by Jimmi08** [comment]
> @Jimmi08 Maybe you copy/pasted from elsewhere? (so it pasted additional tags)

Visual Code editor.  
I tried PSPAD before (comment above) because I use it more, but after your comment, it hit me that I was cleaning code and then I used VC.
