### ISSUE TITLE
extend developer options for github sync

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4061]
## Motivation
During Github sync there is the hardcoded list of plugins where the translation is not updated:
`$excludeMatch   = array('alt_auth','tagwords','faqs');`

It would be nice to have this list as a preference under Advanced Features, so the main admin can set it differently per each site.

The similar functionality is needed for core too, now `$excludeMatch   = false; `  
If you have f.e. business site, you don't use plugins like forum, download. I noticed that some people delete login_menu plugin if they don't allow registration or frontend login (and it causes(ed) fatal error with some themes)
 
## Proposed Solution
To add 2 preferences in Advanced Features, the lists of core plugin excluded for sync and for language sync.  The list of core plugins is stable, so checkbox (uncheck) each plugin separately would be nice (not text field) 

On shared hosting, you have no other option on how to get the latest version (of course except using manual FTP)

## Alternatives
Only manual deleting those files after sync.

**Comment by CaMer0n** [comment]
@Jimmi08 Check this out: 

> The popular Git version control system is installed on all A2 Hosting **shared** and reseller accounts.

https://www.a2hosting.com/kb/developer-corner/version-control-systems1/using-git
https://www.a2hosting.com/web-hosting

Also

https://www.inmotionhosting.com/support/edu/cpanel/how-to-use-git-version-control-in-cpanel/

**Comment by Jimmi08** [comment]
I can't use git on my hosting. Like many others.  

How using git helps with getting other plugins translated?

**Comment by CaMer0n** [comment]
@Jimmi08 The links above show that there ARE inexpensive shared-hosting options that support git.

**Comment by Jimmi08** [comment]
It's not a money problem.  I just can't change provider and I don't want to do it either.  It's more about the location and their excellent support.  

The question was how to translate other plugins when I can't change the excluded list.
