### ISSUE TITLE
SQL query does not work

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4066]
This SQL query is not working:
`$uhrzeit = date("H:i:s");`

`$entries = $sql->gen('SELECT logo_bild FROM #css_logo WHERE (logo_beginn =< '.$uhrzeit.') AND (logo_ende >= '.$uhrzeit.')');`

And this doesn't work either:
`$entries = $sql->select('css_logo', 'logo_bild', 'logo_beginn =< '.$uhrzeit.' AND logo_ende >='.$uhrzeit);`

Where is the mistake?

**Comment by Deltik** [comment]
First thing that stands out to me is that you wrote `=<` for "less than or equal to", but "less than or equal to" is actually `<=`.

**Comment by TrueHatori** [comment]
Ok, I tested it, but it doesn't help either, the queries don't work.

**Comment by Deltik** [comment]
Next thing that stands out to me is that the timestamp, `$uhrzeit`, is not quoted but needs to be quoted.

Try `$uhrzeit = $sql->escape(date("H:i:s"));` to turn `$uhrzeit` into a quoted parameter.

**Comment by TrueHatori** [comment]
I tested it, but no, it doesn't work either, thanks anyway. $entries is always empty, in both variants.

**Comment by Deltik** [comment]
What is the schema of the table `#css_logo`?  You can find out with:

```sql
SHOW CREATE TABLE #css_logo\G
```

… replacing `#css_logo` with the table name.

**Comment by TrueHatori** [comment]
`CREATE TABLE IF NOT EXISTS `e107_css_logo` (`
`  `logo_id` tinyint(2) UNSIGNED NOT NULL AUTO_INCREMENT,`
`  `logo_beginn` time NOT NULL DEFAULT '00:00:00',`
`  `logo_ende` time NOT NULL DEFAULT '00:00:00',`
`  `logo_bild` varchar(254) COLLATE utf8mb4_german2_ci NOT NULL,`
`  PRIMARY KEY (`logo_id`)`
`) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_german2_ci COMMENT='die Zeiten für den Logo-Wechsel oben links';`

**Comment by Deltik** [comment]
@TrueHatori: Okay, so it turns out `e_db::escape()` doesn't do anything.  This would quote the time:

```php
$uhrzeit = "'" . date("H:i:s") . "'";
```

If you can make use of PDO (hopefully everyone by now…), **you should use prepared statements** to avoid quoting things yourself:

```php
$entries = $sql->select( 
        'css_logo',     
        'logo_bild',    
        'logo_beginn <= :uhrzeit AND logo_ende >= :uhrzeit',
        ['uhrzeit' => $uhrzeit]);
```

To troubleshoot SQL errors in the future, you can access `$sql->getLastErrorText()` for the error message that was triggered last.

----

Here's the test code I used in [the e107 test harness](https://github.com/e107inc/e107/tree/master/e107_tests):

```php
<?php
/**
 * e107 website system
 *
 * Copyright (C) 2008-2020 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 */

/**
 * @see https://github.com/e107inc/e107/issues/4066
 */
class Issue4066Test extends \Codeception\Test\Unit
{
	public function testIssue4066()
	{
		/**
		 * @var $sql e_db_pdo
		 */
		$sql = e107::getDb();
		$setup = "CREATE TABLE IF NOT EXISTS `e107_css_logo` (
  `logo_id` tinyint(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `logo_beginn` time NOT NULL DEFAULT '00:00:00',
  `logo_ende` time NOT NULL DEFAULT '00:00:00',
  `logo_bild` varchar(254) COLLATE utf8mb4_german2_ci NOT NULL,
  PRIMARY KEY (`logo_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_german2_ci COMMENT='die Zeiten für den Logo-Wechsel oben links';";
		$teardown = "DROP TABLE `e107_css_logo`";
		$sql->gen($teardown);
		$sql->gen($setup);

		$sql->insert("css_logo", [
			'logo_bild' => 'dummy text',
			'logo_beginn' => '12:34:56',
			'logo_ende' => '12:34:58',
		]);

		$uhrzeit = $this->date("H:i:s");
		$entries = $sql->select(
			'css_logo',
			'logo_bild',
			'logo_beginn <= :uhrzeit AND logo_ende >= :uhrzeit',
			['uhrzeit' => $uhrzeit]);
		$this->assertEquals(1, $entries, "Prepared statement select didn't return expected count");

		$rc = $sql->gen($teardown);
		$this->assertTrue($rc, "Table deletion should have succeeded");
	}

	private function date($_garbage)
	{
		return '12:34:57';
	}
}
```

The test passes, so I cannot reproduce a problem once the `SELECT` code is written correctly.

**Comment by TrueHatori** [comment]
It doesn't work, sorry.

**Comment by Deltik** [comment]
@TrueHatori: Don't double-quote `$uhrzeit`.  Do **either** the surrounding quotes or the prepared arguments, but not both.

**Comment by TrueHatori** [comment]
Ok, I found the failure, now it works. Thanks.
