### ISSUE TITLE
Not able detect page with book/chapter SEF-URL

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4068]
## Bug Description
Because can't use e_QUERY for current page detection, so this is common way how to do it:

`if($page == 'page.php' && isset($_GET['id']))`

With book/chapter/page SEF URL  value of $_GET is wrong and this test fails:

## How to Reproduce
1. Set URL configuration to /page/book-title/chapter-title/page-title
2. Allow Book/Chapter page listing
 
- for single page - it's correct 
```
 e_QUERY id=13 
 [id] => 13
```

For page under chapter:
URL f.e. /general/chapter-1/article-1
```
e_QUERY id=13
Array
(
    [book] => general
    [chapter] => chapter-1
    [name] => 1
    [id] => 
)
```

If you change URL cofiguration to page/page-title:
```
/article-1
e_QUERY 1.0
Array
(
    [name] => 1
    [id] => 1
)
```

 
### PHP Version

```
PHP 7.0.
```

**Comment by CaMer0n** [comment]
@Jimmi08 This is not a bug. If you wish to check a page request, you should use the following code designed for this purpose, instead of checking $_GET: 

    $page = e107::getRegistry('core/page/request');

Example result for **/general/chapter-1/article-2** : 
```
array (size=2)
  'action' => string 'showPage' (length=8)
  'id' => int 2
```

**Comment by Jimmi08** [comment]
Thanks.  Yes, it works, but I have a little problem with this approach.

"page" is for pages (book/chapters) , correct?   And it works only for pages?  So I still need to know e_PAGE == "page.php" and only then use this?  Correct?

@lonalore should then change his testing for pages too in metatag plugin.

**Comment by CaMer0n** [comment]
@Jimmi08 What value do you get for $page when on a non-"pages" URL ?

**Comment by Jimmi08** [comment]
Sorry, I wasn't clear.
Before you had e_PAGE and it was clear and you just tested e_PAGE value.
I understand that it's complicated with SEF-URLs, I don't say it's wrong, ok?

So to test what part of e107 is used, I need always to use:

```
$page = e107::getRegistry('core/page/request');
if (is_null($page))
  Next tests... back to e_PAGE and e_QUERY or e_CURRENT_PLUGIN, e_LEGACY_URL
}
else {
 you are on pages... 
}
```
And it still fails in the gallery. 

I am looking for replacing the test of e_PAGE, which returns "page", "news" (anything)... like before page.php, news.php etc)

**Comment by CaMer0n** [comment]
@Jimmi08 Please update from git. I added e_PAGE definition changes for plugins using e_url.php with SEF.

**Comment by Jimmi08** [comment]
@CaMer0n 
where should be e_PAGE available?

- in e_module.php - it's not defined
- in e_events.php - it's not defined (but metatag plugins uses it here)
- in e_header.php - it's available 

With legacy URLs e_PAGE is defined in all those addons.

**Comment by CaMer0n** [comment]
@Jimmi08 I'm looking into it. I don't think it will be an easy fix though.

**Comment by Jimmi08** [comment]
@CaMer0n I know.  I would postpone this to far far future. Maybe even close this.  It looks like nobody needs this and, frankly, there is no real use for the book/chapter/page system.  No offense.   

It looks like an attempt to combine the content plugin with the old page/menu system but...    

Don't waste time on this. I have already a solution for real series/books/chapters, so I will not bother you with this part of e107 anymore.   But thanks for your time.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 .
