### ISSUE TITLE
wrong class name in e_url addon breaks admin configuration  

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4075]
I am not sure if I should report something like this.

It was my mistake, I am renaming plugin and I forgot to change class name in e_url addon.
Something like this breaks the admin URL configuration window. 

I don't know, I would wait for some error (debug is on) or checking that needed class exists. 

![image](https://user-images.githubusercontent.com/5429548/72730327-76f0a300-3b91-11ea-948d-f27463a0c560.png)

plugin name tags
file name e_url.php
wrong class name class tagcloud_url

At first, I thought it's because core tagcloud plugin was installed (not sure if there is test if the class already exists), but uninstallation didn't help.

Let me know.

**Comment by CaMer0n** [comment]
@Jimmi08 In debug mode, it should throw an error. Did you find one?

**Comment by Jimmi08** [comment]
Nothing related to this, but it was PHP 7.3. I use browser debug, which one to set? Basic should be enough?

**Comment by Jimmi08** [comment]
No debug. With error (wrong class name)
![image](https://user-images.githubusercontent.com/5429548/72816697-dbcafc80-3c68-11ea-94aa-16af96c88661.png)

After fix class name:
 
![image](https://user-images.githubusercontent.com/5429548/72816793-fd2be880-3c68-11ea-9cd4-8a7b5a95667e.png)

Here is code of e_url file, maybe it's problem there.
https://github.com/Jimmi08/e107-free-plugins-by-e107sk/blob/master/tags/e_url.php

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, Basic debug mode should show any php errors associated with your code.

**Comment by Jimmi08** [comment]
> @Jimmi08 Yes, Basic debug mode should show any php errors associated with your code.

In the answer above yours are screenshots from debug mode.

**Comment by CaMer0n** [comment]
@Jimmi08 Here's how the page looks to me with debug enabled after renaming `faq_url` to `download_url` . (ie. a duplicate class name in e_url.php) 

![image](https://user-images.githubusercontent.com/2825679/73126935-b5a9a300-3f6d-11ea-9e31-f67b8ed98f6b.png)

If this isn't the case for you, you may want to check your php.ini settings.

**Comment by Jimmi08** [comment]
Please try not duplicate class but not existing.  
I have never seen report like this and I have display errors on. It's localhost with xampp.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 I was able to reproduce the issue with a missing class.
