### ISSUE TITLE
New HTML layout and theme shortcodes loaded 2x

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4078]
## Bug Description
If you use theme shortcodes in theme.html file, they are loaded 2x. It's not visible, of course, but if you echo something while debugging, you can see that it's echoed 2x.  If you put this shortcode to layout html files, it's rendered only one time.

## How to Reproduce
1. use bootstrap3 theme, f.e. BOOTSTRAP_USERNAV shortcode
2. in theme_shortcodes add some output f.e. `print_a('bootstrap_usernav'); ` You can see it's loaded 2x
4. If you move this shortcode to f.e. home layout, its loaded only one time.

## Expected Behavior
If this behavior is correct, a clear definition that you shouldn't use theme shortcodes in theme.html file.
 
## Screenshots
![image](https://user-images.githubusercontent.com/5429548/72883806-492c6b00-3d05-11ea-9e32-af970db83dae.png)

 
### PHP Version
PHP Version 7.3. 
 
## Additional Information
Using {---HEADER---}  doesn't help, still 2x, only moving header to _layout.html

**Comment by CaMer0n** [comment]
@Jimmi08 I don't find any problem. `{BOOTSTRAP_USERNAV}` is called **twice** in theme.html

Line 18: 	`{BOOTSTRAP_USERNAV: placement=top}`
Line 69:    `{BOOTSTRAP_USERNAV: placement=bottom&dir=up}`

If you test with a different shortcode such as `{BOOTSTRAP_BRANDING}` , it will load once, as intended.

**Comment by Jimmi08** [comment]
@CaMer0n  I wasn't talking about rendering. You visually don't see any problem.  
But class theme_shortcodes is loaded (called) twice times now.

**Comment by CaMer0n** [comment]
@Jimmi08 theme_shortcodes will be loaded whenever required. Each shortcode is not called twice from what I can tell. Please list the steps to reproduce duplicate calling of shortcodes, if you still think it is actually the case. Thanks.

**Comment by Jimmi08** [comment]
> Steps to reproduce the behavior:
> 
> use bootstrap3 theme, f.e. BOOTSTRAP_USERNAV shortcode
> in theme_shortcodes add some output f.e. print_a('bootstrap_usernav'); You can see it's loaded 2x
> If you move this shortcode to f.e. home layout, its loaded only one time.

**Comment by CaMer0n** [comment]
> You can see it's loaded 2x

No, you can see it is **called** twice, because it appears twice in theme.html

Line 18: {BOOTSTRAP_USERNAV: placement=top}
Line 69: {BOOTSTRAP_USERNAV: placement=bottom&dir=up}

**Comment by Jimmi08** [comment]
Oh, I get it now. But it happened to me with a custom theme and shortcodes. This was just testing with boostrap3.  Thanks for your time.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 . Send me your theme with custom shortcodes and I'll be happy to test it for this issue.
