### ISSUE TITLE
email problem with forum

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4079]
I just want to mention this, maybe somebody else has this problem.   

From some point, it stopped to send mail notification from forum plugin.

Test email (in Notify section) works, email is received.   
Notify about user log in, chatbox post works, so notification itself works. 

I am not receiving emails about a new topic (before I got them 2x) and about new answers.  

Github version from 14.1.2020

**Comment by Jimmi08** [comment]
Just note:
```
Fatal error: Uncaught Error: Class 'forum_notify' not found in 
***e107_handlers\event_class.php:204 Stack trace: #0 
***\e107_plugins\forum\forum_class.php(828): e107_event->trigger('user_forum_post...', Array) #1 ***\e107_plugins\forum\forum_class.php(972): e107forum->postAdd(Array, false) #2 ***\e107_plugins\forum\forum_post.php(1242): e107forum->threadAdd(Array, Array) #3 ***\e107_plugins\forum\forum_post.php(206): forum_post_handler->insertPost() #4 ***\e107_plugins\forum\forum_post.php(89): forum_post_handler->processPosted() #5 ***\e107_plugins\forum\forum_post.php(1756): forum_post_handler->__construct() #6 ***\index.php(69): include_once('C:\\xampp72\\htdo...') #7 {main} thrown in
***\e107_handlers\event_class.php on line 204
```

**Comment by Jimmi08** [comment]
Using test notify for  user_forum_post_created 
causes fatal error on live site. 

error log:

` PHP Fatal error:  Uncaught Error: Class 'forum_notify' not found in /***/e107sk.com/web/e107_handlers/event_class.php:204\nStack trace:\n#0 /***/e107sk.com/web/e107_admin/notify.php(226): e107_event->trigger('user_forum_post...', Array)\n#1 /***/e107sk.com/web/e107_admin/notify.php(122): plugin_notify_admin_ui->test()\n#2 /***/e107sk.com/web/e107_handlers/admin_ui.php(1405): plugin_notify_admin_ui->init()\n#3 /***/e107sk.com/web/e107_handlers/admin_ui.php(1378): e_admin_dispatcher->_initController()\n#4 /***/e107sk.com/web/e107_handlers/admin_ui.php(1264): e_admin_dispatcher->getController()\n#5 /***/e107sk.com/web/e107_handlers/admin_ui.php(1074): e_admin in /***/e107sk.com/web/e107_handlers/event_class.php on line 204, referer https://www.e107sk.com/e107_admin/notify.php`

**Comment by Jimmi08** [comment]
The only difference against working download plugin (or working other forum notification) is that user_forum_post_created is used for e_event and for e_notify. 
After changing user_forum_post_created in e_notify (with reinstalling forum plugin, notify_prefs are not changed any other way) to a different name, that fatal error is gone.

**Comment by Moc** [comment]
Doing extensive testing, but not able to reproduce your issues yet. 
- The notifications work fine on localhost for me. PHP 7.2 and 7.3. 
- Cannot reproduce the fatal error 

Other issues found:
1) Post (reply) created, sends the wrong notification (thread updated)
2) When deleting a post/topic, the notification is sent out before the deletion is confirmed (alert dialog box by browser) 
3) Debug mode on, doing a 'Test' notification on user_forum_post_created gives an SQL error:
``` 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
```

**Comment by CaMer0n** [comment]
@Jimmi08 @Moc I tried a "user_forum_post_created" test notification from the admin notifications area. (to MainAdmin and an "Email address") and had no issue. What settings are you using?

**Comment by Jimmi08** [comment]
@CaMer0n I had to rename function in e_notify function, otherwise no notification and fatal error.  
In my case, it could be caused by using outdated e_notify in some old plugin and using a metatag plugin.  Some conflict between e_event and e_notify. I am not able to debug or test this anymore.

**Comment by CaMer0n** [comment]
@Jimmi08 I'm happy to investigate with you on your site.  Are you still using gitter sometimes?

**Comment by Jimmi08** [comment]
Error is back, I can't let it this way too long.

**Comment by Jimmi08** [comment]
@CaMer0n I forgot to mention you to get the notification.

**Comment by CaMer0n** [comment]
@Jimmi08 ah, sorry, I missed you! Please PM me on gitter when you have time.

**Comment by CaMer0n** [comment]
I was able to reproduce this issue after installing the Mentions plugin by @arunshekher 
While there is technically nothing wrong with the code, it uses e107::getEvent()->register() inside e_module.php instead of registering the events via e_event.php or e_notify.php
