### ISSUE TITLE
New Forum icons

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#408]
In v.2 I see 2 new icons that are not defined in forum_icons_template.php and are not between the icons from Forum folder, so they can't have a custom image like the other forum icons. The 2 icons are used in News, but if you put in the news custom icons using:
define('ICONMAIL', 'mail.png');
define('ICONPRINT', 'printer.png');
in the forum are used the default icons. I think for unity it is necessary the 2 new icons used in forum to have icon images like other icons in the forum in forum folder and to be defined in forum_icons_template.php for easy customization. And in the news to be like before defined with - define('ICON... 
Also  must be added the possibility to use font icons not just images for all icons on e107.

**Comment by CaMer0n** [comment]
Closing. This was done a while back
