### ISSUE TITLE
date information on user profile issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4080]
When you click **on your own profile** link, it looks like this (see relative time ):
![image](https://user-images.githubusercontent.com/5429548/73246026-e415c100-41ad-11ea-8562-36f007221277.png)

After refresh page:
![image](https://user-images.githubusercontent.com/5429548/73246068-00b1f900-41ae-11ea-9875-11dce76ab446.png)

I tried to find a reason. 

Shortcode  `{USER_LASTVISIT_LAPSE}` uses `e107::getDate()->computeLapse($this->var['user_currentvisit'])` , so I can see that this should be solved (just now solution). 

But in some cases there are values (in most of cases there is at least 1 second difference):
`print_a($older_date);     print_a($newer_date);    print_a($ret);`
![image](https://user-images.githubusercontent.com/5429548/73246461-fd6b3d00-41ae-11ea-8334-6c243000e273.png)
so this fails:
`if(strpos($ret[0],$secs) !== false)`

Could you add just now a solution for this scenario too?

*
Text ago is displayed twice time, because 
LAN string uses this text: ` [x] ago `

but shortcode adds next there:
` return $this->var['user_currentvisit'] ? "( ".e107::getDate()->computeLapse($this->var['user_currentvisit'])." ".LAN_USER_34." )" : '';`

so ago is displayed 2x.

**Comment by Moc** [comment]
Related https://github.com/e107inc/e107/issues/3605

This issue will also happen on any location where the newly inserted data is done through AJAX (no refresh). After refresh, all is fine.

**Comment by Jimmi08** [comment]
I don't know now if you confirmed the reason for this or not (that issue is not related).  Problem is that there is no scenario if both times are the same. It should return Just now too. ($ret is empty, not only  if first key is seconds)

**Comment by Moc** [comment]
These are multiple bugs, which I confirm :)

**Comment by tgtje** [comment]
Proposing (it is what one sees) : since
LAN_USER-34 is used only once > change the text to
`define("LAN_USER_34", " &#62; today"); instead of `define("LAN_USER_34", "ago");`	`
so it would display :   ( 1 second ago > today )  and  ( in > today ) instead
