### ISSUE TITLE
add parameter for type url in Admin UI to open in new window in read mode

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4081]
## Motivation
If you want to display URL (type url) in read mode, it's because you want to click directly on this link to check it.  Without `target=_blank` this link is opened on the same window.  

Yes, I know that I can use mouse right click. It's annoying if you forget to use it.

## Proposed Solution
If you don't want to change this as default, something like this would be handy
` 'readParms' => array('target'=>'_blank')`

If it is there already, I didn't find it.

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please give this commit a try. You can also use: 

    readParms('class'=>'e-modal')

**Comment by Jimmi08** [comment]
I couldn't sync again... so I repeated your changes manually

It works. Perfect.  Just note for e_modal -  because it really looks better -  
if the target site uses "in a frame because it set 'X-Frame-Options' to 'sameorigin' "   nothing is displayed.

Thank you very much, this is very helpfull.
