### ISSUE TITLE
fields, Admin UI and init

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4083]
Not sure how to call this or how to describe it.  It's not bug, but maybe it's scenario you didn't consider.

I have a bit complicated admin area - more than one view (admin UI for one table), so I have one full Admin UI class and others just extend this one and only $fields are changing. 

But I need to change init() too because of this.

If you use in init() field that is not in $fields list (by mistake or parent class uses this), like this 

```
		// Set drop-down values (if any). 
		$this->fields['catid']['writeParms']['optArray'] = array('catid_0','catid_1', 'catid_2'); // Example Drop-down array. 
```
but catid is not in $fields.

This field is displayed here: (list of available columns)
![image](https://user-images.githubusercontent.com/5429548/73431431-b3b25c00-4340-11ea-94dc-d9c44309a9bf.png)
and the user is able to display it (it's displayed after options column)

![image](https://user-images.githubusercontent.com/5429548/73431532-ee1bf900-4340-11ea-9b98-1ad6523069f2.png)

Maybe you could display there only fields with 'field' set? 
Because that field looks like this. 

```
    [catid] => Array
        (
            [writeParms] => Array
                (
                    [optArray] => Array
                        (
                            [0] => catid_0
                            [1] => catid_1
                            [2] => catid_2
                        )

                )

        )
```
Yes, I was able to fix it, 
```
	public function init()
	{
		parent::init();
		$this->fields['catid'] = array();
	}
```
but then I noticed next problem:
Column is still displayed (because columns are probably saved in user settings ) ,
so there is no testing if saved user fields are used in this Admin UI. 
It could be a problem if this column is removed from displaying in next update .

![image](https://user-images.githubusercontent.com/5429548/73432189-7f3f9f80-4342-11ea-9192-78c86f991b7e.png)

**Comment by Jimmi08** [comment]
It's different problem, but solution is related:

https://github.com/e107inc/e107/issues/4084

**Comment by CaMer0n** [comment]
@Jimmi08 It should be fixed. Please re-open if necessary.
