### ISSUE TITLE
field with type false (not visible, only saved) is able for user to see

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4084]
## Bug Description
I have field that is filed only during update record.  In beforeUpdate() method.
This field has to be listed in $fields, otherwise it's not saved.
Way how to do it is:

> type = false (without quotes) | Hide this field but save it's data if a posted key value is found.

It works. 

Problem is that this field is listed in available columns and after adding it by user, it's content is displayed in read more. 

## How to Reproduce
My field definition:
```
		'updated'                 => array (  'title' => 'Updated', 
		'type' => false,  
		'data' => 'str',),
```

## Expected Behavior
 User is not able see any way content of this field.

## Screenshots
 
![image](https://user-images.githubusercontent.com/5429548/73451608-49151680-4368-11ea-981d-fd90cb698a34.png)

![image](https://user-images.githubusercontent.com/5429548/73451648-60ec9a80-4368-11ea-847f-48e7e5e5e768.png)

 
### PHP Version

```
PHP 7.2
```

**Comment by CaMer0n** [comment]
@Jimmi08 Why don't you use `type=hidden` ?

**Comment by Jimmi08** [comment]
@CaMer0n Because according to documention I want the hidden field but saved in the database. 
`type = false (without quotes) | Hide this field but save its data if a posted key value is found.`

**Comment by CaMer0n** [comment]
@Jimmi08 Did you try `type = hidden`? (it is also in the documentation) . 

`type = false` is typically used when placing 2 fields into a custom method.

**Comment by Jimmi08** [comment]
But that field should be displayed in read mode. I am confused now.

**Comment by Moc** [comment]
Closing, using `type = hidden` should do the trick. If not, please re-open.
