### ISSUE TITLE
custom values for boolean field have problem with national characters

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4085]
## Bug Description
 I have defined my values for boolean fied
`'writeParms' => array ('enabled'=>'Téma', 'disabled'=>'Článok'), `

Those values are converted to Uppercase (not with css) 
```
<span class="bootstrap-switch-handle-on bootstrap-switch-primary" style="width: 66px;">TéMA</span>
<span class="bootstrap-switch-handle-off bootstrap-switch-default" style="width: 66px;">ČLáNOK</span>
```
![image](https://user-images.githubusercontent.com/5429548/73454890-4964e000-436f-11ea-8f36-c1c5d3c53b45.png)

Switching to Slovak admin lang didn' help.

After changing to UpperCase in Admin UI, characters are displayed correctly, so problem is in way how you convert this text to UpperCase.

`'writeParms' => array ('enabled'=>'TÉMA', 'disabled'=>'ČLÁNOK'), `

**Comment by CaMer0n** [comment]
@Jimmi08 Is this still an issue?

**Comment by Jimmi08** [comment]
Yes,
national characters are not to changed to uppercase. They are displayed correctly. 

![image](https://user-images.githubusercontent.com/5429548/75191983-af1c7000-5753-11ea-9be2-0a6544fe2129.png)

**Comment by Moc** [comment]
@Jimmi08 Still an issue?

**Comment by Jimmi08** [comment]
it looks like fixed
![image](https://user-images.githubusercontent.com/5429548/146913268-1edeed8d-1656-47ce-a9b7-6691cda9f61b.png)
