### ISSUE TITLE
how to displaye custom values for boolean field in read mode and filter mode?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4086]
#3652  Question

With custom values for Yes/No texts, they are correctly displayed in Write mode.

What is the correct settings to have it displayed with those value? 

Now it looks like this, 
```
		'readParms' => array ('enabled'=>'TÉMA', 'disabled'=>'ČLÁNOK'), 
		'writeParms' => array ('enabled'=>'TÉMA', 'disabled'=>'ČLÁNOK'), 
```
With filter, there is still Yes/No
![image](https://user-images.githubusercontent.com/5429548/73455653-cba1d400-4370-11ea-87e4-011c7352b739.png)

And with Read mode with inline editing:
![image](https://user-images.githubusercontent.com/5429548/73455728-e8d6a280-4370-11ea-85f9-42844b5ce26e.png)

With Read mode without inline editing:
![image](https://user-images.githubusercontent.com/5429548/73455785-03a91700-4371-11ea-88da-9e05b193c5d0.png)

 Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I believe readParms() was using 'true'=>'custom' instead of 'enabled'='custom'. 
This has been fixed, so that read/write Parms can use either enabled/disabled or true/false key values.

I will look into the 'filter' dropdown.

**Comment by CaMer0n** [comment]
@Jimmi08 Please test it out and let me know. Thank you.

**Comment by Jimmi08** [comment]
Thank you, tested, filter, inline edit mode work.
