### ISSUE TITLE
Github sync fails again after adding test folder - could you increase time again?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4087]
## Slower server is not able to download full zip file
There was the similar problem before
https://github.com/e107inc/e107/issues/2867

` curl_setopt($cp, CURLOPT_TIMEOUT, 40);//FIXME Make Pref - avoids get file timeout on slow connections`

I couldn't sync some for time now on local xampp, then I remembered this issue and voila, after changing 40 to 100, sync worked without problems.  

PS. I would remove LZ theme from core. It's too big.

**Comment by CaMer0n** [comment]
@Jimmi08 You don't have git installed locally?

I use the Git Sync under "Schedule" and it only downloads the changes, rather than the entire repo. 

![image](https://user-images.githubusercontent.com/2825679/73616407-ba063980-45c7-11ea-8ca3-ab792ad2a39c.png)

**Comment by Jimmi08** [comment]
No, I use normal git sync as main admin in Database tools.

**Comment by Jimmi08** [comment]
This should be a preference or input field to set when I select synchronization with Github.  It worked with value 80.

**Comment by LaocheXe** [comment]
@CaMer0n only update "Schedule" that I've seen on my websites is _system::checkCoreUpdate

Where is this _system::gitrepo ??

**Comment by CaMer0n** [comment]
@LaocheXe Do you have shell access? You need to have a .git folder in your install for it to show up. 

@Jimmi08 LandingZero was removed from the core, hopefully this speeds things up.

**Comment by Jimmi08** [comment]
Thanks
