### ISSUE TITLE
Admin panel icons not growing/shrinking as plugins are being added/removed beyond 20.

### ISSUE THREAD

**Issue by Usalabs** [e107inc/e107#4088]
## Bug Description
Admin theme 'Bootstrap 3' using the layout of either flexpanel or infopanel doesn't allow more than 20 icons to be shown at any given time, no matter how many plugins are installed, even trying the customize icons still only shows 20.

## How to Reproduce
1. Go to 'Front Panel'
2. Scroll down to see admin panel of icons
3. Click on 'Manage' icon at the top bar, then click on 'Plugin Manager'
4. Click on 'Not Installed' on the left, then click on the 'Install' icon to install a plugin, then install 2 or 3 more plugins
5. Ignore the 'Configure' options, then click on the E107 logo at the far left top corner of the page, which will open the front panel.
6. Scroll down and see the 'Welcome Message' button and any icons before that,has been hidden to make room for any additional icons, hence only 20 icons shown.

## Expected Behavior
What should happen is, when installing plugins that a configurable, the button is auto displayed on the front panel, and the icon grid should grow and shrink as more plugins are added or removed, so, if 12 plugins are installed than the front panel should show 15 (default)+12=27 icons and not fixed at 20.

## Server Information
Headless Ubuntu Server 18.04.4 LTS

### PHP Operating System
PHP 7.2.27
```
### PHP Modules

[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache



### Client Information

Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

## Additional Information
I can 't upload screenshot video here, so I've added it to my dropbox:-

https://www.dropbox.com/s/6g2sjwbsxi0iqjl/Screen-Video.mp4?dl=0

**Comment by CaMer0n** [comment]
@Usalabs The icons in your admin panel are specific to your account. To customize what display here, go here, choose "Personalize" in the upper right: 

![image](https://user-images.githubusercontent.com/2825679/73616348-14eb6100-45c7-11ea-9e68-a3a52294f12e.png)

Check the box next to the plugins you wish to display, then save.

**Comment by CaMer0n** [comment]
Closing, but please re-open if I missed something else.
