### ISSUE TITLE
User admin columns depend on table, do it more flexible way

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4089]
## Motivation
I use more listings (Admin UI way} on the same table. Different views of the same data. 
I just now found that you are saving user columns of Admin UI 

```
		$this->fieldpref = $new;
		return e107::getUser()->getConfig()
			->set('admin_cols_'.$this->getTableName(), $new)
			->save();
```

This way you override columns for any Admin UI for the same table. 

## Proposed Solution

Either:
- to have this as property (like eventName) 
or
- to have the option to set this functionality off  (not remove column settings, only saving it as prefs, for Admin UI class, not just for option field)

Yes, I know that there is "noselector" param to set this functionality off, but it doesn't solve this problem. 

Thank you

**Comment by CaMer0n** [comment]
@Jimmi08 Please give it a try in admin-ui (enable debug to see what is happening): 

    $table = 'mytable';
    $fieldpref = (etc)..... 
    $fieldPrefName = 'mykey';

**Comment by Jimmi08** [comment]
Perfect. 
I use and tested this way in init()

`$this->fieldPrefName   	= $this->pluginName."-".$mode; 	`

It worked flawlessly, exactly as should have

Thank you.

**Comment by CaMer0n** [comment]
@Jimmi08 You reminded me that I need to prevent plugins overwriting each others' prefs. 
So, now `$this->pluginName` is prefixed by default. 
So, in your case, you can now simply use: 

    $this->fieldPrefName = $mode;

**Comment by Jimmi08** [comment]
@Moc 
this should be marked as documentation and added to blank plugin
