### ISSUE TITLE
default value for pref field in Admin UI

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4090]
This doesn't work anymore for Prefs:
'default'=>true,

Only this:
'writeParms'=>array('default'=>true)

It's a bit complicated now, why did you change this?  It's not common to use writeParms for the preference field. 

Edit:
This:
'writeParms'=>array('default'=>true)
causes that value is always true. You can't change it.

**Comment by CaMer0n** [comment]
> This doesn't work anymore for Prefs:
'default'=>true,`

It's not in the documentation. I don't recall that ever being implemented. 

> 'writeParms'=>array('default'=>true)
causes that value is always true. You can't change it.

What field type are we talking about in this case?

**Comment by Jimmi08** [comment]
@CaMer0n  About preferences.  (Fields are clear, there is Read and Write mode)

Prefs are in Write mode by default .   $pref is not mentioned in documentation, only $fields 

And it's a boolean type.   And yes, I know, that I can set this in plugin.xml.  But it's easier to check this in one place (admin UI).

**Comment by CaMer0n** [comment]
@Jimmi08 Normally it should work. Are you sure the pref value is empty?
```

$parms = vartrue($attributes['writeParms'], array());

if(empty($value) && !empty($parms['default']) && $attributes['type'] !== 'dropdown') // Allow writeParms to set default value.
{
	$value = $parms['default'];
}
```

**Comment by Jimmi08** [comment]
Works
