### ISSUE TITLE
Add some event to Tools/Database/Scan Plugin Directories

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4091]
## Motivation
If the custom plugin uses its own addon solution (example metatag plugin with e_metatag addon),  it would be nice when scan plugin directories would fire the same event to update not core addon too. 

## Proposed Solution
It uses those events bellow:  No idea if **admin_plugin_refresh** event was planned exactly for this, but it would be nice to have it working.

```
		// After updating plugins table.
		$event[] = array(
			'name'     => "system_plugins_table_updated",
			'function' => "metatag_update_addon_list",
		);

		// After a plugin is installed.
		$event[] = array(
			'name'     => "admin_plugin_install",
			'function' => "metatag_update_addon_list",
		);

		// After a plugin is uninstalled.
		$event[] = array(
			'name'     => "admin_plugin_uninstall",
			'function' => "metatag_update_addon_list",
		);

		// After a plugin is upgraded.
		$event[] = array(
			'name'     => "admin_plugin_upgrade",
			'function' => "metatag_update_addon_list",
		);

		// Plugin information is updated.
		$event[] = array(
			'name'     => "admin_plugin_refresh",
			'function' => "metatag_update_addon_list",
		);
```

## Alternatives
You need now to install or uninstall some other plugin to get this working. There is no option to update the addon list if the plugin is already installed and advice user to rescan plugin directory will not help.

**Comment by CaMer0n** [comment]
> You need now to install or uninstall some other plugin to get this working. There is no option to update the addon list if the plugin is already installed and advice user to rescan plugin directory will not help.


@Jimmi08 Have you tried clicking this button? (which appears when Debug mode is active)  

![image](https://user-images.githubusercontent.com/2825679/74184480-b859f880-4bfb-11ea-9a95-ff1dc15e7c2e.png)

**Comment by Jimmi08** [comment]
But plugin (Metatag) itself wasn't updated.  Plugin jmdownload added e_metatag addon.  So  I should change the version of jmdownload plugin to get this displayed?     
 
Forget this.  I just found that that plugin is creating addon list this way:
(no test if the plugin is installed at all and this is called only on events above) 
I need to rewrite this at first.  

```
	/**
	 * Update addon list.
	 */
	public function updateAddonList()
	{
		$fl = e107::getFile();

		$plugList = $fl->get_files(e_PLUGIN, "^plugin\.(php|xml)$", "standard", 1);
		$pluginList = array();
		$addonsList = array();

		// Remove Duplicates caused by having both plugin.php AND plugin.xml.
		foreach($plugList as $num => $val)
		{
			$key = basename($val['path']);
			$pluginList[$key] = $val;
		}

		foreach($pluginList as $p)
		{
			$p['path'] = substr(str_replace(e_PLUGIN, '', $p['path']), 0, -1);
			$plugin_path = $p['path'];

			$addonFile = e_PLUGIN . $plugin_path . '/e_metatag.php';

			if(is_readable($addonFile))
			{
				$addonsList[] = $plugin_path;
			}
		}

		e107::getPlugConfig('metatag')->set('addon_list', $addonsList)->save(false);
		// FIXME - won't work...
		// e107::getCache()->clear('metatag_addon_config');
		e107::getCache()->clearAll('system');
	}
```

**Comment by CaMer0n** [comment]
@Jimmi08 I think we're a bit off-topic now, but Fyi.. the approved core addons are: 

```

	protected $_addon_types = array(
		'e_admin',
		'e_bb',
		'e_cron',
		'e_notify',
		'e_linkgen',
		'e_list',

		'e_meta', // @Deprecated
		'e_emailprint',
		'e_print', // new v2.2
		'e_frontpage',
		'e_latest', /* @deprecated  - see e_dashboard */
		'e_status', /* @deprecated  - see e_dashboard */
		'e_menu',
		'e_search',
		'e_shortcode',
		'e_module',
		'e_event',
		'e_comment',
		'e_sql',
		'e_dashboard', // Admin Front-Page addon.
	//	'e_userprofile', @deprecated @see e_user
		'e_header', // loaded in header prior to javascript manager.
		'e_footer', // Loaded in footer prior to javascript manager.
	//	'e_userinfo', @deprecated @see e_user
		'e_tagwords',
		'e_url', // simple mod-rewrite.
		'e_mailout',
		'e_sitelink', // sitelinks generator.
		'e_tohtml', /* @deprecated  - use e_parse */
		'e_featurebox',
		'e_parse',
		'e_related',
		'e_rss',
		'e_upload',
		'e_user',
		'e_library', // For third-party libraries are defined by plugins/themes.
		'e_gsitemap',
		'e_output', //hook into all pages at the end (after closing </html>)
	);
```

So please keep in mind that your code above looks unconventional and may cease to function in future.

**Comment by Jimmi08** [comment]
I know that list. It's custom plugin addon, not supported by core.  The question was about missing event after refresh plugin list without install/unistall plugin.

Lonalore uses event admin_plugin_refresh and I couldn't find it in the core.

Then I found that he uses very weird way how to get this list.  

_So, was event admin_plugin_refresh removed or is ist planned for future or can I delete this part of his code?_

**Comment by CaMer0n** [comment]
@Jimmi08 It's on line 2940 of plugin_class.php, so the trigger is there. 

    $event->trigger('admin_plugin_'.$function, $plug);


Do you see "Repair Complete (<plugin folder>)" after running it?

**Comment by Jimmi08** [comment]
Oh, the parameter is not the full name, but the combination. This is the reason why I couldn't find it. This is enough for me, I can go on from this. I will reopen this if I find a problem in the core, but I don't think it's this case.
Thanks
