### ISSUE TITLE
How to save images without month folder?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4097]
## 3 Questions
_1.  Is there way how to not saving images without month folder structure?_  
Wasn't there pref for this before? 

_2. How to set writeParms in AdminUI to be able to save images under the plugins folder inside the media folder?_

```
		if(!empty($path))
		{
			$dir = e_MEDIA."plugins/".e107::getParser()->filter($path,'w');
		}
		else
		{
			$dir = $this->mimePaths[$pmime].date("Y-m");
		}
```

3.  If I have a plugin with legacy path, f.e.:  'legacyPath'=>'{e_IMAGE}icons/' , _is there a way to get new images saved in the legacy folder to have them in one place?_

## Expected Source
Where did you look to try to find the answer to your question?
- e107_admin/image.php
- e107_handlers/media_class.php
- e107_handlers/file_class.php

Thanks

## Additional Context
Add any other context or screenshots about the question here.

**Comment by CaMer0n** [comment]
@Jimmi08 2. Did you try using `writeParms('path'=>'foldername')` ?

**Comment by Jimmi08** [comment]
Yes, but it didn't help.  

I solved it somehow with method type and before create/update method.  It was more complicated because value saved in database has to be only file name, but value for media manager has to have {e_IMAGE} in value, otherwise it didn't work.

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I believe the correct code for it is: 

    writeParms('path'=>'plugin');

This should automatically add the image using the same folder name as the plugin, but in the media folder.

**Comment by CaMer0n** [comment]
Closing.
