### ISSUE TITLE
upload images - check for file names

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4100]
## Motivation
![image](https://user-images.githubusercontent.com/5429548/74531813-f756b980-4f2d-11ea-9b9b-47c4ec79d76c.png)

## Proposed Solution
use eHelper::title2sef()  on image name before save it on server 
 
 Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Was this upload performed through media-picker (media manager) ?

**Comment by Jimmi08** [comment]
Uff, good question. I can't remember.

It was either Admin UI field image or imagepicker.

`$ret =  e107::getForm()->imagepicker('image', $category_icon, defset($label, $label), $settings);`

I will check it asap.

**Comment by CaMer0n** [comment]
@Jimmi08 Please test the change and let me know. Thank you!

**Comment by CaMer0n** [comment]
Closing, but please re-open if necessary.
