### ISSUE TITLE
not able to use <> in text field in admin UI

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4102]
The field is defined this way:

`'class_name'              => array (  'title' => LAN_TITLE,  'type' => 'text',  'data' => 'str',  'filter' => true,  'inline' => true, ),`

Needed value:
`< 200 `

I tried inline and normal edit too, but the value is stripped after that sign.

That value wasn't inserted manually, now is saved in the database 
`&lt; 200`

It's displayed correctly
![image](https://user-images.githubusercontent.com/5429548/74658247-240b0b00-5192-11ea-99fa-25d1e75efc02.png)

After changing
![image](https://user-images.githubusercontent.com/5429548/74658294-3edd7f80-5192-11ea-8344-b20f17a94e55.png)

Saving normal text is ok.

I tried this with a news title on installation only with English. The same result.

**Comment by CaMer0n** [comment]
@Jimmi08 Please try with the changes. Thanks

**Comment by Jimmi08** [comment]
Works. Thank you, I tried resaving and editing.
