### ISSUE TITLE
no-books-capter-in-page-list

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4103]
http://e107help.org/4825/no-books-capter-in-page-list

maybe for those who needs it as an enhancement feauture ?

I just post it as described :  if grid is selected in admin -> pages/menus -> options -> list books/capters templates then no articles are displayed

**Comment by CaMer0n** [comment]
hmm, the template already contains the following: 
```
$CHAPTER_TEMPLATE['grid']['listPages']['caption']				= "{CHAPTER_NAME}";
$CHAPTER_TEMPLATE['grid']['listPages']['start']				    = "<!-- Chapter Template: Grid listPages -->{SETIMAGE: w=450}{CHAPTER_BREADCRUMB}<div class='chapter-pages-list'><div class='row'>";
$CHAPTER_TEMPLATE['grid']['listPages']['item']				    = "<div class='col-xs-12 col-md-4 text-center'>{CPAGEMENU}</div>";
$CHAPTER_TEMPLATE['grid']['listPages']['end']				    = "</div></div>";
```

**Comment by tgtje** [comment]
> if grid is selected in admin -> pages/menus -> options -> list books/capters templates then no articles are displayed.

well fooled around a little with it, and it seems that likely there is a mis-interpretation.

Aka main page caption (page/php?) in grid mode > Other Articles

origin  :
page.php
			$text .= "<h3>".LAN_PAGE_14."</h3>"; // Book Title.
			$tmp = $this->listPages(0);
			$text .= $tmp['text'];	// Pages unassigned to Book/Chapters. 


================================
tests


httxxxx /e107_admin/cpage.php?mode=menu&action=edit&tab=2&id=45   >>> edit button (small)
clicking it leads to an empty menu (page)tab in custompages/menus
applying the 'solution' provided on help creates a button >( read more ) > which itself does 
again point to a none existing page...

i do not need an adjustment to get things going, but still grid seems only to apply to menus
if i add (clicking edit) a menu title and make it a button or alike.. it fills the page
so YES it works, but you have to have much more settings needed. Book/chapter need also grid etc...

Anyway.. i would like to close this item, as the original poster on e107help 
is happy with his solution.. i think there is no need to change files at present, nor enhancement.
 panel does both worlds... and default is good.
(kind of like when nothing is assigned to a book/chapter all stuff present but not used (like storaged) is presented in grid.... (not happy with that anyway

It always might be opened when needed  of course ?!
