### ISSUE TITLE
sql error with pdo and Update query (not update method)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4104]
## Question
What could be the reason for this?

**What are you trying to accomplish?**
Save time and use standard SQL query  instead e107 update method

**This query fails:** 
`$sql->gen("UPDATE #".UN_TABLENAME_LINKS_LINKS." SET cid='".$cid."', sid='".$sid."', title='".$title."', url='".$url."', description='".$description."' WHERE lid = ".$lid."");`

I tried this one too:
`$sql->gen("UPDATE #".UN_TABLENAME_LINKS_LINKS." SET cid='".$cid."', sid='".$sid."', title='".$title."', url='".$url."', description='".$description."' WHERE lid = '".$lid."'");`

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error in C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php:1338 Stack trace: #0 C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php(1338): PDOStatement->fetch(2) #1 C:\xampp\htdocs\e107demo\e107_plugins\web_links\admin\web_links_admin_functions.php(171): e_db_pdo->fetch(2) #2 C:\xampp\htdocs\e107demo\e107_plugins\web_links\admin\index.php(129): LinksChangeModRequests('5') #3 {main} thrown in C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php on line 1338`

## Expected Source
 mysql_class handler 
https://github.com/e107inc/e107/issues/4066
https://github.com/e107inc/e107/issues/3820

## Additional Context
After printing this query string:
`UPDATE #links_links SET cid='0', sid='0', title='', url='', description='' WHERE lid = 13`
After replacing # , it's normally executed in phpMyAdmin.
Debug is useless because of that fatal error.

PHP 7.2

Table definition:
https://github.com/Jimmi08/e107-free-plugins-by-e107sk/blob/master/web_links/sql/links_modrequest.php

Thanks.

**Comment by Jimmi08** [comment]
This version failed too (recommended in some other issue):
```
e107::getDb()->update( UN_TABLENAME_LINKS_LINKS, 
        "cid='".$cid."', sid='".$sid."', title='".$title."', url='".$url."', description='".$description."' WHERE lid = '".$lid."'", true);
```

This one worked but it takes time to rewrite it (I tried it just to know that problem is not in data)
```
        $update = array(
        'data' => 
             array(
             'cid' =>  $cid,
             'sid'=>   $sid,
             'title'=>   $title,
             'url'=>  $url,
             'description'=>   $description
             ),
        'WHERE' =>  "lid = ".$lid
        );
        e107::getDb()->update( UN_TABLENAME_LINKS_LINKS, $update);
```

**Comment by Deltik** [comment]
The issue is with your plugin.  Here's your stack trace again:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error in C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php:1338
Stack trace:
#0 C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php(1338): PDOStatement->fetch(2)
#1 C:\xampp\htdocs\e107demo\e107_plugins\web_links\admin\web_links_admin_functions.php(171): e_db_pdo->fetch(2)
#2 C:\xampp\htdocs\e107demo\e107_plugins\web_links\admin\index.php(129): LinksChangeModRequests('5')
#3 {main} thrown in C:\xampp\htdocs\e107demo\e107_handlers\e_db_pdo_class.php on line 1338
```

You are trying to call `e_db::fetch()` after an `UPDATE`, but [`UPDATE` doesn't return anything to fetch](https://stackoverflow.com/a/20316240/1038828).  You should execute a `SELECT` right before the `e_db::fetch()`.

By the way, your rewrite with prepared statements also doesn't work, but it doesn't throw a `PDOException`.  You would get a PHP error `Call to a member function fetch() on int` instead, but that error may be suppressed on your setup.

----

Source code of my tests to reproduce your issue:

In `e107_tests/tests/unit/e_db_pdoTest.php`:
```php
	public function testIssue4104_1()
	{
		$lid = 7919;
		$cid = 1327;
		$sid = 2861;
		$title = "Prime Numbers";
		$url = "https://e107.org";
		$description = "Test for https://github.com/e107inc/e107/issues/4104";
		$this->db->delete('links_modrequest');
		$this->db->gen('CREATE TABLE `#links_modrequest` (
                                 `requestid` int(11) NOT NULL auto_increment,
                                 `lid` int(11) NOT NULL default \'0\',
                                 `cid` int(11) NOT NULL default \'0\',
                                 `sid` int(11) NOT NULL default \'0\',
                                 `title` varchar(100) NOT NULL default \'\',
                                 `url` varchar(100) NOT NULL default \'\',
                                 `description` text NOT NULL,
                                 `modifysubmitter` varchar(60) NOT NULL default \'\',
                                 `brokenlink` int(3) NOT NULL default \'0\',
                                 PRIMARY KEY  (`requestid`),
                                 UNIQUE KEY `requestid` (`requestid`)
                               ) ENGINE=MyISAM AUTO_INCREMENT=1 ;');

		$this->db->truncate('links_modrequest');
		$result = $this->db->insert('links_modrequest', array('lid' => $lid));
		$this->assertEquals(1, $result);
		$result = $this->db->gen("UPDATE #links_modrequest SET cid='" . $cid . "', sid='" . $sid . "', title='" . $title . "', url='" . $url . "', description='" . $description . "' WHERE lid = " . $lid . "");
		$this->db->fetch();
		$this->assertEquals(1, $result);
	}
	
	public function testIssue4104_2()
	{
		$lid = 7919;
		$cid = 1327;
		$sid = 2861;
		$title = "Prime Numbers";
		$url = "https://e107.org";
		$description = "Test for https://github.com/e107inc/e107/issues/4104";
		$this->db->delete('links_modrequest');
		$this->db->gen('CREATE TABLE `#links_modrequest` (
                                 `requestid` int(11) NOT NULL auto_increment,
                                 `lid` int(11) NOT NULL default \'0\',
                                 `cid` int(11) NOT NULL default \'0\',
                                 `sid` int(11) NOT NULL default \'0\',
                                 `title` varchar(100) NOT NULL default \'\',
                                 `url` varchar(100) NOT NULL default \'\',
                                 `description` text NOT NULL,
                                 `modifysubmitter` varchar(60) NOT NULL default \'\',
                                 `brokenlink` int(3) NOT NULL default \'0\',
                                 PRIMARY KEY  (`requestid`),
                                 UNIQUE KEY `requestid` (`requestid`)
                               ) ENGINE=MyISAM AUTO_INCREMENT=1 ;');

		$this->db->truncate('links_modrequest');
		$result = $this->db->insert('links_modrequest', array('lid' => $lid));
		$this->assertEquals(1, $result);
		$update = array(
			'data' =>
				array(
					'cid' =>  $cid,
					'sid'=>   $sid,
					'title'=>   $title,
					'url'=>  $url,
					'description'=>   $description
				),
			'WHERE' =>  "lid = ".$lid
		);
		e107::getDb()->update('links_modrequest', $update);
		$this->db->fetch();
		$this->assertEquals(1, $result);
	}
```

**Comment by Jimmi08** [comment]
@Deltik that plugin is not finished, I am going line by line to rewrite old code. 
 
I am not able to understand what you are saying, but the point was that gen() didn't work and update() worked.  

I don't use $this->db->fetch(); after that UPDATE query.  If e107 uses it, then how to write that query to avoid this error? 

I don't do anything like this, maybe core does this?
`You are trying to call e_db::fetch() after an UPDATE, but UPDATE doesn't return anything to fetch. You should execute a SELECT right before the e_db::fetch().
`
I used die; directly after that query to be sure.

**Comment by Deltik** [comment]
@Jimmi08: Your stack trace showed that the plugin was calling `e_db_pdo::fetch()`:

```
#1 C:\xampp\htdocs\e107demo\e107_plugins\web_links\admin\web_links_admin_functions.php(171): e_db_pdo->fetch(2)
```

If you've changed something, please show me the new stack trace.

----

When you do `e_db_pdo::update()`, the current behavior is to save the affected row count to `e_db_pdo::$mySQLresult` (apparently not documented behavior!).

When you do `e_db_pdo::gen()`, `e_db_pdo::$mySQLresult` becomes a `PDOStatement`.  This makes sense to me.

It is inconsistent what `e_db_pdo::$mySQLresult` is set to after `e_db::update()` and `e_db::gen()`, but it is not intended for `e_db::fetch()` to be called after any `UPDATE` queries.

I cannot reproduce your error from `e_db_pdo::gen()` or `e_db_pdo::update()` alone.  I get your error if I call `e_db_pdo::fetch()` right after the `UPDATE` queries.  As far as I can tell, it is not possible to get the error you got unless you called `e_db::fetch()` after the `UPDATE` query.

To troubleshoot this further, I'll need an updated stack trace.

**Comment by Jimmi08** [comment]
I will post updated version, I didn't know you will use that code.
That fetch is before that update. 
```
	$result = $sql->gen("SELECT requestid, lid, cid, sid, title, url, description FROM #".UN_TABLENAME_LINKS_MODREQUEST." WHERE requestid='".$requestid."'", true);  
 
    while ($row = $sql->fetch($result)) { 
```

I probably know...  oh, I will try to change it to retrieve and I let you know.

**Comment by Jimmi08** [comment]
Solved. I forgot on my gold rule - never use fetch() in the cycle, or better never use fetch() at all.  

The reason is that you can't use e107::getDb() twice times. And for now, nobody was able to explain to me how to do it correctly without retrieve. 

I mean inside fetch() cycle next e107::getDb(). 

Your test failed because after the first update, the query for the original fetch was changed too. 

Thanks again. You can close this now.
