### ISSUE TITLE
Set initial value for email hide setting as TRUE when creating new user

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4107]
## Motivation
With all that GDPR and personal info stuff,  hide email should be set as TRUE when a new user is created

Not tested all parts of system, but with admin option Quick add user hide email is set as false.  And this column is not displayed by default, so you could miss this. 

## Proposed Solution

Hide email should be true when creating a new user record any way.

**Comment by CaMer0n** [comment]
@Jimmi08 Done! :-)
