### ISSUE TITLE
question to latest changes related to social signup

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4108]
## Question
@Deltik  not able to watch actual changes now, so just a quick question, because I just vaguely remember my main problem with this part and why I stopped to use it.

If the user has already the normal account with their email and they try to sign up with a social link connected with the same email, what happens?   (from 2 reasons: - they forgot about it or they suppose that their social account will be added to the existing account - some sites work this way)

Before it ended with fatal error because of unique index of the email field in the database.  

Did you test this scenario?  Thanks. 

PS. Not important, I just didn't want to forget about this.

**Comment by Deltik** [comment]
I didn't end up writing an automated test for that scenario, but I did take it into account.  Expected behavior now:

1. User tries to log in via a social login provider but is already registered with the same email address.
2. The login fails and the user sees this error message:
    > User exists but is not connected through this social login provider

**Comment by Jimmi08** [comment]
Thank you.  I will test this later (in some months maybe), this is correct behavior. 

Maybe `User exists` - `User with this email address exists` - would be better (just because in my case users are used for checking user name, not email, this could hit them to ask for the forgotten password and not checking user name )
