### ISSUE TITLE
Q: Can anyone see the mistake?

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4110]
What is wrong with this query? (Line 53)

![image](https://user-images.githubusercontent.com/17859550/76246166-77c2be80-623d-11ea-8b02-fab66a5df7c5.png)

I should see two lines, but I only get one line.

![image](https://user-images.githubusercontent.com/17859550/76246227-92953300-623d-11ea-9e66-630c0eaf3593.png)

If I make ASC out of ASC then I get the other line. Does anyone see the mistake?

**Comment by Deltik** [comment]
@TrueHatori: Inside your `e_db::fetch()` loop (line 54), you run another query (line 62, and again at line 66), which wipes out the remaining results from the outer loop.  You need to fetch all the rows first before running the next query. `e_db::rows()` can do this in one call.

**Comment by TrueHatori** [comment]
Yes, when I comment out the two queries, both lines are displayed (the while in it was unnecessary).

![image](https://user-images.githubusercontent.com/17859550/76249012-c161d800-6242-11ea-9199-3e9898af2c5a.png)

But how do I get to the other two fields?

![image](https://user-images.githubusercontent.com/17859550/76249165-1271cc00-6243-11ea-96e0-5c3c91ce071a.png)

**Comment by Deltik** [comment]
@TrueHatori: You can use a couple of [`JOIN`](https://www.w3schools.com/sql/sql_join.asp)s to get all the information in just one query.

Alternatively, you can fetch the rows, the iterate over each row and run the two extra queries, but that triples the number of queries you need to run.

**Comment by TrueHatori** [comment]
Many thx. I had never used JOIN before, but I did.
`$entries = $sql->gen("SELECT #verein_finanz_konto.*, #verein_finanz_bereiche.finanz_bereich_bezeichnung, #verein_finanz_konten_posten.finanz_konten_posten FROM #verein_finanz_konto LEFT JOIN #verein_finanz_bereiche ON #verein_finanz_konto.einnahmen_bereich_ID = #verein_finanz_bereiche.finanz_bereich_ID LEFT JOIN #verein_finanz_konten_posten ON #verein_finanz_konto.einnahmen_konto_posten = #verein_finanz_konten_posten.finanz_konten_ID WHERE einnahmen_konto_jahr = ".$jahr." ORDER BY einnahmen_konto_ID ASC");`
