### ISSUE TITLE
How can I manipulate the admin menu?

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4112]
I have this in the admin menu for a club administration. If no club is registered yet, that's a good thing.

![image](https://user-images.githubusercontent.com/17859550/77070102-ecd68680-69e9-11ea-92cd-1031a6148f56.png)

However, as soon as a club has been entered, I want the line (1) to disappear so that you can actually only register one club. Can someone please give me a hint how I can do this and where (in admin_config.php) I have to write the code?

**Comment by Jimmi08** [comment]
If I get you right, you need to find a way how to hide admin menu item on some condition. Don't forget that you need only hide that menu item, but you need to stop the URL for adding a new record to work.    
 
Wouldn't you mind sharing the plugin code with me? Privately if you want.

**Comment by CaMer0n** [comment]
Try this: 

```
class (whatever name you used) extends e_admin_dispatcher
{

    function init()
    {
        if(whatever)
        {
             unset($this->adminMenu['mode/whatever']); 
        }

    }

}

**Comment by TrueHatori** [comment]
Yes, that's how it works. I don't need a "class" at all, it just needed the function right after the end of the "protected $ adminMenu = array" section. Thank you very much.

**Comment by CaMer0n** [comment]
@TrueHatori Yes, that is the correct place to put it.  Not a new class, but inside your existing 'dispatcher' class which contains `$adminMenu`. ;-)
