### ISSUE TITLE
not able upload media - No HTML5 support

### ISSUE THREAD

**Issue by Kojack-59** [e107inc/e107#4116]
When going to media manger, and trying to download a pic from PC, "not html 5 compatibility" appears.

PHP 7.3
cache was cleaned
last version from git (today as discovered another bug with core_image load this week-end)
in console we can read sometimes kCFErrorDomainCFNetwork erreur 303

also question asked here https://www.e107help.org/4858/picture-upload-issue 

thanks for help

**Comment by Kojack-59** [comment]
for info, no issue on http only
when I switched URL In https, I note mis-display of admin pages
(I switched to https but ssl connexion not activated because impossible)

any ideas ?

**Comment by Deltik** [comment]
Sounds like HTTPS is misconfigured on your web server somehow.  What does your network waterfall look like?  **Can you provide a screenshot?**  In Safari, go to [Web Inspector](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/Web_Inspector_Tutorial/EnableWebInspector/EnableWebInspector.html) and load the problematic page while in the Network tab of Web Inspector.

Every reply should be `2xx` or `3xx`.  A `4xx` or `5xx` response indicates a problem.  On my Firefox:

![image](https://user-images.githubusercontent.com/1364268/77955475-e1127c00-7295-11ea-93e4-cf395e7e6fa5.png)

**Comment by Kojack-59** [comment]
hello,
thanks @Deltik 
the issue is related to SSL .
First, not able to activate to parameters / ssl : e107 said "nothing changed - noting to save " !
when I access to docs.php / admin.php or image.php in SSL, 303  error : kCFErrorDomainCFNetwork

in http, all is fine (even if 5second latency are necessary to load image.php & related libs)

how can I properly configure SSL on your site ?

thanks

**Comment by Deltik** [comment]
e107 does not need special configuration to work with HTTPS, except for the "Site URL" in `/e107_admin/prefs.php` under Preferences » Basic Options » Site Information.  Even so, the admin area does not depend on that setting anyway.

Your web hosting provider may be able to help you set up HTTPS on your site; this is out of scope of e107.

**Comment by Kojack-59** [comment]
yes of course. SSL is ok and no issue with other sites like wordpress.
definitely e107 needs something specific on SSL

**Comment by Deltik** [comment]
`kCFErrorDomainCFNetwork` is not an error that appears in e107.  This appears to be specific to Safari.

What is the URL in question?  I can run an SSL test on it.

**Comment by Kojack-59** [comment]
net::ERR_HTTP2_PROTOCOL_ERROR
is the errror on chrome
URL Is image.php for example

**Comment by Kojack-59** [comment]
may be related to pictures and gzip compression

**Comment by Deltik** [comment]
@Kojack-59: The error message is indicative of some kind of misconfiguration on the web server.  There are a wide variety of causes.  Check the error log of your web server for hints.

If you have a CDN or other reverse proxy between the client and the server, try disabling it to rule it out.

I'll close this issue for now, as all signs point to a server configuration problem, but if you can present error logs that show or suggest that e107 is not playing well with your web server, please provide those details, and I'll reevaluate the issue.
