### ISSUE TITLE
SMTP Connection error 

### ISSUE THREAD

**Issue by turtleking1** [e107inc/e107#4117]
Hello
every time I try to send a test email from my e107 website I get this error 

Connection: opening to :25, timeout=30, options=array (
                   	                  )
Connection failed. Error #2: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known [/opt/lampp/htdocs/e107_handlers/phpmailer/class.smtp.php line 298]
Connection failed. Error #2: stream_socket_client(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) [/opt/lampp/htdocs/e107_handlers/phpmailer/class.smtp.php line 298]
SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)

any idea how can I fix it

**Comment by Deltik** [comment]
You did not specify a host to connect to.  To solve this, you need to add the SMTP host.  If your e107 server is the same as your email server, this would be `localhost`.  Otherwise, find out what the SMTP host name is from your email provider.

**Comment by turtleking1** [comment]
problem solved thank you very much
