### ISSUE TITLE
LEFT JOIN and DISTINCT

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#4118]
Hello, I have a problem again and hope someone can help me.
How do I use DISTINCT in connection with LEFT JOIN? I have this script:

![image](https://user-images.githubusercontent.com/17859550/78158798-fc21ef00-7441-11ea-98ed-faa547d024e3.png)

The result is this:

![image](https://user-images.githubusercontent.com/17859550/78158970-37bcb900-7442-11ea-9eb6-4615f9e37796.png)

It looks like DISTINCT affects the second table. That's good, but I need it on both. The entries outlined in red must go away. On the right side I have 2x "Brandenburg" in the database, it is only displayed once, so I suspect DISTINCT affects the second table. When I swap the tables in the query, nothing changes. Can someone tell me where my mistake is? I don't want to show duplicate entries on the left or right.

**Comment by TrueHatori** [comment]
I think I understand my problem now. The query is correct, but of course the "Land" are always included.
Is there a way to hide the outlined fields? So after the first display of "Deutschland" suppress all others.

**Comment by Moc** [comment]
Closing. This is a question about e107 specifically but rather about constructing the correct SQL query. Please use other community platforms for such questions (such as StackOverflow for example)
