### ISSUE TITLE
2 different settings for email

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4123]
One settings is in Users/Mail 
![image](https://user-images.githubusercontent.com/5429548/78420817-0109bd00-7653-11ea-82e3-f518837af8c4.png)

The second one in Contact/Email info in Prefs

![image](https://user-images.githubusercontent.com/5429548/78420864-79707e00-7653-11ea-960a-bcded65532fb.png)

Problem is that I am sure, that I set this to SMTP too. And for some reason (maybe update) it is back to PHP.   PHP sending doesn't work on my server, so I am really sure about SMTP settings.

They send different emails too:
![image](https://user-images.githubusercontent.com/5429548/78420926-087d9600-7654-11ea-9ea5-4beb23f0b0ea.png)

What is the reason for this?  I ask before my PM notification stopped to work and I am not able to find reason for this.

**Comment by CaMer0n** [comment]
It allows one to use a mass mailing service (via SMTP) for newsletters etc., and basic PHP email for site registration etc.

**Comment by Jimmi08** [comment]
Thank you.

So for example, PM notifications use that in Preferences? The same for event notifications?   

I ask because it can be just my imagination, but I can use the only SMTP (it is years this way), so I am sure that I had both settings the same and it got there PHP email somehow.  This issue is confirmation for me that I really checked that both are the same.

**Comment by CaMer0n** [comment]
If I remember well, when the Notification is going to a large number of recipients, it will switch to the mass-mailing ("newsletter") mailing preferences.
