### ISSUE TITLE
different logic (rules) for back compability in news template variables in theme.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4124]
In almost each cases those globals have first priority:
Checked:
$NEWSSTYLE
$COMMENTSTYLE

But $NEWSLISTSTYLE is used this way:
```
		if(deftrue('BOOTSTRAP'))  // v2.x
		{
			$template = e107::getTemplate('news', 'news', 'list');
		}
		else  // v1.x
		{           
			if(empty($NEWSLISTSTYLE))
			{
```

$NEWSLISTSTYLE should have priority too before BOOTSTRAP, because others variables work this way.

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Those are LEGACY global variables. If BOOTSTRAP is found we assume we're using v2.x. 
And if we're using a bootstrap theme, then it was coded for v2, not v1, so I don't see any reason to give legacy values (which do NOT belong in a v2.x theme containing bootstrap) any priority.

**Comment by Jimmi08** [comment]
> And if we're using a bootstrap theme, then it was coded for v2, not v1, so I don't see any reason to give legacy values (which do NOT belong in a v2.x theme containing bootstrap) any priority.

Correct, but then apply the same rule for $NEWSSTYLE and $COMMENTSTYLE too, not only for $NEWSLISTSTYLE

I noticed this because there were V1 themes with bootstrap support already. And because $NEWSSTYLE  still worked, it was confusing why $NEWSLISTSTYLE didn't work. Maw used bootstrap for many of his V1 themes.

BOOTSTRAP should decide if to use bootstrap code (and which version), not if the theme is legacy or not.  For this, there is a different constant.  

I agree this is not the priority,  You can close this.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you. It's a minor change to fix this. Untested commit, so if you could please check that the commit fixed it, I would appreciate it. Thanks.

**Comment by Jimmi08** [comment]
@CaMer0n I appreciate this, but it is still different for $NEWSLISTSTYLE.  

And yes, it should be done how you did it now, I tried to find scenario where it fails, but it looks correct.  One has to be aware that they want to use old ways so they should add THEME_LEGACY... otherwise new templates are used.

**Comment by Jimmi08** [comment]
@CaMer0n On Second Thoughts - what happens if somebody installs V1 theme without adding THEME_LEGACY?  I am vaguely aware (maybe I am wrong) that this constant is set if there is not theme.xml by default. If it is this case, it's correct.

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, THEME_LEGACY is automatically defined when theme.xml is not found.

**Comment by Jimmi08** [comment]
Still different logic for $NEWSLISTSTYLE left

**Comment by CaMer0n** [comment]
@Jimmi08 Please try now.
