### ISSUE TITLE
Why stats logs display something like that?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4125]
I noticed this 
![image](https://user-images.githubusercontent.com/5429548/78807398-4bc56500-79c4-11ea-92e9-e0cd74289d2e.png)
 

1. question

Why is viewing javascript files logged as a visiting page?

2. question 
Why is not there any browser? No Agent? It probably crawls bot. 
 If it helps, that IP was from

>   "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/80.0.3987.92 Safari/537.36"

Thanks

**Comment by tgtje** [comment]
Making a guess here, as i can not oversee the whole..More a comment: since each line (aka data) sees a different ip address (even if from same network range) it triggers the log, where js call is only data stored (searchinfo and/or visitinfo)
