### ISSUE TITLE
tinymce strips rel="nofollow" from links in news 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4128]
## Bug Description
In news article, I added links and manually added rel="nofollow" via source code. 
 
## Expected Behavior
I used before nofollow plugin but it's broken now, so adding this manually to a href tag is minimum what I can do.
EDIT: the problem was somewhere else with this plugin, it works
 
Can somebody confirm this? Because I couldn't believe this and I still think that this is some of my stupid mistakes. 

Thanks

**Comment by Moc** [comment]
@CaMer0n Should this be added to the allowed tags in the parser?

**Comment by CaMer0n** [comment]
@Moc Yes! Done!
