### ISSUE TITLE
email address hiding problem

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#4131]
The email address is displayed in the user menu and profile even if it is set to hidden.

![email2](https://user-images.githubusercontent.com/35248010/79593836-55458000-80dc-11ea-890b-0c8410dd1bd3.png)

![email](https://user-images.githubusercontent.com/35248010/79593834-54145300-80dc-11ea-9765-9cc3612ba5d7.png)

**Comment by Deltik** [comment]
If you are logged in as an admin, user email addresses are still shown to you.  The code that does this is [here](https://github.com/e107inc/e107/blob/v2.2.1/e107_core/shortcodes/batch/user_shortcodes.php#L272).

@Moc: Maybe we could do some improvement to documentation for this?

**Comment by tyupika93** [comment]
Not an administrator. user, rank can also see all email addresses

**Comment by Deltik** [comment]
I cannot reproduce your issue after signing up on your site as a regular user:
![image](https://user-images.githubusercontent.com/1364268/79662481-35fd3000-817a-11ea-86b8-ed280917a5c0.png)

As intended, "_[elrejtve]_" shows for users who have opted to hide their email address.

You can find the list of administrators here: http://www.huaweimagyarorszag.nhely.hu/e107_admin/administrator.php

Ensure that the user you are logged in as is not an admin.
