### ISSUE TITLE
add export option for Welcome message in Admin UI

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4134]
## Motivation
Save time
 
Thanks

**Comment by Moc** [comment]
Think this has already been added at some point in the past?
![image](https://user-images.githubusercontent.com/577978/146950255-d446da9d-2fc0-4a8e-bee0-abbc02921791.png)

**Comment by Jimmi08** [comment]
yes, thanks
https://github.com/e107inc/e107/commit/57aa13ee39ebac04c441a8ea0e06c3cfd28daaf2#diff-139817bab0fbeddb0288575e2aff205c4006ef84bee67047ea75eaf7e11174ae
