### ISSUE TITLE
Why I can't use onchange atribute with select field?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4135]
## Question
Tested with the select field. 
V1 code: 
`$cl.= form::form_select_open("category_form", "onchange=\"top.window.location = '".e_PLUGIN."SP_FormBuilder/admin/formbuilder.php?'+this.options[this.selectedIndex].value;\"");`

Because this code:
```
foreach (array_keys($user_options) as $key)
	{
	if(!isset($def_options[$key]) && substr($key,0,5)!='data-') unset($user_options[$key]); // data-xxxx exempt //remove it?
	}
```

```
if(substr($option,0,5) =='data-')
{
	$ret .= " ".$option."='{$optval}'";	
}
```

I can't update that code with e_form with
`$cl.= $frm->select_open("category_form", array('onchange'=>$onchange) );`

How to do it now?  Thanks

**Comment by CaMer0n** [comment]
https://stackoverflow.com/questions/11179406/jquery-get-value-of-select-onchange

**Comment by Jimmi08** [comment]
> https://stackoverflow.com/questions/11179406/jquery-get-value-of-select-onchange

Sorry, I didn't get what you were trying to say.

I have working code with the latest e107 (jquery, PHP 7.2...) the only problem is that it uses old form class, not a new one e_form.  And because I wanted to update it, I found that it is not possible now. 

Why do you limit user attributes only for "data-"? - I suppose you probably need this for Admin UI,  
There is already the option for this. There are default attributes and user attributes.  
Why they are limited only for name "data-" ? 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 We have jQuery built in, so better to use it. That link provides the modern solution to solve your problem.

**Comment by Jimmi08** [comment]
So you need a separated javascript code. Just great, Thanks
