### ISSUE TITLE
e107_Config Optional's Section

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4136]
I installed a new site a few weeks ago from git, while in URL Configuration, I get a message to add

`
define('e_MOD_REWRITE', true);
`
to e107_config.php.

When adding it, I notice an Optional area, which lack that option. Shouldn't that be there as well?

**Comment by Moc** [comment]
I think this one is not included in the optional defines in e107_config.php by default because it should be used with caution, ie. only when advised through the admin area.
