### ISSUE TITLE
Error page ignoring error_template changes

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4137]
501st website has been up for about 3 years now, using my defaitnzstrap3 theme - I have a custom 404 page set up in the theme templates. (I do keep the files up to date with Github).

![Annotation 501st](https://user-images.githubusercontent.com/5818022/80060077-418e8500-84f3-11ea-80de-6046a0e89714.png)

New site using github files - working on a new theme, using error_template.php in the theme's/templates folder - however, it's not working.

![Annotation ewl](https://user-images.githubusercontent.com/5818022/80060088-44897580-84f3-11ea-992e-f95511e95b11.png)

I've even tried replacing e107_core/templates/error_template.php with my own - still same thing. I've cleared my browser cache, website cache, and tried it on other PC's and web browsers (Firefox, Chrome, Opera GX).

I even tried applying the 501st error_template to the new site, still no changes. error.php hasn't been updated in 2 years, 3 years for the error_template.php. I don't know what the issue is.

**Comment by LaocheXe** [comment]
I've even tried editing e107_handlers/error_page_class.php (edit the setPageNotFound() (404) - tried replacing the LAN's with regular text, nothing.

**Comment by CaMer0n** [comment]
The first site returns a 404 header. 
The second site returns a 501 header. 

Still digging..

**Comment by CaMer0n** [comment]
Solved. .htaccess was missing, so a 501 was returned.
