### ISSUE TITLE
How to check result after update()?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4138]
There are 3 possible results:
- nothing was changed
- successful change
- error 

I noticed that you are testing $sql->getLastErrorNumber() to detect if there is change or not (in news)
but it looks to me that there is an easier way too:
 
value 0 - no changes
value false - error

Correct?

Tested with this code:
```
        $result = $sql->update("spfb", implode(",",$updatearray)." WHERE `form_id`=".intval($form_id), true); 
        $m = $result ? array("s" => "success", "m" => SPFB_FORMS_UPDATED) : 
        ( $result === 0 ? array("s" => "info", "m" => LAN_NO_CHANGE) : array("s" => "danger", "m" => SPFB_FORMS_UPDATEERROR) );
```
and with this too.
```
$update = array(
        'data' => $insert ,
        'WHERE' =>  "form_id = ".intval($form_id) 
        );                                            
        $result = e107::getDb()->update( "spfb" , $update);
```

But I wanted to confirm this.  So what is correct?  test return value after update or getLastErrorNumber() ?

Thanks

**Comment by Moc** [comment]
The SQL methods like `insert()`, `update()`, `delete()`, `gen()` etc, will return false when there's an SQL error. 

You can then retrieve the exact error using methods like `$sql->getLastErrorNumber()` and `$sql->getLastErrorText()`. 

Example:
```php
if(!$sql->update($update_query))
{
	$sqlError = $sql->getLastErrorText();
	return $sqlError;
}
```

**Comment by Jimmi08** [comment]
@Moc 

I spent 2 hours debugging, so I know that this `if($result == FALSE) ` will not work.  This was the original check and it still displayed error after just resaving record.  I tried to find how Admin UI check this (that blue message that nothing was changed), but after finding that news example, I got where the problem is .   

Now you need to use 
`if($result === FALSE)  ` 
because if nothing is change, than $result is 0 (int(0)) so you need === to be sure it is false. 

I don't need to know the exact error. 

There is no bug, everything is OK, I just wanted to be sure that I am on right track -  to check 0 vs false.

**Comment by Moc** [comment]
Ah right, I did this without checking the actual code but using `===` might be necessary then yes. But you are right in saying that the return of 'false' means that there is an SQL error.
