### ISSUE TITLE
Database Utilities - SQL Verification - report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4140]
It's not important, so I don't want to mark it as a bug

I had wrong way written SQL file for the plugin, but SQL verification still said that everything is ok. Only after set debug on, I was able to find the reason ( missing line `) ENGINE=MyISAM;` )

![image](https://user-images.githubusercontent.com/5429548/80208109-cbdc0380-862f-11ea-8a8c-62570f77bf75.png)

Shouldn't it return error message if the SQL file is not able to parse?

Thanks

**Comment by CaMer0n** [comment]
If you're developing you should have debug enabled. And for everyone else, the plugin table installation would fail, so they couldn't actually reproduce the issue you mentioned.
