### ISSUE TITLE
DOWNLOAD_CAT_MAIN_ICON - not able to set size

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4143]
## Bug Description
{DOWNLOAD_CAT_SUB_ICON} and {DOWNLOAD_CAT_MAIN_ICON}
 in core template displays full image 

adding {SETIMAGE: w=40} didn't help

 Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Icons are not treated the same way as images. The size uploaded is the size rendered. You might be able solve your particular issue with CSS.

**Comment by Jimmi08** [comment]
Thanks,
