### ISSUE TITLE
pager in user profile - issue with bootstrap4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4146]
## Bug Description

I thought this was fixed  Just noting,   
https://github.com/e107inc/e107/issues/2962
 

```
<ul class="pager user-view-nextprev">
	                    <li class="previous">
	                       &nbsp;
	                    </li>
		               <li>
	                       <!-- Back to List? -->
	                    </li>
	                    <li class="next">
	                       &nbsp;
	                    </li>
	                </ul>
```

Isn't there something just for pager (3 list item) like pagination to have it the same everywhere?  Or maybe the problem is in the shortcode, because I can see that @Moc fixed this in the pagination template.

**Comment by Moc** [comment]
This should be fixed now, right?

**Comment by Jimmi08** [comment]
I am testing it just now... with bootstrap3 it is ok.  Wait.

**Comment by CaMer0n** [comment]
@Jimmi08 Do you have some other suggestions for this? After the pull-request merge, the next/prev links no longer behave like buttons. 

I tried the following code instead, but the buttons become a bit too large still. 
Maybe you can test and try some other ideas. 

```
<div class="panel-body card-body">
	                <ul class="pagination user-view-nextprev">
	                    <li class="page-item previous col-md-4 text-center">
	                       {USER_JUMP_LINK=prev}
	                    </li>
		               <li class="col-md-4">
	                       <!-- Back to List? -->
	                    </li>
	                    <li class="page-item next col-md-4 text-center">
	                       {USER_JUMP_LINK=next}
	                    </li>
	                </ul>
	            </div>
```

**Comment by Jimmi08** [comment]
@CaMer0n I just synced, where is a problem?
![image](https://user-images.githubusercontent.com/5429548/81598050-ff0bea00-93c6-11ea-9de8-1f0625c12c35.png)
