### ISSUE TITLE
FR - add support for scope none in theme.xml

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4150]
## Motivation
using define("BOOTSTRAP", 	4) is deprecated
you should use `<library name="bootstrap" version="4" scope="all"/>` 

but if bootstrap is already compiled with theme css, it would load bootstrap css 2x

## Proposed Solution
add scope where no core library is loaded

By the way, with scope 'front' BOOTSTRAP is not defined either.

**Comment by CaMer0n** [comment]
@Jimmi08  Did you take a look at `<stylesheets>` in `bootstrap3/theme.xml` ?
Specifically the part about `exclude='bootstrap'`

**Comment by Jimmi08** [comment]
```
	<libraries>
     	<library name="bootstrap" version="4" scope="all"/>
		<library name="fontawesome" version="5" scope="all"/>
	</libraries>
	<stylesheets>
		<css file="style.css" name="Default" exclude='bootstrap' />
	</stylesheets>
```

Result:
`<link  rel="stylesheet" media="all" property="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" />`

+
css/styles.css
```
/*!
* Start Bootstrap - Agency v6.0.0 (https://startbootstrap.com/template-overviews/agency)
* Copyright 2013-2020 Start Bootstrap
* Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/LICENSE)
*/
/*!
 * Bootstrap v4.4.1 (https://getbootstrap.com/)
 * Copyright 2011-2019 The Bootstrap Authors
 * Copyright 2011-2019 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
:root {
```

so bootstrap is loaded 2x 

compiled css with bootstrap is not listed in stylesheet tags. User can't select this css in theme manager.

**Comment by CaMer0n** [comment]
@Jimmi08 You're missing `scope` in your **css** item and you probably forgot to clear the system cache. (you could also reinstall the theme)

### Working example using bootstrap3:  (changed scope to 'both') 
```
  <css file="css/bootstrap-dark.min.css" name="Dark Admin" description="" thumbnail='images/admin_bootstrap-dark.jpg' scope='both' exclude='bootstrap'/>
```
### Admin Area 
![image](https://user-images.githubusercontent.com/2825679/81328310-879a2b80-9051-11ea-85d8-5624f4174156.png)

### Front of site - css loaded (sorted alphabetically): 

![image](https://user-images.githubusercontent.com/2825679/81328397-ab5d7180-9051-11ea-921b-28363dbb5b06.png)

**Comment by Jimmi08** [comment]
No, problem was that the library name is **bootstrap**, but you need to exclude machine_name that is **bootstrap4**.
Now it works.
