### ISSUE TITLE
with e_IFRAME e107::css in theme class doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4151]
## Bug Description
if you use f.e.: 
`if(!defined('e_IFRAME')) define('e_IFRAME',true);`

`e107::css('theme', 	'css/styles.css');`

- if you put it inside __construct(), it's not loaded with e_IFRAME true

**Comment by CaMer0n** [comment]
@Jimmi08 Should normally be fixed by https://github.com/e107inc/e107/commit/951cefec27e2090e13e22e3433939ca632e306f9

**Comment by CaMer0n** [comment]
Closing, but please re-open if necessary.

**Comment by Jimmi08** [comment]
It works now, confirmed. Thanks
