### ISSUE TITLE
Bug: logTime() on null in class2

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4152]
## Bug Description
Fatal error: Uncaught Error: Call to member function logTime() on null in class2.php:403 Stack trace: #0 news.php(22): require_once() #1 {main} thrown in class2.php on line 403.

## How to Reproduce
Have no clue, the site was working just as intended until now.
I've tried uninstalling Log, and Siteinfo plugin (set installflag to 0 in the database) - and still that.

**Comment by LaocheXe** [comment]
I will like to point out, that in Google Chrome, using the e107 Debug tool, Basic - I get the site up, however, when I disable the tool I get the Fatal error again.

http://ewl.defiantz.org/index.php   <--- Fatal error

http://ewl.defiantz.org/index.php?[debug=basic+]   <--- no fatal error

weird part is, I tired it on other browsers as well (Opera GX, Microsoft Edge, Google Chrome, FireFox), and I get the same results - I use the debug, I get the site back, no debug and bam, site returns Fatal error.

**Comment by Moc** [comment]
Yeah it's a bug. Fix incoming :)

**Comment by Moc** [comment]
@LaocheXe should be fixed now
@CaMer0n Please check if this is the appropriate fix :)

**Comment by CaMer0n** [comment]
Closing, but please re-open if necessary.
