### ISSUE TITLE
Question: SITEDISCLAIMER

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4154]
I've notice my site disclaimer is missing in the footer area on my website. I went into site prefs and removed it - to see if the default would show, which it didnt. I do have {SITEDISCLAIMER} set in the _footer_ of my theme.

**Comment by Moc** [comment]
Is the entire theme loaded correctly otherwise? Do you see the closing html tag `</html>` at the end of the source code? No PHP errors in debug mode?

**Comment by LaocheXe** [comment]
Checked the source code and there is an </html> at the end of the page - No PHP errors in debug mode from what I can tell.

Site: http://ewl.defiantz.org/

Theme: ewl_default (have uploaded to e107.org, hasn't been accepted yet)
Theme git: https://github.com/LaocheXe/eWL_Default

**Comment by Jimmi08** [comment]
@LaocheXe you should clear your theme shortcodes file because I can see you copied it from some my theme and I am sure you are not using most of it.  

Sitedisclaimer is working normally. Checked.   Are you sure that your live version has removed SITEDISCLAIMER theme shortcode?

**Comment by LaocheXe** [comment]
@Jimmi08 ood, cause on my site it's not displaying. I have sc_sitedisclaimer commented out in the theme_shortcode, I uncommitted it out, and it's back. Which is weird, you would think if the theme does not have the sitedisclaimer shortcode, that the default shortcode for it would be used.

As for the theme_shortcode.php, yes it's a little missy with left over code that isn't being used, you should see the style.css - I will start clearing them up. I knew I would have to clean up the style sheet, but totally forgot about theme_shortcode - thanks for pointing that out for me.

**Comment by Jimmi08** [comment]
> @Jimmi08   I have sc_sitedisclaimer commented out in the theme_shortcode, I uncommitted it out, and it's back. Which is weird, you would think if the theme does not have the sitedisclaimer shortcode, that the default shortcode for it would be used.

It works exactly this way. I tried, I used your code without modification and it worked. Caching or a different live version...  no idea, but problem is not in core.

**Comment by Moc** [comment]
Probably caching issue.
