### ISSUE TITLE
How to save xml content to database

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4156]
I need to save XML code inserted via Textarea to the database field. The user will copy XML and insert it directly to the database. 
It's not saved now, probably because of the parser. 
How to do it?
Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I don't think it is possible using the adminUI.

**Comment by Jimmi08** [comment]
Thanks. I will do it different way.

**Comment by Jimmi08** [comment]
I forgot to close, sorry
