### ISSUE TITLE
Is this correct way how to do something like this?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4159]
If the theme has color variants, you can set this in theme settings. 

Normally I used style.css, style_orange.css, style_green.css, everything worked.

But one is used that style.css is always loaded as the latest css in the theme, it became a bit confusing (mainly if you wanted to fix something in one place for all colors). (Yes, there is style_custom.css too, but it is for user modification, not for the theme itself).

So I did this:
```
	<stylesheets>
		<css file="style_default.css" name="Default Version"  />
		<css file="style_orange.css" name="Orange Version" />
		<css file="style_green.css" name="Nightvision Version" />
	</stylesheets>
```
and `e107::css('theme', 'style.css');  `in theme.php

I don't know, it doesn't look correct to me.  Order is then:
style.css
style_green.css 

It is just feeling, but it breaks the rule that style.css is loaded as latest css. 

Thanks

**Comment by CaMer0n** [comment]
Yes, and there's no need to name them 'style' either. You should be able to place them in a /css folder. 
eg: 
```
<stylesheets>
	<css file="css/default.css" name="Default Version"  />
	<css file="css/orange.css" name="Orange Version" />
	<css file="css/green.css" name="Nightvision Version" />
</stylesheets>
```

**Comment by Jimmi08** [comment]
Yes, I know, but I dislike that I need to manually insert 
`e107::css('theme', 'style.css'); `
