### ISSUE TITLE
Chat box messages are not updated.

### ISSUE THREAD

**Issue by wangxu1144** [e107inc/e107#4163]
The chat box does not display after sending a new message, the latest message is still two days ago.

**Comment by Jimmi08** [comment]
I can't confirm this. Latest GitHub, PHP 7.2, Everything works. 

It needs more information. Site URL, PHP version, e107 version.  

Did you check if records are not created or just not displayed? 

Plus - what are your chatbox settings?

**Comment by chory** [comment]
Works fine for me
PHP 7.2.30
e107 Versión 2.3.0 (git)

**Comment by wangxu1144** [comment]
> 对我来说很好用
> PHP 7.2.30 e107Versión2.3.0
> （git）

My problem has been solved, thank you :D

**Comment by wangxu1144** [comment]
> 我无法确认。最新的GitHub，PHP 7.2，一切正常。
> 
> 它需要更多信息。网站网址，PHP版本，e107版本。
> 
> 您是否检查了记录是未创建还是未显示？
> 
> 另外-您的聊天框设置是什么？

My problem has been solved, thank you :D
