### ISSUE TITLE
New Warning message in admina area - core image

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4164]
After today sync, a new message appeared:

`The core integrity image is corrupt. File Inspector will be inoperative. Resolve this issue by uploading a good copy of the core image to "". If uploading with FTP, use binary transfer mode. Error message: unable to open phar for reading ""
`
It is a multisite installation on xampp that is using CaMeRon multisite plugin.

The main site (where e107 is installed) is without a message.  All other "subsites" has this warning.  Subsites are set in subdirectories. 

Thanks

@Deltik

**Comment by Deltik** [comment]
This is fixed by https://github.com/e107inc/e107/commit/82587d8708d8baf6c6e971cd588d842ab3a2ff6a

@CaMer0n: FYI: It should have been `e107::getFolder('system_base')` rather than `e107::getFolder('system')`.

**Comment by Jimmi08** [comment]
Thank you.

**Comment by CaMer0n** [comment]
@Deltik Ahh, thanks
