### ISSUE TITLE
Twitch Row, to add Twitch social media butten into website

### ISSUE THREAD

**Issue by MaDDoG9x9** [e107inc/e107#4167]
Please add a Twitch row into:
![image](https://user-images.githubusercontent.com/65389831/82115975-90cc7c00-9766-11ea-8c61-3f35348a3877.png)

to get the social button on the site , like this here:
![image](https://user-images.githubusercontent.com/65389831/82115992-b22d6800-9766-11ea-9b55-b6d5146ff91a.png)

thank you very much :)
Best regards,
MaDDoG

**Comment by Jimmi08** [comment]
Add Vkontakte too. Thank you.

**Comment by Moc** [comment]
Almost done. Still need to figure out the right CSS to add to css/fontello.css. 

@CaMer0n see Gitter :)

**Comment by Moc** [comment]
This should be done, fixed some other icons while I was at it

**Comment by tgtje** [comment]
@Moc  may we assume #1674 is also being seen as resolved? (issue is open). 
Since this adaptation is handled, Twitch works?
