### ISSUE TITLE
image name with - is changed without warning to _ - this is intention?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4168]
I couldn't get why my demo images are not loaded...  

I uploaded them via media manager, then exported (without images) ... and imported to the new site. And they weren't displayed.  

The reason is that their name was changed. agency-new.jpg was changed to agency_new.jpg and because I didn't know this, I let images with the original name. 

This is the correct behavior? 

Thanks

**Comment by CaMer0n** [comment]
Yes, it's intentional.

**Comment by Jimmi08** [comment]
Thanks
