### ISSUE TITLE
using theme template without existing plugin template

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4169]
I did some "shortcut"  and I am using in theme template with the file name that doesn't exist in the plugin itself.

Everything works, but then I noticed a warning about including non-existing file in debug mode.

 It is caused with this:

```
		if(null === self::getRegistry($regPath))
		{
			(deftrue('E107_DEBUG_LEVEL') ? include_once($path) : @include_once($path));
			self::setRegistry($regPath, (isset($$var) ? $$var : array()));
```
 
I wanted to ask if this is a big problem. Or could be later.  
For better understanding - I am using the template for the not existing plugin (like the template that depends only on the theme, not the plugin itself).  

I can solve this in a different way, no problem. but it would need to install the next plugin with my themes. 

If this is just a warning and getTemplate() doesn't have a problem with this (some hidden, everything works flawlessly). could you confirm this?  Thanks.

**Comment by CaMer0n** [comment]
@Jimmi08 It is only a problem if you see a warning in PHP. Some of these debug messages are just so that developers like yourself can see what is happening, and elements that are being looked for.

**Comment by Jimmi08** [comment]
Thanks
