### ISSUE TITLE
Site Links New Window not working

### ISSUE THREAD

**Issue by MaDDoG9x9** [e107inc/e107#4170]
Greetings, 

![image](https://user-images.githubusercontent.com/65389831/82152713-804dfb80-9863-11ea-88a6-3d7b4c6e8b65.png)
If you create a new link here and check "New Window" as option it does not work. Once you created the link and test it in menu, the link will allways be in same window, no new window/tab will be created. Please check it. Thank you :)

Best regards,
MaDDoG

**Comment by Jimmi08** [comment]
It works. My guess is that problem is in your navigation template and there is the missing shortcode for inserting this tag. look for  {LINK_OPEN} in your main navigation template.

**Comment by tgtje** [comment]
No issues here, another theme tested? that is not mentioned

**Comment by MaDDoG9x9** [comment]
I maybe should have mentioned that i`am using BS_Gaming_03 theme from Fizzi... sorry for that :(
@Jimmi08 I opened the navigation template and found a ton of those LINK-OPEN things, but no idea what to change and where :(

**Comment by Jimmi08** [comment]
@tgtje I found the reason. I will let him know about fix here. Just let you know not to waste time on this.

**Comment by Jimmi08** [comment]
@MaDDoG9x9  This could help:

https://www.e107sk.com/forum/general-theme-questions/239/fix-for-bs-gaming-03-not-opening-main-links-in-new-window/

I am not doing this way normally, but I just was in middle on creating another video, so I had used it.

**Comment by Jimmi08** [comment]
@Moc  This can be closed, definitely theme issue.

**Comment by Moc** [comment]
Thanks @Jimmi08
