### ISSUE TITLE
bootstrap3 admin checkboxes are not visible in Display Columns window 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4171]
Admin columns checkboxes are not visible

They are there, they are just too much on left, that they are not visible 

![image](https://user-images.githubusercontent.com/5429548/82192479-585aa880-98f4-11ea-88f3-adc1e154ef7f.png)

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! Please clear browser cache and test again.
