### ISSUE TITLE
Fatal error in admin.php after Github Sync

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4174]
## Bug Description
After sync admin/admin.php got a blank page. The site and other admin links works.

After checking logs, problem started with this message:
`[php7:error] [pid 169058] [client ***] PHP Fatal error:  Uncaught Error: Call to undefined method e107_db_debug::logTime() in ***e107sk.com/web/e107_admin/header.php:29\nStack trace:\n#0 ***e107sk.com/web/e107_admin/footer.php(32): require_once()\n#1 ***e107sk.com/web/e107_admin/db.php(149): require_once('/nfsmnt/hosting...')\n#2 {main}\n  thrown in ***e107sk.com/web/e107_admin/header.php on line 29, referer https://www.e107sk.com/e107_admin/db.php?mode=github`

and then:
```
www.e107sk.com [Thu May 21 15:51:18.731720 2020] [php7:error] [pid 217030] [client ***] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in***e107sk.com/web/class2.php on line 2600, referer https://www.e107sk.com/e107_admin/admin.php
www.e107sk.com [Thu May 21 15:51:18.734118 2020] [php7:error] [pid 217030] [client ***] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in Unknown on line 0, referer https://www.e107sk.com/e107_admin/admin.php
```

I noticed this error on the localhost before, but the next sync (repeating) helped. 
Debugger mode is off (in admin).
Debug browser mode used only for github sync

The rest of admin works.

**Comment by Jimmi08** [comment]
Set debugger mode on, new sync didn't help.

**Comment by CaMer0n** [comment]
@Jimmi08 Is the error still showing up, or did it only display once?

**Comment by Jimmi08** [comment]
Still

**Comment by CaMer0n** [comment]
Resolved.
