### ISSUE TITLE
{CHAPTER_ANCHOR} - why chapter_sef is not used?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4179]
For scrolling you need "anchor" page part.  This shortcode was used for this, but I think it is outdated now.

```
	/**
	 * @example {CHAPTER_ANCHOR}
	 */		
	function sc_chapter_anchor()
	{
		$frm = e107::getForm();
		$row = $this->getChapter();
		
		return $frm->name2id($row['chapter_name']);
	}
```

There is now **chapter_sef** field that should be unique (and it is generated from the name, but it can be different).  But this field is visible and under user control.   

Is any reason why chapter_sef is not used directly? (only that it was added later)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 So that the anchor still functions when SEF is disabled.

**Comment by Jimmi08** [comment]
@CaMer0n I understand, but could you add shortcode for SEF URL?  You will change the title and your links will stop to work.

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, or you change the SEF to match your new title, and the link anchor stops working as well. Maybe you should use `#chapter-{CHAPTER_ID}` instead?

**Comment by Jimmi08** [comment]
Never mind.  I will add a theme shortcode.
