### ISSUE TITLE
Unauthorized access error using Cloudflare

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4181]
It seems e107 security is not working well with cloudflare, getting unauthorized access error after some changes.

**Comment by Moc** [comment]
How did you configure your e107 installation for Cloudflare? What changes did you make?

**Comment by realmontazeri** [comment]
Needs special configuratios for that? getting this error when I try to save or discard changes like editing pages.

**Comment by Moc** [comment]
Let me clarify, I am asking what you current setup is. Which solution/service of Cloudflare are you using. 

> ... getting unauthorized access error after some changes.

What changes are you referring to? 


In the end, assuming Cloudflare handles your security well, you may want to disable e107 security's token in this case specifically. You can do so by setting this is in e107_config.php:

`define('e_SECURITY_LEVEL', 0);`

**Comment by realmontazeri** [comment]
I am currently using latest e107 git version with Cloudflare free plan, tried several firewall rules in Cloudflare to stop this error but still no luck, also tried sessions instead of cookies in e107 security preferences, saving or discarding page contents and many other functions cause this error.

**Comment by Moc** [comment]
Ok, so disabling e107's security level, as said in my previous comment, should work.

**Comment by Moc** [comment]
@realmontazeri Did defining `define('e_SECURITY_LEVEL', 0);` in e107_config.php help?

**Comment by realmontazeri** [comment]
It looks working but is this recommended on a live website?

**Comment by Moc** [comment]
I am not that familiar with the Cloudflare services to know exactly how it works. Assuming Cloudflare handles your website protection, you can disable the token generation and checking (that is essentially what you are doing) on a live website.
