### ISSUE TITLE
How to remove column in AdminUI

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4185]
I hide some field in init()  (displaying depends on some condition)
Example:
`$this->fields['content_subheading']['type'] = "hidden";
`
 But column is still displayed.

It is not listed in `$this->fieldpref`  and it is not listed in column options.  

![image](https://user-images.githubusercontent.com/5429548/83657957-dc35b580-a5c1-11ea-9168-fe660b726b5c.png)

It is not displayed in edit mode. 

I suppose it was set before to display manually and hidden after it.  But if field is hidden, it shouldn't be displayed in list mode either.

Thanks.

**Comment by Moc** [comment]
Can you show me some more of the code?

**Comment by Jimmi08** [comment]
```
	'content_subheading'      => array (  'title' => CONTENT_ADMIN_CAT_LAN_3,
			'type' => 'textarea',
			'data' => 'str',
			'width' => 'auto',
			'help' => '',
			'readParms' =>  array (),
			'writeParms' =>  array ('size'=>'block-level'),
			'class' => 'left',
			'thclass' => 'left',
	),
```


```
public function init()
{
if(!$checksubheading) { $this->fields['content_subheading']['type'] = "hidden"; }
}
```

@Moc  
it is definitely related to user_prefs. That user selected it when it was visible. then settings were changed and list mode ignores it.

![image](https://user-images.githubusercontent.com/5429548/83667725-21acaf80-a5cf-11ea-8fc4-8a44128a08d3.png)

I checked to set that field directly hidden (not in init()), the same result.  

As soon as field type is hidden, user prefs shouldn't have priority. It works for edit mode.

**Comment by CaMer0n** [comment]
'nolist'=>true

**Comment by Jimmi08** [comment]
It is working,. Thank you
