### ISSUE TITLE
'editor' key template for pages - what is intention for this?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4190]
There is in developer (or better debug) mode functionality when you can get some template data in create mode for pages. 

```
			if($this->getAction() == 'create' && e_DEBUG === true)
			{

				$tmp = e107::getCoreTemplate('page', 'default');
				if(!empty($tmp['editor']))
				{
					$this->fields['page_text']['writeParms']['default'] = $tmp['editor'];
				}

			}
```

It looks very interesting. What was the intention for something like that?

`$PAGE_TEMPLATE['default']['editor'] = '<ul class="fa-ul"><li><i class="fa fa-li fa-edit"></i> Level 1</li><li><i class="fa fa-li fa-cog"></i> Level 2</li></ul>`';

Thanks

**Comment by CaMer0n** [comment]
It was experimental for page content templates. ie. the theme could set the default that would be used when creating pages.

**Comment by Jimmi08** [comment]
It would be useful if you use a real template, not hardcoded "default".
