### ISSUE TITLE
title for facebook icon on login page should have different value

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4194]
## Motivation
Details.
Now there is title:  Register with your Facebook account

## Proposed Solution
It should be Log in with your Facebook account

 Thanks
PS. Signup has title Sign-in with your Facebook account, so maybe just wrong LAN.

**Comment by tgtje** [comment]
Provider is a coded [ x ] so general.. please take a look at/in social/lang/English/English(or alike)_global php Notice the differences..
