### ISSUE TITLE
be able to test templating social login/signup without set it on

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4197]
## Motivation
easier testing for signup/login/modal login template

## Proposed Solution
in developer mode (not in debug) return always some content for those shortcodes. F.e. for all core providers to check the result for all possible icons? Or limited number?

I don't know if there is something like theme developer mode.

## Alternatives
Any way, a hardcoded way is ok too.  I thought that I was able to change something in those shortcodes to get always some output, but nothing worked.

## Additional Context
Yes, I could set it on with fake data, but actually my providers' list is blank, no idea why, it is localhost, nobody else has this problem, and trying to check this on live site ended with the site down.  I haven't time to test this, I just need to finish the signup template.

![image](https://user-images.githubusercontent.com/5429548/84866760-74c83d00-b07a-11ea-93e0-80740b6ab7ef.png)

Thanks.

**Comment by tgtje** [comment]
Q:  my providers' list is blank, no idea why, it is localhost  Same here on local, had to select a provider first.. testpage will run, but due to not filled in the ID and url etc.. only messages

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/4193

@tgtje  this FR is about 3 templates and it would be best to test all providers at once when developing theme. Not about social login.
CaMeRon confirmed that he sees providers list on localhost, so I didn't look at it.
