### ISSUE TITLE
Admin UI can be used only for installed plugins?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4198]
## Question
What are you confused or uncertain about?
I have a plugin with plugin.xml  
`installRequired="false"`

But I got warning about the not installed plugin

`e107::getMessage()->addWarning($obj."The plugin is not installed or \$pluginName: is not valid. (".$this->pluginName. ")"); // debug only.
`

It would be enough to have this only for debug, but it is there always.

**Comment by CaMer0n** [comment]
@Jimmi08 Does your plugin use tables or preferences? If so, then` installRequired="true"` is needed.
This is what the Admin-UI is made for.

**Comment by Jimmi08** [comment]
@CaMer0n I thought it, but it is too good to do this manually.  I found ways around this :)  Thanks
