### ISSUE TITLE
handler dependent on social plugin

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#4199]
https://github.com/e107inc/e107/blob/94dbbb02781212ac8a9b81144fbafbd16ea94917/e107_handlers/user_handler.php#L1113

This line requires a file from social plugin. This means that even if you are not using this plugin, you cannot delete it from the plugins folder or the system will crash.

Error shown when deleting social plugin:

Fatal error: require_once(): Failed opening required '../e107_plugins/social/includes/social_login_config.php' (include_path='.;C:/***/php/pear') in C:\***\e107_handlers\user_handler.php on line 1113

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/1379

**Comment by Deltik** [comment]
Easiest way to fix this would be to move `./e107_plugins/social/includes/social_login_config.php` into the core somewhere, but I'm not sure where.

**Comment by Moc** [comment]
@Deltik A new social login handler in `e107_handlers`?

**Comment by Deltik** [comment]
Yes, moving that class `social_login_config` to `e107_handlers` makes sense.

**Comment by Deltik** [comment]
Never mind.  Upon reviewing the code I wrote, I violated the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) by making `social_login_config` aware of Hybridauth when it should only be working with an `e_pref`.  I'll try to decouple these things in my fix.
