### ISSUE TITLE
Don't allow 2.3 compatible themes to use on 2.1 core  and older

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4200]
## Bug Description

There is no information about compatibility on the e107.org themes browser.

Label in Theme manager says only Recommended, that it is not true. Core e107 2.3.0 beta is mandatory not recommended if the theme is marked as compatible with 2.3.0.  
(Github version at least from April 2020 is needed)

Otherwise, the user breaks their site.

**Comment by tgtje** [comment]
Good idea, but it should then also be similar behaviour in core Find themes to be complete.

Just adding as reference (needs to be tested) 
During 'activation' of theme in site : 
Could it rely on <dependencies> like in plugins? Although this would be at a later point in time.
To overcome any issues..

**Comment by CaMer0n** [comment]
@Jimmi08 Please give it a test drive. Thanks. :-)
