### ISSUE TITLE
phpupload javascript error because missing lang

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4204]
## Bug Description
javascript error when admin is in different lang than Englisj

## How to Reproduce
Used Hungarian Admin area

## Expected Behavior
If user uses different admin language than English and js doesn't exist, there should be callback for en.js

## Screenshots

![image](https://user-images.githubusercontent.com/5429548/85732314-8f925580-b6fb-11ea-9a99-ef0223b239f3.png)

Edit: I just noticed that they use 2.2.1 version, maybe it was fixed

**Comment by CaMer0n** [comment]
It belongs in the e107 language pack and the file goes here: `e107_web/js/plupload/i18n`

You can download all of the other language files for plupload here: 
[i18n.zip](https://github.com/e107inc/e107/files/4838872/i18n.zip)

**Comment by CaMer0n** [comment]
Closing. Similar bugs can reported in the language pack repo.
