### ISSUE TITLE
newscats{active} -  shouldn't be {active} replaced by something?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4206]
## Question
Is this correct?  In category news menu.

![image](https://user-images.githubusercontent.com/5429548/86051584-f1352580-ba55-11ea-916a-068e83a0b188.png)

Core template:
```
// category menu
$NEWS_MENU_TEMPLATE['category']['start']       = '<ul class="news-menu-category">';
$NEWS_MENU_TEMPLATE['category']['end']         = '</ul>';
$NEWS_MENU_TEMPLATE['category']['item']        = '
	<li><a class="e-menu-link newscats{active}" href="{NEWS_CATEGORY_URL}">{NEWS_CATEGORY_TITLE}{NEWS_CATEGORY_NEWS_COUNT}</a></li>
';

```
 
Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Please give this change a test drive. 
`{active}` should be replaced with `{ACTIVE}` in your theme's template.

**Comment by Jimmi08** [comment]
It works, Thank you.
