### ISSUE TITLE
SQL Insert Error when creating a page

### ISSUE THREAD

**Issue by KevDoy** [e107inc/e107#4207]
On the latest 2.3.0 I am now seeing this error when trying to create a page.
![image](https://user-images.githubusercontent.com/11251011/86444964-70309500-bcc6-11ea-8015-6314a6875219.png)

The workaround:
It appears that if I don't restrict the robots, this error comes up. Can null be accepted or an option added for no restrictions?

Thanks

**Comment by Moc** [comment]
What's your MySQL version please? It can be found in the admin area - about - PHP info - left sidebar.

**Comment by KevDoy** [comment]
> What's your MySQL version please? It can be found in the admin area - about - PHP info - left sidebar.

5.7.30-0ubuntu0.18.04.1

**Comment by CaMer0n** [comment]
@KevDoy Thank you. I have a made a change, please update the files and run the database update. 
Also, could you please list everything that it says under "MySQL" in the PHP info left-side bar?
Thank you!

**Comment by CaMer0n** [comment]
Closing this as no feedback received.
