### ISSUE TITLE
Could you add some class for comment to be hide this message in theme?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4212]
## Motivation
there is s-message class 
I can't use cpage because it would be hide all messages

the best solution would be to add this as prefs to display this message when comments are off for some page

thanks
 
![image](https://user-images.githubusercontent.com/5429548/87177208-90221300-c2db-11ea-8b66-81fecb9b2deb.png)

**Comment by Moc** [comment]
Needs to be a pref. Closing this in favour of https://github.com/e107inc/e107/issues/3680
