### ISSUE TITLE
what can cause this? class2.php is not available

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4214]
Not my site, but my plugin is used, so I was asked for help. 
Still 2.2.1 version.  They say that nothing was changed (no update, no new plugin, nothing), just out of nothing fatal error. 
 
This
`require_once('../../../class2.php');`
and
`require_once('../../class2.php');`
returns fatal error:

PHP Fatal error: require_once(): Failed opening required '../../../class2.php' (include_path='.;C:\php\pear') in ***\e107_plugins\appstrap\admin\admin_config.php on line 6

They tested it with stats plugin (just to be sure if it is plugin issue or not) and the same error only with `../../class2.php`

PHP Version 7.3.19

This happens with any plugin. But for core plugins, if there is path in e107_admin folder, it works (f.e. news)

What can be the reason for this?

Thanks

**Comment by tgtje** [comment]
Just an observation : you mention >not my site... so live site? if yes...why  C:\php\pear  (pc install xamp/wamp?).

**Comment by Jimmi08** [comment]
@tgtje  no idea, they say that it is a local server.

But I got the answer:
 
> Found the issue. It was permissions related.
> Really odd. This program likes more permissions than I would like to give...

So I am closing this. But it is weird that only plugins folder has a problem.
