### ISSUE TITLE
Wrong comment avatar +  Reason

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4217]
## Bug Description
All comments (anonymous post is disabled)  display the same avatar for all comments (if the user is logged in)

The reason is this code in comment_shortcodes.php

```
		// Posting a new comment (check that it is not an existing comment by anonymous user) - #3813 & 3829
		if($this->var['comment_author_id'] != '0' && USERID)
		{
			$userdata = e107::user(USERID); 
			$this->var = array_merge($this->var, $userdata); 
		}

```
With existing comments $this->var['comment_author_id']  has values 2, 4, 5, so that check is always true and user values are overridden.  It doesn't mind with other values, because they are used from comment itself.

I am not sure about the anonymous post or what should be value for new comments, but that original test is wrong. I am a bit short of time, sorry. 

Edit:
 That fix is more complicated:
```
0 - Anonymous
> 0 - normal user
```
for everything else should be used logged in user data.

**Comment by KiraTheUltimate** [comment]
Same problem to me. Using with modified BS_Magazine_02. I see my own avatar for all users.

![sample](https://user-images.githubusercontent.com/12445784/88388760-6ece2600-cdb5-11ea-91a7-53841c6ce23e.PNG)

**Comment by CaMer0n** [comment]
@Moc @Jimmi08 @KiraTheUltimate  The last commit "should" fix the issue. Tested locally without any issue. 
Please test and confirm asap. 
Thank you.

**Comment by Jimmi08** [comment]
@CaMer0n just locally, latest sync
It looks correct

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 !
