### ISSUE TITLE
Unable to change site preference setting "User class which can email links to items on site" under comments/posting section.

### ISSUE THREAD

**Issue by nalicko** [e107inc/e107#4220]
## Bug Description

Tried to change the "User class which can email links to items on site" setting from Members user class to No One (inactive). However, when attempting to change the setting to any other user class and submitting the changes, it prompts an error stating "Settings not saved as no changes were made." I am using the latest version 2.3.0 and have tried using Chrome, Edge, Firefox, and Internet Explorer with no success.

## How to Reproduce
1. Go to 'Site Preferences'
2. Click on 'Comments/Posting'
3. Scroll down to 'User class which can email links to items on site'
4. Change setting to another user class
5. Error "Settings not saved as no changes were made."

## Expected Behavior

Setting should have changed to the selected user class.

### PHP Operating System

```
Linux s21.fused.com 2.6.32-754.29.1.el6.x86_64 #1 SMP Mon Apr 27 15:30:33 UTC 2020 x86_64
```
### PHP Version

```
PHP Version 5.6.40
```
### MySQL Version

```
MySQL Version 5.7.31
```

### PHP Modules

bcmath
calendar
cgi-fcgi
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
ionCube Loader
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
Reflection
session
SimpleXML
soap
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend Guard Loader
zip
zlib

### Client Information

Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Other HTTP headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Host: duckduckgo.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
SEC-FETCH-DEST: document
SEC-FETCH-MODE: navigate
SEC-FETCH-SITE: none
UPGRADE-INSECURE-REQUESTS: 1

**Comment by Jimmi08** [comment]
Confirmed. 
`$_POST` is correct
`$newValue = $tp->toDB($value); `is correct

it fails on this line: 
`$core_pref->update($key, $newValue);`

Note:  this prefs 'email_item_class' is not listed in core prefs in default_install.xml

**Comment by CaMer0n** [comment]
Thank you @nalicko 

Please update your e107_core/xml/default_install.xml file with the one in github and then run the core preference update found here: 

(your-site.com)/e107_admin/db.php?mode=db_update

**Comment by CaMer0n** [comment]
Closing this, but please re-open if it occurs again.
