### ISSUE TITLE
Adding Disqus comment system to e107

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#4222]
## Motivation
In 2020, the time for forum, registration and comments on each website has expired. Many people are lazy to register and then comment on certain news and articles. A facebook comment is an alternative option, but not everyone has a facebook and they don’t even want to register.

## Proposed Solution
The Disqus comment system is a good alternative. It is used by many large websites, so a lot of people already have a registration. With this registration, they can also comment on other websites where there is a disqus system.

I saw that it is possible to add a Disqus registration in the Social Plugin, but it is not possible to replace the comment system with Disqus.
There is an alternative way to replace to comment system to Disqus or will it be possible to choose this in the settings in the future?

**Comment by Moc** [comment]
On my opinion this is plugin territory. Plugins are able to hook into the comment engine as an alternative to the built in comment functionality. Eventually such a plugin may become a core plugin, but I don't think it should be a core functionality at this point.

**Comment by Jimmi08** [comment]
@KiraTheUltimate Thank you for idea, exactly what I will need soon.  Good to test if it is really so easy... (I have it for 1.0.4 and it was, but it was done only with theme changes)

**Comment by Jimmi08** [comment]
@Moc 
somebody of core developers should try to do this and then you will maybe understand why I am still asking for fix double content  

```
 this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
 this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
```
Each version of the same URL will be loaded with different comments thread.

**Comment by KiraTheUltimate** [comment]
@Jimmi08 

Are you doing such an extension (disqus) for e107 or am I misunderstood?

**Comment by Jimmi08** [comment]
@KiraTheUltimate It is already tested on my site, I added test news, no login is needed (shouldn't be), you can ask there.

**Comment by Jimmi08** [comment]
@Moc this can be closed
