### ISSUE TITLE
backup option doesn't backup database 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4225]
## Bug Description
e107 is not able to backup database on live server

This is localhost:
![image](https://user-images.githubusercontent.com/5429548/89156653-54413d00-d56b-11ea-8c28-979b5c67499c.png)

This is live site:
![image](https://user-images.githubusercontent.com/5429548/89156748-7c30a080-d56b-11ea-99dd-5ce12f0b8f72.png)

As you can see SQL file is not created. 
 

Live site:
PHP Version 5.6.40
10.1.38-MariaDB-1~xenial
PDO: Enabled
NO_ENGINE_SUBSTITUTION

Version 2.3.0 (git)

 Admin log:
 
![image](https://user-images.githubusercontent.com/5429548/89157218-712a4000-d56c-11ea-8875-71fdfa10f154.png)

**Comment by Jimmi08** [comment]
Reason:
This
`$dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host='.$config['mySQLserver'].';dbname='.$config['mySQLdefaultdb'], $config['mySQLuser'], $config['mySQLpassword'], $dumpSettings);`

return error:

`mysqldump-php error: Connection to mysql failed with message: SQLSTATE[HY000] [2005] Unknown MySQL server host 'mariadb101.websupport.sk:3312' (2)`

but correct connection according my hosting should be: 

`$connection = new PDO("mysql:host=mariadb101.websupport.sk;port=3312;dbname=****", "****", "***");`

After hardcoded those 2 values, backup was created:
![image](https://user-images.githubusercontent.com/5429548/89159397-b8660000-d56f-11ea-8bf5-5dd3e88f1ea8.png)

**Comment by Jimmi08** [comment]
This was solved this way before: 

https://github.com/e107inc/e107/issues/1831

**Comment by Moc** [comment]
@Deltik do we need to apply the same fix to the pdo handler?

**Comment by Jimmi08** [comment]
@Moc just for backup, connect() works this way. At least I hope and it didn't fall back to mysql connect.

**Comment by Deltik** [comment]
@Moc: No, the hostname and port are already parsed by the time `e_db_pdo::backup()` is called.  This patch should fix the issue:
```diff
diff --git a/e107_handlers/e_db_pdo_class.php b/e107_handlers/e_db_pdo_class.php
index 1e73bf01b..511f45690 100644
--- a/e107_handlers/e_db_pdo_class.php
+++ b/e107_handlers/e_db_pdo_class.php
@@ -2455,8 +2455,6 @@ class e_db_pdo implements e_db
 
    //     include_once(dirname(__FILE__) . '/Ifsnop/Mysqldump/Mysqldump.php');
 
-        $config = e107::getMySQLConfig();
-
                $dumpSettings = array(
                'compress'                      => !empty($options['gzip']) ? Ifsnop\Mysqldump\Mysqldump::GZIP : Ifsnop\Mysqldump\Mysqldump::NONE,
                'include-tables'                => array(),
@@ -2477,13 +2475,13 @@ class e_db_pdo implements e_db
 
         foreach($tableList as $tab)
         {
-            $dumpSettings['include-tables'][] = $config['mySQLprefix'].trim($tab);
+            $dumpSettings['include-tables'][] = $this->mySQLPrefix.trim($tab);
         }
 
 
         try
         {
-            $dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host='.$config['mySQLserver'].';dbname='.$config['mySQLdefaultdb'], $config['mySQLuser'], $config['mySQLpassword'], $dumpSettings);
+            $dump = new Ifsnop\Mysqldump\Mysqldump("mysql:host={$this->mySQLserver}; port={$this->mySQLport}; dbname={$this->mySQLdefaultdb}", $this->mySQLuser, $this->mySQLpassword, $dumpSettings);
                    $dump->start($backupFile);
                    return $backupFile;
                }
```

**Comment by Deltik** [comment]
@Moc: No, the hostname and port are already parsed by the time `e_db_pdo::backup()` is called.  This patch should fix the issue:
```diff
diff --git a/e107_handlers/e_db_pdo_class.php b/e107_handlers/e_db_pdo_class.php
index 1e73bf01b..511f45690 100644
--- a/e107_handlers/e_db_pdo_class.php
+++ b/e107_handlers/e_db_pdo_class.php
@@ -2455,8 +2455,6 @@ class e_db_pdo implements e_db
 
    //     include_once(dirname(__FILE__) . '/Ifsnop/Mysqldump/Mysqldump.php');
 
-        $config = e107::getMySQLConfig();
-
                $dumpSettings = array(
                'compress'                      => !empty($options['gzip']) ? Ifsnop\Mysqldump\Mysqldump::GZIP : Ifsnop\Mysqldump\Mysqldump::NONE,
                'include-tables'                => array(),
@@ -2477,13 +2475,13 @@ class e_db_pdo implements e_db
 
         foreach($tableList as $tab)
         {
-            $dumpSettings['include-tables'][] = $config['mySQLprefix'].trim($tab);
+            $dumpSettings['include-tables'][] = $this->mySQLPrefix.trim($tab);
         }
 
 
         try
         {
-            $dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host='.$config['mySQLserver'].';dbname='.$config['mySQLdefaultdb'], $config['mySQLuser'], $config['mySQLpassword'], $dumpSettings);
+            $dump = new Ifsnop\Mysqldump\Mysqldump("mysql:host={$this->mySQLserver}; port={$this->mySQLport}; dbname={$this->mySQLdefaultdb}", $this->mySQLuser, $this->mySQLpassword, $dumpSettings);
                    $dump->start($backupFile);
                    return $backupFile;
                }
```

@Jimmi08: Can you try this patch to see if it works for your setup with the custom hostname and port?

**Comment by Jimmi08** [comment]
@Deltik I am getting error:
`mysqldump-php error: Missing database name from DSN string`

This version works (I just replaced $config), but I have no idea what is wrong/different with yours (I checked id, string is correct, db is there):
`$dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host='.$this->mySQLserver.';port='.$this->mySQLport.';dbname='.$this->mySQLdefaultdb, $this->mySQLuser, $this->mySQLpassword, $dumpSettings);`

**Comment by Deltik** [comment]
@Jimmi08: Sorry, I had some extraneous spacing in the DSN string.  [Here](https://github.com/e107inc/e107/issues/4225#issuecomment-668072838)'s the updated patch.  I tested it myself this time, and the data got exported as expected.
