### ISSUE TITLE
Q when you install plugin, e_module is not loaded in plugin_setup.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4226]
## Question
If you need something available through the system, you use e_module 

But I found that it is not available in customplugin_setup.php file.  

Is this correct? 

Thanks

**Comment by CaMer0n** [comment]
e_module.php is only loaded for installed plugins and is loaded by class2.php

**Comment by Jimmi08** [comment]
Thanks, it gives a sense.
