### ISSUE TITLE
Question: System Information Message

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4227]
I am looking at a custom page that has a System Information Message at the bottom - Informing me that Comments on this page are locked.

Thought it was just a message for Admins - but every one can see it. Is it setup to do it like that? 

I would think that message would be for admins, just in case they wanted comments enabled on that page.
https://501stlegion-a3.com/page/terms-and-conditions

Same thing but for news items on another site (No news items at the moment - please check back soon):
https://www.hellsblackaces.com/dir/index.php

**Comment by Moc** [comment]
#3680

I think the best way to fix is to limit this to admin only indeed.
