### ISSUE TITLE
tinymce in admin area with frontend styling

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4228]
Admin theme uses different styling that frontend theme and it would be great for the user if they could see frontend look if they are editing content

I am just working with the theme for 0.7.25 and it is possible there.   The reason is that they load TinyMCE in the iframe 
and using this: `$tinyConfig["content_css"]` =  - where are listed frontend CSS files . 

I don't have idea if this was part of 0.7.25 or this is just some customization, or it is because TinyMCE 3 and it is not possible in TinyMCE 4, but I must say it is pretty cool  

Any thoughs on this? 

See difference? Normally you would see there not styled button. 

![image](https://user-images.githubusercontent.com/5429548/89645788-de1a3e80-d8ba-11ea-9344-411f059f7709.png)

**Comment by Jimmi08** [comment]
In fact, it is pretty easy to do. Result:

 
![image](https://user-images.githubusercontent.com/5429548/99153395-915bb600-26a8-11eb-87c7-9be23ce7873a.png)


Just loading correct files for $editorCSS in wysiwyg.php file. 

Could you add this to the theme config class or somewhere?  What files to load?  theme libraries + those files?

And if it is not set, only then load default bootstrap3 files?

What I did to get it working:
```
        $sitetheme = e107::getPref('sitetheme');
		$pathBS = e107::getLibrary()->getProperty('bootstrap4', 'library_path');
		$pathBS .= '/';
		$pathBS .= e107::getLibrary()->getProperty('bootstrap4', 'path'); // sub-folder

		$pathFA = e107::getLibrary()->getProperty('fontawesome5', 'library_path');
		$pathFA .= '/';
		$pathFA .= e107::getLibrary()->getProperty('fontawesome5', 'path'); // sub-folder

		$pathAn = e107::getLibrary()->getProperty('animate.css', 'library_path');
		$pathAn .= '/';
		$pathAn .= e107::getLibrary()->getProperty('animate.css', 'path'); // sub-folder
        
        
             //		
		$editorCSS = array(
           	0 => $pathBS . '/css/bootstrap.min.css',
            1 => e_THEME_ABS.$sitetheme."/css/freelancer.min.css",
			2 => $pathFA . '/css/all.min.css',
			3 => e_PLUGIN_ABS . 'tinymce4/editor.css',
			4 => $pathAn . 'animate.min.css',

		);
```

**Comment by Jimmi08** [comment]
@CaMer0n  I am aware you are busy, but can you at least tell me if it is planned to consider this?

I have got this working this way:

in theme.php:
 
```
class theme implements e_theme_render
{
 
    var $theme_css_array = array();
    
    function __construct() {
       
        $this->theme_css_array = array(
         0 => e_THEME_ABS.'hestia/assets/css/hestia.css',
         1 => e_THEME_ABS.'hestia/css/color-default.css',
         2 => e_THEME_ABS.'hestia/assets/css/fonts/pe-icon-7-stroke.css',
        ); 
```

In wysiwyg.php

```
        if(class_exists('theme')){
           $themeArray = new theme; 
        }
        foreach($themeArray->theme_css_array AS $key => $css) {
              $editorCSS[$key] = $css;
        }   
	$editorCSS = $tp->replaceConstants($editorCSS, 'abs');
```

And this is result:
![image](https://user-images.githubusercontent.com/5429548/100526670-6f475500-31cb-11eb-9a42-844f56cc86a4.png)


Thanks

**Comment by CaMer0n** [comment]
I like it. It just needs to be mostly automatic (use theme.xml values) and have a pref to enable/disable it.

**Comment by Jimmi08** [comment]
I like the way how you can override style.css...  if there is style_custom.css, it is loaded. 
maybe if there is style_wysiwyg.css (style_tinymce.css), it could be loaded. You can easily use @import to add there css you want to use there.  Just idea. 

And be aware that there should be a way for the theme to override (add its own ones) templates and styles (I needed bootstrap4 buttons there for example).  So more prefs in TinyMCE.

**Comment by Jimmi08** [comment]
@CaMer0n Testing:

```
    <stylesheets>
        <css file="cayman-style.css" name="Cayman" scope="front,wysiwyg" />
        <css file="style.css" name="Default" scope="front,wysiwyg" />
    </stylesheets>
```

cayman-style.css is loaded in WYSIWYG
style.css is not

Cayman shouldn't be listed there:
![image](https://user-images.githubusercontent.com/5429548/107858538-fbfdc880-6e34-11eb-9c64-ef54cfdd8fa7.png)

Not sure how to set cayman-style.css, it is loaded on the front with e107::css() so maybe "front" is not needed.

The files should be loaded in the order as they are in the XML file?

Cache cleared after each change in theme.xml

Otherwise, it is a great difference, thanks:
![image](https://user-images.githubusercontent.com/5429548/107858654-71699900-6e35-11eb-903c-a6474e6f0801.png)

**Comment by CaMer0n** [comment]
@Jimmi08 I tested with your example, and both css files loaded into TinyMce without an issue. I also tested with more files and it works as intended. Yes, files are loaded in the order defined in theme.xml

![image](https://user-images.githubusercontent.com/2825679/107866397-46774900-6e25-11eb-9da9-319a47c29aa7.png)

You can view your generated TinyMce config file here: /e107_plugins/tinymce4/wysiwyg.php?debug=1 to check loaded as well. 

I have fixed the admin area selection.

**Comment by Jimmi08** [comment]
Confirmed. it works. It will need a bit different approach to styling... Thanks

**Comment by CaMer0n** [comment]
You're welcome.
