### ISSUE TITLE
Online Languages packs not displaying in 2.3.0-rc1

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4229]
## Motivation
There are no languages packs listed for 2.3.0 version

![image](https://user-images.githubusercontent.com/5429548/90368200-0861be00-e06a-11ea-9856-73dbac43a09b.png)

## Proposed Solution
1.  Add help for the correct name of the tag if you want to be listed in languages packs 

2. List all available packs, just latest tag, 

Thanks

For actual version this doesn't work:
![image](https://user-images.githubusercontent.com/5429548/90368042-c0429b80-e069-11ea-9e60-62e5e3ec2bd9.png)
![image](https://user-images.githubusercontent.com/5429548/90368086-d2bcd500-e069-11ea-9fe3-6ba61430a700.png)
![image](https://user-images.githubusercontent.com/5429548/90368149-f54eee00-e069-11ea-93ed-a778127725d2.png)

**Comment by CaMer0n** [comment]
I just checked locally and on 2 production sites. The result is the same: 

![image](https://user-images.githubusercontent.com/2825679/90428348-b4aaa100-e078-11ea-8593-243d00790c09.png)

**Comment by Jimmi08** [comment]
@CaMer0n what is your e107 version?  git? Or RC1?

I just updated 2.2.1 local version (with languages listed) to official RC1 release:

![image](https://user-images.githubusercontent.com/5429548/90429026-3a543e00-e0c5-11ea-90c3-c8a8936d117c.png)

German lang was already installed:

![image](https://user-images.githubusercontent.com/5429548/90429056-47712d00-e0c5-11ea-8684-059a5b765ce2.png)

**Comment by CaMer0n** [comment]
Mine is Git. Try enabling DEBUG mode, does it help?

**Comment by Jimmi08** [comment]
No change. I can see error:
`Invalid argument supplied for foreach(), Line 383 of ***\e107_admin\language.php`

**Comment by tgtje** [comment]
Mine (live) does display the same as Cameron's  (with name pre-release x2)

**Comment by Jimmi08** [comment]
Version **2.3.0-rc1**
- no lang packs

I tried to sync with github, I can see that admin/ver.php says 2.3.0 (git), but **version** wasn't changed.

I deleted pref version, run update, and e107 version is now 2.2.0

Lang packs are displayed for 2.2.0.

Then I synced again, and version was changed to 2.3.0 and lang packs are displayed.

So @tgtje  check what is value of your version pref.  I suppose you don't use official release. Next weird thing is that it didn't change version after sync from 2.3.0-rc1 to 2.3.0 git. But it did it after sync from 2.2.0.

**Comment by tgtje** [comment]
@Jimmi08 
2.3.0 (git) 5-5-2020 live
2.3.0 (git) 23-7-2020 local (one of the latest)
2.3.0 (git) 12-01-2020 local ) old one > also displays preleases  
all are synced versions at the time

**Comment by Jimmi08** [comment]
> @Jimmi08
> 2.3.0 (git) 5-5-2020 live
> 2.3.0 (git) 23-7-2020 local (one of the latest)
> 2.3.0 (git) 12-01-2020 local ) old one > also displays preleases
> all are synced versions at the time

But I am testing official release pack, not developer version.

**Comment by tgtje** [comment]
@Jimmi08  Got it, new install from official download.
In the off.version ver php has : $e107info['e107_version'] = "2.3.0-rc1";
While git says $e107info['e107_version'] = "2.3.0 (git)";  (changed 1 month ago).
After changing the off ver php to $e107info['e107_version'] = "2.3.0 (git)"; All functions and language packs show up.

**Comment by CaMer0n** [comment]
@Jimmi08 Please replace the 2 files and close if fixed for you. Thanks

**Comment by Jimmi08** [comment]
Thank you. I will reopen it in the next attempt if needed.
