### ISSUE TITLE
selectize css is loaded on wrong place (order)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4237]
## Bug Description

Selectize css is loaded in the footer and it is very hard to override with theme css 

`	e107::css('core', 'selectize/css/selectize.css', 'jquery');`

The correct way should be this:

`e107::css('core', 'selectize/css/selectize.css' );`

But maybe there is some reason for this.

**Comment by CaMer0n** [comment]
I believe it is because it is only loaded when necessary. And this occurs after the header has been loaded.

**Comment by CaMer0n** [comment]
Try using **!important**, does it help?

**Comment by Jimmi08** [comment]
Yes, it was the solution. I just was surprised why css has a dependency on jquery..
