### ISSUE TITLE
Update Error : No Clue How To Fix.  need Help

### ISSUE THREAD

**Issue by bmatheny33** [e107inc/e107#4239]
Tried to update a working e107 install on my server.  Asked my server guy to complete the UPDATE with the latest downloaded version.  He stated it said he did not have the credentials required when he got to the settings for the database/sql (which I know he has proper credentials).

We stopped the installation at that point and started getting this error...

CRITICAL ERROR:
Line : generic, class2.php
[6]: Unable to form a valid connection to mySQL. Please check that your e107_config.php contains the correct information.

We've put back the original e107_config.php file from our backup of the site before we tried to upgrade.  NO LUCK (same error)

We tried restoring the original site back to the server - no luck (same error).

I'm pretty sure there is a better way to address UPDATES vs. NEW INSTALLS with the e107 application.  Possibly a separate install process vs. this issue.

Right now I need help (a developer or support person) that can help me get the new version installed and working on my server.  I'm no expert and my server guy is saying "find someone that knows e107 to help".  Any takers or suggestions?

![2020-08-27_e107error](https://user-images.githubusercontent.com/36304574/91468230-8aaa6900-e846-11ea-827e-d1f89fb7c342.png)

**Comment by Deltik** [comment]
Upgrading e107 is done by extracting the upgrade archive (a file that ends with `_upgrade.zip` or `_upgrade.tar.gz`) over the existing files.

If you restored a backup of the old site and the issue persists, it is very likely that your administrator made a mistake during the restoration.

I can take a look if you [privately message me](https://gitter.im/Deltik) the credentials to access your e107 files.

**Comment by Deltik** [comment]
As discussed on Gitter, this issue was caused by the wrong password being set for the MySQL user.  After resetting the password, the site came back to life.
