### ISSUE TITLE
type checkboxes doesn't work 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4240]
Maybe this is the intention, but type checkboxes look that it works but all values have value 1, so they are not saved correctly after update.  Dropdown works, but it would be really hard to do something like this dropdown.

Problem was that I noticed the problem too late, that was no warning. 

Original setting:
`'characters'              => array (  'title' => 'Characters',  'type' => 'checkboxes',  'data' => 'str',  'width' => 'auto',  'help' => '',  'readParms' =>  array (),  'writeParms' => array ('multiple'=>'1', 'inline'=>'1'),  'class' => 'left',  'thclass' => 'left',  'filter' => false,  'batch' => false,),
`

`$this->fields['characters']['writeParms']['optArray'] = $values ; // Example Drop-down array. `

![image](https://user-images.githubusercontent.com/5429548/91542360-062b1980-e91e-11ea-9c51-b2d019a94ada.png)

I solved this by using the method type, so it is really no issue for me.   I understand if this is not supported.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 . Could you please post a portion of the HTML generated?

**Comment by Jimmi08** [comment]
More simplier:
 `           'catid'  => array ( 'title' => LAN_CATEGORY 'type' => 'checkboxes', 'data' => 'str', 'width' => 'auto', 'help' => '', 'readParms' => array (), 'writeParms' => array ('multiple'=>'1', 'inline'=>'1'), 'class' => 'left', 'thclass' => 'left', 'filter' => false, 'batch' => false,),`


![image](https://user-images.githubusercontent.com/5429548/92407263-5aae7000-f13a-11ea-83f5-8ebc83336469.png)

all values = 1

`<div id="catid-container" class="checkboxes checkbox" style="display:inline-block" data-original-title="" title=""><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[0]" value="1" id="catid-0-1" class="form-check-input" checked="checked" multiple="multiple" data-original-title="" title=""><span>None</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[5]" value="1" id="catid-5-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Snarry</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[6]" value="1" id="catid-6-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Drarry</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[4]" value="1" id="catid-4-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Severitus</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[3]" value="1" id="catid-3-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Snamione</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[2]" value="1" id="catid-2-1" class="form-check-input" checked="checked" multiple="multiple" data-original-title="" title=""><span>Dramione</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[7]" value="1" id="catid-7-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Iné párovanie</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[10]" value="1" id="catid-10-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Klasické poviedky</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[12]" value="1" id="catid-12-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Scorpius/Rose</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[1]" value="1" id="catid-1-1" class="form-check-input" checked="checked" multiple="multiple" data-original-title="" title=""><span>Mix</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[17]" value="1" id="catid-17-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Snupin</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[14]" value="1" id="catid-14-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Next Gen</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[23]" value="1" id="catid-23-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Crossover</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[15]" value="1" id="catid-15-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Harmony</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[16]" value="1" id="catid-16-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Fremione</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[18]" value="1" id="catid-18-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Remus/Hermiona</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[19]" value="1" id="catid-19-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Remus/Sirius</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[20]" value="1" id="catid-20-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Remus/Tonks</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[21]" value="1" id="catid-21-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Scorpius/Albus</span></label><label class="checkbox-inline" data-original-title="" title=""><input type="checkbox" name="catid[24]" value="1" id="catid-24-1" class="form-check-input" multiple="multiple" data-original-title="" title=""><span>Adventné kalendáre</span></label></div>`

**Comment by Jimmi08** [comment]
And another thing:
dropdown multicheck works only with ` 'writeParms' =>  array ('multiple'=>'1' ), `  
but not with
` 'writeParms' =>  array ('multiple'=>true ), `

It is confusing,

**Comment by CaMer0n** [comment]
@Jimmi08 The tests on this are passing. Try using _useKeyValues_.  Normally type 'checkboxes' shouldn't require 'multiple'. 

https://github.com/e107inc/e107/blob/49c1a0eb1003c8b1d369f4306bb86b2c5745b877/e107_tests/tests/unit/e_formTest.php#L416

**Comment by Jimmi08** [comment]
Thank you.  It looks working. 

Just to have it complete, there is too 'useLabelValues' option.   

@CaMer0n 
Is there a reason why for "checkboxes" don't have a default value (if neither of them is set, then 'useKeyValues' should be used)? Thanks
