### ISSUE TITLE
Question: USER_AREA

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4243]
in the plugin Falling Holidays, in e_header.php - the code `if(vartrue($pluginpref['XMasLights']) && USER_AREA) { ` was used to make sure the plugin would not load in the admin area (just front end) - how would I get it to be just the front end of the site?

**Comment by Moc** [comment]
I don't understand the question. The code you showed is used to display only on frontend (user_area). Do you mean you want code only in the admin area?

**Comment by Jimmi08** [comment]
> I don't understand the question. The code you showed is used to display only on frontend (user_area). Do you mean you want code only in the admin area?

@Moc that code didn't work for some reason and Lights were displayed in the admin area too.  I created that issue in his repository because I printed USER_AREA and it wasn't defined in admin area of this plugin. 
I changed it to test ADMIN_AREA so it works for me now, but it is just weird.

**Comment by Moc** [comment]
Caching perhaps
