### ISSUE TITLE
Forum: Editing message bring back to first message of the thread

### ISSUE THREAD

**Issue by ericc-dream** [e107inc/e107#4245]
## Bug Description
Recently I made a lot of test in the forum to validate the wysiwyg editor TinyMCE
I have a dedicated thread in which I post tests messages since a long time (the first message of the thread is from 2007 !!) , so it have a lot of pages.
I was testing the capability to edit old messages, let say from page 4. When I was done and click on "Update reply" , the forum bring me back on the first page to the first message which is quite annoying !

## How to Reproduce
Take a long thread in the forum, several pages.
Take a message at the end of the thread and select "Edit" 
Do what you want
Click "Update reply" 
You are back to the first page

## Expected Behavior
I was expecting to see the modified message

**Comment by Jimmi08** [comment]
Confirmed.  Page parameter is ignored in editing.

Related:
https://github.com/e107inc/e107/issues/4722
