### ISSUE TITLE
Moderators forum not visible after upgrade

### ISSUE THREAD

**Issue by MarcoV1980** [e107inc/e107#425]
I've made a new userclass named moderators on my v1 install.

Then i put that class as mod for my forum. After upgrade it just shows as:

Moderator(s): Array, Array, Array, Array, Array, Array

**Comment by pierre0042** [comment]
I am having the same issue

**Comment by pierre0042** [comment]
I have no more this issue since #1336 is fixed

**Comment by pierre0042** [comment]
Finally the problem is back :/

**Comment by pierre0042** [comment]
Removing the "Forum thanks" plugin fixed the problem it seems
