### ISSUE TITLE
Is this correct?  One reason for neverending core update

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4258]
I had a neverending core update (Update core database structure):

with debug message:
`Update required in update_routines.php on line 556`

With Database check integrity - no error, tables were OK.

It was caused by the custom plugin. Because I supposed that the SQL file for some plugin has to have the format:
_plugin_name_sql.php_

I renamed it to x_plugin_name_sql.php 
(the reason for this is that I can't have deleted those tables in any case -plugin uninstall etc, but they were used for plugin builder)

After checking the plugin table I noticed that file is there. As in sql addons in core prefs too. 

I had to manually delete that file, remove it from the plugin table and rescan the plugin folder to rid it from core prefs.

After this, no core update message

So the question is: why this file was considered as plugin sql addon?  it didn't match the rules for the addon file.

**Comment by Jimmi08** [comment]
@Moc Without answer I don't know if this is bug or invalid. 
**Shortly:**  Should it accept any *_sgl.php file or only plugin_name_sql.php?
And maybe it is already fixed.

**Comment by Moc** [comment]
I think it will accept any *_sql.php file, not sure.

**Comment by Jimmi08** [comment]
:) it does now,  
`Create a new text file with the _sql.php extension. (eg. 'myplugin_sql.php')`
You are right, there is no mention that it is exclusively this way.  

And I think it is now managed by db-verify and there is not this problem.
