### ISSUE TITLE
Manual uploading plugin doesn't work 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4259]
## Bug Description
When you try to manually upload the plugin zip file, it fails

## Reason and fix:

Wrong action in form:
`<form enctype='multipart/form-data' method='post' action='".e_SELF."'>`
 
Working version (at least on localhost):
`<form enctype='multipart/form-data' method='post' action='".e_SELF."?mode=avail&action=upload'>`

![image](https://user-images.githubusercontent.com/5429548/96551879-46ba6a00-12b3-11eb-9983-b346869cfecd.png)
![image](https://user-images.githubusercontent.com/5429548/96551914-520d9580-12b3-11eb-91ef-0f4e30dbd804.png)

**Comment by CaMer0n** [comment]
Thank you @Jimmi08 !
