### ISSUE TITLE
why in admin area with English lang system is trying to load frontend global files?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4262]
My Admin area is English

![image](https://user-images.githubusercontent.com/5429548/97710198-bacaee00-1abb-11eb-96cb-58f630d0d651.png)

But I can see that a lot of non-existing files are loaded in the admin area.  Why is this? It looks like a waste of time...  Thanks

![image](https://user-images.githubusercontent.com/5429548/97710233-c5858300-1abb-11eb-9534-2e3baf7f3954.png)

**Comment by Moc** [comment]
It checks for global files and if present it loads the file. Global files are loaded on each page.

**Comment by Jimmi08** [comment]
> It checks for global files and if present it loads the file. Global files are loaded on each page.

But why for Slovak and not English?

**Comment by CaMer0n** [comment]
@Jimmi08 It's an issue with the debug message. It is actually trying to load the English file. Commit coming shortly.
