### ISSUE TITLE
Erroneous deletion of language file while LAN's still exist in code

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4266]
## Bug Description
Erroneous deletion ????? of language file while LAN's still exist in code (source using > e107_admin/modcomment.php).
Detected while checking file consistency in translation files. (file by file on line per line)
File > languages/English/admin/lan_modcomment.php

## How to Reproduce
use search on this REPO for example  MDCLAN_14 or MDCLAN_2 (  more defines not listed now, just for quick result).

## Expected Behavior
Should display existance in language file (only modcomment php reproduces LAN use)

## Additional Information
History search on available download packs pointing to the release of V 2.0 date: 2015-09-02.
All packs afterwards will not have this file. !!!

V2.0.beta 1 had it (date 2015-02-11) file was present. This was the last release upto V 2.0

**Comment by CaMer0n** [comment]
@tgtje Did my commit correct the issue for you?

**Comment by tgtje** [comment]
It does. 
I will close this issue (can be reopened if needed, but like to post this as reminder) untill i am able to detect this happens more.

Further investigation points to e107_admin/lancheck.php (line 308) should detect that lan is deprecated. (adding that lan_ back or presence of the file in different lang packs is not 'seen'  or displayed (did different testing).  
Maybe it is a different issue as i expect it should be noticed.  ?? If i am mistaking here, it can be closed or needs investigation.
( the pull request can
