### ISSUE TITLE
separate preference for caching css and js 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4271]
## Motivation
There is an issue with js caching,  it would be nice to caching only css files and let javascript untouched
![image](https://user-images.githubusercontent.com/5429548/100541396-064ff380-3244-11eb-9d6a-18dbd20d043b.png)

## Proposed Solution
Separate this pref into 2 undepended prefs

**Comment by CaMer0n** [comment]
@Jimmi08 What is the issue with JS caching? Is posted on github already?

**Comment by CaMer0n** [comment]
Closing as the JS issue has been resolved.
