### ISSUE TITLE
wrong javascript files caching

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4272]
## Bug Description
I have confirmed that this happens only with javascript caching,  header javascript is not loaded 

## How to Reproduce
My plugin defines js this way:

```
		e107::js('fallingholidays', '/js/animation-min.js', 'jquery');
		e107::js('fallingholidays', '/soundmanager2-nodebug-jsmin.js', 'jquery');
```

it is loaded in the header, not in the footer, which is correct. 

After caching ON, the only script in the header is
 _jquery.min.js_
and footer files:
- _jquery.once.min.js_
- _cached js file_

but inside this file are only footer javascript files...

**Comment by CaMer0n** [comment]
@Jimmi08 Nevermind, this is the issue. Thanks, ;-)

**Comment by Jimmi08** [comment]
@CaMer0n 
in plugins  e_header.php file.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 ! I'll try installing the plugin and see if that helps. Are you testing from the home page?

**Comment by CaMer0n** [comment]
@Jimmi08 I installed the plugin and did the same test as above.. crossing off (in red) each JS file loaded by the cache files. 
So I'm still unable to reproduce the issue you're having. 

![image](https://user-images.githubusercontent.com/2825679/100652170-5ccc3900-32fb-11eb-8f76-eed6098e4b1a.png)
