### ISSUE TITLE
Config file wrong creation

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#428]
Due to examining some causes discovered using file inspector (showing e107 files folder) took a look at config file also.

The latest files from svn > installed > config php creates FILES as files directory
CORE directory is NOT created in config ( at fileserver it is opposite > Core folder exist; Files folder not).

more http://e107.org/e107_plugins/forum/forum_viewtopic.php?247417.0

**Comment by CaMer0n** [comment]
They are optional, and only placed there during a fresh install so the person installing knows that they are additional options.
