### ISSUE TITLE
blogcalendar_menu - still uses db_Select() and db_fetch()

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4283]
## Bug Description
this plugin is part of the official release but it is outdated. SQL queries are not fixed here.

neither e_PAGETITLE nor PAGE_NAME is defined for archive.php 

I would ignore this, but this is part of the official release, so I just take notes here.

By the way, this code is enough for bootstrap 4:

```
$archive = "<div class='row'>";
for($i = 1; $i <= 12; $i++) 
{
	if (($req_year == $cur_year) && ($i == $cur_month)) 
	{
		$req_day = $cur_day;
	} 
	else 
	{
		$req_day = "";
	}
	$archive .= "<div class='col-lg-4 col-md-6 col-sm-12'> ".calendar($req_day, $i, $req_year, $day_links[$i], $pref['blogcal_ws'])."</div> ";
}
$archive .= "</div>";

$ns->tablerender(BLOGCAL_L2 ."&nbsp;$req_year", $archive);
```

**Comment by Jimmi08** [comment]
Else one problem...
there should be some carousel for the bootstrap theme, it didn't work with my theme, and using carousel class caused that only the last calendar was displayed.  Maybe using some core class f.e. ecarousel would be better and independent.

**Comment by CaMer0n** [comment]
Since there is no broken functionality, I'm going to mark this as an enhancement.
