### ISSUE TITLE
{---CAPTION---} display menu caption not page caption if menu is before page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4284]
## Bug Description

If you put menu before page itself (above ---) ,  {---CAPTION---} displays caption for this menu, not for page

Tested with forum and menu was used this way {MENU: path=...} 

**Priority:** low, just mentioned.  Fixed with theme shortcode and e_PAGETITLE or PAGENAME constants.

**Comment by CaMer0n** [comment]
This is the correct behavior if your menu is using the 'default' or 'main' style. 
Please confirm. @Jimmi08  Thanks.

**Comment by Jimmi08** [comment]
@Moc this should be added to documentation

`{---CAPTION---} will find the first caption rendered using style=default or main`

Thanks

**Comment by Jimmi08** [comment]
I forgot to close this

**Comment by Jimmi08** [comment]
@Moc  thank you.  I asked because you know...  I know enough and I still got confused. 

Wrong:
![image](https://files.gitter.im/5e62ad9dd73408ce4fdbde66/YlPH/image.png)

Wrong:
![image](https://files.gitter.im/5e62ad9dd73408ce4fdbde66/TkvH/image.png)

Correct:
![image](https://files.gitter.im/5e62ad9dd73408ce4fdbde66/O6lN/image.png)
