### ISSUE TITLE
Forum breadcrumbs on topic view with 3 forums

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4286]
## Bug Description
Breadcrumbs on forum view page (used {BREADCRUMB} in forum template) are wrong in some case

**normal case:**
parent forum
forum
topic
- breadcrumbs are correct. 
1. /forum
2. /forum#parent forum
3. /forum/forum-sef

**Special case** (nothing in admin stopped me to do this)
parent forum 
subforum
forum 
topic

1. /forum
2. /forum/parent-forum-sef - not #   
3.  /forum/parent-forum-sef  -   not subforum
4.  /forum/forum-sef

I don't know how to fix this.
Thanks

**Comment by Jimmi08** [comment]
This is fixed in 2.3.1

**Comment by Jimmi08** [comment]
It is still there.  I checked wrong page.

On view topic page with subforum, normal structure, just subforum:

![image](https://user-images.githubusercontent.com/5429548/158612627-bc6e9b86-957c-4881-aa67-364aeff9490b.png)

breadcrumbs for subforum are correct

but on topic itself:
![image](https://user-images.githubusercontent.com/5429548/158612915-c6c17503-3b93-4b7b-9c7e-532913a5a428.png)

```
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="/e107-2_3_1_git/" aria-label="Homepage"><i class="fas fa-home"></i> </a></li>
<li class="breadcrumb-item"><a href="/e107-2_3_1_git/forum">Forums</a></li>
<li class="breadcrumb-item"><a href="/e107-2_3_1_git/forum#your-main-category-forum">Your Main Category Forum</a></li>
<li class="breadcrumb-item"><a href="/e107-2_3_1_git/forum/your-main-category-forum/">Your second forum</a></li>
<li class="breadcrumb-item"><a href="/e107-2_3_1_git/forum/second-forum-subforum/">Second forum - subforum</a></li>
<li class="breadcrumb-item">test</li>
</ul>
```

**Comment by Jimmi08** [comment]
this is fix:

![image](https://user-images.githubusercontent.com/5429548/159288473-4a4eb11a-6768-46f4-a63e-fcdbd92182b4.png)

**Comment by Moc** [comment]
@Jimmi08 welcome to submit as PR :)

**Comment by Jimmi08** [comment]
It should solve this too:
https://github.com/e107inc/e107/issues/2565
