### ISSUE TITLE
user extended field - checkboxes and sql error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4287]
## Bug Description
Displaying SQL error because it is trying to work with this field as with DB fied

## How to Reproduce
Normal checkbox field

![image](https://user-images.githubusercontent.com/5429548/101605888-03eb5780-3a03-11eb-9808-1aee566615ae.png)

 
![image](https://user-images.githubusercontent.com/5429548/101609662-82e28f00-3a07-11eb-9435-cabcf70f9b63.png)

Reason for that error is this line:
if($sql->gen("DESCRIBE " . MPREFIX . "{$table_list}"))

`$table_list = ($_POST['table_db']) ? $_POST['table_db'] : $curVals[0];`

and $curVals for checkboxes are filled with checkboxes options.

**Comment by CaMer0n** [comment]
@Jimmi08 Please re-test thanks.

**Comment by Jimmi08** [comment]
@CaMer0n it is still there.

**Comment by Jimmi08** [comment]
Thanks
