### ISSUE TITLE
user extended field - checkboxes are not saved in usersettings 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4288]
## Bug Description
User extended field type checkboxes is not saved

## How to Reproduce
 They are displayed normally:
![image](https://user-images.githubusercontent.com/5429548/101609930-d654dd00-3a07-11eb-8a64-de48f369a92f.png)

$_POST is correct
![image](https://user-images.githubusercontent.com/5429548/101610043-fedcd700-3a07-11eb-852d-e64d7c6b950a.png)

But not saved correctly (other fields work)
Checked in DB too:

![image](https://user-images.githubusercontent.com/5429548/101610313-61ce6e00-3a08-11eb-87fd-5dbfc5f3ff8b.png)

**Comment by Jimmi08** [comment]
If this helps, they are removed after this:
`$eufVals = $ue->sanitizeAll($_POST['ue']);`

**Comment by CaMer0n** [comment]
@Jimmi08 Please try this and see if it helps: 

```
case EUF_CHECKBOX : //checkboxes
   $arr[$field] = e107::serialize($value, 'json'); 
   break;
```

**Comment by Jimmi08** [comment]
Added more debug:

```
if (isset($_POST['ue']))
			{
				$eufVals = $ue->sanitizeAll($_POST['ue']);
                e107::getMessage()->addDebug("<h4>Extended Data - sanitizeAll</h4>".print_a($eufVals,true));
                
				$eufVals = $ue->userExtendedValidateAll($eufVals, varset($_POST['hide'],TRUE));		// Validate the extended user fields
                e107::getMessage()->addDebug("<h4>Extended Data -userExtendedValidateAll</h4>".print_a($eufVals,true));
                
				$changedEUFData['data'] = validatorClass::findChanges($eufVals['data'], $udata,FALSE);
			}

			e107::getMessage()->addDebug("<h4>Extended Data - post validation</h4>".print_a($changedEUFData['data'],true));

```

Results:
After Extended Data - sanitizeAll
```
Array
(
    [user_birthday] => 1970-05-24
    [user_timezone] => America/Grenada
    [user_checkboxtest] => [
    "value1",
    "value2",
    "value3"
]
)
```

After userExtendedValidateAll
