### ISSUE TITLE
LAN_NEWS_23 problem (2 different values)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4290]
## Bug Description
News for gsitemap are defined:

```
			$import[] = array(
				'id'    => $row['category_id'],
				'table' => 'news_category',
				'name' => $row['category_name'],
				'url' => e107::getUrl()->create('news/list/category', $row, array('full' => 1)) , 
				'type' => LAN_NEWS_23
			);
```
and value:  `define("LAN_NEWS_23", "News Categories");`  in lan_news.php

But if you are on news admin page, values for this addons are changed because this:

`define("LAN_NEWS_23", "Choose an image or video for this news item");`
in lan_newspost.php

and import settings have then the different value for 'type' 

Maybe the problem is in using the wrong LAN, for news is used  ADLAN_0 from /admin/English.php  

Thanks

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 . We should use define("LAN_NEWS_23", "News Categories"); and load the frontend lan_news.php into the admin area.

**Comment by tgtje** [comment]
Took a peek on the above.  Maybe in time something was changed as a similar phrase existed for image use : ( NWSLAN_69", "Upload an image or file for use in the news item). (path is admin/lan_newspost php)
It is present as LAN, but _seems not to be used_ 
where ( LAN_ NEWS_ 23", "Choose an image or video for this news item) (path is English/lan_news php)

**Comment by tgtje** [comment]
@Jimmi08 to overcome issue depth (any result from https://github.com/e107inc/e107/commit/cc5fbe87ef9586f4ccefe583dd4aec790b025926#diff-e47532abc9efcd30bb89ef677e81c17e9095aa341afeb8dd41dc76bd46539f7e ) on this?

**Comment by Jimmi08** [comment]
@tgtje I am not able to test it anymore...  with the core gsitemap solution I don't need this

**Comment by tgtje** [comment]
@Jimmi08 could only test if i see anything related : no  So maybe close?
