### ISSUE TITLE
Question: Plugins - Admin Config width ignored

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4294]
## Bug Description
Width used in admin_config.php for plugins is being ignored - Set width from 5% to 15% does nothing, on anything (dropbox, text bot, etc...)

![Annotation 2020-12-20 140703](https://user-images.githubusercontent.com/5818022/102723373-02584400-42cd-11eb-844d-569ad6bbac7a.png)

`
			'game_id'                 => array (  'title' => LAN_eWL_ADMIN_LADDER_GAMES,  'type' => 'dropdown', 'tab'=>0, 'data' => 'int',  'width' => '15%',  'help' => LAN_eWL_ADMIN_LADDER_TT_GAMES,  'readParms' =>  array (),  'writeParms' =>  array (),  'class' => 'left',  'thclass' => 'left',  'filter' => false,  'batch' => false,),
`

![Annotation 2020-12-20 1407103](https://user-images.githubusercontent.com/5818022/102723404-44818580-42cd-11eb-81bb-484c94e4b9c4.png)

**Comment by CaMer0n** [comment]
```width``` determines the width of the column in list mode. 
To set the width of a form element use ```writeParms('size'=>"(value)")```

**Comment by LaocheXe** [comment]
I tried that, but nothing changed, even clear cache on website, and browser. Looks like admin css isn't being overridden - guess a simple solution is to add my own css in the plugin, and call for it in admin_config.

**Comment by CaMer0n** [comment]
@LaocheXe What 'size' values are you using?

**Comment by Moc** [comment]
@LaocheXe  Any feedback?

**Comment by LaocheXe** [comment]
My work around was to make admin.css, call for the admin,css in admin_config.php, and inside the admin.css is:

table input.form-control, table textarea.form-control,  table select.form-control {
    width: 225px;
}

-----

The write parameter that I tried looks like this
'writeParms' =>  array ('size'=>"(15%)")

which didn't work

**Comment by Moc** [comment]
did you try `'writeParms' => array ('size'=>"15%")?

**Comment by LaocheXe** [comment]
@Moc Yes

**Comment by Moc** [comment]
> @Moc Yes

And that didn't work, I assume?

**Comment by LaocheXe** [comment]
Correcy

**Comment by Jimmi08** [comment]
But size is either limited text value like xxlarge,  or integer f.e. 20  20% will not work.

from form_handler:
for text field:
Text-Field  mini, small, medium, large, xlarge, xxlarge 
from documentation:
large, xlarge, xxlarge, block-level

for number, it is only number value - 
bbarea has values: tiny, small, medium, large

I use only xxlarge or block-level, but I can confirm they work with 2.3.1
![image](https://user-images.githubusercontent.com/5429548/147253878-648641da-22f2-430c-97d7-57ef21ffb833.png)
![image](https://user-images.githubusercontent.com/5429548/147253925-d588d55f-3617-47ed-868f-14406bc6d064.png)

**Comment by Moc** [comment]
@LaocheXe Does Jimmi's info help? I'll add it to the documentation.

**Comment by LaocheXe** [comment]
@Jimmi08 I changed  'writeParms' => array ('size'=>"15%") to  'writeParms' => array ('size'=>"xlarge")   is that the correct way? Cause it's not working on my end.

**Comment by LaocheXe** [comment]
I even tried 'writeParms' => 'size=xxlarge'   <-it's how the forum has it, give or take the

**Comment by LaocheXe** [comment]
crap, didn't mean to do that

**Comment by Jimmi08** [comment]
@LaocheXe Which plugin is it? Do I have access to it?   And what Admin UI exactly?

**Comment by LaocheXe** [comment]
eWL Ladders my league plugin I'm working on. The admin ui would be default, used the plugin builder for it. As for access, I could give you access if needed.

**Comment by Jimmi08** [comment]
without seeing your code (all class) is not possible to say what you are doing wrong.  Those arrays can be tricky sometimes. When I have troubles with Admin UI, it is mostly because of my own mistake.

**Comment by Jimmi08** [comment]
Fixed
![image](https://user-images.githubusercontent.com/5429548/147505473-386e3d1a-96ea-4bfc-9d9e-93150b811149.png)

- with dropdown always use writeParms  as an array and both. **size** and **optArray** keys have to be used, not directly writeParms.  From commit, it is clearer, I hope.

**Comment by Moc** [comment]
Just for future reference, can you show us an extract of the code (or link to the commit?). This way, the documentation can include the clearest instructions.

**Comment by Jimmi08** [comment]
It is his private repo. I hope this helps.

![image](https://user-images.githubusercontent.com/5429548/147505996-9826e232-8128-4d89-8db9-7c244ff72e16.png)


![image](https://user-images.githubusercontent.com/5429548/147505916-fe75e6d0-c405-4b1a-a62b-8633fd43bc05.png)
