### ISSUE TITLE
Page load times very slow with EasyPHP

### ISSUE THREAD

**Issue by arel3** [e107inc/e107#4298]
## Bug Description
Title says it all. Is there a fix so it loads fast? 
I'm trying to run e107 locally to create my own theme. 
Another issue is that even if I wait through the torturous page load times I'm experiencing any edits I make to the current theme don't change anything. Perhaps that's a subject for another question I need to research first before creating another 'bug' thread. 

## How to Reproduce
1. Run EasyPHP and install e107, run the install process. 
2. Click on 'anything, any link, even just refresh the page. Load times are horrible (for me, I'm hoping it's not my network or there's a fix if it is).'

## Expected Behavior
Page load times are normal. No errors anywhere. 

## Server Information
```
Win 10 Home 64bit
Latest Version of PHP (installed fresh a few days ago).
Curl Enabled. 
```

### PHP Operating System

```
C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x201223082336\libssh2.dll
```

### PHP Version
`PHP Version 7.1.3`

### PHP Modules

```
apache2handler
bcmath
bz2
calendar
Core
ctype
date
dom
exif
filter
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib
```

### Client Information
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284`

## Additional Information
I've tried Xammp to see if that can do it any better and: [Nope!](https://github.com/e107inc/e107/issues/4297)

**Comment by Moc** [comment]
As developers we use local development environments all the time and we are currently not experiencing such issues. 

Please check other PHP packages and check their performance as I strongly doubt it is caused by e107. Instead I think it is a configuration issue on your local environment.

**Comment by CaMer0n** [comment]
@arel3 Check out https://laragon.org/ . It's what we use for local development. I remember EasyPHP used to be slow when I used it in the past.

**Comment by arel3** [comment]
> As developers we use local development environments all the time and we are currently not experiencing such issues.
> 
> Please check other PHP packages and check their performance as I strongly doubt it is caused by e107. Instead I think it is a configuration issue on your local environment.

I'm working on 30 other projects that require what EasyPHP does. None of the others are doing this. It **is** just e107. 
My LAN is a stable and solid, wired,  speed of 10gb so it's not a network issue either.  

I was hoping there was a fix such as enabling or disabling one of EasyPHP's process options or something. 

The report that e107 lags when links are clicked with EasyPHP is reported. 
It would be nice if the dev's looked in to it.  

Thank you!

**Comment by CaMer0n** [comment]
@arel3 Is this still an issue?

**Comment by arel3** [comment]
> @arel3 Is this still an issue?

@CaMer0n Yes, it is.
