### ISSUE TITLE
PHP8 fatal errors

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4299]
@arel3: This is indeed a bug:
> ```
> Fatal error: Uncaught Error: Undefined constant "MENLAN_11" in D:\Xampp\htdocs\e2\e107_handlers\menumanager_class.php:572
> Stack trace:
>  #0 D:\Xampp\htdocs\e2\e107_handlers\menumanager_class.php(370): e_menuManager->menuScanMenus()
>  #1 D:\Xampp\htdocs\e2\e107_handlers\menumanager_class.php(122): e_menuManager->menuModify()
>  #2 D:\Xampp\htdocs\e2\e107_handlers\theme_handler.php(2891): e_menuManager->__construct()
>  #3 D:\Xampp\htdocs\e2\e107_handlers\theme_handler.php(2599): themeHandler->renderPresets('jumbotron_sideb...')
>  #4 D:\Xampp\htdocs\e2\e107_admin\theme.php(645): themeHandler->renderTheme(1, Array)
>  #5 D:\Xampp\htdocs\e2\e107_admin\theme.php(338): theme_admin_ui->renderThemeConfig('front')
>  #6 D:\Xampp\htdocs\e2\e107_handlers\admin_ui.php(2314): theme_admin_ui->MainPage()
>  #7 D:\Xampp\htdocs\e2\e107_handlers\admin_ui.php(1360): e_admin_controller->dispatchPage()
>  #8 D:\Xampp\htdocs\e2\e107_admin\theme.php(1742): e_admin_dispatcher->runPage()
>  #9 {main} thrown in D:\Xampp\htdocs\e2\e107_handlers\menumanager_class.php on line 572
> ```
> 
> More errors. Is the development for php 8.0 not complete yet?

e107 historically used constants extensively by having them everywhere, but with PHP 8 changing how it behaves towards undefined constants, fatal errors now show up if there are any unaccounted constants.  We are in the process of finding undefined constants and resolving them, so **no, the development for PHP 8.0 is not complete yet**.

> Xampp doesn't have telenet access by default @Deltik so getting it that way isn't possible.
> …
> Glad I didn't go through the effort of making ssh work locally.

I don't understand how Telnet and SSH relate to installing e107.  According to your stack trace above, `git clone https://github.com/e107inc/e107.git D:\Xampp\htdocs\e2` would have put e107 into the path you wanted.

_Originally posted by @Deltik in https://github.com/e107inc/e107/issues/4297#issuecomment-750942033_

**Comment by CaMer0n** [comment]
One of many. Fixes coming up.

**Comment by CaMer0n** [comment]
From @RCEE007

> E107 user registration gives this error: Error
07 - Display name - Value not allowed: TestTest , what could cause this ? Latest Git 2.3.1 PHP 8.0

Fix coming up.

**Comment by Jimmi08** [comment]
`PHP Fatal error:  Uncaught Error: Undefined constant "LAN_MEMBERS_0" in ***templates\\membersonly_template.php:30\nStack trace:\n#0 C:\\xampp8\\htdocs\\e107-cayman\\e107_handlers\\e107_class.php(3566): include_once()\n#1 C:\\xampp8\\htdocs\\e107-cayman\\e107_handlers\\e107_class.php(3262): e107::_getTemplate('membersonly', 'signup', 'core/e107/templ...', './e107_themes/c...', false)\n#2 C:\\xampp8\\htdocs\\e107-cayman\\signup.php(139): e107::getCoreTemplate('membersonly', 'signup')\n#3 {main}\n  thrown in ***templates\\membersonly_template.php on line 30, referer: http://localhost/e107-cayman/`

**Comment by Jimmi08** [comment]
`PHP Fatal error:  Uncaught Error: Undefined constant "LAN_PLUGIN_NEWS_NAME" in ***\\e107_plugins\\news\\news.php:1771\nStack trace:\n#0 ***\\e107_plugins\\news\\news.php(163): news_front->renderDefaultTemplate()\n#1 ***\\e107_plugins\\news\\news.php(74): news_front->detect()\n#2 ***\\e107_plugins\\news\\news.php(1890): news_front->__construct()\n#3 ***\\news.php(23): require_once('C:\\\\xampp8\\\\htdoc...')\n#4 ***\\index.php(107): include('C:\\\\xampp8\\\\htdoc...')\n#5 {main}\n  thrown in ***\\e107_plugins\\news\\news.php on line 1771, referer: ***`

**Comment by CaMer0n** [comment]
@Jimmi08 Please see last commit and rescan your plugins directory.

**Comment by Jimmi08** [comment]
@CaMer0n News fixed, signup still fatal error

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you! Keep 'em coming. We need to find all of these **undefined constant** bugs.  :+1:

**Comment by Jimmi08** [comment]
Not sure if this is PHP 8 related, but it didn't happen before.

```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, 
null given in C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php:3459\nStack trace:\n#0 
C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php(4047): pluginBuilder->createXml(Array)\n#1 
C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php(2512): pluginBuilder->step4()\n#2 
C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php(420): pluginBuilder->run()\n#3 
C:\\xampp8\\htdocs\\***\\e107_handlers\\admin_ui.php(2331): plugin_ui->buildPage()\n#4 
C:\\xampp8\\htdocs\\***\\e107_handlers\\admin_ui.php(1360): e_admin_controller->dispatchPage()\n#5 
C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php(2320): e_admin_dispatcher->runPage()\n#6 {main}\n  thrown in 
C:\\xampp8\\htdocs\\***\\e107_admin\\plugin.php on line 3459, 
referer: http://localhost/***/e107_admin/plugin.php?build=&action=build&mode=create&newplugin=hpslovnik&createFiles=1&step=3
```

**Comment by CaMer0n** [comment]
@Jimmi08 Please try again with after updating.

**Comment by Jimmi08** [comment]
> @Jimmi08 Please try again with after updating.

It works, thanks

**Comment by Jimmi08** [comment]
When trying to generate links for pages (batch option)

`Fatal error: Uncaught Error: Undefined constant "LAN_SITELINK" in ***e107_handlers\admin_ui.php:5551 Stack trace: #0 ***e107_handlers\admin_ui.php(5483): e_admin_ui->_add2nav(Array) #1 ***e107_handlers\admin_ui.php(3763): e_admin_ui->handleListUrlBatch(Array, NULL) #2 ***e107_handlers\admin_ui.php(5270): e_admin_controller_ui->_handleListBatch('url') #3 ***e107_handlers\admin_ui.php(2229): e_admin_ui->ListBatchTrigger('url') #4 ***e107_handlers\admin_ui.php(1333): e_admin_controller->dispatchObserver() #5 ***e107_handlers\admin_ui.php(1105): e_admin_dispatcher->runObservers() #6 ***e107_admin\cpage.php(1163): e_admin_dispatcher->__construct() #7 {main} thrown in ***e107_handlers\admin_ui.php on line 5551`

**Comment by Jimmi08** [comment]
`Fatal error: Uncaught Error: Undefined constant "LAN_PM" in C:\xampp8\htdocs\***\e107_core\shortcodes\batch\admin_shortcodes.php:901 Stack trace: #0 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(1130): admin_shortcodes->sc_admin_pm(Array, '') #1 [internal function]: e_parse_shortcode->doCode(Array) #2 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(996): preg_replace_callback('#\\{([A-Z][^\\x02...', Array, '\t\t\t\t{ADMIN_PM}') #3 C:\xampp8\htdocs\***\e107_handlers\e_parse_class.php(823): e_parse_shortcode->parseCodes('\t\t\t\t{ADMIN_PM}', true, Object(admin_shortcodes), NULL) #4 C:\xampp8\htdocs\***\e107_handlers\e107_class.php(373): e_parse->parseTemplate('\t\t\t\t{ADMIN_PM}', true, Object(admin_shortcodes)) #5 C:\xampp8\htdocs\***\e107_admin\header.php(591): e107::renderLayout('\n<div id="uiMod...', Array) #6 C:\xampp8\htdocs\***\e107_admin\footer.php(34): require_once('C:\\xampp8\\htdoc...') #7 C:\xampp8\htdocs\***\e107_admin\e107_update.php(32): require_once('C:\\xampp8\\htdoc...') #8 {main} thrown in C:\xampp8\htdocs\***\e107_core\shortcodes\batch\admin_shortcodes.php on line 901`

This is weird. The site worked before. PM is not installed (checked installed plugin pref). The theme doesn't use PM related prefs.

**Comment by CaMer0n** [comment]
@Jimmi08 This "should" fix it.

**Comment by Jimmi08** [comment]
With not installed PM plugin (installation fixed this), latest sync:  

`Fatal error: Uncaught Error: Call to a member function sc_pm_nav() on null in C:\xampp8\htdocs\***\e107_plugins\signin\signin_shortcodes.php:243 Stack trace: #0 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(1130): plugin_signin_signin_shortcodes->sc_signin_pm_nav(Array, '') #1 [internal function]: e_parse_shortcode->doCode(Array) #2 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(996): preg_replace_callback('#\\{([A-Z][^\\x02...', Array, '\n\n\t\t<ul class="...') #3 C:\xampp8\htdocs\***\e107_handlers\e_parse_class.php(823): e_parse_shortcode->parseCodes('\n\n\t\t<ul class="...', true, Object(plugin_signin_signin_shortcodes), NULL) #4 C:\xampp8\htdocs\***\e107_plugins\signin\e_shortcode.php(70): e_parse->parseTemplate('\n\n\t\t<ul class="...', true, Object(plugin_signin_signin_shortcodes)) #5 C:\xampp8\htdocs\***\e107_plugins\signin\e_shortcode.php(35): signin_shortcodes->signOut(Array) #6 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(275): signin_shortcodes->sc_signin(Array, '') #7 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(1215): e_parse_shortcode->callScFuncA('signin_shortcod...', 'sc_signin', Array) #8 [internal function]: e_parse_shortcode->doCode(Array) #9 C:\xampp8\htdocs\***\e107_handlers\shortcode_handler.php(996): preg_replace_callback('#\\{([A-Z][^\\x02...', Array, '\t\t\t\t{SIGNIN}\r') #10 C:\xampp8\htdocs\***\e107_handlers\e_parse_class.php(823): e_parse_shortcode->parseCodes('\t\t\t\t{SIGNIN}\r', true, NULL, NULL) #11 C:\xampp8\htdocs\***\e107_handlers\e107_class.php(373): e_parse->parseTemplate('\t\t\t\t{SIGNIN}\r', true, Object(theme_shortcodes)) #12 C:\xampp8\htdocs\***\e107_core\templates\header_default.php(791): e107::renderLayout('<body id="page-...', Array) #13 C:\xampp8\htdocs\***\index.php(189): include_once('C:\\xampp8\\htdoc...') #14 {main} thrown in C:\xampp8\htdocs\***\e107_plugins\signin\signin_shortcodes.php on line 243`

**Comment by CaMer0n** [comment]
@Jimmi08 Please check your `plug_installed` pref value. Something is off. 

	function sc_signin_pm_nav($parm=null)
	{
		if(!e107::isInstalled('pm') )
		{
			return null;
		}

		$sc = e107::getScBatch('pm', true);

		return $sc->sc_pm_nav($parm);;


	}

**Comment by Jimmi08** [comment]
> @Jimmi08 Please check your `plug_installed` pref value. Something is off.
 
I checked it with that first problem with LAN.  It was fixed after your commit, this was the next problem. This one was fixed by installing the plugin. After the uninstallation, it works normally now. 
I know it is weird... I just wanted to take note. Install plugin was the first reaction and now I am not able to simulate it back.

**Comment by CaMer0n** [comment]
@Jimmi08 Okay thank you. Please let me know if it happens again.

**Comment by Jimmi08** [comment]
`Fatal error: Uncaught Error: Undefined constant "USERLV" in ***\e107_plugins\forum\forum_viewtopic.php:368 `

**Comment by Jimmi08** [comment]
`Fatal error: Uncaught Error: Undefined constant "post_thread" in ***\e107_plugins\forum\e_event.php:52 Stack trace: #0 ***\e107_handlers\event_class.php(215): forum_event->forum_eventnewpost(Array, 'user_forum_post...') #1 ***\e107_plugins\forum\forum_class.php(874): e107_event->trigger('user_forum_post...', Array) #2 ***\e107_plugins\forum\forum_post.php(1216): e107forum->postAdd(Array) #3 ***\e107_plugins\forum\forum_post.php(207): forum_post_handler->insertPost() #4 ***\e107_plugins\forum\forum_post.php(90): forum_post_handler->processPosted() #5 ***\e107_plugins\forum\forum_post.php(1757): forum_post_handler->__construct() #6 ***\index.php(69): include_once('***') #7 {main} thrown in ***\e107_plugins\forum\e_event.php on line 52`

**Comment by Jimmi08** [comment]
When quoting topic on the forum

Fa`tal error: Uncaught Error: Undefined constant "LAN_WROTE" in ***\e107_handlers\bbcode_handler.php(392) : eval()'d code:13 Stack trace: #0 ***\e107_handlers\bbcode_handler.php(392): eval() #1 ***\e107_handlers\bbcode_handler.php(202): e_bbcode->proc_bbcode('quote', '', 'Lorem Ipsum is ...', '', '', '[quote]Lorem Ip...') #2 ***\e107_handlers\e_parse_class.php(5338): e_bbcode->parseBBCodes('[quote]Lorem Ip...', '', 'wysiwyg') #3 ***\e107_handlers\e_parse_class.php(1623): e_parse->processModifiers(Array, '[quote]Lorem Ip...', true, true, 'WYSIWYG', '') #4 ***\e107_plugins\tinymce4\plugins\e107\parser.php(136): e_parse->toHTML('[quote]Lorem Ip...', true, 'WYSIWYG') #5 ***\e107_plugins\tinymce4\plugins\e107\parser.php(87): e107TinyMceParser->toHTML('[quote]Lorem Ip...') #6 ***\e107_plugins\tinymce4\plugins\e107\parser.php(309): e107TinyMceParser->__construct() #7 {main} thrown in ***\e107_handlers\bbcode_handler.php(392) : eval()'d code on line 13`

**Comment by Jimmi08** [comment]
It could be related:
https://github.com/e107inc/e107/issues/4405

**Comment by Deltik** [comment]
@Jimmi08: Are you able to use the forum on PHP 8 now that I've wrapped some undefined constants there (https://github.com/e107inc/e107/commit/ccf0f037aa70c00c5dcad050c527848d9b28abbe)?

**Comment by Jimmi08** [comment]
@Deltik yes, no fatal errors

**Comment by Jimmi08** [comment]
Again weird stuff.  
With the featurebox plugin not installed (I went to Pages admin). Then installed the plugin, the error was gone. 
Then uninstalled the plugin again, but the error is not there anymore.  I am just taking notes if this happens to somebody else. 
Site after sync, imported demo data (tables) from the live demo. 

`Fatal error: Uncaught Error: Undefined constant "LAN_PLUGIN_FEATUREBOX_BATCH" in C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php:7776 Stack trace: #0 C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php(7346): e_admin_form_ui->renderBatch(Array, Array) #1 C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php(6359): e_admin_form_ui->getList() #2 C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php(2331): e_admin_ui->ListPage() #3 C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php(1360): e_admin_controller->dispatchPage() #4 C:\xampp8.0\htdocs\e107-cayman\e107_admin\cpage.php(1167): e_admin_dispatcher->runPage() #5 {main} thrown in C:\xampp8.0\htdocs\e107-cayman\e107_handlers\admin_ui.php on line 7776`

**Comment by Jimmi08** [comment]
@Deltik 
It happens only for not logged in user (as main admin I didn't see it before)

`Fatal error: Uncaught Error: Undefined constant "USERLV" in C:\xampp8.0\htdocs\e107-rideblue2\e107_plugins\forum\forum_viewtopic.php:368 Stack trace: #0 C:\xampp8.0\htdocs\e107-rideblue2\index.php(69): include_once() #1 {main} thrown in C:\xampp8.0\htdocs\e107-rideblue2\e107_plugins\forum\forum_viewtopic.php on line 368`

**Comment by Deltik** [comment]
Okay, @Jimmi08, I [wrapped more of those constants](https://github.com/e107inc/e107/commit/7a04260b5f5f9e3a559a547141b61a6e50a46bf0).

**Comment by Jimmi08** [comment]
> Okay, @Jimmi08, I [wrapped more of those constants](https://github.com/e107inc/e107/commit/7a04260b5f5f9e3a559a547141b61a6e50a46bf0).

Thanks, no issues for now.

**Comment by Jimmi08** [comment]
Trying to update 0.7.25 (or maybe older) directly to 2.3.1 git on php8. The result after a click on the first update button. 
Not important for me (I commented that line), it is just some report. 

`
Fatal error: Uncaught Error: Undefined constant "LAN_UPDATE_31" in ***e107_admin\update_routines.php:1028 Stack trace: #0 ***e107_admin\update_routines.php(186): update_706_to_800('do') #1 ***e107_admin\update_routines.php(150): e107Update->updateCore('706_to_800') #2 ***e107_admin\e107_update.php(28): e107Update->__construct(Array) #3 {main} thrown in ***e107_admin\update_routines.php on line 1028`

**Comment by Jimmi08** [comment]
Next one - editing old content

`Fatal error: Uncaught Error: Undefined constant "CORE_LAN18" in ***\e107_core\bbcodes\bb_img.php:282 Stack trace: #0 ***\e107_handlers\bbcode_handler.php(1047): bb_img->toHTML('https://www.com...', ' width=194&heig...') #1 ***\e107_handlers\bbcode_handler.php(382): e_bb_base->bbPreDisplay('https://www.com...', ' width=194&heig...') #2 ***\e107_handlers\bbcode_handler.php(202): e_bbcode->proc_bbcode('img', ' width=194&heig...', 'https://www.com...', '', '', '[img width=194&...') #3 ***\e107_plugins\tinymce4\plugins\e107\parser.php(143): e_bbcode->parseBBCodes('<ul>\n<li>Everyt...') #4 ***\e107_plugins\tinymce4\plugins\e107\parser.php(87): e107TinyMceParser->toHTML('<ul>\n<li>Everyt...') #5 ***\e107_plugins\tinymce4\plugins\e107\parser.php(309): e107TinyMceParser->__construct() #6 {main} thrown in ***\e107_core\bbcodes\bb_img.php on line 282`

**Comment by Jimmi08** [comment]
> @Jimmi08 Okay thank you. Please let me know if it happens again.

It happened again.  

PM plugin was listed in plug_installed prefs, but it wasn't listed between uninstalled plugins. 
`  'pm' => '3.0',`

When this happens...

I have the localhost copy of the site, it can be different, mostly used for testing. Before the real update, I export the database from live site (via hosting, not via e107) a then I import it to the localhost version (create a new one and change the config file). So the database is always actual. Then I run the update on localhost.  
I have set $E107_CONFIG['site_path']  to have the same system and media folders names.
I noticed now that plug_installed is different on localhost, that plugin pm shouldn't be installed at all (it probably was on the local version before changing the database). 
I cleared the cache. 
I run plugins scan. 
plug_installed stayed wrong (outdated).

**Comment by Jimmi08** [comment]
**Forum** -  adding topic fails if poll plugin is installed

`Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, string given in C:\xampp8.0\htdocs\***\e107_plugins\poll\poll_class.php:750 Stack trace: #0 C:\xampp8.0\htdocs\***\e107_plugins\forum\shortcodes\batch\post_shortcodes.php(418): poll->renderPollForm('forum') #1 C:\xampp8.0\htdocs\***\e107_handlers\shortcode_handler.php(1130): plugin_forum_post_shortcodes->sc_forum_post_poll(Array, '') #2 [internal function]: e_parse_shortcode->doCode(Array) #3 C:\xampp8.0\htdocs\***\e107_handlers\shortcode_handler.php(996): preg_replace_callback('#\\{([A-Z][^\\x02...', Array, '\n\t\t\t<div style=...') #4 C:\xampp8.0\htdocs\***\e107_handlers\e_parse_class.php(822): e_parse_shortcode->parseCodes('\n\t\t\t<div style=...', true, NULL, NULL) #5 C:\xampp8.0\htdocs\***\e107_plugins\forum\forum_post.php(903): e_parse->parseTemplate('\n\t\t\t<div style=...', true, Object(plugin_forum_post_shortcodes)) #6 C:\xampp8.0\htdocs\***\e107_plugins\forum\forum_post.php(109): forum_post_handler->renderForm() #7 C:\xampp8.0\htdocs\***\e107_plugins\forum\forum_post.php(1757): forum_post_handler->__construct() #8 C:\xampp8.0\htdocs\***\index.php(69): include_once('C:\\xampp8.0\\htd...') #9 {main} thrown in C:\xampp8.0\htdocs\***\e107_plugins\poll\poll_class.php on line 750`

Adding new poll in admin area fails too:
`Fatal error: Uncaught Error: Attempt to assign property "pollType" on null in C:\xampp8.0\htdocs\***\e107_handlers\shortcode_handler.php:1841 Stack trace: #0 C:\xampp8.0\htdocs\***\e107_handlers\shortcode_handler.php(1928): e_shortcode->setScVar('pollType', 'preview') #1 C:\xampp8.0\htdocs\***\e107_plugins\poll\poll_class.php(344): e_shortcode->__set('pollType', 'preview') #2 C:\xampp8.0\htdocs\***\e107_plugins\poll\admin_config.php(73): poll->render_poll(Array, 'preview') #3 {main} thrown in C:\xampp8.0\htdocs\***\e107_handlers\shortcode_handler.php on line 1841`
