### ISSUE TITLE
Bug: toHTML displays [html][/html] while using TinyMCE/bbarea

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4301]
I've notice last year when users posted news onto a site, it would show [html] at the top, and [/html] at the bottom. I would have to go into the database, and remove that from the db.

Now I notice it with a plugin I am working on - using bbarea in the admin_config.php - with TinyMC enabled - Notice on the front page that it shows [html] - and [/html], I'm using $tp = e107::getParser(); $tp->toHTML($rule['description']); - shows the description, with [html] tags - I think it might be TinyMCE saving the tags to the dd as it should, but parser to html still showing it as it is.

Using current version from Git at this moment

![Annotation 2020-12-26 213214](https://user-images.githubusercontent.com/5818022/103163281-dacc1480-47c1-11eb-8570-5d3f4b7ecc88.png)

**Comment by Jimmi08** [comment]
I think, but I am sure:

You use bbarea in admin but on frontend, you are displaying it like text field.

`[html][/html] ` - it means that HTML tags are inside (it is always with tinymce there)

it should be something like:
`e107::getParser()->toHTML(your field, true, 'DESCRIPTION');`

```
	 * @param string $text
	 * @param boolean $parseBB [optional]
	 * @param string $modifiers [optional] TITLE|SUMMARY|DESCRIPTION|BODY|RAW|LINKTEXT etc.
	 *		Comma-separated list, no spaces allowed
	 *		first modifier must be a CONTEXT modifier, in UPPER CASE.
	 *		subsequent modifiers are lower case - see $this->e_Modifiers for possible values
```
Try to add that second parameter as true, [html] is in fact BBCode, so it should be true.

**Comment by LaocheXe** [comment]
That Works, should add this to developer documentation.

**Comment by Moc** [comment]
> That Works, should add this to developer documentation.

It's on the list for the new developer manual that I am working on.
