### ISSUE TITLE
Some plugins compatibility version

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4309]
Trackback and download plugins still show e107 v1.0 compatibility in plugins management so need to get edited to e107 v2.0

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/103271223-eda93980-49b9-11eb-986d-dd05bb3fb34e.png)

![image](https://user-images.githubusercontent.com/5429548/103271280-0fa2bc00-49ba-11eb-8e43-d8fbd792026d.png)

**Comment by realmontazeri** [comment]
Yes, the issue is fixed in download plugin but for the trackback is still exist (e107_plugins/trackback/plugin.xml)

**Comment by Jimmi08** [comment]
> Yes, the issue is fixed in download plugin but for the trackback is still exist (e107_plugins/trackback/plugin.xml)

I just confirmed your issue with screenshots. I don't argue with you.  :)

**Comment by realmontazeri** [comment]
> > Yes, the issue is fixed in download plugin but for the trackback is still exist (e107_plugins/trackback/plugin.xml)
> 
> I just confirmed your issue with screenshots. I don't argue with you. :)

Your screenshot confirmed that for download plugin, please check your screenshot again because it is still shows compatibility version 1.0

**Comment by realmontazeri** [comment]
Trackback plugin was removed from repository so we are done with this issue.
