### ISSUE TITLE
Questions about language

### ISSUE THREAD

**Issue by Kanonimpresor** [e107inc/e107#431]
I put this issue at the request of Nlstart...

Hi guys, 

I need help with language e107 installed in English, after I loaded my other languages ​​(Portuguese and Spanish) but now I do not want the English language. 

OK 

Before you remove the English, had created tables (Portuguese and Spanish) and create some custom pages. 

Now, I decided to remove the English folder to remove the flag of multi-language. 

In admin -> language, select a default language ok, I have only two languages, with their respective tables. 

The default language (no need tables). but still have tables that were created before modifying the language. 

This new default language is using the generic tables of e107, and now has no content, the content is in their old tables. 

Questions: 

I have to transfer the content created for generic tables of e107? 
after ... 
I have to delete the old tables of the language which is now by default? 

I know I can make these changes, but if tomorrow I decide to put the English, would have to transfer the contents of that language to their respective tables? 

The default language, would have to use their tables, and no, the e107 core. 

PS: How to block the English flag, and left everything as is. easy ....!

Thanks!

**Comment by Moc** [comment]
Closing this issue as I think it is no longer applicable. Please re-open if neccesary. 

I suggest looking into the multilan plugin: https://github.com/e107inc/multilan
