### ISSUE TITLE
Bootstrap3 modern business layout is not fully mobile responsive

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4313]
Modern Business: Home page carousel with fixed custom-menus has issue with featurebox slider mobile responsiveness, It shows large empty space between slider and slide title.

**Comment by realmontazeri** [comment]
Here is the situation on v2.3.1 git
![Screenshot](https://user-images.githubusercontent.com/10089685/103335439-2a446600-4a8a-11eb-8996-af27a3030c3c.png)

**Comment by CaMer0n** [comment]
@realmontazeri Does it render better for you, using the 'hero' plugin?

**Comment by realmontazeri** [comment]
> @realmontazeri Does it render better for you, using the 'hero' plugin?

Yes, hero slider is fully responsive without any issue.

**Comment by CaMer0n** [comment]
Okay, thank you!

**Comment by realmontazeri** [comment]
This issue has been solved during recent changes.
