### ISSUE TITLE
Combining signin and signup option

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4315]
It is nice to have an option to combine signin and signup links so It gets less space on top of the website.

**Comment by Jimmi08** [comment]
This is theme stuff.  

You can:
-  customize bootstrap_nav shortcode and move the signup link to the modal window
-  or can remove the top modal login at all and put link for login itself where there is already a signup link.    
- or you can use sitelinks/navigation and add there those links manually (f.e. like dropdown to save place)

I just hope you copied the bootstrap3 theme under your own name. 
And every time write what e107 you are using. Official 2.3.0 or 2.3.1 git version.
