### ISSUE TITLE
Links page plugin is not functional

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4316]
Clicking on links categories shows the following error:

Fatal error: Uncaught Error: Object of class linkclass could not be converted to string in /home/.../plugins/links_page/link_class.php:285 Stack trace: #0 /home/.../plugins/links_page/links.php(561): linkclass->getOrder() #1 /home/.../plugins/links_page/links.php(176): displayCategoryLinks('2') #2 /home/.../index.php(69): include_once('/home/clients/9...') #3 {main} thrown in /home/.../plugins/links_page/link_class.php on line 285

Also the link category icon is not appearing.

**Comment by Moc** [comment]
Which PHP version are you using?

**Comment by realmontazeri** [comment]
> Which PHP version are you using?

php v7.4 - e107 v2.3.1 git

**Comment by Jimmi08** [comment]
@Moc I am not aware that the LinksPage plugin is available for the 2.x version.   It was removed from e107.org too. 

@realmontazeri from where and what version of LinksPage plugin you are using?

**Comment by realmontazeri** [comment]
As I see this plugin is removed from e107/tree/master/e107_plugins so It seems that this plugin was remained from the older versions of cms.

**Comment by realmontazeri** [comment]
> @Moc I am not aware that the LinksPage plugin is available for the 2.x version. It was removed from e107.org too.
> 
> @realmontazeri from where and what version of LinksPage plugin you are using?

![Screenshot](https://user-images.githubusercontent.com/10089685/103272342-dbd39080-49d1-11eb-8e24-d09b2e4b2de4.png)

**Comment by Jimmi08** [comment]
> > @realmontazeri from where and what version of LinksPage plugin you are using?
> 
> ![Screenshot](https://user-images.githubusercontent.com/10089685/103272342-dbd39080-49d1-11eb-8e24-d09b2e4b2de4.png)

I stopped to update that plugin 07 Mar 2020,  so you have probably old version for 2.0.  It was moved to my old plugins repository and anybody can fix it.

**Comment by Moc** [comment]
I'm closing this one. The plugin is no longer part of core and not supported by the core developers anymore.
