### ISSUE TITLE
GDPR checkbox on contact template for bootstrap4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4318]
This is just a note (not forget this)

This is already applied in the bootstrap4 theme, but because the contact template is not fully tested, it can't be moved to core BT4 templates yet. 

Original code (core/bootstrap3):
```
	<div class='form-group'><label for='gdpr'>".LANCONTACT_24."</label>
		<div class='checkbox'>
			<label>{CONTACT_GDPR_CHECK} ".LANCONTACT_21."</label>
			<div class='help-block'>{CONTACT_GDPR_LINK}</div> 
		</div>
	</div>

```

New code:
```
    {CONTACT_GDPR_CHECK: label=".LANCONTACT_21."}
    <small>{CONTACT_GDPR_LINK}<small>
```

Result:
default bootstrap4:
![image](https://user-images.githubusercontent.com/5429548/103280532-ef322c00-49d0-11eb-8fb5-16695653a0e0.png)

![image](https://user-images.githubusercontent.com/5429548/103280550-fa855780-49d0-11eb-8438-fbec0428e289.png)

new core MDB theme:
![image](https://user-images.githubusercontent.com/5429548/103280626-2a345f80-49d1-11eb-8864-96694218297a.png)

![image](https://user-images.githubusercontent.com/5429548/103280651-3a4c3f00-49d1-11eb-8a53-eed97c972347.png)

**Comment by Jimmi08** [comment]
Version for bootstrap3:
```
	<div class='form-group'>    
	{CONTACT_GDPR_CHECK: label=".LANCONTACT_21."}
    <small>{CONTACT_GDPR_LINK}<small>
	</div>
```

**Comment by Moc** [comment]
So what do we need to do with this?

**Comment by Jimmi08** [comment]
It is too long, I can't remember. There is bootstrap5 already. Closing, if I run in a similar issue, I will create a new one or reopen this.
