### ISSUE TITLE
LM_REMEMBERME - outdated code for checkbox

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4319]
This is there now:

```
			function sc_lm_rememberme($parm='')
			{
				$pref = e107::getPref();
				if($parm == "hidden"){
					return "<input type='hidden' name='autologin' id='autologin' value='1' />";
				}
				if($pref['user_tracking'] != "session")
				{
					return "<label for='autologin'><input type='checkbox' name='autologin' id='autologin' value='1' checked='checked' />".($parm ? $parm : "".LAN_LOGINMENU_6."</label>");
				}
				return '';
			}
```

**Comment by CaMer0n** [comment]
If you can add classes that make it BS3 and BS4 compatible, that would be ideal. :+1:

**Comment by Jimmi08** [comment]
I just asked for using form class with checkbox()  It works correctly for bt3 and now for bt4 (I mean snippets)

**Comment by CaMer0n** [comment]
If you can send a pull-request for these, that would be appreciated. The important thing is that the HTML markup remains almost the same. (so as not to break existing theme styling)

**Comment by Jimmi08** [comment]
closing in favor of https://github.com/e107inc/e107/issues/4331
