### ISSUE TITLE
Error on downloading buttons (download plugin)

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4324]
I get the following error when I click on download buttons (download plugin) e107 v2.3.1 git - php v7.4

Fatal error: Uncaught Error: Call to undefined method e107table::replaceConstants() in /home/.../plugins/download/request.php:141 Stack trace: #0 /home/.../index.php(69): include_once() #1 {main} thrown in /home/.../plugins/download/request.php on line 141

**Comment by CaMer0n** [comment]
Thank you @realmontazeri !
