### ISSUE TITLE
{SIGNIN_SIGNUP_HREF} is not displayed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4325]
## Bug Description
signup link in the navbar is not displayed

## How to Reproduce
$this->authMethod has value string(0) "" so this test is always true and returns null:
`if ($this->regMode !== 1 || $this->authMethod !== 'e107')`

PHP 7.4

**Comment by CaMer0n** [comment]
@Jimmi08 This should fix it. ^^

**Comment by Jimmi08** [comment]
Tested, It is correct now. Thanks
