### ISSUE TITLE
Ordering extended user fields is not functional

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4334]
Automatically fall back to default orders, this issue is happening from php v5.6 to 7.4

**Comment by Jimmi08** [comment]
He means Admin UI, manual changing user_extended_struct_order values works.  The frontend is OK.  The problem is in Ajax. Confirmed for PHP 7.4.

**Comment by realmontazeri** [comment]
Fields in both backend and frontend won't get changed.

**Comment by Jimmi08** [comment]
> Fields in both backend and frontend won't get changed.

@realmontazeri if data in the database are not changed, of course, you will not see change on the frontend either. As soon as you change those data (anyway, f.e. phpmyadmin), the frontend works. So the problem was in the admin area.
