### ISSUE TITLE
Testing e107 menus 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4336]
## Motivation
To avoid confusion
Chapter menu displays content only if the chapters use template "panel".  You don't know this until you look into code why it displays nothing.

## Proposed Solution
Add message for admin similar way how counter plugin,,,,
Admin message: You don't have chapters with template panel. 
Or something like this, because now it looks like not working menu.

Thanks

Just notes (not create too many issues):
 - Why this limitation to "panel"  - if a parent is set, then the template shouldn't be important. 
  _Edit: because to use different look, but then the template should be parameter and panel only default._
 - there is no check if a book has "panel" template. If you do this, the book URL is not correct
 - shortcode {CHAPTER_BUTTON: text=More&size=sm} has hardcoded button classes

**Comment by Jimmi08** [comment]
`News Grid menu`

- default template is col-md-4,  it is hardcoded, not know without looking in code. For Test Menu default template with one item (col-md-12) would be nice. 

- displaying the latest news is different than normal news -  it ignores news location, so it displays other news, other news2 too.  

- it would be great to add news location as parameter...   

You can't use more news grids via menu now - you can have only one set for news grid location and then you have only category selection.

**Comment by Jimmi08** [comment]
**search menu** 

hardcoded without option to template it

**Comment by Jimmi08** [comment]
**user/userlanguage_menu**

- submit button has different markup / classes than other menu buttons

**Comment by CaMer0n** [comment]
@Jimmi08 How is it now?

**Comment by Jimmi08** [comment]
> **user/userlanguage_menu**
> +
> **contact/contact_menu**
> 
> * submit button has different markup / classes than other menu buttons

Fixed

**Comment by Jimmi08** [comment]
Only news/news_grid_menu has different buttons now .
