### ISSUE TITLE
Installation failed because of database name format

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4341]
This issue was happened on a fresh installation of the latest e107git version and php v7.4
![Screenshot](https://user-images.githubusercontent.com/10089685/104132412-5ddc9580-5392-11eb-885d-922e0eeb1885.png)

**Comment by realmontazeri** [comment]
MySQL database prefix name is not editable in shared hosting service because is related to customer id.

**Comment by CaMer0n** [comment]
Related to https://github.com/e107inc/e107/issues/3800

**Comment by CaMer0n** [comment]
@realmontazeri Please give it a try now. Thank you.

**Comment by realmontazeri** [comment]
> @realmontazeri Please give it a try now. Thank you.

The issue is still exist on the latest git version.

**Comment by CaMer0n** [comment]
@realmontazeri Is your database name all numbers?

**Comment by realmontazeri** [comment]
> @realmontazeri Is your database name all numbers?

Nope, it's including letters and underline.

**Comment by CaMer0n** [comment]
@realmontazeri Thanks for the quick response. Maybe the underline is causing the issue. I'll take another look.

**Comment by CaMer0n** [comment]
@realmontazeri I have relaxed the pattern check. Please try again, thank you.

**Comment by realmontazeri** [comment]
@CaMer0n thank you, the issue has been fixed.

**Comment by realmontazeri** [comment]
@CaMer0n thank you, the issue has been fixed.
