### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4342]
It would be nice to have 2FA option for both admin and user via apps like Google authenticator & etc...

**Comment by Moc** [comment]
I agree, it would be nice. I do think this is plugin territory but perhaps for a new core plugin.

**Comment by Moc** [comment]
Actually (after giving it some thought), on the longer run we may also want include more security related features in core such as device management (logged in devices). Then, 2FA / TOTP could be one of those security features.

**Comment by realmontazeri** [comment]
> Actually (after giving it some thought), on the longer run we may also want include more security related features in core such as device management (logged in devices). Then, 2FA / TOTP could be one of those security features.

Awesome!

**Comment by Moc** [comment]
Note the "longer run" haha. First step may be best to do as a plugin. Need to give this some more thought.

**Comment by nlstart** [comment]
Should that be possible to build in with the [alt_auth plugin](https://github.com/e107inc/e107/tree/21e3c3f8ab63ff4b79eb36f3019eaf33cec433dd/e107_plugins/alt_auth)?

**Comment by Moc** [comment]
@nlstart I've started with a simple implementation of the TwoFactorAuth library already, by means of a test. It looks like we'll need to make an adjustment in core to "hook" into the login process, similar to captcha. I'm working with Cameron on that. 

I'm also exploring the option to have it integrates in the alt_auth plugin but didn't get that far he.r

**Comment by Moc** [comment]
So over the past days I've been working on a TwoFactorAuth plugin, and it's ready for initial testing: https://github.com/e107inc/twofactorauth

Thanks to @CaMer0n for some changes in core :) 

I am closing the issue here,  but feel free to open a new issue in the other Github repository.
