### ISSUE TITLE
Changed HTML output for signup shortcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4343]
## Bug Description
not able to rid form-control class with bootstrap theme  
It worked a different way before with the signup template

## How to Reproduce
After update to using e107::getForm()->text() , form-control class is always added to input text field

Reason:
```
		if(!vartrue($options['class']))
		{
			$options['class'] = 'tbox';
		
               } 
		if(deftrue('BOOTSTRAP'))
		{
			$options['class'] .= ' form-control';
		}
```
		   
## Expected Behavior
If I use option class='xxx', then I expect to use only this class (if I need form-control, then parameter xxx form-control should be used

Before it worked this way:

`$options['class'] = vartrue($parm['class'],'');`

Form-control should be added only if parameter class is not sent.  There is no check if that class is not already there
`{SIGNUP_REALNAME: class=input-value form-control}`
causes: 
`<input type="text" name="realname" value="" maxlength="100" id="realname" class="input-value form-control form-control" title="Your full name" size="30" required="required">`

 
Correct fix:

```
		if(!vartrue($options['class']))
		{
			$options['class'] = 'tbox';
		
    		        if(deftrue('BOOTSTRAP'))
    		        {
    			         $options['class'] .= ' form-control';
    		         }
		} 
```

Thanks

**Comment by Jimmi08** [comment]
If this is the intention, I can live with it.

**Comment by CaMer0n** [comment]
It's intentional.

**Comment by Jimmi08** [comment]
Thanks
