### ISSUE TITLE
Information about using {---CAPTION---} - for 2.3.1 only 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4348]
`{---CAPTION---}` is the new magic shortcode for displaying caption in any place of HTML layout (outside tablerender), It displays the caption of first used tablerender() on the page itself.
_Note:_ magic shortcodes work only for style main or default.

Each template must have the key "caption" set . 

With core news template there is:
in news_template.php
`$NEWS_TEMPLATE['default']['caption'] = null; // add a value to user tablerender()`

in news_view_template.php
`$NEWS_VIEW_TEMPLATE['default']['caption'] = null; // add a value to user tablerender()`

It means that tablerender() is not used and `{---CAPTION---}` displays nothing or comment caption.
 
So theme with this functionality always must to have those templates in the theme templates folder.
Examples:
View:
`$NEWS_VIEW_TEMPLATE['default']['caption'] = '{NEWS_TITLE}'; `

Default layout:
`$NEWS_TEMPLATE['default']['caption'] = $NEWS_TEMPLATE['list']['caption'];`
`$NEWS_TEMPLATE['default']['caption'] = '{LAN=PAGE_NAME}';`
`$NEWS_TEMPLATE['default']['caption'] = '{NEWSCATEGORY}';`

**Comment by CaMer0n** [comment]
@Jimmi08 As discussed, tablestyle will now always be used when using the new theme specification. (ie. theme.html)

**Comment by Jimmi08** [comment]
Tested. It works. This is tagged as documentation, so I am closing this.
