### ISSUE TITLE
Canonical URLs for core - overview 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4352]
**Please, don't comment this issue. It is for now only for Cameron and if you have questions or ideas, ask/write them on gitter.  It is not the final version yet.**

All theory you can find here: (it is an updated version for 2021):
![image](https://user-images.githubusercontent.com/5429548/104856213-9ab80780-5911-11eb-966a-fe70b15c882e.png)

https://moz.com/learn/seo/canonicalization

**Summary:**
- not separate solution for legacy and SEF-URLs
- display canonical tag for the page itself
- priority is the homepage

**Important note:**
- canonical URLs is URL when you want to get most of the traffic, so it should be the same URL as in sitemap  and og::url() 

**Now the situation in e107:**

There are 4 main types of URLs related to this topic (with maybe different solution)

1. Frontpage itself (index.php). be aware of duplicates if there is a different frontpage set. 

2.  single pages (f.e. contact.php), and plugin frontpages (f.e. news.php).  
(simply said - what you put in sitelinks)

3. Table related URLs (the combination of the real table and ID value)
 - custom page view,  news view, news category view...  they are defined in e_gsitemap addon or e_gsitemap itself (pages)...  **suggestion**: _move pages to e_gsitemap addon in page plugin, then it will be clear_  
- there is always some unique ID for those pages and table name

4. pages without IDs -  'news_tag', - news tags...

**Comment by Jimmi08** [comment]
Duplicates for Frontpage: (if frontpage is index.php)

```
    {SITEURL} 	{SITEURL}  -  default
    {SITEURL}/index.php	{SITEURL}  -  legacy
    {SITEURL}/?	{SITEURL}	  - this was really indexed by google, maybe some mistypo in sitelinks, no idea, but that link works
    {SITEURL}/	{SITEURL}  - backslash always create duplicate content
```

if Frontpage is set to news.php,  then the canonical URL for news.php should be {SITEURL}.

**Comment by Jimmi08** [comment]
Examples for single pages:  Not tested correct value, it is just displayed to see a pattern here

**Contact page/plugin:**
```
{SITEURL}/contact {SITEURL}/contact
{SITEURL}/contact/ {SITEURL}/contact
{SITEURL}/contact.php	{SITEURL}/contact
correct value: e107::url('contact', 'index');
```

**Gsitemap page/plugin:**
```
 {SITEURL}/gsitemap.php?show	{SITEURL}/sitemap	
 {SITEURL}/gsitemap.php?show=1	{SITEURL}/sitemap    
 correct value: e107::url('gsitemap', 'index');
```

**News front page / news plugin:**

```
{SITEURL}/news/all.html	{SITEURL}/news	 	
{SITEURL}/news/	{SITEURL}/news 	
{SITEURL}/news	{SITEURL}/news 	
{SITEURL}/news.php	{SITEURL}/news	 
    correct value: e107::url('news', 'index');
```

**Forum front page**:
```
    {SITEURL}/forum/   {SITEURL}/forum
    {SITEURL}/forum	{SITEURL}/forum
    {SITEURL}/e107_plugins/forum/forum.php	{SITEURL}/forum
    correct value: e107::url('forum', 'index');
```

So it is always set (should be) in e_url.php with config key "index".

The only plugin I wasn't able to understand how works is gallery plugin.  And there is "page" plugin, that doesn't use e_url.php.

**Comment by Jimmi08** [comment]
**3. Table related URLs.**

- solution for now is available for plugins used e_gsitemap addon, but there is a pagination issue too.

### NEWS

**1. news view (no pagination)** 
`  e107::getUrl()->create('news/view/item', $row, array('full' => 1));`
for
```
				'id'    => $row['news_id'],
				'table' => 'news',
```

**2. news category page (possible pagination)**
`e107::getUrl()->create('news/list/category', $row, array('full' => 1));`
for:
```
				'id'    => $row['category_id'],
				'table' => 'news_category',
```

### FORUM
**1. forums**  
source of this e_gsitemap addon
`'url'   => e107::url('forum','forum',$row, array('mode'=>'full')), // ('forum/forum/view', $row['forum_id']),`
for
```
					'id'    => $row['forum_id'],
					'table' => 'forum',
```

_Note:  missing forum topics_

### DOWNLOADS
1. downloads categories
`'url' => e107::url('download', 'category', $row,   array('mode' => 'full' )),`
For:
```
				'id'    => $row['download_category_id'],
				'table' => 'download_category',
```
2. download item
`'url'   => e107::url('download', 'item', $row,   array('mode' => 'full' )),`
For:
```
				'id'    => $row['download_id'],
				'table' => 'download',
```

**Comment by Jimmi08** [comment]
Testing:

single pages (not book/chapter)
URL: `http://localhost/e107mdb/page/about`
Canonical URL: `http://localhost/e107mdb/page/--sef-not-assigned--/--sef-not-assigned--/about` 

chapter:
URL: `http://localhost/e107mdb/page/general/chapter-1`
Debug: Setting Canonical URL: `http://localhost/e107mdb/page/chapter-1/chapter-1  (2x chapter URL)`

**Comment by Jimmi08** [comment]
@CaMer0n 

Canonical URL for page.php (no query) is:  (non-pretty URLs)

xxx/page.php?id=0

Is this correct? Shouldn't be it only page.php?

**Comment by CaMer0n** [comment]
You're right, it should be `page.php`

**Comment by Moc** [comment]
How far are we on this issue? 

@Jimmi08 Any remaining things to integrate into core?

**Comment by Jimmi08** [comment]
I forgot the constant name to check this.  That page issue was the only one left at that time...
But maybe you could create a new label like "route" - for related issues to this topic. It is going through the system - core + plugins.
Then this can be closed.

**Comment by CaMer0n** [comment]
@Moc I'm closing this one since it's a lot of issues in one. I believe most, if not all, have been corrected.
