### ISSUE TITLE
Users default level got changed

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4355]
Recently after updating to the latest git versions, all the member rank/level got changed automatically to admin(badge) although they are not set as admin class, also I couldn't find any options to change their level/rank value manually:
![Screenshot](https://user-images.githubusercontent.com/10089685/105770299-3f6ec080-5f74-11eb-86c9-b8515781f24f.png)

**Comment by Jimmi08** [comment]
Confirmed. PHP 7.2.
