### ISSUE TITLE
Can't login via admin-area login page

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4356]
It is not possible to login via admin-area login page on the latest git version but it is possible to login into admin-area via front page login drop-down window, even disabling captcha option didn't help (php v7.4)
![Screenshot](https://user-images.githubusercontent.com/10089685/105864573-527ea080-6007-11eb-9425-a0f441b4e40e.png)

**Comment by CaMer0n** [comment]
@realmontazeri Unfortunately, I am unable to reproduce the issue. 
How about you @Moc @tgtje @Jimmi08 ?

**Comment by Moc** [comment]
Nope. Tested on PHP 7.2.

**Comment by CaMer0n** [comment]
@realmontazeri what value to do have for "Password encoding" in your Preferences?
 (ie. `e107_admin/prefs.php#nav-core-prefs-security`)

**Comment by Jimmi08** [comment]
I don't have live site with the latest version, but it works on localhost with 7.4 and 7.2
But I remember a similar issue with login and display name. Are they the same or not for you?

**Comment by realmontazeri** [comment]
> I don't have live site with the latest version, but it works on localhost with 7.4 and 7.2
> But I remember a similar issue with login and display name (I had to use the display name to log in). Are they the same or not for you?

Both username and email are not working on this issue.

**Comment by realmontazeri** [comment]
> @realmontazeri what value to do have for "Password encoding" in your Preferences?
> (ie. `e107_admin/prefs.php#nav-core-prefs-security`)

PHP Default (Preferred), This issue was happened just a few days ago and there was no such problem before that.

**Comment by Jimmi08** [comment]
> Both username and email are not working on this issue.

not email, display name vs login name. Do you have them the same?

**Comment by realmontazeri** [comment]
> > Both username and email are not working on this issue.
> 
> not email, display name vs login name. Do you have them the same?

display name: administrator
login name: admin
both does not work

**Comment by CaMer0n** [comment]
For consistency we upgraded the login routine in the admin area to use the same one used on the front end. 
Could you please update from github and try again?

**Comment by realmontazeri** [comment]
> For consistency we upgraded the login routine in the admin area to use the same one used on the front end.
> Could you please update from github and try again?
> 
> Also, could you please share your server info? ie. the left column here: `/e107_admin/phpinfo.php`

Updated to the latest git version and still having no access

e107
Version 2.3.1 (git)

Security level
[5] Balanced

Site Theme
bootstrap3

Admin Theme
Bootstrap 3 v1.0 by e107 Inc (2013-12-25)

Install date
Tuesday 28 March 2017 - 00:51

Server
Apache
(host: localhost)

PHP Version
7.4.14

MySQL
5.7.32-log
Database: root
PDO: Enabled
Mode: NO_ENGINE_SUBSTITUTION

Charset
utf-8

**Comment by Jimmi08** [comment]
@CaMer0n I changed display name to administrator, login name admin,  now I can't login in admin area. Frontend login work.

**Comment by tgtje** [comment]
Sorry bit busy here are some preliminary results:live php 7.3.22 mariadb git version 14-01 full install no problems. (cookie)
live php 7.3.22 mariadb git version by sync today (27-01) 
array message > 
    [0] => ../e107_themes/bootstrap3/templates/gallery/gallery_template.php

Strange> logging me out after click.. ..using admin path login > OK  (cookie) (log out manual).

Using login php as menu not running > You are seeing this message because you are currently logged in as the Main Admin.????
I logged out!! Using admin path  to return to check > i am logged in....
Switching theme as seems to have issues> going to BS3> adding login menu > After logout main> login menu > login OK

Again using login php (to eliminate> You are seeing this message because you are currently logged in as the Main Admin.

So seems issue on Login.php (or cookie not destroyed by logging out)
Just to inform _I will post more test results doing similar on local environment php 7 and 8_
With 14-01 versions (used recently) there were no issues as far as i can tell.

**Comment by tgtje** [comment]
_Because of the (my mistake) seeing the message of already logged in = correct (using admin cred.).._
This remains : Strange> logging me out after click  did not appear again.

In short: in both versions 14-01 + todays and also on php 7x and php8 **NO** issues logging in/out.
Being login php, menu or by BS3 bar or admin page..all does/behaves as expected.

Similar trying to reproduce as member > all working (admin page does not allow = correct).

**Comment by tgtje** [comment]
Just re-read postings > **display name: administrator**  iff i recall (memory) this is NOT allowed as it is a core used constant (hope that is the correct name)..

**Comment by CaMer0n** [comment]
@realmontazeri Is this still an issue after these last commits?

**Comment by realmontazeri** [comment]
> @realmontazeri Is this still an issue after these last commits?

Yes, the issue is still exist.

**Comment by CaMer0n** [comment]
@realmontazeri Could you please share these (see below) settings that you have in the "Security & Protection" Prefs area?
 (a screenshot is fine). 

![image](https://user-images.githubusercontent.com/2825679/106316844-3b67ca80-6222-11eb-8eaa-a0ca4e2db3de.png)

**Comment by realmontazeri** [comment]
@CaMer0n all values are the same as the picture.

**Comment by CaMer0n** [comment]
Thank you @realmontazeri . Would you have a few moments to discuss this issue in the chatroom? 
( https://gitter.im/e107inc/e107 )

**Comment by realmontazeri** [comment]
@CaMer0n I finally found out the reason of this strange behavior, actually it was not related to cookies, when i disabled the captcha for login page then i was able to login from admin-area login page although the captcha is enabled for admin-area login page so it seems captcha option for the frontpage has conflict with admin-area login page:
![Screenshot](https://user-images.githubusercontent.com/10089685/106340688-e4a8d200-62af-11eb-840d-c83fa3ef6581.png)

**Comment by tgtje** [comment]
Ahh new information.. 
Did a new install php 7.3.5 Using administrator (display) and admin as pw. (no captcha)
I can do everthing i want (so no issue on name) syncing also fine, Shows no troubles (identical for standard names).
However when i DO enable captcha (i used login and admin captcha; No SSL as local) _the issue arises_. So in short i can replicate this behaviour, and even changing names via dbase, has no effect..

**Comment by fred232003** [comment]
![user tracking](https://user-images.githubusercontent.com/48333681/106406046-2325c480-6449-11eb-811e-791d55190b4b.jpg)

Recently I have upgraded my current v.2.3.0 to v2.3.1 github  ( change to sessions )
Its fine now.

**Comment by CaMer0n** [comment]
@realmontazeri Thank you! Your info was very helpful. I believe I have squashed that bug now. Please give it a try with the recent changes.
