### ISSUE TITLE
Graph was disappeared in dashboard

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4357]
The graph tab/section in online table was gone after this commit: 60afb0ba1aea7439cd9ffa59dead58bdc821b1f1 (Fix for bot icon in dashboard online table.)
![Screenshot](https://user-images.githubusercontent.com/10089685/105907909-c8e8c600-603a-11eb-9e52-e59af41c09d7.png)

**Comment by CaMer0n** [comment]
Yes, the old log plugin was removed. You can still install it here: https://github.com/e107inc/log
