### ISSUE TITLE
Fresh Install of v2.3.0 and not able to login

### ISSUE THREAD

**Issue by Grumpypjs08** [e107inc/e107#4361]
## Bug Description
I have done a fresh install of e107 2 times threw softaculous and both times I have not ben able to log in via the admin or front facing login pages it says "Your login details don't match any registered user. Check if you have the CAPS-LOCK key activated, as logins on this site are case sensitive." Also looking at the database directly says the password I created to install is not in there and the value does not work.
## How to Reproduce
1. Go to 'soso.com/e107_admin'
1.5. Or go to 'soso.com/login.php'
2. See error

## Expected Behavior
Login

### Client Information

Mozilla/5.0 (X11; CrOS aarch64 13505.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.152 Safari/537.36

**Comment by CaMer0n** [comment]
Thank you for letting us know @Grumpypjs08 . I assume it is version e107 v2.3.0 that you are running?
Could you share some information about the server? (PHP version etc)

**Comment by Grumpypjs08** [comment]
Correct v2.3.0. I am hosting with infinityfree, and am not sure how to get any other info

**Comment by Grumpypjs08** [comment]
Found the php version it is 7.0

**Comment by Grumpypjs08** [comment]
System: 

Linux freeweb5.byetcluster.com 2.6.32-896.16.1.lve1.4.54.el6.x86_64 #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64
--

**Comment by CaMer0n** [comment]
@Grumpypjs08 Thank you. If you have direct access to your database, you can edit your user account and use the MD5 function 

Like this: UPDATE `e107_user` SET `user_password` = MD5('newpassword') WHERE `e107_user`.`user_id` = 1;

**Comment by Grumpypjs08** [comment]
Still did not work also my user table is called 'e1078b_user'

**Comment by CaMer0n** [comment]
@Grumpypjs08 Sorry about that. Could you please try with a "Private browser window" ?

**Comment by Grumpypjs08** [comment]
That still did not work the URL is https://teach.saveourearth.ml if that helps at all

**Comment by CaMer0n** [comment]
@Grumpypjs08 Sorry for the trouble. I'd be happy to troubleshoot it with you. Just message me in the chatroom when you're available. https://gitter.im/CaMer0n

**Comment by Moc** [comment]
Closing as this was likely a very environment specific issue. 

If the issue still persists on clean installations of the latest e107 version, please re-open.
