### ISSUE TITLE
hardcoded strings in core news templates

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4368]
news_template:

`$NEWS_TEMPLATE['related']['start'] = '{SETIMAGE: w=350&h=350&crop=1}<h2 class="caption">You Might Also Like</h2><div class="row">';`

news_view_template:
`<h3>About the Author</h3>`

You Might Also Like
About the Author

Should those be added to core or to theme LANS? 

Thanks

**Comment by Moc** [comment]
This was fixed https://github.com/e107inc/e107/commit/c33b91ee5c1c4f221242b98117bf33eef5fc466d
