### ISSUE TITLE
Glyphicons appearance issue in TinyMce4 editor

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4371]
Inserting Glyphicons appear like this:

![Screenshot1](https://user-images.githubusercontent.com/10089685/107109294-6a9abf00-6854-11eb-8e16-952ae0b73cb2.png)
![Screenshot2](https://user-images.githubusercontent.com/10089685/107109295-6c648280-6854-11eb-93dd-45d30e0cb9ab.png)

**Comment by tgtje** [comment]
`.fa.fa-github {
  font-family: 'Font Awesome 5 Brands';
  font-weight: 400; }`
  from e107_web  /lib/   font-awesome/5/css/v4-shims.  css
  
  `<p><i class="fa fa-github"></i></p>`
