### ISSUE TITLE
Is this correct? not found page redirect for css and js files

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4373]
If you have the missing file, then you can see the error in the console with the path this file:
![image](https://user-images.githubusercontent.com/5429548/107330303-ab434400-6ab1-11eb-976d-2f547f5dce2c.png)

But with Redirect to System not found page ON you can see there:
![image](https://user-images.githubusercontent.com/5429548/107330404-cb730300-6ab1-11eb-8d18-9550a71429b1.png)

Why is this fired on css or js files? With using e107:css() or e107::js() ?

Shouldn't be this work only for PHP pages? 

I didn't notice this before.

**Comment by CaMer0n** [comment]
@Jimmi08 Maybe check your .htaccess file for ```ErrorDocument``` ?

**Comment by Jimmi08** [comment]
@CaMer0n  default e107 htaccess,  it is localhost
# Custom error pages for PHP scripts only

```
<FilesMatch \.php$>
	ErrorDocument 400 /error.php?400
	ErrorDocument 401 /error.php?401
	ErrorDocument 403 /error.php?403
	ErrorDocument 404 /error.php?404
	ErrorDocument 500 /error.php?500
</FilesMatch>
```

**Comment by CaMer0n** [comment]
@Jimmi08 Then I'm guessing it's something to do with the 'static' configuration in .htaccess.

**Comment by Jimmi08** [comment]
Yes, it is localhost.

**Comment by CaMer0n** [comment]
@Jimmi08 Perhaps this is the cause?  ```RewriteRule .* index.php [L]```

**Comment by CaMer0n** [comment]
@Jimmi08 Maybe this can help: https://webmasters.stackexchange.com/questions/87926/mod-rewrite-ignore-stylesheet-and-javascript

**Comment by Jimmi08** [comment]
I have no idea. I will just not use this option.  But I still think that if this is .htaccess issue, then it will be there always, not only if the internal redirect is set on.

**Comment by CaMer0n** [comment]
Correct, and it could slow things down.

**Comment by CaMer0n** [comment]
Issue confirmed. It shouldn't be going through mod-rewrite for js/css/fonts etc:  

![image](https://user-images.githubusercontent.com/2825679/107431853-e35f7c80-6adb-11eb-9da5-4c23979c86d2.png)

**Comment by Jimmi08** [comment]
Maybe this is related too:
https://github.com/e107inc/e107/issues/3713

**Comment by CaMer0n** [comment]
Confirmed fixed.
