### ISSUE TITLE
Fatal error after latest sync with tinymce4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4378]
missing file wysiwyg_class.php

`<b>Fatal error</b>:  require_once(): Failed opening required 'C:\xampp74\htdocs\e107mdb\e107_plugins\tinymce4/wysiwyg_class.php' (include_path='.;C:\xampp74\php\PEAR') in <b>C:\xampp74\htdocs\e107mdb\e107_plugins\tinymce4\wysiwyg.php</b> on line <b>113</b><br />`

**Comment by CaMer0n** [comment]
Yes, was missing a file.
