### ISSUE TITLE
How to upload to specific directory?

### ISSUE THREAD

**Issue by djbeater** [e107inc/e107#438]
I develop a new plugin, but the problem is, how to upload and after that choose image?

i want structure like this:

my_plugin/images/kategorijas/my_uploaded_pic.jpg

my plugin code part looks like: 

```php

define("PLUGIN_KAT_DIREKTORIJA", "images/kategorijas/"); // kategoriju bilžu direktorija

'bilde_l' => array('title' => LAN_PLUGIN_LA_KAT_PR_BILDE, 'type' => 'image', 'data' => 'str', 'width' => 'auto', 'readParms' => array('title' => LAN_PLUGIN_LA_KAT_PRIEKSSKAT, 'pre' => PLUGIN_KAT_DIREKTORIJA), 'writeParms' => array('title' => LAN_PLUGIN_LA_KAT_PRIEKSSKAT, 'pre' => PLUGIN_KAT_DIREKTORIJA, 'ajax' => TRUE)),

```

but when i upload, i need silly importing etc...

I'm experimenting with 'readParms' and 'writeParms' but nothing useful cannot find.

Can someone tell me some hint, what i need to modify?

Thanks ;)

**Comment by CaMer0n** [comment]
Just use the imagepicker() (see admin-> newspost.php) and save the result to your database table. Then use $tp->thumbUrl() to parse the value back to an <img tag.

**Comment by Jimmi08** [comment]
But how solve this when you use admin_ui? In newspost.php is form  created manually ($text .= $frm...) in show_create_item() function...  

In my case I would like to set default folder for each media category and when I import the pictures to this category, they should be saved in this folder. Or be able set path in import function.  Your change with enabling change url image in admin was great help, but I still need to do it manually where I am importing pictures.

**Comment by Jimmi08** [comment]
this is related:  https://github.com/e107inc/e107/issues/702  
I closed it because I was able to get around it.

**Comment by CaMer0n** [comment]
The problem in v1.x was that plugins stored files in their own folders and this caused permissions issues and made it difficult to backup user-specific data. v2.x solves this by putting everything in either e107_media or e107_system and storing the path and plugin-ownership in the media-manager.

**Comment by CaMer0n** [comment]
Closing this issue. The simple answer is to create a media-category for your plugin and then use e107::getMedia()->importFile() to add to your media-category.

**Comment by Jimmi08** [comment]
@CaMer0n Just a note to this. Or feedback. I was really testing/active using media manager and it works amazing. Great work at this area and big thanks to you. I noticed little issues/questions and I will create new issues later, but just after more testing (I haven't access to my localhost now)
- with new plugin I wasn't able to create new media owner. It should still be done according gallery plugin? in plugin.xml or setup class? 
- one can set media category in admin ui (write parms) but there is no test if media category is available. Result is all uploaded images are in _common category and if you use more categories, you still see them in other category. Warning would be great.

**Comment by CaMer0n** [comment]
@Jimmi08 e107_plugins/banner/plugin.xml has a simple example. Indeed, some kind of check needs to be added for missing categories.
