### ISSUE TITLE
Change submit button location on lan manager

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4380]
![imagem](https://user-images.githubusercontent.com/17130530/107775157-db037d80-6d37-11eb-95e0-4a13b313cc91.png)

It happens that a lot of times, after updating or creating new lan's, the orange button is hidden on the scroll text, and i press the next button by mistake, and had to start over all again. If the orange button was next to it, probably the mistake wouldn't occur....

Other suggestion is remove completely the next button, because we already have the x to close that popup modal (althought it's poorly visible), no?

**Comment by CaMer0n** [comment]
@rica-carv  Done!

**Comment by rica-carv** [comment]
@CaMer0n Wow, that was fast. Thanks, i will test it later. Thanks!
