### ISSUE TITLE
THEME_LAYOUT is not defined in theme_shortcodes.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4382]
for some layouts, THEME_LAYOUT is not defined in theme_shortcodes.php
 
in fact, only home and contact work.

The layout in the body is correct.

**Comment by CaMer0n** [comment]
@Jimmi08 Which theme with which layouts do not have THEME_LAYOUT defined?

**Comment by Jimmi08** [comment]
Cayman, new one.  full and right-sidebar stopped to work after today's sync.

**Comment by Jimmi08** [comment]
Just note to have it complet

THEME_LAYOUT is not available in global shortcodes, only in theme ones.
So using it in e_shortcode.php is not a good idea and all using of it has to be moved to theme shortcodes.

**Comment by CaMer0n** [comment]
Correct. 
Also, plugin addons `e_header.php` and `e_footer.php` still have access to the value of `THEME_LAYOUT` .
