### ISSUE TITLE
problem with  menu area list in menu manager (not menu areas)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4386]
With menu areas in theme.html, everything works:
![image](https://user-images.githubusercontent.com/5429548/107973134-224a7200-6fb5-11eb-9f7d-86493bc79f4e.png)

But after moving the footer to a separate file standard way:
`{---FOOTER---}`

and 

```
	function sc_footer()
	{
		$footerName = varset( $this->actualLayoutData['layout_footer'] , "footer_default");
		$footerpath = THEME . "footers/{$footerName}.html";
 
		if (file_exists($footerpath))
		{
			$text = file_get_contents($footerpath);
		}
		return $text;
	}
```

Menu areas list is empty:

![image](https://user-images.githubusercontent.com/5429548/107973389-73f2fc80-6fb5-11eb-8faf-361956f89305.png)

Rendering menus works.

**Comment by Jimmi08** [comment]
This fixed it:

```
<body class="{LAYOUT_ID}" {BODY_ONLOAD} >
	{---HEADER---}
	{---LAYOUT---}
	{---FOOTER---}
	{MENUAREA=41}{MENUAREA=42}{MENUAREA=43}{MENUAREA=44}
</body>
```
The frontend is correct (no 2x rendering)....  

but adding this to layout.html causes 2x rendering of the same number of area...  Just information.

**Comment by CaMer0n** [comment]
@Jimmi08 Thank you. So if I understand well, Menu Manager is not detecting the MENUAREAS defined by sc_footer(), correct?

**Comment by CaMer0n** [comment]
I tested with this: 

```
function sc_footer()
	{
		return " ---- MY FOOTER --- 
		
		{MENUAREA=456} ";
		```

**Comment by Jimmi08** [comment]
No, in external file. 

`$text = file_get_contents($footerpath);`

**Comment by CaMer0n** [comment]
@Jimmi08 Your code references **THEME**, which, in the admin area, is the path to **bootstrap3**. 

    $footerpath = THEME . "footers/{$footerName}.html";

You should be using:

    $footerpath = e_THEME . 'yourtheme/footers/'.$footerName.'.html';

**Comment by Jimmi08** [comment]
Sorry, It was an error with copying. Menus are loaded on the right side (iframe), so it was correct at that time.

```
		$footerpath = e_THEME. $this->sitetheme . '/footers/' . $footerfile . '.html';

		if (file_exists($footerpath))
		{
			$text = file_get_contents($footerpath);
		}
```

![image](https://user-images.githubusercontent.com/5429548/108100722-96087f80-7086-11eb-92ce-6ad7ced7dfa7.png)

**Comment by Jimmi08** [comment]
Just note.

the system creates that list by parsing content from that shortcode. And because the content is in an external file, it is not parsed. 

So this works:
```
function sc_footer()
{
	return " ---- MY FOOTER --- 
		{MENUAREA=456} ";
}

```

but this not:
`$footerpath = e_THEME. $this->sitetheme  . "/footers/{$footerName}.html";`

And in fact this is workaround for this:

```
		$footerpath = THEME . "footers/{$footerName}.html";
	 	$text = '{MENUAREA=41}{MENUAREA=42}{MENUAREA=43}{MENUAREA=44}';
		if (file_exists($footerpath))
		{
			$text = file_get_contents($footerpath);
		}

```
- in preview THEME has the correct value, so menu areas are loaded
- on the left side, it is ignored, because of bootstrap3, so the text is parsed and it works:

![image](https://user-images.githubusercontent.com/5429548/108593802-2d671e80-7376-11eb-8384-c9a7d5fbb57f.png)

**Comment by CaMer0n** [comment]
@Jimmi08 
> because the content is in an external file, it is not parsed.

 -- that makes absolutely no sense at all. External files are parsed numerous times in e107/PHP without an issue. 

I'll state it again:

###  **The fundamental problem with your code is that the path to the footer file is wrong.**

### Working Example:

#### theme_shortcodes.php 
```
	function sc_footer()
	{
		$theme = e107::getPref('sitetheme');

		$footerpath = e_THEME . $theme. "/footers/foot.html";

		if (file_exists($footerpath))
		{
			return file_get_contents($footerpath);
		}

	}
```

#### foot.html
```
<div>
{MENUAREA=41}
{MENUAREA=42}
{MENUAREA=43}
{MENUAREA=44}
</div>
```

### Result: 

![image](https://user-images.githubusercontent.com/2825679/108599676-61771b00-7347-11eb-8e3e-f555f425f031.png)

**Comment by Jimmi08** [comment]
Did you think that I didn't try almost anything I can?

**Comment by CaMer0n** [comment]
Correct @Jimmi08 . I closed this issue 4 days ago, but since you insisted on a "workaround", I thought it important to clarify the false conclusions that you came to.  I believe checking the value of `$footerpath` would have saved you some time.

**Comment by Jimmi08** [comment]
@CaMer0n I am thankful for this. Really.

But don't you think it was first what I did? It just didn't hit me that I needed to check it on 2 places.  After your first answer I fixed it and it worked.  After the next sync, it didn't it.  Theme prefs and core prefs are not always available in init() of theme shortcodes. And I am not able to point when...  

Now I have another theme with this code (wrong path) and the menu list works and the only difference is the PHP version.  Now it is 7.2.  Latest sync. So could I know that that path is wrong?

![image](https://user-images.githubusercontent.com/5429548/108619683-ade55800-7426-11eb-98e2-03c01fcb6eb9.png)

**Comment by Jimmi08** [comment]
For your info:
This is menu manager (with wrong paths) for PHP 7.2:

![image](https://user-images.githubusercontent.com/5429548/108620251-32d27080-742b-11eb-8aca-2234b5897b86.png)

And this is the same code for PHP 7.4  (second print_a is not displayed)
![image](https://user-images.githubusercontent.com/5429548/108620283-7036fe00-742b-11eb-9334-50facacb1044.png)

And PHP 8
![image](https://user-images.githubusercontent.com/5429548/108620429-711c5f80-742c-11eb-86aa-8d52695de5aa.png)

**Comment by CaMer0n** [comment]
@Jimmi08 You need to check the path that is in the left side-bar (admin area theme), not in the iframe on the right. (front-end theme)

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/108755166-33602980-7547-11eb-8ed1-d74d84fcdc1a.png)

**Comment by CaMer0n** [comment]
Sorry, I can see now that you're outside of the iframe. You see the difference in paths.
