### ISSUE TITLE
FR - add preference/setting for indexing only news detail page

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4392]
There is hardcoded noindexing all news pages except news detail (view):

```
case "all":
e107::meta('robots', 'noindex');
break;
```

+
```
case "tag":
case "author":
case "list":
case "day":
case "month":
default:
	e107::meta('robots', 'noindex');
```

Let this on the site owner's decision, please.   Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 As mentioned before. I will have this confirmed by an SEO specialist. The point of e107 is for admins to not have to worry about details like this.

**Comment by Jimmi08** [comment]
Just note. 
Admin is sometimes different than site owner and site owner wants to do their own SEO politics.  Hardcoded stuff like this without the option to change it in prefs is not a good idea.  Metatag plugin was a solution but it is outdated and over-complicated.  But it was the right way how to do it. 

https://github.com/e107inc/e107/commit/fe8ae40f307807695f91b4e83c09765ab0173692
