### ISSUE TITLE
Message getAll and hasMessage not working...

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4400]
I've got this code:
```
    $msg->warning("Warning text");
   $msg->error("Error text");

if ($msg->hasMessage('warning')) {
    echo $msg->get('error');
    echo $msg->get('warning');
    require_once(FOOTERF);
    exit;
}
```
It currently outputs the messages, but if instead of:
```
if ($msg->hasMessage('warning')) {
    echo $msg->get('error');
    echo $msg->get('warning');
    require_once(FOOTERF);
    exit;
}
```
i use:
```
if ($msg->hasMessage()) {
    echo $msg->getAll;
    require_once(FOOTERF);
    exit;
}
```
I don't get any messages output or they're no messages found....

**Comment by CaMer0n** [comment]
```
$this->mes->addWarning("Warning message");
			$result= $this->mes->hasMessage(E_MESSAGE_WARNING);
			```

**Comment by rica-carv** [comment]
> 
> 
> ```
> $mes = e107::getMessage(); 
> $mes->addWarning("Warning message");
> $result = $mes->hasMessage(E_MESSAGE_WARNING);
> ```
> 
> $result is **true**.
> 
> I don't recognize the methods 'warning' and 'error', they are not part of e107 .

@CaMer0n Regarding the methods, i replyed in the other issue.
Regarding this issue, have you tested `hasMessage `without parms? Shouldn't it check for all message types ang give true or false?,

**Comment by CaMer0n** [comment]
@rica-carv Good point. Let me check that and make a test for it.

**Comment by CaMer0n** [comment]
@rica-carv The test is still passing without any issue. 

```
public function testHasMessage()
{
	$this->mes->reset();

	$result = $this->mes->hasMessage();
	$this->assertFalse($result);

	$result= $this->mes->hasMessage(E_MESSAGE_WARNING);
	$this->assertFalse($result);

	$this->mes->addWarning("Warning message");
	$result= $this->mes->hasMessage(E_MESSAGE_WARNING);
	$this->assertTrue($result);

	$result = $this->mes->hasMessage();
	$this->assertTrue($result);

	$result= $this->mes->hasMessage(E_MESSAGE_INFO);
	$this->assertFalse($result);

}
```

**Comment by rica-carv** [comment]
@CaMer0n Checked, rechecked and triple checked on my side, and now it works also.... Damn gremlins.....
