### ISSUE TITLE
(?) icons in admin area not working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4401]
The help icons in the admin area are suppossed to do anything?

![imagem](https://user-images.githubusercontent.com/17130530/108378442-e73a7f80-71fc-11eb-8722-06395f29e5e1.png)

Currently, in Firefox Developer Edition, they're displayed, but there's nothing more done. No help displayed, nothing....
On previous version the icons weren't there, but help was displayed in the forms input boxes...

**Comment by CaMer0n** [comment]
@rica-carv Could you please share the corresponding $field definition for that screenshot? Normally you should get a popup message when you hover. Are there any javascript errors in your browser console?

**Comment by rica-carv** [comment]
@CaMer0n This is not related to the $field definitoin, i'm almost 100% sure, because i got this bug all around the admin area, inclunding the core prefs area, etc....

I only have a javascript console error, regarding the use of the non-stadard property "zoom":
![imagem](https://user-images.githubusercontent.com/17130530/108600925-b8a1dd80-7391-11eb-93ae-1e2c5c03bb0e.png)

**Comment by CaMer0n** [comment]
@rica-carv Please go to Admin > PHP Info ( /e107_admin/phpinfo.php ) and make sure there are no errors displayed. 
Also please clear cache if you didn't already.

**Comment by rica-carv** [comment]
@CaMer0n Cleaned cache, and still persists....

Meanwhile i do have a PHP error in PHP Info:
![imagem](https://user-images.githubusercontent.com/17130530/108724168-f2ebb600-751c-11eb-9b8d-2339f53aaf41.png)

But can it be related???

**Comment by CaMer0n** [comment]
@rica-carv Can you grant me a login to see the issue, or is this a local installation? I wouldn't hurt to correct that extension issue to rule that out as a possibility. I don't see a connection between the two, but stranger things have happened.

**Comment by rica-carv** [comment]
@CaMer0n I would be happy to give you access, but unfortunatelly this is a local installation....
Meanwhile i'll check for that extension, and try fix that php error...
Thanks for all the help...

**Comment by tgtje** [comment]
I can confirm issue
On php 8 the ? are placed correctly to the right and help text etc. are displayed. (running local).

On live site php 7.3.22 (git 2 or 3 days ago) this issue arises although my case only the icons shift to left next to characters and the helptext is about a 1/2 inch to the left (hovering over the caption).
image of php 7 :
![question](https://user-images.githubusercontent.com/1811857/108885532-396a0f00-7608-11eb-9303-c430996f9e42.jpg)

**Comment by CaMer0n** [comment]
PHP 7.4.15 with Firefox and Chrome: 

![image](https://user-images.githubusercontent.com/2825679/108886425-cdfb4f80-75bd-11eb-97e1-cd8657ba78da.png)

**Comment by Moc** [comment]
Please clear all caches everyone (browser and e107). 

I cannot reproduce it thusfar

**Comment by tgtje** [comment]
Run a quick update to php 7.4.1 (highest available). All fine, switched back to php 7.3 Keeps the correct outcome..
Did delete the browser cache and cookie anyway.. Unsure what exactly causes it. Anyway.. Issue for me resolved
Testcase Edge browser, last accessed site on 24-01 (so cookie should not be involved) all fine. Php version incompatability..?

**Comment by realmontazeri** [comment]
I am not facing such problem on the latest git version.

**Comment by rica-carv** [comment]
@tgtje My issues are still there with PHP 7.4.5.
@Moc Cleaned all caches, problem still there.

I'm still using Firefox Developer Edition 85.0b4 (64-bit)....

**Comment by Moc** [comment]
@rica-carv did you try other browsers?

**Comment by rica-carv** [comment]
@Moc Yes, on Edge i got the same issue....

**Comment by tgtje** [comment]
@rica-carv Maybe already done but did you delete all cookies (in each browser)?(longer period). I cleaned all (caches and browsers,cookies), and upgraded to php 7.4.10 >result..  FF 86.0 64b also fine

**Comment by rica-carv** [comment]
@tgtje Cleaned cookies, caches, and still the same...

**Comment by CaMer0n** [comment]
@rica-carv What plugins do you have installed?

**Comment by rica-carv** [comment]
@CaMer0n Besides core ones, i've got only my own plugin, wich i'm trying to upgrade to PHP 7.x

**Comment by Jimmi08** [comment]
@rica-carv 
check if your plugin doesn't have e_meta or e_header with any css included.  
 And check console for what is moving your icon: 

![image](https://user-images.githubusercontent.com/5429548/109864138-c2192880-7c62-11eb-8366-aa1baac43cb0.png)

**Comment by rica-carv** [comment]
> 
> 
> @rica-carv
> check if your plugin doesn't have e_meta or e_header with any css included.
> And check console for what is moving your icon:
> 
> ![image](https://user-images.githubusercontent.com/5429548/109864138-c2192880-7c62-11eb-8366-aa1baac43cb0.png)

@Jimmi08 I  do have css loaded in e_header (i need it there), but it's minilam, and it's not messing at all with the icon or the popup display....

![imagem](https://user-images.githubusercontent.com/17130530/109865202-b1b17f80-7c5b-11eb-809e-8fe28ae8eccf.png)

This issue must be related with the github version, i'll try to revert back to the latest stable to check if i'm wrong or not...

**Comment by CaMer0n** [comment]
@rica-carv Try changing the admin skin. Does it make a difference?

**Comment by rica-carv** [comment]
@CaMer0n All admin themes come up the same, no tooltip...

The weirdest stuff is that bootstrap tooltip does open...
![imagem](https://user-images.githubusercontent.com/17130530/109869491-d3f9cc00-7c60-11eb-95e0-e2a99623555f.png)

**Comment by CaMer0n** [comment]
@rica-carv Thanks. Do you have any caching enabled?

**Comment by rica-carv** [comment]
@CaMer0n No, i've got caches turned off..., Even with them on, the issue persists...

Don't bother, right now it's not very important to me, i'll try later with a clean install...

**Comment by rica-carv** [comment]
Download from e107.org site, fresh install, all ok:
![imagem](https://user-images.githubusercontent.com/17130530/110151214-1db8f280-7dd8-11eb-9d4b-21559715868e.png)

Download from current github. Icons gone, tooltip appears on the field itself:
![imagem](https://user-images.githubusercontent.com/17130530/110151329-404b0b80-7dd8-11eb-9374-da701575cc1c.png)

Same machine, same localhost, same browser...
I've even tested in diferent languages, the same issues persists....

**Comment by Jimmi08** [comment]
Check this
![image](https://user-images.githubusercontent.com/5429548/110152419-02eb7b80-7de2-11eb-94e7-5e490c3ac636.png)

With ON:
![image](https://user-images.githubusercontent.com/5429548/110152720-5c53aa80-7de2-11eb-98c5-3a737d9f1e32.png)


With OFF:
![image](https://user-images.githubusercontent.com/5429548/110152662-4e9e2500-7de2-11eb-8248-db76d307fc98.png)

**Comment by rica-carv** [comment]
@Jimmi08
Github version, setting saved, before cleaning cache:
![imagem](https://user-images.githubusercontent.com/17130530/110164244-00405480-7de9-11eb-9d4e-0770c9fb58b7.png)
After cleanig cache, zilch, nada.....
![imagem](https://user-images.githubusercontent.com/17130530/110164303-10583400-7de9-11eb-8bd0-eabb06d5888d.png)

Didn't try with the e107.org files, because it doesn't has that setting....

**Comment by Jimmi08** [comment]
Did you run a core update? /e107_admin/e107_update.php

**Comment by rica-carv** [comment]
No, these are fresh installs....

**Comment by CaMer0n** [comment]
@rica-carv That can't be a fresh install from e107.org (v2.3.0) : 

![image](https://user-images.githubusercontent.com/2825679/110175232-4cbe6c80-7db6-11eb-8b22-8aee9ff06496.png)

It appears the issue is no longer "tool tips don't display when I hover on help icon" but rather "help icon does not display" .. is that correct?

**Comment by Jimmi08** [comment]
@CaMer0n from his screens, he is not able to save prefs for displaying help icon.  Not clear if he doesn't know what prefs to set (latest one) or prefs is not saved after the update.

**Comment by rica-carv** [comment]
Err, sorry, just some clarifications...
@CaMer0n You're correct, i switched the images. The one with e107-master in site URL is the latest github files.
My mistake, sorry...

@Jimmi08 Not quite, i indeed can save the prefs, the issue is that after i have to clean caches to get the saved prefs running. And therefore get rid of the help icon. Anyway, it's working on latest github files.... Closing.....

**Comment by CaMer0n** [comment]
@rica-carv Thanks for the update. To save yourself more trouble, you could install TortoiseGit and just sync with github direct from the windows explorer with one mouse click. It has the advantage of removing deprecated files and only downloading what changed.

**Comment by Moc** [comment]
I can also recommend using Github Desktop: https://desktop.github.com/

**Comment by rica-carv** [comment]
@CaMer0n @Moc Thanks for the tips, but i work mainly with a usb pen. I've got all my files and development area in a pen, so i can do any changes whenever i need, on any pc....
Those apps have to be setup on the machine, so....
If there was a portable (for use in usb pen), i'll give it a go...

Thanks anyway....

**Comment by CaMer0n** [comment]
@rica-carv You may want to experiment with this: https://github.com/sheabunge/GitPortable
