### ISSUE TITLE
forum bbcode editor parse only first bbcode 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4403]
## Bug Description
forum bbcode editor parse only first bbcode.  It works in 2.3.0. 

![image](https://user-images.githubusercontent.com/5429548/108484284-f91f2f80-729b-11eb-933e-96e54037fd98.png)
![image](https://user-images.githubusercontent.com/5429548/108484598-44d1d900-729c-11eb-85c0-4bae7e38e303.png)

The same for topic and for the post.

## How to Reproduce
```
Test

[code]first line code[/code]

[code]second line code
[/code]
```
or
```
Test

[code]first line code[/code]

[code]second line code[/code]
```

## Expected Behavior
![image](https://user-images.githubusercontent.com/5429548/108484108-c7a66400-729b-11eb-8f07-6ae46773841a.png)

 PHP 7.4 latest git, tested with bootstrap3 theme

**Comment by CaMer0n** [comment]
@Jimmi08 Very clear. Thank you.
