### ISSUE TITLE
Update loop after installing hero plugin

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4407]
With the latest e107git version and php7.4
![Screenshot](https://user-images.githubusercontent.com/10089685/108625030-d0df2e80-745d-11eb-8e9b-5e3808770483.png)

**Comment by CaMer0n** [comment]
@realmontazeri Please enable debug (and developer mode)  so we can see what is triggering the update. Thanks

**Comment by realmontazeri** [comment]
@CaMer0n Here are the results before and after updating:
![Screenshot1](https://user-images.githubusercontent.com/10089685/108638069-ab284880-74a2-11eb-9fde-7fefa3b839b2.png)
![Screenshot2](https://user-images.githubusercontent.com/10089685/108638074-ad8aa280-74a2-11eb-9f77-297fe1e3932e.png)

**Comment by CaMer0n** [comment]
@realmontazeri Please go here (with debug enabled) : /e107_admin/db.php?mode=verify_sql and select "hero". then share the screenshot. Thanks.

**Comment by realmontazeri** [comment]
@CaMer0n here are the results:

![Screenshot1](https://user-images.githubusercontent.com/10089685/109391000-1605d380-792a-11eb-9763-fba7ebe1cdcb.png)
![Screenshot2](https://user-images.githubusercontent.com/10089685/109391006-1b631e00-792a-11eb-99ed-d6518241e550.png)

**Comment by CaMer0n** [comment]
@realmontazeri Thanks. The commit should fix it. Please re-open if necessary.
