### ISSUE TITLE
Admin area notification settings

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4408]
I have couldn't find any options related to admin area notifications in preference and the following popup shows up constantly so it would be useful to have such options.
![Screenshot](https://user-images.githubusercontent.com/10089685/108625818-2584a880-7462-11eb-8734-83ec9dbc661b.png)

**Comment by Jimmi08** [comment]
Just close it and it shouldn't bother you anymore... at least it doesn't do for me.

**Comment by realmontazeri** [comment]
@Jimmi08 I close it and It comes back again, deleting cookies didn't help also.
