### ISSUE TITLE
An option to hide signup/signin menu

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4409]
Sometimes need to hide signup/signin entries because in some cases registration/login can be restricted to staffs only and this item is currently missing in the list:
![Screenshot](https://user-images.githubusercontent.com/10089685/108626265-82815e00-7464-11eb-88c9-6e293c68ca69.png)

**Comment by Jimmi08** [comment]
It doesn't work this way. 

This should be enough:
![image](https://user-images.githubusercontent.com/5429548/108627643-fae12280-7456-11eb-8007-4f0c6e8f9d79.png)

The rest is a theme problem.  Your picture is from theme preferences. it has nothing with core.
