### ISSUE TITLE
Hero slider arrows incorrect position

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4412]
Desktop 1366x768

![Screenshot1](https://user-images.githubusercontent.com/10089685/108638443-892fc580-74a4-11eb-9ed4-e64f4230221e.png)

Mobile - looks ok

![Screenshot2](https://user-images.githubusercontent.com/10089685/108638469-a795c100-74a4-11eb-8635-bcd53d61c259.png)

**Comment by realmontazeri** [comment]
This issue has been fixed #cb95b4b @CaMer0n Thanks!

**Comment by CaMer0n** [comment]
Great! Thank you! :+1:
