### ISSUE TITLE
Hiding currentpage navbar and the title

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4415]
Need an option to hide this navbar and the page title because in some cases like introducing products doesn't look professional to have this on top the page.

![Screenshot](https://user-images.githubusercontent.com/10089685/108736470-e4b28f80-7546-11eb-8e43-bc01b4e45bdd.png)

**Comment by CaMer0n** [comment]
@realmontazeri This depends a lot on the theme. Typically you would have a layout without these elements and then you would use `Theme Manager > Site Theme` visibility filter to set which pages should use that layout.
