### ISSUE TITLE
Removing /page in custom pages URLs

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4416]
There is no any option in Manage Site URLs >> Profiles to remove /page before /page-title because it would be more logical to see the page title right after domain address.

**Comment by CaMer0n** [comment]
@realmontazeri This already exists: 

![image](https://user-images.githubusercontent.com/2825679/108745162-a047d500-74ef-11eb-9938-59c532e3d247.png)

**Comment by realmontazeri** [comment]
@CaMer0n Thank you!
