### ISSUE TITLE
Can't load index.php

### ISSUE THREAD

**Issue by Ouzelot** [e107inc/e107#4420]
Hey!
I'm a complete newbie to php and e107 please bother with me.

So I finished the install process of e107 and configured everything. But when I try to load up the index.php (with localhost/e107/index.php) I get this error message:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function error_handler::handle_error(), 4 passed and exactly 5 expected in C:\xampp\htdocs\e107\class2.php:2559 Stack trace: #0 C:\xampp\htdocs\e107\e107_handlers\core_functions.php(135): error_handler->handle_error(8192, 'Required parame...', 'C:\\xampp\\htdocs...', 3034) #1 C:\xampp\htdocs\e107\e107_handlers\core_functions.php(135): require_once() #2 C:\xampp\htdocs\e107\class2.php(266): e107_require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\e107\index.php(58): require_once('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\e107\class2.php on line 2559

I tried to solve the problem myself but didn't suceed.
I attached my class2.php file down below.

[class2.zip](https://github.com/e107inc/e107/files/6027987/class2.zip)

Thanks for any help! :)

**Comment by Moc** [comment]
- Are you using version 2.3.0 or the latest files from GitHub?
- Which PHP version are you using?

**Comment by Ouzelot** [comment]
> * Are you using version 2.3.0 or the latest files from GitHub?
> * Which PHP version are you using?

I'm using version 2.3.0

**Comment by Ouzelot** [comment]
> > * Are you using version 2.3.0 or the latest files from GitHub?
> > * Which PHP version are you using?
> 
> I'm using version 2.3.0

Sorry, and PHP version 8.0.2.0

**Comment by Moc** [comment]
Okay. I assume you using PHP version 8. We are still working on full compatability of e107 with PHP 8. 

- In case you want to continue using PHP 8, please use the latest files from Github: https://github.com/e107inc/e107/archive/master.zip but please do not that there may still be issues. 
- If you want to use e107 without issues, please use PHP version 7.

**Comment by Ouzelot** [comment]
> Okay. I assume you using PHP version 8. We are still working on full compatability of e107 with PHP 8.
> 
> * In case you want to continue using PHP 8, please use the latest files from Github: https://github.com/e107inc/e107/archive/master.zip but please do not that there may still be issues.
> * If you want to use e107 without issues, please use PHP version 7.

Okay thanks I'll try that!

**Comment by Moc** [comment]
Let me know how it worked out!

**Comment by Ouzelot** [comment]
> Let me know how it worked out!

It worked thank you so much! 👍
