### ISSUE TITLE
Problem with filter search - it doesn't work for national characters

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4427]
## Bug Description
Search in Admin UI doesn't work for me
I am using table collation utf8_slovak_ci, I tested this on a fresh install in news.

## How to Reproduce
- I added the word `dôverný` in the news title... 
 

![image](https://user-images.githubusercontent.com/5429548/109399654-64c06700-7944-11eb-8eeb-e4ad2dd0dee7.png)

![image](https://user-images.githubusercontent.com/5429548/109399661-71dd5600-7944-11eb-9bba-daab9378838d.png)

After clicking on the filter button, I can see the wrong query (the national character is stripped) 

` QRY=SELECT n.*, nc.category_name, nc.category_sef, u.user_id,u.user_name FROM `e107_news` AS n LEFT JOIN `e107_news_category` AS nc ON n.news_category = nc.category_id LEFT JOIN `e107_user` AS u ON n.news_author = u.user_id WHERE ( n.news_thumbnail LIKE '%dve%' OR n.news_title LIKE '%dve%' OR n.news_summary LIKE '%dve%' OR n.news_meta_keywords LIKE '%dve%' OR n.news_meta_description LIKE '%dve%' OR n.news_sef LIKE '%dve%' ) ORDER BY news_id desc LIMIT 0, 10
`
- filter value is changed too:
![image](https://user-images.githubusercontent.com/5429548/109399714-c385e080-7944-11eb-87ea-50536aefd728.png)

Thanks

**Comment by Jimmi08** [comment]
That problem is in e_QUERY

URL looks:
`newspost.php?searchquery=život&filter_options=&mode=main&action=list&etrigger_filter=etrigger_filter`
but e_QUERY has value:
`searchquery=ivot&filter_options=&mode=main&action=list&etrigger_filter=etrigger_filter`

život vs ivot

**Comment by Jimmi08** [comment]
My suggestion:

- either don't use e_QUERY for searching  and define a new value for example e_SEARCHQUERY, if e_QUERY is filtered this way because of safety reasons

or change that filter:
`$e_QUERY = filter_var($e_QUERY, FILTER_SANITIZE_FULL_SPECIAL_CHARS);`

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 I have added ```FILTER_SANITIZE_FULL_SPECIAL_CHARS```. However, admin-ui has other filtering in place that needs to be addressed in order to correct this issue.

**Comment by Jimmi08** [comment]
Yeah, next it fails on parse_str() on searchquery key.

**Comment by Jimmi08** [comment]
@CaMer0n Solved for now in Admin UI parseRequest()

```
       if(is_string($request_data))
		{
			parse_str($request_data, $request_data);
		}
        
        $value_searchquery = isset($_GET['searchquery']) ? e107::getParser()->post_toForm($_GET['searchquery']) : "";
        
	$this->_request_qry = (array) $request_data;
        $this->_request_qry['searchquery'] = $value_searchquery;
```
