### ISSUE TITLE
Admin UI - check access for inline editing

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4432]
## Motivation
Possibility to use the full functionality of Admin UI in admin area for frontend 

## Proposed Solution

Inline editing should respect the same rules for access as the EDIT button

if access for 'main/edit'  is set, then inline editing should be available only if the user has access to edit action.  

Now edit button is hidden, but inline editing doesn't: 

![image](https://user-images.githubusercontent.com/5429548/109681869-31691c80-7b7e-11eb-8c14-0d5573007040.png)

Yes, I know I can fix this manually in init() for fields, but I think this check should be done by default.

Thanks

**Comment by rica-carv** [comment]
@Jimmi08 Does inline editing works with you? Mine is not working on my plugin admin list mode... It accepts the editing, but it doesn't records the changes made inline....

**Comment by Jimmi08** [comment]
> @Jimmi08 Does inline editing works with you? Mine is not working on my plugin admin list mode... It accepts the editing, but it doesn't records the changes made inline....

I use latest 2.3.1 and yes, it works. Check the console for javascript errors.

**Comment by rica-carv** [comment]
> 
> 
> > @Jimmi08 Does inline editing works with you? Mine is not working on my plugin admin list mode... It accepts the editing, but it doesn't records the changes made inline....
> 
> I use latest 2.3.1 and yes, it works. Check the console for javascript errors.

@Jimmi08 Now it works, go figure! I'm getting beserk with this pc....

**Comment by Moc** [comment]
Closing this because using the Admin UI on the frontend is not supported. 

If the issue occurs in the Admin Area, then please re-open.
