### ISSUE TITLE
Removing Shutdown Stuff like Google+

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4433]
Basically, Google+ is no more, and I came across it in Admin Area -> News -> Create News -> Meta

**Comment by Moc** [comment]
Are you using the latest files from Github? Can you show us a screenshot of where you can see it?

**Comment by Jimmi08** [comment]
Metatag plugin?

**Comment by CaMer0n** [comment]
@Jimmi08 Good point. This is a plugin tab. There is no "meta" tab in "Create News". 
Closing.
