### ISSUE TITLE
page with password is not rendered correctly

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4437]
## Bug Description
page with password protection looks like this:

![image](https://user-images.githubusercontent.com/5429548/110200617-26084080-7e5f-11eb-8a83-c5389bb26917.png)

## How to Reproduce
1. Go to pages
2. Set password
3. Display page
 
PHP 8.  core page template

**Comment by CaMer0n** [comment]
hmm, something tells me this is related to that switch from `simpleParse()` to `parseTemplate()`.

**Comment by Jimmi08** [comment]
@CaMer0n correct, just this one in public function renderPage($template, $vars = null)

![image](https://user-images.githubusercontent.com/5429548/110495409-c4f99a80-80f4-11eb-82b4-3a1c2796dcaf.png)

$vars  is:
```
e_vars Object
(
    [_data:protected] => Array
        (
            [title] => ***
            [message] => 
            [caption] => ***
            [label] => ***
            [password] => ***
            [icon] => ***
            [submit] => ***
            [form_open] => ***
            [form_close] => ***
        )

    [_params:protected] => Array
        (
        )

    [_field_id:protected] => 
)
```
so simple parse should stay there.

and  $this->batch is normal cpage_shortcodes Object.

**Comment by CaMer0n** [comment]
@Jimmi08 Committed. untested. Please close if fixed.

**Comment by Jimmi08** [comment]
Thank you, tested, it works now.
