### ISSUE TITLE
{ALERTS} 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4440]
## Motivation
Possibility to add some enwrap code for this shortcode 

In bootstrap3 theme you are doing this:
```
  <div class="container">
     {ALERTS}
  </div>
```
It is wrong because there is an empty div tag displayed  if there is no alert message

Without it, it can look like this:
![image](https://user-images.githubusercontent.com/5429548/110441433-0fa9f100-80ba-11eb-8ce2-6af0f2b11a62.png)

Theme is full width, but plugin is boxed.

## Proposed Solution
add the parameter to enwrap alert message like hero plugin does (tag + class)

**Comment by CaMer0n** [comment]
@Jimmi08 For now, just use `e107::scStyle()`: 

```
class theme implements e_theme_render
{

    public function init()
    {
		$wrap = array(
			'ALERTS' => '<div class="container">{---}</div>'
		);
		
		e107::scStyle($wrap);

...
```

**Comment by Jimmi08** [comment]
Perfect. I don't ask for more... in 90 percent ALERTS are part of the container already...
