### ISSUE TITLE
Test SMTP Connection not working and failed to send mail after sign up and forgot password 

### ISSUE THREAD

**Issue by turtleking1** [e107inc/e107#4441]
Hello 
I have e107 website running on Ubuntu 20.04.2 using xampp 7.4.15 / PHP 7.4.15 I have a mail server setup and working I tried sending test email and it worked fine but when when I try to register on my website I get a error
(There was a problem, the registration mail was not sent, please contact the website administrator.)
I tried clicking on Test SMTP Connection and nothing shows up 
is there is a way to solve this problem 

e107 version 2.3.0

Thank you

**Comment by tgtje** [comment]
Was going to answe on help, just info : did you also try Sendmail (since Ubuntu..unfamiliar).

**Comment by turtleking1** [comment]
> Ubuntu..unfa
Hello tgtje
I haven't tried Sendmail yet but im going to try it today

**Comment by turtleking1** [comment]
> Was going to answer on help, just info : did you also try Sendmail (since Ubuntu..unfamiliar).

Problem solved using sendmail solved the problem and now everything works fine 
Thank you
