### ISSUE TITLE
Can no longer select the site theme's stylesheets

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4443]
## Bug Description
"**Stylesheets:**" has disappeared from `/e107_admin/theme.php?mode=main&action=main`.

Before:
![image](https://user-images.githubusercontent.com/1364268/110576888-2e929c80-8127-11eb-972c-82402425e0d8.png)

After:
![image](https://user-images.githubusercontent.com/1364268/110577364-1f601e80-8128-11eb-9ede-0fa35d238e08.png)

Regression was introduced in 3bb541a6d9fb0204a84d7307666d3a8823bb6f00 as a fix for #4228:
```
3bb541a6d9fb0204a84d7307666d3a8823bb6f00 is the first bad commit
commit 3bb541a6d9fb0204a84d7307666d3a8823bb6f00
Author: Cameron <e107inc@gmail.com>
Date:   Sat Feb 13 17:56:53 2021 -0800

    Issue #4228 Theme manager - display only the relevant stylesheets for the selected scope.

 e107_handlers/theme_handler.php       | 90 +++++------------------------------
 e107_tests/tests/unit/e_themeTest.php | 22 ++++++++-
 2 files changed, 32 insertions(+), 80 deletions(-)
```

`git bisect log`:
```
git bisect start
# good: [645c05cfbfd4962ea663c8540aa8444dffceb847] PHP8 Compatibility Fixes
git bisect good 645c05cfbfd4962ea663c8540aa8444dffceb847
# bad: [9c9dcb5e5207aa87703da46cd7d32433513c7a65] Issue #4437 Parsing page with password.
git bisect bad 9c9dcb5e5207aa87703da46cd7d32433513c7a65
# good: [04bbad449aa00723975c72b2a99f134fdecbe0d9] Test admin scripts are parsing correctly.
git bisect good 04bbad449aa00723975c72b2a99f134fdecbe0d9
# good: [0fd7ee648256d0fac41a752a9e8fe545fb4e6c9c] Fixes faulty parsing of _GET when debug is activated. Pref editor will now use var_export on arrays when debug mode is active.
git bisect good 0fd7ee648256d0fac41a752a9e8fe545fb4e6c9c
# bad: [340ff05fcde137f1932bc0b5b4c717c07a23d640] Bootstrap5 markup added to download item pagination. Fallback added to e107.css
git bisect bad 340ff05fcde137f1932bc0b5b4c717c07a23d640
# bad: [fc683be4e2b7f602eb032be9395ae9f3df8bbe45] Fix dark drop-down menu
git bisect bad fc683be4e2b7f602eb032be9395ae9f3df8bbe45
# good: [a57c5981686d553db6b50c3fcd0cbe5fdb6b51db] Added missing TinyMce4 files.
git bisect good a57c5981686d553db6b50c3fcd0cbe5fdb6b51db
# good: [5ec3aa7245df1583e722f427b407e5858f6b3280] Set 'front' by default if theme.xml library scope is missing.
git bisect good 5ec3aa7245df1583e722f427b407e5858f6b3280
# bad: [e6bdc0e6ecd632781dc3c2a01ab1c7bd9fe74071] Fix for 'user' stylesheets in Theme Manager.
git bisect bad e6bdc0e6ecd632781dc3c2a01ab1c7bd9fe74071
# good: [6662b04323343af534251dda67aa8a4d972b4f5d] Menu-Manager styling.
git bisect good 6662b04323343af534251dda67aa8a4d972b4f5d
# bad: [b0300f93bf0e3bb5563627faa8719bb94885c469] Changed load order of Menus and Theme Layout detection.
git bisect bad b0300f93bf0e3bb5563627faa8719bb94885c469
# bad: [3bb541a6d9fb0204a84d7307666d3a8823bb6f00] Issue #4228 Theme manager - display only the relevant stylesheets for the selected scope.
git bisect bad 3bb541a6d9fb0204a84d7307666d3a8823bb6f00
# first bad commit: [3bb541a6d9fb0204a84d7307666d3a8823bb6f00] Issue #4228 Theme manager - display only the relevant stylesheets for the selected scope.
```

## How to Reproduce
1. Set [this theme](https://e107.org/themes/?id=957) as the site theme.
2. Go to `/e107_admin/theme.php?mode=main&action=main`.
3. Observe that there is no section called "Stylesheets:".

## Expected Behavior
There should be a picker to select different stylesheets that come with the theme.
This ability is officially documented in https://e107.org/developer-manual#theme-xml

### PHP Operating System

```
Linux host1.xenfinity.com 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
```

### PHP Version

```
PHP Version 8.0.2
```

### PHP Modules

```
amqp
apcu
ast
bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dba
dom
ds
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libsmbclient
libxml
mailparse
mbstring
memcached
msgpack
mysqli
mysqlnd
OAuth
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
psr
raphf
readline
redis
Reflection
rrd
session
shmop
SimpleXML
smbclient
snmp
soap
sockets
sodium
solr
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
uuid
xdebug
xhprof
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib
zmq
```

### Client Information

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0

**Comment by Deltik** [comment]
@Jimmi08: I tried this, but it did not restore the "Stylesheets:" section (e107 revision 9c9dcb5e5):

```diff
deltik@host1:~/public_html/e107_themes/jayya$ git diff
diff --git a/theme.xml b/theme.xml
index 4215812d..4916a74a 100644
--- a/theme.xml
+++ b/theme.xml
@@ -13,10 +13,10 @@
                <image>preview.jpg</image>
        </screenshots>
        <stylesheets>
-               <css file="style.css" name="Default" />
-               <css file="moreblue.css" name="Inspired by Debian MoreBlue Orbit" />
-               <css file="canvas.css" name="Classic Jayya alternative stylesheet" />
-               <css file="pepper.css" name="Classic Jayya alternative stylesheet" />
+               <css file="style.css" name="Default" scope="all" />
+               <css file="moreblue.css" name="Inspired by Debian MoreBlue Orbit" scope="all" />
+               <css file="canvas.css" name="Classic Jayya alternative stylesheet" scope="all" />
+               <css file="pepper.css" name="Classic Jayya alternative stylesheet" scope="all" />
        </stylesheets>
        <layouts>
                <layout name='3_column' title='3 Columns' default='true' />
```

**Comment by Jimmi08** [comment]
@Deltik Did you clear cache? My result (downloaded that theme from e107.org, PHP 7.4

![image](https://user-images.githubusercontent.com/5429548/110745487-a05c0a80-823b-11eb-8a7e-16e320badf44.png)

Or you can try this:
```
 scope="front,admin,wysiwyg"
```

**Comment by Deltik** [comment]
You're right about the cache, @Jimmi08.  I'm surprised that that page would present cached information.

**Comment by Jimmi08** [comment]
> You're right about the cache, @Jimmi08. I'm surprised that that page would present cached information.

For any change in theme.xml, you need to clear the cache. I already asked at least in debug mode/developer to always update this...   Or maybe a button to clear cache directly in the theme manager would be the solution if the cached version is different from the actual one.

**Comment by CaMer0n** [comment]
Cache is automatically cleared after upgrade. Closing this.

**Comment by Deltik** [comment]
@CaMer0n: The issue is concerning a change in behavior, especially one that is not documented [here](https://e107.org/developer-manual#theme-xml).  It is not about the cache.

**Comment by Deltik** [comment]
https://e107.org/developer-manual#theme-xml shows:
```xml
<?xml version="1.0" encoding="utf-8"?>
<e107Theme name="bootstrap" version="1.0" date="2012-12-01" compatibility="2.0">
…
    <stylesheets>
        <css file="style.css" name="Default"  />
        <css file="css/superhero.css" name="Superhero" />
    </stylesheets>
…
</e107Theme>
```

It makes no mention of the `scope` attribute in `e107Theme » stylesheets » css`

**Comment by CaMer0n** [comment]
@Deltik Thanks, I have noted the issue.

**Comment by Deltik** [comment]
To be clear, are all themes expected to add that `scope` attribute, or is e107 going to display stylesheets without the `scope` attribute?

**Comment by Deltik** [comment]
[Fix](https://github.com/e107inc/e107/commit/fb3888abc3ee7b196a93d0916e0d0de23bf33b4e) verified.  Thank you, @CaMer0n!

**Comment by Moc** [comment]
I'll get this updated in docs

**Comment by Jimmi08** [comment]
@CaMer0n Does it work for him because he uses style.css as the first style?  

```
    <stylesheets>
        <css file="skins/default.css" name="Default" scope="front,admin,wysiwyg" />
        <css file="skins/green.css"  name="Only for ***"  scope="front,admin,wysiwyg" />
        <css file="skins/orange.css" name="Orange"   scope="front,admin,wysiwyg"  />
	 <css file="skins/red.css" name="Red"   scope="front,admin,wysiwyg"  />
    </stylesheets>
```

![image](https://user-images.githubusercontent.com/5429548/110971777-93363d00-835b-11eb-8641-0187a731381d.png)

Adding  `default="true"` didn't help.

**Comment by CaMer0n** [comment]
> Does it work for him because he uses style.css as the first style?

I don't think so. 

>Adding default="true" didn't help.

Didn't help what? What am I meant to conclude from your code/screenshot @Jimmi08 ?

**Comment by Jimmi08** [comment]
That no css is marked as default, so no one is loaded.

**Comment by CaMer0n** [comment]
@Jimmi08 You should consider creating a separate feature request for this. (ie. support for manually settings the 'default' css in `<stylesheets>`) . 

`style.css` is (and has always been) the default - the order shouldn't matter.
