### ISSUE TITLE
Plugin XML Lan's not correct....

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4444]
Something happening with language parsing in plugins install area....

![imagem](https://user-images.githubusercontent.com/17130530/110676577-03ae5400-81cc-11eb-9208-fc885abe3015.png)

Portuguese_global lan of newsfeed plugin (green):
`define("LAN_PLUGIN_NEWSFEEDS_DESCRIPTION", "Este plugin irá recuperar feeds rss de outros sites e exibi-los de acordo com suas preferências.");`
Plugin.xml of newsfeed plugin (green):
`	<description lan="LAN_PLUGIN_NEWSFEEDS_DESCRIPTION">This plugin will retrieve rss feeds from other websites and display them according to your preferences.</description>`

Correctly displays the portuguese LAN, since admin area is in Portuguese

Portuguese_global lan of my plugin (red):
`define("LAN_PLUGIN_PHILCAT_DESCRIPTION","Este plugin é um sistema de Catálogo Filatélico com todos os recursos");`
Plugin.xml of my plugin (red):
`<description lan="LAN_PLUGIN_PHILCAT_DESCRIPTION">This plugin is a fully featured Philatelic Catalogue system</description>`

Incorrectly displays the english xml text....

Is this a bug or am i doing somethig wrong here that i can't see?
Both language files are in the languages folder, not in any subfolder....

**Comment by CaMer0n** [comment]
@rica-carv What is the folder for your plugin? Also, did you remove the plugin entry from the plugins database table after adding LANs to your plugin?

**Comment by rica-carv** [comment]
@CaMer0n The folder is located in the plugins folder, and is called "philcat".
A didn't remove any entry from the database after adding LAN's to the plugin.
Maybe the only missing thing is that i'm only working on the Portuguese LAN files, and indeed, the English LAN files are way outdtated.....
Can it be that????

**Comment by rica-carv** [comment]
@CaMer0n I've tried that, and no go... Still the same... Furthermore, i noticed another strange behavior. When on the plugins admin page, the entry for my plugin on the dropdown menu, is in English, but when i go to the plugin page, the dropdown menu entry becomes Portuguese by magic....

**Comment by CaMer0n** [comment]
@rica-carv Have you checked the pref `lan_global_list` ? Is your plugin listed in it?

**Comment by rica-carv** [comment]
> 
> 
> @rica-carv Have you checked the pref `lan_global_list` ? Is your plugin listed in it?

@CaMer0n No, it's not listed there....

**Comment by rica-carv** [comment]
I don't know if its related or not, but the e_dashboard.php file shouldn't load automatically lan's???
In the core plugins, i don't see lans loaded in e_dashboard files, so i did mine like that. Previously it worked, but for some reason it stopped working and now i have to load the lans inside the e_dashboard.php file.
Is this the correct way to do it, load lans in the file?
