### ISSUE TITLE
Activating counter_menu

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4447]
## Bug Description
when activating  (site-ifo) counter menu > error

## How to Reproduce
activate (site-ifo) counter menu
4. See error  (description > see Add. information below)

## Expected Behavior
working state

## Additional Information
The call requests LOG plugin + file  (but is no longer present in core plugins).

`e107_plugins/siteinfo/counter_menu.php
	require_once(e_PLUGIN."log/consolidate.php");
	$logObj = new logConsolidate;`

**Comment by Moc** [comment]
I can't reproduce this with the latest version. 

This check already verifies if the Statistics logging (log) plugin is installed and active: 
```php
if (isset($pref['statActivate']) && $pref['statActivate'] == true) 
```

In case the log plugin is not present, the pref won't be active either, so the following message is displayed: 

![image](https://user-images.githubusercontent.com/577978/147101407-9a687ea4-957c-4c3b-933e-42c638f6f3ed.png)
