### ISSUE TITLE
Lazy toImage???

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4448]
I notice that this line of code exists in e_parsetest.php:
`$result4 = $this->tp->toImage($src, ['loading'=>'lazy']);`

And i assume that we can use the lazy loading method for displaying images.
I've tested it, but for me, there's a small glitch: What if i want to display another image as a placeholder while the definitive image is not loaded by the lazy script???
I've tried with placeholder, and nothing.....

**Comment by CaMer0n** [comment]
@rica-carv Perhaps you can share the html you're trying to achieve?

**Comment by rica-carv** [comment]
@CaMer0n Currently i'm using this line of PHP code, with the lazy jquery library (https://github.com/eisbehr-/jquery.lazy/archive/master.zip) that is in the e107 e_web/lib folder:
`return ("<img class='lazy img-responsive' data-src='".e_PLUGIN_ABS."philcat/".$this->pref['filepath'].$this->var['pais']."/d/".$this->var['cod'].".jpg' data-popimage='".$this->var['cod']."' src='".e_PLUGIN_ABS."philcat/images/miss.jpg' alt='".$this->var['cod']. "' title='' style='vertical-align:middle'>");`

The final outcome, if image exists, is this:
`<img class="lazy thb_many imagepop" loading="lazy" data-popimage="1452" src="/selospt2021_dev/e107_plugins/philcat/media/1/t/1452.jpg" alt="1452" title="" style="vertical-align: middle; display: inline-block;">`

If there's no image, the outcome is this:
`<img class="lazy thb_many" loading="lazy" data-src="/selospt2021_dev/e107_plugins/philcat/media/3/t/3833.jpg" data-popimage="3833" src="/selospt2021_dev/e107_plugins/philcat/images/miss.jpg" alt="3833" title="" style="vertical-align:middle">`

Note that while the image is not loaded, the `miss.jpg` is in place of it....

**Comment by rica-carv** [comment]
@rica-carv Humm, got it..... 👍
