### ISSUE TITLE
theme.php vs theme.html  and e_ROUTE + THEME_LAYOUT problem

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4449]
## Motivation
Fix for older themes without theme class and HTML layouts

## Proposed Solution
There are 2 types of themes now:
- with theme.html and theme class in theme.php   (any other combination should be fixed)
- with theme.php only, legacy way 

Because of changes related to e_ROUTE, the THEME_LAYOUT constant is not available in theme.php  without theme class.   

**Suggestion:**
Using
`e_theme::initThemeLayout(); // set THEME_LAYOUT`
in header_template.php only for HTML themes.  For older themes use it in class2.php before theme.php is used.   e_REQUEST_URL is already defined, so it works.

Use e_ROUTE in Theme Manager only for HTML themes, so this functionality will work only for new themes. Older will use an original way like before.    

One of example why this is needed for legacy themes:
`define('BODYTAG', '<body class="page '.THEME_LAYOUT.'">');`
- different class is added according to layout and it is used for styling. 

or different assets are loaded according to THEME_LAYOUT.

It causes a fatal error in PHP 8 too. 

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 It's not 100% clear what you're trying to 'fix', but I believe this may be the solution you are looking for: 

```
class theme_shortcodes extends e_shortcode
{

	function init()
	{
		define('BODYTAG', '<body class="page '.THEME_LAYOUT.'">');
	}
}
```

**Comment by Jimmi08** [comment]
@CaMer0n I am trying to fix themes for **2.0** without a complete rewrite.

BODYTAG is now solved this way, it works. Thanks. 

I suppose that only solution for this:
```
if(defined(THEME_LAYOUT) && THEME_LAYOUT == "homepage") { $pageloader = '<div class="page-loader" data-toggle="page-loader"></div>';  } 

$LAYOUT['_header_'] = '
    <!-- ======== @Region: #header ======== -->
    <div id="header">
      '.$asp_pageloader.'     
      <a id="#top" href="#content" class="sr-only">Skip to content</a>  
```
is moving this to theme shortcodes?

But this is not possible to fix?
```
if(THEME_LAYOUT == 'homepage') {
	e107::js("theme", "js/wow.js", 'jquery');
}
```

**Comment by CaMer0n** [comment]
@Jimmi08 Everything you would now put into the theme class `init()` you can put into theme_shortcodes `init()` for old themes. 
Your wow.js code should work in either `init()` method.

**Comment by Jimmi08** [comment]
All problems I run into solved for now...  Closing, if I find another example, I will ask here.  Thanks
