### ISSUE TITLE
e_emailprint.php for forum plugin doesn't work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4452]
## Bug Description
e_emailprint.php still uses old forum tables way (not old tables, but it ignores posts and changes in thread)

## How to Reproduce
1. Go to 'forum plugin'
2. Open 'e_emailprint.php' file
3. Look at the code
 
## Expected Behavior
Displaying topic posts content

It uses:
```
$thread_info = $forum->threadGet($thread_id,0,999);
$thread_info[0]
foreach($thread_info as $reply)
etc...
no $forum->PostGet()
```

**Comment by Moc** [comment]
Do you know where this is used in the forum plugin?

**Comment by Moc** [comment]
I'll update it for the V2 forum tables. 

@CaMer0n I do think we still need a V2 specification for this add-on, right? See the related issue.

**Comment by Jimmi08** [comment]
On forum_viewtopic, screen from e107.nl

![image](https://user-images.githubusercontent.com/5429548/111436047-d1d44a80-8701-11eb-856f-7f78ef166577.png)

I fixed it for my site, but It is not clear to me, if the print button is on each post, it should print just reply or all topic?

if this helps:

```
function print_item($thread_id)
{
	global $tp;
	$gen = new convert;
	include_once(e_PLUGIN.'forum/forum_class.php');
	$forum = new e107forum;

	$thread_info = $forum->threadGet($thread_id,0,999);
	$thread_name = $tp->toHTML($thread_info['thread_name'], TRUE);
	$text = "<b>Topic: ".$thread_name."</b><br />
	".$thread_info[0]['user_name'].", ".$gen->convert_date($thread_info['thread_datestamp'], "forum")."<br /><br />
	".$tp->toHTML($thread_info['thread_thread'], TRUE);
 
	$count = 1;
 
	$thread_info = $forum->PostGet($thread_id, 0, 99);

	foreach($thread_info as $reply)
	{    
		$text .= "<br /><br />Re: <b>".$thread_name."</b><br />
		".$reply['user_name'].", ".$gen->convert_date($reply['post_datestamp'], "forum")."<br /><br />
		".$tp->toHTML($reply['post_entry'], TRUE);
	}


//	return "<pre>".print_r($thread_info,TRUE)."</pre>";
	return $text;
}
```

**Comment by Moc** [comment]
Work in progress, but doing some research now. 

>  if the print button is on each post, it should print just reply or all topic?
I just tested on an old v1 installation. The print button shows up on the first (original post) only, and provides printer-friendly page with all entries in the forum topic (original post and all replies).

**Comment by CaMer0n** [comment]
@Moc Yes! I'll get something added shortly for print at least.

**Comment by Moc** [comment]
@Jimmi08 Using the latest files, printing should work again.

**Comment by Moc** [comment]
I'm closing this as I assume it's all working. If not, let me know.
