### ISSUE TITLE
Session storage in DB missing?

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#4454]
Hello, I've set up the "Session save method" in the admin panel to "Database" and changed the "Cookie/session name"

After saving, the session name changed (actually the cookie name changed) because my browser still uses a cookie with the SID.

The fact is that I can't seem to be able to find the session in the DB. I checked in the "*_online" and "*_user" tables, with no luck (user_sess field in *_user table is empty...)

I also did a full database search for a string match in the whole database, also without luck.

Where is my session being stored...?

Thank you.

**Comment by Deltik** [comment]
Sessions are stored in the `_session` table.  Here's the schema for that table:
```
mysql> SHOW CREATE TABLE e107_session\G
*************************** 1. row ***************************
       Table: e107_session
Create Table: CREATE TABLE `e107_session` (
  `session_id` varchar(255) NOT NULL DEFAULT '',
  `session_expires` int unsigned NOT NULL DEFAULT '0',
  `session_user` int unsigned DEFAULT NULL,
  `session_data` text NOT NULL,
  PRIMARY KEY (`session_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
1 row in set (0.01 sec)
```

**Comment by nesjett** [comment]
Thank you Deltik, I guess this table is created after you set "Database" as storage method.

My DB inspector had a cached version of the DB so I was not able to find that table. After a cache reload, It suddenly appeared. (DataGrip software)
