### ISSUE TITLE
Admin UI - Allow saving NULL values in db tables

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4458]
I've been trying everything so that the default admin_ui allowed me to save NULL values on specific database fileds, but it converts empty strings to 0, and doesn't accept NULL instead of empty string....
Is there anyway to store NULL values in the db table without mocking up the code???

Thanks

**Comment by CaMer0n** [comment]
@rica-carv Yes, send the string  `_NULL_` and it should save as NULL.

**Comment by rica-carv** [comment]
@CaMer0n Humm, it's not working, or i'm doing something wrong....
I'm trying to set the value of a field in a table, but in the admin ui that value comes from a dropdown select, so i've set the key value of the option to the string _NULL_, but in the database it's stored 0(zero).....

My HTML inside the select:
```
<option value="_NULL_">Não aplicável</option>
<option value="0" selected="selected">Não denteado</option>
<option value="29">10</option>
<option value="28">10¼</option>
......
```

**Comment by CaMer0n** [comment]
@rica-carv I have added a NULL value example to the blank plugin. You made sure your field (in _sql.php) allows NULL values, right?

**Comment by rica-carv** [comment]
@CaMer0n My table:
```
CREATE TABLE `e107_philcat` (
 `cod` smallint(10) unsigned NOT NULL AUTO_INCREMENT,
 `original` smallint(10) unsigned DEFAULT NULL,
 `serie` smallint(10) unsigned DEFAULT NULL,
 `tiragem` int(10) unsigned DEFAULT NULL,
 `papel` smallint(10) unsigned DEFAULT NULL,
 `dentv` smallint(10) unsigned DEFAULT NULL,
 `denth` smallint(10) unsigned DEFAULT NULL,
 `valor_facial` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
 `cor` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
 `descr` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
 `larg` tinyint(3) unsigned DEFAULT NULL,
 `alt` tinyint(3) unsigned DEFAULT NULL,
 `desenho` smallint(10) unsigned DEFAULT NULL,
 `gravura` smallint(10) unsigned DEFAULT NULL,
 `tipo_imp` smallint(10) unsigned DEFAULT NULL,
 `local_imp` smallint(10) unsigned DEFAULT NULL,
 `observacoes` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
 `pais` smallint(10) unsigned NOT NULL,
 `tipo` smallint(5) unsigned DEFAULT NULL,
 `familia` smallint(5) unsigned DEFAULT NULL,
 PRIMARY KEY (`cod`),
 KEY `series_pecas` (`serie`)
) ENGINE=MyISAM AUTO_INCREMENT=6895 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC
```
As you can see, i'm allowing nulls, since fields dentv & denth default to null.

On admin ui code, i do just a little different:
```
		'denth' =>   array ( 'title' => PHCAT_L34." (".LAN_HEIGHT.")", 'type'=>'number', 'data' => 'int', 'help' => '', 'readParms' => '', 'writeParms'=>'trClass=hidden', 'class' => 'hidden', 'thclass' => 'hidden'),
		'dentv' =>   array ( 'title' => PHCAT_L34." (".LAN_WIDTH." x ".LAN_HEIGHT.")", 'type' => 'method', 'data'=>'int', 'writeParms'=>array('show'=>1, 'tdClassRight'=>'form-inline'), 'help'=>''),

```

And in the method:
```
        $writeParms = array('_NULL_' => PHCAT_LA71, "0" => LAN_NO." ".strtolower(PHCAT_L34)) + varset(self::getdb_table('denteados', 'selarray'), array());
        return $this->renderElement('dentv', $curVal, array('tab'=>0, 'type'=>'dropdown', 'data' => 'int', 'validate' => 'rule_size', 'rule' => 'rule_size', 'error' => 'Validation Error message', 'writeParms' => $writeParms)).
        " x ".
        $this->renderElement('denth', $denthVal, array('tab'=>0, 'type'=>'dropdown', 'data' => 'int', 'validate' => 'rule_size', 'rule' => 'rule_size', 'error' => 'Validation Error message', 'writeParms' => $writeParms));
```

**Comment by CaMer0n** [comment]
Sounds like there the issue is specific to the integer "data" type.

**Comment by rica-carv** [comment]
@CaMer0n Ok, got it. Thes storage of null values is solved, bu removing the type, but the display on the form still defaults null to zero....
On the dropdown, it always shows the zero index as selected, whenever on the table is stored NULL or zero....

**Comment by Moc** [comment]
Reopening this to make sure we check if there's a bug. Not sure if removing 'type' is the right solution here.

**Comment by Jimmi08** [comment]
Correct solution is to use 'data' => 'str' . 
With type 'dropdown' you shouldn't use _int_ data if you want to save NULL (if 0 is a real value, not that nothing is selected)

**Comment by CaMer0n** [comment]
> Correct solution is to use 'data' => 'str' .

Correct. **NULL** is not an integer, so `str` (which, is the default when you remove the 'data') is the 'data' value to use when a mix of data types is required.  (ie. in this case NULL and INTEGER)

**Comment by rica-carv** [comment]
Thank you all. Ended up with @Jimmi08 solution....
Let's see how it goes...
Thanks 👍
