### ISSUE TITLE
Forum Issue Maybe?

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#4459]
I've notice an issue with the forum on the Clan Coyote website - 
![Screenshot 2021-03-22 092258](https://user-images.githubusercontent.com/5818022/112005019-5c48ef80-8af0-11eb-855e-8ab2fee9f398.png)

I thought it might have been them theme - so I went onto the test site, change it to eWL Default 1.5 theme and it's the same. So I removed the forum template from the theme folder - same thing, just the icons went back to normal - It's not showing the top nav or the menus, is this right?

**Comment by tgtje** [comment]
probably yes, but one has to know the theme also.
As seen here (https://web.archive.org/web/20191018023939/https://clancoyote.com/main/e107_plugins/forum/forum.php) date 10/18/2019  (although more than 1 year ago), at that time it was part of, instead full page. 
What did you do? update to github version or..?

Some inquiry done : is it maybe related to the changes made on february 20 ? changing header and footer?  (menu AA fix..)

**Comment by LaocheXe** [comment]
The theme in the screen shot is the cytn (old theme that was slightly converted into e107v2.xx (added bootstrap 3 style sheet).
The second theme I tried is the eWL Default 1.5 that I made last year, The site is using the latest github version.

**Comment by tgtje** [comment]
Running templates by theme or core : as noticed (eWl from org) has forum templates in it.. So they WILL differ from the github version (some styling and LAN).. (test using core, disable theme f/templates).

**Comment by LaocheXe** [comment]
I've deleted the forum templates in eWL theme, but the forum page still has no nav, and menus

**Comment by Jimmi08** [comment]
@tgtje e107.nl forum has the same issue, it is related to 2.3.1 changes... layout vs header and footer.

**Comment by Jimmi08** [comment]
@CaMer0n @Moc 

in files forum.php and forum_viewforum.php (or maybe more)  there is the class using with init() method using HEADERF. But because $HEADER and $FOOTER are not defined as globals, they are empty 

This is fix: 

```
	public function init($forum)
	{
         
		global $FORUM_TEMPLATE, $FORUM_MAIN_FORUM, $forumList, $HEADER, $FOOTER ;
```


```
/**
 * @param $FORUM_VIEW_START
 * @param $urlparms
 * @param $doNothing
 * @return array
 */
function init()
{
	// todo - remove all these globals.
	global $FORUM_VIEW_START, $urlparms, $doNothing;
	global $sc, $FORUM_VIEW_FORUM, $FORUM_VIEW_FORUM_STICKY, $FORUM_VIEW_FORUM_ANNOUNCE;
	global $forum_info, $FORUM_CRUMB;
	global $forum;
    global $HEADER, $FOOTER;
```

This theme is here:  https://github.com/LaocheXe/CYT-Theme
