### ISSUE TITLE
MySQL Query with nested REPLACE is not allowed?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#4460]
I've got a query with this code in it:
`
select distinctrow #philcat.*, CAST( REPLACE(REPLACE(REPLACE(#philcat.valor_facial,'E','00'),'C',''),'$','') AS DECIMAL(10,2)) as valor, #philcat_tipo.descr as desc_tipo........`

but for some reason, e107 throws this error when debugging the SQL:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1`

I've tested the query WITHOUT any mod in plain vanilla phpmyadim, and it works, without any errors!

Is this a e107 bug???? Maybe it doesn't allow all that nested REPLACE ????

Even in ORDER BY it throws the same error:
`ORDER BY CAST(REPLACE(REPLACE(REPLACE(#philcat.valor_facial,'E','00'),'C',''),'$','') AS DECIMAL(10,2)) +0 ASC,`

When query is executed in plain vanilla PHPmyadmin, it throws no error!

**Comment by Deltik** [comment]
The implementations of `e_db::gen()` do not handle the `#philcat` replacement if there isn't whitespace before the `#`.  Your query should run if you add a space between the `(` and the `#`.  Whether this is intentional, I'll defer to @CaMer0n to answer.

**Comment by CaMer0n** [comment]
@rica-carv Could you please post the query you tried in PhpMyadmin that didn't cause errors?

**Comment by rica-carv** [comment]
@CaMer0n 
Here it is:
`select distinctrow e107_philcat.*, e107_philcat_tipo.descr as desc_tipo, philc_dentv.descr as desc_dentv, philc_denth.descr as desc_denth, e107_philcat_papel.descr as desc_papel, e107_philcat_familias.descr as desc_familia, philc_artdes.descr as desc_desenho , philc_artgra.descr as desc_gravura, philc_impt.descr as desc_tipoimp, philc_impl.descr as desc_localimp from e107_philcat left join e107_philcat_tipo on e107_philcat_tipo.cod = e107_philcat.tipo left join e107_philcat_art as philc_artdes on philc_artdes.cod = e107_philcat.desenho left join e107_philcat_art as philc_artgra on philc_artgra.cod = e107_philcat.gravura left join e107_philcat_local as philc_impl on philc_impl.cod = e107_philcat.local_imp left join e107_philcat_imp as philc_impt on philc_impt.cod = e107_philcat.tipo_imp left join e107_philcat_denteados as philc_dentv on philc_dentv.cod = e107_philcat.dentv left join e107_philcat_denteados as philc_denth on philc_denth.cod = e107_philcat.denth left join e107_philcat_papel on e107_philcat_papel.cod = e107_philcat.papel left join e107_philcat_familias on e107_philcat_familias.cod = e107_philcat.familia WHERE e107_philcat.serie IN (868, 869, 870, 871, 872, 873, 874, 876, 877, 878, 875, 880, 879, 881, 882) AND e107_philcat.tipo=1 AND e107_philcat.familia=1 ORDER BY CAST(REPLACE(REPLACE(REPLACE(e107_philcat.valor_facial,'E','00'),'C',''),'$','') AS DECIMAL(10,2)) +0 ASC, e107_philcat.descr ASC`

Originated from plugin code:
`select distinctrow #philcat.*, #philcat_tipo.descr as desc_tipo, philc_dentv.descr as desc_dentv, philc_denth.descr as desc_denth, #philcat_papel.descr as desc_papel, #philcat_familias.descr as desc_familia, philc_artdes.descr as desc_desenho , philc_artgra.descr as desc_gravura, philc_impt.descr as desc_tipoimp, philc_impl.descr as desc_localimp from #philcat left join #philcat_tipo on #philcat_tipo.cod = #philcat.tipo left join #philcat_art as philc_artdes on philc_artdes.cod = #philcat.desenho left join #philcat_art as philc_artgra on philc_artgra.cod = #philcat.gravura left join #philcat_local as philc_impl on philc_impl.cod = #philcat.local_imp left join #philcat_imp as philc_impt on philc_impt.cod = #philcat.tipo_imp left join #philcat_denteados as philc_dentv on philc_dentv.cod = #philcat.dentv left join #philcat_denteados as philc_denth on philc_denth.cod = #philcat.denth left join #philcat_papel on #philcat_papel.cod = #philcat.papel left join #philcat_familias on #philcat_familias.cod = #philcat.familia WHERE #philcat.serie IN (868, 869, 870, 871, 872, 873, 874, 876, 877, 878, 875, 880, 879, 881, 882) AND #philcat.tipo=1 AND #philcat.familia=1 ORDER BY CAST(REPLACE(REPLACE(REPLACE(#philcat.valor_facial,'E','00'),'C',''),'$','') AS DECIMAL(10,2)) +0 ASC, #philcat.descr ASC`

Screen capture after successfull run in phpmyadmin:
![imagem](https://user-images.githubusercontent.com/17130530/112194999-5b53b300-8c01-11eb-8b77-2def36f7a52c.png)

**Comment by CaMer0n** [comment]
@rica-carv The better way is using backticks. Example: 
https://github.com/e107inc/e107/blob/87521f330ff04281d06f0b9a250b8fae853e1c33/e107_plugins/pm/admin_config.php#L587

**Comment by Deltik** [comment]
Even with backticks, that space is still required.  ([Source](https://github.com/e107inc/e107/blob/06b86ee/e107_handlers/e_db_pdo_class.php#L1523))

**Comment by rica-carv** [comment]
Thanks guys, for now problem is solved.... 👍 👍 👍 👍  👍
