### ISSUE TITLE
Feature-menu title is duplicated in home layout

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4461]
![Screenshot](https://user-images.githubusercontent.com/10089685/112177292-67963b00-8c16-11eb-97d2-812758c1e881.png)

**Comment by Jimmi08** [comment]
I can't confirm this with the bootstrap3 theme and latest git. More information is needed. 

![image](https://user-images.githubusercontent.com/5429548/125617083-44e491a3-d6db-4ed3-9ace-9c14729e0f2b.png)
![image](https://user-images.githubusercontent.com/5429548/125617105-2790b6a9-ddc8-43ea-8e0b-b633c1ed5c14.png)

**Comment by Jimmi08** [comment]
`default feature-menu-1 and 2 are located in AREA 14 (home layout) btw this works perfectly in business home layout`

It is not a core bug. On second thoughts maybe it is, Different style should be used for menus.

Check MENU14:
```
				<div class="col-lg-12">
					{MENU=14}
				</div>
```

First SETSTYLE above is` {SETSTYLE=default}` .
if you look in theme.php for that style:

```
			case 'default':
			case 'main':

			    if(!empty($caption))
			    {
			        echo '<h2 class="caption">'.$caption.'</h2>';
			    }
```

the caption is outputted. You can see this in code too: (style is default)
![image](https://user-images.githubusercontent.com/5429548/125619967-b7fb9700-e485-44c3-b516-feb595de0a76.png)


If you use feature-menu-2 in this menu area, its template is **2-column_2:1_text-left** :  
{CMENUTITLE} is there. 

So with this combination, menu title is displayed  2x 

```
	$MENU_TEMPLATE['2-column_2:1_text-left']['start'] 	= '<div class="row">';
	$MENU_TEMPLATE['2-column_2:1_text-left']['body'] 	= '			
													       <div class="cpage-menu col-lg-8 col-md-8"><h4>{CMENUICON}{CMENUTITLE}</h4>{CMENUBODY}</div>
													       <div class="cpage-menu col-lg-4 col-md-4">
													       <a class="btn btn-lg btn-primary pull-right" href="{CPAGEBUTTON=href}">'.LAN_READ_MORE.'</a>
													       </div>
													       '; 
	$MENU_TEMPLATE['2-column_2:1_text-left']['end'] 	= '</div>';
```


Fixes:
1. look for style without exporting caption f.e.  and set it for this menu area:

```
	 <div class="col-lg-12">
                    {SETSTYLE=none}
		   {MENU=14}
	 </div>
```

OR

2. delete {CMENUTITLE} from menu template

I would prefer option 1.
