### ISSUE TITLE
The secondary submenu is not functional on mobile

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4462]
![Screenshot](https://user-images.githubusercontent.com/10089685/112178642-8d700f80-8c17-11eb-8089-fda796463acb.png)

**Comment by 2548ir** [comment]
@Jimmi08 what is your thoughts about this issue?

**Comment by Jimmi08** [comment]
@2548ir 
https://github.com/e107inc/e107/issues/4542

It is not supported by bootstrap. In fact, they are against it (there was some article about it) 
It is not supported by the e107 core. 

The theme has to support this with some other solution.  Mainly javascript or replacing bootstrap navigation another way.
