### ISSUE TITLE
Nested comments display only first child of parent comment 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4465]
## Bug Description
With this structure:
![image](https://user-images.githubusercontent.com/5429548/112348641-4c840380-8cc8-11eb-8ee5-77a01a228d58.png)

Only first child is displayed for item ID 16

## How to Reproduce
1. You can try this with News too 
2. Add more than one child (not child of child, but more replies of parent comment
3.  Only first child is displayed

## Reason
This code in render_comment():
```
	$sql_nc = e107::getDb('nc'); /* a new db must be created here, for nested comment  */
	if ($sub_total = $sql_nc->gen($sub_query))
	{
		while ($row1 = $sql_nc->fetch())
		{
...
                     $text .= $this->render_comment($row1, $table, $action, $id, $width, $subject, $addrating);
...
        }
}

```
Parent query is correct
$sub_query are correct
The problem is in fetch() and this code doesn't work in version 2  (from the beginning of Alpha)

PHP 7.2

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks for this. Please check and re-open if necessary.

**Comment by Jimmi08** [comment]
@CaMer0n 
this is still needed? (new db connection)

$sql_nc = e107::getDb('nc'); /* a new db must be created here, for nested comment  */

**Comment by CaMer0n** [comment]
@Jimmi08 No, which is why I removed it.
