### ISSUE TITLE
glyphicons from theme.xml can't be changed without unistalling theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4469]
## Bug Description

It is not possible to change the path to custom glyphicons in the admin area without uninstalling the theme
 
## How to reproduce

Theme.xml: 
```
	<glyphicons>
		<glyph name='pixeden' pattern='\.(pe-7s-[a-z-0-9]*):before\{'  path='assets/css/fonts/pe-icon-7-stroke.css' class='pe' prefix='pe-7s-'   tag='span' />
	</glyphicons> 
```
Result in admin area:
![image](https://user-images.githubusercontent.com/5429548/112754880-801fa000-8fde-11eb-9fbb-d82e42da8fc4.png)

If you change the path (in my case), old path is still loaded. **Clearing cache didn't help.**
```
	<glyphicons>
		<glyph name='pixeden' pattern='\.(pe-7s-[a-z-0-9]*):before\{'  path='fonts/pe-icon-7-stroke.css' class='pe' prefix='pe-7s-'   tag='span' />
	</glyphicons>
```
![image](https://user-images.githubusercontent.com/5429548/112755038-4307dd80-8fdf-11eb-8f18-b49bc94ac344.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Try modifying e107_admin/theme.php:  (adding the setTheme() line ) 
```
if(empty($_POST) && deftrue('e_DEVELOPER') || deftrue('e_DEBUG')) // check for new theme media and import.
{
		$name = e107::getPref('sitetheme');
		$this->themeObj->setTheme($name, false); 
		e107::getMedia()->import('_common_image', e_THEME.$name, '', 'min-size=10000');
		e107::getMessage()->addInfo('Developer/Debug Mode: Scanning theme images folder for new media to import.');
}
```

Does it help?

**Comment by Jimmi08** [comment]
I added it, but maybe I do something wrong:
This is original path (wrong, just testing):
`/fonts/pe-icon-7-stroke.css`
I checked S_Meta_theme.cache.php too.
It is loaded. 
![image](https://user-images.githubusercontent.com/5429548/112945252-56788d00-9134-11eb-8c7d-ef796404a821.png)

Then I changed it to:
` path='assets/css/fonts/pe-icon-7-stroke.css' `

Cleared cache.  Checked theme array in S_Meta_theme.cache.php
Checked theme array after SetTheme()
Resaved theme prefs to be sure.
There is the correct path:
```
"glyphs": [
            {
                "name": "pixeden",
                "pattern": "\\.(pe-7s-[a-z-0-9]*):before\\{",
                "path": "assets\/css\/fonts\/pe-icon-7-stroke.css",
                "class": "pe",
                "prefix": "pe-7s-",
                "tag": "span"
            }
        ],
```

But wysiwyg is loaded original path until I don't uninstall theme.

![image](https://user-images.githubusercontent.com/5429548/112945724-ecacb300-9134-11eb-8edc-3053a7c7d6fd.png)

You can test this with landingzero theme.

**Comment by Jimmi08** [comment]
This is problem:
`if(empty($_POST) `
To get this work, something has to be changed in theme prefs.

**Comment by Jimmi08** [comment]
It is solved in fact. Ask for any edit is logical. Thanks
