### ISSUE TITLE
glyphs doesn't work in other than bootstrap3 theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4471]
## Bug Description
After the latest changes in the boostrap3 theme, there is something wrong

## How to Reproduce
It works the same way in Voux and Landingzero, but those themes are not updated to use theme class, so I am not sure where the problem lies.

## Expected Behavior
I have set a theme to use frontend styling. It is a bootstrap3 theme with font awesome 4. 

```
	<libraries>
		<library name="bootstrap" version="3" scope="admin,wysiwyg"/>
		<library name="fontawesome" version="4"  scope="admin,front,wysiwyg"/>
	</libraries>
	<stylesheets>
		<css file="style.css" name="Default" exclude="bootstrap" /> 
	</stylesheets>
```

## 1. glyphs are not displayed in the editor

you select glyph from FA 4 set
![image](https://user-images.githubusercontent.com/5429548/112757470-23c27d80-8fea-11eb-877b-6ccabf2b8a26.png)

Nothing is displayed. Originally I thought that this problem:

`$libraries = e107::getTheme('admin')->getThemeFiles('library', 'wysiwyg');`

It is loading libraries from the admin theme, so you will end with bootstrap3 and font awesome 5!  Not sure if there is FA4 icon that is not supported in FA5, but it could be. 

**So how to get  FA 4 css in wysiwyg?**  Scope is correct.
**Why are not front theme libraries used if they are set?**

These css are loaded now in wysiwyg:
content_css: ["/e107-hestia/e107_web/lib/bootstrap/3/css/bootstrap.min.css","/e107-hestia/e107_web/lib/font-awesome/5/css/all.min.css","/e107-hestia/e107_web/lib/font-awesome/5/css/v4-shims.min.css","/e107-hestia/e107_themes/hestia/style.css","/e107-hestia/e107_web/lib/animate.css/animate.min.css","/e107-hestia/e107_plugins/tinymce4/editor.css"]
});

## 2, Why is animate css hardcoded in editor?  It is useless if the theme doesn't support it. 

```
		$animate = e107::library('files', 'animate.css');
		$ret[] = $tp->replaceConstants($animate['css'][0], 'abs');
```

## 3.  glyphs are not correctly displayed on the frontend

For some reason selecting FA 4 icon is converted to glyphicon, but the wrong way (both prepends are used) .
 
`<i class="glyphicon glyphicon-fa-glass"><!-- --></i>`
![image](https://user-images.githubusercontent.com/5429548/112757701-2ffb0a80-8feb-11eb-9523-a37f31709761.png)

![image](https://user-images.githubusercontent.com/5429548/112757726-4d2fd900-8feb-11eb-8579-8dc45e71bbc0.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 First, you'll want to remove 'admin' from each of your `<library>` scopes. 
It's useless to include it with any theme other than bootstrap3 (admin theme). 

My last commit should be a step in the right direction. 

btw. You gave me a good laugh: 
**Bug Description** - "...something wrong"  :1st_place_medal:  :laughing:
**How to Reproduce** - "It works the same way...".

**Comment by Jimmi08** [comment]
Thanks. It looks working.
