### ISSUE TITLE
list of menus in Menu manager is not scrollable

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4476]
## Bug Description
If you have too many menus,  you can't scroll down and select those down...

![image](https://user-images.githubusercontent.com/5429548/113477557-f1e66680-9482-11eb-97b1-c780cd9c755a.png)

PHP 7.4

**Comment by CaMer0n** [comment]
@Jimmi08 admin_style.css line 1815: 
```
body#admin-menus #sc-admin-help .panel-body {
	overflow-y: scroll;
}
```

Please check in the browser you are using what may be overriding this. Also, which admin skin is being used?

![image](https://user-images.githubusercontent.com/2825679/113755898-ad96d880-96c5-11eb-83df-711587a0643f.png)

**Comment by Jimmi08** [comment]
It is now there. No idea what helped. But at least I know what to check. Thanks. 

![image](https://user-images.githubusercontent.com/5429548/113761324-9c76b780-9717-11eb-8364-c0f9a43a3951.png)
