### ISSUE TITLE
pager in Admin UI doesn't work with bootstrap4 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4477]
## Bug Description
I by mistake used a plugin with frontend Admin UI with bootstrap4  theme

Because this code in form handler:

```
		if(defined('BOOTSTRAP') && BOOTSTRAP === 4)
		{
			return '<a class="pager-button btn btn-primary" href="'.$url.'">'.$total.'</a>';
		}
 
```

it looks like this:
![image](https://user-images.githubusercontent.com/5429548/113489210-237f2200-94c3-11eb-8545-cc2546b0c0ac.png)

After removing, it looks correctly:
![image](https://user-images.githubusercontent.com/5429548/113489227-49a4c200-94c3-11eb-8297-d1a15ce5af8c.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 The Admin-UI is designed for use in the admin-area which is runs on Bootstrap 3, so I have switched this to an enhancement.

**Comment by Jimmi08** [comment]
This is fixed on frontend, Correct value is displayed
