### ISSUE TITLE
questions to sessions

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4479]
Sorry for the stupid questions, but I am not familiar with this topic.
I have an old script that used directly $_SESSION 
I would like to use e107 way.

I was able to find that I need to use:
`e107::getSession()->setData(SITEKEY."_ageconsent",1);`
and
`$ageconsent = e107::getSession()->get($session_name);`
(plus check `e107::getSession()->is($session_name)`)
It works.  

But how to set data if it is an array?
`$_SESSION[SITEKEY."_warned"][$_GET['warning']] = 1;`

And with using class2.php can I delete this? Or at least, for now, that session part? 
```
if(!isset($_SESSION)) session_start();
// clear the global variables if register globals is on.
if(ini_get('register_globals')) {
	$arrayList = array_merge($_SESSION, $_GET, $_POST, $_COOKIE);
	foreach($arrayList as $k => $v) {
		unset($GLOBALS[$k]);
	}
}
```
Thanks

**Comment by Deltik** [comment]
I don't quite understand this question:
> But how to set data if it is an array?
> ` $_SESSION[SITEKEY."_warned"][$_GET['warning']] = 1;`

But I do see that there is a method, `e_session::set()`, which handles up to a three-dimensional array.  This should be the equivalent to your code snippet:
```php
e107::getSession()->set(SITEKEY."_warned/{$_GET['warning']}", 1);
```

----

### Answers to the side-questions

* Regarding the session start, `class2.php` takes care of the session (in most cases?), so you should not need to start the session yourself.
* Regarding the check for `register_globals`, `register_globals` was eliminated in PHP 5.4.0, so it is no longer relevant.

**Comment by Jimmi08** [comment]
Perfect, thank you. I will try this. Big help.

**Comment by Jimmi08** [comment]
@Deltik Just info

This worked:
e107::getSession()->set(SITEKEY."_warned/{$_GET['warning']}", 1);
but is() and get() not. 

Data was correct
![image](https://user-images.githubusercontent.com/5429548/113931832-3cedda00-97f3-11eb-8c83-e48402a6096c.png)

So I changed it to a single key and it worked ( _ instead /)

![image](https://user-images.githubusercontent.com/5429548/113931995-6c044b80-97f3-11eb-8e29-4e75cb7cbfbe.png)

The code itself wasn't changed, so key was reason, but maybe I used it wrong way:
`e107::getSession()->is(SITEKEY."_warned/{$storyinfo['rid']}")` 

Again thanks for your help

**Comment by Deltik** [comment]
`e_session` has a confusing API that I believe needs to be reworked.  It appears that `e_session::set()` can write multidimensional arrays up to 3 dimensions, but there's no method that can read multidimensional arrays.

I wanted to introduce a [new API with a much friendlier way to get and set values nested inside multidimensional arrays](https://github.com/e107inc/e107/commit/595440f5c6410a65fbe9e517eed2bdda803aa648#diff-e52167f139e73010dd3d69df142ef7387f79c647a752be3ff9751f630afece10R30-R31) but the project is a very large (and unofficial) undertaking.
