### ISSUE TITLE
Question how to configure social login provider 

### ISSUE THREAD

**Issue by turtleking1** [e107inc/e107#4485]
Hello

I'm trying to setup social login on my e107 website but when I test the login I get a error from Discord Invalid OAuth2 redirect_uri 
How is it possible to fix that problem 

**Discord error**
>
![discord](https://user-images.githubusercontent.com/62931546/114121668-0d23fc80-98ef-11eb-94f6-eafbbad52976.png)

**My e107 Social Configure Login Provider** 
![website](https://user-images.githubusercontent.com/62931546/114121805-54aa8880-98ef-11eb-8049-3e097584ecfd.png)

**and here's my Discord OAuth2**
![discord OAuth2](https://user-images.githubusercontent.com/62931546/114122150-f7fb9d80-98ef-11eb-8e56-00bd47d3d229.png)

**Comment by Deltik** [comment]
When you try to log in using Discord OAuth2, the URL in the address bar will show something like this:

<code>
https://discord.com/oauth2/authorize?response_type=code&client_id=829930649997279263&redirect_uri=<strong>http%3A%2F%2F10.64.229.116%2Fe107%2F%3Froute%3Dsystem%2Fxup%2Flogin%26provider%3DDiscord%26back%3Dhttp%3A%2F%2F10.64.229.116%2Fe107%2Fsignup.php%3Fstage1</strong>&scope=identify+email&state=HA-ZGQINF3W6DKBTUAVPM1CYO9S4X807ERJ25LH
</code>
<br /><br />
The part in bold is the redirect URI, but it is urlencoded.  Pass it through [`urldecode()`](https://urldecode.onlinephpfunctions.com/), and the result is the redirect URI to put into the list of Discord OAuth2 redirect URIs.  You should get an output that looks like:

```
http://10.64.229.116/e107/?route=system/xup/login&provider=Discord&back=http://10.64.229.116/e107/signup.php?stage1 
```

For some reason, Discord requires exact URLs, so `urldecode()`ing the actual `request_uri` in the query string when trying to log in is the most reliable way to get it.

**Comment by Deltik** [comment]
When you try to log in using Discord OAuth2, the URL in the address bar will show something like this:

<code>
https://discord.com/oauth2/authorize?response_type=code&client_id=829930649997279263&redirect_uri=<strong>http%3A%2F%2F10.64.229.116%2Fe107%2F%3Froute%3Dsystem%2Fxup%2Flogin%26provider%3DDiscord%26back%3Dhttp%3A%2F%2F10.64.229.116%2Fe107%2Fsignup.php%3Fstage1</strong>&scope=identify+email&state=HA-ZGQINF3W6DKBTUAVPM1CYO9S4X807ERJ25LH
</code>
<br /><br />

The part in bold is the redirect URI, but it is urlencoded.  Pass it through [`urldecode()`](https://urldecode.onlinephpfunctions.com/), and the result is the redirect URI to put into the list of Discord OAuth2 redirect URIs.  You should get an output that looks like:

```
http://10.64.229.116/e107/?route=system/xup/login&provider=Discord&back=http://10.64.229.116/e107/signup.php?stage1 
```

For some reason, Discord requires exact URLs, so `urldecode()`ing the actual `request_uri` in the query string when trying to log in is the most reliable way to get it.

**Comment by turtleking1** [comment]
> When you try to log in using Discord OAuth2, the URL in the address bar will show something like this:
> 
> ` https://discord.com/oauth2/authorize?response_type=code&client_id=829930649997279263&redirect_uri=**http%3A%2F%2F10.64.229.116%2Fe107%2F%3Froute%3Dsystem%2Fxup%2Flogin%26provider%3DDiscord%26back%3Dhttp%3A%2F%2F10.64.229.116%2Fe107%2Fsignup.php%3Fstage1**&scope=identify+email&state=HA-ZGQINF3W6DKBTUAVPM1CYO9S4X807ERJ25LH `
> 
> The part in bold is the redirect URI, but it is urlencoded. Pass it through [`urldecode()`](https://urldecode.onlinephpfunctions.com/), and the result is the redirect URI to put into the list of Discord OAuth2 redirect URIs. You should get an output that looks like:
> 
> ```
> http://10.64.229.116/e107/?route=system/xup/login&provider=Discord&back=http://10.64.229.116/e107/signup.php?stage1 
> ```
> 
> For some reason, Discord requires exact URLs, so `urldecode()`ing the actual `request_uri` in the query string when trying to log in is the most reliable way to get it.

Hello Deltik
I gave it a try and that fixed my problem thank you so much for your help
