### ISSUE TITLE
Placement of breadcrumb when comments form is rendered

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#4489]
## Bug Description
The breadcrumb is rendered in the wrong place when the comments form is rendered. 

## How to Reproduce
1. Add comments form by using `e107::getComment()->render()`
2. Refresh the page and see that the breadcrumb moves down. (see screenshots) 

## Expected Behavior
Breadcrumb should stay rendered at the same place (see screenshot 1) when comments form is rendered. 

## Screenshots
Screenshot #1: Without comments form 
![image](https://user-images.githubusercontent.com/577978/115111421-920eb600-9f80-11eb-934b-e648dc364bfd.png)

Screenshot #2: With comments form 
![image](https://user-images.githubusercontent.com/577978/115111413-87ecb780-9f80-11eb-9337-1da0d58408f8.png)

**Comment by Jimmi08** [comment]
@CaMer0n 
That problem is because comments use default tablerender and you can't change this from the plugin. And theme uses {---BREADCRUMB---} shortcode.

![image](https://user-images.githubusercontent.com/5429548/115114622-a064ce00-9f90-11eb-9d13-a0fc2c6bc82c.png)

**Comment by CaMer0n** [comment]
@Moc I have added an example to the blank plugin. Please install and navigate to /e107_plugins/_blank/_blank.php with the bootstrap3 theme running. Does it cause the same issue?

**Comment by Moc** [comment]
> Does it cause the same issue?

No, because it is called differently in the _blank plugin, after the tablerender. For me, the comments shortcode is part of the tablerender. 

- I have `{COOKBOOK_COMMENTS}` in my template:
```php
    function sc_cookbook_comments($parm = '')
    {
        $plugin   = 'cookbook';
        $id       = $this->var['r_id'];
        $subject  = $this->var["r_name"];
        $rate     = false;

        return e107::getComment()->render($plugin, $id, $subject, $rate);
    }
```
-  It is rendered like this:
```php
$text .= e107::getParser()->parseTemplate($LAYOUT, true, $sc);
...
e107::breadcrumb($this->breadcrumb_array);
.. 
e107::getRender()->tablerender(LAN_CB_RECIPE.$caption, $text, "recipe-item");

**Comment by CaMer0n** [comment]
`e107::getComment()->render($plugin, $id, $subject, $rate);` uses `tablerender()`, so you're placing one tablerender inside another. 
You should use `e107::getComment()->render($plugin, $id, $subject, $rate);` the same way you would use `$ns->tablerender()`

**Comment by Moc** [comment]
If I change the shortcode to echo instead of return, the comments form is rendered above the other content. 

I'll finish my rewrite and provide you with my code asap so you can check.

**Comment by Moc** [comment]
With the latest files, this is now fixed after changing the style of the comments area (ie. not 'default'). 

This can be done in multiple ways, for example:
1. Through the template:
```php
        {SETSTYLE=cookbook_comments}
        {COOKBOOK_COMMENTS}
```

2. Through the shortcode, using something like this:
```php
$prevStyle = e107::getRender()->getStyle(); 
e107::getRender()->setStyle('comments'); 
$text .= e107::getComment()->render($plugin, $id, $subject, $rate);
e107::getRender()->setStyle($prevStyle);
```

**Comment by Jimmi08** [comment]
Because the search page has a similar issue if style "default" is used, this is the next way how to fix the look:
- changing style in theme.php. 
switch($mode)
{
			   case "search_result":
 				 $style = "normalstyle";
				 break;   
}

**Comment by Jimmi08** [comment]
@Moc 
your solution is changing style for tablestyle() for content item 

This is layout from boostrap5 theme
```
      <!-- Blog Entries Column -->
      <div class="col-md-8">
			{ALERTS}
			{SETSTYLE=main}
			{---}
      </div>
```
Debug

```
<!-- tablestyle initial:  style=default  mode=recipe-item  UniqueId= -->
<!-- 
{
    "list": "",
    "uniqueId": "",
    "menuArea": 0,
    "menuCount": 0,
    "menuTotal": 0,
    "setStyle": "default",
    "caption": "Recipe - White calzones with marinara sauce",
    "styleCount": 1
}
-->
```

After deleting all SETSTYLE from your template, result is

![image](https://user-images.githubusercontent.com/5429548/182953039-a973ad3f-5eb6-4881-bbad-6d3d399e5d26.png)

![image](https://user-images.githubusercontent.com/5429548/182953625-96b704d4-02bd-4ce7-924b-1b309b09e0b0.png)
