### ISSUE TITLE
Don't autocomplete secure-image CAPTCHA input box

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4492]
## Bug Description
Browsers remember what was typed in the input box for the login secure-image/secimg.php CAPTCHA.  This is pointless and also gets in the way by presenting autocomplete options over the page.

## How to Reproduce
1. Go to `/e107_admin/prefs.php#nav-core-prefs-security`.
2. Enable "Display CAPTCHA on login page."
3. In `/e107_admin/menus.php`, activate the `login` menu.
4. On the home page, try filling in the form with the CAPTCHA.
5. Log out, if applicable, and then click on the CAPTCHA input box again.  You should see the previous CAPTCHA attempts pop up.

## Expected Behavior
No auto-complete for `<input id="code-verify" />`

## Screenshots
![image](https://user-images.githubusercontent.com/1364268/115280205-49d0ce80-a10d-11eb-9661-9627f8319414.png)

**Comment by Moc** [comment]
@Deltik Untested but I committed something that should do the trick. Can you confirm?

**Comment by Deltik** [comment]
@Moc: https://github.com/e107inc/e107/commit/ee346eb06ca26ba8ab348ce04099583f05b178a6 does not prevent autocomplete on Mozilla Firefox 88.  This patch, however, does:

```diff
diff --git a/e107_handlers/secure_img_handler.php b/e107_handlers/secure_img_handler.php
index a6e0eadf7..b131c3e88 100644
--- a/e107_handlers/secure_img_handler.php
+++ b/e107_handlers/secure_img_handler.php
@@ -230,7 +230,7 @@ class secure_image
                }

                $frm = e107::getForm();
-               return $frm->hidden("rand_num", $this->random_number).$frm->text("code_verify", "", 20, array( "size"=>20, 'required'=>1, 'placeholder'=>LAN_ENTER_CODE, 'autocomplete' => 'one-time-code'));
+               return $frm->hidden("rand_num", $this->random_number).$frm->text("code_verify", "", 20, array( "size"=>20, 'required'=>1, 'placeholder'=>LAN_ENTER_CODE, 'autocomplete' => 'off'));
        }

```
