### ISSUE TITLE
recommended solution for custom BODYTAG stopped to work

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4494]
## Bug Description
Solution for this:

https://github.com/e107inc/e107/issues/4449#issuecomment-799568187_

doesn't work anymore.

## How to Reproduce
1. Go to bootstrap3 theme and add the needed code
```
	function init()
	{
		define('BODYTAG', '<body class="page '.THEME_LAYOUT.'">');
	}
```
2. Check your body tag in bootstrap3 theme

![image](https://user-images.githubusercontent.com/5429548/115839830-57db6380-a41b-11eb-8dfd-e2ead24e7613.png)

 

### PHP Version

```
PHP Version 7.2
```

**Comment by CaMer0n** [comment]
@Jimmi08 `BODYTAG` is deprecated when using the new theme standard. ie. `theme.html` which already contains the `<body>` tag. Bootstrap3 uses this.  The above code is a work-around for old themes that do not use `theme.html.` Voux uses this. Are you able to reproduce this issue using Voux?

**Comment by Jimmi08** [comment]
@CaMer0n 
This is exactly the reason why I asked for removing my themes from e107.org. I am not able to manage so many themes with different behavior. 
Of course, you are right.
