### ISSUE TITLE
TinyMce

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4502]
## Question
Is there a possible impact on the CDN changes for TinyMce (4) ?
Question on error on e107help (https://www.e107help.org/5300/cdn-error-from-tinymce)
## Expected Source
Tiny posted closing days 

CacheFly CDN (http://tinymce.cachefly.net/) - November 30 2020
TinyMCE CDN (https://cdn.tinymce.com/) - February 25th 2021
Tiny Cloud stable (https://cloud.tinymce.cloud/ & https://cdn.tiny.cloud/) - February 25th 2021

## Additional Context
source : https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/

**Comment by CaMer0n** [comment]
@tgtje This is only an issue for someone using an old version of e107 v2 that points to those CDNs.

**Comment by tgtje** [comment]
Thank you; closing
