### ISSUE TITLE
Wrong images link after migration to new server

### ISSUE THREAD

**Issue by Web-Control** [e107inc/e107#4507]
## Why after migration to a new server all links to images are wrong?

For example:
System tries load image from path:
vinyldjserwis.pl/media/img/a1905xa800/2017-05/fot8_karuzela.jpg

but correct path is:
vinyldjserwis.pl/e107_media/21bb3aefda/images/2017-05/fot8_karuzela.jpg

**Comment by Jimmi08** [comment]
No, it is sef-url version for images path.  Check .htaccess:
`   ReWriteRule ^media\/img\/(a)?([\d]*)x(a)?([\d]*)\/(.*)?$ thumb.php?src=e_MEDIA_IMAGE/$5&$1w=$2&$3h=$4 [NC,L]`

After migration, your problem is probably with the changed hash folder...    this one: 21bb3aefda    if your database name was changed, it is different on the new server.   
There are 2 ways to solve this - copy content to a new folder or made e107 use the old hash.   Not sure now about the second one.

**Comment by Web-Control** [comment]
Copy content to a new folder doesn't work.
Even when i past new  image's path to a browser it say: "Cache folder not writeable! Access denied! "

How to make e107 use the old hash?

**Comment by Jimmi08** [comment]
`How to make e107 use the old hash?`
@Deltik 
What is the correct way now? I always forget. 

@Web-Control 
`"Cache folder not writeable! Access denied! "`
This is your problem. The old hash will not help you. Check .htaccess and folder rights. 
Or catch somebody on gitter who is able to help you with this.

**Comment by Moc** [comment]
@Jimmi08 @Web-Control 

Copy the old hash and paste this in your e107_config.php file, and replace `***` with the correct hash:

$E107_CONFIG['site_path'] = '`***`';

**Comment by Web-Control** [comment]
I write this:
$E107_CONFIG['site_path'] = '21bb3aefda/'; 
in e107_config.php  and it doesn't work.

Maybe the clue will be that I can't also log in to the system with old login and password.

**Comment by tgtje** [comment]
How about this old post? maybe similar  : https://github.com/e107inc/e107/issues/1013

**Comment by Web-Control** [comment]
In the e107_system folder i have three folders like on this picture:
![e107 system folder](https://user-images.githubusercontent.com/28429068/119398573-0bb06700-bcd8-11eb-828d-dcc7006bca05.PNG)

Cashe folder is in first and third one.
I set permission to 777 on both and nothing happened.

...by the way is it ok i have three folders there?

**Comment by tgtje** [comment]
1fst and 3rd? All including second one should have the same structure (afaik). and yes more folders can be present.
Are youre internal sub folders also chmodded ?  All should be .(btw 755 is sufficient and strongly advised).
Some _files_ have 644 
Next check presence of same hash folders in .../e107_media those folders should also have chmod of 755.

**Comment by Web-Control** [comment]
I have hash folders in .../e107_media and i set permission 755 and even higher for them but it still doesnt work :(

And way I can't log in to the system with past admin login and password ?

**Comment by Jimmi08** [comment]
Just info how to check your actual hash  Preferences/File Uploading

It is not listed in the Site Info of PHPInfo option. 

![image](https://user-images.githubusercontent.com/5429548/120465856-b55dbb00-c39e-11eb-92e7-c1c5507b637c.png)

**Comment by Web-Control** [comment]
THX. This was helpful.

After checking actual hash folder and create him under "e107_media/"  and copy all images there problem was solved :).

**Comment by Jimmi08** [comment]
You are welcome, one has to learn this when their media folder looks like this :) Multisite, you know.

This should be the first rule before migration...  (together with backup) 

![image](https://user-images.githubusercontent.com/5429548/120802218-77999780-c542-11eb-8b31-4050710a5556.png)
