### ISSUE TITLE
Unauthorized access! Create news

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#4510]
## Bug Description
I upgraded the system from GitHub on admin area.
I got "Unauthorized access!" after I made news and push button "Create"

Updated: I made something on the admin site I got "Unauthorized access!".

### PHP Version
PHP Version 5.6.40

**Comment by Moc** [comment]
Does this happen all the time when creating a new news item? Or just on some occasions?

**Comment by fizi** [comment]
It was on the all... but was 2 database tables (online, admin log) wrong and I repaired the database and it seems work.

**Comment by Moc** [comment]
Okay, well I assume there was a database corruption then. Closing for now, but do let us know if it occurs again.
