### ISSUE TITLE
Blank page suddenly after no changes recently.

### ISSUE THREAD

**Issue by mgaulton** [e107inc/e107#4524]
## Bug Description
Blank page is returned for some users.
I have 2 of us that get the correct page but everyone else is getting a blank page.
## How to Reproduce
load https://brgc.ca 

## Expected Behavior
Webpage should come up for all users.

## Server Information
hosted 
Apache Version | 2.4.48
PHP Version | 7.2.34
MySQL Version | 5.7.34
Architecture | x86_64
Operating System | linux

### PHP Operating System
Linux hp318.servername.online 3.10.0-962.3.2.lve1.5.42.el7.x86_64 #1 SMP Mon Nov 9 08:11:18 EST 2020 x86_64
### PHP Version
PHP Version 7.4.20

### PHP Modules
bcmath
bz2
calendar
Core
ctype
curl
date
dom
eio
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
i360
iconv
imagick
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

### Client Information
Working 
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

## Additional Information
2 plugins were added on jun 18, not touched since, issues reported Sunday night.

This is the only significant error.
[23-Jun-2021 06:43:59 America/Toronto] PHP Fatal error:  Uncaught Error: Call to a member function setTitle() on null in /home/brgcc690/public_html/e107_handlers/error_page_class.php:247
Stack trace:
#0 /home/brgcc690/public_html/error.php(65): error_page->render(403)
#1 /home/brgcc690/public_html/error.php(46): error_front->renderErrorPage()
#2 /home/brgcc690/public_html/error.php(88): error_front->__construct()
#3 {main}
  thrown in /home/brgcc690/public_html/e107_handlers/error_page_class.php on line 247
[27-Jun-2021 15:46:29 America/Toronto] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000] [1203] User brgcc690_e107brg already has more than 'max_user_connections' active connections in /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php:2761
Stack trace:
#0 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(324): e_db_pdo->_getMySQLaccess()
#1 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(1532): e_db_pdo->db_Query('SELECT * FROM e...', NULL, 'db_Select_gen', false, '', '')
#2 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(621): e_db_pdo->gen('SELECT * FROM e...', false)
#3 /home/brgcc690/public_html/e107_handlers/sitelinks_class.php(1736): e_db_pdo->retrieve('SELECT * FROM #...', NULL)
#4 /home/brgcc690/public_html/e107_core/shortcodes/single/navigation.php(48): e_navigation->initData(1, 'main')
#5 /home/brgcc690/public_html/e107_handlers/shortcode_handler.php(1267): navigation_shortcode('main', '')
#6 [internal function]: e_parse_shortcode->doCode(Array)
#7 /home/brgcc690/public_html/e107_handlers/shortcode_handle in /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php on line 2761
[27-Jun-2021 15:46:29 America/Toronto] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000] [1203] User brgcc690_e107brg already has more than 'max_user_connections' active connections in /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php:2761
Stack trace:
#0 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(324): e_db_pdo->_getMySQLaccess()
#1 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(1532): e_db_pdo->db_Query('SELECT * FROM e...', NULL, 'db_Select_gen', false, '', '')
#2 /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php(621): e_db_pdo->gen('SELECT * FROM e...', false)
#3 /home/brgcc690/public_html/e107_handlers/sitelinks_class.php(1736): e_db_pdo->retrieve('SELECT * FROM #...', NULL)
#4 /home/brgcc690/public_html/e107_core/shortcodes/single/navigation.php(48): e_navigation->initData(1, 'main')
#5 /home/brgcc690/public_html/e107_handlers/shortcode_handler.php(1267): navigation_shortcode('main', '')
#6 [internal function]: e_parse_shortcode->doCode(Array)
#7 /home/brgcc690/public_html/e107_handlers/shortcode_handle in /home/brgcc690/public_html/e107_handlers/e_db_pdo_class.php on line 2761
[28-Jun-2021 11:14:30 America/Toronto] PHP Fatal error:  Uncaught Error: Call to a member function setTitle() on null in /home/brgcc690/public_html/e107_handlers/error_page_class.php:247
Stack trace:
#0 /home/brgcc690/public_html/error.php(65): error_page->render(403)
#1 /home/brgcc690/public_html/error.php(46): error_front->renderErrorPage()
#2 /home/brgcc690/public_html/error.php(88): error_front->__construct()
#3 {main}
  thrown in /home/brgcc690/public_html/e107_handlers/error_page_class.php on line 247

**Comment by Deltik** [comment]
I noticed that your website https://brgc.ca is behind a CDN.  If your web server is not mapping the `X-Forwarded-For` (or equivalent) header from the CDN as the client's true IP, it is possible for the CDN itself to get banned.  Banned page views show up white without logging.

In this case, try removing your CDN's IPs from or deleting the file `/home/brgcc690/public_html/e107_system/*/cache/banlist.php`, where `*` is your site hash (a string that looks like `6de9d0d30a`).

**Comment by mgaulton** [comment]
Thanks. I poked that banlist.php and it had a large number of ipv6
addresses, so I deleted the file.

Is the header something I need to get the host provider todo or can I make
some kind of local change to resolve this?

I have one client report that its now working after delting the file.

**Comment by Deltik** [comment]
Your CDN should have instructions on how to set up your web server to accept or trust the proxied client IP information.  This kind of setup is out of scope of e107, but I can provide insight into how e107 records IP addresses for flood control:

To figure out the client IP address, e107 takes the `$_SERVER['REMOTE_ADDR']`, which comes from the web server, except if `X-Forwarded-For` is provided as a header, e107 uses the last of the comma-delimited IPs in that header.

----

Alternatively, you can disable e107's anti-flood system in _Admin Area » Preferences » Advanced Options » Security & Protection » Enable flood protection?_ and set it to "Off".

Admittedly, the flood protection and banning system is not very intuitive, as is evident from the sudden blank page your users experienced, so it might be worth turning off if it's a recurring issue.

**Comment by mgaulton** [comment]
Awesome, thank you. I figured it was server side but with this hosting /
cpanel, I haven't found anywhere to configure httpd :) I'm inheriting a
system.

I'll monitor and if it occurs again, i'll disable.

Thank you all, the help is very much appreciated
