### ISSUE TITLE
SMTP certificate verify failed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4525]
Hello.
with normal shared hosting I don't have any troubles with SMTP. 

But now the client uses their own VPS server and I am getting an error:

```
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [/var/www/clients/client6/web5/web/clients/handlers/vendor/phpmailer/phpmailer/src/SMTP.php line 467]
```
Of course, I went to troubleshooting, read some stuff about this error. So I asked the server administrator for fixing this.

Their answer was:  remove certificate verification  (if I translated this correctly).  I know that no WordPress site has any troubles with their settings (Postman SMTP plugin is mostly used), so the issue is only with the e107 site. 

Could somebody help/explain this to me?

Thanks

**Comment by Deltik** [comment]
They're probably expecting you to turn off SSL or TLS in _Admin Area » Preferences » Basic Options » Email & Contact Info » Emailing method » SMTP Features_:

![image](https://user-images.githubusercontent.com/1364268/123929129-266ba080-d954-11eb-93c3-06ef73bb1bf0.png)

If you turn off TLS, you might need to switch the port to 25.  Some mail servers may not accept unencrypted SMTP on port 587.
If you turn off SSL, you probably need to switch the port to 25.  I don't know of any mail servers that accept unencrypted SMTP on port 465.

**Comment by Jimmi08** [comment]
I checked with WP their mail server:
![image](https://user-images.githubusercontent.com/5429548/123933278-81bc8380-d992-11eb-82df-4a4ac12a962d.png)
Working setting is:
![image](https://user-images.githubusercontent.com/5429548/123933927-1b843080-d993-11eb-948c-9d2ec511cc88.png)

+ port 25.

Problem with e107 that all combinations fail.

For example:
![image](https://user-images.githubusercontent.com/5429548/123933738-f263a000-d992-11eb-9011-61e061331252.png)

Result: (test email)
```
250-PIPELINING
250-AUTH PLAIN LOGIN
250-STARTTLS
250 HELP
CLIENT -> SERVER: STARTTLS
SMTP INBOUND: "220 TLS go ahead"
SERVER -> CLIENT: 220 TLS go ahead
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [/var/www/clients/client6/web5/web/clients/handlers/vendor/phpmailer/phpmailer/src/SMTP.php line 467]
```

But when I run SMTP test:
![image](https://user-images.githubusercontent.com/5429548/123934252-643be980-d993-11eb-81df-9061fcbc9cc6.png)

The correct combination should be TLS + 25, but it doesn't work either. The same error.

I noticed weird thing -  mail settings in Preferences (Not Users) is falling back to php although I had it set to SMTP too after some time.

Test email in Preferences - no error, but email is not received.
Test email in Users - fails with that verification error.

**Comment by Jimmi08** [comment]
By the way, what setting is used for e107::getEmail()->sendEmail() ? from Preferences or Users? Thanks

**Comment by Deltik** [comment]
Your SMTP test appears to show that the TLS connection fails because the server's certificate cannot be verified.  Make sure the hostname matches what's in the certificate.

If you have the `openssl` command, you can check the certificates with:

```
openssl s_client -connect mail.example.com:587 -starttls smtp </dev/null
```

(Replace `mail.example.com:587` with the SMTP server FQDN and SMTP port.)

----

> By the way, what setting is used for e107::getEmail()->sendEmail() ? from Preferences or Users? Thanks

`e107Email` gets the SMTP information from these prefs:
```
array('mailer', 'smtp_server', 'smtp_username', 'smtp_password', 'smtp_port', 'sendmail', 'siteadminemail', 'siteadmin')
```

So they would be set in _Admin Area » Preferences » Basic Options » Email & Contact Info » Emailing method_.

**Comment by Jimmi08** [comment]
I forgot to thank you.

**Comment by Jimmi08** [comment]
@Deltik Just letting you know.  They answered that they use self-signed certificate. Because WP works, other company with custom PHP solution uses PHP mailer without problems, it is my problem only. So I set only PHP, not SMTP.
