### ISSUE TITLE
Send new Message on user profile is not displayed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4530]
## Bug Description
`{USER_SENDPM}`  is not displayed 

## How to Reproduce
1. Install PM plugin, default settings
2. Not use any classes, just clean installation
3. Add new user and check his profile
 
## Expected Behavior
 
![image](https://user-images.githubusercontent.com/5429548/125778235-52771ce6-57c3-4491-994d-13e7ceb0d8b3.png)

## Reason
function canSendTo($uid) returns false

`$tmp = explode(",", USERCLASS);`

USERCLASS is empty string 

After changing to USERCLASS_LIST, it works

![image](https://user-images.githubusercontent.com/5429548/125778474-80777a8e-4769-4499-bdac-6d2f3b89230a.png)

**Comment by Moc** [comment]
@Jimmi08 Any update?

**Comment by Jimmi08** [comment]
It looks fixed, tested with bootstrap3 and bootstrap5 theme and 2.3.1
