### ISSUE TITLE
Any idea how to solve conflict with FA family name if you use core library?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4531]
What is recommended way for this?

Core library is used:
`<library name="fontawesome" version="5" scope="front,wysiwyg"/>`

Then this is used:
```
.fa, .fas {
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
}
```

But some themes have already FA included or use different font family name and mainly caret is not working:

Example:

```
@media (min-width: 992px)
.dropdown .dropdown-toggle:after, .dropup .dropdown-toggle:after, .dropstart .dropdown-toggle:after, .dropend .dropdown-toggle:after {
    content: "\f107";
    font: normal normal normal 14px/1 FontAwesome;
    border: none;
    vertical-align: middle;
    font-weight: 600;
}
```
When I try to replace it with core, I got:
![image](https://user-images.githubusercontent.com/5429548/125779492-de15f4f0-de31-458d-a4fc-90efac071240.png)

And the first time I saw loading FA this way:
`<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>`
so core library shouldn't be used then?  
After replacing it with core I run to that caret issue...

Where to define FONTAWESOME constant with theme class?

**Comment by Jimmi08** [comment]
Solved

```
	function config_alter(&$libraries)
	{
       // $libraries['cdn.fontawesome'] = array();
        unset($libraries['cdn.fontawesome5']['files']['css']);
        unset($libraries['cdn.fontawesome5']['files']['js']);
        unset($libraries['cdn.fontawesome5']['variants']);
	}
```

**Comment by CaMer0n** [comment]
@Moc for the docs. 

**theme.xml** : 

### CSS Mode
e107 will load FontAwesome CSS files 

    <library name="fontawesome" version="5" scope="front"  />   
    <library name="fontawesome" version="5" scope="front" files="css" />    (same as the above)
### Javascript Mode
e107 will load FontAwesome JS files 

    <library name="fontawesome" version="5" scope="front" files="js" /> 
### No JS/CSS Mode
e107will not load js/css but will still render FontAwesome markup. eg. `<i class="fa fa-phone"></i>` etc.   

    <library name="fontawesome" version="5" scope="front" files="none" />
