### ISSUE TITLE
How to fix this? - select output was changed

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4533]
This is an example from anteup plugin, but I noticed this in other places too:

```
$campaigns = e107::getDb()->retrieve('anteup_campaign', 'name', '', true);
$output = $frm->select('campaign', $campaigns, array('class', $class));
```

Result:

![image](https://user-images.githubusercontent.com/5429548/126367767-28456b6f-19eb-46b4-9a9e-2b5d0797658d.png)

How to fix this? To get just a simple list, no labels.  

Thanks

**Comment by Jimmi08** [comment]
@Moc  This is important. You can test it with anteup plugin.   I suppose it was changed because admin UI

Documentation says this:
`$frm->select($name, $option_array, $selected, $options, $defaultBlank); `
So maybe there is an issue in anteup plugin and it belongs there...

**Comment by Moc** [comment]
@Jimmi08 
This seems to work?:
```php
<?php

require_once("class2.php");

$campaigns = array("test1", "test2"); 

echo e107::getForm()->select('campaign', $campaigns);

```
<select name='campaign' id='campaign' class='tbox select form-control'>
<option value='0' selected='selected'>test1</option>
<option value='1'>test2</option>
</select>
```

**Comment by Jimmi08** [comment]
Great, thank you.  But this is the correct example (detail): - anteup is missing one parameter.

```
 $campaigns = array("1" =>"test1", "2"=>"test2");   //there are keys after returning from retrieve()
 $options = array('class', "campclass");  -  this is not working 
 echo e107::getForm()->select('campaign', $campaigns, '', $options);
```

```
<select name="campaign" id="campaign" class="tbox select form-control">
<option value="1">test1</option>
<option value="2" selected="selected">test2</option>

</select> 
```

What is the reason for this? Why I can't set class like with other form elements?  It looks like code for admin UI.  Those classes don't exist in the frontend (bootstrap). 

```

		if(!empty($options['size']) && !is_numeric($options['size']))
		{
			if(!empty($options['class']))
			{
				$options['class'] .= ' form-control input-' .$options['size'];
			}
			else
			{
				$options['class'] = 'form-control input-' .$options['size'];
			}

			unset($options['size']); // don't include in html 'size='. 	
		}
```

**Comment by Jimmi08** [comment]
Ha, if you use this:
`echo e107::getForm()->select('campaign', $campaigns, '2', 'class=select form-control');`
You will get:
```
<select name="campaign" id="campaign" class="select form-control">
<option value="1" class="select form-control">test1</option>
<option value="2" class="select form-control" selected="selected">test2</option>

</select>
```
There is issue about this:
`https://github.com/e107inc/e107/issues/4491`

**Comment by Moc** [comment]
#4491 Sounds like a bug. Replied there. 

Closing this one.
