### ISSUE TITLE
Social Plugin issue - Discord Login

### ISSUE THREAD

**Issue by F1Racer68** [e107inc/e107#4535]
## Bug Description
First, I am not certain if this is a bug, or a configuration issue on my end.

I have a brand new install of E107 v2.3.0, on a brand new Debian 10 deployment. I am running Apache2, MariDB and PHP7.4.

When attempting to configure the Social plugin to allow users to sign in using their Discord account it results in a "Invalid OAuth2 redirect_uri".

Using the URL provided by the Discord OAuth2 configuration tool on the Discord Developer Portal, everyhting works as expected.

After comparing the URL provided by Discord with the URL being generated by the Social Plugin, there is a significant difference. Social Plugin appears to be adding additional information into the URL that Discord does not recognize.

Social plugin indicates that my Callback URL is https://www.canamvrl.com/

Using that Callback URL as my "Redirect URL" on the Discord Developer Portal, Discord generates the following URL
https://discord.com/api/oauth2/authorize?client_id=869425449967702018&redirect_uri=https%3A%2F%2Fwww.canamvrl.com%2F&response_type=code&scope=identify%20email

When attempting to use the login function from E107, it generates the following URL
https://discord.com/oauth2/authorize?response_type=code&client_id=869425449967702018&redirect_uri=https%3A%2F%2Fwww.canamvrl.com%2F%3Froute%3Dsystem%2Fxup%2Flogin%26provider%3DDiscord%26back%3Dhttps%3A%2F%2Fwww.canamvrl.com%2F&scope=identify+email&state=HA-YV7QLWJASHE8XK32MPO4DF9CNUTI1Z0G56RB

Manually removing the **%3Froute%3Dsystem%2Fxup%2Flogin%26provider%3DDiscord%26back%3Dhttps%3A%2F%2Fwww.canamvrl.com%2F** section from the above URL allows the URL to work correctly, but I cannot ask users to do this every time they try to log in, or when new users attempt to join the site.

## Expected Behavior
Expected behaviour is for Discord login authorization screen to appear, asking user if they wish to grant permission to log into the website using their Discord info (Identity and email)

## Server Information
Debian 10

### PHP Operating System

```
Linux webserver 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
```

### PHP Version

```
7.4.21
```

### PHP Modules

apache2handler
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

### Client Information

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

## Additional Information
Current behaviour:
![image](https://user-images.githubusercontent.com/29759437/127373881-ce00c6ce-e1b3-45d1-91df-4dab2b1a6e8e.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/29759437/127374032-c955dd9b-d153-4db0-b570-5f1ab1b37d65.png)

Any assistance in resolving this issue is greatly appreciated.

**Comment by Deltik** [comment]
This is a duplicate of #4485.

Can you confirm if [my advice in this comment](https://github.com/e107inc/e107/issues/4485#issuecomment-816393031) fixes your problem?

**Comment by Deltik** [comment]
This is probably a duplicate of #4485.

Can you confirm if [my advice in this comment](https://github.com/e107inc/e107/issues/4485#issuecomment-816393031) fixes your problem?

**Comment by F1Racer68** [comment]
I did see that ticket, and attempted that fix before posting this on, but it did not resolve the issue for me. Whatever URL I provide to Discord, there always seems to be extra information in the URL sent by the plugin, which is causing Discord to reject the request.

**Comment by Deltik** [comment]
Right, can you add the following to the allowed allowed `redirect_uri`s in Discord?:
```
https://www.canamvrl.com/?route=system/xup/login&provider=Discord&back=https://www.canamvrl.com/
```

Instead of:
```
https://www.canamvrl.com/
```

**Comment by F1Racer68** [comment]
Apologies. I just tried the suggestion in #4485 again, and it worked this time.

I can only assume a PEBKAC error in copying the URL portion during the previous attempt.

Consider this closed now. Sorry for the unneccessary duplication.
