### ISSUE TITLE
could you add examples into e107_config file

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4537]
## Motivation
Why are you making this feature request?
I always spent too much time finding the right code

## Proposed Solution
add commented code similar 
`// define('e_PDO, true); // Enable PDO mode (used in PHP > 7 and when mysql_* methods are not available)`
for
- how to load JQuery in footer 
- how to set hash folder manually

Thanks

**Comment by Jimmi08** [comment]
Setting hash folder:

```
$E107_CONFIG = array('site_path' => '***');
$E107_CONFIG['site_path'] = '***';
```

**Comment by Jimmi08** [comment]
Setting jQuery to footer. I just found an installation where it was used because it broke my plugin.

`define('e_DEBUG_JS_FOOTER', true);`

Closing because no reaction and I can find the answer here if I need this in the future.

**Comment by Moc** [comment]
Site path ("hash") is now incorporated in e107_config.php by default. 

Not adding the `e_DEBUG_JS_FOOTER` constant because this is not an officially supported future at this point, but rather a debug/dev tool.

**Comment by Jimmi08** [comment]
@Moc 
Why is define('e_DEBUG_JS_FOOTER', true); not supported?  It is moving JQuery to the footer because of site speed. It is pretty important. 
I thought you are talking about jquery2 at first, otherwise I would asked sonner

**Comment by Moc** [comment]
> @Moc Why is define('e_DEBUG_JS_FOOTER', true); not supported? 

It is still a developer/development functionality, which can also be seen from the name "e_DEBUG". If it becomes an officially supported functionality, it should be converted into a pref in the Admin Area for example, or the naming should change. So for now, I decided not to add it to e107_config.php but it may be added in the future.
