### ISSUE TITLE
"That username/password combination is already in use." when "Disallow multiple logins" is enabled

### ISSUE THREAD

**Issue by mgaulton** [e107inc/e107#4538]
## Bug Description
If "Disallow multiple logins" in `/e107_admin/prefs.php#nav-core-prefs-security` is set to "Yes", trying to log in with a second session presents the following error message:

> That username/password combination is already in use.

This is confusing and makes it seem like the user was registering, but it actually means:

> This user is already logged in and cannot be logged in from another session.

## How to Reproduce
1. Enable "Disallow multiple logins" at `/e107_admin/prefs.php#nav-core-prefs-security`
2. Stay logged in.
3. In a separate browser container, try logging in as the same user.
4. Observe the error message, "That username/password combination is already in use."

## Expected Behavior
A more descriptive error message like:

> This user is already logged in and cannot be logged in from another session.

## Screenshots
![image](https://user-images.githubusercontent.com/1364268/129228618-f2f7c1d5-fd0f-4bf7-a552-6c93b3c9327c.png)

## Server Information
e107 2.3.0 with PHP 7.4

**Comment by mgaulton** [comment]
My site is completely down with error 500 currently, after attempting to remove the plugin.
I can't find any logs to determine what is happening.
Urgent assistance would be appreciated :)

**Comment by Deltik** [comment]
Please find us [on Gitter](https://gitter.im/e107inc/e107) for live chat support.
