### ISSUE TITLE
Clean-up all headers

### ISSUE THREAD

**Issue by nlstart** [e107inc/e107#454]
There are various e107 headers all over the current installation.
Let's first discuss and agree upon one standard, and then apply it everywhere.

Signalled:
Different copyright years displayed, different $Source display methods used.

Examples: 
print.php (Copyright (C) 2008-2009)
contact.php Copyright (C) 2008-2013 e107 Inc (e107.org)
e107_plugins/gallery/gallery.php (contains cron header!)

**Comment by Moc** [comment]
Closing this as it is an ongoing and mostly finished activity.
