### ISSUE TITLE
{SUBFORUMS} shortcode is not working

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4544]
## Bug Description
Subforums are not displayed on forum page

## How to Reproduce
I have test forum this structure:
![image](https://user-images.githubusercontent.com/5429548/131254047-0c0b7208-198b-4caf-8a61-4e1f2e07ba79.png)

Main page is correct:

![image](https://user-images.githubusercontent.com/5429548/131254122-459d7c3e-5a02-4720-915c-d54683ba4e3a.png)

but on forum page subforums are not displayed
![image](https://user-images.githubusercontent.com/5429548/131254140-cea409ae-1896-48dd-9e36-1db0b6db1408.png)

Reason for this is in function sc_subforums() - 
global $forumId is NULL

I tried to fix this with:
` $forumSCvars['forumId'] = $forumId; `and then` $forumId = $this->var['forumId']; ` in forum_viewforum.php
I found that  
global $FORUM_VIEW_SUB, $FORUM_VIEW_SUB_START, $FORUM_VIEW_SUB_END; are NULL too.
($forum is OK)

After similar fix (using vars instead global variables), this was result:
![image](https://user-images.githubusercontent.com/5429548/131254519-8a79d788-f298-4088-9de4-79b055a7d596.png)

So there is something deeper... 

Thanks

### PHP Version

```
PHP 8
```

## Additional Information
- used latest e107
- bootstrap3 theme
- no noncore plugins
- PHP 8

**Comment by Deltik** [comment]
I did a regression bisection and found that 4a9cf379a69e58344659fa8619de18a9725cd386 causes the third level subforum to disappear from the second level subforum.  I performed the `git bisect` between `v2.3.0` and 34ad8bc1d807d78d340fa9d0aefe1f6893ef567c.  Log:
```
www-data@e107dev:~/html/e107$ git bisect log
git bisect start
# bad: [34ad8bc1d807d78d340fa9d0aefe1f6893ef567c] More jQuery.once() to jQuery.one() replacements.
git bisect bad 34ad8bc1d807d78d340fa9d0aefe1f6893ef567c
# good: [7214b75794f6431a376f6839bca7f30137f45067] Fixes #4223 - Fix for bootstrap style inside TinyMce. Thanks go to @tgtje
git bisect good 7214b75794f6431a376f6839bca7f30137f45067
# bad: [940390107733a2517222ecaa8478175ebcc24e5a] #3786 - Update documentation for e107::user()
git bisect bad 940390107733a2517222ecaa8478175ebcc24e5a
# good: [fc758b13d61fb8fddb2fb6d9dcb9d754d97ca3fa] Merge pull request #4326 from Jimmi08/patch-5
git bisect good fc758b13d61fb8fddb2fb6d9dcb9d754d97ca3fa
# good: [7279e0273eded587e7e6733d0cbc7224158d6cc5] Valid login event added. Session conflict fix. Session test added. Featurebox tree() fix.
git bisect good 7279e0273eded587e7e6733d0cbc7224158d6cc5
# good: [ab75f150f8910ea30180b8f8b75291cec1ec33cc] PHP8 Fixes. Renamed 'search' class (in search.php) to 'search_front' to avoid conflicts.
git bisect good ab75f150f8910ea30180b8f8b75291cec1ec33cc
# bad: [8b73cfee5cdaabcbc8052184b1427a87857a06bc] Theme manager now using e107::isCompatible() method.
git bisect bad 8b73cfee5cdaabcbc8052184b1427a87857a06bc
# good: [ead2416485034992cc23593d423513f4da131682] Test too specific for shuffle. Needs rework.
git bisect good ead2416485034992cc23593d423513f4da131682
# bad: [45b536b50a9e08537f65bb2e9900633ef08c2084] Removed the json_compat_handler.php and some unused methods.
git bisect bad 45b536b50a9e08537f65bb2e9900633ef08c2084
# bad: [4b0edad4599aefccac4f8d786a04ff90ad56f537] Various PHP8 Fixes
git bisect bad 4b0edad4599aefccac4f8d786a04ff90ad56f537
# bad: [4a9cf379a69e58344659fa8619de18a9725cd386] PHP8 Forum code cleanup
git bisect bad 4a9cf379a69e58344659fa8619de18a9725cd386
# good: [aafd277331b1bfa36fea0763faf95445d497422f] Shuffling issue. Disable test.
git bisect good aafd277331b1bfa36fea0763faf95445d497422f
# first bad commit: [4a9cf379a69e58344659fa8619de18a9725cd386] PHP8 Forum code cleanup
```

**CC:** @CaMer0n because you are the author of 4a9cf379a69e58344659fa8619de18a9725cd386.
