### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4549]
It is really useful to have this feature as a core plugin to upload and change fonts.

**Comment by 2548ir** [comment]
In case of implementation I will pay for the support to PayPal: donate (at) e107.org

**Comment by Jimmi08** [comment]
@2548ir just from curiosity...  
How do you imagine this? It is theme-related, each theme can use different fonts. Do you mean for the bootstrap3 theme? 
In most cases, google fonts are used. But again, without theme support, this will not work. 

They rejected the color picker I was asking for, I am curious about the answer to this.  

BTW, do you mean something like this? (Screenshot is from WordPress theme)
![image](https://user-images.githubusercontent.com/5429548/131548508-aff96857-1172-4cb9-9493-70a6c4588f15.png)

**Comment by 2548ir** [comment]
@Jimmi08 yes, the purpose is default bootstrap theme and a plugin with the same functions in the picture you have mentioned but something more optional.

**Comment by 2548ir** [comment]
@Jimmi08 yes, the purpose is placing such functions inside default bootstrap theme preferences in admin area but something more optional.

**Comment by Moc** [comment]
Themes can easily support this using the theme_config.php file. I'd leave this to theme authors rather than a standard functionality in core.

**Comment by 2548ir** [comment]
Update: for those who need to change the bootstrap default font manually:

@font-face {
    font-family: 'BYekan';
    src: url('/themes/bootstrap3/fonts/BYekan.eot'); /* IE9 Compat Modes */
    src: url('/themes/bootstrap3/fonts/BYekan.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('/themes/bootstrap3/fonts/BYekan.woff') format('woff'), /* Modern Browsers */ url('/themes/bootstrap3/fonts/BYekan.ttf') format('truetype'), /* Safari, Android, iOS */
    font-weight: 700;
}

@font-face {
     font-family: 'B Yekan';
     src: local('?'),
     local('B Yekan'),
     url('/themes/bootstrap3/fonts/BYekan.woff') format('woff');
font-weight: normal;
font-style: normal;
}

body {
	font-family: 'B Yekan', tahoma, Arial;
	font-weight: 400;
	color: #650;
	font-size: 12px;
	line-height: 20px;
	width: 100%;
}

**Comment by 2548ir** [comment]
Update: for those who need to change the bootstrap default font manually:

@font-face {
    font-family: 'BYekan';
    src: url('/themes/bootstrap3/fonts/BYekan.eot');
    src: url('/themes/bootstrap3/fonts/BYekan.eot?#iefix') format('embedded-opentype'), url('/themes/bootstrap3/fonts/BYekan.woff')
    format('woff'), url('/themes/bootstrap3/fonts/BYekan.ttf') format('truetype'),
    font-weight: 700;
}

@font-face {
     font-family: 'B Yekan';
     src: local('?'),
     local('B Yekan'),
     url('/themes/bootstrap3/fonts/BYekan.woff') format('woff');
     font-weight: normal;
     font-style: normal;
}

body {
	font-family: 'B Yekan', tahoma, Arial;
	font-weight: 400;
	color: #650;
	font-size: 12px;
	line-height: 20px;
	width: 100%;
}

**Comment by 2548ir** [comment]
Update: for those who need to change the bootstrap default font manually:

@font-face {
    font-family: 'BYekan';
    src: url('/themes/bootstrap3/fonts/BYekan.eot');
    src: url('/themes/bootstrap3/fonts/BYekan.eot?#iefix') format('embedded-opentype'), url('/themes/bootstrap3/fonts/BYekan.woff') format('woff'), url('/themes/bootstrap3/fonts/BYekan.ttf') format('truetype'),
    font-weight: 700;
}

@font-face {
     font-family: 'B Yekan';
     src: local('?'),
     local('B Yekan'),
     url('/themes/bootstrap3/fonts/BYekan.woff') format('woff');
     font-weight: normal;
     font-style: normal;
}

body {
	font-family: 'B Yekan', tahoma, Arial;
	font-weight: 400;
	color: #650;
	font-size: 12px;
	line-height: 20px;
	width: 100%;
}

**Comment by 2548ir** [comment]
Update: for those who need to change the bootstrap default font manually:

@font-face {
    font-family: 'BYekan';
    src: url('/themes/bootstrap3/fonts/BYekan.eot');
    src: url('/themes/bootstrap3/fonts/BYekan.eot?#iefix') format('embedded-opentype'), url('/themes/bootstrap3/fonts/BYekan.woff') format('woff'), url('/themes/bootstrap3/fonts/BYekan.ttf') format('truetype'),
    font-weight: 700;
}

@font-face {
     font-family: 'BYekan';
     src: local('?'),
     local('B Yekan'),
     url('/themes/bootstrap3/fonts/BYekan.woff') format('woff');
     font-weight: normal;
     font-style: normal;
}

body {
	font-family: 'BYekan', tahoma, Arial;
	font-weight: 400;
	color: #650;
	font-size: 12px;
	line-height: 20px;
	width: 100%;
}
