### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [e107inc/e107#4553]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Moc** [comment]
@zidingz Thank you for your feedback. I'll get to work on the SECURITY.md file. 

In the meantime, please contact us by sending an email to security@e107.org.

**Comment by Moc** [comment]
The `SECURITY.md` file was added: https://github.com/e107inc/e107/commit/b1dbd1744db74a2c91e9c317577c6851ba85c39c

For anyone reading along, after investigation the vulnerability report turned out to be invalid.
