### ISSUE TITLE
weird $_GET key for news.php

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4558]
## Question
How could I find a reason for this? What to test?

- frontend news page  news.php
- with the custom menu, I tested a value of $_GET
- from some reason, there is always a key "tag"

```
Array
(
    [tag] => 
)
```
`array(1) { ["tag"]=> NULL }`
 
Is this correct?

**Comment by Moc** [comment]
I think this check is there to see if the news page with specific tags for newsitems should be displayed.
