### ISSUE TITLE
installation to existing database

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4562]
## Question
 
Why - when installing e107 to the existing database - do you drop all tables and not only e107 tables?

`if($this->dbqry('DROP DATABASE `'.$this->previous_steps['mysql']['db'].'` '))`

**Just from curiosity.** 
I am aware of this and there is the message that data will be deleted, so no problem, but I never met something like this with other CMS. Normally there is a list of tables and those tables are deleted.

What I am doing now:
Back up the existing database, export it, install e107 and then import the original database back.  

Am I right that if you would delete only tables with the set prefix, it would still delete tables with these settings:
Original DB: `e107_wpx_`
New E107 DB: `e107_`

Thanks for your time

**Comment by Deltik** [comment]
According to the Git history, that `DROP DATABASE` was added in [an attempt](https://github.com/e107inc/e107/commit/1bae45f824825f1b80f4ef243aad7c1fc15653ee#diff-19e3c84c1b3ce87245588ae6ee7791fe3b94c98a8f955ea3e89f9f5865144ca0R630) to fix https://github.com/e107inc/e107/issues/676.

I agree with you that it is not a nice solution, so perhaps we should turn this question into a feature request to make the installer not delete the database.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/discussions/4989

**Comment by Jimmi08** [comment]
It is working correctly now. If you check Create database, old database is created. If you left this unchecked. you get warning about database exists but foreign tables are left untouched.
