### ISSUE TITLE
User Search Not Working

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4576]
## Bug Description
When I try to do a search among the users, I get a return of nothing at all.

## How to Reproduce
Go to Users in the Admin panel and attempt to use the search feature.

## Expected Behavior
It should bring up users or IPs that conform to what you're putting in.

## Screenshots
![image](https://user-images.githubusercontent.com/80976233/134961117-2ed2ab9d-f477-4507-b0e0-4c7164e5685b.png)

## Server Information
Not sure what to put here

### PHP Operating System

Linux gator3311.hostgator.com 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64 
```

### PHP Version

PHP Version 7.4.23
```

### PHP Modules

- bcmath
- bz2
- calendar
- cgi-fcgi
- Core
- ctype
- curl
- date
- dom
- exif
- fileinfo
- filter
- ftp
- gd
- gettext
- gmp
- hash
- iconv
- imagick
- imap
- intl
- ionCube Loader
- json
- libxml
- mbstring
- mysqli
- mysqlnd
- odbc
- openssl
- pcntl
- pcre
- PDO
- pdo_mysql
- PDO_ODBC
- pdo_pgsql
- pgsql
- Phar
- posix
- pspell
- readline
- Reflection
- session
- SimpleXML
- soap
- sockets
- SourceGuardian
- SPL
- standard
- tidy
- tokenizer
- xml
- xmlreader
- xmlrpc
- xmlwriter
- xsl
- zip
- zlib

### Client Information

Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by Windthin** [comment]
Something's odd with the search function for the Pages and Menus area. When I do searches, it only shows things in the pages or menus themselves, not in the titles for those pages or menus. Should it do that?

**Comment by CaMer0n** [comment]
@Windthin I'm unable to reproduce this issue. 
In your screenshot you are using 2 filters.. you're searching for "wind" and those in a userclass called "Admin Class". 

Try setting it like this: 

![image](https://user-images.githubusercontent.com/2825679/143091250-8e69158f-cf20-4a60-b851-e5b8b7e85139.png)

Does it help?

**Comment by CaMer0n** [comment]
Traced the issue to the use of `~` in one of the field names. Removed field (unused) to correct the issue. 
Have added field validation to the admin area to avoid similar issues in future.
