### ISSUE TITLE
Captcha for the Visually Impaired

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4577]
## Question
I see several Captcha options available; but I do not know which, if any, is best for somebody with visual impairment; one of my admins has issues there, and I am hoping there is an option with an audio alternative or something similar that she can use?

## Expected Source
I looked on here first to see if anybody mentioned this, and nobody had.

## Additional Context
We've just undergone a major upgrade from 1.04 to 2.x and are only for the first time adding captcha to the site, so I want to make sure I do it in a way that doesn't exclude one of my admins.

**Comment by Moc** [comment]
Hi @Windthin 

These type of questions are best asked on e107help.org for now :)
Closing it here.
