### ISSUE TITLE
Subforums are not appearing within their Forums

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4579]
## Bug Description
When I go a forum with subforums, the subforums are not there.

## How to Reproduce
Go to a forum that has subforums.

## Expected Behavior
Normally, the subforums are listed above normal threads for the forum they belong under.

## Screenshots
![image](https://user-images.githubusercontent.com/80976233/134986934-b8c2b30d-8d46-48b3-86ca-5ac8d55ab954.png)

![image](https://user-images.githubusercontent.com/80976233/134986987-7aeff7bb-f42e-4f81-9ef5-1f2c32e0c578.png)

## Server Information

Not sure what to put here.

### PHP Operating System

Linux gator3311.hostgator.com 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64

### PHP Version

PHP Version 7.4.23

### PHP Modules

bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
ionCube Loader
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pgsql
Phar
posix
pspell
readline
Reflection
session
SimpleXML
soap
sockets
SourceGuardian
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

### Client Information

Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by Moc** [comment]
Perhaps related to #4544

**Comment by Windthin** [comment]
If worst comes to worst, I can create some menus for these until/if it is resolved, so it's less of a problem than some other issues, but it is odd.

**Comment by Jimmi08** [comment]
@Moc  yes, it is related.  I use the e107 version from February 2021 and there are not those issues.
