### ISSUE TITLE
Always need to set UTF-8 before posting, updating etc to db?

### ISSUE THREAD

**Issue by djbeater** [e107inc/e107#458]
#### My problem is with UTF-8 encoding

if i call db with 

```php
$sql = e107::getDb();
```
and insert some data in db my utf-8 characters not posting correctly.

I need alway use this code:
```php
$sql = e107::getDb();
$sql->db_Set_Charset("utf8");
```
If now i post some data all goes OK.

#### Why not set in core default value utf8?

**Comment by CaMer0n** [comment]
@Jimmi08 Do you know if this is still an issue?

**Comment by Jimmi08** [comment]
I am not sure. I can't test it without reinstall xampp itself (now it works without problems)
but I think this is related: 
https://github.com/e107inc/e107/issues/847
There is no feedback so I don't know if my advice helped.

There is no problem on production server (apache, mysql or apache mariadb).

**Comment by CaMer0n** [comment]
Okay thanks, will close it for now.
