### ISSUE TITLE
BBCode Box Doesn't Work

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4580]
## Bug Description
The BBCode box is not working on any page. I have checked it for pages, PMs, and the forum. If you click on the button to BOLD or CENTER or anything else it seems, they do not function.

Testing, the buttons not working are bold, italics, underline, insert image, left align, center align, right align, and justify align. The other buttons seem to be working.

## How to Reproduce
1. Go to any page with a BBCode box.
2. Try to use said box, either on its own or by highlighting something and then hitting a button.

## Expected Behavior
The BBCode buttons should automatically add code to bold, center, etc.

## Server Information
Do not know.

### PHP Operating System
Linux gator3311.hostgator.com 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64

### PHP Version

PHP Version 7.4.23

### PHP Modules

bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
ionCube Loader
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pgsql
Phar
posix
pspell
readline
Reflection
session
SimpleXML
soap
sockets
SourceGuardian
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

### Client Information
Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by CaMer0n** [comment]
@Windthin Please check your browser console for javascript errors.

**Comment by Windthin** [comment]
@CaMer0n I am seeing 12 errors.

![image](https://user-images.githubusercontent.com/80976233/135349916-52f56ec5-a3fe-4a43-b6cc-5dd4f073aca0.png)

**Comment by Windthin** [comment]
That was the front end, I see far more on the back end: 

![image](https://user-images.githubusercontent.com/80976233/135350487-6d979918-a153-43b6-9629-527d697a2cf7.png)

![image](https://user-images.githubusercontent.com/80976233/135350505-5dc5ca29-2492-44fb-b24a-7ea44bae0c09.png)

**Comment by Jimmi08** [comment]
@CaMer0n 
Confirmed, no error in console. BB Code link works, others don't have onclick action. (List works too, onclick is there)

![image](https://user-images.githubusercontent.com/5429548/135350357-1f0c4cfb-9d30-487f-9dfb-84228c60586e.png)

**Comment by Windthin** [comment]
Could this be a bad cookie issue for me? I'm afraid to remove mine, because I don't know how to get back in once I am out of the site, with the maintenance setup.

**Comment by Windthin** [comment]
Okay, so, I purged my browser of old cookies, but it still doesn't work for me. Not seeing any errors from the front end after that, but lots on the back end.

**Comment by Jimmi08** [comment]
@Windthin I don't know I think there is a problem with HTML markup, but I am not sure.

**Comment by Windthin** [comment]
@Jimmi08 I purged my cookies, had no errors, then went into a screen with a BB Code block and got this:

![image](https://user-images.githubusercontent.com/80976233/135355445-00822e0e-ad4e-4abd-8349-4a1daaf70490.png)

**Comment by Windthin** [comment]
Testing, the buttons not working are bold, italics, underline, insert image, left align, center align, right align, and justify align. The other buttons seem to be working.

**Comment by Windthin** [comment]
@CaMer0n @Jimmi08 I took down the maintenance flag temporarily and had a couple of players test the BB Code issue I've been having. They confirmed they also could not use these buttons.

**Comment by Jimmi08** [comment]
@Windthin it is confirmed by me too. And I think I maybe found the reason (nobody confirmed it). I am not able to follow the latest changes (parsing etc), so I have no idea what is wrong. As they said to me some time ago - you shouldn't use the developer version for the live site.   I can't help you, sorry.  I switch to TinyMCE if I need a forum plugin.

**Comment by Windthin** [comment]
@Jimmi08 If there's a better plugin, I am all for that. I did a search though and did not see a TinyMCE, though. What am I seeking, please?

**Comment by CaMer0n** [comment]
@Windthin Bbcode box was failing because the page was failing to fully load. 
The script ended due to an outdated script: e107_plugins/pm/private_msg_menu.php
I have removed it now.

**Comment by Jimmi08** [comment]
@Windthin TinyMce is the core plugin, just install it and set editor in forum options.

**Comment by Windthin** [comment]
@Jimmi08  Okay, for Forum Preferences I see System Default and BBCode as editor options. Both seem to be the same thing, though.

**Comment by Jimmi08** [comment]
@Windthin 

![image](https://user-images.githubusercontent.com/5429548/135771084-5e77d93d-7aff-4914-918b-4b29cd00f2fb.png)

**Comment by Windthin** [comment]
I'm afraid that third option is not showing up. I wonder if it has to do with the issues Cameron says there are with upgrading the forums.

**Comment by Jimmi08** [comment]
@Windthin Did you have Tinymce installed?
![image](https://user-images.githubusercontent.com/5429548/135804435-c4c7b703-ad0d-4e90-b63f-913163483e5a.png)

Latest sync and it is there:
![image](https://user-images.githubusercontent.com/5429548/135804724-b70acd65-b3e9-4e2d-bb0c-057f0d5a338a.png)

**Comment by Windthin** [comment]
@Jimmi08  Okay, I found that under plugins Not Installed and installed it, but the text box didn't change at all, leading me to believe that it is this upgrade issue Cameron mentioned.
