### ISSUE TITLE
what are rules for email debugging

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4581]
What are the rules for email debugging?

I know that there is a preference for this and I have set Mailshot logging No logging. 

But I have a site with debug mode on (with browser addon, Basic, not developer mode). 

I was testing to resend the activation email to user. I understand that this is a nice shortcut for developer, with debug mode on, but it is pretty confusing now.

It wasn't successful because debug mode ON.   I saw the message: 
**Email Debugger active. Simulation Only!**
   
But there was the message about sending email too:
 
![image](https://user-images.githubusercontent.com/5429548/135450181-709416d3-30e0-4165-bf32-b34630170590.png)

I need to look at the code to know that the email wasn't sent at all.

Why do you return success info about sending email?  How can I rely now on this message in other cases when I know it is not always true? 

```

		if(getperms('0') && E107_DEBUG_LEVEL > 0)
		{
			e107::getMessage()->addDebug("Email Debugger active. <b>Simulation Only!</b>");
			e107::getMessage()->addDebug($mailer->preview($eml));
			return true;
		}

		if(!empty($options['debug']))
		{
			return $mailer->preview($eml);
		}

		
		return $mailer->sendEmail($userInfo['user_email'], $userInfo['user_name'], $eml, false);
```

`EDIT:  By the way, this email template is missing from Email templates preview.`
it is there under the signup tab. I got confused because the translation is a bit different and it was displayed in English here.  

Thanks

**Comment by Moc** [comment]
Debug mode should only be used when actually debugging. 

In debug mode, activation emails are not send. The success message is displayed to confirm that normally, the activation email would be send.

**Comment by Jimmi08** [comment]
@Moc it should be a rule for developer mode when you set it on.  
 
I agree, if you debug emails, it shouldn't be sent. But debug mode is used for tons of things. Not only for emails.

I supposed that this setting has something with debugging emails:
![image](https://user-images.githubusercontent.com/5429548/147124992-fa9419c2-fecd-428b-b374-e9cbe5ee03c8.png)
