### ISSUE TITLE
NewPage= Function Not Working

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4586]
## Bug Description
The [newpage=XXX] function is not working properly; instead of creating a dropdown menu with all the sub-pages, the pages show up as large type links in the upper left corner of the page.

## How to Reproduce
1. Use the [newpage=XXX] code in a page to attempt to break up the page into multiple pages.

## Expected Behavior
In  e107 1.04 and before, you could use the [newpage=XXX] function to split up one page into many pages, with a dropdown menu at the bottom allowing for navigation between the pages.

## Screenshots
![image](https://user-images.githubusercontent.com/80976233/135724088-d6e70e18-8147-48a9-aeef-323dc769d0bb.png)

## Server Information
Do not know.

### PHP Operating System
Linux gator3311.hostgator.com 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64

### PHP Version
PHP Version 7.4.23
```

### PHP Modules

bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
ionCube Loader
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pgsql
Phar
posix
pspell
readline
Reflection
session
SimpleXML
soap
sockets
SourceGuardian
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

### Client Information

Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

## Additional Information
Add any other context about the problem here.

**Comment by Moc** [comment]
#2774

**Comment by Windthin** [comment]
@Moc  Hmmm. Based on this response, it seems that newpage is not viable. Is there an alternative for making multiple pages other than lots of pages with menus? I don't really know how this Book and Chapter thing works.

**Comment by Moc** [comment]
Please await @CaMer0n's advice.

**Comment by CaMer0n** [comment]
@Moc I just tested on e107 v1.0.4, and it has similar behavior to v2. 

![image](https://user-images.githubusercontent.com/2825679/143132983-6f2e8d66-5c7e-4b73-ac81-45b56bf4e20b.png)

@Windthin What version of e107 did you have installed prior to beginning your upgrade to v2?

**Comment by Moc** [comment]
I think the main issue is not having a drop-down at the bottom of the page?

@Windthin can you elaborate on the changes you're seeing and what you are expecting to see? 

@CaMer0n I'm pretty confident there have been no changes to this functionality between the latest few 0.7.x releases and the 1.0.4 release. Also @Windthin mentioned 1.0.4 as his previous version.

**Comment by CaMer0n** [comment]
@Moc I thought the same, but that screenshot above is a fresh install of v1.0.4.

**Comment by CaMer0n** [comment]
For reference. Using ```{CPAGENAV: tmpl=dropdown}``` in **page_template.php** will now provide a dropdown version.
