### ISSUE TITLE
USERID is not defined in login event

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4591]
## Bug Description

Not sure if this is a bug or an intention 

I am using the user login event after the user is login in.

Normal e_event.php addon

```
		$event[] = array(
			'name'	=> "login", 
			'function'	=> "create_author_account",  
		);
```

 I need to get userdata (user is already logged in) but this fails:

`$userData = e107::user(USERID);`

`var_dump(USERID);`
`int(0) `

Thanks

**Comment by Moc** [comment]
Closing as duplicate in favour of #4618

**Comment by Jimmi08** [comment]
Thanks, I couldn't find it before, so I thought it was just my imagination that I already reported this.
