### ISSUE TITLE
using 2 editors always ends with tinymce4 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4592]
## Bug Description
If tinymce4 is installed, any setting for other editor is overridden

Case:  need to use tinymce4 for all e107 except custom plugin.  Or use other editor only for forum 

## How to Reproduce
1. You can install SimpleMDE from e107.org
2. Let Tinymce4 installed 
3. Set SimpleMDE for forum
4. Check your post

Result: tinymce4 is loaded 

## Expected Behavior
Needed functionality is already implemented on forum;
`return e107::getForm()->bbarea('post',$text,'forum','forum','large', array('wysiwyg' => $wysiwyg));`
 
In fact, SimpleMDE is not working anymore because .once() jquery error, but it is just example. As soon as you uninstall tinymce4 , then no wysiwyg is displayed, what is correct because broken plugin. 

With tinymce4 installed wrong editor is displayed.

**Comment by Jimmi08** [comment]
Maybe fixed
https://github.com/e107inc/e107/issues/4747

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, please confirm.

**Comment by CaMer0n** [comment]
Closing, but please re-open if necessary.
