### ISSUE TITLE
login event is not working or how to get it works

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4618]
## Bug Description
Not sure if this is because alt_auth is used but the event on user login is not working

## How to Reproduce
I have the same function for login and user edit :

```
		$event[] = array(
			'name'	=> "login", 
			'function'	=> "create_author_account", // ..run this function (see below).
		);
        
		$event[] = array(
			'name'	=> "user_profile_edit",  
			'function'	=> "create_author_account", // ..run this function (see below).
		); 
```

User profile editing is working.

The function uses this:

`$userData = e107::user(USERID);`

Is possible that after the login event USERID is not set?   

The purpose of the event is - to check related table record (by user_id)  and if doesn't exist, then create it.

Thanks

**Comment by Deltik** [comment]
I thought the event was [`user_login`, not `login`](https://github.com/e107inc/e107/blob/31ea9bf7879d3acad35f5f730ee7c1d5ca324ff6/e107_handlers/user_model.php#L1806-L1806).

**Comment by Jimmi08** [comment]
This is from _blank plugin example:

```
		$event[] = array(
			'name'	=> "login", // when this is triggered... (see http://e107.org/developer-manual/classes-and-methods#events)
			'function'	=> "myfunction", // ..run this function (see below).
		);

		return $event;
```

**Comment by Deltik** [comment]
Huh, then what is `user_login`? ಠ_ಠ

**Comment by Jimmi08** [comment]
The field in user table? :)

**Comment by Moc** [comment]
@Jimmi08 Is the login event triggered at all as far as you can see? If not, did you try `user_login`?

**Comment by Jimmi08** [comment]
@Moc 
If I remember correctly, it is triggered, but it fails here:  

```
                   $insert = array(
  					'penname' => $userData['user_name'], 
  					'email' => $userData['user_email'],  
  					'password' => '', //delete 
  					'date' => $userData['user_join'], 
                     'user_id' => USERID,  
  					'_DUPLICATE_KEY_UPDATE' => 1
    				);
```

e_event use both events:

```
		$event[] = array(
			'name'	=> "login", 
			'function'	=> "create_author_account", // ..run this function (see below).
		);
        
		$event[] = array(
			'name'	=> "user_profile_edit",  
			'function'	=> "create_author_account", // ..run this function (see below).
		);   

```

because user_profile_edit works, I don't think that problem is in the event function itself

While debugging SQL I found that this is not working:

$userData = e107::user(USERID);

So it looks like that event is fired before USERID is filled.  Is there a way how to check this?  Or use something to get the ID of just logged-in user?

Thanks

**Comment by Deltik** [comment]
My opinion is that you should be using [`e107::getUser()->getId()`](https://github.com/e107inc/e107/blob/90108eab3c8c7667d3a2560acf97f40dbe4fd3b3/e107_handlers/user_model.php#L153-L153) instead of the constant `USERID`.  The logged in user ID can change during the execution of e107, so having a constant (`USERID`) does not make sense to me.

**Comment by Jimmi08** [comment]
It sounds good to me. USERID is used in most examples, so...
I will try it, thanks.

**Comment by Moc** [comment]
@Jimmi08 Please provide feedback if `e107::getUser()->getId()` worked.

**Comment by Jimmi08** [comment]
Tested this way in e_event:
```
            $new_userid = e107::getUser()->getId();
            $userData = e107::user($new_userid);
            var_dump($new_userid);
            var_dump($userData);
            die;
```

result:
`int(0) bool(false) `

Then I found a similar test is in the forum event... I uncommented it 
```
	    $myfile = fopen("newfile.txt", "a") or die("Unable to open file!");
		$txt = "login (".USERID.")\n";
        $new_userid = e107::getUser()->getId();
        $txt .= "getId (".$new_userid.")\n";
		fwrite($myfile, $txt);
		fwrite($myfile, print_r($data,true));
		fclose($myfile);
```
and the result was:
```
login (0)
getId (0)
Array
(
    [user_id] => 546
    [user_name] => ***
    [class_list] => 253,251,0
    [user_admin] => 0
    [user_email] => ***
)
```
		 
Then it hit me that I am using alt_auth plugin. but result was the same.
So it looks that I should use only $data['user_id'], user is not available in e_event.

But this should be mentioned in _blank plugin e_event file.
