### ISSUE TITLE
Registration Page Not Showing

### ISSUE THREAD

**Issue by Windthin** [e107inc/e107#4624]
## Bug Description
The registration page is blank, meaning nobody can register.

## How to Reproduce
1. Go to the site as a guest (or log out).
2. Click on "Sign Up" on the right-hand side.

## Expected Behavior
There should be a form to let one sign up for the site, along with the instructions telling them what to do.

## Screenshots
![image](https://user-images.githubusercontent.com/80976233/144026340-376d91c4-c83a-461a-9212-91040ca59dc6.png)

## Server Information
Do not know.

### PHP Operating System
Linux gator3311.hostgator.com 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64

### PHP Version
PHP Version 7.4.23P Version 7.3.13

### PHP Modules

bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
ionCube Loader
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pgsql
Phar
posix
pspell
readline
Reflection
session
SimpleXML
soap
sockets
SourceGuardian
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

### Client Information
Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by Jimmi08** [comment]
This is the fix if the theme use the signup template is written the old way:
- add this at the end of the template file. 
```
$SIGNUP_TEMPLATE['start'] = $SIGNUP_BEGIN;
$SIGNUP_TEMPLATE['body'] = $SIGNUP_BODY;
$SIGNUP_TEMPLATE['end'] = $SIGNUP_END;
$SIGNUP_TEMPLATE['coppa'] = $COPPA_TEMPLATE;
$SIGNUP_TEMPLATE['coppa-fail'] = $COPPA_FAIL;
$SIGNUP_TEMPLATE['extended-user-fields'] = $SIGNUP_EXTENDED_USER_FIELDS;
$SIGNUP_TEMPLATE['extended-category'] = $SIGNUP_EXTENDED_CAT ;
```

this 
`if($template = e107::getCoreTemplate('signup'))` is always true, because it is loading core template now, 
so fix above is probably failing. 

$SIGNUP_TEMPLATE is mandatory now to use in signup_template.php file.
