### ISSUE TITLE
user last visit shortcodes (2) look  wrong 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4665]
## Bug Description
I have imported this field according this
		$target['user_lastvisit']   = $source['user_lastvisit'];
and it is not displayed correctly (but it is correct in database)

I think that this:

```
	function sc_user_lastvisit($parm='')
	{
		return $this->var['user_currentvisit'] ? e107::getDate()->convert_date($this->var['user_currentvisit'], "long") : "<i>".LAN_USER_33."</i>";
	}
	
	
	function sc_user_lastvisit_lapse($parm='')
	{	
		return $this->var['user_currentvisit'] ? e107::getDate()->computeLapse($this->var['user_currentvisit']) : '';
	}
```

Should be at least:
```
	function sc_user_lastvisit($parm='')
	{
		return $this->var['user_currentvisit'] ? e107::getDate()->convert_date($this->var['user_currentvisit'], "long") : e107::getDate()->convert_date($this->var['user_lastvisit'], "long");
	}
	
	
	function sc_user_lastvisit_lapse($parm='')
	{	
		return $this->var['user_currentvisit'] ? e107::getDate()->computeLapse($this->var['user_currentvisit']) : e107::getDate()->computeLapse($this->var['user_lastvisit']);
	}
```

Not sure when user_currentvisit is filled. I suppose it is mean that the user is online? if yes, then a message "online" would be better.  

The problem with the solution above is that if that field is not filled it shows the time 1.1.1970 (in according format)

I would suppose that convert_date() or computeLapse() returns nothing if there is no date sent.

value of $this->var['user_lastvisit']  is `string(1) "0" `

Thanks

**Comment by Moc** [comment]
Please try and stick as much as possible to the bug report template. 

In these type of reports, it really helps to provide examples or screenshots. 

Which values are in the database, what are you seeing and what are you expecting to see instead?

If more information is needed, it will be asked for.

**Comment by Jimmi08** [comment]
@Moc 
I asked for confirmation that the code is correct.  Where is the value from field "user_lastvisit"  used?    
Now either LAN_USER_33 is returned or field user_currentvisit.  

I have imported users with the import plugin.  
https://github.com/e107inc/e107/blob/754c29d2302fec5d24153f84fe32dd0a75f1db28/e107_plugins/import/providers/PHPNuke_import_class.php#L149

value $target['user_lastvisit']  is not displayed on user profile page. 

So what field is correct?

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. PR welcome.
