### ISSUE TITLE
Tag cloud plugin words

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4677]
Tag cloud plugin only shows the keywords for news on every page but this supposed to show the keywords belong to its page.

**Comment by CaMer0n** [comment]
@2548ir Please post a screenshot example. thanks.

**Comment by 2548ir** [comment]
@CaMer0n Tag cloud plugin has no config page, The issue was edited.

**Comment by 2548ir** [comment]
I close this issue because there was a misunderstanding on my part about the plugin functionality, tags are only belong to news not pages.
