### ISSUE TITLE
Theme layouts visibility filters

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4678]
In bootstrap3 visibility filters for pages has conflict with news SEF URL, for example /contact added to visibility filters list for jumbotron_full but [contact] word in news SEF URL drops that news page into full-width mode.

**Comment by Jimmi08** [comment]
With 2.3.1 you should use routes for the contact page:
`:contact/index`

More information: https://github.com/e107inc/e107/issues/3912
