### ISSUE TITLE
feature request, theme autosprite folder(s)

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#468]
it would be great if there were options for css sprites automaticly generated.

lets say we have folders 
/theme/sprites/sprite1 
/theme/sprites/sprite2 
/thene/sprites/yetanother.. 

the images in these folders should be combined into just 1 image for each folder, and the css sprite data should be added to the current css output. (ie, background positions
width and height.)

i could write a plugin doing most of this, 
but then it would create yet another css file.. and there already are a lot of those..
so integrating this into the core would be a lot nicer and when cached probably faster.

**Comment by Moc** [comment]
Seeing there have been no other people supporting this feature request in the past, I recommend creating  a plugin for this. If there's anything you need adjusted in core to be able to do develop this plugin, feel free to submit a new issue with that request.
