### ISSUE TITLE
Counter menu doesn't work

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4680]
Activating counter_menu causes page crashing and won't show up in area.

**Comment by Moc** [comment]
Please provide more information:

- What does 'page crashing' look like? Does it stop loading the page? (ie. the footer is not loading?) 
- Do you get any errors or warnings?
- Which PHP version are you using?

**Comment by 2548ir** [comment]
@Moc e107v2.3.1 release - php7.4 - footer is not loading with the following error on sidebar:

Fatal error: require_once(): Failed opening required '../../plugins/log/consolidate.php' (include_path='.:/opt/php7.4/lib/php') in /home/.../plugins/siteinfo/counter_menu.php on line 22

**Comment by Moc** [comment]
This issue is fixed already on GitHub and the fix will be part of the next release. 

Please use the latest files from Gihub or wait for the next release.
