### ISSUE TITLE
forum  - issues with canonical urls on topic pages

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4712]
## Motivation
Get correct canonical urls for forum

## first problem - too often changed URL

Now the topic URL is generated from title (it is OK), but with forum the topic title is changed too often, so its URL and then canonical URL is changed too.

Solution: use only version with ID without title part. Example:

```
		$config['topic'] = array(
			'regex'         => 'forum\/([^\/]*)\/([\d]*)(?:\/|-)([\w-]*)/?\??(.*)',
		//	'regex'			=> '^forum/(.*)/(\d*)(?:-|/)([\w-]*)/?\??(.*)',
			'sef'			=> 'forum/{forum_sef}/{thread_id}/{thread_sef}/',
			'redirect'		=> '{e_PLUGIN}forum/forum_viewtopic.php?id=$2&$4'
		);
- notice removed {thread_sef} from SEF URL
		$config['topic-canonical'] = array(
			'regex'         => 'forum\/([^\/]*)\/([\d]*)(?:\/|-)([\w-]*)/?\??(.*)',
		//	'regex'			=> '^forum/(.*)/(\d*)(?:-|/)([\w-]*)/?\??(.*)',
			'sef'			=> 'forum/{forum_sef}/{thread_id}/',
			'redirect'		=> '{e_PLUGIN}forum/forum_viewtopic.php?id=$2&$4'
		);   
```

## second problem, pagination 
Source:   https://developers.google.com/search/blog/2013/04/5-common-mistakes-with-relcanonical#mistake-1:-rel=canonical-to-the-first-page-of-a-paginated-series

All one topic pages (no p parameter, ?p=2... etc)  have the same canonical URL {this is not a problem only with forum)

I don't know how to solve this your way, but I was able to get needed result this way:

```
$page = (varset($_GET['p']) ? (int)$_GET['p'] : 1);
$thread->threadInfo['thread_page'] = $page;
e107::canonical('forum', 'topic-canonical', $thread->threadInfo); 
```

```
		$config['topic-canonical'] = array(
			'regex'         => 'forum\/([^\/]*)\/([\d]*)(?:\/|-)([\w-]*)/?\??(.*)',
		//	'regex'			=> '^forum/(.*)/(\d*)(?:-|/)([\w-]*)/?\??(.*)',
			'sef'			=> 'forum/{forum_sef}/{thread_id}/?p={thread_page}',
			'redirect'		=> '{e_PLUGIN}forum/forum_viewtopic.php?id=$2&$4'
		);   
```

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. Looks like a suitable solution. PR welcome.
