### ISSUE TITLE
forum - with bootstrap5 forum attachment image are not opened in modal

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4726]
## Bug Description
Just noted, after switching the same theme from bootstrap4 to bootstrap5 forum images (attachment) are not opened 

## How to reproduce this
I will add some info when I am able to test this more, it could be related to something else 

` <a data-modal-caption="***" data-target="#uiModal" rel="external" href="***" class="forum-attachment-image e-modal" target="_blank"><img class="thumbnail" src="***" alt=""></a>`

**Comment by CaMer0n** [comment]
'e-modal' trigger needs to be fixed for BS4/5

**Comment by Jimmi08** [comment]
Sorry, I have no idea how.
