### ISSUE TITLE
newforumposts menu - {LAN=USER} displays value 1

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4755]
## Bug Description
The label for the user column is not correct
`{LAN=USER} `displays value 1

## How to Reproduce
new forum posts menu on the homepage
custom theme (not tested with core themes)
main template

- it was correct in 2.3.1

## This was quick fix:
![image](https://user-images.githubusercontent.com/5429548/163792410-40caace3-c192-46b8-b350-2685d7ae95e1.png)

but it shouldn't happen. English.php should be loaded already.

**Comment by CaMer0n** [comment]
Thanks. PR welcome.

**Comment by Jimmi08** [comment]
@CaMer0n it is no problem to replace LAN, but why is this not working? Core LAN strings are not available in menus? LAN_USER still exists in 2.3.2.  What to check? Theme? Frontpage? Menu itself?

**Comment by CaMer0n** [comment]
This is why. I have since changed the priority. 

```
function lan_shortcode($parm = '')
{
	if(empty($parm))
	{
		return null;
	}

	$lan = trim($parm);
	if(defined($lan))
	{
		return constant($lan);
	}
	elseif(defined('LAN_'.$lan))
	{
		return constant('LAN_'.$lan);
	}
	elseif(ADMIN)
	{
		return "<span class='alert alert-danger' style='padding:0'><strong>".$parm ."</strong> is undefined</span>"; // debug info
	}
}
```

**Comment by Jimmi08** [comment]
THANK YOU! This is the correct fix.
