### ISSUE TITLE
User IP may fail to update in user table. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#4757]
User's IP has changed yet the user table still displays the IP at the time of signup.

**Comment by Deltik** [comment]
I thought that long ago, `e107_user.user_ip` was supposed to be the signup IP to prevent too many signups from the same IP address.

**Comment by CaMer0n** [comment]
I don't think it was coded that way. It's just that it appears the "update" code consistently fails, due to a typo.
I'm going to add an event when the IPs don't match to increase flexibility, so that other actions can be triggered if needed.
