### ISSUE TITLE
Quotes are being rendered with the HTML code instead of string cleaned values in signup emails

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#476]
Example:

Registration details for Dimante&#039;s Corner

Instead of Dimante's Corner

I tried setting up different things in the site name box like the html code instead of the ' a \' these rendered as literals so it must be in the shortcode that crafts the email.  

Thanks
-D-

**Comment by CaMer0n** [comment]
The mail routines have been heavily reworked since this was posted. Can someone retest.? @dimante ?

**Comment by dimante** [comment]
I will test today!

On Thursday, February 5, 2015, Cameron <notifications@github.com> wrote:

> The mail routines have been heavily reworked since this was posted. Can
> someone retest.? @dimante <https://github.com/dimante> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/476#issuecomment-73010972>.
>


-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by CaMer0n** [comment]
Thank you!

**Comment by CaMer0n** [comment]
@dimante Parser routine was reworked. It should have fixed any issue like this one. Please re-open if necessary.

**Comment by dimante** [comment]
Problem is still there with the latest update...

**Comment by dimante** [comment]
"Dimante&#039;s Corner: User Logged In" <- subject line of the user login email with the code for single quote instead of text....

**Comment by dimante** [comment]
Fixed via #b245f8a
