### ISSUE TITLE
Problems ater installing e107

### ISSUE THREAD

**Issue by Dxvid64** [e107inc/e107#4767]
Hello, I'm trying to install a new version of e107 but am having a few problems.  The Forum is installed but not displaying correctly, and the same for the ewiki.  In the plugin manager for the Forum, when I click on the "Repair" routine, the admin area throws up a blank page and when I click the "Return to front panel" link in the corner I get this error message,

CRITICAL ERROR:
Line : generic, class2.php
[6]: Unable to form a valid connection to mySQL. Please check that your e107_config.php contains the correct information.

(In fact I've had this blank page many times whilst using the admin area.  When it happens, one click on "Return" gives the error message and a second click returns the admin page to normal.)

I've had a look at the e107_config.php but am unable to find anything, (zip attached.)  I ran an e107 site 14 years ago which had a Forum and an ewiki but I can't remember any problems with them, although I've probably forgotten most of what I learnt then, so I'm hoping someone here might be able to help.  If you want to see what it looks like onsite go here and click on the Forum and ewiki links at top,

http://mprem2.epizy.com/index.php

I'm also having problems with the login button top right. Once you have logged in the button quite often becomes unclickable.

(Not sure if some of these problems may be caused by the occasional slowness of a free host, www.infinityfree.net, but I did start the other e107 site on a free host without too many problems.)

Thanks for any advice you can give,
David. 

Now the login button has stopped working altogether which is a problem as no-one can join the site.  I hope we can fix this, or I might have to start anew with Wordpress or Joomla, which I would hate to do as as I have had a great experience with e107 up to this point.  I can't even login at - http://mprem2.epizy.com/e107_admin/admin.php - ,  well I suppose it is Fri.13th!

Managed to get back in via the admin.php after restoring .sql backup from this afternoon.  1 down, 3 to go.

**Comment by Dxvid64** [comment]
[phpinfo.zip](https://github.com/e107inc/e107/files/8689056/phpinfo.zip)
added .zip of  e107_config.php

**Comment by Dxvid64** [comment]
[e107_config.zip](https://github.com/e107inc/e107/files/8689088/e107_config.zip)
Sorry wrong zip.  Here is e107_config.php

**Comment by Jimmi08** [comment]
You didn't write what e107 version you installed. 2.3.2 git or stable 2.3.1.   What PHP version?  Ewiki will not work with PHP 7 and probably with new e107 either.

**Comment by Dxvid64** [comment]
Thanks for your reply, I'm using 2.3.2 and PHP 7.  I'll give 2.3.1. a try, the wiki is not essential.

**Comment by Jimmi08** [comment]
You can stay with 2.3.2.  But switch to the core theme to avoid issues with the outdated theme.

**Comment by Dxvid64** [comment]
Well I tried a fresh install of 2.3.1. anyway in case I messed up during previous install, but with same problems.  The theme is one of the things I wanted.  Think I'm going to move on to Wordpress now.  Thanks for your time.

**Comment by Dxvid64** [comment]
Managed to get the forum working so will be staying with e107 a little longer!

**Comment by Dxvid64** [comment]
Well the forum problem is fixed (actually caused by my stupidity, for some reason I didn't realise that when creating a forum you also need to create at least one sub-topic for anything usable to appear.)  And as mentioned above the wiki(s) are nor compatible with V.2.  I think that's a pity as I would have thought a lot of sites might like to include a wiki, I did on the last site.  It's a good way to get members more involved and also a good way to inform newcomers in detail about the topic of your site.  Anyway everything is good now and the site should be going live soon.
Thanks for you patience,
David.

**Comment by Dxvid64** [comment]
I'm still getting the issue of the login button not working from time to time using the "BS Gaming 01" theme, even though it says in its info "2.0 Recommended!".  I also like the "Bootstrap 3" and can switch to that if I have to, but I would prefer to use BS Gaming as first choice.  I've no idea how to fix the button, perhaps tweaking the code somehow?

**Comment by Dxvid64** [comment]
Also, if someone could explain to me, in simple English, what to do about this, I would be grateful,

"Warning
allow_url_fopen: If you have Curl enabled, you should consider disabling this feature.
allow_url_include: This is a security risk and is not needed by e107."

I searched and but didn't understand the results.  Nor do I know whether curl is enabled or not.

**Comment by Jimmi08** [comment]
> I'm still getting the issue of the login button not working from time to time using the "BS Gaming 01" theme, even though it says in its info "2.0 Recommended!". I also like the "Bootstrap 3" and can switch to that if I have to, but I would prefer to use BS Gaming as first choice. I've no idea how to fix the button, perhaps tweaking the code somehow?

You should create a separate issue for this. Something similar was discussed on GitHub as a problem in 2.3.2  But nobody made an issue of this.

![image](https://user-images.githubusercontent.com/5429548/168489859-5684bec3-b07b-4874-b8bd-042c4e6ae46e.png)

![image](https://user-images.githubusercontent.com/5429548/168489774-a8822b5a-9367-4bf7-82cb-2489ca407472.png)

Maybe you should replace the button with a link to login.php

**Comment by Dxvid64** [comment]
Ok thanks.  The issue seems to have gone away again for the time being, but if it returns I will try your suggestion.

**Comment by Dxvid64** [comment]
It seems it may be caused by having "Submit News" as a separate link.  When I put it as a sublink of "News" the login is ok again.

**Comment by Dxvid64** [comment]
Cheers, a login link works a treat!

**Comment by Dxvid64** [comment]
Sadly I've had to change to my second choice Bootstrap 3 theme as although BS Gaming 01 says it is compatible with 2 there are a number of things not working in it.  I suppose it's possible it hasn't been updated since it was created in 2016?

**Comment by Jimmi08** [comment]
@Dxvid64 
you can report your issues here:
 
https://github.com/fizi/BS_Gaming_01

**Comment by Dxvid64** [comment]
Thanks will do that.
