### ISSUE TITLE
No warning / alert with wrong login...

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#4779]
## Bug Description
When logging in goes wrong there's no alert, only when you click on a link it shows....

## How to Reproduce
1. Go to login menu on https://e107.nl/demo/
2. Try to login..
3. Wrong login but no alert message, click on either link in the navigation..
4. See error.. now it shows.... 

## Expected Behavior
Should be directly shown...

## Server Information
e107 - Versie 2.3.3 (git)

Site thema - bootstrap3

Beheer thema - Bootstrap 3 v1.0 Door e107 Inc (2013-12-25)

Installatiedatum - donderdag 14 april 2016 - 09:27

Server - Apache/2 - (Systeem: e107.nl)

MySQL - 5.6.51 - PDO: Aan 

### PHP Operating System
PHP Versie - 7.3.31

### Client Information
Your user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

## Additional Information

Oke, found the problem...
**in**
e107_handlers/login.php line 640

e107::getMessage()->reset()->addError($message, 'default', true); **changed to**

e107::getMessage()->reset()->addError($message);

And the alert shows as it's supposed to but i really do not know why... was changed with e107inc/e107@fd42d23 by Cameron, but it's only a quick and dirty fix because the problem is now in the admin section but that's less of a problem to me..

**Comment by Jimmi08** [comment]
Confirmed.  Still issue.
