### ISSUE TITLE
the Bootstrap 5 Theme has some problem

### ISSUE THREAD

**Issue by bluesky0341** [e107inc/e107#4781]
navigation has problem
Drop-down menu can not display on chrome on PC computer

menu can not display on chrome on mobile phone

**Comment by bluesky0341** [comment]
https://ceramicdowelpins.com/

**Comment by Jimmi08** [comment]
Hi, it works fine for me.  If you mean 3rd level, it is not supported by bootstrap3 itself:

https://github.com/e107inc/e107/issues/1212

**Comment by CaMer0n** [comment]
The bootstrap 5 uses stylesheets on a CDN.  Perhaps these are being blocked. Try using "Inspect" in your browser and viewing the Network tab.

**Comment by Moc** [comment]
Closing due to lack of feedback.

**Comment by Jimmi08** [comment]
Your closing this issue (it should stay closed) just reminded me this:
- one of the e107 advantage was the easily switch between CDN and local version.  With bootstrap5 theme this is not possible.  In my opinion it should reflect core pref for this. 

Nevermind, it is example theme, but when I tried to do it this way (local), this happened:
https://github.com/e107inc/e107/issues/4832

So there is something wrong.
