### ISSUE TITLE
Unauthorized access! when trying to install lang pack

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4782]
## Bug Description

Latest git version (just synced) - trying to install any language 

![image](https://user-images.githubusercontent.com/5429548/171103190-c3e4a194-0e92-4e4f-80c8-103425a3d039.png)

![image](https://user-images.githubusercontent.com/5429548/171103780-89166a6f-e3d8-4896-9373-79fb72a1bdd0.png)

 
## Additional Information

PHP 7.4, xampp on localhost

**Comment by tgtje** [comment]
@Moc  confirmed working :thumbsup:
