### ISSUE TITLE
where can i use custom seo title when i send post

### ISSUE THREAD

**Issue by bluesky0341** [e107inc/e107#4783]
how are you?

where can i use custom seo title when i send post

**Comment by bluesky0341** [comment]
i have checked,only has custom description and keywords

**Comment by bluesky0341** [comment]
this is very  important for seo

**Comment by bluesky0341** [comment]
anyone can help?

**Comment by CaMer0n** [comment]
hi @bluesky0341 . Can you elaborate a bit more. What do you mean by _seo title_? Do you mean the `<title>` tag ?

**Comment by CaMer0n** [comment]
@Moc @bluesky0341 

## Screenshot of the new SEO title field
![image](https://user-images.githubusercontent.com/2825679/172269189-640e020c-c96c-4ee8-b93c-f2aa3bc4adc9.png)

## Screenshot of the new SEO title and description character limit options
![image](https://user-images.githubusercontent.com/2825679/172269470-bc1f5283-6b11-4ee5-9f82-c3b87817691e.png)

**Comment by bluesky0341** [comment]
thanks for mail
our site do not have Screenshot of the new SEO title and description character limit option




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "e107inc/e107"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月7日(星期二) 上午8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [e107inc/e107] where can i use custom seo title when i send post (Issue #4783)





 
@Moc @bluesky0341
 
Screenshot of the new SEO title field
 

 
Screenshot of the new SEO title and description character limit options

**Comment by Jimmi08** [comment]
@CaMer0n 
this new field should be able to use shortcodes. At least global like {SITENAME}, not hardcoded stuff. 
Not to mention the local one like {NEWS_CATEGORY} or organization name from contact preferences. 

The separator should be in prefs too.

**Comment by bluesky0341** [comment]
sorry
i do not understand
i am only a user,do not know so much about php





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "e107inc/e107"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月7日(星期二) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [e107inc/e107] where can i use custom seo title when i send post (Issue #4783)





 
@CaMer0n
 this new field should be able to use shortcodes. At least global like {SITENAME}, not hardcoded stuff.
 Not to mention the local one like {NEWS_CATEGORY} or organization name from contact preferences.
 
The separator should be in prefs too.

**Comment by Jimmi08** [comment]
@bluesky0341 
 if some nick is mentioned, the message is for them, not for you.  That message above was for CaMeRon as the author of the changes.

**Comment by bluesky0341** [comment]
first,thanks for effort,for custom seo title,page also do not have custom seo tile,also how can we adjust the length for keywords
