### ISSUE TITLE
is it safe to use e107-master now?

### ISSUE THREAD

**Issue by bluesky0341** [e107inc/e107#4794]
how are you?

is it safe to use e107-master now?

**Comment by CaMer0n** [comment]
It is generally safe, just be sure to check the build status is "passing" before syncing with it: 

![image](https://user-images.githubusercontent.com/2825679/174341774-93c9f982-abf9-4629-a0fe-d0fdd72479c7.png)

### The safest way to install the latest e107-master from Github is to use this option: 

![image](https://user-images.githubusercontent.com/2825679/174342131-e8399a78-a6dc-4bab-b1ed-b6877b6d6f15.png)
