### ISSUE TITLE
feature request, add image sizes and class .img-responsive to thumbnals and images

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#482]
just like it says in the title.

gtmetrx and google page speed would like that very much.

**Comment by Moc** [comment]
It would help to list the occurrences as you find them so they can be fixed at a quicker pace.

**Comment by willem010** [comment]
i think you got most of them by now.
but i will check again soon.

**Comment by CaMer0n** [comment]
I think we got most of them too. 
Closing, but please re-open if necessary.
