### ISSUE TITLE
showPwdBox on frontend signup form

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4835]
## Bug Description
there are 2 password fields:
for both is generated code for pwdMeter.js
The result is 2 input fields with the same ID 

![image](https://user-images.githubusercontent.com/5429548/181756273-6aee086b-238d-4481-8a90-4f0274ae8486.png)

**EDIT:**
there are 4 input fields with the same ID in fact.
2 times for each password field

## How to Reproduce
See signup page code, bootstrap3 theme

## Expected Behavior
it should work only for password field, not second password field (they should be the same)

## Screenshots
![image](https://user-images.githubusercontent.com/5429548/181757747-e6d47c22-ee24-4257-a697-719818a62400.png)

### PHP Version

```
PHP version 8.1
```

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/2957
