### ISSUE TITLE
{NAV_LINK_IDENTIFIER} works differently for normal sitelinks and for e_sitelink addon

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4836]
## Bug Description
{NAV_LINK_IDENTIFIER} is important for identification what submenu belongs to parent 

If you use function, it works correctly:
![image](https://user-images.githubusercontent.com/5429548/181969091-06e4f66b-286f-4a0e-aac8-7a5c6c80dc95.png)

but if you create submenu manually, it is empty

![image](https://user-images.githubusercontent.com/5429548/181970346-33f56284-2ca1-44a3-b675-1b232beb04be.png)
 
 Is it possible to fix this?
Thanks

**Comment by Jimmi08** [comment]
Forget this,` {NAV_LINK_ID}` is correct solution.

**Comment by Alex-e107nl** [comment]
THX Jimmi, but only using #{NAV_LINK_ID} did not work for me, i had to use #link{NAV_LINK_ID}, only numbers was a no go?
Well maybe theme related, but when someone also has the same problem, this solved this for me!
