### ISSUE TITLE
PHP 8 Fatal error - Undefined constant - LAN_PLUGIN_DOWNLOAD_NAME (search)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4840]
## Bug Description

`Fatal error: Uncaught Error: Undefined constant "LAN_PLUGIN_DOWNLOAD_NAME" in C:\xampp\htdocs\e107-ayroui\e107_handlers\search\comments_download.php:13 Stack trace: #0 C:\xampp\htdocs\e107-ayroui\e107_handlers\search\search_comment.php(40): require_once() #1 C:\xampp\htdocs\e107-ayroui\search.php(820): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\e107-ayroui\search.php(1200): search_front->renderResults() #3 {main} thrown in C:\xampp\htdocs\e107-ayroui\e107_handlers\search\comments_download.php on line 13`

**Note: Download plugin is not installed, it is clean default installation**

## How to Reproduce
1. Go to Search Prefs and save them
2. Go to  search.php and use it 

Result
![image](https://user-images.githubusercontent.com/5429548/182954349-6db8fe54-232f-48f1-9f40-acdcf7ae4b42.png)
At the bottom 
 
### PHP Operating System

```
Xampp, windows
```

### PHP Version

```
PHP 8.1.4
```

**Comment by CaMer0n** [comment]
Can this be closed? This code in **search_comment.php** should prevent this. 

```
			if(!e107::isInstalled($value['dir']))
			{
				continue;
			}
```

**Comment by Jimmi08** [comment]
Yes, thank you.
