### ISSUE TITLE
SETIMAGE in menu is not working 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4846]
## Bug Description
Image in the same menu has different size on different pages 

Core Bootstrap 5  theme used  
Sidebar menu layout is used
Cookbook latest menu is used

Template looks like this:
```
$COOKBOOK_LATESTMENU_TEMPLATE['image-title']['start']   = '
<div class="cookbook_latest_menu m-4">';

$COOKBOOK_LATESTMENU_TEMPLATE['image-title']['item']    = '
 <div class="cookbook_latest_menu-item d-flex align-items-center my-2">
  <div class="cookbook_latest_menu-item-image w-50">
    {SETIMAGE: w=100&h=100}{COOKBOOK_RECIPE_THUMB}
  </div>
  <div class="cookbook_latest_menu-item-name flex-grow-2 ms-3">
    {COOKBOOK_RECIPE_NAME}
  </div>
</div>';

$COOKBOOK_LATESTMENU_TEMPLATE['image-title']['end']     = ' </div>';
```
Notice image size:  `{SETIMAGE: w=100&h=100} `

**Contact page (correct)** 
(book/chapter/page is correct too)
![image](https://user-images.githubusercontent.com/5429548/184009144-e8601535-205a-4acc-8ba8-85ea0840e4cf.png)

`<img class="img-responsive" src="/e107-ayroui/media/img/100x0/2022-08/photo_1557038684_abb03178899.jpg" alt="White calzones with marinara sauce">`

**Cookbook detail page**
![image](https://user-images.githubusercontent.com/5429548/184009610-e588b282-80ff-4b63-be53-2f86897828ad.png)

`<img class="img-responsive" src="/e107-ayroui/media/img/a150xa150/2022-08/photo_1557038684_abb03178899.jpg" alt="White calzones with marinara sauce">`
Notice image size - 150px;

**News Detail page**
![image](https://user-images.githubusercontent.com/5429548/184009844-2a9cc9dd-ca42-4d89-bab8-a0df20a0014c.png)

`<img class="img-responsive" src="/e107-ayroui/media/img/a400xa350/2022-08/photo_1557038684_abb03178899.jpg" alt="White calzones with marinara sauce">`
Notice image size - 400x350px;

What is wrong? Template? Shortcode? Core?

PHP 8.1.2
Latest Github

**Comment by CaMer0n** [comment]
Since it is not a problem anywhere else, I would say the issue is in `{COOKBOOK_RECIPE_THUMB}`

**Comment by Jimmi08** [comment]
Thanks. It works correctly now.
