### ISSUE TITLE
not possible to import back data exported by e107

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4856]
## Bug Description
I couldn't import install data for some theme. The reason was this line:
`<field name="page_title">Learn & Share</field>`

Xml was exported from pages 

After changing to `<field name="page_title">Learn and Share</field>` , xml was imported

## How to Reproduce
* set Learn & Share as page title
* export it from batch option
* try to import it back with Database/tools
 
## PHP
PHP 8, xampp, localhost 

Thanks

**Comment by CaMer0n** [comment]
I followed the **How to Reproduce** steps and was unable to reproduce the issue. 

The `&` is converted to `&amp;` in the database table (as it should be) and the exported value looks like this: 
`<field name="page_title">Learn &amp; Share</field>`. 

This value imports back into the database without any issue.

**Comment by Jimmi08** [comment]
Ok, so it was fixed already, Thanks.
