### ISSUE TITLE
Fatal error PHP 8  - Undefined constant "ADMIN_AREA"

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4859]
## Bug Description
```
Fatal error: Uncaught Error: Undefined constant "ADMIN_AREA" in C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\extended_password_handler.php:391 Stack trace: #0
 C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\e107db_auth.php(166): ExtendedPasswordHandler->CheckPassword(***) 
 #1 C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\alt_auth_adminmenu.php(402): auth_login->login(****) 
 #2 C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\e107db_conf.php(105): alt_auth_admin->alt_auth_test_form('e107db', Object(form)) 
 #3 C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\e107db_conf.php(123): alt_auth_e107db->showForm() 
 #4 {main} thrown in C:\xampp\htdocs\e107-ayroui\e107_plugins\alt_auth\extended_password_handler.php on line 391
```

Installed alt_auth plugin  - trying to find why e107 - e107 combination is not working. Live site is PHP 7.4 but local version is PHP 8.2.  I got this error there.

**Comment by Moc** [comment]
change `if(ADMIN_AREA)` to  if(defset(ADMIN_AREA))`

Should fix it. If yes, I'll commit.

**Comment by Jimmi08** [comment]
It is not correct fix. ADMIN_AREA should be defined as true... 

it is called from e107db_conf.php  that is admin file  (see it is calling admin auth) or $eplug_admin is true. 

```
$eplug_admin = true;
require_once(__DIR__.'/../../class2.php');
require_once(e_ADMIN.'auth.php');
require_once(e_HANDLER.'form_handler.php');
e107::includeLan(e_PLUGIN.'alt_auth/languages/'.e_LANGUAGE.'/admin_e107db_conf.php');
e107::includeLan(e_PLUGIN.'alt_auth/languages/'.e_LANGUAGE.'/admin_alt_auth.php');
define('ALT_AUTH_ACTION', 'e107db');
require_once(e_PLUGIN.'alt_auth/alt_auth_adminmenu.php');
require_once(e_PLUGIN.'alt_auth/extended_password_handler.php');
```

adding define('ADMIN_AREA', true); fixed error.  and you can see log then in admin area.

I think this is related to other issue - detection admin area by file name and word "admin" in path...    it is (was) already issue.

**Comment by Moc** [comment]
What about `if(defsettrue(ADMIN_AREA))`?

**Comment by Jimmi08** [comment]
> What about `if(defsettrue(ADMIN_AREA))`?

The point is that ADMIN_AREA should be true in e107db_conf.php  

Your fix hides error but without ADMIN_AREA true, it is not displaying debug data. 

Or maybe I am wrong.     But if there is $eplug_admin = true;, then there should be define('ADMIN_AREA', true); too - if it is not set by class2.php because admin file name.

**Comment by Moc** [comment]
Ok too much for me to dive into. I'll leave this to others.

**Comment by CaMer0n** [comment]
This should fix it, but please re-open if necessary.

**Comment by Jimmi08** [comment]
@CaMer0n 
So that ADMIN_AREA is not defined in e107db_conf.php is intention?
