### ISSUE TITLE
improvements to splash layout for bootstrap5 theme

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4885]
## Motivation
This theme was based on some my code and there left stuff that shouldn't be there. 

Splash layout is layout for these pages:
- login.php
- signup.php
- fpw.php
- membersonly.php

* moved layout classes (like container and row) to layout file, removed them from tablerender
* removed not officially supported login page as a standalone page
* added splash templates with clean bootstrap 5 markup
* fixed fpw template (wrapper support added as a separate issue and PR)
* fixed login template - added wrappers

**Comment by CaMer0n** [comment]
hi @Jimmi08 It appears your pull-request got deleted. Were you planning to submit another one with those minor changes?

**Comment by Jimmi08** [comment]
Hi, it happens when I rebase my repo. It is just closed, freely use what you consider correct. 

I will not submit another one, at least not this year.  Sorry.
