### ISSUE TITLE
Updating PLUPLOAD 

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#4887]
## Motivation
There's a sec*rity issue with the used version

## Proposed Solution
Maybe it's also time to upgrade the Plupload - multi-runtime File Uploader v2.3.6 to 2.3.9? https://www.plupload.com/download/

I have tried it and it looks like it can be replaced with the 2.3.9. version without any problems?

**Comment by CaMer0n** [comment]
Thank you @Alex-e107nl 
It's done.  :-)
