### ISSUE TITLE
Admin menus appearance issue

### ISSUE THREAD

**Issue by parsfounder** [e107inc/e107#4894]
Menus in admin area with more than 15 entries shows like this:
![screenshot](https://user-images.githubusercontent.com/10089685/197939476-198cc4bf-d1b5-42c2-a40d-eb91221f039b.png)

**Comment by CaMer0n** [comment]
@parsfounder That's an odd one. Any third-party plugins installed? Maybe check the plugins database table?

**Comment by parsfounder** [comment]
@CaMer0n Admin menu issue got fixed after I removed faqs plugin

**Comment by Jimmi08** [comment]
@Moc this can be probably closed. Tested now, no similar issues. 
Similar behavior can appear if you have 2 plugins with the same LAN constant.
