### ISSUE TITLE
e107help

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4899]
## Bug Description
e107help org link presented when instaling showing ( no longer exists)

## How to Reproduce
e107help org link presented when instaling showing

## Expected Behavior
should not reflect non existing site

## Additional Information
site no longer exists. ( eg discussion board)

**Comment by CaMer0n** [comment]
@Moc I think you fixed this one already?

**Comment by tgtje** [comment]
composer.json

**Comment by Moc** [comment]
@tgtje Where does the link to e107help still show? Do you have a screenshot?

**Comment by tgtje** [comment]
used a new git 2.3.3 for installment. It links to discussions.

the latest e107.org pack ( full install from org (2.3.2) has it. (d.d. 28-10). 
So in present git it is corrected.  Ok, having a message on the off pack is 'outdated' and coorected in git.
Closing.
