### ISSUE TITLE
FAQs - PHP 8 error

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4916]
## Bug Description
Fatal error: Uncaught Error: Undefined constant "FAQLAN_41" in C:\xampp\htdocs\e107-2_3_3_git\e107_plugins\faqs\faqs.php:133 Stack trace: #0 C:\xampp\htdocs\e107-2_3_3_git\index.php(69): include_once() #1 {main} thrown in C:\xampp\htdocs\e107-2_3_3_git\e107_plugins\faqs\faqs.php on line 133

## How to Reproduce
Set clasic layout ON 

![image](https://user-images.githubusercontent.com/5429548/206159119-954b5106-a238-4c7f-847b-dd4d764e1ccd.png)

### PHP Version

```
PHP Version 8.2
```

Synced with latest version before testing
Thanks

**Comment by tgtje** [comment]
Must have been lost in the years 2013 >  : `define(FAQLAN_41, "FAQ Categories");`

At present this this would be : `define("LAN_PLUGIN_FAQS_FUNCTIONNAME",	"FAQ Categories");`  ???
