### ISSUE TITLE
Any remaining PHP8 Fatal Errors due to undefined constants. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#4918]
## Bug Description
A catch-all issue for any undefined constants still remaining.

**Comment by CaMer0n** [comment]
faqs.php: 

```
ERROR Undefined constant 'FAQ_ADLAN_30' 
ERROR Undefined constant 'FAQ_ADLAN_29' 
ERROR Undefined constant 'FAQ_ADLAN_30' 
ERROR Undefined constant 'FAQLAN_38' 
ERROR Undefined constant 'FAQ_ADLAN_49' 
ERROR Undefined constant 'NWSLAN_42' 
ERROR Undefined constant 'FAQ_ADLAN_45' 
ERROR Undefined constant 'FAQ_ADLAN_78' 
ERROR Undefined constant 'FAQ_ADLAN_51' 
ERROR Undefined constant 'FAQ_ADLAN_60' 
ERROR Undefined constant 'FAQ_ADLAN_52' 
ERROR Undefined constant 'FAQ_ADLAN_53' 
ERROR Undefined constant 'FAQ_ADLAN_54' 
```

**Comment by CaMer0n** [comment]
Courtesy of @tgtje 

- [ ] FAQ_ADLAN_30 = define(FAQ_ADLAN_30, "You left a required field blank."); (2x... 92 - 112)xxxxx (maybe LAN_REQUIRED_BLANK (/English.php) ??

- [ ] FAQ_ADLAN_29  = define(FAQ_ADLAN_29, "FAQ entry updated");  'at present no suited define found'
- [ ] FAQ_ADLAN_30 = define(FAQ_ADLAN_30, "You left a required field blank."); (2x... 92 - 112)xxxxx (maybe LAN_REQUIRED_BLANK (/English.php)

- [ ] FAQLAN_38 = define(FAQLAN_38, "Comment"); ??? maybe suited : LAN_COMMENTS although normally plural

- [ ] FAQ_ADLAN_49  = define(FAQ_ADLAN_49, "Previous FAQ entries: "); 'at present no suited define found'
- [ ] NWSLAN_42 = languages/English/admin/lan_newspost //define("NWSLAN_42", "Untitled"); - not allowed anymore = line 50 (faqs php 698)

- [ ] FAQ_ADLAN_45 = define(FAQ_ADLAN_45, "Edit"); >?? define("LAN_EDIT","Edit"); (/Engl.php)

- [ ] FAQ_ADLAN_78 = define(FAQ_ADLAN_78, "Category"); if single > define("LAN_CATEGORY", "Category"); ??? (/Engl. php)

- [ ] FAQ_ADLAN_51 = define(FAQ_ADLAN_51, "FAQ Question: ");===========define("LANA_FAQ_QUESTION", "Question"); or define("LANA_FAQ_QUESTIONS", "Questions"); (Faqs/English_admin) OR > define("LAN_FAQS_ASK_A_QUESTION", "Ask a Question"); : Faqs/Global php

- [ ] FAQ_ADLAN_60 = define(FAQ_ADLAN_60, "FAQ Answer:"); ============== define("LANA_FAQ_ANSWER", "Answer");(Faqs/English_admin php)

- [ ] FAQ_ADLAN_52 = define(FAQ_ADLAN_52, "Allow Comments?: "); 'at present no suited (global) define found'

- [ ] FAQ_ADLAN_53 =  define(FAQ_ADLAN_53, "Update FAQ Item ");  'at present no suited define found'
- [ ] FAQ_ADLAN_54 = define(FAQ_ADLAN_54, "Submit FAQ Item");=====maybe : define("LAN_FAQS_012", "Enter your question here...");??? OR > define("LAN_FAQS_014", "Please [register] and/or login to post a question."); (Engl. front)`
```

**Comment by theBlbDan** [comment]
I can open a separate issue if needed.  Using the 'Login as <user>', when navigating to any non-admin area pages, I receive the following.


`Fatal error:  Uncaught Error: Undefined constant "ADMIN" in /usr/www/muh_site/public_html/class2.php:1321
Stack trace:
/usr/www/muh_site/public_html/e107_handlers/user_model.php(655): getperms()
/usr/www/muh_site/public_html/e107_handlers/user_model.php(523): e_user_model->checkAdminPerms()
/usr/www/muh_site/public_html/e107_handlers/user_model.php(2094): e_user_model->isMainAdmin()
/usr/www/muh_site/public_html/e107_handlers/user_model.php(2065): e_user->loadAs()
/usr/www/muh_site/public_html/e107_handlers/user_model.php(1790): e_user->load()
/usr/www/muh_site/public_html/e107_handlers/e107_class.php(1198): e_user->__construct()
/usr/www/muh_site/public_html/e107_handlers/e107_class.php(2112): e107::getObject()
/usr/www/muh_site/public_html/class2.php(1569): e107::getUser()
/usr/www/muh_site/public_html/class2.php(672): init_session()
/usr/www/muh_site/public_html/news.php(22): require_once('...')
{main}
  thrown in <b>/usr/www/muh_site/public_html/class2.php</b> on line <b>1321`

**Comment by CaMer0n** [comment]
@theBlbDan Thank you! Will look into it.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/4966
