### ISSUE TITLE
Fatal error: Uncaught TypeError in viewforum_shortcodes.php

### ISSUE THREAD

**Issue by theBlbDan** [e107inc/e107#4929]
## Bug Description
When I apply a custom user class, i.e. a non fixed class, to a forum, it generates a **Fatal error: Uncaught TypeError**

`Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in /usr/www/public_html/e107_handlers/userclass_class.php:108 Stack trace: #0 /usr/www/public_html/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php(245): user_class->getFixedClassDescription() #1 /usr/www/public_html/e107_handlers/shortcode_handler.php(1154): plugin_forum_viewforum_shortcodes->sc_viewable_by() #2 [internal function]: e_parse_shortcode->doCode() #3 /usr/www/public_html/e107_handlers/shortcode_handler.php(1020): preg_replace_callback() #4 /usr/www/public_html/e107_handlers/e_parse_class.php(848): e_parse_shortcode->parseCodes() #5 /usr/www/public_html/e107_plugins/forum/forum_viewforum.php(445): e_parse->parseTemplate() #6 /usr/www/public_html/e107_plugins/forum/forum_viewforum.php(56): forum_viewforum_front->init() #7 /usr/www/public_html/e107_plugins/forum/forum_viewforum.php(565): forum_viewforum_front->__construct() #8 /usr/www/public_html/index.php(69): include_once('...') #9 {main} thrown in /usr/www/public_html/e107_handlers/userclass_class.php on line 108`

## How to Reproduce
1. Create a standard user class
2. Add this class to a user
3. Apply this class to the 'Visibility' of a forum and then visit this forum as above mentioned user
4. You should get a similar stack trace as shown above.

## Expected Behavior
Well, I kinda expect to apply custom user classes to forums to limit their visibility. It appears that in ./e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php(), it is passing an array which clearly won't work.

### PHP Operating System

```
Linux hosted5 5.15.82 #1 SMP Sat Dec 10 23:29:08 PST 2022 x86_64
```

### PHP Version

```
PHP Version 8.1.12
```

### PHP Modules

apache2handler
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
ionCube Loader
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
ssh2
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

**Comment by Jimmi08** [comment]
I can't confirm.  PHP 8.1.4, latest e107 (2,3,3git), no issue.

**Comment by Moc** [comment]
@theBlbDan which version of e107 are you using? It may very well be that the issue has already been resolved. It will then the part of the official next release. In the mean time, you can try updating to the Github version.

**Comment by Deltik** [comment]
I was able to reproduce the bug on the latest revision of e107 (e107inc/e107@ec68c8891 at the time of writing) using the provided instructions.  Here's my stack trace, which is basically the same:

```
[Sat Dec 24 15:52:34.954293 2022] [php:error] [pid 152691] [client 10.64.229.1:55854] PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /var/www/html/e107/e107_handlers/userclass_class.php:108
Stack trace:
#0 /var/www/html/e107/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php(245): user_class->getFixedClassDescription()
#1 /var/www/html/e107/e107_handlers/shortcode_handler.php(1154): plugin_forum_viewforum_shortcodes->sc_viewable_by()
#2 [internal function]: e_parse_shortcode->doCode()
#3 /var/www/html/e107/e107_handlers/shortcode_handler.php(1020): preg_replace_callback()
#4 /var/www/html/e107/e107_handlers/e_parse_class.php(848): e_parse_shortcode->parseCodes()
#5 /var/www/html/e107/e107_plugins/forum/forum_viewforum.php(445): e_parse->parseTemplate()
#6 /var/www/html/e107/e107_plugins/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#7 /var/www/html/e107/e107_plugins/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#8 /var/www/html/e107/index.php(69): include_once('...')
#9 {main}
  thrown in /var/www/html/e107/e107_handlers/userclass_class.php on line 108, referer: http://10.64.229.116/e107/forum
```

**Comment by Deltik** [comment]
In `./e107_handlers/userclass_class.php` at [this line](https://github.com/e107inc/e107/blob/ec68c889100be01e46ef907d4f149ad2b9c55454/e107_handlers/userclass_class.php#L108-L108), my `$id` is the following value:

```php
array (
  0 => 
  array (
    'user_id' => '4',
    'user_name' => 'newuser',
    'user_class' => '248,3,6',
  ),
)
```

But `$this->fixed_classes` only has these:

```php
array (
  0 => 'Everyone (public)',
  252 => 'Guests',
  255 => 'No One (inactive)',
  253 => 'Members',
  254 => 'Admin',
  250 => 'Main Admin',
  251 => 'Read Only',
  247 => 'New Users',
  246 => 'Search Bots',
)
```

Judging from the name `user_class::getFixedClassDescription()`, the client usage [in `plugin_forum_viewforum_shortcodes::sc_viewable_by()`](https://github.com/e107inc/e107/blob/ec68c889100be01e46ef907d4f149ad2b9c55454/e107_plugins/forum/shortcodes/batch/viewforum_shortcodes.php#L245-L245) is passing in the wrong data.

**Comment by theBlbDan** [comment]
> @theBlbDan which version of e107 are you using?
I'm sorry, I don't know why I didn't provide this already.
Full download fresh install from the e107 site.   Version 2.3.2 


> It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely.
> 
> Please always make a backup of you website (files and database) before updating.
> 
> There is an easy way to sync with Github:
> 
> * Enable developer mode in `Admin Area > Preferences > Advanced features`
> * Go to `Admin Area > Tools > Database > Sync with Github`
> * Press the `Overwrite files` button and wait until the process has finished.

I will give this a try when I get back from Christmas break.

Thanks.

**Comment by Moc** [comment]
@theBlbDan No worries! Enjoy the Christmas break. 

It looks like the bug can be reproduced anyhow. So it still has to be fixed.

**Comment by Deltik** [comment]
The bug comes from https://github.com/e107inc/e107/commit/2dedb86b#diff-d8b2fba5d26ab6acc066765263788bb9005d4d98e7de39b04d888dce1781603dR151-R154, where there's a different return type (string) in the same method that returns an array of structures like this:

```php
array (
  0 => 
  array (
    'user_id' => '4',
    'user_name' => 'newuser',
    'user_class' => '248,3,6',
  ),
)
```
