### ISSUE TITLE
flexpanel layout is not working 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4940]
## Bug Description
Flexpanel layout is not working, and the position of the menu area is not saved to prefs or user prefs 

## How to Reproduce
1. Go to Admin theme
2. Selec Flexpanel layout
3. Move admin panels in dashboard
4. Reload the page

## Expected Behavior
Saving new orders of panels
  
### PHP Version

```
PHP 8.0
```

## Additional Information
Check the IDs of panels. They are saved in DB with the dash, but HTML markup is using underscores.

**Comment by Jimmi08** [comment]
With $dashboards = $this->getAddonDashboards(); there is next related issue - f.e. try add it to chatbox_menu -  underscore in plugin name. Just be aware of this.

**Comment by CaMer0n** [comment]
@Moc Are you able to reproduce the flexpanel issue? I'm not. I'm on PHP 8.2

**Comment by Moc** [comment]
@CaMer0n Yes, I am able to reproduce it. Both on live and local website, PHP 8.1 and 8.2. Using Chrome.

**Comment by CaMer0n** [comment]
Thank you @Moc ! I was finally able to reproduce the issue.  
However I was unable completely fix it.  
@lonalore would you have some ideas about that?

**Comment by Jimmi08** [comment]
Maybe you should check why sometimes is used:  core-infopanel_news  and sometimes core-infopanel-news 
Flexbox script itself is working.

But getting new position with `$info = $this->getMenuPosition('core-infopanel_news');`  return not correct value, becase saved position is _core-infopanel-news_.
