### ISSUE TITLE
Email to moderator on new items in forum

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#4954]
## Motivation
Could you please let me know why you're making this feature request?
Please provide a clear and concise description of what the problem is.

You do not get an email if someone posts messages on the forum. It is possible to subscribe for replies, but assigning an admin/moderator to a panel who receives a notification that a new post has been done is beneficial. It prevents you from going to the forum to have a look. It also allows you to be more responsive when required. In my personal case it would be nice to get a notification on certain forums to see items that are important, fast, instead of looking once or twice a day. To clarify, it is about the notification of a new thread in the forum.

**Comment by Jimmi08** [comment]
I am getting those notifications, 
![image](https://user-images.githubusercontent.com/5429548/212563289-2eeb651d-07f7-4b72-8fbd-42fc4d4f40c1.png)

What is difference in your request against core solution?

**Comment by aducom** [comment]
Good question, appearantly I need to look for the preferences somewhere... This issue can be closed then..

**Comment by Jimmi08** [comment]
**Database/Tools/Notify**
- you can select forum moderators class, Not sure if all moderators get notification or only those for that forum. 

![image](https://user-images.githubusercontent.com/5429548/212564040-48f8deef-0137-45d5-bbb9-1e8fcd0d7c70.png)

**Comment by aducom** [comment]
I have totally overlooked this options as I was searching within the forum. Thnx!
