### ISSUE TITLE
banner plugin - banner_campaign is saving only first campain

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4959]
## Bug Description
only first campain is rendered

## How to Reproduce
- create more than one campain
- check them, save them
- 
![image](https://user-images.githubusercontent.com/5429548/213909028-bfd9b0d5-77dc-4cd8-96cb-dee156d6bbc2.png)

- check config again

![image](https://user-images.githubusercontent.com/5429548/213909056-4c9479a0-59cd-4d54-aa78-74fb2feb57a1.png)

Only first one is checked

 
### PHP Version

```
PHP Version 8,0
```
 
## Additional Information
Saved data in database are incorrect
![image](https://user-images.githubusercontent.com/5429548/213909119-dbefa2bf-feaa-4792-aa25-f77f7faf32dc.png)

**Comment by fizi** [comment]
My problem with banner that same layout and banner not apperas on extend news and cpage. (appear on news.php but not appear on extend news page)

**Comment by Moc** [comment]
@fizi this sounds like a separate issue. Please submit it as a new bug report.

**Comment by fizi** [comment]
Ok, I made it.
