### ISSUE TITLE
Fatal error with PHP 8.2

### ISSUE THREAD

**Issue by Digioso** [e107inc/e107#4961]
## Bug Description

From my webserver logfile:
[Mon Jan 30 08:47:17.964055 2023] [proxy_fcgi:error] [pid 549159:tid 281473405612224] [client 88.130.87.199:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "PRELINK" in /home/digioso/web/baod.de/public_html/e107_themes/GuildWars/theme.php:157\nStack trace:\n#0 /home/digioso/web/baod.de/public_html/class2.php(1078): require_once()\n#1 /home/digioso/web/baod.de/public_html/index.php(58): require_once('...')\n#2 {main}\n  thrown in /home/digioso/web/baod.de/public_html/e107_themes/GuildWars/theme.php on line 157'

## How to Reproduce
1. Use PHP 8.2
2. Open Website
3. Browser gets status code 500
4. See error in webserver logfile

## Expected Behavior
No error.

### PHP Operating System

```
Linux digioso.net 5.15.0-1027-oracle #33-Ubuntu SMP Fri Jan 6 16:30:16 UTC 2023 aarch64 
Ubuntu 22.04
```

### PHP Version

```
PHP Version 8.2.1
```

### PHP Modules

bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
pspell
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

### Client Information

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

## Additional Information
When I switch PHP back to PHP 7.4 the main website is loading without problems.

**Comment by Deltik** [comment]
This is a bug with your theme, `GuildWars`, not a bug within the e107 core.

The theme is trying to access an undefined constant, `PRELINK`, which has been [disallowed since PHP 8.0](https://www.php.net/manual/en/migration80.incompatible.php):

> A number of warnings have been converted into [Error](https://www.php.net/manual/en/class.error.php) exceptions:
>
> * […]
> * Attempting to access unqualified constants which are undefined. Previously, unqualified constant accesses resulted in a warning and were interpreted as strings. 

You will have to fix this in the theme.  Some options:

* Defensively access the constant, which may or may not be defined, using pure PHP:
   
   ```
   defined("PRELINK") ? PRELINK : ""
   ```
* Use the e107 core wrapper, [`deftrue()`](https://github.com/e107inc/e107/blob/21de308f8333ab135b83940ee8ff752c26f25e5c/e107_handlers/core_functions.php#L110-L114), to default the undefined constant to a blank string:
   
   ```
   deftrue("PRELINK")
   ```

**Comment by Digioso** [comment]
Thanks!

I fixed it doing this:

`#define(PRELINK, "");
deftrue("PRELINK");
deftrue("POSTLINK");
#define(POSTLINK, "");
#define(LINKSTART, "<img src='".THEME."images/bullet2.gif' alt='' />&nbsp;");
defined("LINKSTART") ? LINKSTART : "<img src='".THEME."images/bullet2.gif' alt='' />&nbsp;";
defined("LINKED") ? LINKED : "<br />";
defined("LINKALIGN") ? LINKALIGN : "left";
defined("LINKDISPLAY") ? LINKSTART : 2;
#define(LINKEND, "<br />");
#define(LINKALIGN, "left");
#define(LINKDISPLAY, 2);
`
