### ISSUE TITLE
No HTML5 support in Media Manager

### ISSUE THREAD

**Issue by seth7609** [e107inc/e107#4964]
## Bug Description
When Trying to upload a new image using the media manager I am seeing "No HTML5 support". In the console I am getting 2 jQuery errors

Uncaught TypeError: a.indexOf is not a function in file: jquery-3.1.1.min.js:4:19062

and 

Uncaught TypeError: $(...).find(...).once is not a function in file: mediaManager.js:17:42

I thought this was only a problem on the public side of the site but it is also a problem in the admin side as well so if I go to Pages/Menus (e107_admin/cpage.php?mode=page&action=create) it happens there too. It is also a problem in the admin area for the media manager(e107_admin/image.php?mode=main&action=import).

I was having this problem on v2.3.0 and I was hoping that upgrading to 2.3.2 would fix this but it did not. 

## How to Reproduce
1. with TinyMce4 enabled create a form with a WYSIWYG using this code e107::getForm()->bbarea("desc", $desc, null, null, "small")
2. Click the "Insert Media-Manager Image" button inside the WYSIWYG.
3. Click Upload a File
4. Where you would usually see an upload area it just says "No HTML5 support"
## Screenshots
![media_manager](https://user-images.githubusercontent.com/26769438/215840434-40cff508-62e3-40f7-b41a-dd7988dbc3cc.png)
![console](https://user-images.githubusercontent.com/26769438/215840501-27cc0b4e-9da0-4fa0-be96-2976d2f15986.png)

### e107 Version
e107 v2.3.2
### PHP Version
php 7.1.33

**Comment by Jimmi08** [comment]
Little question...  are you in the admin area in the bootstrap3 theme? Why are you manually creating a form when there is admin UI? Or you are doing frontend form?
Your news bbarea is working correctly?

**Comment by seth7609** [comment]
This was found on a front end form. 

Any where that the MM is used I am getting this error. Both on the front using the code provided or in the admin area.

**Comment by Jimmi08** [comment]
that error is in HTML markup by default (everywhere), it is not error message, it is hidden by javascript normally, but it is not fired from some reason.
Your site has to have javascript error - standard e107 is working correctly.  Maybe some plugin or something.   that mediamanager.js issue in console is there because jquery wasn't loaded correctly (line above). Check if your jquery is loaded in header or footer,,, try to use jquery 2 instead 3...
