### ISSUE TITLE
SQL and token error with emoticons

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4972]
## Bug Description
Emoticons are not working.  PHP 8.1.  

First one - Unauthorised access - With configuration form there is missing e_token hidden field.

After fixing (and unset it from $_POST before saving) there is SQL error.  Array is not saved correctly (way how they are changed to string before saving to database) .

## How to Reproduce
1. Go to Emoticons
2. Click on second tab, configure and save
 

PHP 8.1, tested with latest git.

Thanks

**Comment by tgtje** [comment]
:thumbsup:
