### ISSUE TITLE
Sitelogo size issue - defaults are ignored

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4997]
## Bug Description
Sitelogo is used in theme.html this way:
```
                        <a href="{SITEURL}" class="brand-logo">
                            {SITELOGO}
                        </a>
```
on homepage is rendered correctly:
`/e107core/thumb.php?src=e_IMAGE%2FlogoHD.png&amp;w=100&amp;h=0`

on news.php
/e107core/thumb.php?src=e_IMAGE%2FlogoHD.png&amp;aw=400&amp;ah=350
(news image size)
on page.php
/e107core/thumb.php?src=e_IMAGE%2FlogoHD.png&amp;aw=90&amp;ah=90 
(comment avatar size)
 

## Expected Behavior
Don't change default image size on each page 

Latest github version with PHP 8.2 was used

![image](https://user-images.githubusercontent.com/5429548/235648658-6ec42979-d2f4-47a1-a9d6-f428582c2087.png)

![image](https://user-images.githubusercontent.com/5429548/235648772-433ff095-93c4-4469-a171-00c89a1d3623.png)

**Comment by CaMer0n** [comment]
If you need fixed dimensions, then be sure you add them: `{SITELOGO: w=250}` or `{SITELOGO: h=50}`, otherwise the logo dimensions are dynamic and are subject to modification anywhere `{SETIMAGE}` is used.
