### ISSUE TITLE
Can't load some admin pages

### ISSUE THREAD

**Issue by pbuydid** [e107inc/e107#5010]
## Bug Description
I can't load Preferences and Mail sections in admin area. It only shows a white page.

## Screenshots
It only shows a white page. No errors, no code.

### PHP Operating System 

Linux host2145.hostmonster.com 4.19.150-76.ELK.el7.x86_64 #1 SMP Wed Oct 7 01:33:43 CDT 2020 x86_64

```

### PHP Version

8.2
Replace this code block with the PHP version shown
at the top of /e107_admin/phpinfo.php

PHP Version 8.1.19
```

### PHP Modules

1. Go to /e107_admin/phpinfo.php
2. Change the page to "view source" mode by one of these methods:
   - Press [Ctrl]+[u]
   - Press [Option]+[Command]+[u]
   - Add `view-source:` at the beginning of the address bar
3. Copy all the source code
4. Go to https://sed.js.org/
5. Paste everything into the "STDIN:" box
6. In the "Command line (--help):" box, write:

       -rn 's|<h2><a id="module_[^"]+"[^>]+>([^<]+)</a></h2>|\1|p'

7. Copy everything from the "STDOUT | STDERR:" box.
8. Paste what you copied here, replacing this whole "PHP Modules" section.

### Client Information: Shows nothing...

1. Go to https://duckduckgo.com/?q=my+user+agent
2. Towards the top, copy your user agent from the line that begins with "Your user agent".
3. Replace this section with the clipboard contents.

   Example: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0`

**Comment by Deltik** [comment]
You'll need to look at your PHP or web server error log for more details.  There's probably something logged in there involving a "PHP Fatal error".  If you can provide that, we can better narrow down the problem.

Also, what version of e107 are you running?  e107 v2.3.2 supports PHP 8.1.  PHP 8.2 should mostly work on the latest `master` revision.

**Comment by CaMer0n** [comment]
@pbuydid Are you running your admin area in a language other than English?

**Comment by Moc** [comment]
Closing due to lack of feedback. If you are still experiencing the issue, please answer the questions asked above.
