### ISSUE TITLE
Plugin.xml - Control User Access Of Added User Classes?

### ISSUE THREAD

**Issue by Vodhin** [e107inc/e107#5011]
I would like to be able to add User Classes that are Visible/Assignable only by Admins or other specific User Classes. Currently it looks like the plugin.xml `<userClasses>` tag only accepts two attributes:

`<class name="estate_admin" description="Estate Plugin Administrator" />`
`<class name="estate_manager" description="Estate Agency Manager" />`
`<class name="estate_agent" description="Estate Agent" />`

By default these new classes become accessible to any registered member as subscriptions in the usersettings.php file if they are not manually edited in the User Classes settings page by an Admin. Perhaps someone could make an update to process additional attributes in the class tag to include default Visibility and Manager attributes based on either class id or class name?

`<class name="estate_admin" manager="250" visibility="250" description="Estate Plugin Administrator" />`
`<class name="estate_manager" manager="250,estate_admin" visibility="250,estate_admin" description="Estate Agency Manager" />`
`<class name="estate_agent" manager="250,estate_admin,estate_manager" visibility="250,estate_admin,estate_manager"  description="Estate Agent" />`

**Comment by Vodhin** [comment]
Thank you. I will try that.

**Comment by CaMer0n** [comment]
@Vodhin Did @Jimmi08 's code work for you? Looking at the code, I don't see how that would work. 
The default is always this when userclasses are created via plugin.xml:
```
	$tmp['userclass_editclass'] = e_UC_ADMIN;
	$tmp['userclass_visibility'] = e_UC_ADMIN;
```

**Comment by Vodhin** [comment]
> @Vodhin Did @Jimmi08 's code work for you? Looking at the code, I don't see how that would work...
> 

I have not really looked into this further since I have been deep into coding other functions of my plugin. As it still stands, e_107 doesn't have a method to create a set of userclasses with a hierarchy as my original post described, so I have created my own pseudo-userclass system built into this plugin (an Agent belongs to an Agency which belongs to a Company - Main Admins assign a User as a Company Admin in my system, now that Company Admin can create Users and assign them as Managers and Agents of that company).
