### ISSUE TITLE
Free support message in admin area

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#5022]
So I've notice that the current version of e107 (2.3.2) has a message at the top, under the navigation stating that the user can get free support. with a hyper link, linking to e107help.org, Last I checked, that site is down (wish it wasn't, used it a ton of times when I was stuck, or wanting to share my opinion). Should that be updated to another site, or is e107help.org going to return?

Only thing I can see the link for e107help.org is in composer.json - for forum.

**Comment by Deltik** [comment]
The dead link is [fixed in `master`](https://github.com/e107inc/e107/commit/f2f8877a053efec1b13dcc478b460ee6bf351fd3).  It will land in the next release.
