### ISSUE TITLE
UEF on Signup page - fatal error in PHP 8.2

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5039]
## Bug Description
There is a fatal error if you use UEF on the signup page 
Reason:
` Fatal error: Uncaught TypeError: Cannot access offset of type string on string in *** \core\shortcodes\batch\signup_shortcodes.php on line 452`
It is this line because I could move the line numbering while testing.
`$ue->renderElement($ext, varset($_POST['ue']['user_' . $ext['user_extended_struct_name']]), $opts)`

It happens when you display the form the first time.  No form data were posted. 

 print_a($_POST) result:
![image](https://github.com/e107inc/e107/assets/5429548/caba4e3a-2840-4bdf-841c-15bf54d54562)

How to fix this, please?
Thanks

**Comment by Deltik** [comment]
The bug you are encountering was probably fixed by https://github.com/e107inc/e107/pull/4993.  Can you confirm if the patch at https://github.com/e107inc/e107/pull/4993.patch fixes your issue?

**Comment by Jimmi08** [comment]
Ups, I thought I had synced. Sorry, and thank you for your answer.
