### ISSUE TITLE
fix normally not visible fatal error 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5072]
## Motivation
Just to have better code

When you install e107 and there is some error, in PHP 8.2 there is message

`Fatal error: Uncaught TypeError: installLog::exceptionHandler(): Argument #1 ($exception) must be of type Exception, Error given in ***\install.php on line 51`

```
	static function exceptionHandler(Exception $exception)
	{
		$message = $exception->getMessage();
		self::add($message, "error");
	}
```

Actually, I am trying to find out why this happened  :)

 By mistake, I let one folder in the theme folder without theme.xml. Installation was trying to find theme.xml, theme.php and because it did not exist, an error was fired and with PHP 8.2 it ended with this fatal error.

**Comment by Deltik** [comment]
The function `exceptionHandler()` has the wrong parameter signature.  It needs to accept a `Throwable`, not an `Exception`.  See [the documentation for `set_exception_handler()`](https://www.php.net/manual/en/function.set-exception-handler) for more information.

**Comment by Deltik** [comment]
Ah, but `Throwable` didn't exist in PHP 5.6…

An alternative could be to remove the strict type definition and replace it with a phpDoc string.
