### ISSUE TITLE
PHP 8.2 Warnings and Deprecation Notices. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#5079]
## Bug Description
Some code in e107 triggers deprecation notices in PHP 8.2

**Comment by Jimmi08** [comment]
Deprecated: Creation of dynamic property UserHandler::$otherFieldTypes is deprecated in  ...\ehandlers\user_handler.php on line 128

**Comment by Jimmi08** [comment]
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in  ***\ehandlers\e_parse_class.php on line 5309
