### ISSUE TITLE
[Bug]: Fatal error during synchronization 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5103]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

I got a fatal error while trying to sync (from admin tools). 
I am writing this while I am on it, I suppose that refresh or something will help. 

Fatal error: Uncaught Error: Call to undefined method e_jsmanager::renderFavicon() in C:\wamp64\www\e107core\e107_admin\header.php on line 387
Error: Call to undefined method e_jsmanager::renderFavicon() in C:\wamp64\www\e107core\e107_admin\header.php on line 387

![image](https://github.com/e107inc/e107/assets/5429548/d6a1c8f3-5ef1-4e7a-a007-12256fffba00)

### How to reproduce

I am not able to reproduce this.
After refreshing the page, the error is gone.  refreshing

### Expected behavior

Not seeing this type of error when I use the clean core version?   :) 

You should add some label for this like "very rare" or something,  I don't expect you to spend time on this, but I wanted to have it written for the future.  If this happens again or something. 

@Moc Nice template :)

### What browser(s) are you seeing the problem on?

Chrome / Brave

### PHP Version

PHP 8.1.13

**Comment by Moc** [comment]
Probably the files were not loaded correctly yet after the sync, or some temporary caching issue. Don't consider this a bug.

**Comment by tgtje** [comment]
Ok closed, nevertheless. Had the same after sync last week. Repeating the sync (so 2x) the error was gone.
as being an important file, it indeed needs a kind of system 'reset' to load it in fresh.
just to inform

**Comment by Moc** [comment]
yeah it needs to load the header files properly again. The sync function should only be used by developers. And they should know how to refresh :)
