### ISSUE TITLE
[Bug]: comments without ajax issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5111]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

This is just a note for anybody who can test it.

When you use comments without ajax (from any reason, in my case temp test in WordPress environment), comments are not saved in PHP 8 and the reason is this:

![image](https://github.com/e107inc/e107/assets/5429548/5299408d-cb64-407c-98c9-25d2d388c6ca)

It failed in PHP 8 because this variable wasn't set. 

### How to reproduce

Use comments without Ajax.  

I am aware that this is hard to reproduce and I will extend this issue if I have time for this.   

The problem is deeper and I just wanted to save what I found.   Adding this line
			`$comment_share = 0; //BC Fix.`
fixed issue  and comment was saved.
 

### Expected behavior

Working comment system without AJAX.  Ajax is fine but as soon as your site produces any error, it is not working. 

### What browser(s) are you seeing the problem on?

Chrome / Brave

### PHP Version

8.1

**Comment by 3l3ktr0n** [comment]
how do you disable ajax for comments?
