### ISSUE TITLE
[Bug]: e107_admin/theme.php PHP-8.1.25 - Bootstrap 5 theme gives empty screen.. (Dropdowns nav menu also do not work anymore)

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#5113]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

Empty main screen when you use php 8.1.25 when you try to open config of installed Bootstrap5 theme (standard) in the dutch language, in english it works, with php 7.4 both languages work perfectly. The standard bootstrap 3 theme works perfectly!

![Problem_admin_themephp_23-11-2023](https://github.com/e107inc/e107/assets/11962513/e4dad360-1af2-4e00-b252-7d8a6a1418ec)

### How to reproduce

Fresh install e107 (github 23-11-2023) PHP 8.1.25 use Dutch language for admin and go to Thema Manager

### Expected behavior

To see the config of the standard Bootstrap 5 theme... With PHP 7.4 it works as expected!

### What browser(s) are you seeing the problem on?

Firefox

### PHP Version

PHP 8.1.25

**Comment by Jimmi08** [comment]
More info: 
![image](https://github.com/e107inc/e107/assets/5429548/09229b70-459f-4c62-a9ea-7d1155a864b1)

it would help if you fixed the Dutch translation, those strings are missing in Dutch_admin.php:

```
define("LAN_THEMEPREF_04", "Site Name");
define("LAN_THEMEPREF_05", "Logo");
define("LAN_THEMEPREF_06", "Logo &amp; Site Name");
define("LAN_THEMEPREF_07", "left");
define("LAN_THEMEPREF_08", "right");
```

**Comment by Alex-e107nl** [comment]
Done that here locally, did not change anything... i thought the same... I wil edit the language files :-)

**Comment by Jimmi08** [comment]
> define("LAN_THEMEPREF_04", "Site Name");
> define("LAN_THEMEPREF_05", "Logo");
> define("LAN_THEMEPREF_06", "Logo &amp; Site Name");
> define("LAN_THEMEPREF_07", "left");
> define("LAN_THEMEPREF_08", "right");

add too, it was next error. 
`define("LAN_THEMEPREF_00", "Branding:");`

**Comment by Alex-e107nl** [comment]
The translation of TGTJE and me is on [https://sourceforge.net/projects/e107dutch/](https://sourceforge.net/projects/e107dutch/) that is what we use....

**Comment by CaMer0n** [comment]
@Alex-e107nl As this appears to be a language-pack issue, I'll close this. Feel free to open an issue here: https://github.com/e107translations/Dutch about it.
