### ISSUE TITLE
Media-Manager categories for each registered member

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#513]
I'm creating some standalone/custom e107 v2 pages that are largely modelled on the Admin "News" page. These pages will be available to registered users of my website - they will fill in the details and click a "Submit" button to save the page content to the database.

I want to allow them to associate an image with each "article" they submit. The Media Manager offers this functionality, but any uploaded images are put into the common {e_MEDIA_IMAGE} directory.

It would be very useful if the Media Manager could be extended so that each user could upload images to some web space dedicated to _their_ account, and when it came to selecting an image for an article, they would be able to pick an image from among the images they had uploaded there.

Thank you

**Comment by Moc** [comment]
This might be a nice example to add to the documentation.
