### ISSUE TITLE
[Question]: How should be parameter full used for e107::url()?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5140]
### Question

I need to get the full url for some link. 

I used the option  `"full"=>1`   or `full=1`.  It works in all plugin places except e_rss.php.  Here has to be:  ` "mode"=>"full"` used. 

So what is correct?  "mode"=>"full" is only for RSS plugin?

Thanks

 

### Expected Source

in forum plugin, e107_class and rss.php files. 
,

### Additional Context

The reason why it has to in full mode:

in rss.php (it must start with HTTP) otherwise weird URL is used.
```
						if($row['link'])
						{
							if(stripos($row['link'], 'http') !== FALSE)
							{
								$this -> rssItems[$k]['link'] = $row['link'];
							}
							else
							{
								$this -> rssItems[$k]['link'] = SITEURLBASE.e_PLUGIN_ABS.$row['link'];
							}
						}
```

**Comment by Moc** [comment]
I need to update the documentation (https://devguide.e107.org/classes-and-methods/urls#example-2-using-optional-parameters) but you can use `e107::url()`, and then use the fourth parameter (`$options`) which is an array. 

For example: 
```php
 $forum_url = e107::url("forum", "topic", $forum_data, array("mode" => "full"));
```
