### ISSUE TITLE
[Bug]: NoCaptcha ReCaptcha: Login fails with "Incorrect code entered."

### ISSUE THREAD

**Issue by HatchlingByHeart** [e107inc/e107#5163]
### What e107 version are you using?

v2.3.3

### Bug description

Login fails with "Incorrect code entered." despite recaptcha being entered correctly with green tick.
Site Key and Secret Key are entered into plugin config and verified to be correct.
Strangely, the error is not rendered until the page is refreshed.

https://github.com/e107inc/e107/assets/6427368/ca5d4356-9fb6-46e2-a24f-06b141b3d982

### How to reproduce

1. Install e107 2.3.3
2. Install NoCaptcha ReCaptcha plugin
3. Create a ReCaptcha account on Google
4. Enter Site Key and Secret Key on NoCaptcha ReCaptcha plugin settings
5. Attempt to register an account on e107
6. Attempt to login with that account

### Expected behavior

Be able to login and register an account.

### What browser(s) are you seeing the problem on?

Firefox, Chrome / Brave

### PHP Version

PHP 8.2.14

**Comment by HatchlingByHeart** [comment]
The ReCaptcha plugin seems to be unable to communicate with Google for whatever reason, as confirmed by my ReCaptcha console page, which shows 0 traffic.

![Screenshot 2023-12-24 at 07-49-59 reCAPTCHA](https://github.com/e107inc/e107/assets/6427368/7c665c09-f6a5-490c-800f-beeccd3832f1)

Maybe something changed in the API?

**Comment by Jimmi08** [comment]
Hi, 
because it is not a core plugin - this is the wrong repo.  Or discussion can be used I think, not sure. 

because e107.org version is outdated,  try to use the newer version 1.3.  

[](https://github.com/Jimako-e107-plugins/recaptcha)

If it still doesn't work,...  sorry, I don't use it anymore.  I don't know anybody who uses it.   I asked to remove it from e107.org a long time ago.      

There is a captcha plugin (visual captcha) supported by core developers. You can try this one.

**Comment by Jimmi08** [comment]
I found repo:  https://github.com/Jimako-e107-plugins/recaptcha

**Comment by HatchlingByHeart** [comment]
I understand @Jimmi08, thanks for your help. If this plugin isn't supported anymore, then I suppose I should close this issue.

**Comment by Moc** [comment]
Hi,

@Jimmi08 is correct, you are referring to a plugin that is not part of core. Ideally you should create an issue on the platform indicated by the plugin developer. 

For captcha you can use the core captcha. Alternatively there is also visualcaptcha:  https://github.com/e107inc/visualcaptcha
