### ISSUE TITLE
"ip" text box should be limited to 45 characters, not 32 characters, for IPv6

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#5176]
### Discussed in https://github.com/e107inc/e107/discussions/5175

<div type='discussions-op-text'>

<sup>Originally posted by **Jimmi08** January 23, 2024</sup>
Hi,
I am creating only a discussion, not an issue because I am not able to test it on the latest GitHub version. Maybe later. 

I tried to approve a comment on my site and I couldn't because of the IP address. 

![image](https://github.com/e107inc/e107/assets/5429548/a1e573a7-e298-4af4-a3d6-34382d992b82)

Maybe somebody other has this problem too.  
</div>

This is a bug, specifically on [this line](https://github.com/e107inc/e107/blob/d1f1b9e7cc213882a6027a0f50010f8a21f847f5/e107_handlers/form_handler.php#L6618-L6618):

With the `:` separators and potential IPv4-mapped IPv6 addresses, the maximum length of an IPv6 address should be 45 characters, but the text box is incorrectly limited to 32 characters.

**Comment by tgtje** [comment]
common answer :  39 ; but using mapped ip4 too it should be 45.

**Comment by Deltik** [comment]
Good point, @tgtje.  IPv4-mapped IPv6 addresses like `0000:0000:0000:0000:0000:ffff:127.000.000.001` are 45 characters.

I've updated the issue to reflect the proper character limit.
