### ISSUE TITLE
[Bug]: Cannot delete media from library

### ISSUE THREAD

**Issue by BlastFM** [e107inc/e107#5177]
### What e107 version are you using?

v2.3.3

### Bug description

I cannot delete media items, either by hitting the red X on the thumbnail or by selecting the media item with delete.

### How to reproduce

Attempt to delete an item from the library

### Expected behavior

Delete the image file

### What browser(s) are you seeing the problem on?

Microsoft Edge

### PHP Version

7.0.33-0ubuntu0.16.04.16

**Comment by Jimmi08** [comment]
Just addition - it is only in grid view. From the beginning. The list view is working.
![image](https://github.com/e107inc/e107/assets/5429548/6fb3887f-52d3-4726-8b09-2a2d9e977201)

**Comment by BlastFM** [comment]
Ok thanks, I was able to delete images in list view.

Does anyone know when this might get fixed?

**Comment by buckybytes** [comment]
I have been so inspired by the fact you figured out the workaround, I'll take a look at it.  No guarantees though, it'll be my first contribution attempt through github.

**Comment by CaMer0n** [comment]
Thank you @BlastFM ! This has been corrected.

**Comment by PH5HP** [comment]
Hi,

Is this supposed to be fixed in 2.3.3 or in the next release, because I have the same problem in 2.3.3.

Kind regards,
Henk - PH5HP.NL - https://fileserver.ph5hp.nl

**Comment by Jimmi08** [comment]
> Hi,
> 
> Is this supposed to be fixed in 2.3.3 or in the next release, because I have the same problem in 2.3.3.
> 
> Kind regards, Henk - PH5HP.NL - https://fileserver.ph5hp.nl

On the right side you can see version for fix 

![image](https://github.com/e107inc/e107/assets/5429548/664e7628-96a9-4c39-8fd8-e6bb9393e166)

**Comment by BlastFM** [comment]
> Hi,
> 
> Is this supposed to be fixed in 2.3.3 or in the next release, because I have the same problem in 2.3.3.
> 
> Kind regards, Henk - PH5HP.NL - https://fileserver.ph5hp.nl

It has been fixed in the latest version yes

**Comment by Moc** [comment]
It will be fixed in the next release which will be 2.4.0. The fix is not part of the 2.3.3 release (as that version was released before the fix was created). 

You can wait for the next release, or you can update to the latest files on Github. Be aware that the version on Github may not be stable and cause issues. It is therefore not recommended to use it on a live website. In case you do upgrade, be sure to have a backup available.

**Comment by PH5HP** [comment]
Hi,

Thank you for the swift reply. I will wait till the next release, because I can use the list view and delete the images.

Kind regards,
Henk - PH5HP.NL - https://fileserver.ph5hp.nl/

**Comment by BlastFM** [comment]
> The fix will be part of the next release: 2.4.0. The fix is not part of the 2.3.3 release (as that version was released before the fix was created).
> 
> You can wait for the next release, or you can update to the latest files on Github. Be aware that the version on Github may not be stable and cause issues. It is therefore not recommended to use it on a live website. In case you do upgrade, be sure to have a backup available.

I can only speak from my own experience and the version I have works fine in both view modes.
