### ISSUE TITLE
[Bug]: [Plugin]: Links_page plugin doesn't work on php 8.3.3

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#5213]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

The plugin links_page version 2.2 doesn't work on php 8.3.3

When you open the page of links_page plugin, it throws the followin exception:

```php
Fatal error: Uncaught Error: Undefined constant "ADMIN_UP_DOWN" in x/public_html/e107_plugins/links_page/link_defines.php:27
Stack trace: #0 x/public_html/e107_plugins/links_page/links.php(33): require_once()
 #1 x/public_html/index.php(69):
include_once('/...')
 #2 {main} thrown in x/public_html/e107_plugins/links_page/link_defines.php on line
27

```

And if you have the plugin active, and do a search over the links_page plugin, it throws this other exception:

```php
Fatal error: Uncaught Error: Undefined constant "DESC" in x/public_html/e107_plugins/links_page/e_search.php:43 
Stacktrace: #0 x/public_html/search.php(546): links_page_search->config()
 #1 x/public_html/search.php(647):
search_front->search_info('links_page', 'plug', './e107_plugins/...') 
#2 x/public_html/search.php(69): search_front->searchConfig()
#3 x/public_html/search.php(1043): search_front->__construct()
 #4 x/public_html/index.php(107):
include('/...')
 #5 {main} thrown in x/public_html/e107_plugins/links_page/e_search.php on line 43

```

With php 7.4.33 works fine.

### How to reproduce

1. get working your e107 page using php 8.3.3
2. check if you have installed the links_page plugin. It says that is developed from e107 and aparently its latest version is 2.2
3. configure its page on your navigation menu to access it
4. go to it, and check how the site fails to load when you access to the links_page page

### Expected behavior

That the content of the page of the plugin loads without problems.
Like that It can do on php7

### What browser(s) are you seeing the problem on?

Firefox, Chrome / Brave, Microsoft Edge

### PHP Version

php8.3.3

**Comment by Moc** [comment]
Hi, the plugin is no longer part of core (since e107 v2) and is not supported by the core developers anymore.

**Comment by sanslash332** [comment]
Oki @Moc 
Thanks for the advice :-)

I'll try to fix it, but if I need ask something to someone, where I can do that?

E107 have a discussion site or discord for ask for help without compromising or just small questions about coding e107 plugins?

thanks for all :-)

**Comment by Moc** [comment]
You're welcome! :) 

You can use https://github.com/e107inc/e107/discussions/categories/q-a-plugins
And there is a chatroom here: https://app.gitter.im/#/room/#e107inc_e107:gitter.im
