### ISSUE TITLE
[Bug]: Second template file not loading with e107::getTemplate

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#5245]
### What e107 version are you using?

v2.3.3, Latest Github version (just updated)

### Bug description

I'm building a plugin, and i want (or need) two different template files: **plugin_template.php** & **plugin_view_template.php**

Somehow, i'm unable to load **plugin_view_template.php** with `e107::getTemplate('plugin_view', 'plugin_view')`, or any other variant, as matter fact.
But i can load **plugin_template.php** with `e107::getTemplate('plugin', 'plugin')`....

Both templates are on the _template_ folder, so what i'm doing wrong here? Or there's indeed a bug????

### How to reproduce

Create two templates on template folder: **plugin_template.php** & **plugin_view_template.php**
Create two php files on main plugin folder.
In one of them, try to load template **plugin_template.php** with e107::getTemplate & on the other try to load **plugin_view_template.php** with e107::getTemplate
The **plugin_view_template.php** won't load.

### Expected behavior

I expected to be able to load diferent templates in diferent files of the plugin...

### What browser(s) are you seeing the problem on?

Firefox

### PHP Version

PHP 7.4

**Comment by Jimmi08** [comment]
Try
`getTemplate('plugin', "plugin_view");`
and be sure that your template has correct array - $PLUGIN_VIEW -  used.

**Comment by rica-carv** [comment]
Yes, my template has correct array $PLUGIN_VIEW..... 

I'm scavenging for grammar issues... I hate these little bugs...

**Comment by rica-carv** [comment]
Forget it, somehow today is working... without any changes in code! Weird...
