### ISSUE TITLE
Prettyphoto not load

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#5246]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

Prettyphoto (gallery.js) not load on Gallery.
Uncaught TypeError: settings.gallery is undefined
attach http://localhost/e107_plugins/gallery/js/gallery.js:14

### How to reproduce

When I click on the picture the frame does not appear, only the picture.

### Expected behavior

The picture need appear in frame (prettyphoto).

### What browser(s) are you seeing the problem on?

Firefox

### PHP Version

PHP 8.1.10 (localhost)

**Comment by Jimmi08** [comment]
Confirmed. I am not able to fix this.

**Comment by fizi** [comment]
Thanks! Work.
