### ISSUE TITLE
[Question]: Include an icon in Admin Menu?

### ISSUE THREAD

**Issue by Vodhin** [e107inc/e107#5287]
### Question

Is there a way to include an Icon and/or `<span>` elements in a Plugin's Admin Menu? 

**What is documented:**
```
protected $adminMenu = array(
    'estate_agencies/inbox' => array('caption'=> 'Agent Inbox', 'perm' => 'P')
    );
```

**is there something like this:**
```
protected $adminMenu = array(
    'estate_agencies/inbox' => array('caption'=> 'Agent Inbox', 'perm' => 'P', 'icon'=>'<i class="fa fa-envelope">3</i>')
    );
```

### Expected Source

looked in core_functions.php and other places.

### Additional Context

I would like to be able to add icons/counter to the buttons in the Admin Menu for my plugin, similar to how the e_dashboard.php file works.

**Comment by CaMer0n** [comment]
@Vodhin Yes, if you want it to be dynamic, you should create an **init()** method for the class that contains the $adminMenu and then include something like this in it: 
```
$this->adminMenu['estate_agencies/inbox']['badge'] = array('value' => 12, 'type'=>'warning');
```
