### ISSUE TITLE
[Feature request]: Upgrade bootstrap datetimepicker to a maintained repo

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#5292]
### Motivation

The original developer stopped maintaining the package. 

### Proposed Solution

Use the most up-to-date repo in the network:  https://github.com/egis/bootstrap-datetimepicker

### Alternatives

none

**Comment by rica-carv** [comment]
[Bootstrap 5 datetimepicker in github](https://github.com/simplicitesoftware/bootstrap-datetimepicker)
