### ISSUE TITLE
[Bug]: not working Admin UI grid switch for Find plugins - List view is empty

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#5362]
### What e107 version are you using?

v2.3.3, Latest Github version (just updated)

### Bug description

Normal view:

![image](https://github.com/user-attachments/assets/e9737eca-2c8f-44f1-88c3-d5cda6a70168)

List view:

![image](https://github.com/user-attachments/assets/0b503611-567c-4341-928b-b67870c37cd9)

Note: I am using Alex's admin css for testing,  but it has nothing with functionality.

### How to reproduce

1. Go to Plugin Manager
2. Find Plugins
3. Click on icon for List View

### Expected behavior

Not available List view button if this functionality is not supported

### What browser(s) are you seeing the problem on?

Chrome / Brave

### PHP Version

8.2

**Comment by CaMer0n** [comment]
Is it the same in Firefox? I just tested with PHP 8.3

![image](https://github.com/user-attachments/assets/bf16b1cc-1812-4fd1-b55f-787ae4dc866c)

**Comment by tgtje** [comment]
just tested too on loal php 8.2.13 date files april git. and fresh updated with present git files : 
all functions as should using FF list is there

although this error is **still** present 
Warning Undefined array key 1, Line 7388 of C:\wamp64\www\e107n\e107_handlers\form_handler.php
`			list($type,$plugin) = explode('-',$fid,2);`

in present file on git it is line 7409   just posting,  Iff it's an issue????

**Comment by Jimmi08** [comment]
Synced with the latest git version, It works. 
So I went to installation from the first post -  and the problem was that all columns were set off...  that option to display columns.  
Weird, I am sure I haven't used this option.  

![image](https://github.com/user-attachments/assets/88f418d1-4c62-4cd9-a50a-fc949bee1df9)

Nevermind, false issue. Thanks.
