### ISSUE TITLE
[Bug]: Fatal error: Uncaught Error: Undefined constant "CUSLAN_83"

### ISSUE THREAD

**Issue by otula71** [e107inc/e107#5366]
### What e107 version are you using?

Latest Github version (just updated)

### Bug description

When I click on the "Pages/Menus" button, I get 
`Fatal error: Uncaught Error: Undefined constant "CUSLAN_83" in /srv/http/e107_admin/cpage.php:624 Stack trace: #0 /srv/http/e107_handlers/admin_ui.php(1500): [constant expression]() #1 /srv/http/e107_handlers/admin_ui.php(1475): e_admin_dispatcher->_initController() #2 /srv/http/e107_handlers/admin_ui.php(1361): e_admin_dispatcher->getController() #3 /srv/http/e107_handlers/admin_ui.php(1122): e_admin_dispatcher->runObservers() #4 /srv/http/e107_admin/cpage.php(1196): e_admin_dispatcher->__construct() #5 {main} thrown in /srv/http/e107_admin/cpage.php on line 624`

### How to reproduce

1. Go to Administrator's control panel
2. Click on 'Pages/Menus' button

### Expected behavior

I expexted to get the Pages/Menus administration page

### What browser(s) are you seeing the problem on?

Chrome / Brave

### PHP Version

PHP 8.3.15

**Comment by CaMer0n** [comment]
@otula71 Thanks. Are you using the admin area in English?

**Comment by otula71** [comment]
@CaMer0n Yes, in English.

**Comment by CaMer0n** [comment]
@otula71 Thanks. Please check the contents of `e107_languages/English/admin/lan_cpage.php`

It should contain these lines at the bottom: 

```
define("CUSLAN_83", "Will be listed in the Menu-Manager under this name or may be called using {CMENU=name} in your theme. Must use ASCII characters only and be all lowercase.");
define("CUSLAN_84", "Caption displayed on the menu item.");
define("CUSLAN_85", "Leave blank to use the default");
define("CUSLAN_86", "Leave blank to use the corresponding page");
```

**Comment by otula71** [comment]
@CaMer0n Thanks. The lines were missing (I absolutely don't understand how it is possible - I've now checked the zip downloaded from git, from which I installed e107, and the file is fine OK. Strange...) Thank you very much.
