### ISSUE TITLE
filetypes.xml not working with new extensions

### ISSUE THREAD

**Issue by NZMikey** [e107inc/e107#550]
Attempted to add dmg and sit to the filetypes.xml and it keeps insisting under admin download upload that the file extension is invalid.

<class name="253" type="zip,gz,jpg,jpeg,png,gif,xml,dmg,sit" maxupload="40M" />
is the modified version that doesnt seem to work.

**Comment by pierre0042** [comment]
Same error for me

**Comment by pierre0042** [comment]
Screenshot :

![e107-import](https://cloud.githubusercontent.com/assets/4124597/13126898/d1eee3fe-d5cc-11e5-9049-3c7aec2c61d7.png)

**Comment by CaMer0n** [comment]
@LaocheXe Through which area are you trying to upload?

**Comment by LaocheXe** [comment]
@CaMer0n Admin Area -> News

**Comment by Moc** [comment]
Confirmed the issue::

`filetypes.xml` appears not to be checked when uploading new files (plupload). This happens when creating a new download item, but also in the Media Manager (Media Upload/Import, `/e107_admin/image.php?mode=main&action=import`). 

![image](https://user-images.githubusercontent.com/577978/52211314-d0c96180-2889-11e9-8b8d-d951cc5d5a00.png)

Tried uploading a `.dmg` file. Contents of filetypes.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<e107Filetypes>
	<class name="253" type="zip,gz,jpg,jpeg,png,gif,xml,pdf,dmg" maxupload="2M" />
</e107Filetypes>
```

**Comment by Moc** [comment]
@CaMer0n Please also see https://github.com/e107inc/e107/issues/1809

**Comment by CaMer0n** [comment]
@Moc `<class name="253"` = members, not admins.  I believe `filetypes.xml` is currently used for _member_ uploads, not _admin_ uploads. If we want to use it for admin then another entry would need to be added to filetypes.xml ie. `<class name="254"` . However, I don't find this very user-friendly. It should probably function more like `plugin.xml` 'sitelinks'. eg. name='members'. 

In the meantime, I have added .dmg to media-manager.

**Comment by Moc** [comment]
@CaMer0n Well, all admins are 'members' too (= registered user). But I agree with the logic. 
Anyway, filetypes.xml is not used in media manager uploads atm. We'll need to re-think if/how we want to manage filetype extensions by admins.
