### ISSUE TITLE
Import into e107

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#554]
Not a big issue, but it would be nice if it would be coded in to the plugin (Import into e107) - When porting over user groups, forums, etc.... It lacks with the import of sub forums. As in it does not port over sub forum post etc.

User groups would be user classes - I tried to port in the user groups from phpbb and it's lacking the whole area.

**Comment by Moc** [comment]
This depends on the system it needs to be imported from as each external system is different and has a different database structure. Please submit individual issues with specific enhancement suggestions per system that you'd like to import data from into e107. 

Closing this one.
