### ISSUE TITLE
unknown error type

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#565]
As mentioned the existance of (red) form field as on gallery categories page
or media manager > manage. Bottom form filed : Text : Used by..
has no 'setting".

'media_usedby'          => array('title'=> 'Used by',     'type' => 'THIS IS EMPTY',        'data'=> 'text',

line 675 of admin/image.php (d.d 05-05-14)

Either intentional or not 'programmed' yet or just forgotten ?
forum post with img : http://e107.org/e107_plugins/forum/forum_viewtopic.php?251284

**Comment by CaMer0n** [comment]
This was fixed. If it becomes visible again, please re-open.
