### ISSUE TITLE
More descriptive message in log when user registers

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#599]
Last evening i was talking to @Moc about an systemlog message that scared me big time.

![admnlog](https://cloud.githubusercontent.com/assets/6122908/3080873/e6540cf6-e4b6-11e3-83d9-de8f578780f1.png)

first issue .. the systemlog does not show a time.. so it's hard to see what happened here..
and the description .. not really helping.

as it turned out this was a new user registering at the site.
a more clear message would have helped here.

**Comment by Moc** [comment]
Closing this. 

Datestamp issue is fixed a long time ago, should display now. If not, please let me know and I'll re-open. 

The event title is a default title for all inserts in the database. If you click on "More details" in the Further information column it should display exactly what was inserted. This may not have been the case back in 2014 but I am quite sure it is added there now.
