### ISSUE TITLE
IPs v4 and v6

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#600]
When looking at a problem yesterday i noticed 2 different types of IPs in the database.

the ban list contain both ip v4 and v6 ips.
the users now have v6 IP's but show up in the logs as IPv4.
(makes it hard to find the user)

an option to find a user on his IP would be nice here too.
(this now doesnt work for v6 adresses?)
![search ip](https://cloud.githubusercontent.com/assets/6122908/3081004/16c78f28-e4b9-11e3-89ac-35a72a8eb84d.png)

**Comment by CaMer0n** [comment]
@willem010 is this bug still an issue?

**Comment by willem010** [comment]
yeah, that site still has that issue. and it will probably wil stay that way.. 

problem appeared when converting old site to v2.0
the old records are still in v4, the new ones are in v6.

if there was any conversion going on during upgrade, it failed at that time..
problem never got solved, 

but this issue relates to the site whixh is no longer miine, so.. for me .. there is no issue :P lol

btw, 
most of my older pending issues relate to this site
i left the issues open, thinking the issues need to be solved anyway. 
(except for the feature requests .. if you want me to close em.. just say so.. )

all my other e107 sites are working, but noting fancy there, most e107 features are unused,,( and the visitor load cannot be compared.)

**Comment by CaMer0n** [comment]
okay thanks. I'll close it for now, as it's most likely due to the timing of updates and database changes.
