### ISSUE TITLE
download voting dialog 

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#603]
voting sometimes shows:
![voting on detail page](https://cloud.githubusercontent.com/assets/6122908/3081212/28674a36-e4bc-11e3-898d-5153c8bdfe5c.png)

:on my site this happens in some folders..

other folders show correct:
![vote ok](https://cloud.githubusercontent.com/assets/6122908/3081263/012c7f9e-e4bd-11e3-907a-8bee9b6baff3.png)

**Comment by CaMer0n** [comment]
Fixed in #855 so it should fix the rating here too. Please re-open if it is not the case.
