### ISSUE TITLE
Get PDO working again with mysql_class.php

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#605]
Some time ago I added PDO support to the mysql_class.php. 
It appears to be broken now.. 
To enable and test, add the following to e107_config.php

```
define('e_PDO',true);
```

**Comment by CaMer0n** [comment]
@lonalore feel like testing this with me?

**Comment by lonalore** [comment]
Yes, of course! But first, I create a pull-request for issue #991.

**Comment by Moc** [comment]
Where are we on this?
@CaMer0n @lonalore

**Comment by CaMer0n** [comment]
@Moc It should be fully functional, but will require more testing. Yesterday I got the install working with PDO. You can try it by uncommenting these lines at 240: 
```
$this->pdo = true;
define('e_PDO', true);
```
