### ISSUE TITLE
Forum upgrade on empty tables

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#615]
Just tested a fresh install.
Upgrade function well.
1 Error bumped in to.
Forum plugin was installed in v1 (just an install > no threads, parents etc..)
When upgrading the system implies to update the forum.
When updating (unaware of being just an installed plugin, but not configured more)
I did follow steps up to Step 5 (transfer).
There the system 'holds'.

Culprit : the system wants to start a process where there is nothing to do ( or available)
after discovery of empty tables in dbase, 
UNinstalled forum.
Refereshed all, (check for deleted forum tables )

Now installing Forum (v2) just fine. no errors

descriptive : a routine that detects an empty plugin or empty dbase tables

**Comment by CaMer0n** [comment]
Thank you for your detective work, was a very helpful bug report.
