### ISSUE TITLE
question: Load js files async

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#618]
Is there a way to tell e107 the js file added with e107::js to load asynchronously ?

if not, consider this a feature rewuest.

**Comment by CaMer0n** [comment]
@Moc Here's a usage example of this addition for the docs. 

    e107::js('footer', 'https://www.google.com/recaptcha/api.js?hl=en', ['defer','async']);

### Footer Output

    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js?hl=en" defer async></script>

Currently only 'header' and 'footer' are supported.
