### ISSUE TITLE
Feature request: content -set release date or start date/end date

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#644]
I find content could set up start date and end date is much better than release date.
Like News function:

a.Follow item did not set release date or start date/end date, I think some time we need provide short term content. 

Welcome Messages
Poll
Pages/Menus
Downloads
Forum-
e107_plugins/forum/forum_post.php
Gallery

PS: I download gitgub file today for test. I'm not sure this is feature request or not.

**Comment by Moc** [comment]
I'm pretty sure this is outside the scope of e107 at the moment. As Cameron noted, this functionality could be added to plugins individually, e.g. the poll.
