### ISSUE TITLE
question - preformatted text

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#654]
Hi,
I would like to use Syntax Highlighter . 

When I use clean 
![image](https://cloud.githubusercontent.com/assets/5429548/3293088/f63b2db6-f596-11e3-9508-d2a4e999ee00.png)
tags, output is correct, but when I use

![image](https://cloud.githubusercontent.com/assets/5429548/3293097/0a0b850c-f597-11e3-9e35-c24c2c70a8db.png)
 it displayed <br> tags instead new line.  Checked, value from database is changed after calling this: $tp->toHTML($this->pageText, TRUE, 'BODY');   

Thanks
(I thought originally that it's related to tinymce, but afted set it off, it still does this way)

**Comment by CaMer0n** [comment]
TinyMce now includes a format for syntax highlighting.
