### ISSUE TITLE
Feature request: Pages Pagination

### ISSUE THREAD

**Issue by e107bg** [e107inc/e107#664]
On pages list (chapter view) - pages per page (nextprev sortcode)
Page image, same like menu image.
Page icon, same like menu icon.

**Comment by CaMer0n** [comment]
@e107bg I believe the Page custom-fields solves "Page image" and "Page icon".

**Comment by Moc** [comment]
Closing due to lack of feedback. If you still require help, please let us know and I'll re-open.
