### ISSUE TITLE
rss output plugin bugs

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#668]
rss output, 
- news bug in RSS 1.0 mode.
  rendering of output stops on item containing br tag.
 (no problems in rss2.0 mode)

- downloads
  error on download/e_rss.php 
 i think the problem was with line 38 (db_Select)
(suddenly my error reporting stopped reporting.)

**Comment by CaMer0n** [comment]
@willem010 is this one still an issue?

**Comment by willem010** [comment]
i cant test this one,. old site.
i will close it.
