### ISSUE TITLE
Can't delete thread in forum

### ISSUE THREAD

**Issue by stepper** [e107inc/e107#681]
Hi.

Can't delete forum thread.
It updates the page but is still there.
Have downloaded and uploaded the newest version of alpha 2. no luck

Here is the link
http://danishrebels.dk/e107_plugins/forum/forum_viewforum.php?id=4

**Comment by Moc** [comment]
@stepper @mcpeace-maw Is this still an issue using the Bootstrap 3 based theme in the latest Github files?

**Comment by mcpeace-maw** [comment]
I try it in my last theme and it is OK. Notification of the operation it is visible at the end, all seams to be OK. I think it is safe to close this issue.

**Comment by Moc** [comment]
@mcpeace-maw Thank you for the quick reply and testing. Closing this issue.
