### ISSUE TITLE
Socialshare shortcode

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#685]
I used the socialshare shortcode and on news are displayed social links even on admin area nothing is set, External Social Pages fields are empty. If someone don't want to use these links or want just one social link, not all links? I think a better thing is that the shorcode to check if External Social Pages fields are not empty and display just the links that have a target.

**Comment by CaMer0n** [comment]
@mcpeace-maw I'm closing this for now as the shortcode now allows one to set which social URLs to display. eg.  `{XURL_ICONS: type=facebook} `. 
If you think it should be re-opened for some reason, please let me know. thank you.

**Comment by mcpeace-maw** [comment]
All good now, just 1 thing I don't like, min-width:435px hard coded style in social dropdown. If is really needed a min-width there, min-width:225px is for 2 rows of icons, if you activate all and if you use less, empty space is smaller.
