### ISSUE TITLE
How to override core shortcodes

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#690]
I needed to override contact shortcodes, so I did by this (e107_class.php):
![image](https://cloud.githubusercontent.com/assets/5429548/3470292/c695ea68-02b8-11e4-8ca1-016233114889.png)
![image](https://cloud.githubusercontent.com/assets/5429548/3470470/a1cdb038-02ba-11e4-9567-183293719742.png)

this:
- copied core contact_shortcodes.php to contact plugin (folder shortcodes/batch) 
- called it in menu:
$contact_shortcodes = e107::getScBatch('contact', 'contact' , true);

After testing I found that I need rename them (line are from shortcode_handler.php and variable are $class_name and $path:
![image](https://cloud.githubusercontent.com/assets/5429548/3470518/1bd4aea4-02bb-11e4-915f-8c931a6c2ae4.png)

So now my file is called: plugin_contact_contact_shortcodes.php
and class inside is: plugin_contact_plugin_contact_contact_shortcodes. This way everything works, but seems weird.

In manual is:
![image](https://cloud.githubusercontent.com/assets/5429548/3470418/254198c2-02ba-11e4-87db-10eade76da60.png)

So what is right way to do something like that?  I don't want to use e_shortcode. I need way how to rewrite core shortcodes without doing it in core files. 
Thanks

**Comment by rica-carv** [comment]
Just a small question: Do override shortcodes file has to have all the original file shortcodes functions, or it can hold only the specific shortcodes to be overridade, without duplicating the core ones?
For instance:
**Original:** (SHORTCODE1, SHORTCODE2, SHORTCODE3)
**Override:** (SHORTCODE1, SHORTCODE2, SHORTCODE3)
or can it be
**Original:** (SHORTCODE1, SHORTCODE2, SHORTCODE3)
**Override:** (SHORTCODE2)
???

**Comment by CaMer0n** [comment]
These override methods are quite old. I'm working on an updated method now which can use e_shortcode.php with a minor addition.

**Comment by rica-carv** [comment]
@CaMer0n So, if you're working on a updated method, why not allow a theme to override shortcodes? Just like it's donne for templates inside a theme?
If you're interested, i've got a hack of my own on [this theme - work in progress - here](https://github.com/rica-carv/e107_theme-selospt_v2)....
But for me, that's not the way to go, since i'm initiating all the shortcodes as soon the theme is loaded....

**Comment by CaMer0n** [comment]
@rica-carv Not tested, but the same method is used during initialization so theme overrides should work. You can test with e_DEVELOPER set to true in your e107_config.php

**Comment by eduardocp** [comment]
@CaMer0n I change the $override value to true override a shortcode from the forum plugin but my method is never called... Is it possible to override a shortcode from a plugin?

**Comment by rica-carv** [comment]
@eduardocp You need to like [this](https://github.com/e107inc/e107/blob/afbe20614b46805fc8fb169f5dd0a200bf600062/e107_plugins/_blank/e_shortcode.php#L16), inclunding extending the core class e_shortcode.
All is donne inside the theme folder.
You can only override a shortcode from a plugin if the shortcode is global, ie, is available globally.
A local plugin shortcode can only be overriden by a theme, with the method explained above...

**Comment by eduardocp** [comment]
@rica-carv When you say include the file is physically or with `require` (or would be `require_once`)?

Could you give a practical example?

**Comment by rica-carv** [comment]
@eduardocp Is this question related to #2495?
