### ISSUE TITLE
Custom pages - problem withe setting url for page without chapter

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#694]
I have page without chapter (Book/chapter: none)
Default setting works:

![image](https://cloud.githubusercontent.com/assets/5429548/3487032/4987f310-045f-11e4-96cf-b8e95cd1ce2c.png)

After changing for any of others:
![image](https://cloud.githubusercontent.com/assets/5429548/3487035/5dd54868-045f-11e4-90a4-51f1e8c635ed.png)

Thanks.

**Comment by CaMer0n** [comment]
Had to revert the commit on the book/chapter/page sef module. Could you please check and tell me any remaining symptoms?

**Comment by Jimmi08** [comment]
Hi, fresh install. I didn't notice any problems, SEF url for pages seems to work fine.

**Comment by LaocheXe** [comment]
What I notice with Custom Pages is that it doesn't give you the option to give it a link in the main site links area like the older version of e107. I have no issues with custom pages not showing up with no book/chapters
