### ISSUE TITLE
Extended User Fields - not working

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#697]
I added one new (location) and one custom user field. 
When I tried update user profile (the data was not saved), I got this sql error.
![image](https://cloud.githubusercontent.com/assets/5429548/3506497/6f8373c2-0672-11e4-854f-a883961d3680.png)
Did I set something wrong in extented user fields?

**Comment by CaMer0n** [comment]
@Jimmi08 is this one still an issue? I haven't had any problems extended-fields lately.

**Comment by Jimmi08** [comment]
Tested. It works fine.
