### ISSUE TITLE
tagwords - not working

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#699]
Hi, probably forgotten to comment some checks:
No data are inserted in database.
![image](https://cloud.githubusercontent.com/assets/5429548/3521897/70f067e6-0745-11e4-8b48-eeef502ea196.png)
After commenting these 2 lines, everything works
Thanks

**Comment by NZCyrus** [comment]
@Jimmi08 - you mentioned that tagwords with News updates and works fine. 
It doesn't for me, still have this issue after including tagwords with News but none are updated.

![tagwords](https://cloud.githubusercontent.com/assets/7886491/6094030/92ba6d10-af7c-11e4-9148-f5e3f41c1fbe.png)

**Comment by Jimmi08** [comment]
Did you set correct separator? I remember that there was main problem. I didn't try it long time, sorry...

**Comment by Jimmi08** [comment]
Closing this, because there is new issue, this was changed after rewritting news plugin. Too confusing after so much time.

https://github.com/e107inc/e107/issues/1219
