### ISSUE TITLE
Unable to delete userclass

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#714]
Hi all,

I'm trying to clean up some old userclasses that are no longer in use (used only in plugins I didn't re-enable after upgrade) and every time I try to delete, I get this error:

Error
Class not deleted - it is a core class, or is used in the definition of another class, as either parent or edit class

Nobody's assigned to the class I'm trying to delete, it's not a parent of another, and it's not used as an edit class anywhere. It's basically an orphan class. Any ideas?

Cheers,
Min

**Comment by CaMer0n** [comment]
No longer an issue. Closing.
