### ISSUE TITLE
Forum: Quote post under Options dropdown

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#717]
Hi all,

When using the Options drop down to Quote a post, the reply page loads with the correct quote/bbcode in the textarea. I can type in whatever additional content (or none at all) and after selecting the Post a Reply button I'm directed back to main forum page (not the thread I was in) and the new post isn't posted.

If I just start a reply and manually type in the quote bbcode / paste the text to quote in between it works fine in a reply; it's just when using Quote from the Options dropdown that it doesn't seem to work.

Let me know if you want more info (tried it on my live build and also on a fresh local install with same results).

Cheers,
Min
![quote](https://cloud.githubusercontent.com/assets/887725/3711171/c4627b12-14c4-11e4-9937-94be7d697c0b.png)

**Comment by CaMer0n** [comment]
This code is so old and mixed up. Will take another crack at it another time.
