### ISSUE TITLE
filter in news - problem with national characters

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#719]
Yes, I know, again me with german characters.
This happens:
![image](https://cloud.githubusercontent.com/assets/5429548/3767774/a9c9851a-18d0-11e4-8e4d-4280d009cadf.png)
And of course, no correct filtering results.

This is what I checked:
Data are displayed correctly
Data are saved correctly
![image](https://cloud.githubusercontent.com/assets/5429548/3767794/ddf9eeba-18d0-11e4-90ef-952005529b32.png)
My collations are correct:
![image](https://cloud.githubusercontent.com/assets/5429548/3767807/f8a0d33c-18d0-11e4-9215-ef12525c4285.png)

![image](https://cloud.githubusercontent.com/assets/5429548/3767811/000fd492-18d1-11e4-9fb9-c7ec3f768aa9.png)

Only visible problem is bug in phpmyadmin:
![image](https://cloud.githubusercontent.com/assets/5429548/3767820/11aebbdc-18d1-11e4-8e86-08b2f556387d.png)
 (you can't change this)
So I used different database manager, it's seems ok.
![image](https://cloud.githubusercontent.com/assets/5429548/3767891/9ce6ed32-18d1-11e4-86af-4a3fc07233ef.png)

Thanks for help

**Comment by CaMer0n** [comment]
@Jimmi08 Is this still an issue?

**Comment by Jimmi08** [comment]
I really don't know. It seems like it's problem only for some characters, not for all.
First test:
![image](https://cloud.githubusercontent.com/assets/5429548/6029490/48e24304-abf1-11e4-833d-74fe9bf4559c.png)

After insert this and click on button Filter 
![image](https://cloud.githubusercontent.com/assets/5429548/6029503/60f963c8-abf1-11e4-9909-4c780326c529.png)

result is:
![image](https://cloud.githubusercontent.com/assets/5429548/6029551/9d68b9a8-abf1-11e4-97cd-5c121212109a.png)

It wrong with these character:  š, ý, á, í, é, ú, ô.  These ones work: ž, č.

You can test it this way: if you insert them in input file (copy one from above line) and click on filter button, input file is empty. 
![image](https://cloud.githubusercontent.com/assets/5429548/6029630/2544099a-abf2-11e4-9473-2b1493aaf3a8.png)
 
![image](https://cloud.githubusercontent.com/assets/5429548/6029644/41e2fce6-abf2-11e4-8d43-a2b3804a5f25.png)

**Comment by CaMer0n** [comment]
Reproduced it, still trying to find the cause.

**Comment by Jimmi08** [comment]
If this helps:
wrong:
![image](https://cloud.githubusercontent.com/assets/5429548/6041514/71f0c4aa-ac7d-11e4-9cdc-feff39200e9e.png)
good:
![image](https://cloud.githubusercontent.com/assets/5429548/6041542/aa06b08e-ac7d-11e4-9694-7951d21c7e4c.png)

they are values of $request_data from parseRequest() function in admin_ui.php 

e_QUERY is already wrong in __construct function

**Comment by Jimmi08** [comment]
Normal search (search.php) works fine, just tested.

**Comment by CaMer0n** [comment]
@Jimmi08 Please test with search and other areas using url queries.

**Comment by Jimmi08** [comment]
Tested. In admin_ui it works. 
In search.php not, but I don't see the reason. Query is correct... Data inserted in db are correct. But result is empty (checked by manually inserted search query in phpmyadmin) 
I will try to use the same data as I used in working search 2 days ago and let you know.

**Comment by Jimmi08** [comment]
My mistake. I didn't know that I need to search whole word. 
Search works, tested on news and pages...

**Comment by CaMer0n** [comment]
Great! Thank you @Jimmi08  !

**Comment by Jimmi08** [comment]
You are welcome, by the way, I tested Russian, Slovak and Chinese characters. All works.

**Comment by CaMer0n** [comment]
@Jimmi08 - Wonderful! All language restrictions have been removed too, so v2.x language-packs may now be prepared and used.

**Comment by CaMer0n** [comment]
@Jimmi08 This seems to have become an issue again. I'm writing a test for it now.

**Comment by Jimmi08** [comment]
Closing in favour
https://github.com/e107inc/e107/issues/4427
