### ISSUE TITLE
Possible issue in *_setup.php  upgrade_required() method

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#727]
After finishing the forum upgrade procedure, e107 still asks to update the forum. 
This is because the upgrade_required() method is not working as intended. 

If I change the forum_setup.php file to include this, it will still trigger an update request:

```php
	function upgrade_required()
	{
		return false;		
	}
```

/cc @CaMer0n @SecretR

**Comment by CaMer0n** [comment]
@Moc is this one still an issue?

**Comment by Moc** [comment]
Not sure as I haven't tested lately but it is related to https://github.com/e107inc/e107/issues/1012 
Possibly this issue is causing #1012

**Comment by CaMer0n** [comment]
@Moc Closing this, as the related issue in closed also.
