### ISSUE TITLE
Private Message notification email - link to PM is blank

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#729]
Hi all,

Just a small thing - when you have email notifications turned on for Private Messages, the "You can view the PM at:" is blank. 
I'm getting around this by using a bit of the old code from a previous version: 
In pm_class.php, pm_send_notify function, adding:
global $PLUGINS_DIRECTORY;
and
$pmlink = SITEURL.$PLUGINS_DIRECTORY."pm/pm.php?show.{$pmid}";
No idea if this code is even relevant in the new versions but it seems to make the link display in the email and figured I should report it so that someone who knows what they're doing can look into it.

Let me know if you need more info. 
Cheers,
Min

**Comment by CaMer0n** [comment]
@Minnn - is this still an issue?

**Comment by Minnn** [comment]
Just downloading last night's update...
Yes, still blank for me. Sorry.

**Comment by CaMer0n** [comment]
Okay thanks, will look into it.

**Comment by Minnn** [comment]
If it helps, the hack I put in the first post still works (that's how we're getting around it on the live site, at least).

**Comment by CaMer0n** [comment]
@Minnn I haven't test this fully, but in theory it should correct the issue.

**Comment by Minnn** [comment]
Confirmed fixed :)
