### ISSUE TITLE
emoticon coding not rendering assigned emoticons

### ISSUE THREAD

**Issue by kimmetje** [e107inc/e107#732]
When assigning multiple codes or custom codes to an emoticon set, the emoticons do not render correctly.

**Comment by TealFox** [comment]
@CaMer0n , question, were you able to ever track down what was causing this??

**Comment by CaMer0n** [comment]
@TealFox Would you have an alternate emoticon pack you could send me to test?

**Comment by TealFox** [comment]
Sure thing! Incoming! If you would rather me sending it to you in another way, just lemme know and I can do that too.

![angel](https://cloud.githubusercontent.com/assets/4345779/9325170/ba09a368-4590-11e5-96b8-98a203462a1b.png)
![angry](https://cloud.githubusercontent.com/assets/4345779/9325166/ba07ac70-4590-11e5-877b-ab264ec2e2cb.png)
![bell](https://cloud.githubusercontent.com/assets/4345779/9325167/ba07ea00-4590-11e5-9c11-ab5a071681bf.png)
![confused](https://cloud.githubusercontent.com/assets/4345779/9325168/ba081854-4590-11e5-95d3-3ecdcadf1d82.png)
![cool](https://cloud.githubusercontent.com/assets/4345779/9325171/ba0a87b0-4590-11e5-82a7-b0b13f39191c.png)
![crazy](https://cloud.githubusercontent.com/assets/4345779/9325169/ba08ce48-4590-11e5-852e-8966ad76587a.png)
![crown](https://cloud.githubusercontent.com/assets/4345779/9325174/ba1d5cf0-4590-11e5-9d2f-acd149e2cdbb.png)
![crying](https://cloud.githubusercontent.com/assets/4345779/9325172/ba1ae0c4-4590-11e5-8864-bc7f8024c1aa.png)
![devil](https://cloud.githubusercontent.com/assets/4345779/9325173/ba1d111e-4590-11e5-9b9c-903bb9cebfe6.png)
![dislike](https://cloud.githubusercontent.com/assets/4345779/9325176/ba1f5bf4-4590-11e5-82af-925bc19afca7.png)
![evil](https://cloud.githubusercontent.com/assets/4345779/9325177/ba21c736-4590-11e5-9a65-ae29c68cfa59.png)
![happy](https://cloud.githubusercontent.com/assets/4345779/9325175/ba1eed54-4590-11e5-9f13-bdad943ae3c1.png)
![in_love](https://cloud.githubusercontent.com/assets/4345779/9325178/ba2fa2b6-4590-11e5-9964-8c183315aa91.png)
![kiss](https://cloud.githubusercontent.com/assets/4345779/9325179/ba309e14-4590-11e5-93d6-9a5bacd5eead.png)
![like](https://cloud.githubusercontent.com/assets/4345779/9325181/ba34d7a4-4590-11e5-9d60-1ddd15d3c346.png)
![lol](https://cloud.githubusercontent.com/assets/4345779/9325182/ba35150c-4590-11e5-8c75-32f58524d63b.png)
![megaphone](https://cloud.githubusercontent.com/assets/4345779/9325180/ba329c3c-4590-11e5-91a5-a6000484861d.png)
![nerd](https://cloud.githubusercontent.com/assets/4345779/9325183/ba384c36-4590-11e5-9d26-7d55022e60c8.png)
![neutral](https://cloud.githubusercontent.com/assets/4345779/9325185/ba43d7b8-4590-11e5-902d-c3ccab4cd4db.png)
![paper_plane](https://cloud.githubusercontent.com/assets/4345779/9325186/ba475744-4590-11e5-9cca-b94ad5cee3ba.png)
![poo](https://cloud.githubusercontent.com/assets/4345779/9325187/ba47d3c2-4590-11e5-8ba9-9bdae1dd9882.png)
![question](https://cloud.githubusercontent.com/assets/4345779/9325188/ba48653a-4590-11e5-829e-13d2cc499a2e.png)
![sad](https://cloud.githubusercontent.com/assets/4345779/9325189/ba4bed2c-4590-11e5-9922-44c737be8d11.png)
![sick](https://cloud.githubusercontent.com/assets/4345779/9325190/ba4ea526-4590-11e5-94df-520b877c4de9.png)
![sleeping](https://cloud.githubusercontent.com/assets/4345779/9325191/ba5ae21e-4590-11e5-83d4-e7738ee87cc2.png)
![speechless](https://cloud.githubusercontent.com/assets/4345779/9325192/ba5c9f0a-4590-11e5-90cb-4038d2642f72.png)
![star](https://cloud.githubusercontent.com/assets/4345779/9325193/ba5ca8ce-4590-11e5-9195-df783909e9a9.png)
![surprised](https://cloud.githubusercontent.com/assets/4345779/9325194/ba5eada4-4590-11e5-9f16-e5b2b652de86.png)
![tongue](https://cloud.githubusercontent.com/assets/4345779/9325195/ba60bc02-4590-11e5-86c9-320a3013baa8.png)
![wink](https://cloud.githubusercontent.com/assets/4345779/9325196/ba64191a-4590-11e5-88d8-bd2fa48928f5.png)

**Comment by CaMer0n** [comment]
Thanks! If you could generateXML and zip it all up and email it to me, that would be great! :+1:

**Comment by TealFox** [comment]
@CaMer0n , how do I do that? :) the generalXML part?

**Comment by CaMer0n** [comment]
Admin -> Emoticons -> Installed Packs ;-)

**Comment by TealFox** [comment]
Oh that's easy! :laughing:
