### ISSUE TITLE
tinymce, source code and welcome message

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#736]
I needed to insert text in welcome message via source code, because there are some divs, span etc.
So, I inserted this (only copy from html template)
![image](https://cloud.githubusercontent.com/assets/5429548/3988211/cb3040bc-28ad-11e4-85de-ac7adc3209a1.png)
After checking (close source code modal window and reopen):
![image](https://cloud.githubusercontent.com/assets/5429548/3988222/e1ee6e64-28ad-11e4-8949-1e886069b696.png)
Seems fine. No problem with saving.

Then I opened it and save again (update button):
![image](https://cloud.githubusercontent.com/assets/5429548/3988234/027a2fba-28ae-11e4-81b3-905e7e3ea196.png)

No querry error, 
![image](https://cloud.githubusercontent.com/assets/5429548/3988236/12686a54-28ae-11e4-915c-8853dfe6346c.png)

I did the same thing with news and pages and no problem.

**Comment by CaMer0n** [comment]
@Jimmi08 is this still a problem after the recent Tinymce changes?

**Comment by Jimmi08** [comment]
Yes. This maybe helps:
1. fresh install
2. welcome message:
- click on edit button, make no changes, save (update).
Probably correct result (although on other places are message No changes was done or something like that) - green message  (this works first time, I can't reproduce it, later I still got error message)
![image](https://cloud.githubusercontent.com/assets/5429548/5996815/ce70dd92-aab0-11e4-9699-a81efa36e961.png)

3. welcome message again
edit button, no changes, ok, save (update) 
![image](https://cloud.githubusercontent.com/assets/5429548/5996758/dba518a8-aaaf-11e4-90f0-92b25e8c115b.png)
After this I still got this error - when saving WM without real changes.
When I change something, green Successfully updated.

I don't think this is TinyMce related, it seems like wrong messages in welcome message area..
