### ISSUE TITLE
old news images not displaying properly

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#737]
My (old converted by upgrade) newspages use this format in the articles: /{e_IMAGE}newspost_images/image.jpg
this used to work ok, but now they get translated to //e_img/newspost_images/image.jpg
the // in the start of the url makes it not working.

i have no idea when this first appeared.

**Comment by CaMer0n** [comment]
@willem010 Can this one be closed now?

**Comment by willem010** [comment]
i no longer own the site where this was an issue, 
can't test it for you,

just mark it solved. 
(y)

**Comment by CaMer0n** [comment]
ok thanks
