### ISSUE TITLE
News seo - sef url issue

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#738]
sef url's containing html chars are no longer recognised

items with an ' in the title are translated by the browser to : 
sef url = Darkangel's-b-day-bash
href in article =:Darkangel%26%23039%3Bs-b-day-bash
results in a 404 error page.

similar issue on % and &

**Comment by CaMer0n** [comment]
@willem010 I did some work on the SEF converted a little while back. Is this still an issue for you?

**Comment by willem010** [comment]
works ok on my current sites.
