### ISSUE TITLE
news months menu - no language file/not translated + maybe fix

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#743]
News months menu use language file from blogcalendar_menu (good idea, by the way - to reduce language strings this way)
![image](https://cloud.githubusercontent.com/assets/5429548/4036365/1317ef08-2c99-11e4-965b-6bbdedc5ea14.png)
but plugLan function need different name of file:
![image](https://cloud.githubusercontent.com/assets/5429548/4036398/68fde332-2c99-11e4-938b-e7866eeebb81.png)
so to fix this, it's enough to rename file in language folder: from English.php to English_front.php (in blogcalendar_menu)

**Comment by CaMer0n** [comment]
@Moc is this one still an issue?

**Comment by Jimmi08** [comment]
Works. Thank you.
