### ISSUE TITLE
New user signup broken with latest git download...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#772]
When a new user signs up it ends up taking you to a shortcode source page instead of completing the confirmation...

**Comment by dimante** [comment]
latest git and cannot complete a signup again :-(

**Comment by CaMer0n** [comment]
@dimante What are the symptoms?

**Comment by dimante** [comment]
DOwnloading now.  I will let you know how it goes!

On Thu, Aug 20, 2015 at 11:54 PM, Cameron <notifications@github.com> wrote:

> @dimante <https://github.com/dimante> What are the symptoms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/772#issuecomment-133284898>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Ok so we had some forward progress.. It accepted the domain but upon submission the screen showed this alone:

Image file not found: 

And did not send the confirmation email..  So something is still broken.
-D-

**Comment by CaMer0n** [comment]
"Image file not found:" comes from the thumbnail handler. If you can provide login and ftp access as I mentioned above, I can try and see what is causing the problem for you.

**Comment by dimante** [comment]
I can give you a login to E107 but I would have to go through %#$#) trying
to open a hole in the firewall for it...  What's causing the problem is
something in one of the latest updates..  The process was working fine a
few git releases back..  Let me know if you want admin access to the E107
install -Or- (I am a programmer too) if you can point me in the right
direction I can look at things as well.  When this message is displayed the
user still gets created in the database and set to not verified but the
email is never sent so there is a shortcode somewhere or on the page itself
that when the image can't display it dies....  Regardless of the display of
a thumbnail the email confirmation should not fail as a result.  If you
want admin access to the install let me know and I will PM you the details
on the e107 site.

Thanks!
-D-

On Fri, Aug 21, 2015 at 11:51 PM, Cameron <notifications@github.com> wrote:

> "Image file not found:" comes from the thumbnail handler. If you can
> provide login and ftp access as I mentioned above, I can try and see what
> is causing the problem for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/772#issuecomment-133635037>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by CaMer0n** [comment]
Thanks @dimante. Yes, if you could send me a message via e107.org with some  e107-admin login details (with perms 0) that would be great. Then I can take a look around see what I can find. I take it you have sent test emails already via Admin -> Mail ?

**Comment by Moc** [comment]
@dimante Is this issue still present?

**Comment by dimante** [comment]
As of the latest GIT I am not having this issue anymore.
