### ISSUE TITLE
Online menu, newest user (cache?)

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#776]
Hi all,
I'm using the online menu in the sidebar and noticed a few little wacky things happening with it. Not sure if they're related or not, so putting in the one case for now...

1/ Neweset Member isn't newest...until e107 content cache is cleared.
I was testing signup as a new user/email activation, and after I activated my brand new user and logged in as them, Newest Member in online menu still listed the previous newest member.
Logged in as newest user:
![screen shot 2014-10-10 at 10 22 52 am](https://cloud.githubusercontent.com/assets/887725/4586333/aeee3834-5015-11e4-9e6c-acf48b1a3fc6.png)
Logged out/logged back in as me:
![screen shot 2014-10-10 at 10 23 41 am](https://cloud.githubusercontent.com/assets/887725/4586335/c743c052-5015-11e4-8e51-c0aa6edc4a65.png)
Confirmation that TestingChrome should be the Newest user from admin user list:
![screen shot 2014-10-10 at 10 23 55 am](https://cloud.githubusercontent.com/assets/887725/4586341/dbc44362-5015-11e4-9d76-b2701958fb40.png)
Tried hard refreshing, clearing my (browser) cache, etc. Manually deleted all cookies using Chrome inspector to be sure, too. 
It wasn't until I went into admin > Settings > Cache and emptied the e107 cache that it updated with the newest user's name...but then...(see 2/)
![screen shot 2014-10-10 at 10 26 01 am](https://cloud.githubusercontent.com/assets/887725/4586346/f622d368-5015-11e4-9269-80001e507b5c.png)

2/ Duplicate (occasionally triplicate) of same user logged in.
While testing 1/ I was logging out and in a lot as my test and my main accounts. Each time I re-logged in it added another version of me to the online menu. 
![screen shot 2014-10-10 at 10 25 08 am](https://cloud.githubusercontent.com/assets/887725/4586358/137c3864-5016-11e4-8c10-a233cae7db32.png)

Again, I tried deleting cookies/cache, and then the Content cache in cache management again; none of the above removed the extra instance of me, though at one point (while deleting cookies manually through Chrome inspector) it did remove one of the 3 instances of me eventually.
But even after I log out, it still shows two of me as being logged in:
![screen shot 2014-10-10 at 10 30 37 am](https://cloud.githubusercontent.com/assets/887725/4586364/31ac93a6-5016-11e4-9ae5-88437ef3167a.png)
This issue seems to be on some sort of timer, though. In the time it's taken me to write up this issue, it's now dropped me back down to one instance in the logged in menu. I realise this'll be a tricky one to troubleshoot/replicate :-/ let me know if you want me to do any more testing or provide any more info on it.

In case you need this info: I have Content cache enabled, System cache disabled, and my user tracking method is cookies.

**Comment by CaMer0n** [comment]
@Minnn , is this still an issue?

**Comment by Minnn** [comment]
Sorry, I can't test for a little while.@martasalek or @skcihmit would either of you be able to if you get a chance? The process to repeat is above.

**Comment by skcihmit** [comment]
I can test it this evening.

**Comment by skcihmit** [comment]
I couldn't get a duplicate logged in user to appear so that seems fixed.

When adding a new user it shows correctly straight away as being the newest user. Deleting the new user still keeps them as the newest user on that menu though. Clearing the cache still fixes this and the previous new user then becomes the newest user.
Banning a user also removes them from being the newest user without needing to clear the cache so that seems to work fine.

**Comment by CaMer0n** [comment]
okay, thank you!
