### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#779]
If you have several welcome messages for the same category of users, on page you will have rendered the title of the first welcome message and content of the first two welcome messages together ( all enclose in just one menu if enclose enabled ) and not all welcome messages with title and content, every message enclose in his menu one after another so such as normal. And another problem, I think, welcome messages that set "Enclose: Disabled" should still be closed in a "div" with a class different from the menu class in order to simple use a different style from the one used in menus.

**Comment by CaMer0n** [comment]
The default class was added.
