### ISSUE TITLE
Forum: Thread tracking

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#784]
Hi all,

I might just be blind here and I haven't been able to find any other issue logging this here, but the track thread option (allowing for any user to track any thread/be emailed when someone replies) isn't an option any longer, as far as I can see?
Enable tracking is checked in Admin > Content > Forum > Preferences, I'm running the latest from github and the Bootstrap 1.0 theme. 
I remember in the old e107 there was just a button at the top of each thread that let a user track it.

Cheers,
Min

**Comment by martyshep** [comment]
Hi experts, Any progress with this issue resolution?  I have same issue, my e107 v2 website does not allow tracking of forum threads.  If I add in the shortcode as mentioned I get same, it doesn't work correctly.

**Comment by CaMer0n** [comment]
@Minnn @martyshep @Moc This should be fully functional, but if you find an issue, please create a new issue.
