### ISSUE TITLE
plugin preferencies - not used preferencies are still in database

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#787]
I tested this with blank plugin, not with others.

After installation and saving settings, I noticed this:
![image](https://cloud.githubusercontent.com/assets/5429548/4689331/e09a7c7a-56b5-11e4-8e44-623dfda8443a.png)

Because I needed to check initial value from plugin.xml, I added this (there is mistake)

![image](https://cloud.githubusercontent.com/assets/5429548/4689336/1b520086-56b6-11e4-958a-dfdcfaf56ee9.png)

I corrected my mistake:
![image](https://cloud.githubusercontent.com/assets/5429548/4689339/3d17789a-56b6-11e4-91d3-cffa2401a142.png)

But after saving or saving with change there are still not used preferencies in database:
![image](https://cloud.githubusercontent.com/assets/5429548/4689342/78ada60e-56b6-11e4-83ed-05b15fa01ff5.png)

![image](https://cloud.githubusercontent.com/assets/5429548/4689347/83d5d9d4-56b6-11e4-9eec-2f53ca857ff8.png)

Is this should be this way?  Yes, when I unistall plugin  and reinstall again, it will be correct, so I can live with it.
Thanks

**Comment by CaMer0n** [comment]
We need to add "Delete plugin preferences" as an option during plugin uninstall. In the meantime, they are left there as a precaution.

**Comment by Jimmi08** [comment]
Checked with featurebox plugin. Prefs was emptied, so I am closing this. 
![image](https://cloud.githubusercontent.com/assets/5429548/14573115/49353f4a-0353-11e6-815b-676d3e61e461.png)
