### ISSUE TITLE
e107_core_media - suggestion

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#788]
Maybe there is another way, but it would be good to be able to set photo's order in gallery. Do you plan to add field order in core_media table?

**Comment by kreos** [comment]
hi,
can you help for this suggestion??
i need to organize the view of images  in all galleries
in order to sort them by name or other tags such as categories are organized by number
can you help me and all community?
thank you

**Comment by Jimmi08** [comment]
I am closing this because after time I think that this is not good solution.  I think that complex gallery plugin shouldn't be based on media manager tables, just to have images field that are using media manager.  Thanks for your time
