### ISSUE TITLE
menu/page - suggestion

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#791]
I can set tinymce off for all site, but it would be great if I can do it only for some menu or page. Tinymce sometimes messed source code and I need to insert clean html code in menu or page.  
Button to get off editor in menu editing would be nice.  
(I can set this off for all menus with rewritting type of field in admin area, but this has the influence on all menus)

**Comment by CaMer0n** [comment]
This button was added back, although TinyMce is working so well now, I don't see why anyone would want to continue to use bbcodes.
