### ISSUE TITLE
thumb.php  on page with gallery  

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#792]
Sorry, I am asking here because here I can insert pictures  easier way and this is probably problem in my localhost setting.
On my xampp installation I have e107 installation in sub-subfolder. Just now I updated database from production web plus image and media folders. 
Images in news are displayed correctly, but images from menus not.   But when I am editing menus, image is displayed correctly.
If this helps:
frontend: 
![image](https://cloud.githubusercontent.com/assets/5429548/4705895/66e8a84e-5880-11e4-822d-de499e4bcee3.png)
admin (image is there, image manager works)
![image](https://cloud.githubusercontent.com/assets/5429548/4705908/80b124ae-5880-11e4-8c3e-69b389bf7078.png)

Image in news has correct path:
![image](https://cloud.githubusercontent.com/assets/5429548/4705921/9c6611fa-5880-11e4-8071-4f7b0f0ecdce.png)

Thanks

**Comment by CaMer0n** [comment]
@Jimmi08 - is this still an issue after the recent TinyMce changes?

**Comment by Jimmi08** [comment]
I am not able to test it in short time. Closing this if I notice it in future, I will create new issue. Thanks
