### ISSUE TITLE
Downloads DOWNLOAD_LIST_NEXTPREV

### ISSUE THREAD

**Issue by e107bg** [e107inc/e107#793]
DOWNLOAD_LIST_NEXTPREV shortcode is not working
Downloads are inported from e107 v1.0.4

**Comment by CaMer0n** [comment]
@e107bg I'm unable to reproduce this. It seems to be working fine here.

**Comment by CaMer0n** [comment]
@e107bg wIth or without SEF Urls running?

**Comment by tgtje** [comment]
Imported download (upgrade v1 > v2 ) prev.next = showing
system (sitelink #download php )) reports sef url not available
(using sef on downloads does not make diff; however doubting sef urls are working)
![prevnext](https://cloud.githubusercontent.com/assets/1811857/7913854/401f0a98-0873-11e5-9958-c9f83bb0c859.jpg)

**Comment by Moc** [comment]
Closing due to the lack of feedback, please re-open if the issue is still present.
