### ISSUE TITLE
alt_auth plugin - problem with $dsn in PDO - not issue, only report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#794]
Hi, 
I just use alt_auth plugin - other db (mysql)
I needed to change $dsn variable hardway, because my hosting need it different way.

![image](https://cloud.githubusercontent.com/assets/5429548/4725381/065f2a64-5959-11e4-85ab-1f5ec5181eb5.png)

this is info from my hosting:
![image](https://cloud.githubusercontent.com/assets/5429548/4725403/357d604a-5959-11e4-9e74-2c58e061d8f3.png)

**Comment by Moc** [comment]
Just a reference so we know these two issues are linked: #84

**Comment by Jimmi08** [comment]
On new server alth plugin doesn't work at all. I am closing this because it's too old, I am not able to test this.

**Comment by CaMer0n** [comment]
There is a problem then. Re-opening.

**Comment by CaMer0n** [comment]
Closing this in favor of #1948
