### ISSUE TITLE
Files are not physically deleted after deleting from media manager

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#802]
Physical files are not deleted after deleting them from the media manager:

Steps to reproduce:
- Uploaded 2 new images, imported into the 'Common images' category.
- Selected both and used the batch action 'delete'. 
- Confirmed the delete
- Physical image files are still present in the e107_media/_hash_/images/_date_/ folder

Tested both on Windows and Linux installations.

**Comment by Moc** [comment]
Just tested this after updating from Github. Issue seems to be present still using the steps I provided above. Possibly the fix you created only takes care of deleting avatars? This report is related to images in general.

**Comment by CaMer0n** [comment]
Yes, perhaps a 'trash' folder is the best way to go for this.

**Comment by Moc** [comment]
Hmm maybe, not a huge fan of those 'trash' functionalities on other systems. Just seems like more clutter. 
In my opinion, for now it would suffice to just have them physically deleted after doing so from the media manager.
