### ISSUE TITLE
problem using ssl + normal protocol

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#805]
My server has both http and https, and for now i want to use both.
therefore i cant check the "use ssl" box as this makes all connections use ssl.

one of the problems i'm having is the (jq) scripts are always loaded over http
resulting in an error when my user is using https.

can you guys add a detection, and output the scripts using the correct protocol for the request?

(else i would have to copy all scripts to local server, disabling the jquery options all togeher. and load them manually .. )

**Comment by Moc** [comment]
There have been many changes with regards to http/https. If there are any outstanding problems, please open up a new issue.

**Comment by willem010** [comment]
works perfectly. thnx!
