### ISSUE TITLE
Download plugin: SEF URLs not working on sub sub cat.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#807]
suddenly my url's on the download page turned from /category/x/name to 
/e107_plugins/download/download.php?action=list&id=x
the sef urls can be browsed, they just dont show in the download subcat pages.

btw, voting problem on downloads (reported earlier #603 ) now not working for all pages.
(before just on not-sef )
i do notice myself reporting a similar url issue there, so probably related

**Comment by CaMer0n** [comment]
This has been rewritten. Please re-open if necessary.
