### ISSUE TITLE
New forum posts - green dots on the forum pages to indicate new posts

### ISSUE THREAD

**Issue by martasalek** [e107inc/e107#809]
e107 Version 2.0.0, last upgraded on 4/11/14

New forum posts (AKA green dots on the forum page). So, this feature has always been a bit... interesting (how many times did I log in on the old version of e107 to be greeted with a message like 'There have been 10 new posts since your last visit, and you have viewed 13 of them.' :)). Since the upgrade, I don't think I've seen a green dot light up since the first couple of days after we switched over.

I've had a quick poke around (only about half an hour's worth, so far), and have found a function in e107_plugins/forum/forum_class.php called forumGetUnreadForums.

Bearing in mind that my investigations haven't been thorough, what I think I understand about this function (if, indeed, it is the one that makes the dots go green) is the following:
- Every user has a user extended field which stores the list of threads they've viewed in the past. ('In the past' is nebulous - is is it in the past week? Month? Ever? Kind of leaning towards the latter unless you guys have a clean up script running to prune this list.)
- The function considers threads as unread for a user if they are not in this list of viewed threads. (And so, if you are not pruning thread IDs out of the list, this could be a bit of an issue.)
- The function then looks at the remaining threads, and lists those which were posted later than some global variable (AKA The Magic Date Number) called USERLV.

OK, my questions:
- Is this function actually the one which updates the green dots on the forum page?
- What is USERLV? The last time a user logged in? The last time they refreshed the page? The last time they went into a post? Either one of these are potentially an issue, really,  because just because someone's looked at a post/refreshed the main forum page/whatever does NOT mean that they've gone into all of the forums which posted earlier on. So green dots may be lost unnecessarily.
- When do you prune the list of viewed threads?
- Are subforums taken into account properly when working out which dots need to go green?

**Comment by CaMer0n** [comment]
Closing this as it has been replaced by bootstrap glyphs.

**Comment by martasalek** [comment]
Hi, 

By bootstrap glyphs, I think you mean you've upgraded the images for 'new posts'. Our issue was never about the images however; it was about the underlying functionality that recognised posts as 'new'. Can you confirm that you have reworked the algorithm that recognises new posts for a user before closing this issue? We can't upgrade to your latest forum php files at the moment (see issue #973), so we can't test ourselves. 

Cheers

Marta

**Comment by CaMer0n** [comment]
okay, have re-opened and will try to track it down in the code.

**Comment by martasalek** [comment]
Thanks!

**Comment by CaMer0n** [comment]
I found a typo. Will commit and please let me know if it helps.

**Comment by martasalek** [comment]
Thanks, Cameron. As we can't upload the current github plugin/forum files, I manually implemented the files you've changed. I then went and checked our live site - a user has made one new post this morning, and I noticed that the 'new post' dot beside the thread where the post had been made was activated. So seems things are working. Happy for you to close this, and I'll let you know if I notice any strange behaviour once more people post on our site.

Thanks for looking into this!

**Comment by martasalek** [comment]
Thanks, Cameron. As we can't upload the current github plugin/forum files, I manually implemented the files you've changed. I went to our live site and had a look - a user had just posted a comment in one of the forums and that forum's New Post dot had been activated. I went and had a look at the post, and the New Post signal then went away. She then posted something in a different subforum of the same parent forum but the New Post dot did NOT activate. So definitely your fix sorted out part of the problem, but there still seems to be an underlying issue with the logic.

We'll try and investigate further and give you more details.

**Comment by martasalek** [comment]
Update: One of our other admins has noted that the thread where the dot DID activate with a New Post signal was a new thread. When we post in existing threads, however, the New Post signal does NOT activate. Not conclusive, but perhaps something to direct your search?
