### ISSUE TITLE
Admin Area Plugin Section Blank

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#810]
Just installed e107 v2 (download latest files from GitHub here).

I installed a few Plugins (Statistic Logging, Metaweblog, Poll, RSS, and Tagwords). Now when I go to Plugin Manager, I get a blank page. I can get to Plugin Builder and Find Plugins by using the Back button, but Installed and Not installed display blank pages.

**Comment by CaMer0n** [comment]
@LaocheXe is this still an issue? Do you see anything if you enable 'debug' ?

**Comment by LaocheXe** [comment]
No, and I cant re-created it either, the website that it happened on is no longer up so could have been server side issue.

**Comment by CaMer0n** [comment]
okay, thank you!
