### ISSUE TITLE
tinymce jq error on frontend when logged in as admin

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#820]
When i log in to my site,  the front-end errors: 

(index):169 Uncaught TypeError: undefined is not a function
the line in question :
 
			$('.e-dialog-save').live('click', function(){
				
it stops my jq scripts running.

error does not appear when signed out.

**Comment by CaMer0n** [comment]
@willem010 @djbeater Could you please update from Github and retest? Thanks

**Comment by CaMer0n** [comment]
Did a search for .live and it appears it is no longer active. If you find it somewhere, please re-open. thanks
