### ISSUE TITLE
Where is latest documentation for better developing?

### ISSUE THREAD

**Issue by djbeater** [e107inc/e107#827]
#### I need to understand, better ajax loads in e107, sef url implementation and also how to make our custom list page: e.g.:
```
1. xpand_contact_admin.php?mode=supportnew&action=list
```
#### and
```
2. xpand_contact_admin.php?mode=supportall&action=list
```

#### Is there way to do like this, but also display as action list?
```
1. xpand_contact_admin.php?mode=support&action=listnew
```
#### and
```
2. xpand_contact_admin.php?mode=support&action=listall
```

**Comment by nlstart** [comment]
https://github.com/e107inc/e107/wiki/Development-Guide
