### ISSUE TITLE
alpha 2 upgrade database update

### ISSUE THREAD

**Issue by palwalrus** [e107inc/e107#830]
How many times will the database update run? Is there any way I can check progress. I have clicked the update tab about 50 times now and it still says it is functioning correctly and the query stats vary slightly each time suggesting they are doing different work, but there is no end in site. It will not let me continue on to add additional/missing core files until this step completes.

**Comment by palwalrus** [comment]
What I really need to know is what the e107_trackback table definition looks like in v2 alpha 2, then I can correct it manually if need be.

**Comment by CaMer0n** [comment]
Please check the e107_core/sql folder for the table creation details.

**Comment by SecretR** [comment]
SQL parser routine needs general upgrade on this matter - index order doesn't really matter. In fact field order is not important as well :smile: 
Additionally, I'm not really sure if INNODB is proper handled (including foreign keys).

**Comment by OliverGeist** [comment]
I guess I've got the same problem as palwarus described before. But the Debugger does not seem to work in FF 35.0.1 anymore? I installed e107 Debugger 1.2 but got no menue item or any reaction on my website for it.

**Comment by CaMer0n** [comment]
It works in FF 35.0.1 - you may need to customize the toolbar to see it.

**Comment by Jimmi08** [comment]
Confirm it. I use it only in Firefox, version 35.0.1  has no problems.

**Comment by CaMer0n** [comment]
@palwalrus The definition is in e107_plugins/trackback/trackback_sql.php  - if someone upgrading can post a database structure dump of the trackback table, that will help us.

**Comment by OliverGeist** [comment]
I'm not quite sure, if you meant the content of the file "trackback_sql.php" here it is:

CREATE TABLE trackback (
  `trackback_id` int(10) unsigned NOT NULL auto_increment,
  `trackback_pid` int(10) unsigned NOT NULL default '0',
  `trackback_title` varchar(200) NOT NULL default '',
  `trackback_excerpt` varchar(250) NOT NULL default '',
  `trackback_url` varchar(150) NOT NULL default '',
  `trackback_blogname` varchar(150) NOT NULL default '',
   PRIMARY KEY  (`trackback_id`),
   KEY `trackback_pid` (`trackback_pid`)
) ENGINE=MyISAM AUTO_INCREMENT=1;

**Comment by CaMer0n** [comment]
Thanks. Actually, what I need is to see the database structure in phpmyadmin and see how it differs from that file (trackback_sql.php)

**Comment by OliverGeist** [comment]
Although I was not able to find a table called TRACKBACK I can give you a other example and further information.

-- phpMyAdmin SQL Dump
-- version 4.0.7-rc1
-- Server Version: 5.5.41-0+wheezy1
-- PHP-Version: 5.4.36-0+deb7u3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `e107_admin_log` (
  `dblog_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dblog_type` tinyint(3) NOT NULL DEFAULT '0',
  `dblog_eventcode` varchar(10) NOT NULL DEFAULT '',
  `dblog_datestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `dblog_microtime` int(10) unsigned NOT NULL DEFAULT '0',
  `dblog_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `dblog_ip` varchar(45) NOT NULL DEFAULT '',
  `dblog_title` varchar(255) NOT NULL DEFAULT '',
  `dblog_remarks` text NOT NULL,
  PRIMARY KEY (`dblog_id`),
  KEY `dblog_datestamp` (`dblog_datestamp`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=183 ;

**Comment by CaMer0n** [comment]
Thanks, it's specifically the trackback table that I need. Someone who had it installed in v1.x.

**Comment by chory** [comment]
Thanks OliverGeist.
This work for me.
CREATE TABLE trackback (
trackback_id int(10) unsigned NOT NULL auto_increment,
trackback_pid int(10) unsigned NOT NULL default '0',
trackback_title varchar(200) NOT NULL default '',
trackback_excerpt varchar(250) NOT NULL default '',
trackback_url varchar(150) NOT NULL default '',
trackback_blogname varchar(150) NOT NULL default '',
PRIMARY KEY (trackback_id),
KEY trackback_pid (trackback_pid)
) ENGINE=MyISAM AUTO_INCREMENT=1;
