### ISSUE TITLE
search.php 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#835]
I use /page/book-title/chapter-title/page-title SEF URL and Aliases for page. 
This 
$res['link'] = rawurlencode(e107::getUrl()->create('page/view', $row, 'allow=page_id,page_title,page_sef,page'));

has result:

myaliasforpage/view?

in search results.

**Comment by CaMer0n** [comment]
thanks, and can you confirm that the page has a SEF value?

**Comment by Jimmi08** [comment]
I am sure, I use the book/chapter/page-title SEF URL and aliases for page. The same problem is with gsitemap plugin too. The query has no information about book's  and chapter's sef url... 

https://github.com/e107inc/e107/issues/834
