### ISSUE TITLE
Extended User Fields - regex validation code

### ISSUE THREAD

**Issue by skcihmit** [e107inc/e107#837]
Hi,

I just tried to add an extra field to my user signup that requires them to enter a specific string by using the regex validation code. Effectively #^human$#i 
I tested it and anything I type gets passed without the regex failure text appearing and registers them.

**Comment by CaMer0n** [comment]
I'm sorry, I am unable to reproduce this problem. I entered the regexp that you supplied and it triggers an errors on submit as intended.

**Comment by skcihmit** [comment]
Hmm ok, thanks for looking into it. Can you tell me what values you used when setting up the extended field for this? I'll try again with the settings you use (although I've tried it a few different ways by now). Thanks.
