### ISSUE TITLE
Feature Box > Preferences

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#839]
I go to Feature Box > Preferences and only see a drop down menu of Featurebox Menu Category and a Save button - I don't know if this was intended or not. But doesn't show anything else to change in that area.

**Comment by CaMer0n** [comment]
It is correct. Were you expecting something else in particular?

**Comment by LaocheXe** [comment]
Change picture/video placement/alignment, Change placement of the Title, change Title font size, change type of font might be nice but not needed at all. 

Trying to set up the site to look close to what e107.org has (site is in the works, will replace our old site) - http://site1.natotaskforce.com

So was hopping to add the good looking stuff for the image slider on top of the site like e107.org has.

**Comment by CaMer0n** [comment]
Thanks for the feedback. I believe most of those changes can be done using in the theme or with a custom template.  Take a look at e107.org's stylesheet: 
http://e107.org/e107_themes/e107_2014/style.css

**Comment by LaocheXe** [comment]
Well lex question, how to get the < ... > that is being used (Arrows buttons)

**Comment by CaMer0n** [comment]
They usually appear by default. Here's the corresponding html: 

    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
