### ISSUE TITLE
User Settings / Extended User Fields

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#840]
I went in and added a few custom user fields (date of birth, gender, etc) plus some of my own created - I go so I can test it and get a message: System Information - Settings updated and saved into database.

But on the usersettings.php the fields are still empty - I went and added a Real Name, and tried to select a user Class and hit the Save, same message but the user class isn't selected. Real Name was saved, don't know how to check error logs. I disable some fields and tested it again but no go, I was able to upload an avatar and it saved.

In the admin area I selected a user to edit, went to the extended section and added bogus info for a user and hit the save and it saved.

Using Bootstrap 3, using the Jumbotron (sidebar-right) for the usersettings.php

**Comment by CaMer0n** [comment]
Which fields are saving and which are not? Would you say that it's the custom extended fields (your own ones) that are not saving?

**Comment by LaocheXe** [comment]
Correct plus the one already provided by e107 (birthdate etc). it would not save the user classes selected (if you are main admin) and every thing under that.

I went into the database and checked out the user_extended table and did not find user_extended_id (1 which is main admin account), went and insert it via phpmyadmin and added one of the custom extended custom fields and am now able to edit the full profile area.

I went and activated the birthday, gender, and time zone fields and they now save too.

**Comment by CaMer0n** [comment]
is your site an upgrade or a fresh install?

**Comment by LaocheXe** [comment]
Was fresh install

**Comment by Jimmi08** [comment]
Comfirmed. If you add new fields, then add new user, it works (you can then add next fields), but because admin user (ID 1) is created before you add first ext. field, data are not saved - there is no record in database for id 1. 
Latest github (today)
