### ISSUE TITLE
e107 2.0 Alpha 2 - User Settings & Profile with activated friendly URL Configuration do not work

### ISSUE THREAD

**Issue by Digioso** [e107inc/e107#841]
If you activate friendly URL Configuration for Users the 'User Settings' and 'User Progile' pages are no longer accessible.

With Default the link is: http://www.yourwebsite.com/usersettings.php
With Friendly it's: http://www.yourwebsite.com/user/settings?id=1

And Profile:

Default: http://www.yourwebsite.com/user.php?id.1
Friendly: http://www.yourwebsite.com/user/digioso

The friendly links do not work and result into error 404.

**Comment by CaMer0n** [comment]
I can't replicate the 404 errors. Are you sure the contents of e107.htaccess are inside your .htaccess file?

**Comment by Digioso** [comment]
Ah, nope, it wasn't. I didn't check the e107.htaccess file before. Thanks. :)
Maybe it should be explictly mentioned in the URL profiles that you have to ranme that file to .htaccesss .

**Comment by CaMer0n** [comment]
It should auto-rename during installation and if the fails it will normally notify you at the time.
