### ISSUE TITLE
textparse & e107_Compat_handler.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#844]
question, did you guys replace textparse class and the e107_Compat_handler.php? 

Also is there a wiki that gives information to devs on what has changed in the new version?

**Comment by CaMer0n** [comment]
Yes, these were only used for very old code. (pre 0.6 if I remember well). 
At the moment we only have developer documentation on e107.org. If there is some particular information that you feel should be there, please paste it here below. thanks

**Comment by LaocheXe** [comment]
So next question is, what can I use to replace the textparse class? currently working on old plugin and getting caught up at $tt=new textparse;

**Comment by Moc** [comment]
```php
$tp = e107::getParser();
$tp->toDb(.....) 
```

e.g.
```php
$tp->toDb($_POST['field_choices'][$key])
```

The code that you are using above is heavily outdated, used in 0.6 and removed in v2.

**Comment by LaocheXe** [comment]
That seems to work, thanks for the help you two.

**Comment by CaMer0n** [comment]
:+1:   :-)
