### ISSUE TITLE
Call to undefined method e107forum::insert()

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#845]
I don't know if this is right or not, but getting an error Call to undefined method e107forum::insert()

code was: 
$survey_forum->thread_insert($row['survey_name'], $thread_text, $row['survey_forum'], 0, $poster, 1, 0);

now

$survey_forum->insert($row['survey_name'], $thread_text, $row['survey_forum'], 0, $poster, 1, 0);

but no change. 

I tried this:
$survey_forum->threadAdd($row['survey_name'], $thread_text, $row['survey_forum'], 0, $poster, 1, 0);

and get no error but does not post in the selected forum post, any Idea?

**Comment by CaMer0n** [comment]
The survey plugin will need to be updated to use threadAdd();
