### ISSUE TITLE
Plugin Links after User Login

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#846]
Question: I wonder if I make a plugin that will/can add/make a link in the area where the drop down menu (where you can select Settings or Admin Area) with out editing any core files, and if not can this be added as a feature to e107 v2.0x?

**Comment by CaMer0n** [comment]
What kind of link would you put there?

**Comment by LaocheXe** [comment]
Well for starters, if I build a teamspeak plugin - I would add a link to join team speak (ts3server://ip:port=usernick={E107 User DisplayName}

Or if I have a custom area that is kinda of like Admin area but not the admin area - the plugin would put a link either above or below the Admin Area link in that field.

**Comment by LaocheXe** [comment]
Okay lets point this out to hopefully make what I am asking about easier to know.

With the new method of making plugin's there is a e_user.php

Which you know adds stuff to the user profile (Forums adds Forum Post Count).

maybe adding a e_login.php or something else (something like the name you call that login menu) to add such links to it. Would that be possible to do in the future? Or is that something we can do just in a different way?

**Comment by CaMer0n** [comment]
The login menu in the bootstrap3 theme is inside theme_shortcodes.php - so there's nothing preventing you from manually adding that link inside your own theme.

**Comment by LaocheXe** [comment]
Okay

**Comment by Jimmi08** [comment]
Hi, look at e_loginbox.php (used in login_menu plugin)

**Comment by CaMer0n** [comment]
Wow, I didn't even know about that one. Looking at the code it is in dire need of an upgrade to v2.x specifications.
