### ISSUE TITLE
TinyMCE inactive after Jan 31 update

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#849]
I downloaded the latest zip from github and applied the database upgrade. Subsequently I cannot edit any existing article or enter any text to compose a new article.

I enclose an image of an article I am trying to edit, there is no content appearing.
![tinymce](https://cloud.githubusercontent.com/assets/7886491/5990311/6a96ba04-aa0f-11e4-940c-8d69f781ed3a.png)

**Comment by CaMer0n** [comment]
@NZCyrus There was a file missing, however it shouldn't have stopped it from functioning. Are you using any custom tinymce templates? Please clear your browser cache completely and try again. Thanks.

**Comment by NZCyrus** [comment]
I cleared my browser cache in Firefox and Chromium but the above issue remains. I'm not using any custom tinymce templates.

**Comment by NZCyrus** [comment]
After uploading that css file it didn't work. However I noticed a file there called e_meta which I removed.
After that it worked.
Thanks.

**Comment by oxigeno2** [comment]
Confirm same problem after upgrading

**Comment by NZCyrus** [comment]
Are you checking out with subversion or downloading the zip? I download the zip and apply updates to files that have changed since my last upload every week or so. In doing so, I noticed a file that wasn't in the download called e_meta.php. I deleted this file and it works for me. I uploaded the latest file editor.css as well of around five hours ago.

**Comment by oxigeno2** [comment]
Moreover, does not work in news and articles, tab EXTENDED and  MENU!

Complete new installation.

Upload older plugin TinyMCE is not the solution still did not work. The problem somewhere else.

**Comment by oxigeno2** [comment]
Sorry for the misinformation, upload older plugin + erasing cache - problem is solved

**Comment by oxigeno2** [comment]
The problem is e_meta.php, deleted and reinstalled TinyMCE, the problem is solved. It would need delete the file when upgrading. (in new installations there I forgot to file e_meta.php:-()
