### ISSUE TITLE
admin_ui and where query - question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#851]
Hi,
I use copy of admin/image.php for gallery. When I use 
protected $listQry   = "SELECT * FROM #core_media_cat WHERE media_cat_owner = 'gallery' "; 
filtering will stops. 
(SQL is correct / checked in debug mode, but nothing is displayed)

You don't use $listQry in image.php and filtering works. I tested to use $listQry there and filtering stops too, so it's not problem with my copy.  

How to set in admin_ui query with WHERE condition without breaking filtering function?
Thank you

**Comment by CaMer0n** [comment]
When you say 'filtering' do you mean the drop-down filter or a search-text ?

**Comment by Jimmi08** [comment]
Oh, sorry, I meant searching text (searchquery). In media manager there is no field with 'filter'=>true. I added it for gallery_owner to test it. With $listQry  both, searching and filtering will stop to work.
But query is correct, different, but no error .
