### ISSUE TITLE
install process

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#852]
When you click in stage 7 on Continue button, process is going, but button is still available for click, you click again, installation is succesfull, but you get result: (about htaccess)
![image](https://cloud.githubusercontent.com/assets/5429548/5996839/6892a2d4-aab1-11e4-8cfa-782fefefecb9.png)

And you can't go back in install process, but I think I already make a issue from this.

**Comment by CaMer0n** [comment]
Yes, this only happens if .htaccess already exists or e107.htaccess cannot be renamed.

**Comment by Jimmi08** [comment]
Yes, . htaccess was created after first click on button Continue, and when you click second time, it try to create it again and the message appears.  Is there any check that installation process is already running? I can live with it, I know that everything is ok regardless this message.
