### ISSUE TITLE
page comments - should they works this way?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#856]
Clean install, no custom changes, SEF url enabled.

I post comment. OK. I click on reply, textarea appears, click again, next textarea  etc

![image](https://cloud.githubusercontent.com/assets/5429548/6028399/8cc99b74-abe9-11e4-8b26-00546a5b0391.png)

**Comment by Jimmi08** [comment]
Maybe this is related, but comment_class.php has some bootstrap2 classes (without adding BT3 classes)

![image](https://cloud.githubusercontent.com/assets/5429548/6030098/4fd4bda0-abf5-11e4-8375-86ebac75465e.png)

and span12 I saw somewhere too...

**Comment by CaMer0n** [comment]
Nested comments are enabled?

**Comment by Jimmi08** [comment]
Yes, but it seems more as javascript problem (it's on click..)
![image](https://cloud.githubusercontent.com/assets/5429548/6047312/30b2992e-aca9-11e4-82ea-005fbeb964c5.png)
