### ISSUE TITLE
search.php  page, not working + FIX (e_search.php)

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#857]
When you add page to searching, there is empty list of chapters:
![image](https://cloud.githubusercontent.com/assets/5429548/6045589/b3a81718-ac9b-11e4-8186-70d80d382612.png)

The reason is missing field chapter_visibility  in __construct(), but later there is check for access.

![image](https://cloud.githubusercontent.com/assets/5429548/6045622/ff731c88-ac9b-11e4-92c7-c4f343a46e09.png)

And weird thing - you need to save search setting in admin area (without any change) to add page in the searching list)

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please re-test?

**Comment by Jimmi08** [comment]
I labeled it with fix and it seems that I didn't insert it. Sorry.  
Test:
Fresh install: - no pages
![image](https://cloud.githubusercontent.com/assets/5429548/6076412/70dc5ae0-ade3-11e4-882c-809c334e98a8.png)

Admin area:
![image](https://cloud.githubusercontent.com/assets/5429548/6076416/7e54f218-ade3-11e4-9043-89ac1192c159.png)
Nothing other, then saving:
![image](https://cloud.githubusercontent.com/assets/5429548/6076424/8a7d88d4-ade3-11e4-978f-d88c2df6effe.png)
Result:
![image](https://cloud.githubusercontent.com/assets/5429548/6076430/9ca53f02-ade3-11e4-987c-07f22ffc7bf3.png)

Fix (I was sure that I wrote about it, sorry) - missing field chapter_visibility in select (there is test of this field later and it is NULL)
![image](https://cloud.githubusercontent.com/assets/5429548/6076444/ced4e3b0-ade3-11e4-91e9-0d1c0f6db38b.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/6076455/e658c2f4-ade3-11e4-9e8f-94661ae1dbf4.png)


Second problem is that page is not in default list, but it should be according search setting in admin area.

**Comment by CaMer0n** [comment]
Thanks @Jimmi08 . If you submit a pull request, I'll commit it tomorrow morning. (for me)
