### ISSUE TITLE
Comment's behaviour question

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#861]
When I delete comment, it disappeared, but then it's visible with text blocked by admin.  
Before:
![image](https://cloud.githubusercontent.com/assets/5429548/6065971/9841d5c6-ad69-11e4-9d4f-b009e1cc2f19.png)

after click on delete button on first comment (only second comment is visible)
![image](https://cloud.githubusercontent.com/assets/5429548/6065978/a4ccb6b2-ad69-11e4-8d5e-8629e09850c5.png)

after refresh page:
![image](https://cloud.githubusercontent.com/assets/5429548/6066017/001891e4-ad6a-11e4-905a-a43581171675.png)

I've never used comment system before, so maybe it should work this way.  I can live with this, only admin sees 'deleted' comments.

**Comment by Radzi0** [comment]
Yes it should work this way. 

Admin Area > Comments Manager > Manage

You can delete the 'deleted' in the comments manager, or restore them.


Its a nice improvement over what was in v1.0, back in the days you were only allowed to delete a comment or to approve it to be displayed.

**Comment by CaMer0n** [comment]
Indeed

**Comment by Jimmi08** [comment]
Thanks, new for me.
