### ISSUE TITLE
Welcome Message Disable

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#868]
With new version of e107 plus using the bootstrap 3 v1.0 - I disable the welcome message in the admin area and it still is displayed on the front page with an issue - it is displayed wrong and messes up the front page.
 
Disabled 
![untitled-1](https://cloud.githubusercontent.com/assets/5818022/6083789/0ac422fc-adf1-11e4-8841-df721c2bf316.jpg)

Enabled
![untitled-2](https://cloud.githubusercontent.com/assets/5818022/6083796/16f163b4-adf1-11e4-92ce-330f07c0402d.jpg)

**Comment by CaMer0n** [comment]
You disabled welcome-messages using tablerender(). If you wish to disable the welcome-message, delete it, or set the userclass to "No One (inactive)"
