### ISSUE TITLE
Banner plugin display with more than one banner

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#871]
With the Banner menu set to show 'All selected campaigns in one single menu' there is no spacer applied between each banner to separate them.

![banner_display](https://cloud.githubusercontent.com/assets/7886491/6094060/069e6352-af7e-11e4-9f8c-a1e0bca644a7.png)

**Comment by NZCyrus** [comment]
The space is now displaying but the image displayed is stretched to 800 and looks distorted. The original size uploaded and selected from Gallery is not the same.

![adthumb](https://cloud.githubusercontent.com/assets/7886491/6095763/016d0fca-afd1-11e4-8f14-d44c977141e7.png)

**Comment by CaMer0n** [comment]
@NZCyrus Could you please send me a link?

**Comment by NZCyrus** [comment]
@CaMer0n http://www.promotiondata.com

**Comment by CaMer0n** [comment]
@NZCyrus Thanks! If you don't have higher-resolution banners (recommended for responsive design), then you can modify the template and adjust it to the size you wish. (copy the template from e107_plugins/banner to your theme's template folder.. ie. e107_themes/your-theme/templates/banner/banner_template.php

**Comment by CaMer0n** [comment]
The part to modify is:

     {SETIMAGE: w=800}

This sets the image-resizing for the menu.
