### ISSUE TITLE
Tag display page image

### ISSUE THREAD

**Issue by NZCyrus** [e107inc/e107#872]
When clicking on a tag for a news item it takes one to the heading of that article (not a list of articles under that tag as the database is not being updated #699)

The display includes a blank image. How does one (a) remove this placeholder image (b) include an image there if one wants to?

![tag_image](https://cloud.githubusercontent.com/assets/7886491/6094082/43240e48-af7f-11e4-82b5-10c32b02d048.png)

**Comment by CaMer0n** [comment]
You need to increase the value for this setting in Admin-area -> News -> Preferences: 

    Limit for News-Listing Pages

And add an image to the news item in one of the 5 spaces provided. .
