### ISSUE TITLE
How can I get User ID by Session ID? Missing session table, and the schema not contains user_id field.

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#874]
How can I get User ID by Session ID in e107 v2? I browsed source code, and I found the class called 'e_db_session', but I didn't find session table in the database. I think it's not implemented yet. When will it be implemented? And the field 'session_data'  will contain the User ID of logged in user, or not? How will I able to connect User ID with Session ID? :)

I have a Node.js server, and I try to integrate it to e107, and I try to validate user with an authToken, which is MD5(session_id())... I put this authToken as a JS option to the frontend, and the JS (which handles the connection to Node.js server) sends this token to Node.js. Then, of course, I need to validate it, so Node.js server sends this authToken to the (e107) backend, and in a validation callback I try to find User ID out, if the authToken is matching one of the MD5() values of session_id field in the session table, finally I need to return with user_id to Node.js server...

So, I need a solution, how to find out that whatever the session is alive, and which user belongs to. The best solution would be the session table, but it's missing from my database (missing implementation or upgrade path?), and of course, it should be contain the user_id corresponding to the session or 0 for anonymous users.

This kind of solution is implemented in other systems too, e.g:
* Drupal: [database schema](https://www.drupal.org/files/Drupal8_UPsitesWeb_Schema_10-19-2013.png) (sessions table)
* Joomla: [database schema](http://www.torkiljohnsen.com/wp-content/uploads/2006/04/joomla_15_database_schema.png) (jos_session table)

**Comment by SecretR** [comment]
e107 don't have something which it doesn't need :)
However, it's flexible enough to give you everything you'd need. Implementing e107 user session table is easy like that:

1. Create simple plugin - new folder in e107_plugin folder (lets say in our case 'usersession') containing only plugin.xml, usersession_sql.php and e_module.php. If you are not familiar with plugin.xml structure, use the plugin builder in e107 administration section, or just copy/paste/modify one from core plugins. 

2. Fill in your usersession_sql.php like this - https://gist.github.com/SecretR/7625163589f98aae02eb

3. Here is what you'd need in e_module.php - https://gist.github.com/SecretR/87116bc53f56056415be
Take a closer look at the system event triggers to get the whole idea of the code in my example - http://wiki.e107.org/index.php?title=Core_event_trigger

4. Install your plugin. Done. Now do in your app evnironment a simple 
```sql 
SELECT * FROM e107_user_session;
```

DON'T FORGET the cron task you'd need , mentioned in the e_module gist, i.e.:
```sql
DELETE FROM e107_user_session WHERE user_last_seen <= (UNIX_TIMESTAMP() - 6*60*60);
```

**Comment by lonalore** [comment]
Thank you for your answer, this is exactly what I need! :) However, implementing this session table handler in the core would be more practical, or not? Suppose that multiple plugins use their own session table implementation... I think it will not be a good influence on performance.

But, thank you for your codes, I'm going to use them in any case.

**Comment by SecretR** [comment]
There is a small chance we go for core plugin "usersession" if this is much asked feature. But still, plugin, not a built-in core feature.
