### ISSUE TITLE
gallery plugin - social sharing - questions

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#875]
I hope you understand what I am asking... I need more advice than you change something in code.

Ok, on my site I use gallery. (http://kizi.sk/gallery) - (first albums have photos)
1. there are no og:tags and when I use link in FB  (manually inserted), there is no picture. 
I suppose that I should use this: e107::meta('og:title','')
e107::meta('og:type','');
e107::meta('og:description','');	
e107::meta('og:image','');
but where should I put them? In gallery.php in each function? (listCategories(), showImages()) ?

2. prettyPhoto gallery
- I wasn't able to find where are setting for social sharing (tweet and fb buttons). Tweet works fine (although share link for all category, not for only one image), but fb button doesn't (no counting).  Where to look to check this?

3. is there any way how to get url for one picture? 

Thank you. I have done with testing administration, everything works, now I am on frontend, but without understanding how it should work, I am not able to tell if there is issue or not.

**Comment by CaMer0n** [comment]
At the moment it is sharing a direct link to the image. To use custom og: meta tags will require adding a custom page just for displaying. ie. how it would function if prettyPhoto was not there.

**Comment by Jimmi08** [comment]
Yes, I found it. With deeplinking true I can get url for image in prettyPhoto, but it's ignored by social buttons from PP itself.   Wrong decision to use gallery for this. Thank you

**Comment by CaMer0n** [comment]
We might consider an option to use prettyPhoto or not.

**Comment by Jimmi08** [comment]
This is prettyPhoto problem, I found it on some forums, they added deeplinking to get url image, but they ignored this url in social buttons. And facebook button never worked. And if you add new image in gallery, your url image will change in prettyphoto.

I am able to add media_sef url,  change link in gallerythumb, but I am not able to add next level to gallery sef-url. 
I could create my own plugin for this, but again, there is no documentation how solve sef-urls (e_url is not enough,  gallery plugin use only one level, page uses 3 levels, news has to much legacy...   At worst I will go for old good htaccess and custom page for image.  

And I just found that with e_rss I can't set images (you can do it only for news)...

**Comment by Jimmi08** [comment]
Hi, only let you know. I bought another gallery and I was able to implemented it on latest github. Still learning more about setting...  Thank you for everything.
![image](https://cloud.githubusercontent.com/assets/5429548/6106893/b75c9622-b065-11e4-9e5d-1414de08403a.png)

**Comment by Jimmi08** [comment]
Just let you know.  Facebook ignores sharing url with # in it (You can use %23 instead of it but then you need RewrileRule to accept this url (not 404), so it's important to have possibility having url/page for image. 

Gallery I used needs to be created files (images) with .jpg (or png etc). When you use thumb, there is nothing like this, but after I added it in thumb.php, it works (and thumb.php still works too, nice done).  

But I think you can't use image url with thumb.php in og: image tags.
