### ISSUE TITLE
gallery plugin - and e_PAGE

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#876]
What replase current url in version 2 (when I want to use e_PAGE, it's not correct in all gallery plugin)
 gallery index:
![image](https://cloud.githubusercontent.com/assets/5429548/6105844/063211c8-b05c-11e4-8841-7291cc3d9039.png)
gallery list:
![image](https://cloud.githubusercontent.com/assets/5429548/6105858/396847ba-b05c-11e4-95f5-e5906f674351.png)

After setting SEF URL on:
![image](https://cloud.githubusercontent.com/assets/5429548/6105886/77a69004-b05c-11e4-89a4-d137d6bccb56.png)

![image](https://cloud.githubusercontent.com/assets/5429548/6105890/8a8d1936-b05c-11e4-9448-7a7b9bc11045.png)

And I noticed that in gallery list there is question mark in url for gallery index:
![image](https://cloud.githubusercontent.com/assets/5429548/6105903/b5a1403e-b05c-11e4-8bcf-4fe2ae92df84.png)

**Comment by SecretR** [comment]
`e_REQUEST_URI` - absolute page URL (including GET query)
`e_REQUEST_SELF` - full URL (including http(s):// )  without GET query

**Comment by Jimmi08** [comment]
Thank you, I needed to test if you are on pages with gallery plugin. Reason? I dislike to include gallery scripts (and css) in all site, when you need them on one part.  I solved this with using THEME_LAYOUT (galllery has its own layout) for now.
