### ISSUE TITLE
Feature request: event triggerings in core plugins (e.g: forum, pm, chatbox_menu)

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#877]
I didn't find any event triggerings in core plugins, but I really need them. :( I want to register callback functions to different kind of event triggerings, for example: I would like to notify users (clients with active session, using Node.js), if one of them get a new pm. Or I would like to update chatbox contents after a new message has been posted. But I can not do this without hardcoding my modifications into core (plugin) files. I don't understand why these events are missing from these core plugins, because this would be the basis for that, (core and custom) plugins can get in contact with each others.

**Comment by lonalore** [comment]
some suggestions:
* event after new private message has been sent (pm)
* event after private message has been read (pm)
* event after new forum post has been sent (forum)
* event after new forum topic has been created (forum)
* event after new message has been sent (chatbox_menu)
* event after new content has been published (news)
... etc. :)

**Comment by CaMer0n** [comment]
Thanks for the request. You may submit a pull-request for this. Just use the following naming schema: 
user-pm-sent, user-forum-thread-created, user-pm-read, user-forum-topic-created, user-chatbox-posted. You should find news already.

**Comment by CaMer0n** [comment]
More info here: http://e107.org/developer-manual/classes-and-methods#events

**Comment by Moc** [comment]
Please use the terminology 'forum topics' rather than 'forum threads'. Thanks! :)

**Comment by lonalore** [comment]
So it will be good? :)

**Comment by CaMer0n** [comment]
Thank you @Moc for that important point. Nicely done @lonalore - changes merged! :-)

**Comment by lonalore** [comment]
Thank you! :)

**Comment by Moc** [comment]
Re-opened for documentation reminder (I'll do it asap)
