### ISSUE TITLE
How to collect return values from registered callback functions on event triggering?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#880]
I would like to collect return values from the registered callback functions on event triggering. Is it possible?

If I trigger my own event, for example:
$handlers = e107::getEvent()->trigger('nodejs-message-handlers', $data);

Is it possible to collect return values into $handlers from the registered callback functions? Or is it possible to pass $data variable as reference? I hope you can understand this! I'm not sure I've explained it in the clearest way ... :/ I would like to provide the ability in my plugin to use custom handlers are defined in other plugins... o.O

**Comment by lonalore** [comment]
Oke, I did a test. I triggered an event like:

```
/**
   * Get a list of javascript handler files.
   */
  function get_js_handlers() {
    $handlers = array();
    $handlers = e107::getEvent()->trigger('nodejs-js-handlers', $handlers);
    return $handlers;
  }
```

then I registered two callbacks with return values to this event like:

```
// Register events.
$event = e107::getEvent();
$event->register('nodejs-js-handlers', 'nodejs_notify_js_handlers_callback');
$event->register('nodejs-js-handlers', '_nodejs_notify_js_handlers_callback');

/**
 * Node.js Javascript handlers.
 *
 * @param array $handlers
 * @return array $handlers
 */
function nodejs_notify_js_handlers_callback($handlers = array()) {
  $handlers[] = array(
    'plugin' => 'nodejs_notify',
    'file' => 'js/nodejs_notify.js',
  );

  return $handlers;
}

/**
 * Node.js Javascript handlers.
 *
 * @param array $handlers
 * @return array $handlers
 */
function _nodejs_notify_js_handlers_callback($handlers = array()) {
  $handlers[] = array(
    'plugin' => 'nodejs_notify',
    'file' => 'js/nodejs_notify.js.test',
  );

  return $handlers;
}
```

...and I always get the array from the first callback, but the second one is not called by event triggering. :/ 

I checked the trigger method in event_class.php, and I found a break in the foreach... it breaks the loop if there is return value... I don't understand this, in my opinion we should collect retrun values of callback functions into an array, and finally we can check array is empty or not, instead of the isset($ret).

**Comment by lonalore** [comment]
Can I modify the trigger() method as follows? What would be the impact for the current operations?
```
/**
	 * Trigger event
	 * TODO - admin log for failed callback attempts?
	 * 
	 * @param string $eventname
	 * @param mixed $data
	 * @return mixed
	 */
	function trigger($eventname, $data='')
	{
		$returns = array();
		if (isset($this->functions[$eventname]))
		{
			foreach($this->functions[$eventname] as $i => $evt_func)
			{
				$location = '';
				if(isset($this->includes[$eventname][$i])) //no checks
				{
					$location = $this->includes[$eventname][$i];
					e107_include_once($location); 
					unset($this->includes[$eventname][$i]);
				}
				if(is_array($evt_func)) //class, method
				{
					$class = $evt_func[0];
					$method = $evt_func[1];
						
					try
					{
					
						$tmp = new $class($eventname);
						$ret = $tmp->{$method}($data, $eventname); //let callback know what event is calling it
						unset($tmp);
						if (!empty($ret))
						{
						  	$returns[] = $ret;
						}
					}
					catch(Exception $e)
					{
						e107::getLog()->add('Event Trigger failed',array('name'=>$eventname,'location'=>$location,'class'=>$class,'method'=>$method,'error'=>$e),E_LOG_WARNING,'EVENT_01');
					}
				}
				elseif (function_exists($evt_func))
				{
					$ret = $evt_func($data, $eventname); //let callback know what event is calling it
					if (!empty($ret))
					{
					  	$returns[] = $ret;
					}
				  	else
				  	{
					  	e107::getLog()->add('Event Trigger failed',array('name'=>$eventname,'location'=>$location,'function'=>$evt_func),E_LOG_WARNING,'EVENT_01');
					}
				}
			  	else
				{
				  	e107::getLog()->add('Event Trigger failed',array('name'=>$eventname,'location'=>$location,'function'=>$evt_func),E_LOG_WARNING,'EVENT_01');
				}
			}
		}
		return (!empty($returns) ? $returns : false);
	}
```

**Comment by CaMer0n** [comment]
I believe this change would break some things. It is meant to return true/false. It sounds like what you need is more like the functionality of an addon such a e_cron.php. I would suggest having your nodejs plugin scan the plugin directory for plugins contain e_nodejs.php files and store the list an array of your pluginPrefs as e_nodejs_list  (see core preference editor for example of these 'lists').  Once that is done you should be able to call custom methods from within these files using e107::getAddonConfig()

**Comment by lonalore** [comment]
Yes, I have thought of this, it would have been another solution. :) I'll try to implement this solution, thank you!

**Comment by CaMer0n** [comment]
btw, I sent you an email, did you receive it? info@.....

**Comment by lonalore** [comment]
Yes I did! I found it in the junk folder now. o.O
