### ISSUE TITLE
signup impossible 

### ISSUE THREAD

**Issue by ptibogxiv** [e107inc/e107#881]
with the lastest github, sign up is impossible. 

I use extended fields but not social login

the form returns blank to himself (no email ou admin validation)

https://www.animt.fr/signup.php

**Comment by ptibogxiv** [comment]
more bug.. when i add user with admin area, only the user table are created not the user extended

**Comment by CaMer0n** [comment]
@ptibogxiv Please check Admin -> Preferences -> User Registration/Login. Is it set to 'Signup and Login" ?

**Comment by gary231178** [comment]
Hi just installed v2 using the newest master.zip and it appears the above is present again.

When users try to signup, after clicking register it returns to the signup.php page without registering the information and proceeding to tell the user to check email etc etc.

Help??

Regards.

Gary

**Comment by gary231178** [comment]
AAh wondered if this is related to my earlier posted email bug?

I just tried to manually add a user and get that same bug reproduced.
![screenshot_1](https://cloud.githubusercontent.com/assets/12760959/8007933/dd865efa-0b96-11e5-843c-5a38ee9b7f1f.png)
