### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by chory** [e107inc/e107#882]
Main screen show nothing, only white screen. No errors, no colors.
Error log file in server show this
**PHP Fatal error:  Cannot redeclare utf8_to_unicode() (previously declared in /**myweb**/e107_handlers/utf8/utils/unicode.php:37) in /**myweb**/e107_handlers/utf8/utils/unicode.php on line 183**

**Comment by CaMer0n** [comment]
@chory which version are you running?

**Comment by Moc** [comment]
Also do you happen to know your PHP version? If not, please ask your hosting provider.

**Comment by chory** [comment]
Ops, sorry, I forgot to indicate
e107 v2.x downloaded from here https://github.com/e107inc/e107/archive/master.zip
Apache 2.2.29 
PHP 5.4.32
MySQL 5.5.34

**Comment by CaMer0n** [comment]
Okay thank you! Seems your server is missing the 'mbstring' extension and our work-around has a bug. You could recompile PHP to include it, or wait for the fix.

**Comment by chory** [comment]
Yesssss, it is the error, mbstring extension is not ativated.
Thank you very, very, very much
