### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#884]
I am working on a new heme but run into an issue - I used Bootstrap 3 as the ground work - went and made a new xml for it and been doing my changes to it - the issue is, I uploaded it and set it as my site default theme, and get a blank page.

I changed the folder name from bootstrap3 to my theme's name. any ideas?

**Comment by CaMer0n** [comment]
For support, please visit e107help. This area is for bugs and feature requests. Thanks

**Comment by LaocheXe** [comment]
Roger that, sorry. Close this up please
