### ISSUE TITLE
Future-Emotion/lang file  function reqeust 

### ISSUE THREAD

**Issue by hanklu** [e107inc/e107#885]
I wish Emotion/lang/avator file like plugin/them could find or download from office site and install like plugin/them.

**Comment by CaMer0n** [comment]
Language Pack installation from inside admin completed in v2.1.6. 
Emoticons - not done, and not sure how much demand there is for it. 
Avatars - no done, and not sure how much demand there is for it.

**Comment by rica-carv** [comment]
@CaMer0n Normally, a forum has some emoticons and avatars....
Even github and gitter have them, so sooner or latter someone will use them....
