### ISSUE TITLE
Question: How to setup my IDE for e107's Coding Standards

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#886]
I use PhpStorm for my projects, and I want to set it up for e107's coding standards, so I would like to know default formatting values such as maximum chars per lines, tab size, ident, continuation ident... wrapping and braces configuration... etc. 

Is there a list of predefined style I can use? [Something like this](https://www.drupal.org/node/1962108#syntax-formatting)

Thank you!

**Comment by Moc** [comment]
This is a start: https://github.com/e107inc/e107/wiki/e107-Coding-Standard

**Comment by lonalore** [comment]
Ohh thank you! I haven't seen this before. o.O

**Comment by Moc** [comment]
There are some more pages in the wiki on Github which may be interesting. Most of it has been moved to e107.org but it's all in a transitional phase.
