### ISSUE TITLE
[Solved] All my news images are resized

### ISSUE THREAD

**Issue by zekss** [e107inc/e107#888]
I don't know which is the reason by that my news images was resized. I use "Portal Theme 1.0" by Veskoto. The original size of my images is: 720x100 px

With bootstrap theme, my images was resize to 900x300 (it's ok)
But with Portal Theme, my images was resize to 40x5px and it's very ugly 

![problem](https://cloud.githubusercontent.com/assets/8644297/6175774/7a229bec-b2d8-11e4-9388-62287f87b6ee.jpg)

In the code says: 40x0 but the image is 40x5

![problem2](https://cloud.githubusercontent.com/assets/8644297/6176022/4ec6566c-b2da-11e4-8597-9525e0e5e2a1.jpg)

Anyone know how to fix this? Thanks!

**Comment by CaMer0n** [comment]
Yes, I believe the template must be missing the {SETIMAGE} shortcode. 
In the news template of the portal theme, add this:  {SETIMAGE: w=720&h=100}

**Comment by zekss** [comment]
Solved, Everyday I learn something new. Thank you very much Camero

**Comment by CaMer0n** [comment]
You're welcome!
