### ISSUE TITLE
Admin Perfs - Emailing method

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#889]
In the emailing method that is set to smtp - using SMTP Features. I selected SSL and hit save and it keeps displaying none.

**Comment by Moc** [comment]
https://github.com/e107inc/e107/issues/382

**Comment by LaocheXe** [comment]
Ah sorry about that - notice it now.

**Comment by CaMer0n** [comment]
@LaocheXe Please re-test thanks.

**Comment by LaocheXe** [comment]
Works, Thanks!

**Comment by CaMer0n** [comment]
Thank you!
