### ISSUE TITLE
New Plugin Install Database Update

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#892]
Been working on a Plugin for the past few days and got it up and installed (used plugin builder for admin_config.php) - After install and added the settings I get an message in admin area that there is an update for the Database, Update from 1.x to 2.0 with an Update button. "Depending on your particular configuration, you may need to run the upgrade process several times." hit it 10 times and still same thing. Uninstall new plugin and it goes away.

**Comment by CaMer0n** [comment]
I suggest checking your plugins _sql.php file. Also, run Admin -> Database -> Check database validity on your plugin (with debug enabled)

**Comment by LaocheXe** [comment]
I used the featurebox sql.php as a template - changed what I needed. Right now I am going to try to do what the Devs hand book that 107.org has up and use phpMyAdmin. Will also try what you said.

**Comment by LaocheXe** [comment]
Using e107 Database's Check database validity I found the issue - 
Currently
VARCHAR(255) DEFAULT ''
should be
VARCHAR(255) NULL DEFAULT ''

Now it gives me the option to try to fix it. I tried it, It takes me to the Database Utilities section, not telling me any errors - I am using the E107 Debugger plugin with FireFox and have it to display All with no luck. Also it did not fix the issue (which is a typo with my _sql.php which I can fix.

**Comment by CaMer0n** [comment]
It doesn't fix faulty sql files. Just correct your sql file and the issue will be resolved.

**Comment by LaocheXe** [comment]
With the beta I have this issue, problem:

plugin_table1 | plugin_item | Mismatch | Current: VARCHAR(255) DEFAULT " should be VARCHAR(255) NULL DEFAULT "

Now I checked the myplugin_sql.php and it has what it should be, I even tried to update it, re-upload the plugin files, reinstall the plugin but same issue.

in the sql.php I have them like this
`voice_msc` varchar(255) NULL DEFAULT '',
But the database validity says it's not like that (has the NULL removed or not showing). I have other varchar's in the database but they are set to NOT NULL and have no issues.

**Comment by CaMer0n** [comment]
Is the SQL file an export from PHPMyadmin, or did you type it manually?

**Comment by LaocheXe** [comment]
It was an export. I went and redid it in phpmyadmin and exported it again and ran into an issue - idk if it was me but it did not like the:
CREATE TABLE IF NOT EXISTS `voice_exesystem`

"IF NOT EXISTS"

Deleted it and seems to be working 100%
