### ISSUE TITLE
Strange comment get_usXer_date in e107_handlers/e_ranks_class.php

### ISSUE THREAD

**Issue by nlstart** [e107inc/e107#893]
Don't understand the comment change in e107_handlers/e_ranks_class.php on line 209:
from
$userData = e107::getSystemUser($userId)->getData();; //get_user_data($userId);
to
$userData = e107::getSystemUser($userId)->getData();; //get_usXer_data($userId);
???

**Comment by CaMer0n** [comment]
Yep, that was me removing 'get_user_data' from my global search deprecated functions.
