### ISSUE TITLE
SITEDISCLAIMER

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#895]
When using special html characters in the sitedisclaimer, the disclaimer breaks (for example using &lt;).
You should sanitize the input to plain text.

**Comment by LaocheXe** [comment]
Hmmm I'm gonna test that out, be nice to use HTML in that.

**Comment by Crytiqal** [comment]
Same happends when trying to use < in a class name (userclasses)

**Comment by LaocheXe** [comment]
hmmm try bb code?

**Comment by Crytiqal** [comment]
But I want to display <TA\ as a group shorthandle and in the site disclaimer, but everything after and including the "<" gets ignored.

**Comment by LaocheXe** [comment]
so allow HTML in the SITEDISCLAIMER would be a good feature

**Comment by CaMer0n** [comment]
What if you wrap it in html bbcodes? Ie. [html]...[/html]

**Comment by LaocheXe** [comment]
I forgot all about the [htm] bbcode! - @Crytiqal - as CaMer0n said try [html]YourCode[/html]

**Comment by Crytiqal** [comment]
Already tried that,

[html]The Team-Aero™ brand, <TA\ tag and logo are trademarks of Team-Aero Online Gaming[/html]
results in: [html]The Team-Aero™ brand, 

the < being the culprit.

Maybe I should make the tag (<TA\) into a small .png file and use it as a picture.

**Comment by CaMer0n** [comment]
I believe you would need to use an entity for the < - to be valid HTML.

**Comment by Grimston** [comment]
try 

    &lt;

**Comment by Crytiqal** [comment]
Already tried that,

[html]The Team-Aero™ brand, &lt;TA\ tag and logo are trademarks of Team-Aero Online Gaming[/html]
 results in: [html]The Team-Aero™ brand, 

As soon as I hit save, it shows < and when going to the homepage it breaks, as usual.

**Comment by tgtje** [comment]
![disclaimer](https://cloud.githubusercontent.com/assets/1811857/6886246/68970bfc-d636-11e4-8d4e-87e984e6784a.jpg)

it is the TM (most likely) the causes the trouble : 

either as plain txt or surrounded by html : no trouble
The Team-Aero™ brand,  < TA\ tag and logo are trademarks of Team-Aero Online Gaming
typing  >

 The Team-Aero alt+0153, &l(no space) t; TA\tag and logo are trademarks of Team-Aero Online Gaming

as image (with or without html )
