### ISSUE TITLE
Cannot add users

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#897]
Trying to Quick add a user, results in nothing happening, no error or anything, it just doesn't do anything.
(e107_admin/users.php?mode=main&action=add)

When using the signup page (/signup.php)
"An error has occurred creating your user information, please contact the site admin"

Tried via localhost and via webdomain.
--> Site preferences: 
User registration system: Register & Login

**Comment by CaMer0n** [comment]
Could you please verify your database? (Admin --> tools --> database)

**Comment by Crytiqal** [comment]
Check Charset -->Success, Your tables are using the correct character set.
Check database validity --> Success, Tables appear to be okay!
Check for Updates --> both green ticks
Optimize SQL database --> MySQL database e107 optimized

**Comment by CaMer0n** [comment]
Thank you! I will look into it.

**Comment by CaMer0n** [comment]
Do you have any extended user fields?

**Comment by Crytiqal** [comment]
No, not that I am aware of, it was a brand new installation using the •e107 2.0_beta1 Full install (.zip) from the e107 website.

**Comment by Crytiqal** [comment]
I just did a new clean install, exactly the same behavior.

**Comment by LaocheXe** [comment]
odd, I should try this as well with a new install - I just tested it and had no issues using the quick user

**Comment by CaMer0n** [comment]
Could you please run this query from phpmyadmin? And share the result. Thanks

      SELECT @@sql_mode

**Comment by Crytiqal** [comment]
STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by Crytiqal** [comment]
SQL result

Host: localhost
Database: e107
Generation Time: Feb 20, 2015 at 03:00 PM
Generated by: phpMyAdmin 4.3.9 / MySQL 5.6.21-log
SQL query: SELECT @@sql_mode;
Rows: 1





@@sql_mode 


STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by Crytiqal** [comment]
So, is this bug fixed? Can I implement it in my current site or do i have to wait for beta2 to be released?
Thank you for your time.

**Comment by CaMer0n** [comment]
You can simply overwrite the files of beta1 with those from github, and then run the database update in the admin area.. Auto-increment wasn't the problem, it's just that the queries were not compatible with mysql strict mode, which they should be now. If you spot more database issues, please post about it. It is possible some older code still exists which is not yet compatible.

**Comment by Crytiqal** [comment]
Will do, keep up the good work! :)
