### ISSUE TITLE
Bad URLs are generated for emote icons?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#899]
I am working on a chatbox clone plugin, which based on Node.js, and I have a problem with the rendered emote-icons, the URLs of them are not full URLs in some cases. 

Process:
1, Somebody send a chatbox message by an Ajax request
2, On server side, we save message into database, and trigger an event
3, We register a callback function to this event,, and in this function we render the html output of message, and we push this message item to clients
4, A JavaScript in clients browser recieves this message and prepends it to the chatbox container.

So, I generate the html code of messages on server side, so I have to get the full URL of emote icons in all cases.

![alt text](https://dl.dropboxusercontent.com/u/17751753/emotebug.png "Emote render bug")

I render the message in a shortcode, [here:](https://github.com/lonalore/nodejs_chatbox/blob/master/shortcodes/batch/nodejs_chatbox_shortcodes.php#L81)

And the full html output of message item is generated [here:](https://github.com/lonalore/nodejs_chatbox/blob/master/e_module.php#L35)

**Comment by CaMer0n** [comment]
Untested, but the commit 'should' fix it.

**Comment by lonalore** [comment]
Thank you, I'll test it tomorrow and let you know. :)

**Comment by lonalore** [comment]
It works like a charm, thank you! :)
