### ISSUE TITLE
Email not being sent from contact.php 

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#900]
Email testing from the admin email test page is working so not sure why contact.php fails to send.  It displays a message that says it did send...

-D-

**Comment by dimante** [comment]
Claims "Your message was sent." but it's lying :-/

**Comment by CaMer0n** [comment]
okay thanks, will check it out.

**Comment by dimante** [comment]
I see what is going on.  The form has listed that it is going to send to
sales@<mydomain> but it ends up sending to the site admin's email address
instead.  How do I correct this?



On Fri, Feb 20, 2015 at 12:03 AM, Cameron <notifications@github.com> wrote:

> okay thanks, will check it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/900#issuecomment-75193800>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Actually I have confirmed this is a problem.  Even if I go to the main admin settings and change all the emails it is still going to the wrong address :-(

**Comment by CaMer0n** [comment]
So if I understand well, you have the "contact persons" set to "main admin" in admin -> preferences ?

**Comment by dimante** [comment]
​Yes.  But what is odd is the contact form states it is going to send to
the desired recipient...  But as you said, sends to the main admin anyway.​

On Sat, Feb 21, 2015 at 11:31 AM, Cameron <notifications@github.com> wrote:

> So if I understand well, you have the "contact persons" set to "main
> admin" in admin -> preferences ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/900#issuecomment-75382215>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
SO to be complete what I am saying is I have sales@<domain> set in the site
preferences for all but the contact form gets emailed to the main site
admin at a different address..

On Sat, Feb 21, 2015 at 11:33 AM, John Gates <dimante@dimante.net> wrote:

> ​Yes.  But what is odd is the contact form states it is going to send to
> the desired recipient...  But as you said, sends to the main admin anyway.​
>
> On Sat, Feb 21, 2015 at 11:31 AM, Cameron <notifications@github.com>
> wrote:
>
>> So if I understand well, you have the "contact persons" set to "main
>> admin" in admin -> preferences ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/e107inc/e107/issues/900#issuecomment-75382215>.
>>
>
>
>
> --
>
> *This email may contain information that is confidential or
> attorney-client privileged and may constitute inside information. The
> contents of this email are intended only for the recipient(s) listed above.
> If you are not the intended recipient, you are directed not to read,
> disclose, distribute or otherwise use this transmission. If you have
> received this email in error, please notify the sender immediately and
> delete the transmission. Delivery of this message is not intended to waive
> any applicable privileges.*
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by CaMer0n** [comment]
Please go to Admin -> Database -> Preferences Editor, and let me know what value you have for "sitecontacts" . Thanks.

**Comment by dimante** [comment]
254

On Sat, Feb 21, 2015 at 2:18 PM, Cameron <notifications@github.com> wrote:

> Please go to Admin -> Database -> Preferences Editor, and let me know what
> value you have for "sitecontacts" . Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/900#issuecomment-75390656>.
>



-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Thanks!!

On Sunday, March 1, 2015, Cameron <notifications@github.com> wrote:

> Closed #900 <https://github.com/e107inc/e107/issues/900> via c1430f2
> <https://github.com/e107inc/e107/commit/c1430f257a2da4bf32021525fc8e445c28a16ec5>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e107inc/e107/issues/900#event-244136678>.
>


-- 

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Indylogan** [comment]
Hello, may I ask, what was the solution? I have the same issue. Mails are not arriving from contact.php.

Admin -> Database -> Preferences Editor, and let me know what
value you have for "sitecontacts" . Value is: 254

Othe php mailing from the site is OK. Thank you.
