### ISSUE TITLE
Bug in cron.php

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#906]
Admin Area --> Tools --> Schedule Tasks --> e107_admin/cron.php

navigates to a full blank page. (No e107 theme wrapper or anything)

Host is running on Windows

**Comment by CaMer0n** [comment]
I am unable to reproduce this. Please check for error_log in the admin folder and any other PHP errors.

**Comment by Crytiqal** [comment]
I can't seem to find any file named error_log

**Comment by CaMer0n** [comment]
a blank page is often a failed file include. eg. language file etc.

**Comment by CaMer0n** [comment]
@Crytiqal Any news on this one.. is it still an issue?
