### ISSUE TITLE
Social Signup/Login issue

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#907]
1) 

e107_admin/prefs.php#nav-core-prefs-registration
Live --> Get a key from the provider 
https://manage.dev.live.com/ApplicationOverview.aspx --> This page can’t be displayed

2) 

/signup.php?stage1

Register --> Clicking the OpenID logo (Register using your openid account) /?route=system%2Fxup%2Fsignup&provider=openid&back=aHR0cDovL3d3dy50ZWFtLWFlcm8ub3JnL3NpZ251cC5waHA%2Fc3RhZ2Ux --> returns to /signup.php and nothing happening.

I suppose I would need some API key from OpenID but no idea how to use this? It seems broken, I'm sorry if Im mistaken but then the help section should be expanded to guide you in the right direction. (A link to the wiki?)

**Comment by LaocheXe** [comment]
Google sent me here

https://account.live.com/developers/applications/create

Idk if it would work or not. I went to that link above last night and it worked but now it doesn't, so must be the DNS server.

**Comment by Crytiqal** [comment]
Enable your application to use Microsoft accounts 

This site will allow your web-based Android and iOS applications to authenticate users via Microsoft accounts. 

If you want to register an application for Windows 8.1 or Windows Phone 8.1, go to the Windows Store Dashboard instead.


Seems to me this is not for websites, but it should be around here somewhere.

**Comment by LaocheXe** [comment]
Give it a try is all I can say

**Comment by Crytiqal** [comment]
https://msdn.microsoft.com/en-us/library/bb676633.aspx

https://msdn.microsoft.com/en-us/library/hh826544.aspx

**Comment by CaMer0n** [comment]
HybridAuth was recently updated and tested. Closing this, but please re-open a new issue if there is still a social-login issue.
