### ISSUE TITLE
Notify visitors about cookies

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#908]
Since it is required by EU law that every website visitor is informed about the use of cookies..., maybe enable an option in the admin area to show this notice above the page until clicked?

**Comment by LaocheXe** [comment]
That would be a nice feature or a good plugin to have, think I might make one

**Comment by LaocheXe** [comment]
So something like this: Admin Area -> Site Preferences ->  Security & Protection
If User Tracking method Cookies is selected then
Notify Users about Site Cookies? Check Box (Checked = Enabled, unchecked = Disabled)
Also maybe some customization options for the Notification.

**Comment by Crytiqal** [comment]
Also, only if user is a Guest and only if he doesn't already have accepted it before (store in cookie).
If user is a Member, he shouldn't have to be notified anymore (notify about cookies on signup).

include e107_cookie;

if ($user == Guest && $cookie_accept != yes )
{
$tekst .= $pref_cookie_notification;
}

For all other scenarios this rediculous annoying forced EU LAW cookie crap notification doesn't have to be shown ;)

**Comment by Moc** [comment]
This is plugin territory and there are already some e107 plugins out there which do what you want. 

You could use the e_module.php addon for this. The code in this file is executed on each page load. Simply check for cookies there.
