### ISSUE TITLE
Incorrect response code for 404 error

### ISSUE THREAD

**Issue by STR82U** [e107inc/e107#91]
Non existent pages don't return 404 headers - rewrite system isn't being used on the test site I'm working on now but this is an issue I've confirmed in all of the others up to now.

**Comment by Moc** [comment]
This should now be fixed.

**Comment by CaMer0n** [comment]
I need to test it with news. This is the main issue.

**Comment by CaMer0n** [comment]
Hopefully my last commit https://github.com/e107inc/e107/commit/c69a303bce66ba93648cdd168cad231f9ea6a8d4 should fix it.
