### ISSUE TITLE
Bug in Plugin Manager

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#910]
Admin Area --> Plugin Manager --> Find Plugins /plugin.php?mode=online

Search query doesn't do anything.

**Comment by CaMer0n** [comment]
I am unable to reproduce this. Here is an example of the URL after clicking the search button: 
e107_admin/plugin.php?srch=weather&go=&mode=online

**Comment by Crytiqal** [comment]
Yes the query is placed in the url, but there is no return list showing any plugins.

**Comment by oxigeno2** [comment]
Localhost? I should have same problem (impossibility to use cURL)

**Comment by CaMer0n** [comment]
I have cUrl running on a local windows 7 setup. How about you @Crytiqal ?

**Comment by Crytiqal** [comment]
No I don't. I have wget from GnuWin.

Is cURL required? I didn't know.

PS: CaMer0n is it possible to contact you on a different matter?

**Comment by CaMer0n** [comment]
Yes, if you're not already, please follow 'e107' on Twitter, and I'll direct message you.

**Comment by Crytiqal** [comment]
Following you @HNCCox @Crytiqal

**Comment by CaMer0n** [comment]
Closing this. When using a local server it needs to be able to retrieve remote content in some way. Either way cUrl or file_get_contents() for this feature to work.

**Comment by Crytiqal** [comment]
At least write some information in the help files about it :)
Now it seems broken and I would like to be able to browse the online plugin repository.

Isn't it possible with php to retrieve an index list from the remote server?
Or like an <iframe> (forgive me :D )
