### ISSUE TITLE
Bug in links.php

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#911]
Admin Area --> Site links --> Manage

When trying to update the user class for which the link is visible:

Error
SQL Update Error

**Comment by CaMer0n** [comment]
Please enable debug and test again

**Comment by Crytiqal** [comment]
I am really sorry but for some reason it works now...

I am trying to figure out what I changed. I enabled developer functions and turned it back afterwards but it still works so it can't be that.

**Comment by CaMer0n** [comment]
Okay. Thank you!

**Comment by Crytiqal** [comment]
I dropped the e107 table, ran the install.php again, and it seems to be working properly.

**Comment by Crytiqal** [comment]
I get this bug again...

**Comment by CaMer0n** [comment]
Would you mind please turning on debug (Sql Details), it should provide more details than that.

**Comment by Crytiqal** [comment]
Ok, first off, in main admin area:
SELECT * FROM `e107_banner` LIMIT 1  
Table 'e107.e107_banner' doesn't exist 

Second, in settings, site links:

System Debug
e_url.php in ../e107_plugins/gallery is missing the key: gallery. Or, you may need to scan your plugin directories to register e_url.php

Thirdly, when create a new link named TEST and url test.php:

System Debug
SQL Error #1366: Incorrect integer value: '' for column 'link_parent' at row 1

INSERT INTO `e107_links` (`link_id`,`link_button`,`link_name`,`link_category`,`link_parent`,`link_url`,`link_sefurl`,`link_class`,`link_description`,`link_order`,`link_open`,`link_function`,`link_owner`) VALUES (0, '', 'Test', '1', '', 'test.php', '', '0', '', '0', '0', '', '') 
Incorrect integer value: '' for column 'link_parent' at row 1 

Hope this helps

**Comment by Crytiqal** [comment]
As expected by the error, making it a sublink works :)

I think the default value for link_parent should be either a forced integer '0' or not forced at all?

**Comment by CaMer0n** [comment]
That's correct, it needs to be a forced integer. Thank you for this debug information - it helps a lot!
I thought I was running in strict mode in my local setup, but it appears I wasn't. Once that was corrected, I was able to reproduce the problem and correct the issue.
