### ISSUE TITLE
Wrong chars in database. Missing charset from install form and e107_config.php.

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#912]
I just realized that my database contains wrong chars, but my table have utf8_general_ci encoding. So, I checked my e107_config.php and I couldn't find the charset for database connection. Then I checked the installation form, and the charset option is missing in the "stage_2" (form) and "stage_7" (content of e107_config.php) functions (install.php).

**Comment by lonalore** [comment]
I put $mySQLcharset  = 'utf8'; into my config file manually, but I think this option is an essential part of installing process.

**Comment by CaMer0n** [comment]
All fresh installs should be utf8, we just need to make sure it is added to the config file.
