### ISSUE TITLE
Bug in users.php

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#914]
Admin Area --> Users --> Manage ( /users.php )

When managing a user by clicking on the "User class" (Edit User class) I get the list of nearly all the userclasses I have and I can tick them but I cannot save/update this to the user because there is no apply/update button. 

(I have a LOT of userclasses, due to a military chain of command structure, and I guess there are too many to show in the quicklist and it renders the "apply" button offscreen)

Maybe add a scrollbar to the quicklist.

**Comment by CaMer0n** [comment]
Are you talking about the inline editing of userclasses? Perhaps you can send us a screenshot of what you describe?

**Comment by Crytiqal** [comment]
![userclasses](https://cloud.githubusercontent.com/assets/1153508/6422345/ca44340e-bed7-11e4-876e-1690151ca28a.png)

**Comment by Crytiqal** [comment]
Also, would it be possible to get the old function back where you can edit the userclass and assign multiple users to it instead of having to go by every user separately?

**Comment by CaMer0n** [comment]
You can do this using the checkboxes in the main users page and then selecting to add the userclass to those users from the drop down menu.

**Comment by CaMer0n** [comment]
Fix for this will be committed in a minute.
