### ISSUE TITLE
Support request: using sef urls in custom plugin

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#915]
I would like to ask for a little help on how to implement sef urls in a custom plugin? I checked faqs and gallery plugins and I found "e_url.php", "url/url.php", "url/rewrite_url.php", "url/sef_url.php" also I found the controllers too... I think it's a little complicated. Or, it is still under development? 

If I understand correctly, I have to use "url" files under my plugins "url" folder to define rewrite rules, and also I have to use a controller for the sef urls, in the "controllers" folder (controller/action). But, I do not want to have the e.g my render functions twice in my plugin... as in the gallery plugin. The controller and the gallery.php are almost the same. o.O

Is there any documentation about the correct usage of sefurl implementation? :/

**Comment by Jimmi08** [comment]
Thank you that you put it this way. I ask for this too. It's very important to know how this works. It seems now how each plugin was written different way.  I could close this: https://github.com/e107inc/e107/issues/875   if I would understand how to add sef-url for image itself (it's not important if I change gallery plugin or create my own, I just need the rules how to create more levels sef-urls system).

**Comment by lonalore** [comment]
Well, the sef implementation in the PM plugin would be understandable, in a simple create method (in the url/url.php file) we can define routes for the plugin, and then we can generate urls using e107::getUrl()->create()... and I think, this method should generate sef urls if sef is enabled, and normal urls if sef is disabled. The only trouble is that it does not work. :) Htaccess file is available on my site, but the sef urls always run on 404.

**Comment by Jimmi08** [comment]
Yes, I know, PM doesn't have controller like gallery plugin...  that is what I mean that each plugin is written different way. Somebody told me some time ago that if issue has too much comments, it's overlooked by developers, so I will wait how you solve this, I don't want to mess your issue. I just wanted to support your question.

**Comment by lonalore** [comment]
In my opinion e107 should handle all menu paths. For example, plugin developers could create menu paths for their plugins using e_url.php, and they could generate site urls using the way like e107::getUrl()->create().

For example, a method in e_url.php return an array something like this:

```
return array(
  'books' => array(
    'callback' => 'something_callback_function',
    'file' => 'path/to/callback/file/in/plugin/folder',
  ),
  'books/{sef_category}' => array(
    'callback' => 'something_callback_function',
    'params' => array(
      'sef_category' => $params[1],
     ),
    'file' => 'path/to/callback/file/in/plugin/folder',
  ),
  'book/{sef_title}' => array(
    'callback' => 'something_callback_function',
    'params' => array(
      'sef_title' => $params[1],
    ),
    'file' => 'path/to/callback/file/in/plugin/folder',
  ),
);
```

So, e107::getUrl()->create('books/' . $category) method would generate urls like:

if SEF is enabled:
http://something.site/books/fantasy

if SEF is disabled:
http://something.site/?q=books/fantasy

Also, e107 should handle all requests, parse parameters and call the callback functions and pass params to these functions. In the callback functions developers can recieve these params and they could render the page...

Of course, BC is important, but I think old v1 plugins still would works with their old paths like:
http://something.site/e107_plugins/plugin_name/books.php?cat=fantasy

**Comment by lonalore** [comment]
With this method, the e107_plugins directory and the plugin directory would behidden from the users. I think, no one is interested in the plugins name. :P

**Comment by CaMer0n** [comment]
I agree that the url method used by gallery, news, pages is quite complicated and difficult for the average plugin developer to work with. It is why I started on a simpler method similar to what you describe. It can be found in faqs/e_url.php and using e107::url() to create the links.  (see faqs shortcode)
Please take a look. I believe it is better to not use regexp as array keys since they cannot contain unicode.

**Comment by lonalore** [comment]
Hmm, then I will try to implement it in my plugin. I have not looked at faqs carefully, because it didn't work for me, always run into an infinite redirect loop.

**Comment by CaMer0n** [comment]
Yes! With faqs, remove list.php if it exists in the controllers folder.

**Comment by lonalore** [comment]
Excellent! Thank you! :)

**Comment by lonalore** [comment]
Sorry, I must reopen this issue because I have no luck with this e_URL addon file.

In my plugin, I have an e_URL implementation:
https://github.com/lonalore/nodejs_chatbox/blob/master/e_url.php

Then I rescaned plugin directories with e107, and I cleared cache, but I always get a white screen after I type "chatbox" into my browser's address bar. Error log doesn't contain any details.
