### ISSUE TITLE
Admin theme screws up! Major bug

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#916]
Setting the admin theme to bootstrap 3 is a major screw up!

I had to go into the MySQL db and go to e107_core SitePrefs and reset 'admintheme' => 'bootstrap3',
back to 'admintheme' => 'bootstrap', manually cause the entire admin website was broken.

**Comment by CaMer0n** [comment]
yes, it is purely experimental.

**Comment by Crytiqal** [comment]
Oh ok :)

Maybe disable it to be used for admin theme? As anyone else with less knowledge about MySQL would be unable to rectify the problem, ultimately leaving them to start over entirely and frustrated?

**Comment by CaMer0n** [comment]
Will now only allow for bootstrap3 if the following is included in .htaccess: 
 
    SetEnv E_B3_ADMIN true
