### ISSUE TITLE
Media Manager Upload by URL 

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#917]
I tried to upload a youtube video by URL. It tried to take it and now I am left with a file created by me but with no name and it wont delete it - I get an warning "couldn't be renamed. Check file perms." 

I select it and hit the Delete Selected Files and clicked the Ok button and wont remove it.

Now I know that you can't upload a youtube video for an image = but did it to test.

**Comment by CaMer0n** [comment]
It can only import a file which can be downloaded via a browser. YouTube Urls do not contain video files for download. Point it to a .mp4 or .jpg and it should work.
