### ISSUE TITLE
Possible my plugin_shortcodes.php bug

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#918]
I made a plugin that uses the plugin_shortcodes.php that was up on the e107.org Dev help section and called for it in the theme_shortcodes.php but it does not get the code (or add it to the theme).  I included the plugin short codes php file and added {MY_PLUGIN} and no luck.

If I take the function from my plugin_short codes.php and add the function in the theme short codes and add $myplugin=$this->function name();  $text .= $myplugin; then it works.

I asked about this at the e107 help site and Moc gave it a try and had no luck as of yet. He suggested asking Cameron for some help.

**Comment by CaMer0n** [comment]
Only e_shortcode.php content is available site-wide.

**Comment by LaocheXe** [comment]
So rename my plugin_shortcodes.php to e_shortcode.php?

**Comment by LaocheXe** [comment]
I went and renamed it - used the {PLUGIN_NAME} and still no go, it would display text in a menu with the custom url - the plugin stores information in the database and pulls it...

**Comment by CaMer0n** [comment]
Perhaps you can post a GIST, as it's difficult for me to visualize everything you have.

**Comment by LaocheXe** [comment]
https://gist.github.com/LaocheXe/2913a729969276c266b2

That is the e_shortcode.php

**Comment by CaMer0n** [comment]
okay, and this is sitting in a plugin folder called 'voice', correct? And did you make sure it is loaded by doing a plugin-scan in Admin -> Databases?

**Comment by LaocheXe** [comment]
yes

**Comment by LaocheXe** [comment]
I re-did the plugin scan of the daatabase and now it works, thanks!  This information should be in the dev section of e107.org, very useful information!

**Comment by CaMer0n** [comment]
It does mention that already in the developer docs.
