### ISSUE TITLE
[Problem] Missing Captcha Code

### ISSUE THREAD

**Issue by zekss** [e107inc/e107#922]
Hi everyone, in this summer (i'm from argentina) i started to have a lot of bot users registered on my web. I know that this version is not prepared to implement on a web, doesn't care.

So I activated a Captcha Code on Sign Up page, but appears me the following mensaje (on the captcha box):

"missing code"

This is because I use "Simple Portal 1.0" theme or is a bug?

Thanks!

**Comment by LaocheXe** [comment]
Try to install the Stop Forum Spam plugin? Its for version 1.xx but works for v2.xx (I believe).

I will enable caption code to see if I get the same error.

**Comment by LaocheXe** [comment]
Tried it and it works on my end, try re-uploading the files?

**Comment by zekss** [comment]
Thanks. This works on my localhost but in my web host (most important) doesn't work

**Comment by LaocheXe** [comment]
I would clear my cache a few times then try it on the web host, or the web host might have some issues. I notice from an old web host that some things didn't work like images weren't displaying unless I changed their file perms to 777 or whatever it is.

**Comment by zekss** [comment]
Still doesn't work. I clear cache and the web host works perfects, some files are in chmod 777

**Comment by Jimmi08** [comment]
It happened to me when I changed e107 folder names (images or files) or with php 5.5

**Comment by zekss** [comment]
And how do you solved it? Yes, I changed my folder names (also I changed in robots.txt)

**Comment by LaocheXe** [comment]
Change them back I guess - Did you also update the folder names in the e107_config.php as well?

**Comment by zekss** [comment]
Yes, I'm not so foolish haha. My website is up and is working but with very little problems, example: this.

**Comment by Jimmi08** [comment]
Hi,  I wasn't able to solve this. I tried everything - rewrite htaccess, find all hardcoded folder names in code and replaced, Nothing helped. (maybe something related to hash?) 
So for now I renamed all folders except these 2. And I am not for 100% sure what of them caused this problem. 
I don't install new e107 v2 for some months, but with V1 I use new version of google recaptcha and I must say - it stopped all spam to my V1 sites and 10 years old nuke site too. 
I just found that I created issue about this already (look at time):
https://github.com/e107inc/e107/issues/604

**Comment by zekss** [comment]
Aaah ok, well.. I rename the folder images to "e107_images" and nothing, the problem persist (I don't have "e107_files" folder)

**Comment by LaocheXe** [comment]
maybe it's e107_system now?

**Comment by zekss** [comment]
Yes! I change one folder name (e107_system) and one folder name in e107_class (e107_core). I don't know why e107_core doesn't appear on e107_config.php.

It would be good to know the reason for this problem.

Thanks both of you!

**Comment by zekss** [comment]
Em.. I found two problems now. When I log in, I can't see comments on news but if I log out, I see the first 5 comments.

And when I go to: AdminCP --> Content --> Pages/Menu --> Create Page/Menu, the page is blank

<img src="http://i.imgur.com/Oy5JU1v.jpg" />

It is caused by the same thing?

**Comment by LaocheXe** [comment]
id say download the current files of e107 on github and upload them and change ur e107_config.php back to where the folders names - "While this is a bug, I don't recommend modifying the folder names. It serves no purpose while we have SEF Url support." - CaMer0n

**Comment by zekss** [comment]
Ok, I'll try with this and I comment. Thanks!

**Comment by CaMer0n** [comment]
Please add the following to your e107_config.php file - it should allow you to see any errors behind 'blank pages'. 

    define('e_DEBUG', true);

**Comment by zekss** [comment]
Ok thanks, problem solved! I re-upload all files & folders (for doubts). After, I did a clean install of e107 CMS and let the name of the folders by default (e107_ ). I have another problem now with the codification utf8, but I'll let on another post.

**Comment by CaMer0n** [comment]
Please post as a separate issue. I tried to reproduce the problem you mentioned with the non-ascii characters and couldn't.
