### ISSUE TITLE
Question: theme.xml

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#923]
I have a question, asked over at e107help but never got an answer back. Did not find this on the dev section of e107.org.

in theme.xml there is a section for plugins, the url, does is that to link the plugin download page?

Example: <plugin name='gallery' url='core' />

Take it 'core' is already up in the plugins folder - so do I give an http:// link or is it something else?

**Comment by CaMer0n** [comment]
No, it's just a link to the developers website if he/she has one.
