### ISSUE TITLE
Comments are not shown in v2

### ISSUE THREAD

**Issue by AlexL777** [e107inc/e107#924]
Hello Community,

I'm still a novice when it comes to the version e107 v2 and I have everything in English. Today I installed the latest version and me, it is noticed that comments are not displayed.

There are no visible comment field in the front end with the news. I let guests comment and I still early alpha even commented on my News e107. But one day, the comment was gone.

What can I do? An error message is not displayed. Would be grateful for any help.

P.S. Here is the link to one of my news:[Link](http://wpzweinull.ch/cms/e107/news/E107-v2-beta-1-ist-erschienen-und-es-kann-aktualisiert-werden.html)

**Comment by CaMer0n** [comment]
Please re-check your preferences. Admin->Comment Manager -> Preferences. 
Make sure "Allow users to post comments" is checked, as well as "Comments Enabled" for the news items you mentioned.

**Comment by AlexL777** [comment]
Many thanks for your response. So I adjusted it and it will be my only shown what you can see in the screenshot. It just says "Comments" and nothing else more.

At the very beginning, where I e107 2.0 alpha installed, I had comments, but then they were gone.


![comments-e107-2-0-beta1](https://cloud.githubusercontent.com/assets/7885632/6565349/b0406ce6-c6af-11e4-91fe-5cf5a8ec6fd3.jpg)

**Comment by CaMer0n** [comment]
Thank you for the screenshot. Please update from Github and then report back. Thank you.

**Comment by AlexL777** [comment]
Many Thanks. I have just updated and unfortunately are not there yet the comments. It lacks the comment function and these settings I have in the Comment Manager. That's right ?!

![e107-2-0-comments-allow](https://cloud.githubusercontent.com/assets/7885632/6566715/93112c4c-c6bd-11e4-8cad-0a2fa3fc6350.jpg)

**Comment by CaMer0n** [comment]
Please resave the news item and see if that changes anything. I'm unable to reproduce the problem here.

**Comment by AlexL777** [comment]
I have relaunched the blog and the comments feature is again available. I just hope it stays that way and not like the Alpha version. As the comment were suddenly gone. I'll be watching it.

Thank you've made yourself the trouble.

**Comment by CaMer0n** [comment]
Alpha had some mixed up preferences.. ie. on = off, and off= on. It should all be corrected now, but thanks for keeping an eye on it.
