### ISSUE TITLE
Question: Handler Calendar

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#925]
What ever happen to it and is their a replacement for this?

I don't know much, but I do know it's not in the new version of e107 due to out dated code (or so I believe) - Some of the old plugins looks for calendar/calendar_class.php and to counter that I grabbed that folder from the e107_handlers and moved it into the plugins folder of the new version and updated the links in a old plugin (roofdonation tracker) and it works, works I mean it displays the pages now.

**Comment by CaMer0n** [comment]
$frm->datepicker()

**Comment by LaocheXe** [comment]
Fatal error: Call to a member function datepicker()

**Comment by CaMer0n** [comment]
Please read the docs on using the form handler.
