### ISSUE TITLE
[Problem] SQL Update Error & Error with tildes and enies

### ISSUE THREAD

**Issue by zekss** [e107inc/e107#926]
I have a problem with one of the last updates, with codification utf8.

When I did a clean Installation, I see that now the system created a database based on utf8 (in fact, appears in e107_config at a new var: $mySQLcharset = 'utf8';).

Well, the problem is that all my tildes (á, é, í, ó, ú) and enies (ñ) was converted to Ã³, Ã©, etc.
How I fix this? I tryed to change the collation of the DB but doesn't works.

Another error that I notice now is that when I want to change a name of a site link, I can't. Says me: "SQL update error"

I ask this two errors at the same post because one of my site links called: "Información" and now with the problem: "InformaciÃ³n" and when I go to change it, I can't for the "SQL update error" problem

**Comment by CaMer0n** [comment]
Are you running your site in English? If not, which language-pack are you using?

**Comment by zekss** [comment]
Mm.. I see the language of my web on Admin area-->Settings-->languages, alright? If yes, I running my web on english.
Default site language: english
Admin area interface language: default site language.

**Comment by CaMer0n** [comment]
What kind of server are you running it on?

**Comment by zekss** [comment]
OS: linux, Architecture: x86_64, Apache version: 2.2.29, PHP version: 5.4.36, MySQL version: 5.5.42-cll, I put all for doubts.

**Comment by CaMer0n** [comment]
And when you remove or comment-out $mySQLcharset = 'utf8'; from your e107_config.php file - does it fix the issue? Also, would you mind checking Admin -> Tools -> Database -> Check Charset for me before you do that?

**Comment by zekss** [comment]
Great! If I comment the line "$mySQLcharset = 'utf8'" solved the problem with the tildes and enies. But I still have the problem when I want to change a "Site Link" name, says: "SQL Update Error"

<img src="http://i.imgur.com/srjZC8o.jpg" />

**Comment by CaMer0n** [comment]
Please post in a separate issue. Thanks. Could you please post the results of the "Check Charset" from the admin area?

**Comment by zekss** [comment]
Ok. Yes, sorry, I forget to tell you about that
Engine: MyISAM (All except one that is for a plugin that I builded)
Collation: utf8_general_ci (in all tables)
Status: ✓ (in all tables)

Thank you very much!

**Comment by CaMer0n** [comment]
Thanks. All looks okay. It's unusual the the utf-8 setting in e107_config.php CAUSED the problem, usually it fixes it.
