### ISSUE TITLE
e_frontpage

### ISSUE THREAD

**Issue by chory** [e107inc/e107#927]
well, i'm making a plugin PCVillamuriel, and i'm using a custom frontpage
in e_frontpage.php, i have this code

``` php
<?php
  if (!defined('e107_INIT')) { exit; }  
e107::js('PCVillamuriel','js/menu.js','jquery');    // Load Plugin javascript and include jQuery framework 
e107::css('PCVillamuriel','css/PCVillamuriel.css'); 
 $front_page['PCVillamuriel'] = array('page' => $PLUGINS_DIRECTORY.'PCVillamuriel/carteleseventos.php', 'title' => "Carteles");
?>
```

and in Admin Control Panel -> Settings -> Front Page ->  Edit existing rule, i select "carteles", and pulse Update.
But the result main page is only this 

```
Bad request - destination unreachable - e107_pluginsPCVillamurielcarteleseventos.php
```

in my local server works fine.
Why not work correctly in remote?
T.I.A.

**Comment by CaMer0n** [comment]
Thank you. e_frontpage.php needs to be upgraded to v2.x specifications. I will look into it shortly.

**Comment by chory** [comment]
THX, but i dont understand, why no work in remote server

**Comment by CaMer0n** [comment]
Looks like it's removing the folder separators: 
e107_pluginsPCVillamurielcarteleseventos.php
should be e107_plugins/PCVillamuriel/carteleseventos.php ?

**Comment by chory** [comment]
Yes, it is the problem, forlder separatores are removed automatically

**Comment by CaMer0n** [comment]
Try this, does it help?: 

     $front_page['PCVillamuriel'] = array('page' => 'carteleseventos.php', 'title' => "Carteles");

**Comment by chory** [comment]
no, Bad request - destination unreachable - carteleseventos.php

**Comment by CaMer0n** [comment]
Could you please also try this:
   
     $front_page['PCVillamuriel'] = array('page' => '{e_PLUGIN}PCVillamuriel/carteleseventos.php', 'title' => "Carteles");

**Comment by chory** [comment]
Bad request - destination unreachable - e107_plugins/PCVillamurielcarteleseventos.php

**Comment by LaocheXe** [comment]
Admin Area - > Database - > Scan plugin directories    maybe that will work?

**Comment by chory** [comment]
![e107_error](https://cloud.githubusercontent.com/assets/4314070/6659188/c0891204-cb7f-11e4-94d2-6e5b846d7f92.jpg)
```php
<?php

if (!defined('e107_INIT')) { exit; }  
	
	/* OLD
	e107::lan('forum', 'English_front');
	e107::js('PCVillamuriel','js/menu.js','jquery');	// Load Plugin javascript and include jQuery framework 
	e107::css('PCVillamuriel','css/PCVillamuriel.css');	

	$front_page['PCVillamuriel'] = array('page' => '{e_PLUGIN}PCVillamuriel/carteleseventos.php', 'title' => "Carteles");
	*/

// NEW
class PCVillamuriel_frontpage // include plugin-folder in the name.
{
	function config()
	{
		$frontPage = array();
		$frontPage['title'] = "PCVillamuriel"; // .': '.vartrue($row['content_heading']); LAN_PLUGIN_NEWSFEEDS_NAME ?
		$frontPage['page'][] = array('page' => '{e_PLUGIN}PCVillamuriel/carteleseventos.php', 'title' => "Carteles");
		return $frontPage;
	}
}

?>
```

**Comment by LaocheXe** [comment]
uninstall and re-install

**Comment by chory** [comment]
jejeje, you read my mind, i'm do it

**Comment by CaMer0n** [comment]
Please check e107_plugins/download/e_frontpage.php for a working example.

**Comment by chory** [comment]
Please check e107_plugins/download/e_frontpage.php for a working example. 
In git version not exist

**Comment by CaMer0n** [comment]
@chory https://github.com/e107inc/e107/blob/master/e107_plugins/download/e_frontpage.php

**Comment by chory** [comment]
![e_frontpage](https://cloud.githubusercontent.com/assets/4314070/7072222/ea1c9e28-deea-11e4-8f6f-379633930ea4.jpg)
Where is my frontpage?

**Comment by CaMer0n** [comment]
Please run a database -> plugin scan. Is e_frontpage.php being loaded?

**Comment by chory** [comment]
Database is OK

**Comment by CaMer0n** [comment]
Please paste the contents (from prefs editor) of e_frontpage_list. thank you.

**Comment by chory** [comment]
![preferences-editor](https://cloud.githubusercontent.com/assets/4314070/7102533/dfa4c378-e082-11e4-9e85-a2c2b692de71.jpg)

**Comment by CaMer0n** [comment]
I have changed the loading order, please try again and report back. Thank you.

**Comment by chory** [comment]
I go to intall all again from 0

**Comment by chory** [comment]
```php
if (!defined('e107_INIT')) { exit; } 
$front_page['PCVillamuriel'] = array('page' => $PLUGINS_DIRECTORY.'PCVillamuriel/carteleseventos.php', 'title' =>"Carteles");
```
Works fine

**Comment by chory** [comment]
```php
if (!defined('e107_INIT')) { exit; } 
$front_page['PCVillamuriel'] = array('page' => $PLUGINS_DIRECTORY.'PCVillamuriel/carteleseventos.php', 'title' =>"Carteles");
```

return Bad request - destination unreachable - e107_pluginsPCVillamurielcarteleseventos.php

**Comment by CaMer0n** [comment]
Thank you for the update. Could you please remove $PLUGINS_DIRECTORY and use "{e_PLUGIN}" as it is in the 'downloads' example? Does it help?

**Comment by chory** [comment]
```php
<?php
if (!defined('e107_INIT')) { exit; }  
$front_page['PCVillamuriel'] = array('page' => '{e_PLUGIN}PCVillamuriel/carteleseventos.php', 'title' =>"AVPCVillamuriel Eventos");
?>
```
return
 Bad request - destination unreachable - e107_plugins/PCVillamurielcarteleseventos.php
```html
<html><head></head><body>Bad request - destination unreachable - e107_plugins/PCVillamurielcarteleseventos.php</body></html>
```

**Comment by chory** [comment]
I think the problem is in my remote server.
Close this issue

**Comment by chory** [comment]
I think the problem is in my remote server.
Close this issue
![php1](https://cloud.githubusercontent.com/assets/4314070/7260270/2636eff8-e869-11e4-961e-50fec095f2cf.jpg)

**Comment by CaMer0n** [comment]
okay. Thank you for updating.

**Comment by armpit** [comment]
I have this issue when trying to set the newsfeeds or downloads modules as the front page using the release version from e107.org

'Bad request - destination unreachable - e107_plugins/downloaddownload.php'

I'm not familiar with the source of 2.0, I haven't used e107 for a few years, so sorry I haven't been able to look into it more.

I've forked the project and will get familiar with the source once I get a bit more free time.

**Comment by CaMer0n** [comment]
@armpit Please update from Github and see if the problem continues.

**Comment by armpit** [comment]
@CaMer0n Made a fresh install from git on a VPS, activated downloads plugin, then set it as front page. Same error. Sorry I cant give you more, so much on my plate at the moment I forgot about this until I got pinged by github.

**Comment by chory** [comment]
Sorry, I eliminated this project
