### ISSUE TITLE
Problems with tinymce

### ISSUE THREAD

**Issue by enddDD** [e107inc/e107#928]
Hi i am using v2 version,fresh install of e107,and when i try to insert some html in the editor it erase my entire post (if it is a news for example) and gives me this:

The requested URL could not be found on this server. The link you followed is probably outdated.
Please inform the administrator of the referring page if you think this error message has been shown by mistake.

Please click here to go to this site's home page
Please click here to go to this site's search page

If i delete htacces it gives me this:

Not Acceptable

An appropriate representation of the requested resource /e107_plugins/tinymce4/plugins/e107/parser.php could not be found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I have checked the parser.php,it has the correct path,it is on the server, i reuploaded all tinymce but still the same problem.Any ideeas how to solve this??

Thanks.

**Comment by enddDD** [comment]
Hmm, disabling mod_security removes all my website problems, but it is safe to do this? Why does not work with it activated??

**Comment by CaMer0n** [comment]
Please check your mod-security logs. There must be a specific ruleset which is being triggered by Tinymce.

**Comment by CaMer0n** [comment]
Closing this as it is not related to e107, but server configuration.
