### ISSUE TITLE
user.php No entries

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#929]
http://defiantz.org/user.php    =   Nothing to show, Not pulling any users from the database.

**Comment by CaMer0n** [comment]
What does Debug with SQL Details tell you?

**Comment by LaocheXe** [comment]
Nothing at this time - says all queries are good.

**Comment by zekss** [comment]
This happens to me too. I solved it up an old version of the file "user.php" (before the latest updates of user.php). If you need it to solve for the moment, tell me.

After a few test, I Discover that the bug it is on this lines (72 to 85):


$USER_TEMPLATE = e107::getCoreTemplate('user');
e107::scStyle($sc_style);

if(empty($USER_TEMPLATE)) // BC Fix for loading old templates. 
{
	 echo "DEBUG: Using v1.x user template";
	include_once(e107::coreTemplatePath('user')); //correct way to load a core template.	
}


$TEMPLATE = str_replace('{USER_EMBED_USERPROFILE}','{USER_ADDONS}', $TEMPLATE); // BC Fix

$user_shortcodes = e107::getScBatch('user');
$user_shortcodes->wrapper('user/view');


I don't know exactly which is the problem, but well.. I hope it serves to solve it.

PD: I don't know how to post php code here haha, sorry.

**Comment by LaocheXe** [comment]
What was the fix you did last time?

**Comment by zekss** [comment]
Sorry for late answer. Well, I changed the code up (line 72-85) with the old code, that is this:


$qs = explode(".", e_QUERY);
$self_page =($qs[0] == 'id' && intval($qs[1]) == USERID);

include_once(e107::coreTemplatePath('user')); //correct way to load a core template.

$user_shortcodes = e107::getScBatch('user');


For now, is a solution.
