### ISSUE TITLE
URL Profiles: Forum

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#933]
Currently the Forum plugin has default of {E107_PLUGIN_ABS}forum/forum.php

Would like to maybe hid the e107_plugin folder - so forum/forum.php - I changed the rewrite url to SITEURL}forum/forum.php issue is forum icons no longer show plus when you click on a forum/thread/post you got the URL e107_plugins/forum.......

**Comment by CaMer0n** [comment]
I believe this is mostly complete.
