### ISSUE TITLE
Admin Area: Admin Log...

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#934]
In the Admin Area - Admin Log... link does nothing. you can click it as many times as you want and nothing happens. Even with the Statistic Logging enabled.

**Comment by chory** [comment]
Try with  e107_admin/admin.php

**Comment by LaocheXe** [comment]
<a onclick="expandit('adminlog')" style="cursor: pointer">Admin log ...</a>

**Comment by CaMer0n** [comment]
Could you please provide a screenshot of the link you mentioned?

**Comment by LaocheXe** [comment]
[img]http://defiantz.org/e107_media/2c9b99145a/images/2015-04/adminlog_screenshot.png[/img]
