### ISSUE TITLE
YouTube: Media Manager

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#935]
Suggestion: 
Admin Area -> Media Manager -> Preferences -> YouTube: Add a section to add YouTube User Name ex: https://gdata.youtube.com/feeds/api/users/default/uploads   "default would become e107" to view e107 youtube uploaded videos.

user name is also known as the channel name - so mine would be https://gdata.youtube.com/feeds/api/users/UCviqB5QL3SEUsMv-nRSMjug/uploads "UCviqB5QL3SEUsMv-nRSMjug"

Suggestion:
Add a section in Media Manager to view uploaded YouTube Videos from Presences YouTube User Name.

**Comment by willem010** [comment]
did you guys notice the api2.0 shutdown?
you will need to use the api3.0 to make youtube work again
