### ISSUE TITLE
Feature request: event triggering after plugin installation/uninstallation

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#936]
In my plugin, I would like to run a script after a plugin is installed/uninstalled to rescan plugin directories searching for e_XXX.php files. So, is there any event-triggering after plugin installation? And of course, after uninstallation.

**Comment by CaMer0n** [comment]
It sounds like something which could be done by e107 by default. There's already a method in place so it just needs to be called. Pull request welcome. :-)

**Comment by lonalore** [comment]
I inserted event triggerings into the code. Is it acceptable?

**Comment by Moc** [comment]
@lonalore You might want to declare this
```php 
$event = e107::getEvent(); 
```

at the top of the  install_plugin_xml() method. So you can then remove the occurrences of it on the separate lines (1637, 1643, etc.)

**Comment by lonalore** [comment]
Done! :) 

https://github.com/lonalore/e107/commit/d43d37575997fd7fd8d623005e8694472e727631

**Comment by CaMer0n** [comment]
It is only to scan for plugin addons after install/upgrade, correct?

**Comment by lonalore** [comment]
Yes! :) It is only to scan for e_nodejs.php addons, and I save the list of plugins into a plugin pref.
