### ISSUE TITLE
e107/e107_core/shortcodes/batch/comment_shortcodes.php

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#938]
Comment Ratings not working?

The COMMENT_RATE shortcode returns the class icon-thumbs-up and icon-thumbs-down but these are not the correct glyph codes.

I am using a Bootstrap 3 theme and have both font-awesome and glyphicons available which would require either glyphicon glyphicon-thumbs-up or fa fa-thumbs-up

Is this a bug or am I doing something wrong?

**Comment by CaMer0n** [comment]
Sounds like it's calling bootstrap2 glyphs. Added as a bug.

**Comment by CaMer0n** [comment]
They display for me, which theme are you using?

**Comment by pricey1981** [comment]
self-made theme based on Bootstrap3

**Comment by pricey1981** [comment]
aha, revisited theme.php and discovered I'd missed out

define("BOOTSTRAP", 	3);
define("FONTAWESOME", 	4);

Thanks for the indirect hint.
