### ISSUE TITLE
Feature request -> e_userprofile.php, allow more than one "text" item per caption

### ISSUE THREAD

**Issue by sbwMikael** [e107inc/e107#940]
Hi,

At present it is possible to add links to the bottom of a user profile page (user.php) by creating a plugin with a "e_userprofile.php" page. This works well. But at the moment each link is rendered below its own caption.

I'd like to be able to put several related links under a single caption, rather than one link per caption.

The relevant script appears to be in "\e107_core/shortcodes/batch/user_shortcodes.php" in the "sc_user_embed_userprofile" function, somewhere around line 800.

Thanks for considering this modification

**Comment by CaMer0n** [comment]
The correct addon file-type to use in v2.x is e_user.php (you can find examples in the chatbox and forum plugins. )
To add multiple links you could simply include a list in the 'text' variable. Either using 'ul' tag or just separated by line-breaks.

**Comment by sbwMikael** [comment]
Hi CaMer0n - thank you. That was a 3 a.m. thought process (actually this is too, but I'm slightly more lucid tonight... I hope), and soon as I went to bed I realised my mistake - as you suggested, adding line-breaks was all that was required. That's pretty embarrassing. Appreciate your help!
