### ISSUE TITLE
Carousel 'start' Question/issue ?

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#941]
When using (Bootstrap3 theme)  Carousel by means of featurebox; 
(not discussing cache issues with cat templ v2 vs v3)

When using bootstrap carousel V3 cat template  (sometimes v2 too)
The slider refuses to cycle (it will only trigger when manual clicked on next/prev glyph.

Now searching and being tipped by Yvalni, the issue seems to be an interval setting.
Both of us agree on not finding any relationship to this inside the system.

getbootstrap : javascript / carousel comment : 
interval    number  5000    The amount of time to delay between automatically cycling an item. If false, carousel will not automatically cycle.

Maybe it should be placed inside a js file (but which).
As a temp solution to vercome this, i manually added the next piece inside the bootstrap3 theme php : 
line 142 and up (bottom script piece)

// applied after every layout. 
$LAYOUT['_footer_'] = '  <hr>

<div class="row">
    <footer >
        <div class="col-lg-6">
            {NAVIGATION=footer} 
        </div>
        <div class="col-lg-6 text-right">
            {XURL_ICONS: size=2x}
        </div>
        <div class="col-lg-12 text-center">
            <small>{SITEDISCLAIMER}</small>
        </div>
    </footer>
</div>  

```
</div> <!-- /container -->
<script>
$(document).ready(function() {
     $(".carousel").carousel({
         interval: 2000
     })
});    
```

</script>
';

After applying this the slider runs.

**Comment by CaMer0n** [comment]
This should probably go in the featurebox category template.

**Comment by tgtje** [comment]
I believe this is solved in time (never heard anymore issues).. if needed reopen
