### ISSUE TITLE
Login/Logout not work

### ISSUE THREAD

**Issue by chory** [e107inc/e107#942]
Only can logout deleting the cookie, and only can loged me how admin in e107_admin/admin.php.
As a member I can not in any way.

![e107_log](https://cloud.githubusercontent.com/assets/4314070/6922657/168fb186-d7cd-11e4-8a83-f10618d98f40.jpg)

**Comment by CaMer0n** [comment]
Thanks for submitting this. I am unable to reproduce it myself. Could you please tell me more about your server configuration? ie. version of Apache/PHP.

**Comment by chory** [comment]
Apache 2.2.29
PHP 5.4.32
MySQL 5.5.34

**Comment by CaMer0n** [comment]
Thanks. Did you try switching user-tracking to 'sessions' ?

**Comment by chory** [comment]
OK, now can logout, but can't login me
![e107](https://cloud.githubusercontent.com/assets/4314070/6981094/a4d0c92c-d9fc-11e4-9576-7c4c0e40426d.jpg)

**Comment by CaMer0n** [comment]
Thank you. These screenshots are helpful.

**Comment by CaMer0n** [comment]
Please message me through Facebook. I will need to take a look at your setup directly to see what is going on.

**Comment by CaMer0n** [comment]
@chory You can now reach me by private-message by logging in at http://e107.org/developers

**Comment by chory** [comment]
OK

**Comment by CaMer0n** [comment]
Thanks, saw you logged in. Did you send me something?  (needs to be sent to 'admin')

**Comment by CaMer0n** [comment]
@chory - I took a look, and it seems your files are not up-to-date. My admin area has 3 options under "User registration system" in the preferences area. "Register & Login", "Login Only" and "Disabled". 
In the screenshot above, we can see that you only have 2: "Enabled" and "Disabled". Without a doubt - this is the cause of the issue you are having.

**Comment by chory** [comment]
I do not know why. I am using github on my computer, and when the files are updated on my computer, I upload these to the server.

**Comment by CaMer0n** [comment]
No worries. You could try using git clone from the server, and then syncing with github would be very easy - however this will only work with an empty folder.
