### ISSUE TITLE
Bug: Sub-forum Delete

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#949]
When deleting a Sub-forum - it gives me a white screen that says Forums top left corner. with link of this:
  http://defiantz.org/e107_plugins/forum/forum_admin.php?delete.19

**Comment by CaMer0n** [comment]
This is a work in progress - you can see it if you enable debug mode and go to the forum admin area.

**Comment by CaMer0n** [comment]
The forum-admin upgrades have been enabled. Please give it a try and let me know if you come across any issues. Thanks.

**Comment by LaocheXe** [comment]
I can now delete parents, forums, sub-forums. however the manager area seems to freak out when adding new parents and forums (tens to get out of order but when you leave the page and come back it fixes it self)

Also forum mod is always set to CONTACT PEOPLE when creating a new forums (that is just a little weird to me but not an issue)

**Comment by CaMer0n** [comment]
Thank you!. I may have made a recent commit that fixes the "CONTACT PEOPLE" thing. (For me it now defaults to "ADMIN").

**Comment by CaMer0n** [comment]
@LaocheXe If this is fairly stable I believe we can close this issue.
