### ISSUE TITLE
Featurebox problem

### ISSUE THREAD

**Issue by Ashguardian** [e107inc/e107#952]
Hello e107 Team!

I installed the featurebox plugin, and I created 3 contents (Tab1, Tab2, Tab3). I set them as a Tab, and added them a message (1. Tab message, 2. Tab message, 3. Tab message).
![fbox1](https://cloud.githubusercontent.com/assets/11802599/7011269/08d17cac-dca8-11e4-95a4-03ded7c72aa7.png)
The problem is, the Tabs do not display their content correctly.
Tab 1 displays 1. Tab message, but Tab 2 displays 1. Tab message (again), and Tab 3 displays 2. Tab message.
![tab1](https://cloud.githubusercontent.com/assets/11802599/7011283/26d821ce-dca8-11e4-8be6-98d00e7b2a46.png)
![tab2](https://cloud.githubusercontent.com/assets/11802599/7011285/2b57120a-dca8-11e4-98f0-d8ab23dc829a.png)
![tab3](https://cloud.githubusercontent.com/assets/11802599/7011289/3168ce5e-dca8-11e4-9c5b-61e1d453b8eb.png)

**Comment by CaMer0n** [comment]
@Ashguardian Thanks for the screenshots - it should be working as intended now.

**Comment by Ashguardian** [comment]
Yes, it is working fine now! Thank you for the fix!
