### ISSUE TITLE
Users unable to sign up with public email addresses

### ISSUE THREAD

**Issue by rickleib** [e107inc/e107#953]
Folks,

I'm stumped here. No one can sign up on our site, it appears to be only with Yahoo, Gmail, Outlook, Live, AOL and the other freebie email sites.

The error they get is "That does not appear to be a valid email address". 

Help ... Please!!!

Thank you in advance for any help.

**Comment by LaocheXe** [comment]
Odd.

I just tested it on my site and it works with a gmail, Even tested it with Check remote servers when validating email addresses.enabled.

Are your users trying to sing up using social media options, I see AOL, Yahoo, Live (Outlook), and Google (Gmail).

**Comment by rickleib** [comment]
No sir, direct sign up on the site. 

http://blaksheepgamers.com  check it out.

**Comment by CaMer0n** [comment]
Sorry to hear of the troubles you're having. Please go to System Logs, and enable "Rolling Log" on Signup and see if that returns some useful information.

**Comment by CaMer0n** [comment]
Btw, I would switch off "Check remote servers when validating email addresses.", if you have it enabled- it could cause symptoms like that.

**Comment by rickleib** [comment]
This worked! Thank you very much!

**Comment by CaMer0n** [comment]
You're welcome!
