### ISSUE TITLE
Question: Plugin Admin Config Tabs

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#955]
I am editing a plugin builder admin config for my plugin, I see that protected $tabs is commented out, and says Use 'tab'=>0 OR 'tab'=>1 in the $fields below to enable.

Does that mean after all the other stuff to do the tabs, so like

protected $fields = array ( 'checkboxes' =>   array ( 'title' => '', 'type' => null, 'data' => null, 'width' => '5%', 'thclass' => 'center', 'forced' => '1', 'class' => 'center', 'toggle' => 'e-multiselect',  ), 
ETC....
'options' =>   array ( 'title' => 'Options', 'type' => null, 'data' => null, 'width' => '10%', 'thclass' => 'center last', 'class' => 'center last', 'forced' => '1',  ),
'tab'=>1

?????

I'd like an example - I want to add 3/4 tabs up on top - while creating/editing data - (So making a new entry (server details) - after giving IP, Port, and some other stuff - go to Tab 3 (Named: TeamSpeak 3 Viewer) that has the options to add query port, query user, query pass)

**Comment by CaMer0n** [comment]
Please find any plugin which has an admin area with tabs, and you'll find a full example in its corresponding file. The 'tab'=>1 goes inside the field eg: 
 
    'my_field' => array('title'='Name', type'=>'text', 'tab'=>1, ......

**Comment by LaocheXe** [comment]
I see, I did that - but when it comes to submit changes it gives a database error - SQL Error #1054: Unknown column 'voice_qname' in 'field list'

Have no idea why it's doing that.
