### ISSUE TITLE
Bug: The login issue has returned.

### ISSUE THREAD

**Issue by rwjework** [e107inc/e107#957]
After updating to a new install of Beta1 I have a problem logging in as admin. The only file I kept in the clean update was the old e107_config.php. I uploaded everything else and then deleted the install file. I logged in closed the browser and then opened it again. It asked me to log in again and when I tried all I get is a hang - white screen trying to load the specified page. I know the page exists as it is the same page I start with. I tried logging in through the back way e107/e107_admin/admin.php and it just blanks out what I have submitted and asks for the password again. This appears to be an Internet explorer and Google Chrome issue as both lock me out.

**Comment by rwjework** [comment]
Admin account made through install cannot log in through e107/login.php #343 was the initial Bug. However I know that I have Plaintext as my setting prior to the install. So it is a different issue.

**Comment by rwjework** [comment]
A little bit more information on the errors I am getting when trying to log into e107/e107_admin/admin.php. Any help would be appreciated
The value "device-width;" for key "width" is invalid, and has been ignored.
admin.php:6 The value "1;" for key "initial-scale" was truncated to its numeric prefix.
admin.php:6 Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
admin.php:11 Mixed Content: The page at 'https://XXXX/e107/e107_admin/admin.php?failed' was loaded over HTTPS, but requested an insecure stylesheet 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css'. This request has been blocked; the content must be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://www.XXXX/e107/e107_admin/admin.php?failed' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
admin.php:1 Mixed Content: The page at 'https://www.XXXXX/e107/e107_admin/admin.php?failed' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap.min.js?1428580671:6 Uncaught TypeError: undefined is not a function
jquery.zrssfeed.min.js?1428580671:8 Uncaught ReferenceError: jQuery is not defined
bootstrap-editable.min.js?1428580671:5 Uncaught TypeError: Cannot read property 'fn' of undefined
bootstrap-select.min.js?1428580671:1 Uncaught TypeError: Cannot read property 'fn' of undefined
bootstrap-multiselect.js?1428580671:201 Uncaught TypeError: Cannot read property 'fn' of undefined
jasny-bootstrap.js?1428580671:478 Uncaught TypeError: Cannot read property 'fn' of undefined
bootstrap-datetimepicker.min.js?1428580671:1 Uncaught TypeError: Cannot read property 'fn' of undefined
jquery.h5validate.min.js?1428580671:1 Uncaught ReferenceError: jQuery is not defined
jquery.elastic.js?1428580671:162 Uncaught ReferenceError: jQuery is not defined
jquery.at.caret.min.js?1428580671:2 Uncaught ReferenceError: jQuery is not defined
jquery.pwdMeter.js?1428580671:198 Uncaught ReferenceError: jQuery is not defined
bootstrap-tag.js?1428580671:160 Uncaught TypeError: Cannot read property 'fn' of undefined
admin.jquery.js?1428580671:1 Uncaught ReferenceError: $ is not defined
all.jquery.js?1428580671:4 Uncaught ReferenceError: $ is not defined
admin.php?failed:165 Uncaught ReferenceError: jQuery is not defined
admin.php?failed:224 Uncaught ReferenceError: $ is not defined

**Comment by CaMer0n** [comment]
And if you disable https, do the same errors occur?

**Comment by rwjework** [comment]
Thanks for coming back to me. I have never done this in Chrome. In Explorer I have SSLv3 disabled. Would this have caused the error?

**Comment by rwjework** [comment]
In Internet Explorer under the security and HTTP settings on the browser I have the following:-
Check for signatures on downloaded programs - ticked
Enable DOM Storage - ticked
Enable Integrated Windows Authentication - ticked
Enable Native XMLHTTP support - ticked
Use TLS1 - ticked
Use TLS1.1 - ticked
Use TLS 1.2 - ticked
Warm if POST submittal is redirected to a zone that does not permit posts - ticked
All the remainder are unticked.
HTTP Settings are both ticked
What do you want me to try to test to see what might change the errors?
Thanks again for coming back to me

**Comment by CaMer0n** [comment]
Under admin->preferences->security you should find a setting for SSL. Please make sure it is disabled.

**Comment by rwjework** [comment]
Thanks.The problem is I can't get in to the admin area. Is there a way of checking this through PHPMyAdmin?

**Comment by CaMer0n** [comment]
Yes, first backup your DB, then go to the e107_core table. Edit the record marked 'SitePrefs' so that 'ssl_enabled' looks like this: 

     'ssl_enabled' => '0',

Also, go to your cache folder (e107_system/xxxxx/cache/content ) and delete 'S_Config_core.cache.php'

**Comment by rwjework** [comment]
Thanks.The ssl_enabled was already 0. Deleting the file does not make any difference. Any thoughts

**Comment by CaMer0n** [comment]
Have you updated with the latest files from here on Github?

**Comment by Moc** [comment]
@rwjework please re-test using the latest files from Github
