### ISSUE TITLE
Bug: Forums

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#958]
I don't think it is the theme, but notice a few issues in the forums.

1. User Avatar is width:100px, and height:px (no height number entered).
2. forum_viewforum.php - forum image icon is not lining up right with the table, 
3. forum_viewforum.php - table height is a little to high.

http://defiantz.org/e107_plugins/forum/forum_viewforum.php?id=35

**Comment by CaMer0n** [comment]
Does your theme use forum templates?

**Comment by LaocheXe** [comment]
It uses the Bootstrap 3 theme - I don't think it does

**Comment by CaMer0n** [comment]
The current forum template with bootstrap running is responsive and will drop columns when resized. This doesn't seem to be the case with your theme. If you switch to the default bootstrap3 theme, is the problem mentioned above visible?

**Comment by LaocheXe** [comment]
Well seems it's my theme - going have to fix it myself it seems - sorry about this, bug on my part
