### ISSUE TITLE
Downloads plugin does not recognize filetypes.xml + LAN issue

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#959]
Updated file types, can Upload via uploads.php but in admin area plugin downloads upload do not notice the new file types added to the xml.

**Comment by LaocheXe** [comment]
Also the LAN for previous file is not right, just shows the LAN_18 as the text

**Comment by Jimmi08** [comment]
@LaocheXe @Moc  Could you check title of this issue to see without opening what about is it? Thanks

**Comment by Moc** [comment]
Related #550

**Comment by Moc** [comment]
Closing as duplicate of #550. I cannot reproduce the LAN issue anymore.
