### ISSUE TITLE
Blank Popup For Guests

### ISSUE THREAD

**Issue by halfwolf102** [e107inc/e107#960]
I just updated from v1.0.4 to v2 beta 1 and I'm having an issue. As a guest, I get a blank popup on every page on my site. 
![screenshot_2015-04-11-02-42-29](https://cloud.githubusercontent.com/assets/11897424/7100720/1a672d7a-dff7-11e4-9025-0e94977d28d0.png)
(Note the picture is from a mobile device, the desktop popup is slightly different) This wasn't happening before and I don't know what's causing it. Anyone have any ideas?

**Comment by tgtje** [comment]
javascript message ( alike This web site requires that javascript be enabled. Click here for instructions..)
Also previous mentioned at : http://www.e107help.org/590/problem-javascript-alert-in-all-pages

**Comment by halfwolf102** [comment]
For anyone having the same issue, I figured out a quick fix so the statistics plugin can be used without the popup. In the statistic logging plugin folder (log), open e_meta.php and find the following:
	$.ajax({
		type: 'get', 			
		url: url,             
		data: {'lv' :logString},              
		success: function(e) {         
			if(e)
			{
				alert(e);
			}
		}
	});
});
";
then remove this:
			if(e)
			{
				alert(e);
			}
and you will no longer receive a popup message when the plugin is enabled.
