### ISSUE TITLE
Feature Request: Main Parent User Classes

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#961]
I notice two main parent user classes (Everyone, and Inactive) - Maybe allow it so admin can add others etc.

So I'd want to add a main parent called Developers, then add other user classes to that.

Right now I have something like that set up but Developers is under the Inactive parent.

**Comment by Moc** [comment]
Using the hierarchical user class structure, this should be possible. Closing for now, unless you have additional questions.
