### ISSUE TITLE
Bug/Maybe: fallback sitelogo

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#962]
I have updated my testing site code - seems the site logo no longer shows in bootstrap3 theme (site logo selected in site pref's area. I don't know if this was being changed and wip or what - I notice the changes in the shortcodes_theme.php but believe that siteinfo plugin e_shortcode.php handles the fallback sitelogo correct?

**Comment by CaMer0n** [comment]
The default bootstrap theme was modified to allow a logo and/or sitename in the header. This can be set in the theme 'preferences' under 'Branding'

**Comment by LaocheXe** [comment]
Awesome - can you add an option to re-size the logo?

**Comment by CaMer0n** [comment]
It should auto-resize to fit the header.

**Comment by LaocheXe** [comment]
True it looks like it does - but take a look:
http://www.defiantz.org   (not resized header/logo (old code)
http://indev.defiantz.org (resized to fit header (newer version of code)

http://outcastprison.vlink.click     <--- old version of code, logo image was made that size - looks pretty good to me.

**Comment by CaMer0n** [comment]
It looks like you need to crop your logo to remove the extra space around it.

**Comment by LaocheXe** [comment]
That's the ting - it be nice to have the option to resize it so it's not all smushed up - right now I changed the height via theme_shortcode.php Changed SITELOGO: h=30 to SITELOGO: h=70 to get what I have now and changed the Width in css.

**Comment by Jimmi08** [comment]
@Moc  I think that this can be closed. There was some commit regarding sitelogo with F.Barry fix.

**Comment by Moc** [comment]
@LaocheXe Can you re-test this to see if the issue has been resolved?
