### ISSUE TITLE
Bug - Cannot config Social Plugin

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#965]
Fatal error: Cannot use string offset as an array in /home/***/domains/***/public_html/v2/e107_plugins/social/e_admin.php on line 15

Github of today.. 15-04-2015 6842 commits

**Comment by CaMer0n** [comment]
Thanks, will check it out.

**Comment by LaocheXe** [comment]
I have a version of e107 2.x from yesterday and have no issues with the plugin.

**Comment by CaMer0n** [comment]
@Alex-e107nl this should fix it. Please let me know. Thank you.

**Comment by Alex-e107nl** [comment]
Solved! Thx... I follow what you do and man what do you work hard! Compliments!

**Comment by CaMer0n** [comment]
Thank you @Alex-e107nl , I appreciate the positive feedback.

**Comment by MikeyGMT** [comment]
Odd it I pulled down the full install zip today and Social and Featurebox break the front end and neither can be configured - blank page. Enabled Dev Mode pref and found the old e107 Debugger chrome extn, and they don't work either. Sorry Mikey

**Comment by CaMer0n** [comment]
I had nothing to do with the chrome extension - I suggest using the Firefox one.

**Comment by CaMer0n** [comment]
@MikeyGMT Could you send me a URL of the broken front-end?

**Comment by MikeyGMT** [comment]
gmailed you Cam :)

**Comment by CaMer0n** [comment]
Fixed. @MikeyGMT  btw. the error was stored in e107_plugins/social/error_log and the root directory error_log (after I enabled debug and viewed news.php )

**Comment by MikeyGMT** [comment]
Perfect thank you Cam!
