### ISSUE TITLE
Bug: Forum - LAN Admin Status

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#966]
The Admin Area - Admin Status - Forum is showing ADLAN_113

**Comment by CaMer0n** [comment]
Global search of the entire core doesn't return any results for "ADLAN_113". Could you please check your DB tables for this value?

**Comment by LaocheXe** [comment]
https://github.com/e107inc/e107/search?utf8=%E2%9C%93&q=ADLAN_113

Looks like it's been commented out

**Comment by CaMer0n** [comment]
Indeed, it's commented out, but it is not called anywhere from what I can see, that's why I'm thinking it must be in the database (plugins table?)

**Comment by LaocheXe** [comment]
I see nothing about that in the db, I updated my main site code and it isn't there on that one. but I no longer see a section for the forum post status section.
