### ISSUE TITLE
Bug: Submitted News Admin Area

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#967]
e107_admin/newspost.php

Submitted News

News Item Title Mouse Over Tool Tip shows LAN_PREVIEW

Also request:
Submitted News section shows little information (Does not show author etc or even an edit button)

Got a news item submitted and it is in Spanish and I have no idea who submitted it.

**Comment by CaMer0n** [comment]
Did you enable 'author' on the display column ?

**Comment by LaocheXe** [comment]
I do not see an option to do so, my main site code is not fully up to date (last update was a month ago)

**Comment by CaMer0n** [comment]
Little arrow next to 'options'. ;-)
