### ISSUE TITLE
Bug: Install Plugin

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#970]
New plugin which I used the plugin builder -  got an error when installing the plugin 

Can't read SQL definition: ../e107_plugins/arma3life/arma3life_sql.php
<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/a3l_sql.png" />

**Comment by LaocheXe** [comment]
Oh I see the issue now, CREATE TABLE IF NOT EXISTS is the issue. Never mind.

**Comment by CaMer0n** [comment]
Have re-opeened this, as others will experience the same no doubt. It should be easy enough to strip-it-out during the install.
