### ISSUE TITLE
Bug: Featurbox - Bootstrap

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#971]
I notice that with just Bootstrap selected while making a Featurebox, in the content area I added and image and use the bb code to center it but it wont center at all.

**Comment by Moc** [comment]
Do you have TinyMCE installed?

**Comment by LaocheXe** [comment]
Yes

**Comment by Moc** [comment]
Is this still an issue in the latest version?

**Comment by LaocheXe** [comment]
I don't know, don't use the fbox anymore
