### ISSUE TITLE
Chatbox messages and moderation

### ISSUE THREAD

**Issue by Ashguardian** [e107inc/e107#972]
Hi!

I have found some chatbox issues in the latest e107 version, fresh install.

I installed the chatbox plugin:
![cb_admin](https://cloud.githubusercontent.com/assets/11802599/7219724/13bc1d88-e6ae-11e4-9458-85b9766e4047.png)

1.problem is, I can't moderate the chat, got this message:
![cb_error](https://cloud.githubusercontent.com/assets/11802599/7219726/3f21a60a-e6ae-11e4-90e8-3f7c427c316d.png)
I tried different userclass options, but I got the same message.

2.problem is, the displayed number of messages.
I posted six messages for example:
![cb](https://cloud.githubusercontent.com/assets/11802599/7219740/e4cd9c8a-e6ae-11e4-8903-19529d78b533.png)
If I set chatbox posts to display 5 -> all messages displaying
If I set chatbox posts to display 10 -> only 1 message (6th) displaying
If I set chatbox posts to display 15 -> 2 messages (5th and 6th) displaying
and so on.

**Comment by CaMer0n** [comment]
Please re-open if this problem persists.
