### ISSUE TITLE
You are not authorized to post to this forum message appearing

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#973]
Hi all,

We just ran the latest update from github on our site and whenever you either edit someone's post, or try to post a reply (so, whenever it tries to go to /e107_plugins/forum/forum_post.php), an error appears - "You are not authorized to post to this forum."
My user account is an admin account. Have tried from other people's (also admin) accounts; same error is coming up. 

I tested this on a new vanilla install locally, and couldn't replicate - however, I also tested on the entire github fileset but on my existing database (again locally), and the error was there - so it's like, an error on an upgraded site, not on a new one. 

Let me know if you want any more info, but are you able to replicate / look into? We reverted the /forum plugin back to the previous version we had installed to get rid of the problem on the live site.

Cheers,
Min

**Comment by CaMer0n** [comment]
Thank you Min. If you 'edit' the forum settings (in admin) and re-save the permissions etc, does it correct the issue? Are you able to check the DB tables directly via phpmyadmin?

**Comment by CaMer0n** [comment]
Tested a v1.x -> v2.x forum upgrade and was unable to reproduce. :-/

**Comment by martasalek** [comment]
I'll have time to investigate further on Sunday night. I'll have a look at the database and report back if I find anything.

**Comment by Minnn** [comment]
I was thinking Marta that we might be able to test on a cut back version of our DB (like, 3 forum posts or something) and put online so the e107 guys can see too. I'll try get it up some time this week...4 month old baby permitting.

**Comment by martasalek** [comment]
Good luck, Min... :). But it would be interesting to know if it seems like a user class thing or a volume of posts thing.

**Comment by Minnn** [comment]
Hey Cameron - I've created a test environment which uses:
- a (very) cut back version of our database (ie, all our tables are there, but I've cleared the content out of nearly everything),
- the latest github version of e107 (as of 23/04/2015),
- our theme (just bootstrap, with some extra styling). 
Can I set up a user account for you so you can see the issue? If you could send me an email at minn.dean@gmail.com I can send you some authentication details since our test site is behind a password wall.

**Comment by CaMer0n** [comment]
Thank you! Please make sure it is installed via 'git clone' - it will be MUCH easier to update that way.

**Comment by Minnn** [comment]
Thanks for the email - I'll send you the test site details today (I have a rather relentless 4 month old baby so I don't get to do much online (apart from on my phone) anymore - at least until nap time). 
It's not been installed using gitclone, sorry - I wasn't aware of such a thing. I'll look into changing it to use that later.

**Comment by Minnn** [comment]
I've sent you an email with all the authentication details you'll ever need for our test site - but to see this issue we're talking about, log in, head to Forums > Members Message Board > Test topic and try to edit my post. The error should appear for you then.
I've tried updating the forum permissions, plus I've also done db validity checks ("tables appear to be ok!" returns).

**Comment by Minnn** [comment]
Confirmed resolved! Thanks Cameron.

**Comment by CaMer0n** [comment]
You're welcome! :+1:

**Comment by martasalek** [comment]
And the new forum updates have fixed the 'Quote' function too :). Yay! Great work, Cameron :).

**Comment by CaMer0n** [comment]
Thanks Marta. :-)

**Comment by dmitripot** [comment]
Still issue for editing posts after forum db upgrade from 1.x to 2.
