### ISSUE TITLE
Bug in usersettings

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/e107#974]
Logged in as admin, trying to edit usersettings from another user:

http://www.team-aero.org/usersettings.php?3

Fatal error: Call to undefined function parse_admin() in G:\webservers\htdocs\www\e107_admin\header.php on line 634

Logged in as current user:

http://www.team-aero.org/usersettings.php
Trying to update extended userfields Country, Gender, Birthday, Language

Save/update doesn't send to database:

System Debug

Existing User Info
Array
(
    [user_id] => 4
    [user_name] => Crytiqal
    [user_loginname] => crytiqal
    [user_customtitle] => 
    [user_password] => mypassword
    [user_sess] => 
    [user_email] => crytiqal@live.com
    [user_signature] => 
    [user_image] => 
    [user_hideemail] => 0
    [user_join] => 1425155352
    [user_lastvisit] => 1427026063
    [user_currentvisit] => 1429545677
    [user_lastpost] => 0
    [user_chats] => 0
    [user_comments] => 0
    [user_ip] => 0000:0000:0000:0000:0000:ffff:4da1:aab0
    [user_ban] => 0
    [user_prefs] => 
    [user_visits] => 4
    [user_admin] => 0
    [user_login] => Hugo Cox
    [user_class] => 23,253,251,0
    [user_perms] => 
    [user_realm] => 
    [user_pwchange] => 0
    [user_xup] => 
    [user_forum_oldtimestamp] => 0
    [user_forum_newtimestamp] => 0
    [user_forum_newposts] => 0
    [user_extended_id] => 
    [user_hidden_fields] => 
    [user_plugin_forum_viewed] => 
    [user_plugin_forum_posts] => 
    [user_country] => 
    [user_gender] => 
    [user_birthday] => 
    [user_language] => 
    [last_ip] => 
    [user_token] => 66705064b387572428517e38ae23e0195535225bc1c5e9.36820681
    [user_baseclasslist] => 23
    [user_classlist] => 23,253,251,0
)

$allData
Array
(
    [user_name] => Crytiqal
    [user_login] => Hugo Cox
    [user_image] => 
    [user_email] => crytiqal@live.com
    [user_signature] => 
    [user_hideemail] => 0
)

Posted Changes
Array
(
)

Processed Posted Changes
Array
(
)

Eventho I updated those extended fields with new values.

**Comment by Crytiqal** [comment]
In the admin area for extended user fields:

PHP Errors:
Warning: mysql_fetch_row() expects parameter 1 to be resource, boolean given, Line 363 of G:\webservers\htdocs\www\e107_admin\users_extended.php

**Comment by CaMer0n** [comment]
Thanks for posting. Could you tell me what you did to be redirected to "http://www.team-aero.org/usersettings.php?3" ? Currently all use editing is done in e107_admin/user.php

**Comment by Crytiqal** [comment]
Logged in as Admin:
In the navigation bar user panel, click on "Profile"
(http://www.team-aero.org/user.php?id.1)

-> next member x2
(http://www.team-aero.org/user.php?id.3)
Click here to edit this user's information

http://www.team-aero.org/usersettings.php?3 - User Settings - LAN_head_4 :: Team-Aero&trade;

× 
 


Loading…

Close 

Fatal error: Call to undefined function parse_admin() in G:\webservers\htdocs\www\e107_admin\header.php on line 634

**Comment by Crytiqal** [comment]
In the admin area, editing the user's extended fields aren't working properly either;
They all default to text input fields, while the country should be a dropdown list, gender a radio button, birthday a calendar input and language also a dropdown list.

**Comment by CaMer0n** [comment]
For user-extended in admin, you need to switch off debug - because it currently enables a work-in-progress version of the admin area.

**Comment by Crytiqal** [comment]
http://www.team-aero.org/e107_admin/users.php?mode=main&action=edit&id=4#/tab1
Still shows text input fields, instead of corresponding input fields

**Comment by CaMer0n** [comment]
If you find other issues, please create a new issue. Thank you @Crytiqal
