### ISSUE TITLE
Bug: Forums Post Blank Page

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#975]
Today I went to post a new thread and when hitting the Post button a blank page appears.

Post name was Useful Scripts   In the area I added two links with the links bbcode.

Blank Page after adding the post - post does not get written to the database. So I tried again and added some words before the links and same thing, tried again with just words no links and it works, but editing to add the links is a no go, blank page, tried preview and got a blank page as well so I turned on my e107 Debugger on (Mozilla FireFox Plugin),

Going to the Forums, Sub-Forum, view topic and System Debug shows a 'Could not parse Shortcode ../../e107_core/shortcodes/single/user_extended.cs :: {USER_EXTENDED} 

<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture1.png">

I went and editing a post and typed out the link bbcode to google.com

<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture2.png">

Which worked for Preview

<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture3.png">

Tried adding other links via bbcode and got this
<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture4.png">

**Comment by LaocheXe** [comment]
NOTE: Have not updated the main code in the last two weeks and had no issue last week posting more than one link but the links where in a List

**Comment by LaocheXe** [comment]
So going more into it - typed out the link bb code and added the links I wanted and blank page- then I just tried to past the links in with no bbcode and same issue, then I type random stuff and it worked.

Links I tried to put in are from KK's Blog
http://killzonekid.com/arma-extension-url_fetch-dll-v2-0/
and
http://killzonekid.com/arma-scripting-tutorials-url_fetch-callback/

I don't know why but the forum topic wont write to the database with the links in the text area.

**Comment by CaMer0n** [comment]
Thanks for this. I tried posting with your links and was unable to reproduce. Could you please send me a screenshot of Admin -> Preferences -> Text Rendering? Also, are you logged in as admin or a regular user?

**Comment by LaocheXe** [comment]
<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture5.png">

I am logged in as the main admin

**Comment by LaocheXe** [comment]
Update: After adding newer version of the e107 code - this bug is still effecting my website.

**Comment by CaMer0n** [comment]
I see that you don't have TinyMce on the front-end - is it uninstalled?

**Comment by LaocheXe** [comment]
As far as I can tell it might have been server side issue now, it no longer happens. I do have a free web host so that might have been the issue.
