### ISSUE TITLE
LiveInternet counter

### ISSUE THREAD

**Issue by heymukki** [e107inc/e107#980]
Hello , I have this code

<script type="text/javascript"></script>

and I Do not know how to install it in the footer . When I put in the "Site Disclaimer" page is not available then.
sorry for my bad english

**Comment by CaMer0n** [comment]
Try wrapping it in [html] [/html] tags.

**Comment by CaMer0n** [comment]
@heymukki Did this resolve your issue?

**Comment by Moc** [comment]
Closing due to lack of feedback, please let us know if this needs to be reopened
