### ISSUE TITLE
New alternative for hiding clickable e-mail address

### ISSUE THREAD

**Issue by nlstart** [e107inc/e107#981]
e107_core/bbcodes/email.bb  line 13 
Current method is splitting up clickable e-mail address and displaying as such in mouse-over information. Visitors may think the information is not correct or even malicious.

Alternative; disguise the e-mail information as base64 encoded so e-mail harvesting robots won't be able to detect it, e.g. the html code that should be parsed:
``` 
<script type="text/javascript">
var x = Base64.decode("eW91ci1lbWFpbEBkb21haW4udGxk"); // Remove this comment line: the variable x is the encoded value of "your-email@domain.tld"
document.write("<a href=\"" + "mailto:" + x + "\">" + x + "</a>");
</script>
```

**Comment by CaMer0n** [comment]
looks good! I believe a generic js function with a css selector will do the trick.

**Comment by CaMer0n** [comment]
@nlstart I'm going to close this as I found another method which uses only CSS and PHP.
