### ISSUE TITLE
Bug: Flash BBCode+

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#982]
I got a Welcome Message for a user class - with some code for navigation and flash bbcode

The issue is that it displays the flash twice code is

{NAVIGATION=alt}
[center][flash=800,400]/flash/countdown/dg-clock2.swf[/flash][/center]

<img src="http://defiantz.org/e107_media/2c9b99145a/images/2015-04/capture_twoflash.png"></img>

Other Welcome Messages (guest etc) has the same Flash BBCode but noting for NAVIGATION and so no Double Flash

**Comment by CaMer0n** [comment]
Thanks. Does the same thing occur with regular text (instead of the flash bbcode) ?

**Comment by LaocheXe** [comment]
Nope

**Comment by CaMer0n** [comment]
Could you please post the full URL to your flash file so I can test with it here? Thanks

**Comment by LaocheXe** [comment]
defiantz.org/flash/countdown/dg-clock2.swf

**Comment by Moc** [comment]
@LaocheXe Is this issue still present?

**Comment by CaMer0n** [comment]
I did test with that URL at the time, but I don't remember the outcome. :/

**Comment by Moc** [comment]
Please re-open if this is still an issue in the latest version
