### ISSUE TITLE
Bug: signup.php stage1

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#984]
Top 3 text areas are blank (no one knows what to put there)

<img src="https://scontent-ord.xx.fbcdn.net/hphotos-xft1/v/t34.0-12/11134217_10100948997513638_1176554242_n.jpg?oh=1913afc3fddd7bd254c674bc385a80b0&oe=553C9B11"></img>

**Comment by CaMer0n** [comment]
Appears to be a backwards-compatibility issue.

**Comment by CaMer0n** [comment]
Was able to reproduce after fresh install. - looking into it.
