### ISSUE TITLE
Question: e_url.php 

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#987]
On the http://e107.org/developer-manual/plugin-basics/extending-core-functionality
It says to check out Plugin Gallery URL folder for an example, but that shows two files and no e_url.php

I checked out all the URL Configurations and check the plugins for e_url.php and only see Forums that have it. I look at it and can't understand why have that plus a folder called url with url.php and rewrite_url.php - is e_url.php old and no longer being used or am I over thinking this?

If I just have a plugin called dogs, and only have e_url.php will it show up in the admin area with the URL Configurations?

It is hard to understand in my opinion (but im not the brightest person around here) it's a little confusing. 

			'regex'			=> '^dogsref-(.*)/?$',
			'redirect'		=> '{e_PLUGIN}dogs/ref.php?ref=$1',
^^^^^^ What does that tell me? What I am trying to get at, (from looking at the forums) is e_url.php has simple mod-rewrite and has a url folder with two other php files, in URL Configurations section it list me two options to chose from, Default and Friendly, yet for Custom Pages is shows 3 Friendlies etc. So does e_url.php needed or just url.php and rewrite_url.php?

**Comment by lonalore** [comment]
The "url" folder with the "url.php" and "rewrite_url.php" files is an old method to implement SEF urls. Now, you should use only "e_url.php", and you should generate URLs with e107:url().

**Comment by LaocheXe** [comment]
Thanks for the reply, that has cleared much of it up for me.
