### ISSUE TITLE
Issue: Search

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#989]
While testing, I was in the members page (user.php) looking at the list of users on the site. To test if the search works I typed in battlefield (since I have a news post about Battlefield Hardline) and it shows nothing.

http://defiantz.org/search.php?q=battlefield&s=1&r=0&in=&ex=&ep=&be=&t=all

I have selected Search In All sections and yet it says on the page: "Results in Members
No matches found"

I don't know if it is searching just in the user database for battlefield or what, so I tried searching for fire and same results. I typed LaocheXe and get my user id, user name, and signature.

So the issue is that the search function only searches the users, not all area, and tried google but shows nothing under the page (no results) and changes back to all areas

**Comment by CaMer0n** [comment]
Please check admin -> Search - to see which areas are enabled for searching.

**Comment by LaocheXe** [comment]
Every thing is set to every one - In the admin area I notice this: Searchable Comments Areas (when comments search is activated)

Under it is News and then ADLAN_24

**Comment by CaMer0n** [comment]
The link above shows 2 results for 'battle' under 'news' for me.

**Comment by LaocheXe** [comment]
That's odd, wonder why it works now
