### ISSUE TITLE
Possible incorrect cron instructions

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#990]
In the 'schedule tasks' section, the info box on the left instructs the following cron command:

path token=1234 >/dev/null 2>&1

When doing so, I receive an email saying that the cron is misconfigured. It lists:

Sent from cron: token=1234
Stored in e107: 1234

When removing the `token=` part from the cronjob command in my control panel, it all seems to work OK.

**Comment by CaMer0n** [comment]
Depends on the server. I'll add a filter in there which should make it more compatible.
