### ISSUE TITLE
Feature request: (Form API) textfield that uses autocomplete

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#991]
I think, it would be great if e107 core would support an "autocomplete" option for textfield in Form API. 

This Bootstrap 2/3 plugin looks promising: https://github.com/timschlechter/bootstrap-tagsinput
Examples: http://timschlechter.github.io/bootstrap-tagsinput/examples

And... for example if an "autocomplete_path" is set in the options array of text(), e107 would attach the "bootstrap-tagsinput" library to the page, and generate an inline javascript code for the generated input field...

Set an autocomplete path for the textfield:
```php
$frm = e107::getForm();

$frm->text('my-autocomplete-field', 'current_value', 100, array(
	'size' => 'large',
	'autocomplete_path' => e107::url('plugin', 'autocomplete', $data),
));
```
And a javascript for the textfield:
```javascript
jQuery('input#my-autocomplete-field').tagsinput({
  typeahead: {                  
    source: function(query) {
      return jQuery.get('autocomplete_path......');
    }
  }
});
```

**Comment by lonalore** [comment]
Other solution: Provide an ability to alter form element methods (e.g $frm->text())... and by 3th party plugins we can provide the ability to use different kind of autocomplete solutions, or multiselect solutions for select fields... etc. :)

**Comment by CaMer0n** [comment]
There is something called 'typeahead' which is currently used by the 'userpicker' method in $frm. 
I believe you could also send: 
options = array('data-mytrigger'=>'my-data'); to the text() method.

**Comment by lonalore** [comment]
Hmm... so if I understand, I should create an autocomplete textfield with a custom path like this way:

```php
$frm = e107::getForm();

$frm->text('my-autocomplete-field', 'current_value', 100, array(
    'typeahead' => 'custom',
    'data-source' => e_BASE . 'something/path',
));
```

but in the "form_handler.php" (line 403 - 410) the code only allows "typeahead" with "users" value:

```php
if(vartrue($options['typeahead']))
{
    if(vartrue($options['typeahead']) == 'users')
    {
        $options['data-source'] = e_BASE."user.php";
        $options['class'] .= " e-typeahead";
    }
}
```

...so I think need to modify it like:

```php
if(vartrue($options['typeahead']))
{
    if(vartrue($options['typeahead']) == 'users')
    {
        $options['data-source'] = e_BASE."user.php";
        $options['class'] .= " e-typeahead";
    }
    elseif(vartrue($options['typeahead']) == 'custom' && isset($options['data-source']))
    {
        $options['class'] .= " e-typeahead";
    }
}
```

Can I modify "form_handler.php" if this works properly?

**Comment by lonalore** [comment]
After a cup of coffee I just realized that this solution should work too:

```php
$frm = e107::getForm();

$frm->text('my-autocomplete-field', 'current_value', 100, array(
    'class' => 'e-typeahead',
    'data-source' => e_BASE.'something/path',
));
```

I try it today. :)

**Comment by lonalore** [comment]
On the other hand, this Typeahead plugin doesn't work if I use the Bootstrap 3.1.0 theme, because this typeahead js is only included in Bootstrap 2x.

Finally, I decieded to use "Bootstrap Tags Input" with "Typeahead", so I include CSS and JS files in my e_header.php

```php
if (BOOTSTRAP == 3) {
	e107::js('qna', 'js/libraries/bootstrap3-typeahead/bootstrap3-typeahead.min.js');
}
e107::css('qna', 'js/libraries/bootstrap-tagsinput/bootstrap-tagsinput.css');
e107::js('qna', 'js/libraries/bootstrap-tagsinput/bootstrap-tagsinput.js');
```

and in my form:

```php
$text .= $frm->text('my-autocomplete', '', 80, array(
	'id' => 'my-autocomplete',
));

$js = '$("#my-autocomplete").tagsinput({
	typeahead: {
		afterSelect: function(val) {
			this.$element.val("");
		},
		source: function (query, process) {
			return $.post("'.e107::url('qna', 'categories').'", { q: query }, function (data) {
				return data;
			});
		}
	}
});';

e107::js('footer-inline', $js);
```

Demo: http://demo.lonalore.hu/e107v2/qna/categories

**Comment by CaMer0n** [comment]
Thank you! If you can find a typeahead plugin which works for both BS2 and BS3 , it could be added to the core of e107 to replace the existing one.

**Comment by lonalore** [comment]
This plugin works for both BS2 and BS3: https://github.com/bassjobsen/Bootstrap-3-Typeahead

I just put it into an "if" statement because of avoiding multiple includes.

**Comment by lonalore** [comment]
But... I would not bet on it... I try it tomorrow... how can I remove the BS2 typeahead? Which file is it included in? :)

**Comment by CaMer0n** [comment]
I believe it is part of 'jasny'. I would need to check again if we are using other parts of it.

**Comment by CaMer0n** [comment]
To consider? http://brianreavis.github.io/selectize.js/

**Comment by lonalore** [comment]
Wow, nice one! Perfect for me! :D

**Comment by lonalore** [comment]
(approximately) When will this selectize.js be added to the core? :)

**Comment by CaMer0n** [comment]
Please feel free to integrate it, test it and send a pull-request. I don't know when I'll have time to look at it. (low priority as it's not a bug but an enhancement. ).

**Comment by lonalore** [comment]
I left typeahead and I just add selectize.js to the core. I also modified the form handler (text method).

Working example (both BS2 and BS3) is here: 
https://github.com/lonalore/qna/blob/master/categories.php

Live example: http://demo.lonalore.hu/e107v2/qna/categories

**Comment by CaMer0n** [comment]
Thank you! Unable to view your live example. Appears to be a problem loading something from rhcloud.com

**Comment by lonalore** [comment]
Try it again after a minute. :) My test nodejs app goes to idle state if no visitor... :)

**Comment by CaMer0n** [comment]
Looks good!! Would you mind please adding the $frm->userpicker() method to your example?

**Comment by CaMer0n** [comment]
And did you test with e107_admin/cpage.php (modifying the author on a page) ?

**Comment by lonalore** [comment]
Yes, of course! I continue tomorrow. :)

**Comment by CaMer0n** [comment]
Something I forgot to consider: http://vitalets.github.io/x-editable/demo-bs3.html  - we should use the same typeahead script as x-editable.

**Comment by willem010** [comment]
just wondering, looking at this discussion, is the js consolidation working ok now?
cause i feel longer load times coming up  ;)

(but, yeah, this is a nice feature, would come in handy at some of my sites. )

**Comment by lonalore** [comment]
Oke, I modified the userpicker method too, and it works on cpage.php properly. I send you an admin account for my demo site by mail. Feel free to test it.

This "typeahead script as x-editable" is an existing feature in the core? Can I see it in action? Where?

**Comment by lonalore** [comment]
Now you can use plugins for selectize.js like "remove_buttons", "drag_drop" ... etc. :)

**Comment by lonalore** [comment]
Can I make a pull-request?

**Comment by CaMer0n** [comment]
Will it work with x-editable inline editing?

**Comment by lonalore** [comment]
No, because I didn't find this feature in the core. Is it an existing feature? Or, should I implement it?

I tried to add 'inline' => true option for the 'page_author' element in the cpage.php but nothing happened.

**Comment by lonalore** [comment]
Well... x-editable dos not support selectize.js, but select2 is supported.
select2: https://select2.github.io/examples.html

So... we should use select2 insted of selectize.js? :/

**Comment by lonalore** [comment]
Yesterday I started to implement selectize.js into x-editable's popover, and more than half worked. The selectize.js was initialized in the popover successfully, and it saved the new value... 

![](https://www.dropbox.com/s/gndckvu5qok0ylr/selectize_01.png?dl=1)

...but after updating the value, not the username was displayed in the list but user id. 

![](https://www.dropbox.com/s/9yrx90u56fh9dt8/selectize_02.png?dl=1)

So, I have to implement a success callback by x-editable, which insert username into the table instead of user id. If I have time today, I check it.

**Comment by lonalore** [comment]
I integrate userpicker with selectize.js to x-editable popover successfully! :$

@CaMer0n, I sent you an admin account to my demo site, you can test it on cpage.php.

**Comment by CaMer0n** [comment]
@lonalore, excellent work!! Perhaps you could also try loading the selectize.js file in the footer. ie. just add the calls to $frm->text(); instead of the header. This way it should only load the JS when needed.  If you also need inline JS, then you can also add this: 

    e107::js('footer-inline',$jscode); 

I look forward to the pull-request. :+1:

**Comment by CaMer0n** [comment]
@lonalore Found an issue in the "Private Message" popup window in admin area. ("Compose" link). 
http://demo.lonalore.hu/e107v2/e107_plugins/pm/admin_config.php?mode=outbox&action=create&iframe=1

**Comment by lonalore** [comment]
Thank you, I fixed PM issue.

I removed JS and CSS loading from the header, I moved it to the method $frm->text() and it works fine on admin pages, but outside the admin area, the CSS files are not present in the HTML source. I checked the "header_default.php" and I realized that the relevant part of the code is commented out:

```php
/*
$e_js->renderJs('other_css', false, 'css', false);
echo "\n<!-- footer_other_css -->\n";

// Core CSS
$e_js->renderJs('core_css', false, 'css', false);
echo "\n<!-- footer_core_css -->\n";

// Plugin CSS
$e_js->renderJs('plugin_css', false, 'css', false);
echo "\n<!-- footer_plugin_css -->\n";

// Theme CSS
//echo "<!-- Theme css -->\n";
$e_js->renderJs('theme_css', false, 'css', false);
echo "\n<!-- footer_theme_css -->\n";


// Inline CSS - not sure if this should stay at all!
$e_js->renderJs('inline_css', false, 'css', false);
echo "\n<!-- footer_inline_css -->\n";
*/
```

Is there any particular reason for this?

**Comment by lonalore** [comment]
I collected all of my changes into one commit, but I am waiting with pull-request for this "missing $e_js->renderJs()" issue. Can I uncomment the code?

**Comment by CaMer0n** [comment]
CSS has to be loaded in the header. Up until now, we had no way to load an external stylesheet in the body, however, I just found this bit of code which might be worth trying in the body. ie. place something similar to this right before the selector $frm output.. 

    <link type="text/css" rel="stylesheet" property="stylesheet" href="css/homepage.css" />

btw. 
This code loads the CSS in the header: 
    
    $CSSORDER = deftrue('CSSORDER') ? explode(",",CSSORDER) :   array('other','core','plugin','theme','inline');

    foreach($CSSORDER as $val)
    {
	    $cssId = $val."_css";
	    $e_js->renderJs($cssId, false, 'css', false);		
    }

    unset($CSSORDER);

**Comment by lonalore** [comment]
Indeed! :) But it doesn't work, it doesn't load the CSS files into header like on admin pages. Any idea?

**Comment by CaMer0n** [comment]
@lonalore Just added something. Please update and test using e107::css() anywhere AFTER the header is loaded.

**Comment by lonalore** [comment]
It works like a charm, thank you! :)

**Comment by CaMer0n** [comment]
:+1: You're welcome.

**Comment by Moc** [comment]
@lonalore Just wanted to say: great work! Really appreciated.

**Comment by lonalore** [comment]
Thank you! I'm glad I was able to help! :)

**Comment by Moc** [comment]
Is this issue ready to be closed? :)

**Comment by CaMer0n** [comment]
@lonalore In Admin News -> List - with keywords displayed, a huge amount of javascript is generated by these changes. The JS needs to be optimized to use a class selector and then retrieve the ID from the html, rather than a slightly modified copy of the JS for every row.

**Comment by lonalore** [comment]
@CaMer0n yes, it's generates a huge amount of js now. I try to find time on it this week and I rewrite the code.

**Comment by CaMer0n** [comment]
:+1:  Thanks

**Comment by lonalore** [comment]
I removed all JavaScript codes from PHP, and also from HTML output. I tested, it works properly. :)

**Comment by CaMer0n** [comment]
Looks good! Thank you! Please send pull-request. :+1:

**Comment by lonalore** [comment]
Thank you! I created a pull-request. Furthermore, I created an extended javascript documentation in issue #1259

**Comment by CaMer0n** [comment]
Excellent work! Cheers! :+1:
