### ISSUE TITLE
WYSIWYG wont work, always the BBAREA appears

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#992]
WYSIWYG wont work, always the BBAREA appears... but the WYSIWYG is enabled:

![alt text](https://dl.dropboxusercontent.com/u/17751753/github/wysiwyg_02.png "")

But it wont work:
![alt text](https://dl.dropboxusercontent.com/u/17751753/github/wysiwyg_01.png "")

**Comment by CaMer0n** [comment]
Is TinyMce installed? Are you allowed to post HTML (userclass) ?

**Comment by lonalore** [comment]
Mea culpa... :D TinyMce was not installed! Sorry! :)

**Comment by lonalore** [comment]
But, it's quite deceptive. I think the WYSIWYG option in Pref page should be hidden if TinyMce plugin is not installed, because it's unnecessary.
