### ISSUE TITLE
e_SELF and e_QUERY constants are not available if I use SEF URLs

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#996]
e_SELF and e_QUERY constants are not available if I use SEF URLs.

If I use SEF URLs:
http://demo.lonalore.hu/e107v2/qna/ask

...and if I call file directly:
http://demo.lonalore.hu/e107v2/e107_plugins/qna/ask.php

my e_url implementation:
https://github.com/lonalore/qna/blob/master/e_url.php

**Comment by CaMer0n** [comment]
use e_REQUEST_SELF and $_GET

**Comment by lonalore** [comment]
I wanted to use e_SELF for action URL on my form, but finally I used e107::url() instead. I just reported this because I thought it's a bug. Thank You!

**Comment by CaMer0n** [comment]
You can use e_REQUEST_SELF, it should work with SEF enabled and disabled.
